### ISSUE TITLE
[RUMBLE] Playlist downloads fail on /c/ but not on /user/ channels

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#8876] opened 2023-12-29 12:33 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Norway

### Provide a description that is worded well enough to be understood

This issue may be related to https://github.com/yt-dlp/yt-dlp/issues/8782

The issue replicates on two /c/ channels whereas the script behaves normally on a /user/ channel (yt-dlp -S res:480 --dateafter 20221001 --datebefore 20221031 https://rumble.com/user/JeffreyPrather) which plods through all videos and downloads the relevant ones.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-S', 'res:720', '--dateafter', '20221001', '--datebefore', '20221010', 'https://rumble.com/c/RTNews']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-91-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.1.0, websockets-10.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[RumbleChannel] Extracting URL: https://rumble.com/c/RTNews
[download] Downloading playlist: RTNews
[RumbleChannel] RTNews: Downloading page 1
[RumbleChannel] RTNews: Downloading page 2
[RumbleChannel] RTNews: Downloading page 3
[RumbleChannel] RTNews: Downloading page 4
[RumbleChannel] RTNews: Downloading page 5
[RumbleChannel] RTNews: Downloading page 6
[RumbleChannel] RTNews: Downloading page 7
[RumbleChannel] RTNews: Downloading page 8
[RumbleChannel] RTNews: Downloading page 9
[RumbleChannel] RTNews: Downloading page 10
[RumbleChannel] RTNews: Downloading page 11
[RumbleChannel] RTNews: Downloading page 12
[RumbleChannel] RTNews: Downloading page 13
[RumbleChannel] RTNews: Downloading page 14
[RumbleChannel] RTNews: Downloading page 15
[RumbleChannel] RTNews: Downloading page 16
[RumbleChannel] RTNews: Downloading page 17
[RumbleChannel] RTNews: Downloading page 18
[RumbleChannel] RTNews: Downloading page 19
[RumbleChannel] RTNews: Downloading page 20
-
-
-
(lines deleted)
.
.
.
[RumbleChannel] RTNews: Downloading page 630
[RumbleChannel] RTNews: Downloading page 631
[RumbleChannel] RTNews: Downloading page 632
[RumbleChannel] RTNews: Downloading page 633
[RumbleChannel] RTNews: Downloading page 634
[RumbleChannel] RTNews: Downloading page 635
[RumbleChannel] RTNews: Downloading page 636
[RumbleChannel] RTNews: Downloading page 637
[RumbleChannel] RTNews: Downloading page 638
[RumbleChannel] RTNews: Downloading page 639
[RumbleChannel] RTNews: Downloading page 640
[RumbleChannel] RTNews: Downloading page 641
[RumbleChannel] RTNews: Downloading page 642
[RumbleChannel] Playlist RTNews: Downloading 0 items
[download] Finished downloading playlist: RTNews
```

**Comment by bashonly** [comment] 2024-01-28 15:18
Duplicate of #8782

**Closed by bashonly** 2024-01-28 15:18 UTC
Labels: site-bug, triage

**Comment by HalvorRaknes** [comment] 2024-01-28 15:22
@bashonly Why are you closing this issue? It's a major broken site issue!

**Comment by bashonly** [comment] 2024-01-28 15:23
because it's a duplicate!
