### ISSUE TITLE
Vimeo password-protected video results in Unable to download JSON metadata: HTTP Error 400 (apparently max_redirects_exceeded)

### ISSUE THREAD

**Issue by jandr** [yt-dlp/yt-dlp#10127] opened 2024-06-07 06:52 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

(I believe the content can be seen from anywhere, but I tried it from:  )
Spain 

### Provide a description that is worded well enough to be understood

I received 2 links for a course video that is on Vimeo. The first link worked perfectly fine and I could download it using yt-dlp. The second one results in an error stating that it is "Unable to download JSON metadata: HTTP Error 400"

I have updated to the nightly version and I am observing the same behavior. I tried following the instructions in other issues (e.g. such as checking if it has an unlisted hash, but it did not seem to be my case).

- The URL for the video that works is:  https://vimeo.com/user111593501/fdsem9a (https://vimeo.com/946310760 after introducing the password)
- The URL for the video that DOES NOT work is:  https://vimeo.com/user111593501/fdsem9ab (or, after introducing the password, https://vimeo.com/video/946312848)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--video-password', 'PRIVATE', 'https://vimeo.com/user111593501/fdsem9ab']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.01.232725 from yt-dlp/yt-dlp-nightly-builds [db50f19d7] (pip)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.8.12-amd64-x86_64-with-glibc2.38 (OpenSSL 3.2.2 4 Jun 2024, glibc 2.38)
[debug] exe versions: ffmpeg 6.1.1-4 (setts), ffprobe 6.1.1-4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.01.232725 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.01.232725 from yt-dlp/yt-dlp-nightly-builds)
[vimeo] Extracting URL: https://vimeo.com/user111593501/fdsem9ab
[vimeo] 111593501: Downloading webpage
[vimeo] 111593501: Downloading JSON metadata
[vimeo] 111593501: Downloading JSON metadata
ERROR: [vimeo] 111593501: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "/tmp/yt-dlp/venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp/venv/lib/python3.11/site-packages/yt_dlp/extractor/vimeo.py", line 891, in _real_extract
    return self._extract_from_api(video_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp/venv/lib/python3.11/site-packages/yt_dlp/extractor/vimeo.py", line 756, in _extract_from_api
    video = self._download_json(
            ^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp/venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1133, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp/venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1093, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp/venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 954, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp/venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 903, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/tmp/yt-dlp/venv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 890, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp/venv/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4142, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp/venv/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp/venv/lib/python3.11/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp/venv/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/tmp/yt-dlp/venv/lib/python3.11/site-packages/yt_dlp/networking/_requests.py", line 361, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found
```

**Comment by dirkf** [comment] 2024-06-07 10:26
The first private video URL is correctly recognised by the extractor because the page contains a form element with `id` `pw_form`.

The problem private video URL isn't recognised because it doesn't. Instead, the URL redirects to a new JS single-page-application page at the "after introducing" URL, loading JS scripts with the threateningly named path element `vimeo-next`. There is also a JSON key `ablincoln`, maybe a pun for A-B (= Abe) testing.

Enabling JS for vimeo.com and vimeocdn.com yields a page with a password prompt, similar to the old-style password prompt. The JS page dynamically fakes up a password form  with `div`s and a `button`.

Plainly the JS and web traffic will need to analyzed to handle this novel password submission scheme using data from the non-JS page and/or some API URLs.

**Comment by bashonly** [comment] 2024-06-07 14:57
Duplicate of #6603

**Closed by bashonly** 2024-06-07 14:57 UTC
Labels: duplicate, site-bug, site:vimeo
