### ISSUE TITLE
Jable.tv

### ISSUE THREAD

**Issue by D991111** [yt-dlp/yt-dlp#6818] opened 2023-04-15 09:35 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Hongkong

### Provide a description that is worded well enough to be understood

Download from Jable.tv showed HTTPError 403

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Invalid: [etc] https://jable.tv/videos/stars-796/

version: 3.8a (23-01-06 05:25:55 UTC)
platform / locale: Windows-10-10.0.22621-SP0 / zh_tw
order / group / uid: 0 / False / e8ed172d2e734223ad819387e70fb2b3
input: https://jable.tv/videos/stars-796/
type: etc
single: True
url: https://jable.tv/videos/stars-796/
dir: 
zip: 
artist: None
valid / done: False / True
range / range_p: None / None
time: 1681547183.4671173 (23-04-15 08:26:23 UTC) - 3716s elapsed
tags: []
lock: False
color: invalid
paused: False
format: None
p2f: None
segment: None
admin: True
goodbyedpi: False
ytdl: yt_dlp 2023.03.04
pinned: False
extras: {}
live: False
changed: True


[Gallery]
None


[File Names]



[URLs]



[Messages]
extractor: jable
get_video: True, https://jable.tv/videos/stars-796/
[debug] [Jable] Extracting URL: https://jable.tv/videos/stars-796/
[debug] [Jable] stars-796: Downloading webpage
get_video: True, https://jable.tv/videos/stars-796/
[debug] [Jable] Extracting URL: https://jable.tv/videos/stars-796/
[debug] [Jable] stars-796: Downloading webpage
get_video: True, https://jable.tv/videos/stars-796/
[debug] [Jable] Extracting URL: https://jable.tv/videos/stars-796/
[debug] [Jable] stars-796: Downloading webpage
get_video: True, https://jable.tv/videos/stars-796/
[debug] [Jable] Extracting URL: https://jable.tv/videos/stars-796/
[debug] [Jable] stars-796: Downloading webpage
ERROR: [Jable] stars-796: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
get_video: False, https://jable.tv/videos/stars-796/
[debug] [Jable] Extracting URL: https://jable.tv/videos/stars-796/
[debug] [Jable] stars-796: Downloading webpage
get_video: False, https://jable.tv/videos/stars-796/
[debug] [Jable] Extracting URL: https://jable.tv/videos/stars-796/
[debug] [Jable] stars-796: Downloading webpage
get_video: False, https://jable.tv/videos/stars-796/
[debug] [Jable] Extracting URL: https://jable.tv/videos/stars-796/
[debug] [Jable] stars-796: Downloading webpage
get_video: False, https://jable.tv/videos/stars-796/
[debug] [Jable] Extracting URL: https://jable.tv/videos/stars-796/
[debug] [Jable] stars-796: Downloading webpage
ERROR: [Jable] stars-796: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
stop
Traceback (most recent call last):
 File "C:\Users\Shing\AppData\Local\Temp\_MEI154882\ytdl_6e126078\yt_dlp\yt_dlp\extractor\common", line 821, in _request_webpage
   return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
 File "ytdl", line 428, in urlopen
 File "C:\Users\Shing\AppData\Local\Temp\_MEI154882\ytdl_6e126078\yt_dlp\yt_dlp\YoutubeDL", line 3742, in urlopen
   return self._opener.open(req, timeout=self._socket_timeout)
 File "urllib\request", line 531, in open
 File "urllib\request", line 641, in http_response
 File "urllib\request", line 569, in error
 File "urllib\request", line 503, in _call_chain
 File "urllib\request", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Users\Shing\AppData\Local\Temp\_MEI154882\ytdl_6e126078\yt_dlp\yt_dlp\YoutubeDL", line 1518, in wrapper
   return func(self, *args, **kwargs)
 File "C:\Users\Shing\AppData\Local\Temp\_MEI154882\ytdl_6e126078\yt_dlp\yt_dlp\YoutubeDL", line 1594, in __extract_info
   ie_result = ie.extract(url)
 File "C:\Users\Shing\AppData\Local\Temp\_MEI154882\ytdl_6e126078\yt_dlp\yt_dlp\extractor\common", line 694, in extract
   ie_result = self._real_extract(url)
 File "C:\Users\Shing\AppData\Local\Temp\_MEI154882\ytdl_6e126078\yt_dlp\yt_dlp\extractor\jable", line 45, in _real_extract
   webpage = self._download_webpage(url, video_id)
 File "C:\Users\Shing\AppData\Local\Temp\_MEI154882\ytdl_6e126078\yt_dlp\yt_dlp\extractor\common", line 1097, in _download_webpage
   return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
 File "C:\Users\Shing\AppData\Local\Temp\_MEI154882\ytdl_6e126078\yt_dlp\yt_dlp\extractor\common", line 1048, in download_content
   res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
 File "C:\Users\Shing\AppData\Local\Temp\_MEI154882\ytdl_6e126078\yt_dlp\yt_dlp\extractor\common", line 882, in _download_webpage_handle
   urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
 File "C:\Users\Shing\AppData\Local\Temp\_MEI154882\ytdl_6e126078\yt_dlp\yt_dlp\extractor\common", line 839, in _request_webpage
   raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: [Jable] stars-796: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "extractor\etc_downloader", line 63, in get_video
 File "decorator", line 232, in fun
 File "constants", line 909, in wrapper
 File "constants", line 878, in wrapper
 File "extractor\etc_downloader", line 92, in _get_video
 File "extractor\etc_downloader", line 88, in _get_video
 File "ytdl", line 436, in extract_info
 File "C:\Users\Shing\AppData\Local\Temp\_MEI154882\ytdl_6e126078\yt_dlp\yt_dlp\YoutubeDL", line 1507, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\Shing\AppData\Local\Temp\_MEI154882\ytdl_6e126078\yt_dlp\yt_dlp\YoutubeDL", line 1536, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 388, in report_error
yt_dlp.utils.DownloadError: ERROR: [Jable] stars-796: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "utils", line 1260, in start
 File "utils", line 1336, in start_
 File "extractor\etc_downloader", line 27, in read
 File "extractor\etc_downloader", line 75, in get_video
 File "decorator", line 232, in fun
 File "constants", line 909, in wrapper
 File "constants", line 878, in wrapper
 File "extractor\etc_downloader", line 92, in _get_video
 File "extractor\etc_downloader", line 88, in _get_video
 File "ytdl", line 436, in extract_info
 File "C:\Users\Shing\AppData\Local\Temp\_MEI154882\ytdl_6e126078\yt_dlp\yt_dlp\YoutubeDL", line 1507, in extract_info
   return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
 File "C:\Users\Shing\AppData\Local\Temp\_MEI154882\ytdl_6e126078\yt_dlp\yt_dlp\YoutubeDL", line 1536, in wrapper
   self.report_error(str(e), e.format_traceback())
 File "ytdl", line 388, in report_error
yt_dlp.utils.DownloadError: ERROR: [Jable] stars-796: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Invalid: fail=True
EOT: https://jable.tv/videos/stars-796/  (5.7s)
```

**Comment by bashonly** [comment] 2023-04-15 09:40
Duplicate of #6799

**Closed by bashonly** 2023-04-15 09:40 UTC
Labels: site-bug, triage

**Comment by amir32** [comment] 2023-10-01 11:33
Hey there! It seems like you're encountering an HTTP Error 403: Forbidden when trying to download content from jable.tv. This error usually occurs when the server restricts access to the requested resource. To resolve this issue, you can try a few things:

1. **Check Your Permissions:** Ensure that you have the necessary permissions to access the content on jable.tv. Sometimes, certain content may require you to log in or have a specific subscription.

2. **Update yt-dlp:** Make sure you are using the latest version of yt-dlp. You can update it using `yt-dlp -U` to ensure you have the most up-to-date features and bug fixes.

3. **Report the Issue:** If the problem persists, you can report this issue on [yt-dlp's GitHub](https://github.com/yt-dlp/yt-dlp/issues/) by filling out the appropriate issue template. This will help the developers identify and address the problem.

Additionally, if you're a fan of Pokemon, you might want to check out [FusionCalculator.com](https://fusioncalculator.com). It's a fantastic website where you can explore Pokemon fusion possibilities and create your unique fusion Pokemon. It's a fun and creative way to enjoy the world of Pokemon in a whole new light!

I hope this helps you resolve the download issue. If you have any more questions or need further assistance, feel free to ask. Happy downloading, and enjoy your Pokemon adventures on FusionCalculator.com! 😊👾🌟
