### ISSUE TITLE
ERROR: [PornHub] 64449d470be87: Unable to extract encoded url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template.

### ISSUE THREAD

**Issue by redpilleveryday** [yt-dlp/yt-dlp#7029] opened 2023-05-11 01:04 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://pl.pornhub.com/view_video.php?viewkey=64300ed05c441

### Provide a description that is worded well enough to be understood

lisa@ayane:~$ yt-dlp -i -f mp4  https://pl.pornhub.com/view_video.php?viewkey=64449d470be87
[PornHub] Extracting URL: https://pl.pornhub.com/view_video.php?viewkey=64449d470be87
[PornHub] 64449d470be87: Downloading pc webpage
[PornHub] 64449d470be87: Downloading tv webpage
ERROR: [PornHub] 64449d470be87: Unable to extract encoded url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

lisa@ayane:~$ yt-dlp -U
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
lisa@ayane:~$ yt-dlp -vU -i -f mp4  https://pl.pornhub.com/view_video.php?viewkey=64449d470be87
[debug] Command-line config: ['-vU', '-i', '-f', 'mp4', 'https://pl.pornhub.com/view_video.php?viewkey=64449d470be87']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-10-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1k  25 Mar 2021, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.3-0, ffprobe 4.3.3-0, rtmpdump 2.4
[debug] Optional libraries: certifi-2020.06.20, no_Cryptodome-None, pyxattr-0.7.2, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)
[PornHub] Extracting URL: https://pl.pornhub.com/view_video.php?viewkey=64449d470be87
[PornHub] 64449d470be87: Downloading pc webpage
[PornHub] 64449d470be87: Downloading tv webpage
ERROR: [PornHub] 64449d470be87: Unable to extract encoded url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/pornhub.py", line 403, in _real_extract
    js_vars = extract_js_vars(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/pornhub.py", line 340, in extract_js_vars
    assignments = self._search_regex(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1242, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment] 2023-05-11 01:06
This has been fixed in master, see pinned issues

Run `yt-dlp --update-to nightly`

Closing as duplicate of #4299

**Closed by bashonly** 2023-05-11 01:06 UTC
Labels: site-request, triage

**Comment by marek22k** [comment] 2023-06-03 21:20
Maybe a new release should be made so that not so many report the issue anymore (read this for the 2nd time here as I had it myself)?
