### ISSUE TITLE
DisneyNow Error 401: Unauthorized

### ISSUE THREAD

**Issue by DaftMink** [yt-dlp/yt-dlp#2053] opened 2021-12-19 16:45 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

 The extractor for Disney Now is acting up, tried to download the latest episode of T.O.T.S. and got "Unable to download webpage: HTTP Error 401: Unauthorized". Worked December 10th, this week no more. =(

Region: United States 

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://disneynow.com/shows/tots/season-03/episode-13-the-family-treefreddys-neverending-birthday/vdka25640285', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--write-subs']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [Go] Extracting URL: https://disneynow.com/shows/tots/season-03/episode-13-the-family-treefreddys-neverending-birthday/vdka25640285
[Go] vdka25640285: Downloading JSON metadata
[Go] VDKA25640285: Downloading Provider Redirect Page
[Go] VDKA25640285: Logging in
[Go] VDKA25640285: Retrieving Session
ERROR: [Go] vdka25640285: Unable to download webpage: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 715, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3385, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default


C:\YT-DLP>
```

**Comment by pukkandan** [comment] 2021-12-19 17:13
Comcast support is currently broken
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/516

**Closed by pukkandan** 2021-12-19 17:13 UTC
Labels: bug, triage
