### ISSUE TITLE
[FranceTVSite]/[FranceTV] : No video formats found!

### ISSUE THREAD

**Issue by pokemaster974** [yt-dlp/yt-dlp#9332] opened 2024-03-01 13:43 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

URL : https://www.france.tv/france-2/complement-d-enquete/5714862-agriculture-pour-qui-roule-la-fnsea.html

It seems that the plugin doesn't work since today (maybe yesterday).
Regards.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'bv+ba', 'https://www.france.tv/france-2/complement-d-enquete/5714862-agriculture-pour-qui-roule-la-fnsea.html']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip) 
[debug] Python 3.11.7 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 3.0.11 19 Sep 2023) 
[debug] exe versions: ffmpeg 2024-02-15-git-a2cfd6062c-full_build-www.gyan.dev (setts), ffprobe 2024-02-15-git-a2cfd6062c-full_build-www.gyan.dev 
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.43.1, urllib3-2.2.1, websockets-12.0 
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest 
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp        
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp) 
[FranceTVSite] Extracting URL: https://www.france.tv/france-2/complement-d-enquete/5714862-agriculture-pour-qui-roule-la-fnsea.html 
[FranceTVSite] 5714862-agriculture-pour-qui-roule-la-fnsea: Downloading webpage 
[FranceTV] Extracting URL: francetv:552a170c-145e-40e6-963c-10a413108708 
[FranceTV] 552a170c-145e-40e6-963c-10a413108708: Downloading desktop video JSON 
WARNING: [FranceTV] Unable to download JSON metadata: HTTP Error 400: Bad Request 
[FranceTV] 552a170c-145e-40e6-963c-10a413108708: Downloading mobile video JSON 
WARNING: [FranceTV] Unable to download JSON metadata: HTTP Error 400: Bad Request 
[debug] Extractor gave empty title. Creating a generic title 
ERROR: [FranceTV] 552a170c-145e-40e6-963c-10a413108708: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest 
version using  yt-dlp -U 
Traceback (most recent call last): 
  File "C:\Program Files\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1587, in wrapper 
    return func(self, *args, **kwargs) 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Program Files\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1743, in __extract_info 
    return self.process_ie_result(ie_result, download, extra_info) 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Program Files\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1802, in process_ie_result 
    ie_result = self.process_video_result(ie_result, download=download) 
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Program Files\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 2781, in process_video_result 
    self.raise_no_formats(info_dict) 
  File "C:\Program Files\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1085, in raise_no_formats 
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'], 
yt_dlp.utils.ExtractorError: [FranceTV] 552a170c-145e-40e6-963c-10a413108708: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm 
you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment] 2024-03-01 13:45
Duplicate of #9323

**Closed by bashonly** 2024-03-01 13:45 UTC
Labels: site-bug, triage
