### ISSUE TITLE
HTTP Error 403: Forbidden Crunchyroll 2023

### ISSUE THREAD

**Issue by levaculik2** [yt-dlp/yt-dlp#7345] opened 2023-06-18 16:30 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

yesterday I tested the same command and everything was fine, the audios were downloading normally, but today it stopped working.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--match-filters', 'language=pt-BR', '--extractor-args', 'crunchyrollbeta:format=adaptive_dash', '-f', 'ba', '-u', 'PRIVATE', '-p', 'PRIVATE', '--audio-multistreams', '--allow-unplayable-formats', '-a', '/home/levaculik/Documentos/list/crunchyptBR.txt', '--cookies-from-browser', 'chrome', '--no-geo-bypass', '--no-check-certificat', '-o', '%(series)s S0%(season_number)sE0%(episode_number)s - %(episode)s.pt-BR.%(ext)s']
[debug] Batch file urls: ['https://www.crunchyroll.com/watch/G9DUEGQE0/wolf-and-distant-past']
WARNING: You have asked for UNPLAYABLE formats to be listed/downloaded. This is a developer option intended for debugging. 
         If you experience any issues while using this option, DO NOT open a bug report
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-75-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.46.0, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/home/levaculik/.config/google-chrome/Default/Cookies"
[debug] detected desktop environment: XFCE
[debug] Chosen keyring: GNOMEKEYRING
[Cookies] Extracted 3591 cookies from chrome
[debug] cookie version breakdown: {'v10': 0, 'v11': 3567, 'other': 0, 'unencrypted': 24}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/G9DUEGQE0/wolf-and-distant-past
[crunchyroll] Retrieving main page
ERROR: [crunchyroll] G9DUEGQE0: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/crunchyroll.py", line 158, in _real_extract
    api_domain, bucket, params = self._get_params(lang)
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/crunchyroll.py", line 70, in _get_params
    initial_state, app_config = self._get_embedded_json(self._download_webpage(
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1097, in _download_webpage
    return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1048, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 882, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 839, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 821, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3742, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment] 2023-06-18 16:39
I was only able to reproduce this once, and from the second attempt onward I no longer received the 403 response. Try it again? Maybe [installing master branch with pip](https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-master) might help

**Comment by levaculik2** [comment] 2023-06-18 17:12
Hello, I made the changes you said and it works.
thank you very much

**Comment by bashonly** [comment] 2023-06-18 17:31
Closing this since the issue can no longer be reproduced, can reopen if the problem re-emerges

**Closed by bashonly** 2023-06-18 17:31 UTC
Labels: site-bug, triage
