### ISSUE TITLE
Imgur album download broken

### ISSUE THREAD

**Issue by gabrieleancora** [yt-dlp/yt-dlp#5159] opened 2022-10-06 19:07 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Provide a description that is worded well enough to be understood

Hello,
while trying to download this imgur album: https://imgur.com/a/dQIh7nt I keep receiving errors on yt-dlp.

I can  download the album from the browser fine using the imgur function "Download" in the three dots menu. I just did that.
I know that sometimes imgur gives an error "link expired" but I just downloaded it this time and re run `yt-dlp` so it's not that thing blocking the download from the application.

Let me know if you need any more information

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://imgur.com/a/dQIh7nt', '-vU']
[debug] User config "C:\Users\gabri\AppData\Roaming\yt-dlp\config.txt": ['-o', '%(title)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2021-09-30-git-3ee4502753-full_build-www.gyan.dev (setts), ffprobe 2021-09-30-git-3ee4502753-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [imgur:album] Extracting URL: https://imgur.com/a/dQIh7nt
[imgur:album] dQIh7nt: Downloading JSON metadata
ERROR: [imgur:album] dQIh7nt: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\imgur.py", line 128, in _real_extract
  File "yt_dlp\extractor\common.py", line 1032, in download_content
  File "yt_dlp\extractor\common.py", line 996, in download_handle
  File "yt_dlp\extractor\common.py", line 866, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 823, in _request_webpage

  File "yt_dlp\extractor\common.py", line 805, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3682, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by gabrieleancora** [comment] 2022-10-06 19:16
Some other albums that I tried just now:

Album: https://imgur.com/a/N4rc3t2

```shell
[debug] Command-line config: ['https://imgur.com/a/N4rc3t2', '-vU']
[debug] User config "C:\Users\gabri\AppData\Roaming\yt-dlp\config.txt": ['-o', '%(title)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2021-09-30-git-3ee4502753-full_build-www.gyan.dev (setts), ffprobe 2021-09-30-git-3ee4502753-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [imgur:album] Extracting URL: https://imgur.com/a/N4rc3t2
[imgur:album] N4rc3t2: Downloading JSON metadata
ERROR: [imgur:album] N4rc3t2: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\imgur.py", line 128, in _real_extract
  File "yt_dlp\extractor\common.py", line 1032, in download_content
  File "yt_dlp\extractor\common.py", line 996, in download_handle
  File "yt_dlp\extractor\common.py", line 866, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 823, in _request_webpage

  File "yt_dlp\extractor\common.py", line 805, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3682, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Another try:

Album: https://imgur.com/a/pTaoO

```shell
[debug] Command-line config: ['https://imgur.com/a/pTaoO', '-vU']
[debug] User config "C:\Users\gabri\AppData\Roaming\yt-dlp\config.txt": ['-o', '%(title)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2021-09-30-git-3ee4502753-full_build-www.gyan.dev (setts), ffprobe 2021-09-30-git-3ee4502753-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [imgur:album] Extracting URL: https://imgur.com/a/pTaoO
[imgur:album] pTaoO: Downloading JSON metadata
[download] Downloading playlist: Artistic Bathroom
[imgur:album] Playlist Artistic Bathroom: Downloading 2 videos of 2
[download] Downloading video 1 of 2
[debug] [Imgur] Extracting URL: http://imgur.com/MI4G978
[Imgur] MI4G978: Downloading webpage
ERROR: [Imgur] MI4G978: No sources found for video MI4G978. Maybe an image?
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\imgur.py", line 48, in _real_extract

[download] Downloading video 2 of 2
[debug] [Imgur] Extracting URL: http://imgur.com/ptvlx4u
[Imgur] ptvlx4u: Downloading webpage
ERROR: [Imgur] ptvlx4u: No sources found for video ptvlx4u. Maybe an image?
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\imgur.py", line 48, in _real_extract

[download] Finished downloading playlist: Artistic Bathroom
```

Last try

Album: https://imgur.com/a/exAILy5

```shell
[debug] Command-line config: ['https://imgur.com/a/exAILy5', '-vU']
[debug] User config "C:\Users\gabri\AppData\Roaming\yt-dlp\config.txt": ['-o', '%(title)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2021-09-30-git-3ee4502753-full_build-www.gyan.dev (setts), ffprobe 2021-09-30-git-3ee4502753-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [imgur:album] Extracting URL: https://imgur.com/a/exAILy5
[imgur:album] exAILy5: Downloading JSON metadata
ERROR: [imgur:album] exAILy5: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\imgur.py", line 128, in _real_extract
  File "yt_dlp\extractor\common.py", line 1032, in download_content
  File "yt_dlp\extractor\common.py", line 996, in download_handle
  File "yt_dlp\extractor\common.py", line 866, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 823, in _request_webpage

  File "yt_dlp\extractor\common.py", line 805, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3682, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by coletdjnz** [comment] 2022-10-07 06:19
Duplicate of  https://github.com/yt-dlp/yt-dlp/issues/3228

**Closed** 2022-10-07 06:19 UTC
Labels: duplicate, site-bug

**Comment by dirkf** [comment] 2023-10-22 01:30
These albums do not contain video/animated image content:
* https://imgur.com/a/dQIh7nt: only JPEGs
* https://imgur.com/a/N4rc3t2: only JPEGs
* https://imgur.com/a/pTaoO: single JPEG
* https://imgur.com/a/exAILy5: static PNGs

The extractor was not meant to download static images. Had the albums contained video or animated image content, the problem in #3228 would then have applied.
