### ISSUE TITLE
yt-dlp can't log in to learning.oreilly.com

### ISSUE THREAD

**Issue by adbprogrammer** [yt-dlp/yt-dlp#3582] opened 2022-04-28 14:50 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

ERROR: 9780137929511: An extractor error has occurred. (caused by KeyError('next')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Verbose log

```shell
***C:\>yt-dlp -u xxxx -p xxxx -f "bestvideo[ext=mp4][height<=720]+bestaudio[ext=m4a]/best[ext=mp4]/best[ext=mp4][height<=720]" -v -i -c -w -o "E:\Oreilly\%(playlist)s\%(playlist_index)s-%(title)s.%(ext)s" --external-downloader aria2c.exe --all-subs --convert-subs srt --no-check-certificate --restrict-filenames https://learning.oreilly.com/videos/certified-kubernetes-ckad/9780137929511/
[debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-f', 'bestvideo[ext=mp4][height<=720]+bestaudio[ext=m4a]/best[ext=mp4]/best[ext=mp4][height<=720]', '-v', '-i', '-c', '-w', '-o', 'E:\\Oreilly\\%(playlist)s\\%(playlist_index)s-%(title)s.%(ext)s', '--external-downloader', 'aria2c.exe', '--all-subs', '--convert-subs', 'srt', '--no-check-certificate', '--restrict-filenames', 'https://learning.oreilly.com/videos/certified-kubernetes-ckad/9780137929511/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.8.6 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg git-2019-10-13-4f4334b, ffprobe git-2019-10-13-4f4334b
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[safari:course] Downloading login page
ERROR: 9780137929511: An extractor error has occurred. (caused by KeyError('next')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "c:\python38\lib\site-packages\yt_dlp\extractor\common.py", line 639, in extract
    self.initialize()
  File "c:\python38\lib\site-packages\yt_dlp\extractor\common.py", line 544, in initialize
    self._perform_login(username, password)
  File "c:\python38\lib\site-packages\yt_dlp\extractor\safari.py", line 44, in _perform_login
    'https://api.oreilly.com', qs['next'][0])
KeyError: 'next***
```

**Comment by pukkandan** [comment] 2022-04-28 15:02
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3526

**Closed by pukkandan** 2022-04-28 15:02 UTC
Labels: bug, triage
