### ISSUE TITLE
MP4 files are being written with the execute flag (x) enabled

### ISSUE THREAD

**Issue by cereda** [yt-dlp/yt-dlp#3394] opened 2022-04-11 19:49 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hello, friends.

Depending on the video format (it seems to happen at least on `.mp4` files), the output file has now its `x` flag enabled (at least) on Linux. Older versions of `yt-dlp` and/or other formats (like `.webm`) seem to write files with the `-rw-rw-r--.` set (which IMHO is the expected permissions). Tested with at least YouTube and Dailymotion — behaviour was the same permission-wise.

Trying with, e.g,

```sh
$ yt-dlp https://www.youtube.com/watch?v=CQeezCdF4mk
```
we will get

```sh
$ ls -l Sad*
-rw-rw-r--. 1 paulo paulo 86704 jan  7  2020 'Sad Trombone - Gaming Sound Effect (HD) [CQeezCdF4mk].webm'
```

but with

```sh
$ yt-dlp https://www.youtube.com/watch?v=CQeezCdF4mk -f 18
```
we will get

```sh
$ ls -l Sad*
-rwxrwxr-x. 1 paulo paulo 81746 jan  7  2020 'Sad Trombone - Gaming Sound Effect (HD) [CQeezCdF4mk].mp4'
```

Thanks for the project! :wink: 

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-f', '18', 'https://www.youtube.com/watch?v=CQeezCdF4mk']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.16.18-200.fc35.x86_64-x86_64-with-glibc2.34
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=CQeezCdF4mk
[youtube] CQeezCdF4mk: Downloading webpage
[youtube] CQeezCdF4mk: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] CQeezCdF4mk: Downloading 1 format(s): 18
[debug] Invoking downloader on "https://rr2---sn-8p8v-bg06.googlevideo.com/videoplayback?expire=1649727597&ei=DYRUYoeQGJyOobIPv4qd0Aw&ip=177.9.26.86&id=o-AB_zAFPoIhZjNOCtkx38rl873GHftBT7bSwL2V1_sSMn&itag=18&source=youtube&requiressl=yes&mh=Eg&mm=31%2C29&mn=sn-8p8v-bg06%2Csn-bg07dn6l&ms=au%2Crdu&mv=m&mvi=2&pl=24&initcwndbps=730000&vprv=1&mime=video%2Fmp4&gir=yes&clen=81746&ratebypass=yes&dur=5.038&lmt=1578378155603815&mt=1649705579&fvip=1&fexp=24001373%2C24007246&c=ANDROID&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgHvw20eQEz2R2EED4hTp897wzgV55sG_BDZJhlJXgNwwCIG8NQ3bk1EYIhYG6OZNfjPzb6oAPPb2DNy4imChrerhA&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgdAomAJYHwX60WGYpyt-FLoWhw-cblYhglkrvMFjtP8gCIQC0-Xuy3_jvlIIfvEDQe_KWEt_g10meOo9OVMjpwQ7Wzg%3D%3D"
[download] Destination: Sad Trombone - Gaming Sound Effect (HD) [CQeezCdF4mk].mp4
[download] 100% of 79.83KiB in 00:00
$ ls -l Sad\ Trombone\ -\ Gaming\ Sound\ Effect\ \(HD\)\ \[CQeezCdF4mk\].mp4 
-rwxrwxr-x. 1 paulo paulo 80K jan  7  2020 'Sad Trombone - Gaming Sound Effect (HD) [CQeezCdF4mk].mp4'
```

**Comment by pukkandan** [comment] 2022-04-11 19:50
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3371

**Closed by pukkandan** 2022-04-11 19:50 UTC
Labels: bug, triage
