### ISSUE TITLE
yt-dlp doesn't download all of the videos from a playlist.

### ISSUE THREAD

**Issue by noname278** [yt-dlp/yt-dlp#3620] opened 2022-05-02 13:55 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I download a list of videos weekly. This week, 3 out of 8 videos didn't download. I add the videos to a playlist and I download the playlist. I tried copying the videos individually, deleting the .part files and updating with yt-dlp -U. The videos that were downloaded, are already on my flash drive, they are 100% working.

### Verbose log

```shell
I attached 2 verbose logs, I don't know which is the right one, maybe they're the same

WITH --verbose

c:\Usersss\ydl>yt-dlp --verbose https://www.youtube.com/playlist?list=PLxHM38nPHmckbp9J0clz39Q8UGoW1oEIn
[debug] Command-line config: ['--verbose', 'https://www.youtube.com/playlist?list=PLxHM38nPHmckbp9J0clz39Q8UGoW1oEIn']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLxHM38nPHmckbp9J0clz39Q8UGoW1oEIn
[youtube:tab] PLxHM38nPHmckbp9J0clz39Q8UGoW1oEIn: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=PLxHM38nPHmckbp9J0clz39Q8UGoW1oEIn
[youtube:tab] PLxHM38nPHmckbp9J0clz39Q8UGoW1oEIn: Downloading API JSON with unavailable videos
[download] Downloading playlist: download
[youtube:tab] playlist download: Downloading 3 videos
[download] Downloading video 1 of 3
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=GUbN8TdGXL8
[youtube] GUbN8TdGXL8: Downloading webpage
[youtube] GUbN8TdGXL8: Downloading android player API JSON
[debug] Loading youtube-nsig.9cdfefcf from cache
[debug] [youtube] Decrypted nsig XxeFcO46NdAEYHc7OF => yyFexgqv6a1mXQ
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] GUbN8TdGXL8: Downloading 1 format(s): 22
[debug] Invoking downloader on "https://rr2---sn-gqn-vhgs.googlevideo.com/videoplayback?expire=1651520619&ei=CuBvYsb4Oq_Gx_AP4J2B6Ao&ip=2a02%3A2f01%3Aa11b%3A9000%3A292b%3A4d8%3A75e4%3Ada2a&id=o-ACA-n1japnvHPzZe5Jel9NTNRc8zPPOeP8R2b-CQLDPD&itag=22&source=youtube&requiressl=yes&mh=Sh&mm=31%2C29&mn=sn-gqn-vhgs%2Csn-c0q7lns7&ms=au%2Crdu&mv=m&mvi=2&pl=36&initcwndbps=1137500&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=675.654&lmt=1651492096445048&mt=1651498628&fvip=5&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgTEWQRJVL-e_RVEcWYCNEtu1b4mEgPLrXD00QluisotgCIQDZEMRJ81SUxF6znzI2oUSHzIRSU8XVx-vuYMc_SfrrFQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANJ-Gv4OsS8PFDfMAjvMCR7aG07wqKIo3HkPJ42k1MIZAiEA_VJLfy0jZoZO_mh1CaNBZ_XjUKluWz1XEkjx1xktTlY%3D"
[download] Resuming download at byte 270044


ERROR: Did not get any data blocks
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 869, in main
  File "yt_dlp\__init__.py", line 859, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3264, in download
  File "yt_dlp\YoutubeDL.py", line 3237, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1399, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1613, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1812, in __process_playlist
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1834, in __process_iterable_entry
  File "yt_dlp\YoutubeDL.py", line 1567, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1399, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1548, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2648, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3138, in process_info
  File "yt_dlp\YoutubeDL.py", line 2846, in dl
  File "yt_dlp\downloader\common.py", line 457, in download
  File "yt_dlp\downloader\http.py", line 370, in real_download
  File "yt_dlp\downloader\http.py", line 339, in download
  File "yt_dlp\downloader\common.py", line 178, in report_error
  File "yt_dlp\YoutubeDL.py", line 950, in report_error
  File "yt_dlp\YoutubeDL.py", line 884, in trouble


[download] Downloading video 2 of 3
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=gHuTFWDwgbA
[youtube] gHuTFWDwgbA: Downloading webpage
[youtube] gHuTFWDwgbA: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] gHuTFWDwgbA: Downloading 1 format(s): 22
[debug] Invoking downloader on "https://rr1---sn-gqn-vhg6.googlevideo.com/videoplayback?expire=1651520620&ei=DOBvYu2FGoOg8gPryaCIAg&ip=2a02%3A2f01%3Aa11b%3A9000%3A292b%3A4d8%3A75e4%3Ada2a&id=o-AOmpUy9vXZ08r5D-W_RL_46LnC0ZlJxXZifjveGSA-yr&itag=22&source=youtube&requiressl=yes&mh=NJ&mm=31%2C29&mn=sn-gqn-vhg6%2Csn-4g5ednsk&ms=au%2Crdu&mv=m&mvi=1&pl=36&initcwndbps=1058750&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=634.949&lmt=1651455526008769&mt=1651498628&fvip=2&fexp=24001373%2C24007246&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAO10I4q63lBRPyqWmOvj3YAJLle6krY9EK7SdXUSuxFbAiEAqgX96x_rIyDbbZZRc7xfU3YtNOswgg5SAoH67v6rgCU%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIHRPqKNc5aU0gDn14RxsZ5Yr5SXIbqjqoWlpGGAIah2AiEA37SU5rtdi5j-Z0tRm_72rrhZ2uaLvkFo1UZPzXmh2B8%3D"
[download] Resuming download at byte 261420


ERROR: Did not get any data blocks
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 869, in main
  File "yt_dlp\__init__.py", line 859, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3264, in download
  File "yt_dlp\YoutubeDL.py", line 3237, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1399, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1613, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1812, in __process_playlist
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1834, in __process_iterable_entry
  File "yt_dlp\YoutubeDL.py", line 1567, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1399, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1548, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2648, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3138, in process_info
  File "yt_dlp\YoutubeDL.py", line 2846, in dl
  File "yt_dlp\downloader\common.py", line 457, in download
  File "yt_dlp\downloader\http.py", line 370, in real_download
  File "yt_dlp\downloader\http.py", line 339, in download
  File "yt_dlp\downloader\common.py", line 178, in report_error
  File "yt_dlp\YoutubeDL.py", line 950, in report_error
  File "yt_dlp\YoutubeDL.py", line 884, in trouble


[download] Downloading video 3 of 3
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=_1RszUH_4fo
[youtube] _1RszUH_4fo: Downloading webpage
[youtube] _1RszUH_4fo: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] _1RszUH_4fo: Downloading 1 format(s): 22
[debug] Invoking downloader on "https://rr1---sn-gqn-vhg6.googlevideo.com/videoplayback?expire=1651520621&ei=DeBvYtDUItWD6dsP29ub2AE&ip=2a02%3A2f01%3Aa11b%3A9000%3A292b%3A4d8%3A75e4%3Ada2a&id=o-AF2TX9OXjZndQtCKv559o8J6zh1pWkUoH-C8FySJVQG0&itag=22&source=youtube&requiressl=yes&mh=yV&mm=31%2C29&mn=sn-gqn-vhg6%2Csn-4g5e6nzz&ms=au%2Crdu&mv=m&mvi=1&pl=36&initcwndbps=1058750&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1553.205&lmt=1651371008022623&mt=1651498628&fvip=2&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIp5RyUIj118BHdYljbSjs8wGILpjsgCz2g8w7I4X29VAiA2mOj1wFHhLCTtxhCEblrXw2urXbnXol91g7UzQTpKzA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMGjXIkgC-Z2ZXo3ArQ70Cshfl_pPjqjDjC-_VUI8T1nAiA3d1EP4l6fcDrQlnFaYFQKZWAcaQ_OYBsPIj2gxE_0ng%3D%3D"
[download] Resuming download at byte 671187


ERROR: Did not get any data blocks
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 869, in main
  File "yt_dlp\__init__.py", line 859, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3264, in download
  File "yt_dlp\YoutubeDL.py", line 3237, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1399, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1613, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1812, in __process_playlist
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1834, in __process_iterable_entry
  File "yt_dlp\YoutubeDL.py", line 1567, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1399, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1548, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2648, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3138, in process_info
  File "yt_dlp\YoutubeDL.py", line 2846, in dl
  File "yt_dlp\downloader\common.py", line 457, in download
  File "yt_dlp\downloader\http.py", line 370, in real_download
  File "yt_dlp\downloader\http.py", line 339, in download
  File "yt_dlp\downloader\common.py", line 178, in report_error
  File "yt_dlp\YoutubeDL.py", line 950, in report_error
  File "yt_dlp\YoutubeDL.py", line 884, in trouble


[download] Finished downloading playlist: download

WITH -vU

c:\Usersss\ydl>yt-dlp -vU https://www.youtube.com/playlist?list=PLxHM38nPHmckbp9J0clz39Q8UGoW1oEIn
[debug] Command-line config: ['-vU', 'https://www.youtube.com/playlist?list=PLxHM38nPHmckbp9J0clz39Q8UGoW1oEIn']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLxHM38nPHmckbp9J0clz39Q8UGoW1oEIn
[youtube:tab] PLxHM38nPHmckbp9J0clz39Q8UGoW1oEIn: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=PLxHM38nPHmckbp9J0clz39Q8UGoW1oEIn
[youtube:tab] PLxHM38nPHmckbp9J0clz39Q8UGoW1oEIn: Downloading API JSON with unavailable videos
[download] Downloading playlist: download
[youtube:tab] playlist download: Downloading 3 videos
[download] Downloading video 1 of 3
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=GUbN8TdGXL8
[youtube] GUbN8TdGXL8: Downloading webpage
[youtube] GUbN8TdGXL8: Downloading android player API JSON
[debug] Loading youtube-nsig.9cdfefcf from cache
[debug] [youtube] Decrypted nsig S-SFTcU3QpDjHuF2bQ => WDrPgkOxk1C-Ug
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] GUbN8TdGXL8: Downloading 1 format(s): 22
[debug] Invoking downloader on "https://rr2---sn-gqn-vhgs.googlevideo.com/videoplayback?expire=1651520950&ei=VuFvYuiENMvNgQfs8LSQAQ&ip=2a02%3A2f01%3Aa11b%3A9000%3A292b%3A4d8%3A75e4%3Ada2a&id=o-AHzR_HFapewRUyFqgxQ0VRqR6XYACzZc2cEStKPV1LC3&itag=22&source=youtube&requiressl=yes&mh=Sh&mm=31%2C29&mn=sn-gqn-vhgs%2Csn-c0q7lns7&ms=au%2Crdu&mv=m&mvi=2&pl=36&initcwndbps=1105000&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=675.654&lmt=1651492096445048&mt=1651498864&fvip=5&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgCTP-M4Ydl4HPrWohtt3CpSWzpapYsEcL1dbVEaLcaj0CIB3_QFNa5Bk0IBnvyi0pq8jWgqdbmycemt5LWQ79_mt7&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgBb8XRoSXsKJ6utt-jyh1HwD--Y532dMU15kje7WwVycCIQDcs8bHAdKps0_ay6xkKPR-6fjD9J7eWRxz0MrqDPdfGA%3D%3D"
[download] Resuming download at byte 270044


ERROR: Did not get any data blocks
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 869, in main
  File "yt_dlp\__init__.py", line 859, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3264, in download
  File "yt_dlp\YoutubeDL.py", line 3237, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1399, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1613, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1812, in __process_playlist
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1834, in __process_iterable_entry
  File "yt_dlp\YoutubeDL.py", line 1567, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1399, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1548, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2648, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3138, in process_info
  File "yt_dlp\YoutubeDL.py", line 2846, in dl
  File "yt_dlp\downloader\common.py", line 457, in download
  File "yt_dlp\downloader\http.py", line 370, in real_download
  File "yt_dlp\downloader\http.py", line 339, in download
  File "yt_dlp\downloader\common.py", line 178, in report_error
  File "yt_dlp\YoutubeDL.py", line 950, in report_error
  File "yt_dlp\YoutubeDL.py", line 884, in trouble


[download] Downloading video 2 of 3
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=gHuTFWDwgbA
[youtube] gHuTFWDwgbA: Downloading webpage
[youtube] gHuTFWDwgbA: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] gHuTFWDwgbA: Downloading 1 format(s): 22
[debug] Invoking downloader on "https://rr1---sn-gqn-vhg6.googlevideo.com/videoplayback?expire=1651520952&ei=WOFvYofkFePCx_APzuW3qAo&ip=2a02%3A2f01%3Aa11b%3A9000%3A292b%3A4d8%3A75e4%3Ada2a&id=o-AL4n1xkFXK7aO5CTBB7eOhJiHLo5dm4fpOcmeBt2I2oB&itag=22&source=youtube&requiressl=yes&mh=NJ&mm=31%2C29&mn=sn-gqn-vhg6%2Csn-4g5ednsk&ms=au%2Crdu&mv=m&mvi=1&pl=36&initcwndbps=1121250&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=634.949&lmt=1651455526008769&mt=1651498864&fvip=2&fexp=24001373%2C24007246&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgGFkxG1TNqPcha8gR61LP2yT1XwHcFzVkD0uXUnn4ZDcCIEX760ZhI3fwpSlE1SfXfvCMamJIA0ge07a-bSh01ynZ&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALHO6k6WFtDVQuWJxfz8SPGLLLC4a354CAODDPYCCF4fAiAKl5GwUpxD0zHUhXKHdVDMwDR7rZ4M_Hpz9FZCzMwXYA%3D%3D"
[download] Resuming download at byte 261420


ERROR: Did not get any data blocks
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 869, in main
  File "yt_dlp\__init__.py", line 859, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3264, in download
  File "yt_dlp\YoutubeDL.py", line 3237, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1399, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1613, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1812, in __process_playlist
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1834, in __process_iterable_entry
  File "yt_dlp\YoutubeDL.py", line 1567, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1399, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1548, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2648, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3138, in process_info
  File "yt_dlp\YoutubeDL.py", line 2846, in dl
  File "yt_dlp\downloader\common.py", line 457, in download
  File "yt_dlp\downloader\http.py", line 370, in real_download
  File "yt_dlp\downloader\http.py", line 339, in download
  File "yt_dlp\downloader\common.py", line 178, in report_error
  File "yt_dlp\YoutubeDL.py", line 950, in report_error
  File "yt_dlp\YoutubeDL.py", line 884, in trouble


[download] Downloading video 3 of 3
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=_1RszUH_4fo
[youtube] _1RszUH_4fo: Downloading webpage
[youtube] _1RszUH_4fo: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] _1RszUH_4fo: Downloading 1 format(s): 22
[debug] Invoking downloader on "https://rr1---sn-gqn-vhg6.googlevideo.com/videoplayback?expire=1651520953&ei=WeFvYoeFNKSox_APmfu5UA&ip=2a02%3A2f01%3Aa11b%3A9000%3A292b%3A4d8%3A75e4%3Ada2a&id=o-AMWXDoNSvBDyf4Su_cdrXRggtrBTxbVhaItdw8VrsKhA&itag=22&source=youtube&requiressl=yes&mh=yV&mm=31%2C29&mn=sn-gqn-vhg6%2Csn-4g5ednz7&ms=au%2Crdu&mv=m&mvi=1&pl=36&initcwndbps=1121250&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1553.205&lmt=1651371008022623&mt=1651498864&fvip=5&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgXubAA4_LSw8bRz5s82NkdBIB8Jo2qhikrWJ7M_RKB3sCIHLTudfHd7ooRjhypRM9y3uCyhPRGP03y_jqC7D254-k&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgNtQOYudfzbyQYTosv9BE_tP8D64cpmaVBQBDjUcFircCIFu3rbwWNNy4NthTrrjJxyY8ZlTGBQrlpQVZl-pWp6E_"
[download] Resuming download at byte 671187


ERROR: Did not get any data blocks
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 869, in main
  File "yt_dlp\__init__.py", line 859, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3264, in download
  File "yt_dlp\YoutubeDL.py", line 3237, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1399, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1613, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1812, in __process_playlist
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1834, in __process_iterable_entry
  File "yt_dlp\YoutubeDL.py", line 1567, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1399, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1492, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1548, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2648, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3138, in process_info
  File "yt_dlp\YoutubeDL.py", line 2846, in dl
  File "yt_dlp\downloader\common.py", line 457, in download
  File "yt_dlp\downloader\http.py", line 370, in real_download
  File "yt_dlp\downloader\http.py", line 339, in download
  File "yt_dlp\downloader\common.py", line 178, in report_error
  File "yt_dlp\YoutubeDL.py", line 950, in report_error
  File "yt_dlp\YoutubeDL.py", line 884, in trouble


[download] Finished downloading playlist: download
```

**Comment by pukkandan** [comment] 2022-05-02 15:08
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3372

format 22 is currently broken for many videos. Get ffmpeg and download a different format. You could download `-f18` without ffmpeg, but that's only 360p

**Closed by pukkandan** 2022-05-02 15:08 UTC
Labels: bug, triage

**Comment by noname278** [comment] 2022-05-02 16:28
Can you please send a good link to ffmpeg?

**Comment by pukkandan** [comment] 2022-05-02 17:13
https://github.com/yt-dlp/FFmpeg-Builds#downloads

**Comment by noname278** [comment] 2022-05-04 06:58
How can I use ffmpeg? I want to download videos in 720p 25 or 30 fps, like in the past

**Comment by pukkandan** [comment] 2022-05-04 13:22
Just put ffmpeg in the same folder as yt-dlp, then use yt-dlp like normal

**Comment by noname278** [comment] 2022-05-04 13:25
The bin folder?

**Comment by pukkandan** [comment] 2022-05-04 13:40
> The bin folder?

idk where u have put your yt-dlp executable


> Also, can I check in yt-dlp if ffmpeg works? If yes, how?

check the output of `yt-dlp -v`. In your above log, it says `[debug] exe versions: none`. Instead it should say `[debug] exe versions: ffmpeg ...`

**Comment by noname278** [comment] 2022-05-04 14:15
Like this? [debug] Command-line config: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

**Comment by noname278** [comment] 2022-05-04 14:19
[debug] Command-line config: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106796-ge561d16d49-20220503 (setts), ffprobe N-106796-ge561d16d49-20220503
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

**Comment by pukkandan** [comment] 2022-05-04 14:24
> [debug] exe versions: ffmpeg N-106796-ge561d16d49-20220503 (setts), ffprobe N-106796-ge561d16d49-20220503

yup, ffmpeg is present now

**Comment by noname278** [comment] 2022-05-04 14:47
Thank you!
