### ISSUE TITLE
Udemy doesn't work?

### ISSUE THREAD

**Issue by bryn1u** [yt-dlp/yt-dlp#5384] opened 2022-10-28 22:24 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Im trying to download some movie from Udemy but it doesn't work. I get 403 but i was trying to use credential which i used to  in yt-dlp and works well. 
And yes, i have the latest version:
❯ yt-dlp -U                                                                                                                                                      ─╯
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-o', '%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s', 'https://www.udemy.com/course/azure-kubernetes-service-with-azure-devops-and-terraform', '--verbose', '-U']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.10.8 (CPython 64bit) - macOS-13.0-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[udemy:course] Downloading login popup
ERROR: [udemy:course] course: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    self.initialize()
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 576, in initialize
    self._perform_login(username, password)
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/udemy.py", line 165, in _perform_login
    login_popup = self._download_webpage(
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1081, in _download_webpage
    return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1032, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/udemy.py", line 127, in _download_webpage_handle
    ret = super(UdemyIE, self)._download_webpage_handle(
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 866, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 823, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 805, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3682, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment] 2022-10-28 22:45
it's a known issue (see pinned thread), closing as duplicate of #1164

**Closed by bashonly** 2022-10-28 22:45 UTC
Labels: question
