### ISSUE TITLE
Adding an option to keep .vtt when with `--convert-subs` to .srt for most video players as a fallback subtitle

### ISSUE THREAD

**Issue by NewUserHa** [yt-dlp/yt-dlp#6330] opened 2023-02-23 10:52 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Adding an option to keep .vtt when with convert-subs to .srt for most video players as a fallback subtitle will be helpful.

Currently, it seems only `-k`, but since mostly youtube will be downloaded as video+audio so it will mostly also keep the intermediate video and audio.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment] 2023-03-06 15:56
Closig as duplicate of https://github.com/yt-dlp/yt-dlp/issues/6451 since that is a better report

**Closed by pukkandan** 2023-03-06 15:56 UTC
Labels: enhancement, triage
