### ISSUE TITLE
--download-sections only downloads audio from YouTube

### ISSUE THREAD

**Issue by vedantroy** [yt-dlp/yt-dlp#9552] opened 2024-03-28 19:53 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

America

### Provide a description that is worded well enough to be understood

--download-sections results in audio only download (black screen). Possible extra useful information:

```
ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/6.1.1_6 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopenvino --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

Audio file in question: 
[Rick Astley - Never Gonna Give You Up (Official Music Video) [dQw4w9WgXcQ].webm](https://github.com/yt-dlp/yt-dlp/assets/8407819/7115ab92-af40-4354-a568-3e5d61c7d95b)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
https://paste.gg/p/anonymous/83d41a97053e4b28992543352da3dda9 (too long for GH)
```

**Comment by bashonly** [comment] 2024-03-29 01:40
Looks like a duplicate of #7824, which was hidden/removed by github (how helpful), so I guess that means it's a duplicate of #8066

It's an ffmpeg bug with youtube's m3u8 formats

As a workaround, try passing `-S proto:https` or `--extractor-args "youtube:player_client=web"`

In the original (now unavailable) issue, someone said that https://github.com/FFmpeg/FFmpeg/commit/f225f8d7464569c7b917015c26ad30a37a5fbbe2 was the patch that would fix this, but it apparently did not. I'm not sure if this has been reported on ffmpeg's bug tracker

**Closed by bashonly** 2024-03-29 01:40 UTC
Labels: site-bug, triage

**Comment by HybridZach** [comment] 2024-07-05 13:07
> Looks like a duplicate of #7824, which was hidden/removed by github (how helpful), so I guess that means it's a duplicate of #8066
> 
> It's an ffmpeg bug with youtube's m3u8 formats
> 
> As a workaround, try passing `-S proto:https` or `--extractor-args "youtube:player_client=web"`
> 
> In the original (now unavailable) issue, someone said that [FFmpeg/FFmpeg@f225f8d](https://github.com/FFmpeg/FFmpeg/commit/f225f8d7464569c7b917015c26ad30a37a5fbbe2) was the patch that would fix this, but it apparently did not. I'm not sure if this has been reported on ffmpeg's bug tracker

Same issue here today. 
ffmpeg version n6.0
master build yt-dlp

Workaround requires both `proto:https` & `--extractor-args "youtube:player_client=ios"`

`--extractor-args "youtube:player_client=web"` doesn't work.

**Comment by bashonly** [comment] 2024-08-28 22:46
`--extractor-arg "youtube:player_client=default,-ios"` and/or `-S proto:https`

**Comment by dirkf** [comment] 2024-08-30 02:50
As issue 7824 is linked in #3766, is it possible to resuscitate the issue via a GH support issue, or by pulling it from some external archive or scraper site? I believe that GH is prone to report 404 instead of 403 even if the resource exists but is being denied for some reason, so maybe the issue's permissions were broken. Otherwise maybe change that link to https://github.com/yt-dlp/yt-dlp/issues/9552#issuecomment-2026450865?
