### ISSUE TITLE
How do I download highest bitrate video+audio merged?

### ISSUE THREAD

**Issue by goodstuff626** [yt-dlp/yt-dlp#6617] opened 2023-03-24 00:00 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

The command "compat-options format-sort" isn't working any more for me. Is there another command I can use to get highest bitrate video+audio merged like original youtube-dl? 

(I also tried "--compat-options multistreams" "-f bestvideo+bestaudio" but it always just downloads the same as the default yt-dlp, which is lower quality than original youtube-dl.)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment] 2023-03-24 02:20
Do you have ffmpeg installed? Show a verbose log:
> Run your yt-dlp command with -vU flag added (yt-dlp -vU <your command line>)
> Copy the WHOLE output (starting with [debug] Command-line config) and insert it below

**Comment by dirkf** [comment] 2023-03-25 23:39
Or just list the formats and ask for the ones you want ...

**Comment by goodstuff626** [comment] 2023-03-26 03:40
> There is currently a [known issue](https://github.com/yt-dlp/yt-dlp/issues/6561) with `--compat-options format-sort`
> 
> Try `-S tbr` instead
> 
> Also, do you have ffmpeg installed? If you're still having trouble, show a verbose log:
> 
> > Run your yt-dlp command with -vU flag added (yt-dlp -vU )
> > Copy the WHOLE output (starting with [debug] Command-line config) and insert it below



> Or just list the formats and ask for the ones you want ...

Is there a way to use tartube or yt-dlg gui to view formats before downloading? Or do I have to use command line to view formats before downloading?

**Comment by pukkandan** [comment] 2023-03-27 11:24
> Is there a way to use tartube or yt-dlg gui to view formats before downloading?

You'd have to ask elsewhere.

As for your original issue, possibly duplicate of https://github.com/yt-dlp/yt-dlp/issues/6561, closing due to lack of verbose log

**Closed by pukkandan** 2023-03-27 11:24 UTC
Labels: question
