### ISSUE TITLE
SBS ondemand/link.theplatform.com, unable to fetch, previously worked, No video formats found

### ISSUE THREAD

**Issue by XtremeBear** [yt-dlp/yt-dlp#6657] opened 2023-03-28 02:22 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

Unable to fetch video from SBS ondemand/ThePlatform
Failed to download m3u8 information: HTTP Error 403: Forbidden
No video formats found

was working 5 days ago...
Both links result in same error:-
https://www.sbs.com.au/ondemand/tv-series/dinosaur-with-stephen-fry/season-1/dinosaur-with-stephen-fry-s1-ep1/2175290435912
https://www.sbs.com.au/ondemand/watch/2175290435912

yt-dlp-2023.03.27.161807

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.sbs.com.au/ondemand/tv-series/dinosaur-with-stephen-fry/season-1/dinosaur-with-stephen-fry-s1-ep1/2175290435912']
[debug] System config "/etc/yt-dlp.conf": ['--console-title', '--restrict-filenames', '--retries', 'infinite', '--fragment-retries', 'infinite', '--add-metadata', '--embed-metadata', '--ffmpeg-location', '/opt/ffmpeg/ffmpeg', '-o', '~/Downloads/Video/%(title)s.%(ext)s', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36']
[debug] Encodings: locale ISO-8859-1, fs iso8859-1, pref ISO-8859-1, out ISO-8859-1, error ISO-8859-1, screen ISO-8859-1
[debug] yt-dlp version nightly@2023.03.27.161807 [0f0875ed5] (zip)
[debug] Python 3.7.3 (CPython x86_64 64bit) - Linux-4.4.268_XST-x86_64-Intel-R-_Core-TM-_i5-3570K_CPU_@_3.40GHz-with-slackware-14.2 (OpenSSL 1.0.2u  20 Dec 2019, glibc 2.2.5)
[debug] exe versions: ffmpeg 5.1.1-static (setts), ffprobe 5.1.1-static, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1793 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.03.27.161807, Current version: nightly@2023.03.27.161807
Current Build Hash: 6858ba59400c032db443f17fbd9a226fa638e654a4b8593e64556cdf700f1643
yt-dlp is up to date (nightly@2023.03.27.161807)
[SBS] Extracting URL: https://www.sbs.com.au/ondemand/tv-series/dinosaur-with-stephen-fry/season-1/dinosaur-with-stephen-fry-s1-ep1/2175290435912
[SBS] 2175290435912: Downloading JSON metadata
[ThePlatform] Extracting URL: http://link.theplatform.com/s/Bgtm9B/vXTWzSlvr0tW?feed=Video%20-%20Single&mbr=true&manifest=m3u&ord=1553306&policy=11929623&dfptag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.factual.sbs.com.au%2Fsec30htmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast2%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dpreroll%26ad_rule%3D0%26cmsid%3D531%26nofb%3D1%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F2175290435912%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D2175290435912&dfpmidtag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.factual.sbs.com.au%2Fsec30midrollhtmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast2%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dmidroll%26ad_rule%3D0%26cmsid%3D531%26nofb%3D1%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F2175290435912%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D2175290435912#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] vXTWzSlvr0tW: Downloading SMIL data
[ThePlatform] vXTWzSlvr0tW: Downloading m3u8 information
WARNING: [ThePlatform] Failed to download m3u8 information: HTTP Error 403: Forbidden
[ThePlatform] vXTWzSlvr0tW: Downloading JSON metadata
ERROR: [ThePlatform] vXTWzSlvr0tW: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1728, in process_ie_result
    new_result, download=download, extra_info=extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2615, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1047, in raise_no_formats
    expected=has_drm or ignored or expected)
yt_dlp.utils.ExtractorError: [ThePlatform] vXTWzSlvr0tW: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment] 2023-03-28 02:47
Duplicate of #6543

**Closed by bashonly** 2023-03-28 02:47 UTC
Labels: site-bug, triage
