### ISSUE TITLE
[Facebook]  Cannot parse data

### ISSUE THREAD

**Issue by kr-v** [yt-dlp/yt-dlp#4744] opened 2022-08-23 10:58 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Facing this issue facebook.

Video URL : https://www.facebook.com/Teamblackfilms/videos/442779127561375/
Video is playable in incognito as well.
<img width="1728" alt="Screenshot 2022-08-23 at 4 26 34 PM" src="https://user-images.githubusercontent.com/79656118/186141204-c7e6a78c-f53f-4911-8392-30262fcbe695.png">

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--verbose', '--cookies-from-browser', 'chrome', 'https://www.facebook.com/Teamblackfilms/videos/442779127561375/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e088] (zip)
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.12 (CPython 64bit) - macOS-12.5.1-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, certifi-2021.10.08, sqlite3-2.6.0
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/krv/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
[Cookies] Extracted 4160 cookies from chrome
[debug] cookie version breakdown: {'v10': 4113, 'other': 0, 'unencrypted': 47}
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/Teamblackfilms/videos/442779127561375/
[facebook] 442779127561375: Downloading webpage
[facebook] 442779127561375: Downloading webpage
ERROR: [facebook] 442779127561375: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/facebook.py", line 705, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/facebook.py", line 651, in _extract_from_url
    raise ExtractorError('Cannot parse data')
```

**Comment by pukkandan** [comment] 2022-08-23 17:55
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/4311

**Closed by pukkandan** 2022-08-23 17:55 UTC
Labels: duplicate, site-bug, site:facebook
