### ISSUE TITLE
[Broken] Downloads are not archived when used --download-archive

### ISSUE THREAD

**Issue by Filippilny** [yt-dlp/yt-dlp#945] opened 2021-09-11 00:27 UTC
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
filip@Filip-Mac-mini Test % yt-dlp -o '%(playlist_title)s/%(title)s.%(ext)s' "https://youtu.be/wlRfHlMhMRU" --ignore-errors --all-subs --embed-subs  --embed-thumbnail  --download-archive archive.log --verbose

[debug] Command-line config: ['-o', '%(playlist_title)s/%(title)s.%(ext)s', 'https://youtu.be/wlRfHlMhMRU', '--ignore-errors', '--all-subs', '--embed-subs', '--embed-thumbnail', '--download-archive', 'archive.log', '--verbose']
[debug] Loading archive file 'archive.log'

[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 (zip)
[debug] Python version 3.9.4 (CPython 64bit) - macOS-11.5.2-arm64-arm-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://youtu.be/wlRfHlMhMRU
[youtube] wlRfHlMhMRU: Downloading webpage
[youtube] wlRfHlMhMRU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Testing thumbnail 41
[debug] Downloading subtitles: en
[debug] Default format spec: bestvideo*+bestaudio/best
[info] wlRfHlMhMRU: Downloading 1 format(s): 315+251
[info] Writing video subtitles to: NA/Why The Apple Pencil Is So Expensive.en.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=wlRfHlMhMRU&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xftt%2Cxctw&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1631344955&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxoaf&signature=BC4ABD03F7E04FB99DF71158066BE8C2EB8FEA85.C1CA60F43C53B28A58023EF4BF91AA897AAB1FF8&key=yt8&lang=en&fmt=vtt"
[download] Destination: NA/Why The Apple Pencil Is So Expensive.en.vtt
[download] 100% of 3.67KiB in 00:00
[debug] Testing thumbnail 39
[debug] Testing thumbnail 38
[debug] Testing thumbnail 37
[debug] Testing thumbnail 35
[debug] Testing thumbnail 34
[debug] Testing thumbnail 33
[debug] Testing thumbnail 32
[debug] Testing thumbnail 31
[debug] Testing thumbnail 30
[youtube] wlRfHlMhMRU: Downloading thumbnail  ...
[youtube] wlRfHlMhMRU: Writing thumbnail to: NA/Why The Apple Pencil Is So Expensive.webp
[download] NA/Why The Apple Pencil Is So Expensive.webm has already been downloaded
[EmbedSubtitle] Embedding subtitles in "NA/Why The Apple Pencil Is So Expensive.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:NA/Why The Apple Pencil Is So Expensive.webm' -i 'file:NA/Why The Apple Pencil Is So Expensive.en.vtt' -c copy -map 0 -dn -map -0:s -map -0:d -map 1:0 -metadata:s:s:0 language=eng -metadata:s:s:0 handler_name=English -metadata:s:s:0 title=English 'file:NA/Why The Apple Pencil Is So Expensive.temp.webm'
Deleting original file NA/Why The Apple Pencil Is So Expensive.en.vtt (pass -k to keep)
[ThumbnailsConvertor] Converting thumbnail "NA/Why The Apple Pencil Is So Expensive.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:NA/Why The Apple Pencil Is So Expensive.webp' 'file:NA/Why The Apple Pencil Is So Expensive.png'
ERROR: Postprocessing: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2864, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3015, in post_process
    info = self.run_pp(pp, info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2964, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 83, in wrapper
    return func(self, info)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/embedthumbnail.py", line 222, in run
    raise EmbedThumbnailPPError('Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov')
yt_dlp.postprocessor.embedthumbnail.EmbedThumbnailPPError: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov

```
## Description

Hey,

it seems like yt-dlp doesn't record the downloads in the archive. If I however enter the record manually into the archive, it honors it then and skips the video.

**Comment by pukkandan** [comment] 2021-09-11 00:29
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/893

**Closed by pukkandan** 2021-09-11 00:29 UTC
