### ISSUE TITLE
let -F output indicate which audio/video would be chosen

### ISSUE THREAD

**Issue by calestyo** [yt-dlp/yt-dlp#4610] opened 2022-08-09 23:17 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hey.

I think it would be nice if the `-F` option could somehow highlight which video and audio format would be actually taken with the current settings.
The benefit would be, that one sees much easier whether really the "best" formats are selected.

Could be as simple as printing the lines in italics or changing the background colour of the repective lines.

Thanks,
Chris.

**Comment by calestyo** [comment] 2022-08-09 23:19
Or maybe even easier by using a different foreground colour of just the respective ID lines... e.g. a light green.

**Comment by gamer191** [comment] 2022-08-10 00:02
It will always be the format at the bottom of that list, and if that format is video-only, then the audio-only format closest to the bottom will also be downloaded

so in this example:
```
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb1 mhtml 80x45        0    │                  mhtml │ images                                  storyboard
sb0 mhtml 160x90       0    │                  mhtml │ images                                  storyboard
599 m4a   audio only      2 │    5.00MiB   31k https │ audio only          mp4a.40.5   31k 22k ultralow, m4a_dash
600 webm  audio only      2 │    5.59MiB   34k https │ audio only          opus        34k 48k ultralow, webm_dash
139 m4a   audio only      2 │    7.92MiB   49k https │ audio only          mp4a.40.5   49k 22k low, m4a_dash
249 webm  audio only      2 │    8.20MiB   51k https │ audio only          opus        51k 48k low, webm_dash
250 webm  audio only      2 │   10.78MiB   66k https │ audio only          opus        66k 48k low, webm_dash
140 m4a   audio only      2 │   21.01MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, m4a_dash
251 webm  audio only      2 │   20.61MiB  127k https │ audio only          opus       127k 48k medium, webm_dash
17  3gp   176x144      7  1 │   12.78MiB   79k https │ mp4v.20.3       79k mp4a.40.2    0k 22k 144p
597 mp4   256x144     15    │    5.23MiB   32k https │ avc1.4d400b     32k video only          144p, mp4_dash
598 webm  256x144     15    │    4.98MiB   31k https │ vp9             31k video only          144p, webm_dash
394 mp4   256x144     30    │   11.70MiB   72k https │ av01.0.00M.08   72k video only          144p, mp4_dash
160 mp4   256x144     30    │   14.88MiB   92k https │ avc1.4d400c     92k video only          144p, mp4_dash
278 webm  256x144     30    │   15.01MiB   93k https │ vp9             93k video only          144p, webm_dash
395 mp4   426x240     30    │   24.73MiB  152k https │ av01.0.00M.08  152k video only          240p, mp4_dash
133 mp4   426x240     30    │   32.52MiB  200k https │ avc1.4d4015    200k video only          240p, mp4_dash
242 webm  426x240     30    │   32.43MiB  200k https │ vp9            200k video only          240p, webm_dash
396 mp4   640x360     30    │   51.94MiB  320k https │ av01.0.01M.08  320k video only          360p, mp4_dash
134 mp4   640x360     30    │   66.97MiB  413k https │ avc1.4d401e    413k video only          360p, mp4_dash
243 webm  640x360     30    │   58.52MiB  361k https │ vp9            361k video only          360p, webm_dash
18  mp4   640x360     30  2 │  113.60MiB  700k https │ avc1.42001E    700k mp4a.40.2    0k 44k 360p
397 mp4   854x480     30    │   93.46MiB  576k https │ av01.0.04M.08  576k video only          480p, mp4_dash
135 mp4   854x480     30    │  105.26MiB  649k https │ avc1.4d401f    649k video only          480p, mp4_dash
244 webm  854x480     30    │   98.15MiB  605k https │ vp9            605k video only          480p, webm_dash
136 mp4   1280x720    30    │  351.00MiB 2163k https │ avc1.4d401f   2163k video only          720p, mp4_dash
247 webm  1280x720    30    │  222.67MiB 1372k https │ vp9           1372k video only          720p, webm_dash
22  mp4   1280x720    30  2 │ ~380.86MiB 2292k https │ avc1.64001F   2292k mp4a.40.2    0k 44k 720p
398 mp4   1280x720    60    │  271.92MiB 1676k https │ av01.0.08M.08 1676k video only          720p60, mp4_dash
298 mp4   1280x720    60    │  198.31MiB 1222k https │ avc1.4d4020   1222k video only          720p60, mp4_dash
302 webm  1280x720    60    │  307.45MiB 1895k https │ vp9           1895k video only          720p60, webm_dash
399 mp4   1920x1080   60    │  505.55MiB 3116k https │ av01.0.09M.08 3116k video only          1080p60, mp4_dash
299 mp4   1920x1080   60    │  670.68MiB 4134k https │ avc1.64002a   4134k video only          1080p60, mp4_dash
303 webm  1920x1080   60    │  642.81MiB 3962k https │ vp9           3962k video only          1080p60, webm_dash
```
formats 303 and 251 (not 22, because that format isn't audio-only, even though it contains audio) will be downloaded and merged together

DISCLAIMER: I am not a moderator. I am merely sharing my knowledge. This message should not be taken as a rejection of your feature request

**Comment by calestyo** [comment] 2022-08-10 00:08
Yes, I know it's already sorted,... but when one has long lists one still has to search for the break point between video and audio.

So I really though just about some cosmetic highlighting to find it faster.

**Comment by HobbyistDev** [comment] 2022-08-10 00:45
I think what do you want is https://github.com/yt-dlp/yt-dlp/pull/920#issuecomment-1059914615, right ?

**Comment by pukkandan** [comment] 2022-08-10 01:16
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2493

**Closed by pukkandan** 2022-08-10 01:16 UTC
Labels: enhancement, triage

**Comment by calestyo** [comment] 2022-08-10 01:51
> I think what do you want is [#920 (comment)](https://github.com/yt-dlp/yt-dlp/pull/920#issuecomment-1059914615), right ?

Yes.

Funny enough, I had actually searched for both -F and highlight... and still not spotted the existing issue.

**Comment by pukkandan** [comment] 2022-08-10 03:38
It happens sometimes. No worries
