### ISSUE TITLE
[Site Request] sling-tv MSO

### ISSUE THREAD

**Issue by Sipherdrakon** [yt-dlp/yt-dlp#378] opened 2021-06-05 06:11 UTC
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.06.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.oxygen.com/killer-couples/season-15/episode-7/kyle-navin-and-jennifer-valiente
- Single video: https://www.oxygen.com/accident-suicide-or-murder/season-3/episode-7/a-deadly-dose
- Playlist: https://www.oxygen.com/accident-suicide-or-murder/episode-guide

## Description

I was hoping to add sling-tv to the apo-mso list as it allows for login to a lot of sites that philo won't and I don't think would be as hard as getting youtubeTV to work with login, but I honestly don't know.

**Comment by shirt-dev** [comment] 2021-06-08 01:49
Duplicate of #300. Please do not open multiple issues the same request.

**Closed by shirt-dev** 2021-06-08 01:49 UTC
Labels: duplicate

**Comment by Sipherdrakon** [comment] 2021-06-08 03:44
My bad, I only saw the feature request closed and didn't realize I already made a site request for it. :-(
