### ISSUE TITLE
ERROR: [facebook]

### ISSUE THREAD

**Issue by Unknow995-sys** [yt-dlp/yt-dlp#8494] opened 2023-11-02 08:47 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Colombia

### Provide a description that is worded well enough to be understood

ERROR: [facebook] 244517038617364: Unable to download webpage: HTTP Error 302: Found (redirect loop detected) (caused by <HTTPError 302: Found>);

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ERROR: [facebook] 244517038617364: Unable to download webpage: HTTP Error 302: Found (redirect loop detected) (caused by <HTTPError 302: Found>);
```

**Comment by barsnick** [comment] 2023-11-02 09:27
Please stick to the instructions. You input so far is not usable for reproducing your issue.

* Run your yt-dlp command with `-vU` flag added (`yt-dlp -vU <your command line>`)
* Copy the **WHOLE** output (starting with `[debug] Command-line config)` and insert it below

**Comment by bashonly** [comment] 2023-11-02 10:53
looks like a duplicate of #8319

**Comment by heyeanne34** [comment] 2023-11-02 11:18
can i ask how to scrape fb posts like in youtube command?
yt-dlp --print-to-file "%(title)s|%(upload_date)s|%(duration_string)s|%(view_count)s|%(comment_count)s|%(availability)s|%(channel)s|%(webpage_url)s|" "list.txt" "https://www.youtube.com/@IndiaNewsITV/videos"  --playlist-reverse --simulate

**Closed** 2023-11-05 09:25 UTC
Labels: incomplete, site:facebook
