### ISSUE TITLE
[TikTok] Support for Photos

### ISSUE THREAD

**Issue by imanoreotwe** [yt-dlp/yt-dlp#9990] opened 2024-05-21 18:31 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Example URLs

https://www.tiktok.com/@chososfavhairtie/photo/7369836402751671585
https://www.tiktok.com/@itsevykins/photo/7367130722806648106
https://www.tiktok.com/t/ZPRK8TCAT/

### Provide a description that is worded well enough to be understood

Photos will either fail to download because there is no extractor or only download the audio.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-o', 'tmp2/%(title)s.%(ext)s', 'https://www.tiktok.com/@chososfavhairtie/photo/7369836402751671585']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 34f60217e
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.9.1-arch1-1-x86_64-with-glibc2.39 (OpenSSL 3.3.0 9 Apr 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: sqlite3-3.45.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1804 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.tiktok.com/@chososfavhairtie/photo/7369836402751671585
[generic] 7369836402751671585: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 7369836402751671585: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.tiktok.com/@chososfavhairtie/photo/7369836402751671585
Traceback (most recent call last):
  File "/home/wtromary/dev/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wtromary/dev/yt-dlp/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/wtromary/dev/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wtromary/dev/yt-dlp/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tiktok.com/@chososfavhairtie/photo/7369836402751671585
```

**Comment by imanoreotwe** [comment] 2024-05-21 18:32
I can work on this one too if you would like to assign me

**Comment by seproDev** [comment] 2024-05-21 18:34
Downloading photos is out-of-scope

Duplicate of #6168, #6217, #8360

Look into [gallery-dl](https://github.com/mikf/gallery-dl)

**Closed by seproDev** 2024-05-21 18:34 UTC
Labels: duplicate, wontfix, site-enhancement, site:tiktok
