### ISSUE TITLE
[youtube] unable to extract initial player response

### ISSUE THREAD

**Issue by rmstock3** [yt-dlp/yt-dlp#7965] opened 2023-08-26 03:20 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Provide a description that is worded well enough to be understood

Although the downloaded video plays perfect , yt-dlp gives
a warning which should be reported.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ubuntu@ubuntu:~$ yt-dlp -vU -f 22 https://www.youtube.com/watch?v=fqV6poHSLV4 
[debug] Command-line config: ['-vU', '-f', '22', 'https://www.youtube.com/watch?v=fqV6poHSLV4']
[debug] User config "/home/ubuntu/.config/yt-dlp/config": ['--hls-prefer-native']
[debug] System config "/etc/yt-dlp.conf": ['--prefer-free-formats']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.8.2 (CPython x86_64 64bit) - Linux-5.4.0-42-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotlicffi-1.0.9.2, certifi-2019.11.28, mutagen-1.44.0, secretstorage-2.3.1, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=fqV6poHSLV4
[youtube] fqV6poHSLV4: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] fqV6poHSLV4: Downloading ios player API JSON
[youtube] fqV6poHSLV4: Downloading android player API JSON
[youtube] fqV6poHSLV4: Downloading iframe API JS
[youtube] fqV6poHSLV4: Downloading player c153b631
[youtube] fqV6poHSLV4: Downloading web player API JSON
[youtube] fqV6poHSLV4: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] fqV6poHSLV4: Downloading initial data API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] fqV6poHSLV4: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr5---sn-32o-guh6.googlevideo.com/videoplayback?expire=1693041361&ei=cW7pZNS-IKmO1PIP2O2O2AE&ip=2a02%3Aa44f%3A6e78%3A1%3Aca0a%3Aa9ff%3Afe65%3A5159&id=o-AI42Hx7eOklbht5BzR6TtjYklskagfmL9RPNo17GxhUW&itag=22&source=youtube&requiressl=yes&mh=IX&mm=31%2C29&mn=sn-32o-guh6%2Csn-5hne6nzk&ms=au%2Crdu&mv=m&mvi=5&pl=40&initcwndbps=2153750&spc=UWF9f7HSl9OH2GgswmnHTOBj3Jp0lTk&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1708.593&lmt=1692986457044385&mt=1693019581&fvip=2&fexp=24007246&beids=24350017&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgKw99LoAuRcIZsylAutfmBStx3Iufh8IFfEks6xOrLToCIFc83WSxKgTZSdQ1Hvj8lsC_RVB1c6zPALGO_RDotoPC&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgAuSpqhUbLv33AUWK1iKgynNpSAc_bmzNjVCeGTIasH0CIQC7_X49psFv4OZfxjRuWmYbckSsx95N2N4WTXzhM77ETA%3D%3D"
[download] Destination: What REALLY Happened to Prigozhin？ ALL YOU SHOULD KNOW [fqV6poHSLV4].mp4
[download] 100% of   97.90MiB in 00:00:06 at 14.47MiB/s
ubuntu@ubuntu:~$
```

**Comment by bashonly** [comment] 2023-08-26 03:22
Duplicate of #7594

**Closed by bashonly** 2023-08-26 03:22 UTC
Labels: site-bug, triage
