### ISSUE TITLE
Sign in to confirm you’re not a bot. This helps protect our community. Learn more

### ISSUE THREAD

**Issue by kaixuangh** [yt-dlp/yt-dlp#10631] opened 2024-08-02 13:39 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp "https://www.youtube.com/shorts/OXQy_S_I42I"
[youtube] Extracting URL: https://www.youtube.com/shorts/OXQy_S_I42I
[youtube] OXQy_S_I42I: Downloading webpage
[youtube] OXQy_S_I42I: Downloading ios player API JSON
[youtube] OXQy_S_I42I: Downloading android player API JSON
ERROR: [youtube] OXQy_S_I42I: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment] 2024-08-02 14:23
Duplicate of #10128

That's not a verbose log, but it looks like you may be on a very old version of yt-dlp

"Sign in to confirm you're not a bot error" is an indicator that youtube has flagged your IP. You won't be able to use yt-dlp with this IP address unless you pass cookies to yt-dlp, and doing that from this IP will likely lead to the account being banned

**Closed by bashonly** 2024-08-02 14:23 UTC
Labels: question
