### ISSUE TITLE
Skyline WebCams support is not working

### ISSUE THREAD

**Issue by hellishvictor** [yt-dlp/yt-dlp#8358] opened 2023-10-15 17:18 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Spain

### Provide a description that is worded well enough to be understood

Hi, on this [list](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md##) is "SkylineWebcams" but when I try use yt-dlp with:

`yt-dlp "https://www.skylinewebcams.com/es/webcam/espana/cataluna/barcelona/playa-barceloneta.html"`

I get:
```
[SkylineWebcams] Extracting URL: https://www.skylinewebcams.com/es/webcam/espana/cataluna/barcelona/
playa-barceloneta.html
[SkylineWebcams] playa-barceloneta: Downloading webpage
ERROR: [SkylineWebcams] playa-barceloneta: Unable to extract stream url; please report this issue on
  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm y
ou are on the latest version using  yt-dlp -U
```
Cheers.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), scr
een utf-8 (No VT)
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_x86_exe)
[debug] Python 3.7.9 (CPython AMD64 32bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sql
ite3-3.31.1, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 886c73031ff13375df029cbd1ddaca7481c7cba9c8e56d85639c5411268805c7
yt-dlp is up to date (stable@2023.10.13)
```

**Comment by gamer191** [comment] 2023-10-15 22:25
In future, please generate the verbose log using `yt-dlp -vU URL`:
```
[debug] Command-line config: ['https://www.skylinewebcams.com/es/webcam/espana/cataluna/barcelona/playa-barceloneta.html', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.11.0 (CPython iPad5,4 64bit) - macOS-14.0.1-iPad5,4-arm-64bit (OpenSSL 1.1.1i  8 Dec 2020)
[debug] exe versions: ffmpeg n5.1.2-11-g30d432f205 (setts), ffprobe n5.1.2-11-g30d432f205, phantomjs broken, rtmpdump broken
[debug] Optional libraries: Cryptodome-3.15.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.32.3, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[SkylineWebcams] Extracting URL: https://www.skylinewebcams.com/es/webcam/espana/cataluna/barcelona/playa-barceloneta.html
[SkylineWebcams] playa-barceloneta: Downloading webpage
ERROR: [SkylineWebcams] playa-barceloneta: Unable to extract stream url; please report this issue on  https://github.com/yt-dlp/
yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/var/mobile/Containers/Data/Application/586E92B4-8585-442B-9F75-7B37A586D864/Library/lib/python3.11/site-packages/yt_dlp
/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mobile/Containers/Data/Application/586E92B4-8585-442B-9F75-7B37A586D864/Library/lib/python3.11/site-packages/yt_dlp
/extractor/skylinewebcams.py", line 25, in _real_extract
    stream_url = self._search_regex(
                 ^^^^^^^^^^^^^^^^^^^
  File "/var/mobile/Containers/Data/Application/586E92B4-8585-442B-9F75-7B37A586D864/Library/lib/python3.11/site-packages/yt_dlp
/extractor/common.py", line 1263, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment] 2023-10-15 23:59
Duplicate of #7115

**Closed by bashonly** 2023-10-15 23:59 UTC
Labels: site-bug, triage
