### ISSUE TITLE
ON:ORF results in FFmpegPostProcessorError

### ISSUE THREAD

**Issue by arminfuerst** [yt-dlp/yt-dlp#10114] opened 2024-06-05 22:03 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Austria

### Provide a description that is worded well enough to be understood

Downloading this video seems to work in the beginning, but after having downloaded M4A and MP4, the postprocessor stops with an error. M4A-file with audio and MP4-file with video only are left from the download.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://on.orf.at/video/14228910/sommer-auf-drei-raedern
[debug] Command-line config: ['-vU', 'https://on.orf.at/video/14228910/sommer-auf-drei-raedern']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.06.01.185743 from yt-dlp/yt-dlp-master-builds [db50f19d7] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-21-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 6.0.1 (fdk,setts), ffprobe 6.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, requests-2.28.1, secretstorage-3.3.3, sqlite3-3.40.1, urllib3-1.26.12, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.06.01.185743 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.06.01.185743 from yt-dlp/yt-dlp-master-builds)
[orf:on] Extracting URL: https://on.orf.at/video/14228910/sommer-auf-drei-raedern
[orf:on] 14228910: Downloading JSON metadata
[orf:on] 14228910: Downloading m3u8 information
[orf:on] 14228910: Downloading m3u8 information
[orf:on] 14228910: Downloading MPD manifest
[orf:on] 14228910: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 14228910: Downloading 1 format(s): dash-p0va0br3001307-1+dash-p0aa0br192000-1
[debug] Invoking dashsegments downloader on "https://vod-at.mdn.ors.at/cms-austria_nas/_definst_/nas/cms-austria/online/2024-06-03_2015_in_01_Sommer-auf-drei_____14228910__o__2032336759__s15649939_hr.smil/manifest.mpd"
[dashsegments] Total fragments: 535
[download] Destination: Sommer auf drei Rädern [14228910].fdash-p0va0br3001307-1.mp4
[download] 100% of    1.86GiB in 00:03:18 at 9.63MiB/s
[debug] Invoking dashsegments downloader on "https://vod-at.mdn.ors.at/cms-austria_nas/_definst_/nas/cms-austria/online/2024-06-03_2015_in_01_Sommer-auf-drei_____14228910__o__2032336759__s15649939_hr.smil/manifest.mpd"
[dashsegments] Total fragments: 1070
[download] Destination: Sommer auf drei Rädern [14228910].fdash-p0aa0br192000-1.m4a
[download] 100% of  248.08MiB in 00:02:50 at 1.46MiB/s
[Merger] Merging formats into "Sommer auf drei Rädern [14228910].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Sommer auf drei Rädern [14228910].fdash-p0va0br3001307-1.mp4' -i 'file:Sommer auf drei Rädern [14228910].fdash-p0aa0br192000-1.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Sommer auf drei Rädern [14228910].temp.mp4'
[debug] ffmpeg version 6.0.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --disable-decoder=amrnb --disable-decoder=libopenjpeg --disable-gnutls --disable-liblensfun --disable-libopencv --disable-podpages --disable-sndio --disable-stripping --enable-avfilter --enable-chromaprint --enable-frei0r --enable-gcrypt --enable-gpl --enable-ladspa --enable-libaom --enable-libaribb24 --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libdavs2 --enable-libdc1394 --enable-libdrm --enable-libfdk-aac --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libkvazaar --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librsvg --enable-librubberband --enable-libshine --enable-libsmbclient --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-nonfree --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-openssl --enable-postproc --enable-pthreads --enable-shared --enable-version3 --enable-vulkan --incdir=/usr/include/x86_64-linux-gnu --libdir=/usr/lib/x86_64-linux-gnu --prefix=/usr --toolchain=hardened --enable-vaapi --enable-libvpl --enable-libvmaf --enable-libilbc --enable-libjxl --cc=x86_64-linux-gnu-gcc --cxx=x86_64-linux-gnu-g++ --disable-altivec --shlibdir=/usr/lib/x86_64-linux-gnu
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:Sommer auf drei Rädern [14228910].fdash-p0va0br3001307-1.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isomavc1iso6dashmp42cmfc
    creation_time   : 2024-06-02T18:18:41.000000Z
  Duration: 01:28:51.78, start: 0.080000, bitrate: 3004 kb/s
  Stream #0:0[0x1](eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 3000 kb/s, 25 fps, 25 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2024-06-02T18:18:41.000000Z
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : VideoHandler
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5625107228c0] error reading header
file:Sommer auf drei Rädern [14228910].fdash-p0aa0br192000-1.m4a: Invalid data found when processing input

ERROR: Postprocessing: file:Sommer auf drei Rädern [14228910].fdash-p0aa0br192000-1.m4a: Invalid data found when processing input
Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3537, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3719, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3701, in run_all_pps
    info = self.run_pp(pp, info)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3679, in run_pp
    files_to_delete, infodict = pp.run(infodict)
                                ^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 128, in wrapper
    return func(self, info)
           ^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 839, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 329, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 367, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:Sommer auf drei Rädern [14228910].fdash-p0aa0br192000-1.m4a: Invalid data found when processing input
```

**Comment by bashonly** [comment] 2024-06-05 22:05
try upgrading ffmpeg to 6.1.1 or newer

**Comment by bashonly** [comment] 2024-06-05 22:42
this is probably a duplicate of #8641

**Comment by arminfuerst** [comment] 2024-06-05 22:43
> try upgrading ffmpeg to 6.1.1 or newer

Seems a good idea - this is not an easy task for me as it breaks a lot of package dependencies...

**Comment by bashonly** [comment] 2024-06-05 22:46
https://github.com/yt-dlp/FFmpeg-Builds/releases/tag/latest

`yt-dlp -v --ffmpeg-location "/path/to/downloaded/binary/ffmpeg" "URL"`

**Comment by arminfuerst** [comment] 2024-06-05 22:47
Thanks - I'll try after having fixed my system again ;)

**Comment by arminfuerst** [comment] 2024-06-05 23:13
I can now confirm the download was working with ffmpeg version N-115578-g0415bb74c8-20240605.
I would be fine with closing this issue as I don't see any improvements in yt-dlp related to this.

**Closed** 2024-06-05 23:17 UTC
Labels: duplicate, external issue
