### ISSUE TITLE
yt-dlp using --netrc option to download from Twitter is yielding .mp4 files with no audio, video is playing

### ISSUE THREAD

**Issue by walt93** [yt-dlp/yt-dlp#8750] opened 2023-12-10 23:06 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Use yt-dlp to download the specified mp4 video from Twitter.
Observe that while video plays, no audio is heard. 
https://twitter.com/vision4theblind/status/1733837664673988751

Others were noted, including: https://twitter.com/Thekeksociety/status/1733670116473319587

_(All instructions to update to nightly or master failed, so this is reported against 2023.11.16)_

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
% yt-dlp --netrc "https://twitter.com/vision4theblind/status/1733837664673988751" -o "Comedy central illuminati commercial.mp4" -vU
[debug] Command-line config: ['--netrc', 'https://twitter.com/vision4theblind/status/1733837664673988751', '-o', 'Comedy central illuminati commercial.mp4', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (zip)
[debug] Python 3.11.6 (CPython arm64 64bit) - macOS-14.1.1-arm64-arm-64bit (OpenSSL 3.2.0 23 Nov 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, requests-2.31.0, sqlite3-3.44.2, urllib3-2.0.3, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[twitter] Downloading login page
[twitter] Downloading flow token
[twitter] Submitting JS instrumentation response
[twitter] Submitting username
[twitter] Submitting password
[twitter] Submitting account duplication check
[twitter] Logging in
[twitter] Extracting URL: https://twitter.com/vision4theblind/status/1733837664673988751
[twitter] 1733837664673988751: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1733837595581247488
[twitter] 1733837664673988751: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, br, size, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1733837595581247488: Downloading 1 format(s): http-2176
[debug] Invoking http downloader on "https://video.twimg.com/ext_tw_video/1733837595581247488/pu/vid/avc1/576x1024/nYXy56Qvd1JPgVI_.mp4?tag=12"
[download] Destination: Comedy central illuminati commercial.mp4
[download] 100% of    5.70MiB in 00:00:00 at 89.29MiB/s
```

**Comment by walt93** [comment] 2023-12-10 23:11
Update: followed up on the URL emitted in 3rd to last line of debug output.
https://video.twimg.com/ext_tw_video/1733837595581247488/pu/vid/avc1/576x1024/nYXy56Qvd1JPgVI_.mp4
no audio plays on this in the browser
I claim there must be other .mp4 files which could be found to return here …

**Comment by DaddyBoard** [comment] 2023-12-14 11:15
Confirm I have the same issue with Twitter.

Although free online ones like ssstwitter(dot)com are doing the same thing, no audio. 

Also trying to send a video saved this way via WhatsApp errors out saying "This type of video can't be sent" when its literally .mp4 
@bashonly

**Comment by benwh1** [comment] 2023-12-14 20:11
I have this problem too. The downloaded videos work in Firefox but VLC can't play the audio.

As a temporary workaround, the files can be fixed with FFmpeg by running `ffmpeg -i [input] -c copy [output]`.

**Comment by dirkf** [comment] 2023-12-15 02:20
So does specifying FFmpeg as (external-)downloader result in good media?

**Comment by bashonly** [comment] 2023-12-19 12:58
> So does specifying FFmpeg as (external-)downloader result in good media?

Yeah it does. Though I don't think we can force ffmpeg as external FD for http formats, nor can we force a fixup for them (without modifying core code).

I think the best solution is to prioritize HLS formats.

This is a dupe of #8117

**Closed by bashonly** 2023-12-19 12:58 UTC
Labels: external issue, site-bug, triage
