### ISSUE TITLE
Platform Support

### ISSUE THREAD

**Issue by commet24** [yt-dlp/yt-dlp#10770] opened 2024-08-16 15:16 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Belarus

### Example URLs

- Single video: https://plvideo.ru/watch?v=4VdiJaW2Af36
- Playlist: https://plvideo.ru/playlist?v=&list=dlaTfVPoXThN

### Provide a description that is worded well enough to be understood

Doesn't download cause of unsupported URL.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://plvideo.ru/watch?v=4VdiJaW2Af36']         [debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8                                         [debug] yt-dlp version nightly@2024.08.15.233031 from yt-dlp/yt-dlp-nightly-builds [d62fef7e0] (pip)                                [debug] Python 3.11.9 (CPython aarch64 64bit) - Linux-4.14.186-perf-g7df73a1af183-aarch64-with-libc (OpenSSL 3.3.1 4 Jun 2024, libc)[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1                               [debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0                [debug] Proxy map: {}                       [debug] Request Handlers: urllib, requests, websockets                                  [debug] Loaded 1830 extractors              [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest                            Latest version: nightly@2024.08.15.233031 from yt-dlp/yt-dlp-nightly-builds             yt-dlp is up to date (nightly@2024.08.15.233031 from yt-dlp/yt-dlp-nightly-builds)      [generic] Extracting URL: https://plvideo.ru/watch?v=4VdiJaW2Af36                       [generic] watch?v=4VdiJaW2Af36: Downloading webpage                                     WARNING: [generic] Falling back on generic information extractor                        [generic] watch?v=4VdiJaW2Af36: Extracting information                                  [debug] Looking for embeds                  ERROR: Unsupported URL: https://plvideo.ru/watch?v=4VdiJaW2Af36                         Traceback (most recent call last):            File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper                        return func(self, *args, **kwargs)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^        File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info                 ie_result = ie.extract(url)                             ^^^^^^^^^^^^^^^               File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 740, in extract                  ie_result = self._real_extract(url)                     ^^^^^^^^^^^^^^^^^^^^^^^       File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2526, in _real_extract          raise UnsupportedError(url)             yt_dlp.utils.UnsupportedError: Unsupported URL: https://plvideo.ru/watch?v=4VdiJaW2Af36
```

**Comment by bashonly** [comment] 2024-08-16 19:42
Duplicate of #10311

**Closed by bashonly** 2024-08-16 19:42 UTC
Labels: site-request, triage
