### ISSUE TITLE
Bilibili flv format unsupported

### ISSUE THREAD

**Issue by z0z0r4** [yt-dlp/yt-dlp#6559] opened 2023-03-18 17:01 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

China

### Example URLs

https://www.bilibili.com/video/BV1Ts411z762/?p=3

### Provide a description that is worded well enough to be understood

https://www.bilibili.com/video/BV1Ts411z762/?p=3

视频是flv格式，无法下载

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\DELL>yt-dlp "https://www.bilibili.com/video/BV1Ts411z762/?p=3&vd_source=b2c616c25dc7b37a6c964cca2473ad8c" --cookies-from-browser edge -vU
[debug] Command-line config: ['https://www.bilibili.com/video/BV1Ts411z762/?p=3&vd_source=b2c616c25dc7b37a6c964cca2473ad8c', '--cookies-from-browser', 'edge', '-vU']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from edge
[debug] Extracting cookies from: "C:\Users\DELL\AppData\Local\Microsoft\Edge\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\DELL\AppData\Local\Microsoft\Edge\User Data\Local State"
[Cookies] Extracted 1475 cookies from edge
[debug] cookie version breakdown: {'v10': 1475, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1Ts411z762/?p=3&vd_source=b2c616c25dc7b37a6c964cca2473ad8c
[BiliBili] 1Ts411z762: Downloading webpage
[BiliBili] BV1Ts411z762: Extracting videos in anthology
[BiliBili] Format(s) 1080P 高清, 360P 流畅, 720P 高清 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[BiliBili] 4232628: Extracting chapters
ERROR: [BiliBili] BV1Ts411z762_p3: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "D:\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 2615, in process_video_result
    self.raise_no_formats(info_dict)
  File "D:\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1046, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [BiliBili] BV1Ts411z762_p3: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```
```

**Comment by bashonly** [comment] 2023-03-19 01:55
This seems to be fixed by the patch here: https://github.com/yt-dlp/yt-dlp/issues/5874#issuecomment-1365452076
And also by PR #6438

Related: #3659, #5655
and it appears to be a duplicate of #5874, closing as such

**Closed by bashonly** 2023-03-19 01:55 UTC
Labels: site-request, triage
