### ISSUE TITLE
[youtube] Stuck in infinite loop grabbing API JSON on channels

### ISSUE THREAD

**Issue by jorong1** [yt-dlp/yt-dlp#1611] opened 2021-11-10 03:33 UTC
[ytdl-errorapi.txt](https://github.com/yt-dlp/yt-dlp/files/7509621/ytdl-errorapi.txt)
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

North America or Worldwide

### Description

I did my best to search the bug tracker but couldn't find anything about this.

I am getting stuck in seemingly infinite loops where the youtube extractor tries to download the API JSON for channels. This bug does not appear to be channel specific, it simply triggers after either going through multiple other channels, or randomly with a single channel. I am unsure if it's some kind of blackholing effect as a limiter.

Please see the verbose log for an example. The linked channel does not have over 1000 pages, let alone over 100.

This also occurs with other channels, it's random.
https://www.youtube.com/channel/UC5Jj_A0NjP2vtcZZvvYU7qw/videos
or https://www.youtube.com/channel/UCnFP0IU4gpnmcLnVzDLUtfw

I've tried grabbing with different IPs over VPNs or powercycling my modem, with no change.

I can provide more details when needed. Thanks!

### Verbose log

```shell
$ yt-dlp -Uv --config-location ./youtube-dl.conf
[debug] Command-line config: ['-vvv', '--config-location', './youtube-dl.conf']
[debug] Custom config file: ./youtube-dl.conf
[debug] Custom config: ['-f', 'bestvideo[ext=webm]+bestaudio[ext=webm]/bestvideo[ext=mp4]+bestaudio[ext=webm]/bestvide
o+bestaudio', '-i', '-o', '/mnt/youtubedl/%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s - [%(resolution)s] [%(id)s].%(ext)s', '--ffmpeg-location', '/usr/local/bin/', '--no-write-playlist-metafiles', '--concurrent-fragments', '16', '--downloader-args', '-x 16 -s 16', '--retries', '20', '--download-archive', '/mnt/youtubedl/youtube-dl-archive.txt', '-a', '/mnt/youtubedl/youtube-dl-channels.txt', '--merge-output-format', 'mkv', '--write-sub', '--all-subs', '--convert-subs', 'srt', '--add-metadata', '--write-description', '--write-thumbnail', '-v']
[debug] Batch file urls: ['https://www.youtube.com/channel/UCyduf4VRZnF7RXSrqqexX5w',]
WARNING: --downloader-args given without specifying name. The arguments will be given to all external downloaders
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1 (zip)
[debug] Python version 3.7.3 (CPython 64bit) - Linux-5.10.0-0.bpo.8-amd64-x86_64-with-debian-10.11
[debug] exe versions: ffmpeg 4.2.1 (fdk), ffprobe 4.2.1
[debug] Optional libraries: Crypto, keyring, sqlite
[debug] Proxy map: {}
[debug] Loading archive file '/mnt/youtubedl/youtube-dl-archive.txt'
yt-dlp is up to date (2021.11.10.1)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/UCyduf4VRZnF7RXSrqqexX5w
WARNING: [youtube:tab] A channel/user page was given. All the channel's videos will be downloaded. To download only th
e videos in the home page, add a "/featured" to the URL
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/channel/UCyduf4VRZnF7RXSrqqexX5w/videos
[download] Downloading playlist: Grace Motley - Videos
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 1: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 2: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 3: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 4: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 5: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 6: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 7: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 8: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 9: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 10: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 11: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 12: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 13: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 14: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 15: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 16: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 17: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 18: Downloading API JSON
[...]
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 1638: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 1639: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 1640: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 1641: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 1642: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 1643: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 1644: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 1645: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 1646: Downloading API JSON
[youtube:tab] UCyduf4VRZnF7RXSrqqexX5w page 1647: Downloading API JSON
^C
ERROR: Interrupted by user
```

**Comment by coletdjnz** [comment] 2021-11-10 03:34
Currently appears to be a YouTube issue, I'm getting this too. Passing the channel's uploads playlist should workaround it for now.

**Comment by jorong1** [comment] 2021-11-10 03:43
Thanks for the insight, glad it isn't just me. I will sit tight for a proper fix, and for urgent stuff will use your workaround!

**Comment by xaeiougit** [comment] 2021-11-10 04:42
An option to automatically derive and use the uploads playlist URL from the channels videos URL could be a useful addition to yt-dl to mitigate this problem in the future.

**Comment by periperipea** [comment] 2021-11-10 05:20
For what it's worth, same issue occurs on youtube-dl, so definitely something changed on Youtube side.

**Comment by Trit34** [comment] 2021-11-10 09:32
@coletdjnz : I make my own webradio with `mpv --ytdl-format=140 --shuffle [channel’s URL]`, and I had the (bad) surprise to see the command do nothing this morning (CET). Thankfully, using the uploaded videos playlist URL works.

Could you past the link to the tweet ackowledging this is a bug?

Plus, there is a bug with videos repeated again and again on the “Videos” page: https://twitter.com/TeamYouTube/status/1458363111799496710

Hopefully, all these bugs will be fixed soon and we will use youtube-dl/yt-dlp again without updating them.

**Comment by coletdjnz** [comment] 2021-11-10 09:43
> @coletdjnz : I make my own webradio with `mpv --ytdl-format=140 --shuffle [channel’s URL]`, and I had the (bad) surprise to see the command do nothing this morning (CET). Thankfully, using the uploaded videos playlist URL works.
> 
> Could you past the link to the tweet ackowledging this is a bug?
> 
> Plus, there is a bug with videos repeated again and again on the “Videos” page: https://twitter.com/TeamYouTube/status/1458363111799496710
> 
> Hopefully, all these bugs will be fixed soon and we will use youtube-dl/yt-dlp again without updating them.

The one you linked is pretty much what they are responding with atm - that's the issue that's causing this issue with yt-dl(p). I've reworded my comment since they technically haven't acknowledged it as a bug yet afaik.

**Comment by pukkandan** [comment] 2021-11-10 13:13
> An option to automatically derive and use the uploads playlist URL from the channels videos URL could be a useful addition to yt-dl to mitigate this problem in the future.

1. This wont solve anything. Maybe next time, they will break playlists and not /videos 🤷 
2. The uploads playlist does not contain all videos of the channel for very large channels. So an auto-redirection is not good. It must be user's own choice to choose one or the other

**Comment by xaeiougit** [comment] 2021-11-10 14:14
> > An option to automatically derive and use the uploads playlist URL from the channels videos URL could be a useful addition to yt-dl to mitigate this problem in the future.
> 
> 1. This wont solve anything. Maybe next time, they will break playlists and not /videos shrug
>
> 2. The uploads playlist does not contain all videos of the channel for very large channels. So an auto-redirection is not good. It must be user's own choice to choose one or the other

I wasn't aware of that caveat, I'll keep an eye out for it  -  thanks!

Although I didn't mean to imply auto-direction without use of a command line option, I get your point ...on reflection it's perhaps a confusing overload of functionality to put something like this into yt-dl.  Messing with the URL used to scrape channels would be better handled as a function within my "multiple channel scraper" script.  I just added one, and it's also got me thinking about other ways I could play with the download URL to make update runs more efficient and or robust ready for the next youtube breakage 😀

Thanks for the great tool in yt-dl.

**Comment by cg0** [comment] 2021-11-10 14:24
Issue seems to be sorted for me now in the UK.

**Comment by makeworld-the-better-one** [comment] 2021-11-10 14:53
I can't replicate this in Canada either. I tested by using the URLs in the original comment. Seems like the issue is fixed on YouTube's end and yt-dlp doesn't need to do anything?

**Comment by ThomasWarnasch** [comment] 2021-11-10 15:14
Can confirm that issue no longer appears to be occurring.

**Comment by pukkandan** [comment] 2021-11-10 15:50
Seems to be fixed

**Closed by pukkandan** 2021-11-10 15:50 UTC
Labels: external issue

**Comment by rebane2001** [comment] 2021-11-13 02:12
It has not been fixed, it is just a lot more rare now, but it definitely still keeps happening.

**Comment by pukkandan** [comment] 2021-11-13 04:32
Oh, Does it happen in browser too? or only in yt-dlp?

**Comment by radoslawg** [comment] 2021-11-13 07:20
I can confirm. It still happens. However, it seems to be random which makes it harder to give example. When I try to redownload it work and obviously when I look in browser it also works. I hope this is not some kind of countermeasure/honeypot for applications like yt-dlp but simple youtube bug.

**Comment by rebane2001** [comment] 2021-11-13 09:56
I can't say as I don't use YouTube enough myself for this to happen. The yt-dlp jobs I have load channels tens of thousands of times a day and even with that it is still pretty rare. As rare as it may be, it is still critical if not caught.

**Comment by pukkandan** [comment] 2021-11-13 11:06
@coletdjnz Do you have any idea if we can detect this issue and raise an error instead of the infinite loop?

**Comment by rebane2001** [comment] 2021-11-13 11:14
@pukkandan I propose we could detect the same video IDs repeated an abnormal number of times (this would not work for playlists, but would be fine for channel video pages).

**Comment by chapmanjacobd** [comment] 2022-09-05 06:24
I've experienced this only very rarely on Topic pages. `--playlist-end` works well

https://m.youtube.com/channel/UCodMGMP1NNN7Bg-i8x5VrNA/videos

**Comment by chapmanjacobd** [comment] 2022-09-05 06:25
I've experienced this only very rarely on Topic pages. --playlist-end works well

https://m.youtube.com/channel/UCI4-cRRz7SKOg5LxAruPpbQ/playlists

**Comment by gczychi** [comment] 2025-06-12 06:10
This is probably a very dumb question, but where can I find the «uploaded videos playlist URL»?

I have two possible channel id’s (for example: `youtube.com/@EdBolian` or `youtube.com/channel/UCHJB_mpFHEjzrHgCO06a7Tg`).
I can’t see any playlist or sub-category named «uploaded videos». So, where can I find the uploaded videos playlist URL?
Thanks a lot!

**Comment by coletdjnz** [comment] 2025-06-12 06:14
> This is probably a very dumb question, but where can I find the «uploaded videos playlist URL»?
> 
> I have two possible channel id’s (for example: `youtube.com/@EdBolian` or `youtube.com/channel/UCHJB_mpFHEjzrHgCO06a7Tg`).
> I can’t see any playlist or sub-category named «uploaded videos». So, where can I find the uploaded videos playlist URL?
> Thanks a lot!

uploaded videos playlist id is the channel id but the UC prefix is replaced with UU https://www.youtube.com/playlist?list=UUHJB_mpFHEjzrHgCO06a7Tg
