### ISSUE TITLE
[Odnoklassniki]Cannot download the full, hd, sd, low, lowest, mobile formats from ok.ru

### ISSUE THREAD

**Issue by sebma** [yt-dlp/yt-dlp#4729] opened 2022-08-21 21:15 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

Hi,

`yt-dlp` cannot download the full, hd, sd, low, lowest, mobile formats from ok.ru.
Only the `mpd` formats are recognized, the others are `unknown` : 
```python
$ yt-dlp --ignore-config -U https://ok.ru/video/2174442605292 -F
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[Odnoklassniki] 2174442605292: Downloading desktop webpage
[Odnoklassniki] 2174442605292: Downloading m3u8 information
[info] Available formats for 2174442605292:
ID       EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
mobile   mp4 unknown        │                  https │ unknown           unknown
hls-136  mp4 240x144     24 │ ~ 95.57MiB  137k m3u8  │ unknown      137k unknown    0k
mpd-0    mp4 240x144     24 │ ~ 73.22MiB  105k https │ avc1.64000C  105k mp4a.40.2  0k 44k DASH video, mp4_dash
lowest   mp4 unknown        │                  https │ unknown           unknown
hls-339  mp4 400x240     24 │ ~237.16MiB  339k m3u8  │ unknown      339k unknown    0k
mpd-1    mp4 400x240     24 │ ~207.67MiB  297k https │ avc1.64000D  297k mp4a.40.2  0k 44k DASH video, mp4_dash
low      mp4 unknown        │                  https │ unknown           unknown
hls-682  mp4 600x360     24 │ ~476.80MiB  682k m3u8  │ unknown      682k unknown    0k
mpd-2    mp4 600x360     24 │ ~437.16MiB  626k https │ avc1.64001E  626k mp4a.40.2  0k 44k DASH video, mp4_dash
sd       mp4 unknown        │                  https │ unknown           unknown
hls-1196 mp4 800x480     24 │ ~836.16MiB 1196k m3u8  │ unknown     1196k unknown    0k
mpd-3    mp4 800x480     24 │ ~779.27MiB 1115k https │ avc1.64001E 1115k mp4a.40.2  0k 44k DASH video, mp4_dash
hd       mp4 unknown        │                  https │ unknown           unknown
hls-2625 mp4 1200x720    24 │ ~  1.79GiB 2626k m3u8  │ unknown     2626k unknown    0k
mpd-4    mp4 1200x720    24 │ ~  1.69GiB 2478k https │ avc1.64001F 2478k mp4a.40.2  0k 44k DASH video, mp4_dash
full     mp4 unknown        │                  https │ unknown           unknown
hls-4683 mp4 1800x1080   24 │ ~  3.20GiB 4683k m3u8  │ unknown     4683k unknown    0k
mpd-5    mp4 1800x1080   24 │ ~  3.05GiB 4464k https │ avc1.640028 4464k mp4a.40.2  0k 44k DASH video, mp4_dash
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp --ignore-config -vU https://ok.ru/video/2174442605292 -f full/hd/sd/low/lowest/mobile
[debug] Command-line config: ['--ignore-config', '-vU', 'https://ok.ru/video/2174442605292', '-f', 'full/hd/sd/low/lowest/mobile']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (pip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.15.0-46-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1-static (setts), ffprobe 4.4-1ppa1, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.12.05, mutagen-1.45.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [Odnoklassniki] Extracting URL: https://ok.ru/video/2174442605292
[Odnoklassniki] 2174442605292: Downloading desktop webpage
[Odnoklassniki] 2174442605292: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 2174442605292: Downloading 1 format(s): full
[debug] Invoking http downloader on "https://vd254.mycdn.me/?expires=1661202596402&srcIp=88.170.110.213&pr=10&srcAg=CHROME&ms=185.226.52.4&type=5&sig=JsqVQA9ZQSY&ct=0&urls=45.136.22.6&clientType=0&id=618769681132"
ERROR: unable to download video data: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3170, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 2894, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/downloader/common.py", line 442, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/downloader/http.py", line 371, in real_download
    establish_connection()
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3648, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by dirkf** [comment] 2022-08-22 13:32
Duplicate of #4462.

**Closed** 2022-08-22 18:51 UTC
Labels: duplicate, site-bug
