### ISSUE TITLE
[youtube] could there be a way to download all subtitles and all .*orig auto subs?

### ISSUE THREAD

**Issue by NewUserHa** [yt-dlp/yt-dlp#3314] opened 2022-04-05 18:42 UTC
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

no

### Description

for subs current rules is at https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L2671:
1. auto-subs will not be downloaded if there's already a normal sub in the dict with the same key/lang
2. if no sub-lang argument, default to 'en' (not be documented btw)
3. if no 'en', download the first item of the dict of all-langs.

Imagine if there's a video with another language normal subtitles,  which is not 'en' and not at the first one. then the yt-dlp can't get the right subtitles.

what about making:
1. users can download both normal subtitles and auto-subs that both have the same key/lang
2. since most normal subs are precise because they are not created by machines, let users be able to download all normal subs, probably via --sub-lang with the same kind suffix like `.*orig` or something others

### Verbose log

```shell
no
```

**Comment by pukkandan** [comment] 2022-04-05 19:04
You are putting too many different (but related) issues in one report

> users can download both normal subtitles and auto-subs that both have the same key/lang

Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2262

> since most normal subs are precise because they are not created by machines, let users be able to download all normal subs, probably via --sub-lang with the same kind suffix like .*orig or something others

You can do `--sub-lang all`

> Imagine if there's a video with another language normal subtitles, which is not 'en' and not at the first one. then the yt-dlp can't get the right subtitles.

I agree it makes sense to prioritize normal subs over auto-subs in step 3

**Comment by NewUserHa** [comment] 2022-04-05 19:17
> You are putting too many different (but related) issues in one report

the 2 are actually one issue: keep both for users to choose, via --sub-lang or new option to achieve

> You can do --sub-lang all

translated subtitles are too poor to use

> I agree it makes sense to prioritize normal subs over auto-subs in step 3

auto-subs(not translated) are sometimes very accurate and it's timed based on the speakers.
but normal subtitles are still crapy sometimes because of the volunteer translators. so probably save both and let the human users decide which is great.

**Comment by NewUserHa** [comment] 2022-04-05 19:20
the best default situation probably is to download all or users selected normal subtitles (or based on users' locale info), and download auto-subs only for the languages of the videos

**Comment by NewUserHa** [comment] 2022-04-05 19:26
from https://github.com/yt-dlp/yt-dlp/issues/2262#issuecomment-1007921078:
> most people would expect --sub-lang to keep behaving as it currently does

right. so I think:
> probably via --sub-lang with the same kind suffix like .*orig or something others

**Comment by NewUserHa** [comment] 2022-04-05 19:37
or maybe probably that ignoring all auto-translated subtitles and downloading all other shows in the settings of the player of youtube is also an acceptable choice.

**Comment by pukkandan** [comment] 2022-04-06 07:40
> > You can do --sub-lang all
>
> translated subtitles are too poor to use

Don't use --write-auto-subs, just `--write-subs --sub-langs all`


> from [#2262 (comment)](https://github.com/yt-dlp/yt-dlp/issues/2262#issuecomment-1007921078):
> 
> > most people would expect --sub-lang to keep behaving as it currently does
> 
> so I think:
> 
> > probably via --sub-lang with the same kind suffix like .*orig or something others
> 
> and probably could also make the 'auto-subs' in its filename for users to distinguish the quality.

Please continue discussion of this in #2262, not here

> so probably save both and let the human users decide which is great.

That is what #2262 is requesting

**Comment by NewUserHa** [comment] 2022-04-06 07:44
> Don't use --write-auto-subs, just --write-subs --sub-langs all

But this can't handle when there're only auto-subs and no normal subs at all

**Closed** 2022-04-08 08:36 UTC
Labels: enhancement

**Comment by pukkandan** [comment] 2022-04-08 11:13
> Imagine if there's a video with another language normal subtitles, which is not 'en' and not at the first one. then the yt-dlp can't get the right subtitles.

This part has been fixed in d8a58ddce7a4aaf0d525041ab3b01eb2ab2d0a41


> users can download both normal subtitles and auto-subs that both have the same key/lang
since most normal subs are precise because they are not created by machines, let users be able to download all normal subs, probably via --sub-lang with the same kind suffix like .*orig or something others

These can be tracked in #2262

**Comment by NewUserHa** [comment] 2022-04-08 11:15
thanks!

**Comment by NewUserHa** [comment] 2022-04-09 14:19
https://www.youtube.com/watch?v=KHEZCXfyxjU
found a link for test that has both 'en' and 'en auto-generated CC'
and the 'en' covers only part of the content
