### ISSUE TITLE
Brighteon

### ISSUE THREAD

**Issue by miscellaneous01** [yt-dlp/yt-dlp#8959] opened 2024-01-08 21:09 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

commandline: yt-dlp -civ https://www.brighteon.com/5b234a28-8a88-4b14-ac7c-8ca49b868b48

does not work anymore.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yy -civ https://www.brighteon.com/5b234a28-8a88-4b14-ac7c-8ca49b868b48 
[debug] Command-line config: ['-civ', 'https://www.brighteon.com/5b234a28-8a88-4b14-ac7c-8ca49b868b48']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (linux_exe)
[debug] Python 3.10.13 (CPython x86_64 64bit) - Linux-3.19.0-32-generic-x86_64-with-glibc2.19 (OpenSSL 3.2.0 23 Nov 2023, glibc 2.19)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[generic] Extracting URL: https://www.brighteon.com/5b234a28-8a88-4b14-ac7c-8ca49b868b48
[generic] 5b234a28-8a88-4b14-ac7c-8ca49b868b48: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 5b234a28-8a88-4b14-ac7c-8ca49b868b48: Extracting information
[debug] Looking for embeds
[html5] 5b234a28-8a88-4b14-ac7c-8ca49b868b48: Downloading m3u8 information
[html5] 5b234a28-8a88-4b14-ac7c-8ca49b868b48: Downloading MPD manifest
ERROR: An extractor error has occurred. (caused by KeyError('sourceURL')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 718, in extract
  File "yt_dlp/extractor/generic.py", line 2526, in _real_extract
  File "yt_dlp/extractor/generic.py", line 2555, in _extract_embeds
  File "yt_dlp/extractor/common.py", line 3785, in extract_from_webpage
  File "yt_dlp/extractor/genericembeds.py", line 24, in _extract_from_webpage
  File "yt_dlp/extractor/common.py", line 3112, in _parse_html5_media_entries
  File "yt_dlp/extractor/common.py", line 3065, in _media_formats
  File "yt_dlp/extractor/common.py", line 2528, in _extract_mpd_formats
  File "yt_dlp/extractor/common.py", line 2555, in _extract_mpd_formats_and_subtitles
  File "yt_dlp/extractor/common.py", line 2741, in _parse_mpd_formats_and_subtitles
  File "yt_dlp/extractor/common.py", line 2625, in extract_multisegment_info
  File "yt_dlp/extractor/common.py", line 2620, in extract_Initialization
KeyError: 'sourceURL'
```

**Comment by bashonly** [comment] 2024-01-08 21:11
Duplicate of #8269

**Closed by bashonly** 2024-01-08 21:11 UTC
Labels: site-bug, triage
