### ISSUE TITLE
new: SEVERE class threat "Trojan:Win32/Spursint.F!cl" detected

### ISSUE THREAD

**Issue by hydra3333** [yt-dlp/yt-dlp#1579] opened 2021-11-06 22:55 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

After previously allowing it up until 2 days ago, the latest Microsoft win defender detects the latest ydl release as a SEVERE class threat "Trojan:Win32/Spursint.F!cl"  "This program is dangerous and executes commands from an attacker."

### Verbose log

```shell
nil
```

**Comment by pukkandan** [comment] 2021-11-06 22:56
Duplicate of #25

**Closed by pukkandan** 2021-11-06 22:56 UTC
Labels: bug, triage

**Comment by ZekePolarisBSH** [comment] 2022-11-15 05:15
I found this in a zip file that has GIF images. It only came from that one zip and non of the other zips and they all came from the same source. This is confusing. Trojan:Win32/Spursint.F!cl
