### ISSUE TITLE
tiktok dosnt work everytime it should

### ISSUE THREAD

**Issue by MrIcedTea** [yt-dlp/yt-dlp#9987] opened 2024-05-21 08:58 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

germany

### Provide a description that is worded well enough to be understood

some videos/profiles dont work, maybe an european server or so

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU https://www.tiktok.com/@aurubis.ag
[debug] Command-line config: ['-vU', 'https://www.tiktok.com/@aurubis.ag']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (linux_exe)
[debug] Python 3.10.14 (CPython x86_64 64bit) - Linux-5.10.0-28-amd64-x86_64-with-glibc2.31 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user] Extracting URL: https://www.tiktok.com/@aurubis.ag
[tiktok:user] aurubis.ag: Downloading webpage
[debug] [tiktok:user] {'app_name': 'musical_ly', 'app_version': '34.1.2', 'manifest_app_version': '2023401020', 'aid': '0', 'iid': '7351144126450059040'}
[tiktok:user] aurubis.ag: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 3)
[debug] [tiktok:user] {'app_name': 'musical_ly', 'app_version': '34.1.2', 'manifest_app_version': '2023401020', 'aid': '0', 'iid': '7351153174894626592'}
[tiktok:user] aurubis.ag: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 3)
[debug] [tiktok:user] {'app_name': 'musical_ly', 'app_version': '34.1.2', 'manifest_app_version': '2023401020', 'aid': '0', 'iid': '7351149742343391009'}
[tiktok:user] aurubis.ag: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (1/3)...
[debug] [tiktok:user] {'app_name': 'musical_ly', 'app_version': '34.1.2', 'manifest_app_version': '2023401020', 'aid': '0', 'iid': '7351149742343391009'}
[tiktok:user] aurubis.ag: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (2/3)...
[debug] [tiktok:user] {'app_name': 'musical_ly', 'app_version': '34.1.2', 'manifest_app_version': '2023401020', 'aid': '0', 'iid': '7351149742343391009'}
[tiktok:user] aurubis.ag: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (3/3)...
[debug] [tiktok:user] {'app_name': 'musical_ly', 'app_version': '34.1.2', 'manifest_app_version': '2023401020', 'aid': '0', 'iid': '7351149742343391009'}
[tiktok:user] aurubis.ag: Downloading user video list page 1
ERROR: [tiktok:user] aurubis.ag: aurubis.ag: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 734, in extract
  File "yt_dlp/extractor/tiktok.py", line 889, in _real_extract
  File "yt_dlp/utils/traversal.py", line 280, in traverse_obj
  File "yt_dlp/utils/traversal.py", line 268, in _traverse_obj
  File "yt_dlp/utils/traversal.py", line 256, in apply_path
  File "yt_dlp/utils/traversal.py", line 185, in apply_key
  File "yt_dlp/utils/_utils.py", line 2222, in __getitem__
  File "yt_dlp/extractor/tiktok.py", line 857, in _video_entries_api
  File "yt_dlp/utils/_utils.py", line 5081, in __iter__
  File "yt_dlp/extractor/common.py", line 3862, in _error_or_warning
  File "yt_dlp/utils/_utils.py", line 5089, in report_retry
  File "yt_dlp/extractor/tiktok.py", line 859, in _video_entries_api
  File "yt_dlp/extractor/tiktok.py", line 183, in _call_api
  File "yt_dlp/extractor/tiktok.py", line 114, in _call_api_impl
  File "yt_dlp/extractor/common.py", line 1127, in download_content
  File "yt_dlp/extractor/common.py", line 1094, in download_handle
  File "yt_dlp/extractor/common.py", line 1082, in parse
  File "yt_dlp/extractor/common.py", line 1069, in _parse_json
  File "yt_dlp/extractor/common.py", line 1052, in __print_error

  File "yt_dlp/utils/_utils.py", line 552, in decode
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp/extractor/common.py", line 1066, in _parse_json
  File "json/__init__.py", line 359, in loads
  File "yt_dlp/utils/_utils.py", line 560, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by bashonly** [comment] 2024-05-21 13:59
Duplicate of #3776

**Comment by bashonly** [comment] 2024-05-21 14:00
update to nightly if you're having trouble with individual videos

**Closed by bashonly** 2024-05-21 13:59 UTC
Labels: duplicate, site-bug, site:tiktok
