### ISSUE TITLE
france.tv

### ISSUE THREAD

**Issue by triplesixman** [yt-dlp/yt-dlp#8091] opened 2023-09-12 08:41 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

I just wanted to download some videos from france.tv but I keep getting this error. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
root@local:~/test# /usr/local/bin/yt-dlp.sh "https://www.france.tv/sport/autres-sports/championnats-d-europe-d-equitation/5222604-1ere-manche-par-equipe-megane-moissonnier-en-difficulte-la-france-recule-au-classement.html" -vU
[debug] Command-line config: ['https://www.france.tv/sport/autres-sports/championnats-d-europe-d-equitation/5222604-1ere-manche-par-equipe-megane-moissonnier-en-difficulte-la-france-recule-au-classement.html', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (source)
[debug] Git HEAD: cc0619f62
[debug] Python 3.9.7 (CPython x86_64 64bit) - Linux-5.10.0-25-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg N-111869-g7aa71ab5c0-20230831 (setts), ffprobe N-111869-g7aa71ab5c0-20230831, phantomjs 2.1.1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
Traceback (most recent call last):
  File "/opt/yt-dlp/yt_dlp/__main__.py", line 17, in <module>
    yt_dlp.main()
  File "/opt/yt-dlp/yt_dlp/__init__.py", line 1008, in main
    _exit(*variadic(_real_main(argv)))
  File "/opt/yt-dlp/yt_dlp/__init__.py", line 998, in _real_main
    return ydl.download(all_urls)
  File "/opt/yt-dlp/yt_dlp/YoutubeDL.py", line 3485, in download
    self.__download_wrapper(self.extract_info)(
  File "/opt/yt-dlp/yt_dlp/YoutubeDL.py", line 3460, in wrapper
    res = func(*args, **kwargs)
  File "/opt/yt-dlp/yt_dlp/YoutubeDL.py", line 1549, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/opt/yt-dlp/yt_dlp/YoutubeDL.py", line 821, in get_info_extractor
    ie = get_info_extractor(ie_key)()
  File "/opt/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 37, in __new__
    instance = cls.real_class.__new__(cls.real_class)
  File "/opt/yt-dlp/yt_dlp/utils/_utils.py", line 5553, in __get__
    return self.func(cls)
  File "/opt/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 33, in real_class
    cls._real_class = getattr(importlib.import_module(cls._module), cls.__name__)
  File "/opt/python/versions/3.9.7/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/yt-dlp/yt_dlp/extractor/francetv.py", line 9, in <module>
    from .dailymotion import DailymotionIE
  File "/opt/yt-dlp/yt_dlp/extractor/dailymotion.py", line 6, in <module>
    from ..compat import compat_HTTPError
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/opt/yt-dlp/yt_dlp/compat/compat_utils.py", line 36, in __getattribute__
    ret = super().__getattribute__(attr)
  File "/opt/yt-dlp/yt_dlp/compat/compat_utils.py", line 54, in __getattr__
    ret = from_child(attr)
  File "/opt/yt-dlp/yt_dlp/compat/compat_utils.py", line 76, in from_child
    return getattr(child, attr)
  File "/opt/yt-dlp/yt_dlp/compat/compat_utils.py", line 36, in __getattribute__
    ret = super().__getattribute__(attr)
  File "/opt/yt-dlp/yt_dlp/compat/compat_utils.py", line 57, in __getattr__
    callback(attr)
  File "/opt/yt-dlp/yt_dlp/compat/_deprecated.py", line 7, in <lambda>
    passthrough_module(__name__, '.._legacy', callback=lambda attr: warnings.warn(
DeprecationWarning: yt_dlp.compat._deprecated.compat_HTTPError is deprecated
```

**Comment by bashonly** [comment] 2023-09-12 10:13
I can't reproduce the error with master or with 2023.07.06

> [debug] yt-dlp version stable@2023.07.06 [b532a3481] (source)

Did you manually modify the source code?

**Comment by triplesixman** [comment] 2023-09-12 10:39
> I can't reproduce the error with master or with 2023.07.06
> 
> > [debug] yt-dlp version stable@2023.07.06 [[b532a34](https://github.com/yt-dlp/yt-dlp/commit/b532a3481046e1eabb6232ee8196fb696c356ff6)] (source)
> 
> Did you manually modify the source code?

No change in the code, I'll do further tests later today to see if I identify the problem

**Comment by bashonly** [comment] 2023-09-12 10:42
You seem to have the changes from this commit a250b247334ce9f641e709cbb64974da6034a2b3

But you do not the changes from this commit 3d2623a898196640f7cc0fc8b70118ff19e6925d, which was committed *before* the above commit

Try re-installing or re-cloning

**Closed** 2023-09-13 14:24 UTC
Labels: cant-reproduce
