### ISSUE TITLE
Twitter Spaces

### ISSUE THREAD

**Issue by slavakurilyak** [yt-dlp/yt-dlp#4386] opened 2022-07-19 02:51 UTC
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

It would be great to see [Twitter Spaces](https://help.twitter.com/en/using-twitter/spaces) support

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by HobbyistDev** [comment] 2022-07-19 04:20
Duplicate of #1249

**Closed** 2022-07-19 06:36 UTC
Labels: enhancement, triage
