### ISSUE TITLE
can not be download iqiyi.com

### ISSUE THREAD

**Issue by LanVaa** [yt-dlp/yt-dlp#7402] opened 2023-06-23 15:23 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Vietnam

### Provide a description that is worded well enough to be understood

C:\ffmpeg\bin>yt-dlp "https://www.iqiyi.com/v_1cqqgumpqkc.html?spm=a2h0c.8166622.PhoneSokuProgram_2.dtitle&vfm=m_549_skss&fv=8c8453c816db6550"
[iqiyi] Extracting URL: https://www.iqiyi.com/v_1cqqgumpqkc.html?spm=a2h0c.8166622.PhoneSokuProgram_2.dtitle&vfm=m_549_skss&fv=8c8453c816db6550
[iqiyi] temp_id: download video page
ERROR: [iqiyi] None: Can't find any video; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\ffmpeg\bin>yt-dlp -vU "https://www.iqiyi.com/v_1cqqgumpqkc.html?spm=a2h0c.8166622.PhoneSokuProgram_2.dtitle&vfm=m_549_skss&fv=8c8453c816db6550"
[debug] Command-line config: ['-vU', 'https://www.iqiyi.com/v_1cqqgumpqkc.html?spm=a2h0c.8166622.PhoneSokuProgram_2.dtitle&vfm=m_549_skss&fv=8c8453c816db6550']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-05-18-git-01d9a84ef5-full_build-www.gyan.dev (setts), ffprobe 2023-05-18-git-01d9a84ef5-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 37e7ffe204309357cfd1388b0e2c782a30e293ddd0f2761a9a8f6afa185b3566
yt-dlp is up to date (stable@2023.06.22)
[iqiyi] Extracting URL: https://www.iqiyi.com/v_1cqqgumpqkc.html?spm=a2h0c.8166622.PhoneSokuProgram_2.dtitle&vfm=m_549_skss&fv=8c8453c816db6550
[iqiyi] temp_id: download video page
ERROR: [iqiyi] None: Can't find any video; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 708, in extract
  File "yt_dlp\extractor\iqiyi.py", line 355, in _real_extract
```

**Comment by bashonly** [comment] 2023-06-23 15:32
Duplicate of #2740

**Closed by bashonly** 2023-06-23 15:32 UTC
Labels: site-bug, triage
