### ISSUE TITLE
youtube search can not get video description 

### ISSUE THREAD

**Issue by kaixuangh** [yt-dlp/yt-dlp#10198] opened 2024-06-17 03:28 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

def get_youtube_search(keyword, max_results=10):
    ydl_opts = {
        'quiet': True,
        'skip_download': True,
        'extract_flat': True,
        'default_search': 'ytsearch',
        'noplaylist': True,  # 避免搜索结果返回整个播放列表
    }

    with YoutubeDL(ydl_opts) as ydl:
        # "ytsearch10:关键词" 将搜索与“关键词”相关的前10个视频
        search_keyword = f'ytsearch{max_results}:{keyword}'
        result = ydl.extract_info(search_keyword, download=False)
        return format_crawler_data(result)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by kaixuangh** [comment] 2024-06-17 03:36
description是None

**Comment by bashonly** [comment] 2024-06-17 06:17
please show complete verbose output (replace `'quiet': True` with `'verbose': True` in your ydl opts)

**Comment by seproDev** [comment] 2024-06-17 07:57
The problem is that you use `extract_flat`. From the search playlist alone, we don't know the description. You need to actually let the video extract to get the description.

**Comment by bashonly** [comment] 2024-06-17 15:18
Duplicate of #6717

Youtube only returns partial descriptions with the search results (what you get with `extract_flat`). See https://github.com/yt-dlp/yt-dlp/issues/6717#issuecomment-1498603054

Related: #7445

**Closed by bashonly** 2024-06-17 15:18 UTC
Labels: question, incomplete
