### ISSUE TITLE
Extracting metadata of Tiktok Movies result in "Failed to parse JSON" and a non 0 error return code.

### ISSUE THREAD

**Issue by RensvanderZwan** [yt-dlp/yt-dlp#5707] opened 2022-12-04 17:48 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The parsing error results in a commandline return code other than 0.
Evethough the Parsing error, metadata is extracted and a json is returned.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
.\yt-dlp.exe -vU -j "https://www.tiktok.com/@nasrulah47/video/7173252680914062598"
[debug] Command-line config: ['-vU', '-j', 'https://www.tiktok.com/@nasrulah47/video/7173252680914062598']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@nasrulah47/video/7173252680914062598
[TikTok] 7173252680914062598: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7173252680914062598: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7173252680914062598: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7173252680914062598: Downloading video feed
WARNING: [TikTok] 7173252680914062598: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7173252680914062598: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7173252680914062598: Downloading 1 format(s): 0
{"id": "7173252680914062598", "title": "@Mardinli\ud83c\uddf9\ud83c\uddf7 adl\u0131 kullan\u0131c\u0131ya #cevap ", "duration": 64, "view_count": 266300, "like_count": 18400, "repost_count": 1521, "comment_count": 1120, "timestamp": 1670153044, "creator": null, "uploader": "nasrulah47", "uploader_id": "6931344640248054786", "uploader_url": "https://www.tiktok.com/@MS4wLjABAAAA5xYIXp126J3C03DmNG8oFxUtIZiOXINoYtA4SNFH0bYNTn_g0bTIo5-VzzJNYOWd", "track": "Love You So", "album": "Love You So", "artist": "The King Khan & BBQ Show", "formats": [{"url": "https://v16-webapp.tiktok.com/1226b672c9378d20b0b300e40a6b5545/638d2fd1/video/tos/useast2a/tos-useast2a-pve-0068/oolWXzGICEfkgPDNCoNMnkx2gCI3xAzUhUdAQO/?a=1988&ch=0&cr=0&dr=0&lr=tiktok_m&cd=0%7C0%7C1%7C0&cv=1&br=1108&bt=554&cs=0&ds=3&ft=IecA0onfD12Nvo2M8ZIxRyhjWlJG-UjNSsopi9&mime_type=video_mp4&qs=0&rc=OWRmNGQ5ZzRlaDY0OmhlOUBpMzhxPGc6ZjQ7aDMzNzczM0A0XzYtLTMuXy4xLV4zLWI0YSMuY29fcjRnMzNgLS1kMTZzcw%3D%3D&l=202212041738570101890730451005A411&btag=80000", "ext": "mp4", "width": 576, "height": 1018, "protocol": "https", "video_ext": "mp4", "audio_ext": "none", "format_id": "0", "format": "0 - 576x1018", "resolution": "576x1018", "dynamic_range": "SDR", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.50 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en-us,en;q=0.5", "Sec-Fetch-Mode": "navigate", "Referer": "https://www.tiktok.com/@nasrulah47/video/7173252680914062598", "Cookie": "ttwid=1%7CWqPIz8BhtGjOZV30ZnOXwuTfeJrjjzcT9uwhB2bgntk%7C1670175537%7C1704ac216c716b7a2eb26d22b215c201911ba7c5651772c03cccd60382ac48c0; tt_csrf_token=0GHMSACn-sJlQl8OUSFXmTlX9L3cX68Xi2Y0; tt_chain_token=+h2aAEHZd128gLJVT6xo1Q==; msToken=QW6OjzdfFs_09gKvTM7zmYTgVRW2rtI6Mp-VYXs2Xd1G45p7YYN_zb2ojsvSTc-Eylw777NvCE0kH_xlwKoYhTAfuajpyemMNj0="}}], "thumbnails": [], "description": "@Mardinli\ud83c\uddf9\ud83c\uddf7 adl\u0131 kullan\u0131c\u0131ya #cevap ", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.50 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en-us,en;q=0.5", "Sec-Fetch-Mode": "navigate", "Referer": "https://www.tiktok.com/@nasrulah47/video/7173252680914062598", "Cookie": "ttwid=1%7CWqPIz8BhtGjOZV30ZnOXwuTfeJrjjzcT9uwhB2bgntk%7C1670175537%7C1704ac216c716b7a2eb26d22b215c201911ba7c5651772c03cccd60382ac48c0; tt_csrf_token=0GHMSACn-sJlQl8OUSFXmTlX9L3cX68Xi2Y0; tt_chain_token=+h2aAEHZd128gLJVT6xo1Q==; msToken=QW6OjzdfFs_09gKvTM7zmYTgVRW2rtI6Mp-VYXs2Xd1G45p7YYN_zb2ojsvSTc-Eylw777NvCE0kH_xlwKoYhTAfuajpyemMNj0="}, "webpage_url": "https://www.tiktok.com/@nasrulah47/video/7173252680914062598", "original_url": "https://www.tiktok.com/@nasrulah47/video/7173252680914062598", "webpage_url_basename": "7173252680914062598", "webpage_url_domain": "tiktok.com", "extractor": "TikTok", "extractor_key": "TikTok", "playlist": null, "playlist_index": null, "display_id": "7173252680914062598", "fulltitle": "@Mardinli\ud83c\uddf9\ud83c\uddf7 adl\u0131 kullan\u0131c\u0131ya #cevap ", "duration_string": "1:04", "upload_date": "20221204", "requested_subtitles": null, "_has_drm": null, "url": "https://v16-webapp.tiktok.com/1226b672c9378d20b0b300e40a6b5545/638d2fd1/video/tos/useast2a/tos-useast2a-pve-0068/oolWXzGICEfkgPDNCoNMnkx2gCI3xAzUhUdAQO/?a=1988&ch=0&cr=0&dr=0&lr=tiktok_m&cd=0%7C0%7C1%7C0&cv=1&br=1108&bt=554&cs=0&ds=3&ft=IecA0onfD12Nvo2M8ZIxRyhjWlJG-UjNSsopi9&mime_type=video_mp4&qs=0&rc=OWRmNGQ5ZzRlaDY0OmhlOUBpMzhxPGc6ZjQ7aDMzNzczM0A0XzYtLTMuXy4xLV4zLWI0YSMuY29fcjRnMzNgLS1kMTZzcw%3D%3D&l=202212041738570101890730451005A411&btag=80000", "ext": "mp4", "width": 576, "height": 1018, "protocol": "https", "video_ext": "mp4", "audio_ext": "none", "format_id": "0", "format": "0 - 576x1018", "resolution": "576x1018", "dynamic_range": "SDR", "epoch": 1670175537, "_filename": "@Mardinli\ud83c\uddf9\ud83c\uddf7 adl\u0131 kullan\u0131c\u0131ya #cevap  [7173252680914062598].mp4", "filename": "@Mardinli\ud83c\uddf9\ud83c\uddf7 adl\u0131 kullan\u0131c\u0131ya #cevap  [7173252680914062598].mp4", "urls": "https://v16-webapp.tiktok.com/1226b672c9378d20b0b300e40a6b5545/638d2fd1/video/tos/useast2a/tos-useast2a-pve-0068/oolWXzGICEfkgPDNCoNMnkx2gCI3xAzUhUdAQO/?a=1988&ch=0&cr=0&dr=0&lr=tiktok_m&cd=0%7C0%7C1%7C0&cv=1&br=1108&bt=554&cs=0&ds=3&ft=IecA0onfD12Nvo2M8ZIxRyhjWlJG-UjNSsopi9&mime_type=video_mp4&qs=0&rc=OWRmNGQ5ZzRlaDY0OmhlOUBpMzhxPGc6ZjQ7aDMzNzczM0A0XzYtLTMuXy4xLV4zLWI0YSMuY29fcjRnMzNgLS1kMTZzcw%3D%3D&l=202212041738570101890730451005A411&btag=80000", "_type": "video", "_version": {"version": "2022.11.11", "current_git_head": null, "release_git_head": "8b64402", "repository": "yt-dlp/yt-dlp"}}
```

**Comment by bashonly** [comment] 2022-12-04 17:58
This has been fixed in master, but there has not been a new release yet. If you don't want to wait, you can [install the master branch with PIP](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip) or try the current release of the [unofficial daily builds](https://github.com/ytdl-patched/yt-dlp)

Closing as duplicate of #5688

**Closed by bashonly** 2022-12-04 17:58 UTC
Labels: duplicate, site-bug, site:tiktok
