### ISSUE TITLE
[Broken] CBS The Late Show with Stephen Colbert

### ISSUE THREAD

**Issue by mindbomb** [yt-dlp/yt-dlp#1056] opened 2021-09-22 12:49 UTC
## Checklist

- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running yt-dlp version **2021.09.02**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\WINDOWS\system32>yt-dlp https://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/dnGYFmhQWwoH_NjFw4pNlgFvJIn_dm4d/the-late-show-9-21-21-bob-woodward-robert-costa-leon-bridges-/ -v
[debug] User config file: C:\Users\xstre\AppData\Roaming\yt-dlp\config.txt
[debug] User config: ['--output', 'F:\\Chrome Downloads\\%(title)s.%(ext)s', '--format-sort', '+vcodec:h264', '--ffmpeg-location', 'C:\\Program Files\\yt-dlp']
[debug] Command-line config: ['https://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/dnGYFmhQWwoH_NjFw4pNlgFvJIn_dm4d/the-late-show-9-21-21-bob-woodward-robert-costa-leon-bridges-/', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 3.0.1, ffprobe 3.0.1
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [CBS] Extracting URL: https://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/dnGYFmhQWwoH_NjFw4pNlgFvJIn_dm4d/the-late-show-9-21-21-bob-woodward-robert-costa-leon-bridges-/
[CBS] dnGYFmhQWwoH_NjFw4pNlgFvJIn_dm4d: Downloading XML
[CBS] dnGYFmhQWwoH_NjFw4pNlgFvJIn_dm4d: Downloading JSON metadata
ERROR: [CBS] dnGYFmhQWwoH_NjFw4pNlgFvJIn_dm4d: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1214, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1252, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1298, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2177, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 849, in raise_no_formats
yt_dlp.utils.ExtractorError: [CBS] dnGYFmhQWwoH_NjFw4pNlgFvJIn_dm4d: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

This series was working until very recently.

**Comment by ParadoxGBB** [comment] 2021-09-22 23:14
+1, hit this today as well.

**Comment by pukkandan** [comment] 2021-09-23 23:43
Looks like this video has DRM. Whether just some specific shows has DRM or they add non-DRM formats just for older episodes, I do not know

**Comment by pukkandan** [comment] 2021-09-23 23:48
Great, this issue is a duplicate of https://github.com/yt-dlp/yt-dlp/issues/240 😠

> [x] I've searched the bugtracker for similar issues including closed ones

Please do ACTUALLY SEARCH before ticking this

**Closed by pukkandan** 2021-09-23 23:48 UTC
Labels: DRM
