### ISSUE TITLE
Stripchat URLS not downloading?

### ISSUE THREAD

**Issue by pro-ject143** [yt-dlp/yt-dlp#4808] opened 2022-09-01 10:29 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have been experiencing this problem for seven days. Every webpage I try to download I get a similar message.

ERROR: [Stripchat] Anastasiya_korol: Unable to download webpage: <urlopen error [Errno 11001] getaddrinfo failed> (caused by URLError(gaierror(11001, 'getaddrinfo failed')))

Is there an issue that can be fixed?

I am running yt-dlp version 2022.08.19 

Thank you

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Lesmiscore** [comment] 2022-09-01 10:34
![image](https://user-images.githubusercontent.com/10355528/187894147-a21dfb95-2256-4d2f-be22-fd95a34ae726.png)

**Comment by Lesmiscore** [comment] 2022-09-01 10:38
Duplicate of #4794

**Closed by Lesmiscore** 2022-09-01 10:38 UTC
Labels: incomplete, NSFW, site-bug
