### ISSUE TITLE
Error downloading from Paramount Plus.

### ISSUE THREAD

**Issue by sandrosg2018** [yt-dlp/yt-dlp#1965] opened 2021-12-11 18:08 UTC
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I wanted to know what command to download Paramount Plus?

**Comment by Ashish0804** [comment] 2021-12-11 18:43
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1963

**Closed by Ashish0804** 2021-12-11 18:43 UTC
Labels: question
