### ISSUE TITLE
MTV extractor status

### ISSUE THREAD

**Issue by notsolowki** [yt-dlp/yt-dlp#5282] opened 2022-10-19 01:49 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is the MTV extractor still broken. i cant figure out if there is a fix yet or a workaround. i get error on almost all videos from mtv. i see there has been a lot of development i didnt know if there has been any progress for the MTV site?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment] 2022-10-19 07:10
> * [x]  I'm asking a question and **not** reporting a bug or requesting a feature

Do not abuse the "Question" template to post incomplete issues/feature requests.

Possible duplicate of https://github.com/yt-dlp/yt-dlp/issues/5249

**Closed by pukkandan** 2022-10-19 07:10 UTC
Labels: question

**Comment by notsolowki** [comment] 2022-10-19 07:22
actually i dont think these two questions are duplicates.
