### ISSUE TITLE
Twitter: "No video could be found in this tweet" even though tweet has video when unauthenticated

### ISSUE THREAD

**Issue by HexCodeFFF** [yt-dlp/yt-dlp#7920] opened 2023-08-21 04:20 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

This tweet: https://twitter.com/yahiamice/status/1692877756349005977

when I try to download unauthenticated, I get the error "no video could be found in this tweet". As of writing, this is a public tweet with a video. The same error occurs on any public tweet with a video. When I use the `--cookies-from-browser` option it works fine.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\Users\minec> yt-dlp -vU "https://twitter.com/yahiamice/status/1692877756349005977"
[debug] Command-line config: ['-vU', 'https://twitter.com/yahiamice/status/1692877756349005977']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[twitter] Extracting URL: https://twitter.com/yahiamice/status/1692877756349005977
[twitter] 1692877756349005977: Downloading syndication JSON
[twitter] Some metadata is missing without authentication. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (twitter) to provide account credentials
ERROR: [twitter] 1692877756349005977: No video could be found in this tweet
  File "C:\Users\minec\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\minec\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\twitter.py", line 1276, in _real_extract
    self.raise_no_formats('No video could be found in this tweet', expected=True)
  File "C:\Users\minec\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1188, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by bashonly** [comment] 2023-08-21 05:13
This has been [fixed in master](https://github.com/yt-dlp/yt-dlp/commit/92315c03774cfabb3a921884326beb4b981f786b)

If you don't want to wait for next stable release, [install the master branch](https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-master)

Duplicate of #7850

**Closed by bashonly** 2023-08-21 05:13 UTC
Labels: site-bug, triage

**Comment by Fritz66** [comment] 2023-09-12 10:33
**You can download Twitter videos if you change the URL to a Nitter instance.**

Let's say you want to download the video https://**twitter.com**/buitengebieden/status/1693272930224845107 , here is how it works: Just change the URL to https:/**/nitter.nicfab.eu**/buitengebieden/status/1693272930224845107 or https://**nitter.cz**/buitengebieden/status/1693272930224845107 .
There are maybe more instances, but for now I'm fine with these two.

It would be great if yt-dlp would automatically change the hostname internally.. Possible?

**Comment by bashonly** [comment] 2023-09-12 10:37
> It would be great if yt-dlp would automatically change the hostname internally.. Possible?

It's not necessary. The Twitter extractor has been fixed, as noted above. `yt-dlp --update-to nightly` is another way to get the patch
