### ISSUE TITLE
[Odysee/LBRY] CERTIFICATE VERIFY FAILED

### ISSUE THREAD

**Issue by JaxonPlays** [yt-dlp/yt-dlp#2567] opened 2022-01-31 23:10 UTC
### Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Domain odysee.com does not download JSON, therefore, cannot download requested files.

### Verbose log

```shell
[debug] Command-line config: ['--download-archive', 'C:\\Users\\oraba\\Documents\\dl\\archive.txt', '-i', '-R', '100', '--continue', '--wait-for-video', '100', '--yes-overwrites', '--no-part', '--clean-infojson', '--live-from-start', '--no-warnings', '--no-write-playlist-metafiles', '--convert-thumbnails', 'jpg', '--embed-thumbnail', '--write-thumbnail', '--write-description', '--write-info-json', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]', '-o', '%(uploader)s (%(uploader_id)s)\\%(upload_date)s - %(title)s - %(id)s.%(ext)s', '-vU', 'https://odysee.com/@TheQuartering:1/instant-karma-pokimane-makes-an-oopsie:7']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg git-2020-03-27-e34157f, ffprobe git-2020-03-27-e34157f
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file 'C:\\Users\\oraba\\Documents\\dl\\archive.txt'
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [lbry] Extracting URL: https://odysee.com/@TheQuartering:1/instant-karma-pokimane-makes-an-oopsie:7
[lbry] @TheQuartering#1/instant-karma-pokimane-makes-an-oopsie#7: Downloading stream JSON metadata
ERROR: [lbry] @TheQuartering:1/instant-karma-pokimane-makes-an-oopsie:7: Unable to download JSON metadata: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)'))) (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))
  File "yt_dlp\extractor\common.py", line 730, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3526, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1506, in https_open
  File "urllib\request.py", line 1357, in do_open
```

**Comment by pukkandan** [comment] 2022-01-31 23:21
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1339

**Closed by pukkandan** 2022-01-31 23:21 UTC
Labels: bug, triage
