### ISSUE TITLE
Unable to download any tiktok videos

### ISSUE THREAD

**Issue by Ternoc** [yt-dlp/yt-dlp#2282] opened 2022-01-09 21:27 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Description

I tried to download several tiktok videos and it returned an error.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://www.tiktok.com/@nayhxo/video/7039385885250538758']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.9.9 (CPython 64bit) - macOS-12.2-arm64-arm-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@nayhxo/video/7039385885250538758
[TikTok] 7039385885250538758: Downloading video details
WARNING: [TikTok] 7039385885250538758: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; Retrying with webpage
[TikTok] 7039385885250538758: Downloading webpage
[TikTok] 7039385885250538758: Downloading video webpage
ERROR: [TikTok] 7039385885250538758: Unable to extract json_string; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/opt/homebrew/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.9/site-packages/yt_dlp/extractor/tiktok.py", line 368, in _real_extract
    json_string = self._search_regex(
  File "/opt/homebrew/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1173, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by MinePlayersPE** [comment] 2022-01-09 21:49
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2133

**Closed** 2022-01-09 21:51 UTC
Labels: duplicate, site:tiktok
