### ISSUE TITLE
Enable downloading of specific segments of a video (ie: 0:01-0:30 seconds, etc)

### ISSUE THREAD

**Issue by forrie** [yt-dlp/yt-dlp#2548] opened 2022-01-30 19:41 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Would it be possible to provide an option to yt-dlp where I can select only a certain segment of video to download (or retain/trim locally, otherwise)?   For example, a video of 3 mins -- I want just a segment at timeline 0:00 through 0:25, and perhaps another at 1:03 through 1:25, saved as individual clips (or segments).

**Comment by pukkandan** [comment] 2022-01-30 19:43
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/52
Also see https://github.com/yt-dlp/yt-dlp/issues/686#issuecomment-904191812

**Closed by pukkandan** 2022-01-30 19:43 UTC
Labels: enhancement, triage
