### ISSUE TITLE
Discovery+ not working

### ISSUE THREAD

**Issue by JannaJive** [yt-dlp/yt-dlp#4964] opened 2022-09-18 20:31 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

have used yt-dlp on discovery+ for awhile, but for 3 weeks it hasn't worked at all, i have subscription and can watch the videos in any browser jus won't work in yt-dlp

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\janna>C:\Users\janna\Downloads\yt-dlp\yt-dlp.exe --verbose --cookies C:\Users\janna\Downloads\yt-dlp\discoveryplus.com_cookies.txt -f "bestvideo[height<=480]+bestaudio/best[height<=480]" "https://www.discoveryplus.com/video/on-the-case-with-paula-zahn/jennys-story"
[debug] Command-line config: ['--verbose', '--cookies', 'C:\\Users\\janna\\Downloads\\yt-dlp\\discoveryplus.com_cookies.txt', '-f', 'bestvideo[height<=480]+bestaudio/best[height<=480]', 'https://www.discoveryplus.com/video/on-the-case-with-paula-zahn/jennys-story']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-108101-gf1b35fc8f0-20220911 (setts), ffprobe N-108101-gf1b35fc8f0-20220911
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] [DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/video/on-the-case-with-paula-zahn/jennys-story
[debug] Using fake IP 6.159.20.158 (US) as X-Forwarded-For
[DiscoveryPlus] on-the-case-with-paula-zahn/jennys-story: Downloading JSON metadata
[DiscoveryPlus] 4923613: Downloading JSON metadata
[DiscoveryPlus] on-the-case-with-paula-zahn/jennys-story: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 4923613: Downloading 1 format(s): dash-video=247000+dash-audio_eng=125000
[debug] Invoking dashsegments downloader on "https://dplus-northamerica.media-edge.prod-vod.h264.io/286ac188-ebc4-4611-867f-1f7c4c0370ca/dash_clear_fmp4/edge-cache-token=Expires=1663619014&KeyName=media-edge-key-prod-northamerica-200d417&Signature=KNS8ZiOpZJiOW2RSq9SMex0fE6GGtdIv5Yzy3DXO6OIFvLqHVhlw5CMiriRuLatz8PYeZUW13brjozdZ9FJtAg/master.mpd"
[dashsegments] Total fragments: 636
[download] Destination: Jenny's Story [4923613].fdash-video=247000.mp4
[debug] File locking is not supported. Proceeding without locking
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
  File "yt_dlp\__main__.py", line 18, in <module>
  File "yt_dlp\__init__.py", line 962, in main
  File "yt_dlp\__init__.py", line 954, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3293, in download
  File "yt_dlp\YoutubeDL.py", line 3268, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1448, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1556, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1614, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2712, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3153, in process_info
  File "yt_dlp\YoutubeDL.py", line 2895, in dl
  File "yt_dlp\downloader\common.py", line 443, in download
  File "yt_dlp\downloader\dash.py", line 54, in real_download
  File "yt_dlp\downloader\fragment.py", line 373, in download_and_append_fragments_multiple
  File "yt_dlp\downloader\fragment.py", line 517, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 463, in download_fragment
  File "yt_dlp\utils.py", line 5794, in __iter__
  File "yt_dlp\downloader\fragment.py", line 460, in error_callback
  File "yt_dlp\downloader\common.py", line 388, in report_retry
  File "yt_dlp\utils.py", line 5801, in report_retry
  File "yt_dlp\downloader\common.py", line 391, in <lambda>
  File "yt_dlp\YoutubeDL.py", line 994, in report_error
  File "yt_dlp\YoutubeDL.py", line 923, in trouble

ERROR: fragment 1 not found, unable to continue
  File "yt_dlp\__main__.py", line 18, in <module>
  File "yt_dlp\__init__.py", line 962, in main
  File "yt_dlp\__init__.py", line 954, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3293, in download
  File "yt_dlp\YoutubeDL.py", line 3268, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1448, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1556, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1614, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2712, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3153, in process_info
  File "yt_dlp\YoutubeDL.py", line 2895, in dl
  File "yt_dlp\downloader\common.py", line 443, in download
  File "yt_dlp\downloader\dash.py", line 54, in real_download
  File "yt_dlp\downloader\fragment.py", line 373, in download_and_append_fragments_multiple
  File "yt_dlp\downloader\fragment.py", line 518, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 482, in append_fragment
  File "yt_dlp\YoutubeDL.py", line 994, in report_error
  File "yt_dlp\YoutubeDL.py", line 923, in trouble


[debug] Invoking dashsegments downloader on "https://dplus-northamerica.media-edge.prod-vod.h264.io/286ac188-ebc4-4611-867f-1f7c4c0370ca/dash_clear_fmp4/edge-cache-token=Expires=1663619014&KeyName=media-edge-key-prod-northamerica-200d417&Signature=KNS8ZiOpZJiOW2RSq9SMex0fE6GGtdIv5Yzy3DXO6OIFvLqHVhlw5CMiriRuLatz8PYeZUW13brjozdZ9FJtAg/master.mpd"
[dashsegments] Total fragments: 638
[download] Destination: Jenny's Story [4923613].fdash-audio_eng=125000.m4a
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
  File "yt_dlp\__main__.py", line 18, in <module>
  File "yt_dlp\__init__.py", line 962, in main
  File "yt_dlp\__init__.py", line 954, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3293, in download
  File "yt_dlp\YoutubeDL.py", line 3268, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1448, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1556, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1614, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2712, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3153, in process_info
  File "yt_dlp\YoutubeDL.py", line 2895, in dl
  File "yt_dlp\downloader\common.py", line 443, in download
  File "yt_dlp\downloader\dash.py", line 54, in real_download
  File "yt_dlp\downloader\fragment.py", line 373, in download_and_append_fragments_multiple
  File "yt_dlp\downloader\fragment.py", line 517, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 463, in download_fragment
  File "yt_dlp\utils.py", line 5794, in __iter__
  File "yt_dlp\downloader\fragment.py", line 460, in error_callback
  File "yt_dlp\downloader\common.py", line 388, in report_retry
  File "yt_dlp\utils.py", line 5801, in report_retry
  File "yt_dlp\downloader\common.py", line 391, in <lambda>
  File "yt_dlp\YoutubeDL.py", line 994, in report_error
  File "yt_dlp\YoutubeDL.py", line 923, in trouble

ERROR: fragment 1 not found, unable to continue
  File "yt_dlp\__main__.py", line 18, in <module>
  File "yt_dlp\__init__.py", line 962, in main
  File "yt_dlp\__init__.py", line 954, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3293, in download
  File "yt_dlp\YoutubeDL.py", line 3268, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1448, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1556, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1614, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2712, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3153, in process_info
  File "yt_dlp\YoutubeDL.py", line 2895, in dl
  File "yt_dlp\downloader\common.py", line 443, in download
  File "yt_dlp\downloader\dash.py", line 54, in real_download
  File "yt_dlp\downloader\fragment.py", line 373, in download_and_append_fragments_multiple
  File "yt_dlp\downloader\fragment.py", line 518, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 482, in append_fragment
  File "yt_dlp\YoutubeDL.py", line 994, in report_error
  File "yt_dlp\YoutubeDL.py", line 923, in trouble
```

**Comment by elyse0** [comment] 2022-09-18 23:02
It has been fixed in https://github.com/yt-dlp/yt-dlp/commit/7657ec7ed6318dd66dd72cc100ba7bc5b911366e, try using master or wait for the next release

Duplicate of https://github.com/yt-dlp/yt-dlp/issues/4187

**Comment by JannaJive** [comment] 2022-09-18 23:54
i'm so grateful for your response but this is all so new to my senior citizen brain, i  just don't know what to do next to get my yt-dlp up n running again

**Comment by elyse0** [comment] 2022-09-19 00:42
Well, in the meantime you can download an **unofficial** daily build from https://github.com/ytdl-patched/yt-dlp/releases

That should fix this error, but please do not open issues using that version.

**Closed** 2022-09-19 04:39 UTC
Labels: duplicate, site-bug

**Comment by JannaJive** [comment] 2022-09-19 06:01
omg that worked a charm tytyty so very much!!!

**Comment by MotleyC** [comment] 2022-09-19 20:17
Does this fix the issue of not pulling the subtitles also?

**Comment by Mr-Jake** [comment] 2022-09-19 22:59
> Does this fix the issue of not pulling the subtitles also?

Subtitles can be downloaded in dash mp4 format only. Be aware that this subtitle format is not supported by ffmpeg. So they can't be embedded or converted to another format using yt-dlp or ffmpeg.

However, using mp4box
```
mp4box -raw 1 subtitle.en.mp4
```
The output is subtitle.en.vtt

**Comment by MotleyC** [comment] 2022-09-19 23:14
I will try that ty
