### ISSUE TITLE
unable to extract initial player response, unable to extract yt initial data

### ISSUE THREAD

**Issue by ShalokShalom** [yt-dlp/yt-dlp#7634] opened 2023-07-18 17:04 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Austria

### Provide a description that is worded well enough to be understood

Hi there. I got told by the output, to report that. 
The video downloaded correctly, so I dont have any issue with it. 
As you can see, there are multiple errors: 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--extract-audio', '--audio-format', 'mp3', '--verbose', 'https://www.youtube.com/watch?v=NlQLrnoAons']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.4.3-zen1-2-zen-x86_64-with-glibc2.37 (OpenSSL 3.1.1 30 May 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: certifi-2023.05.07, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=NlQLrnoAons
[youtube] NlQLrnoAons: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] NlQLrnoAons: Downloading ios player API JSON
[youtube] NlQLrnoAons: Downloading android player API JSON
[youtube] NlQLrnoAons: Downloading iframe API JS
[youtube] NlQLrnoAons: Downloading player 4cc5d082
[youtube] NlQLrnoAons: Downloading web player API JSON
[debug] Saving youtube-nsig.4cc5d082 to cache
[debug] [youtube] Decrypted nsig cLMOTBikNlL1CgGlBh => yMgy9Omebe2Uzw
[youtube] NlQLrnoAons: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] NlQLrnoAons: Downloading initial data API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] NlQLrnoAons: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr4---sn-2gb7snez.googlevideo.com/videoplayback?expire=1689720900&ei=5MO2ZIvHHYO6WeHMqOAF&ip=2a02%3A1748%3Add5e%3A7f60%3Ad681%3A4baf%3Afb0%3Af275&id=o-AFN0bM-s-QTzBNg4rzuXTIDiJZRr-9ol6eMYH9lOiHsK&itag=251&source=youtube&requiressl=yes&mh=y-&mm=31%2C26&mn=sn-2gb7snez%2Csn-c0q7lnsl&ms=au%2Conr&mv=m&mvi=4&pl=53&pcm2=no&initcwndbps=1520000&spc=Ul2SqzGLKvYKrOdTq11vT1wJmLKThns&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=12816505&dur=908.381&lmt=1563296219976207&mt=1689698948&fvip=3&keepalive=yes&fexp=24007246&c=ANDROID&txp=2301222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALcpwZY3HiakoZO71CsD_EIcsjLav3cM2juZ7qwYwJRIAiEAqO7T5FaMFDwQliVBWJYpIFrIuLntKIHreXx_KA9Oj5k%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgBPh7MBmczK61N73SPB3UUdLEpq4r40emLW1Q-y0QBKcCIQD1DjBbHoVqzT9Cgs39UAgu5lFn5TpCND9VQvIT550DCw%3D%3D"
[download] Destination: Attika - Cele mai tari hituri tiganesti unguresti [NlQLrnoAons].webm
[download] 100% of   12.22MiB in 00:00:02 at 4.44MiB/s
[debug] ffmpeg command line: ffprobe -show_streams 'file:Attika - Cele mai tari hituri tiganesti unguresti [NlQLrnoAons].webm'
[ExtractAudio] Destination: Attika - Cele mai tari hituri tiganesti unguresti [NlQLrnoAons].mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Attika - Cele mai tari hituri tiganesti unguresti [NlQLrnoAons].webm' -vn -acodec libmp3lame -q:a 5.0 -movflags +faststart 'file:Attika - Cele mai tari hituri tiganesti unguresti [NlQLrnoAons].mp3'
Deleting original file Attika - Cele mai tari hituri tiganesti unguresti [NlQLrnoAons].webm (pass -k to keep)
```

**Comment by gamer191** [comment] 2023-07-18 21:22
Duplicate of #7594. If you want to help fix this, please see https://github.com/yt-dlp/yt-dlp/issues/7594#issuecomment-1636870165

**Closed** 2023-07-18 21:22 UTC
Labels: site-bug, triage
