### ISSUE TITLE
can no longer download twitter videos

### ISSUE THREAD

**Issue by abetomas** [yt-dlp/yt-dlp#7907] opened 2023-08-19 20:51 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I used to be able to download twitter videos with no authentication.  I can no longer do this and I get errors below.  The twitter url (https://twitter.com/TheFigen_/status/1692892924336382408) can be viewed without any logins.

Thanks for your help.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

~$ yt-dlp -vU  https://twitter.com/TheFigen_/status/1692892924336382408                                    
[debug] Command-line config: ['-vU', 'https://twitter.com/TheFigen_/status/1692892924336382408']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-13.5-arm64-arm-64bit (OpenSSL 3.1.1 30 May 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[twitter] Extracting URL: https://twitter.com/TheFigen_/status/1692892924336382408
[twitter] 1692892924336382408: Downloading syndication JSON
[twitter] Some metadata is missing without authentication. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (twitter) to provide account credentials
ERROR: [twitter] 1692892924336382408: No video could be found in this tweet
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/extractor/twitter.py", line 1276, in _real_extract
    self.raise_no_formats('No video could be found in this tweet', expected=True)
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6_1/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1188, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

~$

**Comment by abetomas** [comment] 2023-08-19 21:13
I also tried to specify --username {user} --password {pass} -2 {2FA token} and I got another message
----
$ yt-dlp --username xxx --password xxx -2 nnn https://twitter.com/TheFigen_/status/1692892924336382408
[twitter] Downloading login page
[twitter] Downloading flow token
[twitter] Submitting JS instrumentation response
[twitter] Submitting username
[twitter] Submitting password
ERROR: [twitter] 1692892924336382408: Unrecognized subtask ID "DenyLoginSubtask"; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by bashonly** [comment] 2023-08-20 04:30
> I used to be able to download twitter videos with no authentication. I can no longer do this and I get errors below. 

This has been [fixed in master](https://github.com/yt-dlp/yt-dlp/commit/92315c03774cfabb3a921884326beb4b981f786b)

If you don't want to wait for next stable release, [install the master branch](https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-master)

> I also tried to specify --username {user} --password {pass} -2 {2FA token} and I got another message
> Unrecognized subtask ID "DenyLoginSubtask"

That means Twitter has deemed your login attempt as suspicious. Not sure how exactly they decide this, but I can't reproduce it with my account. [Pass cookies](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp) instead

Closing as duplicate of #7850

**Closed by bashonly** 2023-08-20 04:30 UTC
Labels: question
