### ISSUE TITLE
[Youtube] VR180 videos not downloading in stereo

### ISSUE THREAD

**Issue by ANewDawn** [yt-dlp/yt-dlp#69] opened 2021-02-10 12:34 UTC
When downloading vr180 videos it only downloads in mono and not stereo side-by-side

It seems when viewing the videos inside android app or YouTube vr app they display correctly so could be user agent issue.

More info on this here:

https://github.com/ytdl-org/youtube-dl/issues/16647

 https://github.com/ytdl-org/youtube-dl/issues/22690

**Comment by pukkandan** [comment] 2021-02-19 13:06
I am unable to find a reliable way to do this. So I'm marking this as `help-needed`

**Comment by makuchan** [comment] 2021-05-14 21:03
I think the left and right images are not SBS but multi-stream used for multiple angles.

**Comment by coletdjnz** [comment] 2021-08-15 07:48
> It seems when viewing the videos inside android app or YouTube vr app they display correctly so could be user agent issue.

I think this is working now, since we support the android client among others. In my tests when using the android client I can get the stereo version to download.

Notice that the resolution changes for the formats between clients:

**WEB:**
```
yt-dlp "https://www.youtube.com/watch?v=u-6Hu6xpR68" -vF --extractor-args youtube:player_client=web
[debug] Command-line config: ['https://www.youtube.com/watch?v=u-6Hu6xpR68', '-vF', '--extractor-args', 'youtube:player_client=web']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.08.10 
[debug] Python version 3.9.6 (CPython 64bit) - Linux-5.13.8-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: keyring, mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=u-6Hu6xpR68
[youtube] u-6Hu6xpR68: Downloading webpage
[debug] Sort order given by extractor: quality, height, fps, source
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, height, fps, source, res, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[info] Available formats for u-6Hu6xpR68:
ID  EXT  RESOLUTION FPS |  FILESIZE    TBR  PROTO | VCODEC        VBR  ACODEC     ABR  ASR    MORE INFO
--- ---- ---------- --- - ---------- ------ ----- - ----------- ------ --------- ---- ------- -----------------------------------
249 webm audio only     |  905.99KiB   46k  https |                    opus       46k 48000Hz low (maybe throttled), webm_dash
250 webm audio only     |  1.17MiB     61k  https |                    opus       61k 48000Hz low (maybe throttled), webm_dash
140 m4a  audio only     |  2.47MiB    129k  https |                    mp4a.40.2 129k 44100Hz medium (maybe throttled), m4a_dash
251 webm audio only     |  2.33MiB    121k  https |                    opus      121k 48000Hz medium (maybe throttled), webm_dash
160 mp4  256x144    30  |  988.77KiB   50k  https | avc1.4d400c   50k                         144s (maybe throttled), mp4_dash
278 webm 256x144    30  |  1.47MiB     77k  https | vp9           77k                         144s (maybe throttled), webm_dash
133 mp4  426x240    30  |  2.11MiB    110k  https | avc1.4d4015  110k                         240s (maybe throttled), mp4_dash
242 webm 426x240    30  |  2.79MiB    146k  https | vp9          146k                         240s (maybe throttled), webm_dash
18  mp4  640x360    30  |  12.67MiB   663k  https | avc1.42001E  663k  mp4a.40.2   0k 44100Hz 360p
134 mp4  640x360    30  |  4.05MiB    212k  https | avc1.4d401e  212k                         360s (maybe throttled), mp4_dash
243 webm 640x360    30  |  6.13MiB    321k  https | vp9          321k                         360s (maybe throttled), webm_dash
135 mp4  854x480    30  |  6.72MiB    352k  https | avc1.4d401f  352k                         480s (maybe throttled), mp4_dash
244 webm 854x480    30  |  11.26MiB   589k  https | vp9          589k                         480s (maybe throttled), webm_dash
22  mp4  1280x720   30  |            1090k  https | avc1.64001F 1090k  mp4a.40.2   0k 44100Hz 720p
136 mp4  1280x720   30  |  11.59MiB   607k  https | avc1.4d401f  607k                         720s (maybe throttled), mp4_dash
247 webm 1280x720   30  |  22.65MiB  1187k  https | vp9         1187k                         720s (maybe throttled), webm_dash
137 mp4  1920x1080  30  |  42.75MiB  2240k  https | avc1.640028 2240k                         1080s (maybe throttled), mp4_dash
248 webm 1920x1080  30  |  40.36MiB  2115k  https | vp9         2115k                         1080s (maybe throttled), webm_dash
271 webm 2560x1440  30  |  124.31MiB 6515k  https | vp9         6515k                         1440s (maybe throttled), webm_dash
313 webm 2880x2160  30  |  208.32MiB 10918k https | vp9         10918k                        2160s (maybe throttled), webm_dash
272 webm 2880x2880  30  |  99.83MiB  5231k  https | vp9         5231k                         2880s (maybe throttled), webm_dash
```
**ANDROID:** 
```
$ yt-dlp "https://www.youtube.com/watch?v=u-6Hu6xpR68" -vF --extractor-args youtube:player_client=android
[debug] Command-line config: ['https://www.youtube.com/watch?v=u-6Hu6xpR68', '-vF', '--extractor-args', 'youtube:player_client=android']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.08.10 
[debug] Python version 3.9.6 (CPython 64bit) - Linux-5.13.8-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: keyring, mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=u-6Hu6xpR68
[youtube] u-6Hu6xpR68: Downloading webpage
[youtube] u-6Hu6xpR68: Downloading android player API JSON
[debug] Sort order given by extractor: quality, height, fps, source
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, height, fps, source, res, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[info] Available formats for u-6Hu6xpR68:
ID  EXT  RESOLUTION FPS |  FILESIZE    TBR  PROTO | VCODEC        VBR  ACODEC     ABR  ASR    MORE INFO
--- ---- ---------- --- - ---------- ------ ----- - ----------- ------ --------- ---- ------- -----------------
139 m4a  audio only     |  954.56KiB   48k  https |                    mp4a.40.5  48k 22050Hz low, m4a_dash
249 webm audio only     |  905.99KiB   46k  https |                    opus       46k 48000Hz low, webm_dash
250 webm audio only     |  1.17MiB     61k  https |                    opus       61k 48000Hz low, webm_dash
140 m4a  audio only     |  2.47MiB    129k  https |                    mp4a.40.2 129k 44100Hz medium, m4a_dash
251 webm audio only     |  2.33MiB    121k  https |                    opus      121k 48000Hz medium, webm_dash
17  3gp  176x144    7   |  1.46MiB     76k  https | mp4v.20.3     76k  mp4a.40.2   0k 22050Hz 144p
160 mp4  256x144    30  |  1.04MiB     54k  https | avc1.4d400c   54k                         144s, mp4_dash
278 webm 256x144    30  |  1.46MiB     76k  https | vp9           76k                         144s, webm_dash
133 mp4  426x240    30  |  2.30MiB    120k  https | avc1.4d4015  120k                         240s, mp4_dash
242 webm 426x240    30  |  2.86MiB    149k  https | vp9          149k                         240s, webm_dash
134 mp4  640x360    30  |  4.57MiB    239k  https | avc1.4d401e  239k                         360s, mp4_dash
18  mp4  640x360    30  |  12.67MiB   663k  https | avc1.42001E  663k  mp4a.40.2   0k 44100Hz 360p
243 webm 640x360    30  |  6.31MiB    330k  https | vp9          330k                         360s, webm_dash
135 mp4  854x480    30  |  7.69MiB    403k  https | avc1.4d401f  403k                         480s, mp4_dash
244 webm 854x480    30  |  11.77MiB   616k  https | vp9          616k                         480s, webm_dash
136 mp4  1280x720   30  |  13.02MiB   682k  https | avc1.4d401f  682k                         720s, mp4_dash
22  mp4  1280x720   30  |            1090k  https | avc1.64001F 1090k  mp4a.40.2   0k 44100Hz 720p
247 webm 1280x720   30  |  23.75MiB  1244k  https | vp9         1244k                         720s, webm_dash
137 mp4  1920x1080  30  |  48.17MiB  2524k  https | avc1.640028 2524k                         1080s, mp4_dash
248 webm 1920x1080  30  |  42.06MiB  2204k  https | vp9         2204k                         1080s, webm_dash
271 webm 2560x1440  30  |  131.95MiB 6915k  https | vp9         6915k                         1440s, webm_dash
313 webm 3840x2160  30  |  279.65MiB 14656k https | vp9         14656k                        2160s, webm_dash
272 webm 5760x2880  30  |  200.37MiB 10501k https | vp9         10501k                        2880s, webm_dash
```

@pukkandan is the fact that stereo/mono has the same format code a concern?

**Comment by pukkandan** [comment] 2021-08-15 08:28
> is the fact that stereo/mono has the same format code a concern? when using player_client=android,web (default), they are treated as the same.

technically, yes - and we should try to fix it if possible. But in practice, it should not be a big deal since it only affects VR videos, we get the "better" one by default, and we can get the other format by restricting clients

**Comment by pukkandan** [comment] 2021-08-15 08:34
Confirmed that the android client is in-fact fetching the SBS format

**Closed by pukkandan** 2021-08-15 08:34 UTC
Labels: help wanted, site-enhancement

**Comment by tufeixp** [comment] 2025-01-22 05:53
> Confirmed that the android client is in-fact fetching the SBS format

@pukkandan Why can't I find the serviceIntegrityDimensions.poToken string following these steps:https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide , anything changing?
