### ISSUE TITLE
download rate is slow than 2023.03.04

### ISSUE THREAD

**Issue by zshnb** [yt-dlp/yt-dlp#7417] opened 2023-06-25 14:32 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

i download with cmd `yt-dlp -f 'bestvideo[height<=?2160]/best' -o video-raw.video --no-warnings -N 50 --sleep-interval 1 https://www.youtube.com/watch?v=60pHJXUjaJ` takes 17min, but in same machine downgrade to 2023.03.04, it only takes 2min17s, how to fix this

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube] Extracting URL: https://www.youtube.com/watch?v=60pHJXUjaJY
[youtube] 60pHJXUjaJY: Downloading webpage
[youtube] 60pHJXUjaJY: Downloading ios player API JSON
[youtube] 60pHJXUjaJY: Downloading android player API JSON
[youtube] 60pHJXUjaJY: Downloading m3u8 information
[info] 60pHJXUjaJY: Downloading 1 format(s): 313
[download] Sleeping 1.00 seconds ...
[download] Destination: video-raw.video
[download] 100% of    9.53GiB in 00:17:36 at 9.24MiB/s

---
[youtube] Extracting URL: https://www.youtube.com/watch?v=60pHJXUjaJY
[youtube] 60pHJXUjaJY: Downloading webpage
[youtube] 60pHJXUjaJY: Downloading android player API JSON
[info] 60pHJXUjaJY: Downloading 1 format(s): 313
[download] Sleeping 1.00 seconds ...
[dashsegments] Total fragments: 977
[download] Destination: video-raw.video
[download] 100% of    9.53GiB in 00:02:18 at 70.24MiB/s
```

**Comment by gamer191** [comment] 2023-06-25 14:43
Duplicate of #7377
The solution is to pass `--extractor-args youtube:include_duplicate_formats -S proto:dash`

This is not enabled by default, because most users don't use `-N`, so enabling this by default would slow downloads down for most users

**Comment by pukkandan** [comment] 2023-06-25 14:46
With https://github.com/yt-dlp/yt-dlp/commit/58786a10f212bd63f9ad1d0b4d9e4d31c3b385e2, you can also pass `--extractor-args youtube:formats=dashy`

**Closed** 2023-06-25 14:46 UTC
Labels: duplicate, question

**Comment by zshnb** [comment] 2023-06-26 05:10
> Duplicate of #7377 The solution is to pass `--extractor-args youtube:include_duplicate_formats -S proto:dash`
> 
> This is not enabled by default, because most users don't use `-N`, so enabling this by default would slow downloads down for most users

this is work! thank you
