### ISSUE TITLE
Twitter/X media page

### ISSUE THREAD

**Issue by am517** [yt-dlp/yt-dlp#8522] opened 2023-11-05 03:26 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

US

### Example URLs

-Playlist: https://twitter.com/TrumpWarRoom/media

### Provide a description that is worded well enough to be understood

I would like to download all videos from the media tab of a twitter profile. There may be images posted here too, but I imagine they can be skipped. I only want the videos posted by the user (media tab), not just shared (main twitter stream).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
➜  ~ yt-dlp -vU https://twitter.com/TrumpWarRoom/media
[debug] Command-line config: ['-vU', 'https://twitter.com/TrumpWarRoom/media']
[debug] User config "/Users/me/.config/yt-dlp/config": ['--cookies-from-browser', 'firefox', '--cache-dir', '/Users/me/.config/youtube-dl/', '--user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:85.0) Gecko/20100101 Firefox/85.0', '--geo-bypass', '-i', '--no-mark-watched', '--no-warnings', '--retries', 'infinite', '--fragment-retries', 'infinite', '--download-archive', '/Users/me/.config/youtube-dl/downloads.txt', '-o', '/Volumes/Movies/Youtubes/%(uploader)s/%(playlist_title)s/%(upload_date)s - %(title)s.%(ext)s', '-f', 'bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a][abr<=192]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best', '--sub-format', 'srt', '--convert-subs', 'srt', '--write-subs', '--write-auto-subs', '--embed-subs', '--compat-options', 'no-keep-subs', '--sub-lang', 'en,ja', '--embed-thumbnail', '--parse-metadata', 'channel:%(meta_artist)s', '--parse-metadata', 'webpage_url:%(meta_comment)s', '--parse-metadata', 'upload_date:%(meta_date>%Y:%m:%d)s', '--embed-metadata', '--embed-chapters']
Extracting cookies from firefox
[debug] Extracting cookies from: "/Users/me/Library/Application Support/Firefox/Profiles/xy4v0sei.default-release-1574345941647/cookies.sqlite"
Extracted 740 cookies from firefox
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Compatibility options: no-keep-subs
[debug] Python 3.11.6 (CPython arm64 64bit) - macOS-14.1-arm64-arm-64bit (OpenSSL 3.1.4 24 Oct 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.43.2, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Loading archive file '/Users/me/.config/youtube-dl/downloads.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)
[generic] Extracting URL: https://twitter.com/TrumpWarRoom/media
[generic] media: Downloading webpage
[generic] media: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://twitter.com/TrumpWarRoom/media
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.13/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.13/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1702, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.13/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.13/libexec/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2575, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://twitter.com/TrumpWarRoom/media
```

**Comment by bashonly** [comment] 2023-11-05 03:44
Duplicate of #6450

If it's even possible to implement anymore, it's unlikely to be worth the effort considering new ownership and API instability

**Closed by bashonly** 2023-11-05 03:44 UTC
Labels: duplicate, site-enhancement, site:instagram

**Comment by am517** [comment] 2023-11-05 04:32
"considering new ownership and API instability"
That sounds like a personal issue, but ok.
