### ISSUE TITLE
Servustv extractor is not working anymore

### ISSUE THREAD

**Issue by ZWatcher** [yt-dlp/yt-dlp#3089] opened 2022-03-16 15:49 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Description

The extractor seems not working anymore on the servustv.com side anymore.

Example urls:
https://www.servustv.com/unterhaltung/v/aa-27thr2be11w11/
https://www.servustv.com/unterhaltung/v/aa-1uumaxe9h1w12/

### Verbose log

```shell
C:\Programme & Tools\Youtube-dl>yt-dlp.exe -vU https://www.servustv.com/unterhaltung/v/aa-27thr2be11w11/
[debug] Command-line config: ['-vU', 'https://www.servustv.com/unterhaltung/v/aa-27thr2be11w11/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg git-2020-02-18-ebee808, ffprobe git-2020-02-18-ebee808
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://www.servustv.com/unterhaltung/v/aa-27thr2be11w11/
[generic] aa-27thr2be11w11: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] aa-27thr2be11w11: Downloading webpage
[generic] aa-27thr2be11w11: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.servustv.com/unterhaltung/v/aa-27thr2be11w11/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\generic.py", line 3985, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.servustv.com/unterhaltung/v/aa-27thr2be11w11/
```

**Comment by someziggyman** [comment] 2022-05-23 21:26
Servus.py extractor still does not work. I mean it might be, but for some reason all servustv link are processed by Generic extractor. Is there a typo somewhere?

**Comment by someziggyman** [comment] 2022-05-24 08:27
@pukkandan This issue is fixed by updating regex (after researching all the discussions in this and other repos) seems to switch extraction from generic to servus.py as expected and it works:

    _VALID_URL = r'''(?x)
                    https?://
                        (?:www\.)?
                        (?:
                            servus\.com/(?:(?:at|de)/p/[^/]+|tv/videos)|
                            (?:servustv|pm-wissen)\.com/(?:videos|[^/]+/v)
                        )
                        /(?P<id>[aA]{2}-\w+|\d+-\d+|\w+)
                    '''

Also, maybe servus extractor can be improved by using what this plugin has to offer?
https://pypi.org/project/ytdlp-servustv/

It will require just minor adjustments in utils.py file and maybe editing the servus.py itself.. Just an improvement suggestion, while we are at it.

**Comment by pukkandan** [comment] 2022-05-24 08:38
Duplicate of #1076

> This issue is fixed by updating regex (after researching all the discussions in this and other repos) seems to switch extraction from generic to servus.py as expected and it works

@someziggyman There is no use pinging me. I cannot test whether the change actually solves the issue because of geo-restriction. Please make a PR

> Also, maybe servus extractor can be improved by using what this plugin has to offer?
[pypi.org/project/ytdlp-servustv](https://pypi.org/project/ytdlp-servustv/)

See #1498. You can copy the PR and address it's reviews if you wish to

**Closed by pukkandan** 2022-05-24 08:38 UTC
Labels: geo-blocked, site-bug

**Comment by uahim** [comment] 2022-05-25 18:04
@someziggyman though your fix does work when tested with e.g. https://regex101.com/ it actually fails for me when using in the extractor, suggesting they did change something more in the back as well:

```
[debug] [generic] Extracting URL: https://www.servustv.com/unterhaltung/v/aa-23zx4h1192112/
[generic] aa-23zx4h1192112: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] aa-23zx4h1192112: Downloading webpage
[generic] aa-23zx4h1192112: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.servustv.com/unterhaltung/v/aa-23zx4h1192112/
```
