### ISSUE TITLE
Won't download Facebook videos. Unsure if duplicate, as I don't understand most of what's said in other reports.

### ISSUE THREAD

**Issue by Nick268** [yt-dlp/yt-dlp#8500] opened 2023-11-02 16:30 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Provide a description that is worded well enough to be understood

I have taken the URL of the video with yt-dlp -v -F https://www.facebook.com/685999454/videos/pcb.10161169787829455/1535161793966312. It claims it cannot parse the data.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.facebook.com/685999454/videos/pcb.10161169787829455/1535161793966312']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (debian*)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.2.0-36-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-3.37.2, websockets-9.1
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)
[facebook] Extracting URL: https://www.facebook.com/685999454/videos/pcb.10161169787829455/1535161793966312
[facebook] 1535161793966312: Downloading webpage
[facebook] 1535161793966312: Downloading webpage
ERROR: [facebook] 1535161793966312: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/facebook.py", line 752, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/facebook.py", line 697, in _extract_from_url
    raise ExtractorError('Cannot parse data')
```

**Comment by bashonly** [comment] 2023-11-02 16:31
When I try to view that link in browser:

> This Video Isn't Available Anymore
> The link may be broken or the video may have been removed. You can explore more videos or try logging into facebook.com and then visiting the link again.

**Comment by Nick268** [comment] 2023-11-02 16:34
It's working for me. Here's a screen grab from seconds ago.
![Screenshot from 2023-11-02 16-33-15](https://github.com/yt-dlp/yt-dlp/assets/24611055/24277f4b-7fda-4071-ad3c-eddff0aca97d)

**Comment by bashonly** [comment] 2023-11-02 16:35
Are you logged into facebook in your browser?

> - [x] I've checked that all provided URLs are playable in a browser with the same IP and ***same login details***

**Comment by Nick268** [comment] 2023-11-02 16:35
Ah, interestingly the URL is different when I paste the one from the error message!!!

**Comment by Nick268** [comment] 2023-11-02 16:36
> Are you logged into facebook in your browser?
> 
> > * [x]  I've checked that all provided URLs are playable in a browser with the same IP and _**same login details**_

yes.

**Comment by bashonly** [comment] 2023-11-02 16:36
If it is only viewable when logged in, then you need to pass cookies to yt-dlp. yt-dlp cannot magically bypass authwall. But beware that facebook is happy to ban accounts when it detects 3rd party app usage such as yt-dlp

**Comment by Nick268** [comment] 2023-11-02 16:39
> If it is only viewable when logged in, then you need to pass cookies to yt-dlp. yt-dlp cannot magically bypass authwall. But beware that facebook is happy to ban accounts when it detects 3rd party app usage such as yt-dlp

Ah. The issue then becomes "I have no idea how to pass cookies". Not so much a site-bug as a user bug! Hmm. More reading required..

**Comment by bashonly** [comment] 2023-11-02 16:39
First, try passing the redirected URL to see if that works without cookies.

Then, if that doesn't work, and you feel like risking your account:
https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp

**Comment by Nick268** [comment] 2023-11-02 16:43
> First, try passing the redirected URL to see if that works without cookies.

Same error unfortunately.

Thanks for the Link. If "The Register" is to be believed then Facebook may charge users to get around the latest EU data collection consent stuff for adverts. That may be my trigger to dump Facebook any way.

**Comment by bashonly** [comment] 2023-11-05 09:17
Closing, since if the issue persists then this a duplicate of #4311

**Closed by bashonly** 2023-11-05 09:17 UTC
Labels: question, site:facebook

**Comment by acontreras89** [comment] 2025-04-21 20:05
#4311 has the conversation locked so I'll just share it here in case it helps.

This happens to me when trying to download geoblocked content. For instance, [this video](https://www.facebook.com/watch/?v=1449179876064876) is only available to swedes. If I connect to a VPN service I'm able to view it in the browser, but I cannot download it using `yt-dlp`:

```
[facebook] Extracting URL: https://www.facebook.com/watch/?v=1449179876064876
[facebook] 1449179876064876: Downloading webpage
[facebook] 1449179876064876: Downloading webpage
ERROR: [facebook] 1449179876064876: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```
