### ISSUE TITLE
[PornHub] ph61e9950ee4fd1: Unable to extract encoded url

### ISSUE THREAD

**Issue by 7uul** [yt-dlp/yt-dlp#6661] opened 2023-03-28 10:33 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Since a few days, pornhub videos cannot longer be downloaded.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
2023-03-28 12:22:51,653 main     INFO     itubego-dl version: v5.4.0
2023-03-28 12:22:53,320 downloader INFO     init succeed by params: {"add_playlist_index": "false", "audio_quality": "320Kb/s", "media_type": "video", "nocheckcertificate": "true", "read_cookie": "false", "save_id3": "true", "save_path": "F:/Blue/Misc/.temp/67677_eRsAAKdOAAA", "subtitle": "en", "url": "https://de.pornhub.com/view_video.php?viewkey=ph61e9950ee4fd1", "uuid": "442bb778", "video_quality": "1080P", "log_path": "C:/Users/ADM/AppData/Local/iTubeGo/Log", "params_filepath": "F:/Blue/Misc/.temp/67677_eRsAAKdOAAA/param.json", "ffmpeg_location": "C:/Program Files (x86)/iTubeGo", "device": "pc", "proxy": null, "ratelimit": "", "playlist_reverse_index": "false", "print_formats": "false"}
2023-03-28 12:22:53,325 downloader INFO     start processing
2023-03-28 12:22:53,325 downloader INFO     start extracting video
2023-03-28 12:22:57,578 downloader ERROR    Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1578, in __extract_info
  File "yt_dlp\extractor\common.py", line 693, in extract
  File "yt_dlp\extractor\pornhub.py", line 404, in _real_extract
  File "yt_dlp\extractor\pornhub.py", line 341, in extract_js_vars
  File "yt_dlp\extractor\common.py", line 1241, in _search_regex
yt_dlp.utils.RegexNotFoundError: [PornHub] ph61e9950ee4fd1: Unable to extract encoded url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "downloader.py", line 195, in process
  File "downloader.py", line 351, in _ytdl_extract_info
  File "downloader.py", line 348, in extract
  File "downloader.py", line 339, in extract
  File "yt_dlp\YoutubeDL.py", line 1491, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1520, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1012, in report_error
  File "yt_dlp\YoutubeDL.py", line 952, in trouble
yt_dlp.utils.DownloadError: ERROR: [PornHub] ph61e9950ee4fd1: Unable to extract encoded url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

2023-03-28 12:22:57,578 downloader INFO     ytdl extract failed, try youget extract info
2023-03-28 12:22:59,530 main     ERROR    Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1578, in __extract_info
  File "yt_dlp\extractor\common.py", line 693, in extract
  File "yt_dlp\extractor\pornhub.py", line 404, in _real_extract
  File "yt_dlp\extractor\pornhub.py", line 341, in extract_js_vars
  File "yt_dlp\extractor\common.py", line 1241, in _search_regex
yt_dlp.utils.RegexNotFoundError: [PornHub] ph61e9950ee4fd1: Unable to extract encoded url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "downloader.py", line 195, in process
  File "downloader.py", line 351, in _ytdl_extract_info
  File "downloader.py", line 348, in extract
  File "downloader.py", line 339, in extract
  File "yt_dlp\YoutubeDL.py", line 1491, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1520, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1012, in report_error
  File "yt_dlp\YoutubeDL.py", line 952, in trouble
yt_dlp.utils.DownloadError: ERROR: [PornHub] ph61e9950ee4fd1: Unable to extract encoded url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "itubego-dl.py", line 49, in main
  File "manager.py", line 31, in process
  File "downloader.py", line 200, in process
  File "downloader.py", line 383, in _youget_ectract_info
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Grub4K** [comment] 2023-03-28 10:46
Closing as duplicate of #4299

**Closed** 2023-03-28 10:47 UTC
Labels: duplicate
