### ISSUE TITLE
Unable to download JSON metadata: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by spirillen** [yt-dlp/yt-dlp#8502] opened 2023-11-02 19:24 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

denmark

### Provide a description that is worded well enough to be understood

```
yt-dlp https://www.dr.dk/drtv/se/top-gear_-sportsbiler-paa-den-tyske-autobahn_412660 -F
```

This have start failing, usually work fine., so I admit I dare the site is supported as the backend is red5 hosted content.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.dr.dk/drtv/se/top-gear_-sportsbiler-paa-den-tyske-autobahn_412660', '-vUF']
[debug] User config "/home/$USER/yt-dlp.conf": ['--proxy', 'socks5://127.0.0.1:9050/', '-4', '-c', '--rm-cache-dir', '--write-thumbnail', '--embed-thumbnail', '--convert-thumbnails', 'webp', '--write-subs', '--sub-langs', 'en-en-nP7-*;da-es-*;en-es-*;es-es-*', '--audio-quality', '0', '--audio-format', 'm4a', '--ffmpeg-location', '/usr/local/bin/ffmpeg', '--output', '%(playlist_index|)s%(playlist_index&. |)s%(title)s.%(ext)s', '-f', 'bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4][protocol^=http][protocol!*=dash] / bv*+ba/b']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (zip)
[debug] Python 3.9.12 (CPython x86_64 64bit) - Linux-5.15.0-88-generic-x86_64-with-glibc2.35 (OpenSSL 1.1.1q  5 Jul 2022, glibc 2.35)
[debug] exe versions: ffmpeg N-67646-gf2687a3b69-static (setts), ffprobe N-67646-gf2687a3b69-static
[debug] Optional libraries: brotli-None, certifi-2022.09.24, sqlite3-3.39.3
[debug] Proxy map: {'all': 'socks5://127.0.0.1:9050/'}
[debug] Loaded 1890 extractors
Removing cache dir /home/$USER/.cache/yt-dlp ..
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: be5cfb6be8930e1a5f427533ec32f2a481276b3da7b249d0150ce2b740ccf1ce
yt-dlp is up to date (stable@2023.10.13)
[drtv] Extracting URL: https://www.dr.dk/drtv/se/top-gear_-sportsbiler-paa-den-tyske-autobahn_412660
[drtv] top-gear_-sportsbiler-paa-den-tyske-autobahn_412660: Downloading webpage
[drtv] 00022311260: Downloading video JSON
ERROR: [drtv] top-gear_-sportsbiler-paa-den-tyske-autobahn_412660: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
ie_result = self._real_extract(url)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/drtv.py", line 203, in _real_extract
data = self._download_json(
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1069, in download_content
res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1033, in download_handle
res = self._download_webpage_handle(
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 903, in _download_webpage_handle
urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 860, in _request_webpage
raise ExtractorError(errmsg, cause=err)

File "/usr/local/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 410, in _send
res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
File "/home/$USER/miniconda/lib/python3.9/urllib/request.py", line 523, in open
response = meth(req, response)
File "/home/$USER/miniconda/lib/python3.9/urllib/request.py", line 632, in http_response
response = self.parent.error(
File "/home/$USER/miniconda/lib/python3.9/urllib/request.py", line 561, in error
return self._call_chain(*args)
File "/home/$USER/miniconda/lib/python3.9/urllib/request.py", line 494, in _call_chain
result = func(*args)
File "/home/$USER/miniconda/lib/python3.9/urllib/request.py", line 641, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4051, in urlopen
return self._request_director.send(req)
File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 114, in send
response = handler.send(request)
File "/usr/local/bin/yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
return func(self, *args, **kwargs)
File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 325, in send
return self._send(request)
File "/usr/local/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 415, in _send
raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 847, in _request_webpage
return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4070, in urlopen
raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found
```

**Comment by bashonly** [comment] 2023-11-02 19:30
Duplicate of #8298

**Closed by bashonly** 2023-11-02 19:30 UTC
Labels: site-bug, triage
