### ISSUE TITLE
Allow choosing a default subtitle track for output video

### ISSUE THREAD

**Issue by alpha-tango-kilo** [yt-dlp/yt-dlp#7925] opened 2023-08-21 11:29 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

In my use case, I want to download all available subtitles for a video, and then embed them. Then, when I play the video, I want it to default to showing the English subtitles. Currently, it's whatever your video player default to, which isn't always what I want.

I know at least some video containers support setting a default subtitle track, so if this were possible in the future that'd be cool. If it's relatively simple to implement I may be able to look at adding it myself

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Not applicable
```

**Comment by bashonly** [comment] 2023-08-21 19:20
Possible duplicate of #2799
Also related: #3709

**Comment by alpha-tango-kilo** [comment] 2023-08-22 09:33
My feature suggestion does look similar to both, however in the case of the open PR, I believe it's the first subtitle track downloaded that becomes forced/default. I'd like to be able to choose. [This suggestion](https://github.com/yt-dlp/yt-dlp/issues/2799#issuecomment-1183922967) could work for specifying per-language forced/default preferences

**Comment by pukkandan** [comment] 2023-08-27 00:19
The linked issues are about changing state of all subtitles, not about specific ones. Providing options to set default track is out of scope. Use ffmpeg etc to edit your video.

**Closed** 2023-08-28 11:21 UTC
Labels: enhancement, wontfix
