### ISSUE TITLE
oreilly video download failing with 404 for logged in user

### ISSUE THREAD

**Issue by santhosh-v** [yt-dlp/yt-dlp#1009] opened 2021-09-17 13:59 UTC
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Command-line config: ['https://learning.oreilly.com/videos/getting-started-with/9780136787709/', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg git-2020-04-03-52523b6, ffprobe git-2020-04-03-52523b6
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[safari:course] Downloading login page
[safari:course] Logging in
[safari:course] Completing login
[debug] [safari:course] Extracting URL: https://learning.oreilly.com/videos/getting-started-with/9780136787709/
[safari:course] 9780136787709: Downloading course JSON
[download] Downloading playlist: Getting Started with Kubernetes LiveLessons, 2nd Edition
[safari:course] playlist Getting Started with Kubernetes LiveLessons, 2nd Edition: Collected 87 videos; downloading 87 of them
[download] Downloading video 1 of 87
[safari:api] Downloading login page
[debug] [safari:api] Extracting URL: https://learning.oreilly.com/api/v1/book/9780136787709/chapter/GSK2_00_00_00.html
[safari:api] 9780136787709/GSK2_00_00_00: Downloading part JSON
[safari] Downloading login page
[debug] [safari] Extracting URL: https://learning.oreilly.com/library/view/getting-started-with/9780136787709/GSK2_00_00_00.html
[safari] 9780136787709-GSK2_00_00_00: Downloading webpage
ERROR: [safari] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 693, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3218, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default

[download] Downloading video 2 of 87
[debug] [safari:api] Extracting URL: https://learning.oreilly.com/api/v1/book/9780136787709/chapter/GSK2_01_01_00.html
[safari:api] 9780136787709/GSK2_01_01_00: Downloading part JSON
[debug] [safari] Extracting URL: https://learning.oreilly.com/library/view/getting-started-with/9780136787709/GSK2_01_01_00.html
[safari] 9780136787709-GSK2_01_01_00: Downloading webpage
ERROR: [safari] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 693, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3218, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default

[download] Downloading video 3 of 87
[debug] [safari:api] Extracting URL: https://learning.oreilly.com/api/v1/book/9780136787709/chapter/GSK2_01_01_01.html
[safari:api] 9780136787709/GSK2_01_01_01: Downloading part JSON

```
 

## Description

When oreilly video link is provided a 404 is reported. But if we try to download without login params like username and password, I could see above is getting downloaded. But it might be full length video similar to registered login

**Comment by Ashish0804** [comment] 2021-09-17 14:02
Looks like dupe of https://github.com/yt-dlp/yt-dlp/issues/586
Can u confirm this is different issue?

**Closed** 2021-09-17 20:37 UTC
Labels: duplicate
