### ISSUE TITLE
iq.com download error

### ISSUE THREAD

**Issue by son01420309** [yt-dlp/yt-dlp#8143] opened 2023-09-18 07:02 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

korea

### Provide a description that is worded well enough to be understood

new version , (old version same)

download error

404 JS module 

![20230915_201603707](https://github.com/yt-dlp/yt-dlp/assets/37327804/d6860278-24c8-4953-943d-ee49fb77f1b9)
 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-o', 'Downloads/%(title)s.1080p.WEB-DL.H264.AAC.%(ext)s', '--cookies', 'www.iq.com_cookies.txt', '--embed-subs', '--sub-langs', 'all', '--concurrent-fragments', '9', 'https://www.iq.com/play/교양반아-햇살은-내-곁에-7화-pwrcyjten0?lang=ko']
[debug] Encodings: locale cp949, fs utf-8, pref cp949, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-107859-g89ea7a2442-20220823 (setts), ffprobe N-107859-g89ea7a2442-20220823, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[iq.com] Extracting URL: https://www.iq.com/play/교양반아-햇살은-내-곁에-7화-pwrcyjten0?lang=ko
[iq.com] pwrcyjten0: Downloading webpage
[iq.com] pwrcyjten0: Downloading webpack JS
[iq.com] pwrcyjten0: Downloading #9943 module JS
[iq.com] pwrcyjten0: Downloading #9922 module JS
[iq.com] pwrcyjten0: Downloading #9864 module JS
[iq.com] pwrcyjten0: Downloading #9839 module JS
[iq.com] pwrcyjten0: Downloading #9491 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] pwrcyjten0: Downloading #8741 module JS
[iq.com] pwrcyjten0: Downloading #8085 module JS
[iq.com] pwrcyjten0: Downloading #7045 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] pwrcyjten0: Downloading #5482 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] pwrcyjten0: Downloading #5465 module JS
[iq.com] pwrcyjten0: Downloading #5449 module JS
[iq.com] pwrcyjten0: Downloading #5189 module JS
[iq.com] pwrcyjten0: Downloading #4959 module JS
[iq.com] pwrcyjten0: Downloading #4753 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] pwrcyjten0: Downloading #4681 module JS
[iq.com] pwrcyjten0: Downloading #4403 module JS
[iq.com] pwrcyjten0: Downloading #4182 module JS
[iq.com] pwrcyjten0: Downloading #3087 module JS
[iq.com] pwrcyjten0: Downloading #2925 module JS
[iq.com] pwrcyjten0: Downloading #2846 module JS
[iq.com] pwrcyjten0: Downloading #2708 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] pwrcyjten0: Downloading #2398 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] pwrcyjten0: Downloading #2274 module JS
[iq.com] pwrcyjten0: Downloading #2248 module JS
[iq.com] pwrcyjten0: Downloading #2152 module JS
[iq.com] pwrcyjten0: Downloading #1903 module JS
[iq.com] pwrcyjten0: Downloading #1650 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] pwrcyjten0: Downloading #1647 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] pwrcyjten0: Downloading #1487 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] pwrcyjten0: Downloading #1417 module JS
[iq.com] pwrcyjten0: Downloading #1361 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] pwrcyjten0: Downloading #1126 module JS
[iq.com] pwrcyjten0: Downloading #1106 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] pwrcyjten0: Downloading #268 module JS
ERROR: [iq.com] pwrcyjten0: Unable to extract player JS; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\iqiyi.py", line 570, in _real_extract
  File "yt_dlp\extractor\iqiyi.py", line 553, in _update_bid_tags
  File "yt_dlp\extractor\iqiyi.py", line 544, in _extract_vms_player_js
```

**Comment by gamer191** [comment] 2023-09-18 13:55
possible duplicate of #8123

**Closed** 2023-09-18 13:58 UTC
Labels: duplicate, site-bug
