### ISSUE TITLE
Nickelodeon.nl is broken

### ISSUE THREAD

**Issue by Scrooge200FES** [yt-dlp/yt-dlp#4025] opened 2022-06-08 20:43 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Netherlands

### Description

Nickelodeon.nl gives me an error. The site's playable videos are region blocked, but you can still browse it in America. I tested this with the following URL: https://www.nickelodeon.nl/episodes/1pcwwo/spongebob-me-mosterd-boodschappenlijstje-seizoen-seasonnumber-11-afl-17. I have checked, and my yt-dlp download is both updated and complete.

### Verbose log

```shell
Microsoft Windows [Version 10.0.19043.1706]
(c) Microsoft Corporation. All rights reserved.

C:\...>yt-dlp -vU https://www.nickelodeon.nl/episodes/1pcwwo/spongebob-me-mosterd-boodschappenlijstje-seizoen-seasonnumber-11-afl-17
[debug] Command-line config: ['-vU', 'https://www.nickelodeon.nl/episodes/1pcwwo/spongebob-me-mosterd-boodschappenlijstje-seizoen-seasonnumber-11-afl-17']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev (setts), ffprobe 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [nick.de] Extracting URL: https://www.nickelodeon.nl/episodes/1pcwwo/spongebob-me-mosterd-boodschappenlijstje-seizoen-seasonnumber-11-afl-17
[nick.de] spongebob-me-mosterd-boodschappenlijstje-seizoen-seasonnumber-11-afl-17: Downloading webpage
[nick.de] 2c0b66da-499a-11e8-bfd4-0026b9414f30: Downloading JSON metadata
[nick.de] 2c0b66da-499a-11e8-bfd4-0026b9414f30: Downloading info
ERROR: [nick.de] spongebob-me-mosterd-boodschappenlijstje-seizoen-seasonnumber-11-afl-17: Unable to download XML: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\mtv.py", line 327, in _real_extract
  File "yt_dlp\extractor\mtv.py", line 231, in _get_videos_info
  File "yt_dlp\extractor\mtv.py", line 234, in _get_videos_info_from_url
  File "yt_dlp\extractor\common.py", line 980, in _download_xml
  File "yt_dlp\extractor\common.py", line 959, in _download_xml_handle
  File "yt_dlp\extractor\common.py", line 801, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 786, in _request_webpage

  File "yt_dlp\extractor\common.py", line 768, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3596, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by Scrooge200FES** [comment] 2022-06-18 21:52
I still can't download videos, I tried today and yesterday. The main error is "Unable to download XML" after I link to the page.

**Comment by pukkandan** [comment] 2022-07-17 22:28
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/169

**Closed by pukkandan** 2022-07-17 22:28 UTC
Labels: site-bug, triage
