### ISSUE TITLE
precondition check failed

### ISSUE THREAD

**Issue by Corrupsy** [yt-dlp/yt-dlp#9598] opened 2024-04-03 01:29 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

i dont know whats going, when i click download its not working

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[ERROR @ 16:15:56 | Cinema] WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
[ERROR @ 16:15:56 | Cinema] WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[ERROR @ 16:15:56 | Cinema] WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
[ERROR @ 16:15:56 | Cinema] WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[ERROR @ 16:15:56 | Cinema] WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
[ERROR @ 16:15:56 | Cinema] WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[ERROR @ 16:15:57 | Cinema] WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
```

**Comment by bashonly** [comment] 2024-04-03 04:05
you either need to update yt-dlp or whatever 3rd party tool you're using needs to update yt-dlp

duplicate of #9316

**Closed by bashonly** 2024-04-03 04:05 UTC
Labels: bug, triage

**Comment by arose26** [comment] 2024-04-16 22:28
just tested on nightly and this problem still occurs.

**Comment by bashonly** [comment] 2024-04-16 22:31
@arose26 show a verbose log

**Comment by arose26** [comment] 2024-04-16 22:37
yt-dlp -f "(bestvideo+bestaudio/best)[protocol!*=dash]"  --format mp4 --external-downloader ffmpeg --external-downloader-args "ffmpeg_i:-ss 1295 -t 3" https://www.youtube.com/watch?v=KoAHs4X1o9E  --force-overwrites --output test.mp4 --verbose

[debug] Command-line config: ['-f', '(bestvideo+bestaudio/best)[protocol!*=dash]', '--format', 'mp4', '--external-downloader', 'ffmpeg', '--external-downloader-args', 'ffmpeg_i:-ss 1295 -t 3', 'https://www.youtube.com/watch?v=KoAHs4X1o9E', '--force-overwrites', '--output', 'test.mp4', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.

**Comment by bashonly** [comment] 2024-04-16 22:38
> [debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp

**Comment by arose26** [comment] 2024-04-16 22:38
yt-dlp --version gives me 2024.04.13.232802
maybe it's because I'm running that from subprocess

**Comment by arose26** [comment] 2024-04-16 22:40
pip uninstall yt-dlp solved it
