### ISSUE TITLE
Ceska televize (iVysilani) is broken after recent site update

### ISSUE THREAD

**Issue by xmstspider** [yt-dlp/yt-dlp#1914] opened 2021-12-07 09:18 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Czech republic

### Description

Hi,

Ceska Televize updated their platform and the extractor is unable to fetch anything anymore.

### Verbose log

```shell
yt-dlp -Uv https://www.ceskatelevize.cz/porady/11454740577-pribehy-20-stoleti/221562261760007/
[debug] Command-line config: ['-Uv', 'https://www.ceskatelevize.cz/porady/11454740577-pribehy-20-stoleti/221562261760007/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (zip)
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.15.6-100.fc34.x86_64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: keyring, sqlite
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [CeskaTelevize] Extracting URL: https://www.ceskatelevize.cz/porady/11454740577-pribehy-20-stoleti/221562261760007/
[CeskaTelevize] 221562261760007: Downloading webpage
ERROR: [CeskaTelevize] 221562261760007: Unable to extract iframe player url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/xzdse/bin/yt-dlp/yt_dlp/extractor/common.py", line 597, in extract
    ie_result = self._real_extract(url)
  File "/home/xzdse/bin/yt-dlp/yt_dlp/extractor/ceskatelevize.py", line 102, in _real_extract
    refer_url = update_url_query(unescapeHTML(self._search_regex(
  File "/home/xzdse/bin/yt-dlp/yt_dlp/extractor/common.py", line 1171, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract iframe player url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/xzdse/bin/yt-dlp/yt_dlp/extractor/common.py", line 597, in extract
    ie_result = self._real_extract(url)
  File "/home/xzdse/bin/yt-dlp/yt_dlp/extractor/ceskatelevize.py", line 102, in _real_extract
    refer_url = update_url_query(unescapeHTML(self._search_regex(
  File "/home/xzdse/bin/yt-dlp/yt_dlp/extractor/common.py", line 1171, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract iframe player url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xzdse/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1329, in wrapper
    return func(self, *args, **kwargs)
  File "/home/xzdse/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1398, in __extract_info
    ie_result = ie.extract(url)
  File "/home/xzdse/bin/yt-dlp/yt_dlp/extractor/common.py", line 623, in extract
    raise type(e)(e.msg, **kwargs)
yt_dlp.utils.RegexNotFoundError: [CeskaTelevize] 221562261760007: Unable to extract iframe player url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by Ashish0804** [comment] 2021-12-07 10:12
>I've searched the bugtracker for similar issues including closed ones. DO NOT post duplicates

This is not for shitz and gigglez.

duplicate of https://github.com/yt-dlp/yt-dlp/issues/1899

**Closed by Ashish0804** 2021-12-07 10:12 UTC
Labels: extractor-bug, triage

**Comment by xmstspider** [comment] 2021-12-07 12:37
Strange, searched for both "ceska" and "ivysilani" and found old tickets only. Anyway, good that someone is on it already...
