### ISSUE TITLE
[Broken] SoundCloud

### ISSUE THREAD

**Issue by 89z** [yt-dlp/yt-dlp#975] opened 2021-09-14 18:10 UTC
Doing a request like this:

~~~
GET /resolve?client_id=fSSdm5yTnDka1g0Fz1CO5Yx6z0NbeHAj&url=https%3A%2F%2Fsoundcloud.com%2Fpdis_inpartmaint%2Fharold-budd-perhaps-moss HTTP/1.1
Host: api-v2.soundcloud.com
~~~

Result:

~~~
HTTP/1.1 401 Unauthorized
~~~

For some reason, this old `client_id` works though:

~~~
GET /resolve?client_id=a3e059563d7fd3372b49b37f00a00bcf&url=https%3A%2F%2Fsoundcloud.com%2Fpdis_inpartmaint%2Fharold-budd-perhaps-moss HTTP/1.1
Host: api-v2.soundcloud.com
~~~

Result:

~~~
HTTP/1.1 200 OK
~~~

I found the working `client_id` here:

<https://github.com/flyingrub/scdl/blob/master/scdl/__init__.py>

and the problem code is here:

<https://github.com/yt-dlp/yt-dlp/blob/e9a30b181e4c27319df5e97d46bdfeb61e0d07bf/yt_dlp/extractor/soundcloud.py#L307-L309>

**Comment by pukkandan** [comment] 2021-09-14 18:32
### IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE

You don't even say what the issue you are facing is, much less provide a verbose log. Create a new issue using the correct template with all necessary information including the `--verbose` output

**Closed by pukkandan** 2021-09-14 18:32 UTC

**Comment by 89z** [comment] 2021-09-14 18:45
Looks like the code trys the `client_id` I linked, then if it fails (which will be every single time), it just pulls a new code from the HTML.

**Comment by pukkandan** [comment] 2021-09-14 18:50
dude, I still don't understand what your issue is in the first place! Are you just saying the static client id is not working? If so, the validity of client id keeps changing all the time - hence the fallback and caching. The last time the extractor was updated, that id was working. There is no point in trying to keep the static id up-to-date

**Comment by 89z** [comment] 2021-09-14 18:53
How about you just ignore this issue, and go about your day. I didnt follow the dumb template, as I am not a robot, I am a human being. I gave more than enough info to describe what the issue is, and how to replicate the problem. But because I didnt follow the dumb template, issue was closed.

I put care into the issue. I searched previous issues, I searched the code, I tried with latest version. I gave multiple links to help explain, but you still close anyway. So if you want to be shitty like that, then I dont really care to discuss the problem further, I will just fix it myself, on my own project.

**Comment by pukkandan** [comment] 2021-09-14 19:09
> How about you just ignore this issue, and go about your day.

Then why the hell did you open the issue on my repo!

> I gave more than enough info to describe what the issue is, and how to replicate the problem

Well, then clearly I am just dumb. I don't see you explaining what issue you are having with yt-dlp. From reading the initial issue, there is no information to deduce what your issue is in relation to yt-dlp. You don't even say what yt-dlp command you are running. 

> Looks like the code trys the `client_id` I linked, then if it fails (which will be every single time), it just pulls a new code from the HTML.

This comment (which you have now deleted - and this is not the first time you are deleting comments mid-conversation) clarifies to me that you never even tried downloading it using yt-dlp and that you tried to just copy the static user id and it didnt work. So u opened an issue that soundcloud is broken? 

If what you are trying to report with the issue is just that the static id is invalid, I have already replied to you about it
