### ISSUE TITLE
Support for downloading videos from jio cinema

### ISSUE THREAD

**Issue by aryanchoudharypro** [yt-dlp/yt-dlp#9559] opened 2024-03-29 11:46 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

India

### Example URLs

Https://www.jiocinema.com. there are other links that the mobile app generates so I am not sure how can I put them here I can provide more details as necessary

### Provide a description that is worded well enough to be understood

There's a free streaming platform known as jio cinema through which downloading is not possible when using  yt-dlp

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-P', '/storage/emulated/0/Download/Seal', '--newline', '--config-locations', '/data/user/0/com.junkfood.seal/cache/config.txt', '--no-cache-dir', '--ffmpeg-location', '/data/app/~~k1lWxc1bR4WUqhVkQIbfzQ==/com.junkfood.seal-wRdJPL7PBI9JxB_XUTUjAQ==/lib/arm64/libffmpeg.so', 'https://go.jc.fm/fRhd/ato7is36']
[debug] | Config "/data/user/0/com.junkfood.seal/cache/config.txt": ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version nightly@2024.03.22.232703 from yt-dlp/yt-dlp-nightly-builds [e5d4f1110] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-5.4.259-NameLess-ga56c5f19713b-aarch64-with-libc (OpenSSL 1.1.1t  7 Feb 2023, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.17, mutagen-1.46.0, sqlite3-3.30.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1807 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
WARNING: [generic] Falling back on generic information extractor
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.jiocinema.com/movies/the-rise-of-darkrai-pokemon-the-movie/3780293/watch?af_force_deeplink=true&source_caller=api&pid=mobile_share&shortlink=ato7is36&af_adset=Share%20MOVIE%20Adset&af_ad=Share%20for%20The%20Rise%20of%20Darkrai%20-%20Pokemon%20the%20Movie&deep_link_value=jiovootviacom18%3A%2F%2Fjiovoot%2Fdetail%2F3780293&af_channel=Share%20Button&c=Share%20Media
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1605, in wrapper
    return func(self, *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1740, in __extract_info
    ie_result = ie.extract(url)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 732, in extract
    ie_result = self._real_extract(url)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/generic.py", line 2530, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.jiocinema.com/movies/the-rise-of-darkrai-pokemon-the-movie/3780293/watch?af_force_deeplink=true&source_caller=api&pid=mobile_share&shortlink=ato7is36&af_adset=Share%20MOVIE%20Adset&af_ad=Share%20for%20The%20Rise%20of%20Darkrai%20-%20Pokemon%20the%20Movie&deep_link_value=jiovootviacom18%3A%2F%2Fjiovoot%2Fdetail%2F3780293&af_channel=Share%20Button&c=Share%20Media
```

**Comment by seproDev** [comment] 2024-03-29 11:52
Duplicate of #5563

**Closed by seproDev** 2024-03-29 11:52 UTC
Labels: site-request, triage
