### ISSUE TITLE
PBS - Unable to extract

### ISSUE THREAD

**Issue by wallyps** [yt-dlp/yt-dlp#11928] opened 2024-12-27 21:23 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

https://www.pbs.org/video/take-a-chance-wdZQCx/

[pbs] Downloading JSON metadata
Extracting cookies from firefox
Extracted 2912 cookies from firefox
[pbs] Extracting URL: https://www.pbs.org/video/take-a-chance-wdZQCx/
[pbs] take-a-chance-wdZQCx: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page

ERROR: An extractor error has occurred. (caused by KeyError('title')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\pbs.py", line 689, in _real_extract
KeyError: 'title'

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-o', 'lidia', 'https://www.pbs.org/video/take-a-chance-wdZQCx/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.12.26.232815 from yt-dlp/yt-dlp-nightly-builds [0b6b7742c] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 2020-11-04-git-cfdddec0c8-full_build-www.gyan.dev, ffprobe 2020-11-04-git-cfdddec0c8-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.12.26.232815 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.12.26.232815 from yt-dlp/yt-dlp-nightly-builds)
[debug] Using fake IP 6.66.219.101 (US) as X-Forwarded-For
[pbs] Downloading JSON metadata
[pbs] Extracting URL: https://www.pbs.org/video/take-a-chance-wdZQCx/
[pbs] take-a-chance-wdZQCx: Downloading webpage

[pbs] Extracting URL: https://www.pbs.org/video/take-a-chance-wdZQCx/
[pbs] take-a-chance-wdZQCx: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: An extractor error has occurred. (caused by KeyError('title')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\pbs.py", line 689, in _real_extract
KeyError: 'title'
```

**Comment by dirkf** [comment] 2024-12-27 23:02
Presumably #11514 again, but account and/or in-region needed.

**Comment by october262** [comment] 2024-12-28 06:25
try again with yt-dlp --force-generic-extractor "https://www.pbs.org/video/take-a-chance-wdZQCx/"
the video will now download.

**Comment by bashonly** [comment] 2024-12-28 21:45
Duplicate of #11514

**Closed by bashonly** 2024-12-28 21:45 UTC
Labels: site-bug, triage

**Comment by wallyps** [comment] 2024-12-28 22:38
> try again with yt-dlp --force-generic-extractor "https://www.pbs.org/video/take-a-chance-wdZQCx/" the video will now download.

Thank you! It works perfectly!

**Comment by slmingol** [comment] 2025-01-03 16:51
Ran into this issue as well:

```
$ yt-dlp 'https://www.pbs.org/video/part-two-painter-god-6wqjeo/'
[pbs] Downloading JSON metadata
[pbs] Extracting URL: https://www.pbs.org/video/part-two-painter-god-6wqjeo/
[pbs] part-two-painter-god-6wqjeo: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: An extractor error has occurred. (caused by KeyError('title')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

```
$ yt-dlp -U
Latest version: stable@2024.12.23 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.23 from yt-dlp/yt-dlp)
```

Confirming that the above tip ` yt-dlp --force-generic-extractor ...` worked for me as well.

**Comment by Garman12** [comment] 2025-07-18 21:21
Reporting the same issue, same site different video, verified playing in Firefox 128.12.0esr on the same laptop: 
``` 
$ yt-dlp -vU https://pbs.org/video/america-numbers-surviving-year-one/ 
[debug] Command-line config: ['-vU', 'https://pbs.org/video/america-numbers-surviving-year-one/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2025.06.30 from yt-dlp/yt-dlp [b01878449] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-37-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.16 11 Feb 2025, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0
[debug] Optional libraries: certifi-2022.09.24, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12 (unsupported)
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Plugin directories: none
[debug] Loaded 1857 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2025.06.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2025.06.30 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://pbs.org/video/america-numbers-surviving-year-one/
[generic] america-numbers-surviving-year-one: Downloading webpage
[redirect] Following redirect to https://www.pbs.org/video/america-numbers-surviving-year-one/
[debug] Using fake IP 6.207.148.83 (US) as X-Forwarded-For
[pbs] Downloading JSON metadata
[pbs] Extracting URL: https://www.pbs.org/video/america-numbers-surviving-year-one/
[pbs] america-numbers-surviving-year-one: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: An extractor error has occurred. (caused by KeyError('title')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/garrick/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 752, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/garrick/.local/bin/yt-dlp/yt_dlp/extractor/pbs.py", line 729, in _real_extract
    'title': info['title'],
             ~~~~^^^^^^^^^
KeyError: 'title'
```
Followed up with generic extractor which did not work: 
```
$ yt-dlp -vU --force-generic-extractor https://www.pbs.org/video/america-numbers-surviving-year-one/
[debug] Command-line config: ['-vU', '--force-generic-extractor', 'https://www.pbs.org/video/america-numbers-surviving-year-one/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2025.06.30 from yt-dlp/yt-dlp [b01878449] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-37-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.16 11 Feb 2025, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0
[debug] Optional libraries: certifi-2022.09.24, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12 (unsupported)
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Plugin directories: none
[debug] Loaded 1857 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2025.06.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2025.06.30 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.pbs.org/video/america-numbers-surviving-year-one/
[generic] america-numbers-surviving-year-one: Downloading webpage
WARNING: [generic] Forcing generic information extractor
[generic] america-numbers-surviving-year-one: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.pbs.org/video/america-numbers-surviving-year-one/
Traceback (most recent call last):
  File "/home/garrick/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1662, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/garrick/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1797, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/garrick/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 752, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/garrick/.local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2579, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.pbs.org/video/america-numbers-surviving-year-one/
```
