### ISSUE TITLE
Yt-dlp has stopped downloading All Youtube videos from channels(only downloading a small number)

### ISSUE THREAD

**Issue by harshbhardwaj77** [yt-dlp/yt-dlp#8981] opened 2024-01-12 08:40 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

I use yt-dlp to download Youtube videos. But recently **it has stopped downloading all the videos from channels.**

When I try to download youtube shorts from a channe **which has 1000s of shorts , it doesn't download all the shorts.**

**It gives me Warning - Incomplete Data Received**

It is only downloading 240 shorts , even though a while ago it used to download all the shorts even if they were in 1000s.

I am using the latest version of yt-dlp.

Please help with this issue !!!

![Screenshot 2024-01-12 062836](https://github.com/yt-dlp/yt-dlp/assets/97728891/d271a03b-0924-420e-a53a-83d3ea8c56dd)
![Screenshot 2024-01-12 062917](https://github.com/yt-dlp/yt-dlp/assets/97728891/235482fb-a574-4f85-bb0f-69a884b9a899)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-o', "'/Violet/%(title)s-%(autonumber)s.%(ext)s'", '--download-archive', "'/Archives/!VioletArchive.txt", 'https://www.youtube.com/@violettVon']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.5 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 3.0.9 30 May 2023)
[debug] exe versions: ffmpeg 2023-10-29-git-2532e832d2-full_build-www.gyan.dev (setts), ffprobe 2023-10-29-git-2532e832d2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.42.0, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Loading archive file "'/Archives/!VioletArchive.txt"
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/@violettVon
[youtube:tab] @violettVon: Downloading webpage
[debug] [youtube:tab] Selected tab: 'videos' (videos), Requested tab: ''
[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[youtube:tab] @violettVon/streams: Downloading webpage
[debug] [youtube:tab] Selected tab: 'streams' (live), Requested tab: 'streams'
[youtube:tab] @violettVon/shorts: Downloading webpage
[debug] [youtube:tab] Selected tab: 'shorts' (shorts), Requested tab: 'shorts'
[youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUw5Shy-28c8udygOn-u3HrQ
```

**Comment by bashonly** [comment] 2024-01-12 14:01
Duplicate of #8910

**Closed by bashonly** 2024-01-12 14:01 UTC
Labels: site-bug, triage
