### ISSUE TITLE
Possible bug in --trim-file-names implementation

### ISSUE THREAD

**Issue by marcello-pietrobon** [yt-dlp/yt-dlp#5526] opened 2022-11-13 16:28 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I was using the flag `--trim-file-names`

I have to say first that current code works, but on a private modification of yt-dlp slightly modified on my side,
the current use of rsplit() shows up as a bug and it doesn't work leaving a long filename not trimmed as soon as it has an extra  '.' (dot) in it's basename (i.e. beside the dot of the extension)

YoutubeDL.py (lines 1327-1331)

```
            # https://github.com/blackjack4494/youtube-dlc/issues/85
            trim_file_name = self.params.get('trim_file_name', False)
            if trim_file_name:
                no_ext, *ext = filename.rsplit('.', 2)
                filename = join_nonempty(no_ext[:trim_file_name], *ext, delim='.')
```

if we want to take off the extension, trim the path, and then put the extension back we should use 1 as parameter, rather than 2,
that is:

```
                no_ext, *ext = filename.rsplit('.', 1)
```

Hope it helps.

Regards

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Sorry the bug doesn't show up if I just run yt-dlp on the public implementation, so the output wouldn't give any useful information.
I truly hope you don't block me for this. Thanks.
```

**Comment by pukkandan** [comment] 2022-11-13 16:29
> if we want to take off the extension, trim the path, and then put the extension back we should use 1 as parameter, rather than 2, that is:
> 
> ```
>                 no_ext, *ext = filename.rsplit('.', 1)
> ```

The issue with that is that subtitles, infojson etc have 2 extensions, like `.info.json`/`.en.srt` etc

**Comment by marcello-pietrobon** [comment] 2022-11-13 16:33
Thank you for the quick answer.

Best.

**Comment by pukkandan** [comment] 2022-11-13 16:34
The issue itself is a duplicate of https://github.com/yt-dlp/yt-dlp/issues/2314

---

> ```shell
> Sorry the bug doesn't show up if I just run yt-dlp on the public implementation, so the output wouldn't give any useful information.
> ```

In the future, even if you don't think there is no "usefull" information in the logs, provide it anyways. If the issue were not already known, the issue description lacks enough information which the verbose log would actually provide

**Closed by pukkandan** 2022-11-13 16:34 UTC
Labels: bug, triage

**Comment by marcello-pietrobon** [comment] 2022-11-13 16:36
Okay, I will. Even if coming from my personal implementation.

**Comment by pukkandan** [comment] 2022-11-13 16:37
> Even if coming from my personal implementation.

wdym? The bug is known to exist in yt-dlp

**Comment by marcello-pietrobon** [comment] 2022-11-13 17:39
> wdym? The bug is known to exist in yt-dlp

The problem I was having with my personal implementation forked from your version 2022.10.04
has now disappeared with the version 2022.11.11 in the test case I was using.
I reported here because I felt there still was a problem not understanding that 2 on the instruction `filename.rsplit('.', 2)`

By a short debugging I see that the filename is still split on the 'unwanted' dot on the basename, but then the the line
`                filename = join_nonempty(no_ext[:trim_file_name], *ext, delim='.')
`
seems to work a bit differently than before, so that the filename gets shortened enough for the file to be downloaded.

**Comment by marcello-pietrobon** [comment] 2022-11-13 17:40
Maybe a general fix could be that if in the variable `force_ext` in the line

`                    filename = replace_extension(filename, force_ext, info_dict.get('ext'))
`

 appear n dots, then when later trimming we do could use

`                no_ext, *ext = filename.rsplit('.', n+1)
`

And similarly do the same in the code

```
if tmpl_type in ('', 'temp'):
    final_ext, ext = self.params.get('final_ext'), info_dict.get('ext')
    if final_ext and ext and final_ext != ext and filename.endswith(f'.{final_ext}'):
        filename = replace_extension(filename, ext, final_ext)

```

A bit cumbersome but probably the problem would then appear very rarely. Just an idea.

**Comment by pukkandan** [comment] 2022-11-13 17:41
> Maybe a general fix could be that if in the variable `force_ext` in the line
> 
> ` filename = replace_extension(filename, force_ext, info_dict.get('ext'))`
> 
> appear n dots, then when later trimming we do could use
> 
> ` no_ext, *ext = filename.rsplit('.', n+1)`

That sounds good. Will you make a PR?

**Comment by marcello-pietrobon** [comment] 2022-11-13 17:47
I've never done a pull request (blush). But I can learn it and do in the next 10 days or less (I'm extremely busy these days
Would that be good for you?

**Comment by pukkandan** [comment] 2022-11-13 17:48
sure, take your time

**Comment by Alarez777** [comment] 2024-04-18 16:40
> > if we want to take off the extension, trim the path, and then put the extension back we should use 1 as parameter, rather than 2, that is:
> > ```
> >                 no_ext, *ext = filename.rsplit('.', 1)
> > ```
> 
> The issue with that is that subtitles, infojson etc have 2 extensions, like `.info.json`/`.en.srt` etc

hi I was using yt-dlp and I came across this bug I see that it has not been fixed yet and you mention that the proposed solution was not accepted because of `.info.json`/`.en.srt` extensions.
But if you know about this type of extensions, couldn't you see which is the biggest extension of characters and put it as a condition in an if? I know that maybe it is not ideal but isn't it better than not working?
I mean something like this
`            if trim_file_name:
                no_ext, *ext = filename.rsplit(".", 2)
                if len(ext[0]) >= 4:
                    no_ext, *ext = filename.rsplit(".", 1)
                filename = join_nonempty(no_ext[:trim_file_name], *ext, delim=".")
`
