### ISSUE TITLE
Youtube videos demuxed - no audio video combinations

### ISSUE THREAD

**Issue by CJBeausoleil** [yt-dlp/yt-dlp#10477] opened 2024-07-15 11:54 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I noticed a few days ago (13 July 2024), for the first time, that `yt-dlp -F` to list available formats shows nothing but _video_only_ and _audio_only_ streams (files) no audio video combinations are available. It used to be that youtube provided audio+video muxed options.

Did something change? If so please can someone explain to me the reason for audio and video only streams?
What would be the benefit of audio video only streams? Did Youtube change the way it provides video streams? Is this a change in the way yt-dlp operates? Has anyone else noticed this?

I searched issues and and discussions for something related but I couldn't find anything.

Thank you.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe -vU -F https://www.youtube.com/watch?v=DjVqn0CzOfI
[debug] Command-line config: ['-vU', '-F', 'https://www.youtube.com/watch?v=DjVqn0CzOfI']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19043-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.09 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=DjVqn0CzOfI
[youtube] DjVqn0CzOfI: Downloading webpage
[youtube] DjVqn0CzOfI: Downloading ios player API JSON
[debug] Loading youtube-nsig.8d9f6215 from cache
[debug] [youtube] Decrypted nsig RkKNHdYoWS5pQ9YS2th => vO-CE_1nyOmAcQ
[debug] Loading youtube-nsig.8d9f6215 from cache
[debug] [youtube] Decrypted nsig _uUoAI1fcHrMDcUWaTT => g0swIpgLz_CfYQ
[youtube] DjVqn0CzOfI: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for DjVqn0CzOfI:
ID  EXT   RESOLUTION FPS CH │   FILESIZE  TBR PROTO │ VCODEC         VBR ACODEC      ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        1    │                 mhtml │ images                                 storyboard
sb1 mhtml 80x45        1    │                 mhtml │ images                                 storyboard
sb0 mhtml 160x90       1    │                 mhtml │ images                                 storyboard
233 mp4   audio only        │                 m3u8  │ audio only         unknown             [ru] Default, IOS
234 mp4   audio only        │                 m3u8  │ audio only         unknown             [ru] Default, IOS
139 m4a   audio only      2 │    1.06MiB  49k https │ audio only         mp4a.40.5   49k 22k [ru] low, IOS, m4a_dash
140 m4a   audio only      2 │    2.81MiB 130k https │ audio only         mp4a.40.2  130k 44k [ru] medium, IOS, m4a_dash
251 webm  audio only      2 │    2.85MiB 132k https │ audio only         opus       132k 48k [ru] medium, WEB, webm_dash
269 mp4   256x144     30    │ ~  1.95MiB  90k m3u8  │ avc1.4D400C    90k video only          IOS
160 mp4   256x144     30    │  361.00KiB  16k https │ avc1.4D400C    16k video only          144p, IOS, mp4_dash
230 mp4   640x360     30    │ ~  5.47MiB 252k m3u8  │ avc1.4D401E   252k video only          IOS
134 mp4   640x360     30    │  878.99KiB  40k https │ avc1.4D401E    40k video only          360p, IOS, mp4_dash
18  mp4   640x360     30  2 │ ≈  3.64MiB 168k https │ avc1.42001E        mp4a.40.2       44k [ru] 360p, WEB
605 mp4   640x360     30    │ ~  4.10MiB 189k m3u8  │ vp09.00.21.08 189k video only          IOS
232 mp4   1280x720    30    │ ~  8.30MiB 383k m3u8  │ avc1.64001F   383k video only          IOS
136 mp4   1280x720    30    │    2.00MiB  93k https │ avc1.64001F    93k video only          720p, IOS, mp4_dash
270 mp4   1920x1080   30    │ ~ 12.44MiB 573k m3u8  │ avc1.640028   573k video only          IOS
137 mp4   1920x1080   30    │    3.38MiB 156k https │ avc1.640028   156k video only          1080p, IOS, mp4_dash
```
```

**Comment by bashonly** [comment] 2024-07-15 14:35
Format 18 is still available (360p video+audio). Youtube removed format 17 several months, and they are in the process of removing format 22 (or maybe they've even completed the removal): 
- #10206

These 3 formats were the only muxed video+audio formats that Youtube provided for the past several years. They are/were legacy formats; they were only being served for old clients/devices. They were not being served to web browsers. Youtube has been phasing out old client versions so that they can rollout client integrity checks and whatnot, so it follows that they would phase out these legacy formats.

If you pass `--extractor-arg "youtube:player_client=mediaconnect"` you can get combined video+audio HLS streams up to 1080p; that's really only other option besides format 18.

Closing as duplicate of #10206

**Closed by bashonly** 2024-07-15 14:35 UTC
Labels: question
