### ISSUE TITLE
How to specify format options to get f135 video + audio from f18 format on youtube?

### ISSUE THREAD

**Issue by Otw-cz** [yt-dlp/yt-dlp#5046] opened 2022-09-26 08:32 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I used this with youtube-dl:
youtube-dl -f 135+18 ... and result was mp4 with 135 video and audio from format 18 (360p vid, 96kbit audio) so I get 480p vid with smaller file size than by using -f 135+140. I used yt-dlp as drop in replacement and now I realized that it downloads only f135 so no audio on result files...
Is it possible to achieve this with YT-DLP? I tried some combinations and no luck so far.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by gamer191** [comment] 2022-09-26 08:39
Can you please post a verbose output (add `--verbose` to the end of your command and then copy-paste the output into a github comment)

**Comment by Otw-cz** [comment] 2022-09-26 08:46
youtube-dl -f 135+18 --verbose vlXK8yHyog8
[debug] Command-line config: ['-f', '135+18', '--verbose', 'vlXK8yHyog8']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.0-18-amd64-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.2-static, ffprobe 4.3.2-static, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] [youtube] Extracting URL: vlXK8yHyog8
[youtube] vlXK8yHyog8: Downloading webpage
[youtube] vlXK8yHyog8: Downloading android player API JSON
[youtube] vlXK8yHyog8: Downloading MPD manifest
[youtube] vlXK8yHyog8: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] vlXK8yHyog8: Downloading 1 format(s): 135
[debug] Invoking dashsegments downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1664203496/ei/iGYxY8XKH5j-gAf4nbr4CA/ip/91.121.16.203/id/be55caf321f2a20f/source/youtube/requiressl/yes/playback_host/rr5---sn-25glenez.googlevideo.com/mh/ea/mm/31%2C29/mn/sn-25glenez%2Csn-25ge7nsl/ms/au%2Crdu/mv/m/mvi/5/pl/16/tx/24280135/txs/24280135%2C24280136%2C24280137%2C24280138%2C24280139/hfr/1/as/fmp4_audio_clear%2Cfmp4_sd_hd_clear/initcwndbps/228750/spc/yR2vp-nAWDAdHPMqDsfGTTMzht--hbE/vprv/1/mt/1664181664/fvip/6/itag_bl/376%2C377%2C384%2C385%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cspc%2Cvprv%2Citag/sig/AOq0QJ8wRgIhAOwKqBuxne-tiIBWectETQVGAb3pz7Rz5UZzai0kcjBnAiEAtQyume1FyZmZ6vO5URYqzyK0qd7jankdWkLn_d_a83c%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRAIgLhIYtw0x4_bYRFRErV5Wl-3l2BjR_WSAPOgHSF1XgcICIGuX109E1TaJtnLuvJlyqGUIvpGjPxlLlceaU5kLTWFK"
[dashsegments] Total fragments: 16
[download] Destination: Dan Mohler - Biggest Problem On The Planet (It's not ISIS) [vlXK8yHyog8].mp4
[download] 100% of 5.83MiB in 00:01 at 4.13MiB/s

**Comment by clusterized** [comment] 2022-09-26 11:37
`--compat-options multistreams --ppa "Merger:-map -1:v"`

**Comment by gamer191** [comment] 2022-09-26 13:05
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2228

**Comment by Otw-cz** [comment] 2022-09-26 13:09
> `--compat-options multistreams --ppa "Merger:-map -1:v"`

Thank you very much! 
youtube-dl -f 135+18 --merge-output-format mp4 --compat-options multistreams --ppa "Merger:-map -1:v" vlXK8yHyog8
works for me :-)

**Closed** 2022-09-26 15:51 UTC
Labels: duplicate, question

**Comment by clusterized** [comment] 2022-09-26 16:21
Oh, I just noticed that using `--video-multistreams` instead of `--compat-options multistreams` achieves the same thing here. Not that it really matters, it's just shorter and more precise.
