### ISSUE TITLE
Download N last videos from channel/playlist

### ISSUE THREAD

**Issue by xoid** [yt-dlp/yt-dlp#4003] opened 2022-06-07 09:00 UTC
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Would be great to limit downloading from channel/playlist by N newest videos only.
I've try 
--playlist-reverse --max-downloads 6
but it didnt help. 
--dateafter is also not exactly what I want (And works way long)

**Comment by pukkandan** [comment] 2022-06-07 11:13
Duplicate of #2951

**Closed by pukkandan** 2022-06-07 11:13 UTC
Labels: enhancement
