### ISSUE TITLE
[RaiPlay] Audio not present in downloaded file

### ISSUE THREAD

**Issue by rgabbo** [yt-dlp/yt-dlp#2918] opened 2022-03-01 18:04 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Description

Some new videos, when downloaded, miss the audio track.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://www.raiplay.it/video/2022/02/Vostro-Onore-S1E1-1cfec896-afdd-4b28-b4f7-dec1464d428a.html']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 5.0-essentials_build-www.gyan.dev (setts), ffprobe 5.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [RaiPlay] Extracting URL: https://www.raiplay.it/video/2022/02/Vostro-Onore-S1E1-1cfec896-afdd-4b28-b4f7-dec1464d428a.html
[RaiPlay] 1cfec896-afdd-4b28-b4f7-dec1464d428a: Downloading video JSON
[RaiPlay] 1cfec896-afdd-4b28-b4f7-dec1464d428a: Downloading XML metadata for platform mon
[RaiPlay] 1cfec896-afdd-4b28-b4f7-dec1464d428a: Downloading m3u8 information
[RaiPlay] 1cfec896-afdd-4b28-b4f7-dec1464d428a: Downloading XML metadata for platform flash
[RaiPlay] 1cfec896-afdd-4b28-b4f7-dec1464d428a: Downloading XML metadata for platform native
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1cfec896-afdd-4b28-b4f7-dec1464d428a: Downloading 1 format(s): hls-2400
[debug] Invoking downloader on "https://StreamCdnG42-b70cb04c54ab478189e9d8ee45637b13.msvdn.net/ostr2/podcastcdn/teche_root/YT_ITALIA_TECHE_HD_multiaudio/XJ8pNYi66NQgCJzDen63qweeqqEEqualeeqqEEqual_,1200,1800,2400/chunklist_b2344000_vo_slita_t64MjQwMA==.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 317
[download] Destination: Vostro Onore - S1E1 [1cfec896-afdd-4b28-b4f7-dec1464d428a].mp4
[download] 100% of 933.76MiB in 02:30
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:Vostro Onore - S1E1 [1cfec896-afdd-4b28-b4f7-dec1464d428a].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Vostro Onore - S1E1 [1cfec896-afdd-4b28-b4f7-dec1464d428a].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Vostro Onore - S1E1 [1cfec896-afdd-4b28-b4f7-dec1464d428a].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:Vostro Onore - S1E1 [1cfec896-afdd-4b28-b4f7-dec1464d428a].temp.mp4"
```

**Comment by dirkf** [comment] 2022-03-02 17:05
Looks like [this problem](https://github.com/ytdl-org/youtube-dl/issues/27830), with untested patch. yt-dl gets no video formats at all from the UK.

**Comment by pukkandan** [comment] 2022-03-15 21:46
Duplicate of #887

**Closed by pukkandan** 2022-03-15 21:46 UTC
Labels: site-bug
