### ISSUE TITLE
Getting Error while downloading Douyin (Chinese tiktok) videos

### ISSUE THREAD

**Issue by OR3ACH** [yt-dlp/yt-dlp#11825] opened 2024-12-15 13:41 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

America

### Provide a description that is worded well enough to be understood

It asks for cookies (fresh without login should be fine it says), but still doesn't works and gives Warning and Error.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://v.douyin.com/iUr4dn2E/', '--cookies', './cookie.txt']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version nightly@2024.12.13.232928 from yt-dlp/yt-dlp-nightly-builds [2037a6414] (zip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-6.1.0-26-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.7-0, ffprobe 4.3.7-0
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.34.1, urllib3-2.2.3, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.12.13.232928 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.12.13.232928 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://v.douyin.com/iUr4dn2E/
[generic] iUr4dn2E: Downloading webpage
[redirect] Following redirect to https://www.douyin.com/video/7446663995907378466?previous_page=app_code_link
[Douyin] Extracting URL: https://www.douyin.com/video/7446663995907378466?previous_page=app_code_link
[Douyin] 7446663995907378466: Downloading web detail JSON
WARNING: [Douyin] 7446663995907378466: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
ERROR: [Douyin] 7446663995907378466: Fresh cookies (not necessarily logged in) are needed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/container/apps/ytdl/./yt-dlp/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/home/container/apps/ytdl/./yt-dlp/yt_dlp/extractor/tiktok.py", line 1342, in _real_extract
    raise ExtractorError(
```

**Comment by bashonly** [comment] 2024-12-15 14:30
Duplicate of #9667

***Please*** check the PINNED **KNOWN ISSUES** thread before opening a new issue

**Closed by bashonly** 2024-12-15 14:30 UTC
Labels: duplicate, site-bug, site:tiktok
