### ISSUE TITLE
What changed in audio extraction command in v12.25? How to pass arguments now?

### ISSUE THREAD

**Issue by Tinase-nau** [yt-dlp/yt-dlp#2118] opened 2021-12-25 19:18 UTC
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Updated from v12.01 to v12.25, now my script doesn't work as intended.
It downloads fine, but audio extraction is now broken. Did something change in that part?
I was using this code for extracting:
`-x --audio-format flac --ppa "ExtractAudio+ffmpeg:-compression_level 0 -ac 2"`
Now with v12.25 I get this error
`Codec AVOption compression_level () specified for input file #0 (file:C:\*SNIP*) is not a decoding option.`
What do I need to do differently now?

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '-i', '-w', '-f', 'bestaudio', '--ffmpeg-location', 'C:\\Program Files\\FFmpeg', '-x', '--audio-format', 'flac', '--ppa', 'ExtractAudio+ffmpeg:-compression_level 0 -ac 2', '-o', 'C:\\Users\\Administrator\\Desktop\\MEDIASOURCE\\%(title)s.%(ext)s', '-a', 'URLS TO DOWNLOAD.txt']
[debug] Batch file urls: ['https://youtu.be/vRljsm_kyDk']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.25 [87e0499] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg n4.4.1-3-g9d88dd17ef-20211204 (setts), ffprobe n4.4.1-3-g9d88dd17ef-20211204
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.25, Current version: 2021.12.25
yt-dlp is up to date (2021.12.25)
[debug] [youtube] Extracting URL: https://youtu.be/vRljsm_kyDk
[youtube] vRljsm_kyDk: Downloading webpage
[youtube] vRljsm_kyDk: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] vRljsm_kyDk: Downloading 1 format(s): 251
[debug] Invoking downloader on "https://rr6---sn-nu5gh5o-uaal.googlevideo.com/videoplayback?expire=1640481027&ei=o2zHYb72DtqTv_IPoYOPyA0&ip=87.119.182.189&id=o-APXg3rsb1srgvditWL2ams6sk15raHKlWeoUtNSXdLKQ&itag=251&source=youtube&requiressl=yes&mh=ZH&mm=31%2C29&mn=sn-nu5gh5o-uaal%2Csn-5goeen7k&ms=au%2Crdu&mv=m&mvi=6&pl=25&gcr=ee&initcwndbps=1100000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=7939853&dur=438.261&lmt=1605330141450682&mt=1640459108&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=1311222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAM-XHV0who530PpGpRbEbugahfEWiFC_6t9NrwXVnvh7AiA23EPRL63Bi_ZJ60V56v0D-c151f6Izolo4eYXmaqbxg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgW_BNpmUJ8MHg88Uq2rchcB7FViUjafKFtrv52ii66igCIQD_SHS37bC2FZ3g-qKIL_WM_SFLg37EKi67dRLsHyR5Wg%3D%3D"
[download] Destination: C:\Users\Administrator\Desktop\MEDIASOURCE\The Clouds.webm
[download] 100% of 7.57MiB in 00:02
[debug] ffmpeg command line: "C:\Program Files\FFmpeg\ffprobe" -show_streams "file:C:\Users\Administrator\Desktop\MEDIASOURCE\The Clouds.webm"
[ExtractAudio] Destination: C:\Users\Administrator\Desktop\MEDIASOURCE\The Clouds.flac
[debug] ffmpeg command line: "C:\Program Files\FFmpeg\ffmpeg" -y -loglevel "repeat+info" -compression_level 0 -ac 2 -i "file:C:\Users\Administrator\Desktop\MEDIASOURCE\The Clouds.webm" -vn -acodec flac -movflags "+faststart" "file:C:\Users\Administrator\Desktop\MEDIASOURCE\The Clouds.flac"
[debug] ffmpeg version n4.4.1-3-g9d88dd17ef-20211204 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10-win32 (GCC) 20210610
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --disable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --disable-vulkan --disable-libglslang --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20211204
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, matroska,webm, from 'file:C:\Users\Administrator\Desktop\MEDIASOURCE\The Clouds.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:07:18.26, start: -0.007000, bitrate: 144 kb/s
  Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Codec AVOption compression_level () specified for input file #0 (file:C:\Users\Administrator\Desktop\MEDIASOURCE\The Clouds.webm) is not a decoding option.
ERROR: audio conversion failed: Codec AVOption compression_level () specified for input file #0 (file:C:\Users\Administrator\Desktop\MEDIASOURCE\The Clouds.webm) is not a decoding option.
Traceback (most recent call last):
  File "yt_dlp\postprocessor\ffmpeg.py", line 434, in run_ffmpeg
  File "yt_dlp\postprocessor\ffmpeg.py", line 326, in run_ffmpeg
  File "yt_dlp\postprocessor\ffmpeg.py", line 280, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 319, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Codec AVOption compression_level () specified for input file #0 (file:C:\Users\Administrator\Desktop\MEDIASOURCE\The Clouds.webm) is not a decoding option.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\postprocessor\ffmpeg.py", line 508, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 436, in run_ffmpeg
yt_dlp.postprocessor.common.AudioConversionError: Codec AVOption compression_level () specified for input file #0 (file:C:\Users\Administrator\Desktop\MEDIASOURCE\The Clouds.webm) is not a decoding option.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3176, in run_pp
  File "yt_dlp\postprocessor\common.py", line 22, in run
  File "yt_dlp\postprocessor\common.py", line 117, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 510, in run
yt_dlp.utils.PostProcessingError: audio conversion failed: Codec AVOption compression_level () specified for input file #0 (file:C:\Users\Administrator\Desktop\MEDIASOURCE\The Clouds.webm) is not a decoding option.
```

**Comment by pukkandan** [comment] 2021-12-27 02:47
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2112, fixed in new release

**Closed by pukkandan** 2021-12-27 02:47 UTC
Labels: question
