### ISSUE TITLE
Broken video on 8/1 Face the Nation

### ISSUE THREAD

**Issue by mindbomb** [yt-dlp/yt-dlp#618] opened 2021-08-02 23:35 UTC
Off the cbs website, the full 8/1 episode of Face the Nation can be downloaded. However, after approximately 6 mins, the video becomes unplayable. This problem is in the current version of yt-dlp, but not in youtube-dl.

```
C:\WINDOWS\system32>yt-dlp https://www.cbsnews.com/video/81-fauci-manchin-kashkari-alroy-preis-gottlieb/ -v
[debug] User config file: C:\Users\xstre\AppData\Roaming\yt-dlp\config.txt
[debug] User config: ['-o', 'F:\\Chrome Downloads\\%(title)s.%(ext)s', '-S', 'res:1080', '--ffmpeg-location', 'C:\\Program Files\\yt-dlp']
[debug] Command-line config: ['https://www.cbsnews.com/video/81-fauci-manchin-kashkari-alroy-preis-gottlieb/', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.24 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.2-2021-02-20-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-20-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [cbsnews] Extracting URL: https://www.cbsnews.com/video/81-fauci-manchin-kashkari-alroy-preis-gottlieb/
[cbsnews] 81-fauci-manchin-kashkari-alroy-preis-gottlieb: Downloading webpage
[cbsnews] HOStQR3ItyoBcPBUlclyTCdoT99d_MKl: Downloading XML
[cbsnews] HOStQR3ItyoBcPBUlclyTCdoT99d_MKl: Downloading PDL_MP4 SMIL data
[cbsnews] HOStQR3ItyoBcPBUlclyTCdoT99d_MKl: Checking video URL
[cbsnews] HOStQR3ItyoBcPBUlclyTCdoT99d_MKl: Downloading StreamPack SMIL data
[cbsnews] HOStQR3ItyoBcPBUlclyTCdoT99d_MKl: Downloading m3u8 information
[cbsnews] HOStQR3ItyoBcPBUlclyTCdoT99d_MKl: Downloading Downloadable SMIL data
[cbsnews] HOStQR3ItyoBcPBUlclyTCdoT99d_MKl: Checking video URL
[cbsnews] HOStQR3ItyoBcPBUlclyTCdoT99d_MKl: Downloading HLS_CLEAR SMIL data
[cbsnews] HOStQR3ItyoBcPBUlclyTCdoT99d_MKl: Downloading m3u8 information
[debug] Sort order given by user: res:1080
[debug] Formats sorted by: hasvid, ie_pref, lang, res:1080(1080.0), quality, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[cbsnews] HOStQR3ItyoBcPBUlclyTCdoT99d_MKl: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
[info] HOStQR3ItyoBcPBUlclyTCdoT99d_MKl: Downloading 1 format(s): hls-3183+hls-96
[debug] Invoking downloader on "https://prod.vodvideo.cbsnews.com/cbsnews/vr/hls/2021/07/20/1923899459703/764365_hls/ftn_080121_ms_PRORES_2CH_2997P_764365_3000/stream.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 463
[download] Destination: F:\Chrome Downloads\8_1 - Fauci, Manchin, Kashkari, Alroy-Preis, Gottlieb.fhls-3183.mp4
[download] 100% of 1006.63MiB in 02:03
[debug] Invoking downloader on "https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/07/20/1923899459703/ftn_080121_ms_PRORES_2CH_2997P_764369_,2228,4628,3128,1628,848,503,000.mp4.csmil/index_5_a.m3u8?null=0&id=AgBg73mPFys7z8R%2fCGGEmUFJzXGaRltnn2weWC55ew8j6RgwzpAsmg0r%2fjP1VYllATqe4uSnku6DDw%3d%3d&hdntl=exp=1628033348~acl=%2fi%2ftemp_hd_gallery_video%2fCBS_Production_Outlet_VMS%2fvideo_robot%2fCBS_Production_Entertainment%2f2021%2f07%2f20%2f1923899459703%2fftn_080121_ms_PRORES_2CH_2997P_764369_*~data=hdntl~hmac=578430917ab77b925346f0c1f0c0bb9225cab1868dd7328b3d9b00730fbc757f"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 277
[download] Destination: F:\Chrome Downloads\8_1 - Fauci, Manchin, Kashkari, Alroy-Preis, Gottlieb.fhls-96.mp4
[download] 100% of 39.18MiB in 00:22
[Merger] Merging formats into "F:\Chrome Downloads\8_1 - Fauci, Manchin, Kashkari, Alroy-Preis, Gottlieb.mp4"
[debug] ffmpeg command line: "C:\Program Files\yt-dlp\ffmpeg" -y -loglevel "repeat+info" -i "file:F:\Chrome Downloads\8_1 - Fauci, Manchin, Kashkari, Alroy-Preis, Gottlieb.fhls-3183.mp4" -i "file:F:\Chrome Downloads\8_1 - Fauci, Manchin, Kashkari, Alroy-Preis, Gottlieb.fhls-96.mp4" -c copy -map "0:v:0" -map "1:a:0" "file:F:\Chrome Downloads\8_1 - Fauci, Manchin, Kashkari, Alroy-Preis, Gottlieb.temp.mp4"
Deleting original file F:\Chrome Downloads\8_1 - Fauci, Manchin, Kashkari, Alroy-Preis, Gottlieb.fhls-96.mp4 (pass -k to keep)
Deleting original file F:\Chrome Downloads\8_1 - Fauci, Manchin, Kashkari, Alroy-Preis, Gottlieb.fhls-3183.mp4 (pass -k to keep)
[debug] ffmpeg command line: "C:\Program Files\yt-dlp\ffprobe" -show_streams "file:F:\Chrome Downloads\8_1 - Fauci, Manchin, Kashkari, Alroy-Preis, Gottlieb.mp4"
[FixupM3u8] Fixing malformed AAC bitstream of "F:\Chrome Downloads\8_1 - Fauci, Manchin, Kashkari, Alroy-Preis, Gottlieb.mp4"
[debug] ffmpeg command line: "C:\Program Files\yt-dlp\ffmpeg" -y -loglevel "repeat+info" -i "file:F:\Chrome Downloads\8_1 - Fauci, Manchin, Kashkari, Alroy-Preis, Gottlieb.mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc "file:F:\Chrome Downloads\8_1 - Fauci, Manchin, Kashkari, Alroy-Preis, Gottlieb.temp.mp4"
```

**Comment by october262** [comment] 2021-08-03 00:32
try updating again, the latest version is 2021.08.02 - https://www.videohelp.com/software/yt-dlp

**Comment by pukkandan** [comment] 2021-08-03 00:33
> [FixupM3u8] Fixing malformed AAC bitstream of "F:\Chrome Downloads\8_1 - Fauci, Manchin, Kashkari, Alroy-Preis, Gottlieb.mp4"

Seems ffmpeg completely breaks the audio stream when doing this. Using `ffmpeg 3.0.1` gives me the undamaged file. You can either downgrade your ffmpeg to this version, or download using ffmpeg itself (`--downloader m3u8:ffmpeg`) so that fixup is not needed

----

Also, next time **DONOT skip the issue template**

**Comment by pukkandan** [comment] 2021-09-16 20:29
#998 is a duplicate of this. But more discussion about this issue has happened there. So closing this instead as duplicate

**Closed by pukkandan** 2021-09-16 20:29 UTC
Labels: external issue
