### ISSUE TITLE
Redgifs.com extractor: Unable to extract oauth token

### ISSUE THREAD

**Issue by minimaldevofnull** [yt-dlp/yt-dlp#5377] opened 2022-10-28 06:44 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

Unable to download videos from redgifs.com

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--proxy', 'socks5://127.0.0.1:9090', '-F', 'https://redgifs.com/watch/bubblypalatablehogget']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] API
[debug] Python 3.10.4 (CPython 64bit) - Linux-5.18.1-arch1-1-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: certifi-2021.10.08, sqlite3-2.6.0
[debug] Proxy map: {'http': 'socks5://127.0.0.1:9090', 'https': 'socks5://127.0.0.1:9090'}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [RedGifs] Extracting URL: https://redgifs.com/watch/bubblypalatablehogget
[RedGifs] bubblypalatablehogget: Downloading webpage
[RedGifs] bubblypalatablehogget: Downloading webpage
ERROR: [RedGifs] bubblypalatablehogget: Unable to extract oauth token; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/redgifs.py", line 153, in _real_extract
    video_info = self._call_api(
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/redgifs.py", line 82, in _call_api
    self._fetch_oauth_token(video_id)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/redgifs.py", line 76, in _fetch_oauth_token
    oauth_token = self._html_search_regex(
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1260, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1224, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment] 2022-10-29 22:37
Fixed in 0c908911f9e9f348a5036c35f2906615347c4aa2

Wait for the next release, or [install the master branch with PIP](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip)

Duplicate of #5311

**Closed by bashonly** 2022-10-29 22:37 UTC
Labels: duplicate, site-bug
