### ISSUE TITLE
HTTP Error 503 error even with 1000 retries, browser working fine

### ISSUE THREAD

**Issue by Feathered-Serpent** [yt-dlp/yt-dlp#2559] opened 2022-01-31 13:32 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Upon trying to download https://www.youtube.com/watch?v=xtkxUUsp92I I get the logged error. Watching the video in the browser works without problems. Other videos of the same playlist also work without errors upon download. I even tried with -R 1000, but it's not downloading a single byte, so I thought this might quality as a bug. (I shortened the protocol, as between attempt 10 and attempt 990 the entries always looked the same just with higher retry number)

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-R', '1000', 'https://www.youtube.com/watch?v=xtkxUUsp92I']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-01-05-git-66deab3a26-full_build-www.gyan.dev, ffprobe 2021-01-05-git-66deab3a26-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=xtkxUUsp92I
[youtube] xtkxUUsp92I: Downloading webpage
[youtube] xtkxUUsp92I: Downloading android player API JSON
[youtube] xtkxUUsp92I: Downloading MPD manifest
[youtube] xtkxUUsp92I: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] xtkxUUsp92I: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1643657106/ei/MuP3YZftE9KN1gLlkrCwBA/ip/5.61.188.199/id/c6d931514b29f762/source/youtube/requiressl/yes/playback_host/rr5---sn-4g5e6nzs.googlevideo.com/mh/pe/mm/31%2C26/mn/sn-4g5e6nzs%2Csn-5hneknee/ms/au%2Conr/mv/m/mvi/5/pl/23/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/gcr/de/initcwndbps/2487500/vprv/1/mt/1643635006/fvip/5/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cgcr%2Cvprv%2Citag/sig/AOq0QJ8wRAIgX49L0wOjPZxus-7zkUzvdNlyXWcPuWzGROMtHl4KNaYCIERbPGZRvtucCq5b17AwTkcBc2Vnf-RFf4Lsm6Ej8EE_/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhAM82hNSj-Cv1ouW_ji1u1M-iN-n_OvSOg4XkMKh0QgmXAiEAkHIi6dhByxdA0lA_EVD5WovmzjWT0yZL3J9BV3XGR1c%3D"
[dashsegments] Total fragments: 66
[download] Destination: SQUAT RAGE!!!11!1!1elf [xtkxUUsp92I].f248.webm
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 1 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 2 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 3 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 4 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 5 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 7 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 8 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 9 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 10 of 1000) ...
[...]
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 990 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 991 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 992 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 993 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 994 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 995 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 996 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 997 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 998 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 999 of 1000) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 1000 of 1000) ...
ERROR: giving up after 1000 retries
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 849, in main
  File "yt_dlp\__init__.py", line 839, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3180, in download
  File "yt_dlp\YoutubeDL.py", line 3153, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1358, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1503, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2589, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3036, in process_info
  File "yt_dlp\YoutubeDL.py", line 2769, in dl
  File "yt_dlp\downloader\common.py", line 440, in download
  File "yt_dlp\downloader\dash.py", line 56, in real_download
  File "yt_dlp\downloader\fragment.py", line 382, in download_and_append_fragments_multiple
  File "yt_dlp\downloader\fragment.py", line 515, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 449, in download_fragment
  File "yt_dlp\downloader\fragment.py", line 133, in _download_fragment
  File "yt_dlp\downloader\common.py", line 440, in download
  File "yt_dlp\downloader\http.py", line 385, in real_download
  File "yt_dlp\downloader\common.py", line 177, in report_error
  File "yt_dlp\YoutubeDL.py", line 923, in report_error
  File "yt_dlp\YoutubeDL.py", line 853, in trouble

ERROR: unable to download video data: [Errno 2] No such file or directory: 'SQUAT RAGE!!!11!1!1elf [xtkxUUsp92I].f248.webm.part-Frag1'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3036, in process_info
  File "yt_dlp\YoutubeDL.py", line 2769, in dl
  File "yt_dlp\downloader\common.py", line 440, in download
  File "yt_dlp\downloader\dash.py", line 56, in real_download
  File "yt_dlp\downloader\fragment.py", line 382, in download_and_append_fragments_multiple
  File "yt_dlp\downloader\fragment.py", line 515, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 449, in download_fragment
  File "yt_dlp\downloader\fragment.py", line 139, in _download_fragment
  File "yt_dlp\downloader\fragment.py", line 142, in _read_fragment
  File "yt_dlp\downloader\common.py", line 218, in sanitize_open
  File "yt_dlp\utils.py", line 669, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'SQUAT RAGE!!!11!1!1elf [xtkxUUsp92I].f248.webm.part-Frag1'
```

**Comment by pukkandan** [comment] 2022-01-31 14:55
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/502

Use `--check-formats`

**Closed by pukkandan** 2022-01-31 14:55 UTC
Labels: bug, triage
