### ISSUE TITLE
An alternative option to --mtime that uses the original upload date instead of Last-Modified

### ISSUE THREAD

**Issue by Wryyyong** [yt-dlp/yt-dlp#2353] opened 2022-01-15 20:32 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When organising video collections, I've a habit of sorting the directory by `Date modified` in the hopes it will match the upload order. Unfortunately, as `--mtime` uses `Last-Modified`, that isn't always the case.

An alternative option to the command that applies the video's original upload date instead of `Last-Modified` would be useful for serial organisation.

**Comment by pukkandan** [comment] 2022-01-16 05:20
Duplicate of #903

**Closed by pukkandan** 2022-01-16 05:20 UTC
Labels: enhancement, triage

**Comment by Wryyyong** [comment] 2022-01-16 05:42
Bleh, I did what I believe to be a thorough dig through the bugtracker and never noticed that.

Ah well.
