### ISSUE TITLE
Arte.tv HTTP Error 404

### ISSUE THREAD

**Issue by Steveland** [yt-dlp/yt-dlp#3637] opened 2022-05-04 08:22 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Arte.tv broken with HTTP Error 404

### Verbose log

```shell
C:\Users\Me\Desktop\yt-dlp>yt-dlp.exe -Uv "https://www.arte.tv/fr/videos/100225-000-A/sagrada-familia-le-defi-de-gaudi/"
[debug] Command-line config: ['-Uv', 'https://www.arte.tv/fr/videos/100225-000-A/sagrada-familia-le-defi-de-gaudi/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.7.9 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [ArteTV] Extracting URL: https://www.arte.tv/fr/videos/100225-000-A/sagrada-familia-le-defi-de-gaudi/
[ArteTV] 100225-000-A: Downloading JSON metadata
ERROR: [ArteTV] 100225-000-A: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\arte.py", line 58, in _real_extract
  File "yt_dlp\extractor\common.py", line 1033, in _download_json
  File "yt_dlp\extractor\common.py", line 1011, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 800, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 785, in _request_webpage

  File "yt_dlp\extractor\common.py", line 767, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3601, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 641, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by lcheylus** [comment] 2022-05-04 09:13
Issue with Arte API v1 (now completely down), see #3302

**Comment by pukkandan** [comment] 2022-05-04 14:30
Duplicate of #3622

**Closed by pukkandan** 2022-05-04 14:30 UTC
Labels: site-bug, triage
