### ISSUE TITLE
Paramount+ Global

### ISSUE THREAD

**Issue by LouBlu08** [yt-dlp/yt-dlp#5033] opened 2022-09-25 17:21 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia/Europe

### Example URLs

https://www.paramountplus.com/shows/calvin-and-kaisons-play-power/video/8JEcCgqfaKcvBf6AJMFGsvT0MYte_RUm/calvin-and-kaison-s-play-power-ultimate-hero/
https://www.paramountplus.com/shows/aerial-america/video/K_8IrDKmGoTe4Mnqfti0JQuvzb8MLRCM/aerial-america-california/

### Provide a description that is worded well enough to be understood

I've noticed a lot of content on international versions of P+ currently aren't available on the US version (both shows and language options). For some reason, only the US version of P+ is supported (if you try and access a UK show with a US account, it won't work, but if you try and access a Australian show with a UK account, it works just fine), any time I try to rip stuff from a international version (i.e, Mexico or Australia), it gives me a 403 error. It would be neat if you could add support for the other countries in the future.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.paramountplus.com/shows/blues-clues/video/YZqYwu9sJNARDyM1huzbEwC5jzeW6sXB/blue-s-clues-snack-time/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-04-03-git-1291568c98-full_build-www.gyan.dev (setts), ffprobe 4.4-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [ParamountPlus] Extracting URL: https://www.paramountplus.com/shows/blues-clues/video/YZqYwu9sJNARDyM1huzbEwC5jzeW6sXB/blue-s-clues-snack-time/
[ParamountPlus] YZqYwu9sJNARDyM1huzbEwC5jzeW6sXB: Downloading JSON metadata
ERROR: [ParamountPlus] YZqYwu9sJNARDyM1huzbEwC5jzeW6sXB: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\cbs.py", line 70, in _real_extract
  File "yt_dlp\extractor\paramountplus.py", line 95, in _extract_video_info
  File "yt_dlp\extractor\common.py", line 1030, in download_content
  File "yt_dlp\extractor\common.py", line 994, in download_handle
  File "yt_dlp\extractor\common.py", line 864, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 821, in _request_webpage

  File "yt_dlp\extractor\common.py", line 803, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3656, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment] 2022-12-10 11:47
Duplicate of #4897

**Closed by bashonly** 2022-12-10 11:47 UTC
Labels: site-enhancement, triage
