### ISSUE TITLE
Support local ip servers

### ISSUE THREAD

**Issue by sadtank** [yt-dlp/yt-dlp#10552] opened 2024-07-24 23:52 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

local network

### Example URLs

10.0.0.0        -   10.255.255.255  (10/8 prefix)
172.16.0.0      -   172.31.255.255  (172.16/12 prefix)
192.168.0.0     -   192.168.255.255 (192.168/16 prefix)
*.local
*.internal

### Provide a description that is worded well enough to be understood

I propose that yt-dlp allow local IPs (or include a parameter allowing users to force the attempt.)

yt-dlp already supports youtube front end servers like Invidious. And yt-dlp works on [these public servers](https://docs.invidious.io/instances/) just fine.

However, when running an invidious server on a local network, yt-dlp throws an "Unsupported URL" error. 

For more information on local network top level domains https://serverfault.com/questions/17255/top-level-domain-domain-suffix-for-private-network

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'http://192.168.1.60:3420/watch?v=dQw4w9WgXcQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-44-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, pyxattr-0.7.2, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2024.07.09 from yt-dlp/yt-dlp
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[generic] Extracting URL: http://192.168.1.60:3420/watch?v=dQw4w9WgXcQ
[generic] watch?v=dQw4w9WgXcQ: Downloading webpage
[redirect] Following redirect to http://192.168.1.60:2000/?origin=host&app=invidious&path=%2Fwatch%3Fv%3DdQw4w9WgXcQ
[generic] Extracting URL: http://192.168.1.60:2000/?origin=host&app=invidious&path=%2Fwatch%3Fv%3DdQw4w9WgXcQ
[generic] ?origin=host&app=invidious&path=/watch?v=dQw4w9WgXcQ: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ?origin=host&app=invidious&path=/watch?v=dQw4w9WgXcQ: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: http://192.168.1.60:2000/?origin=host&app=invidious&path=%2Fwatch%3Fv%3DdQw4w9WgXcQ
Traceback (most recent call last):
  File "/home/sadtank/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sadtank/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1757, in __extract_info
    ie_result = ie.extract(url)
  File "/home/sadtank/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/home/sadtank/.local/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2521, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: http://192.168.1.60:2000/?origin=host&app=invidious&path=%2Fwatch%3Fv%3DdQw4w9WgXcQ
```

**Comment by bashonly** [comment] 2024-07-25 03:12
> yt-dlp already supports youtube front end servers like Invidious. And yt-dlp works on [these public servers](https://docs.invidious.io/instances/) just fine.

When you pass a public invidious instance URL to yt-dlp, the only thing that yt-dlp does is capture the youtube video ID from the url and then proceed with extraction from Youtube. yt-dlp does not currently support actually extracting from invidious instances.

What you are requesting would need #8952 (native invidious support) as well as #5103 (self-hosted extractors framework). I am closing this as a duplicate of those two issues

**Closed by bashonly** 2024-07-25 03:12 UTC
Labels: site-request, triage

**Comment by cameronj86** [comment] 2025-05-14 15:57
This is working for me on Debian. 

It never worked when I used an IP address or a `.lan` address w/ an untrusted cert, but once I added the certificate to `/usr/local/share/ca-certificates/` in Debian (also I added it to Firefox but not sure if that's relevant for yt-dlp), I am able to pass-through `.lan` links to yt-dlp w/o error.
