### ISSUE TITLE
motogp

### ISSUE THREAD

**Issue by faber-castel** [yt-dlp/yt-dlp#4113] opened 2022-06-19 16:02 UTC
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

France

### Example URLs

https://www.motogp.com/en/videos/2022/06/19/bagnaia-s-title-dream-hangs-by-a-thread-after-strange-crash/426374

### Description

yt-dlp can't seem to find the different stream and neither download the video from the website. 
As an example, it is possible to download the best quality video (without choosing) with ffmpeg.

to download or check the differents quality of the video, I have to get the "index.mpd" url, which do not stay active during an unlimited time.

### Verbose log

```shell
yt-dlp -vU --no-part --restrict-filenames --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0" --add-header "Cookie:visid_incap_2437617=sBG2fVN8QsKKHsrf3c4jhemKm2EAAAAAQUIPAAAAAABxfAnKfQ6IGHcxW8Au5uWH; visid_incap_2379695=0qHZqh8NRiKlctSYpoNZYd25oGIAAAAAQUIPAAAAAAB9nr9uRdXJhACXO79wcUpc" --referer "https://www.motogp.com/" "https://cdn4.vod.mcr.dorna.com/fe505973c223fa923f02d56612c782bab4d7ad233c4570cb1121e5a8654c016c/1655654459/Z6hFA6VR%2BjsppVExtUxzQFAVh1Mgpnfj9f0MWzug75beCiDkmYxb2wOmE%2F08x5I%2B/101322/index.mpd"
[debug] Command-line config: ['-vU', '--no-part', '--restrict-filenames', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0', '--add-header', 'Cookie:visid_incap_2437617=sBG2fVN8QsKKHsrf3c4jhemKm2EAAAAAQUIPAAAAAABxfAnKfQ6IGHcxW8Au5uWH; visid_incap_2379695=0qHZqh8NRiKlctSYpoNZYd25oGIAAAAAQUIPAAAAAAB9nr9uRdXJhACXO79wcUpc', '--referer', 'https://www.motogp.com/', 'https://cdn4.vod.mcr.dorna.com/fe505973c223fa923f02d56612c782bab4d7ad233c4570cb1121e5a8654c016c/1655654459/Z6hFA6VR%2BjsppVExtUxzQFAVh1Mgpnfj9f0MWzug75beCiDkmYxb2wOmE%2F08x5I%2B/101322/index.mpd']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-187-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: certifi-2018.01.18, pycrypto-2.6.1, pyxattr-0.6.0, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://cdn4.vod.mcr.dorna.com/fe505973c223fa923f02d56612c782bab4d7ad233c4570cb1121e5a8654c016c/1655654459/Z6hFA6VR%2BjsppVExtUxzQFAVh1Mgpnfj9f0MWzug75beCiDkmYxb2wOmE%2F08x5I%2B/101322/index.mpd
[generic] index: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] index: Downloading webpage
[generic] index: Extracting information
ERROR: unsupported operand type(s) for +: 'NoneType' and 'str'
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2847, in _real_extract
    mpd_url=url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 2832, in _parse_mpd_formats_and_subtitles
    base_url = base_url_e.text + base_url
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by pukkandan** [comment] 2022-06-19 20:22
Run the same with `--write-pages` and attach the `.dump` file generated

**Comment by faber-castel** [comment] 2022-06-19 22:31
here it is, thanks
[index_https_-_cdn4.vod.mcr.dorna.com_ae9f3f7805ec83e65c6c43e6b15e4d295b0e6a7459f51b13b045aebe926e23a4_1655678067_zHIE2G0XFZWBy2dIBXd8cMOrnL9uFqFVqo%2FrUm14PcN%2FDRoxt67BCe5I2JcUQ%2FiU_101322_index.mpd.zip](https://github.com/yt-dlp/yt-dlp/files/8936523/index_https_-_cdn4.vod.mcr.dorna.com_ae9f3f7805ec83e65c6c43e6b15e4d295b0e6a7459f51b13b045aebe926e23a4_1655678067_zHIE2G0XFZWBy2dIBXd8cMOrnL9uFqFVqo.2FrUm14PcN.2FDRoxt67BCe5I2JcUQ.2FiU_101322_index.mpd.zip)

**Comment by pukkandan** [comment] 2022-06-19 23:20
Can you check if this fixes it?
```diff
diff --git a/yt_dlp/extractor/common.py b/yt_dlp/extractor/common.py
index 3e3e55798..3e8ba5bdd 100644
--- a/yt_dlp/extractor/common.py
+++ b/yt_dlp/extractor/common.py
@@ -2817,7 +2817,7 @@ def extract_Initialization(source):
                     base_url = ''
                     for element in (representation, adaptation_set, period, mpd_doc):
                         base_url_e = element.find(_add_ns('BaseURL'))
-                        if base_url_e is not None:
+                        if base_url_e and base_url_e.text:
                             base_url = base_url_e.text + base_url
                             if re.match(r'^https?://', base_url):
                                 break
```

**Comment by faber-castel** [comment] 2022-06-20 08:17
it is working !!!!
I also tried to specify a custom resolution and worked without issue.
thanks a lot

**Comment by pukkandan** [comment] 2022-06-20 08:18
This patch breaks some other stuff, so can't be merged as-is. But atleast now I know for sure where the issue is

**Closed** 2022-06-29 01:15 UTC
Labels: site-bug
