### ISSUE TITLE
cannot parse data with cookies (facebook private video)

### ISSUE THREAD

**Issue by halpz** [yt-dlp/yt-dlp#5356] opened 2022-10-25 15:59 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

I am trying to download a Facebook video, it requires a login to view. I have tried --cookies-from-browser and also --cookies cookies.txt but they both say "cannot parse data"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.facebook.com/StanislawVanDobroniak/videos/181168832965369/', '--cookies', '/Users/paul/Downloads/cookies.txt', '-vU']
[debug] User config "/Users/paul/.config/yt-dlp/config": ['--prefer-ffmpeg', '--write-sub', '--sub-lang', 'en', '--merge-output-format', 'mkv', '-f', '(bestvideo+bestaudio)/best', '-o', '~/Downloads/%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.9.15 (CPython 64bit) - macOS-13.0-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [facebook] Extracting URL: https://www.facebook.com/StanislawVanDobroniak/videos/181168832965369/
[facebook] 181168832965369: Downloading webpage
[facebook] 181168832965369: Downloading webpage
ERROR: [facebook] 181168832965369: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.9/site-packages/yt_dlp/extractor/facebook.py", line 705, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.9/site-packages/yt_dlp/extractor/facebook.py", line 651, in _extract_from_url
    raise ExtractorError('Cannot parse data')
```

**Comment by pukkandan** [comment] 2022-12-10 11:25
Duplicate of #4311

**Closed by pukkandan** 2022-12-10 11:25 UTC
Labels: duplicate, site-bug, site:facebook
