### ISSUE TITLE
yt-dlp_linux fails to load

### ISSUE THREAD

**Issue by nicolaasjan** [yt-dlp/yt-dlp#6394] opened 2023-03-02 07:21 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Built from current source (b38cae4) and got it from https://github.com/ytdl-patched/yt-dlp/releases/latest.
(can't raise an issue there)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp_linux -vU
Traceback (most recent call last):
  File "yt_dlp/__main__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "yt_dlp/__init__.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "yt_dlp/cookies.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "yt_dlp/aes.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "yt_dlp/dependencies/__init__.py", line 69, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "yt_dlp/dependencies/Cryptodome.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "Cryptodome/PublicKey/RSA.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "Cryptodome/Math/Numbers.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "Cryptodome/Math/_IntegerGMP.py", line 100, in <module>
  File "Cryptodome/Util/_raw_api.py", line 193, in load_lib
  File "os.py", line 680, in __getitem__
KeyError: 'CONDA_PREFIX'
[17110] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by nicolaasjan** [comment] 2023-03-02 08:20
Version 2023.02.27.334 [4b01018] was the last good one.

**Comment by nicolaasjan** [comment] 2023-03-02 08:29
I'm aware this may not be the right place to ask about unofficial versions, but it seems important enough.

**Comment by pukkandan** [comment] 2023-03-02 17:58
Could you show me the output of `yt-dlp -svu1 -p2 test:BiliIntl` from a working version?

**Comment by Grub4K** [comment] 2023-03-02 18:09
I think `cffi` is not correctly imported in Cryptodome. We just have to yield it as an import:
```diff
diff --git a/yt_dlp/__pyinstaller/hook-yt_dlp.py b/yt_dlp/__pyinstaller/hook-yt_dlp.py
index 63dcdffe0..9327bef64 100644
--- a/yt_dlp/__pyinstaller/hook-yt_dlp.py
+++ b/yt_dlp/__pyinstaller/hook-yt_dlp.py
@@ -3,23 +3,24 @@
 from PyInstaller.utils.hooks import collect_submodules


-def pycryptodome_module():
+def pycryptodome_modules():
     try:
         import Cryptodome  # noqa: F401
+        yield 'Cryptodome'
+        yield 'cffi'
     except ImportError:
         try:
             import Crypto  # noqa: F401
             print('WARNING: Using Crypto since Cryptodome is not available. '
                   'Install with: pip install pycryptodomex', file=sys.stderr)
-            return 'Crypto'
+            yield 'Crypto'
         except ImportError:
             pass
-    return 'Cryptodome'


 def get_hidden_imports():
     yield 'yt_dlp.compat._legacy'
-    yield pycryptodome_module()
+    yield from pycryptodome_modules()
     yield from collect_submodules('websockets')
     # These are auto-detected, but explicitly add them just in case
     yield from ('mutagen', 'brotli', 'certifi')
```
Confirmed working by @bashonly. Maybe the `Crypto` module also needs some help

**Comment by pukkandan** [comment] 2023-03-02 18:15
> Confirmed working

Assuming this was checked with an autobuild, you can commit

**Comment by nicolaasjan** [comment] 2023-03-02 18:30
> Could you show me the output of `yt-dlp -svu1 -p2 test:BiliIntl` from a working version?

```
yt-dlp_linux -svu1 -p2 test:BiliIntl
[debug] Command-line config: ['-svu1', '-p2', 'test:BiliIntl']
[debug] User config "/home/nico/.config/yt-dlp/config": ['--rm-cache-dir', '-o', '/dev/shm/test-dlp/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4][vcodec!*=av01]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--no-mtime', '--add-metadata', '--convert-thumbnails', 'jpg', '--embed-thumbnail', '--ppa', 'ThumbnailsConvertor:-qmin 1 -q:v 1', '--ppa', 'ffmpeg:-metadata synopsis=""', '--force-ipv4', '--sponsorblock-remove', 'all', '--console-title']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] ytdl-patched/yt-dlp version 2023.02.27.334 [4b01018] (linux_exe)
[debug] ** This build is unofficial daily builds, provided for ease of use.
[debug] ** Please do not ask for any support.
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux-5.4.0-139-generic-x86_64-with-glibc2.31 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.31)
[debug] exe versions: ffmpeg N-109874-gaeceefa622-Nico-20230218 (fdk,setts), ffprobe N-109874-gaeceefa622-Nico-20230218, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
Removing cache dir /home/nico/.cache/yt-dlp ...
[TestURL] Extracting URL: test:BiliIntl
[TestURL] Test URL: https://www.bilibili.tv/en/play/34613/341736
[BiliIntl] Downloading login key
ERROR: An extractor error has occurred. (caused by KeyError('CONDA_PREFIX')); please report this issue on  https://github.com/ytdl-patched/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 690, in extract
  File "yt_dlp/extractor/common.py", line 596, in initialize
  File "yt_dlp/extractor/bilibili.py", line 904, in _perform_login
  File "yt_dlp/compat/compat_utils.py", line 36, in __getattribute__
  File "yt_dlp/compat/compat_utils.py", line 54, in __getattr__
  File "yt_dlp/compat/compat_utils.py", line 73, in from_child
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "Cryptodome/PublicKey/RSA.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "Cryptodome/Math/Numbers.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "Cryptodome/Math/_IntegerGMP.py", line 100, in <module>
  File "Cryptodome/Util/_raw_api.py", line 193, in load_lib
  File "os.py", line 680, in __getitem__
KeyError: 'CONDA_PREFIX'

```

**Comment by Grub4K** [comment] 2023-03-02 18:49
False alert, the previous fix didnt seem to have worked. The auto-build that was working was from master which was from before dependency restructuring...

**Comment by Grub4K** [comment] 2023-03-02 21:54
The issue was `cffi` after all (again). I fixed it providing it as an additional dep to the `mamba` reqs. See [this](https://github.com/Grub4K/actions-test/compare/merged..merged-conda) for the diff. Alternatively we can add `cffi` to the requirements, I remember [issues with that before](https://github.com/yt-dlp/yt-dlp/issues/6272#issuecomment-1435437647) as well, it seems to be a hard req on linux(?). Maybe `cffi; sys_platform == 'linux'`?

The binary can be downloaded from the actions-test [artifacts](https://github.com/Grub4K/actions-test/actions/runs/4318371691) for testing. `yt-dlp_linux` from there on Windows WSL (which reprod. the error before) now works.

**Comment by bashonly** [comment] 2023-03-03 05:45
For reference:

Option 1. only require `cffi` for conda/mamba builds
 * diff: https://github.com/Grub4K/actions-test/commit/1c0aaa70aaefe4533224a476e8e82ee1412b8413
 * [working artifacts/builds](https://github.com/Grub4K/actions-test/actions/runs/4320073080)

Option 2. `cffi` for all
 * diff: https://github.com/Grub4K/actions-test/commit/d0d002daf7b109bbde4cac867ab35eebafafa6a9
 * [working artifacts/builds](https://github.com/Grub4K/actions-test/actions/runs/4320054328)

Both of the above patches are based on [master merged into the automated releases PR branch](https://github.com/Grub4K/actions-test/commit/ddfe4c511e54dc63007b82f6d1a1de619a84f035), which yields the same [broken `yt-dlp_linux` build](https://github.com/Grub4K/actions-test/actions/runs/4313867145) on its own

I think option 2 will prevent future headaches and is the way to go unless there's a downside I'm unaware of

> So the bug existed in older versions too, and the recent restructuring of dependencies just brought it to the front

Looks like the problem has existed since the conda build PR was merged. I get the same CONDA_PREFIX KeyError from running the BiliIntl test with `2022.11.11`

**Comment by pukkandan** [comment] 2023-03-03 07:01
Add (1) to the release PR for now[^1] for now since we don't know if there's any other consequence to installing cffi on other platforms

[^1]: I'll cherry pick it out. No point fixing in current build script causing merge conflict

**Comment by mlampe** [comment] 2023-03-03 18:46
`Cryptodome` searches the system for `libgmp.so*` at run-time to `dlopen` it if found. If `cffi` is available, a prefered code path is used. But the default code path ends in searching the current `conda` environment (pointed to by `$CONDA_PREFIX`) and terminates fatally if there is no such environment.

**Closed** 2023-03-03 19:49 UTC
Labels: bug, high-priority
