### ISSUE TITLE
bilibili audio support

### ISSUE THREAD

**Issue by hrm-princess-fluffybutt** [yt-dlp/yt-dlp#3755] opened 2022-05-16 05:27 UTC
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

channel page https://space.bilibili.com/84519699/audio
single audio page https://www.bilibili.com/audio/au1963616

### Description

requesting support for bilibili audios

### Verbose log

```shell
D:\youtube dl\program>yt-dlp -vU https://www.bilibili.com/audio/au1864879
[debug] Command-line config: ['-vU', 'https://www.bilibili.com/audio/au1864879']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106624-g391ce570c8-20220415 (setts), ffprobe N-106624-g391ce570c8-20220415
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [BilibiliAudio] Extracting URL: https://www.bilibili.com/audio/au1864879
[BilibiliAudio] 1864879: Downloading JSON metadata
[BilibiliAudio] 1864879: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1864879: Downloading 1 format(s): 0
[debug] Invoking downloader on "https://upos-sz-mirrorcos.bilivideo.com/ugaxcode/m200930a26w00zthvkj8f3ukztivyiiw-192k.m4a?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1652685971&gen=playurlv2&os=cosbv&oi=1170356195&trid=3832a013a13f484cae35eda0cf127512B&platform=pc&upsig=0d85e782cf419a8ad95f6be9009af20e&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&nettype=0&orderid=0,1&logo=00000000"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3138, in process_info
  File "yt_dlp\YoutubeDL.py", line 2846, in dl
  File "yt_dlp\downloader\common.py", line 457, in download
  File "yt_dlp\downloader\http.py", line 369, in real_download
  File "yt_dlp\downloader\http.py", line 128, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3601, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by NanaMizukiAnother7** [comment] 2022-05-16 08:33
That issue is already fixed in #2834 and duplicate of #2872!

**Comment by pukkandan** [comment] 2022-05-16 13:20
@NanaMizukiAnother7 The linked PR was merged in February, while OP is using the April release. So it appears to be a different issue (or the solution has stopped working)

**Comment by NanaMizukiAnother7** [comment] 2022-05-16 16:12
Oh well. That means this is not duplicate.

**Comment by lockmatrix** [comment] 2022-06-26 07:31
I test it on master 8d214c484c57ac3eb19043c7dc72e4f24e3018e2 , it still works.
I think this issue can be closed.
@hrm-princess-fluffybutt

**Comment by pukkandan** [comment] 2022-06-26 09:46
You are right. It's working now. But it definitely wasn't when I triaged it. Possibly temporary issue from the website. I'm closing it for now - can re-open if the issue re-appears

**Closed by pukkandan** 2022-06-26 09:46 UTC
Labels: site-bug
