### ISSUE TITLE
DiscoveryPlus Show Italy Broken

### ISSUE THREAD

**Issue by si70so15** [yt-dlp/yt-dlp#2317] opened 2022-01-12 19:47 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When I try to download a free video (see the link in log), I have this error: <HTTPError 404: 'Not Found'>
Other videos of the same serie working fine.
Thank you

### Verbose log

```shell
yt-dlp.exe --newline --max-downloads 100 -i -o "D:\Temp\dl\%(series)s %(season_number)dx%(episode_number)02d %(title)s.%(ext)s" -v --ignore-config --hls-prefer-native -Uv --verbose "https://www.discoveryplus.com/it/video/the-modern-baker/stagione-1-episodio-6-pizza-co"
[debug] Command-line config: ['--newline', '--max-downloads', '100', '-i', '-o', 'D:\\Temp\\dl\\%(series)s %(season_number)dx%(episode_number)02d %(title)s.%(ext)s', '-v', '--ignore-config', '--hls-prefer-native', '-Uv', '--verbose', 'https://www.discoveryplus.com/it/video/the-modern-baker/stagione-1-episodio-6-pizza-co']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 2021-08-14-git-acd079843b-full_build-www.gyan.dev (setts), ffprobe 2021-08-14-git-acd079843b-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [DiscoveryPlusItaly] Extracting URL: https://www.discoveryplus.com/it/video/the-modern-baker/stagione-1-episodio-6-pizza-co
[debug] [DPlay] Extracting URL: https://discoveryplus.it/video/the-modern-baker/stagione-1-episodio-6-pizza-co
[debug] Using fake IP ??.??.???.??? (XX) as X-Forwarded-For
[DPlay] the-modern-baker/stagione-1-episodio-6-pizza-co: Downloading token
[DPlay] the-modern-baker/stagione-1-episodio-6-pizza-co: Downloading JSON metadata
ERROR: [DPlay] the-modern-baker/stagione-1-episodio-6-pizza-co: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 717, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3458, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

**Comment by pukkandan** [comment] 2022-01-15 13:31
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2138

**Comment by bann0** [comment] 2022-01-15 17:30
Works for me.
You must always use "--cookies cookies_from_free_subscription.txt" also for free videos.

[debug] Command-line config: ['--no-config', '-v', '-F', '--cookies', 'discoveryplus.com_cookies.txt', 'https://www.discoveryplus.com/it/video/the-modern-baker/stagione-1-episodio-6-pizza-co']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.7.3 (CPython 64bit) - Linux-4.19.0-18-amd64-x86_64-with-debian-10.11
[debug] exe versions: ffmpeg 4.1.8-0, ffprobe 4.1.8-0, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: Crypto, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [DiscoveryPlusItaly] Extracting URL: https://www.discoveryplus.com/it/video/the-modern-baker/stagione-1-episodio-6-pizza-co
[debug] Using fake IP 79.17.209.24 (IT) as X-Forwarded-For
[DiscoveryPlusItaly] the-modern-baker/stagione-1-episodio-6-pizza-co: Downloading JSON metadata
[DiscoveryPlusItaly] 1313849: Downloading JSON metadata
[DiscoveryPlusItaly] the-modern-baker/stagione-1-episodio-6-pizza-co: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 1313849:
ID                        EXT RESOLUTION FPS │   FILESIZE   TBR PROTO  │ VCODEC        VBR ACODEC     MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-stereo_128000-Italian mp4                │                  m3u8_n │ audio only        unknown    [it] Italian
hls-299                   mp4 416x234     25 │ ~ 49.80MiB  299k m3u8_n │ avc1.4D400C  299k video only
hls-423                   mp4 640x360     25 │ ~ 70.58MiB  423k m3u8_n │ avc1.4D4016  423k video only
hls-660                   mp4 960x540     25 │ ~110.06MiB  660k m3u8_n │ avc1.4D401F  660k video only
hls-958                   mp4 1280x720    25 │ ~159.55MiB  958k m3u8_n │ avc1.4D401F  958k video only
hls-1672                  mp4 1920x1080   25 │ ~278.51MiB 1672k m3u8_n │ avc1.4D4028 1672k video only
hls-2456                  mp4 1920x1080   25 │ ~408.97MiB 2456k m3u8_n │ avc1.4D4028 2456k video only
hls-3577                  mp4 1920x1080   25 │ ~595.61MiB 3577k m3u8_n │ avc1.4D4028 3577k video only

**Comment by si70so15** [comment] 2022-01-15 20:45
Hi bann0,
I have saved cookies from chrome to a txt file with an extension, then I have passed the file name as a parameter to yt-dlp, but i still get the same error.
Can you tell me where am I wrong?
thank you.

**Comment by pukkandan** [comment] 2022-01-16 05:21
Try `--cookies-from-browser`

**Comment by si70so15** [comment] 2022-01-16 05:30
Hi pukkandan, I also try using "--cookie-from-browser chrome", but I still have the same error.
Also after reset all cookie from website.
Thanks.

**Comment by si70so15** [comment] 2022-01-16 16:45
HI to all,
I still have always the same error also with other videos,
If I try to view with chrome from site webpage work fine, but with yt-dlp does not work, also passing the login credentials.
Some one have some suggestion to give me?
Thanks

yt-dlp.exe -i -o "D:\Temp\videoDownloads\%(series)s %(season_number)dx%(episode_number)02d %(title)s.%(ext)s" -v -Uv --verbose "https://www.discoveryplus.com/it/video/i-re-dellasfalto/stagione-2-episodio-1" --cookies-from-browser chrome --username ????? --password ????

[debug] Command-line config: ['-i', '-o', 'D:\\Temp\\videoDownloads\\%(series)s %(season_number)dx%(episode_number)02d %(title)s.%(ext)s', '-v', '-Uv', '--verbose', 'https://www.discoveryplus.com/it/video/i-re-dellasfalto/stagione-2-episodio-1', '--cookies-from-browser', 'chrome', '--username', 'PRIVATE', '--password', 'PRIVATE']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\user\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[Cookies] Extracted 3124 cookies from chrome
[debug] cookie version breakdown: {'v10': 3124, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 2021-08-14-git-acd079843b-full_build-www.gyan.dev (setts), ffprobe 2021-08-14-git-acd079843b-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [DiscoveryPlusItaly] Extracting URL: https://www.discoveryplus.com/it/video/i-re-dellasfalto/stagione-2-episodio-1
[debug] [DPlay] Extracting URL: https://discoveryplus.it/video/i-re-dellasfalto/stagione-2-episodio-1
[debug] Using fake IP 79.53.195.95 (IT) as X-Forwarded-For
[DPlay] i-re-dellasfalto/stagione-2-episodio-1: Downloading JSON metadata
**ERROR: [DPlay] i-re-dellasfalto/stagione-2-episodio-1: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.**
  File "yt_dlp\extractor\common.py", line 717, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3458, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default

**Comment by bann0** [comment] 2022-01-16 17:07
Maybe Your executable doesn't have the latest discoveryplus commits.
Try git clone or wait for the next release.

**Comment by pukkandan** [comment] 2022-02-22 20:19
Pls update whether this is still an issue

**Closed** 2022-02-27 15:43 UTC
Labels: incomplete, site-bug
