### ISSUE TITLE
"HTTP Error 401: Unauthorized" Error, Yet Cookies Seem To Be Valid

### ISSUE THREAD

**Issue by danepedersen** [yt-dlp/yt-dlp#6779] opened 2023-04-11 21:45 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

I am using Mozilla VPN to access the site from here in Canada and I can confirm that it works because the keyError goes away when the VPN is turned on and set to Australia.  I use YouTube-dl with the YouTube-dl-GUI helper app.

The issue appears to be a user-credentials one, as the download process terminates with an HTTP 401 error.  Up to this point, I have never had that issue before.  The cookies for the site, which I downloaded as a .txt file, are attached here.
[iview.abc.net.au_cookies.txt](https://github.com/yt-dlp/yt-dlp/files/11205177/iview.abc.net.au_cookies.txt)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Error: [debug] Command-line config: ['https://iview.abc.net.au/show/abc-news-act/series/0/video/NU2304C101S00', '-o', 'D:\\Downloaded Audio-Video Tracks\\ViaYouTubeDL\\abc.net.au\\Custom\\%(title)s-%(id)s.%(ext)s', '-o', 'D:/VideosForProcessing/ABCNewsCanberra04112023.mp4', '--referer', 'https://iview.abc.net.au/video/NU2304C101S00', '--cookies', 'D:/iview.abc.net.au_cookies.txt', '-vU']
Error: [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error cp1252 (No ANSI), screen cp1252 (No ANSI)
Error: [debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
Error: [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
Error: [debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts), ffprobe 5.1.2-essentials_build-www.gyan.dev
Error: [debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
Error: [debug] Proxy map: {}
Error: [debug] Loaded 1786 extractors
Error: [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
Error: [debug] Using fake IP 1.133.13.149 (AU) as X-Forwarded-For
[abc.net.au:iview] Extracting URL: https://iview.abc.net.au/show/abc-news-act/series/0/video/NU2304C101S00
[abc.net.au:iview] NU2304C101S00: Downloading JSON metadata
[abc.net.au:iview] NU2304C101S00: Downloading webpage
Error: ERROR: [abc.net.au:iview] NU2304C101S00: Unable to download webpage: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Error:   File "yt_dlp\extractor\common.py", line 694, in extract
Error:   File "yt_dlp\extractor\abc.py", line 204, in _real_extract
Error:   File "yt_dlp\extractor\common.py", line 1097, in _download_webpage
Error:   File "yt_dlp\extractor\common.py", line 1048, in download_content
Error:   File "yt_dlp\extractor\common.py", line 882, in _download_webpage_handle
Error:   File "yt_dlp\extractor\common.py", line 839, in _request_webpage
Error:   File "yt_dlp\extractor\common.py", line 821, in _request_webpage
Error:   File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
Error:   File "urllib\request.py", line 531, in open
Error:   File "urllib\request.py", line 640, in http_response
Error:   File "urllib\request.py", line 569, in error
Error:   File "urllib\request.py", line 502, in _call_chain
Error:   File "urllib\request.py", line 649, in http_error_default
Error: urllib.error.HTTPError: HTTP Error 401: Unauthorized
An error occured
```

**Comment by bashonly** [comment] 2023-04-11 21:57
Duplicate of #4032

**Closed by bashonly** 2023-04-11 21:57 UTC
Labels: site-bug, triage
