### ISSUE TITLE
https://v.douyin.com/iAfjpuwt/

### ISSUE THREAD

**Issue by a184734919** [yt-dlp/yt-dlp#11500] opened 2024-11-11 02:14 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

China

### Example URLs

https://v.douyin.com/iAfjpuwt/

### Provide a description that is worded well enough to be understood

I want to download Douyin's video but it reports the following error. I swear I'm using the latest cookies
Error: WARNING: [Douyin] 7433832678895422783: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)

Error: ERROR: [Douyin] 7433832678895422783: Fresh cookies (not necessarily logged in) are needed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Download failed with code: 1

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
function downloadVideo(
  url,
  outputDir = "./downloads",
  cookiesFile = "./cookies.txt"
) {
  const command = `yt-dlp --cookies ${cookiesFile} -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --merge-output-format mp4 -o "${path.join(
    outputDir,
    "%(title)s.%(ext)s"
  )}" ${url}`;

  const downloadProcess = exec(command);

  downloadProcess.stdout.on("data", (data) => {
    console.log(`Downloading: ${data}`);
  });

  downloadProcess.stderr.on("data", (data) => {
    console.error(`Error: ${data}`);
  });

  downloadProcess.on("close", (code) => {
    if (code === 0) {
      console.log("Download complete!");
    } else {
      console.error(`Download failed with code: ${code}`);
    }
  });
}
```

**Comment by bashonly** [comment] 2024-11-11 19:45
Duplicate of #9667

**Closed by bashonly** 2024-11-11 19:45 UTC
Labels: duplicate, site-bug, site:tiktok
