### ISSUE TITLE
ERROR: Unsupported URL: https://www.instagram.com/reels/C69PXQPPZlH/

### ISSUE THREAD

**Issue by nimaxin** [yt-dlp/yt-dlp#9928] opened 2024-05-15 17:45 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

yt-dlp can not download links from Instagram Reels, and instead raises an error message stating that the URL is unsupported. This issue prevents users from downloading content from Instagram Reels using the yt-dlp library."

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
root@nimaxin:~/temp# yt-dlp -vU "https://www.instagram.com/reels/C69PXQPPZlH"
[debug] Command-line config: ['-vU', 'https://www.instagram.com/reels/C69PXQPPZlH']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (pip)
[debug] Python 3.10.12 (CPython aarch64 64bit) - Linux-5.15.0-100-generic-aarch64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2020.06.20, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.instagram.com/reels/C69PXQPPZlH
[generic] C69PXQPPZlH: Downloading webpage
[redirect] Following redirect to https://www.instagram.com/reels/C69PXQPPZlH/
[generic] Extracting URL: https://www.instagram.com/reels/C69PXQPPZlH/
[generic] C69PXQPPZlH: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] C69PXQPPZlH: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.instagram.com/reels/C69PXQPPZlH/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.instagram.com/reels/C69PXQPPZlH/
```

**Comment by bashonly** [comment] 2024-05-15 17:47
Duplicate of #6689

Workaround: modify the URL, changing `/reels/` to `/reel/`

**Closed by bashonly** 2024-05-15 17:47 UTC
Labels: duplicate, site-bug, site:instagram
