### ISSUE TITLE
Bitchute New UI

### ISSUE THREAD

**Issue by muhannad-hash** [yt-dlp/yt-dlp#10323] opened 2024-07-01 11:41 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

the Bithcute changed their UI two days ago and I am getting extractor error
`ERROR: [BitChute] ev6GADm5LIM: Video is unavailable. Please make sure this video is playable in the browser before reporting this issue.`
this is the link to their announcemnt
https://www.paychute.com/feed/0fea4886-cd64-4f4b-88d7-7f3502e4943f

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://bitchute.com/video/ev6GADm5LIM/', '-Uv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp (linux_exe)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.8.0-36-generic-x86_64-with (OpenSSL 3.1.4 24 Oct 2023)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.2, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[BitChute] Extracting URL: https://bitchute.com/video/ev6GADm5LIM/
[BitChute] ev6GADm5LIM: Downloading webpage
ERROR: [BitChute] ev6GADm5LIM: Video is unavailable. Please make sure this video is playable in the browser before reporting this issue.
  File "yt_dlp/extractor/common.py", line 734, in extract
  File "yt_dlp/extractor/bitchute.py", line 150, in _real_extract
  File "yt_dlp/extractor/common.py", line 1257, in raise_no_formats
```

**Comment by seproDev** [comment] 2024-07-01 11:48
Duplicate of #10293

Update to nightly
```
yt-dlp --update-to nightly
```

**Closed by seproDev** 2024-07-01 11:48 UTC
Labels: site-bug, triage

**Comment by skullquake** [comment] 2024-07-25 22:15
I do not know if they are going to deprecate the old site, in case they do, for future work with the new API

`#!/bin/bash
URL=$1
VIDEO_ID=$(filename $1)
JSON=$(
	curl 'https://api.bitchute.com/api/beta/video' \
	  -s \
	  -H 'accept: application/json, text/plain, */*' \
	  -H 'accept-language: en-US,en;q=0.7' \
	  -H 'authorization: Bearer Wos22ySfEDIGP6vhW5Pn2JmPTCodLk' \
	  -H 'content-type: application/json' \
	  -H 'origin: https://www.bitchute.com' \
	  -H 'priority: u=1, i' \
	  -H 'referer: https://www.bitchute.com/' \
	  -H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Brave";v="126"' \
	  -H 'sec-ch-ua-mobile: ?0' \
	  -H 'sec-ch-ua-platform: "Windows"' \
	  -H 'sec-fetch-dest: empty' \
	  -H 'sec-fetch-mode: cors' \
	  -H 'sec-fetch-site: same-site' \
	  -H 'sec-gpc: 1' \
	  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36' \
	  --data-raw '{"video_id":"'$VIDEO_ID'"}'
)
CHANNEL_ID=$(echo $JSON|jq -r '.channel.channel_id')
VIDEO_NAME=$(echo $JSON|jq -r '.video_name')
MP4_URL=https://seed307.bitchute.com/$CHANNEL_ID/$VIDEO_ID.mp4
wget "$MP4_URL" -O "$VIDEO_NAME".mp4
`
