### ISSUE TITLE
Generic extractor can crash if Brotli is not available

### ISSUE THREAD

**Issue by dirkf** [yt-dlp/yt-dlp#5855] opened 2022-12-23 01:35 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Testing #5851 in a configuration where no Brotli decoder was available showed the crash in the log.

The problem is this extractor code:
https://github.com/yt-dlp/yt-dlp/blob/1fc089143c79b02b8373ae1d785d5e3a68635d4d/yt_dlp/extractor/generic.py#L2306-L2318

Normally there is a check for a supported Brotli encoder (using `SUPPORTED_ENCODINGS`). Specifying `*` in the `Accept-encoding` header bypasses that check.

However, I don't think that `*` does what is wanted according to the comments in the above code. The code wants to get the resource with no decoding (because decoding in yt-dl[p] starts by reading the entire response), but `*` still allows the server to send a compressed response. What is wanted is the `identity` encoding which is the default if no other encoding is specified. Or, to re-cast the decoding process so that the whole response stream is not read before decoding, but that means creating stream decoding methods for Brotli and zlib.

Also, there could be a check for a supported encoding in `YoutubeDLHandler.http_response()`, perhaps synthesizing 416 or 406 id the server has sent an encoding that isn't supported, instead of the crash seen here.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-F', 'https://www.extra.cz/cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: c73355510
[debug] Python 3.9.15 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-glibc2.23 (OpenSSL 1.1.1s  1 Nov 2022, glibc 2.23)
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2019.11.28, secretstorage-3.2.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1735 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[generic] Extracting URL: https://www.extra.cz/cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867
[generic] cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867: Downloading webpage
ERROR: 'NoneType' object has no attribute 'decompress'
Traceback (most recent call last):
  File "/home/df/Documents/src/yt-dlp/yt_dlp/YoutubeDL.py", line 1495, in wrapper
    return func(self, *args, **kwargs)
  File "/home/df/Documents/src/yt-dlp/yt_dlp/YoutubeDL.py", line 1571, in __extract_info
    ie_result = ie.extract(url)
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/generic.py", line 2314, in _real_extract
    full_response = self._request_webpage(url, video_id, headers={
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/common.py", line 807, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/df/Documents/src/yt-dlp/yt_dlp/YoutubeDL.py", line 3719, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/df/Documents/src/yt-dlp/yt_dlp/utils.py", line 1452, in http_response
    io.BytesIO(self.brotli(resp.read())), old_resp.headers, old_resp.url, old_resp.code)
  File "/home/df/Documents/src/yt-dlp/yt_dlp/utils.py", line 1389, in brotli
    return brotli.decompress(data)
AttributeError: 'NoneType' object has no attribute 'decompress'
```

**Comment by dirkf** [comment] 2022-12-23 01:37
[@pukkandan said](https://github.com/yt-dlp/yt-dlp/issues/5851#issuecomment-1363387601):
> The code is originally from ytdl-org/youtube-dl@58bde34.

**Comment by dirkf** [comment] 2022-12-23 02:03
In yt-dl Brotli isn't yet supported so this problem hasn't come up.

With this (but not yet changing the dubious comment above):
```diff
--- old/yt_dlp/extractor/generic.py
+++ new/yt_dlp/extractor/generic.py
@@ -2312,7 +2312,7 @@
         # It may probably better to solve this by checking Content-Type for application/octet-stream
         # after a HEAD request, but not sure if we can rely on this.
         full_response = self._request_webpage(url, video_id, headers={
-            'Accept-Encoding': '*',
+            'Accept-Encoding': 'identity',
             **smuggled_data.get('http_headers', {})
         })
         new_url = full_response.geturl()
```
the problem command succeeds:
```shellsession
$ python3.9 -m yt_dlp -v -F 'https://www.extra.cz/cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867'
[debug] Command-line config: ['-v', '-F', 'https://www.extra.cz/cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: c73355510
[debug] Python 3.9.15 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-glibc2.23 (OpenSSL 1.1.1s  1 Nov 2022, glibc 2.23)
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2019.11.28, secretstorage-3.2.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1735 extractors
[generic] Extracting URL: https://www.extra.cz/cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867
[generic] cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867: Extracting information
[debug] Looking for embeds
[debug] Identified a JSON LD
[generic] Extracting URL: https://stream.eom.cz/storage-prod/videos/D1yA3uml-57xeMHzN.mp4#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867%22%2C+%22to_generic%22%3A+true%2C+%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fwww.extra.cz%2Fcauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867%22%7D%7D
[generic] cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867: Downloading webpage
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867:
ID  EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
────────────────────────────────────────────
mp4 mp4 unknown    │ https │ unknown unknown
$
```
Of course there might be regressions with other URLs.

In addition to checking that the actual encoding is supported, the response processing in yt-dl inherited here seems rather repetitive and doesn't allow for the possibility of [multiple encodings](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding#syntax). Maybe something like this would be more straightforward (move gzip decoding to a static method matching the other encodings, introduce a generic expansion method, iterate on content encoding):
```diff
--- old/yt_dlp/utils.py
+++ new/yt_dlp/utils.py
@@ -1388,6 +1388,40 @@
             return data
         return brotli.decompress(data)
 
+    @staticmethod
+    def gz(data):
+        if not data:
+            return data
+        gz = gzip.GzipFile(fileobj=io.BytesIO(data), mode='rb')
+        uncompressed = None
+        try:
+            uncompressed = io.BytesIO(gz.read())
+        except OSError as original_ioerror:
+            # There may be junk at the end of the file
+            # See http://stackoverflow.com/q/4928560/35070 for details
+            for i in range(1, 1024):
+                try:
+                    gz = gzip.GzipFile(fileobj=io.BytesIO(content[:-i]), mode='rb')
+                    uncompressed = io.BytesIO(gz.read())
+                except OSError:
+                    continue
+                break
+            else:
+                raise original_ioerror
+        return uncompressed
+
+    def _expand(self, response):
+        enc = response.headers['Content-encoding']
+        expander = getattr(self, enc, None)
+        if callable(expander):
+            old_resp = response
+            expanded = io.BytesIO(expander(response.read()))
+            response = urllib.request.addinfourl(
+                expanded, old_resp.headers, old_resp.url, old_resp.code)
+            response.msg = old_resp.msg
+            del response.headers['Content-encoding']
+        return response
+
     def http_request(self, req):
         # According to RFC 3986, URLs can not contain non-ASCII characters, however this is not
         # always respected by websites, some tend to give out URLs with non percent-encoded
@@ -1418,40 +1452,13 @@
         return super().do_request_(req)
 
     def http_response(self, req, resp):
-        old_resp = resp
-        # gzip
-        if resp.headers.get('Content-encoding', '') == 'gzip':
-            content = resp.read()
-            gz = gzip.GzipFile(fileobj=io.BytesIO(content), mode='rb')
-            try:
-                uncompressed = io.BytesIO(gz.read())
-            except OSError as original_ioerror:
-                # There may be junk add the end of the file
-                # See http://stackoverflow.com/q/4928560/35070 for details
-                for i in range(1, 1024):
-                    try:
-                        gz = gzip.GzipFile(fileobj=io.BytesIO(content[:-i]), mode='rb')
-                        uncompressed = io.BytesIO(gz.read())
-                    except OSError:
-                        continue
-                    break
-                else:
-                    raise original_ioerror
-            resp = urllib.request.addinfourl(uncompressed, old_resp.headers, old_resp.url, old_resp.code)
-            resp.msg = old_resp.msg
-            del resp.headers['Content-encoding']
-        # deflate
-        if resp.headers.get('Content-encoding', '') == 'deflate':
-            gz = io.BytesIO(self.deflate(resp.read()))
-            resp = urllib.request.addinfourl(gz, old_resp.headers, old_resp.url, old_resp.code)
-            resp.msg = old_resp.msg
-            del resp.headers['Content-encoding']
-        # brotli
-        if resp.headers.get('Content-encoding', '') == 'br':
-            resp = urllib.request.addinfourl(
-                io.BytesIO(self.brotli(resp.read())), old_resp.headers, old_resp.url, old_resp.code)
-            resp.msg = old_resp.msg
-            del resp.headers['Content-encoding']
+        for content_enc in (resp.headers.get('Content-encoding') or '').split(', '):
+            if content_enc and content_enc != 'identity':
+                if content_enc not in SUPPORTED_ENCODINGS:
+                    raise urllib.error.HTTPError(
+                        req.full_url, 406, 'Content-encoding %s not supported' % (content_enc, ), resp.headers, resp)
+                resp['Content-encoding'] = content_enc
+                resp = self._expand(resp)
         # Percent-encode redirect URL of Location HTTP header to satisfy RFC 3986 (see
         # https://github.com/ytdl-org/youtube-dl/issues/6457).
         if 300 <= resp.code < 400:
```

**Comment by pukkandan** [comment] 2022-12-23 04:44
> In yt-dl Brotli isn't yet supported so this problem hasn't come up.

The issue is there, just that no error is raised. ytdl instead just downloads the encoded file as-is

```
❯ youtube-dl -v https://www.extra.cz/cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.extra.cz/cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867']
[debug] Encodings: locale cp65001, fs mbcs, out cp65001, pref cp65001
[debug] youtube-dl version 2022.10.05.810
** This build is unofficial daily builds, provided for ease of use.
** Please do not ask for any support.
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.22000
[debug] exe versions: ffmpeg n5.1.2-8-g5746987bad-20221204, ffprobe N-109332-g45ab5307a6-20221201, phantomjs 2.1.1
[debug] Proxy map: {}
[generic] cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867: Requesting header
WARNING: Could not send HEAD request to https://www.extra.cz/cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867: HTTP Error 405: Method Not Allowed
[generic] cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867: Downloading webpage
WARNING: Falling back on generic information extractor.
WARNING: URL could be a direct video link, returning it as such.
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://www.extra.cz/cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867'
[download] Destination: cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867-cauky-lidi-70-dil-babis-predstavil-pohadky-prymulanek-nebo-andrejovy-nove-saty-ac867.unknown_video
[download] 100% of 73.54KiB in 00:01
```

**Comment by pukkandan** [comment] 2022-12-23 04:44
cc @coletdjnz

**Comment by dirkf** [comment] 2022-12-23 05:14
Yes, yt-dl gets the br-encoded file, fails to parse it since it has no idea about `br` and guesses that this chunk of unknown binary must be a video (`content-type: text/html; charset=utf-8` should have been a hint that that was wrong).

**Comment by coletdjnz** [comment] 2022-12-23 05:54
Using `Accept-Encoding: identity` should be fine for this one request. 

The networking code is in a sort of freeze until #2861 is merged (unless it is really urgent), since it's being rewritten anyways.

I'm not entirely sure why they weren't using that to begin with. But I've found lots of weird workarounds for accept-encoding (like the youtube-dl no compression header, which I remove in #2861 and opt for identity header). Guessing it's just legacy code.

**Comment by dirkf** [comment] 2022-12-23 11:31
The 1-line Generic fix should do the trick.

Please consider the revised patch to `utils.py` above as a suggestion for #2861 or a related update, where applicable.

**Comment by coletdjnz** [comment] 2023-01-02 01:55
Closing as technically fixed by https://github.com/yt-dlp/yt-dlp/commit/3e01ce744a981d8f19ae77ec695005e7000f4703 but will look into the urllib improvements.

**Closed** 2023-01-02 01:54 UTC
Labels: bug
