### ISSUE TITLE
Sorting by `size` variable does not work

### ISSUE THREAD

**Issue by ischmidt20** [yt-dlp/yt-dlp#4501] opened 2022-07-30 21:34 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I am unable to sort formats by size. Per the documentation:

> Eg: `+res` prefers format with the smallest resolution. 

By the same logic, `+size` must prefer the format with the smallest "size" (Exact filesize if available, otherwise approximate filesize). However, it appears this variable is not being considered at all. Sorting by `+res` works as expected, but not `+size`.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -F -S +size https://www.paramountplus.com/shows/video/kaWvMpPYbGBFzNVASW8sT6JxB226Mwul/ -v
[debug] Command-line config: ['-F', '-S', '+size', 'https://www.paramountplus.com/shows/video/kaWvMpPYbGBFzNVASW8sT6JxB226Mwul/', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.5-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1 (fdk,setts), ffprobe 5.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [ParamountPlus] Extracting URL: https://www.paramountplus.com/shows/video/kaWvMpPYbGBFzNVASW8sT6JxB226Mwul/
[ParamountPlus] kaWvMpPYbGBFzNVASW8sT6JxB226Mwul: Downloading JSON metadata
[ParamountPlus] kaWvMpPYbGBFzNVASW8sT6JxB226Mwul: Downloading JSON metadata
[ParamountPlus] kaWvMpPYbGBFzNVASW8sT6JxB226Mwul: Downloading DASH_CENC_PRECON SMIL data
[ParamountPlus] kaWvMpPYbGBFzNVASW8sT6JxB226Mwul: Downloading m3u8 information
[debug] Sort order given by user: +size
[debug] Formats sorted by: hasvid, ie_pref, +filesize, +fs_approx, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for kaWvMpPYbGBFzNVASW8sT6JxB226Mwul:
ID       EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR
──────────────────────────────────────────────────────────────────────────────────
hls-95   mp4 audio only │ ~ 69.74MiB   95k m3u8  │ audio only        mp4a.40.2 95k
hls-495  mp4 640x360    │ ~363.39MiB  495k m3u8  │ avc1.640028  495k mp4a.40.2  0k
hls-838  mp4 768x432    │ ~615.20MiB  838k m3u8  │ avc1.640028  838k mp4a.40.2  0k
hls-1616 mp4 960x540    │ ~  1.16GiB 1616k m3u8  │ avc1.640028 1616k mp4a.40.2  0k
hls-2214 mp4 1024x576   │ ~  1.59GiB 2214k m3u8  │ avc1.640028 2214k mp4a.40.2  0k
hls-3112 mp4 1280x720   │ ~  2.23GiB 3112k m3u8  │ avc1.640028 3112k mp4a.40.2  0k
hls-4610 mp4 1280x720   │ ~  3.31GiB 4610k m3u8  │ avc1.640028 4610k mp4a.40.2  0k

yt-dlp -F -S +res https://www.paramountplus.com/shows/video/kaWvMpPYbGBFzNVASW8sT6JxB226Mwul/ -v
[debug] Command-line config: ['-F', '-S', '+res', 'https://www.paramountplus.com/shows/video/kaWvMpPYbGBFzNVASW8sT6JxB226Mwul/', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.5-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1 (fdk,setts), ffprobe 5.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [ParamountPlus] Extracting URL: https://www.paramountplus.com/shows/video/kaWvMpPYbGBFzNVASW8sT6JxB226Mwul/
[ParamountPlus] kaWvMpPYbGBFzNVASW8sT6JxB226Mwul: Downloading JSON metadata
[ParamountPlus] kaWvMpPYbGBFzNVASW8sT6JxB226Mwul: Downloading JSON metadata
[ParamountPlus] kaWvMpPYbGBFzNVASW8sT6JxB226Mwul: Downloading DASH_CENC_PRECON SMIL data
[ParamountPlus] kaWvMpPYbGBFzNVASW8sT6JxB226Mwul: Downloading m3u8 information
[debug] Sort order given by user: +res
[debug] Formats sorted by: hasvid, ie_pref, +res, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for kaWvMpPYbGBFzNVASW8sT6JxB226Mwul:
ID       EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR
──────────────────────────────────────────────────────────────────────────────────
hls-95   mp4 audio only │ ~ 69.74MiB   95k m3u8  │ audio only        mp4a.40.2 95k
hls-3112 mp4 1280x720   │ ~  2.23GiB 3112k m3u8  │ avc1.640028 3112k mp4a.40.2  0k
hls-4610 mp4 1280x720   │ ~  3.31GiB 4610k m3u8  │ avc1.640028 4610k mp4a.40.2  0k
hls-2214 mp4 1024x576   │ ~  1.59GiB 2214k m3u8  │ avc1.640028 2214k mp4a.40.2  0k
hls-1616 mp4 960x540    │ ~  1.16GiB 1616k m3u8  │ avc1.640028 1616k mp4a.40.2  0k
hls-838  mp4 768x432    │ ~615.20MiB  838k m3u8  │ avc1.640028  838k mp4a.40.2  0k
hls-495  mp4 640x360    │ ~363.39MiB  495k m3u8  │ avc1.640028  495k mp4a.40.2  0k
```

**Comment by pukkandan** [comment] 2022-07-30 21:36
The issue is the `filesize_approx=duration*tbr` is calculated after sorting. 

For now, you can sort by tbr as a workaround. `-S +tbr`

**Comment by ischmidt20** [comment] 2022-07-30 21:42
I cannot sort by `tbr` as really my ultimate goal is to do something like `size:7G`, which is a function of duration as well

**Comment by ischmidt20** [comment] 2022-07-30 21:44
My workaround will probably be to get all the formats, and then write my own function to pick the best one and then download that one, but that seems too "hacky" when clearly yt-dlp already has the scaffolding to select the best format in one shit

**Comment by pukkandan** [comment] 2022-07-30 22:23
I suspect actually fixing this will be difficult and will take time 

Does `-f "bv[filesize_approx<7G]"` work for the time-being?

**Comment by ischmidt20** [comment] 2022-07-30 23:33
No:

```
yt-dlp -F https://www.espn.com/watch/player/_/id/f9230b4a-2beb-43c5-84f2-a4a09cf73547 --cookies espn.com_cookies.txt
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading m3u8 information
[info] Available formats for f9230b4a-2beb-43c5-84f2-a4a09cf73547:
ID       EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR
──────────────────────────────────────────────────────────────────────────────────────
hls-250  mp4 320x180     30 │ ~341.71MiB  250k m3u8  │ avc1.4d001f  250k mp4a.40.2  0k
hls-550  mp4 384x216     30 │ ~751.75MiB  550k m3u8  │ avc1.4d001f  550k mp4a.40.2  0k
hls-1000 mp4 512x288     30 │ ~  1.33GiB 1000k m3u8  │ avc1.4d001f 1000k mp4a.40.2  0k
hls-1420 mp4 640x360     30 │ ~  1.90GiB 1420k m3u8  │ avc1.4d001f 1420k mp4a.40.2  0k
hls-2150 mp4 896x504     30 │ ~  2.87GiB 2150k m3u8  │ avc1.4d001f 2150k mp4a.40.2  0k
hls-2980 mp4 960x540     30 │ ~  3.98GiB 2980k m3u8  │ avc1.4d0020 2980k mp4a.40.2  0k
hls-4190 mp4 1280x720    30 │ ~  5.59GiB 4190k m3u8  │ avc1.640028 4190k mp4a.40.2  0k
hls-6600 mp4 1280x720    60 │ ~  8.81GiB 6600k m3u8  │ avc1.640028 6600k mp4a.40.2  0k
hls-8250 mp4 1280x720    60 │ ~ 11.01GiB 8250k m3u8  │ avc1.640028 8250k mp4a.40.2  0k
```

```
yt-dlp -f "bv[filesize_approx<7G]" https://www.espn.com/watch/player/_/id/f9230b4a-2beb-43c5-84f2-a4a09cf73547 --cookies espn.com_cookies.txt
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading m3u8 information
ERROR: [WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Requested format is not available. Use --list-formats for a list of available formats
```

`'fs_approx<7G'` or `'size<7G'` both return `SyntaxError: Invalid filter specification `

**Comment by pukkandan** [comment] 2022-07-31 13:13
For your example, it should be `b[filesize_approx<7G]`, not `bv` since the formats are pre-merged

**Comment by ischmidt20** [comment] 2022-07-31 14:41
This works, thank yoU!

**Closed** 2023-02-12 19:50 UTC
Labels: bug
