### ISSUE TITLE
new No video formats found

### ISSUE THREAD

**Issue by mofateh86** [yt-dlp/yt-dlp#7492] opened 2023-07-02 22:39 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

trying to download this public FB reel https://www.facebook.com/reel/162236813355587 , i get :

No video formats found!; please report this issue 

(while other videos from reels downloaded normally)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.facebook.com/reel/162236813355587
[debug] Command-line config: ['-vU', 'https://www.facebook.com/reel/162236813355587']
[debug] Encodings: locale cp1256, fs utf-8, pref cp1256, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-03-31-git-e301a24fa1-full_build-www.gyan.dev (setts), ffprobe 2022-03-31-git-e301a24fa1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 37e7ffe204309357cfd1388b0e2c782a30e293ddd0f2761a9a8f6afa185b3566
yt-dlp is up to date (stable@2023.06.22)
[facebook:reel] Extracting URL: https://www.facebook.com/reel/162236813355587
[facebook] Extracting URL: https://m.facebook.com/watch/?v=162236813355587&_rdr
[facebook] 162236813355587: Downloading webpage
ERROR: [facebook] 162236813355587: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1555, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1652, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1711, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2653, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1067, in raise_no_formats
yt_dlp.utils.ExtractorError: [facebook] 162236813355587: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment] 2023-07-02 22:41
Duplicate of #7469

**Closed by bashonly** 2023-07-02 22:41 UTC
Labels: duplicate, site-bug, site:facebook
