### ISSUE TITLE
Coming from oauth2 plugin now integrated in yt-dlp, but stopped to work

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [yt-dlp/yt-dlp#11441] opened 2024-11-03 03:25 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

just updated to the new release, I was using before the yt-dlp-oauth2 plugin and everything worked well.
so according to the author I removed the python plugin as now it's integrated into yt-dlp and changed the login "oauth2" by "oauth" and followed the usual procedure google device etc...
but now all videos I wanty to download  are marked unavailable. did I miss anything? I don't think it's a bug, but surely something I missed to do or clean or else, reason why I open an issue "ask a question" first.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://youtu.be/WKOBs9eKJqc?si=p5OvRcOQabv8RIL4']
[debug] System config "/etc/yt-dlp.conf": ['--source-address', '2001:bc8:1203:362:6051:1b6c:606f:35ef', '-vU', '--geo-verification-proxy', 'rumble.com', '--proxy', 'node221.e-blokos.com:3128', '--no-cookies', '--cache-dir', '/home/PEERTUBE/.cache', '--username', 'PRIVATE', '--password', 'PRIVATE', '--force-ipv4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (zip)
[debug] Python 3.12.7 (CPython x86_64 64bit) - Linux-6.11.6-x86_64-with-glibc2.39 (OpenSSL 3.2.2 4 Jun 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.2 (fdk,setts), ffprobe 6.1.2
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2023.05.07, pyxattr-0.7.2, requests-2.32.3, sqlite3-3.45.1, urllib3-1.26.20, websockets-13.0
[debug] Proxy map: {'all': 'node221.e-blokos.com:3128'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Plugin directories: ['/usr/local/lib64/python3.12/site-packages/yt_dlp_plugins', '/usr/local/lib/python3.12/site-packages/yt_dlp_plugins']
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info (HTTP Error 403: rate limit exceeded); Please try again later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[debug] Loading youtube.oauth_refresh_token_default from cache
[youtube] oauth: Refreshing access token
[debug] [youtube] oauth: Logged in using profile "default"
[youtube] Extracting URL: https://youtu.be/WKOBs9eKJqc?si=p5OvRcOQabv8RIL4
[youtube] WKOBs9eKJqc: Downloading webpage
[youtube] WKOBs9eKJqc: Downloading ios player API JSON
[youtube] WKOBs9eKJqc: Downloading mweb player API JSON
ERROR: [youtube] WKOBs9eKJqc: Video unavailable. This content isn’t available.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4671, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1275, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by bashonly** [comment] 2024-11-03 03:30
Your account has been blocked. Closing as duplicate of #10085

**Closed by bashonly** 2024-11-03 03:30 UTC
Labels: question

**Comment by ROBERT-MCDOWELL** [comment] 2024-11-03 03:52
ok thanks.. :-\

**Comment by bashonly** [comment] 2024-11-03 20:10
To clarify, your Youtube account is restricted. I didn't mean your GH account is blocked from the repo or anything. The restriction can last anywhere from 2 days to 2 months. You will only be able to watch videos with the account using certain official clients. Usually the android app will always work. Sometimes the webpage won't

**Comment by ROBERT-MCDOWELL** [comment] 2024-11-03 21:16
ok it's more clear indeed. I just wonder on which criteria YT reich decides to restrict since the method used by oauth is the same as any TV or device... meaning that if a school with one account share videos on the same account can be at anytime be restricted... hilarious.... the end of YT is near...

**Comment by DTrombett** [comment] 2024-11-03 22:58
It's not necessarily because oauth. It's because you probably extracted/downloaded too many videos and YouTube flagged that as automated activity, leading to an account ban. It appears to happen with cookies too at the same rate

**Comment by ROBERT-MCDOWELL** [comment] 2024-11-03 23:06
@DTrombett I wonder how the differentiate download and play a movie if it's only by checking the browser consistency....

**Comment by bashonly** [comment] 2024-11-04 00:12
There are many ways to detect yt-dlp usage, but it's likely the inhuman rate of video consumption coupled with the lack of Botguard and Droidguard attestation that gets accounts flagged. You can read up about [passing a PO token to yt-dlp](https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide) when using your account with it; doing so may reduce the chances of your account being restricted like this. (AFAIK there's nothing that can be done while it's currently restricted)

**Comment by ROBERT-MCDOWELL** [comment] 2024-11-04 00:33
- the lack of Botguard/Droidguard
yeah it's mort this, as for now my activities are no more than 100 downloads / day.... po token seems more a trick than a solution like oauth, and I won't be surprised YT will fix it soon....

**Comment by bashonly** [comment] 2024-11-04 00:41
OAuth is not really a solution. though. Passing OAuth is not effectively different than passing cookies. They are just different ways of authenticating. What I'm saying is using a PO token ***with*** authentication might prevent your account from being restricted like this in the future.

**Comment by ROBERT-MCDOWELL** [comment] 2024-11-04 00:59
ok I will see if it's restricting too long.. .thanks for help
