### ISSUE TITLE
Occationally getting "ERROR: __init__() missing 1 required positional argument: 'msg'" at the end of download status line.

### ISSUE THREAD

**Issue by maaldheefee** [yt-dlp/yt-dlp#2079] opened 2021-12-22 13:16 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I'm occasionally (inconsistently) getting the following error and then the program ends abruptly. I've gotten it randomly with different URLs, but it's inconsistent. I can't even reproduce it, even if I delete everything and start over again. But it has happened to be more than a few times.

`[download]  18.6% of 43.86MiB at 42.47KiB/s ETA 14:20ERROR: __init__() missing 1 required positional argument: 'msg'`

If I run the same command again, it'll resume the download and complete it successfully.

### Verbose log

I can't have a verbose log because I can't reproduce it intentionally. But the non-verbose log goes like this:

```shell
...
...
...
[info] ___: Downloading 1 format(s): 247+251
[info] Downloading video thumbnail 45 ...
[info] Writing video thumbnail 45 to: d:\Downloads\YouTube-DL\TEMP\NA\___.webp
[download] Resuming download at byte 8332621
[download] Destination: d:\Downloads\YouTube-DL\TEMP\NA\___.f247.webm
[download]  18.6% of 43.86MiB at 42.47KiB/s ETA 14:20ERROR: __init__() missing 1 required positional argument: 'msg'
```

**Comment by pukkandan** [comment] 2021-12-22 13:25
I assume you are using `--throttled-rate` option. If so, it is a known bug and is fixed in https://github.com/yt-dlp/yt-dlp/commit/43b2290658d37af9a2cb03f0407166eb9a172385

If the cause is something else, I will need verbose log

**Closed by pukkandan** 2021-12-22 13:25 UTC
Labels: bug, triage
