### ISSUE TITLE
Not able to download TikTok videos since today

### ISSUE THREAD

**Issue by agrawalbs05** [yt-dlp/yt-dlp#9718] opened 2024-04-18 17:34 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

ERROR: [TikTok] 7358970554273238318: Unable to extract webpage video data; please report

Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --cookies-from-browser firefox --paths /tmp/appshark_mactyxp1y_al/com.zhiliaoapp.musically_33.7.4_2023307040_1713460519/1713460525/ingress_share_tiktok_from_gallery_round2/videos --output BasketballNear.mp4 --write-info-json --write-playlist-metafiles https://www.tiktok.com/@bronnbolton7/video/7358970554273238318      
[TikTok] Extracting URL: https://www.tiktok.com/@bronnbolton7/video/7358970554273238318
Extracting cookies from firefox
Extracted 235 cookies from firefox
[TikTok] 7358970554273238318: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 3)
[TikTok] 7358970554273238318: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 3)
[TikTok] 7358970554273238318: Downloading video feed
WARNING: [TikTok] 7358970554273238318: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); trying with webpage
[TikTok] 7358970554273238318: Downloading webpage
ERROR: [TikTok] 7358970554273238318: Unable to extract webpage video data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment] 2024-04-18 17:35
Duplicate of #9506

**Closed by bashonly** 2024-04-18 17:35 UTC
Labels: duplicate, site-bug, site:tiktok
