### ISSUE TITLE
[QUESTION] Take extra legal precautions?

### ISSUE THREAD

**Issue by pirate486743186** [yt-dlp/yt-dlp#2355] opened 2022-01-16 10:32 UTC
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

(this is recent)
Host of Youtube-dl Web Site Sued by Major Record Labels
https://news.slashdot.org/story/22/01/16/025217/host-of-youtube-dl-web-site-sued-by-major-record-labels

This is not over.... They haven't even noticed that youtube-dl is dead and still beat it's dead rotting corpse. When youtube brakes on youtube-dl and yt-dlp gains attention, they will turn to it. This is just a matter of time.

Maybe.... yt-dlp should take some more precautions?
Maybe you should seriously consider splitting the project after all....

**Comment by nicolaasjan** [comment] 2022-01-16 17:35
@lvqcl
Why the downvote?
I can understand why some people get concerned.

And a backup plan is always wise (GitLab?).

Although it is not very likely that they'll target GitHub again after their previous failure.
This hosting company is just an easier target for them now.

**Comment by lvqcl** [comment] 2022-01-16 17:48
@nicolaasjan 
Because why post the same rejected idea #2121 again?

**Comment by nicolaasjan** [comment] 2022-01-16 17:53
> @nicolaasjan Because why post the same rejected idea #2121 again?

Ah, I see.
I wasn't aware of that...

**Comment by pukkandan** [comment] 2022-01-16 18:27
Duplicate of #2121

@pirate486743186 Don't spam the same "idea" repeatedly

**Closed by pukkandan** 2022-01-16 18:27 UTC
Labels: question

**Comment by pirate486743186** [comment] 2022-01-17 12:48
@pukkandan

It's not a fucking duplicate, the lawsuit is new.
Gitlab is also an other option.

**Comment by Ashish0804** [comment] 2022-01-19 08:03
Lmao just fork it and maintain a copy yourself. Since ur nick starts with "p" aswell so u don't even have to change the name xD.

**Comment by Ashish0804** [comment] 2022-01-19 08:06
@nicolaasjan gitlab complies with DMCA notices too (infact all good platforms do)
If anyone wants backup then best way is to clone the repo locally

**Comment by Lesmiscore** [comment] 2022-01-19 09:07
Push your copies to Keybase.

**Comment by pukkandan** [comment] 2022-01-19 09:50
I have local backup of the repo and all issues (https://github.com/MichaelMure/git-bug). I encourage anyone else who is concerned about this to do the same
