### ISSUE TITLE
Write comments to a separate file (not info.json)

### ISSUE THREAD

**Issue by RadicalGDPRist** [yt-dlp/yt-dlp#3164] opened 2022-03-22 23:20 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

*I'm using yt-dlp with Youtube*

Currently yt-dlp downloads comments and writes them along other data in `.info.json`. I don't think it's a good idea and propose a separate `.comments.json` file to be added.

- Main reason: comments will be lost if .info.json is overwritten
- It's not clear at a glance if there're comments saved. E.g. browsing file directory locally / archive.org uploads

For example these two invocations of yt-dlp will first download and then remove stored comments (comments are erased with the second invocation that runs --write-info-json):

```
$ url='https://www.youtube.com/watch?v=9sETkKlln38'; ../yt-dlp.exe --write-comments -f bestaudio --write-info-json "$url"; ../yt-dlp.exe -f bestvideo --write-info-json "$url"
```

# Possible solutions?

1. Separate comments file, like .description
   - ease of use, clarity, easy to implement
   - downside: what's about embedding into video file? `--embed-info-json` exists and works. Keep comments in both places?
2. Preserve comments in `info.json` by merging
   - keeps current format
   - resolves the issue of overwriting and erasing previously fetched comments
   - merging? lots of work

One day someone will make a tool to read the downloaded comments in a simple way for the user. Then it'll only become a question if the user knows there're comments at all. I imagine a small desktop tool that'd launch a comment viewer (right click -> open with) or in case of archive.org a browser extension that could notify the user automatically. The json format doesn't matter, but it's important to signal the existance of comments (see I'm really pushing for a separate file :)

Comments?

**Comment by pukkandan** [comment] 2022-03-22 23:45
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2372

**Closed by pukkandan** 2022-03-22 23:45 UTC
Labels: enhancement, triage
