### ISSUE TITLE
[FranceTV] Can download video or audio of direct flux, but can't download both at the same time

### ISSUE THREAD

**Issue by pokemaster974** [yt-dlp/yt-dlp#3593] opened 2022-04-29 12:43 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Description
`yt-dlp -F https://www.france.tv/france-2/direct.html`
> [FranceTVSite] direct: Downloading webpage
> [FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading desktop video JSON
> [FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading mobile video JSON
> [FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading signed hls manifest URL
> [FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading m3u8 information
> [FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading signed hls manifest URL
> [FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading m3u8 information
> [info] Available formats for 006194ea-117d-4bcf-94a9-153d999c59ae:
> ID                                EXT RESOLUTION FPS │   TBR PROTO  │ VCODEC        VBR ACODEC     MORE INFO
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> hls-audio_0-2_Audio_Description-0 mp4 audio only     │       m3u8_n │ audio only        unknown    [qad] audio description, 2 Audio Description
> hls-audio_0-2_Audio_Description-1 mp4 audio only     │       m3u8_n │ audio only        unknown    [qad] audio description, 2 Audio Description
> hls-audio_0-1_Francais-0          mp4 audio only     │       m3u8_n │ audio only        unknown    [fra] 1 Francais
> hls-audio_0-1_Francais-1          mp4 audio only     │       m3u8_n │ audio only        unknown    [fra] 1 Francais
> hls-audio_0-3_Version_Originale-0 mp4 audio only     │       m3u8_n │ audio only        unknown    [qaa] 3 Version Originale
> hls-audio_0-3_Version_Originale-1 mp4 audio only     │       m3u8_n │ audio only        unknown    [qaa] 3 Version Originale
> hls-237-0                         mp4 256x144     25 │  237k m3u8_n │ avc1.42C01E  237k video only
> hls-237-1                         mp4 256x144     25 │  237k m3u8_n │ avc1.42C01E  237k video only
> hls-547-0                         mp4 384x216     25 │  547k m3u8_n │ avc1.42C01E  547k video only
> hls-547-1                         mp4 384x216     25 │  547k m3u8_n │ avc1.42C01E  547k video only
> hls-1152-0                        mp4 640x360     25 │ 1152k m3u8_n │ avc1.4D401E 1152k video only
> hls-1152-1                        mp4 640x360     25 │ 1152k m3u8_n │ avc1.4D401E 1152k video only
> hls-1647-0                        mp4 960x540     25 │ 1647k m3u8_n │ avc1.4D401F 1647k video only
> hls-1647-1                        mp4 960x540     25 │ 1647k m3u8_n │ avc1.4D401F 1647k video only
> hls-2857-0                        mp4 1280x720    25 │ 2857k m3u8_n │ avc1.64001F 2857k video only
> hls-2857-1                        mp4 1280x720    25 │ 2857k m3u8_n │ avc1.64001F 2857k video only

Hi, I can download the video with this command :
`yt-dlp -v --restrict-filenames --no-overwrites --no-continue -f "hls-2857-1" -o test.ts https://www.france.tv/france-2/direct.html`
And the audio with this command :
`yt-dlp -v --restrict-filenames --no-overwrites --no-continue -f "hls-audio_0-1_Francais-1" -o test.ts https://www.france.tv/france-2/direct.html`

But if I try to download both at the same time with this command :
`yt-dlp -v --restrict-filenames --no-overwrites --no-continue -f "hls-2857-1"+"hls-audio_0-1_Francais-1" -o test.ts https://www.france.tv/france-2/direct.html`
I got error with authentication error (403)

### Verbose log

```shell
[debug] Command-line config: ['-v', '--restrict-filenames', '--no-overwrites', '--no-continue', '-f', 'hls-2857-1+hls-audio_0-1_Francais-1', '-o', 'test.ts', 'https://www.france.tv/france-2/direct.html']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.8.5 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2021-09-30-git-3ee4502753-essentials_build-www.gyan.dev (setts), ffprobe 2021-09-30-git-3ee4502753-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [FranceTVSite] Extracting URL: https://www.france.tv/france-2/direct.html
[FranceTVSite] direct: Downloading webpage
[debug] [FranceTV] Extracting URL: francetv:006194ea-117d-4bcf-94a9-153d999c59ae
[FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading desktop video JSON
[FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading mobile video JSON
[FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading signed hls manifest URL
[FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading m3u8 information
[FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading signed hls manifest URL
[FranceTV] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 006194ea-117d-4bcf-94a9-153d999c59ae: Downloading 1 format(s): hls-2857-1+hls-audio_0-1_Francais-1
[debug] Invoking downloader on "https://live-ssai.ftven.fr/ZXhwPTE2NTEyNTc3MDl+YWNsPSUyZip+aG1hYz04ZDhiMDI4MmI3NDE5Mjk5MjFmNjU3OWUyNzgxMDQwY2ZiNmUyZjQ5NGI4MWI1Njk1ZjFjODJmNmQzYWFmNWE4/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/bc35bf30-d3fa-4d74-9cf5-8eb53424814f/4.m3u8", "https://live-ssai.ftven.fr/ZXhwPTE2NTEyNTc3MDl+YWNsPSUyZip+aG1hYz04ZDhiMDI4MmI3NDE5Mjk5MjFmNjU3OWUyNzgxMDQwY2ZiNmUyZjQ5NGI4MWI1Njk1ZjFjODJmNmQzYWFmNWE4/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/bc35bf30-d3fa-4d74-9cf5-8eb53424814f/5.m3u8"
[download] Destination: test.ts.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
" -i "https://live-ssai.ftven.fr/ZXhwPTE2NTEyNTc3MDl+YWNsPSUyZip+aG1hYz04ZDhiMDI4MmI3NDE5Mjk5MjFmNjU3OWUyNzgxMDQwY2ZiNmUyZjQ5NGI4MWI1Njk1ZjFjODJmNmQzYWFmNWE4/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/bc35bf30-d3fa-4d74-9cf5-8eb53424814f/4.m3u8" -i "https://live-ssai.ftven.fr/ZXhwPTE2NTEyNTc3MDl+YWNsPSUyZip+aG1hYz04ZDhiMDI4MmI3NDE5Mjk5MjFmNjU3OWUyNzgxMDQwY2ZiNmUyZjQ5NGI4MWI1Njk1ZjFjODJmNmQzYWFmNWE4/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/bc35bf30-d3fa-4d74-9cf5-8eb53424814f/5.m3u8" -c copy -map "0:0" -map "1:0" -f mp4 "file:test.ts.mp4.part"
ffmpeg version 2021-09-30-git-3ee4502753-essentials_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.3.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57.  7.100 / 57.  7.100
  libavcodec     59.  9.101 / 59.  9.101
  libavformat    59.  5.100 / 59.  5.100
  libavdevice    59.  0.101 / 59.  0.101
  libavfilter     8. 10.100 /  8. 10.100
  libswscale      6.  1.100 /  6.  1.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
[tcp @ 000001db7d99f240] Starting connection attempt to 2a02:26f0:2b00:22::687d:3d9 port 443
[tcp @ 000001db7d99f240] Successfully connected to 2a02:26f0:2b00:22::687d:3d9 port 443
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-VERSION:6')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-DISCONTINUITY-SEQUENCE:0')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-04-29T08:41:42.040Z')
[hls @ 000001db7d99e6c0] Skip ('#EXT-OATCLS-SCTE35:/DAlAAAAAyiYAP/wFAUBN7k2f+//GzB0kH4BWLIwum0AAAAA+xXaDw==')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-CUE-OUT:251.000')
[hls @ 000001db7d99e6c0] Skip ('#EXT-OATCLS-SCTE35:/DAgAAAAAyiYAP/wDwUBN7k2f0//HIkmwLptAAAAACB9z5E=')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-CUE-IN')
[hls @ 000001db7d99e6c0] Skip ('#EXT-OATCLS-SCTE35:/DAlAAAAAyiYAP/wFAUBN7lAf+//JY/18H4BYk8guncAAAAA7XkYBQ==')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-CUE-OUT:258.000')
[hls @ 000001db7d99e6c0] Skip ('#EXT-OATCLS-SCTE35:/DAgAAAAAyiYAP/wDwUBN7lAf0//JvJFELp3AAAAAAFgr+A=')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-CUE-IN')
[hls @ 000001db7d99e6c0] Skip ('#EXT-OATCLS-SCTE35:/DAlAAAAAyiYAP/wFAUBN7lKf+//MDeJUH4BZ81guoEAAAAApQTBcw==')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-CUE-OUT:262.000')
[hls @ 000001db7d99e6c0] Skip ('#EXT-OATCLS-SCTE35:/DAgAAAAAyiYAP/wDwUBN7lKf0//MZ9WsLqBAAAAAGxVNfs=')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-CUE-IN')
[hls @ 000001db7d99e6c0] Skip ('#EXT-OATCLS-SCTE35:/DAlAAAAAyiYAP/wFAUBN7lUf+//PnZysH4BhKQwuosAAAAA2gDxEQ==')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-CUE-OUT:283.000')
[hls @ 000001db7d99e6c0] Skip ('#EXT-OATCLS-SCTE35:/DAgAAAAAyiYAP/wDwUBN7lUf0//P/sW4LqLAAAAADB3fvs=')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-CUE-IN')
[hls @ 000001db7d99e6c0] Skip ('#EXT-OATCLS-SCTE35:/DAlAAAAAyiYAP/wFAUBN7lef+//Q95lUH4BWhHAupUAAAAAfr6L5Q==')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-CUE-OUT:252.000')
[hls @ 000001db7d99e6c0] Skip ('#EXT-OATCLS-SCTE35:/DAgAAAAAyiYAP/wDwUBN7lef0//RTh3ELqVAAAAALrfOi4=')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-CUE-IN')
[hls @ 000001db7d99e6c0] Skip ('#EXT-OATCLS-SCTE35:/DAlAAAAAyiYAP/wFAUBN7lof+//Uzn2kH4BiiJwup8AAAAAxf9QSQ==')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-CUE-OUT:287.000')
[hls @ 000001db7d99e6c0] Skip ('#EXT-OATCLS-SCTE35:/DAgAAAAAyiYAP/wDwUBN7lof0//VMQZALqfAAAAAChdt+0=')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-CUE-IN')
[hls @ 000001db7d99e6c0] Skip ('#EXT-OATCLS-SCTE35:/DAlAAAAAyiYAP/wFAUBN7lyf+//V7IUUH4BY66wuqkAAAAAqu5Rkg==')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-CUE-OUT:259.000')
[hls @ 000001db7d99e6c0] Skip ('#EXT-OATCLS-SCTE35:/DAgAAAAAyiYAP/wDwUBN7lyf0//WRXDALqpAAAAABPw47k=')
[hls @ 000001db7d99e6c0] Skip ('#EXT-X-CUE-IN')
[hls @ 000001db7d99e6c0] HLS request for url 'https://live-ssai.ftven.fr/ZXhwPTE2NTEyNTc3MDl+YWNsPSUyZip+aG1hYz04ZDhiMDI4MmI3NDE5Mjk5MjFmNjU3OWUyNzgxMDQwY2ZiNmUyZjQ5NGI4MWI1Njk1ZjFjODJmNmQzYWFmNWE4/out/v1/535afd7806de45fea4e030b74cea3b8f/index_5_952922.ts?m=1633708122', offset 0, playlist 0
[hls @ 000001db7d99e6c0] Opening 'https://live-ssai.ftven.fr/ZXhwPTE2NTEyNTc3MDl+YWNsPSUyZip+aG1hYz04ZDhiMDI4MmI3NDE5Mjk5MjFmNjU3OWUyNzgxMDQwY2ZiNmUyZjQ5NGI4MWI1Njk1ZjFjODJmNmQzYWFmNWE4/v1/key//france2-hls/758a7008-13f9-4c3a-a3c8-a2661b5c575e' for reading
[tcp @ 000001db7d9a6c80] Starting connection attempt to 2a02:26f0:2b00:22::687d:3d9 port 443
[tcp @ 000001db7d9a6c80] Successfully connected to 2a02:26f0:2b00:22::687d:3d9 port 443
[AVIOContext @ 000001db7dbc62c0] Statistics: 16 bytes read, 0 seeks
[hls @ 000001db7d99e6c0] Opening 'crypto+https://live-ssai.ftven.fr/ZXhwPTE2NTEyNTc3MDl+YWNsPSUyZip+aG1hYz04ZDhiMDI4MmI3NDE5Mjk5MjFmNjU3OWUyNzgxMDQwY2ZiNmUyZjQ5NGI4MWI1Njk1ZjFjODJmNmQzYWFmNWE4/out/v1/535afd7806de45fea4e030b74cea3b8f/index_5_952922.ts?m=1633708122' for reading
[tcp @ 000001db7d9a6c80] Starting connection attempt to 2a02:26f0:2b00:22::687d:3d9 port 443
[tcp @ 000001db7d9a6c80] Successfully connected to 2a02:26f0:2b00:22::687d:3d9 port 443
[h264 @ 000001db7da17040] Reinit context to 1280x720, pix_fmt: yuv420p
Input #0, hls, from 'https://live-ssai.ftven.fr/ZXhwPTE2NTEyNTc3MDl+YWNsPSUyZip+aG1hYz04ZDhiMDI4MmI3NDE5Mjk5MjFmNjU3OWUyNzgxMDQwY2ZiNmUyZjQ5NGI4MWI1Njk1ZjFjODJmNmQzYWFmNWE4/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/bc35bf30-d3fa-4d74-9cf5-8eb53424814f/4.m3u8':
  Duration: N/A, start: 84338.370933, bitrate: N/A
  Program 0
    Metadata:
      variant_bitrate : 0
  Stream #0:0: Video: h264 (High), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, left), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn
    Metadata:
      variant_bitrate : 0
  Stream #0:1: Data: scte_35
    Metadata:
      variant_bitrate : 0
  Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
  Stream #0:3: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
[tcp @ 000001db7d9a7300] Starting connection attempt to 2a02:26f0:2b00:22::687d:3d9 port 443
[tcp @ 000001db7d9a7300] Successfully connected to 2a02:26f0:2b00:22::687d:3d9 port 443
[https @ 000001db7dbb46c0] HTTP error 403 Forbidden
https://live-ssai.ftven.fr/ZXhwPTE2NTEyNTc3MDl+YWNsPSUyZip+aG1hYz04ZDhiMDI4MmI3NDE5Mjk5MjFmNjU3OWUyNzgxMDQwY2ZiNmUyZjQ5NGI4MWI1Njk1ZjFjODJmNmQzYWFmNWE4/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/bc35bf30-d3fa-4d74-9cf5-8eb53424814f/5.m3u8: Server returned 403 Forbidden (access denied)
[AVIOContext @ 000001db7daa2e00] Statistics: 396864 bytes read, 0 seeks
[AVIOContext @ 000001db7d9a8540] Statistics: 526057 bytes read, 0 seeks


ERROR: ffmpeg exited with code 1
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\yt-dlp.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\__init__.py", line 869, in main
    _real_main(argv)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\__init__.py", line 859, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 3264, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 3237, in wrapper
    res = func(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 1399, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 1567, in process_ie_result
    return self.extract_info(
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 1399, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 2648, in process_video_result
    self.process_info(new_info)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 3085, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 2846, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\downloader\common.py", line 457, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\downloader\external.py", line 69, in real_download
    self.report_error('%s exited with code %d' % (
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\downloader\common.py", line 178, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 950, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 884, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

**Comment by pukkandan** [comment] 2022-04-29 13:45
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2696

**Closed by pukkandan** 2022-04-29 13:45 UTC
Labels: site-bug, triage
