### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by spirillen** [yt-dlp/yt-dlp#10145] opened 2024-06-09 19:15 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe (Tor network)

### Provide a description that is worded well enough to be understood

ERROR: [youtube] d7i7LT8__FM: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

`/home/$USER/yt-dlp.conf`

```bash
grep -vE "^($|#)" /home/$USER/yt-dlp.conf
--proxy "socks5://127.0.0.1:9050/"
-4
-c
--rm-cache-dir
--embed-thumbnail
--no-cookies
--no-embed-metadata
--write-subs
--sub-format vtt
--audio-quality 0
--ffmpeg-location /home/spirillen/yt-dlp/ffmpeg
--output "%(playlist_index|)s%(playlist_index&. |)s%(title)s.%(ext)s"
-f 'bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4][protocol^=http][protocol!*=dash] / bv*+ba/b'
-S "res:2160,proto,codec:h264"
```

Questions, Just ask

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.youtube.com/playlist?list=PLm5FlhgS5UCBslYKpZs-Y4d6BEEypxua3 --sub-langs "da" 
[debug] Command-line config: ['-vU', 'https://www.youtube.com/playlist?list=PLm5FlhgS5UCBslYKpZs-Y4d6BEEypxua3', '--sub-langs', 'da']
[debug] User config "/home/spirillen/yt-dlp.conf": ['--proxy', 'socks5://127.0.0.1:9050/', '-4', '-c', '--rm-cache-dir', '--embed-thumbnail', '--no-cookies', '--no-embed-metadata', '--write-subs', '--sub-format', 'vtt', '--audio-quality', '0', '--ffmpeg-location', '/home/spirillen/yt-dlp/ffmpeg', '--output', '%(playlist_index|)s%(playlist_index&. |)s%(title)s.%(ext)s', '-f', 'bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4][protocol^=http][protocol!*=dash] / bv*+ba/b', '-S', 'res:2160,proto,codec:h264']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-35-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg N-115551-g4037d5e103-20240603 (setts), ffprobe N-115551-g4037d5e103-20240603, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.45.1, pyxattr-0.7.2, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.0.3, websockets-10.3
[debug] Proxy map: {'all': 'socks5://127.0.0.1:9050/'}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1820 extractors
Removing cache dir /home/spirillen/.cache/yt-dlp ..
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLm5FlhgS5UCBslYKpZs-Y4d6BEEypxua3
[youtube:tab] PLm5FlhgS5UCBslYKpZs-Y4d6BEEypxua3: Downloading webpage
WARNING: [youtube:tab] ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (1/3)...
[youtube:tab] PLm5FlhgS5UCBslYKpZs-Y4d6BEEypxua3: Downloading webpage
[youtube:tab] PLm5FlhgS5UCBslYKpZs-Y4d6BEEypxua3: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Boat Build RAN III
[youtube:tab] PLm5FlhgS5UCBslYKpZs-Y4d6BEEypxua3 page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (1/3)...
[youtube:tab] PLm5FlhgS5UCBslYKpZs-Y4d6BEEypxua3 page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (2/3)...
[youtube:tab] PLm5FlhgS5UCBslYKpZs-Y4d6BEEypxua3 page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (3/3)...
[youtube:tab] PLm5FlhgS5UCBslYKpZs-Y4d6BEEypxua3 page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Giving up after 3 retries
[debug] Skipping writing playlist thumbnail
[youtube:tab] Playlist Boat Build RAN III: Downloading 81 items of 81
[download] Downloading item 1 of 81
[youtube] Extracting URL: https://www.youtube.com/watch?v=8TWL66xmHio
[youtube] 8TWL66xmHio: Downloading webpage
[youtube] 8TWL66xmHio: Downloading ios player API JSON
ERROR: [youtube] 8TWL66xmHio: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
ie_result = self._real_extract(url)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4248, in _real_extract
self.raise_no_formats(reason, expected=True)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1257, in raise_no_formats
raise ExtractorError(msg, expected=expected, video_id=video_id)

[download] Downloading item 2 of 81
[youtube] Extracting URL: https://www.youtube.com/watch?v=v1o1CxIuhAg
[youtube] v1o1CxIuhAg: Downloading webpage
[youtube] v1o1CxIuhAg: Downloading ios player API JSON
ERROR: [youtube] v1o1CxIuhAg: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
ie_result = self._real_extract(url)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4248, in _real_extract
self.raise_no_formats(reason, expected=True)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1257, in raise_no_formats
raise ExtractorError(msg, expected=expected, video_id=video_id)

[download] Downloading item 3 of 81
[youtube] Extracting URL: https://www.youtube.com/watch?v=Vs11sQQdhPM
[youtube] Vs11sQQdhPM: Downloading webpage
[youtube] Vs11sQQdhPM: Downloading ios player API JSON
ERROR: [youtube] Vs11sQQdhPM: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
ie_result = self._real_extract(url)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4248, in _real_extract
self.raise_no_formats(reason, expected=True)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1257, in raise_no_formats
raise ExtractorError(msg, expected=expected, video_id=video_id)

[download] Downloading item 4 of 81
[youtube] Extracting URL: https://www.youtube.com/watch?v=NrRZPVfg1yo
[youtube] NrRZPVfg1yo: Downloading webpage
[youtube] NrRZPVfg1yo: Downloading ios player API JSON
ERROR: [youtube] NrRZPVfg1yo: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
ie_result = self._real_extract(url)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4248, in _real_extract
self.raise_no_formats(reason, expected=True)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1257, in raise_no_formats
raise ExtractorError(msg, expected=expected, video_id=video_id)

[download] Downloading item 5 of 81
[youtube] Extracting URL: https://www.youtube.com/watch?v=1nMGKQPVEcw
[youtube] 1nMGKQPVEcw: Downloading webpage
[youtube] 1nMGKQPVEcw: Downloading ios player API JSON
ERROR: [youtube] 1nMGKQPVEcw: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
ie_result = self._real_extract(url)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4248, in _real_extract
self.raise_no_formats(reason, expected=True)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1257, in raise_no_formats
raise ExtractorError(msg, expected=expected, video_id=video_id)

[download] Downloading item 6 of 81
[youtube] Extracting URL: https://www.youtube.com/watch?v=s6zJDo-wd1w
[youtube] s6zJDo-wd1w: Downloading webpage
[youtube] s6zJDo-wd1w: Downloading ios player API JSON
ERROR: [youtube] s6zJDo-wd1w: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
ie_result = self._real_extract(url)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4248, in _real_extract
self.raise_no_formats(reason, expected=True)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1257, in raise_no_formats
raise ExtractorError(msg, expected=expected, video_id=video_id)

[download] Downloading item 7 of 81
[youtube] Extracting URL: https://www.youtube.com/watch?v=cG15vhj2Sac
[youtube] cG15vhj2Sac: Downloading webpage
[youtube] cG15vhj2Sac: Downloading ios player API JSON
ERROR: [youtube] cG15vhj2Sac: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
ie_result = self._real_extract(url)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4248, in _real_extract
self.raise_no_formats(reason, expected=True)
File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1257, in raise_no_formats
raise ExtractorError(msg, expected=expected, video_id=video_id)

[download] Downloading item 8 of 81
[youtube] Extracting URL: https://www.youtube.com/watch?v=oaco8ITBP4A
[youtube] oaco8ITBP4A: Downloading webpage
^C
ERROR: Interrupted by user
```

**Comment by MrSmite** [comment] 2024-06-10 02:31
I recently experienced this too. Before it happened I was receiving a bunch of "read timeout, retrying" errors.

**Comment by bashonly** [comment] 2024-06-10 03:33
Duplicate of #10128

**Closed by bashonly** 2024-06-10 03:33 UTC
Labels: duplicate, site-bug, site:instagram, site:vimeo

**Comment by spirillen** [comment] 2024-06-10 21:18
> Duplicate of #10128

Fantastic @bashonly, thanks for locating it, I had no success finding a similar issue.
