### ISSUE TITLE
Sponsorblock: an option to wait for data from their api?

### ISSUE THREAD

**Issue by LTGM** [yt-dlp/yt-dlp#10158] opened 2024-06-11 03:56 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I tried to search but didn't find a way how to do that

Is there an option to wait for data from sponsorblock api/server and NOT download the video UNTIL the requested data is received?

It makes no sense for example if I say to remove the ads (from a very long video in 4k quality) to proceed with the download only to find out after a few hours that all ads are still here and there was a one-minute downtime on their side or just some random internet issue where yt-dlp failed to fetch the necessary data and now I have to download everything again and manually check if the data was received properly this time; it is so annoying

Once again, everything works fine for the most part but sometimes it may fail due to their API not responding in time or some other error that may be already fixed a second after this first attempt/ping was sent...

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment] 2024-06-11 04:18
Duplicate of #9953

Could you share some example URLs over in that issue, please?

**Closed by bashonly** 2024-06-11 04:18 UTC
Labels: enhancement, triage
