### ISSUE TITLE
[extractor/nebula] nebula download fails with "Unable to extract Zype access token"

### ISSUE THREAD

**Issue by opensourceiskey** [yt-dlp/yt-dlp#6040] opened 2023-01-15 09:30 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Austria

### Provide a description that is worded well enough to be understood

Starting yesterday it seems that nebula has stopped working with yt-dlp. It says that yt-dlp is not able to extract the Zype access token. Before today it all worked by opening a Video in any browser, but this time it sadly was not enough. It seems nebula.tv has changed the way their how they provide videos. I'm not even sure they use Zype anymore.

In the code there is a comment directly above the line where the error is thrown:
                # TODO: Reimplement the same Zype token polling the Nebula frontend implements
                # see https://github.com/ytdl-org/youtube-dl/pull/24805#issuecomment-749231532
I will find out more about it and come back later, maybe I can find something out.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --netrc -vU https://nebula.tv/videos/tldrnewsuk-could-prince-harrys-book-end-the-monarchy
[debug] Command-line config: ['--netrc', '-vU', 'https://nebula.tv/videos/tldrnewsuk-could-prince-harrys-book-end-the-monarchy']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-125-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg N-109562-g0431f9805e-20230110 (setts), ffprobe N-109562-g0431f9805e-20230110, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.6.1, brotli-1.0.7, certifi-2019.11.28, mutagen-1.44.0, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[Nebula] Logging in to Nebula with supplied credentials
[Nebula] Authorizing to Nebula
[Nebula] Retrieving Zype access token
ERROR: [Nebula] tldrnewsuk-could-prince-harrys-book-end-the-monarchy: Unable to extract Zype access token from Nebula API authentication endpoint. Open an arbitrary video in a browser with this account to generate a token
  File "/home/wedekit8/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 677, in extract
    self.initialize()
  File "/home/wedekit8/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 583, in initialize
    self._perform_login(username, password)
  File "/home/wedekit8/.local/lib/python3.8/site-packages/yt_dlp/extractor/nebula.py", line 149, in _perform_login
    self._zype_access_token = self._fetch_zype_access_token()
  File "/home/wedekit8/.local/lib/python3.8/site-packages/yt_dlp/extractor/nebula.py", line 110, in _fetch_zype_access_token
    raise ExtractorError(
```

**Comment by pukkandan** [comment] 2023-01-15 10:49
Check if https://github.com/yt-dlp/yt-dlp/pull/5979 solves your issue

**Comment by CarlFink** [comment] 2023-01-15 13:50
Having the same issue, and yt-dlp 2023.01.06 does not fix the problem. I am not a developer. Does that include the change from 5979? Thanks.

**Comment by Grub4K** [comment] 2023-01-15 13:56
No, since the PR is still open, which means the code has not been merged with the master branch yet. You will have to wait for a release after the PR status has changed from "Open" to "Merged" or run yt-dlp from source. If you cant do the latter you will unfortunately have to wait.

**Comment by CarlFink** [comment] 2023-01-15 16:35
Thank you, Simon. I appreciate your explaining.Message ID: 
***@***.***>

**Comment by Lamieur** [comment] 2023-01-18 17:09
I checked by just dropping https://raw.githubusercontent.com/hheimbuerger/yt-dlp/nebula-remove-cookie-support/yt_dlp/extractor/nebula.py from #5979 into my installation and yes, it works fine for downloading. However, I mainly use yt-dlp as mpv's backend, and here it completely breaks on rewinding/fast forwarding. It works better if I give mpv the full manifest.m3u8 url directly, but who would want to spend so much time in the debug console ;)

I still say usable enough, we can blame all issues on the site change until our hero @hheimbuerger gets to it. Pull ahead :)

BTW, is there a way to drop in extractors somewhere? Like streamlink has ~/.local/share/streamlink/plugins where I can just drop in whatever.py from a different branch or older version.

(I tried dropping this nebula.py into ~/.config/yt-dlp/plugins/local/yt_dlp_plugins/extractor, but that doesn't work because of different namespaces)

**Comment by CarlFink** [comment] 2023-01-19 03:07
@Lamieur: can you explain that in enough detail that I could do what you did? I know nothing about how yt-dlp actually works, but I gather plugins are python scripts? (Yes, I'm that much of a beginner.)

**Comment by hheimbuerger** [comment] 2023-01-19 10:38
@pukkandan You may assign this issue to me. However, I can confirm that #5979 appears to fix this issue.

```
C:\Videos>yt-dlp --netrc -vU https://nebula.tv/videos/tldrnewsuk-could-prince-harrys-book-end-the-monarchy
[debug] Command-line config: ['--netrc', '-vU', 'https://nebula.tv/videos/tldrnewsuk-could-prince-harrys-book-end-the-monarchy']
[...]
[debug] Git HEAD: a73260c0d
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg n4.4-154-g79c114e1b2-20210930 (setts), ffprobe n4.4-154-g79c114e1b2-20210930, phantomjs 2.1.1
[...]
[Nebula] Logging in to Nebula with supplied credentials
[Nebula] Authorizing to Nebula
[Nebula] Extracting URL: https://nebula.tv/videos/tldrnewsuk-could-prince-harrys-book-end-the-monarchy
[Nebula] tldrnewsuk-could-prince-harrys-book-end-the-monarchy: Fetching video meta data
[Nebula] tldrnewsuk-could-prince-harrys-book-end-the-monarchy: Fetching video stream info
[Nebula] tldrnewsuk-could-prince-harrys-book-end-the-monarchy: Downloading m3u8 information
[...]
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 71
[download] Destination: Could Prince Harry's Book End the Monarchy？ [63c1a29f71ae840001c9d49a].f9269.mp4
```

**Comment by hheimbuerger** [comment] 2023-01-19 10:40
@Lamieur I don't think anything changed that should affect mpv's ability to rewind/fast forward.

Can you research further whether yt-dlp / the Nebula extractor is really the root cause here? If so, could you please open a new issue for that, tagging me in the process?

**Comment by Geneocide** [comment] 2023-01-19 21:21
I have this issue as well, and I'm using username/password for authentication so I don't think #5979 would fix it.

**Comment by pukkandan** [comment] 2023-01-19 21:44
The PR does more than it's title suggests

**Comment by Butterfly-Dragon** [comment] 2023-02-15 09:10
i tried to download from nebula after reading this thread and i finally have it start downloading my queue and also i get that... it finds no videos in my videos 😅:

```
py -m yt_dlp --config-location "D://Downloads//Downloader///!Downloader//youtube-dl.cfg" --cookies "D://Downloads//Downloader///!Downloader//cookies-youtube.txt" -u [REDACTED] -p [REDACTED] https://nebula.app/myshows
[Cookies] Extracting cookies from chrome
[Cookies] Extracted 1579 cookies from chrome
[nebula:subscriptions] Logging in to Nebula with supplied credentials
[nebula:subscriptions] Authorizing to Nebula
[nebula:subscriptions] Extracting URL: https://nebula.app/myshows
[download] Downloading playlist: myshows
[nebula:subscriptions] Playlist myshows: Downloading N/A items
[nebula:subscriptions] myshows: Retrieving subscriptions page 1
[nebula:subscriptions] extramythology-europes-punchiest-undead-myth: Fetching video stream info
[nebula:subscriptions] extramythology-europes-punchiest-undead-myth: Downloading m3u8 information
[download] Downloading item 1 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63eadda4370e930001485de6: No video formats found!
[nebula:subscriptions] legaleagle-this-supreme-court-case-will-destroy-the-internet: Fetching video stream info
[nebula:subscriptions] legaleagle-this-supreme-court-case-will-destroy-the-internet: Downloading m3u8 information
[download] Downloading item 2 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63ebaba6fa3fac0001475edd: No video formats found!
[nebula:subscriptions] extrahistory-the-black-dinner-scotlands: Fetching video stream info
[nebula:subscriptions] extrahistory-the-black-dinner-scotlands: Downloading m3u8 information
[download] Downloading item 3 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63e5923496fad0000105c64b: No video formats found!
[nebula:subscriptions] philosophytube-the-rich-have-their-own-ethics-effective-altruism-the-crypto-crash: Fetching video stream info
[nebula:subscriptions] philosophytube-the-rich-have-their-own-ethics-effective-altruism-the-crypto-crash: Downloading m3u8 information
[download] Downloading item 4 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63e8b4b25084220001f687e1: No video formats found!
[nebula:subscriptions] wendover-the-airline-industrys-problem-with-absolutely-ancient-it: Fetching video stream info
[nebula:subscriptions] wendover-the-airline-industrys-problem-with-absolutely-ancient-it: Downloading m3u8 information
[download] Downloading item 5 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63e51857db9eea0001db0031: No video formats found!
[nebula:subscriptions] extracredits-why-using-ai-art-is-dangerous-in-games: Fetching video stream info
[nebula:subscriptions] extracredits-why-using-ai-art-is-dangerous-in-games: Downloading m3u8 information
[download] Downloading item 6 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63e3f70149654f0001dc173b: No video formats found!
[nebula:subscriptions] jordanharrod-chatgpt-explained-by-chatgpt: Fetching video stream info
[nebula:subscriptions] jordanharrod-chatgpt-explained-by-chatgpt: Downloading m3u8 information
[download] Downloading item 7 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63e2826314672800019bdc97: No video formats found!
[nebula:subscriptions] legaleagle-was-it-legal-to-shoot-down-the-chinese-spy-balloon: Fetching video stream info
[nebula:subscriptions] legaleagle-was-it-legal-to-shoot-down-the-chinese-spy-balloon: Downloading m3u8 information
[download] Downloading item 8 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63e27a5fb586010001f42bbc: No video formats found!
[nebula:subscriptions] practical-engineering-why-some-roadways-are-made-of-styrofoam: Fetching video stream info
[nebula:subscriptions] practical-engineering-why-some-roadways-are-made-of-styrofoam: Downloading m3u8 information
[download] Downloading item 9 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63dace25bb8e77000194c25a: No video formats found!
[nebula:subscriptions] extrahistory-who-wants-to-live-forever-frederick-the-great-5: Fetching video stream info
[nebula:subscriptions] extrahistory-who-wants-to-live-forever-frederick-the-great-5: Downloading m3u8 information
[download] Downloading item 10 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63d9c443aebd450001a137b9: No video formats found!
[nebula:subscriptions] soyouhaventread-so-you-havent-read-snow-crash-by-neal-stephenson: Fetching video stream info
[nebula:subscriptions] soyouhaventread-so-you-havent-read-snow-crash-by-neal-stephenson: Downloading m3u8 information
[download] Downloading item 11 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63d94a5c40ac5e000199a08b: No video formats found!
[nebula:subscriptions] jordanharrod-i-tested-aigenerated-5minute-crafts: Fetching video stream info
[nebula:subscriptions] jordanharrod-i-tested-aigenerated-5minute-crafts: Downloading m3u8 information
[download] Downloading item 12 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63d84ee5e210120001ea3dad: No video formats found!
[nebula:subscriptions] razbuten-2022s-game-of-the-year: Fetching video stream info
[nebula:subscriptions] razbuten-2022s-game-of-the-year: Downloading m3u8 information
[download] Downloading item 13 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63d82b86b8859300011ba67b: No video formats found!
[nebula:subscriptions] razbuten-the-games-that-got-me-through-2022: Fetching video stream info
[nebula:subscriptions] razbuten-the-games-that-got-me-through-2022: Downloading m3u8 information
[download] Downloading item 14 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63d81aa9cdb3c2000156f976: No video formats found!
[nebula:subscriptions] legaleagle-bidens-classified-documents-are-bad: Fetching video stream info
[nebula:subscriptions] legaleagle-bidens-classified-documents-are-bad: Downloading m3u8 information
[download] Downloading item 15 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63d80276bd2a2e00014af55f: No video formats found!
[nebula:subscriptions] extrahistory-the-seven-years-war-frederick-the-great-4-extra-history: Fetching video stream info
[nebula:subscriptions] extrahistory-the-seven-years-war-frederick-the-great-4-extra-history: Downloading m3u8 information
[download] Downloading item 16 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63d466c7ec6c990001c5c362: No video formats found!
[nebula:subscriptions] philosophytube-the-prince-trailer: Fetching video stream info
[nebula:subscriptions] philosophytube-the-prince-trailer: Downloading m3u8 information
[download] Downloading item 17 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63e170f5fc756400013d4fc0: No video formats found!
[nebula:subscriptions] legaleagle-ai-lawyers-are-not-the-future: Fetching video stream info
[nebula:subscriptions] legaleagle-ai-lawyers-are-not-the-future: Downloading m3u8 information
[download] Downloading item 18 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63d2bbebd004e8000111abc6: No video formats found!
[nebula:subscriptions] legaleagle-ai-art-v-copyright-stable-diffusion-lawsuit: Fetching video stream info
[nebula:subscriptions] legaleagle-ai-art-v-copyright-stable-diffusion-lawsuit: Downloading m3u8 information
[download] Downloading item 19 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63d28db44ebcb20001edddb3: No video formats found!
[nebula:subscriptions] extracredits-things-i-learned-on-my-first-game: Fetching video stream info
[nebula:subscriptions] extracredits-things-i-learned-on-my-first-game: Downloading m3u8 information
[download] Downloading item 20 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63d05e996a0f0c00014db5f5: No video formats found!
[nebula:subscriptions] wendover-the-impossible-ethical-bargain-behind-african-safaris: Fetching video stream info
[nebula:subscriptions] wendover-the-impossible-ethical-bargain-behind-african-safaris: Downloading m3u8 information
[download] Downloading item 21 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63d01bd1fcd8050001d9b4fe: No video formats found!
[nebula:subscriptions] extrahistory-forging-a-legend-frederick-the-great-3-extra-history: Fetching video stream info
[nebula:subscriptions] extrahistory-forging-a-legend-frederick-the-great-3-extra-history: Downloading m3u8 information
[download] Downloading item 22 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63cc2eb159ad810001f03db3: No video formats found!
[nebula:subscriptions] legaleagle-alex-jones-is-now-personally-bankrupt: Fetching video stream info
[nebula:subscriptions] legaleagle-alex-jones-is-now-personally-bankrupt: Downloading m3u8 information
[download] Downloading item 23 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63cbfd99ee1c8200014f1d5a: No video formats found!
[nebula:subscriptions] jacob-geller-the-failed-space-weapons-of-the-us-military: Fetching video stream info
[nebula:subscriptions] jacob-geller-the-failed-space-weapons-of-the-us-military: Downloading m3u8 information
[download] Downloading item 24 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63c1991971f41a00016c5062: No video formats found!
[nebula:subscriptions] jacob-geller-the-conceptual-failure-of-orbital-lasers: Fetching video stream info
[nebula:subscriptions] jacob-geller-the-conceptual-failure-of-orbital-lasers: Downloading m3u8 information
[download] Downloading item 25 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63c19a6c71ae840001c9d473: No video formats found!
[nebula:subscriptions] lowspecgamer-full-interview-with-steve-furber: Fetching video stream info
[nebula:subscriptions] lowspecgamer-full-interview-with-steve-furber: Downloading m3u8 information
[download] Downloading item 26 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63cee6a59965c600019798be: No video formats found!
[nebula:subscriptions] lowspecgamer-how-the-bbc-micro-failed-in-america: Fetching video stream info
[nebula:subscriptions] lowspecgamer-how-the-bbc-micro-failed-in-america: Downloading m3u8 information
[download] Downloading item 27 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63cec0cddfa52c0001fe0d6f: No video formats found!
[nebula:subscriptions] lowspecgamer-how-amateurs-created-the-world-most-popular-cpu: Fetching video stream info
[nebula:subscriptions] lowspecgamer-how-amateurs-created-the-world-most-popular-cpu: Downloading m3u8 information
[download] Downloading item 28 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63c7efe9a87c5800011ac3ac: No video formats found!
[nebula:subscriptions] soyouhaventread-so-you-havent-read-slaughterhouse-five-by-kurt-vonnegut: Fetching video stream info
[nebula:subscriptions] soyouhaventread-so-you-havent-read-slaughterhouse-five-by-kurt-vonnegut: Downloading m3u8 information
[download] Downloading item 29 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63c5f048dd46160001b20a49: No video formats found!
[nebula:subscriptions] practical-engineering-what-really-happened-with-the-substation-attacks-in-north-carolina: Fetching video stream info
[nebula:subscriptions] practical-engineering-what-really-happened-with-the-substation-attacks-in-north-carolina: Downloading m3u8 information
[download] Downloading item 30 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63c18b8c71ae840001c9d435: No video formats found!
[nebula:subscriptions] extrahistory-the-school-of-battle-frederick-the-great-2-extra-history: Fetching video stream info
[nebula:subscriptions] extrahistory-the-school-of-battle-frederick-the-great-2-extra-history: Downloading m3u8 information
[download] Downloading item 31 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63c2e68c3f18f600017ce784: No video formats found!
[nebula:subscriptions] legaleagle-dungeons-dragons-rolls-a-1-on-new-license-ogl-11: Fetching video stream info
[nebula:subscriptions] legaleagle-dungeons-dragons-rolls-a-1-on-new-license-ogl-11: Downloading m3u8 information
[download] Downloading item 32 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63c2cc903ea20800011da593: No video formats found!
[nebula:subscriptions] extracredits-when-challenging-quests-are-controversial: Fetching video stream info
[nebula:subscriptions] extracredits-when-challenging-quests-are-controversial: Downloading m3u8 information
[download] Downloading item 33 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63bde2d73276d00001b614ad: No video formats found!
[nebula:subscriptions] wendover-the-one-tiny-law-that-keeps-amtrak-terrible: Fetching video stream info
[nebula:subscriptions] wendover-the-one-tiny-law-that-keeps-amtrak-terrible: Downloading m3u8 information
[download] Downloading item 34 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63bd8bd6a103730001722cbb: No video formats found!
[nebula:subscriptions] extrahistory-worst-childhood-ever-frederick-the-great-1: Fetching video stream info
[nebula:subscriptions] extrahistory-worst-childhood-ever-frederick-the-great-1: Downloading m3u8 information
[download] Downloading item 35 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63b89be2e4ed6e000122513e: No video formats found!
[nebula:subscriptions] extrahistory-the-path-to-pearl-harbor-lies: Fetching video stream info
[nebula:subscriptions] extrahistory-the-path-to-pearl-harbor-lies: Downloading m3u8 information
[download] Downloading item 36 of N/A
[info] There's no subtitles for the requested languages
ERROR: [nebula:subscriptions] 63b88bfc6639eb00011cb3ff: No video formats found!
[nebula:subscriptions] jordan-harrod-the-future-of-large-language-models-qa: Fetching video stream info
[nebula:subscriptions] jordan-harrod-the-future-of-large-language-models-qa: Downloading m3u8 information
```

**Comment by pukkandan** [comment] 2023-02-17 19:18
We are discussing it https://github.com/yt-dlp/yt-dlp/pull/5979#issuecomment-1434456017

I'm closing this since OP's issue is solved

**Closed by pukkandan** 2023-02-17 19:18 UTC
Labels: account-needed, site-bug, can-share-account
