### ISSUE TITLE
ERROR: [youtube] ZkW3aoYhFwY: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

### ISSUE THREAD

**Issue by quanpy** [yt-dlp/yt-dlp#10683] opened 2024-08-07 03:34 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

run :  yt-dlp -F https://www.youtube.com/watch?v=ZkW3aoYhFwY, request error till 2024/8/7

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(base) [root@WiiTube-20230214 ~]# yt-dlp -F https://www.youtube.com/watch?v=ZkW3aoYhFwY
[youtube] Extracting URL: https://www.youtube.com/watch?v=ZkW3aoYhFwY
[youtube] ZkW3aoYhFwY: Downloading webpage
[youtube] ZkW3aoYhFwY: Downloading ios player API JSON
[youtube] ZkW3aoYhFwY: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] ZkW3aoYhFwY: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] ZkW3aoYhFwY: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] ZkW3aoYhFwY: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] ZkW3aoYhFwY: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
```

**Comment by bashonly** [comment] 2024-08-07 03:45
@quanpy you are using a very outdated version of yt-dlp. Update. If you still get the "sign in to confirm" error, then this is a duplicate of #10128 and your IP is blocked

@gadi-playstream-gg all of those IPs are blocked

**Closed by bashonly** 2024-08-07 03:45 UTC
Labels: bug, triage

**Comment by gadi-playstream-gg** [comment] 2024-08-07 05:41
@bashonly so what's the workaround? how people are using it on scale? just locally on their machines?
