### ISSUE TITLE
[youtube] add 1080p premium

### ISSUE THREAD

**Issue by joaquinito2070** [yt-dlp/yt-dlp#6770] opened 2023-04-11 11:30 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Spain

### Provide a description that is worded well enough to be understood

https://blog.youtube/news-and-events/5-premium-features-to-up-your-youtube-game/
From this blog post, 1080p premium is added on iOS.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I:\cuerpo>yt-dlp --list-formats --extractor-args "youtube:player_client=all" -vU --cookies-from-browser opera https://www.youtube.com/watch?v=cOv1GoWVcY4
[debug] Command-line config: ['--list-formats', '--extractor-args', 'youtube:player_client=all', '-vU', '--cookies-from-browser', 'opera', 'https://www.youtube.com/watch?v=cOv1GoWVcY4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg n5.1.3-20230402 (setts), ffprobe n5.1.3-20230402
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from opera
[debug] Extracting cookies from: "C:\Users\joaqu\AppData\Roaming\Opera Software\Opera Stable\Network\Cookies"
[debug] Found local state file at "C:\Users\joaqu\AppData\Roaming\Opera Software\Opera Stable\Local State"
[Cookies] Extracted 6027 cookies from opera
[debug] cookie version breakdown: {'v10': 6027, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Extractor Plugins: AGB+NSIG (YoutubeIE)
[debug] Post-Processor Plugins: ReturnYoutubeDislikePP
[debug] Plugin directories: ['C:\\Users\\joaqu\\AppData\\Roaming\\Python\\Python311\\site-packages\\yt_dlp_plugins']
[debug] Loaded 1791 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[youtube+AGB+NSIG] Extracting URL: https://www.youtube.com/watch?v=cOv1GoWVcY4
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading webpage
[debug] [youtube+AGB+NSIG] Extracted SAPISID cookie
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading android player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading android embedded player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading android music player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading android creator player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading android embedscreen player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading web embedded client config
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading player 7da8dd3e
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading web embedded player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading web music client config
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading web music player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading web creator player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading web embedscreen player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading tv embedded player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading ios player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading ios embedded player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading ios music player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading ios creator player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading ios embedscreen player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading mweb player API JSON
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading mweb embedscreen player API JSON
[debug] Loading youtube-nsig.7da8dd3e from cache
[debug] [youtube+AGB+NSIG] Decrypted nsig SFx9Rvkp4iEKityz3yQ => d4CCqtBAwlmg5A
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading m3u8 information
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading m3u8 information
[youtube+AGB+NSIG] cOv1GoWVcY4: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] Available formats for cOv1GoWVcY4:
ID      EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2     mhtml 48x27        1    │                  mhtml │ images                                  storyboard
sb1     mhtml 80x45        1    │                  mhtml │ images                                  storyboard
sb0     mhtml 160x90       1    │                  mhtml │ images                                  storyboard
233     mp4   audio only        │                  m3u8  │ audio only          unknown             Default, IOS
234     mp4   audio only        │                  m3u8  │ audio only          unknown             Default, IOS
599     m4a   audio only      2 │  722.31KiB   31k dash  │ audio only          mp4a.40.5   31k 22k ultralow, ANDR, m4a_dash
600     webm  audio only      2 │  836.89KiB   36k dash  │ audio only          opus        36k 48k ultralow, ANDR, webm_dash
249-drc webm  audio only      2 │    1.20MiB   53k dash  │ audio only          opus        53k 48k low, DRC, TV-E, webm_dash
250-drc webm  audio only      2 │    1.54MiB   67k dash  │ audio only          opus        67k 48k low, DRC, TV-E, webm_dash
139     m4a   audio only      2 │    1.12MiB   49k dash  │ audio only          mp4a.40.5   49k 22k low, ANDR, m4a_dash
249     webm  audio only      2 │    1.20MiB   52k dash  │ audio only          opus        52k 48k low, ANDR, webm_dash
250     webm  audio only      2 │    1.53MiB   67k dash  │ audio only          opus        67k 48k low, ANDR, webm_dash
140-drc m4a   audio only      2 │    2.96MiB  130k dash  │ audio only          mp4a.40.2  130k 44k medium, DRC, TV-E, m4a_dash
251-drc webm  audio only      2 │    3.04MiB  133k dash  │ audio only          opus       133k 48k medium, DRC, TV-E, webm_dash
140     m4a   audio only      2 │    2.96MiB  130k dash  │ audio only          mp4a.40.2  130k 44k medium, ANDR, m4a_dash
251     webm  audio only      2 │    3.03MiB  133k dash  │ audio only          opus       133k 48k medium, ANDR, webm_dash
17      3gp   176x144     12  1 │    1.76MiB   77k dash  │ mp4v.20.3       77k mp4a.40.2    0k 22k 144p, ANDR
597     mp4   256x144     12    │  760.47KiB   32k dash  │ avc1.4d400b     32k video only          144p, ANDR, mp4_dash
598     webm  256x144     12    │  571.39KiB   24k dash  │ vp9             24k video only          144p, ANDR, webm_dash

602     mp4   256x144     12    │ ~  1.91MiB   82k m3u8  │ vp09.00.10.08   82k video only          IOS
160     mp4   256x144     24    │    1.13MiB   50k dash  │ avc1.4d400c     50k video only          144p, ANDR, mp4_dash
269     mp4   256x144     24    │ ~  3.46MiB  148k m3u8  │ avc1.4D400C    148k video only          IOS
278     webm  256x144     24    │    1.57MiB   69k dash  │ vp9             69k video only          144p, ANDR, webm_dash

603     mp4   256x144     24    │ ~  3.59MiB  153k m3u8  │ vp09.00.11.08  153k video only          IOS
133     mp4   426x240     24    │    2.26MiB   99k dash  │ avc1.4d4015     99k video only          240p, ANDR, mp4_dash
229     mp4   426x240     24    │ ~  5.72MiB  244k m3u8  │ avc1.4D4015    244k video only          IOS
242     webm  426x240     24    │    2.45MiB  107k dash  │ vp9            107k video only          240p, ANDR, webm_dash

604     mp4   426x240     24    │ ~  6.31MiB  269k m3u8  │ vp09.00.20.08  269k video only          IOS
134     mp4   640x360     24    │    4.21MiB  184k dash  │ avc1.4d401e    184k video only          360p, ANDR, mp4_dash
230     mp4   640x360     24    │ ~ 11.13MiB  475k m3u8  │ avc1.4D401E    475k video only          IOS
18      mp4   640x360     24  2 │   10.86MiB  475k dash  │ avc1.42001E    475k mp4a.40.2    0k 44k 360p, ANDR
243     webm  640x360     24    │    5.24MiB  229k dash  │ vp9            229k video only          360p, ANDR, webm_dash

605     mp4   640x360     24    │ ~ 15.10MiB  644k m3u8  │ vp09.00.21.08  644k video only          IOS
135     mp4   854x480     24    │    7.99MiB  350k dash  │ avc1.4d401e    350k video only          480p, ANDR, mp4_dash
231     mp4   854x480     24    │ ~ 16.79MiB  717k m3u8  │ avc1.4D401E    717k video only          IOS
244     webm  854x480     24    │    7.49MiB  327k dash  │ vp9            327k video only          480p, ANDR, webm_dash

606     mp4   854x480     24    │ ~ 22.49MiB  960k m3u8  │ vp09.00.30.08  960k video only          IOS
22      mp4   1280x720    24  2 │ ~ 18.20MiB  777k https │ avc1.64001F    777k mp4a.40.2    0k 44k 720p, ANDR
136     mp4   1280x720    24    │   14.81MiB  648k dash  │ avc1.4d401f    648k video only          720p, ANDR, mp4_dash
232     mp4   1280x720    24    │ ~ 32.28MiB 1377k m3u8  │ avc1.4D401F   1377k video only          IOS
247     webm  1280x720    24    │   13.65MiB  597k dash  │ vp9            597k video only          720p, ANDR, webm_dash

609     mp4   1280x720    24    │ ~ 37.45MiB 1598k m3u8  │ vp09.00.31.08 1598k video only          IOS
137     mp4   1920x1080   24    │   41.59MiB 1819k dash  │ avc1.640028   1819k video only          1080p, ANDR, mp4_dash

270     mp4   1920x1080   24    │ ~105.25MiB 4491k m3u8  │ avc1.640028   4491k video only          IOS
248     webm  1920x1080   24    │   25.59MiB 1120k dash  │ vp9           1120k video only          1080p, ANDR, webm_dash
614     mp4   1920x1080   24    │ ~ 67.90MiB 2897k m3u8  │ vp09.00.40.08 2897k video only          IOS
616     mp4   1920x1080   24    │ ~113.85MiB 4857k m3u8  │ vp09.00.40.08 4857k video only          IOS
```

**Comment by joaquinito2070** [comment] 2023-04-11 11:36
@pukkandan I have premium subscription.

**Comment by ThePhoenix576** [comment] 2023-04-11 17:25
Wow. This is what I'm waiting for. Seems like for AVC it's 1819k vs 4491k. And for VP9 it's 1120k vs 4857k

I wonder if it's just a better compression setting where it is just better overall. Or if it's like a certain times bigger in terms of bitrate. If it's that much better for 1080p 60fps too etc, might be worth the premium price 😉

**Comment by Lesmiscore** [comment] 2023-04-11 17:37
1. Duplicate of https://github.com/yt-dlp/yt-dlp/issues/6769
2. Seems like they're already present in the -F table

Closing

**Closed by Lesmiscore** 2023-04-11 17:37 UTC
Labels: account-needed, site-bug, can-share-account
