### ISSUE TITLE
Support extractor for hanime.tv

### ISSUE THREAD

**Issue by xsbee** [yt-dlp/yt-dlp#4007] opened 2022-06-07 18:33 UTC
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

India

### Example URLs

- Single Video: https://hanime.tv/videos/hentai/kanojo-x-kanojo-x-kanojo-1
- Single Video: https://hanime.tv/videos/hentai/kanojo-x-kanojo-x-kanojo-3
- Single Video: https://hanime.tv/videos/hentai/fuzzy-lips-2
- Playlist: https://hanime.tv/playlists/duuilob7bmyefj5kikbx
- Playlist: https://hanime.tv/videos/hentai/first-love-1?playlist_id=duuilob7bmyefj5kikbx

### Description

hanime.tv is a large video publishing platform catering to Doujinshi consumers. It helps reducing testosterone or estrogen levels of adolescent or adult people. Therefore I conclude that the aforementioned feature will be helpful for many.

For the implementer: https://github.com/rxqv/htv/tree/master/hanimetv

### Verbose log

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.18.1-zen1-1-zen-x86_64-with-glibc2.35
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
```

**Comment by pukkandan** [comment] 2022-06-07 18:51
Duplicate of https://github.com/yt-dlp/yt-dlp/pull/1312

**Closed by pukkandan** 2022-06-07 18:51 UTC
Labels: site-request, triage

**Comment by xsbee** [comment] 2022-06-08 02:22
That's unfortunate. But don't all the pornographic sites (which it has support for) infringe copyright?
