### ISSUE TITLE
NHK World HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by TeppanY** [yt-dlp/yt-dlp#6992] opened 2023-05-05 03:37 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States and most likely worldwide

### Provide a description that is worded well enough to be understood

Document 72 Hours is a weekly show. Two weeks ago (last week's show was a re-run) I successfully downloaded the then-latest show (https://www3.nhk.or.jp/nhkworld/en/ondemand/video/4026193/). Attempting to download the show today results in a 503 error. The same goes for the latest episode as well as a different show I tried for testing.

Episode that worked two weeks ago, April 17, 2023: https://www3.nhk.or.jp/nhkworld/en/ondemand/video/4026193/
Latest episode released May 2, 2023: https://www3.nhk.or.jp/nhkworld/en/ondemand/video/4026194/
Different show from the same site: https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2099001/

All attempted downloads result in 503 error.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www3.nhk.or.jp/nhkworld/en/ondemand/video/4026194/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[NhkVod] Extracting URL: https://www3.nhk.or.jp/nhkworld/en/ondemand/video/4026194/
[NhkVod] 4026-194: Downloading JSON metadata
[Piksel] Extracting URL: https://player.piksel.com/v/refid/nhkworld/prefid/nw_vod_v_en_4026_194_20230502113000_02_1683004957
[Piksel] nw_vod_v_en_4026_194_20230502113000_02_1683004957: Downloading webpage
ERROR: [Piksel] nw_vod_v_en_4026_194_20230502113000_02_1683004957: Unable to download webpage: HTTP Error 503: Service Unavailable (caused by <HTTPError 503: 'Service Unavailable'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\piksel.py", line 79, in _real_extract
  File "yt_dlp\extractor\common.py", line 1097, in _download_webpage
  File "yt_dlp\extractor\common.py", line 1048, in download_content
  File "yt_dlp\extractor\common.py", line 882, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
```

**Comment by bashonly** [comment] 2023-05-05 05:22
Looks like NHK uses their own API for video now instead of the Piksel API.

---
### Notes for devs:

Let's take this URL: https://www3.nhk.or.jp/nhkworld/en/ondemand/video/4026193/ 

The `NhkVod` extractor actually works up until it returns a url to the `Piksel` extractor. So we need to add code to handle the rest of the extraction within nhk.py

Instead of making calls to the Piksel API, the webpage first requests this javascript/html page:
https://movie-s.nhk.or.jp/v/refid/nhkworld/prefid/nw_vod_v_en_4026_193_20230418113000_01_1681787304?embed=js&targetId=videoplayer&de-responsive=true&de-callback-method=nwCustomCallback&de-appid=nw_vod_v_en_4026_193_20230418113000_01_1681787304&de-subtitle-on=false

In the extractor that could be done like this:
```py
        if is_video:
            vod_id = episode['vod_id']
            js_page = self._download_webpage(
                f'https://movie-s.nhk.or.jp/v/refid/nhkworld/prefid/{vod_id}', vod_id,
                'Downloading JS info', query={
                    'embed': 'js',
                    'targetId': 'videoplayer',
                    'de-responsive': True,
                    'de-callback-method': 'nwCustomCallback',
                    'de-appid': vod_id,
                    'de-subtitle-on': False,
                })
```

From that javascript, we need to extract the `data-de-api-key` and `data-de-program-uuid` values:
```js
newVideo.setAttribute('data-de-api-key','67f5b750-b419-11e9-8a16-0e45e8988f42');
newVideo.setAttribute('data-de-program-uuid','dr646i6d');
```
Then we can call this API endpoint, using the `data-de-api-key` value in the URL path and the `data-de-program-uuid` value in the query, which has all the metadata we need:
https://movie-s.nhk.or.jp/ws/ws_program/api/67f5b750-b419-11e9-8a16-0e45e8988f42/apiv/5/mode/json?v=dr646i6d

**Comment by menschel** [comment] 2023-05-20 08:38
You're on the wrong track pal. They just switched to self-hosting.

https://github.com/ytdl-org/youtube-dl/pull/32213

**Comment by bashonly** [comment] 2023-05-20 17:57
@menschel thanks, pal

**Comment by sjthespian** [comment] 2023-05-24 00:12
I just hacked the patch from @menschel into a clone of the yt-dlp repo, and I can confirm that this fixes the problem with downloading video from NHK. If you want, I can fork it into my own repo and submit a PR...

**Comment by pukkandan** [comment] 2023-05-24 06:46
https://github.com/yt-dlp/yt-dlp/issues/4202#issuecomment-1167302440

**Comment by githottub** [comment] 2023-05-25 18:06
> I just hacked the patch from @menschel into a clone of the yt-dlp repo, and I can confirm that this fixes the problem with downloading video from NHK. If you want, I can fork it into my own repo and submit a PR...

Comment referenced by pukkandan (yt-elp member) seems to imply you should proceed with submitting a PR. Hope you will do so and we can see the fix merged into nightly soon. TIA

**Comment by githottub** [comment] 2023-05-28 17:42
Some may not be aware but NHK World only leaves most videos on their site for usually up to a month before they are removed. Because of this unfortunate reality, there are many people desperately awaiting a fix so we can d/l videos which are important to us before they disappear and can no longer be streamed. Imagine you have an autistic child that becomes attached to a video and watches it every day... but, if that routine is disrupted because it's no longer available, they will become distraught. If someone could PLEASE move this forward it would be sincerely appreciated. Thank you!

**Comment by menschel** [comment] 2023-05-29 09:17
> Some may not be aware but NHK World only leaves most videos on their site for usually up to a month before they are removed. Because of this unfortunate reality, there are many people desperately awaiting a fix so we can d/l videos which are important to us before they disappear and can no longer be streamed. Imagine you have an autistic child that becomes attached to a video and watches it every day... but, if that routine is disrupted because it's no longer available, they will become distraught. If someone could PLEASE move this forward it would be sincerely appreciated.

use 
`pip install git+https://github.com/menschel/youtube-dl.git@dev_nhk`
and then download as usual with youtube-dl

I don't intend to push a PR to yt-dlp ever again.

**Comment by githottub** [comment] 2023-05-31 17:04
@menschel ping

Thank you for the install info to your patched version. Sadly, this will not help the many people who are Windows users or don't have the tech savvy to install it on Linux and a CLI rather than a GUI. Since most GUI interfaces have switched over to yt-dlp, it's unfortunate something happened to make you not want to push a PR here. Particularly since your PR for youtube-dl looks like it might become yet another of many that sit there for weeks or months never getting merged despite being good to go. And since no one here has actually moved this issue forward after a month.

**Comment by githottub** [comment] 2023-05-31 19:21
Thanks. I wasn't talking about me but the millions of people who barely know Windows and don't have a clue about anything more technical than using a web browser, word processor, etc. All those people need a GUI based app that simply allows them to paste in a URL and download videos. And since most of the GUI apps now use yt-dlp (due to lack of youtube-dl development) there will be many people stuck until a fix makes in into a PR and then gets officially merged. Anyway, thanks again and if you ever change your mind about putting forth your fix here, it will surely help out many people.

**Comment by githottub** [comment] 2023-05-31 20:19
@sjthespian Thank you!!!

**Closed** 2023-06-01 21:52 UTC
Labels: site-bug

**Comment by bisoh** [comment] 2023-06-10 21:52
> Some may not be aware but NHK World only leaves most videos on their site for usually up to a month before they are removed. Because of this unfortunate reality, there are many people desperately awaiting a fix so we can d/l videos which are important to us before they disappear and can no longer be streamed. Imagine you have an autistic child that becomes attached to a video and watches it every day... but, if that routine is disrupted because it's no longer available, they will become distraught. If someone could PLEASE move this forward it would be sincerely appreciated. Thank you!
> 
> @bashonly ping @sjthespian ping

Should be fixed. I ran `yt-dlp --update-to nightly` and that version works with NHK. However, you need to get the URL of the video from the HTML. Let me know if you need help
