### ISSUE TITLE
 No video formats found!  Facebook reels error 

### ISSUE THREAD

**Issue by vjaideep08** [yt-dlp/yt-dlp#7568] opened 2023-07-11 12:54 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I was using yt-dlp to extract the meta data of the facebook reels and videos. Suddenly the package started throwing the error format not found for facebook reels only. 
the output (error is pasted clearly). someone please help through this.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[facebook:reel] Extracting URL: https://www.facebook.com/reel/792307819122376
[facebook] Extracting URL: https://m.facebook.com/watch/?v=792307819122376&_rdr
[facebook] 792307819122376: Downloading webpage
ERROR: [facebook] 792307819122376: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1709, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1768, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2732, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1073, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [facebook] 792307819122376: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Jayadeep/fb_to_images/url1.py", line 59, in <module>
    info_dict = ydl.extract_info(youtube_url, download=False)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1549, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1709, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1788, in process_ie_result
    return self.extract_info(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1549, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1578, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1042, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 981, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [facebook] 792307819122376: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U


 yt-dlp -U
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)


 yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.19.0-1028-aws-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
```

**Comment by bashonly** [comment] 2023-07-11 12:55
Duplicate of #7469

**Closed by bashonly** 2023-07-11 12:55 UTC
Labels: duplicate, site-bug, site:facebook
