### ISSUE TITLE
NBC.com HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by dwaderich** [yt-dlp/yt-dlp#2342] opened 2022-01-15 01:07 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

NBC.com failing with error HTTP Error 404: Not Found with and without creds.  attached both verbose logs

### Verbose log

```shell
With creds:

[debug] Command-line config: ['https://www.nbc.com/law-and-order-special-victims-unit/video/burning-with-rage-forever/9000172715', '--ap-mso', 'DTV', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--hls-prefer-native', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-89409-g4678339e74, ffprobe N-89409-g4678339e74
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [NBC] Extracting URL: https://www.nbc.com/law-and-order-special-victims-unit/video/burning-with-rage-forever/9000172715
[NBC] 9000172715: Downloading JSON metadata
[NBC] 9000172715: Downloading JSON metadata
[debug] Loading ap-mvpd.nbcentertainment from cache
[NBC] 9000172715: Retrieving Media Token
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/NnzsPC/media/guid/2410887629/9000172715?mbr=true&manifest=m3u&auth=%3CsignatureInfo%3Ekv0oyfX963O2gmOex2IzFVCoaHpNUA%2FulQzvk3AdOibRpOJbfaOfadjDPXeWbQ6IRmRPzlU7lDVDoDMcEVPabQpMxfpeJos7pea0%2BMxHc77UzWCkuKWuzQB8xD2H9Uyvd9E2qZ%2FT4DaFx8A5VKjdzXcw4CVUCG49PWnITQYmia4%3D%3CsignatureInfo%3E%3CauthToken%3E%3CsessionGUID%3Ec4eb8118591bf13d2af8124070396b97%3C%2FsessionGUID%3E%3CrequestorID%3Enbcentertainment%3C%2FrequestorID%3E%3CresourceID%3E%3C%21%5BCDATA%5B%3Crss+version%3D%222.0%22+xmlns%3Amedia%3D%22http%3A%2F%2Fsearch.yahoo.com%2Fmrss%2F%22%3E%3Cchannel%3E%3Ctitle%3Enbcentertainment%3C%2Ftitle%3E%3Citem%3E%3Ctitle%3EBurning+with+Rage+Forever%3C%2Ftitle%3E%3Cguid%3E9000172715%3C%2Fguid%3E%3Cmedia%3Arating+scheme%3D%22urn%3Av-chip%22%3ETV-14%3C%2Fmedia%3Arating%3E%3C%2Fitem%3E%3C%2Fchannel%3E%3C%2Frss%3E%5D%5D%3E%3C%2FresourceID%3E%3Cttl%3E420000%3C%2Fttl%3E%3CissueTime%3E2022-01-14+17%3A02%3A32+-0800%3C%2FissueTime%3E%3CmvpdId%3EDTV%3C%2FmvpdId%3E%3C%2FauthToken%3E#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 9000172715: Downloading SMIL data
[ThePlatform] 9000172715: Downloading m3u8 information
WARNING: [ThePlatform] Failed to download m3u8 information: HTTP Error 404: Not Found
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] 9000172715: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
ERROR: [ThePlatform] 9000172715: Requested format is not available
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1437, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1541, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1489, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2535, in process_video_result
yt_dlp.utils.ExtractorError: [ThePlatform] 9000172715: Requested format is not available




Without creds:

[debug] Command-line config: ['https://www.nbc.com/law-and-order-special-victims-unit/video/burning-with-rage-forever/9000172715', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-89409-g4678339e74, ffprobe N-89409-g4678339e74
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [NBC] Extracting URL: https://www.nbc.com/law-and-order-special-victims-unit/video/burning-with-rage-forever/9000172715
[NBC] 9000172715: Downloading JSON metadata
[NBC] 9000172715: Downloading JSON metadata
[debug] Loading ap-mvpd.nbcentertainment from cache
[NBC] 9000172715: Retrieving Media Token
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/NnzsPC/media/guid/2410887629/9000172715?mbr=true&manifest=m3u&auth=%3CsignatureInfo%3EDTicHpyrjqGOXkgcicsss2q6DhEyygwFO8NBsgqRC%2FshCQ6pBVdbrMdV3f6MnIdTEhPBwrhE%2BA6GHZkZ3aGI0qhv9wh%2Fs%2Fw4Zp5Q9ute8gjJ%2B1s49JXzcpkJzmDMbJa7IM3M9qg49o%2FznbN812jIl68%2FDnsEVeSon4Oxjn6jmAI%3D%3CsignatureInfo%3E%3CauthToken%3E%3CsessionGUID%3Ec4eb8118591bf13d2af8124070396b97%3C%2FsessionGUID%3E%3CrequestorID%3Enbcentertainment%3C%2FrequestorID%3E%3CresourceID%3E%3C%21%5BCDATA%5B%3Crss+version%3D%222.0%22+xmlns%3Amedia%3D%22http%3A%2F%2Fsearch.yahoo.com%2Fmrss%2F%22%3E%3Cchannel%3E%3Ctitle%3Enbcentertainment%3C%2Ftitle%3E%3Citem%3E%3Ctitle%3EBurning+with+Rage+Forever%3C%2Ftitle%3E%3Cguid%3E9000172715%3C%2Fguid%3E%3Cmedia%3Arating+scheme%3D%22urn%3Av-chip%22%3ETV-14%3C%2Fmedia%3Arating%3E%3C%2Fitem%3E%3C%2Fchannel%3E%3C%2Frss%3E%5D%5D%3E%3C%2FresourceID%3E%3Cttl%3E420000%3C%2Fttl%3E%3CissueTime%3E2022-01-14+17%3A05%3A43+-0800%3C%2FissueTime%3E%3CmvpdId%3EDTV%3C%2FmvpdId%3E%3C%2FauthToken%3E#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 9000172715: Downloading SMIL data
[ThePlatform] 9000172715: Downloading m3u8 information
WARNING: [ThePlatform] Failed to download m3u8 information: HTTP Error 404: Not Found
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] 9000172715: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
ERROR: [ThePlatform] 9000172715: Requested format is not available
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1437, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1541, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 1489, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2535, in process_video_result
yt_dlp.utils.ExtractorError: [ThePlatform] 9000172715: Requested format is not available
```

**Comment by rgiuffre** [comment] 2022-01-17 10:15
https://www.nbc.com/this-is-us/video/the-challenger/9000177989

Also not working, but plays in MS-Edge. No credentials necessary.

**Comment by pukkandan** [comment] 2022-01-17 13:50
Duplicate of #1032

**Closed by pukkandan** 2022-01-17 13:50 UTC
Labels: account-needed, site-bug
