### ISSUE TITLE
Download not working for afreecatv.com VODs

### ISSUE THREAD

**Issue by ScoobyDoo2021** [yt-dlp/yt-dlp#6347] opened 2023-02-25 00:08 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Trying to download a VOD from afreecatv.com but getting Verbose Output pasted below.

URL of the VOD:
https://vod.afreecatv.com/player/98749112

The VOD can be played even if not logged into site.

(afreecatv.com is the Korean version of Twitch.com)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://vod.afreecatv.com/player/98749112', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109920-gac6eec1fc2-20230224 (setts)
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[afreecatv] Extracting URL: https://vod.afreecatv.com/player/98749112
[afreecatv] 98749112: Downloading webpage
ERROR: [afreecatv] 98749112: Unable to extract station; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 693, in extract
  File "yt_dlp\extractor\afreecatv.py", line 232, in _real_extract
  File "yt_dlp\extractor\common.py", line 1241, in _search_regex
```

**Comment by bashonly** [comment] 2023-02-25 00:17
Duplicate of #6133

Will be fixed by #6283

Please use the appropriate issue template in the future

**Closed by bashonly** 2023-02-25 00:17 UTC
Labels: question
