### ISSUE TITLE
[DRTV] Unable to download JSON metadata: HTTP Error 404 (dr.dk)

### ISSUE THREAD

**Issue by PhilFra** [yt-dlp/yt-dlp#8298] opened 2023-10-06 19:42 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Denmark

### Provide a description that is worded well enough to be understood

Downloading from "https://www.dr.dk/drtv/tv-guide" (Supported site "DRTV") was no problem 3 days ago. Since then, attempts to download previous broadcasts have resulted in the following error: 

_Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)_

A test can be done with this url:
_yt-dlp.exe "https://www.dr.dk/drtv/se/alene-i-vildmarken_-opfindsomme-shelters_169521"_

Downloading something from "https://www.dr.dk/drtv/tv-guide" 5 minutes after a direct transmission ends is no problem. I think that the transmission then is transcoded into different formats, and these transcoded formats can no longer be downloaded because of a missing JSON.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe -vU "https://www.dr.dk/drtv/se/alene-i-vildmarken_-opfindsomme-shelters_169521"
[debug] Command-line config: ['-vU', 'https://www.dr.dk/drtv/se/alene-i-vildmarken_-opfindsomme-shelters_169521']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.10.04.180415 [b095fd3fa] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-03-07-git-e645a1ddb9-essentials_build-www.gyan.dev (setts), ffprobe 2022-03-07-git-e645a1ddb9-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.10.04.180415, Current version: nightly@2023.10.04.180415
Current Build Hash: 00fc0b80ab8bf1f1d3acc7002a6f078bb0574f63e6a6e2dcf18d82e736c9f482
yt-dlp is up to date (nightly@2023.10.04.180415)
[drtv] Extracting URL: https://www.dr.dk/drtv/se/alene-i-vildmarken_-opfindsomme-shelters_169521
[drtv] alene-i-vildmarken_-opfindsomme-shelters_169521: Downloading webpage
[drtv] 00922000810: Downloading video JSON
ERROR: [drtv] alene-i-vildmarken_-opfindsomme-shelters_169521: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\drtv.py", line 203, in _real_extract
  File "yt_dlp\extractor\common.py", line 1069, in download_content
  File "yt_dlp\extractor\common.py", line 1033, in download_handle
  File "yt_dlp\extractor\common.py", line 903, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 860, in _request_webpage

  File "yt_dlp\networking\_urllib.py", line 410, in _send
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4051, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_urllib.py", line 415, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 847, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4070, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found
```

**Comment by bashonly** [comment] 2023-10-06 19:47
see also https://github.com/ytdl-org/youtube-dl/issues/32581

**Comment by fredvej** [comment] 2023-10-07 07:44
@garret1317 regarding the tag: drtv may be geoblocked from abroad, but the problem is also present when trying to download from Denmark.

On Linux the verbose output is:
`[debug] Command-line config: ['-vU', 'https://www.dr.dk/drtv/se/alene-i-vildmarken_-opfindsomme-shelters_169521']
[debug] User config "/home/freddy/.config/yt-dlp/config": ['--paths', '~/Videos/youtube-dl', '--output', '%(title)s.%(upload_date)s.%(vcodec)s.%(acodec)s.%(autonumber)02d.%(ext)s', '--restrict-filenames', '--all-subs', '--embed-subs', '--embed-metadata', '--no-overwrites', '--no-playlist', '--min-sleep-interval', '1', '--max-sleep-interval', '2', '--concurrent-fragments', '4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (zip)
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-6.1.55-1-MANJARO-x86_64-with-glibc2.38 (OpenSSL 3.1.3 19 Sep 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: certifi-2023.07.22, sqlite3-3.43.1
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.07, Current version: stable@2023.10.07
Current Build Hash: 47743cde1f66f16f8ef8440b78171877122b1277f906dbebfb7d49fb4c64ab0b
yt-dlp is up to date (stable@2023.10.07)
[drtv] Extracting URL: https://www.dr.dk/drtv/se/alene-i-vildmarken_-opfindsomme-shelters_169521
[drtv] alene-i-vildmarken_-opfindsomme-shelters_169521: Downloading webpage
[drtv] 00922000810: Downloading video JSON
ERROR: [drtv] alene-i-vildmarken_-opfindsomme-shelters_169521: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/freddy/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/extractor/drtv.py", line 203, in _real_extract
    data = self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/extractor/common.py", line 1069, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/extractor/common.py", line 1033, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/extractor/common.py", line 903, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/extractor/common.py", line 860, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/freddy/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 410, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/freddy/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4051, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 415, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/freddy/bin/yt-dlp/yt_dlp/extractor/common.py", line 847, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4070, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found
`

**Comment by Marge-Innovera** [comment] 2023-10-07 15:33
Confirming that I get the same error message on both geoblocked and unrestricted content. 

The URLs play fine in a browser, but yt-dlp is getting the 404 error listed above by the previous poster.

**Comment by PhilFra** [comment] 2023-10-07 21:57
bashonly refers to #32581 that is the exact same isue. And they point to svtplay_dl that works with links from drtv with this error. Svtplay_dl seems to have fixed the problem. There is no need to continue this thead. Follow #32581 instead.

**Comment by bashonly** [comment] 2023-10-07 22:10
The extractor still needs to be fixed in *this* project. I was only linking the upstream issue to share information. Reopening

**Comment by thomasdn** [comment] 2023-10-14 13:35
If anyone needs to be able to route traffic through Denmark in order to test this, please get in touch.

**Comment by fredvej** [comment] 2023-10-14 19:36
Testing nightly build from Denmark, error still present.
```[debug] Command-line config: ['-vU', 'https://www.dr.dk/drtv/se/alene-i-vildmarken_-opfindsomme-shelters_169521']
[debug] User config "/home/freddy/.config/yt-dlp/config": ['--paths', '~/Videos/youtube-dl', '--output', '%(title)s.%(upload_date)s.%(vcodec)s.%(acodec)s.%(autonumber)02d.%(ext)s', '--restrict-filenames', '--all-subs', '--embed-subs', '--embed-metadata', '--no-overwrites', '--no-playlist', '--min-sleep-interval', '1', '--max-sleep-interval', '2', '--concurrent-fragments', '4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version nightly@2023.10.13.233318 [8a8b54523] (zip)
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-6.1.55-1-MANJARO-x86_64-with-glibc2.38 (OpenSSL 3.1.3 19 Sep 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: certifi-2023.07.22, requests-2.28.2, sqlite3-3.43.1, urllib3-1.26.15
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.10.13.233318, Current version: nightly@2023.10.13.233318
Current Build Hash: 9a8cdff1568c6943e52c8a0e6c9d8002ffd68cbfa20a3b19af2d307510fde0ed
yt-dlp is up to date (nightly@2023.10.13.233318)
[drtv] Extracting URL: https://www.dr.dk/drtv/se/alene-i-vildmarken_-opfindsomme-shelters_169521
[drtv] alene-i-vildmarken_-opfindsomme-shelters_169521: Downloading webpage
[drtv] 00922000810: Downloading video JSON
ERROR: [drtv] alene-i-vildmarken_-opfindsomme-shelters_169521: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/freddy/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/extractor/drtv.py", line 203, in _real_extract
    data = self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/extractor/common.py", line 1069, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/extractor/common.py", line 1033, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/extractor/common.py", line 903, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/extractor/common.py", line 860, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/freddy/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 396, in _send
    res = opener.open(urllib_req, timeout=float(request.extensions.get('timeout') or self.timeout))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/freddy/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4051, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/networking/common.py", line 114, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/networking/_helper.py", line 204, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/networking/common.py", line 325, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 401, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/freddy/bin/yt-dlp/yt_dlp/extractor/common.py", line 847, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/freddy/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4073, in urlopen
    raise _CompatHTTPError(e) from e
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found
```

**Comment by anders55j** [comment] 2023-10-16 01:17
I'm pretty sure the content that isn't geo-restricted has the same problem. For example: https://www.dr.dk/drtv/episode/explainer_-hvordan-fjerner-man-co2-fra-luften_409062

**Comment by 0HAg0** [comment] 2023-10-16 15:13
It has nothing to do with geo-restrictions. DRTV has changed the way the site works, which has coursed problems - not only for yt-dlp but also for similar programs like for example TV4ever.

**Comment by gamer191** [comment] 2023-10-19 12:23
@0HAg0 we know. That label is just so developers know which issues they can work on. A developer in America can't work on a site that's geo-restricted to Denmark (unless they have a VPN), so it's helpful that this site has videos that aren't geo-restricted

**Comment by 0HAg0** [comment] 2023-10-20 19:32
> @0HAg0 we know. That label is just so developers know which issues they can work on. A developer in America can't work on a site that's geo-restricted to Denmark (unless they have a VPN), so it's helpful that this site has videos that aren't geo-restricted
> 
> EDIT: to clarify, developers can work on whatever they want, but practically speaking idk how a developer could work on a site they can't access

Thank you, for enlightening me.

**Comment by and-hammer** [comment] 2023-10-26 20:20
As a side note, in case anyone is working on this issue: yt-dlp grabs the wrong extractor when attempting to download content links of the type "serie". The other types (e.g. "episode", "saeson") did not seem to have that issue before this JSON metadata issue was reported. So be aware of the links used to test possible solutions.

**Comment by almx** [comment] 2023-11-04 00:20
I am close to finalizing my work to fix the DRTV extractor in PR #8484 and hope to have it ready soon.

**Comment by henrik-jensen** [comment] 2023-11-12 02:21
> I am close to finalizing my work to fix the DRTV extractor in PR #8484 and hope to have it ready soon.

@almx 
Can you give some advise on how to checkout your patch on a Windows 10 machine native or with WSL (Ubuntu 22.04/20.04/18.04)?
I've only used the binary exe previously, though I have installed "Python 3.11.3" in my path.

**Closed** 2023-11-15 22:42 UTC
Labels: site-bug, triage

**Comment by 0HAg0** [comment] 2023-12-06 22:17
I get this error:
[debug] Command-line config: ['https://www.dr.dk/drtv/se/kriminalkommissaer-barnaby_411314', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-167-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg N-112750-g6d60cc7baf-20231114 (setts), ffprobe N-112750-g6d60cc7baf-20231114
[debug] Optional libraries: Cryptodome-3.19.0, certifi-2019.11.28, requests-2.22.0, secretstorage-2.3.1, sqlite3-3.31.1, urllib3-1.25.8
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1901 extractors
[drtv] Downloading anonymous token
[drtv] Extracting URL: https://www.dr.dk/drtv/se/kriminalkommissaer-barnaby_411314
[drtv] kriminalkommissaer-barnaby_411314: Downloading webpage
[drtv] 00022363080: Downloading stream data
[drtv] 00022363080: Downloading m3u8 information
[drtv] 00022363080: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 00022363080: Downloading 1 format(s): video_hls-5671+video_hls-audio_medium-English
[debug] Invoking hlsnative downloader on "https://drod20b.akamaized.net/dk/encrypted/none/02/656c4e1bc4af574840769c02/00022363080/stream_fmp4/Kriminalkommiss_DRTV2022Jan_FullHD_16x9_VideoMain_video_5500.m3u8?aka_me_session_id=AAAAAAAAAACLQXJlAAAAAN1rKjD7TFvvmYByEZppNPIep46vohIEkEeqoG%2foQ6LtV91z3hWlHc8G9DBAewgeA%2fgnkd1ctg3U&aka_media_format_type=hls"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 534
[download] Destination: Kriminalkommissær Barnaby [00022363080].fvideo_hls-5671.mp4

[download]   0.6% of ~ 418.58KiB at    1.93KiB/s ETA Unknown (frag 2/534)
[download]   0.4% of ~ 558.34KiB at    1.93KiB/s ETA Unknown (frag 3/534)
[download]   0.7% of ~ 418.62KiB at    3.28KiB/s ETA Unknown (frag 3/534)
[download]   0.6% of ~ 523.44KiB at    3.28KiB/s ETA Unknown (frag 4/534)ERROR: Data must be padded to 16 byte boundary in CBC mode
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2922, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3370, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3109, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/hls.py", line 375, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 516, in download_and_append_fragments
    decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 364, in decrypt_fragment
    return unpad_pkcs7(aes_cbc_decrypt_bytes(frag_content, decrypt_info['KEY'], iv))
  File "/usr/local/bin/yt-dlp/yt_dlp/aes.py", line 11, in aes_cbc_decrypt_bytes
    return Cryptodome.AES.new(key, Cryptodome.AES.MODE_CBC, iv).decrypt(data)
  File "/home/henrik/.local/lib/python3.8/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 246, in decrypt
    raise ValueError("Data must be padded to %d byte boundary in CBC mode" % self.block_size)
ValueError: Data must be padded to 16 byte boundary in CBC mode


**Same error with this url, and Python 3.10.12** :
[debug] Command-line config: ['-v', 'https://www.dr.dk/drtv/se/chelsea-detective_-det-blaa-rum_414364']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-88-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg N-112777-g08e97dae20-20231117 (setts), ffprobe N-112777-g08e97dae20-20231117
[debug] Optional libraries: Cryptodome-3.19.0, certifi-2020.06.20, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1901 extractors
[drtv] Downloading anonymous token
[drtv] Extracting URL: https://www.dr.dk/drtv/se/chelsea-detective_-det-blaa-rum_414364
[drtv] chelsea-detective_-det-blaa-rum_414364: Downloading webpage
[drtv] 00022363960: Downloading stream data
[drtv] 00022363960: Downloading m3u8 information
[drtv] 00022363960: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 00022363960: Downloading 1 format(s): video_hls-5672+video_hls-audio_medium-English
[debug] Invoking hlsnative downloader on "https://drod21k.akamaized.net/dk/encrypted/none/b7/654b0902eb177a1c409dccb7/00022363960/stream_fmp4/Chelsea-Detecti_DRTV2022Jan_FullHD_16x9_VideoMain_video_5500.m3u8?aka_me_session_id=AAAAAAAAAABuCVplAAAAAGfCnp0vRNdMK5N3%2fhQ6DmXtHO3peD9FhqdTIUM2H5SIv9D2XHaXLz1TlvK4YL0HbUqBg5dovUgP&aka_media_format_type=hls"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 536
[download] Destination: Chelsea Detective： Det blå rum [00022363960].fvideo_hls-5672.mp4

[download]   0.2% of ~ 419.80KiB at      0.00B/s ETA Unknown (frag 0/536)
[download]   0.1% of ~ 840.64KiB at      0.00B/s ETA Unknown (frag 1/536)
[download]   0.4% of ~ 420.06KiB at    5.92KiB/s ETA Unknown (frag 1/536)
[download]   0.2% of ~ 630.48KiB at    5.92KiB/s ETA Unknown (frag 2/536)ERROR: Data must be padded to 16 byte boundary in CBC mode
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2922, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3370, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3109, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/hls.py", line 375, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 516, in download_and_append_fragments
    decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 364, in decrypt_fragment
    return unpad_pkcs7(aes_cbc_decrypt_bytes(frag_content, decrypt_info['KEY'], iv))
  File "/usr/local/bin/yt-dlp/yt_dlp/aes.py", line 11, in aes_cbc_decrypt_bytes
    return Cryptodome.AES.new(key, Cryptodome.AES.MODE_CBC, iv).decrypt(data)
  File "/home/henrik/.local/lib/python3.10/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 246, in decrypt
    raise ValueError("Data must be padded to %d byte boundary in CBC mode" % self.block_size)
ValueError: Data must be padded to 16 byte boundary in CBC mode

**Comment by bashonly** [comment] 2023-12-06 22:19
Unrelated to the issue you are replying to. As a workaround try it with `--downloader ffmpeg`
