### ISSUE TITLE
[youtube] `-f 18`: Got error: 0 bytes read, 10126891 more expected

### ISSUE THREAD

**Issue by geroale** [yt-dlp/yt-dlp#10536] opened 2024-07-22 18:08 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The itag 18 of this video is not working, probably because of the poToken experiment.
https://www.youtube.com/watch?v=A5ab7U9RVLE
Possibly there are many more videos out there with the same problem.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp_macos -f 18 --rm-cache-dir --no-cache-dir -- "https://www.youtube.com/watch?v=A5ab7U9RVLE"
Cache is disabled (Did you combine --no-cache-dir and --rm-cache-dir?)
[youtube] Extracting URL: https://www.youtube.com/watch?v=A5ab7U9RVLE
[youtube] A5ab7U9RVLE: Downloading webpage
WARNING: [youtube] Webpage contains broken formats (poToken experiment detected). Ignoring initial player response
[youtube] A5ab7U9RVLE: Downloading ios player API JSON
[youtube] A5ab7U9RVLE: Downloading player 38c5c1c9
[youtube] A5ab7U9RVLE: Downloading web player API JSON
[youtube] A5ab7U9RVLE: Downloading m3u8 information
[info] A5ab7U9RVLE: Downloading 1 format(s): 18
[download] Destination: Lazza - CENERE [A5ab7U9RVLE].mp4
[download]   0.6% of    9.77MiB at  696.18KiB/s ETA 00:14[download] Got error: 82894 bytes read, 9940589 more expected. Retrying (1/10)...
[download] Got error: 0 bytes read, 10126891 more expected. Retrying (2/10)...
[download] Got error: 0 bytes read, 10178039 more expected. Retrying (3/10)...
[download] Got error: 0 bytes read, 10178039 more expected. Retrying (4/10)...
[download] Got error: 0 bytes read, 10178039 more expected. Retrying (5/10)...
[download] Got error: 0 bytes read, 9961941 more expected. Retrying (6/10)...
[download] Got error: 0 bytes read, 10178039 more expected. Retrying (7/10)...
[download] Got error: 0 bytes read, 10047259 more expected. Retrying (8/10)...
[download] Got error: 0 bytes read, 10081444 more expected. Retrying (9/10)...
[download] Got error: 0 bytes read, 10089770 more expected. Retrying (10/10)...
[download] Got error: 0 bytes read, 10178039 more expected. Giving up after 10 retries
```

**Comment by bashonly** [comment] 2024-07-22 18:12
Unrelated to potoken (which causes HTTP Error 403). I was able to extract the url without any potoken warnings and I still experienced the "0 bytes read" errors from your log. If you can't reproduce this with other videos, then it's very likely that format 18 is just broken on Youtube's end for this video. This happens with some videos and there's nothing we can do about it.

**Comment by bashonly** [comment] 2024-07-24 05:30
Closing as duplicate of #3372

**Closed by bashonly** 2024-07-24 05:30 UTC
Labels: question
