### ISSUE TITLE
Youtube Download now fails with API error

### ISSUE THREAD

**Issue by dubrowin** [yt-dlp/yt-dlp#11518] opened 2024-11-12 08:42 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Israel and US

### Provide a description that is worded well enough to be understood

When trying to download a youtube URL, I am receiving an error.

`Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)`

The problem started for me on Nov 11th around 14:25 UTC.
I have tried the latest build and the nightly build.

**Latest:**

`yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (pip)
[debug] Python 3.10.12 (CPython aarch64 64bit) - Linux-6.8.0-1018-aws-aarch64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.46.0, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Extractor Plugins: oauth2 (YoutubeBaseInfoExtractor), oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeFeedsInfoExtractor), oauth2 (YoutubeHistoryIE), oauth2 (YoutubeIE), oauth2 (YoutubeLivestreamEmbedIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubePlaylistIE), oauth2 (YoutubeRecommendedIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeShortsAudioPivotIE), oauth2 (YoutubeSubscriptionsIE), oauth2 (YoutubeTabBaseInfoExtractor), oauth2 (YoutubeTabIE), oauth2 (YoutubeTruncatedIDIE), oauth2 (YoutubeTruncatedURLIE), oauth2 (YoutubeWatchLaterIE), oauth2 (YoutubeYtBeIE), oauth2 (YoutubeYtUserIE)
[debug] Plugin directories: ['/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp_plugins']
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.04 from yt-dlp/yt-dlp)`

**Nightly:**

`yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.11.11.232805 from yt-dlp/yt-dlp-nightly-builds [a9f85670d] (zip)
[debug] Python 3.12.3 (CPython aarch64 64bit) - Linux-6.8.0-1016-aws-aarch64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.0.7, websockets-14.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.11.11.232805 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.11.11.232805 from yt-dlp/yt-dlp-nightly-builds)`

I've also tried both the yt-dlp-youtube-oauth2 plugin and the new native auth. Both give the same error.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU --verbose --no-playlist -ca /tmp/youtube-download.sh.tmp -o "%(title)s-%(id)s.%(ext)s" --remux-video mp4  --restrict-filenames --username=oauth --password ''
[debug] Command-line config: ['-vU', '--verbose', '--no-playlist', '-ca', '/tmp/youtube-download.sh.tmp', '-o', '%(title)s-%(id)s.%(ext)s', '--remux-video', 'mp4', '--restrict-filenames', '--username=PRIVATE', '--password', 'PRIVATE']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=jGK7dWd8o6Y']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.11.11.232805 from yt-dlp/yt-dlp-nightly-builds [a9f85670d] (zip)
[debug] Python 3.12.3 (CPython aarch64 64bit) - Linux-6.8.0-1016-aws-aarch64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.0.7, websockets-14.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.11.11.232805 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.11.11.232805 from yt-dlp/yt-dlp-nightly-builds)
[debug] Loading youtube.oauth_refresh_token_default from cache
[youtube] oauth: Refreshing access token
[debug] [youtube] oauth: Logged in using profile "default"
[youtube] Extracting URL: https://www.youtube.com/watch?v=jGK7dWd8o6Y
[youtube] jGK7dWd8o6Y: Downloading webpage
[youtube] jGK7dWd8o6Y: Downloading ios player API JSON
[youtube] jGK7dWd8o6Y: Downloading mweb player API JSON
[debug] Loading youtube-nsig.6f0e2ed6 from cache
[debug] [youtube] Decrypted nsig 6S7pgpxk5VAHQZtF4 => eV531PHbNgZFcg
[debug] Loading youtube-nsig.6f0e2ed6 from cache
[debug] [youtube] Decrypted nsig j9F55s4_Dw9rwxxYm => YH2BoLS2hE39sw
[youtube] jGK7dWd8o6Y: Downloading m3u8 information
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] jGK7dWd8o6Y: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] jGK7dWd8o6Y: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] jGK7dWd8o6Y: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] jGK7dWd8o6Y: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
ERROR: [youtube] jGK7dWd8o6Y: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
  File "/home/ubuntu/./yt-dlp/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/./yt-dlp/yt_dlp/extractor/youtube.py", line 4902, in _real_extract
    initial_data = self._extract_response(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/./yt-dlp/yt_dlp/extractor/youtube.py", line 1270, in _extract_response
    next(main_retries)
  File "/home/ubuntu/./yt-dlp/yt_dlp/utils/_utils.py", line 5271, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/home/ubuntu/./yt-dlp/yt_dlp/extractor/common.py", line 3895, in _error_or_warning
    RetryManager.report_retry(
  File "/home/ubuntu/./yt-dlp/yt_dlp/utils/_utils.py", line 5279, in report_retry
    raise e
  File "/home/ubuntu/./yt-dlp/yt_dlp/extractor/youtube.py", line 1243, in _extract_response
    response = self._call_api(
               ^^^^^^^^^^^^^^^
  File "/home/ubuntu/./yt-dlp/yt_dlp/extractor/youtube.py", line 861, in _call_api
    return self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/./yt-dlp/yt_dlp/extractor/common.py", line 1152, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/./yt-dlp/yt_dlp/extractor/common.py", line 1112, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/./yt-dlp/yt_dlp/extractor/common.py", line 962, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/./yt-dlp/yt_dlp/extractor/common.py", line 911, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/ubuntu/./yt-dlp/yt_dlp/extractor/common.py", line 898, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/./yt-dlp/yt_dlp/YoutubeDL.py", line 4162, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/./yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/./yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/./yt-dlp/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/./yt-dlp/yt_dlp/networking/_requests.py", line 365, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request
```

**Comment by observeroftime02** [comment] 2024-11-12 13:37
Seems related to #11462 and #11503

Tl:Dr, stop using oauth, it's broken on youtube's end, perhaps on purpose, perhaps for good. For now, back to cookies (and perhaps add the PO token as well, although I'm not certain how long a PO token remains valid for). That did the trick for me in your situation.

[This](https://github.com/yt-dlp/yt-dlp/wiki/Extractor) documentation proved helpful when setting all of that up.

**Comment by Zackoswald** [comment] 2024-11-12 13:37
你好，邮件我已收到！

**Comment by dubrowin** [comment] 2024-11-12 13:50
> Seems related to #11462 and #11503
> 
> Tl:Dr, stop using oauth, it's broken on youtube's end, perhaps on purpose, perhaps for good. For now, back to cookies (and perhaps add the PO token as well). That did the trick for me in your situation.
> 
> [This](https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide) documentation proved helpful when setting all of that up. Does anybody know how long a PO token remains "valid" for?

OAuth was required because of where my IP packets are coming from.

Looking into the cookie option to see if I can get that work.

**Comment by bashonly** [comment] 2024-11-12 15:52
Duplicate of #11462

Use cookies, not oauth. Oauth is broken for many and going away very soon

**Closed by bashonly** 2024-11-12 15:52 UTC
Labels: site-bug, triage
