### ISSUE TITLE
Using aria2c mangles subtitle downloads from SVTPlay

### ISSUE THREAD

**Issue by kribjo** [yt-dlp/yt-dlp#2691] opened 2022-02-08 15:08 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

The included specific example content URL should be globally accessible, tested by me from Sweden though

### Description

Good example URL (NB: not all content on SVTPlay is globally accessible and with soft subtitles): https://www.svtplay.se/video/12511412/telefonsupporten/telefonsupporten-avsnitt-1?id=jRbBVYj

I initially noticed problems with '--downloader aria2c' and '--embed-subs' on SVTPlay; ffmpeg refused embedding with the error "Invalid data found when processing input". Further examination showed that the subtitle files downloaded by aria2c were "corrupted" (probably actually gzipped, not tested though).

I have then done some narrowing down and it seems the the way yt-dlp uses aria2c's option '--header "Accept-Encoding: gzip, deflate' does not play well with SVTPlay (and possibly other sites). I have tried to replicate the problem on YouTube and Vimeo but it seems they are not affected by this issue, why that is so is beyond what I know at this time.

I have noticed some other issues that might be related to this issue, but I cannot say that they are the same, and in any case it seems this report still adds to the background of a possible common issue:
#1936
#2502

You will see from the logs below that downloading subs from SVTPlay gives different results (note the file size in the last lines) when using --downloader native and --downloader aria2c. The natively downloaded file is a well-formed VTT subtitle file as expected while the aria2c download is not in the expected format.

I have also tried the aria2c command line on its own, as formatted by yt-dlp, and compared to the same command line but with '--header "Accept-Encoding: gzip, deflate' omitted, and while the latter results in a correctly formatted 2205 bytes long file with the same contents as when using yt-dlp with the native downloader, the former (of course) results in a 1119 bytes long file with the same unreadable content as when using yt-dlp with aria2c as downloader. Please see the log section below for the command lines.

I am not sure in which way this could/should be fixed, but here are my thoughts:
The "quick fix" would obviously be to remove the problematic option from the aria2c command line (but maybe only when downloading subtitles?).
But is this just one "badly" programmed site that needs a workaround or does yt-dlp (or even aria2c?) handle the subtitle downloading in a problematic way which should be addressed for all sites?
Should yt-dlp actually try to get the subtitle file in this (gzipped/deflated?) format and then put it in the right format before handing it to ffmpeg?
Or should ffmpeg be able to handle the unusually formed subtitle file, maybe if we tell it that it is not in the standard format it expects?

### Verbose log

```shell
yt-dlp.exe --ignore-config -vU --skip-download --all-subs --downloader aria2c "https://www.svtplay.se/video/12511412/telefonsupporten/telefonsupporten-avsnitt-1?id=jRbBVYj"
[debug] Command-line config: ['--ignore-config', '-vU', '--skip-download', '--all-subs', '--downloader', 'aria2c', 'https://www.svtplay.se/video/12511412/telefonsupporten/telefonsupporten-avsnitt-1?id=jRbBVYj']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] Using fake IP 78.75.110.253 (SE) as X-Forwarded-For
[debug] [SVTPlay] Extracting URL: https://www.svtplay.se/video/12511412/telefonsupporten/telefonsupporten-avsnitt-1?id=jRbBVYj
[SVTPlay] jRbBVYj: Downloading JSON metadata
[SVTPlay] jRbBVYj: Downloading m3u8 information
WARNING: [SVTPlay] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
[SVTPlay] jRbBVYj: Downloading m3u8 information
[SVTPlay] jRbBVYj: Downloading m3u8 information
[SVTPlay] jRbBVYj: Downloading m3u8 information
[SVTPlay] jRbBVYj: Downloading m3u8 information
[SVTPlay] jRbBVYj: Downloading MPD manifest
WARNING: [SVTPlay] Ignoring subtitle tracks found in the DASH manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
[SVTPlay] jRbBVYj: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: sv
[debug] Default format spec: bestvideo*+bestaudio/best
[info] jRbBVYj: Downloading 1 format(s): hls-cmaf-full-3290+dashhbbtv-5
Deleting existing file Försenade [jRbBVYj].sv.vtt
[info] Writing video subtitles to: Försenade [jRbBVYj].sv.vtt
[debug] Invoking downloader on "https://svt-vod-2t.akamaized.net/d0/world/20210823/10559062-3759-4523-9080-ad672d97c2ff/text/text-0.vtt"
[download] Destination: Försenade [jRbBVYj].sv.vtt
[debug] aria2c command line: aria2c -c "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--file-allocation=none" -x16 -j16 -s16 --min-split-size 1M --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4556.0 Safari/537.36" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Encoding: gzip, deflate" --header "Accept-Language: en-us,en;q=0.5" --header "Sec-Fetch-Mode: navigate" "--check-certificate=true" "--remote-time=true" "--show-console-readout=true" --out ".\Försenade [jRbBVYj].sv.vtt.part" "--auto-file-renaming=false" -- "https://svt-vod-2t.akamaized.net/d0/world/20210823/10559062-3759-4523-9080-ad672d97c2ff/text/text-0.vtt"
[aria2c] Downloaded 1119 bytes
[download] 100% of 1.09KiB in 00:00

yt-dlp.exe --ignore-config -vU --skip-download --all-subs --downloader native "https://www.svtplay.se/video/12511412/telefonsupporten/telefonsupporten-avsnitt-1?id=jRbBVYj"
[debug] Command-line config: ['--ignore-config', '-vU', '--skip-download', '--all-subs', '--downloader', 'native', 'https://www.svtplay.se/video/12511412/telefonsupporten/telefonsupporten-avsnitt-1?id=jRbBVYj']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] Using fake IP 78.72.232.22 (SE) as X-Forwarded-For
[debug] [SVTPlay] Extracting URL: https://www.svtplay.se/video/12511412/telefonsupporten/telefonsupporten-avsnitt-1?id=jRbBVYj
[SVTPlay] jRbBVYj: Downloading JSON metadata
[SVTPlay] jRbBVYj: Downloading m3u8 information
WARNING: [SVTPlay] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
[SVTPlay] jRbBVYj: Downloading m3u8 information
[SVTPlay] jRbBVYj: Downloading m3u8 information
[SVTPlay] jRbBVYj: Downloading m3u8 information
[SVTPlay] jRbBVYj: Downloading m3u8 information
[SVTPlay] jRbBVYj: Downloading MPD manifest
WARNING: [SVTPlay] Ignoring subtitle tracks found in the DASH manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
[SVTPlay] jRbBVYj: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: sv
[debug] Default format spec: bestvideo*+bestaudio/best
[info] jRbBVYj: Downloading 1 format(s): hls-cmaf-full-3290+dashhbbtv-5
[info] Writing video subtitles to: Försenade [jRbBVYj].sv.vtt
[debug] Invoking downloader on "https://svt-vod-2t.akamaized.net/d0/world/20210823/10559062-3759-4523-9080-ad672d97c2ff/text/text-0.vtt"
[download] Destination: Försenade [jRbBVYj].sv.vtt
[download] 100% of 2.15KiB in 00:00

"Bad" command line, as formed by yt-dlp, with malformed/unusable result:
aria2c -c "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--file-allocation=none" -x16 -j16 -s16 --min-split-size 1M --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4556.0 Safari/537.36" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Encoding: gzip, deflate" --header "Accept-Language: en-us,en;q=0.5" --header "Sec-Fetch-Mode: navigate" "--check-certificate=true" "--remote-time=true" "--show-console-readout=true" --out ".\Försenade [jRbBVYj].sv.vtt.part" "--auto-file-renaming=false" -- "https://svt-vod-2t.akamaized.net/d0/world/20210823/10559062-3759-4523-9080-ad672d97c2ff/text/text-0.vtt"

Modified command line, with good/expected result:
aria2c -c "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--file-allocation=none" -x16 -j16 -s16 --min-split-size 1M --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4556.0 Safari/537.36" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Language: en-us,en;q=0.5" --header "Sec-Fetch-Mode: navigate" "--check-certificate=true" "--remote-time=true" "--show-console-readout=true" --out ".\Försenade [jRbBVYj].sv.vtt.part" "--auto-file-renaming=false" -- "https://svt-vod-2t.akamaized.net/d0/world/20210823/10559062-3759-4523-9080-ad672d97c2ff/text/text-0.vtt"
```

**Comment by pukkandan** [comment] 2022-02-08 16:20
As a workaround, try `--downloader-args "--http-accept-gzip=true"`

**Comment by kribjo** [comment] 2022-02-08 19:17
Thanks, confirming that adding `--downloader-args "--http-accept-gzip=true"` seems to fix it. No errors and output file is fine, including subtitles. After reading aria2 docs it seems it could hardly cause a problem to always add this?

**Comment by kribjo** [comment] 2022-02-08 19:20
Using `--header "Accept-Encoding: gzip, deflate" ` without `--http-accept-gzip=true` seems weird? Doesn't that make aria2 say that we will accept gzip/deflate content, but then we will not inflate it?

**Comment by pukkandan** [comment] 2022-02-10 16:11
Closing as duplicate of #1936

**Closed by pukkandan** 2022-02-10 16:11 UTC
Labels: site-bug, triage
