### ISSUE TITLE
xvideos falling back on generic extractor

### ISSUE THREAD

**Issue by nicolaasjan** [yt-dlp/yt-dlp#9494] opened 2024-03-19 16:20 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

the Netherlands

### Provide a description that is worded well enough to be understood

Title.
Video downloads fine however.
But why is it falling back on the Generic extractor?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --ignore-config https://www.xvideos.com/video.hifflud37bd/hot_young_blonde_on_the_beach
[debug] Command-line config: ['-vU', '--ignore-config', 'https://www.xvideos.com/video.hifflud37bd/hot_young_blonde_on_the_beach']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.03.18.170739 from yt-dlp/yt-dlp-master-builds [22e4dfacb] (linux_exe)
[debug] Python 3.10.13 (CPython x86_64 64bit) - Linux-5.4.0-173-generic-x86_64-with-glibc2.31 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.31)
[debug] exe versions: ffmpeg N-113699-g0c8e64e268-20240219 (setts), ffprobe N-113699-g0c8e64e268-20240219, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.03.18.170739 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.03.18.170739 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://www.xvideos.com/video.hifflud37bd/hot_young_blonde_on_the_beach
[generic] hot_young_blonde_on_the_beach: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] hot_young_blonde_on_the_beach: Extracting information
[debug] Looking for embeds
[debug] Identified a JSON LD
[generic] Extracting URL: https://gcore-vid.xvideos-cdn.com/lcLDmnEHNuCIRitUT4xckQ==,1710875683/videos/mp4/e/2/c/xvideos.com_e2c633a0a567ee9276e670bcdc0e3db9-2.mp4#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22hot_young_blonde_on_the_beach%22%2C+%22to_generic%22%3A+true%2C+%22referer%22%3A+%22https%3A%2F%2Fwww.xvideos.com%2Fvideo.hifflud37bd%2Fhot_young_blonde_on_the_beach%22%7D
[generic] hot_young_blonde_on_the_beach: Downloading webpage
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] hot_young_blonde_on_the_beach: Downloading 1 format(s): mp4
[debug] Invoking http downloader on "https://gcore-vid.xvideos-cdn.com/lcLDmnEHNuCIRitUT4xckQ==,1710875683/videos/mp4/e/2/c/xvideos.com_e2c633a0a567ee9276e670bcdc0e3db9-2.mp4"
[download] Destination: Hot Young Blonde On The Beach [hot_young_blonde_on_the_beach].mp4
[download] 100% of    9.80MiB in 00:00:00 at 18.75MiB/s
```

**Comment by nicolaasjan** [comment] 2024-03-19 16:22
```
yt-dlp --ignore-config -F https://www.xvideos.com/video.hifflud37bd/hot_young_blonde_on_the_beach
[generic] Extracting URL: https://www.xvideos.com/video.hifflud37bd/hot_young_blonde_on_the_beach
[generic] hot_young_blonde_on_the_beach: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] hot_young_blonde_on_the_beach: Extracting information
[generic] Extracting URL: https://gcore-vid.xvideos-cdn.com/-SsUBPfiJ2DFo6GwQIy_og==,1710875271/videos/mp4/e/2/c/xvideos.co...e_on_the_beach%22%7D
[generic] hot_young_blonde_on_the_beach: Downloading webpage
[info] Available formats for hot_young_blonde_on_the_beach:
ID  EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
────────────────────────────────────────────
mp4 mp4 unknown    │ https │ unknown unknown
```

**Comment by nicolaasjan** [comment] 2024-03-19 16:28
Offtopic side note:
MPV media player gives:

```
mpv https://www.xvideos.com/video.hifflud37bd/hot_young_blonde_on_the_beach
Failed to recognize file format.
Exiting... (Errors when loading file)
```

**Comment by bashonly** [comment] 2024-03-19 16:30
> why is it falling back on the Generic extractor?

url format changed and is no longer matched by the dedicated extractor

Closing as duplicate of #9493

**Closed by bashonly** 2024-03-19 16:30 UTC
Labels: site-bug, triage
