### ISSUE TITLE
Display Video Index Option (video X of Y)

### ISSUE THREAD

**Issue by hl2guide** [yt-dlp/yt-dlp#3299] opened 2022-04-04 07:56 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

# Description
Please consider adding two useful features for the option "--batch-file" that shows: `video (X of Y)`

# Example
`Downloading video 5 of 15`

# Areas
* the window title (`--console-title`)
* the console output text

**Comment by pukkandan** [comment] 2022-04-04 10:01
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3126

**Closed by pukkandan** 2022-04-04 10:01 UTC
Labels: enhancement, triage
