### ISSUE TITLE
[FEATURE REQUEST] don't enable subtitles by default

### ISSUE THREAD

**Issue by RedirectCleaner** [yt-dlp/yt-dlp#6649] opened 2023-03-27 10:15 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

when downloading downloading a video with subtiles with the option --embed-subs, the embedded subtitle gets enabled by default. The default behavior should be to not enable any subtitle by default or at least allow to set the default/no default subtitle.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment] 2023-03-27 10:50
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2799. See workarounds in https://github.com/yt-dlp/yt-dlp/pull/3709

**Closed by pukkandan** 2023-03-27 10:50 UTC
Labels: enhancement, triage
