### ISSUE TITLE
various on title by different languarge setting, can't control during downloaing from playlist

### ISSUE THREAD

**Issue by icesof** [yt-dlp/yt-dlp#3839] opened 2022-05-22 15:42 UTC
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Recently, the video's title will be changed by the language setting in my personal account. 

for example, https://www.youtube.com/watch?v=7jTs5fWviUM

By setting the Language to "English (US)", the video's title will be displayed in English characters. After changing to "simple Chinese", the title will be displayed in Chinese characters. Seems like the behavior coming from the author of the video.

Now, I try to download the video for recently x days with "match-title" in Chinese characters (by pass-in one playlist, https://www.youtube.com/c/ettvCTime/videos). With/ without the passing in my cookie file, the yt-dlp gets the video title in English characters only. Not sure how to enforce the way of language setting on a website.

**Comment by pukkandan** [comment] 2022-05-22 16:29
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/387

**Closed by pukkandan** 2022-05-22 16:29 UTC
Labels: question
