### ISSUE TITLE
Postprocessors are not invoked when using `--skip-download`

### ISSUE THREAD

**Issue by UlyssesZh** [yt-dlp/yt-dlp#8261] opened 2023-10-01 19:33 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When `--write-subs --skip-download` is used, we can download subtitle files without downloading video files. However, if there are some postprocessors that process subtitle files, they will not be run when `--skip-download` is present, so they cannot process the downloaded subtitles. This is mentioned [in the README of srt_fix plugin](https://github.com/bindestriche/srt_fix/tree/984e548494794e4e438bbd43ee0211e99f824064#--skip-downlaod).

Compare when the `--skip-download` is not present:
<details><summary><pre>yt-dlp -vU --paths temp --write-auto-sub --sub-lang en --convert-subs=srt --use-postprocessor srt_fix https://youtu.be/qWNQUvIk954</pre></summary>
<pre>[debug] Command-line config: ['-vU', '--paths', 'temp', '--write-auto-sub', '--sub-lang', 'en', '--convert-subs=srt', '--use-postprocessor', 'srt_fix', 'https://youtu.be/qWNQUvIk954']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-84-generic-x86_64-with-glibc2.31 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-3.31.1, websockets-11.0.3
[debug] Proxy map: {}
[debug] Post-Processor Plugins: srt_fixPP
[debug] Plugin directories: ['/home/ulysses/.pyenv/versions/3.10.6/lib/python3.10/site-packages/yt_dlp_plugins']
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
yt-dlp is up to date (stable@2023.09.24)
[youtube] Extracting URL: https://youtu.be/qWNQUvIk954
[youtube] qWNQUvIk954: Downloading webpage
[youtube] qWNQUvIk954: Downloading ios player API JSON
[youtube] qWNQUvIk954: Downloading android player API JSON
[youtube] qWNQUvIk954: Downloading m3u8 information
[info] qWNQUvIk954: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] qWNQUvIk954: Downloading 1 format(s): 616+251
Deleting existing file temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.vtt
[info] Writing video subtitles to: temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=qWNQUvIk954&ei=xMoZZZnHJu3BsfIPxr2c4AQ&caps=asr&opi=112496729&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1696214324&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cei%2Ccaps%2Copi%2Cxoaf&signature=8E4A71E005D3A16FB721D30FABFAADAA946D2529.36F672857C05C3129E13454CD511A64FA1C694B6&key=yt8&kind=asr&lang=en&fmt=vtt"
[download] Destination: temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.vtt
[download] 100% of    7.56KiB in 00:00:00 at 29.23KiB/s
[SubtitlesConvertor] Converting subtitles
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.vtt' -f srt -movflags +faststart 'file:temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.srt'
Deleting original file temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.vtt (pass -k to keep)
[download] temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].webm has already been downloaded
[srt_fix] Postprocessing en
[MoveFiles] Moving file "temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.srt" to "Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.srt"
[MoveFiles] Moving file "temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en-original.srt" to "Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en-original.srt"
</pre></details>

and when `--skip-download` is present:
<details><summary><pre>yt-dlp -vU --paths temp --skip-download --write-auto-sub --sub-lang en --convert-subs=srt --use-postprocessor srt_fix https://youtu.be/qWNQUvIk954</pre></summary>
<pre>[debug] Command-line config: ['-vU', '--paths', 'temp', '--skip-download', '--write-auto-sub', '--sub-lang', 'en', '--convert-subs=srt', '--use-postprocessor', 'srt_fix', 'https://youtu.be/qWNQUvIk954']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-84-generic-x86_64-with-glibc2.31 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-3.31.1, websockets-11.0.3
[debug] Proxy map: {}
[debug] Post-Processor Plugins: srt_fixPP
[debug] Plugin directories: ['/home/ulysses/.pyenv/versions/3.10.6/lib/python3.10/site-packages/yt_dlp_plugins']
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
yt-dlp is up to date (stable@2023.09.24)
[youtube] Extracting URL: https://youtu.be/qWNQUvIk954
[youtube] qWNQUvIk954: Downloading webpage
[youtube] qWNQUvIk954: Downloading ios player API JSON
[youtube] qWNQUvIk954: Downloading android player API JSON
[youtube] qWNQUvIk954: Downloading m3u8 information
[info] qWNQUvIk954: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] qWNQUvIk954: Downloading 1 format(s): 616+251
[info] Writing video subtitles to: temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=qWNQUvIk954&ei=QssZZc7nGvqcsfIP3aG8-AE&caps=asr&opi=112496729&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1696214450&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cei%2Ccaps%2Copi%2Cxoaf&signature=3932FE4C9D502106CC05DCADDB06C6B4E41D0F89.704EF907B44096AB8EBD8FA0E6825A96153AB3C8&key=yt8&kind=asr&lang=en&fmt=vtt"
[download] Destination: temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.vtt
[download] 100% of    7.56KiB in 00:00:00 at 68.80KiB/s
[SubtitlesConvertor] Converting subtitles
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.vtt' -f srt -movflags +faststart 'file:temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.srt'
Deleting original file temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.vtt (pass -k to keep)</pre>
</details>

As can be seen, the postprocessor is run in the former, but is not in the latter.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--paths', 'temp', '--skip-download', '--write-auto-sub', '--sub-lang', 'en', '--convert-subs=srt', '--use-postprocessor', 'srt_fix', 'https://youtu.be/qWNQUvIk954']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-84-generic-x86_64-with-glibc2.31 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-3.31.1, websockets-11.0.3
[debug] Proxy map: {}
[debug] Post-Processor Plugins: srt_fixPP
[debug] Plugin directories: ['/home/ulysses/.pyenv/versions/3.10.6/lib/python3.10/site-packages/yt_dlp_plugins']
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
yt-dlp is up to date (stable@2023.09.24)
[youtube] Extracting URL: https://youtu.be/qWNQUvIk954
[youtube] qWNQUvIk954: Downloading webpage
[youtube] qWNQUvIk954: Downloading ios player API JSON
[youtube] qWNQUvIk954: Downloading android player API JSON
[youtube] qWNQUvIk954: Downloading m3u8 information
[info] qWNQUvIk954: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] qWNQUvIk954: Downloading 1 format(s): 616+251
[info] Writing video subtitles to: temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=qWNQUvIk954&ei=QssZZc7nGvqcsfIP3aG8-AE&caps=asr&opi=112496729&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1696214450&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cei%2Ccaps%2Copi%2Cxoaf&signature=3932FE4C9D502106CC05DCADDB06C6B4E41D0F89.704EF907B44096AB8EBD8FA0E6825A96153AB3C8&key=yt8&kind=asr&lang=en&fmt=vtt"
[download] Destination: temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.vtt
[download] 100% of    7.56KiB in 00:00:00 at 68.80KiB/s
[SubtitlesConvertor] Converting subtitles
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.vtt' -f srt -movflags +faststart 'file:temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.srt'
Deleting original file temp/Rick Astley - Never Gonna Stop (Official Video) [qWNQUvIk954].en.vtt (pass -k to keep)
```

**Comment by bashonly** [comment] 2023-10-02 20:16
Duplicate of #6986, see my reply in that issue

**Closed by bashonly** 2023-10-02 20:16 UTC
Labels: bug, triage
