### ISSUE TITLE
How to avoid re-embedding subs for existing videos

### ISSUE THREAD

**Issue by dabreadman** [yt-dlp/yt-dlp#3207] opened 2022-03-26 13:42 UTC
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I was trying to download a playlist with subtitles, but because the playlist was long, and my connection was slow, I had to do this over a few days. What I noticed is that `yt-dlp` will re-embed the subtitles for existing videos (even though they have been embedded), and this takes ages.

```
What happens now
Day 1: Downloaded 1-10
Day 2: (re) embed 1-10, download 11-15
Day 3: (re) embed 1-15, download 16-18
...
```

Is there a way to NOT embed videos with subtitles, or simply ignore checking existing videos?

```bash
yt-dlp -o "Trash Taste/%(uploader)s: %(title)s.%(ext)s" --windows-filenames --embed-subs --sub-langs "en.*,zh.*,ja",-live_chat --ffmpeg-location "D:\Software\Passive\ffmpeg-master-latest-win64-gpl\bin" "https://www.youtube.com/c/TrashTaste"
````
The `ffmpeg-location` points to the patched build.

**Comment by pukkandan** [comment] 2022-03-26 20:06
Duplicate of #3206, #1467

**Closed by pukkandan** 2022-03-26 20:06 UTC
Labels: question

**Comment by dabreadman** [comment] 2022-03-26 20:52
> Duplicate of #3206, #1467

Thanks, was searching with "embed subs" and "reembed". Can I use the same file for `--write-archive` between multiple playlists?

**Comment by pukkandan** [comment] 2022-03-26 20:55
If the same video exists in 2 playlists, do you want to download it twice? If not, you can use the same archive

**Comment by dabreadman** [comment] 2022-03-26 20:56
I meant instead of `archive-playlist1.txt`, `archive-playlist2.txt`... can I instead write all of them to `archive-playlists.txt`?

**Comment by pukkandan** [comment] 2022-03-26 20:59
Yes, that is what I replied to...

If you write all playlist's archive to same file, each video will only be downloaded once, irrespective how many times is appears in the various playlists. If that is okay, you can use the same file

**Comment by dabreadman** [comment] 2022-03-26 21:00
Oh cool, and is there a way to archive downloaded files, or would `--write-archive` do that automatically, without reembedding subtitles?

**Comment by pukkandan** [comment] 2022-03-26 21:02
You can do one pass without `--embed-subtitles`

**Comment by pukkandan** [comment] 2022-03-26 21:03
You can also do `--force-write-archive -s`, but this will add all videos currently in the playlists to archive **irrespective of whether it was actually downloaded before**

**Comment by dabreadman** [comment] 2022-03-26 21:12
Right, thanks!

**Comment by dabreadman** [comment] 2022-03-26 21:13
I can't quite do that since I still only downloaded half of the videos on my playlist :<

**Comment by pukkandan** [comment] 2022-03-26 21:14
hm.. Do you know how many videos have been downloaded? Are you downloading them in order?

**Comment by pukkandan** [comment] 2022-03-26 21:16
If yes to both, you can do something like
```
yt-dlp --download-archive archive-playlists.txt -s --force-write-archive --playlist-end 100 "URL"
```

**Comment by dabreadman** [comment] 2022-03-26 21:17
Since i download the whole list, i can simply count the number of videos there are in the folder, and hopefully, they stay in order :?

**Comment by pukkandan** [comment] 2022-03-26 21:19
> and hopefully, they stay in order :?

As long as u didn't use --playlist-reverse or similar

> If I downloaded 43 out of 93 videos, would it be 43 instead of 100?

yes

**Comment by dabreadman** [comment] 2022-03-26 21:21
Thanks!

**Comment by dabreadman** [comment] 2022-03-26 21:22
Do you know if they only write to archive after completion, or on start?
i.e. if I cancel a download, or cancel mid embedding subtitles, would it be in the archive?

**Comment by pukkandan** [comment] 2022-03-26 21:24
When you are **not** using `--force-write-archive`, the video is only added to archive after download and all postprocessing is done. So if you stop it midway, download fails etc, it won't be added

**Comment by dabreadman** [comment] 2022-03-26 21:26
Since it archives the video's id, I don't have to be worried since they download playlists in order of the most recent to the oldest, right?

**Comment by pukkandan** [comment] 2022-03-26 21:27
worried about what?

**Comment by pukkandan** [comment] 2022-03-26 21:28
> since they download playlists in order of the most recent to the oldest, right?

playlists are downloaded in the order they are shown in the website. This may not be always recent to oldest

**Comment by dabreadman** [comment] 2022-03-26 21:29
> worried about what?

Was originally worried about how if you download the most recent video (A) and archive it, and new video (B) pop out, it'd not download B and instead redownload A.

That was a dumb dumb on my part

**Comment by dabreadman** [comment] 2022-03-26 21:30
> > since they download playlists in order of the most recent to the oldest, right?
> 
> playlists are downloaded in the order they are shown in the website. This may not be always recent to oldest

Didn't know, interesting. I was downloading a series where they had video listed `video #1`, `video #2`, and it seems to go in a descending order, thus the assumption

**Comment by dabreadman** [comment] 2022-03-26 21:33
> > since they download playlists in order of the most recent to the oldest, right?
> 
> playlists are downloaded in the order they are shown in the website. This may not be always recent to oldest

Huh, would this change? If it would then maybe

```
yt-dlp --download-archive archive-playlists.txt -s --force-write-archive --playlist-end 100 "URL"
```

wouldn't quite work, since they get displayed in different order?

**Comment by pukkandan** [comment] 2022-03-26 21:36
bruh, you downloaded the **first** 43 videos, right? This command tells yt-dlp to forcibly write the first 43 ids to archive. It will work whatever order they are in

**Comment by dabreadman** [comment] 2022-03-26 21:40
> bruh, you downloaded the **first** 43 videos, right? This command tells yt-dlp to forcibly write the first 43 ids to archive. It will work whatever order they are in

You mentioned `playlists are downloaded in the order they are shown in the website`, which is why I'm curious if they'd change the way they display the videos (by date/views etc), but I know realise it's the order in the playlist. 

If it's videos of a channel, it'd be all the videos from most recent to oldest (but would they change it to say, views for example)?

**Comment by pukkandan** [comment] 2022-03-26 21:46
The default order for youtube channels hasn't changed in years. But could they change it? yes. You'll need to go ask youtube if they will ...

But how is this relevant to this question? The order probably hasn't changed b/w when u downloaded and now. That's all that matters. Who cares if it changes later on!?

I suggest you first try out the command before asking further questions

**Comment by dabreadman** [comment] 2022-03-26 22:27
> The default order for youtube channels hasn't changed in years. But could they change it? yes. You'll need to go ask youtube if they will ...

This is all I need to know XD
Thanks, it worked.
