### ISSUE TITLE
Now whether to list and download videos on Youtube requires you to log in?

### ISSUE THREAD

**Issue by DOSforever** [yt-dlp/yt-dlp#11024] opened 2024-09-17 10:58 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

现在是否列出和下载 youtube 上的视频都要求你登录，比如必须使用 `--cookies-from-browser` 选项，不登录的话会提示：

> ERROR: [youtube] xxxxxxxxxxx: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

是不是所有人都遇到这现象？

----

Now whether to list and download videos on Youtube requires you to log in, for example, you must use the `--cookies-from-browser` option, if you don't log in, you will be prompted:

> ERROR: [youtube] xxxxxxxxxxx: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

Is this happening to everyone?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --version
2024.08.06
```

**Comment by seproDev** [comment] 2024-09-17 10:59
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/10128

Youtube has blocked access from your IP address

**Closed** 2024-09-17 18:21 UTC
Labels: duplicate, site-bug
