### ISSUE TITLE
[BiliIntl] Question about the number of download selections for bilibili.tv

### ISSUE THREAD

**Issue by ltsj** [yt-dlp/yt-dlp#4907] opened 2022-09-13 14:15 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Southeast Asia(Singapore and ...)

### Example URLs

https://www.bilibili.tv/en/play/1060698

### Provide a description that is worded well enough to be understood

`yt-dlp -o "%(episode_id)s"  https://www.bilibili.tv/en/play/1060698 -I 3 --all-subs  --sub-format srt --remux-video mkv --embed-subs -u PRIVATE -p PRIVATE`
The above is the command I use. I specify to download the third episode, but it will read every episode before the third episode. This process is very slow. If it is an episode with a large number of episodes, will it be possible? Long wait... Is it possible to just download the specified number of episodes instead of waiting to read each episode?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-o', '%(episode_number)s', 'https://www.bilibili.tv/en/play/1060698', '-I', '3', '--all-subs', '--sub-format', 'srt', '--remux-video', 'mkv', '--embed-subs', '-u', 'PRIVATE', '-p', 'PRIVATE']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (linux_exe)
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.10.0-11-amd64-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-61656-gfbd22504c4-static (setts), phantomjs 140207397599168
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[BiliIntlSeries] Downloading login key
[BiliIntlSeries] Logging in
[debug] [BiliIntlSeries] Extracting URL: https://www.bilibili.tv/en/play/1060698
[BiliIntlSeries] 1060698: Downloading JSON metadata
[download] Downloading playlist: Sekai no Owari ni Shiba Inu to
[BiliIntlSeries] 1060698: Downloading JSON metadata
[BiliIntlSeries] 11491441: Downloading video formats
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliIntlSeries] 11491441: Downloading subtitles list
[BiliIntlSeries] 11491441: Downloading subtitles for English
[BiliIntlSeries] 11491441: Downloading subtitles for ภาษาไทย
[BiliIntlSeries] 11491441: Downloading subtitles for Tiếng Việt
[BiliIntlSeries] 11491441: Downloading subtitles for Bahasa Indonesia
[BiliIntlSeries] 11491441: Downloading subtitles for Bahasa Melayu
[BiliIntlSeries] 11491441: Downloading subtitles for 中文（简体）
[BiliIntlSeries] 11491576: Downloading video formats
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliIntlSeries] 11491576: Downloading subtitles list
[BiliIntlSeries] 11491576: Downloading subtitles for English
[BiliIntlSeries] 11491576: Downloading subtitles for ภาษาไทย
[BiliIntlSeries] 11491576: Downloading subtitles for Tiếng Việt
[BiliIntlSeries] 11491576: Downloading subtitles for Bahasa Indonesia
[BiliIntlSeries] 11491576: Downloading subtitles for Bahasa Melayu
[BiliIntlSeries] 11491576: Downloading subtitles for 中文（简体）
[BiliIntlSeries] 11491682: Downloading video formats
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliIntlSeries] 11491682: Downloading subtitles list
[BiliIntlSeries] 11491682: Downloading subtitles for English
[BiliIntlSeries] 11491682: Downloading subtitles for ภาษาไทย
[BiliIntlSeries] 11491682: Downloading subtitles for Tiếng Việt
[BiliIntlSeries] 11491682: Downloading subtitles for Bahasa Indonesia
[BiliIntlSeries] 11491682: Downloading subtitles for Bahasa Melayu
[BiliIntlSeries] 11491682: Downloading subtitles for 中文（简体）
[BiliIntlSeries] Playlist Sekai no Owari ni Shiba Inu to: Downloading 1 videos
[download] Downloading video 1 of 1
[info] 11491682: Downloading subtitles: en, th, vi, id, ms, zh-Hans
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 11491682: Downloading 1 format(s): 8+2
[info] Writing video subtitles to: 3.en.srt
[info] Writing video subtitles to: 3.th.srt
[info] Writing video subtitles to: 3.vi.srt
[info] Writing video subtitles to: 3.id.srt
[info] Writing video subtitles to: 3.ms.srt
[info] Writing video subtitles to: 3.zh-Hans.srt
[debug] Invoking http downloader on "https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/oi/na/n220630er38o5clav06gu82oguzvnaoi-1-251210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1663084931&gen=playurlv2&os=akam&oi=2892592144&trid=dfab42e1a4084b20814deb9983d52c57i&mid=1201850291&platform=pc&upsig=d24552f1d30911f3438fb37163021543&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1663084931~hmac=51c93eb0d2bda36d1f3c01e9e34439e949213bc9d2b3820324cb43e953a8b898&bvc=vod&nettype=0&orderid=0,1&logo=00000000"
[download] Got error: <urlopen error EOF occurred in violation of protocol (_ssl.c:997)>. Retrying (1/10)...
[download] Destination: 3.f8.mp4
[download] 100% of 9.04MiB in 00:01 at 6.87MiB/s
[debug] Invoking http downloader on "https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/oi/na/n220630er38o5clav06gu82oguzvnaoi-1-2d1301000023.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1663084931&gen=playurlv2&os=akam&oi=2892592144&trid=dfab42e1a4084b20814deb9983d52c57i&mid=1201850291&platform=pc&upsig=fabf35f5f5cb1c4c628bc4f2509da0d9&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1663084931~hmac=c1366ea67eb29e336f904dc978ecd441af8164523ff87780b69bc9ee7cf332be&bvc=vod&nettype=0&orderid=0,1&logo=00000000"
[download] Destination: 3.f2.mp4
[download] 100% of 4.74MiB in 00:00 at 17.32MiB/s
[Merger] Merging formats into "3.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:3.f8.mp4 -i file:3.f2.mp4 -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart file:3.temp.mp4
Deleting original file 3.f8.mp4 (pass -k to keep)
Deleting original file 3.f2.mp4 (pass -k to keep)
[VideoRemuxer] Remuxing video from mp4 to mkv; Destination: 3.mkv
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:3.mp4 -map 0 -dn -ignore_unknown -c copy -movflags +faststart file:3.mkv
Deleting original file 3.mp4 (pass -k to keep)
[EmbedSubtitle] Embedding subtitles in "3.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:3.mkv -i file:3.en.srt -i file:3.th.srt -i file:3.vi.srt -i file:3.id.srt -i file:3.ms.srt -i file:3.zh-Hans.srt -map 0 -dn -ignore_unknown -c copy -map -0:s -map 1:0 -metadata:s:s:0 language=eng -map 2:0 -metadata:s:s:1 language=tha -map 3:0 -metadata:s:s:2 language=vie -map 4:0 -metadata:s:s:3 language=ind -map 5:0 -metadata:s:s:4 language=msa -map 6:0 -metadata:s:s:5 language=zho -movflags +faststart file:3.temp.mkv
Deleting original file 3.en.srt (pass -k to keep)
Deleting original file 3.zh-Hans.srt (pass -k to keep)
Deleting original file 3.id.srt (pass -k to keep)
Deleting original file 3.th.srt (pass -k to keep)
Deleting original file 3.vi.srt (pass -k to keep)
Deleting original file 3.ms.srt (pass -k to keep)
[download] Finished downloading playlist: Sekai no Owari ni Shiba Inu to
```

**Comment by ltsj** [comment] 2022-10-30 08:04
Is this a bilibili.tv website feature or...? It's not like this when I download YouTube😳

**Comment by HobbyistDev** [comment] 2022-11-15 03:43
I think the problem is in these lines:
https://github.com/yt-dlp/yt-dlp/blob/a4894d3e25943c4ecf4f38c0d50ce592d2175f29/yt_dlp/extractor/bilibili.py#L1023-L1027

The entries is keep adding all episode from series. The response that returned from series json is like this:
<details><summary>JSON sample</summary>

```json
{
  "code": 0,
  "message": "0",
  "ttl": 1,
  "data": {
    "sections": [
      {
        "title": "",
        "ep_list_title": "1-20",
        "episodes": [
          {
            "cover": "https://pic.bstarstatic.com/ogv/8254ebd31d57e9eced389b0df06750955ab27ff2.png",
            "limit": 0,
            "limit_text": "",
            "episode_id": "11491441",
            "short_title_display": "E1",
            "long_title_display": "",
            "title_display": "E1",
            "publish_time": "2022-08-02T18:00:00+08:00"
          },
          {
            "cover": "https://pic.bstarstatic.com/ogv/fc7fe53a0df29729f134072578a9775ba9a93047.png",
            "limit": 0,
            "limit_text": "",
            "episode_id": "11491576",
            "short_title_display": "E2",
            "long_title_display": "",
            "title_display": "E2",
            "publish_time": "2022-08-04T18:00:00+08:00"
          }
        ]
      },
      {
        "title": "",
        "ep_list_title": "21-40",
        "episodes": [
          {
            "cover": "https://pic.bstarstatic.com/ogv/f4f26d4768c41c8dde3321194cc37a52f1f85312.png",
            "limit": 0,
            "limit_text": "",
            "episode_id": "11493454",
            "short_title_display": "E21",
            "long_title_display": "",
            "title_display": "E21",
            "publish_time": "2022-09-06T18:00:00+08:00"
          },
          {
            "cover": "https://pic.bstarstatic.com/ogv/a17320235ce48b1229be5fe8fa9a684fd477561e.png",
            "limit": 0,
            "limit_text": "",
            "episode_id": "11493519",
            "short_title_display": "E22",
            "long_title_display": "",
            "title_display": "E22",
            "publish_time": "2022-09-08T18:00:00+08:00"
          },
          {
            "cover": "https://pic.bstarstatic.com/ogv/3411acd310767b29f79d3c389330bc819865d201.png",
            "limit": 0,
            "limit_text": "",
            "episode_id": "11493646",
            "short_title_display": "E23",
            "long_title_display": "",
            "title_display": "E23",
            "publish_time": "2022-09-10T18:00:00+08:00"
          }
        ]
      }
    ]
  }
}
```
</details>

Maybe we can filter episode_number based on `short_title_display` or `title_display`, but i don't know this is reliable or not.

**Comment by pukkandan** [comment] 2022-11-15 05:43
This is a bit of a complicated problem, and there are actually quite a few separate (but related) issues here.

1. `yt-dlp "video url"` spends so much time extracting subtitles, which may never be used

Fixing this is easy
```diff
diff --git a/yt_dlp/extractor/bilibili.py b/yt_dlp/extractor/bilibili.py
index de28aa4b7..0bcc2ba10 100644
--- a/yt_dlp/extractor/bilibili.py
+++ b/yt_dlp/extractor/bilibili.py
@@ -890,7 +890,7 @@ def _extract_video_info(self, video_data, *, ep_id=None, aid=None):
             'episode_number': int_or_none(self._search_regex(
                 r'^E(\d+)(?:$| - )', video_data.get('title_display') or '', 'episode number', default=None)),
             'formats': self._get_formats(ep_id=ep_id, aid=aid),
-            'subtitles': self._get_subtitles(ep_id=ep_id, aid=aid),
+            'subtitles': self.extract_subtitles(ep_id=ep_id, aid=aid),
             'extractor_key': BiliIntlIE.ie_key(),
         }
```

2. Full information of all previous videos are extracted even when `--playlist-items` is used (what OP reported)

This happens because the extractor (2) does not return `url_result`s, but instead full infodicts and because it (2) returns a generator (which can't be indexed). Changing either of these will fix this problem.

The issue with naively returning a `url_result` is that `video_data` will have to be extracted again by making an additional webpage request, which makes extraction inefficient for people who don't use `-I`. So the simple solution would be to return a `PagedList` (with page_size=1) instead of the generator. This is what I was planning to do, but then I noticed the next issue

3. Similar to `-I`, `--flat-playlist` is inefficient here

While similar to (2), this cannot be solved using a `PagedList`. The only way to fix this is to return a `url_result`. The standard way of dealing which such situation is to `smuggle_url` the necessary data from the playist IE to the video IE. But the whole `video_data` is too big to justifiably smuggle. We would have to instead pre-process the necessary information from the `video_data` and smuggle just that.

Something like this:
```py
class BiliIntlBaseIE(...):
    def _extract_video_metadata(self, video_data, video_id):
        return {
            'id': video_id,
            'title': ...,
            'thumbnail': ...,
            'episode_number': ...,
        }

   # Is this function even needed anymore?
    def _extract_video_info(...):
            **_extract_video_metadata(video_data, ep_id or aid)
            'formats': ...,
            'subtitles': ...,
        }

class BiliIntlIE(...):
    def _make_url(ep_id, aid):
        ...

    def _real_extract(...):
        url, video_data = unsmuggle_url(url)
        if not video_data:
            webpage = ...
            ...

class BiliIntlSeriesIE(...):
    def _entries(...):
      ...
      yield self.url_result(smuggle_url(
          BiliIntlIE._make_url(...), self._extract_video_metadata(...)), ...)
```

**Comment by pukkandan** [comment] 2023-01-01 09:13
Closed by https://github.com/yt-dlp/yt-dlp/commit/26fdfc3704a278acada27cc420d67c6d3f71423b

**Closed by pukkandan** 2023-01-01 09:13 UTC
Labels: site-enhancement
