### ISSUE TITLE
[Broken] Niconico

### ISSUE THREAD

**Issue by Magizero** [yt-dlp/yt-dlp#171] opened 2021-03-15 13:47 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.03.15**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['--list-formats', '--verbose', 'https://www.nicovideo.jp/watch/sm31589985']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.03.15
[debug] Python version 3.8.7 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg n4.3.1-29-g89daac5fe2, ffprobe n4.3.1-29-g89daac5fe2
[debug] Proxy map: {}
[niconico] sm31589985: Downloading webpage
[niconico] sm31589985: Downloading video info page
ERROR: The video can't downloaded.
Traceback (most recent call last):
  File "c:\users\cleo\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\niconico.py", line 398, in _real_extract
    dmc_info = api_data['video']['dmcInfo']
KeyError: 'dmcInfo'
Traceback (most recent call last):
  File "c:\users\cleo\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\niconico.py", line 398, in _real_extract
    dmc_info = api_data['video']['dmcInfo']
KeyError: 'dmcInfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\cleo\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 1024, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\cleo\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 1045, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\cleo\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\common.py", line 554, in extract
    ie_result = self._real_extract(url)
  File "c:\users\cleo\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\niconico.py", line 400, in _real_extract
    raise ExtractorError('The video can\'t downloaded.',
yt_dlp.utils.ExtractorError: The video can't downloaded.

```

## Description

This just happened recently. I tried doing the clear cache method but it still doesn't work. I also did use login credentials but same error happens (even on other youtube-dl forks)

**Comment by pukkandan** [comment] 2021-03-16 05:00
Related: https://github.com/animelover1984/youtube-dl/issues/29

**Comment by Magizero** [comment] 2021-03-16 05:56
Btw I forgot to mention that it also now asks for login credentials. Just last week I didn't need any login credentials to download and check formats.

**Comment by animelover1984** [comment] 2021-03-17 02:16
> Btw I forgot to mention that it also now asks for login credentials. Just last week I didn't need any login credentials to download and check formats.

Can you give an example? Seems to be working for me on my branch, without providing credentials.

**Comment by nao20010128nao** [comment] 2021-03-17 07:47
As my opinion, we should remove support for FLV formats, since Niconico will no longer provide Flash version.

This is why user experience error message to provide credential.

**Comment by Magizero** [comment] 2021-03-17 08:10
> Can you give an example? Seems to be working for me on my branch, without providing credentials.

I just realized that error prompt was from yt-dlc oops! I'm still unable to download. I still kept getting the error.

`[niconico] sm31589985: Downloading webpage
[niconico] sm31589985: Downloading video info page
ERROR: The video can't downloaded.`

**Comment by pukkandan** [comment] 2021-03-17 10:07
I've pushed a partial fix based on https://github.com/animelover1984/youtube-dl/commit/b5eff52dd9ed5565672ea1694b38c9296db3fade

* SMILE formats still dont work and many of the improvements from #49 is therefore broken
* I haven't tested if all metadata is extracted correctly.
* Code also needs refactoring.
Maybe @tsukumijima or @kurumigi may be interested in fixing it?

**Comment by tsukumijima** [comment] 2021-03-17 12:06
https://blog.nicovideo.jp/niconews/149209.html (Japanese)
As you can see in this article, on March 15th, the "ruins" function of niconico's deleted video was terminated. This is part of the steps to update the comment server in the future.
This organized the structure of JSON data in the watch page. The data itself does not appear to have changed, but the location of the keys where the data resides seems to have changed significantly.
I would like to cooperate, but unfortunately I don't have time to tackle this issue right now.

**Comment by rivke41levp656** [comment] 2021-03-17 20:09
The fix does not seem to work for videos which require credentials:

```
[debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', '--ignore-config', 'https://www.nicovideo.jp/watch/so37994933']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.03.15 
[debug] Python version 3.7.3 (CPython 64bit) - Linux-4.19.0-14-amd64-x86_64-with-debian-10.8
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[niconico] Logging in
[niconico] so37994933: Downloading webpage
[niconico] so37994933: Downloading video info page
WARNING: [niconico] Unable to obtain smile video information
[debug] Sort order given by user: 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: Unable to extract video title; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1024, in wrapper
    return func(self, *args, **kwargs)
  File "/home/username/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1045, in __extract_info
    ie_result = ie.extract(url)
  File "/home/username/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 554, in extract
    ie_result = self._real_extract(url)
  File "/home/username/.local/lib/python3.7/site-packages/yt_dlp/extractor/niconico.py", line 501, in _real_extract
    webpage, 'video title')
  File "/home/username/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 1050, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/username/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 1041, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract video title; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

Using the same command with a normal video works.

**Comment by animelover1984** [comment] 2021-03-18 06:26
> I've pushed a partial fix based on [animelover1984/youtube-dl@b5eff52](https://github.com/animelover1984/youtube-dl/commit/b5eff52dd9ed5565672ea1694b38c9296db3fade)
> 
> * SMILE formats still dont work and many of the improvements from #49 is therefore broken
> * I haven't tested if all metadata is extracted correctly.
> * Code also needs refactoring.
>   Maybe @tsukumijima or @kurumigi may be interested in fixing it?

I'll also be taking a better look at my extractor issues when I have a chance. I made some quick fixes in the interest of restoring basic functionality, but I don't think it's ideal.

**Comment by pukkandan** [comment] 2021-03-19 09:39
related: https://github.com/ytdl-org/youtube-dl/issues/28484

**Comment by CXwudi** [comment] 2021-03-21 03:54
> The fix does not seem to work for videos which require credentials:
> 
> ```
> [debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', '--ignore-config', 'https://www.nicovideo.jp/watch/so37994933']
> [debug] Loading archive file None
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
> [debug] yt-dlp version 2021.03.15 
> [debug] Python version 3.7.3 (CPython 64bit) - Linux-4.19.0-14-amd64-x86_64-with-debian-10.8
> [debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, phantomjs 2.1.1, rtmpdump 2.4
> [debug] Proxy map: {}
> [niconico] Logging in
> [niconico] so37994933: Downloading webpage
> [niconico] so37994933: Downloading video info page
> WARNING: [niconico] Unable to obtain smile video information
> [debug] Sort order given by user: 
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> ERROR: Unable to extract video title; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
> Traceback (most recent call last):
>   File "/home/username/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1024, in wrapper
>     return func(self, *args, **kwargs)
>   File "/home/username/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1045, in __extract_info
>     ie_result = ie.extract(url)
>   File "/home/username/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 554, in extract
>     ie_result = self._real_extract(url)
>   File "/home/username/.local/lib/python3.7/site-packages/yt_dlp/extractor/niconico.py", line 501, in _real_extract
>     webpage, 'video title')
>   File "/home/username/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 1050, in _html_search_regex
>     res = self._search_regex(pattern, string, name, default, fatal, flags, group)
>   File "/home/username/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 1041, in _search_regex
>     raise RegexNotFoundError('Unable to extract %s' % _name)
> yt_dlp.utils.RegexNotFoundError: Unable to extract video title; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
> ```
> 
> Using the same command with a normal video works.
> 
> EDIT: using https://github.com/animelover1984/youtube-dl works, but yt-dlp does not for paid videos.

Honestly, the issue is: login will break
```
[debug] Command-line config: ['-v', 'https://www.nicovideo.jp/watch/sm38140033', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Loading archive file None
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] yt-dlp version 2021.03.15 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 5c5fae6d2
[debug] Python version 3.8.2 (CPython 32bit) - Windows-10-10.0.18362-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[niconico] Logging in
[niconico] sm38140033: Downloading webpage
[niconico] sm38140033: Downloading video info page
WARNING: [niconico] Unable to obtain smile video information
[debug] Sort order given by user:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: Unable to extract video title; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "D:\11134\Videos\Vocaloid Coding POC\yt-dlp\yt_dlp\YoutubeDL.py", line 1025, in wrapper
    return func(self, *args, **kwargs)
  File "D:\11134\Videos\Vocaloid Coding POC\yt-dlp\yt_dlp\YoutubeDL.py", line 1046, in __extract_info
    ie_result = ie.extract(url)
  File "D:\11134\Videos\Vocaloid Coding POC\yt-dlp\yt_dlp\extractor\common.py", line 554, in extract
    ie_result = self._real_extract(url)
  File "D:\11134\Videos\Vocaloid Coding POC\yt-dlp\yt_dlp\extractor\niconico.py", line 499, in _real_extract
    title = self._html_search_regex(
  File "D:\11134\Videos\Vocaloid Coding POC\yt-dlp\yt_dlp\extractor\common.py", line 1050, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "D:\11134\Videos\Vocaloid Coding POC\yt-dlp\yt_dlp\extractor\common.py", line 1041, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract video title; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```
If I tried without login on the same link. 
```
PS D:\11134\Videos\Vocaloid Coding POC\yt-dlp>  python .\yt_dlp\__main__.py -v https://www.nicovideo.jp/watch/sm38140033
[debug] Command-line config: ['-v', 'https://www.nicovideo.jp/watch/sm38140033']
[debug] Loading archive file None
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] yt-dlp version 2021.03.15 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 5c5fae6d2
[debug] Python version 3.8.2 (CPython 32bit) - Windows-10-10.0.18362-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[niconico] sm38140033: Downloading webpage
[niconico] sm38140033: Downloading video info page
WARNING: [niconico] Unable to obtain smile video information
[debug] Sort order given by user:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] Downloading format(s) h264_360p-aac_64kbps
[debug] Invoking downloader on 'niconico_dmc:sm38140033/archive_h264_360p/archive_aac_64kbps'
[niconico_dmc] Downloading from DMC
[niconico] sm38140033: Downloading webpage
[niconico] sm38140033: Downloading JSON metadata
[niconico] sm38140033: Downloading JSON metadata for h264_360p-aac_64kbps
[niconico_dmc] Heartbeat with 60.0 second interval ...
[download] Destination: BeatSea「それはシャンデリーナ ‐ feat.鏡音リン」 [sm38140033].mp4
[download]  32.1% of 12.47MiB at 336.12KiB/s ETA 00:25
```

**Comment by pukkandan** [comment] 2021-03-21 06:22
@rivke41levp656 @CXwudi Try using `--cookies`, not `--username --password`

**Comment by rivke41levp656** [comment] 2021-03-21 07:29
@pukkandan same result for me, yt-dlp fails, other fork succeeds.

**Comment by pukkandan** [comment] 2021-03-21 10:13
> @pukkandan same result for me, yt-dlp fails, other fork succeeds.

With cookies? I don't have a niconico account to test/fix this unless someone is willing to DM me their account details

**Comment by CXwudi** [comment] 2021-03-21 15:16
@rivke41levp656 confirmed same result 
```
python .\yt_dlp\__main__.py -v https://www.nicovideo.jp/watch/sm38140033 --cookie '.\nico cookies.txt'
[debug] Command-line config: ['-v', 'https://www.nicovideo.jp/watch/sm38140033', '--cookie', '.\\nico cookies.txt']
...
yt_dlp.utils.RegexNotFoundError: Unable to extract video title; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by xtkoba** [comment] 2021-03-21 23:05
It seems that the title information of the form `<meta property="og:title" content="...">` is not available when (and only when) logged in. Maybe we have to get it separately without logging in.

If you do not need the title info, you can use the following patch as a workaround (which sets the title field to `NA`):
```
--- a/yt_dlp/extractor/niconico.py
+++ b/yt_dlp/extractor/niconico.py
@@ -496,9 +496,7 @@
         if not title:
             title = self._og_search_title(webpage, default=None)
         if not title:
-            title = self._html_search_regex(
-                r'<span[^>]+class="videoHeaderTitle"[^>]*>([^<]+)</span>',
-                webpage, 'video title')
+            title = "NA"
 
         watch_api_data_string = self._html_search_regex(
             r'<div[^>]+id="watchAPIDataContainer"[^>]+>([^<]+)</div>',
```

**Comment by CXwudi** [comment] 2021-03-22 00:38
@xtkoba very thanks for this hint, I tried `title = get_video_info_web("title")` and it works now 
```
title = get_video_info_web('originalTitle')
if not title:
    title = self._og_search_title(webpage, default=None)
if not title:
    title = self._html_search_regex(
        r'<span[^>]+class="videoHeaderTitle"[^>]*>([^<]+)</span>',
        webpage, 'video title')
if not title:
    title = get_video_info_web('title')
```

**Comment by pukkandan** [comment] 2021-03-23 08:53
@CXwudi @xtkoba Was busy yesterday. I've pusher your patch

**Comment by betsu0** [comment] 2021-03-26 01:29
not work HLS+AES128

[debug] Command-line config: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.nicovideo.jp/watch/so38016254']
[debug] Loading archive file None
[debug] Encodings: locale cp932, fs utf-8, out utf-8, pref cp932
[debug] yt-dlp version 2021.03.24.1 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.8.8 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[niconico] Logging in
[niconico] so38016254: Downloading webpage
[niconico] so38016254: Downloading video info page
WARNING: [niconico] Unable to obtain smile video information
[debug] Sort order given by user:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Downloading format(s) h264_720p-aac_192kbps
[debug] Invoking downloader on 'niconico_dmc:so38016254/archive_h264_720p/archive_aac_192kbps'
[niconico_dmc] Downloading from DMC
[niconico] so38016254: Downloading webpage
[niconico] so38016254: Downloading JSON metadata
[niconico] so38016254: Downloading JSON metadata for h264_720p-aac_192kbps
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "C:\Users\betsu\Desktop\yt-dlp-master\yt_dlp\extractor\common.py", line 666, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\betsu\Desktop\yt-dlp-master\yt_dlp\YoutubeDL.py", line 2822, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by betsu0** [comment] 2021-03-26 01:31
not work HLS+AES128

```
[debug] Command-line config: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.nicovideo.jp/watch/so38016254']
[debug] Loading archive file None
[debug] Encodings: locale cp932, fs utf-8, out utf-8, pref cp932
[debug] yt-dlp version 2021.03.24.1 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.8.8 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 3.2.4, ffprobe 3.2.4
[debug] Proxy map: {}
[niconico] Logging in
[niconico] so38016254: Downloading webpage
[niconico] so38016254: Downloading video info page
WARNING: [niconico] Unable to obtain smile video information
[debug] Sort order given by user:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Downloading format(s) h264_720p-aac_192kbps
[debug] Invoking downloader on 'niconico_dmc:so38016254/archive_h264_720p/archive_aac_192kbps'
[niconico_dmc] Downloading from DMC
[niconico] so38016254: Downloading webpage
[niconico] so38016254: Downloading JSON metadata
[niconico] so38016254: Downloading JSON metadata for h264_720p-aac_192kbps
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see https://github.com/yt-dlp/yt-dlp on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
File "C:\Users\betsu\Desktop\yt-dlp-master\yt_dlp\extractor\common.py", line 666, in _request_webpage
return self._downloader.urlopen(url_or_request)
File "C:\Users\betsu\Desktop\yt-dlp-master\yt_dlp\YoutubeDL.py", line 2822, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 531, in open
response = meth(req, response)
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 640, in http_response
response = self.parent.error(
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 569, in error
return self._call_chain(*args)
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 502, in _call_chain
result = func(*args)
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 649, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by CXwudi** [comment] 2021-03-26 01:46
I am not living in Japan so I can't open that link, it seems like we need a VPN for testing it. 
@betsu0 Are you living in Japan or have you tried to let yt-dlp connect through your VPN?

**Comment by nao20010128nao** [comment] 2021-03-26 02:26
For debuggers: you need a VPN via Japan.
Use of Vultr's Tokyo region is not suitable.

**Comment by CXwudi** [comment] 2021-03-26 03:03
Huh, I tried deleting cookies, close my browsers, connect ExpressVPN to Japan, restart the browsers, and it still doesn't work for me. Now I am curious how can we access this video?

**Comment by nao20010128nao** [comment] 2021-03-26 03:06
@CXwudi I'm now trying to reverse it, and HLS downloading is now successful with non-encrypted video.

**Comment by nao20010128nao** [comment] 2021-03-26 03:20
Can you please give me a clue to decode this m3u8 playlist?
'https://pb120e3b8fe.dmc.nico/hlsvod/ht2_nicovideo/nicovideo-so38016254_e8df3356615512c1b53e2303aec25553cfc0724f9704cf84920ff21257998705/1/ts/playlist.m3u8?ht2_nicovideo=6-RlNALwwzLH_1616728649535.omdscwgjkg_qqk3t6_174ayi1mh9xle'
 I successfully extracted this from  https://www.nicovideo.jp/watch/so38016254

**Comment by CXwudi** [comment] 2021-03-26 04:12
@nao20010128nao Nice fix on your side. By looking at your code change, I realized that all `['dmcInfo']` (e.g. [this](https://github.com/yt-dlp/yt-dlp/blob/b23b9eefd9b5f5044103d5dfcab9b890522e2908/yt_dlp/extractor/niconico.py#L214) and [this](https://github.com/yt-dlp/yt-dlp/blob/b23b9eefd9b5f5044103d5dfcab9b890522e2908/yt_dlp/extractor/niconico.py#L232)) should be updated as it is the old schema no longer used. Maybe this can solve the issue on yt-dlp's side?

**Comment by nao20010128nao** [comment] 2021-03-26 04:16
@CXwudi Yes. my version does not use `dmcInfo`, so it's possible.

**Comment by CXwudi** [comment] 2021-03-26 04:23
> Can you please give me a clue to decode this m3u8 playlist?
> https://gist.github.com/nao20010128nao/ec2db2ac52c350420a37b3bc3ccab0bf

@nao20010128nao Maybe one of the contributors from #49 could help to decode this list. I can't even bypass the region restriction so I can't really help with encrypted videos extraction that much. But my guess is,  links are downloadable just like the one from normal extraction?

**Comment by nao20010128nao** [comment] 2021-03-26 04:23
I'm failing to decode ts files in m3u8 playlist.

@CXwudi How should I share my Internet connection with you?

**Comment by CXwudi** [comment] 2021-03-26 04:30
@nao20010128nao It's already 12pm on my place now, but I have contacted you on discord, maybe we can check tmr

**Comment by nao20010128nao** [comment] 2021-03-26 07:45
@CXwundi
I replied you in Discord with credential for proxy.

**Comment by CXwudi** [comment] 2021-03-26 16:44
I am sorry, I am also failing to decode files in m3u8 playlist.......

Here is my [code fix](https://github.com/yt-dlp/yt-dlp/compare/master...CXwudi:niconico-fix-and-improve) and my [run log](https://gist.github.com/CXwudi/b1859cd449f5c2eff3e4e12608dcc4e9)

**Comment by pukkandan** [comment] 2021-03-26 17:03
What is the output when using `--hls-prefer-native` @CXwudi ?

**Comment by CXwudi** [comment] 2021-03-26 17:19
@pukkandan wired output video file, looks like the m3u8 list itself is saved as video file [log](https://gist.github.com/CXwudi/c45ca94c0e20a02affa781deb3210c6f)

**Comment by pukkandan** [comment] 2021-04-04 11:48
Update based on discussion we had on discord

It is possible to download the actual `ts` fragments using https://github.com/pukkandan/yt-dlp-dev/tree/nico. However, it is not possible to decode it rn. It seems like the key that yt-dlp gets from the manifest is invalid for whatever reason

**Comment by tsukumijima** [comment] 2021-04-04 13:36
I think this will be helpful (Japanese): https://qiita.com/tor4kichi/items/91550a71119f3878bfba#comment-346de200d84c79876831
If it is not different from the old specification, you need to request "https://nvapi.nicovideo.jp/v1/2ab0cbaa/watch?t={tracking_id}" before accessing the encryption key. If you do not make a request or make a request without the required headers, a fake encryption key will be returned.

**Comment by CXwudi** [comment] 2021-04-26 03:40
Should this issue be closed by my pr #273

**Comment by pukkandan** [comment] 2021-04-26 04:22
No, sorry
github automatically closed it since you wrote "fix #no" in the description

**Comment by pukkandan** [comment] 2021-04-26 04:30
Update on this issue based on discussions on discord:

@nao20010128nao claims to have gotten it working in their fork; and this is my attempt to port it over https://github.com/pukkandan/yt-dlp-dev/tree/nico (based on code by @CXwudi)

However, I cannot get either to work with proxy or VPN. So unless someone who is in japan can make a PR, this is sadly not going anywhere

**Comment by tsukumijima** [comment] 2021-04-26 18:00
I live in Japan, Is there anything that I can help with?

**Comment by pukkandan** [comment] 2021-04-27 06:48
First, you'll need to test whether either https://github.com/pukkandan/yt-dlp-dev/tree/nico or https://github.com/nao20010128nao/ytdl-patched work to get the encrypted videos.

If @nao20010128nao's patch work, but mine doesn't, we need to figure out why (my version is basically just nao's patch applied on top of #49). The prime candidates that could be causing the issue are either some of the headers, or location of the ping

**Comment by tsukumijima** [comment] 2021-04-27 16:19
I tried.
With ytdl-patched, the encrypted HLS video download was successful.
yt-dlp-dev failed because it couldn't decrypt the HLS video.

**Comment by CXwudi** [comment] 2021-04-27 17:24
@tsukumijima would you mind pasting a full log of yt-dlp-dev u got?

**Comment by tsukumijima** [comment] 2021-04-27 17:47
I found out why yt-dlp-dev didn't work.
The cause was a simple mistake, the dictionary key was wrong.

Simply replace `x['video']['delivery']['trackingId']` with `x['media']['delivery']['trackingId']` and you can now download. ..
It also works without the `Origin` and `Referer` headers.
I also didn't need the `X-Niconico-Language` header. In the first place, I don't think the specification of this header will affect the response of the API.

Also, for unencrypted videos, just because a request to `https://nvapi.nicovideo.jp/v1/2ab0cbaa/watch` fails does not mean that subsequent downloads will fail.
Therefore, it is wrong to raise ExtractorError if the request to `https://nvapi.nicovideo.jp/v1/2ab0cbaa/watch` fails.

The modified code is as follows.
```
        def ping():
            status = try_get(
                self._download_json(
                    'https://nvapi.nicovideo.jp/v1/2ab0cbaa/watch', video_id,
                    query={'t': try_get(api_data, lambda x: x['media']['delivery']['trackingId'])},
                    note='Acquiring permission for downloading video',
                    headers={
                        'X-Frontend-Id': '6',
                        'X-Frontend-Version': '0',
                    }),
                lambda x: x['meta']['status'])
            if status != 200:
                self.report_warning('Failed to acquire permission for playing video. The video may not download.')
```

**Comment by pukkandan** [comment] 2021-04-27 17:53
You have tested this modified code, correct? I'm asking since I wont be able to test it myself

**Comment by CXwudi** [comment] 2021-04-27 17:54
I am so sorry I couldn't catch that dictionary key mistake at first. I should have do a full scan at first 😓

**Comment by pukkandan** [comment] 2021-04-27 18:02
Could you make a PR with your changes? that would be easier

**Comment by CXwudi** [comment] 2021-04-27 18:16
Let me know when the PR is ready, I'd like to involve and learn niconico's mechanism

**Comment by tsukumijima** [comment] 2021-04-27 19:49
There is no official announcement, but it seems that SMILEVIDEO was abolished just when the JSON format of the viewing page changed. As a proof of that, even for videos posted before August 2016, the item "Watch with old distribution system" has disappeared from the menu when right-clicking the video, and the SMILE VIDEO information has disappeared from the API response.

**Comment by tsukumijima** [comment] 2021-04-27 20:31
> Could you make a PR with your changes? that would be easier

I created a PR.
I've changed the implementation around the API headers to my personal taste, but it's not required. It depends on how clean the code you want.
https://github.com/pukkandan/yt-dlp-dev/pull/2

**Closed** 2021-04-28 13:50 UTC
Labels: bug, help wanted

**Comment by tsukumijima** [comment] 2021-04-30 05:29
My changes have been merged into the nico branch of yt-dlp-dev, but when will I merge them into the master branch of yt-dlp?

**Comment by pukkandan** [comment] 2021-04-30 05:30
It was merged in https://github.com/yt-dlp/yt-dlp/commit/2291dbce2a1aa9c5e9e060eb7ac306f037234eb1

**Comment by tsukumijima** [comment] 2021-04-30 06:16
Oops, I overlooked it. Thank you!

**Comment by nao20010128nao** [comment] 2021-05-08 13:01
Just to note: For SMILE formats, it's still "present" in older embed pages. The method is indicated in nicozon.net and the code below is doing the same.
I was able to download so-called "economy" format, while others are 403. Looks like we have to dig into SWF to download other formats, if it's still available internally.

https://github.com/nao20010128nao/ytdl-patched/blob/master/youtube_dl/extractor/niconico_smile.py

**Comment by tsukumijima** [comment] 2021-05-08 13:54
That's interesting. For compatibility?

**Comment by nao20010128nao** [comment] 2021-05-09 00:33
@tsukumijima I think yes, but idk what client still uses it, since SWF player seems to use DMC for playback.

**Comment by Dioxaz** [comment] 2021-05-23 07:51
I think what happens is that the Nicozon downloader is simply retrieving the links via the old flapi trick which URL is http://flapi.nicovideo.jp/api/getflv/[your_video_id]

This can still retrieve the original Smile link to this day but then you get a 403 error regardless if you're Premium or not.
