### ISSUE TITLE
[Feature Request] A mode for awaiting a scheduled premiere

### ISSUE THREAD

**Issue by fstirlitz** [yt-dlp/yt-dlp#940] opened 2021-09-10 10:42 UTC
Right now, if a scheduled broadcast isn’t live yet, this is treated as an extractor error. It would be nice to have a mode that instead of displaying an error and exiting, simply waits out until the broadcast starts and then performs extraction again (which by then should succeed normally).

(Thought of this while waiting for <https://www.youtube.com/watch?v=rtLbghso0Zc>.)

**Comment by pukkandan** [comment] 2021-09-10 10:56
Duplicate of #878

**Closed by pukkandan** 2021-09-10 10:56 UTC
