### ISSUE TITLE
bilibili bangumi broken

### ISSUE THREAD

**Issue by matsumotokenji** [yt-dlp/yt-dlp#7726] opened 2023-07-29 23:13 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Malaysia

### Provide a description that is worded well enough to be understood

as title, bilibili bangumi broken for the provided video link, i have also tried it with and without cookies.

video url:
https://www.bilibili.com/bangumi/play/ss45573
alternet: (Will forward to above URL)
https://www.bilibili.com/video/BV1w94y1i7f1 

e.g. yt-dlp.exe --cookies bilibili_cookies.txt https://www.bilibili.com/bangumi/play/ss45573 -F -vU

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Command:
yt-dlp.exe https://www.bilibili.com/bangumi/play/ss45573 -F -vU

Debug Message:
[debug] Command-line config: ['https://www.bilibili.com/bangumi/play/ss45573', '-F', '-vU']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-01-17-git-dcc9454ab9-full_build-www.gyan.dev (setts), ffprobe 2022-01-17-git-dcc9454ab9-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[BiliBiliBangumi] Extracting URL: https://www.bilibili.com/bangumi/play/ss45573
[BiliBiliBangumi] ss45573: Downloading webpage
ERROR: [BiliBiliBangumi] ss45573: Unable to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\bilibili.py", line 440, in _real_extract
  File "yt_dlp\extractor\common.py", line 1272, in _search_json
  File "yt_dlp\extractor\common.py", line 1258, in _search_regex
```

**Comment by bashonly** [comment] 2023-07-29 23:15
run `yt-dlp --update-to nightly` and try again

Fixed by bdd0b75e3f41ff35440eda6d395008beef19ef2f

Duplicate of #6701

**Closed by bashonly** 2023-07-29 23:15 UTC
Labels: site-bug, triage
