### ISSUE TITLE
[ARTETV] Error during download : Unable to download JSON metadata: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by bestov94** [yt-dlp/yt-dlp#3713] opened 2022-05-11 18:57 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

root@debian:/work/Download# yt-dlp -v 'https://www.arte.tv/fr/videos/103960-027-A/le-dessous-des-cartes/'
[debug] Command-line config: ['-v', 'https://www.arte.tv/fr/videos/103960-027-A/le-dessous-des-cartes/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-14-amd64-x86_64-with-glibc2.31
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [ArteTV] Extracting URL: https://www.arte.tv/fr/videos/103960-027-A/le-dessous-des-cartes/
[ArteTV] 103960-027-A: Downloading JSON metadata
ERROR: [ArteTV] 103960-027-A: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/arte.py", line 57, in _real_extract
    info = self._download_json(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1029, in _download_json
    res = self._download_json_handle(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1008, in _download_json_handle
    res = self._download_webpage_handle(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 800, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 785, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 767, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 3601, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

root@debian:/work/Download# 

### Verbose log

```shell
root@debian:/work/Download# yt-dlp -v 'https://www.arte.tv/fr/videos/103960-027-A/le-dessous-des-cartes/'
[debug] Command-line config: ['-v', 'https://www.arte.tv/fr/videos/103960-027-A/le-dessous-des-cartes/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-14-amd64-x86_64-with-glibc2.31
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [ArteTV] Extracting URL: https://www.arte.tv/fr/videos/103960-027-A/le-dessous-des-cartes/
[ArteTV] 103960-027-A: Downloading JSON metadata
ERROR: [ArteTV] 103960-027-A: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/arte.py", line 57, in _real_extract
    info = self._download_json(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1029, in _download_json
    res = self._download_json_handle(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1008, in _download_json_handle
    res = self._download_webpage_handle(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 800, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 785, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 767, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 3601, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

root@debian:/work/Download#
```

**Comment by Gro-Tsen** [comment] 2022-05-11 20:15
I'm not able to fix this myself, but here is some information in case it helps gain some time to whoever will: the metadata JSON has changed location: `_API_BASE` needs to be changed to `https://api.arte.tv/api/player/v2` in `ArteTVBaseIE`. But this is not enough because it has also changed format. The streams data is now at `data` → `attributes` → `streams` within the JSON, which is a list of objects whose `url` attribute is the link to the m3u8 proper, and various other attributes are of interest (e.g., `mainQuality`, `versions`).

**Comment by goggle** [comment] 2022-05-11 23:07
You will be able to download the video with the patch from this PR: https://github.com/yt-dlp/yt-dlp/pull/3302

**Comment by pukkandan** [comment] 2022-05-12 04:54
### DO NOT BLINDLY TICK THE CHECK BOXES

They are instructions for you to follow!!

![image](https://user-images.githubusercontent.com/6623388/167994731-4c20efda-1666-44e2-a5b4-0d6158a1596e.png)


Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3662

**Closed by pukkandan** 2022-05-12 04:54 UTC
Labels: bug, triage

**Comment by bestov94** [comment] 2022-05-12 20:23
Thanks
