### ISSUE TITLE
Spiegel Podcast (German)

### ISSUE THREAD

**Issue by rdorsch** [yt-dlp/yt-dlp#7333] opened 2023-06-17 13:46 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Germany

### Example URLs

- Example for single video (tested): https://www.spiegel.de/gesundheit/kaelte-wie-uns-kalte-duschen-und-eisbaeder-kraft-geben-podcast-mit-josephine-worseck-a-1545bfb5-6f50-475f-b07c-69d8bd9c17b8
- RSS feed (I did not test this): https://www.omnycontent.com/d/playlist/5ac1e950-45c7-4eb7-87c0-aa0f018441b8/895a9f0b-6d87-4d20-aaba-abc000ffb087/913ea7fc-e0c6-4ba8-8360-abc000ffb08c/podcast.rss

### Provide a description that is worded well enough to be understood

yt-dlp is not able to download the audio file of the podcast in Spiegel Online.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
rd@h370:~$ yt-dlp -vU 'https://www.spiegel.de/gesundheit/kaelte-wie-uns-kalte-duschen-und-eisbaeder-kraft-geben-podcast-mit-josephine-worseck-a-1545bfb5-6f50-475f-b07c-69d8bd9c17b8'
[debug] Command-line config: ['-vU', 'https://www.spiegel.de/gesundheit/kaelte-wie-uns-kalte-duschen-und-eisbaeder-kraft-geben-podcast-mit-josephine-worseck-a-1545bfb5-6f50-475f-b07c-69d8bd9c17b8']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (debian*)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-9-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.9 30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3-1 (setts), ffprobe 5.1.3-1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[Spiegel] Extracting URL: https://www.spiegel.de/gesundheit/kaelte-wie-uns-kalte-duschen-und-eisbaeder-kraft-geben-podcast-mit-josephine-worseck-a-1545bfb5-6f50-475f-b07c-69d8bd9c17b8
[Spiegel] 1545bfb5-6f50-475f-b07c-69d8bd9c17b8: Downloading webpage
ERROR: [Spiegel] 1545bfb5-6f50-475f-b07c-69d8bd9c17b8: Unable to extract media id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/spiegel.py", line 41, in _real_extract
    media_id = self._html_search_regex(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1278, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1242, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

rd@h370:~$
```

**Comment by bashonly** [comment] 2023-06-17 17:05
Currently the extractor only looks for jwplatform embeds. This page embeds a Omny.fm podcast mp3, so the extractor needs to be improved.

A workaround that could be used right now:
 - view the page source
 - ctrl+F for `omnycontent`
 - copy the `podcast.rss` url: 
     - https://www.omnycontent.com/d/playlist/5ac1e950-45c7-4eb7-87c0-aa0f018441b8/895a9f0b-6d87-4d20-aaba-abc000ffb087/913ea7fc-e0c6-4ba8-8360-abc000ffb08c/podcast.rss
 - pass that link to yt-dlp to download the entire podcast feed
 
To properly download single episodes with the correct metadata, the extractor would need a patch like this:
```diff
diff --git a/yt_dlp/extractor/spiegel.py b/yt_dlp/extractor/spiegel.py
index 3701e295a..9a4824945 100644
--- a/yt_dlp/extractor/spiegel.py
+++ b/yt_dlp/extractor/spiegel.py
@@ -1,5 +1,18 @@
+import base64
+import json
+
 from .common import InfoExtractor
 from .jwplatform import JWPlatformIE
+from ..utils import (
+    ExtractorError,
+    extract_attributes,
+    float_or_none,
+    get_element_html_by_attribute,
+    int_or_none,
+    traverse_obj,
+    unescapeHTML,
+    url_or_none,
+)
 
 
 class SpiegelIE(InfoExtractor):
@@ -7,16 +20,30 @@ class SpiegelIE(InfoExtractor):
     _VALID_URL = r'https?://(?:www\.)?(?:spiegel|manager-magazin)\.de(?:/[^/]+)+/[^/]*-(?P<id>[0-9]+|%s)(?:-embed|-iframe)?(?:\.html)?(?:$|[#?])' % _UUID_RE
     _TESTS = [{
         'url': 'http://www.spiegel.de/video/vulkan-tungurahua-in-ecuador-ist-wieder-aktiv-video-1259285.html',
-        'md5': '50c7948883ec85a3e431a0a44b7ad1d6',
+        'md5': '733e87cb88914af3dc75feab363aac57',
         'info_dict': {
             'id': 'II0BUyxY',
             'display_id': '1259285',
             'ext': 'mp4',
-            'title': 'Vulkan Tungurahua in Ecuador ist wieder aktiv - DER SPIEGEL - Wissenschaft',
+            'title': 'Vulkan Tungurahua in Ecuador ist wieder aktiv',
             'description': 'md5:8029d8310232196eb235d27575a8b9f4',
             'duration': 48.0,
             'upload_date': '20130311',
             'timestamp': 1362997920,
+            'thumbnail': 'https://cdn.jwplayer.com/v2/media/II0BUyxY/poster.jpg?width=720',
+        },
+    }, {
+        'url': 'https://www.spiegel.de/gesundheit/kaelte-wie-uns-kalte-duschen-und-eisbaeder-kraft-geben-podcast-mit-josephine-worseck-a-1545bfb5-6f50-475f-b07c-69d8bd9c17b8',
+        'md5': '897603a3c33df6bb26163795c0b6a968',
+        'info_dict': {
+            'id': '48327741-e92a-4cb4-bced-b01a017d2373',
+            'ext': 'mp3',
+            'display_id': '1545bfb5-6f50-475f-b07c-69d8bd9c17b8',
+            'title': 'Gesunde Kälte: Wie uns kalte Duschen und Eisbäder Kraft geben (Mit Josephine Worseck)',
+            'description': 'md5:94586d82937f06348695d9d00fd68822',
+            'tags': 'count:18',
+            'thumbnail': r're:^https://www\.omnycontent\.com/.+/image\.jpg',
+            'duration': 1822.772,
         },
     }, {
         'url': 'http://www.spiegel.de/video/schach-wm-videoanalyse-des-fuenften-spiels-video-1309159.html',
@@ -36,16 +63,49 @@ class SpiegelIE(InfoExtractor):
     }]
 
     def _real_extract(self, url):
-        video_id = self._match_id(url)
-        webpage = self._download_webpage(url, video_id)
-        media_id = self._html_search_regex(
-            r'(&#34;|["\'])mediaId\1\s*:\s*(&#34;|["\'])(?P<id>(?:(?!\2).)+)\2',
-            webpage, 'media id', group='id')
+        display_id = self._match_id(url)
+        webpage = self._download_webpage(url, display_id)
+        jwplatform_id = traverse_obj(
+            get_element_html_by_attribute('data-component', 'JWPlayer', webpage),
+            ({extract_attributes}, 'data-settings', {json.loads}, 'mediaId'))
+
+        if jwplatform_id:
+            return {
+                '_type': 'url_transparent',
+                'id': display_id,
+                'display_id': display_id,
+                'url': f'jwplatform:{jwplatform_id}',
+                'title': self._og_search_title(webpage, default=None),
+                'ie_key': JWPlatformIE.ie_key(),
+            }
+
+        omny_data = self._parse_json(
+            base64.b64decode(
+                self._search_regex(r'<div[^>]+\bx-audio-omny="([^"]+)"', webpage, 'omny data')).decode(),
+            display_id, transform_source=unescapeHTML)
+
+        omny_id = traverse_obj(omny_data, ('audios', ..., 'omnystudioClipId', {str}), get_all=False)
+        if not omny_id:
+            raise ExtractorError('Unable to extract omny id')
+
+        omny_api_data = self._download_json(
+            f'https://omny.fm/api/orgs/5ac1e950-45c7-4eb7-87c0-aa0f018441b8/clips/{omny_id}',
+            omny_id, 'Downloading Omny.fm API JSON')
+        media_url = url_or_none(omny_api_data.get('VideoUrl'))
+        video_codec = 'none' if not media_url else None
+
         return {
-            '_type': 'url_transparent',
-            'id': video_id,
-            'display_id': video_id,
-            'url': 'jwplatform:%s' % media_id,
-            'title': self._og_search_title(webpage, default=None),
-            'ie_key': JWPlatformIE.ie_key(),
+            'id': omny_id,
+            'display_id': display_id,
+            'url': media_url or omny_api_data.get('AudioUrl'),
+            'vcodec': video_codec,
+            **traverse_obj(omny_api_data, {
+                'title': 'Title',
+                'description': 'Description',
+                'tags': ('Tags', ..., {lambda x: x or None}),
+                'season_number': ('Season', {int_or_none}),
+                'episode_number': ('Episode', {int_or_none}),
+                'duration': ('DurationSeconds', {float_or_none}),
+                'thumbnail': ('ImageUrl', {url_or_none}),
+            }),
         }
```

**Comment by bashonly** [comment] 2023-11-07 17:52
Duplicate of #1728

**Closed by bashonly** 2023-11-07 17:52 UTC
Labels: site-bug, patch-available
