### ISSUE TITLE
info = ydl.extract_info(url, download=False) RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by kishoreyakkanti** [yt-dlp/yt-dlp#8208] opened 2023-09-26 09:57 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "fb_scraper.py", line 67, in reels
    info = ydl.extract_info(url, download=False)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1564, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1575, in wrapper
    return func(self, *args, **kwargs)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1731, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1813, in process_ie_result
    extra_info=extra_info)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1564, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1575, in wrapper
    return func(self, *args, **kwargs)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1710, in __extract_info
    ie_result = ie.extract(url)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/extractor/generic.py", line 2563, in _real_extract
    embeds = list(self._extract_embeds(original_url, webpage, urlh=full_response, info_dict=info_dict))
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/extractor/generic.py", line 2588, in _extract_embeds
    gen = ie.extract_from_webpage(self._downloader, url, webpage)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/extractor/lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/extractor/lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/extractor/lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
  [Previous line repeated 485 more times]
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/utils/_utils.py", line 5016, in __get__
    return self.func(cls)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/extractor/lazy_extractors.py", line 33, in real_class
    cls._real_class = getattr(importlib.import_module(cls._module), cls.__name__)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
  File "<frozen importlib._bootstrap>", line 148, in __enter__
  File "<frozen importlib._bootstrap>", line 174, in _get_module_lock
  File "<frozen importlib._bootstrap>", line 59, in __init__
RecursionError: maximum recursion depth exceeded while calling a Python object

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] API
[debug] params: {'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.7.16 (CPython x86_64 64bit) - Linux-5.10.192-182.736.amzn2.x86_64-x86_64-with-glibc2.2.5 (OpenSSL 1.0.2k-fips  26 Jan 2017, glibc 2.2.5)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
https://www.facebook.com/594872649014090
[generic] Extracting URL: https://www.facebook.com/594872649014090
[generic] 594872649014090: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F594872649014090
[generic] Extracting URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2F594872649014090
[generic] ?next=https://www.facebook: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ?next=https://www.facebook: Extracting information
[debug] Looking for embeds
WARNING: Falling back to normal extractor since lazy extractor VLiveWebArchiveIE does not have attribute real_class; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
maximum recursion depth exceeded while calling a Python object

Traceback (most recent call last):
  File "fb_scraper.py", line 67, in reels
    info = ydl.extract_info(url, download=False)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1564, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1575, in wrapper
    return func(self, *args, **kwargs)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1731, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1813, in process_ie_result
    extra_info=extra_info)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1564, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1575, in wrapper
    return func(self, *args, **kwargs)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1710, in __extract_info
    ie_result = ie.extract(url)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/extractor/generic.py", line 2563, in _real_extract
    embeds = list(self._extract_embeds(original_url, webpage, urlh=full_response, info_dict=info_dict))
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/extractor/generic.py", line 2588, in _extract_embeds
    gen = ie.extract_from_webpage(self._downloader, url, webpage)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/extractor/lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/extractor/lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/extractor/lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
  [Previous line repeated 485 more times]
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/utils/_utils.py", line 5016, in __get__
    return self.func(cls)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/extractor/lazy_extractors.py", line 33, in real_class
    cls._real_class = getattr(importlib.import_module(cls._module), cls.__name__)
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
  File "<frozen importlib._bootstrap>", line 148, in __enter__
  File "<frozen importlib._bootstrap>", line 174, in _get_module_lock
  File "<frozen importlib._bootstrap>", line 59, in __init__
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by bashonly** [comment] 2023-09-26 10:13
Duplicate of #8168

**Closed by bashonly** 2023-09-26 10:13 UTC
Labels: duplicate, question, spam, site:facebook
