### ISSUE TITLE
[NeteaseMusic] It doesn't seem to be working properly

### ISSUE THREAD

**Issue by timi137137** [yt-dlp/yt-dlp#10239] opened 2024-06-22 21:37 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Provide a description that is worded well enough to be understood

Use Version: 2024.05.27
Use Command:  
`yt-dlp --cookies-from-browser chrome --proxy socks5://127.0.0.1:7890 -f "ba" -x --audio-format wav https://music.163.com/#/song?id=29758212`
or
`yt-dlp --cookies-from-browser chrome --proxy socks5://127.0.0.1:7890 -f "ba" -x --audio-format wav http://163cn.tv/rSfsXhr`

Result: They are abnormal because the content they get is not the best.The link given should normally get an audio with a file size of 95.38MB.
原因：他们是不正常的，因为获取到的内容并非最好。给出的链接中正常应该获取到一个文件大小为95.38MB的音频。

**!! And he can't identify what's best  !!**

The following figure shows the file sizes and details obtained by YT-DLP and third parties
以下图中展示了YT-DLP和第三方途径获取的文件大小及详情
![image](https://github.com/yt-dlp/yt-dlp/assets/36812439/7bd538a2-ce1d-4622-bcc9-515a6a8463d9)
![image](https://github.com/yt-dlp/yt-dlp/assets/36812439/165d6cad-04ce-4e7b-b011-670cd2556bfc)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --cookies-from-browser chrome --proxy socks5://127.0.0.1:7890 -f "ba" -x --audio-format wav http://163cn.tv/rSfsXhr
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'chrome', '--proxy', 'socks5://127.0.0.1:7890', '-f', 'ba', '-x', '--audio-format', 'wav', 'http://163cn.tv/rSfsXhr']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110338-g4570ba5d86-20230421 (setts), ffprobe N-110338-g4570ba5d86-20230421
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.2, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {'all': 'socks5://127.0.0.1:7890'}
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\timi\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\timi\AppData\Local\Google\Chrome\User Data\Local State"
Attempting to unlock cookies
Extracted 3817 cookies from chrome
[debug] cookie version breakdown: {'v10': 4268, 'other': 0, 'unencrypted': 33}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: ['D:\\App\\System\\Other\\YoutudeDownloader\\yt-dlp-plugins\\cookie_unlock\\yt_dlp_plugins']
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[generic] Extracting URL: http://163cn.tv/rSfsXhr
[generic] rSfsXhr: Downloading webpage
[redirect] Following redirect to https://y.music.163.com/m/song?app_version=9.0.95&id=29758212&uct2=uaUUcf1jMmkXBeDb%2FlNQMg==&dlt=0846
[netease:song] Extracting URL: https://y.music.163.com/m/song?app_version=9.0.95&id=29758212&uct2=uaUUcf1jMmkXBeDb%2FlNQMg==&dlt=0846
[netease:song] 29758212: Downloading song info
[netease:song] 29758212: Downloading song URL info: bitrate 128000
[netease:song] 29758212: Checking song URL
[netease:song] 29758212: Downloading song URL info: bitrate 192000
[netease:song] 29758212: Checking song URL
[netease:song] 29758212: Downloading song URL info: bitrate 320000
[netease:song] 29758212: Checking song URL
[netease:song] 29758212: Downloading lyrics data
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
ERROR: [netease:song] 29758212: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1606, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1762, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1821, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2955, in process_video_result
yt_dlp.utils.ExtractorError: [netease:song] 29758212: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by timi137137** [comment] 2024-06-22 21:38
Third party tools are: https://github.com/Suxiaoqinx/Netease_url

**Comment by bashonly** [comment] 2024-06-22 22:03
Duplicate of #9196

**Closed by bashonly** 2024-06-22 22:03 UTC
Labels: site-bug, triage

**Comment by timi137137** [comment] 2024-06-23 08:56
@bashonly Please note that this repetition represents only one of the issues, and it has not been fixed.

Problem 1: Unable to obtain sound quality. This is repeated but now he has a total of 7 sound qualities, only 6 in PR
![image](https://github.com/yt-dlp/yt-dlp/assets/36812439/2f9860b6-5d9c-4ebe-a01d-369e9daaeb67)

Problem 2: He can't read my SVIP information. I have installed chrome cookie unlock plug-in, which can clearly prove that my account information can be used (the third party uses the same browser cookie), but yt-dlp cannot be effectively invoked, which proves that the problem is not solved.
