### ISSUE TITLE
ERROR: [Instagram]: Requested content is not available, rate-limit reached or login required 

### ISSUE THREAD

**Issue by Suncatcher** [yt-dlp/yt-dlp#11166] opened 2024-10-05 04:53 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Downloading the below reel via Seal fails:
https://www.instagram.com/reel/DApNLulPew0/?utm_source=ig_web_button_native_share
![Screenshot_20241004_214350_Seal](https://github.com/user-attachments/assets/2c9dc9a9-5e1b-4c83-bd74-fc059f7ed326)
```

App version: 1.13.0 (11302)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 

URL: https://www.instagram.com/reel/DApNLulPew0
WARNING: [Instagram] DApNLulPew0: General metadata extraction failed (some metadata might be missing).
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] DApNLulPew0: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials

```
The Seal error recommends to create an issue here.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-P', '/storage/emulated/0/Download/Seal', '--newline', '--config-locations', '/data/user/0/com.junkfood.seal/cache/config.txt', '--no-cache-dir', '--ffmpeg-location', '/data/app/~~CmBgnWhfMajpcwbq69_itg==/com.junkfood.seal-2IqXd5SGTioT-M-H-9OG2Q==/lib/arm64/libffmpeg.so', 'https://www.instagram.com/reel/DApNLulPew0/?utm_source=ig_web_button_native_share']
[debug] | Config "/data/user/0/com.junkfood.seal/cache/config.txt": ['--no-mtime', '-S', 'ext', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-5.15.123-android13-3-28579584-aarch64-with-libc (OpenSSL 1.1.1t  7 Feb 2023, libc)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.17, mutagen-1.46.0, sqlite3-3.30.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2024.09.27/SHA2-256SUMS
[debug] Downloading yt-dlp from https://github.com/yt-dlp/yt-dlp/releases/download/2024.09.27/yt-dlp
WARNING: Restart yt-dlp to use the updated version
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 17, in <module>
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 1072, in main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 1062, in _real_main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3572, in download
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3547, in wrapper
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1595, in extract_info
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 844, in get_info_extractor
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 37, in __new__
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils/_utils.py", line 4996, in __get__
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 33, in real_class
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 548, in _get_data
zipimport.ZipImportError: bad local file header: '/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp'
```

**Comment by grqz** [comment] 2024-10-05 07:46
duplicate of #11151

**Closed** 2024-10-05 07:47 UTC
Labels: duplicate, site:instagram
