### ISSUE TITLE
[X / Twitter] Error while trying to download a video (Error 22: Invalid argument)

### ISSUE THREAD

**Issue by ANormalDumbass** [yt-dlp/yt-dlp#11251] opened 2024-10-14 23:00 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Any

### Provide a description that is worded well enough to be understood

While trying to download a video from Twitter, i've gotten an error about an "Invalid Argument", yt-dlp tries to save a fragment of the video with the name "ricky - resumen de la conversación en la que cam se inventa que dalas ha tenido intenciones con ella. lo compara con un delincuente sexual y suelta otras perlitas que sus nuevos amigos seguramente no habían escuchado. [1845884909975433216].fhls-252.mp4.ytdl" and it gives this error.

Here is the command i have done, which got the error: 

yt-dlp.exe https://twitter.com/rickyedit/status/1845885184341631084

The error comes from yt-dlp, by trying to save a file with the name too long. An easy fix is to check the output name, and if it's too long, it should cut it, or insert other name.

Another easy fix the user can do is by inserting another name to the file saved, as this: 
yt-dlp.exe -o "video_twitter.mp4" https://twitter.com/rickyedit/status/1845885184341631084

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\redacted\Desktop\REDACTED>yt-dlp.exe -vU https://twitter.com/rickyedit/status/1845885184341631084
[debug] Command-line config: ['-vU', 'https://twitter.com/rickyedit/status/1845885184341631084']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.13.232959 from yt-dlp/yt-dlp-nightly-builds [cba786850] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.13.232959 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.13.232959 from yt-dlp/yt-dlp-nightly-builds)
[twitter] Extracting URL: https://twitter.com/rickyedit/status/1845885184341631084
[twitter] 1845885184341631084: Downloading guest token
[twitter] 1845885184341631084: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1845884909975433216
[twitter] 1845885184341631084: Downloading m3u8 information
[debug] Sort order given by extractor: res, proto:m3u8, br, size
[debug] Formats sorted by: hasvid, ie_pref, res, proto:m3u8(8), br, size, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1845884909975433216: Downloading 1 format(s): hls-252+hls-audio-128000-Audio
[debug] Invoking hlsnative downloader on "https://video.twimg.com/amplify_video/1845884909975433216/pl/avc1/1140x720/S7pDj-t_FqYQVWnv.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 233
[download] Destination: ricky - resumen de la conversación en la que cam se inventa que dalas ha tenido intenciones con ella. lo compara con un delincuente sexual y suelta otras perlitas que sus nuevos amigos seguramente no habían escuchado. [1845884909975433216].fhls-252.mp4
[download] Unable to open file: [Errno 22] Invalid argument: 'ricky - resumen de la conversación en la que cam se inventa que dalas ha tenido intenciones con ella. lo compara con un delincuente sexual y suelta otras perlitas que sus nuevos amigos seguramente no habían escuchado. [1845884909975433216].fhls-252.mp4.ytdl'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'ricky - resumen de la conversación en la que cam se inventa que dalas ha tenido intenciones con ella. lo compara con un delincuente sexual y suelta otras perlitas que sus nuevos amigos seguramente no habían escuchado. [1845884909975433216].fhls-252.mp4.ytdl'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'ricky - resumen de la conversación en la que cam se inventa que dalas ha tenido intenciones con ella. lo compara con un delincuente sexual y suelta otras perlitas que sus nuevos amigos seguramente no habían escuchado. [1845884909975433216].fhls-252.mp4.ytdl'. Retrying (3/3)...
ERROR: Unable to download video: [Errno 22] Invalid argument: 'ricky - resumen de la conversación en la que cam se inventa que dalas ha tenido intenciones con ella. lo compara con un delincuente sexual y suelta otras perlitas que sus nuevos amigos seguramente no habían escuchado. [1845884909975433216].fhls-252.mp4.ytdl'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 590, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3465, in process_info
  File "yt_dlp\YoutubeDL.py", line 3203, in dl
  File "yt_dlp\downloader\common.py", line 466, in download
  File "yt_dlp\downloader\hls.py", line 158, in real_download
  File "yt_dlp\downloader\fragment.py", line 77, in _prepare_and_start_frag_download
  File "yt_dlp\downloader\fragment.py", line 213, in _prepare_frag_download
  File "yt_dlp\downloader\fragment.py", line 97, in _write_ytdl_file
  File "yt_dlp\downloader\common.py", line 243, in wrapper
  File "yt_dlp\utils\_utils.py", line 5250, in __iter__
  File "yt_dlp\downloader\common.py", line 236, in error_callback
  File "yt_dlp\utils\_utils.py", line 5258, in report_retry
  File "yt_dlp\downloader\common.py", line 245, in wrapper
  File "yt_dlp\downloader\common.py", line 256, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 593, in sanitize_open
OSError: [Errno 22] Invalid argument: 'ricky - resumen de la conversación en la que cam se inventa que dalas ha tenido intenciones con ella. lo compara con un delincuente sexual y suelta otras perlitas que sus nuevos amigos seguramente no habían escuchado. [1845884909975433216].fhls-252.mp4.ytdl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 3015, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 179, in wrapper
  File "yt_dlp\YoutubeDL.py", line 3495, in process_info
yt_dlp.utils.UnavailableVideoError: Unable to download video: [Errno 22] Invalid argument: 'ricky - resumen de la conversación en la que cam se inventa que dalas ha tenido intenciones con ella. lo compara con un delincuente sexual y suelta otras perlitas que sus nuevos amigos seguramente no habían escuchado. [1845884909975433216].fhls-252.mp4.ytdl'
```

**Comment by gamer191** [comment] 2024-10-14 23:13
use `--output "%(title).200B [%(id)s].%(ext)s"` to shorten the title or `--output "%(title)s.%(ext)s"` to remove the video id (part in square quotes)

Closing as duplicate of https://github.com/yt-dlp/yt-dlp/issues/1136

**Closed by gamer191** 2024-10-14 23:13 UTC
Labels: site-bug, triage

**Comment by ANormalDumbass** [comment] 2024-10-14 23:15
The duplicate is from 2021, how was I supposed to find that?

Also, why hasn't that error been fixed since them?

**Comment by bashonly** [comment] 2024-10-15 00:03
> The duplicate is from 2021, how was I supposed to find that?

No one said you were supposed to. The issue was closed as a duplicate and linked to the original for tracker maintenance

> I'm pretty sure most yt-dlp users don't even know that they can change it's own file name

There is [an entire section of the README devoted to this](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template) with [several usage examples](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template-examples)

> this is an error from the code's side.

https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-2021699075
