### ISSUE TITLE
Unable to extract Initial JS player n function name

### ISSUE THREAD

**Issue by frogtile** [yt-dlp/yt-dlp#2615] opened 2022-02-03 03:57 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

while downloading a playlist there was this error message printed before downloading every video of that playlist. (the download was successful).

```
yt-dlp -f 249,243 https://youtube.com/playlist?list=PLE3MtMBjMVLezj0KQmJFbw6gWLZhpfuo4
``` 

### Verbose log

```shell
yt-dlp --verbose -f 249,243 https://youtube.com/playlist?list=PLE3MtMBjMVLezj0KQmJFbw6gWLZhpfuo4
[debug] Command-line config: ['--verbose', '-f', '249,243', 'https://youtube.com/playlist?list=PLE3MtMBjMVLezj0KQmJFbw6gWLZhpfuo4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.15.18-200.fc35.x86_64-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://youtube.com/playlist?list=PLE3MtMBjMVLezj0KQmJFbw6gWLZhpfuo4
[youtube:tab] PLE3MtMBjMVLezj0KQmJFbw6gWLZhpfuo4: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=PLE3MtMBjMVLezj0KQmJFbw6gWLZhpfuo4
[youtube:tab] PLE3MtMBjMVLezj0KQmJFbw6gWLZhpfuo4: Downloading API JSON with unavailable videos
[download] Downloading playlist: Statics
[youtube:tab] playlist Statics: Downloading 19 videos
[download] Downloading video 1 of 19
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=uAzpUfTeS5E
[youtube] uAzpUfTeS5E: Downloading webpage
[youtube] uAzpUfTeS5E: Downloading android player API JSON
[youtube] uAzpUfTeS5E: Downloading player cdb8d439
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = iqhPXWLKL0Ali1P ; player = https://www.youtube.com/s/player/cdb8d439/player_ias.vflset/en_US/base.js
uAzpUfTeS5E: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 2412, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 2433, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 2421, in _extract_n_function_name
    return self._search_regex(
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] uAzpUfTeS5E: Downloading 2 format(s): 249, 243
[debug] Invoking downloader on "https://rr2---sn-nu5gb5ux-q5je.googlevideo.com/videoplayback?expire=1643881932&ei=bFH7YaGeOZCw1AaGx7aQCA&ip=103.146.92.37&id=o-AKhnLsd-XdWL8c_SG_uLpR27SCPCWG975RpINwMahzs3&itag=249&source=youtube&requiressl=yes&mh=bC&mm=31%2C29&mn=sn-nu5gb5ux-q5je%2Csn-n0hhpujvh-q5j6&ms=au%2Crdu&mv=m&mvi=2&pl=24&initcwndbps=856250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=7389762&dur=1236.841&lmt=1620732709207504&mt=1643859903&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAL_5yOIlawE1k76mUNHqGWeSvf_g4Ve8tHGSo11qeddbAiEAuHGqj8a_Himvd-Z0JSjWqeSLVrxVP4vYUHse5qXzjtY%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgXy-PAQ1RY3B-TtVgS0mZr6Gt6EqaNWUQeU2Twa9QcBkCIBaueD_tLjTy2-KjVAjQ6DZ5VK9B9YuQ-OUnugiQyJ9Y"
[download] Destination: Statics Part 1 (Introduction) [uAzpUfTeS5E].webm
[download]  14.0% of 7.05MiB at 760.85KiB/s ETA 00:08^C
ERROR: Interrupted by user
```

**Comment by coletdjnz** [comment] 2022-02-03 04:05
> I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates

![image](https://user-images.githubusercontent.com/27879174/152279294-e4c96930-e6d3-4b31-9b79-72c33f5c1407.png)

duplicate of https://github.com/yt-dlp/yt-dlp/issues/2569 https://github.com/yt-dlp/yt-dlp/issues/2575 https://github.com/yt-dlp/yt-dlp/issues/2576 https://github.com/yt-dlp/yt-dlp/issues/2588 https://github.com/yt-dlp/yt-dlp/issues/2602

Already fixed in master, downloads should not be impacted.

**Closed by coletdjnz** 2022-02-03 04:05 UTC
Labels: duplicate, site-bug

**Comment by frogtile** [comment] 2022-02-03 04:28
@coletdjnz sorry, I was in hurry, didn't think this could happen to others as well.
