### ISSUE TITLE
yt-dlp not downloading facebook videos (like reels) since June 2024

### ISSUE THREAD

**Issue by pibolito** [yt-dlp/yt-dlp#10285] opened 2024-06-28 01:31 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

[debug] Command-line config: ['-vU', 'https://www.facebook.com/reel/1160876751728187']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (pip)
[debug] Python 3.8.16 (CPython x86_64 64bit) - Linux-3.10.0-1160.108.1.el7.x86_64-x86_64-with-glibc2.17 (OpenSSL 1.0.2k-fips  26 Jan 2017, glibc 2.17)
[debug] exe versions: ffmpeg 3.4.13, ffprobe 3.4.13
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, websockets
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[facebook:reel] Extracting URL: https://www.facebook.com/reel/1160876751728187
[facebook] Extracting URL: https://m.facebook.com/watch/?v=1160876751728187&_rdr
[facebook] 1160876751728187: Downloading webpage
ERROR: [facebook] 1160876751728187: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment] 2024-06-28 01:33
Duplicate of #10227

Update to nightly:
```
# To update to nightly from stable executable/binary:
yt-dlp --update-to nightly

# To install nightly with pip:
python3 -m pip install -U --pre "yt-dlp[default]"
```

**Closed by seproDev** 2024-06-28 01:33 UTC
Labels: duplicate, site-bug, site:facebook
