### ISSUE TITLE
Twitter / X Videos Will Not Download Unless -o is Used to Sanitize filenames

### ISSUE THREAD

**Issue by scramblr** [yt-dlp/yt-dlp#11495] opened 2024-11-10 16:14 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Global

### Provide a description that is worded well enough to be understood

Hello, The X (Twitter) parser seems to not be working, both on actual tweets with the video embedded, or the direct link to the "Video Address" unless you use the -o option to output the file to a sane filename. Since this seems to happen VERY frequently on Twitter/X - I'm proposing that a feature be added to automatically name the file the Tweet Number.mp4 only, instead of usernames, descriptions, etc. If the user wants a more robust name, let them choose it through flags. This will cut down the amount of "Twitter isnt working on yt-dlp" reports by a huge amount.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug]
H:\VIDEO\INBOUND - UNPROCESSED VIDEO>yt-dlp "https://x.com/i/status/1855362770637664497" -vU
[debug] Command-line config: ['https://x.com/i/status/1855362770637664497', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.11.09.232836 from yt-dlp/yt-dlp-nightly-builds [f13df591d] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.1-full_build-www.gyan.dev (setts), ffprobe 7.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.11.09.232836 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.11.09.232836 from yt-dlp/yt-dlp-nightly-builds)
[twitter] Extracting URL: https://x.com/i/status/1855362770637664497
[twitter] 1855362770637664497: Downloading guest token
[twitter] 1855362770637664497: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1855362342701129728
[twitter] 1855362770637664497: Downloading m3u8 information
[debug] Sort order given by extractor: res, proto:m3u8, br, size
[debug] Formats sorted by: hasvid, ie_pref, res, proto:m3u8(8), br, size, lang, quality, fps, hdr:12(7), vcodec, channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1855362342701129728: Downloading 1 format(s): hls-820+hls-audio-128000-Audio
[debug] Invoking hlsnative downloader on "https://video.twimg.com/amplify_video/1855362342701129728/pl/avc1/720x1280/cBkxCLlQLUdLn65J.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 196
[download] Destination: Bryan Dawson🇺🇸 - 🚨‼️MUST WATCH and SHARE before Elon Musk bans it：  Since US media won’t tell you, UK activists, Led By Donkeys, dropped this video on how Elon Musk and his use of X helped get Donald Trump elected.  @ByDonkeys [1855362342701129728].fhls-820.mp4
[download] Unable to open file: [Errno 22] Invalid argument: 'Bryan Dawson🇺🇸 - 🚨‼️MUST WATCH and SHARE before Elon Musk bans it：  Since US media won’t tell you, UK activists, Led By Donkeys, dropped this video on how Elon Musk and his use of X helped get Donald Trump elected.  @ByDonkeys [1855362342701129728].fhls-820.mp4.ytdl'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'Bryan Dawson🇺🇸 - 🚨‼️MUST WATCH and SHARE before Elon Musk bans it：  Since US media won’t tell you, UK activists, Led By Donkeys, dropped this video on how Elon Musk and his use of X helped get Donald Trump elected.  @ByDonkeys [1855362342701129728].fhls-820.mp4.ytdl'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'Bryan Dawson🇺🇸 - 🚨‼️MUST WATCH and SHARE before Elon Musk bans it：  Since US media won’t tell you, UK activists, Led By Donkeys, dropped this video on how Elon Musk and his use of X helped get Donald Trump elected.  @ByDonkeys [1855362342701129728].fhls-820.mp4.ytdl'. Retrying (3/3)...
ERROR: Unable to download video: [Errno 22] Invalid argument: 'Bryan Dawson🇺🇸 - 🚨‼️MUST WATCH and SHARE before Elon Musk bans it：  Since US media won’t tell you, UK activists, Led By Donkeys, dropped this video on how Elon Musk and his use of X helped get Donald Trump elected.  @ByDonkeys [1855362342701129728].fhls-820.mp4.ytdl'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 607, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3461, in process_info
  File "yt_dlp\YoutubeDL.py", line 3199, in dl
  File "yt_dlp\downloader\common.py", line 466, in download
  File "yt_dlp\downloader\hls.py", line 158, in real_download
  File "yt_dlp\downloader\fragment.py", line 77, in _prepare_and_start_frag_download
  File "yt_dlp\downloader\fragment.py", line 213, in _prepare_frag_download
  File "yt_dlp\downloader\fragment.py", line 97, in _write_ytdl_file
  File "yt_dlp\downloader\common.py", line 243, in wrapper
  File "yt_dlp\utils\_utils.py", line 5271, in __iter__
  File "yt_dlp\downloader\common.py", line 236, in error_callback
  File "yt_dlp\utils\_utils.py", line 5279, in report_retry
  File "yt_dlp\downloader\common.py", line 245, in wrapper
  File "yt_dlp\downloader\common.py", line 256, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 610, in sanitize_open
OSError: [Errno 22] Invalid argument: 'Bryan Dawson🇺🇸 - 🚨‼️MUST WATCH and SHARE before Elon Musk bans it：  Since US media won’t tell you, UK activists, Led By Donkeys, dropped this video on how Elon Musk and his use of X helped get Donald Trump elected.  @ByDonkeys [1855362342701129728].fhls-820.mp4.ytdl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1625, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1781, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1840, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 3011, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 178, in wrapper
  File "yt_dlp\YoutubeDL.py", line 3491, in process_info
yt_dlp.utils.UnavailableVideoError: Unable to download video: [Errno 22] Invalid argument: 'Bryan Dawson🇺🇸 - 🚨‼️MUST WATCH and SHARE before Elon Musk bans it：  Since US media won’t tell you, UK activists, Led By Donkeys, dropped this video on how Elon Musk and his use of X helped get Donald Trump elected.  @ByDonkeys [1855362342701129728].fhls-820.mp4.ytdl'


H:\VIDEO\INBOUND - UNPROCESSED VIDEO>yt-dlp "https://x.com/i/status/1855362770637664497" -vU -o test.mp4
[debug] Command-line config: ['https://x.com/i/status/1855362770637664497', '-vU', '-o', 'test.mp4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.11.09.232836 from yt-dlp/yt-dlp-nightly-builds [f13df591d] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.1-full_build-www.gyan.dev (setts), ffprobe 7.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.11.09.232836 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.11.09.232836 from yt-dlp/yt-dlp-nightly-builds)
[twitter] Extracting URL: https://x.com/i/status/1855362770637664497
[twitter] 1855362770637664497: Downloading guest token
[twitter] 1855362770637664497: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1855362342701129728
[twitter] 1855362770637664497: Downloading m3u8 information
[debug] Sort order given by extractor: res, proto:m3u8, br, size
[debug] Formats sorted by: hasvid, ie_pref, res, proto:m3u8(8), br, size, lang, quality, fps, hdr:12(7), vcodec, channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1855362342701129728: Downloading 1 format(s): hls-820+hls-audio-128000-Audio
[debug] Invoking hlsnative downloader on "https://video.twimg.com/amplify_video/1855362342701129728/pl/avc1/720x1280/cBkxCLlQLUdLn65J.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 196
[download] Destination: test.fhls-820.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of   48.54MiB in 00:00:37 at 1.28MiB/s
[debug] Invoking hlsnative downloader on "https://video.twimg.com/amplify_video/1855362342701129728/pl/mp4a/128000/NCHJi-GrXQJZ4AT6.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 196
[download] Destination: test.fhls-audio-128000-Audio.mp4
[download] 100% of    9.08MiB in 00:00:30 at 308.60KiB/s
[debug] ffmpeg command line: ffprobe -show_streams file:test.fhls-audio-128000-Audio.mp4
[Merger] Merging formats into "test.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:test.fhls-820.mp4 -i file:test.fhls-audio-128000-Audio.mp4 -c copy -map 0:v:0 -map 1:a:0 -bsf:a:0 aac_adtstoasc -movflags +faststart file:test.temp.mp4
Deleting original file test.fhls-audio-128000-Audio.mp4 (pass -k to keep)
Deleting original file test.fhls-820.mp4 (pass -k to keep)

H:\VIDEO\INBOUND - UNPROCESSED VIDEO>
```

**Comment by Grub4K** [comment] 2024-11-10 16:21
Duplicate of #1136

**Closed by Grub4K** 2024-11-10 16:21 UTC
Labels: site-bug, triage

**Comment by scramblr** [comment] 2024-11-10 16:30
My bad. thanks @Grub4K

**Comment by dirkf** [comment] 2024-11-11 01:35
Although the topic of this issue is discussed in #1136, is this not a separate, and actually achievable, request?

There is no reason for the entire text of a tweet/xeet to be its `title`. Let that be in the `description` and create a title, either just `Tweet` (then the ID will be added in the default output template), or by truncating the text to, say, 20 (possibly an extractor option) characters.

**Comment by bashonly** [comment] 2024-11-11 19:50
@dirkf Would we do the same for the tiktok, reddit and facebook extractors (and any other site where the extractor currently uses the full post's text as the `title`)?

**Comment by dirkf** [comment] 2024-11-11 23:19
Twitter/X seems to be the main source of complaints and one of these mods seems like a good way to prevent them.

The same principle could apply to the other sites, but I don't see the same level of problem reports for them.
