### ISSUE TITLE
"WARNING: Falling back to normal extractor"

### ISSUE THREAD

**Issue by Onii-Chan-Discord** [yt-dlp/yt-dlp#1948] opened 2021-12-10 07:50 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

`WARNING: Falling back to normal extractor since lazy extractor YoutubeSearchIE doe have attribute _VALID_URL; please report this issue on  https://github.com/yt-dlplp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt on how to update. Be sure to call yt-dlp with the --verbose flag and include its ete output.`

Im getting this error message, is it something i should be worry about, if it is how should i fix it? Because i cant understand the error message because its kinda botched.

### Verbose log

```shell
(dev) ubuntu@instance-20211029-1639:~/cogs$ yt-dlp  -Uv https://www.youtube.com/watch?v=tt2k8PGm-TI
[debug] Command-line config: ['-Uv', 'https://www.youtube.com/watch?v=tt2k8PGm-TI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.11.0-1019-oracle-aarch64-with-glibc2.31
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=tt2k8PGm-TI
[youtube] tt2k8PGm-TI: Downloading webpage
[youtube] tt2k8PGm-TI: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] tt2k8PGm-TI: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://r2---sn-hxa7zn7s.googlevideo.com/videoplayback?expire=1639144164&ei=hAazYd7iGvGAjuMP5vqzOA&ip=168.138.8.86&id=o-ALVlpLPA_QkiXcJVc0AhYs-o9Dk7X3UcLSlR73-1MGJq&itag=248&source=youtube&requiressl=yes&mh=jL&mm=31%2C26&mn=sn-hxa7zn7s%2Csn-ntqe6n76&ms=au%2Conr&mv=m&mvi=2&pl=24&gcr=cn&initcwndbps=1551250&vprv=1&mime=video%2Fwebm&gir=yes&clen=43545990&dur=337.002&lmt=1628126702304323&mt=1639122294&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgKgXZefO-3rWbF8_1Ce_pRM0cq9WtAZsr4c8EoPJp9_ECIQCdKAf0BwpfNU554HgcRsWCNmNfAhh6ypkJ3Wxupoa43Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALP_F7FNKfOojdTqAI1vdpm_wpdQtREcnzXU7kR496p8AiB4xpOf0gNZZiv4zgFHuiKjwT45Pj5pPtlvmP8JI2zOXQ%3D%3D"
[download] Destination: ZAYN - Dusk Till Dawn (Official Video) ft. Sia [tt2k8PGm-TI].f248.webm
[download] 100% of 41.53MiB in 00:01                                      
[debug] Invoking downloader on "https://r2---sn-hxa7zn7s.googlevideo.com/videoplayback?expire=1639144164&ei=hAazYd7iGvGAjuMP5vqzOA&ip=168.138.8.86&id=o-ALVlpLPA_QkiXcJVc0AhYs-o9Dk7X3UcLSlR73-1MGJq&itag=251&source=youtube&requiressl=yes&mh=jL&mm=31%2C26&mn=sn-hxa7zn7s%2Csn-ntqe6n76&ms=au%2Conr&mv=m&mvi=2&pl=24&gcr=cn&initcwndbps=1551250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=5353732&dur=337.041&lmt=1590786080941441&mt=1639122294&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgfrCpnmqjOAP87aUEZXaPzkQrofgxXH1Lato6E9wMP_ACIDXd9gERtNkj3oMdYKvyC8nkkIS-HH10xuy1VEOnpOI9&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALP_F7FNKfOojdTqAI1vdpm_wpdQtREcnzXU7kR496p8AiB4xpOf0gNZZiv4zgFHuiKjwT45Pj5pPtlvmP8JI2zOXQ%3D%3D"
[download] Destination: ZAYN - Dusk Till Dawn (Official Video) ft. Sia [tt2k8PGm-TI].f251.webm
[download] 100% of 5.11MiB in 00:00                                     
[Merger] Merging formats into "ZAYN - Dusk Till Dawn (Official Video) ft. Sia [tt2k8PGm-TI].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:ZAYN - Dusk Till Dawn (Official Video) ft. Sia [tt2k8PGm-TI].f248.webm' -i 'file:ZAYN - Dusk Till Dawn (Official Video) ft. Sia [tt2k8PGm-TI].f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:ZAYN - Dusk Till Dawn (Official Video) ft. Sia [tt2k8PGm-TI].temp.webm'
Deleting original file ZAYN - Dusk Till Dawn (Official Video) ft. Sia [tt2k8PGm-TI].f248.webm (pass -k to keep)
Deleting original file ZAYN - Dusk Till Dawn (Official Video) ft. Sia [tt2k8PGm-TI].f251.webm (pass -k to keep)
```

**Comment by Ashish0804** [comment] 2021-12-10 08:05
the log doesn't reflect the error message afaics

**Comment by coletdjnz** [comment] 2021-12-10 08:08
duplicate of https://github.com/yt-dlp/yt-dlp/issues/1851
fixed in https://github.com/yt-dlp/yt-dlp/commit/2c4aaaddc99dfb57cb3a5395e4d2fff2f4b819a4

**Closed by coletdjnz** 2021-12-10 08:08 UTC
Labels: bug, triage

**Comment by Onii-Chan-Discord** [comment] 2021-12-10 11:24
Ah my bad i must have missed it, apologies for making a duplicate, also you mentioned it was fixed? Well would you know why its still happening to me?

**Comment by pukkandan** [comment] 2021-12-10 11:30
It is fixed in code, but not yet released.

Also, the warning is nothing to worry about for the end user. Even if the lazy extraction breaks, there are fallbacks in place to ensure that it doesn't actually harm the running of the program. But if you encounter this again (after next release), be sure to report again so that we can keep making it better

**Comment by Onii-Chan-Discord** [comment] 2021-12-10 11:37
Ok thank you!
