### ISSUE TITLE
Regression in "make install" with commit 77f90330

### ISSUE THREAD

**Issue by ldoolitt** [yt-dlp/yt-dlp#3479] opened 2022-04-19 05:46 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

If have a patch, that I will attempt to attach.  Maybe I'm strange, but I always install yt-dlp before using it.
I had to add yt_dlp/compat yt_dlp/compat/asyncio to the list of dirs put in the zip file.

Should yt_dlp/extractor/anvato_token_generator go on that list, too?

Is there some history / explanation to go with the "touch -t 200001010101"
command?  For that and the zip command, I had to add another level of
search for .py files: yt_dlp/*/*/*.py
I purposefully kept this patch to the minimum, not changing any style.
E.g., in that "cp -pPR" command, the -R part seems useless and confusing.

### Verbose log

```shell
$ yt-dlp -f 22 https://www.youtube.com/watch?v=2jc1Gw-JP8g
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/larry/bin/yt-dlp/__main__.py", line 13, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/home/larry/bin/yt-dlp/yt_dlp/__init__.py", line 12, in <module>
ModuleNotFoundError: No module named 'yt_dlp.compat'
```

**Comment by ldoolitt** [comment] 2022-04-19 05:48
Patch attached here, I hope
[install1.txt](https://github.com/yt-dlp/yt-dlp/files/8510185/install1.txt)

**Comment by pukkandan** [comment] 2022-04-19 09:22
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3467

**Closed by pukkandan** 2022-04-19 09:22 UTC
Labels: bug, triage
