### ISSUE TITLE
Download from https://www.pbs.org not working: ERROR: An extractor error has occurred. (caused by KeyError('title'))

### ISSUE THREAD

**Issue by noybman** [yt-dlp/yt-dlp#9397] opened 2024-03-09 01:49 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

use yt-dlp with the URL "https://www.pbs.org/wgbh/nova/video/nova-wonders-what-are-animals-saying/"
It returns the following error: ERROR: An extractor error has occurred. (caused by KeyError('title'))
I am not on a VPN, the video plays, I don't even have a PBS account.

Note: as of my report, there were 5 very closely related existing bugs of the same Extractor error with key:title. etc...
https://github.com/yt-dlp/yt-dlp/issues/7139
https://github.com/yt-dlp/yt-dlp/issues/3879
https://github.com/yt-dlp/yt-dlp/issues/2606
https://github.com/yt-dlp/yt-dlp/issues/3711

These either did not apply in this case, or trying the switches did not help.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--update-to', 'nightly', '--no-check-certificate']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error utf-8, screen cp1252 (No VT)
[debug] yt-dlp version nightly@2024.03.08.232718 from yt-dlp/yt-dlp-nightly-builds [f4f9f6d00] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev, rtmpdump 2.3
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1836 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
yt-dlp is up to date (nightly@2024.03.08.232718 from yt-dlp/yt-dlp-nightly-builds)

[pbs] Downloading JSON metadata
[pbs] Extracting URL: https://www.pbs.org/wgbh/nova/video/nova-wonders-what-are-animals-saying/
[pbs] nova-wonders-what-are-animals-saying: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: An extractor error has occurred. (caused by KeyError('title')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment] 2024-03-09 16:05
Duplicate of #2606

**Closed by bashonly** 2024-03-09 16:05 UTC
Labels: site-bug, triage
