### ISSUE TITLE
Tele 5 download not working

### ISSUE THREAD

**Issue by arminfuerst** [yt-dlp/yt-dlp#2807] opened 2022-02-16 22:38 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Description

Tele 5 seems to have redesigned the mediathek.

### Verbose log

```shell
[debug] Command-line config: ['--write-thumbnail', '--write-description', '-vU', 'https://tele5.de/mediathek/relic-hunter-die-schatzjaegerin/der-millionen-dollar-handschuh/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-11-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.4 (setts,fdk), ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {'https': 'http://xxxx:yyyy@my.server:9999'}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] Using fake IP 53.29.73.43 (DE) as X-Forwarded-For
[debug] [Tele5] Extracting URL: https://tele5.de/mediathek/relic-hunter-die-schatzjaegerin/der-millionen-dollar-handschuh/
[Tele5] der-millionen-dollar-handschuh: Downloading webpage
ERROR: [Tele5] der-millionen-dollar-handschuh: Unable to extract jwplatform id; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/tele5.py", line 102, in _real_extract
    jwplatform_id = extract_id(JWPLATFORM_ID_RE, 'jwplatform id')
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/tele5.py", line 91, in extract_id
    return self._html_search_regex(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1195, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by dirkf** [comment] 2022-02-17 01:01
Good news: fixed in yt-dl PR https://github.com/ytdl-org/youtube-dl/pull/30532, which should transfer directly to yt-dlp.

Bad news: `ERROR: DRM protected (caused by ExtractorError(u'Missing deviceId in context',))`

Can you play this in the browser with DRM disabled?

**Comment by arminfuerst** [comment] 2022-02-17 09:06
> Good news: fixed in yt-dl PR [ytdl-org/youtube-dl#30532](https://github.com/ytdl-org/youtube-dl/pull/30532), which should transfer directly to yt-dlp.
> 
> Bad news: `ERROR: DRM protected (caused by ExtractorError(u'Missing deviceId in context',))`
> 
> Can you play this in the browser with DRM disabled?

You are right, it's not working without DSM - too bad :(

**Comment by uahim** [comment] 2022-03-02 22:33
@dirkf @arminfuerst actually, after a quick check, half of the titles currently online are offered without drm so your fix/pull request comes in handy. thank you.

(a little shameless self-promotion: for the titles that do require drm, I created a dirty little user javascript + user css that makes the new page less annoying: https://greasyfork.org/en/scripts/440645-tele5-video )

**Comment by dirkf** [comment] 2022-03-02 23:36
Some content producers can't get them enough of that tasty DRM. The Mouse likes it more than chocolate, which I hear is preferred to the traditional cheese.

But locally produced shows may not be affected so much.

**Comment by pukkandan** [comment] 2022-03-04 20:58
50e93e03a7ca6ae35a319ea310104f7d6d91eee3

**Closed by pukkandan** 2022-03-04 20:58 UTC
Labels: site-bug, solved-upstream
