### ISSUE TITLE
Can't download from Facebook because of old python version 

### ISSUE THREAD

**Issue by Rahumi-f** [yt-dlp/yt-dlp#11184] opened 2024-10-07 06:21 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Iraq

### Provide a description that is worded well enough to be understood

App version: 1.13.0 (11302)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.10.01.232843

URL: https://www.facebook.com/share/r/LSeCnUJM3wi1r7TZ/
Deprecated Feature: Support for Python version 3.8 has been deprecated. Please update to Python 3.9 or above
ERROR: [facebook] 8299614263441148: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I used the seal app on Android
```

**Comment by grqz** [comment] 2024-10-07 06:28
that's just a deprecation warning and should not cause the issue. see https://github.com/JunkFood02/Seal/issues/1729
duplicate of #4311

**Comment by seproDev** [comment] 2024-10-07 09:02
grqz is correct. In addition the facebook link leads to a instagram reel which is a duplicate of #11151

**Closed by seproDev** 2024-10-07 09:02 UTC
Labels: invalid, site:facebook, site:instagram
