### ISSUE TITLE
FaceBook links with multiple videos are not downloadable

### ISSUE THREAD

**Issue by lyves352** [yt-dlp/yt-dlp#11270] opened 2024-10-17 09:52 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Singapore

### Example URLs

https://www.facebook.com/stories/1135565196870075/UzpfSVNDOjM3MzQ3MjcyMDY3ODgxNzE=/?view_single=1

### Provide a description that is worded well enough to be understood

The link contains multiple videos, the real video link can be found in the html, you can manually copy the MP4 link in the html for download.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.facebook.com/stories/1135565196870075/UzpfSVNDOjM3MzQ3MjcyMDY3ODgxNzE=/?view_single=1', '-vU']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.0.3 (fdk,setts), ffprobe 5.0.3
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890', 'ftp': 'http://127.0.0.1:7890'}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.07 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.facebook.com/stories/1135565196870075/UzpfSVNDOjM3MzQ3MjcyMDY3ODgxNzE=/?view_single=1
[generic] ?view_single=1: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fstories%2F1135565196870075%2FUzpfSVNDOjM3MzQ3MjcyMDY3ODgxNzE%3D%2F%3Fview_single%3D1
[generic] Extracting URL: https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fstories%2F1135565196870075%2FUzpfSVNDOjM3MzQ3MjcyMDY3ODgxNzE%3D%2F%3Fview_single%3D1
[generic] login.php?next=https://www.facebook: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] login.php?next=https://www.facebook: Extracting information
[debug] Looking for embeds
[redirect] Following redirect to https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fstories%2F1135565196870075%2FUzpfSVNDOjM3MzQ3MjcyMDY3ODgxNzE%3D%2F%3Fview_single%3D1&_fb_noscript=1
[generic] Extracting URL: https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fstories%2F1135565196870075%2FUzpfSVNDOjM3MzQ3MjcyMDY3ODgxNzE%3D%2F%3Fview_single%3D1&_fb_noscript=1
[generic] login.php?next=https://www.facebook: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] login.php?next=https://www.facebook: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fstories%2F1135565196870075%2FUzpfSVNDOjM3MzQ3MjcyMDY3ODgxNzE%3D%2F%3Fview_single%3D1&_fb_noscript=1
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\generic.py", line 2526, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fstories%2F1135565196870075%2FUzpfSVNDOjM3MzQ3MjcyMDY3ODgxNzE%3D%2F%3Fview_single%3D1&_fb_noscript=1
```

**Comment by seproDev** [comment] 2024-10-17 10:26
I can not view the URL without signing in. Can you? If not you will need to pass cookies.

**Comment by bashonly** [comment] 2024-10-17 10:31
Duplicate of #5763

**Closed** 2024-10-17 10:31 UTC
Labels: duplicate, site-enhancement, site:facebook

**Comment by AlizerUncaged** [comment] 2024-10-20 10:10
> I can not view the URL without signing in. Can you? If not you will need to pass cookies.

Still does not work, I have passed `--cookies-from-browser firefox` it falls back to generic extractor and eventually fails.

**Comment by bashonly** [comment] 2024-10-20 15:57
that issue is being tracked in #5763 as mentioned above
