### ISSUE TITLE
[REQ] iq.com (from iqiyi.com)

### ISSUE THREAD

**Issue by jazz1611** [yt-dlp/yt-dlp#2131] opened 2021-12-27 07:28 UTC
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://www.iq.com/?lang=en_us
https://www.iq.com/album/bad-and-crazy-2021-1gavr9ryfjl?lang=en_us
https://www.iq.com/play/bad-and-crazy-episode-1-1fj6iypksgg?lang=en_us

### Description

Hello,

Can you add support for the site iq.com? it come from iqiyi.com. Also it support VIP account too. Thank you.

Regards,

### Verbose log

```shell
C:\Users\Administrator>yt-dlp -Uv "https://www.iq.com/play/bad-and-crazy-episode-1-1fj6iypksgg?lang=en_us"
[debug] Command-line config: ['-Uv', 'https://www.iq.com/play/bad-and-crazy-episode-1-1fj6iypksgg?lang=en_us']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: https://www.iq.com/play/bad-and-crazy-episode-1-1fj6iypksgg?lang=en_us
[generic] bad-and-crazy-episode-1-1fj6iypksgg?lang=en_us: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] bad-and-crazy-episode-1-1fj6iypksgg?lang=en_us: Downloading webpage
[generic] bad-and-crazy-episode-1-1fj6iypksgg?lang=en_us: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.iq.com/play/bad-and-crazy-episode-1-1fj6iypksgg?lang=en_us
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1423, in __extract_info
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\generic.py", line 3829, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.iq.com/play/bad-and-crazy-episode-1-1fj6iypksgg?lang=en_us
```

**Comment by MinePlayersPE** [comment] 2021-12-27 07:30
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/704

**Closed** 2021-12-27 10:33 UTC
Labels: site-request, triage
