### ISSUE TITLE
Many alarm bell events in iTerm2

### ISSUE THREAD

**Issue by dimitarvp** [yt-dlp/yt-dlp#1887] opened 2021-12-04 22:54 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When not specifying an external downloader, the downloading phase makes my iTerm2 terminal issue hundreds of bell events. I am on latest macOS.

Tried `ssh`-ing into a Linux box through iTerm2 and did the same -- same problem.

Alacritty, both locally and when `ssh`-ed in the Linux box didn't do the same. It did seem to show double progress bar however (which was corrected to a single line of output on download completion).

While the process was working on iTerm2 I could see some of the special shell sequences (f.ex. download timing: `1;37m00:00`). Looked through iTerm2 options and couldn't see anything different from before. I believe the problem got introduced in the latest release because I am almost sure it wasn't acting like that a week or two before.

Anything obviously dumb that I am doing?

### Verbose log

```shell
yt-dlp -Uv --restrict-filenames --output '%(title)s.%(ext)s' --ignore-errors --embed-subs --all-subs --format 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' --embed-thumbnail --audio-quality 0 --add-metadata --xattrs --xattr-set-filesize --prefer-free-formats --geo-bypass --no-mark-watched --console-title --http-chunk-size 500K --no-warnings https://www.youtube.com/watch\?v\=PWwvR6cSH4o
[debug] Command-line config: ['-Uv', '--restrict-filenames', '--output', '%(title)s.%(ext)s', '--ignore-errors', '--embed-subs', '--all-subs', '--format', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--embed-thumbnail', '--audio-quality', '0', '--add-metadata', '--xattrs', '--xattr-set-filesize', '--prefer-free-formats', '--geo-bypass', '--no-mark-watched', '--console-title', '--http-chunk-size', '500K', '--no-warnings', 'https://www.youtube.com/watch?v=PWwvR6cSH4o']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (zip)
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.15.2-2-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Crypto, keyring, sqlite
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=PWwvR6cSH4o
[youtube] PWwvR6cSH4o: Downloading webpage
[youtube] PWwvR6cSH4o: Downloading android player API JSON
[debug] Loading youtube-nsig.54223c10 from cache
[debug] [youtube] Decrypted nsig qZGKFc9cHBF45VBZiI => SLUILp6wywCRqA
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: en
[info] PWwvR6cSH4o: Downloading 1 format(s): 299+140
[info] Writing video subtitles to: Dad_Jokes_with_Kratos.en.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=PWwvR6cSH4o&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xftt%2Cxctw&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1638683047&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxoaf&signature=9D85A10882B6A0BD77F1E90058233F1FCC29254B.D215812F9523C3C4239CA4CA7AE20EF108441ABE&key=yt8&lang=en&fmt=vtt"
[download] Unable to resume
[download] Destination: Dad_Jokes_with_Kratos.en.vtt
[download] 100% of 1.50KiB in 00:00                                      1;37m00:00
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: Dad_Jokes_with_Kratos.webp
[debug] Invoking downloader on "https://r2---sn-puqoxu-nv4l.googlevideo.com/videoplayback?expire=1638679448&ei=OO-rYaDoAuXLx_AP1KyhuAQ&ip=94.155.138.21&id=o-ANMdH85rVqa9yogsSW7B6v4gqu5PpXPY3gyDGKDnKtu7&itag=299&source=youtube&requiressl=yes&mh=-t&mm=31%2C29&mn=sn-puqoxu-nv4l%2Csn-nv47lnly&ms=au%2Crdu&mv=m&mvi=2&pl=24&initcwndbps=1337500&vprv=1&mime=video%2Fmp4&gir=yes&clen=48348472&dur=125.366&lmt=1577226794882404&mt=1638657417&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgGW9V2uxDpzfCkeIJ3vPQ1fpfZkUfy1bKWxerU9iGtyQCICthZxFxhIcCHdGJ7-rfb268yTXx8oZt5cYB4KuQqLva&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAO4ta51Rt4lF-Kt-Q_u--U9N3jVn7ZrJaRpVQyd0cbV-AiEAw-vbOO26VJ9QB8_W9h7ZWEg6DCCorTTXuy7jQjkmqSI%3D"
[download] Destination: Dad_Jokes_with_Kratos.f299.mp4
[download] 100% of 46.11MiB in 00:03                                     1;37m00:03
[debug] Invoking downloader on "https://r2---sn-puqoxu-nv4l.googlevideo.com/videoplayback?expire=1638679448&ei=OO-rYaDoAuXLx_AP1KyhuAQ&ip=94.155.138.21&id=o-ANMdH85rVqa9yogsSW7B6v4gqu5PpXPY3gyDGKDnKtu7&itag=140&source=youtube&requiressl=yes&mh=-t&mm=31%2C29&mn=sn-puqoxu-nv4l%2Csn-nv47lnly&ms=au%2Crdu&mv=m&mvi=2&pl=24&initcwndbps=1337500&vprv=1&mime=audio%2Fmp4&gir=yes&clen=2031026&dur=125.434&lmt=1577225963447294&mt=1638657417&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJwoWAmMhm9ceJEN5Ob3JCs9eM-sGqqEOtYSjws6OqfoAiEA-RH3MtUiYB1fgbLwiSvKXWUFnQBCxe2C4Nl6HyxkWoc%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAO4ta51Rt4lF-Kt-Q_u--U9N3jVn7ZrJaRpVQyd0cbV-AiEAw-vbOO26VJ9QB8_W9h7ZWEg6DCCorTTXuy7jQjkmqSI%3D"
[download] Destination: Dad_Jokes_with_Kratos.f140.m4a
[download] 100% of 1.94MiB in 00:00                                     1;37m00:00
[Merger] Merging formats into "Dad_Jokes_with_Kratos.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:Dad_Jokes_with_Kratos.f299.mp4 -i file:Dad_Jokes_with_Kratos.f140.m4a -c copy -map 0:v:0 -map 1:a:0 file:Dad_Jokes_with_Kratos.temp.mp4
Deleting original file Dad_Jokes_with_Kratos.f299.mp4 (pass -k to keep)
Deleting original file Dad_Jokes_with_Kratos.f140.m4a (pass -k to keep)
[EmbedSubtitle] Embedding subtitles in "Dad_Jokes_with_Kratos.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:Dad_Jokes_with_Kratos.mp4 -i file:Dad_Jokes_with_Kratos.en.vtt -c copy -map 0 -dn -map -0:s -map -0:d -c:s mov_text -map 1:0 -metadata:s:s:0 language=eng -metadata:s:s:0 handler_name=English -metadata:s:s:0 title=English file:Dad_Jokes_with_Kratos.temp.mp4
Deleting original file Dad_Jokes_with_Kratos.en.vtt (pass -k to keep)
[Metadata] Adding metadata to "Dad_Jokes_with_Kratos.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:Dad_Jokes_with_Kratos.mp4 -map 0 -dn -c copy -metadata 'title=Dad Jokes with Kratos' -metadata date=20180508 -metadata 'description=Kratos may be a dad now, but his journey to fatherhood won'"'"'t be complete until he delivers some truly awful dad jokes. We teamed up with Kratos voice actor Christopher Judge to make our daddy dreams a reality.

SUBSCRIBE for more videos! http://bit.ly/2B7gM6M

Like us on Facebook: http://bit.ly/PolygonFB
Follow us on Twitter: http://bit.ly/PolygonTwitter
Follow us on Instagram: http://bit.ly/PolygonInsta
And for more great news and coverage, check out: www.polygon.com

Polygon is an entertainment website founded in 2012 in partnership with Vox Media. Our mission is to cover not only games but the artists who make them, the fans who love them, and the culture surrounding them.' -metadata 'synopsis=Kratos may be a dad now, but his journey to fatherhood won'"'"'t be complete until he delivers some truly awful dad jokes. We teamed up with Kratos voice actor Christopher Judge to make our daddy dreams a reality.

SUBSCRIBE for more videos! http://bit.ly/2B7gM6M

Like us on Facebook: http://bit.ly/PolygonFB
Follow us on Twitter: http://bit.ly/PolygonTwitter
Follow us on Instagram: http://bit.ly/PolygonInsta
And for more great news and coverage, check out: www.polygon.com

Polygon is an entertainment website founded in 2012 in partnership with Vox Media. Our mission is to cover not only games but the artists who make them, the fans who love them, and the culture surrounding them.' -metadata 'purl=https://www.youtube.com/watch?v=PWwvR6cSH4o' -metadata 'comment=https://www.youtube.com/watch?v=PWwvR6cSH4o' -metadata artist=Polygon file:Dad_Jokes_with_Kratos.temp.mp4
[ThumbnailsConvertor] Converting thumbnail "Dad_Jokes_with_Kratos.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i file:Dad_Jokes_with_Kratos.webp file:Dad_Jokes_with_Kratos.png
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json file:Dad_Jokes_with_Kratos.mp4
[EmbedThumbnail] ffmpeg: Adding thumbnail to "Dad_Jokes_with_Kratos.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:Dad_Jokes_with_Kratos.mp4 -i file:Dad_Jokes_with_Kratos.png -c copy -map 0 -dn -map 1 -disposition:3 attached_pic file:Dad_Jokes_with_Kratos.temp.mp4
Deleting original file Dad_Jokes_with_Kratos.png (pass -k to keep)
Deleting original file Dad_Jokes_with_Kratos.webp (pass -k to keep)
[XAttrMetadata] Writing metadata to file's xattrs
```

**Comment by pukkandan** [comment] 2021-12-05 10:06
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1859, fixed in https://github.com/yt-dlp/yt-dlp/commit/3efb96a6d1e364e7d4906ca786be21e94e1cf472

**Closed** 2021-12-05 10:06 UTC
Labels: bug, duplicate
