### ISSUE TITLE
Tele5

### ISSUE THREAD

**Issue by usergittest123** [yt-dlp/yt-dlp#4637] opened 2022-08-12 04:59 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

2 films at one url
only one can be downloaded
example:
https://tele5.de/mediathek/merlin-2-der-letzte-zauberer/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://tele5.de/mediathek/merlin-2-der-letzte-zauberer/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2021-09-30-git-3ee4502753-full_build-www.gyan.dev (setts), ffprobe 2021-09-30-git-3ee4502753-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] Using fake IP 53.83.79.5 (DE) as X-Forwarded-For
[debug] [Tele5] Extracting URL: https://tele5.de/mediathek/merlin-2-der-letzte-zauberer/
[Tele5] merlin-2-der-letzte-zauberer: Downloading webpage
[Tele5] 2913986: Downloading token
[Tele5] 2913986: Downloading JSON metadata
[Tele5] 2913986: Downloading JSON metadata
[Tele5] 2913986: Downloading MPD manifest
[Tele5] 2913986: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), channels, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2913986: Downloading 1 format(s): hls-6550+dash-995756510
[debug] Invoking hlsnative downloader on "https://dplaynordics-vod-07.akamaized.net/dplaydni/243110/0/hls/10783500004/exp=1660366689~acl=%2f*~data=hdntl~hmac=2070aa7996b22730d48dc54c82dd178b3dca55ad60bc38e27f02df97448e3388/1024744653-prog_index.m3u8?hdntl=exp=1660366689~acl=/*~data=hdntl~hmac=2070aa7996b22730d48dc54c82dd178b3dca55ad60bc38e27f02df97448e3388&version_hash=21e895c0"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 530
[download] Destination: Merlin 2 - Der letzte Zauberer - Teil 1 [2913986].fhls-6550.mp4
[debug] File locking is not supported. Proceeding without locking
```

**Comment by HobbyistDev** [comment] 2022-08-12 05:38
Duplicate of #3051

**Closed** 2022-08-12 07:12 UTC
Labels: site-bug, triage
