### ISSUE TITLE
[TF1][WAT.TV] Erreur dans le delivery

### ISSUE THREAD

**Issue by D84web** [yt-dlp/yt-dlp#8855] opened 2023-12-26 11:29 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

yt-dlp is unable to extract videos from TF1.fr

I have no idea what to do. I am not logged on to view this video.

Thanks for the help.

[Sorry for my poor English]

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.tf1.fr/tf1/telefilms-de-noel/videos/recherche-fiance-pour-noel-56520173.html

[debug] Command-line config: ['-vU', 'https://www.tf1.fr/tf1/telefilms-de-noel/videos/recherche-fiance-pour-noel-56520173.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-169-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2019.11.28, mutagen-1.47.0, requests-2.31.0, secretstorage-2.3.1, sqlite3-3.31.1, urllib3-2.1.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[TF1] Extracting URL: https://www.tf1.fr/tf1/telefilms-de-noel/videos/recherche-fiance-pour-noel-56520173.html
[TF1] recherche-fiance-pour-noel-56520173: Downloading JSON metadata
[wat.tv] Extracting URL: wat:14047175
[wat.tv] 14047175: Downloading JSON metadata
ERROR: [wat.tv] 14047175: Erreur dans le delivery
  File "/home/nicolas/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/home/nicolas/.local/lib/python3.8/site-packages/yt_dlp/extractor/wat.py", line 76, in _real_extract
    raise ExtractorError(error_desc, expected=True)
```

**Comment by bashonly** [comment] 2023-12-26 11:35
Duplicate of #8191

**Closed by bashonly** 2023-12-26 11:35 UTC
Labels: site-bug, triage
