### ISSUE TITLE
XVideos HTTP 404 when downloading m3u8 information

### ISSUE THREAD

**Issue by jsiz** [yt-dlp/yt-dlp#1823] opened 2021-11-28 11:47 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Download from XVideo using the latest patch works, but some url doesn't. Like this one in particular.

### Verbose log

```shell
[debug] Command-line config: ['-o', './video/%(title)s.%(ext)s', 'http://www.xvideos.com/video65982001/what_s_her_name', '--retries', 'infinite', '--fragment-retries', 'infinite', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Lazy loading extractors is disabled
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.19.128-microsoft-standard-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [XVideos] Extracting URL: http://www.xvideos.com/video65982001/what_s_her_name
[XVideos] 65982001: Downloading webpage
[XVideos] 65982001: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 65982001: Downloading 1 format(s): hls-720p
[debug] Invoking downloader on "https://hls-hw.xvideos-cdn.com/videos_new/hls/16/af/cf/16afcfef69dcdd74d15d36d570540b5a/hls-720p-64652.m3u8?e=1638110135&l=0&h=e190584c5702efab90109c8c36a8cf40"
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/yt_dlp/YoutubeDL.py", line 2876, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/local/lib/python3.6/dist-packages/yt_dlp/YoutubeDL.py", line 2597, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/lib/python3.6/dist-packages/yt_dlp/downloader/common.py", line 399, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.6/dist-packages/yt_dlp/downloader/hls.py", line 68, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
  File "/usr/local/lib/python3.6/dist-packages/yt_dlp/YoutubeDL.py", line 3319, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by pukkandan** [comment] 2021-11-28 12:27
Duplicate of #1811

**Comment by sergeevabc** [comment] 2021-12-02 10:25
Does not work for a few weeks, a fix would be appreciated.

**Comment by MinePlayersPE** [comment] 2021-12-05 11:20
`--check-formats` works as intended (skips the erroring formats)
And this seems to be a server issue too, as specifically setting 720p on that video also results in an loading error on the site

**Comment by sergeevabc** [comment] 2021-12-06 09:01
@MinePlayersPE, ```--check-formats``` does not work on my end, e.g.
```console
$ yt-dlp --check-formats --verbose https://www.xvideos.com/video27173585/pornvideosdaily.top_-_ariana_marie_lets_you_cum_on_her_[debug] Command-line config: ['--check-formats', '--verbose', 'https://www.xvideos.com/video27173585/pornvideosdaily.top_-_ariana_marie_lets_you_cum_on_her_lovely_face']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1251
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg n4.4-19-g8d172d9409 (setts), ffprobe n4.3.2-ffmpeg-windows-build-helpers
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [XVideos] Extracting URL: https://www.xvideos.com/video27173585/pornvideosdaily.top_-_ariana_marie_lets_you_cum_on_her_lovely_face [XVideos] 27173585: Downloading webpage
ERROR: [XVideos] 27173585: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 713, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3295, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

**Comment by pukkandan** [comment] 2021-12-06 09:02
@sergeevabc Update your yt-dlp

**Comment by MinePlayersPE** [comment] 2021-12-06 09:03
@sergeevabc This issue is not the same as https://github.com/yt-dlp/yt-dlp/issues/1788

**Comment by pukkandan** [comment] 2021-12-06 09:04
@MinePlayersPE  Can you confirm that the issue exists only for formats that are broken in browser? If so, ig this issue can be closed

**Comment by serveral1** [comment] 2021-12-06 17:06
can confirm that updating to the latest version fixes this issue

**Closed** 2022-01-01 06:12 UTC
Labels: NSFW, site-bug

**Comment by dl21g5** [comment] 2022-01-08 23:49
@pukkandan 

Different issue from the m3u8 404:

```ERROR: Giving up after 10 fragment retries```

```
	C:\Users\smiggy-smoll>yt-dlp --verbose https://www.xvideos.com/video65513071/let_s_put_a_finger_in_her_pussy_
	[debug] Command-line config: ['--verbose', 'https://www.xvideos.com/video65513071/let_s_put_a_finger_in_her_pussy_']
	[debug] User config file: C:\Users\smiggy-smoll\AppData\Roaming\yt-dlp\config.txt
	[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
	[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
	[debug] Python version 3.8.10 (CPython 64bit)
	[debug] exe versions: ffmpeg 4.4-essentials_build-www.gyan.dev (setts), ffprobe 4.4-essentials_build-www.gyan.dev
	[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
	[debug] Proxy map: {}
	[debug] [XVideos] Extracting URL: https://www.xvideos.com/video65513071/let_s_put_a_finger_in_her_pussy_
	[XVideos] 65513071: Downloading webpage
	[XVideos] 65513071: Downloading m3u8 information
	[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_a
	pprox, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
	[debug] Default format spec: bestvideo*+bestaudio/best
	[info] 65513071: Downloading 1 format(s): hls-1080p
	[debug] Invoking downloader on "https://cdn77-vid.xvideos-cdn.com/xSPg5XZJHAp7u8iaUw4fLg==,1641696028/videos_new/hls/ed/
	ff/f0/edfff0551ec19f8ade3deee6ec3df776/hls-1080p-77517.m3u8"
	[hlsnative] Downloading m3u8 manifest
	[hlsnative] Total fragments: 55
	[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10) ...
	[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10) ...
	[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10) ...
	[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10) ...
	[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10) ...
	[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10) ...
	[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10) ...
	[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10) ...
	[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10) ...
	[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10) ...
	ERROR: Giving up after 10 fragment retries
	  File "yt_dlp\__main__.py", line 19, in <module>
	  File "yt_dlp\__init__.py", line 842, in main
	  File "yt_dlp\__init__.py", line 832, in _real_main
	  File "yt_dlp\YoutubeDL.py", line 3113, in download
	  File "yt_dlp\YoutubeDL.py", line 3086, in wrapper
	  File "yt_dlp\YoutubeDL.py", line 1344, in extract_info
	  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
	  File "yt_dlp\YoutubeDL.py", line 1437, in __extract_info
	  File "yt_dlp\YoutubeDL.py", line 1489, in process_ie_result
	  File "yt_dlp\YoutubeDL.py", line 2551, in process_video_result
	  File "yt_dlp\YoutubeDL.py", line 2991, in process_info
	  File "yt_dlp\YoutubeDL.py", line 2701, in dl
	  File "yt_dlp\downloader\common.py", line 440, in download
	  File "yt_dlp\downloader\hls.py", line 358, in real_download
	  File "yt_dlp\downloader\fragment.py", line 515, in download_and_append_fragments
	  File "yt_dlp\downloader\fragment.py", line 473, in download_fragment
	  File "yt_dlp\downloader\common.py", line 177, in report_error
	  File "yt_dlp\YoutubeDL.py", line 912, in report_error
	  File "yt_dlp\YoutubeDL.py", line 842, in trouble

	ERROR: fragment 1 not found, unable to continue
	  File "yt_dlp\__main__.py", line 19, in <module>
	  File "yt_dlp\__init__.py", line 842, in main
	  File "yt_dlp\__init__.py", line 832, in _real_main
	  File "yt_dlp\YoutubeDL.py", line 3113, in download
	  File "yt_dlp\YoutubeDL.py", line 3086, in wrapper
	  File "yt_dlp\YoutubeDL.py", line 1344, in extract_info
	  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
	  File "yt_dlp\YoutubeDL.py", line 1437, in __extract_info
	  File "yt_dlp\YoutubeDL.py", line 1489, in process_ie_result
	  File "yt_dlp\YoutubeDL.py", line 2551, in process_video_result
	  File "yt_dlp\YoutubeDL.py", line 2991, in process_info
	  File "yt_dlp\YoutubeDL.py", line 2701, in dl
	  File "yt_dlp\downloader\common.py", line 440, in download
	  File "yt_dlp\downloader\hls.py", line 358, in real_download
	  File "yt_dlp\downloader\fragment.py", line 516, in download_and_append_fragments
	  File "yt_dlp\downloader\fragment.py", line 484, in append_fragment
	  File "yt_dlp\downloader\common.py", line 177, in report_error
	  File "yt_dlp\YoutubeDL.py", line 912, in report_error
	  File "yt_dlp\YoutubeDL.py", line 842, in trouble
```

**Comment by MinePlayersPE** [comment] 2022-01-09 11:45
@dl21g5 `--check-formats` works, right?

**Comment by dl21g5** [comment] 2022-01-09 12:50
@MinePlayersPE That fixed it. Didn't know about that command. It was automatically downloading the 1080p stream even though it was unavailable. Thanks.
