### ISSUE TITLE
possible to remove temp folder extractions for binaries?

### ISSUE THREAD

**Issue by ask2018** [yt-dlp/yt-dlp#1024] opened 2021-09-18 19:44 UTC
## Checklist

- [ X] I'm asking a question
- [ X I've looked through the README and FAQ for similar questions
- [ X] I've searched the bugtracker for similar questions including closed ones

## Question

It is possible to run  yt-dlp without extracting binaries inside temp folder on Windows (in my case it was _MEI101362 folder and files inside) like it was on original yt-dl?
The problem is each time I'm trying to download something, it extracts some binaries inside temp folder and those binaries needs network access so my firewall always asking if I want to allow them network access or not and I cannot setup rules for temp files auto deleted after the program is closed.

**Comment by nyuszika7h** [comment] 2021-09-18 20:24
Duplicate of #661, #705 and #890

**Comment by ask2018** [comment] 2021-09-18 22:14
Sorry missed those other issues, but my problem is little bit different. I don't have problem with those files on disk, but I need them in static folder and keep them there, so I can setup the firewall rules for them. This way I cannot and it keeps asking and that's really annoying and also not possible to automate any download process, because it's always waiting for permissions.

**Comment by pukkandan** [comment] 2021-09-19 13:19
It seems your issue is solvable without switching away from pyinstaller - https://pyinstaller.readthedocs.io/en/stable/usage.html#defining-the-extraction-location

**Comment by ask2018** [comment] 2021-09-19 14:06
Would be cool. But I'm not sure about it from the link you provided. If I understand it correctly, that will just change the location of temp folder used. But does it also disable the random name of the folder created inside that temp folder? And does it also disable auto deleting the files after job is done?
The problem is I need static path and keep the files there, else I cannot setup the rules. Well I can setup the rules for static path without keeping the files there, but each time I will cleanup the rules to remove non existing binaries from it, it will purge it and I need to create the rules again.

**Comment by ask2018** [comment] 2021-09-19 14:22
Also solution where it's not all packed inside single exe would be good for me. I don't mind how many files are there, I just need them on static places without this temp unpacking inside random folder names. So in case it is possible somehow easily make an "unpacked" version, where not all files are in single exe and where nothing unpacks inside random folders, then such solution would be also good for me.

**Comment by pukkandan** [comment] 2021-09-19 14:26
compiling without `--one-file` is easy. But making the auto-updater work with that is going to take some work. Can't u just install from pip btw?

**Comment by ask2018** [comment] 2021-09-19 14:30
Personally I don't care about auto updater, I don't use auto updaters in general and I'm updating manually anyway if needed.
Well I can install from pip, but I've been using some GUI tools and I'm not sure if there is some compatible with that. Will check it out.

**Comment by ask2018** [comment] 2021-09-19 14:37
So looks like the GUI works with the pip installed one - at least after the quick test I did, so I guess I can accept this as solution for my problem. Thank you.

**Comment by pukkandan** [comment] 2021-09-19 14:39
Since so many people are asking for it, I'll release the --onedir version anyway. But don't expect updates to be added for it

**Comment by ask2018** [comment] 2021-09-19 14:41
Ok thank you.

**Comment by pukkandan** [comment] 2021-09-19 18:02
#880 will add a zip with `--onedir`. Here's a test release: https://github.com/pukkandan/yt-dlp-dev/releases/tag/2021.09.19.2

**Comment by ask2018** [comment] 2021-09-19 18:56
Test release works fine for me and it fully solves my firewall rules issue. Thank you.

**Closed** 2021-09-24 01:01 UTC
Labels: enhancement
