### ISSUE TITLE
[NeteaseMusic] Extract flac audio

### ISSUE THREAD

**Issue by hafeoz** [yt-dlp/yt-dlp#9196] opened 2024-02-12 19:17 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Example URLs

https://music.163.com/#/song?id=1952853555

### Provide a description that is worded well enough to be understood

Netease music extractor is unable to extract high quality audio from API.

The reason (AFAIK) is that the extractor [searches for specific media IDs](https://github.com/yt-dlp/yt-dlp/blob/882e3b753c79c7799ce135c3a5edb72494b576af/yt_dlp/extractor/neteasemusic.py#L25), which does not cover all possible IDs.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--list-formats', '--cookies', '/home/hafeoz/.ytdlp-cookies.txt', '-vU', 'https://music.163.com/#/song?id=1952853555']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.7-arch3-1-x86_64-with-glibc2.38 (OpenSSL 3.2.0 23 Nov 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[netease:song] Extracting URL: https://music.163.com/#/song?id=1952853555
[netease:song] 1952853555: Downloading song info
[netease:song] 1952853555: Downloading song URL info: bitrate 128002
[netease:song] 1952853555: Checking song URL
[netease:song] 1952853555: Downloading song URL info: bitrate 192002
[netease:song] 1952853555: Checking song URL
[netease:song] 1952853555: Downloading song URL info: bitrate 320002
[netease:song] 1952853555: Checking song URL
[netease:song] 1952853555: Downloading lyrics data
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 1952853555:
ID     EXT RESOLUTION │ FILESIZE PROTO │ VCODEC  ACODEC   ABR ASR
─────────────────────────────────────────────────────────────────
bMusic mp3 unknown    │  2.93MiB http  │ unknown unknown 128k 48k
mMusic mp3 unknown    │  4.40MiB http  │ unknown unknown 192k 48k
hMusic mp3 unknown    │  7.33MiB http  │ unknown unknown 320k 48k
```

**Comment by timi137137** [comment] 2024-06-23 19:45
**The translator will lose the meaning it was intended to convey, so it will be conveyed directly in the native language.**
**Please forgive me if there is any problem**

通过实验，发现yt-dlp目前使用的接口被升级过，导致出现获取音质缺漏。
目前音质对应如下：
```text
bMusic = 标准
lMusic = 标准，不知道为什么会有两个一样的但这个和另一个标准内容是一模一样的
mMusic = 未知
hMusic = 极高
sqMusic = 无损
hrMusic = Hi-Res
```
以上表格对应歌曲
链接为：https://music.163.com/song?id=2058263030
音质截图为：
![image](https://github.com/yt-dlp/yt-dlp/assets/36812439/ef79a457-96ea-4b8f-8880-55b0cb8af873)

---

根据[Suxiaoqinx](https://github.com/Suxiaoqinx/Netease_url)大佬的项目可以得知，网易云更新了该接口的鉴权方式，旧的鉴权方式就算用SVIP的Cookie也是抓不到需要的内容的。
而在第三方网易云播放器[HyPlayer的代码](https://github.com/HyPlayer/HyPlayer/blob/cd3906803894e3d01867d25f4f90ad9d4b0396a5/HyPlayer/HyPlayControl/HyPlayList.cs#L1085)中也能明显看出，必须要传入确定的音质才能获取到音频文件。
对应音质列表如下：
```cs
"standard" => "标准",
"higher" => "较高",
"exhigh" => "极高",
"lossless" => "无损",
"hires" => "Hi-Res",
"jyeffect" => "高清环绕声",
"sky" => "沉浸环绕声",
"jymaster" => "超清母带",
_ => "在线"
```

总结：如果需要让yt-dlp能正常获取并抓取网易云音乐可能还需要您多费心，您辛苦了

**Comment by hafeoz** [comment] 2024-06-24 19:32
So it seems like there are 2 APIs for fetching music URL: `eapi/song/enhance/player/url`, which `yt-dlp` is currently using, and `eapi/song/enhance/player/url/v1`. The latter one have more quality "levels" and should probably be used instead?

I'm going to tinker a bit to see how the new API work, but I've stopped using Netease a few months ago so I'm unlikely to contribute if the API is more complex than I imagined.

FYI for future developers: the new API I'm talking about can be found [here](https://github.com/HyPlayer/NeteaseCloudMusicAPI/blob/63c7f30975bdf88d19252f3cd1bbad8ea97eb450/NeteaseCloudMusicApi/CloudMusicApiProviders.cs#L789) and [here](https://github.com/Suxiaoqinx/Netease_url/blob/29b47c53372a744184b1d896e656fef5e4a8f9b1/main.py#L114) (found via link provided by @timi137137 above)

@timi137137 我非常粗略的看了一下那两个项目，似乎API变化不大。我打算用新的API试试，但是我现在不用网易云音乐了，所以要是太复杂的话可能就会放弃哈😂

**Comment by timi137137** [comment] 2024-06-25 03:02
> So it seems like there are 2 APIs for fetching music URL: `eapi/song/enhance/player/url`, which `yt-dlp` is currently using, and `eapi/song/enhance/player/url/v1`. The latter one have more quality "levels" and should probably be used instead?
> 
> I'm going to tinker a bit to see how the new API work, but I've stopped using Netease a few months ago so I'm unlikely to contribute if the API is more complex than I imagined.
> 
> FYI for future developers: the new API I'm talking about can be found [here](https://github.com/HyPlayer/NeteaseCloudMusicAPI/blob/63c7f30975bdf88d19252f3cd1bbad8ea97eb450/NeteaseCloudMusicApi/CloudMusicApiProviders.cs#L789) and [here](https://github.com/Suxiaoqinx/Netease_url/blob/29b47c53372a744184b1d896e656fef5e4a8f9b1/main.py#L114) (found via link provided by @timi137137 above)
> 
> @timi137137 我非常粗略的看了一下那两个项目，似乎API变化不大。我打算用新的API试试，但是我现在不用网易云音乐了，所以要是太复杂的话可能就会放弃哈😂

@hafeoz OKOK辛苦你了，主要是yt-dlp的贡献机制我太不熟了

**Comment by pzhlkj6612** [comment] 2024-06-26 13:17
Hi, @timi137137 !

> 主要是yt-dlp的贡献机制我太不熟了
> 
> \[Google translated\] mainly because I am not familiar with the contribution mechanism of yt-dlp

你可以跟随 CONTRIBUTING.md 的“[DEVELOPER INSTRUCTIONS](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)”章节去做提交。你也可以查看那些已被合并的拉取请求以了解其他人是如何制作“信息提取器”的。在 Discord 频道里问编程问题也是受欢迎的。

You can follow the "[DEVELOPER INSTRUCTIONS](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions)" chapter in the CONTRIBUTING.md file to write your commits. You can also check other merged PRs to see how people made "Info Extractors". Asking programming questions in Discord channels is also welcome.

**Closed** 2024-06-27 16:17 UTC
Labels: site-enhancement

**Comment by changjian-k2k** [comment] 2025-03-12 09:14
> So it seems like there are 2 APIs for fetching music URL: `eapi/song/enhance/player/url`, which `yt-dlp` is currently using, and `eapi/song/enhance/player/url/v1`. The latter one have more quality "levels" and should probably be used instead?
> 
> I'm going to tinker a bit to see how the new API work, but I've stopped using Netease a few months ago so I'm unlikely to contribute if the API is more complex than I imagined.
> 
> FYI for future developers: the new API I'm talking about can be found [here](https://github.com/HyPlayer/NeteaseCloudMusicAPI/blob/63c7f30975bdf88d19252f3cd1bbad8ea97eb450/NeteaseCloudMusicApi/CloudMusicApiProviders.cs#L789) and [here](https://github.com/Suxiaoqinx/Netease_url/blob/29b47c53372a744184b1d896e656fef5e4a8f9b1/main.py#L114) (found via link provided by [@timi137137](https://github.com/timi137137) above)
> 
> [@timi137137](https://github.com/timi137137) 我非常粗略的看了一下那两个项目，似乎API变化不大。我打算用新的API试试，但是我现在不用网易云音乐了，所以要是太复杂的话可能就会放弃哈😂

不用网易云音乐的话，其他还有什么高音质的音乐下载平台嘛？
