### ISSUE TITLE
Extract metadata from music.youtube.com

### ISSUE THREAD

**Issue by Rexadev** [yt-dlp/yt-dlp#3822] opened 2022-05-21 09:05 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

1. Explicit Rating "E" in ITUNESADVISORY field
2. Album Name is not copied example - `music.youtube.com/watch?v=J9BQRMBjUOY`
Album there is `Blizzard Of Ozz (40th Anniversary Expanded Edition)`
Now yt-dlp only copies if is available in description of www. subdomain version `www.youtube.com/watch?v=J9BQRMBjUOY`
3.  www. and music. subdomains have different titles example - `www.youtube.com/watch?v=f-e8-DUqt0I` is War Pigs and `music.youtube.com/watch?v=f-e8-DUqt0I` is War Pigs (2009 - Remaster). There should be way if to use whichever is longer.
4.  Save lyrics in LYRICS field from Lyrics tab in music.youtube.com example - `music.youtube.com/watch?v=q4ixeKXJGvo&list=RDAMVMq4ixeKXJGvo`

**Comment by pukkandan** [comment] 2022-05-21 10:24
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/622

**Closed by pukkandan** 2022-05-21 10:24 UTC
Labels: enhancement, triage

**Comment by Rexadev** [comment] 2022-05-21 11:26
@pukkandan not duplicate I have more points
