### ISSUE TITLE
Redbull TV download NOT working

### ISSUE THREAD

**Issue by electrickarl** [yt-dlp/yt-dlp#9416] opened 2024-03-10 20:43 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

ERROR: [RedBull] natural-selection-tour-2024-duels-spencer-obrien-vs-mary-rand: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
sudo apt install yt-dlp
[sudo] password for necromarxist:           
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
yt-dlp is already the newest version (2022.04.08-1).
yt-dlp set to manually installed.
```

**Comment by bashonly** [comment] 2024-03-10 20:55
Duplicate of #9170

> yt-dlp is already the newest version (2022.04.08-1).

Your distro's package repository has a severely outdated version. You should [install yt-dlp by other means](https://github.com/yt-dlp/yt-dlp/wiki/Installation). While this won't fix the RedbullTV issue, it will fix many, many others, and you'll be able to submit a proper bug report next time.

**Closed by bashonly** 2024-03-10 20:55 UTC
Labels: bug, triage
