### ISSUE TITLE
SponsorBlock doesn't work as it should in python code

### ISSUE THREAD

**Issue by Dmitrisv** [yt-dlp/yt-dlp#1555] opened 2021-11-05 11:18 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Sponsorblock didn't fetching segments when i use in postprocessors.

Code:

```
import yt_dlp 

ydl_opts = {
    'format': 'bv*[ext=mp4]+ba*[ext=m4a]',
    'postprocessors': [{
        "key":"SponsorBlock",
        "categories":"all",
    }]}


with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    ydl.download([input("URL: ")])
```

URL example:
https://www.youtube.com/watch?v=54-9xeWLHqQ

### Verbose log

```shell
(idk how to add flag "verbose" in python code)
[youtube] 54-9xeWLHqQ: Downloading webpage
[youtube] 54-9xeWLHqQ: Downloading android player API JSON
[info] 54-9xeWLHqQ: Downloading 1 format(s): 137+140
[download] Destination: ЧТО СТАЛО С ЦЫПЛЕНКОМ РЭМБО В ДЕРЕВНЕ [54-9xeWLHqQ].f137.mp4
[download] 100% of 177.67MiB in 00:17
[download] Destination: ЧТО СТАЛО С ЦЫПЛЕНКОМ РЭМБО В ДЕРЕВНЕ [54-9xeWLHqQ].f140.m4a
[download] 100% of 6.54MiB in 00:00
[Merger] Merging formats into "ЧТО СТАЛО С ЦЫПЛЕНКОМ РЭМБО В ДЕРЕВНЕ [54-9xeWLHqQ].mp4"
Deleting original file ЧТО СТАЛО С ЦЫПЛЕНКОМ РЭМБО В ДЕРЕВНЕ [54-9xeWLHqQ].f137.mp4 (pass -k to keep)
Deleting original file ЧТО СТАЛО С ЦЫПЛЕНКОМ РЭМБО В ДЕРЕВНЕ [54-9xeWLHqQ].f140.m4a (pass -k to keep)
[SponsorBlock] Fetching SponsorBlock segments
[SponsorBlock] No segments were found in the SponsorBlock database
```

**Comment by pukkandan** [comment] 2021-11-05 12:50
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1238

Also, that video doesnt have any segments

> [SponsorBlock] No segments were found in the SponsorBlock database

**Closed by pukkandan** 2021-11-05 12:50 UTC
Labels: bug, triage
