### ISSUE TITLE
Vimeo: yt-dlp not finding source/original format on multiple non-standard URL types

### ISSUE THREAD

**Issue by tometto432** [yt-dlp/yt-dlp#10717] opened 2024-08-11 21:58 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Several Vimeo URL types seem to be failing to find the source/original format.  

Let me preface by saying, this is my first time using GitHub to try to have an issue resolved.  There is a similar issue #9163, and because I didn't want to post a duplicate issue, I posted an update to that existing issue, but several days have gone by and it doesn't seem like anyone has looked at it.  If there was a step I missed in order to highlight that I was updating that the existing issue needed help, please let me know.

I have also updated my Vimeo.py extractor with the piece of code provided by dirkf in issue #9163 to help get the source format (if available) for URLs in the format "https://player.vimeo.com/video/XXXXXX" and have confirmed that it often works, as will be demonstrated in one of the below examples. However, there are still some URL formats that are failing.

- PW protected video, "https://vimeo.com/video/XXXXXX" format URL

Example: https://vimeo.com/video/371764747 (pw: Hambremovie2022)

It seems that most pw-protected videos now use a "https://vimeo.com/video/XXXXXX" format URL, and I do not know of any way to direct them to the normal "https://vimeo.com/XXXXXX" format.

Using this URL format, there is no source format, even when passing cookies.

However, if I reconfigure the URL to the "https://player.vimeo.com/video/XXXXXX" (https://player.vimeo.com/video/371764747) format and pass cookies, yt-dlp will locate the source format (thanks to the code from dirkf).  However, this reconfiguring the URL is not always an possible option, as some videos have privacy settings that prevent the "https://player.vimeo.com/video/XXXXXX" format and thus it is desirable to be able to obtain the source format for the "https://vimeo.com/video/XXXXXX" format URL.

- URL with unlisted hash, no pw required

Example: https://vimeo.com/144579403/ec02229140

When logged into Vimeo, the on-page download option shows an Original format option.
But even when passing cookies, yt-dlp is not listing it.

I tried reconfiguring the URL to the "https://player.vimeo.com/video/XXXXXX" (https://player.vimeo.com/video/144579403) format, but it still does not show any Original/source format.

I also tried it with the unlisted hash (https://player.vimeo.com/video/144579403?h=ec02229140), but it still does not show any Original/source format.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://vimeo.com/video/371764747', '--video-password', 'PRIVATE', '-F']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-12.2.1-arm64-arm-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[vimeo] Extracting URL: https://vimeo.com/video/371764747
[vimeo] 371764747: Downloading webpage
[vimeo] 371764747: Downloading viewer info
[vimeo] 371764747: Downloading API JSON
[vimeo] 371764747: Downloading API JSON
[vimeo] 371764747: Downloading JSON metadata
[vimeo] 371764747: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 371764747: Downloading fastly_skyfire m3u8 information
[vimeo] 371764747: Downloading akfire_interconnect_quic MPD information
WARNING: [vimeo] 371764747: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[vimeo] 371764747: Downloading fastly_skyfire MPD information
WARNING: [vimeo] 371764747: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[info] Available formats for 371764747:
ID                                               EXT RESOLUTION FPS │   FILESIZE    TBR PROTO │ VCODEC         VBR ACODEC     MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-akfire_interconnect_quic-audio-high-Original mp4 audio only     │                   m3u8  │ audio only         unknown    Original
hls-fastly_skyfire-audio-high-Original           mp4 audio only     │                   m3u8  │ audio only         unknown    Original
hls-akfire_interconnect_quic-409                 mp4 426x240     25 │ ~317.89MiB   409k m3u8  │ avc1.640015   409k video only
hls-fastly_skyfire-409                           mp4 426x240     25 │ ~317.89MiB   409k m3u8  │ avc1.640015   409k video only
hls-akfire_interconnect_quic-615                 mp4 640x360     25 │ ~478.01MiB   615k m3u8  │ avc1.64001E   615k video only
hls-fastly_skyfire-615                           mp4 640x360     25 │ ~478.01MiB   615k m3u8  │ avc1.64001E   615k video only
hls-akfire_interconnect_quic-1136                mp4 960x540     25 │ ~882.95MiB  1136k m3u8  │ avc1.64001F  1136k video only
hls-fastly_skyfire-1136                          mp4 960x540     25 │ ~882.95MiB  1136k m3u8  │ avc1.64001F  1136k video only
hls-akfire_interconnect_quic-2269                mp4 1280x720    25 │ ~  1.72GiB  2269k m3u8  │ avc1.640020  2269k video only
hls-fastly_skyfire-2269                          mp4 1280x720    25 │ ~  1.72GiB  2269k m3u8  │ avc1.640020  2269k video only
hls-akfire_interconnect_quic-5145                mp4 1920x1080   25 │ ~  3.91GiB  5145k m3u8  │ avc1.64002A  5145k video only
hls-fastly_skyfire-5145                          mp4 1920x1080   25 │ ~  3.91GiB  5145k m3u8  │ avc1.64002A  5145k video only
hls-akfire_interconnect_quic-12074               mp4 2560x1440   25 │ ~  9.16GiB 12074k m3u8  │ avc1.640033 12074k video only
hls-fastly_skyfire-12074                         mp4 2560x1440   25 │ ~  9.16GiB 12074k m3u8  │ avc1.640033 12074k video only
hls-akfire_interconnect_quic-23371               mp4 3840x2160   25 │ ~ 17.74GiB 23371k m3u8  │ avc1.640034 23371k video only
hls-fastly_skyfire-23371                         mp4 3840x2160   25 │ ~ 17.74GiB 23371k m3u8  │ avc1.640034 23371k video only

[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://player.vimeo.com/video/371764747', '--video-password', 'PRIVATE', '-F']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-12.2.1-arm64-arm-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[vimeo] Extracting URL: https://player.vimeo.com/video/371764747
[vimeo] 371764747: Downloading webpage
[vimeo] 371764747: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 371764747: Downloading fastly_skyfire m3u8 information
[vimeo] 371764747: Downloading akfire_interconnect_quic MPD information
WARNING: [vimeo] 371764747: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[vimeo] 371764747: Downloading fastly_skyfire MPD information
WARNING: [vimeo] 371764747: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[vimeo] 371764747: Downloading JSON metadata
[vimeo] 371764747: Downloading jwt token
[vimeo] 371764747: Downloading JSON metadata
[vimeo] 371764747: Determining source extension
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[info] Available formats for 371764747:
ID                                               EXT RESOLUTION FPS │   FILESIZE    TBR PROTO │ VCODEC         VBR ACODEC     MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-akfire_interconnect_quic-audio-high-Original mp4 audio only     │                   m3u8  │ audio only         unknown    Original
hls-fastly_skyfire-audio-high-Original           mp4 audio only     │                   m3u8  │ audio only         unknown    Original
hls-akfire_interconnect_quic-409                 mp4 426x240     25 │ ~317.89MiB   409k m3u8  │ avc1.640015   409k video only
hls-fastly_skyfire-409                           mp4 426x240     25 │ ~317.89MiB   409k m3u8  │ avc1.640015   409k video only
hls-akfire_interconnect_quic-615                 mp4 640x360     25 │ ~478.01MiB   615k m3u8  │ avc1.64001E   615k video only
hls-fastly_skyfire-615                           mp4 640x360     25 │ ~478.01MiB   615k m3u8  │ avc1.64001E   615k video only
hls-akfire_interconnect_quic-1136                mp4 960x540     25 │ ~882.95MiB  1136k m3u8  │ avc1.64001F  1136k video only
hls-fastly_skyfire-1136                          mp4 960x540     25 │ ~882.95MiB  1136k m3u8  │ avc1.64001F  1136k video only
hls-akfire_interconnect_quic-2269                mp4 1280x720    25 │ ~  1.72GiB  2269k m3u8  │ avc1.640020  2269k video only
hls-fastly_skyfire-2269                          mp4 1280x720    25 │ ~  1.72GiB  2269k m3u8  │ avc1.640020  2269k video only
hls-akfire_interconnect_quic-5145                mp4 1920x1080   25 │ ~  3.91GiB  5145k m3u8  │ avc1.64002A  5145k video only
hls-fastly_skyfire-5145                          mp4 1920x1080   25 │ ~  3.91GiB  5145k m3u8  │ avc1.64002A  5145k video only
hls-akfire_interconnect_quic-12074               mp4 2560x1440   25 │ ~  9.16GiB 12074k m3u8  │ avc1.640033 12074k video only
hls-fastly_skyfire-12074                         mp4 2560x1440   25 │ ~  9.16GiB 12074k m3u8  │ avc1.640033 12074k video only
hls-akfire_interconnect_quic-23371               mp4 3840x2160   25 │ ~ 17.74GiB 23371k m3u8  │ avc1.640034 23371k video only
hls-fastly_skyfire-23371                         mp4 3840x2160   25 │ ~ 17.74GiB 23371k m3u8  │ avc1.640034 23371k video only
source                                           mp4 3840x2160   25 │   89.80GiB        https │ unknown            unknown

[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://vimeo.com/144579403/ec02229140', '-F']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-12.2.1-arm64-arm-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[vimeo] Extracting URL: https://vimeo.com/144579403/ec02229140
[vimeo] 144579403: Downloading viewer info
[vimeo] 144579403: Downloading API JSON
[vimeo] 144579403: Downloading API JSON
[vimeo] 144579403: Downloading JSON metadata
[vimeo] 144579403: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 144579403: Downloading fastly_skyfire m3u8 information
[vimeo] 144579403: Downloading akfire_interconnect_quic MPD information
WARNING: [vimeo] 144579403: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[vimeo] 144579403: Downloading fastly_skyfire MPD information
WARNING: [vimeo] 144579403: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[info] Available formats for 144579403:
ID                                               EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-akfire_interconnect_quic-audio-high-Original mp4 audio only     │                  m3u8  │ audio only        unknown    Original
hls-akfire_interconnect_quic-audio-low-Original  mp4 audio only     │                  m3u8  │ audio only        unknown    Original
hls-fastly_skyfire-audio-high-Original           mp4 audio only     │                  m3u8  │ audio only        unknown    Original
hls-fastly_skyfire-audio-low-Original            mp4 audio only     │                  m3u8  │ audio only        unknown    Original
hls-akfire_interconnect_quic-479                 mp4 640x244     24 │ ~ 38.20MiB  479k m3u8  │ avc1.4D4016  479k video only
hls-fastly_skyfire-479                           mp4 640x244     24 │ ~ 38.20MiB  479k m3u8  │ avc1.4D4016  479k video only
http-360p                                        mp4 640x244     24 │                  https │ unknown           unknown
hls-akfire_interconnect_quic-950                 mp4 960x366     24 │ ~ 75.76MiB  950k m3u8  │ avc1.64001F  950k video only
hls-fastly_skyfire-950                           mp4 960x366     24 │ ~ 75.76MiB  950k m3u8  │ avc1.64001F  950k video only
http-540p                                        mp4 960x366     24 │                  https │ unknown           unknown
hls-akfire_interconnect_quic-1976                mp4 1366x520    24 │ ~157.59MiB 1976k m3u8  │ avc1.640020 1976k video only
hls-fastly_skyfire-1976                          mp4 1366x520    24 │ ~157.59MiB 1976k m3u8  │ avc1.640020 1976k video only
http-720p                                        mp4 1366x520    24 │                  https │ unknown           unknown
hls-akfire_interconnect_quic-4578                mp4 1920x730    24 │ ~365.10MiB 4578k m3u8  │ avc1.640028 4578k video only
hls-fastly_skyfire-4578                          mp4 1920x730    24 │ ~365.10MiB 4578k m3u8  │ avc1.640028 4578k video only
http-1080p                                       mp4 1920x730    24 │                  https │ unknown           unknown

[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://player.vimeo.com/video/144579403', '-F']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-12.2.1-arm64-arm-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[vimeo] Extracting URL: https://player.vimeo.com/video/144579403
[vimeo] 144579403: Downloading webpage
[vimeo] 144579403: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 144579403: Downloading fastly_skyfire m3u8 information
[vimeo] 144579403: Downloading akfire_interconnect_quic MPD information
WARNING: [vimeo] 144579403: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[vimeo] 144579403: Downloading fastly_skyfire MPD information
WARNING: [vimeo] 144579403: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[vimeo] 144579403: Downloading JSON metadata
[vimeo] 144579403: Downloading jwt token
[vimeo] 144579403: Downloading JSON metadata
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[info] Available formats for 144579403:
ID                                               EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-akfire_interconnect_quic-audio-high-Original mp4 audio only     │                  m3u8  │ audio only        unknown    Original
hls-akfire_interconnect_quic-audio-low-Original  mp4 audio only     │                  m3u8  │ audio only        unknown    Original
hls-fastly_skyfire-audio-high-Original           mp4 audio only     │                  m3u8  │ audio only        unknown    Original
hls-fastly_skyfire-audio-low-Original            mp4 audio only     │                  m3u8  │ audio only        unknown    Original
hls-akfire_interconnect_quic-486                 mp4 640x244     24 │ ~ 38.76MiB  486k m3u8  │ avc1.4D4016  486k video only
hls-fastly_skyfire-486                           mp4 640x244     24 │ ~ 38.76MiB  486k m3u8  │ avc1.4D4016  486k video only
http-360p                                        mp4 640x244     24 │                  https │ unknown           unknown
hls-akfire_interconnect_quic-957                 mp4 960x366     24 │ ~ 76.32MiB  957k m3u8  │ avc1.64001F  957k video only
hls-fastly_skyfire-957                           mp4 960x366     24 │ ~ 76.32MiB  957k m3u8  │ avc1.64001F  957k video only
http-540p                                        mp4 960x366     24 │                  https │ unknown           unknown
hls-akfire_interconnect_quic-1983                mp4 1366x520    24 │ ~158.15MiB 1983k m3u8  │ avc1.640020 1983k video only
hls-fastly_skyfire-1983                          mp4 1366x520    24 │ ~158.15MiB 1983k m3u8  │ avc1.640020 1983k video only
http-720p                                        mp4 1366x520    24 │                  https │ unknown           unknown
hls-akfire_interconnect_quic-4585                mp4 1920x730    24 │ ~365.66MiB 4585k m3u8  │ avc1.640028 4585k video only
hls-fastly_skyfire-4585                          mp4 1920x730    24 │ ~365.66MiB 4585k m3u8  │ avc1.640028 4585k video only
http-1080p                                       mp4 1920x730    24 │                  https │ unknown           unknown

[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://player.vimeo.com/video/144579403?h=ec02229140', '-F']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-12.2.1-arm64-arm-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[vimeo] Extracting URL: https://player.vimeo.com/video/144579403?h=ec02229140
[vimeo] 144579403: Downloading webpage
[vimeo] 144579403: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 144579403: Downloading fastly_skyfire m3u8 information
[vimeo] 144579403: Downloading akfire_interconnect_quic MPD information
WARNING: [vimeo] 144579403: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[vimeo] 144579403: Downloading fastly_skyfire MPD information
WARNING: [vimeo] 144579403: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[vimeo] 144579403: Downloading JSON metadata
[vimeo] 144579403: Downloading jwt token
[vimeo] 144579403: Downloading JSON metadata
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[info] Available formats for 144579403:
ID                                               EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-akfire_interconnect_quic-audio-high-Original mp4 audio only     │                  m3u8  │ audio only        unknown    Original
hls-akfire_interconnect_quic-audio-low-Original  mp4 audio only     │                  m3u8  │ audio only        unknown    Original
hls-fastly_skyfire-audio-high-Original           mp4 audio only     │                  m3u8  │ audio only        unknown    Original
hls-fastly_skyfire-audio-low-Original            mp4 audio only     │                  m3u8  │ audio only        unknown    Original
hls-akfire_interconnect_quic-486                 mp4 640x244     24 │ ~ 38.76MiB  486k m3u8  │ avc1.4D4016  486k video only
hls-fastly_skyfire-486                           mp4 640x244     24 │ ~ 38.76MiB  486k m3u8  │ avc1.4D4016  486k video only
http-360p                                        mp4 640x244     24 │                  https │ unknown           unknown
hls-akfire_interconnect_quic-957                 mp4 960x366     24 │ ~ 76.32MiB  957k m3u8  │ avc1.64001F  957k video only
hls-fastly_skyfire-957                           mp4 960x366     24 │ ~ 76.32MiB  957k m3u8  │ avc1.64001F  957k video only
http-540p                                        mp4 960x366     24 │                  https │ unknown           unknown
hls-akfire_interconnect_quic-1983                mp4 1366x520    24 │ ~158.15MiB 1983k m3u8  │ avc1.640020 1983k video only
hls-fastly_skyfire-1983                          mp4 1366x520    24 │ ~158.15MiB 1983k m3u8  │ avc1.640020 1983k video only
http-720p                                        mp4 1366x520    24 │                  https │ unknown           unknown
hls-akfire_interconnect_quic-4585                mp4 1920x730    24 │ ~365.66MiB 4585k m3u8  │ avc1.640028 4585k video only
hls-fastly_skyfire-4585                          mp4 1920x730    24 │ ~365.66MiB 4585k m3u8  │ avc1.640028 4585k video only
http-1080p                                       mp4 1920x730    24 │                  https │ unknown           unknown
```

**Comment by bashonly** [comment] 2024-08-11 23:55
Duplicate of #9163

**Comment by bashonly** [comment] 2024-08-11 23:55
- #10721

**Closed by bashonly** 2024-08-11 23:55 UTC
Labels: duplicate, site-bug, site:vimeo
