### ISSUE TITLE
Embed all subtitles, thumbnails, metadata, etc. in one go

### ISSUE THREAD

**Issue by 0n-s** [yt-dlp/yt-dlp#3316] opened 2022-04-05 20:03 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp commit **e491d06d344dde805bf5ea14d63310428cc7edf4**.
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When using flags like `--embed-subtitles`, `--embed-metadata`, & `--embed-thumbnail` (but surprisingly not `--embed-info-json`, which is done as part of `--embed-metadata`), yt-dlp will perform the tasks associated with them one-by-one. While this is simple, this is very inefficient. For very large videos like [Black Mesa: The 16 Year Project to Remake Half-Life | Noclip Documentary](https://youtu.be/G_TcAxAKCAI), which takes up a combined 21G(!) with the default format selection, this is bad because it will result in this 21G being written to disk an entire 5 times: once to download the individual video & audio streams, once to just merge the two together, once to embed subtitles, once to embed metadata, & once more to add the thumbnail.

This is not only incredibly inefficient & slow, it also significantly increases the amount of I/O done. Not to pigeonhole options here, but as the aforementioned options are very good for creating a fully archived bundle of a video with all its associated assets & metadata in a single file, it's likely the video is being downloaded to disk, & I don't think I need to explain why multiplying the amount of I/O done to download a video is a bad idea in that case (multiplying I/O is bad regardless, but especially harmful to disks). My mitigation for these big videos has been to download them to a RAM-backed filesystem & push them to disk when it's done processing, which is not practical because

- it's still very slow; 21G may be significantly speedier to process through when I/O goes at RAM speed but it's still 21G
- it requires the FS to be able to fit the size of the entire video…times 2
- that's a lot of RAM being used on repetitive filesystem I/O which could've otherwise been page cache

Even worse is that when running `yt-dlp` on already downloaded videos (there are a number of reasons to do this, like updating thumbnails; downloading April Fools videos before & after April Fools is a great example), the same inefficiencies apply, which can be awful if e.g. you're trying to download a playlist of livestream archives on an unstable connection. Not the worst case scenario since there are almost certainly no subtitles, but livestreams are generally large, & if your connection drops when downloading said playlist, you'll find yourself waiting for a while before you start downloading again as `yt-dlp` embeds all the assets of completed videos one-by-one. & I don't think this behavior is bad, it's just that it is made much worse by `yt-dlp` doing all the tasks one-by-one.

So it would be nice if `yt-dlp` could just summon ffmpeg once to do all of these tasks, which would allow for significant savings in I/O for those who use a combination of these options. I'm sure it's possible considering ffmpeg's flexibility.

It's also worth noting that despite the title, this is also an issue with several other "tasks" including the `FixupM3u8` task (commonly summoned without any special options when downloading VODs on Twitch, & also powered by FFmpeg; I prefer not to include an example URL because of the much more transient nature of Twitch VODs, but let me know if this is a problem). I'm not quite sure if any of these have a generic name, so the issue title is not as inclusive as I wish it could be. But this is indeed an issue with these as well.

Note: my log doesn't involve me actually downloading the example video since I can't exactly do that on a whim, but it illustrates that `yt-dlp` will write the video to disk much more than is necessary, so I believe it's enough.

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-R', '1024', '--ignore-config', '-o', '%(title)s-%(id)s.%(ext)s', '--embed-metadata', '--embed-subs', '--embed-chapters', '--embed-thumbnail', '--embed-info-json', 'https://youtu.be/G_TcAxAKCAI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.9.12 (CPython 64bit) - Linux-5.16.0-ns-g0c947b893d69-x86_64-Intel-R-_Core-TM-_i7-8550U_CPU_@_1.80GHz-with-libc
[debug] exe versions: ffmpeg present (setts,needs_adtstoasc), ffprobe present
[debug] Optional libraries: brotlicffi, Crypto, sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.2
yt-dlp is up to date (2022.03.08.2)
[debug] [youtube] Extracting URL: https://youtu.be/G_TcAxAKCAI
[youtube] G_TcAxAKCAI: Downloading webpage
[youtube] G_TcAxAKCAI: Downloading android player API JSON
[debug] Loading youtube-nsig.9e50a907 from cache
[debug] [youtube] Decrypted nsig TtvAgmQ-QnfPjQ2u => flKItA6P2gimLA
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: en
[debug] Default format spec: bestvideo*+bestaudio/best
[info] G_TcAxAKCAI: Downloading 1 format(s): 315+251
Deleting existing file Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.en.vtt
[info] Writing video subtitles to: Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.en.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=G_TcAxAKCAI&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&xoaf=4&hl=en&ip=0.0.0.0&ipbits=0&expire=1649208458&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cxoaf&signature=6C5E6C557767B5123C9F073925A12020BFCA266D.100EAE93AA0ED205439186A31EE89260ABA55E4E&key=yt8&lang=en&fmt=vtt"
[download] Destination: Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.en.vtt

[download] 1.00KiB at Unknown speed (00:01)
[download] 3.00KiB at Unknown speed (00:01)
[download] 7.00KiB at 245.64KiB/s (00:01)  
[download] 15.00KiB at 212.67KiB/s (00:01)
[download] 31.00KiB at 65.85KiB/s (00:01) 
[download] 63.00KiB at 80.09KiB/s (00:02)
[download] 127.00KiB at 76.64KiB/s (00:03)
[download] 200.52KiB at 83.01KiB/s (00:03)
[download] 216.08KiB at 81.56KiB/s (00:04)
[download] 100% of 216.08KiB in 00:04     
Deleting existing file Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.webp
[info] Downloading video thumbnail 41 ...
WARNING: Unable to download video thumbnail 41: HTTP Error 404: Not Found
[info] Downloading video thumbnail 40 ...
WARNING: Unable to download video thumbnail 40: HTTP Error 404: Not Found
[info] Downloading video thumbnail 39 ...
WARNING: Unable to download video thumbnail 39: HTTP Error 404: Not Found
[info] Downloading video thumbnail 38 ...
WARNING: Unable to download video thumbnail 38: HTTP Error 404: Not Found
[info] Downloading video thumbnail 37 ...
[info] Writing video thumbnail 37 to: Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.webp
WARNING: webm doesn't support embedding a thumbnail, mkv will be used
[download] Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.mkv has already been downloaded
[EmbedSubtitle] Embedding subtitles in "Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.mkv' -i 'file:Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.en.vtt' -map 0 -dn -ignore_unknown -c copy -map -0:s -map 1:0 -metadata:s:s:0 language=eng -metadata:s:s:0 handler_name=English -metadata:s:s:0 title=English -movflags +faststart 'file:Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.temp.mkv'
Deleting original file Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.en.vtt (pass -k to keep)
[debug] Writing info-json to: Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.info.json.temp
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.mkv'
[Metadata] Adding metadata to "Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.mkv' -i 'file:Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.meta' -map 0 -dn -ignore_unknown -c copy -map_metadata 1 -metadata 'title=Black Mesa: The 16 Year Project to Remake Half-Life | Noclip Documentary' -metadata date=20220315 -metadata 'description=Support us on Patreon (get perks!) ► https://www.patreon.com/noclip
or Join Noclip on YouTube (similar perks!) ► https://bit.ly/3nH3FUf
SUBSCRIBE for More Free Game Docs ► http://bit.ly/noclipsubscribe

We talk to Crowbar Collective about their 16 year journey rebuilding the original Half-Life.

Noclip'"'"'s work is 100% crowdfunded.
Patreon: https://www.patreon.com/noclip
Website: https://www.noclip.video
Store: https://store.noclip.video
Instagram: https://www.instagram.com/noclipvideo/
Twitter: https://twitter.com/noclipvideo
Twitch: https://twitch.tv/noclip
Podcast: https://noclippodcast.libsyn.com/
Podcast Channel: http://youtube.com/noclippodcast

Produced & Hosted by Danny O'"'"'Dwyer
Lead Editor Jeremy Jayne
Filmed by Jeremy Jayne
Additional Editing by Danny O'"'"'Dwyer
Gameplay Capture by Frank Howley
Captions by Denis Walsh [incoming]

0:00 - Cold Open
2:01 - Intro
5:26 - Recreating Half-Life
29:19 - From Copycats to Creators
46:45 - XEN
1:09:48 - Gonarch'"'"'s Lair
1:21:28 - Interloper
1:47:34 - Nihilanth
2:01:17 - Outro
 2:07:34 - Credits' -metadata 'synopsis=Support us on Patreon (get perks!) ► https://www.patreon.com/noclip
or Join Noclip on YouTube (similar perks!) ► https://bit.ly/3nH3FUf
SUBSCRIBE for More Free Game Docs ► http://bit.ly/noclipsubscribe

We talk to Crowbar Collective about their 16 year journey rebuilding the original Half-Life.

Noclip'"'"'s work is 100% crowdfunded.
Patreon: https://www.patreon.com/noclip
Website: https://www.noclip.video
Store: https://store.noclip.video
Instagram: https://www.instagram.com/noclipvideo/
Twitter: https://twitter.com/noclipvideo
Twitch: https://twitch.tv/noclip
Podcast: https://noclippodcast.libsyn.com/
Podcast Channel: http://youtube.com/noclippodcast

Produced & Hosted by Danny O'"'"'Dwyer
Lead Editor Jeremy Jayne
Filmed by Jeremy Jayne
Additional Editing by Danny O'"'"'Dwyer
Gameplay Capture by Frank Howley
Captions by Denis Walsh [incoming]

0:00 - Cold Open
2:01 - Intro
5:26 - Recreating Half-Life
29:19 - From Copycats to Creators
46:45 - XEN
1:09:48 - Gonarch'"'"'s Lair
1:21:28 - Interloper
1:47:34 - Nihilanth
2:01:17 - Outro
 2:07:34 - Credits' -metadata 'purl=https://www.youtube.com/watch?v=G_TcAxAKCAI' -metadata 'comment=https://www.youtube.com/watch?v=G_TcAxAKCAI' -metadata 'artist=Noclip - Video Game Documentaries' -map -0:4 -attach 'Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.info.json.temp' -metadata:s:4 mimetype=application/json -movflags +faststart 'file:Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.temp.mkv'
[ThumbnailsConvertor] Converting thumbnail "Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.webp' -movflags +faststart 'file:Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.png'
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.mkv'
[EmbedThumbnail] ffmpeg: adding thumbnail to "Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.mkv' -map 0 -dn -ignore_unknown -c copy -map -0:2 -attach 'Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.png' -metadata:s:4 mimetype=image/png -metadata:s:4 filename=cover.png -movflags +faststart 'file:Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.temp.mkv'
Deleting original file Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.webp (pass -k to keep)
Deleting original file Black Mesa - The 16 Year Project to Remake Half-Life _ Noclip Documentary-G_TcAxAKCAI.png (pass -k to keep)
```

**Comment by pukkandan** [comment] 2022-04-06 07:57
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/126

**Closed by pukkandan** 2022-04-06 07:57 UTC
Labels: enhancement, triage
