### ISSUE TITLE
Disable setting of default flag for subtitle tracks

### ISSUE THREAD

**Issue by christoph-heinrich** [yt-dlp/yt-dlp#4717] opened 2022-08-20 13:41 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Currently the default flag gets set on tracks, which isn't a problem for me when it comes to video and audio tracks, but I would like to be able to not add the default flag for subtitles.
Because of that default flag, video players will automatically select that subtitle track when opening the file. While I want the subtitles to be available, in case I need them, I don't want them to be enabled by default.
One way around this would be to configure the video player to never select subtitles by default, but then that breaks the behavior for when automatic subtitle selection is actually desired (e.g. forced subtitles).

I don't know if anyone would benefit from making this configurable for video and audio tracks, but there is certainly a use case when it comes to subtitles.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment] 2022-08-20 16:21
Duplicate of #2799

**Closed by pukkandan** 2022-08-20 16:21 UTC
Labels: enhancement, triage

**Comment by christoph-heinrich** [comment] 2022-08-20 22:11
Sorry for the noise, but I didn't find that issue when looking for existing ones.
However that linked issue got me on the right track to finding a solution to this, and I've added a comment over there (and edited it several times :sweat_smile: along the way) on how to not have subtitle tracks set as default.
