### ISSUE TITLE
[Douyin] TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by testaccountnamer** [yt-dlp/yt-dlp#7854] opened 2023-08-15 22:55 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I can't download Douyin videos, even though I have recent cookies for the website.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[user@NET ~]$ yt-dlp -vU --cookies-from chromium "https://www.douyin.com/video/7265151697159310644"
[debug] Command-line config: ['-vU', '--cookies-from', 'chromium', 'https://www.douyin.com/video/7265151697159310644']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.1.44-1-MANJARO-x86_64-with-glibc2.38 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from chromium
[debug] Extracting cookies from: "/home/user/.config/chromium/Default/Cookies"
[Cookies] Extracted 26 cookies from chromium
[debug] cookie version breakdown: {'v10': 26, 'v11': 0, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[Douyin] Extracting URL: https://www.douyin.com/video/7265151697159310644
[Douyin] 7265151697159310644: Downloading video feed
[Douyin] 7265151697159310644: Unable to find video in feed; trying with webpage
[Douyin] 7265151697159310644: Downloading webpage
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 1028, in _real_extract
    return self._parse_aweme_video_web(get_first(render_data, ('aweme', 'detail')), url, video_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 353, in _parse_aweme_video_web
    video_info = aweme_detail['video']
                 ~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by purple5pumpkin235** [comment] 2023-08-16 12:38
Same problem here. Don't know if it's related, but Firefox ctrl+i now sees 2 videos per page. Until yesterday, only 1 video was loaded in the ctrl+i view. 

Downloading through Firefox ctrl+i, as well as download sites like tikwm, continue to work fine for douyin.

**Comment by xuen97** [comment] 2023-08-18 04:38
Same problem for me. Used fresh cookies but failed as well.

Verbose Output:
`yt-dlp https://www.douyin.com/video/7254548707851406626 --cookies douyin.com_cookies.txt
[Douyin] Extracting URL: https://www.douyin.com/video/7254548707851406626
[Douyin] 7254548707851406626: Downloading video feed
[Douyin] 7254548707851406626: Unable to find video in feed; trying with webpage
[Douyin] 7254548707851406626: Downloading webpage
ERROR: 'NoneType' object is not subscriptable`

**Comment by bashonly** [comment] 2023-08-18 18:33
I can't reproduce the issue. I can download OP's link fine with cookies from browser.

Can someone experiencing the issue run this command and then upload the dumped pages and share the log?
```
yt-dlp -vF --write-pages --cookies-from-browser BROWSER "https://www.douyin.com/video/7265151697159310644"
```
(of course replace `BROWSER` with your actual browser, or replace `--cookies-from-browser BROWSER` with `--cookies your_cookies.txt` if you prefer to use a cookiefile)

**Comment by testaccountnamer** [comment] 2023-08-19 17:47
@bashonly 

The logs:

[7265151697159310644_https_-_www.douyin.com_video_7265151697159310644.txt](https://github.com/yt-dlp/yt-dlp/files/12386433/7265151697159310644_https_-_www.douyin.com_video_7265151697159310644.txt)
[7265151697159310644_https_-_aweme.snssdk.com_aweme_v1_feed_aweme_id=7265151697159310644_version_name=23.3.0_version_code=230300_build_number=23.3.0_manifest_version_code=230300_update_version_code=230300____ed7f0990967b6822f613393027d704e7.txt](https://github.com/yt-dlp/yt-dlp/files/12386434/7265151697159310644_https_-_aweme.snssdk.com_aweme_v1_feed_aweme_id.7265151697159310644_version_name.23.3.0_version_code.230300_build_number.23.3.0_manifest_version_code.230300_update_version_code.230300____ed7f0990967b6822f613393027d704e7.txt)

**Comment by bashonly** [comment] 2023-08-20 10:42
Hmm. there is no video detail info in the html dump you posted. There must be an API call being made on your end that fetches the info, but it doesn't happen when I browse the page. Someone who is also experiencing this issue will need to work on a fix for this

**Comment by kamendula** [comment] 2023-09-08 06:56
exactly same with me.

**Comment by RallyQ** [comment] 2023-09-12 02:37
ERROR: 'NoneType' object is not subscriptable
Same thing. It was normal yesterday
Re-log in to the account, no

**Comment by wranai** [comment] 2023-09-12 18:32
There is a new API endpoint that returns what's missing: https://www.douyin.com/aweme/v1/web/aweme/detail/

It requires signatures that I don't know how to generate.

**Comment by wwfcnu** [comment] 2023-09-21 16:58
> I extracted the json from <script id="RENDER_DATA" type="application/json">, seems like the aweme detail is no longer in it
This analysis will only get part of the video link, How to get links to all videos

**Comment by LyceumHewun** [comment] 2023-10-12 03:48
> I can't reproduce the issue. I can download OP's link fine with cookies from browser.
> 
> Can someone experiencing the issue run this command and then upload the dumped pages and share the log?
> 
> ```
> yt-dlp -vF --write-pages --cookies-from-browser BROWSER "https://www.douyin.com/video/7265151697159310644"
> ```
> 
> (of course replace `BROWSER` with your actual browser, or replace `--cookies-from-browser BROWSER` with `--cookies your_cookies.txt` if you prefer to use a cookiefile)

I'm experiencing same the issue. 

run the command on win11 x64
```
.\yt-dlp_x86.exe -vF --write-pages --cookies .\www.douyin.com_cookies.txt https://www.douyin.com/video/7265151697159310644
```
### Complete Verbose Output
```
[debug] Command-line config: ['-vF', '--write-pages', '--cookies', '.\\www.douyin.com_cookies.txt', 'https://www.douyin.com/video/7265151697159310644']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (win_x86_exe)
[debug] Python 3.7.9 (CPython AMD64 32bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.31.1, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[Douyin] Extracting URL: https://www.douyin.com/video/7265151697159310644
[Douyin] 7265151697159310644: Downloading video feed
[Douyin] Saving request to \\?\C:\Users\91754\Downloads\7265151697159310644_https_-_aweme.snssdk.com_aweme_v1_feed_aweme_id=7265151697159310644_version_name=23.3.0_version_code=230300_build_number=23.3.0_manifest_version_code=230300_update_version_code=230300____5ee17fbba8adb44702b87b30fd70c88b.dump
[Douyin] 7265151697159310644: Unable to find video in feed; trying with webpage
[Douyin] 7265151697159310644: Downloading webpage
[Douyin] Saving request to 7265151697159310644_https_-_www.douyin.com_video_7265151697159310644.dump
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\tiktok.py", line 1055, in _real_extract
  File "yt_dlp\extractor\tiktok.py", line 354, in _parse_aweme_video_web
TypeError: 'NoneType' object is not subscriptable

```

### Dump File

Here's the dump file.
[7265151697159310644_https_-_www.douyin.com_video_7265151697159310644.txt](https://github.com/yt-dlp/yt-dlp/files/12876811/7265151697159310644_https_-_www.douyin.com_video_7265151697159310644.txt)

**Comment by ahm750** [comment] 2024-01-05 15:53
Any updates on the Douyin extractor? It's broken in the latest update (yt-dlp 2023.12.30)

**Closed** 2024-02-28 02:31 UTC
Labels: site-bug, site:tiktok
