### ISSUE TITLE
ABC.com/Go Updated Provider Login Page Breaks yt-dlp, "Unable to extract post url"

### ISSUE THREAD

**Issue by ViRGEdx** [yt-dlp/yt-dlp#10973] opened 2024-09-11 02:46 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

ABC.com has updated their provider login page for accessing paywalled materials. Previously, yt-dlp's Go extractor could navigate this and log in with the Adobe Pass family of options. However the page update has broken this functionality, resulting in an "Unable to extract post url" error.

To note, this does not seem to be an issue at the provider level itself. I've tested this with valid logins for multiple providers (and some invalid ones for yet more providers as well) and yt-dlp is not making it far enough to even try to log in. So something is broken at the more basic extractor or Adobe Pass level. This also means that basic debugging does not require a valid account.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://abc.com/episode/3ee331a3-b5d8-47b4-9f06-3fa2b12b6bc1/playlist/PL554912060', '--ap-mso', 'DTV', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds [d1c4d88b2] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 7.0.2-essentials_build-www.gyan.dev (setts), ffprobe 7.0.2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1832 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds)
[Go] Extracting URL: https://abc.com/episode/3ee331a3-b5d8-47b4-9f06-3fa2b12b6bc1/playlist/PL554912060
[Go] PL554912060: Downloading webpage
[Go] vdka37713213: Downloading JSON metadata
[debug] Loading ap-mvpd.ABC from cache
[Go] VDKA37713213: Downloading Provider Redirect Page
[Go] VDKA37713213: Downloading Provider Login Page
ERROR: [Go] Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\go.py", line 250, in _real_extract
  File "yt_dlp\extractor\adobepass.py", line 1715, in _extract_mvpd_auth
  File "yt_dlp\extractor\adobepass.py", line 1395, in post_form
  File "yt_dlp\extractor\common.py", line 1369, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1333, in _search_regex
```

**Comment by bashonly** [comment] 2024-09-11 03:05
Duplicate of #2188

**Closed by bashonly** 2024-09-11 03:05 UTC
Labels: site-bug, triage
