### ISSUE TITLE
Different error codes if the errors are different

### ISSUE THREAD

**Issue by JoseAngelB** [yt-dlp/yt-dlp#3842] opened 2022-05-22 21:07 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

For automation jobs, it will be good if there is an error, the program returns a different error code for each kind of error instead always return 1.
It can be 1 if is a syntax error, 2 can't find any video in the link, 3 if there is an extractor error, 4 if the error is because a 40X retrieving the stream, 5 if it is a ffmpeg error, 6 if it is a pre or postprocessor error... Or something like that

**Comment by pukkandan** [comment] 2022-05-23 05:11
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2947

**Closed by pukkandan** 2022-05-23 05:11 UTC
Labels: enhancement, triage
