### ISSUE TITLE
 douyin 2022.02.04   raise ExtractorError('Fresh cookies (not necessarily logged in) are needed')

### ISSUE THREAD

**Issue by wanghaisheng** [yt-dlp/yt-dlp#2841] opened 2022-02-20 12:57 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

china

### Description

$ yt-dlp -Uv www.douyin.com/video/6997703748135030020 --cookies-from-browser firefox 

### Verbose log

```shell
$ yt-dlp -Uv www.douyin.com/video/6997703748135030020 --cookies-from-browser firefox 
[debug] Command-line config: ['-Uv', 'www.douyin.com/video/6997703748135030020', '--cookies-from-browser', 'firefox']
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\dubo\AppData\Roaming\Mozilla\Firefox\Profiles\7u6b59qt.default-release-1628897394371\cookies.sqlite"
[Cookies] Extracted 3061 cookies from firefox
[debug] Encodings: locale cp936, fs utf-8, out utf-8, err utf-8, pref cp936
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.8.5 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: www.douyin.com/video/6997703748135030020
WARNING: [generic] The url doesn't specify the protocol, trying with http
[debug] [Douyin] Extracting URL: http://www.douyin.com/video/6997703748135030020
[Douyin] 6997703748135030020: Downloading video details
WARNING: [Douyin] 6997703748135030020: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U; Retrying with feed workaround
[Douyin] 6997703748135030020: Downloading video feed
WARNING: [Douyin] 6997703748135030020: Unable to find video in feed; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U; Retrying with webpage
[Douyin] 6997703748135030020: Downloading webpage
ERROR: [Douyin] 6997703748135030020: Fresh cookies (not necessarily logged in) are needed; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
  File "D:\Program Files\anaconda3\lib\site-packages\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "D:\Program Files\anaconda3\lib\site-packages\yt_dlp\extractor\tiktok.py", line 814, in _real_extract
    raise ExtractorError('Fresh cookies (not necessarily logged in) are needed')
```
```

**Comment by pukkandan** [comment] 2022-02-20 13:08
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2267

**Closed by pukkandan** 2022-02-20 13:08 UTC
Labels: duplicate, site-bug, site:tiktok

**Comment by wwfcnu** [comment] 2023-08-03 03:41
这个问题怎么解决的，我也遇到了

**Comment by wwfcnu** [comment] 2023-08-03 03:41
[Douyin] Extracting URL: https://www.douyin.com/video/7184385271910108476
[Douyin] 7184385271910108476: Downloading video feed
[Douyin] 7184385271910108476: Unable to find video in feed; trying with webpage
[Douyin] 7184385271910108476: Downloading webpage
WARNING: [Douyin] unable to extract render data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Douyin] 7184385271910108476: Fresh cookies (not necessarily logged in) are needed

**Comment by linlance** [comment] 2024-05-10 01:47
meet the same error:
WARNING: [Douyin] 7364022131870453028: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
ERROR: [Douyin] 7364022131870453028: Fresh cookies (not necessarily logged in) are needed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the
 appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
