### ISSUE TITLE
[Broken] Does not extract `title` (and other metadata?) correctly when using cookies

### ISSUE THREAD

**Issue by parasiteoflife** [yt-dlp/yt-dlp#795] opened 2021-08-27 07:09 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Description

- If I provide a cookie file no metadata is correctly extracted except for the release date. If cookie file is not provided then all metadata is downloaded correctly except for the date.
- Either way if the video's date is correctly or incorrectly extracted the file timestamps are always the current time.
- For certain videos it doesn't download the highest quality available.
- `%(height)s` doesn't work, I get `NA`, which I supposed is tied to the first issue.

I've tried with this url `https://www.facebook.com/watch/?v=1878804305467115` and yt-dlp downloads the hd (720p) resolution instead of 1080p (as is available in Facebook and using `-F`).

Formats: 

```
[facebook] 1878804305467115: Downloading webpage
[info] Available formats for 1878804305467115:
ID                       EXT RESOLUTION |   TBR PROTO | VCODEC        VBR ACODEC     ABR  ASR    MORE INFO
------------------------ --- ---------- - ----- ----- - ----------- ----- --------- ---- ------- ---------------------------
267002183810670a         m4a audio only |   49k https |                   mp4a.40.5  49k 48000Hz [eng], DASH audio, m4a_dash
369014396860447v         mp4 256x144    |  104k https | avc1.4d401e  104k                        [eng], DASH video, mp4_dash
230936214102549v         mp4 426x240    |  255k https | avc1.4d401e  255k                        [eng], DASH video, mp4_dash
353790831701348v         mp4 480x270    |  372k https | avc1.4d401e  372k                        [eng], DASH video, mp4_dash
120351801961492v         mp4 640x360    |  587k https | avc1.4d401e  587k                        [eng], DASH video, mp4_dash
806983556129511v         mp4 852x480    |  898k https | avc1.4d401f  898k                        [eng], DASH video, mp4_dash
292469741234465v         mp4 1280x720   | 1638k https | avc1.4d401f 1638k                        [eng], DASH video, mp4_dash
818863141609894v         mp4 1920x1080  | 4175k https | avc1.4d401f 4175k                        [eng], DASH video, mp4_dash
dash_sd_src              mp4 unknown    |       https | unknown           unknown
dash_sd_src_no_ratelimit mp4 unknown    |       https | unknown           unknown
dash_hd_src              mp4 unknown    |       https | unknown           unknown
dash_hd_src_no_ratelimit mp4 unknown    |       https | unknown           unknown
```

## Verbose log

WITH COOKIES:

```
[debug] Command-line config: ['-v', '-R', '15', '-i', '-o', '%(extractor)s\\%(uploader)s\\%(title)s (%(id)s) [%(height)sp].%(ext)s', '--cookies', 'Z:\\cookies.txt', '-f', 'bv*+ba/b', '--add-metadata', '--paths', 'TEMP:X:\\temp1', '--paths', 'HOME:X:\\temp2', 'https://www.facebook.com/watch/?v=1878804305467115']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-07-06-git-758e2da289-full_build-www.gyan.dev, ffprobe 2021-07-06-git-758e2da289-full_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/watch/?v=1878804305467115
[facebook] 1878804305467115: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: 1878804305467115
[facebook] playlist 1878804305467115: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[info] 1878804305467115: Downloading 1 format(s): hd
[debug] Invoking downloader on "https://video-lim1-1.xx.fbcdn.net/v/t42.1790-2/21889864_370068176746040_2261232253356998656_n.mp4?_nc_cat=101&vs=c87cc8394789ebd4&_nc_vs=HBksFQAYJEdFZ0RUZ0U0dGpjMmsxQUJBQUFBQUFEQmdtRWZidjRHQUFBRhUAAsgBABUAGCRHT29zVGdFY2I1LTFMX01CQUFBQUFBQUFGZ1kwYnY0R0FBQUYVAgLIAQBLBogScHJvZ3Jlc3NpdmVfcmVjaXBlATEgbWVhc3VyZV9vcmlnaW5hbF9yZXNvbHV0aW9uX3NzaW0AKGNvbXB1dGVfc3NpbV9vbmx5X2F0X29yaWdpbmFsX3Jlc29sdXRpb24AEWRpc2FibGVfcG9zdF9wdnFzAA1zdWJzYW1wbGVfZnBzABB2bWFmX2VuYWJsZV9uc3ViABUAJQAcAAAmgvWo7eaw1gYVAigCQzMYC3Z0c19wcmV2aWV3HBdAPmtDlYEGJRgpZGFzaF92M18xMjgwX2NyZl8yM19oaWdoXzMuMV9mcmFnXzJfdmlkZW8SABgYdmlkZW9zLnZ0cy5jYWxsYmFjay5wcm9kOBJWSURFT19WSUVXX1JFUVVFU1QbCIgVb2VtX3RhcmdldF9lbmNvZGVfdGFnBm9lcF9oZBNvZW1fcmVxdWVzdF90aW1lX21zDTE2MzAwMTQ1MDY2MTcMb2VtX2NmZ19ydWxlB3VubXV0ZWQTb2VtX3JvaV9yZWFjaF9jb3VudAUzOTM3NQxvZW1fdmlkZW9faWQQMTg3ODgwNDMwNTQ2NzExNRJvZW1fdmlkZW9fYXNzZXRfaWQQMTg3ODgwNDMwMjEzMzc4MhVvZW1fdmlkZW9fcmVzb3VyY2VfaWQQMTg3ODgwNDI5ODgwMDQ0ORxvZW1fc291cmNlX3ZpZGVvX2VuY29kaW5nX2lkDzM3MDA2ODE3MzQxMjcwNyUCHAAlxAEbB4gBcwQzOTA1AmNkCjIwMTctMDktMTkDcmNiBTM5MzAwA2FwcAZWaWRlb3MCY3QGTEVHQUNZE29yaWdpbmFsX2R1cmF0aW9uX3MJMzAuMDYzMzY3AnRzD29lcF9wcm9ncmVzc2l2ZQA%3D&ccb=1-5&_nc_sid=25cb26&efg=eyJ2ZW5jb2RlX3RhZyI6Im9lcF9oZCJ9&_nc_ohc=uWxFbr-FTy8AX9hoiZ9&_nc_ht=video-lim1-1.xx&oh=646f32d1992330561be73e3697c02153&oe=61282C30&_nc_rid=890b6c5e4c2142a&_nc_vts_prog=1&vts=1&_nc_vts_internal=1"
[download] Destination: X:\temp1\facebook\NA\Facebook video #1878804305467115 (1878804305467115) [NAp].mp4
[download] 100% of 7.46MiB in 00:00
[Metadata] Adding metadata to "X:\temp1\facebook\NA\Facebook video #1878804305467115 (1878804305467115) [NAp].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:X:\temp1\facebook\NA\Facebook video #1878804305467115 (1878804305467115) [NAp].mp4" -map 0 -dn -c copy -metadata "title=Facebook video #1878804305467115" -metadata "date=20170919" -metadata "purl=https://www.facebook.com/watch/?v=1878804305467115" -metadata "comment=https://www.facebook.com/watch/?v=1878804305467115" -metadata "artist=551301391550753" "file:X:\temp1\facebook\NA\Facebook video #1878804305467115 (1878804305467115) [NAp].temp.mp4"
[MoveFiles] Moving file "X:\temp1\facebook\NA\Facebook video #1878804305467115 (1878804305467115) [NAp].mp4" to "X:\temp2\facebook\NA\Facebook video #1878804305467115 (1878804305467115) [NAp].mp4"
[download] Finished downloading playlist: 1878804305467115
```

WITHOUT COOKIES:

```
[debug] Command-line config: ['-v', '-R', '15', '-i', '-o', '%(extractor)s\\%(uploader)s\\%(title)s (%(id)s) [%(height)sp].%(ext)s', '-f', 'bv*+ba/b', '--add-metadata', '--paths', 'TEMP:X:\\temp1', '--paths', 'HOME:X:\\temp2', 'https://www.facebook.com/watch/?v=1878804305467115']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-07-06-git-758e2da289-full_build-www.gyan.dev, ffprobe 2021-07-06-git-758e2da289-full_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/watch/?v=1878804305467115
[facebook] 1878804305467115: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 1878804305467115: Downloading 1 format(s): dash_hd_src_no_ratelimit
[debug] Invoking downloader on "https://video-lim1-1.xx.fbcdn.net/v/t42.1790-2/21889864_370068176746040_2261232253356998656_n.mp4?_nc_cat=101&vs=c87cc8394789ebd4&_nc_vs=HBksFQAYJEdFZ0RUZ0U0dGpjMmsxQUJBQUFBQUFEQmdtRWZidjRHQUFBRhUAAsgBABUAGCRHT29zVGdFY2I1LTFMX01CQUFBQUFBQUFGZ1kwYnY0R0FBQUYVAgLIAQBLBogScHJvZ3Jlc3NpdmVfcmVjaXBlATEgbWVhc3VyZV9vcmlnaW5hbF9yZXNvbHV0aW9uX3NzaW0AKGNvbXB1dGVfc3NpbV9vbmx5X2F0X29yaWdpbmFsX3Jlc29sdXRpb24AEWRpc2FibGVfcG9zdF9wdnFzAA1zdWJzYW1wbGVfZnBzABB2bWFmX2VuYWJsZV9uc3ViABUAJQAcAAAmgvWo7eaw1gYVAigCQzMYC3Z0c19wcmV2aWV3HBdAPmtDlYEGJRgpZGFzaF92M18xMjgwX2NyZl8yM19oaWdoXzMuMV9mcmFnXzJfdmlkZW8SABgYdmlkZW9zLnZ0cy5jYWxsYmFjay5wcm9kOBJWSURFT19WSUVXX1JFUVVFU1QbCIgVb2VtX3RhcmdldF9lbmNvZGVfdGFnBm9lcF9oZBNvZW1fcmVxdWVzdF90aW1lX21zDTE2MzAwMTUwNDAzNjEMb2VtX2NmZ19ydWxlB3VubXV0ZWQTb2VtX3JvaV9yZWFjaF9jb3VudAUzOTM3NQxvZW1fdmlkZW9faWQQMTg3ODgwNDMwNTQ2NzExNRJvZW1fdmlkZW9fYXNzZXRfaWQQMTg3ODgwNDMwMjEzMzc4MhVvZW1fdmlkZW9fcmVzb3VyY2VfaWQQMTg3ODgwNDI5ODgwMDQ0ORxvZW1fc291cmNlX3ZpZGVvX2VuY29kaW5nX2lkDzM3MDA2ODE3MzQxMjcwNyUCHAAlxAEbB4gBcwQzOTA1AmNkCjIwMTctMDktMTkDcmNiBTM5MzAwA2FwcAZWaWRlb3MCY3QGTEVHQUNZE29yaWdpbmFsX2R1cmF0aW9uX3MJMzAuMDYzMzY3AnRzD29lcF9wcm9ncmVzc2l2ZQA%3D&ccb=1-5&_nc_sid=b16ca8&efg=eyJ2ZW5jb2RlX3RhZyI6Im9lcF9oZCJ9&_nc_ohc=uWxFbr-FTy8AX9hoiZ9&_nc_ht=video-lim1-1.xx&oh=257cb5685dfe951a5f15e94150d8a4fa&oe=61282C30&_nc_rid=1fbb8e36a64d475&_nc_vts_prog=1&vts=1&_nc_vts_internal=1"
[download] Destination: X:\temp1\facebook\Atlanta Empire en Facebook Watch\Atlanta Empire en Facebook Watch (1878804305467115) [NAp].mp4
[download] 100% of 7.46MiB in 00:03
[Metadata] Adding metadata to "X:\temp1\facebook\Atlanta Empire en Facebook Watch\Atlanta Empire en Facebook Watch (1878804305467115) [NAp].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:X:\temp1\facebook\Atlanta Empire en Facebook Watch\Atlanta Empire en Facebook Watch (1878804305467115) [NAp].mp4" -map 0 -dn -c copy -metadata "title=Atlanta Empire en Facebook Watch" -metadata "date=20210509" -metadata "description=Relive  LEGENDS CUP 2017?  Watch it NOW at www.YouTube.com/MyLFL in HD with incredible access inside locker-rooms, huddles and sidelines." -metadata "synopsis=Relive  LEGENDS CUP 2017?  Watch it NOW at www.YouTube.com/MyLFL in HD with incredible access inside locker-rooms, huddles and sidelines." -metadata "purl=https://www.facebook.com/watch/?v=1878804305467115" -metadata "comment=https://www.facebook.com/watch/?v=1878804305467115" -metadata "artist=Atlanta Empire en Facebook Watch" "file:X:\temp1\facebook\Atlanta Empire en Facebook Watch\Atlanta Empire en Facebook Watch (1878804305467115) [NAp].temp.mp4"
[MoveFiles] Moving file "X:\temp1\facebook\Atlanta Empire en Facebook Watch\Atlanta Empire en Facebook Watch (1878804305467115) [NAp].mp4" to "X:\temp2\facebook\Atlanta Empire en Facebook Watch\Atlanta Empire en Facebook Watch (1878804305467115) [NAp].mp4"
```

**Comment by pukkandan** [comment] 2021-09-01 03:53
> If I provide a cookie file no metadata is correctly extracted except for the release date. If cookie file is not provided then all metadata is downloaded correctly except for the date.

You don't say exactly which metadata, but I assume its a duplicate of #453 

> Either way if the video's date is correctly or incorrectly extracted the file timestamps are always the current time.

File timestamp is set from the `Last-modified` header given by facebook (if any) and may not match the upload date


> For certain videos it doesn't download the highest quality available.
> %(height)s doesn't work, I get NA, which I supposed is tied to the first issue.

Fixed in https://github.com/yt-dlp/yt-dlp/commit/8a2d992389c37f5f99f5c74677f7900f1ae45f94

**Comment by werid** [comment] 2021-11-19 19:38
> > If I provide a cookie file no metadata is correctly extracted except for the release date. If cookie file is not provided then all metadata is downloaded correctly except for the date.
> 
> You don't say exactly which metadata, but I assume its a duplicate of #453

#453 is closed - is this considered fixed? I am having same problem as OP, and doesn't appear to be fixed in current release.

without cookies, title (and probably other metadata) is correct, and with cookies, title is "Facebook video #<facebook video id>"

**Comment by pukkandan** [comment] 2021-11-19 23:21
#453 was about upload_date, description etc. Since OP never gave more info on this, I assumed this is same. But I can reproduce that title is wrong without cookies

**Closed** 2022-01-11 16:49 UTC
Labels: site-bug, site:facebook
