### ISSUE TITLE
Twitter Download does not work for videos with age restriction

### ISSUE THREAD

**Issue by UnbreakCode** [yt-dlp/yt-dlp#6333] opened 2023-02-23 15:38 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I was trying to download an age restricted video from twitter with my twitter cookes from my browser using `--cookies-from-browser chrome`. yt-dlp still wasn't able to download the video.
Tweet: [https://twitter.com/6goettin/status/1619724321760616452](url)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Niclas\Desktop>yt-dlp -vU -f bestvideo+bestaudio/best https://twitter.com/6goettin/status/1619724321760616452 --cookies-from-browser chrome
[debug] Command-line config: ['-vU', '-f', 'bestvideo+bestaudio/best', 'https://twitter.com/6goettin/status/1619724321760616452', '--cookies-from-browser', 'chrome']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n4.4-178-g4b583e5425-20211012 (setts), ffprobe n4.4-178-g4b583e5425-20211012
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Niclas\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Niclas\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 3287 cookies from chrome
[debug] cookie version breakdown: {'v10': 3287, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[twitter] Extracting URL: https://twitter.com/6goettin/status/1619724321760616452
[debug] [twitter] Using GraphQL API (Auth = True)
[twitter] 1619724321760616452: Downloading JSON metadata
[debug] [twitter] Extracting from video info: 1619724243175866371
[twitter] 1619724321760616452: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, tbr, vbr, abr, filesize, fs_approx, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[info] 1619724243175866371: Downloading 1 format(s): http-950
[debug] Invoking http downloader on "https://video.twimg.com/ext_tw_video/1619724243175866371/pu/vid/400x848/vsHm9gFDxqq0kC9z.mp4?tag=12"
[download] Unable to open file: [Errno 22] Invalid argument: 'Ariel Nichtmerjungfrau｜ OF 3,50💲‼️ - @donambiento Das is auch wild. Flext mit nem dude der sein besten freund inklusive seine ganze familie ausgeknipst hat. Und das er genügend hitmans hat lol. Was is das leute also bitte. Sobald dat ganze endlich gerichtlich seinen lauf genommen ha, kan ich  ein paar andere sachen auftischen. [1619724243175866371].mp4.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'Ariel Nichtmerjungfrau｜ OF 3,50💲‼️ - @donambiento Das is auch wild. Flext mit nem dude der sein besten freund inklusive seine ganze familie ausgeknipst hat. Und das er genügend hitmans hat lol. Was is das leute also bitte. Sobald dat ganze endlich gerichtlich seinen lauf genommen ha, kan ich  ein paar andere sachen auftischen. [1619724243175866371].mp4.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: 'Ariel Nichtmerjungfrau｜ OF 3,50💲‼️ - @donambiento Das is auch wild. Flext mit nem dude der sein besten freund inklusive seine ganze familie ausgeknipst hat. Und das er genügend hitmans hat lol. Was is das leute also bitte. Sobald dat ganze endlich gerichtlich seinen lauf genommen ha, kan ich  ein paar andere sachen auftischen. [1619724243175866371].mp4.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: 'Ariel Nichtmerjungfrau｜ OF 3,50💲‼️ - @donambiento Das is auch wild. Flext mit nem dude der sein besten freund inklusive seine ganze familie ausgeknipst hat. Und das er genügend hitmans hat lol. Was is das leute also bitte. Sobald dat ganze endlich gerichtlich seinen lauf genommen ha, kan ich  ein paar andere sachen auftischen. [1619724243175866371].mp4.part'
Traceback (most recent call last):
  File "yt_dlp\utils.py", line 639, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 272, in download
  File "yt_dlp\downloader\common.py", line 228, in wrapper
  File "yt_dlp\utils.py", line 6109, in __iter__
  File "yt_dlp\downloader\common.py", line 221, in error_callback
  File "yt_dlp\utils.py", line 6117, in report_retry
  File "yt_dlp\downloader\common.py", line 230, in wrapper
  File "yt_dlp\downloader\common.py", line 241, in sanitize_open
  File "yt_dlp\utils.py", line 642, in sanitize_open
OSError: [Errno 22] Invalid argument: 'Ariel Nichtmerjungfrau｜ OF 3,50💲‼️ - @donambiento Das is auch wild. Flext mit nem dude der sein besten freund inklusive seine ganze familie ausgeknipst hat. Und das er genügend hitmans hat lol. Was is das leute also bitte. Sobald dat ganze endlich gerichtlich seinen lauf genommen ha, kan ich  ein paar andere sachen auftischen. [1619724243175866371].mp4.part'
```

**Comment by bashonly** [comment] 2023-02-23 16:22
The output filename is too long for Windows.

Workaround: add `-o "%(title).150B [%(id)s].%(ext)s"` to your command. And if that still doesn't work, try changing `150` to a lower value until it works

Duplicate of #5695

See also: #1136

**Closed by bashonly** 2023-02-23 16:22 UTC
Labels: bug, triage
