### ISSUE TITLE
Instagram fail even with login

### ISSUE THREAD

**Issue by wxolp** [yt-dlp/yt-dlp#2547] opened 2022-01-30 18:02 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Verbose log

~~~
[debug] Command-line config: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.instagram.com/p/CZVEugIPkVn/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.9.9 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 2021-06-30-git-de8e6e67e7-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[Instagram] Downloading login webpage
[Instagram] Logging in
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/CZVEugIPkVn/
[Instagram] CZVEugIPkVn: Downloading webpage
WARNING: [Instagram] unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
ERROR: [Instagram] CZVEugIPkVn: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "C:\python\lib\site-packages\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "C:\python\lib\site-packages\yt_dlp\extractor\instagram.py", line 347, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "C:\python\lib\site-packages\yt_dlp\extractor\common.py", line 1300, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "C:\python\lib\site-packages\yt_dlp\extractor\common.py", line 1195, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "C:\python\lib\site-packages\yt_dlp\extractor\common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
~~~

**Comment by MinePlayersPE** [comment] 2022-01-30 22:12
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2435 and https://github.com/yt-dlp/yt-dlp/issues/2522 ?

**Closed** 2022-01-30 23:31 UTC
Labels: site-bug, triage

**Comment by wxolp** [comment] 2022-01-31 01:08
Can you please give some more context? Why are you linking to closed issues? Do I need to use a different version or something?

**Comment by wxolp** [comment] 2022-01-31 01:11
OK looks like it was fixed here:

https://github.com/yt-dlp/yt-dlp/commit/013322a95e396ab21c8febc3e560d8a177c87f4a

but not on a release yet
