### ISSUE TITLE
rtve - "ValueError: not enough values to unpack (expected 2, got 1)"

### ISSUE THREAD

**Issue by nerviZida** [yt-dlp/yt-dlp#6925] opened 2023-04-26 22:00 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

spain

### Provide a description that is worded well enough to be understood

IN WINDOWS

[debug] Command-line config: ['https://www.rtve.es/alacarta/videos/documentos-tv/bajo-un-cielo-envenenado/6847021/', '-v']                                                                                                                      
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8                           
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)                                                          
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)                   
[debug] exe versions: ffmpeg git-2020-06-26-7447045, ffprobe git-2020-06-26-7447045                                     
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4                                                                                                                   
[debug] Proxy map: {'http': 'http://proxy.xxxx.xxx:8080', 'https': 'https://proxy.xxxx.xxx:8080', 'ftp': 'ftp://proxy.xxxx.xxx:8080'}                                                                                                           
[debug] Loaded 1786 extractors                                                                                          
[rtve.es:alacarta] Fetching manager info                                                                                
[rtve.es:alacarta] Extracting URL: https://www.rtve.es/alacarta/videos/documentos-tv/bajo-un-cielo-envenenado/6847021/  
[rtve.es:alacarta] 6847021: Downloading JSON metadata                                                                   
[rtve.es:alacarta] 6847021: Downloading url information                                                                 
ERROR: not enough values to unpack (expected 2, got 1)                                                                  
Traceback (most recent call last):                                                                                        
File "yt_dlp\YoutubeDL.py", line 1518, in wrapper                                                                       
File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info                                                                
File "yt_dlp\extractor\common.py", line 694, in extract                                                                 
File "yt_dlp\extractor\rtve.py", line 143, in _real_extract                                                             
File "yt_dlp\extractor\rtve.py", line 118, in _extract_png_formats                                                      
File "yt_dlp\extractor\rtve.py", line 81, in _decrypt_url                                                             
ValueError: not enough values to unpack (expected 2, got 1)   

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', '-i', '-r', '3000k', '-f', 'best[height<=720]/22/18/0', '--write-thumbnail', '--no-check-certificate', '--write-auto-sub', '--sub-lang', 'en,es', '--convert-subs', 'srt', '-o', '%(upload_date)s -%(title)s-%(id)s.%(ext)s', 'https://www.rtve.es/alacarta/videos/ciencia-maps/instituto-astrofisica-canarias/6817811/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-96-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Crypto-broken 2.6.1, certifi-2019.11.28, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
ERROR: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/rtve.py", line 143, in _real_extract
    formats = self._extract_png_formats(video_id)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/rtve.py", line 118, in _extract_png_formats
    for quality, video_url in self._decrypt_url(png):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/rtve.py", line 81, in _decrypt_url
    quality, url_data = text.split(b'%%')
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by nerviZida** [comment] 2023-04-26 22:08
[debug] Command-line config: ['-vU', '--proxy', 'socks5://127.0.0.1:9050', 'https://www.rtve.es/alacarta/videos/telediario-matinal/8-horas-26-04-23/6874451/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (debian*)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-6.0.0-0.deb11.6-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {'http': 'socks5://127.0.0.1:9050', 'https': 'socks5://127.0.0.1:9050'}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/rtve.py", line 143, in _real_extract
    formats = self._extract_png_formats(video_id)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/rtve.py", line 118, in _extract_png_formats
    for quality, video_url in self._decrypt_url(png):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/rtve.py", line 81, in _decrypt_url
    quality, url_data = text.split(b'%%')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by dirkf** [comment] 2023-04-26 22:42
There's an outstanding yt-dl PR https://github.com/ytdl-org/youtube-dl/pull/31241 for RTVE, but the author and I haven't managed to get it over the line.

This patch from the PR against the current stable yt-dlp extractor fixes your issue:
```diff
@@ -99,17 +77,12 @@
                 break
             data = encrypted_data.read(length)
             if chunk_type == b'tEXt':
-                alphabet_data, text = data.replace(b'\0', b'').split(b'#')
-                components = text.split(b'%%')
-                if len(components) < 2:
-                    components.insert(0, b'')
-                quality, url_data = components
-
+                alphabet_data, text = data.split(b'\0')
+                quality, url_data = text.split(b'%%')
                 alphabet = []
                 e = 0
                 d = 0
                 for l in alphabet_data.decode('iso-8859-1'):
-                # for l in _bytes_to_chr(alphabet_data):
                     if d == 0:
                         alphabet.append(l)
                         d = e = (e + 1) % 4
```

**Comment by bashonly** [comment] 2023-04-26 22:55
@dirkf that patch's diff looks inverted? I think it should be
```diff
diff --git a/yt_dlp/extractor/rtve.py b/yt_dlp/extractor/rtve.py
index a99a266c6..ba9121c62 100644
--- a/yt_dlp/extractor/rtve.py
+++ b/yt_dlp/extractor/rtve.py
@@ -77,8 +77,11 @@ def _decrypt_url(png):
                 break
             data = encrypted_data.read(length)
             if chunk_type == b'tEXt':
-                alphabet_data, text = data.split(b'\0')
-                quality, url_data = text.split(b'%%')
+                alphabet_data, text = data.replace(b'\0', b'').split(b'#')
+                components = text.split(b'%%')
+                if len(components) < 2:
+                    components.insert(0, b'')
+                quality, url_data = components
                 alphabet = []
                 e = 0
                 d = 0
```

Also this looks to be a duplicate of #1346, since the /alacarta/ link redirects in browser to /play/

**Closed** 2023-04-26 22:57 UTC
Labels: duplicate, site-bug, patch-available

**Comment by nerviZida** [comment] 2023-05-02 22:16
Many, many, many... THANK YOU
You saved me,

Really.

Thank you.

**Comment by victorterancas** [comment] 2023-05-17 21:30
> Many, many, many... THANK YOU You saved me,
> 
> Really.
> 
> Thank you.

Hi

I downloaded the last release of yt-dlp from [yt-dlp releases](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases) but i still have the same problem. Were you able to download from "rtve"?

Thank you.

**Comment by powerfrontier** [comment] 2023-06-18 13:13
I still have the same error. I tried the stable and nightly versions and apply the patch above, but nothing fix the problem:

`[rtve.es:infantil] Fetching manager info
[rtve.es:infantil] Extracting URL: https://www.rtve.es/infantil/serie/simon/video/robot-super-ferdi/6900044/
[rtve.es:infantil] 6900044: Downloading JSON metadata
[rtve.es:infantil] 6900044: Downloading url information
ERROR: not enough values to unpack (expected 2, got 1)`

**Comment by nerviZida** [comment] 2023-08-03 19:54
**Translated by Argos Translate**
Original version in your email.

Hi.

I'm sorry for the delay, but I haven't been through much.

I have no idea, but what dirkf and bashonly are telling us is that we have to compile the yt-dlp by applying the patch they tell us.

I see you've got an app on github, so I don't understand your question. 
But in order not to take anything for granted (it is not the account holder that the post has written), and without the urge to offend you, here goes a mock and simple explanation.

I've done it the way Bashonly poses and it works.

You have to download the source code, and in the "yt-dlp-master/yt-dlp-master/yt_dlp/extractor" folder you have the "rtve.py" file where you have to remove the lines marked with a "-" and add the marked with a "+".

And then compile the executable.

python3 -m pip install -U pyinstaller -r requirements.txt
python3 devscripts/make_lazy_extractors.py
python3 pyinst.py --onefile

I compile it for linux and now it's working. I don't know if it would work for you, but if you want, I'll try to pass my executable or rtve.py file.

Adiós.

**Comment by spinbilly** [comment] 2025-01-15 10:14
In 2025, downloading videos from www.rtve.es still does not work

**Comment by meGAmeS1** [comment] 2025-03-31 09:58
@spinbilly Sadly the owners of the repo are a bit overwhelmed by the work on extractors and don't merge code easily. I did the work to add RTVE Play compatibility a while ago, you may show your support by putting a 👍 or a ❤️ on the first post here : https://github.com/yt-dlp/yt-dlp/pull/10388 (and if anyone want to use what I did, you can clone the repo and try it for yourself, even though it's harder than simply use the released and packaged versions of yt-dlp)
