### ISSUE TITLE
YouTube playlist "FileNotFoundError"

### ISSUE THREAD

**Issue by Wilann** [yt-dlp/yt-dlp#2904] opened 2022-02-27 17:13 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Description

I'm trying to download a playlist of videos using the below command format: 
```
 yt-dlp -i URL -o "%(upload_date)s - %(title)s" --download-archive "archive.txt" --config-location config_video.txt 
```

Where `config_video.txt` is:
```
--merge-output mp4
--embed-thumbnail
```

For some reason, I'm getting a `FileNotFoundError`. There are 172 videos in the playlist - I've attempted to download videos 1-6, and only the 1st one downloads successfully. Videos 2-6 have files with extensions: 
- `.f248.webm`
- `.f251.webm`
- `.temp.mp4`
- `.webp`
before reaching the error, where yt-dlp them moves on to the next video. 
The full verbose log can be seem below with exact paths. If anyone could give me a hint on what the issue is, I would greatly appreciate it - thank you! 

### Verbose log

```shell
yt-dlp -i "https://www.youtube.com/playlist?list=PLpVpBRIlzWuBhafF49DkSHb1RMyrtv390" -o "/Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/%(upload_date)s - %(title)s" --download-archive "/Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/archive.txt" --config-location /Volumes/Palkia/ytdlp/config_video.txt --verbose

[debug] Command-line config: ['-i', 'https://www.youtube.com/playlist?list=PLpVpBRIlzWuBhafF49DkSHb1RMyrtv390', '-o', '/Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/%(upload_date)s - %(title)s', '--download-archive', '/Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/archive.txt', '--config-location', '/Volumes/Palkia/ytdlp/config_video.txt', '--verbose']
[debug] | Config "/Volumes/Palkia/ytdlp/config_video.txt": ['--merge-output', 'mp4', '--embed-thumbnail']
[debug] User config "/Users/wilsonchan/.config/yt-dlp/config": ['--add-metadata']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.7.4 (CPython 64bit) - Darwin-21.2.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file '/Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/archive.txt'
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLpVpBRIlzWuBhafF49DkSHb1RMyrtv390
[youtube:tab] PLpVpBRIlzWuBhafF49DkSHb1RMyrtv390: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=PLpVpBRIlzWuBhafF49DkSHb1RMyrtv390
[youtube:tab] PLpVpBRIlzWuBhafF49DkSHb1RMyrtv390: Downloading API JSON with unavailable videos
[download] Downloading playlist: Xenoblade Chronicles 2: All Story Cutscenes - ENGLISH
[youtube:tab] PLpVpBRIlzWuBhafF49DkSHb1RMyrtv390 page 1: Downloading API JSON
[debug] Skipping writing playlist thumbnail
[youtube:tab] playlist Xenoblade Chronicles 2: All Story Cutscenes - ENGLISH: Downloading 172 videos
[download] Downloading video 1 of 172
[download] Xenoblade Chronicles 2 Cutscene 001 - A Boy and the Sea - ENGLISH has already been recorded in the archive
[download] Downloading video 2 of 172
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=pMb2KAhUB-Q
[youtube] pMb2KAhUB-Q: Downloading webpage
[youtube] pMb2KAhUB-Q: Downloading android player API JSON
[youtube] pMb2KAhUB-Q: Downloading MPD manifest
[youtube] pMb2KAhUB-Q: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] pMb2KAhUB-Q: Downloading 1 format(s): 248+251
Deleting existing file /Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/20171227 - Xenoblade Chronicles 2 Cutscene 002 - The Legend of Elysium - ENGLISH.webp
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: /Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/20171227 - Xenoblade Chronicles 2 Cutscene 002 - The Legend of Elysium - ENGLISH.webp
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1646003174/ei/hq8bYuuCDPC2ir4Ppb-dkAY/ip/216.58.16.107/id/a4c6f628085407e4/source/youtube/requiressl/yes/playback_host/rr8---sn-qpnugpc0uxa-tu1l.googlevideo.com/mh/1b/mm/31%2C29/mn/sn-qpnugpc0uxa-tu1l%2Csn-tt1eln7e/ms/au%2Crdu/mv/m/mvi/8/pl/17/tx/24070731/txs/24070731%2C24070734/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/793750/spc/4ocVC8KUWN6mVfnP60TlEarqlEiq/vprv/1/mt/1645981025/fvip/3/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cspc%2Cvprv%2Citag/sig/AOq0QJ8wRgIhANzcNdAolu760phOZqzVCGkAvZMJIJ7BCYJiw5ICdvQFAiEArMoO1aHTRKzCXGlNnZcCIFHANod6xVFVB3GISCimD1A%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhAId0x2Y0lQdBwMSnTkjziikVodfLEYKjWcOAw6EYsn_wAiEAnPT7qF6iEdkezfDdjJAugXyyRWVbketlmf30j9Q5SDo%3D"
[download] /Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/20171227 - Xenoblade Chronicles 2 Cutscene 002 - The Legend of Elysium - ENGLISH.f248.webm has already been downloaded
[download] 100% of 63.30MiB
[debug] Invoking downloader on "https://rr8---sn-qpnugpc0uxa-tu1l.googlevideo.com/videoplayback?expire=1646003174&ei=hq8bYt6wOYreigTMyJ34BA&ip=216.58.16.107&id=o-AGyJSutV-GvrPWR_QphB5piXKPELWuRzha3O1sKtPY2v&itag=251&source=youtube&requiressl=yes&mh=1b&mm=31%2C29&mn=sn-qpnugpc0uxa-tu1l%2Csn-tt1e7n7k&ms=au%2Crdu&mv=m&mvi=8&pl=17&initcwndbps=793750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=5318212&otfp=1&dur=342.961&lmt=1564397987687672&mt=1645981025&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIgVVmQlg_IAGcxtL3Auj-63cz6P-GXs94FbBnF0IIuqNsCIQCNDs8z-_fTiibO59TOXpzIHRNsd-0XN_jh57xnL6H8nw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgc4PyQCiRA96Y8np9VUGm7tGlLDZ29-aCyUMVBtC6XCMCIQCYzw4PDCaaQ8aV0_F30iK8VO3nGMQGIOLjbbSDLZJVXA%3D%3D"
[download] /Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/20171227 - Xenoblade Chronicles 2 Cutscene 002 - The Legend of Elysium - ENGLISH.f251.webm has already been downloaded
[download] 100% of 5.07MiB
[Merger] Merging formats into "/Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/20171227 - Xenoblade Chronicles 2 Cutscene 002 - The Legend of Elysium - ENGLISH.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/20171227 - Xenoblade Chronicles 2 Cutscene 002 - The Legend of Elysium - ENGLISH.f248.webm' -i 'file:/Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/20171227 - Xenoblade Chronicles 2 Cutscene 002 - The Legend of Elysium - ENGLISH.f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:/Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/20171227 - Xenoblade Chronicles 2 Cutscene 002 - The Legend of Elysium - ENGLISH.temp.mp4'
[debug] ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.27)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_4 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, matroska,webm, from 'file:/Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/20171227 - Xenoblade Chronicles 2 Cutscene 002 - The Legend of Elysium - ENGLISH.f248.webm':
  Metadata:
    encoder         : google/video-file
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 65 
                    : Segment-Durations-Ms: 5333,5334,5200,5466,5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),533 
                    :  
                    : 
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:/Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/20171227 - Xenoblade Chronicles 2 Cutscene 002 - The Legend of Elysium - ENGLISH.f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:05:42.96, start: -0.007000, bitrate: 124 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
[mp4 @ 0x7fc0e1025c00] track 1: codec frame size is not set
Output #0, mp4, to 'file:/Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/20171227 - Xenoblade Chronicles 2 Cutscene 002 - The Legend of Elysium - ENGLISH.temp.mp4':
  Metadata:
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 65 
                    : Segment-Durations-Ms: 5333,5334,5200,5466,5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),533 
                    :  
                    : 
    encoder         : Lavf58.45.100
    Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 30 fps, 30 tbr, 16k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp4 @ 0x7fc0e1025c00] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 85328 >= 85328
av_interleaved_write_frame(): Invalid argument
[mp4 @ 0x7fc0e1025c00] Starting second pass: moving the moov atom to the beginning of the file
frame=  162 fps=0.0 q=-1.0 Lsize=     616kB time=00:00:05.34 bitrate= 944.7kbits/s speed= 854x    
video:555kB audio:79kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
ERROR: Conversion failed!
Traceback (most recent call last):
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3296, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/postprocessor/common.py", line 117, in wrapper
    return func(self, info)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 830, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 296, in run_ffmpeg_multiple_files
    [(out_path, opts)], **kwargs)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 333, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

[Metadata] Adding metadata to "/Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/20171227 - Xenoblade Chronicles 2 Cutscene 002 - The Legend of Elysium - ENGLISH.mp4"
ERROR: [Errno 2] No such file or directory: '/Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/20171227 - Xenoblade Chronicles 2 Cutscene 002 - The Legend of Elysium - ENGLISH.mp4'
Traceback (most recent call last):
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1517, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 2607, in process_video_result
    self.process_info(new_info)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3159, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3336, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3323, in run_all_pps
    info = self.run_pp(pp, info)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 3296, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/postprocessor/common.py", line 117, in wrapper
    return func(self, info)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 713, in run
    itertools.chain(self._options(info['ext']), *options))
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 296, in run_ffmpeg_multiple_files
    [(out_path, opts)], **kwargs)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 302, in real_run_ffmpeg
    os.stat(encodeFilename(path)).st_mtime for path, _ in input_path_opts if path)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 302, in <genexpr>
    os.stat(encodeFilename(path)).st_mtime for path, _ in input_path_opts if path)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/Palkia/Games/Cutscenes (youtube-dl)/Xenoblade Chronicles 2 (youtube-dl)/20171227 - Xenoblade Chronicles 2 Cutscene 002 - The Legend of Elysium - ENGLISH.mp4'
```
```

**Comment by pukkandan** [comment] 2022-02-27 22:28
> [mp4 @ 0x7fc0e1025c00] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 85328 >= 85328
> ...
> yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

Duplicate of https://github.com/yt-dlp/yt-dlp/issues/871

**Closed by pukkandan** 2022-02-27 22:28 UTC
Labels: site-bug, triage

**Comment by Wilann** [comment] 2022-02-27 22:31
Thanks for pointing me to the right issue - will it be fixed in the next yt-dlp version?

**Comment by pukkandan** [comment] 2022-02-27 22:37
It is not a yt-dlp issue. Read the conversation on the issue I linked

**Comment by Wilann** [comment] 2022-02-28 00:20
I did read - sorry, I thought a ffmpeg would be updated to a particular version when updating yt-dlp
