### ISSUE TITLE
Getting ERROR: [youtube] tJ51nR4-tLs: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

### ISSUE THREAD

**Issue by PragyanCoder** [yt-dlp/yt-dlp#10707] opened 2024-08-10 09:34 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi Team When I try to use yt-dlp for YouTube videos I get a error
ERROR: [youtube] tJ51nR4-tLs: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.youtube.com/watch?v=x3dGHdUorAk
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=x3dGHdUorAk']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-1022-aws-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2020.06.20, mutagen-1.47.0, pyxattr-0.7.2, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=x3dGHdUorAk
[youtube] x3dGHdUorAk: Downloading webpage
[youtube] x3dGHdUorAk: Downloading ios player API JSON
[youtube] x3dGHdUorAk: Downloading web creator player API JSON
ERROR: [youtube] x3dGHdUorAk: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py",
line 4358, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1263, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by Grub4K** [comment] 2024-08-10 09:49
Duplicate of #10128

**Closed by Grub4K** 2024-08-10 09:49 UTC
Labels: question

**Comment by OnClickListener2048** [comment] 2024-08-12 12:21
known issue but we can't do anything about it

**Comment by CN-CODEGOD** [comment] 2024-08-22 14:03
Having the same problem,there is two posible reason of this error,youtube have blocking your acc or your ip; 
i solve the problem by changing vpn into diiferent ip

**Comment by Luke-sumAll** [comment] 2024-08-26 03:25
> Having the same problem,there is two posible reason of this error,youtube have blocking your acc or your ip; i solve the problem by changing vpn into diiferent ip

Hello～I'm experiencing the same problem, can you please tell me the exact steps you took to set up the proxy?Thank you！
