### ISSUE TITLE
Reddit: ERROR: unable to download video data

### ISSUE THREAD

**Issue by RingoTheDog** [yt-dlp/yt-dlp#2936] opened 2022-03-03 19:29 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Description

URL:  
https://www.reddit.com/r/ukraine/comments/t5ug4p/the_entire_staff_of_the_russian_tv_channel_the/

fails with:
ERROR: unable to download video data: [Errno 2] No such file or directory:

### Verbose log

```shell
>yt-dlp.py -v "https://www.reddit.com/r/ukraine/comments/t5ug4p/the_entire_staff_of_the_russian_tv_channel_the/"
[debug] Command-line config: ['-v', 'https://www.reddit.com/r/ukraine/comments/t5ug4p/the_entire_staff_of_the_russian_tv_channel_the/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (zip)
[debug] Python version 3.6.6 (CPython 64bit) - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [Reddit] Extracting URL: https://www.reddit.com/r/ukraine/comments/t5ug4p/the_entire_staff_of_the_russian_tv_channel_the/
[Reddit] t5ug4p: Downloading JSON metadata
[Reddit] t5ug4p: Downloading m3u8 information
[Reddit] t5ug4p: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] cjg9ka7ov6l81: Downloading 1 format(s): hls-597+dash-audio_0_123274
[debug] Invoking downloader on "https://v.redd.it/cjg9ka7ov6l81/HLS_270.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 17
[download] Destination: The Entire staff of the Russian TV channel “the rain” resigned during a live stream with last words - “no war” and then played “swan lake” ballet video (just like they did on all USSR tv channels when it suddenly collapsed) [cjg9ka7ov6l81].fhls-597.mp4
ERROR: unable to download video data: [Errno 2] No such file or directory: 'The Entire staff of the Russian TV channel “the rain” resigned during a live stream with last words - “no war” and then played “swan lake” ballet video (just like they did on all USSR tv channels when it suddenly collapsed) [cjg9ka7ov6l81].fhls-597.mp4.ytdl'
Traceback (most recent call last):
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\YoutubeDL.py", line 3068, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\YoutubeDL.py", line 2801, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\downloader\common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\downloader\hls.py", line 145, in real_download
    self._prepare_and_start_frag_download(ctx, info_dict)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\downloader\fragment.py", line 90, in _prepare_and_start_frag_download
    self._prepare_frag_download(ctx)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\downloader\fragment.py", line 215, in _prepare_frag_download
    self._write_ytdl_file(ctx)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\downloader\fragment.py", line 110, in _write_ytdl_file
    frag_index_stream, _ = self.sanitize_open(self.ytdl_filename(ctx['filename']), 'w')
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\downloader\common.py", line 218, in sanitize_open
    return sanitize_open(filename, open_mode)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\utils.py", line 668, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
FileNotFoundError: [Errno 2] No such file or directory: 'The Entire staff of the Russian TV channel “the rain” resigned during a live stream with last words - “no war” and then played “swan lake” ballet video (just like they did on all USSR tv channels when it suddenly collapsed) [cjg9ka7ov6l81].fhls-597.mp4.ytdl'
```

**Comment by pukkandan** [comment] 2022-03-04 11:39
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1136

**Closed by pukkandan** 2022-03-04 11:39 UTC
Labels: site-bug, triage
