### ISSUE TITLE
--download-sections feature starts downloading 10 seconds before time given

### ISSUE THREAD

**Issue by NicolasAili** [yt-dlp/yt-dlp#5981] opened 2023-01-06 23:50 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When I download using the --download-sections option, it seems that the download starts 10 seconds before the time given.

For instance, when I run :
yt-dlp https://www.youtube.com/watch?v=mxXvV2ww9Xs --download-sections *0:10-0:20

The video downloaded start at the beginning (0:00) and not 0:10. Therefore, the video length is 20 seconds and not 10, as it should be.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=mxXvV2ww9Xs', '-vU', '--download-sections', '*0:10-0:20']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-135-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: certifi-2019.11.28, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=mxXvV2ww9Xs
[youtube] mxXvV2ww9Xs: Downloading webpage
[youtube] mxXvV2ww9Xs: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] mxXvV2ww9Xs: Downloading 1 format(s): 248+251
[info] mxXvV2ww9Xs: Downloading 1 time ranges: 10.0-20.0
[debug] Invoking ffmpeg downloader on "https://rr5---sn-25ge7nz6.googlevideo.com/videoplayback?expire=1673070566&ei=hrO4Y8TpI7WFvdIPtpiOmA8&ip=185.228.228.118&id=o-ABQmMKPgvipj_eSK2WEVO3KNQXe2jbPfDGHg6ziUEqVs&itag=248&source=youtube&requiressl=yes&mh=gr&mm=31%2C29&mn=sn-25ge7nz6%2Csn-25glenld&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=700000&spc=zIddbDmaVXv8cCQLHVjN3VzPrE7FDn0&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=13007123&dur=85.252&lmt=1453173214615203&mt=1673048736&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKgs4eB7AekCJUHJRuuNLFg981xojj0w3LMriP1loPXNAiEAjIE6fb1kz7Pytu8Ep23EWzpeGGgT1GDD4gL1b9OO4cc%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgXYfAYfzUPMES0K8p0TSr9VY-BpZ6RsQw1DZu2_ZrddoCIH2ee6TJvoot13CnzwSiE907KBKiMqful89pj0aZ6d7K", "https://rr5---sn-25ge7nz6.googlevideo.com/videoplayback?expire=1673070566&ei=hrO4Y8TpI7WFvdIPtpiOmA8&ip=185.228.228.118&id=o-ABQmMKPgvipj_eSK2WEVO3KNQXe2jbPfDGHg6ziUEqVs&itag=251&source=youtube&requiressl=yes&mh=gr&mm=31%2C29&mn=sn-25ge7nz6%2Csn-25glenld&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=700000&spc=zIddbDmaVXv8cCQLHVjN3VzPrE7FDn0&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=1034206&dur=85.281&lmt=1453173068391584&mt=1673048736&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgLuSStAg4-v3x0hPYeyzOBgT7owGd5kFccdLX9-1pkaUCIF6WSTXRJJCIDDu6wCjtGvJwVCwOrpCe7aBPtMGEwmU8&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgXYfAYfzUPMES0K8p0TSr9VY-BpZ6RsQw1DZu2_ZrddoCIH2ee6TJvoot13CnzwSiE907KBKiMqful89pj0aZ6d7K"
[download] Destination: One Minute Song [mxXvV2ww9Xs].webm
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.54 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
' -ss 10.0 -t 10.0 -i 'https://rr5---sn-25ge7nz6.googlevideo.com/videoplayback?expire=1673070566&ei=hrO4Y8TpI7WFvdIPtpiOmA8&ip=185.228.228.118&id=o-ABQmMKPgvipj_eSK2WEVO3KNQXe2jbPfDGHg6ziUEqVs&itag=248&source=youtube&requiressl=yes&mh=gr&mm=31%2C29&mn=sn-25ge7nz6%2Csn-25glenld&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=700000&spc=zIddbDmaVXv8cCQLHVjN3VzPrE7FDn0&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=13007123&dur=85.252&lmt=1453173214615203&mt=1673048736&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKgs4eB7AekCJUHJRuuNLFg981xojj0w3LMriP1loPXNAiEAjIE6fb1kz7Pytu8Ep23EWzpeGGgT1GDD4gL1b9OO4cc%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgXYfAYfzUPMES0K8p0TSr9VY-BpZ6RsQw1DZu2_ZrddoCIH2ee6TJvoot13CnzwSiE907KBKiMqful89pj0aZ6d7K' -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.54 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
' -ss 10.0 -t 10.0 -i 'https://rr5---sn-25ge7nz6.googlevideo.com/videoplayback?expire=1673070566&ei=hrO4Y8TpI7WFvdIPtpiOmA8&ip=185.228.228.118&id=o-ABQmMKPgvipj_eSK2WEVO3KNQXe2jbPfDGHg6ziUEqVs&itag=251&source=youtube&requiressl=yes&mh=gr&mm=31%2C29&mn=sn-25ge7nz6%2Csn-25glenld&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=700000&spc=zIddbDmaVXv8cCQLHVjN3VzPrE7FDn0&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=1034206&dur=85.281&lmt=1453173068391584&mt=1673048736&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgLuSStAg4-v3x0hPYeyzOBgT7owGd5kFccdLX9-1pkaUCIF6WSTXRJJCIDDu6wCjtGvJwVCwOrpCe7aBPtMGEwmU8&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgXYfAYfzUPMES0K8p0TSr9VY-BpZ6RsQw1DZu2_ZrddoCIH2ee6TJvoot13CnzwSiE907KBKiMqful89pj0aZ6d7K' -c copy -map 0:0 -map 1:0 -f webm 'file:One Minute Song [mxXvV2ww9Xs].webm.part'
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[tcp @ 0x55bd5467f480] Starting connection attempt to 74.125.168.74 port 443
[tcp @ 0x55bd5467f480] Successfully connected to 74.125.168.74 port 443
[tcp @ 0x55bd54940b40] Starting connection attempt to 74.125.168.74 port 443
[tcp @ 0x55bd54940b40] Successfully connected to 74.125.168.74 port 443
Input #0, matroska,webm, from 'https://rr5---sn-25ge7nz6.googlevideo.com/videoplayback?expire=1673070566&ei=hrO4Y8TpI7WFvdIPtpiOmA8&ip=185.228.228.118&id=o-ABQmMKPgvipj_eSK2WEVO3KNQXe2jbPfDGHg6ziUEqVs&itag=248&source=youtube&requiressl=yes&mh=gr&mm=31%2C29&mn=sn-25ge7nz6%2Csn-25glenld&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=700000&spc=zIddbDmaVXv8cCQLHVjN3VzPrE7FDn0&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=13007123&dur=85.252&lmt=1453173214615203&mt=1673048736&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKgs4eB7AekCJUHJRuuNLFg981xojj0w3LMriP1loPXNAiEAjIE6fb1kz7Pytu8Ep23EWzpeGGgT1GDD4gL1b9OO4cc%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgXYfAYfzUPMES0K8p0TSr9VY-BpZ6RsQw1DZu2_ZrddoCIH2ee6TJvoot13CnzwSiE907KBKiMqful89pj0aZ6d7K':
  Metadata:
    encoder         : google
  Duration: 00:01:25.25, start: 0.000000, bitrate: 1220 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), 1 reference frame, yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 1k tbn, 1k tbc (default)
[tcp @ 0x55bd5492e440] Starting connection attempt to 74.125.168.74 port 443
[tcp @ 0x55bd5492e440] Successfully connected to 74.125.168.74 port 443
Input #1, matroska,webm, from 'https://rr5---sn-25ge7nz6.googlevideo.com/videoplayback?expire=1673070566&ei=hrO4Y8TpI7WFvdIPtpiOmA8&ip=185.228.228.118&id=o-ABQmMKPgvipj_eSK2WEVO3KNQXe2jbPfDGHg6ziUEqVs&itag=251&source=youtube&requiressl=yes&mh=gr&mm=31%2C29&mn=sn-25ge7nz6%2Csn-25glenld&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=700000&spc=zIddbDmaVXv8cCQLHVjN3VzPrE7FDn0&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=1034206&dur=85.281&lmt=1453173068391584&mt=1673048736&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgLuSStAg4-v3x0hPYeyzOBgT7owGd5kFccdLX9-1pkaUCIF6WSTXRJJCIDDu6wCjtGvJwVCwOrpCe7aBPtMGEwmU8&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgXYfAYfzUPMES0K8p0TSr9VY-BpZ6RsQw1DZu2_ZrddoCIH2ee6TJvoot13CnzwSiE907KBKiMqful89pj0aZ6d7K':
  Metadata:
    encoder         : google
  Duration: 00:01:25.28, start: -0.007000, bitrate: 97 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp, delay 312 (default)
Output #0, webm, to 'file:One Minute Song [mxXvV2ww9Xs].webm.part':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0(eng): Video: vp9 (Profile 0), 1 reference frame, yuv420p(tv, bt709/unknown/unknown), 1920x1080 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 29.97 fps, 29.97 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp, delay 312 (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
Automatically inserted bitstream filter 'vp9_superframe'; args=''
frame=   38 fps=0.0 q=-1.0 size=      77kB time=-00:00:03.42 bitrate=N/A speed=Nframe=   51 fps= 36 q=-1.0 size=     268kB time=-00:00:02.99 bitrate=N/A speed=Nframe=   67 fps= 35 q=-1.0 size=     268kB time=-00:00:02.45 bitrate=N/A speed=Nframe=  161 fps= 65 q=-1.0 size=     762kB time=00:00:00.68 bitrate=9165.3kbits/frame=  172 fps= 56 q=-1.0 size=     762kB time=00:00:01.04 bitrate=5972.8kbits/frame=  271 fps= 65 q=-1.0 size=     864kB time=00:00:04.34 bitrate=1627.2kbits/frame=  321 fps= 64 q=-1.0 size=    1460kB time=00:00:06.02 bitrate=1986.0kbits/frame=  437 fps= 72 q=-1.0 size=    1460kB time=00:00:09.88 bitrate=1209.3kbits/No more output streams to write to, finishing.
frame=  440 fps= 72 q=-1.0 Lsize=    2044kB time=00:00:09.98 bitrate=1676.7kbits/s speed=1.62x    
video:1732kB audio:302kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.516232%
Input file #0 (https://rr5---sn-25ge7nz6.googlevideo.com/videoplayback?expire=1673070566&ei=hrO4Y8TpI7WFvdIPtpiOmA8&ip=185.228.228.118&id=o-ABQmMKPgvipj_eSK2WEVO3KNQXe2jbPfDGHg6ziUEqVs&itag=248&source=youtube&requiressl=yes&mh=gr&mm=31%2C29&mn=sn-25ge7nz6%2Csn-25glenld&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=700000&spc=zIddbDmaVXv8cCQLHVjN3VzPrE7FDn0&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=13007123&dur=85.252&lmt=1453173214615203&mt=1673048736&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKgs4eB7AekCJUHJRuuNLFg981xojj0w3LMriP1loPXNAiEAjIE6fb1kz7Pytu8Ep23EWzpeGGgT1GDD4gL1b9OO4cc%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgXYfAYfzUPMES0K8p0TSr9VY-BpZ6RsQw1DZu2_ZrddoCIH2ee6TJvoot13CnzwSiE907KBKiMqful89pj0aZ6d7K):
  Input stream #0:0 (video): 441 packets read (1773806 bytes); 
  Total: 441 packets (1773806 bytes) demuxed
Input file #1 (https://rr5---sn-25ge7nz6.googlevideo.com/videoplayback?expire=1673070566&ei=hrO4Y8TpI7WFvdIPtpiOmA8&ip=185.228.228.118&id=o-ABQmMKPgvipj_eSK2WEVO3KNQXe2jbPfDGHg6ziUEqVs&itag=251&source=youtube&requiressl=yes&mh=gr&mm=31%2C29&mn=sn-25ge7nz6%2Csn-25glenld&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=700000&spc=zIddbDmaVXv8cCQLHVjN3VzPrE7FDn0&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=1034206&dur=85.281&lmt=1453173068391584&mt=1673048736&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgLuSStAg4-v3x0hPYeyzOBgT7owGd5kFccdLX9-1pkaUCIF6WSTXRJJCIDDu6wCjtGvJwVCwOrpCe7aBPtMGEwmU8&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgXYfAYfzUPMES0K8p0TSr9VY-BpZ6RsQw1DZu2_ZrddoCIH2ee6TJvoot13CnzwSiE907KBKiMqful89pj0aZ6d7K):
  Input stream #1:0 (audio): 1000 packets read (309149 bytes); 
  Total: 1000 packets (309149 bytes) demuxed
Output file #0 (file:One Minute Song [mxXvV2ww9Xs].webm.part):
  Output stream #0:0 (video): 440 packets muxed (1773722 bytes); 
  Output stream #0:1 (audio): 999 packets muxed (308870 bytes); 
  Total: 1439 packets (2082592 bytes) muxed
[AVIOContext @ 0x55bd548e5000] Statistics: 6 seeks, 17 writeouts
[AVIOContext @ 0x55bd546866c0] Statistics: 2029444 bytes read, 1 seeks
[AVIOContext @ 0x55bd548e1e00] Statistics: 327680 bytes read, 0 seeks
[download] 100% of    2.00MiB in 00:00:07 at 256.51KiB/s
```

**Comment by bashonly** [comment] 2023-01-07 00:05
Duplicate of #4216:

> Video files cannot be cut at exact timestamps without re-encoding. `--download-sections` do not re-encode by default. To make it do so, use `--force-keyframes-at-cuts`

See pinned issues

**Closed by bashonly** 2023-01-07 00:05 UTC
Labels: duplicate, question
