### ISSUE TITLE
TypeError: '<' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by bani6809** [yt-dlp/yt-dlp#3016] opened 2022-03-10 10:38 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

With 2022.03.08.1 I get this crash:
TypeError: '<' not supported between instances of 'float' and 'str'

Version 2022.02.04 does not crash, and downloads fine.

### Verbose log

```shell
[debug] Command-line config: ['--ignore-config', '--config-location', 'c:\\Users\\xyz\\yt-dlp.conf', '--proxy', '', '-v', 'https://www.youtube.com/watch?v=z4TVnbuy4Lw']
[debug] | Config "c:\Users\xyz\yt-dlp.conf": ['-v', '-i', '-o', '%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s - (%(duration)ss) [%(resolution)s] [%(id)s].%(ext)s', '--playlist-end', '100', '--sleep-requests', '1', '--sleep-interval', '2', '--max-sleep-interval', '5', '--throttled-rate', '600K', '--encoding', 'utf-8', '--download-archive', 'youtube-dl-archive.txt', '--no-overwrites', '--prefer-ffmpeg', '--merge-output-format', 'mkv', '--write-sub', '--all-subs', '--convert-subs', 'srt', '--embed-subs', '--add-metadata', '--write-description', '--write-annotations', '--write-all-thumbnails', '--write-info-json', '--format', '(bestvideo[vcodec^=av01][height>=4320][fps>30]/bestvideo[vcodec=vp9.2][height>=4320][fps>30]/bestvideo[vcodec=vp9][height>=4320][fps>30]/bestvideo[vcodec^=av01][height>=2160][fps>30]/bestvideo[vcodec=vp9.2][height>=2160][fps>30]/bestvideo[vcodec=vp9][height>=2160][fps>30]/bestvideo[vcodec^=av01][height>=1440][fps>30]/bestvideo[vcodec=vp9.2][height>=1440][fps>30]/bestvideo[vcodec=vp9][height>=1440][fps>30]/bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec=vp9.2][height>=1080][fps>30]/bestvideo[vcodec=vp9][height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec=vp9.2][height>=1080]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec=vp9.2][height>=720][fps>30]/bestvideo[vcodec=vp9][height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec=vp9.2][height>=720]/bestvideo[vcodec=vp9][height>=720]/bestvideo[height>=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best', '--proxy', '', '--rm-cache-dir', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3627.1 Safari/537.36', '--cookies', 'youtube-cookies.txt', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref utf-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 2021-12-06-git-ef00d40e32-full_build-www.gyan.dev (setts), ffprobe 2021-12-06-git-ef00d40e32-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file 'youtube-dl-archive.txt'
Removing cache dir C:\Users\xyz\.cache\yt-dlp ..
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=z4TVnbuy4Lw
[youtube] z4TVnbuy4Lw: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] Sleeping 1.0 seconds ...
[youtube] z4TVnbuy4Lw: Downloading android player API JSON
[youtube] Sleeping 1.0 seconds ...
[youtube] z4TVnbuy4Lw: Downloading player 6d3a4914
[debug] Saving youtube-nsig.6d3a4914 to cache
[debug] [youtube] Decrypted nsig v8iXvl6p9CqK6NORn => oWKNT2CTZ1NR5w
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: en
[info] z4TVnbuy4Lw: Downloading 1 format(s): 399+251
[info] Writing video description to: NileRed Shorts (UCA0mlN90EHCizvo101nbr-g)\20220308 - This is what gallium does to aluminum - (182s) [1080x1920] [z4TVnbuy4Lw].description
[info] Writing video subtitles to: NileRed Shorts (UCA0mlN90EHCizvo101nbr-g)\20220308 - This is what gallium does to aluminum - (182s) [1080x1920] [z4TVnbuy4Lw].en.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=z4TVnbuy4Lw&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xctw&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1646933633&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxoaf&signature=5DA9F8B946E1C7E69DF606EA9EB531F84EB4AB3F.DF0E11BA97D8DC421D88887BB6368043852E4CF6&key=yt8&lang=en&fmt=vtt"
[download] Destination: NileRed Shorts (UCA0mlN90EHCizvo101nbr-g)\20220308 - This is what gallium does to aluminum - (182s) [1080x1920] [z4TVnbuy4Lw].en.vtt
[download] 1.00KiB at 124.96KiB/s (00:00)ERROR: '<' not supported between instances of 'float' and 'str'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1473, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1529, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2638, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2890, in process_info
  File "yt_dlp\YoutubeDL.py", line 3859, in _write_subtitles
  File "yt_dlp\YoutubeDL.py", line 2835, in dl
  File "yt_dlp\downloader\common.py", line 453, in download
  File "yt_dlp\downloader\http.py", line 384, in real_download
  File "yt_dlp\downloader\http.py", line 334, in download
TypeError: '<' not supported between instances of 'float' and 'str'
```

**Comment by dirkf** [comment] 2022-03-10 11:07
Duplicate of #2996.

**Closed** 2022-03-10 11:11 UTC
Labels: bug, triage
