### ISSUE TITLE
yt_dlp.utils.ExtractorError: [facebook] 244378855011108: No video formats found!

### ISSUE THREAD

**Issue by mayasl** [yt-dlp/yt-dlp#7490] opened 2023-07-02 20:52 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Sri Lanka

### Provide a description that is worded well enough to be understood

I can access this particular video in a web browser and download it with the web services such as savefrom.net. Also, I am able to download other videos from Facebook.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
~ $ yt-dlp -vU https://fb.watch/lxsEqNBNJg/?mibextid=Nif5oz
[debug] Command-line config: ['-vU', 'https://fb.watch/lxsEqNBNJg/?mibextid=Nif5oz']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (zip)
[debug] Python 3.11.4 (CPython armv8l 32bit) - Linux-3.18.91-15641782-QB44726894-armv8l-with-libc (OpenSSL 3.1.1 30 May 2023, libc)
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 924464eb831bdb99d854b9d47ff9e1c0870eab276113adaf8a74a8561ad332b9
yt-dlp is up to date (stable@2023.06.22)
[generic] Extracting URL: https://fb.watch/lxsEqNBNJg/?mibextid=Nif5oz
[generic] ?mibextid=Nif5oz: Downloading webpage
[redirect] Following redirect to https://web.facebook.com/reel/244378855011108/
[facebook:reel] Extracting URL: https://web.facebook.com/reel/244378855011108/
[facebook] Extracting URL: https://m.facebook.com/watch/?v=244378855011108&_rdr
[facebook] 244378855011108: Downloading webpage
ERROR: [facebook] 244378855011108: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1555, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1652, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1711, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2653, in process_video_result
    self.raise_no_formats(info_dict)
  File "/data/data/com.termux/files/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1067, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [facebook] 244378855011108: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment] 2023-07-02 20:54
Duplicate of #7469

**Closed by bashonly** 2023-07-02 20:54 UTC
Labels: duplicate, site-bug, site:facebook
