### ISSUE TITLE
[YouTube] Most videos don't download

### ISSUE THREAD

**Issue by ForxBase** [yt-dlp/yt-dlp#11079] opened 2024-09-25 03:10 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Videos don't download, playlists don't download either. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/@aespa/shorts', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.3 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.1-essentials_build-www.gyan.dev (setts), ffprobe 7.0.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.0.9, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.3, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/@aespa/shorts
[youtube:tab] @aespa/shorts: Downloading webpage
[debug] [youtube:tab] Selected tab: 'shorts' (shorts), Requested tab: 'shorts'
[download] Downloading playlist: aespa - Shorts
[youtube:tab] UC9GtSLeksfK4yuJ_g1lgQbg page 1: Downloading API JSON
[youtube:tab] UC9GtSLeksfK4yuJ_g1lgQbg page 2: Downloading API JSON
[youtube:tab] UC9GtSLeksfK4yuJ_g1lgQbg page 3: Downloading API JSON
[youtube:tab] UC9GtSLeksfK4yuJ_g1lgQbg page 4: Downloading API JSON
[youtube:tab] UC9GtSLeksfK4yuJ_g1lgQbg page 5: Downloading API JSON
[youtube:tab] UC9GtSLeksfK4yuJ_g1lgQbg page 6: Downloading API JSON
[youtube:tab] UC9GtSLeksfK4yuJ_g1lgQbg page 7: Downloading API JSON
[youtube:tab] UC9GtSLeksfK4yuJ_g1lgQbg page 8: Downloading API JSON
[youtube:tab] UC9GtSLeksfK4yuJ_g1lgQbg page 9: Downloading API JSON
[youtube:tab] UC9GtSLeksfK4yuJ_g1lgQbg page 10: Downloading API JSON
[youtube:tab] UC9GtSLeksfK4yuJ_g1lgQbg page 11: Downloading API JSON
[youtube:tab] UC9GtSLeksfK4yuJ_g1lgQbg page 12: Downloading API JSON
[youtube:tab] UC9GtSLeksfK4yuJ_g1lgQbg page 13: Downloading API JSON
[youtube:tab] Playlist aespa - Shorts: Downloading 0 items
[download] Finished downloading playlist: aespa - Shorts

And:

[debug] Command-line config: ['https://www.youtube.com/@Reaganhill.official/', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.3 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.1-essentials_build-www.gyan.dev (setts), ffprobe 7.0.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.0.9, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.3, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/@Reaganhill.official/
[youtube:tab] @Reaganhill.official: Downloading webpage
[debug] [youtube:tab] Selected tab: 'videos' (videos), Requested tab: ''
[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[youtube:tab] @Reaganhill.official/shorts: Downloading webpage
[debug] [youtube:tab] Selected tab: 'shorts' (shorts), Requested tab: 'shorts'
[youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UU3SWvnT3XpK8qbo0HiB32jQ
[download] Downloading playlist: Reagan Hill
[youtube:tab] Playlist Reagan Hill: Downloading 2 items of 2
[download] Downloading item 1 of 2
[download] Downloading playlist: Reagan Hill - Videos
[youtube:tab] Playlist Reagan Hill - Videos: Downloading 10 items of 10
[download] Downloading item 1 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=IKtU7uUWTDo
[youtube] IKtU7uUWTDo: Downloading webpage
[youtube] IKtU7uUWTDo: Downloading ios player API JSON
[youtube] IKtU7uUWTDo: Downloading web creator player API JSON
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig EEAvv5oZQfHjB1bJ1H => bMmMhpED42cpAA
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig F1vvRMXyA0T8AfAiDU => omLrh7BP9TtGNw
[youtube] IKtU7uUWTDo: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] IKtU7uUWTDo: Downloading 1 format(s): 248+251
[download] The cutest haul!!🩵💕 Which is your fav？ #unboxing #tryon #haul #fashion  #summerfits [IKtU7uUWTDo].webm has already been downloaded
[download] Downloading item 2 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=4vKeUBUQsZ0
[youtube] 4vKeUBUQsZ0: Downloading webpage
[youtube] 4vKeUBUQsZ0: Downloading ios player API JSON
[youtube] 4vKeUBUQsZ0: Downloading web creator player API JSON
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig Tv62Q7x65JX1SlMnZR => lIdOQNRVjd5wTA
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig wLEBLvCYaNwHHucl29 => FNtan_Rv0kIFJw
[youtube] 4vKeUBUQsZ0: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 4vKeUBUQsZ0: Downloading 1 format(s): 136+251
[download] Heatless Curls Tut for perfect waves!✨ #heatlesswaves #heatlesscurls #hairtutorial #tutorial #hair [4vKeUBUQsZ0].mkv has already been downloaded
[download] Downloading item 3 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=jKR3PL9pHy0
[youtube] jKR3PL9pHy0: Downloading webpage
[youtube] jKR3PL9pHy0: Downloading ios player API JSON
[youtube] jKR3PL9pHy0: Downloading web creator player API JSON
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig mgxEVdXh-on6Ak8cl4 => A4-UqZTj6IDtRg
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig 4tCvKJFdcLR6GWF2lx => 14bohBB2QR5lDg
[youtube] jKR3PL9pHy0: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] jKR3PL9pHy0: Downloading 1 format(s): 247+251
[download] Fav summer outfits tryon haul!!🩵 #shoppinghaul #tryon #haul [jKR3PL9pHy0].webm has already been downloaded
[download] Downloading item 4 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=gzoixtLfkZs
[youtube] gzoixtLfkZs: Downloading webpage
[youtube] gzoixtLfkZs: Downloading ios player API JSON
[youtube] gzoixtLfkZs: Downloading web creator player API JSON
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig -Aj7Zn17wEnvoFE2P- => uyi2VRvRuCzaPw
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig LlIwPZjYPnIbkjlsJj => Ps3EiVTVbVrssA
[youtube] gzoixtLfkZs: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] gzoixtLfkZs: Downloading 1 format(s): 248+251
[download] Summer outfit must-haves!🛍️ (run to get both these #shorts !!!). Watch for my tryon haul!💕 [gzoixtLfkZs].webm has already been downloaded
[download] Downloading item 5 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=olLSkaxkgeQ
[youtube] olLSkaxkgeQ: Downloading webpage
[youtube] olLSkaxkgeQ: Downloading ios player API JSON
[youtube] olLSkaxkgeQ: Downloading web creator player API JSON
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig RxRqQ27O2XnDX8hhEf => LnfJc6MzlrRoKw
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig fmJRtjxOFlmsu39zHY => sq4-Dh7KHRdYrA
[youtube] olLSkaxkgeQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] olLSkaxkgeQ: Downloading 1 format(s): 248+251
[download] shopping haul 🩵 I love the dress & mic 🎤😊 [olLSkaxkgeQ].webm has already been downloaded
[download] Downloading item 6 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=kTdeWKSckrE
[youtube] kTdeWKSckrE: Downloading webpage
[youtube] kTdeWKSckrE: Downloading ios player API JSON
[youtube] kTdeWKSckrE: Downloading web creator player API JSON
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig 8LRMoY2GXHT9Y_CnZh => NItDy4mdkDUFpQ
[youtube] kTdeWKSckrE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] kTdeWKSckrE: Downloading 1 format(s): 248+251
[download] Shopping haul🛍️ (watch for my try-on haul💕) [kTdeWKSckrE].webm has already been downloaded
[download] Downloading item 7 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=vJI28ctHbGs
[youtube] vJI28ctHbGs: Downloading webpage
[youtube] vJI28ctHbGs: Downloading ios player API JSON
[youtube] vJI28ctHbGs: Downloading web creator player API JSON
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig Vomb0Kvb2FJZa6fdqw => 096pZmm5F0QMag
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig eWvN4AAVdJKT9ZW580 => wTEfz_Jh-kagFg
[youtube] vJI28ctHbGs: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] vJI28ctHbGs: Downloading 1 format(s): 248+251
[download] At home starbies pink drink!🩷 [vJI28ctHbGs].webm has already been downloaded
[download] Downloading item 8 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=EhcUAD2oVjU
[youtube] EhcUAD2oVjU: Downloading webpage
[youtube] EhcUAD2oVjU: Downloading ios player API JSON
[youtube] EhcUAD2oVjU: Downloading web creator player API JSON
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig n2WmG3mCBW6XpkLCIN => hrMK8FXSTPMpVw
[youtube] EhcUAD2oVjU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] EhcUAD2oVjU: Downloading 1 format(s): 248+251
[download] GRWM everyday look 🦋 #grwmroutine #naturallook #naturalbeauty  #naturalmakeup #cleangirlaesthetic [EhcUAD2oVjU].webm has already been downloaded
[download] Downloading item 9 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=i1nk1iBVWWw
[youtube] i1nk1iBVWWw: Downloading webpage
[youtube] i1nk1iBVWWw: Downloading ios player API JSON
[youtube] i1nk1iBVWWw: Downloading web creator player API JSON
[debug] [youtube] Extracting signature function js_c9dd45ed_105
[debug] Loading youtube-sigfuncs.js_c9dd45ed_105 from cache
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig VSmZmN8Hx_m_Gh-TXx => 1GAsLlu75glPTQ
[youtube] i1nk1iBVWWw: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] i1nk1iBVWWw: Downloading 1 format(s): 248+251
[download] In New York✨🗽 Living our best life!  #fashionmodels #nyfw #instagrammodels #streetstyle [i1nk1iBVWWw].webm has already been downloaded
[download] Downloading item 10 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=7QFR6X8gmdg
[youtube] 7QFR6X8gmdg: Downloading webpage
[youtube] 7QFR6X8gmdg: Downloading ios player API JSON
[youtube] 7QFR6X8gmdg: Downloading web creator player API JSON
[debug] Loading youtube-nsig.c9dd45ed from cache
[debug] [youtube] Decrypted nsig N_e1gQvGM9_bTzNrfb => H-JvPzxZhok2Qw
[youtube] 7QFR6X8gmdg: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7QFR6X8gmdg: Downloading 1 format(s): 248+251
[download] GRWM makeover using SHEGLAM Ember Rose ~ Pretty, soft rosy shades. #sheglam #makeover #beautytips 💗 [7QFR6X8gmdg].webm has already been downloaded
[download] Finished downloading playlist: Reagan Hill - Videos
[download] Downloading item 2 of 2
[download] Downloading playlist: Reagan Hill - Shorts
[youtube:tab] UC3SWvnT3XpK8qbo0HiB32jQ page 1: Downloading API JSON
[youtube:tab] Playlist Reagan Hill - Shorts: Downloading 0 items
[download] Finished downloading playlist: Reagan Hill - Shorts
[download] Finished downloading playlist: Reagan Hill
```

**Comment by bashonly** [comment] 2024-09-25 03:27
Duplicate of #10936

update to nightly

**Closed by bashonly** 2024-09-25 03:27 UTC
Labels: site-bug, triage
