### ISSUE TITLE
RatingRestricted HiDive

### ISSUE THREAD

**Issue by drknss89** [yt-dlp/yt-dlp#4279] opened 2022-07-06 03:01 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Trying to download a show from HiDive with TV-MA rating and keep getting RatingRestricted.  What should I be using to get around this?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--newline', '-i', '--hls-prefer-native', '--write-description', '--write-info-json', '--cookies', 'C:/Users/rdkno/OneDrive/Desktop/Movies/cookies.txt', '--write-thumbnail', '--windows-filenames', '--output', 'C:/Users/rdkno/OneDrive/Desktop/Movies/Unsorted Videos/%(title)s.%(ext)s', '-vU', '-u', 'PRIVATE', '-p', 'PRIVATE', '-f', '(b[language=en][height<=1080])', '-o', '%(extractor_key)s/%(series)s/%(series)s Season %(season_number)s Episode %(episode_number)s.%(ext)s', '--external-downloader', 'm3u8:ffmpeg', '--add-metadata', '--rm-cache-dir', '--remux-video', 'mkv', '--merge-output-format', 'mkv', 'https://www.hidive.com/stream/to-love-ru/s01e001']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error cp1252 (No ANSI), screen cp1252 (No ANSI)
[debug] yt-dlp version 2022.06.29 [9d339c4]
[debug] Checking exe version: ffmpeg -bsfs
[debug] Python 3.9.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2021.10.08, sqlite3-2.6.0
[debug] Proxy map: ()
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Removing cache dir C:\Users\rdkno\AppData\Local\Tartube\msys64\home\rdkno/.cache/yt-dlp ..
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[HiDive] None: Downloading webpage
[HiDive] Logging in
[debug] [HiDive] Extracting URL: https://www.hidive.com/stream/to-love-ru/s01e001
[HiDive] to-love-ru/s01e001: Downloading JSON metadata

ERROR: [HiDive] to-love-ru/s01e001: HiDive said: RatingRestricted
```

**Comment by october262** [comment] 2022-07-06 23:44
> ```shell
> https://www.hidive.com/stream/to-love-ru/s01e001
> ```

try using a cookies.txt file

**Comment by drknss89** [comment] 2022-07-07 13:45
I do, I am able to watch in Firefox browser no issue

**Comment by october262** [comment] 2022-07-07 17:26
> ```shell
> https://www.hidive.com/stream/to-love-ru/s01e001
> ```

try with yt-dlp --force-generic-extractor "https://www.hidive.com/stream/to-love-ru/s01e001"

**Comment by october262** [comment] 2022-07-07 17:53
> I do, I am able to watch in Firefox browser no issue

are you using both user name & password  and cookies.txt ??
try again without username & password option and just use the cookies.txt

**Comment by pukkandan** [comment] 2022-07-07 21:21
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3336

**Closed by pukkandan** 2022-07-07 21:21 UTC
Labels: site-bug, triage

**Comment by chexxor** [comment] 2022-12-11 00:24
I believe the "ProfileUID" cookie needs to be added to the HTTP request. I'll need to figure out how to fetch the right value there from the login process.
