### ISSUE TITLE
BilibiliBangumi broken

### ISSUE THREAD

**Issue by quzzimi** [yt-dlp/yt-dlp#6944] opened 2023-04-29 07:58 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Vietnam

### Provide a description that is worded well enough to be understood

Cant download BilibiliBangumi Vid anymore

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\>yt-dlp.exe -vU https://www.bilibili.com/bangumi/play/ep706097
[debug] Command-line config: ['-vU', 'https://www.bilibili.com/bangumi/play/ep70
6097']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8 (No VT), error
utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-8.1-6.3.9600-SP0 (OpenSSL
1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, m
utagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releas
es/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a
9421
yt-dlp is up to date (stable@2023.03.04)
[BiliBiliBangumi] Extracting URL: https://www.bilibili.com/bangumi/play/ep706097

[BiliBiliBangumi] ep706097: Downloading webpage
ERROR: [BiliBiliBangumi] ep706097: Unable to extract play info; please report th
is issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the approp
riate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\bilibili.py", line 376, in _real_extract
  File "yt_dlp\extractor\common.py", line 1256, in _search_json
  File "yt_dlp\extractor\common.py", line 1242, in _search_regex
```

**Comment by october262** [comment] 2023-04-29 08:40
it's possible the the movie is DRM protected because the website is wanting 
to install the widevine plugin

**Comment by bashonly** [comment] 2023-04-29 10:10
Duplicate of #6944

**Closed by bashonly** 2023-04-29 10:10 UTC
Labels: site-bug, triage

**Comment by quzzimi** [comment] 2023-07-21 07:20
![image](https://github.com/yt-dlp/yt-dlp/assets/14950009/b9aacc56-9826-4217-9baa-2229c081c264)
broken again, do i open new issue ?

**Comment by bashonly** [comment] 2023-07-21 10:04
@quzzimi that is an old version of yt-dlp. update
