### ISSUE TITLE
[BiliBili] unable to extract play info

### ISSUE THREAD

**Issue by 2333-Del** [yt-dlp/yt-dlp#11665] opened 2024-11-28 08:24 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Provide a description that is worded well enough to be understood

I was able to download videos normally at first, but this afternoon I found that the video download started to report errors. I tested a video on three different IP hosts, and this video was able to download correctly yesterday, but today it fails with an error. I tried different types of URLs and also attempted to add cookies to download the video, but none of them worked. I suspect that Bilibili may have updated its anti-scraping mechanism.And I am very sure that my yt-dlp is the latest version.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -Uv --extract-audio --audio-format mp3 -o "%(id)s-%(title)s.%(ext)s" "https://www.bilibi
li.com/video/BV1HB4y1N7CY/" --ffmpeg-location "D:\workhome\ffmpeg\ffmpeg-master-latest-win64-gpl\bin"
[debug] Command-line config: ['-Uv', '--extract-audio', '--audio-format', 'mp3', '-o', '%(id)s-%(title)s.%(ext)s', 'https://www.bilibili.com/video/BV1HB4y1N7CY/', '--ffmpeg-location', 'D:\\workhome\\ffmpeg\\ffmpeg-master-latest-win64-gpl\\bin']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (pip)
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1w  11 Sep 2023)
[debug] exe versions: ffmpeg N-117770-g322b240cea-20241114 (setts), ffprobe N-117770-g322b240cea-20241114
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, requests-2.32.3, sqlite3-3.45.3, urllib3-1.26.20, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.18 from yt-dlp/yt-dlp)
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1HB4y1N7CY/
[BiliBili] 1HB4y1N7CY: Downloading webpage
WARNING: [BiliBili] unable to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BiliBili] 1HB4y1N7CY: Failed to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "D:\workhome\anaconda3\envs\crawl11\Lib\site-packages\yt_dlp\extractor\common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workhome\anaconda3\envs\crawl11\Lib\site-packages\yt_dlp\extractor\bilibili.py", line 664, in _real_extract
    raise ExtractorError('Failed to extract play info')
```

**Comment by xbzhang1994** [comment] 2024-11-28 08:34
YI also encountered the same problem

**Comment by fgr178707** [comment] 2024-11-28 09:01
> I also encountered the same problem

+1

**Comment by grqz** [comment] 2024-11-28 09:15
seems like `window.__playinfo__` is removed from the page source now

**Comment by grqz** [comment] 2024-11-28 09:27
the extractor should have provided a fallback...
```diff
diff --git a/yt_dlp/extractor/bilibili.py b/yt_dlp/extractor/bilibili.py
index 02ea67707..7de609a6c 100644
--- a/yt_dlp/extractor/bilibili.py
+++ b/yt_dlp/extractor/bilibili.py
@@ -644,7 +644,8 @@ def _real_extract(self, url):
             video_data = initial_state['videoInfo']
         else:
             play_info_obj = self._search_json(
-                r'window\.__playinfo__\s*=', webpage, 'play info', video_id, fatal=False)
+                r'window\.__playinfo__\s*=', webpage, 'play info', video_id, default=None)
+            play_info = None
             if not play_info_obj:
                 if traverse_obj(initial_state, ('error', 'trueCode')) == -403:
                     self.raise_login_required()
@@ -652,7 +653,9 @@ def _real_extract(self, url):
                     raise ExtractorError(
                         'This video may be deleted or geo-restricted. '
                         'You might want to try a VPN or a proxy server (with --proxy)', expected=True)
-            play_info = traverse_obj(play_info_obj, ('data', {dict}))
+                play_info = self._download_playinfo(video_id, initial_state['cid'], headers=headers)
+            else:
+                play_info = traverse_obj(play_info_obj, ('data', {dict}))
             if not play_info:
                 if traverse_obj(play_info_obj, 'code') == 87007:
                     toast = get_element_by_class('tips-toast', webpage) or ''
```

**Comment by grqz** [comment] 2024-11-28 10:24
I made a [custom build](https://github.com/grqz/yt-dlp/releases/tag/ie%2Fbilibili%2Fpi_fallbk) for those who don't want to run/build from source. Run `yt-dlp --update-to grqz/yt-dlp@ie/bilibili/pi_fallbk` to switch to that channel and run `yt-dlp --update-to nightly` to switch back afterwards if necessary.

**Comment by 20NE** [comment] 2024-11-28 10:51
> EDIT:  Is the patch not working as expected?
patch works like charm. Thanks!

**Comment by pokeslog** [comment] 2024-11-28 11:03
patch doesn't work.

**Comment by grqz** [comment] 2024-11-28 11:05
> patch doesn't work.


could you please send a verbose log?

**Comment by hhhnaad** [comment] 2024-11-28 11:19
> the extractor should have provided a fallback...
> 
> ```diff
> diff --git a/yt_dlp/extractor/bilibili.py b/yt_dlp/extractor/bilibili.py
> index 02ea67707..7de609a6c 100644
> --- a/yt_dlp/extractor/bilibili.py
> +++ b/yt_dlp/extractor/bilibili.py
> @@ -644,7 +644,8 @@ def _real_extract(self, url):
>              video_data = initial_state['videoInfo']
>          else:
>              play_info_obj = self._search_json(
> -                r'window\.__playinfo__\s*=', webpage, 'play info', video_id, fatal=False)
> +                r'window\.__playinfo__\s*=', webpage, 'play info', video_id, default=None)
> +            play_info = None
>              if not play_info_obj:
>                  if traverse_obj(initial_state, ('error', 'trueCode')) == -403:
>                      self.raise_login_required()
> @@ -652,7 +653,9 @@ def _real_extract(self, url):
>                      raise ExtractorError(
>                          'This video may be deleted or geo-restricted. '
>                          'You might want to try a VPN or a proxy server (with --proxy)', expected=True)
> -            play_info = traverse_obj(play_info_obj, ('data', {dict}))
> +                play_info = self._download_playinfo(video_id, initial_state['cid'], headers=headers)
> +            else:
> +                play_info = traverse_obj(play_info_obj, ('data', {dict}))
>              if not play_info:
>                  if traverse_obj(play_info_obj, 'code') == 87007:
>                      toast = get_element_by_class('tips-toast', webpage) or ''
> ```
> 
> EDIT: why am I getting downvoted? Is the patch not working as expected? If so, please attach a _verbose_ log

[BiliBili] 1004110373: Downloading webpage
ERROR: 1004042161: An extractor error has occurred. (caused by KeyError('data')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by Tony15246** [comment] 2024-11-28 11:22
>  EDIT: Is the patch not working as expected?

I'm on linux and using firefox. The patch works good for me. Thanks!

**Comment by grqz** [comment] 2024-11-28 11:25
@hhhnaad that's not a _full verbose log_. pass `-v` to yt_dlp and post the _full_ log here, starting with `[debug]`

**Comment by hhhnaad** [comment] 2024-11-28 11:41
``

> @hhhnaad that's not a _full verbose log_. pass `-v` to yt_dlp and post the _full_ log here, starting with `[debug]`
> 
> EDIT: I think the issue is caused by using the raw video_id instead of bvid. i'll update the code shortly

`[debug] Command-line config: ['-v', '-o', '%(id)s-%(title)s.%(ext)s', 'https://www.bilibili.com/video/av1001429231', '--ffmpeg-location', '/usr/bin/ffmpeg']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792]
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.20 (CPython x86_64 64bit) - Linux-5.4.0-200-generic-x86_64-with-glibc2.31 (OpenSSL 3.0.15 3 Sep 2024, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[BiliBili] Extracting URL: https://www.bilibili.com/video/av1001429231
[BiliBili] 1001429231: Downloading webpage
[BiliBili] 1001429231: Downloading wbi sign
[BiliBili] 1001429231: Downloading video formats for cid 1459677881 
ERROR: 1001429231: An extractor error has occurred. (caused by KeyError('data')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/youjiaxuan/.conda/envs/overalldownloader/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/home/youjiaxuan/.conda/envs/overalldownloader/lib/python3.9/site-packages/yt_dlp/extractor/bilibili.py", line 656, in _real_extract
    play_info = self._download_playinfo(video_id, initial_state['cid'], headers=headers)
  File "/home/youjiaxuan/.conda/envs/overalldownloader/lib/python3.9/site-packages/yt_dlp/extractor/bilibili.py", line 172, in _download_playinfo
    return self._download_json(
KeyError: 'data'`

**Comment by grqz** [comment] 2024-11-28 11:51
ive updated the pr code. videos with avid should also work now.

**Comment by xbzhang1994** [comment] 2024-11-28 12:10
yt-dlp --update-to grqz/yt-dlp@ie/bilibili/pi_fallbk  
i get this error: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update 
How fix it?

**Comment by bashonly** [comment] 2024-11-28 14:16
don't use `--break-system-packages`

**Comment by 84415011** [comment] 2024-11-28 14:41
why this bug happen?

**Comment by bashonly** [comment] 2024-11-28 14:53
it was due to a change on the site's end

**Comment by EtienneXIONG** [comment] 2024-11-28 15:41
**After 3 days using successful, the 4th day show the following problem. Please tell me how to fix it. Thanks forward !**
G:\DownloadVideo>yt-dlp --cookies-from-browser firefox https://www.bilibili.com/video/BV185mDYpESw/?spm_id_from=333.999.top_right_bar_window_custom_collection.content.click&vd_source=42882c4cd8d85f30b50034f3e169cc71
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV185mDYpESw/?spm_id_from=333.999.top_right_bar_window_custom_collection.content.click
[BiliBili] 185mDYpESw: Downloading webpage
Extracting cookies from firefox
Extracted 126 cookies from firefox
WARNING: [BiliBili] unable to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BiliBili] 185mDYpESw: Failed to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
'vd_source' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by mrljdx** [comment] 2024-11-29 02:28
Same issue：
```bash
ERROR: [BiliBili] 1RwSBYfEzj: Failed to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. 

Confirm you are on the latest version using  yt-dlp -U
```
 yt-dlp version is 2024.11.18

**Comment by GarrBoss** [comment] 2024-11-29 02:29
Excitely,The mistake that happened yesterday is answered so much when you look at it.

**Comment by mrljdx** [comment] 2024-11-29 02:31
> Excitely,The mistake that happened yesterday is answered so much when you look at it.

There was no such error yesterday. I woke up today and found an error when running. I suspect that Bilibili has updated its web page strategy.

**Comment by GarrBoss** [comment] 2024-11-29 02:41
> > Excitely,The mistake that happened yesterday is answered so much when you look at it.
> 
> There was no such error yesterday. I woke up today and found an error when running. I suspect that Bilibili has updated its web page strategy.

Yes, it wasn't dawn when I checked this, about 5 hours ago.

**Comment by maidmeow4** [comment] 2024-11-29 03:18
> I made a [custom build](https://github.com/grqz/yt-dlp/releases/tag/ie%2Fbilibili%2Fpi_fallbk) for those who don't want to run/build from source. Run `yt-dlp --update-to grqz/yt-dlp@ie/bilibili/pi_fallbk` to switch to that channel and run `yt-dlp --update-to nightly` to switch back afterwards if necessary.

This patch is working fine, thank you!

**Comment by siubb** [comment] 2024-11-29 03:51
Thank you for the hotfix.
Does anyone know if this issue is handled in the nightly build?

**Comment by EtienneXIONG** [comment] 2024-11-29 03:55
I'm not sure.&nbsp;I'm an individual user.




熊蕴远
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yt-dlp/yt-dlp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月29日(星期五) 中午11:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yt-dlp/yt-dlp] Bilibili cannot detect the 'extract play info'  (Issue #11665)





 
Thank you for the hotfix.
 Does anyone know if this issue is handled in the nightly build?

**Comment by EtienneXIONG** [comment] 2024-11-29 05:12
thanks a lot ! I've updated now. It's working correctly !




熊蕴远
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yt-dlp/yt-dlp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月29日(星期五) 中午11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yt-dlp/yt-dlp] Bilibili cannot detect the 'extract play info'  (Issue #11665)





  
I made a custom build for those who don't want to run/build from source. Run yt-dlp --update-to ***@***.***/bilibili/pi_fallbk to switch to that channel and run yt-dlp --update-to nightly to switch back afterwards if necessary.
  
This patch is working fine, thank you!

**Comment by s0urcelab** [comment] 2024-11-29 05:15
@grqz When can we expect your patch to be merged into master branch?

**Comment by grqz** [comment] 2024-11-29 07:36
@2333-Del Please don't close this issue yet. This is just a _temporary_ patch and you shouldn't close this issue until it's merged into master so that maintainers can see this issue

**Comment by grqz** [comment] 2024-11-29 07:57
> @grqz When can we expect your patch to be merged into master branch?

You could ask the maintainers. They've been quite busy recently so don't expect the patch to be merged very soon. I will make a [yt-dlp plugin](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#plugins) later if there's no progress on the pr for a long time

**Comment by EtienneXIONG** [comment] 2024-11-29 08:12
I've updated now. It's not very urgent for. So don't worry. Thanks a lot !




熊蕴远
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yt-dlp/yt-dlp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月29日(星期五) 下午3:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yt-dlp/yt-dlp] Bilibili cannot detect the 'extract play info'  (Issue #11665)





  
@grqz When can we expect your patch to be merged into master branch?
  
You could ask the maintainers. They've been quite busy recently so don't expect the patch to be merged very soon. I will make a yt-dlp plugin later if there's no progress on the pr for a long time

**Comment by gengjiawen** [comment] 2024-11-29 10:26
@bashonly can you review the pending pr fixing this ?

**Comment by s0urcelab** [comment] 2024-11-29 10:29
> > @grqz When can we expect your patch to be merged into master branch?
> 
> You could ask the maintainers. They've been quite busy recently so don't expect the patch to be merged very soon. I will make a [yt-dlp plugin](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#plugins) later if there's no progress on the pr for a long time

Much appreciated!

**Comment by emontaccini** [comment] 2024-11-29 21:24
still not working for me

**Comment by grqz** [comment] 2024-11-29 22:06
I think my method is better because according to https://github.com/nilaoda/BBDown/blob/22fa77a29e93ac7012f9193b73dfbffa1ea8cade/BBDown.Core/Parser.cs#L66, BBDown only extracts `window.__playinfo__` from the webpage if that's a premium video and otherwise it seems to be always downloading one from the API regardless of its presence on the webpage. In contrast my pr #11667 tries to extract `window.__playinfo__` and falls back to the API on extraction failure, which makes fewer requests if the site decides to add `window.__playinfo__` back

**Comment by stu2116Edward** [comment] 2024-11-30 12:03
Here's another way to download Bilibili videos: <https://github.com/ScottSloan/Bili23-Downloader>
I don't know what principle it uses to achieve this. Maybe similar to this one.

**Comment by humygithub** [comment] 2024-11-30 12:05
20241127，all is OK
from 20231128，errors happend：

C:\Users\Administrator\Desktop>yt-dlp https://www.bilibili.com/video/BV1ndnZeVE8f
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1ndnZeVE8f
[BiliBili] 1ndnZeVE8f: Downloading webpage
WARNING: [BiliBili] unable to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BiliBili] 1ndnZeVE8f: Failed to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Closed** 2024-12-01 21:55 UTC
Labels: site-bug

**Comment by grqx** [comment] 2024-12-04 08:20
please move this conversation to #10554, and also attach your verbose log
