### ISSUE TITLE
Instagram user page gives error

### ISSUE THREAD

**Issue by purple512** [yt-dlp/yt-dlp#5996] opened 2023-01-09 05:46 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Globally

### Provide a description that is worded well enough to be understood

I thought it would be possible to give yt-dlp an Instagram user page, and it would download all videos. That works with other sites, so I figured it was worth a try. It seems to try to do something but it ends with an error about a regex not matching.

This does not seem to be specific to any one user, but a general issue with the site. If this operation (grabbing all of a user's videos) is not supported I would expect a more suitable error than a Regex failure.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.instagram.com/nasa/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[instagram:user] Extracting URL: https://www.instagram.com/nasa/
[instagram:user] nasa: Downloading webpage
←[0;31mERROR:←[0m [instagram:user] nasa: Unable to extract ←[0;94mdata←[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\tools\python-3.8\lib\site-packages\yt_dlp\extractor\common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "C:\tools\python-3.8\lib\site-packages\yt_dlp\extractor\instagram.py", line 610, in _real_extract
    data = self._parse_graphql(webpage, user_or_tag)
  File "C:\tools\python-3.8\lib\site-packages\yt_dlp\extractor\instagram.py", line 543, in _parse_graphql
    self._search_regex(
  File "C:\tools\python-3.8\lib\site-packages\yt_dlp\extractor\common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment] 2023-01-09 09:33
Duplicate of #4394

User extraction is broken, and there is not much motivation to fix it.

Due to instagram's rate-limit for users who are not logged in, you would only be able to get less than 12 posts without passing cookies.

And since instagram can *and does* detect yt-dlp usage and they don't hesitate to ban accounts that are making high volumes of "suspicious" requests, even testing user extraction would require throwing away one or more accounts.

**Closed by bashonly** 2023-01-09 09:33 UTC
Labels: duplicate, site-bug, site:instagram
