### ISSUE TITLE
Zee5 Premium Video Extraction Error

### ISSUE THREAD

**Issue by prajwalan364** [yt-dlp/yt-dlp#1697] opened 2021-11-17 15:23 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [ ] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

zee5  premium movies links are not extracting with premium account and not able to download

i think they made some changes, for premium movies there is no **hls_url** field in api and **hls token** is also empty. 

**may be they removed the hls_url field for premium movies**

### Verbose log

```shell
PS G:\YoutubeDL> .\yt-dlp.exe https://www.zee5.com/movies/details/aranmanai-3/0-0-1z535888 -u <number> --verbose
[debug] Command-line config: ['https://www.zee5.com/movies/details/aranmanai-3/0-0-1z535888', '-u', 'PRIVATE', '--verbose']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-103553-g5e7e2e5031-20210908 (setts), ffprobe N-103553-g5e7e2e5031-20210908
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[Zee5] Logging in
[Zee5] Sending OTP
[Zee5] SMS successfully sent
Type OTP and press [Return]:
[Zee5] Verifying OTP
[debug] [Zee5] Extracting URL: https://www.zee5.com/movies/details/aranmanai-3/0-0-1z535888
[Zee5] 0-0-1z535888: Downloading access token
[Zee5] 0-0-1z535888: Downloading JSON metadata
ERROR: [Zee5] 0-0-1z535888: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
File "yt_dlp\extractor\common.py", line 713, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3295, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

**Comment by Ashish0804** [comment] 2021-11-17 15:37
This has DRM.
Provide a non-DRM'd example

**Comment by prajwalan364** [comment] 2021-11-17 15:45
non DRM movies works fine
premium movies are not working even with credentials

**Comment by Ashish0804** [comment] 2021-11-17 15:49
> non DRM movies works fine premium movies are not working even with credentials

Premium != DRM
If you can't provide non DRM example where this issue occurs then this is not an issue (other than cleaner error message maybe). We do not support downloading of DRM content and I won't make changes to extractor just to accommodate DRM'd video. 
Btw this is assuming that the error in log is genuine( and not some account error or network error) as I don't have an account rn to test myself.

**Comment by Ashish0804** [comment] 2021-11-17 16:16
>I think zee5 made some changes
I have no way to test(and work on) this if you won't/can't provide a non DRM'd example 🤷‍♂️

**Comment by prajwalan364** [comment] 2021-11-17 16:22
**i think this is the non DRM'd example**

PS G:\YoutubeDL> .\yt-dlp.exe https://www.zee5.com/movies/details/action-film-starring-puneeth-rajkumar/0-0-2677 --verbose
[debug] Command-line config: ['https://www.zee5.com/movies/details/action-film-starring-puneeth-rajkumar/0-0-2677', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-103553-g5e7e2e5031-20210908 (setts), ffprobe N-103553-g5e7e2e5031-20210908
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [Zee5] Extracting URL: https://www.zee5.com/movies/details/action-film-starring-puneeth-rajkumar/0-0-2677
[Zee5] 0-0-2677: Downloading access token
[Zee5] 0-0-2677: Downloading JSON metadata
[Zee5] 0-0-2677: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 0-0-2677: Downloading 1 format(s): 3443
[debug] Invoking downloader on "https://zee5vodnd.akamaized.net/hls1/elemental/hls/Movies/Drama/DODDAMANE_HUDGA_MOVIE_RevRTR_kn_43228f769d6be44ef852e02508669123/index1080lowp/hdntl=exp=1637252388~acl=%2f*~data=hdntl~hmac=bcd58bc679ff19e70a54e87d118da96d5d51bc3d2470e4280b7cb88661267d6e/1080lowp.m3u8?aka_me_session_id=AAAAAAAAAAAkfZZhAAAAACVxURdV%2fvBYoP0XNr3FhFghh%2f6hsVUI8Asbge8NFHoLDBC3e8d0yT8nub%2f+n1qsskHKw4Nlj68j&aka_media_format_type=hls"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1370
[download] Destination: Doddmane Hudga [0-0-2677].mp4
[download]   1.8% of ~2.11GiB at  4.23MiB/s ETA 11:32 (frag 25/1370)
ERROR: Interrupted by user
PS G:\YoutubeDL>

**Comment by Ashish0804** [comment] 2021-11-17 16:26
>i think this is the non DRM'd example

But it works 😑 

What i mean when i say i need a non-DRM'd url to work on this is that 
1. The url content is not DRM'd
AND
2. The url results in the issue in the OP log

**Comment by Ashish0804** [comment] 2021-11-18 16:16
Closing this since this was confirmed to be DRM "issue" on discord.

**Closed by Ashish0804** 2021-11-18 16:16 UTC
Labels: incomplete, DRM, extractor-bug
