### ISSUE TITLE
Separate language preference for `--write-subs` and `--write-auto-subs`

### ISSUE THREAD

**Issue by JunkFood02** [yt-dlp/yt-dlp#5898] opened 2022-12-29 16:34 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When `all,-live_chat` is used with `--write-auto-subs`, it downloads all of the machine-translated subtitles. 

I'd like to pass `all,-live_chat` for normal subtitles and `.*orig` for only downloading the original auto subtitles from YouTube

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment] 2022-12-29 16:52
Duplicate of #2262

**Closed by pukkandan** 2022-12-29 16:52 UTC
Labels: enhancement, triage
