### ISSUE TITLE
Can't download all youtube shorts from one channel like I used too

### ISSUE THREAD

**Issue by ariaamaia** [yt-dlp/yt-dlp#10981] opened 2024-09-11 17:27 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I used to download all shorts from one youtube channel using a command: "yt-dlp -ciw -o “%(title)s.%(ext)s” -v https://www.youtube.com/@GirlCrafts/shorts". it worked perfectly but today I wasn't able to do it.
the programm rans it's course for a couple of seconds, but in the end 0 shorts are downloaded.

also the chanell I want to download from has around 700 shorts. but now yt-dlp for some reason counts around 1830 extractors?

I also tried using a command "yt-dlp https://www.youtube.com/@GirlCrafts/shorts", but it does nothing too.
0 items downloaded.

I don't know what is the problem. just a way ago this method worked.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/@GirlCrafts/shorts']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 7.0.2-full_build-www.gyan.dev (setts), ffprobe 7.0.2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/@GirlCrafts/shorts
[youtube:tab] @GirlCrafts/shorts: Downloading webpage
[debug] [youtube:tab] Selected tab: 'shorts' (shorts), Requested tab: 'shorts'
[download] Downloading playlist: Girl Crafts - Shorts
[youtube:tab] UCOuy4N97edtXlmPhwwOiuaA page 1: Downloading API JSON
[youtube:tab] UCOuy4N97edtXlmPhwwOiuaA page 2: Downloading API JSON
[youtube:tab] UCOuy4N97edtXlmPhwwOiuaA page 3: Downloading API JSON
[youtube:tab] UCOuy4N97edtXlmPhwwOiuaA page 4: Downloading API JSON
[youtube:tab] Playlist Girl Crafts - Shorts: Downloading 0 items
[download] Finished downloading playlist: Girl Crafts - Shorts
```

**Comment by bashonly** [comment] 2024-09-11 17:53
Duplicate of #10936

**Closed by bashonly** 2024-09-11 17:53 UTC
Labels: bug, triage
