### ISSUE TITLE
Problem with downloading from ARTE

### ISSUE THREAD

**Issue by pavel167** [yt-dlp/yt-dlp#8179] opened 2023-09-22 12:59 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,
I used yt-dlp last Sunday to downloading videos from ARTE channel.
Today I've tried and it doesn't work anymore.
Here below log.
Help, please.
Sincerely

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(env_video_dnld) pavel@MISSURI:~/env_video_dnld$ yt-dlp -F https://www.arte.tv/fr/videos/111786-002-A/pillages-trafics-cie-2-6/
[ArteTV] Extracting URL: https://www.arte.tv/fr/videos/111786-002-A/pillages-trafics-cie-2-6/
[ArteTV] 111786-002-A: Downloading JSON metadata
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
ERROR: [ArteTV] 111786-002-A: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
(env_video_dnld) pavel@MISSURI:~/env_video_dnld$
```

**Comment by bashonly** [comment] 2023-09-22 13:37
Duplicate of #8156

**Closed by bashonly** 2023-09-22 13:37 UTC
Labels: question

**Comment by pavel167** [comment] 2023-09-22 14:00
Thanks !
