### ISSUE TITLE
No Audio when download video using --format 'mp4[height<=720]' option

### ISSUE THREAD

**Issue by blueray453** [yt-dlp/yt-dlp#11187] opened 2024-10-07 16:23 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Why there is no audio in the video when i download. I found https://github.com/yt-dlp/yt-dlp/issues/10189 I do not think this is a duplicate because I just said video height<=720 and did not tell anything about audio.

Is there any other option i need to use to ask to download audio as well? How can I be more specific and say download video with height height<=720 and that has audio.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --format 'mp4[height<=720]' --output "%(title)s.%(ext)s" "https://www.youtube.com/watch?v=7FChPvEOUHQ"
[debug] Command-line config: ['-vU', '--format', 'mp4[height<=720]', '--output', '%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=7FChPvEOUHQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-25-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.14 4 Jun 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.1, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.09.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.09.27 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=7FChPvEOUHQ
[youtube] 7FChPvEOUHQ: Downloading webpage
[youtube] 7FChPvEOUHQ: Downloading ios player API JSON
[youtube] 7FChPvEOUHQ: Downloading web creator player API JSON
[youtube] 7FChPvEOUHQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] 7FChPvEOUHQ: Downloading 1 format(s): 609
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1728339320/ei/GAkEZ8LZIJuHjuMP9NafwQo/ip/103.98.107.101/id/ec50a13ef10e5074/itag/609/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D12390688%3Bdur%3D505.713%3Bgir%3Dyes%3Bitag%3D247%3Blmt%3D1653137061502232/rqh/1/hls_chunk_host/rr1---sn-pjjoxu-q5j6.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/VA/mm/31,29/mn/sn-pjjoxu-q5j6,sn-h557sn6d/ms/au,rdu/mv/m/mvi/1/pcm2cms/yes/pl/24/vprv/1/playlist_type/DVR/dover/13/txp/5319224/mt/1728317161/fvip/1/short_key/1/keepalive/yes/fexp/51300761/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,vprv,playlist_type/sig/AJfQdSswRQIgb-K7JVgEHifoYliSbGRemBC3S3ubHoMMqll5symC5FkCIQCYGQFF5U7rVDdf9tyv0zFa0xI-L5dsp1Lut_9xK5d-Ng%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pcm2cms,pl/lsig/ACJ0pHgwRAIgW1QwYvTE1zKqXvpx5TW0sjda-bKUgbqNk3VT4c8Fw8cCIFNSDQPra773MPxjgR4yznrkqJ-jiJ4rcLNNaHItb5gK/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 95
[download] Destination: 6 Minute core workout for beginners.mp4
[download] 100% of   11.88MiB in 00:01:35 at 127.45KiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:6 Minute core workout for beginners.mp4'
```

**Comment by DTrombett** [comment] 2024-10-07 16:34
Use `-S "res:720"` instead. If you want a mp4 for some reason do not pass `-f mp4` since it will choose only one format (video+audio if available, only video otherwise), but use `-S res:720,vcodec:h264,acodec:aac`

**Comment by bashonly** [comment] 2024-10-07 23:13
Duplicate of #11185

**Closed by bashonly** 2024-10-07 23:13 UTC
Labels: question
