### ISSUE TITLE
Black video for the first few seconds before resuming in sync with audio.

### ISSUE THREAD

**Issue by kaykhan** [yt-dlp/yt-dlp#5992] opened 2023-01-08 11:21 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I noticed when i download a youtube clip and play it back, the first few second of the clip the video has a black screen but the audio is working. After 2 or 3 seconds the videos resumes in sync with the audio. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://youtube.com/clip/UgkxUDCzRSGLKVutthIkoc5aiTGqpM_PKLgC']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.11.1 (CPython x86_64 64bit) - Linux-5.15.0-56-generic-x86_64-with-glibc2.35 (OpenSSL 1.1.1s  1 Nov 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[youtube:clip] Extracting URL: https://youtube.com/clip/UgkxUDCzRSGLKVutthIkoc5aiTGqpM_PKLgC
[youtube:clip] UgkxUDCzRSGLKVutthIkoc5aiTGqpM_PKLgC: Downloading webpage
[youtube] Extracting URL: https://www.youtube.com/watch?v=PcapirY2gnE
[youtube] PcapirY2gnE: Downloading webpage
[youtube] PcapirY2gnE: Downloading android player API JSON
[debug] [youtube] Extracting signature function js_e5f6cbd5_106
[debug] Loading youtube-sigfuncs.js_e5f6cbd5_106 from cache
[debug] Loading youtube-nsig.e5f6cbd5 from cache
[debug] [youtube] Decrypted nsig ktNXfCleIL5E7tMVt => 2iycOQrVf29OWA
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] UgkxUDCzRSGLKVutthIkoc5aiTGqpM_PKLgC: Downloading 1 format(s): 308+251
[debug] Invoking ffmpeg downloader on "https://rr5---sn-cu-h5oe7.googlevideo.com/videoplayback?expire=1673198398&ei=3qa6Y9fuDomLp-oP3L-4gAs&ip=86.132.26.251&id=o-ABFSPMP49GE6IXasMDjbb45THmQ_Dat2TUq_M-AHzpcr&itag=308&source=youtube&requiressl=yes&mh=ou&mm=31%2C29&mn=sn-cu-h5oe7%2Csn-cu-c9i6&ms=au%2Crdu&mv=m&mvi=5&pl=25&initcwndbps=2155000&spc=zIddbMUaY9ZJWHQepggA1RAAjuPTsOM&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=20505642986&dur=18045.899&lmt=1673130557070351&mt=1673176443&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=7319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgQKRPiRVsw6UoSPc6szFVePaWxHP_Rs0-94TgGsMHd0ACIQC32OXR-z4-TL5tUytNFvwCc8DZ8z1dGNHxJmlCwCRQ3w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgGAWReYJaPiaqxhcoKLh08wjlofoO5HoliQ_AEDlUsYcCIQDG9WXrmX-ESxFGhxx1wZEMdy0NUx6WlGZ959bP-xfyZQ%3D%3D", "https://rr5---sn-cu-h5oe7.googlevideo.com/videoplayback?expire=1673198398&ei=3qa6Y9fuDomLp-oP3L-4gAs&ip=86.132.26.251&id=o-ABFSPMP49GE6IXasMDjbb45THmQ_Dat2TUq_M-AHzpcr&itag=251&source=youtube&requiressl=yes&mh=ou&mm=31%2C29&mn=sn-cu-h5oe7%2Csn-cu-c9i6&ms=au%2Crdu&mv=m&mvi=5&pl=25&initcwndbps=2155000&spc=zIddbMUaY9ZJWHQepggA1RAAjuPTsOM&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=247122890&dur=18045.921&lmt=1673130409007075&mt=1673176443&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=7318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgNsM2lRFn_TkFbig9g4P9kRIAU0m_hTbKIcIKUttmFJECIQDRdM0yQ86Ihqs2KoKZCzp1pf4XgWh97MHdV_5veIpEwQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgGAWReYJaPiaqxhcoKLh08wjlofoO5HoliQ_AEDlUsYcCIQDG9WXrmX-ESxFGhxx1wZEMdy0NUx6WlGZ959bP-xfyZQ%3D%3D"
[download] Destination: Memes ｜ Sneako's house tonight reviewing ＂Died Suddenly＂ doc tonight @ 9 [UgkxUDCzRSGLKVutthIkoc5aiTGqpM_PKLgC].webm
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
' -ss 9534.46 -t 37.173000000000684 -i 'https://rr5---sn-cu-h5oe7.googlevideo.com/videoplayback?expire=1673198398&ei=3qa6Y9fuDomLp-oP3L-4gAs&ip=86.132.26.251&id=o-ABFSPMP49GE6IXasMDjbb45THmQ_Dat2TUq_M-AHzpcr&itag=308&source=youtube&requiressl=yes&mh=ou&mm=31%2C29&mn=sn-cu-h5oe7%2Csn-cu-c9i6&ms=au%2Crdu&mv=m&mvi=5&pl=25&initcwndbps=2155000&spc=zIddbMUaY9ZJWHQepggA1RAAjuPTsOM&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=20505642986&dur=18045.899&lmt=1673130557070351&mt=1673176443&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=7319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgQKRPiRVsw6UoSPc6szFVePaWxHP_Rs0-94TgGsMHd0ACIQC32OXR-z4-TL5tUytNFvwCc8DZ8z1dGNHxJmlCwCRQ3w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgGAWReYJaPiaqxhcoKLh08wjlofoO5HoliQ_AEDlUsYcCIQDG9WXrmX-ESxFGhxx1wZEMdy0NUx6WlGZ959bP-xfyZQ%3D%3D' -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
' -ss 9534.46 -t 37.173000000000684 -i 'https://rr5---sn-cu-h5oe7.googlevideo.com/videoplayback?expire=1673198398&ei=3qa6Y9fuDomLp-oP3L-4gAs&ip=86.132.26.251&id=o-ABFSPMP49GE6IXasMDjbb45THmQ_Dat2TUq_M-AHzpcr&itag=251&source=youtube&requiressl=yes&mh=ou&mm=31%2C29&mn=sn-cu-h5oe7%2Csn-cu-c9i6&ms=au%2Crdu&mv=m&mvi=5&pl=25&initcwndbps=2155000&spc=zIddbMUaY9ZJWHQepggA1RAAjuPTsOM&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=247122890&dur=18045.921&lmt=1673130409007075&mt=1673176443&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=7318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgNsM2lRFn_TkFbig9g4P9kRIAU0m_hTbKIcIKUttmFJECIQDRdM0yQ86Ihqs2KoKZCzp1pf4XgWh97MHdV_5veIpEwQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgGAWReYJaPiaqxhcoKLh08wjlofoO5HoliQ_AEDlUsYcCIQDG9WXrmX-ESxFGhxx1wZEMdy0NUx6WlGZ959bP-xfyZQ%3D%3D' -c copy -map 0:0 -map 1:0 -f webm 'file:Memes ｜ Sneako'"'"'s house tonight reviewing ＂Died Suddenly＂ doc tonight @ 9 [UgkxUDCzRSGLKVutthIkoc5aiTGqpM_PKLgC].webm.part'
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[tcp @ 0x55f17f92e800] Starting connection attempt to 81.134.108.16 port 443
[tcp @ 0x55f17f92e800] Successfully connected to 81.134.108.16 port 443
[tcp @ 0x55f17fc52e80] Starting connection attempt to 81.134.108.16 port 443
[tcp @ 0x55f17fc52e80] Successfully connected to 81.134.108.16 port 443
Input #0, matroska,webm, from 'https://rr5---sn-cu-h5oe7.googlevideo.com/videoplayback?expire=1673198398&ei=3qa6Y9fuDomLp-oP3L-4gAs&ip=86.132.26.251&id=o-ABFSPMP49GE6IXasMDjbb45THmQ_Dat2TUq_M-AHzpcr&itag=308&source=youtube&requiressl=yes&mh=ou&mm=31%2C29&mn=sn-cu-h5oe7%2Csn-cu-c9i6&ms=au%2Crdu&mv=m&mvi=5&pl=25&initcwndbps=2155000&spc=zIddbMUaY9ZJWHQepggA1RAAjuPTsOM&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=20505642986&dur=18045.899&lmt=1673130557070351&mt=1673176443&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=7319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgQKRPiRVsw6UoSPc6szFVePaWxHP_Rs0-94TgGsMHd0ACIQC32OXR-z4-TL5tUytNFvwCc8DZ8z1dGNHxJmlCwCRQ3w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgGAWReYJaPiaqxhcoKLh08wjlofoO5HoliQ_AEDlUsYcCIQDG9WXrmX-ESxFGhxx1wZEMdy0NUx6WlGZ959bP-xfyZQ%3D%3D':
  Metadata:
    encoder         : google/video-file
  Duration: 05:00:45.90, start: 0.000000, bitrate: 9090 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), 1 reference frame, yuv420p(tv, bt709), 2560x1440, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
[tcp @ 0x55f17fbcf240] Starting connection attempt to 81.134.108.16 port 443
[tcp @ 0x55f17fbcf240] Successfully connected to 81.134.108.16 port 443
[tcp @ 0x55f17ff3bfc0] Starting connection attempt to 81.134.108.16 port 443
[tcp @ 0x55f17ff3bfc0] Successfully connected to 81.134.108.16 port 443
Input #1, matroska,webm, from 'https://rr5---sn-cu-h5oe7.googlevideo.com/videoplayback?expire=1673198398&ei=3qa6Y9fuDomLp-oP3L-4gAs&ip=86.132.26.251&id=o-ABFSPMP49GE6IXasMDjbb45THmQ_Dat2TUq_M-AHzpcr&itag=251&source=youtube&requiressl=yes&mh=ou&mm=31%2C29&mn=sn-cu-h5oe7%2Csn-cu-c9i6&ms=au%2Crdu&mv=m&mvi=5&pl=25&initcwndbps=2155000&spc=zIddbMUaY9ZJWHQepggA1RAAjuPTsOM&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=247122890&dur=18045.921&lmt=1673130409007075&mt=1673176443&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=7318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgNsM2lRFn_TkFbig9g4P9kRIAU0m_hTbKIcIKUttmFJECIQDRdM0yQ86Ihqs2KoKZCzp1pf4XgWh97MHdV_5veIpEwQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgGAWReYJaPiaqxhcoKLh08wjlofoO5HoliQ_AEDlUsYcCIQDG9WXrmX-ESxFGhxx1wZEMdy0NUx6WlGZ959bP-xfyZQ%3D%3D':
  Metadata:
    encoder         : google/video-file
  Duration: 05:00:45.92, start: -0.007000, bitrate: 109 kb/s
  Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp, delay 312 (default)
Output #0, webm, to 'file:Memes ｜ Sneako's house tonight reviewing ＂Died Suddenly＂ doc tonight @ 9 [UgkxUDCzRSGLKVutthIkoc5aiTGqpM_PKLgC].webm.part':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0(eng): Video: vp9 (Profile 0), 1 reference frame, yuv420p(tv, bt709), 2560x1440 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp, delay 312 (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
Automatically inserted bitstream filter 'vp9_superframe'; args=''
frame=    1 fps=0.0 q=-1.0 size=       1kB time=00:00:00.00 bitrate=N/A speed=  frame=   42 fps=0.0 q=-1.0 size=       1kB time=-00:00:03.75 bitrate=N/A speed=Nframe=   70 fps= 63 q=-1.0 size=       1kB time=-00:00:03.29 bitrate=N/A speed=Nframe=  125 fps= 75 q=-1.0 size=       1kB time=-00:00:02.37 bitrate=N/A speed=Nframe=  180 fps= 83 q=-1.0 size=       1kB time=-00:00:01.45 bitrate=N/A speed=Nframe=  221 fps= 83 q=-1.0 size=    5120kB time=-00:00:00.77 bitrate=N/A speed=Nframe=  270 fps= 84 q=-1.0 size=    5120kB time=00:00:00.04 bitrate=1023001.0kbiframe=  302 fps= 80 q=-1.0 size=    7936kB time=00:00:00.56 bitrate=115885.4kbitframe=  327 fps= 77 q=-1.0 size=    7936kB time=00:00:00.98 bitrate=66270.9kbitsframe=  347 fps= 73 q=-1.0 size=    7936kB time=00:00:01.32 bitrate=49214.0kbitsframe=  380 fps= 72 q=-1.0 size=    7936kB time=00:00:01.86 bitrate=34933.8kbitsframe=  444 fps= 77 q=-1.0 size=   13056kB time=00:00:02.94 bitrate=36366.8kbitsframe=  566 fps= 89 q=-1.0 size=   13056kB time=00:00:04.95 bitrate=21572.2kbitsframe=  602 fps= 88 q=-1.0 size=   15104kB time=00:00:05.55 bitrate=22262.0kbitsframe=  638 fps= 87 q=-1.0 size=   15104kB time=00:00:06.15 bitrate=20092.9kbitsframe=  675 fps= 85 q=-1.0 size=   15104kB time=00:00:06.78 bitrate=18246.9kbitsframe=  716 fps= 85 q=-1.0 size=   15104kB time=00:00:07.45 bitrate=16590.5kbitsframe=  746 fps= 83 q=-1.0 size=   15104kB time=00:00:07.95 bitrate=15548.1kbitsframe=  790 fps= 83 q=-1.0 size=   20480kB time=00:00:08.70 bitrate=19281.9kbitsframe=  844 fps= 84 q=-1.0 size=   20480kB time=00:00:09.60 bitrate=17474.4kbitsframe=  902 fps= 85 q=-1.0 size=   23040kB time=00:00:10.55 bitrate=17876.8kbitsframe=  932 fps= 84 q=-1.0 size=   23040kB time=00:00:11.06 bitrate=17063.9kbitsframe=  972 fps= 83 q=-1.0 size=   23040kB time=00:00:11.74 bitrate=16075.6kbitsframe= 1020 fps= 84 q=-1.0 size=   23040kB time=00:00:12.54 bitrate=15050.1kbitsframe= 1101 fps= 87 q=-1.0 size=   23040kB time=00:00:13.88 bitrate=13597.3kbitsframe= 1142 fps= 86 q=-1.0 size=   28160kB time=00:00:14.55 bitrate=15846.0kbitsframe= 1202 fps= 87 q=-1.0 size=   30464kB time=00:00:15.55 bitrate=16040.7kbitsframe= 1238 fps= 86 q=-1.0 size=   30464kB time=00:00:16.15 bitrate=15445.0kbitsframe= 1280 fps= 86 q=-1.0 size=   30464kB time=00:00:16.85 bitrate=14803.7kbitsframe= 1316 fps= 85 q=-1.0 size=   30464kB time=00:00:17.45 bitrate=14294.9kbitsframe= 1352 fps= 85 q=-1.0 size=   30464kB time=00:00:18.05 bitrate=13820.0kbitsframe= 1394 fps= 85 q=-1.0 size=   35584kB time=00:00:18.75 bitrate=15540.3kbitsframe= 1442 fps= 85 q=-1.0 size=   35584kB time=00:00:19.56 bitrate=14902.3kbitsframe= 1502 fps= 84 q=-1.0 size=   38400kB time=00:00:20.55 bitrate=15301.7kbitsframe= 1557 fps= 85 q=-1.0 size=   38400kB time=00:00:21.48 bitrate=14644.2kbitsframe= 1593 fps= 85 q=-1.0 size=   38400kB time=00:00:22.08 bitrate=14246.3kbitsframe= 1622 fps= 84 q=-1.0 size=   38400kB time=00:00:22.56 bitrate=13943.2kbitsframe= 1655 fps= 83 q=-1.0 size=   43520kB time=00:00:23.12 bitrate=15419.6kbitsframe= 1721 fps= 84 q=-1.0 size=   43520kB time=00:00:24.22 bitrate=14719.3kbitsframe= 1802 fps= 86 q=-1.0 size=   46080kB time=00:00:25.55 bitrate=14769.8kbitsframe= 1846 fps= 85 q=-1.0 size=   46080kB time=00:00:26.30 bitrate=14352.6kbitsframe= 1880 fps= 85 q=-1.0 size=   46080kB time=00:00:26.85 bitrate=14054.9kbitsframe= 1923 fps= 85 q=-1.0 size=   46080kB time=00:00:27.58 bitrate=13686.5kbitsframe= 1956 fps= 85 q=-1.0 size=   46080kB time=00:00:28.14 bitrate=13414.1kbitsframe= 2006 fps= 85 q=-1.0 size=   51200kB time=00:00:28.95 bitrate=14484.1kbitsframe= 2078 fps= 86 q=-1.0 size=   51200kB time=00:00:30.15 bitrate=13907.8kbitsframe= 2102 fps= 85 q=-1.0 size=   53760kB time=00:00:30.55 bitrate=14412.0kbitsframe= 2147 fps= 85 q=-1.0 size=   53760kB time=00:00:31.32 bitrate=14060.9kbitsframe= 2198 fps= 85 q=-1.0 size=   53760kB time=00:00:32.16 bitrate=13693.7kbitsframe= 2242 fps= 85 q=-1.0 size=   53760kB time=00:00:32.90 bitrate=13385.7kbitsframe= 2289 fps= 85 q=-1.0 size=   59136kB time=00:00:33.68 bitrate=14383.2kbitsframe= 2342 fps= 86 q=-1.0 size=   59136kB time=00:00:34.55 bitrate=14018.2kbitsframe= 2390 fps= 86 q=-1.0 size=   59136kB time=00:00:35.36 bitrate=13699.9kbitsframe= 2422 fps= 85 q=-1.0 size=   61440kB time=00:00:35.90 bitrate=14019.6kbitsframe= 2463 fps= 85 q=-1.0 size=   61440kB time=00:00:36.58 bitrate=13759.0kbitsNo more output streams to write to, finishing.
frame= 2498 fps= 85 q=-1.0 Lsize=   65061kB time=00:00:37.16 bitrate=14342.5kbits/s speed=1.26x    
video:64479kB audio:549kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.050302%
Input file #0 (https://rr5---sn-cu-h5oe7.googlevideo.com/videoplayback?expire=1673198398&ei=3qa6Y9fuDomLp-oP3L-4gAs&ip=86.132.26.251&id=o-ABFSPMP49GE6IXasMDjbb45THmQ_Dat2TUq_M-AHzpcr&itag=308&source=youtube&requiressl=yes&mh=ou&mm=31%2C29&mn=sn-cu-h5oe7%2Csn-cu-c9i6&ms=au%2Crdu&mv=m&mvi=5&pl=25&initcwndbps=2155000&spc=zIddbMUaY9ZJWHQepggA1RAAjuPTsOM&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=20505642986&dur=18045.899&lmt=1673130557070351&mt=1673176443&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=7319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgQKRPiRVsw6UoSPc6szFVePaWxHP_Rs0-94TgGsMHd0ACIQC32OXR-z4-TL5tUytNFvwCc8DZ8z1dGNHxJmlCwCRQ3w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgGAWReYJaPiaqxhcoKLh08wjlofoO5HoliQ_AEDlUsYcCIQDG9WXrmX-ESxFGhxx1wZEMdy0NUx6WlGZ959bP-xfyZQ%3D%3D):
  Input stream #0:0 (video): 2499 packets read (66046212 bytes); 
  Total: 2499 packets (66046212 bytes) demuxed
Input file #1 (https://rr5---sn-cu-h5oe7.googlevideo.com/videoplayback?expire=1673198398&ei=3qa6Y9fuDomLp-oP3L-4gAs&ip=86.132.26.251&id=o-ABFSPMP49GE6IXasMDjbb45THmQ_Dat2TUq_M-AHzpcr&itag=251&source=youtube&requiressl=yes&mh=ou&mm=31%2C29&mn=sn-cu-h5oe7%2Csn-cu-c9i6&ms=au%2Crdu&mv=m&mvi=5&pl=25&initcwndbps=2155000&spc=zIddbMUaY9ZJWHQepggA1RAAjuPTsOM&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=247122890&dur=18045.921&lmt=1673130409007075&mt=1673176443&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=7318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgNsM2lRFn_TkFbig9g4P9kRIAU0m_hTbKIcIKUttmFJECIQDRdM0yQ86Ihqs2KoKZCzp1pf4XgWh97MHdV_5veIpEwQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgGAWReYJaPiaqxhcoKLh08wjlofoO5HoliQ_AEDlUsYcCIQDG9WXrmX-ESxFGhxx1wZEMdy0NUx6WlGZ959bP-xfyZQ%3D%3D):
  Input stream #1:0 (audio): 2082 packets read (562761 bytes); 
  Total: 2082 packets (562761 bytes) demuxed
Output file #0 (file:Memes ｜ Sneako's house tonight reviewing ＂Died Suddenly＂ doc tonight @ 9 [UgkxUDCzRSGLKVutthIkoc5aiTGqpM_PKLgC].webm.part):
  Output stream #0:0 (video): 2498 packets muxed (66026535 bytes); 
  Output stream #0:1 (audio): 2081 packets muxed (562603 bytes); 
  Total: 4579 packets (66589138 bytes) muxed
[AVIOContext @ 0x55f17fc95740] Statistics: 2 seeks, 256 writeouts
[AVIOContext @ 0x55f17f936440] Statistics: 66649494 bytes read, 1 seeks
[AVIOContext @ 0x55f17fc865c0] Statistics: 622592 bytes read, 1 seeks
[download] 100% of   63.54MiB in 00:00:31 at 2.03MiB/s
```

**Comment by bashonly** [comment] 2023-01-08 12:53
Duplicate of #5080, #4216

Youtube clips are essentially the original youtube videos with `--download-sections` timestamps applied

From #4216:
> Video files cannot be cut at exact timestamps without re-encoding. `--download-sections` do not re-encode by default. To make it do so, use `--force-keyframes-at-cuts`

If you do not want to re-encode, you may have better results with a newer version of ffmpeg (5.1+) and/or with a different media player. (using ffmpeg n5.1.2 and mpv I don't have any problems with this clip)

**Closed by bashonly** 2023-01-08 12:53 UTC
Labels: bug, triage

**Comment by PlaylistsTrance** [comment] 2023-03-24 13:20
I don't think this is a duplicate. The problem that's stated here is that the start position of the video does not line up with the start position of the audio, not that the timestamp isn't exact.

For example:

```yt-dlp --download-sections "*0:53-1:15" https://youtu.be/W6DOkcLlIgE
yt-dlp --download-sections "*0:54-1:15" https://youtu.be/W6DOkcLlIgE
yt-dlp --download-sections "*0:55-1:15" https://youtu.be/W6DOkcLlIgE
yt-dlp --download-sections "*0:56-1:15" https://youtu.be/W6DOkcLlIgE
yt-dlp --download-sections "*0:57-1:15" https://youtu.be/W6DOkcLlIgE```

All of these downloads have the exact same audio, however, the first two downloads have the video start at 0.279, and the other 3 downloads have the video start at 4.492.

Would it be possible to force the audio to be cut at the same timestamps as the video?

**Comment by pukkandan** [comment] 2023-03-24 16:40
@PlaylistsTrance Show log of it not working as expected with `--force-keyframes`

**Comment by PlaylistsTrance** [comment] 2023-03-24 17:58
Doesn't that re-encode?

**Comment by PlaylistsTrance** [comment] 2023-03-24 19:51
The only way I could see this being possible is to first detect the nearest video keyframe, and then use that timestamp for ffmpeg -ss. I don't know if that's feasible.

**Comment by michealespinola** [comment] 2023-03-24 21:16
If I understand this correctly, its an issue of cutting the streams separately - but FFmpeg by default cuts at the last previous keyframe, whereas the audio has no such default/requirement- correct?

Perhaps some timecode maths could be applied to further trim the audio stream start to match the resulting video stream?

**Comment by PlaylistsTrance** [comment] 2023-03-24 23:07
I'm not entirely sure if the audio does not have any requirements when cutting, because of those 5 different start timestamps in the example I gave earlier, the audio cut is the same for all of them.

**Comment by michealespinola** [comment] 2023-03-24 23:22
> the audio cut is the same for all of them.

Testing this again, you are right. The audio cut is the same in the example timestamps for me as well. I've made certain to delete all previously downloaded files between attempts. That makes even less sense now.
