### ISSUE TITLE
Can't merge a video and audio with -f 303+251

### ISSUE THREAD

**Issue by fugitive666** [yt-dlp/yt-dlp#2124] opened 2021-12-26 11:39 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.25**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [ ] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [x] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When I issue the following command, it will fail to merge the video and audio. Please help to check it.

PS C:\Users\jsm\Desktop\youtube-dl> .\yt-dlp.exe -f 303+251 --playlist-items 1 https://www.youtube.com/playlist?list=PLlmap9oF-wQrYpyi-FSb-YVWxVXO_uYmv
[youtube:tab] PLlmap9oF-wQrYpyi-FSb-YVWxVXO_uYmv: Downloading webpage
[youtube:tab] PLlmap9oF-wQrYpyi-FSb-YVWxVXO_uYmv: Downloading API JSON with unavailable videos
[download] Downloading playlist: 政大 陳天進  高等微積分 2018 1072
[youtube:tab] playlist 政大 陳天進  高等微積分 2018 1072: Downloading 1 videos
[download] Downloading video 1 of 1
[youtube] _425RF6WzUw: Downloading webpage
[youtube] _425RF6WzUw: Downloading android player API JSON
[youtube] _425RF6WzUw: Downloading MPD manifest
[youtube] _425RF6WzUw: Downloading MPD manifest
[info] _425RF6WzUw: Downloading 1 format(s): 303+251
[dashsegments] Total fragments: 237
[download] Destination: 107下 高等微積分 2019 02 26 1 2 1 [_425RF6WzUw].f303.webm
[download] 100% of 336.05MiB in 03:47
[download] Destination: 107下 高等微積分 2019 02 26 1 2 1 [_425RF6WzUw].f251.webm
[download] 100% of 16.20MiB in 00:02
[Merger] Merging formats into "107下 高等微積分 2019 02 26 1 2 1 [_425RF6WzUw].webm"
ERROR: Postprocessing: Conversion failed!
[download] Finished downloading playlist: 政大 陳天進  高等微積分 2018 1072

P.S. The link, https://youtu.be/yT_5mZnrQ2I, is the same file to test.

### Verbose log

```shell
[debug] Command-line config: ['-Uv']
[debug] Encodings: locale cp950, fs utf-8, out utf-8, err utf-8, pref cp950
[debug] yt-dlp version 2021.12.25 [87e0499] (win_exe)
[debug] Python version 3.7.9 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.25, Current version: 2021.12.25
yt-dlp is up to date (2021.12.25)
```

**Comment by nyuszika7h** [comment] 2021-12-26 11:46
Next time post a **full** verbose log, append `-Uv` after the rest of the options rather than just using it alone. But I'm able to reproduce this:
```
❯ yt-dlp --ignore-config -v -f 303+251 --playlist-items 1 'https://www.youtube.com/playlist?list=PLlmap9oF-wQrYpyi-FSb-YVWxVXO_uYmv'
[debug] Command-line config: ['--ignore-config', '-v', '-f', '303+251', '--playlist-items', '1', 'https://www.youtube.com/playlist?list=PLlmap9oF-wQrYpyi-FSb-YVWxVXO_uYmv']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.25 [87e049962]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.10.0-8-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg N-59843-g4f44a218e5-static (setts), ffprobe N-59843-g4f44a218e5-static, phantomjs .
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLlmap9oF-wQrYpyi-FSb-YVWxVXO_uYmv
[youtube:tab] PLlmap9oF-wQrYpyi-FSb-YVWxVXO_uYmv: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=PLlmap9oF-wQrYpyi-FSb-YVWxVXO_uYmv
[youtube:tab] PLlmap9oF-wQrYpyi-FSb-YVWxVXO_uYmv: Downloading API JSON with unavailable videos
[download] Downloading playlist: 政大 陳天進  高等微積分 2018 1072
[youtube:tab] playlist 政大 陳天進  高等微積分 2018 1072: Downloading 1 videos
[download] Downloading video 1 of 1
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=_425RF6WzUw
[youtube] _425RF6WzUw: Downloading webpage
[youtube] _425RF6WzUw: Downloading android player API JSON
[youtube] _425RF6WzUw: Downloading MPD manifest
[youtube] _425RF6WzUw: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] _425RF6WzUw: Downloading 1 format(s): 303+251
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1640540689/ei/sVXIYfG9NIXi-gb16bOwBQ/ip/[REDACTED]/id/ff8db9445e96cd4c/source/youtube/requiressl/yes/playback_host/rr4---sn-4g5ednsk.googlevideo.com/mh/Et/mm/31%2C29/mn/sn-4g5ednsk%2Csn-4g5lznle/ms/au%2Crdu/mv/m/mvi/4/pl/47/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/645000/vprv/1/mt/1640518877/fvip/4/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgdbobFJlVbpjalDXI-59mlkI5cG2NHbhToCmtUBpna6YCIQD7lYg6INBf1tkAu4yuDs8PIZY-jn4LtbbBLgZDVTvRMw%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIhAMna_W6nqoTqmnV_IVv301KYUDpEnf61ihD8coUbRvBrAiAD7iiwmBKIKH5_mMC0QjgIjvHZg1ACHgtcgiqq7KxoCg%3D%3D"
[dashsegments] Total fragments: 237
[download] Destination: 107下 高等微積分 2019 02 26 1 2 1 [_425RF6WzUw].f303.webm
[download] 100% of 336.05MiB in 00:25
[debug] Invoking downloader on "https://rr4---sn-4g5lznle.googlevideo.com/videoplayback?expire=1640540690&ei=slXIYZ25EYST8gPphbXABQ&ip=[REDACTED]&id=o-ANf_VaU1GSzR-9OFF7hdyCNpzTUDJ8BSPkUDA-dmvLGF&itag=251&source=youtube&requiressl=yes&mh=Et&mm=31%2C26&mn=sn-4g5lznle%2Csn-5hne6nsy&ms=au%2Conr&mv=m&mvi=4&pl=47&initcwndbps=682500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=16983046&otfp=1&dur=1195.221&lmt=1564777635340736&mt=1640518633&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIgRajXCDkdZEHiwHm1KdlP1eA-8PQH5FgVpKkOoC0ttpkCIQD5UfQZMUStxo0cNMtQG1sloHNoK83PGP27KWi_PS0HEw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgb8QxfmfYCWOnlrauHqV-HX2nVleLtf_0txwr1iP3OEgCIAzAZgFdRMHV3gYqsTvUwpKK2SXxHmRVVMDM1t8YePJ7"
[download] Destination: 107下 高等微積分 2019 02 26 1 2 1 [_425RF6WzUw].f251.webm
[download] 100% of 16.20MiB in 00:00
[Merger] Merging formats into "107下 高等微積分 2019 02 26 1 2 1 [_425RF6WzUw].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:107下 高等微積分 2019 02 26 1 2 1 [_425RF6WzUw].f303.webm' -i 'file:107下 高等微積分 2019 02 26 1 2 1 [_425RF6WzUw].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:107下 高等微積分 2019 02 26 1 2 1 [_425RF6WzUw].temp.webm'
[debug] ffmpeg version N-59843-g4f44a218e5-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      57. 10.101 / 57. 10.101
  libavcodec     59. 14.100 / 59. 14.100
  libavformat    59.  9.102 / 59.  9.102
  libavdevice    59.  0.101 / 59.  0.101
  libavfilter     8. 19.100 /  8. 19.100
  libswscale      6.  1.101 /  6.  1.101
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Input #0, matroska,webm, from 'file:107下 高等微積分 2019 02 26 1 2 1 [_425RF6WzUw].f303.webm':
  Metadata:
    encoder         : google/video-file
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 236
                    : Segment-Durations-Ms: 5072,5071,5072(r=2),5071,5072(r=2),5071,5072(r=2),5071,5072(r=1),5071,5072(r=2),5071,5072(r=2),5071,5072(r=2),5071,5072(r=1),5071,5072(r=2),5071,5072(r=2),5071,5072(r=2),5071,5072(r=1),5071,5072(r=2),5071,5072(r=2),5071,5072(r=2),507
                    :
                    :
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 59.94 fps, 59.94 tbr, 1k tbn (default)
Input #1, matroska,webm, from 'file:107下 高等微積分 2019 02 26 1 2 1 [_425RF6WzUw].f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:19:55.22, start: -0.007000, bitrate: 113 kb/s
  Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Output #0, webm, to 'file:107下 高等微積分 2019 02 26 1 2 1 [_425RF6WzUw].temp.webm':
  Metadata:
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 236
                    : Segment-Durations-Ms: 5072,5071,5072(r=2),5071,5072(r=2),5071,5072(r=2),5071,5072(r=1),5071,5072(r=2),5071,5072(r=2),5071,5072(r=2),5071,5072(r=1),5071,5072(r=2),5071,5072(r=2),5071,5072(r=2),5071,5072(r=1),5071,5072(r=2),5071,5072(r=2),5071,5072(r=2),507
                    :
                    :
    encoder         : Lavf59.9.102
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 59.94 fps, 59.94 tbr, 1k tbn (default)
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[webm @ 0x70d5000] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5088 >= 5072
av_interleaved_write_frame(): Invalid argument
frame=  307 fps=0.0 q=-1.0 Lsize=     225kB time=00:00:05.10 bitrate= 361.9kbits/s speed=2.06e+03x
video:126kB audio:100kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "/home/nyuszika7h/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3062, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "/home/nyuszika7h/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3233, in post_process
    info = self.run_pp(pp, info)
  File "/home/nyuszika7h/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3176, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/home/nyuszika7h/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/nyuszika7h/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 117, in wrapper
    return func(self, info)
  File "/home/nyuszika7h/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 820, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/nyuszika7h/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 280, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/home/nyuszika7h/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 319, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

[download] Finished downloading playlist: 政大 陳天進  高等微積分 2018 1072
```

**Comment by nyuszika7h** [comment] 2021-12-26 11:49
Actually, this looks like a duplicate of #871.

**Comment by fugitive666** [comment] 2021-12-26 12:03
a duplicated issue.

**Closed** 2021-12-26 12:03 UTC
Labels: bug, triage
