### ISSUE TITLE
VK error "Failed to parse JSON "

### ISSUE THREAD

**Issue by blotsome** [yt-dlp/yt-dlp#4336] opened 2022-07-12 03:13 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Error when attempting to download from vk.com, public video.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://vk.com/video-184417838_456240932']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4]
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.4.0-113-generic-x86_64-with-glibc2.27 (glibc 2.27)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2018.01.18, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [vk] Extracting URL: https://vk.com/video-184417838_456240932
[vk] -184417838_456240932: Downloading JSON metadata
ERROR: [vk] -184417838_456240932: Failed to parse JSON (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/debianuser/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "/home/debianuser/.local/lib/python3.10/site-packages/yt_dlp/extractor/vk.py", line 328, in _real_extract
    payload = self._download_payload('al_video', video_id, data)
  File "/home/debianuser/.local/lib/python3.10/site-packages/yt_dlp/extractor/vk.py", line 55, in _download_payload
    code, payload = self._download_json(
  File "/home/debianuser/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1002, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/home/debianuser/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 972, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal), urlh
  File "/home/debianuser/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 962, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
  File "/home/debianuser/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 947, in _parse_json
    raise ExtractorError(errmsg, cause=ve)

  File "/home/debianuser/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 942, in _parse_json
    return json.loads(
  File "/usr/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/home/debianuser/.local/lib/python3.10/site-packages/yt_dlp/utils.py", line 599, in decode
    return super().decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by HobbyistDev** [comment] 2022-07-12 03:27
Looks duplicate of #3797

**Closed** 2022-07-12 06:58 UTC
Labels: site-bug, triage
