### ISSUE TITLE
Fails to download from francetv

### ISSUE THREAD

**Issue by pavel167** [yt-dlp/yt-dlp#10197] opened 2024-06-17 00:51 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Hello
One week ago it was Ok.
Today doesn't work

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(env_video_dnld) pavel@MISSURI:~/env_video_dnld$ yt-dlp -vU -F https://www.france.tv/films/longs-metrages/6075164-i-m-not-there.html
[debug] Command-line config: ['-vU', '-F', 'https://www.france.tv/films/longs-metrages/6075164-i-m-not-there.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-35-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, requests-2.31.0, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[FranceTVSite] Extracting URL: https://www.france.tv/films/longs-metrages/6075164-i-m-not-there.html
[FranceTVSite] 6075164-i-m-not-there: Downloading webpage
[FranceTV] Extracting URL: francetv:be7dc086-c442-4685-8116-ddeac2248c31#__youtubedl_smuggle=%7B%22hostname%22%3A+%22www.france.tv%22%7D
[FranceTV] be7dc086-c442-4685-8116-ddeac2248c31: Downloading desktop chrome video JSON
[FranceTV] be7dc086-c442-4685-8116-ddeac2248c31: Downloading mobile safari video JSON
[FranceTV] be7dc086-c442-4685-8116-ddeac2248c31: Downloading MPD manifest
WARNING: [FranceTV] Failed to download MPD manifest: HTTP Error 403: Forbidden
[FranceTV] be7dc086-c442-4685-8116-ddeac2248c31: Downloading m3u8 information
WARNING: [FranceTV] Failed to download m3u8 information: HTTP Error 403: Forbidden
[FranceTV] be7dc086-c442-4685-8116-ddeac2248c31: Checking for geo-restriction
WARNING: Only images are available for download. use --list-formats to see them
[debug] Sort order given by extractor: res, tbr, proto
[debug] Formats sorted by: hasvid, ie_pref, res, tbr, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, vext, aext, hasaud, source, id
[info] Available formats for be7dc086-c442-4685-8116-ddeac2248c31:
ID           EXT   RESOLUTION │ PROTO │ VCODEC MORE INFO
─────────────────────────────────────────────────────────
spritesheets mhtml unknown    │ mhtml │ images storyboard
(env_video_dnld) pavel@MISSURI:~/env_video_dnld$
```

**Comment by bashonly** [comment] 2024-06-17 03:37
Duplicate of #10175

Fixed in master. Update to nightly:

```
python3 -m pip install -U --pre "yt-dlp[default]"
```

**Closed by bashonly** 2024-06-17 03:37 UTC
Labels: site-bug, triage
