### ISSUE TITLE
NBC 404

### ISSUE THREAD

**Issue by jriker1** [yt-dlp/yt-dlp#1627] opened 2021-11-11 01:31 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Make sure latest version of yt-dlp is installed with pip on Windows.  Getting 404 errors with NBC trying to download shows.  Like The Voice: https://www.nbc.com/the-voice/video/live-top-20-eliminations/9000210543

Getting grabbed a piece as it went by: 

```
[hls @ 000002069e5de400] Opening 'crypto+https://nbcmpx-vh.akamaihd.net/i/prod/video/e6R/FAc/9000210543/NvPUJ2CseGaIWyfokWT-d/HD_TVE_THEVOICE_11092021_,185,783,483,300,86,35,0k.mp4.csmil/segment9_1_av.ts?null=0&id=AgBi5NtzFyFU6HpxjGFhRCLZL7o8LGMaHksUM1TJa0scsu9J%2fxJUIJxrGC0iNc9+FuJxqmzpoQpE3w%3d%3d&hdntl=exp=1636680442~acl=/i/prod/video/e6R/FAc/9000210543/NvPUJ2CseGaIWyfokWT-d/HD_TVE_THEVOICE_11092021_*~data=hdntl~hmac=124b6509f343ded3b5e3ad2c960bfbc31ad194e6195393866dd4c22e4c7e9eea' for reading
[https @ 000002069e5e8a00] HTTP error 404 Not Found
[crypto @ 000002069ec00cc0] Unable to open resource: https://nbcmpx-vh.akamaihd.net/i/prod/video/e6R/FAc/9000210543/NvPUJ2CseGaIWyfokWT-d/HD_TVE_THEVOICE_11092021_,185,783,483,300,86,35,0k.mp4.csmil/segment9_1_av.ts?null=0&id=AgBi5NtzFyFU6HpxjGFhRCLZL7o8LGMaHksUM1TJa0scsu9J%2fxJUIJxrGC0iNc9+FuJxqmzpoQpE3w%3d%3d&hdntl=exp=1636680442~acl=/i/prod/video/e6R/FAc/9000210543/NvPUJ2CseGaIWyfokWT-d/HD_TVE_THEVOICE_11092021_*~data=hdntl~hmac=124b6509f343ded3b5e3ad2c960bfbc31ad194e6195393866dd4c22e4c7e9eea
[hls @ 000002069e5de400] Failed to open segment 9 of playlist 0
[hls @ 000002069e5de400] Opening 'crypto+https://nbcmpx-vh.akamaihd.net/i/prod/video/e6R/FAc/9000210543/NvPUJ2CseGaIWyfokWT-d/HD_TVE_THEVOICE_11092021_,185,783,483,300,86,35,0k.mp4.csmil/segment10_1_av.ts?null=0&id=AgBi5NtzFyFU6HpxjGFhRCLZL7o8LGMaHksUM1TJa0scsu9J%2fxJUIJxrGC0iNc9+FuJxqmzpoQpE3w%3d%3d&hdntl=exp=1636680442~acl=/i/prod/video/e6R/FAc/9000210543/NvPUJ2CseGaIWyfokWT-d/HD_TVE_THEVOICE_11092021_*~data=hdntl~hmac=124b6509f343ded3b5e3ad2c960bfbc31ad194e6195393866dd4c22e4c7e9eea' for reading
[https @ 000002069e5e8a00] HTTP error 404 Not Found
[crypto @ 000002069ec00cc0] Unable to open resource: https://nbcmpx-vh.akamaihd.net/i/prod/video/e6R/FAc/9000210543/NvPUJ2CseGaIWyfokWT-d/HD_TVE_THEVOICE_11092021_,185,783,483,300,86,35,0k.mp4.csmil/segment10_1_av.ts?null=0&id=AgBi5NtzFyFU6HpxjGFhRCLZL7o8LGMaHksUM1TJa0scsu9J%2fxJUIJxrGC0iNc9+FuJxqmzpoQpE3w%3d%3d&hdntl=exp=1636680442~acl=/i/prod/video/e6R/FAc/9000210543/NvPUJ2CseGaIWyfokWT-d/HD_TVE_THEVOICE_11092021_*~data=hdntl~hmac=124b6509f343ded3b5e3ad2c960bfbc31ad194e6195393866dd4c22e4c7e9eea
[hls @ 000002069e5de400] Failed to open segment 10 of playlist 0
[hls @ 000002069e5de400] Opening 'crypto+https://nbcmpx-vh.akamaihd.net/i/prod/video/e6R/FAc/9000210543/NvPUJ2CseGaIWyfokWT-d/HD_TVE_THEVOICE_11092021_,185,783,483,300,86,35,0k.mp4.csmil/segment11_1_av.ts?null=0&id=AgBi5NtzFyFU6HpxjGFhRCLZL7o8LGMaHksUM1TJa0scsu9J%2fxJUIJxrGC0iNc9+FuJxqmzpoQpE3w%3d%3d&hdntl=exp=1636680442~acl=/i/prod/video/e6R/FAc/9000210543/NvPUJ2CseGaIWyfokWT-d/HD_TVE_THEVOICE_11092021_*~data=hdntl~hmac=124b6509f343ded3b5e3ad2c960bfbc31ad194e6195393866dd4c22e4c7e9eea' for reading

```

Command was basically:

`--audio-quality 0 --add-metadata --ap-mso Comcast_SSO --ap-username <myloginname> --ap-password <my_login_password> https://www.nbc.com/the-voice/video/live-top-20-eliminations/9000210543 -o "The Voice S21E16.mp4"`

### Verbose log

```shell
[debug] Command-line config: ['--audio-quality', '0', '--add-metadata', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.nbc.com/the-voice/video/live-top-20-eliminations/9000210543', '-o', 'The Voice S21E16.mp4', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.9.0 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [NBC] Extracting URL: https://www.nbc.com/the-voice/video/live-top-20-eliminations/9000210543
[NBC] 9000210543: Downloading JSON metadata
[NBC] 9000210543: Downloading JSON metadata
[NBC] 9000210543: Downloading Provider Redirect Page
[NBC] 9000210543: Confirming auto login
[NBC] 9000210543: Retrieving Session
[debug] Saving ap-mvpd.nbcentertainment to cache
[NBC] 9000210543: Retrieving Authorization Token
[debug] Saving ap-mvpd.nbcentertainment to cache
[NBC] 9000210543: Retrieving Media Token
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/NnzsPC/media/guid/2410887629/9000210543?mbr=true&manifest=m3u&auth=%3CsignatureInfo%3ERam9%2FKPhRdtaBdqIeFV2D4uENUqbRr326cZwtTNs%2F%2FVnSI0cgX3TpHhVsL20ZljOFZNcdseJA%2BuNhXDLV3S7BMuxgJxCBMsaptjp%2B5FZPZATlP7WIjbggg6dkZi%2F1VBOKc39zE4NtVO8b7YtVaNX1T3GVilAmsxYqS1Bafr7GCU%3D%3CsignatureInfo%3E%3CauthToken%3E%3CsessionGUID%3E4fc043b16ed1aff6ef1d0fad32591510%3C%2FsessionGUID%3E%3CrequestorID%3Enbcentertainment%3C%2FrequestorID%3E%3CresourceID%3E%3C%21%5BCDATA%5B%3Crss+version%3D%222.0%22+xmlns%3Amedia%3D%22http%3A%2F%2Fsearch.yahoo.com%2Fmrss%2F%22%3E%3Cchannel%3E%3Ctitle%3Enbcentertainment%3C%2Ftitle%3E%3Citem%3E%3Ctitle%3ELive+Top+20+Eliminations%3C%2Ftitle%3E%3Cguid%3E9000210543%3C%2Fguid%3E%3Cmedia%3Arating+scheme%3D%22urn%3Av-chip%22%3ETV-PG%3C%2Fmedia%3Arating%3E%3C%2Fitem%3E%3C%2Fchannel%3E%3C%2Frss%3E%5D%5D%3E%3C%2FresourceID%3E%3Cttl%3E420000%3C%2Fttl%3E%3CissueTime%3E2021-11-10+17%3A30%3A28+-0800%3C%2FissueTime%3E%3CmvpdId%3EComcast_SSO%3C%2FmvpdId%3E%3C%2FauthToken%3E#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 9000210543: Downloading SMIL data
[ThePlatform] 9000210543: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] 9000210543: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 9000210543: Downloading 1 format(s): hls-7927
[debug] Invoking downloader on "https://nbcmpx-vh.akamaihd.net/i/prod/video/e6R/FAc/9000210543/NvPUJ2CseGaIWyfokWT-d/HD_TVE_THEVOICE_11092021_,185,783,483,300,86,35,0k.mp4.csmil/index_1_av.m3u8?null=0&id=AgBi5NtzFyFU+jVyjGEXuW97tf8ZihW4P2ovrLLmQtKtKB1h9+Ge0MIAn5wTgq%2fhfQBjBmFPq+NsEQ%3d%3d&hdntl=exp=1636680629~acl=%2fi%2fprod%2fvideo%2fe6R%2fFAc%2f9000210543%2fNvPUJ2CseGaIWyfokWT-d%2fHD_TVE_THEVOICE_11092021_*~data=hdntl~hmac=f29c2a44f0b8c4fe84257b5e5e748f85982464b36b462a6716538dbcd550de8a"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 258
[download] Destination: The Voice S21E16.mp4
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10) ...
ERROR: Giving up after 10 fragment retries
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jriker1.ICEO\AppData\Local\Programs\Python\Python39\Scripts\yt-dlp.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\__init__.py", line 795, in main
    _real_main(argv)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\__init__.py", line 785, in _real_main
    retcode = ydl.download(all_urls)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2965, in download
    self.__download_wrapper(self.extract_info)(
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2942, in wrapper
    res = func(*args, **kwargs)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1303, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1311, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1349, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1451, in process_ie_result
    return self.process_ie_result(
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1399, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2430, in process_video_result
    self.process_info(new_info)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2853, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2578, in dl
    return fd.download(name, new_info, subtitle)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\common.py", line 399, in download
    ret = self.real_download(filename, info_dict)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\hls.py", line 349, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\fragment.py", line 487, in download_and_append_fragments
    frag_content, frag_index = download_fragment(fragment, ctx)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\fragment.py", line 450, in download_fragment
    self.report_error('Giving up after %s fragment retries' % fragment_retries)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\common.py", line 172, in report_error
    self.ydl.report_error(*args, **kargs)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 881, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', tb)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 820, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

ERROR: object of type 'bool' has no len()
Traceback (most recent call last):
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1311, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1349, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1451, in process_ie_result
    return self.process_ie_result(
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1399, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2430, in process_video_result
    self.process_info(new_info)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2853, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2578, in dl
    return fd.download(name, new_info, subtitle)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\common.py", line 399, in download
    ret = self.real_download(filename, info_dict)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\hls.py", line 349, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\fragment.py", line 488, in download_and_append_fragments
    result = append_fragment(decrypt_fragment(fragment, frag_content), frag_index, ctx)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\fragment.py", line 368, in decrypt_fragment
    decrypted_data = aes_cbc_decrypt_bytes(frag_content, decrypt_info['KEY'], iv)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\aes.py", line 12, in aes_cbc_decrypt_bytes
    return compat_pycrypto_AES.new(key, compat_pycrypto_AES.MODE_CBC, iv).decrypt(data)
  File "c:\users\jriker1.iceo\appdata\local\programs\python\python39\lib\site-packages\Cryptodome\Cipher\_mode_cbc.py", line 229, in decrypt
    plaintext = create_string_buffer(len(ciphertext))
TypeError: object of type 'bool' has no len()
```

**Comment by pukkandan** [comment] 2021-12-08 22:30
Issue is that Comcast_SSO is broken. Duplicate of #516

**Closed by pukkandan** 2021-12-08 22:30 UTC
Labels: account-needed, extractor-bug
