### ISSUE TITLE
yt-dlp don't support telegram?follow is my script and an error output,can you help me?

### ISSUE THREAD

**Issue by mingming-ctr** [yt-dlp/yt-dlp#6452] opened 2023-03-06 15:40 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood
```
yt-dlp  -vU   https://t.me/iPapkorn/784
[debug] Command-line config: ['-vU', 'https://t.me/iPapkorn/784']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe) 
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021) 
[debug] exe versions: ffmpeg N-109961-gad17e29224-20230305 (setts), ffprobe N-109961-gad17e29224-20230305 
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4 
[debug] Proxy map: {'http': 'http://127.0.0.1:10809', 'https': 'https://127.0.0.1:10809', 'ftp': 'ftp://127.0.0.1:10809'} 
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[telegram:embed] Extracting URL: https://t.me/iPapkorn/784
[telegram:embed] 784: Downloading embed frame
WARNING: [telegram:embed] unable to extract video URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: Extractor telegram:embed returned nothing; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment] 2023-03-06 16:08
Does the video load in your web browser? It doesn't for me:

> Media is too big
> VIEW IN TELEGRAM

The telegram extractor does not currently support native app-only content

**Comment by gamer191** [comment] 2023-03-06 23:12
I think this is a duplicate of #3606, although your verbose log has a slightly different error message, so I'm not sure, and I don't have time to test if that's due to you using a newer version of yt-dlp

On a side note, please use the site-bug template in future

**Closed** 2023-03-07 07:21 UTC
Labels: site-enhancement, triage
