### ISSUE TITLE
[Broken] HTTP Error 400 in viki videos

### ISSUE THREAD

**Issue by bladeosen** [yt-dlp/yt-dlp#651] opened 2021-08-08 01:42 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\chris\Desktop\pro>yt-dlp.exe --verbose --all-subs --embed-subs --write-auto-subs --hls-prefer-ffmpeg https://www.viki.com/videos/1177210v-replay-episode-1
[debug] Command-line config: ['--verbose', '--all-subs', '--embed-subs', '--write-auto-subs', '--hls-prefer-ffmpeg', 'https://www.viki.com/videos/1177210v-replay-episode-1']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [viki] Extracting URL: https://www.viki.com/videos/1177210v-replay-episode-1
[viki] 1177210v: Downloading video JSON
[viki] 1177210v: Downloading video streams JSON
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 679, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3158, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

## Description

Error when I trying download viki videos but not in all videos

**Comment by bladeosen** [comment] 2021-08-08 01:43
Error when I trying download viki videos but not in all videos

**Comment by bursthead5000** [comment] 2021-08-08 02:57
**Be sure to call yt-dlp with the --verbose flag and include its complete output**

**Comment by pukkandan** [comment] 2021-08-08 03:21
Provide verbose output. Dont use screenshot

**Comment by bladeosen** [comment] 2021-08-08 11:11
Sorry, it's done

C:\Users\chris\Desktop\pro>yt-dlp.exe --verbose --all-subs --embed-subs --write-auto-subs --hls-prefer-ffmpeg https://www.viki.com/videos/1177210v-replay-episode-1
[debug] Command-line config: ['--verbose', '--all-subs', '--embed-subs', '--write-auto-subs', '--hls-prefer-ffmpeg', 'https://www.viki.com/videos/1177210v-replay-episode-1']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.0, ffprobe 4.0, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [viki] Extracting URL: https://www.viki.com/videos/1177210v-replay-episode-1
[viki] 1177210v: Downloading video JSON
[viki] 1177210v: Downloading video streams JSON
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 679, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3158, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default

**Comment by zackmark29** [comment] 2021-08-08 21:21
Yeah non-drm not available for this
error in my tool: [ERROR]:DRM playback unsupported | cannot serve non-drm content

**Comment by llacb47** [comment] 2021-08-08 21:45
This extractor should display a more appropriate error message when `api.viki.io/v5/playback_streams/`  returns HTTP 400, clearly informing the user that viki does not permit non-DRM versions to be accessed. Related: https://github.com/yt-dlp/yt-dlp/issues/636

**Comment by pukkandan** [comment] 2021-08-08 21:48
> This extractor should display a more appropriate error message when api.viki.io/v5/playback_streams/ returns HTTP 400

Agreed. hence why I didn't close this issue

But, this is not actually the same as #636. That is trying to address the cases where we already detect DRM, but only raise a "No formats" error. In this case, the current code doesn't understand whether the error is DRM or not

**Comment by zackmark29** [comment] 2021-08-09 03:25
Yeah it should raise drm error. The viki response has specific error message for drm content.
```
{'vcode': 6460, 'error': 'DRM playback unsupported', 'details': 'cannot serve non-drm content'}
```

**Closed** 2021-08-09 19:53 UTC
Labels: DRM

**Comment by FJ0451** [comment] 2021-08-11 23:20
Apologies if this is a naive question, is it typical to get a DRM error on only a subset of episodes within the same series on Viki? For example Viki series 'Healer' episodes 1,2,6,8,10,11,12,15 won't download, but all the _other_ episodes do. This seems to be working as intended but that sure seems like a weird choice on Vikis part?

**Comment by zackmark29** [comment] 2021-08-13 04:38
> Apologies if this is a naive question, is it typical to get a DRM error on only a subset of episodes within the same series on Viki? For example Viki series 'Healer' episodes 1,2,6,8,10,11,12,15 won't download, but all the _other_ episodes do. This seems to be working as intended but that sure seems like a weird choice on Vikis part?

For Healer, When you see Kocowa tag it means it doesn't have non-drm content. Or maybe non-drm available on some episode (like what you said)

![image](https://user-images.githubusercontent.com/62680932/129305519-3af7c441-51da-4757-8a5c-7c7b89436373.png)
