### ISSUE TITLE
ap-mso YouTube TV support

### ISSUE THREAD

**Issue by Joe-Applebrook** [yt-dlp/yt-dlp#8595] opened 2023-11-17 02:01 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [x] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I would like to download from a website that requires me to log into a TV provider, but all I have is YouTube TV, which isn't supported. I was wondering if there were plans to add it to the list of supported providers.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Joe-Applebrook** [comment] 2023-11-17 02:03
(Apologies if I did something wrong while filling this out, I'm not very code-savvy and I've never really used GitHub before)

**Comment by bashonly** [comment] 2023-11-17 04:27
Duplicate of #1034

> (Apologies if I did something wrong while filling this out, I'm not very code-savvy and I've never really used GitHub before)

no worries / all good

**Closed by bashonly** 2023-11-17 04:27 UTC
Labels: enhancement, triage
