### ISSUE TITLE
'Connection to rr2---sn-cxaaj5o5q5-t9cl.googlevideo.com timed out'

### ISSUE THREAD

**Issue by rapre8** [yt-dlp/yt-dlp#8800] opened 2023-12-19 03:01 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

Issue: Keeps retrying to connect to something... not well versed enough to help here.
Issue happens for all the videos i try to download. I can access and watch the videos normally....
Possible cause: I do not know 
Possible solutions: Once again, no clue.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\rapha>yt-dlp -vU --extract-audio --audio-format mp3 --audio-quality 0 -o "C:\Users\rapha\Music\YOUTUBE_DOWNLOADER\%(title)s-%(id)s.%(ext)s"  --playlist-start 4 --playlist-end 44 --embed-metadata -R 20 -N 5 PLMepJhedUEnK7nJHP46ErlqKvk-VC9gqV
[debug] Command-line config: ['-vU', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', '-o', 'C:\\Users\\rapha\\Music\\YOUTUBE_DOWNLOADER\\%(title)s-%(id)s.%(ext)s', '--playlist-start', '4', '--playlist-end', '44', '--embed-metadata', '-R', '20', '-N', '5', 'PLMepJhedUEnK7nJHP46ErlqKvk-VC9gqV']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.12.18.232711 from yt-dlp/yt-dlp-nightly-builds [00a3e47bf] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109937-g05438db024-20230228 (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1795 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2023.12.18.232711 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2023.12.18.232711 from yt-dlp/yt-dlp-nightly-builds)
[youtube:playlist] Extracting URL: PLMepJhedUEnK7nJHP46ErlqKvk-VC9gqV
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLMepJhedUEnK7nJHP46ErlqKvk-VC9gqV
[youtube:tab] PLMepJhedUEnK7nJHP46ErlqKvk-VC9gqV: Downloading webpage
WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos are hidden
[youtube:tab] PLMepJhedUEnK7nJHP46ErlqKvk-VC9gqV: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Beats
[youtube:tab] Playlist Beats: Downloading 41 items of 2244
[download] Downloading item 1 of 41
[youtube] Extracting URL: https://www.youtube.com/watch?v=1OMvEZaM414
[youtube] 1OMvEZaM414: Downloading webpage
[youtube] 1OMvEZaM414: Downloading ios player API JSON
[youtube] 1OMvEZaM414: Downloading android player API JSON
[youtube] 1OMvEZaM414: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] 1OMvEZaM414: Downloading 1 format(s): 251
[download] C:\Users\rapha\Music\YOUTUBE_DOWNLOADER\Pink Blood +-1OMvEZaM414.mp3 has already been downloaded
[debug] ffmpeg command line: ffprobe -show_streams "file:C:\Users\rapha\Music\YOUTUBE_DOWNLOADER\Pink Blood +-1OMvEZaM414.mp3"
[ExtractAudio] Not converting audio C:\Users\rapha\Music\YOUTUBE_DOWNLOADER\Pink Blood +-1OMvEZaM414.mp3; file is already in target format mp3
[Metadata] Adding metadata to "C:\Users\rapha\Music\YOUTUBE_DOWNLOADER\Pink Blood +-1OMvEZaM414.mp3"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\Users\rapha\Music\YOUTUBE_DOWNLOADER\Pink Blood +-1OMvEZaM414.mp3" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=Pink Blood +" -metadata "date=20230315" -metadata "description=Provided to YouTube by Foundation Media LLC

Pink Blood + · TOKYOPILL

Abandon The Flesh !

℗ 2022 LISTEN TO THE KIDS

Released on: 2022-03-14

Main  Artist: TOKYOPILL
Producer: TOKYOPILL
Author: TOKYOPILL

Auto-generated by YouTube." -metadata "synopsis=Provided to YouTube by Foundation Media LLC

Pink Blood + · TOKYOPILL

Abandon The Flesh !

℗ 2022 LISTEN TO THE KIDS

Released on: 2022-03-14

Main  Artist: TOKYOPILL
Producer: TOKYOPILL
Author: TOKYOPILL

Auto-generated by YouTube." -metadata "purl=https://www.youtube.com/watch?v=1OMvEZaM414" -metadata "comment=https://www.youtube.com/watch?v=1OMvEZaM414" -metadata "artist=TOKYOPILL" -metadata "album=Abandon The Flesh !" -movflags "+faststart" "file:C:\Users\rapha\Music\YOUTUBE_DOWNLOADER\Pink Blood +-1OMvEZaM414.temp.mp3"
[download] Downloading item 2 of 41
[youtube] Extracting URL: https://www.youtube.com/watch?v=ZuqZ9WPOJW8
[youtube] ZuqZ9WPOJW8: Downloading webpage
[youtube] ZuqZ9WPOJW8: Downloading ios player API JSON
[youtube] ZuqZ9WPOJW8: Downloading android player API JSON
[youtube] ZuqZ9WPOJW8: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] ZuqZ9WPOJW8: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr2---sn-cxaaj5o5q5-t9cl.googlevideo.com/videoplayback?expire=1702976041&ei=yQWBZdzJEJ6P_9EP176SkAw&ip=70.54.165.79&id=o-AKByrM6zcxRe5C4Mfec-xrgjflPNoV1mjilc5hXTxWq2&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=5y&mm=31%2C29&mn=sn-cxaaj5o5q5-t9cl%2Csn-cxaaj5o5q5-t0ak&ms=au%2Crdu&mv=m&mvi=2&pl=24&gcr=ca&initcwndbps=2223750&spc=UWF9f19wSnOuruZKIDhuJ_2HknApDi8&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=2633822&dur=168.021&lmt=1686177954288561&mt=1702954130&fvip=1&keepalive=yes&fexp=24007246&c=ANDROID&txp=2318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAK4zJ0SsHmr7WqbGULxdUJJwfOp0SvUc1CfYdkcNksUUAiB1oHtdVeRqcMrdPE_eKdaG6BClzc5zXpFwxbYINRrOwg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRAIgMRo3lIplQuWqCNPC8RVyBSFtL6QGA8rYv_-SKEUS20UCIDOpL7j6e7DdIvtYRH0FqpWkwkDyu-t7qJYQ2cXlhDhI"
[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x00000260B7025220>, 'Connection to rr2---sn-cxaaj5o5q5-t9cl.googlevideo.com timed out. (connect timeout=20.0)'). Retrying (1/20)...
[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x00000260B6F14D90>, 'Connection to rr2---sn-cxaaj5o5q5-t9cl.googlevideo.com timed out. (connect timeout=20.0)'). Retrying (2/20)...
```
```

**Comment by gamer191** [comment] 2023-12-19 10:22
can you please run this command and send the output:
```
yt-dlp --verbose "https://rr2---sn-cxaaj5o5q5-t9cl.googlevideo.com/" "https://rr2---sn-cxaaj5o5q5-t0ak.googlevideo.com/"
```

**Comment by rapre8** [comment] 2023-12-20 01:10
Here it is:
```
yt-dlp --verbose "https://rr2---sn-cxaaj5o5q5-t9cl.googlevideo.com/" "https://rr2---sn-cxaaj5o5q5-t0ak.googlevideo.com/"
[debug] Command-line config: ['--verbose', 'https://rr2---sn-cxaaj5o5q5-t9cl.googlevideo.com/', 'https://rr2---sn-cxaaj5o5q5-t0ak.googlevideo.com/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.12.18.232711 from yt-dlp/yt-dlp-nightly-builds [00a3e47bf] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109937-g05438db024-20230228 (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1795 extractors
[generic] Extracting URL: https://rr2---sn-cxaaj5o5q5-t9cl.googlevideo.com/
[generic] rr2---sn-cxaaj5o5q5-t9cl.googlevideo: Downloading webpage
ERROR: [generic] Unable to download webpage: (<urllib3.connection.HTTPSConnection object at 0x000002A2E2ED8430>, 'Connection to rr2---sn-cxaaj5o5q5-t9cl.googlevideo.com timed out. (connect timeout=20.0)') (caused by TransportError("(<urllib3.connection.HTTPSConnection object at 0x000002A2E2ED8430>, 'Connection to rr2---sn-cxaaj5o5q5-t9cl.googlevideo.com timed out. (connect timeout=20.0)')"))
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2392, in _real_extract
  File "yt_dlp\extractor\common.py", line 863, in _request_webpage

  File "urllib3\connection.py", line 203, in _new_conn
  File "urllib3\util\connection.py", line 85, in create_connection
  File "urllib3\util\connection.py", line 73, in create_connection
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\networking\_requests.py", line 304, in _send
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 445, in increment
  File "urllib3\util\util.py", line 39, in reraise
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 491, in _make_request
  File "urllib3\connectionpool.py", line 467, in _make_request
  File "urllib3\connectionpool.py", line 1096, in _validate_conn
  File "urllib3\connection.py", line 611, in connect
  File "urllib3\connection.py", line 212, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000002A2E2ED8430>, 'Connection to rr2---sn-cxaaj5o5q5-t9cl.googlevideo.com timed out. (connect timeout=20.0)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 850, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4069, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_requests.py", line 332, in _send
yt_dlp.networking.exceptions.TransportError: (<urllib3.connection.HTTPSConnection object at 0x000002A2E2ED8430>, 'Connection to rr2---sn-cxaaj5o5q5-t9cl.googlevideo.com timed out. (connect timeout=20.0)')

[generic] Extracting URL: https://rr2---sn-cxaaj5o5q5-t0ak.googlevideo.com/
[generic] rr2---sn-cxaaj5o5q5-t0ak.googlevideo: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\generic.py", line 2392, in _real_extract
  File "yt_dlp\extractor\common.py", line 863, in _request_webpage

  File "yt_dlp\YoutubeDL.py", line 4069, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_requests.py", line 341, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 850, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4101, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found
```

**Comment by NotZoeyDev** [comment] 2023-12-20 01:14
I'm also having the same issue and it seems to have been happening for a few days now.
Based off @rapre8's profile, we're more likely to be living in the same area (Québec).

It might be a region based issue or an ISP issue.

**Comment by rapre8** [comment] 2023-12-20 01:46
Hi yall, following @NotZoeyDev's comment, I tried using a VPN, and it somehow allowed the initial code to work. So your hypothesis sounds good.

**Comment by gamer191** [comment] 2023-12-20 02:30
@rapre8 your issue is a duplicate of https://github.com/yt-dlp/yt-dlp/issues/1986. I'd recommend you to either:
1. Wait for the issue to resolve itself, if it hasn't already
2. use a vpn, --force-ipv4 or --force-ipv6
3. if you're an advanced user, use `--print urls` to get the video URLs, then follow the instructions at #1986 to manually modify the URLs, then merge them manually. Alternatively, you can use `-f b` to cap the formats at 720p, and hence ensure you don't have to manually merge them

@NotZoeyDev your issue is probably also a duplicate of #1986, but I can't know if you don't post a verbose log. Just run your original command with `--verbose` and send the output. Also, please send the output of `yt-dlp --verbose "https://rr2---sn-cxaaj5o5q5-t9cl.googlevideo.com/" "https://rr2---sn-cxaaj5o5q5-t0ak.googlevideo.com/"`

**Closed** 2023-12-31 03:56 UTC
Labels: incomplete, site-bug, triage
