### ISSUE TITLE
[Bug] Postprocessing Conversion Failed

### ISSUE THREAD

**Issue by Obscure2020** [yt-dlp/yt-dlp#1228] opened 2021-10-10 19:44 UTC
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Verbose log

```
C:\Testing>yt-dlp -F https://youtu.be/jR_L0paWJCY
[youtube] jR_L0paWJCY: Downloading webpage
[youtube] jR_L0paWJCY: Downloading android player API JSON
[youtube] jR_L0paWJCY: Downloading MPD manifest
[youtube] jR_L0paWJCY: Downloading MPD manifest
[info] Available formats for jR_L0paWJCY:
ID  EXT  RESOLUTION FPS |  FILESIZE   TBR PROTO | VCODEC        VBR ACODEC     ABR  ASR    MORE INFO
--- ---- ---------- --- - --------- ----- ----- - ----------- ----- --------- ---- ------- ---------------------
139 m4a  audio only     |  1.64MiB    47k https |                   mp4a.40.5  47k 22050Hz low, m4a_dash
140 m4a  audio only     |  4.37MiB   127k https |                   mp4a.40.2 127k 44100Hz medium, m4a_dash
251 webm audio only     |  3.90MiB   113k https |                   opus      113k 48000Hz medium, webm_dash
17  3gp  176x144    10  |  2.75MiB    80k https | mp4v.20.3     80k mp4a.40.2   0k 22050Hz 144p
160 mp4  256x144    30  |            108k dash  | avc1.4d400b  108k                        DASH video, mp4_dash
278 webm 256x144    30  |             95k dash  | vp9           95k                        DASH video, webm_dash
133 mp4  426x240    30  |            242k dash  | avc1.4d400c  242k                        DASH video, mp4_dash
242 webm 426x240    30  |            220k dash  | vp9          220k                        DASH video, webm_dash
134 mp4  640x360    30  |  17.78MiB  517k https | avc1.4d401e  517k                        360p, mp4_dash
18  mp4  640x360    30  |  22.83MiB  663k https | avc1.42001E  663k mp4a.40.2   0k 44100Hz 360p
243 webm 640x360    30  |            405k dash  | vp9          405k                        DASH video, webm_dash
135 mp4  854x480    30  |           1155k dash  | avc1.4d4014 1155k                        DASH video, mp4_dash
244 webm 854x480    30  |            752k dash  | vp9          752k                        DASH video, webm_dash
136 mp4  1280x720   30  |           2310k dash  | avc1.4d4016 2310k                        DASH video, mp4_dash
22  mp4  1280x720   30  |           2120k https | avc1.64001F 2120k mp4a.40.2   0k 44100Hz 720p
247 webm 1280x720   30  |           1505k dash  | vp9         1505k                        DASH video, webm_dash
298 mp4  1280x720   60  |           3465k dash  | avc1.4d4016 3465k                        DASH video, mp4_dash
302 webm 1280x720   60  |           2646k dash  | vp9         2646k                        DASH video, webm_dash
299 mp4  1920x1080  60  |           5775k dash  | avc1.64001e 5775k                        DASH video, mp4_dash
303 webm 1920x1080  60  |           4410k dash  | vp9         4410k                        DASH video, webm_dash

C:\Testing>yt-dlp -Uv -N 5 --merge-output-format mkv --format-sort codec --embed-thumbnail --embed-metadata https://youtu.be/jR_L0paWJCY
[debug] Command-line config: ['-Uv', '-N', '5', '--merge-output-format', 'mkv', '--format-sort', 'codec', '--embed-thumbnail', '--embed-metadata', 'https://youtu.be/jR_L0paWJCY']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.10.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.10)
[debug] [youtube] Extracting URL: https://youtu.be/jR_L0paWJCY
[youtube] jR_L0paWJCY: Downloading webpage
[youtube] jR_L0paWJCY: Downloading android player API JSON
[youtube] jR_L0paWJCY: Downloading MPD manifest
[youtube] jR_L0paWJCY: Downloading MPD manifest
[debug] Sort order given by user: codec
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, vcodec, acodec, quality, res, fps, source, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] jR_L0paWJCY: Downloading 1 format(s): 303+251
[debug] Testing thumbnail 39
[debug] Testing thumbnail 38
[debug] Testing thumbnail 36
[debug] Testing thumbnail 35
[debug] Testing thumbnail 34
[debug] Testing thumbnail 33
[debug] Testing thumbnail 32
[debug] Testing thumbnail 31
[debug] Testing thumbnail 30
[info] Downloading video thumbnail ...
[info] Writing video thumbnail to: Donkey Kong Country 2 - Stickerbush Symphony [VRC6 Cover] (Oscilloscope Visual) [jR_L0paWJCY].webp
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1633915482/ei/-j1jYYL_J8f92_gP6IKTyAY/ip/130.108.234.39/id/8d1fcbd296962426/source/youtube/requiressl/yes/playback_host/r1---sn-v5goxu-jhiz.googlevideo.com/mh/m4/mm/31%2C29/mn/sn-v5goxu-jhiz%2Csn-vgqsknee/ms/au%2Crdu/mv/m/mvi/1/pl/16/tx/24027694/txs/24027691%2C24027692%2C24027693%2C24027694%2C24067852/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1102500/vprv/1/mt/1633893404/fvip/1/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgPgWK_Wu-V7ToigeTe5ju2p7eMbfnjo-VvfgTyU7yM6UCIQCJ9AKO6fi0aP7QUSeFr8e3q-_DoCUk6Xgv2uk62uf5HA%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIhAMJABDw60mwOtGb54stsx6VnUSrGKo-6b0xrnXKMfDc7AiAMcodDyBg4Fgh7EyiyYj6DfUES4HC309WTTGopKiTSeQ%3D%3D"
[dashsegments] Total fragments: 56
[download] Destination: Donkey Kong Country 2 - Stickerbush Symphony [VRC6 Cover] (Oscilloscope Visual) [jR_L0paWJCY].f303.webm
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download] 100% of 124.51MiB in 00:03
[debug] Invoking downloader on "https://r1---sn-v5goxu-jhiz.googlevideo.com/videoplayback?expire=1633915483&ei=-z1jYaPNE4jKjAS74bzgAg&ip=130.108.234.39&id=o-ADsHjTafDdlwjFop6KjhjEms-io7J93Tqnke8qnJ4Hf3&itag=251&source=youtube&requiressl=yes&mh=m4&mm=31%2C29&mn=sn-v5goxu-jhiz%2Csn-vgqsknee&ms=au%2Crdu&mv=m&mvi=1&pl=16&initcwndbps=1102500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=4088471&otfp=1&dur=288.581&lmt=1565752741087333&mt=1633893404&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIgFcVPwpEdvq_-kIzpSZkrkemEBEhfm1mKpQTKSn2ry-sCIQC1l86IVWVHdwtm4llX4PmZpf8E-V2x2j5KiEwT2iCKRQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAM2ViYIoJPIR3vBtLu6pBALmpTJj_IzBCZTNBNnGpjF7AiEAjrOCU9tLRkEyQH4HXh8voVDn9UszAEIRy3KvlMLcaSU%3D"
[download] Destination: Donkey Kong Country 2 - Stickerbush Symphony [VRC6 Cover] (Oscilloscope Visual) [jR_L0paWJCY].f251.webm
[download] 100% of 3.90MiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams "file:Donkey Kong Country 2 - Stickerbush Symphony [VRC6 Cover] (Oscilloscope Visual) [jR_L0paWJCY].f251.webm"
[Merger] Merging formats into "Donkey Kong Country 2 - Stickerbush Symphony [VRC6 Cover] (Oscilloscope Visual) [jR_L0paWJCY].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Donkey Kong Country 2 - Stickerbush Symphony [VRC6 Cover] (Oscilloscope Visual) [jR_L0paWJCY].f303.webm" -i "file:Donkey Kong Country 2 - Stickerbush Symphony [VRC6 Cover] (Oscilloscope Visual) [jR_L0paWJCY].f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:Donkey Kong Country 2 - Stickerbush Symphony [VRC6 Cover] (Oscilloscope Visual) [jR_L0paWJCY].temp.mkv"
[debug] ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, matroska,webm, from 'file:Donkey Kong Country 2 - Stickerbush Symphony [VRC6 Cover] (Oscilloscope Visual) [jR_L0paWJCY].f303.webm':
  Metadata:
    encoder         : google/video-file
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 55
                    : Segment-Durations-Ms: 5333,5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),533
                    :
                    :
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1920x1080, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:Donkey Kong Country 2 - Stickerbush Symphony [VRC6 Cover] (Oscilloscope Visual) [jR_L0paWJCY].f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 00:04:48.58, start: -0.007000, bitrate: 113 kb/s
  Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Output #0, matroska, to 'file:Donkey Kong Country 2 - Stickerbush Symphony [VRC6 Cover] (Oscilloscope Visual) [jR_L0paWJCY].temp.mkv':
  Metadata:
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 55
                    : Segment-Durations-Ms: 5333,5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),5334,5333(r=1),533
                    :
                    :
    encoder         : Lavf58.76.100
  Stream #0:0(eng): Video: vp9 (Profile 0) (VP90 / 0x30395056), yuv420p(tv, bt709/unknown/unknown), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 60 tbr, 1k tbn, 1k tbc (default)
  Stream #0:1(eng): Audio: opus ([255][255][255][255] / 0xFFFFFFFF), 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[matroska @ 000001d0b5af4d00] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5350 >= 5333
av_interleaved_write_frame(): Invalid argument
frame=  323 fps=0.0 q=-1.0 Lsize=    2362kB time=00:00:05.36 bitrate=3608.8kbits/s speed= 658x
video:2317kB audio:70kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 2867, in process_info
  File "yt_dlp\YoutubeDL.py", line 3025, in post_process
  File "yt_dlp\YoutubeDL.py", line 2968, in run_pp
  File "yt_dlp\postprocessor\common.py", line 21, in run
  File "yt_dlp\postprocessor\common.py", line 108, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 741, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 255, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 292, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

## Description

For some bizarre reason, yt-dlp will happily download the components of [https://youtu.be/jR_L0paWJCY](https://youtu.be/jR_L0paWJCY) but seems incapable of stitching them together into an mkv. I'm having trouble figuring out what the problem is, as nothing about this specific video seems different or unique. I did some research online, and someone theorized that yt-dlp doesn't like merging VP9 video with OPUS audio, but that theory turned out to be wrong, as yt-dlp can download and merge [https://youtu.be/G1olTRCqWBc](https://youtu.be/G1olTRCqWBc) at the same settings (resulting in VP9 with OPUS) with no issues.

**Comment by pukkandan** [comment] 2021-10-10 21:50
Duplicate of #871

**Closed by pukkandan** 2021-10-10 21:50 UTC
Labels: bug, triage

**Comment by FSaldanha** [comment] 2024-04-29 21:46
In case someone else is facing the same issue, here are some less technical steps if you are unsure how to use the FFmpeg custom builds (assuming you are using Linux):

- Download the build [here](https://github.com/yt-dlp/FFmpeg-Builds)
- In the folder where you will run yt-dlp, create a new directory (e.g. `ffmpegytdlp`)
- Extract the files inside the `bin` folder of the download to this newly created directory
- Run `yt-dlp` with `--ffmpeg-location ./ffmpegytdlp`

Since I had to figure this out by reading multiple sources, I hope it helps.

**Comment by conectionist** [comment] 2025-01-18 14:54
> In case someone else is facing the same issue, here are some less technical steps if you are unsure how to use the FFmpeg custom builds (assuming you are using Linux):
> 
> * Download the build [here](https://github.com/yt-dlp/FFmpeg-Builds)
> * In the folder where you will run yt-dlp, create a new directory (e.g. `ffmpegytdlp`)
> * Extract the files inside the `bin` folder of the download to this newly created directory
> * Run `yt-dlp` with `--ffmpeg-location ./ffmpegytdlp`
> 
> Since I had to figure this out by reading multiple sources, I hope it helps.

This solution worked for me.
Thank you very much for taking the time to write it!
