### ISSUE TITLE
Channel4.com

### ISSUE THREAD

**Issue by SamuelWN** [yt-dlp/yt-dlp#3150] opened 2022-03-21 23:35 UTC
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United Kingdom

### Example URLs

- Single Video: https://www.channel4.com/programmes/8-out-of-10-cats-does-countdown/on-demand/71817-004
- Playlist: https://www.channel4.com/programmes/8-out-of-10-cats-does-countdown

### Description

Site requires that you access via a UK IP address and that you sign up for a free account. 

Videos are streamed via DASH.

### Verbose log

```shell
$ yt-dlp -vU  --cookies channel4.com_cookies.txt https://www.channel4.com/programmes/8-out-of-10-cats-does-countdown/on-demand/71817-004
[debug] Command-line config: ['-vU', '--cookies', 'channel4.com_cookies.txt', 'https://www.channel4.com/programmes/8-out-of-10-cats-does-countdown/on-demand/71817-004']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Python version 3.6.9 (CPython 64bit) - Linux-5.4.0-100-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg N-103180-g7dfdc15a27 (setts,fdk), ffprobe N-103180-g7dfdc15a27, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://www.channel4.com/programmes/8-out-of-10-cats-does-countdown/on-demand/71817-004
[generic] 71817-004: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 71817-004: Downloading webpage
[generic] 71817-004: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.channel4.com/programmes/8-out-of-10-cats-does-countdown/on-demand/71817-004
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1459, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 617, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3985, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.channel4.com/programmes/8-out-of-10-cats-does-countdown/on-demand/71817-004
```

**Comment by nyuszika7h** [comment] 2022-03-21 23:59
Duplicate of #1719 and #2605. The site has DRM so it can't be supported.

**Closed** 2022-03-22 00:33 UTC
Labels: site-request, triage
