### ISSUE TITLE
TVer's new URLs aren't being picked by yt-dlp

### ISSUE THREAD

**Issue by GT2000byte** [yt-dlp/yt-dlp#3331] opened 2022-04-07 06:43 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Description

Recently, the TVer website (Site to watch Japanese TV shows right after they have aired) received a new makeover, however with that the player also received an URL makeover. Before, the links accepted by yt-dlp/Open Video Downloader were:

**https://tver.jp/corner/f0102324**

Those worked fine. The new links the site began using are now:

**https://tver.jp/episodes/eprotqfwwv**

Which immediately throws an error in OVD and yt-dlp cannot accept. Hope there's a workaround for said new URL format, I can only download from there by getting the video & audio streams separated.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://tver.jp/episodes/eprotqfwwv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://tver.jp/episodes/eprotqfwwv
[generic] eprotqfwwv: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] eprotqfwwv: Downloading webpage
[generic] eprotqfwwv: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://tver.jp/episodes/eprotqfwwv
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\generic.py", line 3985, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tver.jp/episodes/eprotqfwwv
```

**Comment by Lesmiscore** [comment] 2022-04-07 06:56
Duplicate of #3261

**Closed by Lesmiscore** 2022-04-07 06:56 UTC
Labels: site-bug, triage
