### ISSUE TITLE
--download-sections doens't work on youtube livestream

### ISSUE THREAD

**Issue by rrfqi** [yt-dlp/yt-dlp#8450] opened 2023-10-27 12:27 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Indonesia

### Provide a description that is worded well enough to be understood

Is there anything wrong with my command or yt-dlp doesn't support download specific time range from livestream that doesn't have runtime/duration? I tried with `--live-from start`, it works but no way I'm downloading the livestream 120 hours

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--live-from-start', '--download-sections', '#-6hours - -5hours', '-o', '2023.10.27.test.%(ext)s', 'https://www.youtube.com/watch?v=aJkIZDfn53Q']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109138-g3bcec58535-20221119 (setts), ffprobe N-109138-g3bcec58535-20221119
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
[youtube] Extracting URL: https://www.youtube.com/watch?v=aJkIZDfn53Q
[youtube] aJkIZDfn53Q: Downloading webpage
[youtube] aJkIZDfn53Q: Downloading ios player API JSON
[youtube] aJkIZDfn53Q: Downloading android player API JSON
[youtube] aJkIZDfn53Q: Downloading MPD manifest
[youtube] aJkIZDfn53Q: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] aJkIZDfn53Q: Cannot match chapters since chapter information is unavailable
```

**Comment by bashonly** [comment] 2023-10-28 06:55
Duplicate of #3451

see https://github.com/yt-dlp/yt-dlp/issues/8092#issuecomment-1715526126

**Closed by bashonly** 2023-10-28 06:55 UTC
Labels: site-bug, triage

**Comment by rrfqi** [comment] 2023-10-28 08:22
> Duplicate of #3451
> 
> see [#8092 (comment)](https://github.com/yt-dlp/yt-dlp/issues/8092#issuecomment-1715526126)

okay now it's downloading but when it's trying to download the last fragment it's stuck forever, is there any solution for this?

**Comment by bashonly** [comment] 2023-10-28 08:27
what do you mean by "stuck forever"? can you share verbose log output?

**Comment by rrfqi** [comment] 2023-10-28 08:51
nevermind, turns out it takes about 20 minutes to download the last fragment and merge video and audio.

but I just faced new problem, when I try to download again for another time range, I got this error

```
[debug] Command-line config: ['-vU', '--external-downloader', 'ffmpeg', '--live-from-start', '--download-sections', '#-593minutes - -590minutes', '-o', '2023.10.28.test.%(ext)s', 'https://www.youtube.com/watch?v=aJkIZDfn53Q']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109138-g3bcec58535-20221119 (setts)
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
[youtube] Extracting URL: https://www.youtube.com/watch?v=aJkIZDfn53Q
[youtube] aJkIZDfn53Q: Downloading webpage
[youtube] aJkIZDfn53Q: Downloading ios player API JSON
[youtube] aJkIZDfn53Q: Downloading android player API JSON
[youtube] aJkIZDfn53Q: Downloading MPD manifest
[youtube] aJkIZDfn53Q: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] aJkIZDfn53Q: Cannot match chapters since chapter information is unavailable
```

**Comment by rrfqi** [comment] 2023-10-28 09:00
oh my bad, it's switched to stable release, idk why it switched automatically xD

**Comment by bashonly** [comment] 2023-10-28 09:01
you probably ran yt-dlp with `-U` and it updated itself to current stable

Note that this is a custom pre-release build that I have made available for convenience. I cannot offer support for it as if it is yt-dlp proper. The pull request has not been merged into yt-dlp yet. Once it has been, then it would be fine to open an issue about it

**Comment by rrfqi** [comment] 2023-10-28 14:52
> you probably ran yt-dlp with `-U` and it updated itself to current stable
> 
> Note that this is a custom pre-release build that I have made available for convenience. I cannot offer support for it as if it is yt-dlp proper. The pull request has not been merged into yt-dlp yet. Once it has been, then it would be fine to open an issue about it

do you know solution for this problem?
https://streamable.com/5tll5j

**Comment by bashonly** [comment] 2023-11-07 20:37
@rrfqi I do not, sorry. After that PR is merged, if the problem is still happening, then I could look further into it

**Comment by rrfqi** [comment] 2024-03-23 14:39
why pre-release 2023.10.03.050313 removed?

**Comment by bashonly** [comment] 2024-03-23 14:42
@rrfqi here: https://github.com/bashonly/yt-dlp/releases/tag/live-from-sections
```
yt-dlp --update-to bashonly/yt-dlp@live-from-sections
```
