### ISSUE TITLE
[Viu] can't download/see the list formats, ERROR: Unsupported URL

### ISSUE THREAD

**Issue by rrfqi** [yt-dlp/yt-dlp#7668] opened 2023-07-22 16:45 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

any idea how to fix this?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-N', '16', '--remux-video', 'mkv', '--embed-subs', '--sub-langs', 'id', '--convert-subs', 'srt', '--no-part', '--list-formats', '--replace-in-metadata', 'title,uploader', '[ _]', '.', '-o', 'F:\\yt-dlp-master\\downloads\\%(title)s.%(ext)s', 'https://www.viu.com/ott/id/id/vod/2180935/Home-School']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.13 (CPython AMD64 64bit) - Windows-10-10.0.14393-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg N-102186-g8b83a4a885 (setts)
[debug] Optional libraries: certifi-2023.05.07, pycrypto-3.18.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1857 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://www.viu.com/ott/id/id/vod/2180935/Home-School
[generic] Home-School: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Home-School: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.viu.com/ott/id/id/vod/2180935/Home-School
Traceback (most recent call last):
  File "F:\yt-dlp-master\yt_dlp\YoutubeDL.py", line 1577, in wrapper
    return func(self, *args, **kwargs)
  File "F:\yt-dlp-master\yt_dlp\YoutubeDL.py", line 1712, in __extract_info
    ie_result = ie.extract(url)
  File "F:\yt-dlp-master\yt_dlp\extractor\common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "F:\yt-dlp-master\yt_dlp\extractor\generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.viu.com/ott/id/id/vod/2180935/Home-School
```

**Comment by bashonly** [comment] 2023-07-22 17:06
Duplicate of #6482

There's [a workaround you can try](https://github.com/yt-dlp/yt-dlp/issues/7562#issuecomment-1628924971), but it doesn't work for all URLs. The extractor needs to be fixed

**Closed by bashonly** 2023-07-22 17:06 UTC
Labels: question

**Comment by rrfqi** [comment] 2023-07-22 17:10
> Duplicate of #6482
> 
> There's [a workaround you can try](https://github.com/yt-dlp/yt-dlp/issues/7562#issuecomment-1628924971), but it doesn't work for all URLs. The extractor needs to be fixed

replacing https://www.viu.com/ott/id/id-en/vod/2180935/Home-School with https://www.viu.com/ott/id/en-id/vod/2180935/Home-School still not working, any idea how to fix the extractor?

**Comment by bashonly** [comment] 2023-07-22 17:17
No. Someone needs to fix/rewrite the code

**Comment by rrfqi** [comment] 2023-07-22 18:33
> No. Someone needs to fix/rewrite the code

I see, alright
