### ISSUE TITLE
[Broken] VH1.com 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by Sipherdrakon** [yt-dlp/yt-dlp#745] opened 2021-08-20 19:38 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-o', '%(playlist)s/%(playlist_index)s_-_%(title)s_[WEBDL-%(height)s].%(ext)s', '-f', 'best', '-ic', '--restrict-filenames', '--newline', '--cookies', 'cookies.txt', '--console-title', '--all-subs', '--embed-subs', '-a', 'ytdlready.txt', '--verbose']
[debug] Batch file urls: ['https://www.vh1.com/episodes/ju2nao/love-hip-hop-atlanta-see-you-at-the-crossroads-season-10-ep-7']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [vh1.com] Extracting URL: https://www.vh1.com/episodes/ju2nao/love-hip-hop-atlanta-see-you-at-the-crossroads-season-10-ep-7
[vh1.com] ju2nao: Downloading webpage
ERROR: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1199, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1224, in __extract_info
  File "yt_dlp\extractor\common.py", line 575, in extract
  File "yt_dlp\extractor\vh1.py", line 42, in _real_extract
  File "yt_dlp\extractor\mtv.py", line 233, in _get_videos_info
  File "yt_dlp\extractor\mtv.py", line 40, in _id_from_uri
AttributeError: 'NoneType' object has no attribute 'split'

```

## Description

Seems like paramount has changed a few sites, this is not the exact same problem as paramountnetwork.com but it seems it also can not extract the mgid and therefore has been broken.

**Comment by pukkandan** [comment] 2021-08-20 19:44
Marking as duplicate of #713 since the underlying issue is same

**Closed by pukkandan** 2021-08-20 19:44 UTC
