### ISSUE TITLE
--embed-subs and --write-auto-sub not working correctly together.

### ISSUE THREAD

**Issue by UttermostUsername** [yt-dlp/yt-dlp#1037] opened 2021-09-20 05:15 UTC
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Command-line config: ['-v', '--embed-subs', '--sub-langs', 'en-US,en-GB,en*', '--write-auto-sub', '--merge-output-format', 'mkv', '-f', 'bestvideo[height<=280]+bestaudio/best[height<=280]', 'https://www.youtube.com/watch?v=Uf1c0tEGfrU']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-05-12-git-175f675f7b-full_build-www.gyan.dev, ffprobe 2021-05-12-git-175f675f7b-full_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=Uf1c0tEGfrU
[youtube] Uf1c0tEGfrU: Downloading webpage
[youtube] Uf1c0tEGfrU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Downloading subtitles: en
[info] Uf1c0tEGfrU: Downloading 1 format(s): 242+251
[info] Writing video subtitles to: Hair - Last Week Tonight with John Oliver (HBO) [Uf1c0tEGfrU].en.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=Uf1c0tEGfrU&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xftt%2Cxctw&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1632139296&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxoaf&signature=B9303B55B5E79BBAAEB2B07E10AD793CEC32639E.1F98FBD37107F12D40DE1594FB6940C3697D1969&key=yt8&kind=asr&lang=en&fmt=vtt&tlang=en"
[download] Destination: Hair - Last Week Tonight with John Oliver (HBO) [Uf1c0tEGfrU].en.vtt

[download] 1.00KiB at 980.89KiB/s (00:00)
[download] 3.00KiB at  2.87MiB/s (00:00) 
[download] 7.00KiB at 685.57KiB/s (00:00)
[download] 15.00KiB at 729.88KiB/s (00:00)
[download] 31.00KiB at 424.15KiB/s (00:00)
[download] 63.00KiB at 519.80KiB/s (00:00)
[download] 127.00KiB at 728.13KiB/s (00:00)
[download] 233.52KiB at  1.01MiB/s (00:00) 
[download] 100% of 233.52KiB in 00:00      
[debug] Invoking downloader on "https://r3---sn-n4v7sne7.googlevideo.com/videoplayback?expire=1632135696&ei=sBVIYZiVM8vlkgbymI2oDw&ip=209.58.142.158&id=o-AMwD2zaEtz5ZEzQ1TA7Is_mEWzRLgMrxHY--wSaNJgby&itag=242&source=youtube&requiressl=yes&mh=K4&mm=31%2C26&mn=sn-n4v7sne7%2Csn-a5meknek&ms=au%2Conr&mv=m&mvi=3&pl=24&initcwndbps=1018750&vprv=1&mime=video%2Fwebm&gir=yes&clen=18894147&dur=1463.195&lmt=1621090843199506&mt=1632113808&fvip=3&keepalive=yes&fexp=24001373%2C24007246&beids=9466587&c=ANDROID&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgUHAPHBgRUH_rIXWwQuJ0Fq4oHYR2No7gcO8B6Wu1dK8CIFSqEXx6q3iF3Xu82VYqEwUzaavab_3i1_n9mR_4pgLq&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgBUOLsQBaASzHwjmgR7awesaNk_Xxs-tZSrgXnJNYtxcCIQCKu_pIS1-IHIdAjOxPr2f5gSIEmXJG7X-rhWKX5H2w8g%3D%3D"
[download] Destination: Hair - Last Week Tonight with John Oliver (HBO) [Uf1c0tEGfrU].f242.webm

[download]   0.0% of 18.02MiB at 62.00KiB/s ETA 04:57
[download]   0.0% of 18.02MiB at 149.14KiB/s ETA 02:03
[download]   0.0% of 18.02MiB at 302.83KiB/s ETA 01:00
[download]   0.1% of 18.02MiB at 574.38KiB/s ETA 00:32
[download]   0.2% of 18.02MiB at 414.83KiB/s ETA 00:44
[download]   0.3% of 18.02MiB at 513.38KiB/s ETA 00:35
[download]   0.7% of 18.02MiB at 722.35KiB/s ETA 00:25
[download]   1.4% of 18.02MiB at  1.08MiB/s ETA 00:16 
[download]   2.8% of 18.02MiB at  1.70MiB/s ETA 00:10 
[download]   5.5% of 18.02MiB at  2.38MiB/s ETA 00:07 
[download]  11.1% of 18.02MiB at  2.88MiB/s ETA 00:05 
[download]  22.2% of 18.02MiB at  3.26MiB/s ETA 00:04 
[download]  43.0% of 18.02MiB at  3.47MiB/s ETA 00:02 
[download]  54.5% of 18.02MiB at  3.57MiB/s ETA 00:02 
[download]  54.5% of 18.02MiB at 56.51KiB/s ETA 02:28 
[download]  54.6% of 18.02MiB at 138.24KiB/s ETA 01:00
[download]  54.6% of 18.02MiB at 283.39KiB/s ETA 00:29
[download]  54.6% of 18.02MiB at 541.49KiB/s ETA 00:15
[download]  54.7% of 18.02MiB at 423.81KiB/s ETA 00:19
[download]  54.9% of 18.02MiB at 507.49KiB/s ETA 00:16
[download]  55.2% of 18.02MiB at 703.73KiB/s ETA 00:11
[download]  55.9% of 18.02MiB at  1.03MiB/s ETA 00:07 
[download]  57.3% of 18.02MiB at  1.64MiB/s ETA 00:04 
[download]  60.1% of 18.02MiB at  2.32MiB/s ETA 00:03 
[download]  65.6% of 18.02MiB at  2.90MiB/s ETA 00:02 
[download]  76.7% of 18.02MiB at  1.45MiB/s ETA 00:02 
[download]  82.3% of 18.02MiB at  1.66MiB/s ETA 00:01 
[download]  93.4% of 18.02MiB at  1.82MiB/s ETA 00:00 
[download] 100.0% of 18.02MiB at  1.86MiB/s ETA 00:00 
[download] 100% of 18.02MiB in 00:09                  
[debug] Invoking downloader on "https://r3---sn-n4v7sne7.googlevideo.com/videoplayback?expire=1632135696&ei=sBVIYZiVM8vlkgbymI2oDw&ip=209.58.142.158&id=o-AMwD2zaEtz5ZEzQ1TA7Is_mEWzRLgMrxHY--wSaNJgby&itag=251&source=youtube&requiressl=yes&mh=K4&mm=31%2C26&mn=sn-n4v7sne7%2Csn-a5meknek&ms=au%2Conr&mv=m&mvi=3&pl=24&initcwndbps=1018750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=20456295&dur=1463.221&lmt=1621084585069254&mt=1632113808&fvip=3&keepalive=yes&fexp=24001373%2C24007246&beids=9466587&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgc8tVIIojQfa-rb948zgaJFANHQWianR70j9ODUlT38YCIDV-y3_x20KacHv0ct7ploOpemLoSfKger1RTfypflVg&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgBUOLsQBaASzHwjmgR7awesaNk_Xxs-tZSrgXnJNYtxcCIQCKu_pIS1-IHIdAjOxPr2f5gSIEmXJG7X-rhWKX5H2w8g%3D%3D"
[download] Destination: Hair - Last Week Tonight with John Oliver (HBO) [Uf1c0tEGfrU].f251.webm

[download]   0.0% of 19.51MiB at 63.54KiB/s ETA 05:14
[download]   0.0% of 19.51MiB at 137.89KiB/s ETA 02:24
[download]   0.0% of 19.51MiB at 282.85KiB/s ETA 01:10
[download]   0.1% of 19.51MiB at 521.74KiB/s ETA 00:38
[download]   0.2% of 19.51MiB at 387.66KiB/s ETA 00:51
[download]   0.3% of 19.51MiB at 497.42KiB/s ETA 00:40
[download]   0.6% of 19.51MiB at 696.91KiB/s ETA 00:28
[download]   1.3% of 19.51MiB at  1.05MiB/s ETA 00:18 
[download]   2.6% of 19.51MiB at  1.66MiB/s ETA 00:11 
[download]   5.1% of 19.51MiB at  2.34MiB/s ETA 00:07 
[download]  10.2% of 19.51MiB at  2.76MiB/s ETA 00:06 
[download]  20.5% of 19.51MiB at  3.20MiB/s ETA 00:04 
[download]  39.9% of 19.51MiB at  2.50MiB/s ETA 00:04 
[download]  50.0% of 19.51MiB at  2.22MiB/s ETA 00:04 
[download]  50.0% of 19.51MiB at 44.94KiB/s ETA 03:42 
[download]  50.0% of 19.51MiB at 114.35KiB/s ETA 01:27
[download]  50.0% of 19.51MiB at 239.43KiB/s ETA 00:41
[download]  50.0% of 19.51MiB at 465.32KiB/s ETA 00:21
[download]  50.1% of 19.51MiB at 400.59KiB/s ETA 00:24
[download]  50.3% of 19.51MiB at 510.14KiB/s ETA 00:19
[download]  50.6% of 19.51MiB at 711.62KiB/s ETA 00:13
[download]  51.2% of 19.51MiB at  1.06MiB/s ETA 00:08 
[download]  52.5% of 19.51MiB at  1.67MiB/s ETA 00:05 
[download]  55.1% of 19.51MiB at  2.35MiB/s ETA 00:03 
[download]  60.2% of 19.51MiB at  2.87MiB/s ETA 00:02 
[download]  70.5% of 19.51MiB at  3.19MiB/s ETA 00:01 
[download]  88.9% of 19.51MiB at  3.48MiB/s ETA 00:00 
[download]  99.7% of 19.51MiB at  3.47MiB/s ETA 00:00 
[download]  99.7% of 19.51MiB at 89.35KiB/s ETA 00:00 
[download]  99.7% of 19.51MiB at 197.66KiB/s ETA 00:00
[download]  99.7% of 19.51MiB at 385.08KiB/s ETA 00:00
[download]  99.8% of 19.51MiB at 676.38KiB/s ETA 00:00
[download]  99.8% of 19.51MiB at 424.29KiB/s ETA 00:00
[download] 100.0% of 19.51MiB at 482.13KiB/s ETA 00:00
[download] 100.0% of 19.51MiB at 474.74KiB/s ETA 00:00
[download] 100% of 19.51MiB in 00:08                  
[Merger] Merging formats into "Hair - Last Week Tonight with John Oliver (HBO) [Uf1c0tEGfrU].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Hair - Last Week Tonight with John Oliver (HBO) [Uf1c0tEGfrU].f242.webm" -i "file:Hair - Last Week Tonight with John Oliver (HBO) [Uf1c0tEGfrU].f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:Hair - Last Week Tonight with John Oliver (HBO) [Uf1c0tEGfrU].temp.mkv"
Deleting original file Hair - Last Week Tonight with John Oliver (HBO) [Uf1c0tEGfrU].f251.webm (pass -k to keep)
Deleting original file Hair - Last Week Tonight with John Oliver (HBO) [Uf1c0tEGfrU].f242.webm (pass -k to keep)
[EmbedSubtitle] Embedding subtitles in "Hair - Last Week Tonight with John Oliver (HBO) [Uf1c0tEGfrU].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Hair - Last Week Tonight with John Oliver (HBO) [Uf1c0tEGfrU].mkv" -i "file:Hair - Last Week Tonight with John Oliver (HBO) [Uf1c0tEGfrU].en.vtt" -c copy -map 0 -dn -map "-0:s" -map "-0:d" -map "1:0" "-metadata:s:s:0" "language=eng" "-metadata:s:s:0" "handler_name=English" "-metadata:s:s:0" "title=English" "file:Hair - Last Week Tonight with John Oliver (HBO) [Uf1c0tEGfrU].temp.mkv"
Deleting original file Hair - Last Week Tonight with John Oliver (HBO) [Uf1c0tEGfrU].en.vtt (pass -k to keep)


```

## Description

This pertains to Youtube.

When passing --embed-subs and --write-auto-sub only the auto-subs are downloaded. I have two videos to show this behavior.
 
The first is "https://www.youtube.com/watch?v=Uf1c0tEGfrU". On this video there is a manually created "en-US" language subtitle and an auto-generated "en" language subtitle.

The second is "https://www.youtube.com/watch?v=2ONqZ8Mxweo". On this video there is a manually created "en" language subtitle and an auto-generated "en" language subtitle.

In both cases when passing --embed-subs and --write-auto-sub ONLY the auto subtitle is embedded. What should happen, for the first video, is for BOTH subtitles are downloaded and embedded in the order the "--sub-langs" lists.
In the second video either BOTH should be downloaded with the auto-subtitle being embedded last (or in the order --embed-subs and --write-auto-sub is passed) or only the manual subtitle should be downloaded and embedded.

When using --write-sub in addition to --embed-subs both subtitles are downloaded and embedded properly however they aren't deleted from disk after being embedded. There seems no way to download both subtitles, embed in the proper order, and then delete them from the hard-disk.

**Comment by pukkandan** [comment] 2021-09-20 09:51
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/826. Also see https://github.com/yt-dlp/yt-dlp/issues/630

**Closed by pukkandan** 2021-09-20 09:51 UTC
