### ISSUE TITLE
Paramount Plus only downloads 50 episodes from a season

### ISSUE THREAD

**Issue by ralioc** [yt-dlp/yt-dlp#3311] opened 2022-04-05 10:53 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

I have been having issues with paraomountplus.com only downloading 50 episodes instead of the complete series.  If there's a total of 51 or more episodes, it will only download the first 50 it sees and then stops. For example, I'm downloading the show "Moesha".  The paramount website shows a total of 127 episodes for the complete series and yt-dlp shows "downloading video xx of 50".  Is there a fix for this?

I run a batch file.  I interrupted the download so I could provide the verbose log.

### Verbose log

```shell
C:\Users\xxxxx>yt-dlp --config-location A:\PMTP\config.txt -vU
[debug] Command-line config: ['--config-location', 'A:\\PMTP\\config.txt', '-vU']
[debug] | Config "A:\PMTP\config.txt": ['--batch-file', 'A:/PMTP/dl.txt', '--format', '(bv*+ba/b) [protocol^=http][protocol!*=dash] / (bv*+ba/b)', '--cookies-from-browser', 'firefox', '--ignore-errors', '--retries', '5000', '--geo-bypass', '--throttled-rate', '3M', '--fragment-retries', '5000', '--no-check-certificates', '--windows-filenames', '--progress', '--embed-subs', '--embed-chapters', '--embed-metadata', '--continue', '--no-overwrites', '--no-playlist', '--download-archive', 'A:/PMTP/archive.txt', '--remux-video', 'mkv', '-o', 'A:/PMTP/%(series)s/S%(season_number)s/%(series)s - %(episode_number)s - %(title)s.%(ext)s']
[debug] Batch file urls: ['https://www.paramountplus.com/shows/daria/', 'https://www.paramountplus.com/shows/big-nate/', 'https://www.paramountplus.com/shows/aaahh-real-monsters/', 'https://www.paramountplus.com/shows/abby-hatcher/', 'https://www.paramountplus.com/shows/moesha/', 'https://www.paramountplus.com/shows/i_love_lucy/', 'https://www.paramountplus.com/shows/acapulco-shore/', 'https://www.paramountplus.com/shows/action-league-now/', 'https://www.paramountplus.com/shows/the-adventures-of-jimmy-neutron-boy-genius/', 'https://www.paramountplus.com/shows/the-adventures-of-kid-danger/', 'https://www.paramountplus.com/shows/the-adventures-of-paddington/', 'https://www.paramountplus.com/shows/adventures-of-paddington-bear/', 'https://www.paramountplus.com/shows/adventures-of-sonic/', 'https://www.paramountplus.com/shows/the-adventures-of-super-mario-bros-3/', 'https://www.paramountplus.com/shows/aeon-flux/', 'https://www.paramountplus.com/shows/all-grown-up/', 'https://www.paramountplus.com/shows/all-in-with-cam-newton/', 'https://www.paramountplus.com/shows/all-that/', 'https://www.paramountplus.com/shows/all-that-2019/', 'https://www.paramountplus.com/shows/allegras-window/', 'https://www.paramountplus.com/shows/alvinnn-and-the-chipmunks/', 'https://www.paramountplus.com/shows/the-amanda-show/', 'https://www.paramountplus.com/shows/the-angry-beavers/', 'https://www.paramountplus.com/shows/archies-weird-mysteries/', 'https://www.paramountplus.com/shows/are-you-afraid-of-the-dark/', 'https://www.paramountplus.com/shows/are-you-afraid-of-the-dark-2019/', 'https://www.paramountplus.com/shows/are-you-smarter-than-a-5th-grader/', 'https://www.paramountplus.com/shows/are-you-the-one/', 'https://www.paramountplus.com/shows/as-told-by-ginger/', 'https://www.paramountplus.com/shows/avatar-the-last-airbender/', 'https://www.paramountplus.com/shows/awesomenesstv/', 'https://www.paramountplus.com/shows/awesomeness-tvs-next-influencer/', 'https://www.paramountplus.com/shows/awkward/', 'https://www.paramountplus.com/shows/b-positive/', 'https://www.paramountplus.com/shows/baby-sharks-big-show-shorts/', 'https://www.paramountplus.com/shows/badass-bitches-of-history/', 'https://www.paramountplus.com/shows/baldwin-hills/', 'https://www.paramountplus.com/shows/behind-the-music/', 'https://www.paramountplus.com/shows/before-i-forget/', 'https://www.paramountplus.com/shows/beavis-and-butt-head/', 'https://www.paramountplus.com/shows/beauty-and-the-beast/', 'https://www.paramountplus.com/shows/being-mary-jane/', 'https://www.paramountplus.com/shows/big-brother-australia/', 'https://www.paramountplus.com/shows/beverly-hills-90210/', 'https://www.paramountplus.com/shows/big_brother/', 'https://www.paramountplus.com/shows/bible-hunters/', 'https://www.paramountplus.com/shows/beyond-the-edge/', 'https://www.paramountplus.com/shows/blue_bloods/', 'https://www.paramountplus.com/shows/the_brady_bunch/', 'https://www.paramountplus.com/shows/bob-hearts-abishola/', 'https://www.paramountplus.com/shows/breadwinners/', 'https://www.paramountplus.com/shows/bull/', 'https://www.paramountplus.com/shows/bunsen-is-a-beast/', 'https://www.paramountplus.com/shows/the-burn-with-jeff-ross/', 'https://www.paramountplus.com/shows/caroline-in-the-city/', 'https://www.paramountplus.com/shows/csi-vegas/', 'https://www.paramountplus.com/shows/cmt-music-awards/', 'https://www.paramountplus.com/shows/the-casagrandes/', 'https://www.paramountplus.com/shows/catdog/', 'https://www.paramountplus.com/shows/celebrity-deathmatch/', 'https://www.paramountplus.com/shows/cheers/', 'https://www.paramountplus.com/shows/chappelles-show/', 'https://www.paramountplus.com/shows/clarissa-explains-it-all/', 'https://www.paramountplus.com/shows/clive-davis-most-iconic-performances/', 'https://www.paramountplus.com/shows/clone-high/', 'https://www.paramountplus.com/shows/cloudy-with-a-chance-of-meatballs/', 'https://www.paramountplus.com/shows/come-dance-with-me/', 'https://www.paramountplus.com/shows/comedy-central-stand-up-presents/', 'https://www.paramountplus.com/shows/comedy-central-presents/', 'https://www.paramountplus.com/shows/combate-global/', 'https://www.paramountplus.com/shows/college-hill/', 'https://www.paramountplus.com/shows/the-city/', 'https://www.paramountplus.com/shows/the-comedy-jam/', 'https://www.paramountplus.com/shows/criminal_minds/', 'https://www.paramountplus.com/shows/crazy-monster/', 'https://www.paramountplus.com/shows/crank-yankers/']
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\xxxxx\AppData\Roaming\Mozilla\Firefox\Profiles\8sw2hwxt.default-release\cookies.sqlite"
[Cookies] Extracted 1426 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.2.3, ffprobe 2022-03-07-git-e645a1ddb9-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file 'A:/PMTP/archive.txt'
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [ParamountPlusSeries] Extracting URL: https://www.paramountplus.com/shows/moesha/
[download] Downloading playlist: moesha
[ParamountPlusSeries] moesha: Downloading JSON metadata
[ParamountPlusSeries] playlist moesha: Downloading 50 videos
[download] Downloading video 1 of 50
[download] iwbxuTAjzNl1HYjKKGg6aGUsPSqBKPpN has already been recorded in the archive
[download] Downloading video 2 of 50
[download] e7aBgNNEVxk5FQfwbJ9G2j6a3Kv85s0q has already been recorded in the archive
[download] Downloading video 3 of 50
[download] Rhym7H333v7FGY2d8KE9k7POPn_XFH5r has already been recorded in the archive
[download] Downloading video 4 of 50
[download] Po7MCHWDJMsB7ByifdAnwYg0vgLqwmdw has already been recorded in the archive
[download] Downloading video 5 of 50
[download] Ff9qC4r9YoGKSHI3CzrGg6784RgViNAe has already been recorded in the archive
[download] Downloading video 6 of 50
[download] 9Fe7lNwR0zLUC_k57AYTHZMVQw9kRKko has already been recorded in the archive
[download] Downloading video 7 of 50
[download] j_Cuk64mnD9e1sJI8LHOLX_ofHAjc5_e has already been recorded in the archive
[download] Downloading video 8 of 50
[download] iWUEydUPf6j4i2Wg0XjdVvK1d3ysxdaO has already been recorded in the archive
[download] Downloading video 9 of 50
[download] HhOCzxGu3Cp7P9McauM2wUN3k_F2mWtU has already been recorded in the archive
[download] Downloading video 10 of 50
[download] 3rAz1XjI62j5_Tr5LjNja2mQ2IgMS_iG has already been recorded in the archive
[download] Downloading video 11 of 50
[download] 1EvGcvA6t6hkoUbsS2hzGAw_vxeAFPqx has already been recorded in the archive
[download] Downloading video 12 of 50
[download] 0MMZQXKXxOpr2J_c9rQpmY8TxbDuBLDq has already been recorded in the archive
[download] Downloading video 13 of 50
[download] uIhqVFd_YQaV5gwbv1icvUADST4Xc_a7 has already been recorded in the archive
[download] Downloading video 14 of 50
[download] sxnL2OXDcflUCbvkuTxxLbmcz3CbvGUS has already been recorded in the archive
[download] Downloading video 15 of 50
[download] q7xSzDo9YSIMoY6Klq3GEcNxBqBCUsLr has already been recorded in the archive
[download] Downloading video 16 of 50
[download] a1DFIqpTVuWrKTRP_dWxfm6dpmnWD8s1 has already been recorded in the archive
[download] Downloading video 17 of 50
[download] VgsZVXucpjkyyL_P9JVo____MG27XkTe has already been recorded in the archive
[download] Downloading video 18 of 50
[download] 1yzw3vGOf_DBDm9GW7wjCxrgEp8YM_V_ has already been recorded in the archive
[download] Downloading video 19 of 50
[download] xE8IA9IvCKepuukHWKwp8zUUsyyLMBqs has already been recorded in the archive
[download] Downloading video 20 of 50
[download] foRYFNzHrM9jjY1Rjf1TEsZ3CWJqaelU has already been recorded in the archive
[download] Downloading video 21 of 50
[download] _yX_E6LYsdSAsP6Sqgh23gsxB_LZxqwy has already been recorded in the archive
[download] Downloading video 22 of 50
[download] SgxCMZ_dJ1KtL0XVuBk0KCySXsH1LIKe has already been recorded in the archive
[download] Downloading video 23 of 50
[download] BzkqT5rSYGZFZLecJjmDeOjMFg_kgDDb has already been recorded in the archive
[download] Downloading video 24 of 50
[download] 3afH5EvGl1iL1frNpahF698TFHYZuyb3 has already been recorded in the archive
[download] Downloading video 25 of 50
[download] x3WdUcxQkOKmG1_5XfFWUlv_q448uI7f has already been recorded in the archive
[download] Downloading video 26 of 50
[download] wuq_liSal_EyOJ6nHSwYVbL9kGuXO_I5 has already been recorded in the archive
[download] Downloading video 27 of 50
[download] sF0aI4CtJNql9GNQi8N2WI_cG7Sa5_7k has already been recorded in the archive
[download] Downloading video 28 of 50
[download] pmVeBlPlWMC8G0H_MZBs0_1iauaXy5UI has already been recorded in the archive
[download] Downloading video 29 of 50
[debug] [ParamountPlus] Extracting URL: https://www.paramountplus.com/shows/moesha/video/pFsp4lNus_CQ5_G9rEZZTVFIfzzI4MmP/moesha-not-my-pumpkin/
[ParamountPlus] pFsp4lNus_CQ5_G9rEZZTVFIfzzI4MmP: Downloading JSON metadata
[ParamountPlus] pFsp4lNus_CQ5_G9rEZZTVFIfzzI4MmP: Downloading JSON metadata
[ParamountPlus] pFsp4lNus_CQ5_G9rEZZTVFIfzzI4MmP: Downloading DASH_CENC_PRECON SMIL data
[ParamountPlus] pFsp4lNus_CQ5_G9rEZZTVFIfzzI4MmP: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en
[info] pFsp4lNus_CQ5_G9rEZZTVFIfzzI4MmP: Downloading 1 format(s): hls-3121
[info] Video subtitle en.vtt is already present
[debug] Invoking downloader on "https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2020/10/03/1799543363723/MOESHA_0088_SD_2398_2CH_306373_,2228,4628,3128,1628,848,503,000.mp4.csmil/index_2_av.m3u8?null=0&id=AgA%2fm1%2fTFyNiLhweTGI82cA8CzwH2YU5PA0%2fmrbB2BLhlnD0SvpCbTqgFBhC0iJEv1H4c5Kjgn31Tg%3d%3d&hdntl=exp=1649242012~acl=%2fi%2ftemp_hd_gallery_video%2fCBS_Production_Outlet_VMS%2fvideo_robot%2fCBS_Production_Entertainment%2f2020%2f10%2f03%2f1799543363723%2fMOESHA_0088_SD_2398_2CH_306373_*~data=hdntl~hmac=5ee217ebdce084f51fe792ff8aa280a38b51abe71673b00daec68e6fb7111afb"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 128
[download] Destination: A:\PMTP\Moesha\S5\Moesha - 5 - Moesha - Not My Pumpkin.mp4
[download]   8.2% of ~490.68MiB at  1.72MiB/s ETA 03:27 (frag 10/128)
ERROR: Interrupted by user
```

**Comment by nyuszika7h** [comment] 2022-04-05 11:29
Duplicate of #3155.

**Closed** 2022-04-05 11:34 UTC
Labels: duplicate, site-bug
