### ISSUE TITLE
Tiktok profile download not getting video lists, individual files work

### ISSUE THREAD

**Issue by katse007** [yt-dlp/yt-dlp#2534] opened 2022-01-29 10:11 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Tiktok profile download not getting video lists, individual files work though. 

### Verbose log

```shell
ytdlp --verbose https://www.tiktok.com/@josekuthy
[debug] Command-line config: ['--verbose', 'https://www.tiktok.com/@josekuthy']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-12-17-git-b780b6db64-full_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [tiktok:user] Extracting URL: https://www.tiktok.com/@josekuthy
[tiktok:user] josekuthy: Downloading webpage
[tiktok:user] josekuthy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying...
[tiktok:user] josekuthy: Downloading user video list page 1 (attempt 1)
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying...
[tiktok:user] josekuthy: Downloading user video list page 1 (attempt 2)
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying...
[tiktok:user] josekuthy: Downloading user video list page 1 (attempt 3)
ERROR: [tiktok:user] josekuthy: josekuthy: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\tiktok.py", line 561, in _real_extract
  File "yt_dlp\utils.py", line 5135, in traverse_obj
  File "yt_dlp\utils.py", line 5121, in _traverse_obj
  File "yt_dlp\utils.py", line 2736, in __getitem__
  File "yt_dlp\extractor\tiktok.py", line 530, in _video_entries_api
  File "yt_dlp\extractor\tiktok.py", line 80, in _call_api
  File "yt_dlp\extractor\common.py", line 992, in _download_json
  File "yt_dlp\extractor\common.py", line 978, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 1007, in _parse_json
```

**Comment by pukkandan** [comment] 2022-01-29 21:18
Duplicate of #2534

**Closed by pukkandan** 2022-01-29 21:18 UTC
Labels: duplicate, site-bug, site:tiktok
