### ISSUE TITLE
Error using --live-from-start --download-sections

### ISSUE THREAD

**Issue by sxx520** [yt-dlp/yt-dlp#8092] opened 2023-09-12 11:10 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Use the following command line
 
yt-dlp https://www.youtube.com/watch?v=0FtAWSlHMu0 --proxy http://127.0.0.1:7890/ --live-from-start --download-sections  "*-5mins - 0"  --force-keyframes  --concurrent-fragments 8 -vU

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=0FtAWSlHMu0', '--proxy', 'http://127.0.0.1:7890/', '--live-from-start', '--download-sections', '*-5mins - 0', '--force-keyframes', '--concurrent-fragments', '8', '-vU']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.5 (CPython AMD64 64bit) - Windows-10-10.0.18363-SP0 (OpenSSL 3.0.9 30 May 2023)
[debug] exe versions: ffmpeg 2023-09-04-git-f8503b4c33-full_build-www.gyan.dev (setts), ffprobe 2023-09-04-git-f8503b4c33-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.47.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'http': 'http://127.0.0.1:7890/', 'https': 'http://127.0.0.1:7890/'}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=0FtAWSlHMu0
[youtube] 0FtAWSlHMu0: Downloading webpage
[youtube] 0FtAWSlHMu0: Downloading ios player API JSON
[youtube] 0FtAWSlHMu0: Downloading android player API JSON
[youtube] 0FtAWSlHMu0: Downloading MPD manifest
[youtube] 0FtAWSlHMu0: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 0FtAWSlHMu0: Downloading 1 format(s): 248+140
[info] 0FtAWSlHMu0: Downloading 1 time ranges: -300.0-0.0
ERROR: This format cannot be partially downloaded. Aborting
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Python\Scripts\yt-dlp.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Python\Lib\site-packages\yt_dlp\__init__.py", line 1008, in main
    _exit(*variadic(_real_main(argv)))
  File "D:\Python\Lib\site-packages\yt_dlp\__init__.py", line 998, in _real_main
    return ydl.download(all_urls)
  File "D:\Python\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3485, in download
    self.__download_wrapper(self.extract_info)(
  File "D:\Python\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3460, in wrapper
    res = func(*args, **kwargs)
  File "D:\Python\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1549, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "D:\Python\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Python\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1709, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "D:\Python\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1768, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "D:\Python\Lib\site-packages\yt_dlp\YoutubeDL.py", line 2897, in process_video_result
    self.process_info(new_info)
  File "D:\Python\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3264, in process_info
    self.report_error(f'{msg}. Aborting')
  File "D:\Python\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1042, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "D:\Python\Lib\site-packages\yt_dlp\YoutubeDL.py", line 970, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

**Comment by sxx520** [comment] 2023-09-12 11:11
error message: ERROR: This format cannot be partially downloaded. Aborting

**Comment by bashonly** [comment] 2023-09-12 11:13
`--live-from-start` with `--download-sections` is not currently supported

There is a PR to add support for this: #6498 ([here's a pre-release build](https://github.com/bashonly/yt-dlp/releases/tag/2023.07.22.185234))

Closing as duplicate of #3451

**Closed by bashonly** 2023-09-12 11:13 UTC
Labels: question

**Comment by sxx520** [comment] 2023-09-13 04:25
Didn't solve the problem

**Comment by sxx520** [comment] 2023-09-13 04:27
using  yt-dlp https://www.youtube.com/watch?v=QCBM5LtrY4k --proxy http://127.0.0.1:7890/ --live-from-start --download-sections  "*00:00:00-00:05:00"  --force-keyframes  --concurrent-fragments 4 -vU

output：



[debug] Command-line config: ['https://www.youtube.com/watch?v=QCBM5LtrY4k', '--proxy', 'http://127.0.0.1:7890/', '--live-from-start', '--download-sections', '*00:00:00-00:05:00', '--force-keyframes', '--concurrent-fragments', '4', '-vU']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.22.185234 [f780bb52b] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.18363-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-09-04-git-f8503b4c33-full_build-www.gyan.dev (setts), ffprobe 2023-09-04-git-f8503b4c33-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'all': 'http://127.0.0.1:7890/'}
[debug] Loaded 1857 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.22.185234
Current Build Hash: 9cb23e2fd45fc307c6ebe0d477539fdd760e06fe1703d2289acab103106ef2a7
yt-dlp is up to date (stable@2023.07.22.185234)
[youtube] Extracting URL: https://www.youtube.com/watch?v=QCBM5LtrY4k
[youtube] QCBM5LtrY4k: Downloading webpage
[youtube] QCBM5LtrY4k: Downloading ios player API JSON
[youtube] QCBM5LtrY4k: Downloading android player API JSON
[youtube] QCBM5LtrY4k: Downloading MPD manifest
[youtube] QCBM5LtrY4k: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] QCBM5LtrY4k: Downloading 1 format(s): 248+140
[info] QCBM5LtrY4k: Downloading 1 time ranges: 0.0-300.0
[debug] Invoking dashsegments downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1694600581/ei/JTkBZaaILfuavcAPjMODuAU/ip/61.221.110.205/id/QCBM5LtrY4k.1/source/yt_live_broadcast/requiressl/yes/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/spc/UWF9f2-safAtPtuHcgfJ9_mMBd5J1FQ/vprv/1/pacing/0/itag_bl/376%2C377%2C384%2C385%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24007246%2C24362685%2C24363393/beids/24350018/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Cas%2Cspc%2Cvprv%2Citag%2Cplaylist_type/sig/AOq0QJ8wRAIgKje3H9zOh_3h6IZxYCbvZuS46Ij_r304cp7R7nejOUACIDp8d4R9-c1lxYdFnIRGqPB2_6um_8ati6PSCk-TQUSN", "https://manifest.googlevideo.com/api/manifest/dash/expire/1694600581/ei/JTkBZaaILfuavcAPjMODuAU/ip/61.221.110.205/id/QCBM5LtrY4k.1/source/yt_live_broadcast/requiressl/yes/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/spc/UWF9f2-safAtPtuHcgfJ9_mMBd5J1FQ/vprv/1/pacing/0/itag_bl/376%2C377%2C384%2C385%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24007246%2C24362685%2C24363393/beids/24350018/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Cas%2Cspc%2Cvprv%2Citag%2Cplaylist_type/sig/AOq0QJ8wRAIgKje3H9zOh_3h6IZxYCbvZuS46Ij_r304cp7R7nejOUACIDp8d4R9-c1lxYdFnIRGqPB2_6um_8ati6PSCk-TQUSN"
[dashsegments] Total fragments: unknown (live)
[download] Destination: 【洪淑芬⧸張雅婷 報新聞】錢康明再爆高虹安! 南港建案基泰2.0？ 綠甩鍋台農巴西蛋？ 超思藏鏡人是他？ 開箱蘋果新機! 20230913 @CtiNews [QCBM5LtrY4k].f248.mkv
[debug] File locking is not supported. Proceeding without locking
[dashsegments] Total fragments: unknown (live)
[download] Destination: 【洪淑芬⧸張雅婷 報新聞】錢康明再爆高虹安! 南港建案基泰2.0？ 綠甩鍋台農巴西蛋？ 超思藏鏡人是他？ 開箱蘋果新機! 20230913 @CtiNews [QCBM5LtrY4k].f140.mkv
WARNING: The download speed shown is only of one thread. This is a known issue
[debug] [youtube] Selected section: 0 -> 300.0
[debug] [youtube] [QCBM5LtrY4k] Generating fragments for format 248
WARNING: The download speed shown is only of one thread. This is a known issue
[debug] [youtube] Selected section: 0 -> 300.0
[debug] [youtube] [QCBM5LtrY4k] Generating fragments for format 140
ERROR: The downloaded file is empty
  File "threading.py", line 890, in _bootstrap
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "concurrent\futures\thread.py", line 80, in _worker
  File "concurrent\futures\thread.py", line 57, in run
  File "yt_dlp\downloader\fragment.py", line 394, in thread_func
  File "yt_dlp\downloader\fragment.py", line 537, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 310, in _finish_frag_download
  File "yt_dlp\YoutubeDL.py", line 1060, in report_error
  File "yt_dlp\YoutubeDL.py", line 988, in trouble

ERROR: The downloaded file is empty
  File "threading.py", line 890, in _bootstrap
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "concurrent\futures\thread.py", line 80, in _worker
  File "concurrent\futures\thread.py", line 57, in run
  File "yt_dlp\downloader\fragment.py", line 394, in thread_func
  File "yt_dlp\downloader\fragment.py", line 537, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 310, in _finish_frag_download
  File "yt_dlp\YoutubeDL.py", line 1060, in report_error
  File "yt_dlp\YoutubeDL.py", line 988, in trouble

**Comment by sxx520** [comment] 2023-09-13 04:29
Want to achieve downloading from the beginning to the 5th minute of the live broadcast，Please tell me how to achieve it，Thanks。

**Comment by bashonly** [comment] 2023-09-13 04:31
In that PR, the syntax for `--download-sections` is different when used with `--live-from-start`

you can use relative times:
```shell
--download-sections "#-2hours - -1hour"  // Start downloading from 2 hours ago and stop until 1 hour ago
--download-sections "#-1hour - 0" // Start downloading from 1 hour ago and stop until now
--download-sections "#-1hour - 1hour" // Start downloading from 1 hour ago and stop until 1 hour from now
```

or you can use unix timestamps with `*`
```shell
--download-sections "*1694579393-1694579410"
--download-sections "*1694579393-inf"
```

> Want to achieve downloading from the beginning to the 5th minute of the live broadcast

you'll need to figure out when the livestream started and calculate an argument based on the start time

note that `--live-from-start` can only lookback 120 hours from the current time

**Comment by sxx520** [comment] 2023-09-13 04:47
We currently don’t know the exact launch time，Maybe there is any way to directly use the given time interval?
For example "00:00:00-00:05:00" from the beginning of the live broadcast to 5 minutes after the start，
For example "00:05:00-00:10:00" from 5 minutes to the 10th minute after the live broadcast starts。
If my inquiry has no value，
Please forgive me for asking. I'm sorry.

**Comment by bashonly** [comment] 2023-09-13 04:52
No, you need to use the syntax I just described

If it is a very long-running stream, you can use `--download-sections "#-7200minutes - -7195minutes"` to go back as far as possible and download 5 minutes

**Comment by sxx520** [comment] 2023-09-13 05:21
OK, I will try to follow the steps you described, thank you again！！！
