### ISSUE TITLE
WARNING: [youtube] Unable to mark watched: [Errno 11004] getaddrinfo failed

### ISSUE THREAD

**Issue by Obegg** [yt-dlp/yt-dlp#8173] opened 2023-09-21 18:02 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Trying to use `yt-dlp` option `--mark-watched` to mark watched videos on YouTube.
```
yt-dlp -vU --mark-watched --cookies-from-browser firefox <GitHub>
```

Note: `<GitHub>` is just a censored URL

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--mark-watched', '--cookies-from-browser', 'firefox', '<GitHub>']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\GitHub\AppData\Roaming\Mozilla\Firefox\Profiles\GitHub.default-release\cookies.sqlite"
Extracted 929 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.09.21.155918 [35f9a306e] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-112128-gfa20f5cd9 (setts)
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1875 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.09.21.155918, Current version: nightly@2023.09.21.155918
Current Build Hash: 1c09891078c64d16711fc956e5d2076e0051e7e08f3ea23c597c0fcb9ed5db2b
yt-dlp is up to date (nightly@2023.09.21.155918)
[youtube] Extracting URL: <GitHub>
[youtube] Ob7lueNz2oY: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] Ob7lueNz2oY: Downloading ios player API JSON
[youtube] Ob7lueNz2oY: Downloading android player API JSON
[youtube] Ob7lueNz2oY: Downloading m3u8 information
[youtube] Ob7lueNz2oY: Marking watched
WARNING: [youtube] Unable to mark watched: [Errno 11004] getaddrinfo failed
[youtube] Ob7lueNz2oY: Marking fully watched
WARNING: [youtube] Unable to mark watched: [Errno 11004] getaddrinfo failed
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Ob7lueNz2oY: Downloading 1 format(s): 313+251
[debug] Invoking http downloader on "<GitHub>"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: you will never have this [Ob7lueNz2oY].f313.webm
[download] 100% of   12.18MiB in 00:00:00 at 21.41MiB/s
[debug] Invoking http downloader on "<GitHub>"
[download] Destination: you will never have this [Ob7lueNz2oY].f251.webm
[download] 100% of  314.06KiB in 00:00:00 at 2.26MiB/s
[Merger] Merging formats into "you will never have this [Ob7lueNz2oY].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:you will never have this [Ob7lueNz2oY].f313.webm" -i "file:you will never have this [Ob7lueNz2oY].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:you will never have this [Ob7lueNz2oY].temp.webm"
Deleting original file you will never have this [Ob7lueNz2oY].f251.webm (pass -k to keep)
Deleting original file you will never have this [Ob7lueNz2oY].f313.webm (pass -k to keep)
```

**Comment by bashonly** [comment] 2023-09-21 18:14
by any chance do you use pi-hole

**Comment by bashonly** [comment] 2023-09-21 18:16
`--mark-watched` works by sending a request to a google tracking server. pi-hole is blocking it

This is a duplicate of #8149

**Closed by bashonly** 2023-09-21 18:16 UTC
Labels: site-bug, triage

**Comment by coletdjnz** [comment] 2023-09-21 18:50
> I did not see error 61, I saw error 11004.

Different OS has different error codes and may behave differently, as well as both pi-holes may be configured to behave differently. The underlying issue is the same though - DNS issue.
