### ISSUE TITLE
Some Playlists Cannot be Fully Downloaded

### ISSUE THREAD

**Issue by JohnRobson** [yt-dlp/yt-dlp#11568] opened 2024-11-17 17:19 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Most of the time yt-dlp woks well, but I figure out that in some playlists it download None or Only One playlist, examples:
$ \yt-dlp --yes-playlist https://www.youtube.com/@kathryndobrow205/playlists
$ \yt-dlp --yes-playlist https://www.youtube.com/@BriTheMathGuy/playlists

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ \yt-dlp -vU https://www.youtube.com/@kathryndobrow205/playlists
[debug] Command-line config: ['-vU', 'https://www.youtube.com/@kathryndobrow205/playlists']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b]
[debug] Python 3.12.7 (CPython x86_64 64bit) - Linux-6.6.58-1-lts-x86_64-with-glibc2.40 (OpenSSL 3.4.0 22 Oct 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotlicffi-1.1.0.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.46.1, urllib3-1.26.20, websockets-12.0, xattr-0.10.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.04 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/@kathryndobrow205/playlists
[youtube:tab] @kathryndobrow205/playlists: Downloading webpage
[debug] [youtube:tab] Selected tab: 'playlists' (playlists), Requested tab: 'playlists'
[download] Downloading playlist: Kathryn Dobrow - Playlists
[youtube:tab] Playlist Kathryn Dobrow - Playlists: Downloading 0 items
[download] Finished downloading playlist: Kathryn Dobrow - Playlists
```

**Comment by bashonly** [comment] 2024-11-17 17:20
Duplicate of #11524

**Closed by bashonly** 2024-11-17 17:20 UTC
Labels: bug, triage
