### ISSUE TITLE
[YT] Chapter titles no longer parsed

### ISSUE THREAD

**Issue by Kooldude93** [yt-dlp/yt-dlp#9204] opened 2024-02-14 04:47 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Chapter titles are no longer parsed and default to Bookmark 1, Bookmark 2, ect.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-o', 'C:/work-area/Downloads/%(title)s [%(id)s].%(ext)s', '-o', 'C:/work-area/Downloads/chapters:%(title)s.%(ext)s', '-vU', '--retries', '4', '--embed-chapters', '--embed-subs', '--no-mtime', '--merge-output-format', 'mkv', 'https://www.youtube.com/watch?v=g19lNpK_71E']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110402-ge3143703e9-20230427 (setts), ffprobe N-110402-ge3143703e9-20230427, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=g19lNpK_71E
[youtube] g19lNpK_71E: Downloading webpage
[youtube] g19lNpK_71E: Downloading ios player API JSON
[youtube] g19lNpK_71E: Downloading android player API JSON
[debug] Loading youtube-nsig.b854ee52 from cache
[debug] [youtube] Decrypted nsig hrADYv8yld6Oa0Dl => mDNY6gdtJ_azNg
[youtube] g19lNpK_71E: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] g19lNpK_71E: Downloading 1 format(s): 303+251
[info] There are no subtitles for the requested languages
[debug] Invoking http downloader on "https://rr2---sn-nx5s7n7z.googlevideo.com/videoplayback?expire=1707953962&ei=yfrMZe3tPNXWsfIP_piFwAI&ip=216.243.56.240&id=o-AD-nLWLz_D3Za5h35LaBJzcqrfMwnuoJEwJnPNLiTc_K&itag=303&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=88&mm=31%2C26&mn=sn-nx5s7n7z%2Csn-n4v7snse&ms=au%2Conr&mv=m&mvi=2&pl=19&initcwndbps=2818750&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=98179099&dur=599.899&lmt=1707841677300032&mt=1707931493&fvip=2&keepalive=yes&fexp=24007246&c=IOS&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgIKR8qXPCpnETLYQ94gEyroTcWabMQGKwJACk1O8btqsCIH9qgeOnE-U7JZA6jrvx71Cqjmr2mpLcQXS6WVnd-xgm&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=APTiJQcwRQIhAIdko2IURzfCMm_RKcmllDzvdkGuOHnOh-t6JS_pk_W_AiBoutQV1Fr8_QVYy_cHMOvqA4kIK6nG2DyXZLhfLto29Q%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: C:\work-area\Downloads\chapters#Huge Progress for Yuzu, a NEW GBA Emulator, Winlator Development and more....f303.webm
[download] 100% of   93.63MiB in 00:00:01 at 49.51MiB/s
[debug] Invoking http downloader on "https://rr4---sn-nx57ynsd.googlevideo.com/videoplayback?expire=1707953962&ei=yvrMZaebCO7LsfIP6JGNgAM&ip=216.243.56.240&id=o-AOtC0yCF0o0k4_RznkvQijksXIEmwZWINJXd8koV9N-O&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=88&mm=31%2C26&mn=sn-nx57ynsd%2Csn-o097znzr&ms=au%2Conr&mv=m&mvi=4&pl=19&initcwndbps=798750&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=9584525&dur=599.921&lmt=1707834256301778&mt=1707932218&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAMI5UGOGL-Vg-pqhvSUb7cPd64J_GX0k_yr9ZgvJSqYkAiEA3r9tuzelYwSh38w95mwHVPw4IAEkGerN0aocQImFgoc%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=APTiJQcwRQIhAMap2FurPT8HEFEaqclm9j2LsP9ikRVh2MaX1hChEFOcAiBA13KW1rRx0VXOZ2Md9popEr4p7rjTxmHIEgOFpU7G4g%3D%3D"
[download] Destination: C:\work-area\Downloads\chapters#Huge Progress for Yuzu, a NEW GBA Emulator, Winlator Development and more....f251.webm
[download] 100% of    9.14MiB in 00:00:00 at 57.80MiB/s
[Merger] Merging formats into "C:\work-area\Downloads\chapters#Huge Progress for Yuzu, a NEW GBA Emulator, Winlator Development and more....mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\work-area\Downloads\chapters#Huge Progress for Yuzu, a NEW GBA Emulator, Winlator Development and more....f303.webm" -i "file:C:\work-area\Downloads\chapters#Huge Progress for Yuzu, a NEW GBA Emulator, Winlator Development and more....f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:C:\work-area\Downloads\chapters#Huge Progress for Yuzu, a NEW GBA Emulator, Winlator Development and more....temp.mkv"
Deleting original file C:\work-area\Downloads\chapters#Huge Progress for Yuzu, a NEW GBA Emulator, Winlator Development and more....f303.webm (pass -k to keep)
Deleting original file C:\work-area\Downloads\chapters#Huge Progress for Yuzu, a NEW GBA Emulator, Winlator Development and more....f251.webm (pass -k to keep)
[EmbedSubtitle] There aren't any subtitles to embed
[Metadata] Adding metadata to "C:\work-area\Downloads\chapters#Huge Progress for Yuzu, a NEW GBA Emulator, Winlator Development and more....mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:\work-area\Downloads\chapters#Huge Progress for Yuzu, a NEW GBA Emulator, Winlator Development and more....mkv" -i "file:C:\work-area\Downloads\chapters#Huge Progress for Yuzu, a NEW GBA Emulator, Winlator Development and more....meta" -map 0 -dn -ignore_unknown -c copy -map_metadata 1 -movflags "+faststart" "file:C:\work-area\Downloads\chapters#Huge Progress for Yuzu, a NEW GBA Emulator, Winlator Development and more....temp.mkv"
```

**Comment by bashonly** [comment] 2024-02-14 17:47
Duplicate of #6859

ffmpeg regression in version 6.0. Upgrade to 6.1.1: https://github.com/yt-dlp/FFmpeg-Builds

**Closed by bashonly** 2024-02-14 17:47 UTC
Labels: site-bug, triage
