### ISSUE TITLE
YouTube - "mountain" statistics in progress bar

### ISSUE THREAD

**Issue by upintheairsheep** [yt-dlp/yt-dlp#3884] opened 2022-05-27 20:32 UTC
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Example URLs

https://www.youtube.com/watch?v=p5jRNAvly7g
https://www.youtube.com/watch?v=uCnzQYRqYwI

### Description

youtube has a new feature where there are view statistics can be viewed in the progress bar. Please add that information to the info json probably with a flag required.

### Verbose log

```shell
not attempted
```

**Comment by HobbyistDev** [comment] 2022-06-18 10:41
I think you mean 'heatmap', if yes then this one is duplicate of #3888

**Closed** 2022-06-18 13:33 UTC
Labels: duplicate, site-enhancement
