### ISSUE TITLE
[Instagram] Reel Content with don't need login, Requerid login

### ISSUE THREAD

**Issue by iiroak** [yt-dlp/yt-dlp#10129] opened 2024-06-07 13:20 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Chile

### Provide a description that is worded well enough to be understood

I am trying to download this public Reel, which does not require login, I have verified it several times in different browsers. But when using it in the console it indicates that it needs a login
IG Link: https://www.instagram.com/reel/C59fbW7PFZn/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.instagram.com/reel/C59fbW7PFZn/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (py2exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-11-02-git-4dbfb52230-full_build-www.gyan.dev (setts), ffprobe 2023-11-02-git-4dbfb52230-full_build-www.gyan.dev
[debug] Optional libraries: brotli-1.1.0, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[Instagram] Extracting URL: https://www.instagram.com/reel/C59fbW7PFZn/
[Instagram] C59fbW7PFZn: Setting up session
[Instagram] C59fbW7PFZn: Downloading JSON metadata
WARNING: [Instagram] C59fbW7PFZn: General metadata extraction failed (some metadata might be missing).
[Instagram] C59fbW7PFZn: Downloading webpage
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
[Instagram] C59fbW7PFZn: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] C59fbW7PFZn: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
  File "yt_dlp\extractor\common.pyc", line 734, in extract
  File "yt_dlp\extractor\instagram.pyc", line 460, in _real_extract
  File "yt_dlp\extractor\common.pyc", line 1239, in raise_login_required

--- WITH COOKIES FROM CHROME --
[debug] Command-line config: ['-vU', 'https://www.instagram.com/reel/C59fbW7PFZn/', '--cookies-from-browser', 'chrome']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (py2exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-11-02-git-4dbfb52230-full_build-www.gyan.dev (setts), ffprobe 2023-11-02-git-4dbfb52230-full_build-www.gyan.dev
[debug] Optional libraries: brotli-1.1.0, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\iroaK\AppData\Local\Google\Chrome\User Data\Profile 19\Network\Cookies"
[debug] Found local state file at "C:\Users\iroaK\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Loading cookie      0/   531WARNING: failed to decrypt cookie (AES-GCM) because the MAC check failed. Possibly the key is wrong?
Extracted 479 cookies from chrome (38 could not be decrypted)
[debug] cookie version breakdown: {'v10': 529, 'other': 0, 'unencrypted': 2}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[Instagram] Extracting URL: https://www.instagram.com/reel/C59fbW7PFZn/
[Instagram] C59fbW7PFZn: Setting up session
[Instagram] C59fbW7PFZn: Downloading JSON metadata
WARNING: [Instagram] C59fbW7PFZn: General metadata extraction failed (some metadata might be missing).
[Instagram] C59fbW7PFZn: Downloading webpage
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
[Instagram] C59fbW7PFZn: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] C59fbW7PFZn: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
  File "yt_dlp\extractor\common.pyc", line 734, in extract
  File "yt_dlp\extractor\instagram.pyc", line 460, in _real_extract
  File "yt_dlp\extractor\common.pyc", line 1239, in raise_login_required
```

**Comment by bashonly** [comment] 2024-06-12 23:44
Duplicate of #7165

It's not working with cookies from chrome likely because yt-dlp is failing to decrypt some of your cookies:

```
[Cookies] Loading cookie      0/   531WARNING: failed to decrypt cookie (AES-GCM) because the MAC check failed. Possibly the key is wrong?
Extracted 479 cookies from chrome (38 could not be decrypted)
```

This is possibly a side effect of using the [py2exe build where many things are kind-of broken](https://github.com/yt-dlp/yt-dlp/issues/10087) .

[Try exporting your cookies to a text file](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp) and passing them to yt-dlp with the `--cookies` option. Be aware though that instagram does not hesitate to ban accounts when it detects 3rd party tool usage

**Closed by bashonly** 2024-06-12 23:44 UTC
Labels: duplicate, site-bug, site:instagram
