### ISSUE TITLE
[Instagram] ERROR: C0AsYItMrr7: An extractor error has occurred. (caused by KeyError('config'));

### ISSUE THREAD

**Issue by Dune808** [yt-dlp/yt-dlp#9881] opened 2024-05-08 04:16 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

I'm running mediaforge and after talking to the bot developer she said it was an issue with yt-dlp, so I came here. I used my login for twitter and youtube and neither are having this issue, only instagram. The command works if I don't add the instagram argument but I run into rate limit issues. ERROR: C0AsYItMrr7: An extractor error has occurred is all I can discern, I'm not particularly good with coding but that's the error that gets thrown up when I try to download.
![image_2024-05-08_001449971](https://github.com/yt-dlp/yt-dlp/assets/146230115/4557da6f-92b0-4732-9e91-072eaab5054c)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I'm sorry but idk how to do any of these in the mediaforge instance and the developer of the bot is on hiatus so I can't ask her how to do it
```

**Comment by bashonly** [comment] 2024-05-08 04:18
Duplicate of #7328

Login via user/pass/netrc is broken; this is being tracked in the above linked issue

`--cookies` and `--cookies-from-browser` should work, but be aware that IG does not hesitate at all to ban accounts using 3rd party tools

**Closed by bashonly** 2024-05-08 04:18 UTC
Labels: duplicate, site-bug, site:instagram
