### ISSUE TITLE
Set mtime for thumbnail and description files

### ISSUE THREAD

**Issue by AlttiRi** [yt-dlp/yt-dlp#6756] opened 2023-04-09 21:50 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Currently yt-dlp sets mtime only for video files.

I would like if yt-dlp will set file modification time for thumbnail (`--write-thumbnail`) and description (`--write-description`) files too.

It would be useful for people who use file sorting by mtime. In this case all 3 files (video, image, text) will be near each other in the explorer.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
```

**Comment by bashonly** [comment] 2023-10-13 21:31
Duplicate of #655

**Closed by bashonly** 2023-10-13 21:31 UTC
Labels: enhancement
