### ISSUE TITLE
n-tv.de Unable to extract info

### ISSUE THREAD

**Issue by DottieUnderwood** [yt-dlp/yt-dlp#8403] opened 2023-10-21 16:49 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

n-tv.de reports an error for any video

Example:
yt-dlp https://www.n-tv.de/mediathek/videos/panorama/Wasser-im-Flensburger-Hafen-steht-noch-relativ-hoch-article24480119.html

ERROR: [n-tv.de] 24480119: Unable to extract info

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.n-tv.de/mediathek/videos/panorama/Wasser-im-Flensburger-Hafen-steht-noch-relativ-hoch-article24480119.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.5.0-9-generic-x86_64-with-glibc2.38 (OpenSSL 3.0.10 1 Aug 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-3.42.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
yt-dlp is up to date (stable@2023.10.13)
[n-tv.de] Extracting URL: https://www.n-tv.de/mediathek/videos/panorama/Wasser-im-Flensburger-Hafen-steht-noch-relativ-hoch-article24480119.html
[n-tv.de] 24480119: Downloading webpage
ERROR: [n-tv.de] 24480119: Unable to extract info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/xxxx/.local/pipx/venvs/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxxx/.local/pipx/venvs/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/ntvde.py", line 36, in _real_extract
    info = self._parse_json(self._search_regex(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/xxxx/.local/pipx/venvs/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1263, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment] 2023-10-21 21:29
Duplicate of #3179

**Closed by bashonly** 2023-10-21 21:29 UTC
Labels: site-bug, triage

**Comment by 1100101** [comment] 2023-10-22 14:56
@bashonly Why did you mark this as geo-blocked? 
The author of the ticket stated that he is in Germany, and there the video loads just fine in the browser.

**Comment by bashonly** [comment] 2023-10-22 14:57
The content is geo-restricted to Germany, so any developer needs to have a German IP in order to work on this. It is a duplicate anyways, this is moot
