### ISSUE TITLE
telewebion

### ISSUE THREAD

**Issue by hypercianstand** [yt-dlp/yt-dlp#4188] opened 2022-06-26 09:19 UTC
### Checklist

- [x] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

/watch https://telewebion.com/episode/0x28e0ab5

ERROR: Unsupported URL: https://telewebion.com/episode/0x28e0ab5

### Verbose log

```shell
2022-06-26T09:18:38.613876+00:00 app[web.1]: 2022-06-26 09:18:38,613 - bot.helper.mirror_utils.download_utils.youtube_dl_download_helper - WARNING - [generic] Falling back on generic information extractor.
2022-06-26T09:18:39.043717+00:00 app[web.1]: 2022-06-26 09:18:39,043 - bot.helper.mirror_utils.download_utils.youtube_dl_download_helper - ERROR - ERROR: Unsupported URL: https://telewebion.com/episode/0x28e0ab5
```

**Comment by gamer191** [comment] 2022-06-26 09:46
https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-your-question-about-yt-dlp

**Comment by HobbyistDev** [comment] 2022-06-26 09:57
Doesn't this duplicate of #2598 ?

**Closed** 2022-06-26 10:02 UTC
Labels: incomplete, site-bug
