### ISSUE TITLE
Format extraction often misses some available formats

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [yt-dlp/yt-dlp#10208] opened 2024-06-19 01:12 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The results of `--list-formats` occasionally (frequently) misses the `22` format in its output as per output below.
Note that in the 1st run, **ID** `22` is shown in the list, but in the 2st run, **ID** `22` is missing, though 1280x720 format is available (as can be seen by the other 1280x720 entries). This has been happening to me for about a month or two.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
user@host$ yt-dlp -vU --list-formats "https://www.youtube.com/watch?v=BaW_jenozKc"
[debug] Command-line config: ['-vU', '--list-formats', 'https://www.youtube.com/watch?v=BaW_jenozKc']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 90c3721a3
[debug] Python 3.12.3 (CPython x86_64 64bit) - macOS-14.2.1-x86_64-i386-64bit (OpenSSL 3.3.0 9 Apr 2024)
[debug] exe versions: ffmpeg 7.0 (setts), ffprobe 7.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: sqlite3-3.45.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=BaW_jenozKc
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading ios player API JSON
[debug] Loading youtube-nsig.84314bef from cache
[debug] [youtube] Decrypted nsig GxgrqN8fNpr_7mBc_O => ypnFufZ3Hu776A
[youtube] BaW_jenozKc: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for BaW_jenozKc:
ID      EXT   RESOLUTION FPS CH │   FILESIZE  TBR PROTO │ VCODEC         VBR ACODEC      ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb0     mhtml 48x27       10    │                 mhtml │ images                                 storyboard
233     mp4   audio only        │                 m3u8  │ audio only         unknown             [en] Default, IOS
234     mp4   audio only        │                 m3u8  │ audio only         unknown             [en] Default, IOS
139-drc m4a   audio only      2 │   60.21KiB  49k https │ audio only         mp4a.40.5   49k 22k [en] low, DRC, IOS, m4a_dash
139     m4a   audio only      2 │   60.20KiB  49k https │ audio only         mp4a.40.5   49k 22k [en] low, IOS, m4a_dash
140-drc m4a   audio only      2 │  157.14KiB 130k https │ audio only         mp4a.40.2  130k 44k [en] medium, DRC, IOS, m4a_dash
140     m4a   audio only      2 │  157.16KiB 130k https │ audio only         mp4a.40.2  130k 44k [en] medium, IOS, m4a_dash
269     mp4   256x144     30    │ ~ 83.18KiB  68k m3u8  │ avc1.4D400C    68k video only          IOS
160     mp4   256x144     30    │   14.93KiB  12k https │ avc1.4D400C    12k video only          144p, IOS, mp4_dash
230     mp4   640x360     30    │ ~205.33KiB 168k m3u8  │ avc1.4D401E   168k video only          IOS
134     mp4   640x360     30    │   29.39KiB  24k https │ avc1.4D401E    24k video only          360p, IOS, mp4_dash
18      mp4   640x360     30  2 │  199.11KiB 165k https │ avc1.42001E        mp4a.40.2       44k [en] 360p, WEB
605     mp4   640x360     30    │ ~255.88KiB 210k m3u8  │ vp09.00.21.08 210k video only          IOS
22      mp4   1280x720    30  2 │ ≈216.64KiB 179k https │ avc1.64001F        mp4a.40.2       44k [en] 720p, WEB
232     mp4   1280x720    30    │ ~247.03KiB 202k m3u8  │ avc1.4D401F   202k video only          IOS
136     mp4   1280x720    30    │   59.04KiB  49k https │ avc1.4D401F    49k video only          720p, IOS, mp4_dash
270     mp4   1920x1080   30    │ ~484.67KiB 397k m3u8  │ avc1.640028   397k video only          IOS
137     mp4   1920x1080   30    │  286.74KiB 239k https │ avc1.640028   239k video only          1080p, IOS, mp4_dash


user@host$ yt-dlp -vU --list-formats "https://www.youtube.com/watch?v=BaW_jenozKc"
[debug] Command-line config: ['-vU', '--list-formats', 'https://www.youtube.com/watch?v=BaW_jenozKc']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 90c3721a3
[debug] Python 3.12.3 (CPython x86_64 64bit) - macOS-14.2.1-x86_64-i386-64bit (OpenSSL 3.3.0 9 Apr 2024)
[debug] exe versions: ffmpeg 7.0 (setts), ffprobe 7.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: sqlite3-3.45.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=BaW_jenozKc
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading ios player API JSON
[debug] Loading youtube-nsig.84314bef from cache
[debug] [youtube] Decrypted nsig oftiQ02t4OC3HptPX7 => KKuESmTqteTKrQ
[youtube] BaW_jenozKc: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for BaW_jenozKc:
ID      EXT   RESOLUTION FPS CH │   FILESIZE  TBR PROTO │ VCODEC         VBR ACODEC      ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb0     mhtml 48x27       10    │                 mhtml │ images                                 storyboard
233     mp4   audio only        │                 m3u8  │ audio only         unknown             [en] Default, IOS
234     mp4   audio only        │                 m3u8  │ audio only         unknown             [en] Default, IOS
139-drc m4a   audio only      2 │   60.21KiB  49k https │ audio only         mp4a.40.5   49k 22k [en] low, DRC, IOS, m4a_dash
139     m4a   audio only      2 │   60.20KiB  49k https │ audio only         mp4a.40.5   49k 22k [en] low, IOS, m4a_dash
140-drc m4a   audio only      2 │  157.14KiB 130k https │ audio only         mp4a.40.2  130k 44k [en] medium, DRC, IOS, m4a_dash
140     m4a   audio only      2 │  157.16KiB 130k https │ audio only         mp4a.40.2  130k 44k [en] medium, IOS, m4a_dash
269     mp4   256x144     30    │ ~ 83.18KiB  68k m3u8  │ avc1.4D400C    68k video only          IOS
160     mp4   256x144     30    │   14.93KiB  12k https │ avc1.4D400C    12k video only          144p, IOS, mp4_dash
230     mp4   640x360     30    │ ~205.33KiB 168k m3u8  │ avc1.4D401E   168k video only          IOS
134     mp4   640x360     30    │   29.39KiB  24k https │ avc1.4D401E    24k video only          360p, IOS, mp4_dash
18      mp4   640x360     30  2 │  199.11KiB 165k https │ avc1.42001E        mp4a.40.2       44k [en] 360p, WEB
605     mp4   640x360     30    │ ~255.88KiB 210k m3u8  │ vp09.00.21.08 210k video only          IOS
232     mp4   1280x720    30    │ ~247.03KiB 202k m3u8  │ avc1.4D401F   202k video only          IOS
136     mp4   1280x720    30    │   59.04KiB  49k https │ avc1.4D401F    49k video only          720p, IOS, mp4_dash
270     mp4   1920x1080   30    │ ~484.67KiB 397k m3u8  │ avc1.640028   397k video only          IOS
137     mp4   1920x1080   30    │  286.74KiB 239k https │ avc1.640028   239k video only          1080p, IOS, mp4_dash
```

**Comment by bashonly** [comment] 2024-06-19 01:24
Sometimes Youtube doesn't send the stream info for format 22. Nothing we can do about that. Duplicate of #10206

**Closed by bashonly** 2024-06-19 01:24 UTC
Labels: bug, triage
