### ISSUE TITLE
kick recording 

### ISSUE THREAD

**Issue by zdhd122a** [yt-dlp/yt-dlp#7394] opened 2023-06-23 04:42 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Bulgaria

### Example URLs

https://kick.com/sixtysevenradio

### Provide a description that is worded well enough to be understood

Trying to record from the kick platform, checked if this platform is in the supported sites by the link https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md and yes yt-dlp supports kick but when recording it gives an error which I will leave below, tried both the .exe version of yt-dlp and the pip version gives the same error

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe -vU --cookies-from-browser chrome https://kick.com/sixtysevenradio
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'chrome', 'https://kick.com/sixtysevenradio']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.2.3, ffprobe 2022-02-24-git-8ef03c2ff1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\35988\AppData\Local\Google\Chrome\User Data\Profile 1\Network\Cookies"
[debug] Found local state file at "C:\Users\35988\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 45 cookies from chrome
[debug] cookie version breakdown: {'v10': 45, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 37e7ffe204309357cfd1388b0e2c782a30e293ddd0f2761a9a8f6afa185b3566
yt-dlp is up to date (stable@2023.06.22)
[Kick] Setting up session
WARNING: [Kick] Unable to download webpage: HTTP Error 403: Forbidden
[Kick] Extracting URL: https://kick.com/sixtysevenradio
[Kick] sixtysevenradio: Downloading API JSON
ERROR: [Kick] sixtysevenradio: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 708, in extract
  File "yt_dlp\extractor\kick.py", line 59, in _real_extract
  File "yt_dlp\extractor\kick.py", line 27, in _call_api
  File "yt_dlp\extractor\common.py", line 1062, in download_content
  File "yt_dlp\extractor\common.py", line 1026, in download_handle
  File "yt_dlp\extractor\common.py", line 896, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 853, in _request_webpage

  File "yt_dlp\extractor\common.py", line 835, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3786, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment] 2023-06-23 09:30
Duplicate of #6748

**Closed by bashonly** 2023-06-23 09:30 UTC
Labels: site-bug, triage
