### ISSUE TITLE
add html decode for facebook

### ISSUE THREAD

**Issue by error-reporting** [yt-dlp/yt-dlp#10771] opened 2024-08-16 16:04 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.facebook.com/reel/1250338579678163/?app=fbl

### Provide a description that is worded well enough to be understood

adding html decoding for facebook uploader parsing
i notice facebook was using html encode in their uploader metadata field

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Downloading:
Title: 64K views · 757 reactions | Tập 5: #Yugi ứng dụng môn Vật lý vào đánh bài cực ảo và cái kết đắng dành cho Haga #yugioh #anime #vuatrodua | Vua Trò Đùa | Vua Trò Đùa · Original audio
URL: https://www.facebook.com/reel/1155436925787716/?app=fbl
Type: video
Command: 
 -N "4" --retries "20" --fragment-retries "5" --sponsorblock-api "https://sponsor.ajay.app" --trim-filenames "182" --write-thumbnail --convert-thumbnails "jpg" --no-mtime --parse-metadata "uploader:^(?P<uploader>.*?)(?:(?= - Topic)|$)" --parse-metadata "%(uploader,channel,creator,artist|null)s:%(uploader)s" --write-description --sponsorblock-mark "all" --embed-chapters -f "2230948357238018v+1176617906685175a/2230948357238018v+ba/2230948357238018v/b" --write-subs --write-auto-subs --sub-format "vtt/best" --convert-subtitles "vtt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/283" -o "%(title).170B %(id).70B %(uploader)s %(availability)s %(upload_date)s.%(ext)s" -vU
--add-header "Referer:https://www.youtube.com"
--buffer-size "4096"
--no-hls-use-mpegts --write-info-json
--write-playlist-metafiles
--write-comments
--merge-output-format "mkv"
--username "huynhnhuthoang5@gmail.com"
--password "2 0 0 0 mah 3.8v"
--fixup "never"
--add-metadata
--remux-video "mkv" --replace-in-metadata "video:title" ".+" "64K views · 757 reactions | Tập 5: #Yugi ứng dụng môn Vật lý vào đánh bài cực ảo và cái kết đắng dành cho Haga #yugioh #anime #vuatrodua | Vua Trò Đùa | Vua Trò Đùa · Original audi" --replace-in-metadata "video:uploader" ".+" "64K views &#xb7; 757 reactions" "https://www.facebook.com/reel/1155436925787716/?app=fbl" 


Latest version: master@2024.08.15.195757 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.08.15.195757 from yt-dlp/yt-dlp-master-builds)
[facebook:reel] Extracting URL: https://www.facebook.com/reel/1155436925787716/?app=fbl
[facebook] Downloading login page
[facebook] Logging in
[facebook] Extracting URL: https://m.facebook.com/watch/?v=1155436925787716&_rdr
[facebook] 1155436925787716: Downloading webpage
[MetadataParser] Parsed uploader from '%(uploader)s': '64K views &#xb7; 757 reactions | T&#x1ead;p 5: #Yugi &#x1ee9;ng d&#x1ee5;ng m&#xf4;n V&#x1ead;t l&#xfd; v&#xe0;o &#x111;&#xe1;nh b&#xe0;i c&#x1ef1;c &#x1ea3;o v&#xe0; c&#xe1;i k&#x1ebf;t &#x111;&#x1eaf;ng d&#xe0;nh cho Haga #yugioh #anime #vuatrodua | Vua Tr&#xf2; &#x110;&#xf9;a | Vua Tr&#xf2; &#x110;&#xf9;a &#xb7; Original audio'
[MetadataParser] Parsed uploader from '%(uploader,channel,creator,artist|null)s': '64K views &#xb7; 757 reactions | T&#x1ead;p 5: #Yugi &#x1ee9;ng d&#x1ee5;ng m&#xf4;n V&#x1ead;t l&#xfd; v&#xe0;o &#x111;&#xe1;nh b&#xe0;i c&#x1ef1;c &#x1ea3;o v&#xe0; c&#xe1;i k&#x1ebf;t &#x111;&#x1eaf;ng d&#xe0;nh cho Haga #yugioh #anime #vuatrodua | Vua Tr&#xf2; &#x110;&#xf9;a | Vua Tr&#xf2; &#x110;&#xf9;a &#xb7; Original audio'
[SponsorBlock] SponsorBlock is not supported for Facebook
[info] 1155436925787716: Downloading 1 format(s): 2230948357238018v+1176617906685175a
[MetadataParser] Changed title to: 64K views · 757 reactions | Tập 5: #Yugi ứng dụng môn Vật lý vào đánh bài cực ảo và cái kết đắng dành cho Haga #yugioh #anime #vuatrodua | Vua Trò Đùa | Vua Trò Đùa · Original audi
[MetadataParser] Changed uploader to: 64K views &#xb7; 757 reactions
[info] Writing video description to: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/283/64K views · 757 reactions ｜ Tập 5： #Yugi ứng dụng môn Vật lý vào đánh bài cực ảo và cái kết đắng dành cho Haga #yugioh #anime #vuatrodua ｜ Vua  1155436925787716 64K views &#xb7; 757 .description
[info] There are no subtitles for the requested languages
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/283/64K views · 757 reactions ｜ Tập 5： #Yugi ứng dụng môn Vật lý vào đánh bài cực ảo và cái kết đắng dành cho Haga #yugioh #anime #vuatrodua ｜ Vua  1155436925787716 64K views &#xb7; 757 .jpg
[info] Writing video metadata as JSON to: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/283/64K views · 757 reactions ｜ Tập 5： #Yugi ứng dụng môn Vật lý vào đánh bài cực ảo và cái kết đắng dành cho Haga #yugioh #anime #vuatrodua ｜ Vua  1155436925787716 64K views &#xb7; 757 .info.json
[SubtitlesConvertor] There aren't any subtitles to convert
[ThumbnailsConvertor] Not converting thumbnail "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/283/64K views · 757 reactions ｜ Tập 5： #Yugi ứng dụng môn Vật lý vào đánh bài cực ảo và cái kết đắng dành cho Haga #yugioh #anime #vuatrodua ｜ Vua  1155436925787716 64K views &#xb7; 757 .jpg"; already is in target format jpg
[download] Destination: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/283/64K views · 757 reactions ｜ Tập 5： #Yugi ứng dụng môn Vật lý vào đánh bài cực ảo và cái kết đắng dành cho Haga #yugioh #anime #vuatrodua ｜ Vua  1155436925787716 64K views &#xb7; 757 .f2230948357238018v.mp4

[download]   0.0% of    9.24MiB at   17.95KiB/s ETA 08:47
[download]   0.1% of    9.24MiB at   52.77KiB/s ETA 02:59
[download]   0.3% of    9.24MiB at  105.15KiB/s ETA 01:29
[download]   0.6% of    9.24MiB at  197.93KiB/s ETA 00:47
[download]   1.3% of    9.24MiB at  313.94KiB/s ETA 00:29
[download]   2.7% of    9.24MiB at  211.16KiB/s ETA 00:43
[download]   4.4% of    9.24MiB at  335.99KiB/s ETA 00:26
[download]   7.7% of    9.24MiB at  292.92KiB/s ETA 00:29
[download]  10.4% of    9.24MiB at  304.84KiB/s ETA 00:27
[download]  14.1% of    9.24MiB at  253.72KiB/s ETA 00:32
[download]  15.9% of    9.24MiB at  286.10KiB/s ETA 00:27
[download]  19.5% of    9.24MiB at  312.56KiB/s ETA 00:24
[download]  25.1% of    9.24MiB at  356.35KiB/s ETA 00:19
[download]  32.5% of    9.24MiB at  426.85KiB/s ETA 00:14
[download]  46.0% of    9.24MiB at  536.79KiB/s ETA 00:09
[download]  61.0% of    9.24MiB at  648.66KiB/s ETA 00:05
[download]  79.8% of    9.24MiB at  776.19KiB/s ETA 00:02
[download] 100.0% of    9.24MiB at  884.45KiB/s ETA 00:00
[download] 100% of    9.24MiB in 00:00:11 at 830.64KiB/s 
[download] Destination: /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/283/64K views · 757 reactions ｜ Tập 5： #Yugi ứng dụng môn Vật lý vào đánh bài cực ảo và cái kết đắng dành cho Haga #yugioh #anime #vuatrodua ｜ Vua  1155436925787716 64K views &#xb7; 757 .f1176617906685175a.m4a

[download]   0.6% of  689.18KiB at   94.49KiB/s ETA 00:07
[download]   1.7% of  689.18KiB at  248.73KiB/s ETA 00:02
[download]   4.1% of  689.18KiB at  506.25KiB/s ETA 00:01
[download]   8.7% of  689.18KiB at  681.87KiB/s ETA 00:00
[download]  18.0% of  689.18KiB at 1004.02KiB/s ETA 00:00
[download]  36.6% of  689.18KiB at    1.11MiB/s ETA 00:00
[download]  73.7% of  689.18KiB at  990.92KiB/s ETA 00:00
[download] 100.0% of  689.18KiB at    1.04MiB/s ETA 00:00
[download] 100% of  689.18KiB in 00:00:00 at 826.17KiB/s 
[Merger] Merging formats into "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/283/64K views · 757 reactions ｜ Tập 5： #Yugi ứng dụng môn Vật lý vào đánh bài cực ảo và cái kết đắng dành cho Haga #yugioh #anime #vuatrodua ｜ Vua  1155436925787716 64K views &#xb7; 757 .mkv"
Deleting original file /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/283/64K views · 757 reactions ｜ Tập 5： #Yugi ứng dụng môn Vật lý vào đánh bài cực ảo và cái kết đắng dành cho Haga #yugioh #anime #vuatrodua ｜ Vua  1155436925787716 64K views &#xb7; 757 .f1176617906685175a.m4a (pass -k to keep)
Deleting original file /storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/283/64K views · 757 reactions ｜ Tập 5： #Yugi ứng dụng môn Vật lý vào đánh bài cực ảo và cái kết đắng dành cho Haga #yugioh #anime #vuatrodua ｜ Vua  1155436925787716 64K views &#xb7; 757 .f2230948357238018v.mp4 (pass -k to keep)
[VideoRemuxer] Not remuxing media file "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/283/64K views · 757 reactions ｜ Tập 5： #Yugi ứng dụng môn Vật lý vào đánh bài cực ảo và cái kết đắng dành cho Haga #yugioh #anime #vuatrodua ｜ Vua  1155436925787716 64K views &#xb7; 757 .mkv"; already is in target format mkv
[Metadata] Adding metadata to "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/283/64K views · 757 reactions ｜ Tập 5： #Yugi ứng dụng môn Vật lý vào đánh bài cực ảo và cái kết đắng dành cho Haga #yugioh #anime #vuatrodua ｜ Vua  1155436925787716 64K views &#xb7; 757.mkv"
```

**Comment by bashonly** [comment] 2024-08-16 16:09
Altogether the wrong data is being extracted as `uploader`

Duplicate of #9057

**Closed by bashonly** 2024-08-16 16:09 UTC
Labels: duplicate, site-bug, site:facebook

**Comment by error-reporting** [comment] 2024-08-16 16:19
my case don't have the character \n. within the facebook video description
