### ISSUE TITLE
Unable to extract initial player response/yt initial data

### ISSUE THREAD

**Issue by Pelle-B** [yt-dlp/yt-dlp#7904] opened 2023-08-19 12:49 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Sweden

### Provide a description that is worded well enough to be understood

This seems to be different than #7900 as download and extraction succeeds. The warnings started to occur yesterday (18th August)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -Uvx --audio-format="mp3" https://www.youtube.com/watch?v=_zovGiekEEU[debug] Command-line config: ['-Uvx', '--audio-format=mp3', 'https://www.youtube.com/watch?v=_zovGiekEEU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.4.11-Venom-x86_64-with-glibc2.36 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 6.0 (fdk,setts), ffprobe 6.0
[debug] Optional libraries: brotli-1.0.9, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=_zovGiekEEU
[youtube] _zovGiekEEU: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] _zovGiekEEU: Downloading ios player API JSON
[youtube] _zovGiekEEU: Downloading android player API JSON
[youtube] _zovGiekEEU: Downloading iframe API JS
[youtube] _zovGiekEEU: Downloading player f980f2a9
[youtube] _zovGiekEEU: Downloading web player API JSON
[debug] Loading youtube-nsig.f980f2a9 from cache
[debug] [youtube] Decrypted nsig kNibZeJ1CM3vAO3vQ9 => hn33zG0LevC-hA
[youtube] _zovGiekEEU: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] _zovGiekEEU: Downloading initial data API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] _zovGiekEEU: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr1---sn-cgxqc5oqufv-5gol.googlevideo.com/videoplayback?expire=1692470255&ei=j7fgZKSGH8e1v_IPs8GKwAY&ip=31.209.43.33&id=o-AAucb3pir61mnNCgzJEZHQ69qhpPN3wxX-E835Uh6yRG&itag=251&source=youtube&requiressl=yes&mh=AW&mm=31%2C26&mn=sn-cgxqc5oqufv-5gol%2Csn-i5h7lnls&ms=au%2Conr&mv=m&mvi=1&pcm2cms=yes&pl=22&pcm2=no&initcwndbps=1868750&spc=UWF9f6l6lSAFbebsByYjRZOO2QCxVTU&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=2364117&dur=178.081&lmt=1642502339218879&mt=1692448147&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=6211224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIfSHZJBqQkSTqm66IHHDCi6Hsrd-Xh3IoW9yVn1mdpCgIhAKTjdIx7BX4WWml0MOSWPpreUulmPx8HcZZe187ltkf9&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAKwU3YQP3YeZ9m4ZxxKNUTc3jfM6utw7mBWJWs6tBiGWAiAkf7j71pMAUWsY7XeUdcDNbdgMSaHa-ohWo83W27iBSw%3D%3D"
[download] Destination: Meme Bianchi - NUVOLE - Orchestra Ceragioli [_zovGiekEEU].webm
[download] 100% of    2.25MiB in 00:00:00 at 6.18MiB/s
[debug] ffmpeg command line: ffprobe -show_streams 'file:Meme Bianchi - NUVOLE - Orchestra Ceragioli [_zovGiekEEU].webm'
[ExtractAudio] Destination: Meme Bianchi - NUVOLE - Orchestra Ceragioli [_zovGiekEEU].mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Meme Bianchi - NUVOLE - Orchestra Ceragioli [_zovGiekEEU].webm' -vn -acodec libmp3lame -q:a 5.0 -movflags +faststart 'file:Meme Bianchi - NUVOLE - Orchestra Ceragioli [_zovGiekEEU].mp3'
Deleting original file Meme Bianchi - NUVOLE - Orchestra Ceragioli [_zovGiekEEU].webm (pass -k to keep)
```

**Comment by bashonly** [comment] 2023-08-19 13:36
Duplicate of #7594

**Closed by bashonly** 2023-08-19 13:36 UTC
Labels: site-bug, triage
