### ISSUE TITLE
Ability to strip Emoji from downloaded file 

### ISSUE THREAD

**Issue by aindriu80** [yt-dlp/yt-dlp#4836] opened 2022-09-03 09:55 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi, 

I download some videos with yt-dlp and watch them through Kodi, some are hours-long programming tutorials and I don't get to watch them all in one go.  

Problem - Some videos have emojis in the title and my watch progress can't be saved.  I would like the ability to strip out the emojis in the title when downloading them via yt-dlp. 

I have set up a MySQL database so I can store my watch progress and share it with multiple devices.  Kodi can't write the progress because it has emojis in the title - having the ability to remove them would be great

Here is an error from the Kodi logs

`2022-09-03 10:33:34.439 T:32885   ERROR <general>: AddFile unable to addfile ()
2022-09-03 10:33:34.445 T:32885   ERROR <general>: SQL: [MyVideos119] Undefined MySQL error: Code (1366)
                                                   Query: insert into files (idFile, idPath, strFileName) values(NULL, 24, 'Example Video File with an emjoi at the end 🤩 - TESTED.webm')`

Can yt-dlp add the ability to remove emojis from the title at download?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment] 2022-09-03 10:08
Use --restrict-filenames or --replace-in-metadata for even more controll

**Comment by pukkandan** [comment] 2022-09-03 10:09
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3047

**Comment by aindriu80** [comment] 2022-09-06 19:27
oh thanks for that pointer

**Closed** 2022-09-07 05:54 UTC
Labels: question
