### ISSUE TITLE
Remove duplicated lines from subtitles

### ISSUE THREAD

**Issue by YakivGluck** [yt-dlp/yt-dlp#3352] opened 2022-04-08 09:36 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Auto-generated subtitles downloaded from YouTube usually have duplicated lines. Removing such lines is more or less easy with additional scripts. But wouldn't it be great to have this feature integrated in yt-dlp with a separate option to activate it?

( [an example of mentioned scripts](https://gist.github.com/davidcortesortuno/64723e4262889f592def55c1927db651) )

**Comment by pukkandan** [comment] 2022-04-08 09:55
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1734

**Closed by pukkandan** 2022-04-08 09:55 UTC
Labels: enhancement, triage
