### ISSUE TITLE
Instagram reel is not leechwatching

### ISSUE THREAD

**Issue by Ashishsinghpvt** [yt-dlp/yt-dlp#4670] opened 2022-08-15 15:17 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.14** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When ever i am trying to leechwatch reel it is showing error like this
 ERROR: [Instagram] Cg6darWDp4Y: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
bot.helper.mirror_utils.download_utils.youtube_dl_download_helper - WARNING - [Instagram] parsing .netrc: No authenticators for instagram (None, line None)
2022-08-15 15:00:58,790 - bot.helper.mirror_utils.download_utils.youtube_dl_download_helper - WARNING - [Instagram] Cg6darWDp4Y: General metadata extraction failed
2022-08-15 15:00:59,402 - bot.helper.mirror_utils.download_utils.youtube_dl_download_helper - WARNING - [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2022-08-15 15:00:59,402 - bot.helper.mirror_utils.download_utils.youtube_dl_download_helper - WARNING - [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2022-08-15 15:00:59,403 - bot.helper.mirror_utils.download_utils.youtube_dl_download_helper - ERROR - ERROR: [Instagram] Cg6darWDp4Y: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by hanimourra** [comment] 2022-08-15 15:41
I experienced the same (using 08.14.2022 build) today. Some Reels are working and some are not.

Not working with yt-dlp:
https://www.instagram.com/reel/ChSGRJDgDjX/

Working with yt-dlp:
https://www.instagram.com/reel/ChKaiN0JQ1O/

**Comment by gamer191** [comment] 2022-08-16 00:59
@Ashishsinghpvt That's not a verbose log. Can you please provide a verbose log?

**Comment by gamer191** [comment] 2022-08-16 01:02
> I experienced the same (using 08.14.2022 build) today. Some Reels are working and some are not.

@hanimourra can you please send a verbose log (run `yt-dlp URL --verbose` and send the output), because @Ashishsinghpvt seems to be using a program other than yt-dlp?

**Comment by observeroftime01** [comment] 2022-08-16 01:51
Because nobody else wants to post a verbose log, and I ran into the same issue today, I'm going to post a log. It appears to be the same issue OP is experiencing, so I feel this is appropriate to add here.

> Not working with yt-dlp:
> https://www.instagram.com/reel/ChKaiN0JQ1O/

```
C:\Users\user>yt-dlp -vU --ignore-config https://www.instagram.com/reel/ChKaiN0JQ1O/
[debug] Command-line config: ['-vU', '--ignore-config', 'https://www.instagram.com/reel/ChKaiN0JQ1O/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.14 [5593720] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-18-git-cb22d5ea3c-full_build-www.gyan.dev (setts), ffprobe 2022-07-18-git-cb22d5ea3c-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.14, Current version: 2022.08.14
yt-dlp is up to date (2022.08.14)
[debug] [Instagram] Extracting URL: https://www.instagram.com/reel/ChKaiN0JQ1O/
[Instagram] ChKaiN0JQ1O: Downloading JSON metadata
WARNING: [Instagram] ChKaiN0JQ1O: General metadata extraction failed
[Instagram] ChKaiN0JQ1O: Downloading video info
[Instagram] ChKaiN0JQ1O: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] ChKaiN0JQ1O: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\instagram.py", line 427, in _real_extract
  File "yt_dlp\extractor\common.py", line 1359, in _og_search_video_url
  File "yt_dlp\extractor\common.py", line 1254, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1218, in _search_regex
```

>OPs URL
>https://www.instagram.com/reel/Cg6darWDp4Y/

```
C:\Users\user>yt-dlp -vU --ignore-config https://www.instagram.com/reel/Cg6darWDp4Y/
[debug] Command-line config: ['-vU', '--ignore-config', 'https://www.instagram.com/reel/Cg6darWDp4Y/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.14 [5593720] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-18-git-cb22d5ea3c-full_build-www.gyan.dev (setts), ffprobe 2022-07-18-git-cb22d5ea3c-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.14, Current version: 2022.08.14
yt-dlp is up to date (2022.08.14)
[debug] [Instagram] Extracting URL: https://www.instagram.com/reel/Cg6darWDp4Y/
[Instagram] Cg6darWDp4Y: Downloading JSON metadata
WARNING: [Instagram] Cg6darWDp4Y: General metadata extraction failed
[Instagram] Cg6darWDp4Y: Downloading video info
[Instagram] Cg6darWDp4Y: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] Cg6darWDp4Y: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\instagram.py", line 427, in _real_extract
  File "yt_dlp\extractor\common.py", line 1359, in _og_search_video_url
  File "yt_dlp\extractor\common.py", line 1254, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1218, in _search_regex
```

**Comment by pukkandan** [comment] 2022-08-16 02:12
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/4532

**Closed by pukkandan** 2022-08-16 02:12 UTC
Labels: site-bug, triage
