### ISSUE TITLE
Support for Tiktok downloading user channel please

### ISSUE THREAD

**Issue by Zachary247** [yt-dlp/yt-dlp#8443] opened 2023-10-26 23:37 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

Error trying to parse the JSON data from the TikTok user video list page. It was working 2 days ago just fine but it seems tiktok have updated there website recently. I really enjoyed using yt-dlp and all the effort put into making this app.
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user] Extracting URL: https://www.tiktok.com/@username1
[tiktok:user] username1: Downloading webpage
[tiktok:user] username1: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] username1: Downloading user video list page 1
ERROR: [tiktok:user] username1: username1: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.tiktok.com/@cblackyyy']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user] Extracting URL: https://www.tiktok.com/@cblackyyy
[tiktok:user] cblackyyy: Downloading webpage
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (1/3)...
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (2/3)...
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (3/3)...
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
ERROR: [tiktok:user] cblackyyy: cblackyyy: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\tiktok.py", line 806, in _real_extract
  File "yt_dlp\utils\traversal.py", line 239, in traverse_obj
  File "yt_dlp\utils\traversal.py", line 227, in _traverse_obj
  File "yt_dlp\utils\traversal.py", line 215, in apply_path
  File "yt_dlp\utils\traversal.py", line 173, in apply_key
  File "yt_dlp\utils\_utils.py", line 2195, in __getitem__
  File "yt_dlp\extractor\tiktok.py", line 774, in _video_entries_api
  File "yt_dlp\utils\_utils.py", line 5114, in __iter__
  File "yt_dlp\extractor\common.py", line 3760, in _error_or_warning
  File "yt_dlp\utils\_utils.py", line 5122, in report_retry
  File "yt_dlp\extractor\tiktok.py", line 776, in _video_entries_api
  File "yt_dlp\extractor\tiktok.py", line 132, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 125, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 62, in _call_api_impl
  File "yt_dlp\extractor\common.py", line 1069, in download_content
  File "yt_dlp\extractor\common.py", line 1039, in download_handle
  File "yt_dlp\extractor\common.py", line 1029, in parse
  File "yt_dlp\extractor\common.py", line 1016, in _parse_json
  File "yt_dlp\extractor\common.py", line 999, in __print_error

  File "yt_dlp\utils\_utils.py", line 555, in decode
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1013, in _parse_json
  File "json\__init__.py", line 370, in loads
  File "yt_dlp\utils\_utils.py", line 563, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by bashonly** [comment] 2023-10-26 23:46
> WARNING: The program functionality for this site has been marked as broken, and will probably not work.

Duplicate of #3776

you might have better luck using this plugin: https://github.com/bashonly/yt-dlp-TTUser

**Closed by bashonly** 2023-10-26 23:46 UTC
Labels: duplicate, site-bug, site:tiktok

**Comment by Zachary247** [comment] 2023-10-27 01:08
Nope didn't have any luck there either. It was working find a before but 2 days ago it stopped working. here is me trying it with the plugin yt-dlp-TTUser Complete Verbose Output below. 
PS D:\yt-dlp-TTUser> .\yt-dlp --extractor-args "tiktok:sec_uid=7275274545622336513" -vU https://www.tiktok.com/@cblackyyy
[debug] Command-line config: ['--extractor-args', 'tiktok:sec_uid=7275274545622336513', '-vU', 'https://www.tiktok.com/@cblackyyy']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user] Extracting URL: https://www.tiktok.com/@cblackyyy
[tiktok:user] cblackyyy: Downloading webpage
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (1/3)...
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (2/3)...
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (3/3)...
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] cblackyyy: Downloading user video list page 1
ERROR: [tiktok:user] cblackyyy: cblackyyy: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\tiktok.py", line 806, in _real_extract
  File "yt_dlp\utils\traversal.py", line 239, in traverse_obj
  File "yt_dlp\utils\traversal.py", line 227, in _traverse_obj
  File "yt_dlp\utils\traversal.py", line 215, in apply_path
  File "yt_dlp\utils\traversal.py", line 173, in apply_key
  File "yt_dlp\utils\_utils.py", line 2195, in __getitem__
  File "yt_dlp\extractor\tiktok.py", line 774, in _video_entries_api
  File "yt_dlp\utils\_utils.py", line 5114, in __iter__
  File "yt_dlp\extractor\common.py", line 3760, in _error_or_warning
  File "yt_dlp\utils\_utils.py", line 5122, in report_retry
  File "yt_dlp\extractor\tiktok.py", line 776, in _video_entries_api
  File "yt_dlp\extractor\tiktok.py", line 132, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 125, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 62, in _call_api_impl
  File "yt_dlp\extractor\common.py", line 1069, in download_content
  File "yt_dlp\extractor\common.py", line 1039, in download_handle
  File "yt_dlp\extractor\common.py", line 1029, in parse
  File "yt_dlp\extractor\common.py", line 1016, in _parse_json
  File "yt_dlp\extractor\common.py", line 999, in __print_error

  File "yt_dlp\utils\_utils.py", line 555, in decode
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1013, in _parse_json
  File "json\__init__.py", line 370, in loads
  File "yt_dlp\utils\_utils.py", line 563, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)

**Comment by tonyfreelance** [comment] 2023-10-27 02:09
Got the same issue today. It was fine before though.

**Comment by Zachary247** [comment] 2023-10-27 02:33
hoping someone finds a fix

**Comment by bashonly** [comment] 2023-10-27 03:54
@Zachary247 You haven't installed the plugin correctly. It is not being loaded by yt-dlp in the above log. The plugin will not be loaded by yt-dlp if you just downloaded/installed it to `D:\yt-dlp-TTUser`

See https://github.com/bashonly/yt-dlp-TTUser#installation for instructions on how to install it with pip,
or see https://github.com/yt-dlp/yt-dlp#installing-plugins for other installation methods.

Locking this since it is a duplicate and further plugin support should be handled on the plugin's issue tracker
