### ISSUE TITLE
CW Shows not working with -f height

### ISSUE THREAD

**Issue by kucksdorfs** [yt-dlp/yt-dlp#687] opened 2021-08-12 12:18 UTC
Yesterday and today I was using yt-dlp for two CW shows and its not honoring the height format I have in the config (that work with other shows/networks). Below is the relevant config items.
```

[debug] User config file: C:\Users\stephen\AppData\Roaming\yt-dlp\config.txt
[debug] User config: ['--write-sub', '-f', '[ext=mp4][height<=720]/[ext=mp4][height<=1080]/[ext=mp4][height<=720]+bestaudio/[ext=mp4][height<=1080]+bestaudio/bestvideo+bestaudio']
[debug] Command-line config: ['-o', 'Riverdale\\Riverdale - s05e11 - Chapter Eighty-Seven: Strange Bedfellows  (Ep.511).%(ext)s', 'https://www.cwtv.com/shows/riverdale/chapter-eighty-seven-strange-bedfellows/?play=764f6359-f0aa-49ff-bf44-894ef31beeb5', '--verbose', '-F']
```

Here is the formats:

```
[info] Available formats for 764f6359-f0aa-49ff-bf44-894ef31beeb5:
ID                       EXT RESOLUTION FPS |   TBR PROTO  | VCODEC        VBR ACODEC  MORE INFO
------------------------ --- ---------- --- - ----- ------ - ----------- ----- ------- -------------
hls-AUDIOGROUP-English-0 mp4 audio only     |       m3u8_n |                   unknown [en], English
hls-AUDIOGROUP-English-1 mp4 audio only     |       m3u8_n |                   unknown [en], English
hls-261-0                mp4 416x234    23  |  261k m3u8_n | avc1.42C01E  261k
hls-261-1                mp4 416x234    23  |  261k m3u8_n | avc1.42C01E  261k
hls-261-2                mp4 416x234    23  |  261k m3u8_n | avc1.42C01E  261k
hls-261-3                mp4 416x234    23  |  261k m3u8_n | avc1.42C01E  261k
hls-495-0                mp4 480x270    23  |  495k m3u8_n | avc1.42C01E  495k
hls-495-1                mp4 480x270    23  |  495k m3u8_n | avc1.42C01E  495k
hls-495-2                mp4 480x270    23  |  495k m3u8_n | avc1.42C01E  495k
hls-495-3                mp4 480x270    23  |  495k m3u8_n | avc1.42C01E  495k
hls-665-0                mp4 640x360    23  |  665k m3u8_n | avc1.42C01E  665k
hls-665-1                mp4 640x360    23  |  665k m3u8_n | avc1.42C01E  665k
hls-665-2                mp4 640x360    23  |  665k m3u8_n | avc1.42C01E  665k
hls-665-3                mp4 640x360    23  |  665k m3u8_n | avc1.42C01E  665k
hls-1301-0               mp4 960x540    23  | 1301k m3u8_n | avc1.4D401F 1301k
hls-1301-1               mp4 960x540    23  | 1301k m3u8_n | avc1.4D401F 1301k
hls-1301-2               mp4 960x540    23  | 1301k m3u8_n | avc1.4D401F 1301k
hls-1301-3               mp4 960x540    23  | 1301k m3u8_n | avc1.4D401F 1301k
hls-1907-0               mp4 1280x720   23  | 1907k m3u8_n | avc1.4D401F 1907k
hls-1907-1               mp4 1280x720   23  | 1907k m3u8_n | avc1.4D401F 1907k
hls-1907-2               mp4 1280x720   23  | 1907k m3u8_n | avc1.4D401F 1907k
hls-1907-3               mp4 1280x720   23  | 1907k m3u8_n | avc1.4D401F 1907k
hls-2542-0               mp4 1280x720   23  | 2542k m3u8_n | avc1.4D401F 2542k
hls-2542-1               mp4 1280x720   23  | 2542k m3u8_n | avc1.4D401F 2542k
hls-2542-2               mp4 1280x720   23  | 2542k m3u8_n | avc1.4D401F 2542k
hls-2542-3               mp4 1280x720   23  | 2542k m3u8_n | avc1.4D401F 2542k
hls-5132-0               mp4 1920x1080  23  | 5132k m3u8_n | avc1.640028 5132k
hls-5132-1               mp4 1920x1080  23  | 5132k m3u8_n | avc1.640028 5132k
hls-5132-2               mp4 1920x1080  23  | 5132k m3u8_n | avc1.640028 5132k
hls-5132-3               mp4 1920x1080  23  | 5132k m3u8_n | avc1.640028 5132k
hls-8160-0               mp4 1920x1080  23  | 8160k m3u8_n | avc1.640028 8160k
hls-8160-1               mp4 1920x1080  23  | 8160k m3u8_n | avc1.640028 8160k
hls-8160-2               mp4 1920x1080  23  | 8160k m3u8_n | avc1.640028 8160k
hls-8160-3               mp4 1920x1080  23  | 8160k m3u8_n | avc1.640028 8160k

```

Manually using -f hls-2542-3+hls-AUDIOGROUP-English-0 gives me the results I expect.

This also appears to be an issue in the upstream youtube-dl project.

**Comment by pukkandan** [comment] 2021-08-12 13:51
This is an issue with your format string. You should use `bv[ext=mp4][height<=720]+bestaudio` as the third (and 4th) terms. You are missing the `bv` specifier

Also, assuming you are just trying to get limit your download to mp4+720p, it is easier to just use `-S "ext:mp4:m4a,res:720"`

**Comment by kucksdorfs** [comment] 2021-08-12 18:06
> 
> 
> This is an issue with your format string. You should use `bv[ext=mp4][height<=720]+bestaudio` as the third (and 4th) terms. You are missing the `bv` specifier
> 
> Also, assuming you are just trying to get limit your download to mp4+720p, it is easier to just use `-S "ext:mp4:m4a,res:720"`

Thank you for your response. I'll change my config to your recommendation.

I would like to say that the config I sent worked fine for older episodes (DC's Legends of Tomorrow S6E10 - https://www.cwtv.com/shows/dcs-legends-of-tomorrow/bad-blood/?play=9eec2d27-c9bb-4cc8-ad18-5cb52904eb78) but this weeks (DC's Legends of Tomorrow S6E11 - https://www.cwtv.com/shows/dcs-legends-of-tomorrow/the-final-frame/?play=cb1a208b-06b0-4c9f-aea3-37813540d3e4). I am not going to pretend I fully understand the syntax for the -f flag, but these settings have worked for youtube-dl for years.

All that said, I will go with your suggestion and close this if that solves my issue. Thank you.

**Comment by pukkandan** [comment] 2021-08-13 05:44
If the video has a pre-merged format, then your original selector will work. You can check in the -F of the videos that used to work whether this is the case. Also, if you think the isue is infact caused by yt-dlp, show verbose logs (as well as -F output) of the same video in both yt-dlp and in youtube-dl

**Comment by kucksdorfs** [comment] 2021-08-13 12:12
> 
> 
> If the video has a pre-merged format, then your original selector will work. You can check in the -F of the videos that used to work whether this is the case. Also, if you think the isue is infact caused by yt-dlp, show verbose logs (as well as -F output) of the same video in both yt-dlp and in youtube-dl

It looks like CW now has separate audio and video tracks. When running yt-dlp -F on the links I provided in my last comment it shows a separate audio track.

I was hoping I could keep a generic "720 video resolution, then 1080, or best video and best audio for whatever video" in that order. I have a different system that will act like an RSS feed for TV shows. From there I can generate a consistent -o format (show name\show name - episode name.extension).

It looks like your recommendation of the -S should work, but I haven't tested it yet.

**Comment by pukkandan** [comment] 2021-08-14 18:02
Please close if your issue is solved

**Closed** 2021-08-16 12:06 UTC
Labels: question
