### ISSUE TITLE
Unable to download video from TikTok, `Error Unable to extract sigi state`

### ISSUE THREAD

**Issue by zulfiqarlaili** [yt-dlp/yt-dlp#9472] opened 2024-03-16 21:34 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Malaysia

### Provide a description that is worded well enough to be understood

I'm unable to download or fetch video data from TikTok. I've updated `yt-dlp` to version `2024.3.10`. I even tried to downgrade to version `2023.12.30` but the issue still happen.

Error
```
[TikTok] Extracting URL: https://www.tiktok.com/@catplanet6/video/7309135341791792426?is_from_webapp=1
[TikTok] 7309135341791792426: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7309135341791792426: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7309135341791792426: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7309135341791792426: Downloading video feed
WARNING: [TikTok] 7309135341791792426: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7309135341791792426: Downloading webpage
ERROR: [TikTok] 7309135341791792426: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.tiktok.com/@catplanet6/video/7309135341791792426\?is_from_webapp\=1\&sender_device\=pc
[debug] Command-line config: ['-vU', 'https://www.tiktok.com/@catplanet6/video/7309135341791792426?is_from_webapp=1&sender_device=pc']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (pip)
[debug] Python 3.11.2 (CPython arm64 64bit) - macOS-14.2.1-arm64-arm-64bit (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-3.43.2, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2024.03.10, Current version: stable@2023.09.24
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[TikTok] Extracting URL: https://www.tiktok.com/@catplanet6/video/7309135341791792426?is_from_webapp=1&sender_device=pc
[TikTok] 7309135341791792426: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7309135341791792426: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7309135341791792426: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7309135341791792426: Downloading video feed
WARNING: [TikTok] 7309135341791792426: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7309135341791792426: Downloading webpage
ERROR: [TikTok] 7309135341791792426: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/Users/J0W432431K/.pyenv/versions/3.11.2/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/J0W432431K/.pyenv/versions/3.11.2/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 700, in _real_extract
    sigi_data = self._get_sigi_state(webpage, video_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/J0W432431K/.pyenv/versions/3.11.2/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 52, in _get_sigi_state
    return self._search_json(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/J0W432431K/.pyenv/versions/3.11.2/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1277, in _search_json
    json_string = self._search_regex(
                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/J0W432431K/.pyenv/versions/3.11.2/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1263, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment] 2024-03-16 21:37
install nightly

if you installed with homebrew:
```
brew uninstall yt-dlp
brew install --HEAD yt-dlp
```

or if you installed with pip:
```
python3 -m pip install -U --pre yt-dlp[default]
```

dupe of pinned issue

**Closed by bashonly** 2024-03-16 21:37 UTC
Labels: duplicate, site-bug, site:tiktok

**Comment by zulfiqarlaili** [comment] 2024-03-17 04:29
Thank you @bashonly 😊
