### ISSUE TITLE
When parameter -N is used, the file modification time can't be set after downloading.

### ISSUE THREAD

**Issue by DCxDESIGN** [yt-dlp/yt-dlp#6995] opened 2023-05-05 15:16 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm using a Windows version of yt-dlp and found that,

- If I use default options to download a video (eg. https://www.youtube.com/watch?v=JJG_Qu41IQw ), the Modification Time of the file should be the uploading time, like this:
![SShot-20230505-230028-explorer](https://user-images.githubusercontent.com/48208459/236495384-146d044c-c594-4082-a937-d85478b83036.png)

- But if I use "-N [x]" to use multiple threads to download the video, the Modification Time won't be set to the uploading time, like this:
![SShot-20230505-230121-explorer](https://user-images.githubusercontent.com/48208459/236495768-e2d6a715-2385-4e69-af0c-e232cf2e8f95.png)

Some other information for your reference:

- When I use "--no-mtime" and other in default, the Modification Time won't be reset. This function works well.
- When I use "-N [x]" and "--mtime", this issue can still be reproduced.
- When I use "--downloader aria2c" and "--mtime", this issue can still be reproduced.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\zc169\Desktop>yt-dlp -vU --proxy http://127.0.0.1:7890 -f 137+140 "https://www.youtube.com/watch?v=JJG_Qu41IQw" -N 16
[debug] Command-line config: ['-vU', '--proxy', 'http://127.0.0.1:7890', '-f', '137+140', 'https://www.youtube.com/watch?v=JJG_Qu41IQw', '-N', '16']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev (setts), ffprobe 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: https://www.youtube.com/watch?v=JJG_Qu41IQw
[youtube] JJG_Qu41IQw: Downloading webpage
[youtube] JJG_Qu41IQw: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] JJG_Qu41IQw: Downloading 1 format(s): 137+140
[debug] Invoking dashsegments downloader on "https://rr2---sn-oguelnze.googlevideo.com/videoplayback?expire=1683321100&ei=rBxVZIztDoWN1d8PqJKlyAg&ip=172.105.232.7&id=o-AD7Pi-Ck9ofFaKMgfdbMLj1cmIZCTg782HfEtRMq1Ecq&itag=137&source=youtube&requiressl=yes&mh=Ty&mm=31%2C29&mn=sn-oguelnze%2Csn-oguesn6d&ms=au%2Crdu&mv=m&mvi=2&pl=21&initcwndbps=112500&spc=qEK7B9kr9iF2i2DtHu0316J6pilfClM&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=14051172&dur=31.080&lmt=1521307590513865&mt=1683299119&fvip=1&keepalive=yes&fexp=24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgTZOPCN5lCRDX5Ipv7vc_nFZXTJUIN6jLggZoaoDyEiECIQDQxQz_sGNlxDisGqK28zWWlS_dSaeBRuZoh5HM4sj-bA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhALEg9YZ86GEPvoc5owLfq3MQsTTQi1cVxywjzk_TZgzTAiEAi9whk0UOdXZu-WNWT51NMwn2I50A3n7XaUT1jXsBPuM%3D"
[dashsegments] Total fragments: 2
[download] Destination: Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].f137.mp4
[debug] File locking is not supported. Proceeding without locking
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100% of   13.40MiB in 00:00:01 at 8.07MiB/s
[debug] Invoking dashsegments downloader on "https://rr2---sn-oguelnze.googlevideo.com/videoplayback?expire=1683321100&ei=rBxVZIztDoWN1d8PqJKlyAg&ip=172.105.232.7&id=o-AD7Pi-Ck9ofFaKMgfdbMLj1cmIZCTg782HfEtRMq1Ecq&itag=140&source=youtube&requiressl=yes&mh=Ty&mm=31%2C29&mn=sn-oguelnze%2Csn-oguesn6d&ms=au%2Crdu&mv=m&mvi=2&pl=21&initcwndbps=112500&spc=qEK7B9kr9iF2i2DtHu0316J6pilfClM&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=495272&dur=31.137&lmt=1521307522919898&mt=1683299119&fvip=1&keepalive=yes&fexp=24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgZ3KMPjatyasmzDjgdOgwK0cdGQG78gxwLK8TxG5N-B8CIGBWyLOFMw6df6ny6rg2WqE44TJLucYtoG1uhSua5dMP&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhALEg9YZ86GEPvoc5owLfq3MQsTTQi1cVxywjzk_TZgzTAiEAi9whk0UOdXZu-WNWT51NMwn2I50A3n7XaUT1jXsBPuM%3D"
[dashsegments] Total fragments: 1
[download] Destination: Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].f140.m4a
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100% of  483.66KiB in 00:00:00 at 569.82KiB/s
[Merger] Merging formats into "Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].f137.mp4" -i "file:Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].f140.m4a" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].temp.mp4"
Deleting original file Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].f140.m4a (pass -k to keep)
Deleting original file Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].f137.mp4 (pass -k to keep)

C:\Users\zc169\Desktop>yt-dlp -vU --proxy http://127.0.0.1:7890 -f 137+140 "https://www.youtube.com/watch?v=JJG_Qu41IQw"
[debug] Command-line config: ['-vU', '--proxy', 'http://127.0.0.1:7890', '-f', '137+140', 'https://www.youtube.com/watch?v=JJG_Qu41IQw']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev (setts), ffprobe 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: https://www.youtube.com/watch?v=JJG_Qu41IQw
[youtube] JJG_Qu41IQw: Downloading webpage
[youtube] JJG_Qu41IQw: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] JJG_Qu41IQw: Downloading 1 format(s): 137+140
[debug] Invoking dashsegments downloader on "https://rr2---sn-oguelnze.googlevideo.com/videoplayback?expire=1683321176&ei=-BxVZOKVFrKV1d8PjMSxsAk&ip=172.105.232.7&id=o-ANOf8aO-S23HMu6kcOkjHSHySJraLKWK-TNo06mJ2E2_&itag=137&source=youtube&requiressl=yes&mh=Ty&mm=31%2C29&mn=sn-oguelnze%2Csn-oguesn6d&ms=au%2Crdu&mv=m&mvi=2&pl=21&initcwndbps=132500&spc=qEK7B3RYJ5_rzg4DDmUVgR4Yq2Va5Jo&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=14051172&dur=31.080&lmt=1521307590513865&mt=1683299119&fvip=1&keepalive=yes&fexp=24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIubhdhGRac7sYD_r3USuSVEiMsdXOqFJuQuZKbo7Af2AiAzFhLIq1tEppB-VYj9RetXsOchlhBiFZrZLLBqCDEexw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAL9nibr4IdDkE5mFjY05RNSeyuMTcwLROz_lpuo8LEnmAiEA1vx5Rf-En5DJWSB9JoBKuX0RSN1t9cxERAC35ixgBJc%3D"
[dashsegments] Total fragments: 2
[download] Destination: Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].f137.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of   13.40MiB in 00:00:03 at 4.35MiB/s
[debug] Invoking dashsegments downloader on "https://rr2---sn-oguelnze.googlevideo.com/videoplayback?expire=1683321176&ei=-BxVZOKVFrKV1d8PjMSxsAk&ip=172.105.232.7&id=o-ANOf8aO-S23HMu6kcOkjHSHySJraLKWK-TNo06mJ2E2_&itag=140&source=youtube&requiressl=yes&mh=Ty&mm=31%2C29&mn=sn-oguelnze%2Csn-oguesn6d&ms=au%2Crdu&mv=m&mvi=2&pl=21&initcwndbps=132500&spc=qEK7B3RYJ5_rzg4DDmUVgR4Yq2Va5Jo&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=495272&dur=31.137&lmt=1521307522919898&mt=1683299119&fvip=1&keepalive=yes&fexp=24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOjPnt2MY6ZeEuwxihobatsUCpISvQebnEwsAWMhukY-AiA6I195eQjhmf_r6FDuFWhuUuBbSo9FEgwQVxCVUMcQ-Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAL9nibr4IdDkE5mFjY05RNSeyuMTcwLROz_lpuo8LEnmAiEA1vx5Rf-En5DJWSB9JoBKuX0RSN1t9cxERAC35ixgBJc%3D"
[dashsegments] Total fragments: 1
[download] Destination: Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].f140.m4a
[download] 100% of  483.66KiB in 00:00:00 at 487.21KiB/s
[Merger] Merging formats into "Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].f137.mp4" -i "file:Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].f140.m4a" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].temp.mp4"
Deleting original file Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].f140.m4a (pass -k to keep)
Deleting original file Queen Elizabeth II Officially Opens The London 2012 Olympics - Opening Ceremony [JJG_Qu41IQw].f137.mp4 (pass -k to keep)
```

**Comment by bashonly** [comment] 2023-05-05 15:20
Duplicate of #5522

Related #3224

**Closed by bashonly** 2023-05-05 15:20 UTC
Labels: bug, triage
