### ISSUE TITLE
Consider extending the information shown on the commandline when the main video (larger video) can not be downloaded and instead some smaller video is downloaded on e. g. redtube or other websites that show a similar problem

### ISSUE THREAD

**Issue by rubyFeedback** [yt-dlp/yt-dlp#8324] opened 2023-10-11 00:30 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.07** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

So I am using yt-dlp and for youtube it works very well.

However had, on other websites there are some issues. For instance, on redtube (you know, that site for ... educational content and stuff), I consistently now seem to get just a tiny ~9 seconds download of an intro but the main video is not downloaded. Using an extension like Video downloader in chrome also does not show the URL; or it shows a "Forbidden" entry. Ok this is mostly the status quo.

At the same time I know that there has to be a way that I can view the video as-is, because it plays in my browser (thorium, which is based on chrome) just fine. Yet I can not get yt-dlp to download the main file directly.

On the issue tracker there are various older reports where people recommend one to run yt-dlp via:

    -vU

I tried this. Unfortunately that did not really give me a lot of useful information.

I am not going to provide a specific URL ... can't reveal that educational purpose as-is, but it affects
pretty much any video on redtube for me.

So here is the slightly modified output:

    [debug] Command-line config: ['-vU', 'https://www.redtube.com/SOME_NUMBER_HERE']
    [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
    [debug] yt-dlp version stable@2023.10.07 [377e85a17]
    [debug] Lazy loading extractors is disabled
    [debug] Python 3.12.0 (CPython x86_64 64bit) - Linux-6.1.38-1-MANJARO-x86_64-with-glibc2.37 (OpenSSL 3.1.1 30 May 2023, glibc 2.37)
    [debug] exe versions: ffmpeg N-112362-g4c422de1db (fdk,setts), ffprobe N-112362-g4c422de1db, rtmpdump 2.4
    [debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.43.2, websockets-11.0.3
    [debug] Proxy map: {}
    [debug] Loaded 1886 extractors
    [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
    Available version: stable@2023.10.07, Current version: stable@2023.10.07
    yt-dlp is up to date (stable@2023.10.07)
    [RedTube] Extracting URL: https://www.redtube.com/SOME_NUMBER_HERE
    [RedTube] SOME_NUMBER_HERE: Downloading webpage
    [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
    [debug] Default format spec: bestvideo*+bestaudio/best
    [info] SOME_NUMBER_HERE: Downloading 1 format(s): 0
    [debug] Invoking http downloader on "data:image/gif;base64,<data>"
    [download] Destination: A famous person tries to do something legendary really [SOME_NUMBER_HERE].mp4
    [download] 100% of     42.00B in 00:00:00 at 30.33KiB/s

The thing is that this does not really tell me much at all.

So now comes my feature request:

Would it be possible for yt-dlp to give more information in such an event?

For instance, the download is only of a 9 seconds video rather than, say, 10 minutes.
So I seem to only be able to download that small video (like a decoy).

Perhaps yt-dlp could show one or two sentences about this; ideally also how to work
around this IF a solution exists. Not everyone will scan through old issues to find
out how to solve stuff. Right now I also don't know the reason; I assume the remote
server somehow blocks yt-dlp, but the video is being played in the browser, so data
**must** have been transferred. Perhaps other useful information could be shown
here too; I may not be the only one to struggle with this.

In general I think yt-dlp is awesome and I'd love to see it become more of a general
downloader of multimedia files, not just from youtube. For youtube it works very
well but so many other websites probably use a similar restriction (e. g. the
"Forbidden" stuff) and I'd love to just use one tool (yt-dlp) for the job. Interestingly
yt-dlp also works for videos on youtube where one has to log in normally, so perhaps
that code can also be extended towards what other websites use (I really don't know
how that block works, I need to research this eventually since I keep on running into
that issue).

At any rate, please feel free to ignore this issue if it is not applicable.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
No.
```

**Comment by gamer191** [comment] 2023-10-13 00:35
yt-dlp is already a general video/audio downloader, which supports over 1000 websites (admittedly most of them are broken, because websites change so often)
I can narrow down your issue into 2 problems:
1. yt-dlp should give a warning for tiny downloads (42 bytes in your example log)
2. the redtube extractor is broken and downloads the wrong video

It should be noted that yt-dlp does not support piracy sites. However, it seems like redtube is not a piracy site, it's just nsfw and hence you didn

**Comment by gamer191** [comment] 2023-10-13 00:39
Sorry, I accidentally clicked "send" too early. Please refer to https://github.com/yt-dlp/yt-dlp/issues/8324 to see my full message

**Comment by bashonly** [comment] 2023-10-13 04:53
This looks like an extractor bug, but we cannot be sure, because:

> I am not going to provide a specific URL 

Without this and an unedited verbose log, nothing can be fixed or improved

**Comment by gamer191** [comment] 2023-10-13 10:30
Duplicate of #7659

**Closed by gamer191** 2023-10-13 10:30 UTC
Labels: incomplete, NSFW
