### ISSUE TITLE
BBC Archive

### ISSUE THREAD

**Issue by DavidCWGA** [yt-dlp/yt-dlp#5281] opened 2022-10-18 22:54 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Provide a description that is worded well enough to be understood

BBC Archive URLs return the following error:

`ERROR: the JSON object must be str, bytes or bytearray, not dict`

Example URL: https://www.bbc.co.uk/archive/church-mill-stream-olney-interlude/zj3bpg8

Example playlist URL: https://www.bbc.co.uk/archive/interludes/zjkk382

I don't know if this is related to #4389 or not.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.bbc.co.uk/archive/church-mill-stream-olney-interlude/zj3bpg8']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (zip)
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.0-18-amd64-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [bbc] Extracting URL: https://www.bbc.co.uk/archive/church-mill-stream-olney-interlude/zj3bpg8
[bbc] zj3bpg8: Downloading webpage
ERROR: the JSON object must be str, bytes or bytearray, not dict
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1553, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/bbc.py", line 1190, in _real_extract
    initial_data = self._parse_json(initial_data, playlist_id, fatal=False)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 976, in _parse_json
    return json.loads(
  File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
```

**Comment by pukkandan** [comment] 2022-10-19 07:04
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/4313

**Closed by pukkandan** 2022-10-19 07:04 UTC
Labels: site-bug, triage
