### ISSUE TITLE
tiktok

### ISSUE THREAD

**Issue by aliafshany** [yt-dlp/yt-dlp#2150] opened 2021-12-28 17:11 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

yt-dlp -F https://vm.tiktok.com/ZSeueTL1n/
[generic] ZSeueTL1n: Requesting header
[redirect] Following redirect to https://www.tiktok.com/@noemihopperr/video/7045381038062783750?_d=secCgwIARCbDRjEFSADKAESPgo8gulJxcsglFLUxxMGMV8DCG0lYSCSLHYG5YCMnujvpgkguhuNLBgx5%2FjOQSzNecUPHmDRZAPki3lklUl7GgA%3D&language=en&preview_pb=0&sec_user_id=MS4wLjABAAAAnt-u0B_4XszFL5zFGFtlNSOCZEHTL5MHX6IjSKpSpEamsrov0OWj2xJ2H_Jg9upz&share_app_id=1233&share_item_id=7045381038062783750&share_link_id=ab8b0274-fb22-41ff-8a76-fc96bbbd1924&source=h5_m&timestamp=1640668038&u_code=d225ebal7b93cb&user_id=6598440820873363461&utm_campaign=client_share&utm_medium=android&utm_source=copy&_r=1
[TikTok] 7045381038062783750: Downloading video details
WARNING: [TikTok] 7045381038062783750: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; Retrying with webpage
[TikTok] 7045381038062783750: Downloading webpage
[TikTok] 7045381038062783750: Downloading video webpage
ERROR: [TikTok] 7045381038062783750: Unable to extract json_string; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
afshany@Afshanys-MacBook-Pro ~ % yt-dlp --version
2021.12.27

### Verbose log

```shell
yt-dlp -Uv yt-dlp -F https://vm.tiktok.com/ZSeueTL1n/
[debug] Command-line config: ['-Uv', 'yt-dlp', '-F', 'https://vm.tiktok.com/ZSeueTL1n/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.9.9 (CPython 64bit) - macOS-11.6.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: yt-dlp
ERROR: [generic] 'yt-dlp' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:yt-dlp" ) to search YouTube
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 2558, in _real_extract
    raise ExtractorError(

[debug] [generic] Extracting URL: https://vm.tiktok.com/ZSeueTL1n/
[generic] ZSeueTL1n: Requesting header
[redirect] Following redirect to https://www.tiktok.com/@noemihopperr/video/7045381038062783750?_d=secCgwIARCbDRjEFSADKAESPgo8gulJxcsglFLUxxMGMV8DCG0lYSCSLHYG5YCMnujvpgkguhuNLBgx5%2FjOQSzNecUPHmDRZAPki3lklUl7GgA%3D&language=en&preview_pb=0&sec_user_id=MS4wLjABAAAAnt-u0B_4XszFL5zFGFtlNSOCZEHTL5MHX6IjSKpSpEamsrov0OWj2xJ2H_Jg9upz&share_app_id=1233&share_item_id=7045381038062783750&share_link_id=ab8b0274-fb22-41ff-8a76-fc96bbbd1924&source=h5_m&timestamp=1640668038&u_code=d225ebal7b93cb&user_id=6598440820873363461&utm_campaign=client_share&utm_medium=android&utm_source=copy&_r=1
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@noemihopperr/video/7045381038062783750?_d=secCgwIARCbDRjEFSADKAESPgo8gulJxcsglFLUxxMGMV8DCG0lYSCSLHYG5YCMnujvpgkguhuNLBgx5%2FjOQSzNecUPHmDRZAPki3lklUl7GgA%3D&language=en&preview_pb=0&sec_user_id=MS4wLjABAAAAnt-u0B_4XszFL5zFGFtlNSOCZEHTL5MHX6IjSKpSpEamsrov0OWj2xJ2H_Jg9upz&share_app_id=1233&share_item_id=7045381038062783750&share_link_id=ab8b0274-fb22-41ff-8a76-fc96bbbd1924&source=h5_m&timestamp=1640668038&u_code=d225ebal7b93cb&user_id=6598440820873363461&utm_campaign=client_share&utm_medium=android&utm_source=copy&_r=1
[TikTok] 7045381038062783750: Downloading video details
WARNING: [TikTok] 7045381038062783750: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; Retrying with webpage
[TikTok] 7045381038062783750: Downloading webpage
[TikTok] 7045381038062783750: Downloading video webpage
ERROR: [TikTok] 7045381038062783750: Unable to extract json_string; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.9/site-packages/yt_dlp/extractor/tiktok.py", line 368, in _real_extract
    json_string = self._search_regex(
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1173, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by pukkandan** [comment] 2021-12-28 18:31
Duplicate of #2133

**Closed by pukkandan** 2021-12-28 18:31 UTC
Labels: duplicate, site-bug, site:tiktok
