### ISSUE TITLE
RTSP URL Extraction?

### ISSUE THREAD

**Issue by HowToYoutubeViews** [yt-dlp/yt-dlp#647] opened 2021-08-07 23:52 UTC
Sup guys,
_nice job really appreciate your efforts to keep posting this all the time!_
Well I was wondering if somehow youtube discontinued the "RTSP" '3GP' URLs from the mobile useragent requests.

Since I have build an app which plays youtube videos _(I don't want to use VLC so I build my own rtsp request)_ but after couple of weeks I came back to play with this app again after some time,  my request can not find any "**RTSP**" stream URL "m.youtube.com .... ONLY some links like [this:](https://r2---sn-a0jpm-a0ms.googlevideo.com/videoplayback?expire=1628398478&ei=Lg8PYcmWHYyz7gO2vrioCA&ip=193.23.245.81&id=o-AGU6rd2F-93i69Dd7Sw5rucdthIVZT2vO4-H1XZq22L3&itag=22&source=youtube&requiressl=yes&vprv=1&mime=video%2Fmp4&ns=8l217fsNQ7cjXCZR4cUgxm4G&cnr=14&ratebypass=yes&dur=525.328&lmt=1604367838128924&fexp=24001373,24007246&c=MWEB&txp=5535432&n=W4tyP80nkC472OY&sparams=expire,ei,ip,id,itag,source,requiressl,vprv,mime,ns,cnr,ratebypass,dur,lmt&sig=AOq0QJ8wRgIhAJqqrUepwIbCspoczuAg7A_ZSBhAIh_cT0gtVoHJu6koAiEA11Zf2sMAoUX-Ipq-Sgb0GplopPE-aBCaRcS0aNjvVrc%3D&redirect_counter=1&rm=sn-5hneld7l&req_id=c21ffd235841a3ee&cms_redirect=yes&ipbypass=yes&mh=Wd&mip=92.223.89.208&mm=31&mn=sn-a0jpm-a0ms&ms=au&mt=1628379903&mv=m&mvi=2&pcm2cms=yes&pl=24&lsparams=ipbypass,mh,mip,mm,mn,ms,mv,mvi,pcm2cms,pl&lsig=AG3C_xAwRQIhAPY0Q8UBq4kcHbLL7tjfIQ7MZxOYu5G0tzpD3ZnI7mpJAiAopIqkQDxRrNCm5wtSrG5miMtFUg5P_fqnRj6KgwxL4Q%3D%3D) can be retrieved but it will be useless for me since my RTSP viewer doesn't know to play this url link which is HTTPS instead of RTSP.

any suggestion I really appreciate!

**Comment by pukkandan** [comment] 2021-08-08 03:24
Duplicate of #649

**Closed by pukkandan** 2021-08-08 03:24 UTC
Labels: question
