### ISSUE TITLE
Ceska Televize broken support

### ISSUE THREAD

**Issue by Slavomir9** [yt-dlp/yt-dlp#7301] opened 2023-06-13 08:55 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Czech Republic

### Provide a description that is worded well enough to be understood

Hello,
can you please update this app for support download Ceska Televize?
Video examples:
https://www.ceskatelevize.cz/porady/25025-cina-dneska/

https://ct24.ceskatelevize.cz/ekonomika/3593025-inflace-bude-brzy-jednociferna-veri-mateju-z-cnb-dalsi-odbornici-vsak-maji-obavy)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp https://ct24.ceskatelevize.cz/ekonomika/3593025-inflace-bude-brzy-jednociferna-veri-mateju-z-cnb-dalsi-odbornici-vsak-maji-obavy
[generic] Extracting URL: https://ct24.ceskatelevize.cz/ekonomika/3593025-inflace-bude-brzy-jednociferna-veri-mateju-z-cnb-...nici-vsak-maji-obavy
[generic] 3593025-inflace-bude-brzy-jednociferna-veri-mateju-z-cnb-dalsi-odbornici-vsak-maji-obavy: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 3593025-inflace-bude-brzy-jednociferna-veri-mateju-z-cnb-dalsi-odbornici-vsak-maji-obavy: Extracting information
ERROR: Unsupported URL: https://ct24.ceskatelevize.cz/ekonomika/3593025-inflace-bude-brzy-jednociferna-veri-mateju-z-cnb-dalsi-odbornici-vsak-maji-obavy
```

**Comment by bashonly** [comment] 2023-06-13 09:36
Duplicate of #6539

**Closed by bashonly** 2023-06-13 09:36 UTC
Labels: site-bug, triage
