### ISSUE TITLE
Instagram: Unable to extract username

### ISSUE THREAD

**Issue by SubZero5** [yt-dlp/yt-dlp#8048] opened 2023-09-07 06:30 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Turkey

### Provide a description that is worded well enough to be understood

WARNING: [Instagram] unable to extract username
ERROR: [Instagram] Cw1yI2_SmQf: Unable to extract video url

Note: Other URLs seems to work fine though...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\X\Downloads>yt-dlp..exe -vU https://www.instagram.com/reel/Cw1yI2_SmQf/
[debug] Command-line config: ['-vU', 'https://www.instagram.com/reel/Cw1yI2_SmQf/']
[debug] Encodings: locale cp1254, fs utf-8, pref cp1254, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.22.185234 [f780bb52b] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1857 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.22.185234
Current Build Hash: 9cb23e2fd45fc307c6ebe0d477539fdd760e06fe1703d2289acab103106ef2a7
yt-dlp is up to date (stable@2023.07.22.185234)
[Instagram] Extracting URL: https://www.instagram.com/reel/Cw1yI2_SmQf/
[Instagram] Cw1yI2_SmQf: Setting up session
[Instagram] Cw1yI2_SmQf: Downloading JSON metadata
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] Cw1yI2_SmQf: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\instagram.py", line 486, in _real_extract
  File "yt_dlp\extractor\common.py", line 1406, in _og_search_video_url
  File "yt_dlp\extractor\common.py", line 1299, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1263, in _search_regex


C:\Users\X\Downloads>
```

**Comment by bashonly** [comment] 2023-09-07 07:05
Duplicate of #5967

**Closed by bashonly** 2023-09-07 07:05 UTC
Labels: duplicate, site-bug, site:instagram
