### ISSUE TITLE
[YouTube] Urlopen error timed out

### ISSUE THREAD

**Issue by user7230724** [yt-dlp/yt-dlp#6153] opened 2023-02-04 07:41 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

The video is unrestricted.

### Provide a description that is worded well enough to be understood

Some videos from YouTube cannot be downloaded due to the unavailability of the server https://rr1---sn-8p2hvcpax-cxbl.googlevideo.com/ (which is globally unavailable according to the https://downforeveryoneorjustme.com/). The videos play properly in the browser. When inspecting the network log, we observe that the same server is attempted first in the browser, but after it fails, the next available server is chosen: https://rr3---sn-nv47znel.googlevideo.com/ which works properly. Yt-dlp should use the fallback server as well.

None of these alternatives helped: using cookies, passing `-4` or `-6` flags, disabling cache directory, increasing retries number, increasing fragment retries number, trying on a different operating system (Ubuntu), testing other formats.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

Note 1: we use format 248, just to show that this is not a duplicate of #3372. None of the formats work for this video.

Note 2: we removed the ip address from the URL for privacy reasons.

```txt
[debug] Command-line config: ['-vU', '-f', '248', 'OfFRALj2ShA']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19043-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[youtube] Extracting URL: OfFRALj2ShA
[youtube] OfFRALj2ShA: Downloading webpage
[youtube] OfFRALj2ShA: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] OfFRALj2ShA: Downloading 1 format(s): 248
[debug] Invoking http downloader on "https://rr1---sn-8p2hvcpax-cxbl.googlevideo.com/videoplayback?expire=1675517744&ei=0AreY4WmMI671wLy57zQCg&id=o-AASPZuBt_qxSJW24VpsiBxXgFHdhK3vEbKUak1qXXfIY&itag=248&source=youtube&requiressl=yes&mh=Z1&mm=31%2C29&mn=sn-8p2hvcpax-cxbl%2Csn-nv47ln7z&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=431250&spc=H3gIhtr-gazZzIDs1m35wEAryeBTYAE&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=61354041&dur=186.219&lmt=1542409538262194&mt=1675495748&fvip=4&keepalive=yes&fexp=24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOTNJ9xL5fnw7qG8MM8JQ8oLRvwF6VN4KJBhqK6qNVWlAiEA9TKzsVgN29jA7i9w4TT9df1Zc-BTdWZ9EPf0csY-6BA%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALy37CdIFE7HE4R7l3cRIyG6GFXGnjRJgk8G0VL6ibB5AiBEYam5EUgu0lxS7Vb9g-9cuFyM6KdTkJZP0zHsRtvbeA%3D%3D"
[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (2/10)...
[download] Got error: <urlopen error timed out>. Retrying (3/10)...
[download] Got error: <urlopen error timed out>. Retrying (4/10)...
[download] Got error: <urlopen error timed out>. Retrying (5/10)...
[download] Got error: <urlopen error timed out>. Retrying (6/10)...
[download] Got error: <urlopen error timed out>. Retrying (7/10)...
[download] Got error: <urlopen error timed out>. Retrying (8/10)...
[download] Got error: <urlopen error timed out>. Retrying (9/10)...
[download] Got error: <urlopen error timed out>. Retrying (10/10)...
[download] Got error: <urlopen error timed out>. Giving up after 10 retries
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 970, in main
  File "yt_dlp\__init__.py", line 960, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3358, in download
  File "yt_dlp\YoutubeDL.py", line 3333, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1491, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1599, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1658, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2772, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3236, in process_info
  File "yt_dlp\YoutubeDL.py", line 2959, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\http.py", line 369, in real_download
  File "yt_dlp\utils.py", line 6023, in __iter__
  File "yt_dlp\downloader\common.py", line 389, in report_retry
  File "yt_dlp\utils.py", line 6030, in report_retry
  File "yt_dlp\downloader\common.py", line 392, in <lambda>
  File "yt_dlp\YoutubeDL.py", line 1012, in report_error
  File "yt_dlp\YoutubeDL.py", line 941, in trouble
```

**Comment by gamer191** [comment] 2023-02-04 09:26
duplicate of https://github.com/yt-dlp/yt-dlp/issues/1986

**Closed by gamer191** 2023-02-04 09:26 UTC
Labels: site-bug, triage

**Comment by gamer191** [comment] 2023-02-04 09:30
Also, both websites are down, according to that website. I assume that CDN's will alwaysappear to be down, since they don't have a homepage (there's probably a more technical term, but that will do)
