### ISSUE TITLE
[DiscoveryPlus] videos that require a subscription not working

### ISSUE THREAD

**Issue by nmills3** [yt-dlp/yt-dlp#2529] opened 2022-01-29 00:11 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Description

When trying to download shows on DiscoveryPlus i'm getting the following error message 
`[DiscoveryPlus] how-its-made/paving-asphaltmarshmallow-cookiesloudspeakers: This video is only available for registered users. You may want to use --cookies.`
I can confirm that i am using cookies and have tried the solutions in the similar issue #2233 with no success. My account is registered and i've tried both the --cookies flag and the --cookies from browser flag to get cookies and got the same result with both

### Verbose log

```shell
[debug] Command-line config: ['--cookies-from-browser', 'chrome', 'https://www.discoveryplus.com/gb/video/how-its-made/paving-asphaltmarshmallow-cookiesloudspeakers', '-vU']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\nicho\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[Cookies] Extracted 3216 cookies from chrome
[debug] cookie version breakdown: {'v10': 3216, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/gb/video/how-its-made/paving-asphaltmarshmallow-cookiesloudspeakers
[debug] Using fake IP 6.144.112.199 (US) as X-Forwarded-For
[DiscoveryPlus] how-its-made/paving-asphaltmarshmallow-cookiesloudspeakers: Downloading JSON metadata
ERROR: [DiscoveryPlus] how-its-made/paving-asphaltmarshmallow-cookiesloudspeakers: This video is only available for registered users. You may want to use --cookies.
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\dplay.py", line 369, in _real_extract
  File "yt_dlp\extractor\dplay.py", line 92, in _get_disco_api_info
  File "yt_dlp\extractor\dplay.py", line 50, in _process_errors
```

**Comment by pukkandan** [comment] 2022-01-29 00:35
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2138

**Closed by pukkandan** 2022-01-29 00:35 UTC
Labels: site-bug, triage
