### ISSUE TITLE
 <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>

### ISSUE THREAD

**Issue by gaicihui** [yt-dlp/yt-dlp#3034] opened 2022-03-11 13:01 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I don't know why ？how about that？what should I do？

### Verbose log

```shell
D:\download YTB world and part video>yt-dlp.exe --merge-output-format mp4 https://www.youtube.com/watch?v=LFOx-vmYrts
[youtube] LFOx-vmYrts: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>
[youtube] LFOx-vmYrts: Downloading android player API JSON
WARNING: [youtube] <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>. Retrying ...
[youtube] LFOx-vmYrts: Downloading android player API JSON (retry #1)
WARNING: [youtube] <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>. Retrying ...
[youtube] LFOx-vmYrts: Downloading android player API JSON (retry #2)
WARNING: [youtube] <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>. Retrying ...
[youtube] LFOx-vmYrts: Downloading android player API JSON (retry #3)
[youtube] LFOx-vmYrts: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>
[youtube] LFOx-vmYrts: Downloading web player API JSON
WARNING: [youtube] <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>. Retrying ...
[youtube] LFOx-vmYrts: Downloading web player API JSON (retry #1)
WARNING: [youtube] Unable to download API page: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = aElexTuk3e6BnRHmC ; player = None
Cannot decrypt nsig without player_url; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = JRHhCJNKQa3xyRc6n ; player = None
Cannot decrypt nsig without player_url; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
[youtube] LFOx-vmYrts: Downloading initial data API JSON
[info] LFOx-vmYrts: Downloading 1 format(s): 315+251
Deleting existing file C:\Users\Administrator\Downloads\Nomadic Ambience\Walking in the Rain, Zermatt Switzerland and Mattervispa, Rain and City Sounds-3840x2160.webp
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: C:\Users\Administrator\Downloads\Nomadic Ambience\Walking in the Rain, Zermatt Switzerland and Mattervispa, Rain and City Sounds-3840x2160.webp
[SubtitlesConvertor] There aren't any subtitles to convert
[download] Resuming download at byte 50529485
ERROR: unable to download video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>
```

**Comment by coletdjnz** [comment] 2022-03-12 05:40
Some sort of connection issue, probably on your end given that it's happening to every request. If it's still happening, please post a verbose log (i.e. with `-v` or `--verbose`)

**Comment by gaicihui** [comment] 2022-03-12 06:43
> 某种连接问题，可能在您的最后，因为它几乎发生在每个请求中。如果它仍然发生，请发布详细日志（即使用`-v`or `--verbose`）

D:\download YTB world and part video>yt-dlp.exe  https://youtu.be/uUR4020kmrs -v
[debug] Command-line config: ['https://youtu.be/uUR4020kmrs', '-v']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, err utf-8, pref cp936
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg N-105896-ga0724328a8-20220311 (setts), ffprobe N-105896-ga0724328a8-20220311
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {'http': 'http://127.0.0.1:10809', 'https': 'https://127.0.0.1:10809', 'ftp': 'ftp://127.0.0.1:10809'}
[debug] [youtube] Extracting URL: https://youtu.be/uUR4020kmrs
[youtube] uUR4020kmrs: Downloading webpage
[youtube] uUR4020kmrs: Downloading android player API JSON
WARNING: [youtube] <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>. Retrying ...
[youtube] uUR4020kmrs: Downloading android player API JSON (retry #1)
WARNING: [youtube] <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>. Retrying ...
[youtube] uUR4020kmrs: Downloading android player API JSON (retry #2)
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] uUR4020kmrs: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://rr2---sn-ipoxu-un5d.googlevideo.com/videoplayback?expire=1647088822&ei=VkAsYuL9OMaCvcAPzqyCsAU&ip=111.249.218.149&id=o-AA8ZUg4G2-OGBQU8-shCxO6EZgGf6ipV6APwClKB7s7O&itag=248&source=youtube&requiressl=yes&mh=hN&mm=31%2C26&mn=sn-ipoxu-un5d%2Csn-oguesnzz&ms=au%2Conr&mv=m&mvi=2&pl=25&initcwndbps=702500&vprv=1&mime=video%2Fwebm&gir=yes&clen=264189092&dur=3264.127&lmt=1625016480505398&mt=1647066778&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgKxWDXNBCBz1QK_PdMR7ZnvERH_88sZp1nSHmnzJr9vACIQDPnflNoJgvun_w67DTBc4L0psJ_d3hKBFL06ooXdj1XQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANMqCK1aRH0WPK2XrJ5GpBUzsTJ6Y5CE1RID31_SDnshAiAVRuiRBlNjMOjIf8cffRGJqDhBK-PqvZvh2ZqzM3Xfxw%3D%3D"
[download] Destination: Night walks on the rooftops ~ lofi _ relax _ stress relief [uUR4020kmrs].f248.webm
[download]  73.5% of 251.95MiB at  5.75MiB/s ETA 00:11ERROR: unable to download video data: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>
Traceback (most recent call last):
  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1421, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3110, in process_info
  File "yt_dlp\YoutubeDL.py", line 2835, in dl
  File "yt_dlp\downloader\common.py", line 453, in download
  File "yt_dlp\downloader\http.py", line 383, in real_download
  File "yt_dlp\downloader\http.py", line 135, in establish_connection
  File "yt_dlp\downloader\http.py", line 129, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3591, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1524, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>

**Comment by coletdjnz** [comment] 2022-03-12 08:21
Yeah, I am pretty sure this is an issue on your end. If your internet is fine, it is probably the proxy you are using. Try another proxy server maybe?

Since you can partially get through the download, a workaround  could be to add `--extractor-retries 20` and keep running the command again until it finished. Not ideal, though.

---
For devs:
Should we look into supporting retries on this type of error? Seems to be something that many have run into on unstable connections (see upstream), and as seen here retrying may help. Of course, doesn't help if the issue is server side (e.g. https://github.com/yt-dlp/yt-dlp/issues/1307). 

Somewhat related: #2969

**Comment by pukkandan** [comment] 2022-03-13 21:19
> Should we look into supporting retries on this type of error? Seems to be something that many have run into on unstable connections 

We can track this in #3056

Closing this, since a retry should fix the issue

**Closed by pukkandan** 2022-03-13 21:19 UTC
Labels: cant reproduce, external issue
