### ISSUE TITLE
Can we have an option to log/archive failed downloads?

### ISSUE THREAD

**Issue by cxr6548** [yt-dlp/yt-dlp#5723] opened 2022-12-06 02:26 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

My use cases mostly involve downloading mass quantities of videos. Occasionally only one or a handful of videos will fail to download for one reason or another, most often in my case because the filename is too long.

Working with the output and/or logs can be a bit of a handful. What I'd really like is another command switch like `--failed-download-archive <filename.txt>` that only records failures for later review.

I cannot find an example to show off at the moment. It's very intermittent and I've manually intervened in the past so I don't know which of my videos were affected. 

I'm aware that using `%(title).ns` is a solution for the particular problem above.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment] 2022-12-06 09:23
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1761. Also see https://github.com/yt-dlp/yt-dlp/issues/3605#issuecomment-1114269461

**Closed by pukkandan** 2022-12-06 09:23 UTC
Labels: enhancement, triage
