### ISSUE TITLE
404 on Youtube specified video

### ISSUE THREAD

**Issue by scegg** [yt-dlp/yt-dlp#7552] opened 2023-07-09 01:38 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Hongkong

### Provide a description that is worded well enough to be understood

Link: https://www.youtube.com/watch?v=Um4ocHSusVE

This can be played here without problem.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.youtube.com/watch?v=Um4ocHSusVE
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=Um4ocHSusVE']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.2.0-1005-azure-x86_64-with-glibc2.37 (OpenSSL 3.1.1 30 May 2023, glibc 2.37)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 0556fff82db6c942a5dfbb9583e2896013847b28b95186b3800f730a8d5e0c0a
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=Um4ocHSusVE
[youtube] Um4ocHSusVE: Downloading webpage
[youtube] Um4ocHSusVE: Downloading ios player API JSON
[youtube] Um4ocHSusVE: Downloading android player API JSON
[youtube] Um4ocHSusVE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Um4ocHSusVE: Downloading 1 format(s): 616+251
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1688888243/ei/Uw-qZLalFOWG1d8PtpO3kA4/ip/20.205.110.174/id/526e287074aeb151/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D381544843%3Bdur%3D976.642%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1688861820379838/hls_chunk_host/rr4---sn-i3b7knzs.googlevideo.com/mh/OW/mm/31,29/mn/sn-i3b7knzs,sn-i3belnl7/ms/au,rdu/mv/m/mvi/4/pl/21/initcwndbps/4090000/vprv/1/playlist_type/DVR/dover/13/txp/3308224/mt/1688866151/fvip/1/short_key/1/keepalive/yes/fexp/24007246/beids/24350017/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,vprv,playlist_type/sig/AOq0QJ8wRQIgc8p0aJLobX8_3ToEzHqUmVNv9twkdIunZUYHepM1I1MCIQD5OVLzFXhP9MdJU246x6GubOG48ZnjCLv-GVUgXwR-_w%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRQIgeaH0NHPlEaGiyyhrn51tJqGQJmskaFtPqQCz5LLMdU0CIQD3wClevIEkcabOj_9RTooAKEpgXAW9Yghsndu6eHkSLg%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 3345, in process_info
  File "yt_dlp/YoutubeDL.py", line 3084, in dl
  File "yt_dlp/downloader/common.py", line 461, in download
  File "yt_dlp/downloader/hls.py", line 77, in real_download
  File "yt_dlp/YoutubeDL.py", line 3863, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 634, in http_response
  File "urllib/request.py", line 563, in error
  File "urllib/request.py", line 496, in _call_chain
  File "urllib/request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by bashonly** [comment] 2023-07-09 03:00
For newly uploaded videos, format 616 may not have finished processing yet, even though Youtube lists that it is available. You can add `--check-formats` to your command when downloading new videos if you want yt-dlp to select the next best quality when 616 is not yet available

Btw 616 seems to available now

Duplicate of #7510

**Closed** 2023-07-09 03:00 UTC
Labels: duplicate, cant-reproduce, site-bug

**Comment by Fribb** [comment] 2023-07-25 08:08
I have had this issue for a few weeks now but only for one particular channel and not for all their videos. But I can't get the video to download in "good" quality.

When I list the available formats:

```
[youtube] Extracting URL: https://www.youtube.com/watch?v=xGx2aHeSG48
[youtube] xGx2aHeSG48: Downloading webpage
[youtube] xGx2aHeSG48: Downloading ios player API JSON
[youtube] xGx2aHeSG48: Downloading android player API JSON
[youtube] xGx2aHeSG48: Downloading m3u8 information
[info] Available formats for xGx2aHeSG48:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb1 mhtml 80x45        0    │                  mhtml │ images                                  storyboard
sb0 mhtml 160x90       0    │                  mhtml │ images                                  storyboard
233 mp4   audio only        │                  m3u8  │ audio only          unknown             Default
234 mp4   audio only        │                  m3u8  │ audio only          unknown             Default
599 m4a   audio only      2 │    4.09MiB   31k https │ audio only          mp4a.40.5   31k 22k ultralow, m4a_dash
600 webm  audio only      2 │    4.90MiB   37k https │ audio only          opus        37k 48k ultralow, webm_dash
139 m4a   audio only      2 │    6.48MiB   49k https │ audio only          mp4a.40.5   49k 22k low, m4a_dash
249 webm  audio only      2 │    7.07MiB   53k https │ audio only          opus        53k 48k low, webm_dash
250 webm  audio only      2 │   11.00MiB   83k https │ audio only          opus        83k 48k low, webm_dash
140 m4a   audio only      2 │   17.19MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, m4a_dash
251 webm  audio only      2 │   19.22MiB  145k https │ audio only          opus       145k 48k medium, webm_dash
17  3gp   176x144      7  1 │   10.79MiB   81k https │ mp4v.20.3           mp4a.40.2       22k 144p
597 mp4   256x144     15    │    4.73MiB   36k https │ avc1.4d400b     36k video only          144p, mp4_dash
602 mp4   256x144     15    │ ~ 15.01MiB  110k m3u8  │ vp09.00.10.08  110k video only
598 webm  256x144     15    │    4.29MiB   32k https │ vp9             32k video only          144p, webm_dash
269 mp4   256x144     30    │ ~ 26.51MiB  195k m3u8  │ avc1.4D400C    195k video only
160 mp4   256x144     30    │   12.02MiB   91k https │ avc1.4D400C     91k video only          144p, mp4_dash
603 mp4   256x144     30    │ ~ 23.65MiB  174k m3u8  │ vp09.00.11.08  174k video only
278 webm  256x144     30    │   10.20MiB   77k https │ vp09.00.11.08   77k video only          144p, webm_dash
229 mp4   426x240     30    │ ~ 50.52MiB  372k m3u8  │ avc1.4D4015    372k video only
133 mp4   426x240     30    │   26.03MiB  196k https │ avc1.4D4015    196k video only          240p, mp4_dash
604 mp4   426x240     30    │ ~ 42.78MiB  315k m3u8  │ vp09.00.20.08  315k video only
242 webm  426x240     30    │   17.88MiB  135k https │ vp09.00.20.08  135k video only          240p, webm_dash
230 mp4   640x360     30    │ ~119.69MiB  880k m3u8  │ avc1.4D401E    880k video only
134 mp4   640x360     30    │   48.86MiB  368k https │ avc1.4D401E    368k video only          360p, mp4_dash
18  mp4   640x360     30  2 │   61.56MiB  464k https │ avc1.42001E         mp4a.40.2       44k 360p
605 mp4   640x360     30    │ ~ 81.49MiB  599k m3u8  │ vp09.00.21.08  599k video only
243 webm  640x360     30    │   30.06MiB  226k https │ vp09.00.21.08  226k video only          360p, webm_dash
231 mp4   854x480     30    │ ~207.08MiB 1523k m3u8  │ avc1.4D401F   1523k video only
135 mp4   854x480     30    │   83.01MiB  625k https │ avc1.4D401F    625k video only          480p, mp4_dash
606 mp4   854x480     30    │ ~140.74MiB 1035k m3u8  │ vp09.00.30.08 1035k video only
244 webm  854x480     30    │   46.80MiB  352k https │ vp09.00.30.08  352k video only          480p, webm_dash
22  mp4   1280x720    30  2 │ ≈175.86MiB 1293k https │ avc1.64001F         mp4a.40.2       44k 720p
232 mp4   1280x720    30    │ ~359.58MiB 2644k m3u8  │ avc1.64001F   2644k video only
136 mp4   1280x720    30    │  154.69MiB 1165k https │ avc1.64001F   1165k video only          720p, mp4_dash
609 mp4   1280x720    30    │ ~315.57MiB 2321k m3u8  │ vp09.00.31.08 2321k video only
247 webm  1280x720    30    │   84.36MiB  635k https │ vp09.00.31.08  635k video only          720p, webm_dash
270 mp4   1920x1080   30    │ ~695.80MiB 5117k m3u8  │ avc1.640028   5117k video only
137 mp4   1920x1080   30    │  284.67MiB 2144k https │ avc1.640028   2144k video only          1080p, mp4_dash
614 mp4   1920x1080   30    │ ~439.90MiB 3235k m3u8  │ vp09.00.40.08 3235k video only
248 webm  1920x1080   30    │  135.29MiB 1019k https │ vp09.00.40.08 1019k video only          1080p, webm_dash
616 mp4   1920x1080   30    │ ~779.78MiB 5734k m3u8  │ vp09.00.40.08 5734k video only          Premium
```

All of the formats are available. But when I try to download the video it says "not found". Example, the 614 version.

```
yt-dlp -f 614 --check-formats --cookies /config/youtube.com_cookies.txt https://www.youtube.com/watch?v=xGx2aHeSG48 -P /youtube-other -v
[debug] Command-line config: ['-f', '614', '--check-formats', '--cookies', '/config/youtube.com_cookies.txt', 'https://www.youtube.com/watch?v=xGx2aHeSG48', '-P', '/youtube-other', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.1.36-Unraid-x86_64-with (OpenSSL 3.0.9 30 May 2023)
[debug] exe versions: ffmpeg 5.1.3 (setts), ffprobe 5.1.3
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=xGx2aHeSG48
[youtube] xGx2aHeSG48: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] xGx2aHeSG48: Downloading ios player API JSON
[youtube] xGx2aHeSG48: Downloading android player API JSON
[youtube] xGx2aHeSG48: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] xGx2aHeSG48: Downloading 1 format(s): 614
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1690293102/ei/Dn-_ZOumM9KD4gGFxqrIDg/ip/5.146.203.76/id/c46c766877921b8f/itag/614/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D141859851%3Bdur%3D1113.846%3Bgir%3Dyes%3Bitag%3D248%3Blmt%3D1690239747680389/hls_chunk_host/rr1---sn-5hneknek.googlevideo.com/mh/WE/mm/31,26/mn/sn-5hneknek,sn-4g5lznl7/ms/au,onr/mv/m/mvi/1/pl/21/initcwndbps/2338750/vprv/1/playlist_type/DVR/dover/13/txp/3309224/mt/1690271145/fvip/3/short_key/1/keepalive/yes/fexp/24007246,24362686,51000024/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,vprv,playlist_type/sig/AOq0QJ8wRQIhAOX_qAvJCA2PdkPGmtXREDdfipQTeitCZyMTli0j2zH4AiA9AcAikkFzQshjUl964D0zJBtXCEZArTA62kKYa8eifg%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRQIgZNcwrfCcazL47RauGxXbhomh1wQmIcfV1ZOvFKUX-cYCIQCRCQ0nqhRllLMxt9PpJ3MtXt3V-gtKq_0c6P4OlGLrgw%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3363, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3084, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 461, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/downloader/hls.py", line 77, in real_download
    urlh = self.ydl.urlopen(self._prepare_url(info_dict, man_url))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3863, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
Interestingly enough, I checked a few now.

* 270: 404
* 616: 404
* 248: works
* 137: works
* 597: works
* 614: 404

And this video was released 10 hours ago.  Still, the `--check-formats` does nothing in that regard, the error is still 404. But with `--check-all-formats` this works and version `248+251` is downloaded.

**Comment by pukkandan** [comment] 2023-07-25 10:44
--check-formats appear to be broken. Will fix asap
