### ISSUE TITLE
ERROR: [Ixigua] 6996881461559165471: Failed to get SSR_HYDRATED_DATA;

### ISSUE THREAD

**Issue by k15fb-mmo** [yt-dlp/yt-dlp#10219] opened 2024-06-20 10:24 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

i update to Lastest version of yt-dlp but i can't to download video from IXIGUA (ERROR: [Ixigua] 6996881461559165471: Failed to get SSR_HYDRATED_DATA;)

yt-dlp -vU --referer 'https://www.ixigua.com/' --cookies ixigua.com_cookies.txt -f "ba/b" --ignore-errors 'https://www.ixigua.com/7381652489134670371'
[debug] Command-line config: ['-vU', '--referer', 'https://www.ixigua.com/', '--cookies', 'ixigua.com_cookies.txt', '-f', 'ba/b', '--ignore-errors', 'https://www.ixigua.com/7381652489134670371']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.17.232743 from yt-dlp/yt-dlp-nightly-builds [90c3721a3] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.2.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.17.232743 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.17.232743 from yt-dlp/yt-dlp-nightly-builds)
[Ixigua] Extracting URL: https://www.ixigua.com/7381652489134670371
[Ixigua] 738165248913467037: Downloading webpage
ERROR: [Ixigua] 738165248913467037: Failed to get SSR_HYDRATED_DATA; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\ixigua.py", line 67, in _real_extract
  File "yt_dlp\extractor\ixigua.py", line 39, in _get_json_data

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --referer 'https://www.ixigua.com/' --cookies ixigua.com_cookies.txt -f "ba/b" --ignore-errors 'https://www.ixigua.com/7381652489134670371'
[debug] Command-line config: ['-vU', '--referer', 'https://www.ixigua.com/', '--cookies', 'ixigua.com_cookies.txt', '-f', 'ba/b', '--ignore-errors', 'https://www.ixigua.com/7381652489134670371']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.17.232743 from yt-dlp/yt-dlp-nightly-builds [90c3721a3] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.2.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.17.232743 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.17.232743 from yt-dlp/yt-dlp-nightly-builds)
[Ixigua] Extracting URL: https://www.ixigua.com/7381652489134670371
[Ixigua] 738165248913467037: Downloading webpage
ERROR: [Ixigua] 738165248913467037: Failed to get SSR_HYDRATED_DATA; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\ixigua.py", line 67, in _real_extract
  File "yt_dlp\extractor\ixigua.py", line 39, in _get_json_data
```

**Comment by bashonly** [comment] 2024-06-20 13:23
Duplicate of #5374

**Closed by bashonly** 2024-06-20 13:23 UTC
Labels: question

**Comment by k15fb-mmo** [comment] 2024-07-03 06:21
> Duplicate of #5374

yt-dlp -vU --referer 'https://www.ixigua.com/home/457031191899364' --cookies ixigua.com_cookies.txt --download-archive archive.txt -f "ba/b" --ignore-errors 'https://www.ixigua.com/7385173674623500834'
[debug] Command-line config: ['-vU', '--referer', 'https://www.ixigua.com/home/457031191899364', '--cookies', 'ixigua.com_cookies.txt', '--download-archive', 'archive.txt', '-f', 'ba/b', '--ignore-errors', 'https://www.ixigua.com/7385173674623500834']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.17.232743 from yt-dlp/yt-dlp-nightly-builds [90c3721a3] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.2.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1823 extractors
[debug] Loading archive file 'archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.07.02.232715/SHA2-256SUMS
Current version: nightly@2024.06.17.232743 from yt-dlp/yt-dlp-nightly-builds
Latest version: nightly@2024.07.02.232715 from yt-dlp/yt-dlp-nightly-builds
Current Build Hash: b5ecf10128908f4cacf7537bc3ad46fb48e04a62d35ee8966f581bdaae7b7760
Updating to nightly@2024.07.02.232715 from yt-dlp/yt-dlp-nightly-builds ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.07.02.232715/yt-dlp.exe
Updated yt-dlp to nightly@2024.07.02.232715 from yt-dlp/yt-dlp-nightly-builds
[debug] Restarting: C:\bin\yt-dlp.exe -vU --referer https://www.ixigua.com/home/457031191899364 --cookies ixigua.com_cookies.txt --download-archive archive.txt -f ba/b --ignore-errors https://www.ixigua.com/7385173674623500834
[debug] Command-line config: ['-vU', '--referer', 'https://www.ixigua.com/home/457031191899364', '--cookies', 'ixigua.com_cookies.txt', '--download-archive', 'archive.txt', '-f', 'ba/b', '--ignore-errors', 'https://www.ixigua.com/7385173674623500834']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.02.232715 from yt-dlp/yt-dlp-nightly-builds [d28aa87e2] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.2.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1831 extractors
[debug] Loading archive file 'archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.07.02.232715 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.07.02.232715 from yt-dlp/yt-dlp-nightly-builds)
[Ixigua] Extracting URL: https://www.ixigua.com/7385173674623500834
[Ixigua] 738517367462350083: Downloading webpage
ERROR: [Ixigua] 738517367462350083: Failed to get SSR_HYDRATED_DATA; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\ixigua.py", line 67, in _real_extract
  File "yt_dlp\extractor\ixigua.py", line 39, in _get_json_data
