### ISSUE TITLE
Parse error at position 56 (near '') (discoveryplus)

### ISSUE THREAD

**Issue by BondeDK** [yt-dlp/yt-dlp#5600] opened 2022-11-19 21:20 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

On some titles on Discoveryplus i get the error 
" Parse error at position 56 (near '') " it is not on all the the titles this error occurs

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.2-2021-02-27-full_build-www.gyan.dev, ffprobe 2022-06-16-git-5242ede48d-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] [generic] Extracting URL: https://dplus-dk-prod-vod.akamaized.net/36aa8a64-31cc-4ce6-b7d1-b980f60ec2df/hls_clear_ts/hdntl=exp=1668978258~acl=/36aa8a64-31cc-4ce6-b7d1-b980f60ec2df/hls_clear_ts/*~data=hdntl~hmac=76627de96db68bd9deab23c550e99d6526f0b4576c83de7bd72fb7ba2e5f340f/master.m3u8?mfs=GgoKCBICEAEaAhAB
[generic] master: Downloading webpage
[debug] Identified a direct video link
[generic] master: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] master: Downloading subtitles: sv, nb, da, fi
[debug] Default format spec: bestvideo*+bestaudio/best
[info] master: Downloading 1 format(s): 10207+audio-aacl-125-English
[info] Writing video subtitles to: master [master].sv.vtt
[debug] Invoking hlsnative downloader on "https://dplus-dk-prod-vod.akamaized.net/36aa8a64-31cc-4ce6-b7d1-b980f60ec2df/hls_clear_ts/hdntl=exp=1668978258~acl=/36aa8a64-31cc-4ce6-b7d1-b980f60ec2df/hls_clear_ts/*~data=hdntl~hmac=76627de96db68bd9deab23c550e99d6526f0b4576c83de7bd72fb7ba2e5f340f/c1_caption/prog_index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 12
[download] Destination: master [master].sv.vtt
[debug] File locking is not supported. Proceeding without locking
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download] 100.0% of ~ 116.24KiB at   20.00MiB/s ETA 00:00 (frag 12/12)ERROR: Parse error at position 56 (near '')
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1582, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1641, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2737, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2983, in process_info
  File "yt_dlp\YoutubeDL.py", line 3950, in _write_subtitles
  File "yt_dlp\YoutubeDL.py", line 2924, in dl
  File "yt_dlp\downloader\common.py", line 446, in download
  File "yt_dlp\downloader\hls.py", line 351, in real_download
  File "yt_dlp\downloader\fragment.py", line 506, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 479, in append_fragment
  File "yt_dlp\downloader\hls.py", line 266, in pack_fragment
  File "yt_dlp\webvtt.py", line 363, in parse_fragment
  File "yt_dlp\webvtt.py", line 217, in parse
yt_dlp.webvtt.ParseError: Parse error at position 56 (near '')
```

**Comment by flashdagger** [comment] 2022-11-19 22:40
Parser fails because fragment 3 does not contain any cue blocks. Quickfix could be:

```patch
diff --git a/yt_dlp/webvtt.py b/yt_dlp/webvtt.py
--- a/yt_dlp/webvtt.py	(revision 34ccbda725d00b11c4f2266a9809adf677925c62)
+++ b/yt_dlp/webvtt.py	(date 1668897416013)
@@ -93,7 +93,7 @@
     ([0-9]{3})?
 ''')
 _REGEX_EOF = re.compile(r'\Z')
-_REGEX_NL = re.compile(r'(?:\r\n|[\r\n])')
+_REGEX_NL = re.compile(r'(?:\r\n|[\r\n]|$)')
 _REGEX_BLANK = re.compile(r'(?:\r\n|[\r\n])+')
```

**Comment by pukkandan** [comment] 2022-11-19 23:16
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2867 ?

**Comment by flashdagger** [comment] 2022-11-20 07:32
Seems so. But definitely the exact issue as in #3930.

**Closed** 2022-11-20 08:45 UTC
Labels: bug, duplicate
