### ISSUE TITLE
Youtube live_chat download not working anymore

### ISSUE THREAD

**Issue by jenlunds** [yt-dlp/yt-dlp#8017] opened 2023-09-03 09:50 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Youtube live_chat download doesn't work anymore. It seems like it stopped working sometime around Aug 24. It just downloads ~410KiB (first fragment?). Same thing happens if I try to download it live or afterwards.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--ignore-config', '--skip-download', '--sub-langs', 'live_chat', '--write-sub', 'ZvjP1RcAHJQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-159-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2019.11.28, mutagen-1.46.0, secretstorage-2.3.1, sqlite3-2.6.0, websockets-9.1, xattr-0.9.9
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: ZvjP1RcAHJQ
[youtube] ZvjP1RcAHJQ: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] ZvjP1RcAHJQ: Downloading ios player API JSON
[youtube] ZvjP1RcAHJQ: Downloading android player API JSON
[youtube] ZvjP1RcAHJQ: Downloading iframe API JS
[youtube] ZvjP1RcAHJQ: Downloading player 0a835141
[youtube] ZvjP1RcAHJQ: Downloading web player API JSON
[debug] Loading youtube-nsig.0a835141 from cache
[debug] [youtube] Decrypted nsig Zw6gTqd7psj1WLtFMM => MNVAiudIXbsqOA
[youtube] ZvjP1RcAHJQ: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] ZvjP1RcAHJQ: Downloading initial data API JSON
[info] ZvjP1RcAHJQ: Downloading subtitles: live_chat
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ZvjP1RcAHJQ: Downloading 1 format(s): 303+251
[info] Writing video subtitles to: life is half 2 ending [ZvjP1RcAHJQ].live_chat.json
[debug] Invoking youtube_live_chat downloader on "https://www.youtube.com/watch?v=ZvjP1RcAHJQ&bpctr=9999999999&has_verified=1"
[youtube_live_chat] Downloading live chat
[youtube_live_chat] Total fragments: unknown (live)
[download] Destination: life is half 2 ending [ZvjP1RcAHJQ].live_chat.json
[download]  410.11KiB at    1.10MiB/s (00:00:00) (frag 1)
```

**Comment by bashonly** [comment] 2023-09-03 09:59
Duplicate of #7594

`yt-dlp --update-to nightly`
or
https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-master
or
https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest

**Closed by bashonly** 2023-09-03 09:59 UTC
Labels: site-bug, triage
