### ISSUE TITLE
Modification time

### ISSUE THREAD

**Issue by znaczki654** [yt-dlp/yt-dlp#9814] opened 2024-04-28 21:56 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I can see in the readme file that the --mtime is described to change the modifcation date. As understood it changes the modification date of the output file to the modification date of the file in the server.

Could you please create an option to change modification time to the time when the video was uploaded?
This is the example link:
https://www.youtube.com/watch?v=OqjTtnmGv8s
(my video)
Date of upload: 26.10.2021
Date of modification: ‎11.03.‎2023, ‏‎23:29:32 (doesn't really know why, maybe she has changed something this year?)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp https://www.youtube.com/watch?v=OqjTtnmGv8s -vU --mtime --write-description -f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b" 
[debug] Command-line config: ['https://www.youtube.com/watch?v=OqjTtnmGv8s', '-vU', '--mtime', '--write-description', '-f', 'bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out cp1250 (No VT), error cp1250 (No VT), screen cp1250 (No VT)
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 7.0-essentials_build-www.gyan.dev (setts), ffprobe 7.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=OqjTtnmGv8s
[youtube] OqjTtnmGv8s: Downloading webpage
[youtube] OqjTtnmGv8s: Downloading ios player API JSON
[youtube] OqjTtnmGv8s: Downloading android player API JSON
WARNING: [youtube] Skipping player responses from android clients (got player responses for video "aQvGIIdgFDM" instead of "OqjTtnmGv8s")
[debug] Loading youtube-nsig.652ba3a2 from cache
[debug] [youtube] Decrypted nsig IIbeIwwPpDtyVs3pEb => PrqoNLTlH8UO7A
[debug] Loading youtube-nsig.652ba3a2 from cache
[debug] [youtube] Decrypted nsig 6P3PH8BO--Yj49KAkI => xzcA1kKP8zuzrg
[youtube] OqjTtnmGv8s: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] OqjTtnmGv8s: Downloading 1 format(s): 137+140
[info] Writing video description to: Jojo Akali [OqjTtnmGv8s].description
[debug] Invoking http downloader on "https://rr3---sn-x2pm-3ufe7.googlevideo.com/videoplayback?expire=1714362834&ei=csUuZq-XD-z0i9oPjoq_mA4&ip=94.231.3.95&id=o-AH2O3wMZEgxzYxn8lHPDFCjLwL9CrkYJipHYt4IWjTSi&itag=137&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=Mj&mm=31%2C29&mn=sn-x2pm-3ufe7%2Csn-f5f7knee&ms=au%2Crdu&mv=m&mvi=3&pl=20&initcwndbps=2896250&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=14150580&dur=64.366&lmt=1678573778500892&mt=1714340947&fvip=3&keepalive=yes&c=IOS&txp=6216224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAOcYMX4Zp4pwS8iQ3RMKgW837jFcER-FGwMDQ45e58jSAiEA5OP-ZSQKPu4oSueJxPthyVfJU3QJm6_WgXWiBr4f598%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIhAMSgEPNBIWNDnZtDqUFSTT5CfFJKkxPZ_jpRWsUXaRt1AiAA7f6S6zijlBR5A3IQ2oY2rLvXlW0SAj3JVhdlU5wmNQ%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Jojo Akali [OqjTtnmGv8s].f137.mp4

[download]   0.0% of   13.50MiB at  333.38KiB/s ETA 00:41
[download]   0.0% of   13.50MiB at  749.79KiB/s ETA 00:18
[download]   0.1% of   13.50MiB at    1.71MiB/s ETA 00:07
[download]   0.1% of   13.50MiB at    3.66MiB/s ETA 00:03
[download]   0.2% of   13.50MiB at    4.88MiB/s ETA 00:02
[download]   0.5% of   13.50MiB at    1.83MiB/s ETA 00:07
[download]   0.9% of   13.50MiB at    2.26MiB/s ETA 00:05
[download]   1.8% of   13.50MiB at    2.85MiB/s ETA 00:04
[download]   3.7% of   13.50MiB at    4.14MiB/s ETA 00:03
[download]   7.4% of   13.50MiB at    5.18MiB/s ETA 00:02
[download]  14.8% of   13.50MiB at    6.55MiB/s ETA 00:01
[download]  29.6% of   13.50MiB at    7.45MiB/s ETA 00:01
[download]  59.3% of   13.50MiB at    7.98MiB/s ETA 00:00
[download]  73.4% of   13.50MiB at    8.12MiB/s ETA 00:00
[download]  73.4% of   13.50MiB at   28.08KiB/s ETA 02:11
[download]  73.4% of   13.50MiB at   84.25KiB/s ETA 00:43
[download]  73.4% of   13.50MiB at  196.59KiB/s ETA 00:18
[download]  73.5% of   13.50MiB at  409.76KiB/s ETA 00:08
[download]  73.6% of   13.50MiB at  846.84KiB/s ETA 00:04
[download]  73.8% of   13.50MiB at    1.64MiB/s ETA 00:02
[download]  74.3% of   13.50MiB at    1.91MiB/s ETA 00:01
[download]  75.2% of   13.50MiB at    3.77MiB/s ETA 00:00
[download]  77.1% of   13.50MiB at    5.51MiB/s ETA 00:00
[download]  80.8% of   13.50MiB at    5.77MiB/s ETA 00:00
[download]  88.2% of   13.50MiB at    5.90MiB/s ETA 00:00
[download] 100.0% of   13.50MiB at    5.98MiB/s ETA 00:00
[download] 100% of   13.50MiB in 00:00:02 at 5.89MiB/s   
[debug] Invoking http downloader on "https://rr3---sn-x2pm-3ufe7.googlevideo.com/videoplayback?expire=1714362834&ei=csUuZq-XD-z0i9oPjoq_mA4&ip=94.231.3.95&id=o-AH2O3wMZEgxzYxn8lHPDFCjLwL9CrkYJipHYt4IWjTSi&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=Mj&mm=31%2C29&mn=sn-x2pm-3ufe7%2Csn-f5f7knee&ms=au%2Crdu&mv=m&mvi=3&pl=20&initcwndbps=2896250&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=1043541&dur=64.435&lmt=1678573772860151&mt=1714340947&fvip=3&keepalive=yes&c=IOS&txp=6211224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAJeKXSI8OyfOwM_poJVSKQCve_Ub6os5RLzcD0d4V1KhAiEA62_UZ1p46P7t_iDqwNY6HJSZ68e5UasxM7q5e1lK3FY%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIhAMSgEPNBIWNDnZtDqUFSTT5CfFJKkxPZ_jpRWsUXaRt1AiAA7f6S6zijlBR5A3IQ2oY2rLvXlW0SAj3JVhdlU5wmNQ%3D%3D"
[download] Destination: Jojo Akali [OqjTtnmGv8s].f140.m4a

[download]   0.1% of 1019.08KiB at  496.31KiB/s ETA 00:02
[download]   0.3% of 1019.08KiB at    1.45MiB/s ETA 00:00
[download]   0.7% of 1019.08KiB at    2.27MiB/s ETA 00:00
[download]   1.5% of 1019.08KiB at    4.87MiB/s ETA 00:00
[download]   3.0% of 1019.08KiB at    7.55MiB/s ETA 00:00
[download]   6.2% of 1019.08KiB at    6.83MiB/s ETA 00:00
[download]  12.5% of 1019.08KiB at    6.52MiB/s ETA 00:00
[download]  25.0% of 1019.08KiB at    6.22MiB/s ETA 00:00
[download]  50.1% of 1019.08KiB at    6.14MiB/s ETA 00:00
[download] 100.0% of 1019.08KiB at    6.13MiB/s ETA 00:00
[download] 100% of 1019.08KiB in 00:00:00 at 1.54MiB/s   
[Merger] Merging formats into "Jojo Akali [OqjTtnmGv8s].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:Jojo Akali [OqjTtnmGv8s].f137.mp4" -i "file:Jojo Akali [OqjTtnmGv8s].f140.m4a" -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart "file:Jojo Akali [OqjTtnmGv8s].temp.mp4"
Deleting original file Jojo Akali [OqjTtnmGv8s].f140.m4a (pass -k to keep)
Deleting original file Jojo Akali [OqjTtnmGv8s].f137.mp4 (pass -k to keep)
```

**Comment by bashonly** [comment] 2024-04-28 21:58
Duplicate of #903

You may be interested in this plugin: https://github.com/bradenhilton/yt-dlp-FixupMtime

**Closed by bashonly** 2024-04-28 21:58 UTC
Labels: enhancement, triage

**Comment by znaczki654** [comment] 2024-04-28 22:01
But can it be fixed in further release?

**Comment by bashonly** [comment] 2024-04-28 22:02
That's what #903 is tracking
