### ISSUE TITLE
Beeg broken

### ISSUE THREAD

**Issue by campones** [yt-dlp/yt-dlp#2763] opened 2022-02-13 19:55 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

worldwide

### Description

Beeg is not working, it used to be a plugin on the former youtube-dl,  not sure it is the case now

### Verbose log

```shell
yt-dlp -vvv https://beeg.com/-01036758196?t=1488-2088
[debug] Command-line config: ['-vvv', 'https://beeg.com/-01036758196?t=1488-2088']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-96-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg N-101901-gb593abd (setts), ffprobe N-101901-gb593abd, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://beeg.com/-01036758196?t=1488-2088
[generic] -01036758196?t=1488-2088: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] -01036758196?t=1488-2088: Downloading webpage
[generic] -01036758196?t=1488-2088: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://beeg.com/-01036758196?t=1488-2088
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/generic.py", line 3986, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://beeg.com/-01036758196?t=1488-2088
```

**Comment by pukkandan** [comment] 2022-02-13 20:39
Duplicate of #2592

**Closed by pukkandan** 2022-02-13 20:39 UTC
Labels: site-bug, triage
