### ISSUE TITLE
Make the ETA a moving average to increase stability

### ISSUE THREAD

**Issue by chausies** [yt-dlp/yt-dlp#4267] opened 2022-07-04 09:46 UTC
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When I was downloading a long video (https://www.youtube.com/watch?v=3jw8XF1mW4U), the ETA would constantly be jumping wildly between between 2 minutes to 1h every time it updated (as my download speed changed). But this is hardly informative of what the actual overall completion time would be.

What you should do is take a weighted average a.k.a. exponential smoothing (e.g. average_eta = 0.95*average_eta + 0.05*current_eta) for the ETA you display, so that it's much more stable and informative, while still being dynamic. Most good progress bars do this (e.g. https://github.com/tqdm/tqdm).

Is it too hard to implement this as the default behavior? I think it'd be very worthwhile.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment] 2022-07-04 10:15
Related: https://github.com/yt-dlp/yt-dlp/pull/3345

**Comment by pukkandan** [comment] 2022-07-05 08:16
Closing as duplicate of #2197

**Closed by pukkandan** 2022-07-05 08:16 UTC
Labels: enhancement
