### ISSUE TITLE
SUPPORT FOR FACEBOOK REEELS BROKEN

### ISSUE THREAD

**Issue by plang22** [yt-dlp/yt-dlp#11553] opened 2024-11-15 12:42 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Kenya

### Provide a description that is worded well enough to be understood

Since the last update , support for facebook  broke, i have updated to the latest version but the issue persist, i am using it as an import in python code, i have also tested directly i.e yt-dlp  <Facebook reel url link> ....

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.facebook.com/iamkybaldwin/videos/facebook-only-allows-90-seconds-on-reels-so-heres-the-extended-version-heyjude-t/316203414406924/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (pip) 
[debug] Python 3.12.6 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 3.0.15 3 Sep 2024) 
[debug] exe versions: ffmpeg N-117141-gb4d9fa6cb9-20240924 (setts), ffprobe N-117141-gb4d9fa6cb9-20240924 
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {'http': 'http://10.223.197.40:8080', 'https': 'http://10.223.197.40:8080', 'ftp': 'http://10.223.197.40:8080'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest 
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec 
Current version: stable@2024.10.22 from yt-dlp/yt-dlp 
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update 
[facebook] Extracting URL: https://www.facebook.com/iamkybaldwin/videos/facebook-only-allows-90-seconds-on-reels-so-heres-the-extended-version-heyjude-t/316203414406924/
[facebook] 316203414406924: Downloading webpage 
ERROR: [facebook] 316203414406924: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last): 
  File "d:\Projects\InternetDownloader\Django_web_main\API_server\.venv\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Projects\InternetDownloader\Django_web_main\API_server\.venv\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1781, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Projects\InternetDownloader\Django_web_main\API_server\.venv\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1840, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Projects\InternetDownloader\Django_web_main\API_server\.venv\Lib\site-packages\yt_dlp\YoutubeDL.py", line 2846, in process_video_result
    self.raise_no_formats(info_dict)
  File "d:\Projects\InternetDownloader\Django_web_main\API_server\.venv\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1122, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [facebook] 316203414406924: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by gamer191** [comment] 2024-11-15 14:09
Update to nightly:
```
pip install -U --pre "yt-dlp[default]"
```

**Comment by bashonly** [comment] 2024-11-15 14:37
Duplicate of #11497

**Closed by bashonly** 2024-11-15 14:37 UTC
Labels: duplicate, site-bug, site:facebook

**Comment by plang22** [comment] 2024-11-16 17:53
> Update to nightly:
> 
> ```
> pip install -U --pre "yt-dlp[default]"
> ```

It worked, thanks
