### ISSUE TITLE
another forbidden error

### ISSUE THREAD

**Issue by dew-hattens** [yt-dlp/yt-dlp#11956] opened 2024-12-30 20:36 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

denmark

### Provide a description that is worded well enough to be understood

Have tried the -U upgrade feature without luck

[Command Prompt.txt](https://github.com/user-attachments/files/18277580/Command.Prompt.txt)

C:\Users\marti\Downloads>yt-dlp.exe --verbose https://www.youtube.com/watch?v=cZwow_u9xlE
[debug] Command-line config: ['--verbose', 'https://www.youtube.com/watch?v=cZwow_u9xlE']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 2024-12-26-git-fe04b93afa-full_build-www.gyan.dev (setts), ffprobe 2024-12-26-git-fe04b93afa-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=cZwow_u9xlE
[youtube] cZwow_u9xlE: Downloading webpage
[youtube] cZwow_u9xlE: Downloading ios player API JSON
[youtube] cZwow_u9xlE: Downloading mweb player API JSON
[debug] [youtube] cZwow_u9xlE: ios client https formats require a PO Token which was not provided. They will be skippedas they may yield HTTP Error 403. You can manually pass a PO Token for this client with --extractor-args "youtube:po_token=ios+XXX. For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide . To enablethese broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig d8pnUvY-XgOuE8uvV => PGlIjoLa5PInsg
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig rmO_Cv1UydEy-u_N5 => ixXutQOPZIdQCQ
[youtube] cZwow_u9xlE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] cZwow_u9xlE: Downloading 1 format(s): 616+251
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1735612054/ei/NgJzZ_ycEreNv_IP4a34wAM/ip/2a09:5e41:20b:b730:85bd:5e87:ed5e:9e9d/id/719c28c3fbbdc651/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D1163621492%3Bdur%3D5132.127%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1735446088614202/rqh/1/hls_chunk_host/rr3---sn-uqj-55gs.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/met/1735590454,/mh/m4/mm/31,29/mn/sn-uqj-55gs,sn-5go7ynl6/ms/au,rdu/mv/m/mvi/3/pl/45/rms/au,au/force_finished/1/initcwndbps/5165000/spc/x-caUHL2ecL7JQP6G9DX51qeJcLvT1Cp1HoGtZlhpnJL90g6hHa0sFo/vprv/1/playlist_type/DVR/dover/13/txp/5432434/mt/1735590080/fvip/2/short_key/1/keepalive/yes/fexp/51326932,51335594,51371294/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,force_finished,spc,vprv,playlist_type/sig/AJfQdSswRgIhANv394I20k21QfUfpqZwlxagjMl5PxVjAvIJPig8g9eaAiEA9e1tzrHP42OlaWDzI75dLHojNh-l7Pffz5RObzy8AEs%3D/lsparams/hls_chunk_host,met,mh,mm,mn,ms,mv,mvi,pl,rms,initcwndbps/lsig/AGluJ3MwRQIgE4a8dQFeclLo1e19sS7rVPURXs24sCfxMe43o60LJSkCIQCMb9LSU0V2h3wqnZpJ_tQk7UNeEQnyhi0GQe8XXnljgQ%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 979
[download] Destination: The Atlantis Puzzle (2024) ｜ Full Movie ｜ Documentary [cZwow_u9xlE].f616.mp4
[debug] File locking is not supported. Proceeding without locking
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
[download] fragment not found; Skipping fragment 1 ...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (7/10)...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\marti\Downloads>yt-dlp.exe --verbose https://www.youtube.com/watch?v=cZwow_u9xlE
[debug] Command-line config: ['--verbose', 'https://www.youtube.com/watch?v=cZwow_u9xlE']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 2024-12-26-git-fe04b93afa-full_build-www.gyan.dev (setts), ffprobe 2024-12-26-git-fe04b93afa-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=cZwow_u9xlE
[youtube] cZwow_u9xlE: Downloading webpage
[youtube] cZwow_u9xlE: Downloading ios player API JSON
[youtube] cZwow_u9xlE: Downloading mweb player API JSON
[debug] [youtube] cZwow_u9xlE: ios client https formats require a PO Token which was not provided. They will be skippedas they may yield HTTP Error 403. You can manually pass a PO Token for this client with --extractor-args "youtube:po_token=ios+XXX. For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide . To enablethese broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig d8pnUvY-XgOuE8uvV => PGlIjoLa5PInsg
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig rmO_Cv1UydEy-u_N5 => ixXutQOPZIdQCQ
[youtube] cZwow_u9xlE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] cZwow_u9xlE: Downloading 1 format(s): 616+251
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1735612054/ei/NgJzZ_ycEreNv_IP4a34wAM/ip/2a09:5e41:20b:b730:85bd:5e87:ed5e:9e9d/id/719c28c3fbbdc651/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D1163621492%3Bdur%3D5132.127%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1735446088614202/rqh/1/hls_chunk_host/rr3---sn-uqj-55gs.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/met/1735590454,/mh/m4/mm/31,29/mn/sn-uqj-55gs,sn-5go7ynl6/ms/au,rdu/mv/m/mvi/3/pl/45/rms/au,au/force_finished/1/initcwndbps/5165000/spc/x-caUHL2ecL7JQP6G9DX51qeJcLvT1Cp1HoGtZlhpnJL90g6hHa0sFo/vprv/1/playlist_type/DVR/dover/13/txp/5432434/mt/1735590080/fvip/2/short_key/1/keepalive/yes/fexp/51326932,51335594,51371294/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,force_finished,spc,vprv,playlist_type/sig/AJfQdSswRgIhANv394I20k21QfUfpqZwlxagjMl5PxVjAvIJPig8g9eaAiEA9e1tzrHP42OlaWDzI75dLHojNh-l7Pffz5RObzy8AEs%3D/lsparams/hls_chunk_host,met,mh,mm,mn,ms,mv,mvi,pl,rms,initcwndbps/lsig/AGluJ3MwRQIgE4a8dQFeclLo1e19sS7rVPURXs24sCfxMe43o60LJSkCIQCMb9LSU0V2h3wqnZpJ_tQk7UNeEQnyhi0GQe8XXnljgQ%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 979
[download] Destination: The Atlantis Puzzle (2024) ｜ Full Movie ｜ Documentary [cZwow_u9xlE].f616.mp4
[debug] File locking is not supported. Proceeding without locking
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
[download] fragment not found; Skipping fragment 1 ...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 2 (7/10)...
```

**Comment by bashonly** [comment] 2024-12-30 20:39
Duplicate of #11868

**Comment by coletdjnz** [comment] 2024-12-30 20:40
https://github.com/yt-dlp/yt-dlp/issues/11868

**Closed by bashonly** 2024-12-30 20:39 UTC
Labels: site-bug, triage
