### ISSUE TITLE
Retry downloads with a temporary failure instead of skipping

### ISSUE THREAD

**Issue by vphantom** [yt-dlp/yt-dlp#11757] opened 2024-12-07 00:15 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I was reticent to add to the list of issues but I think this suggestion, if feasible, would be a great improvement. 😉

Relevant command line options being set: `--retries infinite --file-access-retries infinite --fragment-retries infinite --extractor-retries infinite --sleep-requests 2 --sleep-interval 2 --sleep-subtitles 2`

Despite these, DNS resolution is still attempted a single time with `2024.12.03`.  Maybe it's my cellular Internet's fault, but I get occasional DNS lookup failures which cause yt-dlp to immediately give up on the URL and move on to the next, which will work correctly.  I don't have actual logs of the issue yet since it happens only a few times a week, but the error is of type: `Unable to download webpage: <urllib3.connection.HTTPSConnection object at 0x...>: Failed to resolve 'www.youtube.com' ([Errno -3] Try again)`

It would be great if this type of temporary error allowed retries instead of moving on to the next URL.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment] 2024-12-07 18:33
Duplicate of #6627

**Closed by bashonly** 2024-12-07 18:33 UTC
Labels: enhancement, triage
