### ISSUE TITLE
Can't download violent/graphic video from Facebook

### ISSUE THREAD

**Issue by ivo-ns** [yt-dlp/yt-dlp#7559] opened 2023-07-09 22:46 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Bulgaria

### Example URLs

https://www.facebook.com/ivon.mladenova/posts/7266440750037713/

### Provide a description that is worded well enough to be understood

I tried to download that has this:

![image](https://github.com/yt-dlp/yt-dlp/assets/121167698/b8511ead-214d-4619-8cf6-0ad191df470a)

I  clicked Learn more and then "See video":

![image](https://github.com/yt-dlp/yt-dlp/assets/121167698/326331f4-4ea5-4f0d-8422-bd25cdc28d77)

I'm able to see the video, but I'm unable to download it with yt-dlp.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'chrome', 'https://www.facebook.com/ivon.mladenova/posts/7266440750037713/']
[debug] User config "C:\Users\johnl\AppData\Roaming\yt-dlp\config.txt": ['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '-i', '-o', 'D:/Courses/%(title)s.%(ext)s', '--no-mtime']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2021-02-02-git-2367affc2c-full_build-www.gyan.dev, ffprobe 2021-02-02-git-2367affc2c-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\johnl\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\johnl\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 5966 cookies from chrome
[debug] cookie version breakdown: {'v10': 5970, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[facebook] Extracting URL: https://www.facebook.com/ivon.mladenova/posts/7266440750037713/
[facebook] 7266440750037713: Downloading webpage
[facebook] 7266440750037713: Downloading webpage
ERROR: [facebook] 7266440750037713: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\facebook.py", line 707, in _real_extract
  File "yt_dlp\extractor\facebook.py", line 654, in _extract_from_url
```

**Comment by bashonly** [comment] 2023-07-10 01:33
Probable duplicate of #4311

The error is being caused by yt-dlp's facebook extractor not working with cookies (#4311), but I suppose it's possible that even if the linked issue is resolved, the extractor may need an additional fix/improvement to be able to get graphic content

**Closed** 2024-03-03 21:17 UTC
Labels: duplicate, account-needed, site-bug, can-share-account, site:facebook
