### ISSUE TITLE
VK video now loading

### ISSUE THREAD

**Issue by avrutg** [yt-dlp/yt-dlp#4506] opened 2022-07-31 14:38 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

https://vk.com/video-33621085_456240177

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'Chromium', '-F', '-vU', 'https://vk.com/video-33621085_456240177']                                                                                                                     [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8                           [debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)                                                                 [debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0                                                       [debug] Checking exe version: ffmpeg -bsfs                                                                              [debug] Checking exe version: ffprobe -bsfs                                                                             [debug] Checking exe version: avprobe -bsfs                                                                             [debug] exe versions: ffmpeg n5.0-ffmpeg-windows-build-helpers (fdk,setts)                                              [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3                                                                                                                 [Cookies] Extracting cookies from chromium                                                                              [debug] Extracting cookies from: "C:\Users\avrutg\AppData\Local\Chromium\User Data\Default\Network\Cookies"             [debug] Found local state file at "C:\Users\avrutg\AppData\Local\Chromium\User Data\Local State"                        [Cookies] Extracted 2251 cookies from chromium                                                                          [debug] cookie version breakdown: {'v10': 2251, 'other': 0, 'unencrypted': 0}                                           [debug] Proxy map: {}                                                                                                   [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest                               Latest version: 2022.07.18, Current version: 2022.07.18                                                                 yt-dlp is up to date (2022.07.18)                                                                                       [debug] [vk] Extracting URL: https://vk.com/video-33621085_456240177                                                    [vk] -33621085_456240177: Downloading JSON metadata                                                                     ERROR: [vk] Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U                                                                            File "yt_dlp\extractor\common.py", line 644, in extract                                                                 File "yt_dlp\extractor\vk.py", line 328, in _real_extract                                                               File "yt_dlp\extractor\vk.py", line 55, in _download_payload                                                            File "yt_dlp\extractor\common.py", line 1004, in download_content                                                       File "yt_dlp\extractor\common.py", line 968, in download_handle                                                         File "yt_dlp\extractor\common.py", line 838, in _download_webpage_handle                                                File "yt_dlp\extractor\common.py", line 795, in _request_webpage                                                                                                                                                                                File "yt_dlp\extractor\common.py", line 777, in _request_webpage                                                        File "yt_dlp\YoutubeDL.py", line 3639, in urlopen                                                                       File "urllib\request.py", line 531, in open                                                                             File "urllib\request.py", line 640, in http_response                                                                    File "urllib\request.py", line 569, in error                                                                            File "urllib\request.py", line 502, in _call_chain                                                                      File "urllib\request.py", line 649, in http_error_default                                                             urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by pukkandan** [comment] 2022-07-31 14:49
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/4097

**Closed by pukkandan** 2022-07-31 14:49 UTC
Labels: site-bug, triage
