### ISSUE TITLE
[Patreon] 403 on profile URL

### ISSUE THREAD

**Issue by TheFrenchGhosty** [yt-dlp/yt-dlp#3631] opened 2022-05-03 21:57 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Multiples IP have been tried

### Description

All Patreon profiles `https://www.patreon.com/[USERNAME]` don't download and just 403 now. Posts URLs still work correctly.

I can share an account that pledges to 2 creators if needed.

### Verbose log

```shell
$ yt-dlp -vvv --cookies cookies.txt https://www.patreon.com/[REDACTED]/
[debug] Command-line config: ['-vvv', '--cookies', 'cookies.txt', 'https://www.patreon.com/[REDACTED]/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-[REDACTED]
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [PatreonUser] Extracting URL: https://www.patreon.com/[REDACTED]/
[PatreonUser] [REDACTED]: Downloading webpage
[download] Downloading playlist: [REDACTED]
[PatreonUser] [REDACTED]: Downloading posts page 1
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 767, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3601, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

[PatreonUser] playlist [REDACTED]: Downloading 0 videos
[download] Finished downloading playlist: [REDACTED]
```

**Comment by afterdelight** [comment] 2022-05-04 15:08
can you shaew both account so we can check

**Comment by qadfly** [comment] 2022-05-09 00:50
Can confirm - I am also getting a 403 Error on Patreon profiles, but individual posts work fine

**Comment by left1000** [comment] 2022-05-11 22:12
I have the same problem as well, I am thinking it's true in 100% of cases right now.

**Comment by AustinHasten** [comment] 2022-05-27 23:11
I have been getting this for probably months now. Changing my useragent does not help.

**Comment by afterdelight** [comment] 2022-05-29 02:39
is thos fixed yet?

**Comment by afterdelight** [comment] 2022-07-03 20:06
yes, give me your patreon id and password so i can test it

**Comment by AustinHasten** [comment] 2022-07-03 20:09
> yes, give me your patreon id and password so i can test it

Yeah I'm not giving creds to the guy who just posted "is thos fixed yet?"

**Comment by left1000** [comment] 2022-07-09 17:43
I am having this same issue, which is weird, because on may 11th 2022 I read some notes on this yt-dlp github that taught me how to make this command work. Either I've forgotten how to do it, or it no longer works as of now :(

**Comment by pukkandan** [comment] 2022-07-10 05:09
Yes, the issue is only about playlists. There is another issue open about patreon's own video player, but embedded videos still work

**Comment by pukkandan** [comment] 2022-07-10 05:13
@afterdelight Can you really try and solve the problem if I give you a patreon account? All your other comments point to the answer being NO. Phishing attempts will not be tolerated here. If you infact can, send me a mail and I will unban you after putting it to the test

**Comment by AustinHasten** [comment] 2022-07-10 17:32
I didn't have any issues with Patreon's video player just before the extractor stopped working outright. I have made a few local modifications to the extractor, can't remember if this is something I specifically fixed. The extractor isn't working for me even for any kind of individual post or else I would look into it and create a PR.

**Comment by left1000** [comment] 2022-07-10 18:38
I will say when using yt-dlp to download embedded vimeo videos from a single patreon post, I had to export my cookies like.... every 3or4 posts. I think patreon is closing sessions more rapidly now in defense against ripping tools perhaps? (I doubt this insight matters, but I left it out of my prior message)

**Comment by coletdjnz** [comment] 2022-07-18 08:50
I have a patreon account and I can reproduce. Related: https://github.com/mikf/gallery-dl/issues/1922, https://github.com/mikf/gallery-dl/issues/2627

Patreon seem to have a bit of anti-bot/scraping measures going on. Cloudflare+datadome.

I seem to be running into the cloudflare captcha a lot (I think that is the main cause of the 403s). (would it be useful to add some sort of captcha detection into core for better error message?)

I've tried messing around with a few things. 

gallery-dl seems to, at least in the past, work around cloudflare issues by disabling TLSv1.2, but that doesn't seem to work for me in yt-dlp if I force it.

However, using the mobile user agent is giving me a bit of success: `--user-agent "Patreon/7.6.28"`

**Closed** 2022-07-22 22:23 UTC
Labels: account-needed, site-bug, can-share-account
