### ISSUE TITLE
Canalplus extractor

### ISSUE THREAD

**Issue by l1l0l** [yt-dlp/yt-dlp#3803] opened 2022-05-19 21:37 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

canalplus.com extractor dosent work.

By the way, when I was reading  the code I've noticed that in the extractor(canalplus.py), the _VALID_URL dosent  seem to be ok. For your information, the new domain name of Canalplus is canalplus.com  (the old one mycanal.fr redirect to canalplus.com)

_* verbose log edited_

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.canalplus.com/divertissement/tpmp-week-end-le-beforeemission-du-13-mai-2022/h/17039434_50013?episodeId=18785284_50013']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.0 (CPython 64bit) - macOS-10.16-x86_64-i386-64bit
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://www.canalplus.com/divertissement/tpmp-week-end-le-beforeemission-du-13-mai-2022/h/17039434_50013?episodeId=18785284_50013
[generic] 17039434_50013?episodeId=18785284_50013: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 17039434_50013?episodeId=18785284_50013: Downloading webpage
[generic] 17039434_50013?episodeId=18785284_50013: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.canalplus.com/divertissement/tpmp-week-end-le-beforeemission-du-13-mai-2022/h/17039434_50013?episodeId=18785284_50013
Traceback (most recent call last):
  File "/Users/anass/anaconda3/envs/home_media/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/anass/anaconda3/envs/home_media/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/anass/anaconda3/envs/home_media/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/Users/anass/anaconda3/envs/home_media/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 4031, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.canalplus.com/divertissement/tpmp-week-end-le-beforeemission-du-13-mai-2022/h/17039434_50013?episodeId=18785284_50013
```

**Comment by HobbyistDev** [comment] 2022-06-26 11:29
Related / duplicate of #461

**Closed** 2022-06-26 12:00 UTC
Labels: site-bug, triage
