### ISSUE TITLE
[ABC iView] ERROR: Data must be padded to 16 byte boundary in CBC mode

### ISSUE THREAD

**Issue by schmidtp72** [yt-dlp/yt-dlp#10251] opened 2024-06-23 23:28 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

I'm having issues with the above error on ABC iView. yt-dlp has worked previously, however these new episodes seem to get this particular error. The error seems to produce itself on random fragments, however when re-running the same command without removing the previous attempt, it will fail at the same segment. I've also tried using the option --no-resize-buffer which got the download a bit further (from 71/171 up to segment 165/171)

Before submitting, I updated to the latest build and then nightly. The errors still present. I've also tried youtube-dl.exe which results in errors as well. This error seems to only be on the Windows version. If I run yt-dlp on Linux (Fedora) with the same link, the download completes without error.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://iview.abc.net.au/video/LE2302V003S00', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.22.232706 from yt-dlp/yt-dlp-nightly-builds [a8520244b] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.2.3, ffprobe 6.1.1-essentials_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.22.232706 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.22.232706 from yt-dlp/yt-dlp-nightly-builds)
[debug] Using fake IP 1.150.133.8 (AU) as X-Forwarded-For
[abc.net.au:iview] Extracting URL: https://iview.abc.net.au/video/LE2302V003S00
[abc.net.au:iview] LE2302V003S00: Downloading JSON metadata
[abc.net.au:iview] LE2302V003S00: Downloading webpage
[abc.net.au:iview] LE2302V003S00: Downloading m3u8 information
WARNING: [abc.net.au:iview] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] LE2302V003S00: Downloading 1 format(s): hls-2093
[debug] Invoking hlsnative downloader on "https://iview-vod-hls.akamaized.net/prod/le2/LE2302V003S00MA1D1/20240621133604/hls/4500000/hdntl=exp=1719269142~acl=%2f*~data=hdntl~hmac=603509b7cd7bdab5dc7e7acdf564f4bccc0a50e3c5738f2f0a2ffdccdce07416/stream.m3u8?aka_me_session_id=AAAAAAAAAAAW93lmAAAAACk6MPYnOg2yjseEgSyRexmGCVMmLuCMhhjoJ2RGkHfwdX7XW54N64s%2fkEEn+%2fnYDowz555n2bzl&aka_media_format_type=hls"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 171
[download] Destination: Series 11 Ep 3 Montaigne, Greg Larsen, Nooky & Zoe Coombs Marr [LE2302V003S00].mp4
[debug] File locking is not supported. Proceeding without locking
[download] Series 11 Ep 3 Montaigne, Greg Larsen, Nooky & Zoe Coombs Marr [LE2302V003S00].mp4.part-Frag165 has already been downloaded
[download]  95.7% of ~ 418.52MiB at      0.00B/s ETA Unknown (frag 165/171)ERROR: Data must be padded to 16 byte boundary in CBC mode
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1605, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1820, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2993, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3459, in process_info
  File "yt_dlp\YoutubeDL.py", line 3180, in dl
  File "yt_dlp\downloader\common.py", line 466, in download
  File "yt_dlp\downloader\hls.py", line 381, in real_download
  File "yt_dlp\downloader\fragment.py", line 516, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 364, in decrypt_fragment
  File "yt_dlp\aes.py", line 11, in aes_cbc_decrypt_bytes
  File "Cryptodome\Cipher\_mode_cbc.py", line 246, in decrypt
ValueError: Data must be padded to 16 byte boundary in CBC mode
```

**Comment by bashonly** [comment] 2024-06-23 23:33
Duplicate of #3810

Workaround: pass `--downloader ffmpeg` to yt-dlp

**Closed by bashonly** 2024-06-23 23:33 UTC
Labels: site-bug, triage

**Comment by schmidtp72** [comment] 2024-06-24 00:28
I put a comment in [https://github.com/yt-dlp/yt-dlp/issues/3810](url)
--downleader ffmeg 
worked for Windows
