### ISSUE TITLE
coverage of youtube community posts

### ISSUE THREAD

**Issue by zyrup** [yt-dlp/yt-dlp#7015] opened 2023-05-08 12:11 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

international

### Example URLs

https://www.youtube.com/@JustSomeGuy/community

### Provide a description that is worded well enough to be understood

Ability to download youtube community posts content through yt-dlp

See documentation: https://support.google.com/youtube/answer/9409631

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.7.16 (CPython x86_64 64bit) - Darwin-20.6.0-x86_64-i386-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-90069-gdd8351b118-tessus, rtmpdump 2.4
[debug] Optional libraries: no_Cryptodome-None, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)
```

**Comment by Lesmiscore** [comment] 2023-05-08 12:32
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3883

**Closed by Lesmiscore** 2023-05-08 12:32 UTC
Labels: site-enhancement, triage

**Comment by zyrup** [comment] 2023-05-08 12:47
@Lesmiscore what is the status here, there doesn't seem to be an official response why this feature-request is being ignored. Adding wontfix is not helpful, it would be nice to have actual collaborators here.

**Comment by pukkandan** [comment] 2023-05-08 17:27
yt-dlp is for downloading video/audio and its metadata, not for text, images etc. The video in community posts, if any gets downloaded just fine.

**Comment by zyrup** [comment] 2023-05-08 17:32
Well one could also interpret the community posts as metadata since they usually concern themselves about the videos

**Comment by Bakr-Ali** [comment] 2023-11-11 20:33
> Use other tools for community posts

Do you know any tool for archiving community posts? I found this discussion while looking for one and I hope you know any such tools? @Lesmiscore
