### ISSUE TITLE
[Broken] YouTube comment downloading

### ISSUE THREAD

**Issue by L33Tech** [yt-dlp/yt-dlp#541] opened 2021-07-21 20:47 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.07.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
E:\YTDL\Test>yt-dlp -v https://www.youtube.com/watch?v=ESrGecuBY-I-zHHQ -o '%(channel)s-%(upload_date)s-%(title)s-%(id)s.%(ext)s' -o 'thumbnail,subtitle,description,annotation,infojson:%(channel)s-%(upload_date)s-%(title)s-%(id)s\%(channel)s-%(upload_date)s-%(title)s-%(id)s.%(ext)s' --datebefore 20170101 --match-filter "availability = 'unlisted'" --format "((571/272/402/337/315/313/401/336/308/400/271/335/303/299/399/137/248/334/302/298/398/247/136/333/244/135/397/332/243/134/396/331/242/133/395/330/160/394/278)[protocol!=http_dash_segments])+(bestaudio[acodec=opus]/bestaudio[protocol!=http_dash_segments])/best" --write-annotations --write-description --write-info-json --write-thumbnail --embed-thumbnail --write-comments --add-metadata --fixup warn --geo-bypass --no-call-home --write-url-link --write-subs --write-playlist-metafiles --download-archive downloaded.txt
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=ESrGecuBY-I-zHHQ', '-o', "'%(channel)s-%(upload_date)s-%(title)s-%(id)s.%(ext)s'", '-o', "'thumbnail,subtitle,description,annotation,infojson:%(channel)s-%(upload_date)s-%(title)s-%(id)s\\%(channel)s-%(upload_date)s-%(title)s-%(id)s.%(ext)s'", '--datebefore', '20170101', '--match-filter', "availability = 'unlisted'", '--format', '((571/272/402/337/315/313/401/336/308/400/271/335/303/299/399/137/248/334/302/298/398/247/136/333/244/135/397/332/243/134/396/331/242/133/395/330/160/394/278)[protocol!=http_dash_segments])+(bestaudio[acodec=opus]/bestaudio[protocol!=http_dash_segments])/best', '--write-annotations', '--write-description', '--write-info-json', '--write-thumbnail', '--embed-thumbnail', '--write-comments', '--add-metadata', '--fixup', 'warn', '--geo-bypass', '--no-call-home', '--write-url-link', '--write-subs', '--write-playlist-metafiles', '--download-archive', 'downloaded.txt']
[debug] Loading archive file 'downloaded.txt'

[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.07 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-04-25-git-d98884be41-full_build-www.gyan.dev, ffprobe 2021-04-25-git-d98884be41-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=ESrGecuBY-I-zHHQ
[youtube] ESrGecuBY-I: Downloading webpage
[youtube] ESrGecuBY-I: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] ESrGecuBY-I: Downloading 1 format(s): 298+251
[youtube] Downloading initial comment continuation page
WARNING: [youtube] Incomplete data received. Retrying ...
[youtube] Downloading initial comment continuation page (retry #1)
WARNING: [youtube] Incomplete data received. Retrying ...
[youtube] Downloading initial comment continuation page (retry #2)
WARNING: [youtube] Incomplete data received. Retrying ...
[youtube] Downloading initial comment continuation page (retry #3)
ERROR: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1142, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1178, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1219, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2198, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2358, in process_info
  File "yt_dlp\YoutubeDL.py", line 2860, in post_extract
  File "yt_dlp\YoutubeDL.py", line 2852, in actual_post_extract
  File "yt_dlp\extractor\youtube.py", line 2927, in <lambda>
  File "yt_dlp\extractor\youtube.py", line 2157, in _extract_comments
  File "yt_dlp\extractor\youtube.py", line 2080, in _comment_entries
yt_dlp.utils.ExtractorError: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.


```

## Description

When trying to download this video, the comment download fails. It said to report the issue, so I'm doing so. The provided URL to test is a random one, but all comment downloads seem broken. Please let me know if there's any other required info, and thanks for the great work!

**Comment by colethedj** [comment] 2021-07-21 20:52
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/507
Fixed by: https://github.com/yt-dlp/yt-dlp/pull/466

**Comment by llacb47** [comment] 2021-07-21 20:52
https://github.com/yt-dlp/yt-dlp/issues/531#issuecomment-882665207

**Comment by L33Tech** [comment] 2021-07-21 20:54
Oh I thought that other issue was specific to the android extractor... my bad.

**Comment by colethedj** [comment] 2021-07-21 20:55
> Oh I thought that other issue was specific to the android extractor... my bad.

Yeah, sorry. I've renamed that issue now for the time-being. The fix will be in the next release.

**Closed** 2021-07-21 20:54 UTC
Labels: duplicate

**Comment by L33Tech** [comment] 2021-07-21 20:58
Will the next release be soon? I'm trying to archive videos that will be removed by YouTube on the 23rd. If not I'll try to build or run from source myself. Thanks!

**Comment by pukkandan** [comment] 2021-07-21 21:08
@L33Tech Just created now

**Comment by L33Tech** [comment] 2021-07-21 21:08
@pukkandan AWESOME, thank you so much!
