### ISSUE TITLE
This is the error I get when trying to download video from pornhub. Here is the verbose log

### ISSUE THREAD

**Issue by ronnynonymous88** [yt-dlp/yt-dlp#11032] opened 2024-09-18 05:03 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

This is the error I get when trying to download video from pornhub. Here is the verbose log

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
F:\YT-DLP>yt-dlp --verbose  https://www.pornhub.com/view_video.php?viewkey=676811419
[debug] Command-line config: ['--verbose', 'https://www.pornhub.com/view_video.php?viewkey=676811419']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds [4a9bc8c36] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-09-16-git-76ff97cef5-full_build-www.gyan.dev (setts), ffprobe 2024-09-16-git-76ff97cef5-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1835 extractors
[PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=676811419
[PornHub] 676811419: Downloading pc webpage
ERROR: [PornHub] 676811419: Unable to extract title; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\pornhub.py", line 305, in _real_extract
  File "yt_dlp\extractor\common.py", line 1381, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1345, in _search_regex
```

**Comment by grqz** [comment] 2024-09-18 05:46
cant reproduce...

<details><summary>logs</summary>

```log
[debug] Command-line config: ['-vUF', 'https://www.pornhub.com/view_video.php?viewkey=676811419']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.14.232748 from yt-dlp/yt-dlp-nightly-builds [a06bb5867] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116607-gdeee00e2eb-20240812 (setts), ffprobe N-116607-gdeee00e2eb-20240812
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: GetPOT (YoutubeIE)
[debug] Plugin directories: ['C:\\Users\\Admin\\Downloads\\yt-dlp\\yt-dlp-plugins\\bgutil-ytdlp-pot-provider.zip\\yt_dlp_plugins', 'C:\\Users\\Admin\\Downloads\\yt-dlp\\yt-dlp-plugins\\yt-dlp-get-pot.zip\\yt_dlp_plugins']
[debug] Loaded 1835 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.09.17.232940/SHA2-256SUMS
Current version: nightly@2024.09.14.232748 from yt-dlp/yt-dlp-nightly-builds
Latest version: nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds
Current Build Hash: 0a138b25af88488681104db132b2b3551c3f072b5ab0b7dfd84db0e24dc7862c
Updating to nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.09.17.232940/yt-dlp.exe
Updated yt-dlp to nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds
[debug] Restarting: yt-dlp.exe -vUF "https://www.pornhub.com/view_video.php?viewkey=676811419"
[debug] Command-line config: ['-vUF', 'https://www.pornhub.com/view_video.php?viewkey=676811419']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds [4a9bc8c36] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116607-gdeee00e2eb-20240812 (setts), ffprobe N-116607-gdeee00e2eb-20240812
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: GetPOT (YoutubeIE)
[debug] Plugin directories: ['C:\\Users\\Admin\\Downloads\\yt-dlp\\yt-dlp-plugins\\bgutil-ytdlp-pot-provider.zip\\yt_dlp_plugins', 'C:\\Users\\Admin\\Downloads\\yt-dlp\\yt-dlp-plugins\\yt-dlp-get-pot.zip\\yt_dlp_plugins']
[debug] Loaded 1835 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds)
[PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=676811419
[PornHub] 676811419: Downloading pc webpage
[PornHub] 676811419: Downloading m3u8 information
[PornHub] 676811419: Downloading m3u8 information
[PornHub] 676811419: Downloading m3u8 information
[PornHub] 676811419: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 676811419:
ID       EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC      ACODEC
────────────────────────────────────────────────────────────────────────────
240p     mp4 240p           │                  https │ unknown     unknown
hls-293  mp4 426x240     25 │ ~ 32.91MiB  293k m3u8  │ avc1.640015 mp4a.40.2
480p     mp4 480p           │                  https │ unknown     unknown
hls-644  mp4 854x480     25 │ ~ 72.26MiB  644k m3u8  │ avc1.64001e mp4a.40.2
720p     mp4 720p           │                  https │ unknown     unknown
hls-1326 mp4 1280x720    25 │ ~148.85MiB 1327k m3u8  │ avc1.64001f mp4a.40.2
```

</details>

**Comment by bashonly** [comment] 2024-09-18 15:44
Duplicate of #9889

the site is blocked in your region

**Closed by bashonly** 2024-09-18 15:44 UTC
Labels: question, cant-reproduce

**Comment by dirkf** [comment] 2025-02-16 02:07
The age verification prompt in the UK (for now) and presumably in mainland Europe is just an overlay over the rest of the page that loads as normally as it does in a browser with JS disabled: the prompt doesn't even appear since it's populated by JS (with text like "This website contains age-restricted materials including nudity and explicit depictions of sexual activity. By entering, you affirm that you are at least 18 years of age or the age of majority in the jurisdiction you are accessing the website from and you consent to viewing sexually explicit content.", depending on your selected language). The prompt has no effect on extraction.

The "age verification" message sent in Texas, etc, says that the local law on age verification is so onerous and/or wrong-headed that Aylo won't send the page at all.

In either case no amount of cookies affects basic video extraction, though features only available when logged in (if the extractor has any) will require them.
