### ISSUE TITLE
Only part of video was downloaded

### ISSUE THREAD

**Issue by Wilann** [yt-dlp/yt-dlp#3700] opened 2022-05-10 18:49 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Description

When downloading [this](https://www.youtube.com/watch?v=rpe5xxPagtk) video of 4h 24min long, the downloaded file is only 4h long. It seems the first 24 minutes didn't get downloaded. 

Here's the `ffprobe` of the file, since it may take too long to download to debug:
```
ffprobe "BWF Thomas Cup Finals 2022 _ Japan vs. England _ Group D [rpe5xxPagtk].mkv"
ffprobe version 4.2.4-1ubuntu0.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-liblensfun --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from 'BWF Thomas Cup Finals 2022 _ Japan vs. England _ Group D [rpe5xxPagtk].mkv':
  Metadata:
    HTTP://YOUTUBE.COM/STREAMING/METADATA/SEGMENT/102015: Sequence-Number: 296 
                    : Ingestion-Walltime-Us: 1652167490136049 
                    : Ingestion-Uncertainty-Us: 74 
                    : Stream-Duration-Us: 1480000000 
                    : Max-Dvr-Duration-Us: 14400000000 
                    : Target-Duration-Us: 5000000 
                    : Streamable: T 
                    : First-Frame-Time-Us: 1652167490739888 
                    : First-Frame-Uncertainty-Us: 68 
                    : Encoding-Alias: L1_Bg 
                    :  
                    : 
    ENCODER         : Lavf58.29.100
  Duration: 03:59:56.35, start: 0.000000, bitrate: 2008 kb/s
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      DURATION        : 03:59:56.333000000
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      HANDLER_NAME    : ISO Media file produced by Google Inc.
      DURATION        : 03:59:56.348000000
```

### Verbose log

```shell
[debug] Command-line config: ['-i', 'https://www.youtube.com/watch?v=rpe5xxPagtk', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.15.15-76051515-generic-x86_64-with-glibc2.31
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=rpe5xxPagtk
[youtube] rpe5xxPagtk: Downloading webpage
[youtube] rpe5xxPagtk: Downloading android player API JSON
[youtube] rpe5xxPagtk: Downloading m3u8 information
WARNING: [youtube] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] rpe5xxPagtk: Downloading MPD manifest
WARNING: [youtube] Ignoring subtitle tracks found in the DASH manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] rpe5xxPagtk: Downloading m3u8 information
[youtube] rpe5xxPagtk: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] rpe5xxPagtk: Downloading 1 format(s): 248+140
WARNING: Requested formats are incompatible for merge and will be merged into mkv
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1652226476/ei/TKV6YsGnCPmBir4PlI-KkAI/ip/216.58.16.107/id/rpe5xxPagtk.2/source/yt_live_broadcast/requiressl/yes/tx/24027708/txs/24027707%2C24027708%2C24027709%2C24027710%2C24067856/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/force_finished/1/gcr/ca/vprv/1/pacing/0/itag_bl/376%2C377%2C384%2C385%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24001373%2C24007246/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Cas%2Cforce_finished%2Cgcr%2Cvprv%2Citag%2Cplaylist_type/sig/AOq0QJ8wRQIgMFrXq5aWlcZJeMZEtoutZ8tpJSgTmfSWBRBjG-7TXucCIQCqbsViszUeGhFnVaRLKxZO3yYHpnHekaG3zAw3Z0lvpQ%3D%3D"
[dashsegments] Total fragments: 2879
[download] Destination: BWF Thomas Cup Finals 2022 _ Japan vs. England _ Group D [rpe5xxPagtk].f248.webm
[download] 100% of 3.15GiB in 37:28
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1652226476/ei/TKV6YsGnCPmBir4PlI-KkAI/ip/216.58.16.107/id/rpe5xxPagtk.2/source/yt_live_broadcast/requiressl/yes/tx/24027708/txs/24027707%2C24027708%2C24027709%2C24027710%2C24067856/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/force_finished/1/gcr/ca/vprv/1/pacing/0/itag_bl/376%2C377%2C384%2C385%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24001373%2C24007246/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Cas%2Cforce_finished%2Cgcr%2Cvprv%2Citag%2Cplaylist_type/sig/AOq0QJ8wRQIgMFrXq5aWlcZJeMZEtoutZ8tpJSgTmfSWBRBjG-7TXucCIQCqbsViszUeGhFnVaRLKxZO3yYHpnHekaG3zAw3Z0lvpQ%3D%3D"
[dashsegments] Total fragments: 2879
[download] Destination: BWF Thomas Cup Finals 2022 _ Japan vs. England _ Group D [rpe5xxPagtk].f140.m4a
[download] 100% of 225.07MiB in 18:46
[Merger] Merging formats into "BWF Thomas Cup Finals 2022 _ Japan vs. England _ Group D [rpe5xxPagtk].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:BWF Thomas Cup Finals 2022 _ Japan vs. England _ Group D [rpe5xxPagtk].f248.webm' -i 'file:BWF Thomas Cup Finals 2022 _ Japan vs. England _ Group D [rpe5xxPagtk].f140.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:BWF Thomas Cup Finals 2022 _ Japan vs. England _ Group D [rpe5xxPagtk].temp.mkv'
Deleting original file BWF Thomas Cup Finals 2022 _ Japan vs. England _ Group D [rpe5xxPagtk].f140.m4a (pass -k to keep)
Deleting original file BWF Thomas Cup Finals 2022 _ Japan vs. England _ Group D [rpe5xxPagtk].f248.webm (pass -k to keep)
```

**Comment by krichbanana** [comment] 2022-05-10 20:18
it says Live Mode "Post-Live Manifestless" in the "Stats for nerds" when you right-click the video, which means the video hasn't finished processing yet. It's a known issue that livestreams may not download properly for some time after the stream ends, ranging from minutes to possibly days.

Either wait a while longer for it to finish, or select an alternative format with "-f 137+140"

**Comment by Wilann** [comment] 2022-05-10 20:27
Thanks so much for your response! Is there a way to automatically select `-f 137+140` if the video hasn't finished processing yet? I'm currently using: `-f "bestvideo+bestaudio[ext=m4a]/best"`

**Comment by krichbanana** [comment] 2022-05-10 23:02
I don't believe there is currently a way to automatically determine whether a video or format has finished processing and selecting a format based on that. You would have to check beforehand. If you list the formats with `-F`, any format with the tilde `~` next to the filesize could *potentially* be incomplete. If you don't see any storyboard formats or formats without the `~` next to the size, then the video is likely still processing.

I think if you know if the video is not yet processed, then `-f 'bv[vcodec!=vp9]+ba[ext=m4a]'` should do what you want. It should work even for processed videos as well.

**Comment by pukkandan** [comment] 2022-05-11 04:18
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1564

**Closed by pukkandan** 2022-05-11 04:18 UTC
Labels: site-bug, triage

**Comment by Wilann** [comment] 2022-05-11 18:40
Thanks for the suggestion @krichbanana. I tried using `-f 'bv[vcodec!=vp9]+ba[ext=m4a]`, but it seems to be inconsistent. It's hard to demonstrate for a specific video. I understand that this issue is being worked on - will wait for it to be fixed.

In the mean time, is there a way to `-i` a playlist, and only download videos, let's say, 12 hours after the live has ended? This way I can hope that within that time the video will be finished processing.
