### ISSUE TITLE
Can't download Bangumi from bilibili

### ISSUE THREAD

**Issue by xmduhan** [yt-dlp/yt-dlp#4411] opened 2022-07-22 03:01 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Provide a description that is worded well enough to be understood

I try to download bangumi with url: https://www.bilibili.com/bangumi/play/ss37587 and it failed.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
e$ yt-dlp -vU https://www.bilibili.com/bangumi/play/ss37587
[debug] Command-line config: ['-vU', 'https://www.bilibili.com/bangumi/play/ss37587']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.4 (CPython 64bit) - Linux-5.15.0-41-generic-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {'https': 'http://192.168.2.1:1081', 'http': 'http://192.168.2.1:1081'}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://www.bilibili.com/bangumi/play/ss37587
[generic] ss37587: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] ss37587: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.bilibili.com/bangumi/play/ss37587
Traceback (most recent call last):
  File "/home/duhan/source/bbgame/.pygame/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/home/duhan/source/bbgame/.pygame/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1506, in __extract_info
    ie_result = ie.extract(url)
  File "/home/duhan/source/bbgame/.pygame/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/home/duhan/source/bbgame/.pygame/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 4108, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.bilibili.com/bangumi/play/ss37587
```

**Comment by Lesmiscore** [comment] 2022-07-22 03:31
Duplicate of #1878

**Closed by Lesmiscore** 2022-07-22 03:31 UTC
Labels: site-bug, triage
