### ISSUE TITLE
Brighteon.com videos cant download.  An extractor error has occurred. (caused by KeyError('sourceURL'));

### ISSUE THREAD

**Issue by quasher2024** [yt-dlp/yt-dlp#10361] opened 2024-07-05 18:23 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

I cant tell if this issue is closed or still open.  Closed tab says "this issue was solved in youtube-dl  But when I try to download that program I get, "unavailable for legal reasons"  I did see an "open" tag too, but that went into a discussion about mpd manifests,  didnt say pending solution, or tell us to wait for a solution or any other instructions, just the dead end info about mpd manifests not being passed on to ytd-dl.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU https://www.brighteon.com/5c92f796-a5e5-45bf-a027-4f35cf788519
[debug] Command-line config: ['-vU', 'https://www.brighteon.com/5c92f796-a5e5-45bf-a027-4f35cf788519']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-106-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5, websockets-9.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.02 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.02 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.brighteon.com/5c92f796-a5e5-45bf-a027-4f35cf788519
[generic] 5c92f796-a5e5-45bf-a027-4f35cf788519: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 5c92f796-a5e5-45bf-a027-4f35cf788519: Extracting information
[debug] Looking for embeds
[html5] 5c92f796-a5e5-45bf-a027-4f35cf788519: Downloading m3u8 information
[html5] 5c92f796-a5e5-45bf-a027-4f35cf788519: Downloading MPD manifest
ERROR: An extractor error has occurred. (caused by KeyError('sourceURL')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/fran-desktop/scripts/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/home/fran-desktop/scripts/yt-dlp/yt_dlp/extractor/generic.py", line 2516, in _real_extract
    embeds = list(self._extract_embeds(original_url, webpage, urlh=full_response, info_dict=info_dict))
  File "/home/fran-desktop/scripts/yt-dlp/yt_dlp/extractor/generic.py", line 2545, in _extract_embeds
    current_embeds.append(next(gen))
  File "/home/fran-desktop/scripts/yt-dlp/yt_dlp/extractor/common.py", line 3885, in extract_from_webpage
    for info in ie._extract_from_webpage(url, webpage) or []:
  File "/home/fran-desktop/scripts/yt-dlp/yt_dlp/extractor/genericembeds.py", line 24, in _extract_from_webpage
    entries = self._parse_html5_media_entries(url, webpage, video_id, m3u8_id='hls') or []
  File "/home/fran-desktop/scripts/yt-dlp/yt_dlp/extractor/common.py", line 3227, in _parse_html5_media_entries
    is_plain_url, formats = _media_formats(src, media_type, f)
  File "/home/fran-desktop/scripts/yt-dlp/yt_dlp/extractor/common.py", line 3180, in _media_formats
    formats = self._extract_mpd_formats(
  File "/home/fran-desktop/scripts/yt-dlp/yt_dlp/extractor/common.py", line 2606, in _extract_mpd_formats
    fmts, subs = self._extract_mpd_formats_and_subtitles(*args, **kwargs)
  File "/home/fran-desktop/scripts/yt-dlp/yt_dlp/extractor/common.py", line 2613, in _extract_mpd_formats_and_subtitles
    return self._merge_mpd_periods(periods)
  File "/home/fran-desktop/scripts/yt-dlp/yt_dlp/extractor/common.py", line 2655, in _merge_mpd_periods
    for period in periods:
  File "/home/fran-desktop/scripts/yt-dlp/yt_dlp/extractor/common.py", line 2857, in _parse_mpd_periods
    representation_ms_info = extract_multisegment_info(representation, adaption_set_ms_info)
  File "/home/fran-desktop/scripts/yt-dlp/yt_dlp/extractor/common.py", line 2737, in extract_multisegment_info
    extract_Initialization(segment_list)
  File "/home/fran-desktop/scripts/yt-dlp/yt_dlp/extractor/common.py", line 2732, in extract_Initialization
    ms_info['initialization_url'] = initialization.attrib['sourceURL']
KeyError: 'sourceURL'
```

**Comment by bashonly** [comment] 2024-07-05 18:27
Duplicate of #8269

**Closed by bashonly** 2024-07-05 18:27 UTC
Labels: site-bug, triage

**Comment by mrkapqa** [comment] 2024-08-22 13:53
still receiving this error as of August 22. 2024
like here

https://www.brighteon.com/a5b31f9e-b523-4171-b875-1d795cbfbcbb

`yt-dlp 'https://www.brighteon.com/a5b31f9e-b523-4171-b875-1d795cbfbcbb'
[generic] Extracting URL: https://www.brighteon.com/a5b31f9e-b523-4171-b875-1d795cbfbcbb
[generic] a5b31f9e-b523-4171-b875-1d795cbfbcbb: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] a5b31f9e-b523-4171-b875-1d795cbfbcbb: Extracting information
[html5] a5b31f9e-b523-4171-b875-1d795cbfbcbb: Downloading m3u8 information
[html5] a5b31f9e-b523-4171-b875-1d795cbfbcbb: Downloading MPD manifest
ERROR: An extractor error has occurred. (caused by KeyError('sourceURL')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
`
`yt-dlp -U
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)`
