### ISSUE TITLE
HTTP 404 Error on arte.tv

### ISSUE THREAD

**Issue by itsek** [yt-dlp/yt-dlp#3649] opened 2022-05-05 09:31 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Tried to download Video, URL:
https://www.arte.tv/de/videos/108825-000-A/heller-weg/

gives this verbose error:

### Verbose log

```shell
yt-dlp "https://www.arte.tv/de/videos/108825-000-A/heller-weg/" -vU
[debug] Command-line config: ['https://www.arte.tv/de/videos/108825-000-A/heller-weg/', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.15.0-27-generic-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [ArteTV] Extracting URL: https://www.arte.tv/de/videos/108825-000-A/heller-weg/
[ArteTV] 108825-000-A: Downloading JSON metadata
ERROR: [ArteTV] 108825-000-A: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/eugen/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/home/eugen/.local/lib/python3.10/site-packages/yt_dlp/extractor/arte.py", line 57, in _real_extract
    info = self._download_json(
  File "/home/eugen/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1029, in _download_json
    res = self._download_json_handle(
  File "/home/eugen/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1008, in _download_json_handle
    res = self._download_webpage_handle(
  File "/home/eugen/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 800, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/eugen/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 785, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/eugen/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 767, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/eugen/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3601, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
`
```

**Comment by NanaMizukiAnother7** [comment] 2022-05-05 09:37
#3622

**Comment by Lesmiscore** [comment] 2022-05-05 09:40
Duplicate of #3622

**Closed** 2022-05-05 09:40 UTC
Labels: bug, triage
