### ISSUE TITLE
Soundcloud 404 and 429 errors ending download despite -ciw flag

### ISSUE THREAD

**Issue by DunnesH** [yt-dlp/yt-dlp#3118] opened 2022-03-19 14:29 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

I download from a txt file of artist profiles. If one artist changes their profile url normally yt-dlp would just return an error but keep downloading to the next one. Since the update, every time I get a 404 (profile not found) or 429 (too many requests) anywhere during the download it cascades into more errors and ends the download, despite using -ciw flag.

Thanks!

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-ciw', 'https://soundcloud.com/profilethatdoesntexist']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] Loading soundcloud.client_id from cache
[debug] [soundcloud:user] Extracting URL: https://soundcloud.com/profilethatdoesntexist
[soundcloud:user] profilethatdoesntexist: Downloading user info
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 735, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3591, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\soundcloud.py", line 795, in _real_extract
  File "yt_dlp\extractor\soundcloud.py", line 99, in _download_json
  File "yt_dlp\extractor\common.py", line 997, in _download_json
  File "yt_dlp\extractor\common.py", line 976, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 768, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 753, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [soundcloud:user] Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 864, in main
  File "yt_dlp\__init__.py", line 854, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3254, in download
  File "yt_dlp\YoutubeDL.py", line 3227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1380, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1407, in wrapper
  File "yt_dlp\utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
[19756] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by pukkandan** [comment] 2022-03-19 14:33
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2993

This seems to be a more serious issue than I initially thought.

Because of this and a few other serious bugs, I'll see if I can get a new release out asap

**Closed** 2022-03-26 03:08 UTC
Labels: bug, duplicate

**Comment by awsms** [comment] 2022-04-25 17:28
I'm still having this same exact issue on yt-dlp 2022.04.08 with a Go+ account

**Comment by mkdior** [comment] 2024-05-28 08:18
> I'm still having this same exact issue on yt-dlp 2022.04.08 with a Go+ account

429's? The soundcloud API has a download rate limit, so after n~ downloads it blocks your token for an hour or two. @pukkandan, the issue here is, I'm not sure if this is shared amongst all yt-dlp services, but in my case, I use the `archive` option, but it seems to still send the request to soundcloud for that one archived song, which results in a rate-limit, practically always around the same song.

Imagine I have 20K songs in the queue, the first 500 are registered in the archive, for some reason, each time I hit the 500 mark, I get the rate limit, so for the first run, that's fine, but on the second run, after the 429 has expired, it will go through the list, send requests all the way up to song 500, and correctly mark them all as archived, thus skipping them, but it will hit the 429 rate limit, because it send the requests for those items.

Is it possible to store the urls in the archive as well, so we can skip the archived values altogether without wasting a request?

**Comment by bashonly** [comment] 2024-05-28 14:21
@mkdior  the latest version of yt-dlp lets you work around the rate-limit with the `--retry-sleep` and `--extractor-retries` options

**Comment by mkdior** [comment] 2024-05-28 17:55
> --retry-sleep



> @mkdior the latest version of yt-dlp lets you work around the rate-limit with the `--retry-sleep` and `--extractor-retries` options

Hey there,

Hope all is well. Thank you for your reply. Do you have any idea if what I said is actually happening though, is a request sent for an archived entry? Genuinely curious! I'm running my script now with your mentioned options, again, thanks for that.

**Comment by bashonly** [comment] 2024-05-28 18:18
> Do you have any idea if what I said is actually happening though, is a request sent for an archived entry? 

The true `id` of the URL cannot be determined without performing extraction, so yes, a request is being sent for the archived entry.

You may also be interested in the newly-added `formats` extractor-arg for soundcloud, which lets you control the number of API requests made per URL: https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#soundcloud
