### ISSUE TITLE
[youtube] ERROR: fragment 1 not found, unable to continue

### ISSUE THREAD

**Issue by zone559** [yt-dlp/yt-dlp#8380] opened 2023-10-19 02:42 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

yt-dlp automatically picking video format that does not work.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Desktop\Downloads\yt-dlp>yt-dlp --verbose https://www.youtube.com/watch?v=KIaGP41BO90
[debug] Command-line config: ['--verbose', 'https://www.youtube.com/watch?v=KIaGP41BO90']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=KIaGP41BO90
[youtube] KIaGP41BO90: Downloading webpage
[youtube] KIaGP41BO90: Downloading ios player API JSON
[youtube] KIaGP41BO90: Downloading android player API JSON
[youtube] KIaGP41BO90: Downloading m3u8 information
[youtube] KIaGP41BO90: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] KIaGP41BO90: Downloading 1 format(s): 248+251
[debug] Invoking dashsegments downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1697704515/ei/45UwZe-vBp6VsfIPh4Oe4Aw/ip/76.114.49.72/id/2886863f8d413bdd/source/youtube/requiressl/yes/playback_host/rr3---sn-jvhj5nu-nh4z.googlevideo.com/mh/sy/mm/31%2C29/mn/sn-jvhj5nu-nh4z%2Csn-n4v7snls/ms/au%2Crdu/mv/m/mvi/3/pcm2cms/yes/pl/22/tx/51018870/txs/51018864%2C51018865%2C51018866%2C51018867%2C51018868%2C51018869%2C51018870/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1446250/spc/UWF9fzdRhk8UpKxgZH915YQWBC40Elhn8k7hS-4I9w/vprv/1/mt/1697682541/fvip/2/keepalive/yes/fexp/24007246/beids/24350018/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cspc%2Cvprv%2Citag/sig/AGM4YrMwRAIgLF9g0JM4yaie2nMNLH6PePxOng0DYn34W_7ZvPM4uRgCIEqr9WZv1EF8AOhkrRNw7RyI_hg2ML7uWAIrK9oD7P97/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps/lsig/AK1ks_kwRAIgD9dY4wez40mtyvPlYPSeiXZJfCT9U1UI-S0Qbulv9J8CIHFT_Joh4EEXT7apIef6dK1Du-oZf8wQC3t3yYR8egoN"
[dashsegments] Total fragments: 23
[download] Destination: Katelyn and Marcic [KIaGP41BO90].f248.webm
[debug] File locking is not supported. Proceeding without locking
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (1/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (2/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (3/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (4/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (5/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (6/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (7/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (8/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (9/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (10/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Giving up after 10 retries
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1008, in main
  File "yt_dlp\__init__.py", line 998, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3510, in download
  File "yt_dlp\YoutubeDL.py", line 3485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1556, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1723, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2921, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3369, in process_info
  File "yt_dlp\YoutubeDL.py", line 3108, in dl
  File "yt_dlp\downloader\common.py", line 455, in download
  File "yt_dlp\downloader\dash.py", line 60, in real_download
  File "yt_dlp\downloader\fragment.py", line 376, in download_and_append_fragments_multiple
  File "yt_dlp\downloader\fragment.py", line 514, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 463, in download_fragment
  File "yt_dlp\downloader\fragment.py", line 125, in _download_fragment
  File "yt_dlp\downloader\common.py", line 455, in download
  File "yt_dlp\downloader\http.py", line 362, in real_download
  File "yt_dlp\utils\_utils.py", line 5114, in __iter__
  File "yt_dlp\downloader\common.py", line 401, in report_retry
  File "yt_dlp\utils\_utils.py", line 5121, in report_retry
  File "yt_dlp\downloader\common.py", line 404, in <lambda>
  File "yt_dlp\YoutubeDL.py", line 1045, in report_error
  File "yt_dlp\YoutubeDL.py", line 973, in trouble

ERROR: fragment 1 not found, unable to continue
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1008, in main
  File "yt_dlp\__init__.py", line 998, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3510, in download
  File "yt_dlp\YoutubeDL.py", line 3485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1556, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1723, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2921, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3369, in process_info
  File "yt_dlp\YoutubeDL.py", line 3108, in dl
  File "yt_dlp\downloader\common.py", line 455, in download
  File "yt_dlp\downloader\dash.py", line 60, in real_download
  File "yt_dlp\downloader\fragment.py", line 376, in download_and_append_fragments_multiple
  File "yt_dlp\downloader\fragment.py", line 515, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 480, in append_fragment
  File "yt_dlp\YoutubeDL.py", line 1045, in report_error
  File "yt_dlp\YoutubeDL.py", line 973, in trouble


[debug] Invoking http downloader on "https://rr3---sn-jvhj5nu-nh4z.googlevideo.com/videoplayback?expire=1697704516&ei=5JUwZe-bG47FsfIPgeGeyAg&ip=76.114.49.72&id=o-AC5FyM1gMMQV0DkZHh6D149Y3rm8gJXNWz7KdyZG0oMU&itag=251&source=youtube&requiressl=yes&mh=sy&mm=31%2C29&mn=sn-jvhj5nu-nh4z%2Csn-n4v7snls&ms=au%2Crdu&mv=m&mvi=3&pl=22&initcwndbps=1446250&spc=UWF9fxo4YqqR3ZV3qdCf0p6yE8f7KLY&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=1919914&dur=117.941&lmt=1562126748799316&mt=1697682541&fvip=2&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=2201222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRAIgL4xqZdL9rqP6m6zRFhk1urZR2uwFv_AHow-6-bjI9vMCIAFC6pw2JRnuLygkfBsoASQpAep0FBaSTEsIIi3RKo6_&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRgIhANu0xS5NLilxHrgjml2Mslqcu-U8sezcMbCv_DDNF0mIAiEAhTk6EmaCuzkEEmnZ0IJ2LYdpP8XrrDTfu29WS7Nl4gY%3D"
[download] Katelyn and Marcic [KIaGP41BO90].f251.webm has already been downloaded
[download] 100% of    1.83MiB
```

**Comment by bashonly** [comment] 2023-10-19 03:32
It's an error on youtube's server. Pass `--check-formats` to have test the selected format and re-select the next best format if testing fails

Duplicate of #7872

**Closed by bashonly** 2023-10-19 03:32 UTC
Labels: site-bug, triage
