### ISSUE TITLE
yt-dlp is not downloading videos from instagram anymore 

### ISSUE THREAD

**Issue by soulfulkhani** [yt-dlp/yt-dlp#11157] opened 2024-10-04 07:37 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

hi, i was trying to download a video and yt-dlp suddenly could not download it. i have tried with nightly version as well, but it was working fine day after yesterday. so i wonder what could be the real issue here .
.
.
*`WARNING: [Instagram] xxxxxxxx: General metadata extraction failed (some metadata might be missing).
[Instagram] xxxxxxxx: Downloading webpage
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
[Instagram] xxxxxx: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] xxxxxxx: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
'igsh' is not recognized as an internal or external command,
operable program or batch file.`*

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\>yt-dlp -vU  -F https://www.instagram.com/reel/xxxxxxxx
[debug] Command-line config: ['-vU', '-F', 'https://www.instagram.com/reel/xxxxxxxxx']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-12-21-git-1e42a48e37-full_build-www.gyan.dev (setts), ffprobe 2023-12-21-git-1e42a48e37-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.09.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.09.27 from yt-dlp/yt-dlp)
[Instagram] Extracting URL: https://www.instagram.com/reel/xxxxxxxxxxx
[Instagram] xxxxxxx: Setting up session
[Instagram] xxxxxxx: Downloading JSON metadata
WARNING: [Instagram] xxxxxxxxxx: General metadata extraction failed (some metadata might be missing).
[Instagram] xxxxxxxxxx: Downloading webpage
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
[Instagram] xxxxxxxx: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] xxxxxxxxx: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\instagram.py", line 460, in _real_extract
  File "yt_dlp\extractor\common.py", line 1257, in raise_login_required
```

**Comment by grqz** [comment] 2024-10-04 07:39
seems like duplicate of #11151

**Comment by soulfulkhani** [comment] 2024-10-04 08:22
> seems like a duplicate of #11151

Opps my bad

**Comment by soulfulkhani** [comment] 2024-10-04 08:22
Okay the issue is already have bern made before

**Closed** 2024-10-04 08:24 UTC
Labels: duplicate, site-bug, site:instagram
