### ISSUE TITLE
Not Downloading From Sonyliv [Site Request]

### ISSUE THREAD

**Issue by shahidhasanzai** [yt-dlp/yt-dlp#558] opened 2021-07-24 10:51 UTC
please fix it ,its showing DRM protected, 

I need to download this show in hindi language 

https://www.sonyliv.com/sports/wwe-smackdown-1700000191/wwe-smackdown-24-jul-2021-1000127528?watch=true

![image](https://user-images.githubusercontent.com/75906314/126866232-680f3053-9379-47da-8d2e-6a1b8583d372.png)

**Comment by Ashish0804** [comment] 2021-07-24 10:52
use `--allow-unplayable-formats` to get the encrypted files.

**Comment by shahidhasanzai** [comment] 2021-07-24 12:19
i dont know bro , how i will use --allow-unplayable-formats ? i wanna download DRM content from sonyliv ,please help me bro ,i am new

**Comment by shahidhasanzai** [comment] 2021-07-24 12:20
this is link https://www.sonyliv.com/sports/wwe-smackdown-1700000191/wwe-smackdown-24-jul-2021-1000127528?watch=true

**Comment by Ashish0804** [comment] 2021-07-24 12:21
you are using `youtube-dl` :facepalm: 
Open an issue here instead https://github.com/ytdl-org/youtube-dl/issues

OR

Try `yt-dlp` with `--allow-unplayable-formats`

`yt-dlp --allow-unplayable-formats https://www.sonyliv.com/sports/wwe-smackdown-1700000191/wwe-smackdown-24-jul-2021-1000127528?watch=true`

**Comment by shahidhasanzai** [comment] 2021-07-24 12:28
oh my GOD ,its working ,but bro how i will choose langugage > i wanna download this show with hindi and english language ,and size 720p HD

**Comment by Ashish0804** [comment] 2021-07-24 12:29
use `-F` to see all the available formats and then use `-f <video_id>+<audio_id>`

**Comment by shahidhasanzai** [comment] 2021-07-24 12:29
Thank you sooo much bro Love you :) you really help me

**Comment by Ashish0804** [comment] 2021-07-24 12:31
Closing this now since the problem is solved. If you need further help take a look at the readme and/or join the discord server.

**Comment by shahidhasanzai** [comment] 2021-07-24 12:32
![image](https://user-images.githubusercontent.com/75906314/126868520-64bb89c2-bd4d-478f-a2c1-787e775193ca.png)

**Comment by shahidhasanzai** [comment] 2021-07-24 12:32
bor little problem facing here ,give me discord also , i will join there , can i get your whastapp Ashish bro :)

**Closed by Ashish0804** 2021-07-24 12:31 UTC
Labels: DRM
