### ISSUE TITLE
[Broken] --get-comments fails

### ISSUE THREAD

**Issue by defder-su** [yt-dlp/yt-dlp#531] opened 2021-07-19 15:43 UTC
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.07.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Command-line config: ['--no-check-certificate', '--verbose', '--get-comments', 'https://www.youtube.com/watch?v=m2R0egcldAc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.07.07 (zip)
[debug] Python version 3.9.4 (CPython 64bit) - macOS-10.13.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=m2R0egcldAc
[youtube] m2R0egcldAc: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] m2R0egcldAc: Downloading 1 format(s): 303+251
[youtube] Downloading initial comment continuation page 
WARNING: [youtube] Incomplete data received. Retrying ...
[youtube] Downloading initial comment continuation page (retry #1)
WARNING: [youtube] Incomplete data received. Retrying ...
[youtube] Downloading initial comment continuation page (retry #2)
WARNING: [youtube] Incomplete data received. Retrying ...
[youtube] Downloading initial comment continuation page (retry #3)
ERROR: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1142, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1178, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1219, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2198, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2358, in process_info
    self.post_extract(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2860, in post_extract
    actual_post_extract(info_dict or {})
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2852, in actual_post_extract
    extra = post_extractor().items()
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 2927, in <lambda>
    info['__post_extractor'] = lambda: self._extract_comments(ytcfg, video_id, contents, webpage, xsrf_token)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 2157, in _extract_comments
    for comment in comment_iter:
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 2080, in _comment_entries
    raise ExtractorError(last_error)
yt_dlp.utils.ExtractorError: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.



```

## Description

The flag "get-comments" causes error.

yt-dlp --no-check-certificate --verbose --get-comments https://www.youtube.com/watch?v=m2R0egcldAc

**Comment by llacb47** [comment] 2021-07-19 15:59
search issues first please.

https://github.com/yt-dlp/yt-dlp/issues/510#issuecomment-880362269

**Comment by defder-su** [comment] 2021-07-19 17:03
`yt-dlp --no-check-certificate --verbose https://www.youtube.com/watch?v=m2R0egcldAc` works.

The issue reproduces only with "get-comments"

**Comment by pukkandan** [comment] 2021-07-19 17:26
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/507
Fixed by: https://github.com/yt-dlp/yt-dlp/pull/466

**Closed by pukkandan** 2021-07-19 17:26 UTC
