### ISSUE TITLE
[Tubi] 20 video limit when downloading from a series?

### ISSUE THREAD

**Issue by sgarc103** [yt-dlp/yt-dlp#10048] opened 2024-05-28 01:33 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

US

### Example URLs

https://tubitv.com/series/4071/astro-boy

### Provide a description that is worded well enough to be understood

Download states it will download 1-20 regardless of how many episode are available on tubi

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://tubitv.com/series/4071/astro-boy']
[debug] User config "C:\Users\sgarc\AppData\Roaming\yt-dlp\config": ['-o', 'D:\\Video\\Anime\\Astroboy\\%(title)s.%(ext)s', '--ffmpeg-location', 'C:\\yt-dlp', '--cookies-from-browser', 'firefox', '--write-thumbnail', '--write-sub', '--write-auto-subs', '--embed-subs', '--sub-lang', 'en.*,en-US,English', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-07-19-git-efa6cec759-full_build-www.gyan.dev (setts), ffprobe 2023-07-19-git-efa6cec759-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.2, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\sgarc\AppData\Roaming\Mozilla\Firefox\Profiles\8fflcw4s.default-release\cookies.sqlite"
Extracted 852 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[TubiTvShow] Extracting URL: https://tubitv.com/series/4071/astro-boy
[download] Downloading playlist: astro-boy
[TubiTvShow] astro-boy: Downloading webpage
[info] There are no playlist thumbnails to download
[TubiTvShow] Playlist astro-boy: Downloading 20 items of 20
[download] Downloading item 1 of 20
```

**Comment by bashonly** [comment] 2024-05-28 03:34
Duplicate of #8563

**Closed by bashonly** 2024-05-28 03:34 UTC
Labels: site-request, triage
