### ISSUE TITLE
[vimeo] Incorrect description for certain videos

### ISSUE THREAD

**Issue by shoxie007** [yt-dlp/yt-dlp#7176] opened 2023-05-30 22:29 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

If a video has an empty description, yt-dlp will pick up something else and use it as the description. For example, for this video:
```https://vimeo.com/251632201```
the description which yt-dlp picks up is:
```"Power your marketing strategy with perfectly branded videos to drive better ROI."```
which is incorrect. The description should be empty.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--get-description', 'https://vimeo.com/251632201']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.05.30.154327 [1fe5bf240] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg n4.4-154-g79c114e1b2-20210923 (setts)
[debug] Optional libraries: certifi-2019.11.28, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1840 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.05.30.154327, Current version: nightly@2023.05.30.154327
Current Build Hash: 6e0482f61c2a1fd60fc19ba6a10b928842ed1a735714e115fa9b8e325a56ab7b
yt-dlp is up to date (nightly@2023.05.30.154327)
[vimeo] Extracting URL: https://vimeo.com/251632201
[vimeo] 251632201: Downloading webpage
[vimeo] 251632201: Downloading JSON metadata
[vimeo] 251632201: Downloading JSON metadata
[vimeo] 251632201: Checking Original video URL
[vimeo] 251632201: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 251632201: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 251632201: Downloading fastly_skyfire m3u8 information
[vimeo] 251632201: Downloading fastly_skyfire m3u8 information
[vimeo] 251632201: Downloading akfire_interconnect_quic MPD information
[vimeo] 251632201: Downloading akfire_interconnect_quic MPD information
[vimeo] 251632201: Downloading fastly_skyfire MPD information
[vimeo] 251632201: Downloading fastly_skyfire MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 251632201: Downloading 1 format(s): Original
Power your marketing strategy with perfectly branded videos to drive better ROI.
```

**Comment by bashonly** [comment] 2023-05-30 22:32
Duplicate of #4354

**Closed by bashonly** 2023-05-30 22:32 UTC
Labels: duplicate, site-enhancement, site:vimeo

**Comment by shoxie007** [comment] 2023-05-30 22:37
> Duplicate of #4354

I see. Thanks. I'll post a comment to that issue.
