### ISSUE TITLE
[ZenYandex] Does not download videos

### ISSUE THREAD

**Issue by AlexTeplov45** [yt-dlp/yt-dlp#11050] opened 2024-09-21 05:06 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

 yt-dlp https://dzen.ru/video/watch/6553decf11b02f63384cf554
[ZenYandex] Extracting URL: https://dzen.ru/video/watch/6553decf11b02f63384cf554
[ZenYandex] 6553decf11b02f63384cf554: Downloading webpage
[ZenYandex] 6553decf11b02f63384cf554: Redirecting
ERROR: local variable 'fmts' referenced before assignment

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://dzen.ru/video/watch/6553decf11b02f63384cf554
[debug] Command-line config: ['-vU', 'https://dzen.ru/video/watch/6553decf11b02f63384cf554']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
[debug] Python 3.9.13 (CPython x86_64 64bit) - macOS-10.15.7-x86_64-i386-64bit (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg N-103360-g7f194c7d96-tessus (setts), phantomjs 2.1.1
[debug] Optional libraries: sqlite3-3.39.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[ZenYandex] Extracting URL: https://dzen.ru/video/watch/6553decf11b02f63384cf554
[ZenYandex] 6553decf11b02f63384cf554: Downloading webpage
[ZenYandex] 6553decf11b02f63384cf554: Redirecting
ERROR: local variable 'fmts' referenced before assignment
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/yandexvideo.py", line 276, in _real_extract
    formats.extend(fmts)
UnboundLocalError: local variable 'fmts' referenced before assignment
```

**Comment by bashonly** [comment] 2024-09-21 05:55
Duplicate of #10818

**Closed by bashonly** 2024-09-21 05:55 UTC
Labels: site-bug, triage
