### ISSUE TITLE
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.

### ISSUE THREAD

**Issue by zone559** [yt-dlp/yt-dlp#9398] opened 2024-03-09 01:52 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Still download, but there was an issue.

WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] ry6h82hkwTw: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] ry6h82hkwTw: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] ry6h82hkwTw: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Desktop\Downloads\yt-dlp>yt-dlp -s --verbose https://www.youtube.com/watch?v=ry6h82hkwTw
[debug] Command-line config: ['-s', '--verbose', 'https://www.youtube.com/watch?v=ry6h82hkwTw']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-12-07-git-f89cff96d0-essentials_build-www.gyan.dev (setts), ffprobe 2023-12-07-git-f89cff96d0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Extractor Plugins: TTUser (TikTokUserIE)
[debug] Plugin directories: ['C:\\Users\\Desktop\\Downloads\\yt-dlp\\yt-dlp-plugins\\yt_dlp_ttuser-2024.2.27-py3-none-any.whl\\yt_dlp_plugins']
[debug] Loaded 1798 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=ry6h82hkwTw
[youtube] ry6h82hkwTw: Downloading webpage
[youtube] ry6h82hkwTw: Downloading ios player API JSON
[youtube] ry6h82hkwTw: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] ry6h82hkwTw: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] ry6h82hkwTw: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] ry6h82hkwTw: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] [youtube] Extracting signature function js_c48a9559_112
[youtube] ry6h82hkwTw: Downloading player c48a9559
[debug] Saving youtube-sigfuncs.js_c48a9559_112 to cache
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig P4f2ZwO9VQv4rvuj => jC4ndyHky5rMjQ
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig yoTuetTQAMe_5wWf => Cy56Tc-0PLNo2g
[youtube] ry6h82hkwTw: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ry6h82hkwTw: Downloading 1 format(s): 313+251
```

**Comment by seproDev** [comment] 2024-03-09 01:53
Duplicate of #9316

Update to nightly

if you are using the exe/zip:
```
yt-dlp --update-to nightly
```

or if you installed with pip:
```
python3 -m pip install -U --pre yt-dlp
```

**Closed by seproDev** 2024-03-09 01:53 UTC
Labels: site-bug, triage
