### ISSUE TITLE
Unable to extract __NUXT__ Problem with IPrima.cz

### ISSUE THREAD

**Issue by StudioTeamTV** [yt-dlp/yt-dlp#7633] opened 2023-07-18 14:26 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [x] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Czech Republic

### Provide a description that is worded well enough to be understood

Hello, I was looking for a program to download videos from **IPrima.cz** and I found it and it worked until about the seventh month 2023 suddenly when one day I wanted to download from **IPrima.cz** again it didn't work and it kept saying something from __NUXT__:

 _ERROR: [IPrima] 5-danuv-vyber: Unable to extract __NUXT__; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U_

And yes I'm using the latest version I've tried the program and reinstalled it several times and I've tried another computer but it still doesn't work I don't know why but it's probably supported because it used to work and it detects that it's **IPrima.cz** and the video player on the page also works
if it can be fixed I'd be very happy for an answer
The .dump file: https://gist.github.com/StudioTeamTV/56da57fbfb38053c213263ef3551e005

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.iprima.cz/serialy/prima-particka/best-of-particka-prima/5-danuv-vyber']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
ERROR: [IPrima] 5-danuv-vyber: Login is required to access any iPrima content. Use --username and --password, --netrc-cmd, or --netrc (iprima) to provide account credentials
  File "yt_dlp\extractor\common.py", line 707, in extract
  File "yt_dlp\extractor\common.py", line 616, in initialize
  File "yt_dlp\extractor\iprima.py", line 114, in _real_initialize
  File "yt_dlp\extractor\common.py", line 1170, in raise_login_required
```

**Comment by bashonly** [comment] 2023-07-18 14:45
Duplicate of #7229

Will be fixed by #7216

**Closed by bashonly** 2023-07-18 14:45 UTC
Labels: site-bug, triage
