### ISSUE TITLE
"ERROR: [youtube] videoID: This live event has ended." on live video that has just ended but is still playable on YouTubes website.

### ISSUE THREAD

**Issue by nabeelr** [yt-dlp/yt-dlp#11218] opened 2024-10-10 23:42 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

Similar to issue #4695 however my Pi-Hole is disabled, and yet, once the live ended, I am unable to download the livestream that can still be re-watched on youtube like any normal YT video, however has now ended broadcasting live.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU https://www.youtube.com/watch?v=RGmQ7472Fd8                                              [debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=RGmQ7472Fd8']                                              [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8                                      [debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (debian*)                                                [debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.40 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.40)                                                                                                              [debug] exe versions: ffmpeg 7.0.2-3 (setts), ffprobe 7.0.2-3, rtmpdump 2.4                                                      [debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, pyxattr-0.8.1, requests-2.32.3, sqlite3-3.46.0, urllib3-2.0.7, websockets-10.4                                                                                   [debug] Proxy map: {}                                                                                                            [debug] Request Handlers: urllib, requests                                                                                       [debug] Loaded 1838 extractors                                                                                                   [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest                                        [debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec                     Current version: stable@2024.09.27 from yt-dlp/yt-dlp                                                                            Latest version: stable@2024.10.07 from yt-dlp/yt-dlp                                                                             ERROR: As yt-dlp has been installed via apt, you should use that to update.  If you're on a stable release, also check backports.[youtube] Extracting URL: https://www.youtube.com/watch?v=RGmQ7472Fd8                                                            [youtube] RGmQ7472Fd8: Downloading webpage                                                                                       [youtube] RGmQ7472Fd8: Downloading ios player API JSON                                                                           [youtube] RGmQ7472Fd8: Downloading web creator player API JSON                                                                   [debug] [youtube] RGmQ7472Fd8: Video is in Post-Live Manifestless mode                                                           ERROR: [youtube] RGmQ7472Fd8: This live event has ended.                                                                           File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 741, in extract                                             ie_result = self._real_extract(url)                                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^                                                                                            File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 4468, in _real_extract                                     self.raise_no_formats(reason, expected=True)                                                                                   File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1275, in raise_no_formats                                   raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by bashonly** [comment] 2024-10-10 23:48
post complete verbose output

**Comment by nabeelr** [comment] 2024-10-10 23:57
> post complete verbose output

I did, it's there in the post.

It wraps weirdly because I use tmux.

**Comment by gamer191** [comment] 2024-10-11 00:21
Here, I reformatted it
```
$ yt-dlp -vU https://www.youtube.com/watch?v=RGmQ7472Fd8
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=RGmQ7472Fd8']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (debian*)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.40 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2-3 (setts), ffprobe 7.0.2-3, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, pyxattr-0.8.1, requests-2.32.3, sqlite3-3.46.0, urllib3-2.0.7, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2024.09.27 from yt-dlp/yt-dlp
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
ERROR: As yt-dlp has been installed via apt, you should use that to update.  If you're on a stable release, also check backports.
[youtube] Extracting URL: https://www.youtube.com/watch?v=RGmQ7472Fd8
[youtube] RGmQ7472Fd8: Downloading webpage
[youtube] RGmQ7472Fd8: Downloading ios player API JSON
[youtube] RGmQ7472Fd8: Downloading web creator player API JSON
[debug] [youtube] RGmQ7472Fd8: Video is in Post-Live Manifestless mode
ERROR: [youtube] RGmQ7472Fd8: This live event has ended.
File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 741, in extract
ie_result = self._real_extract(url)
            ^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 4468, in _real_extract
self.raise_no_formats(reason, expected=True)
File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1275, in raise_no_formats
raise ExtractorError(msg, expected=expected, video_id=video_id)
```

The issue remains incomplete, because of `ERROR: As yt-dlp has been installed via apt, you should use that to update.  If you're on a stable release, also check backports.`

**Comment by nabeelr** [comment] 2024-10-11 00:25
> The issue remains incomplete, because of `ERROR: As yt-dlp has been installed via apt, you should use that to update. If you're on a stable release, also check backports.`

This is the latest version that apt has.

**Comment by gamer191** [comment] 2024-10-11 00:27
I've verified that this issue is fixed on the latest version of yt-dlp, as it's caused by issues with the web_creator client. If you have issues updating, I recommend passing `--extractor-args "youtube:player_client=mweb,default"` or adding it to a file called config.txt that can be created in the output directory

Alternatively, feel free to uninstall the apt version and instead install the pip version, see https://github.com/yt-dlp/yt-dlp/wiki/Installation#android

**Closed** 2024-10-11 00:29 UTC
Labels: incomplete

**Comment by nabeelr** [comment] 2024-10-11 00:30
> I've verified that this issue is fixed on the latest version of yt-dlp,

Is there a timeline for when the apt version will be updated? It's the package manager I use in WSL, so I'd prefer to stick to it if possible.

**Comment by Grub4K** [comment] 2024-10-11 00:32
We do not maintain the apt package, you will have to ask the packagers

**Comment by nabeelr** [comment] 2024-10-11 00:33
Ahh, cool. Thanks for the info!

**Comment by gamer191** [comment] 2024-10-11 00:42
> Is there a timeline for when the apt version will be updated? It's the package manager I use in WSL, so I'd prefer to stick to it if possible.

Sorry, we have no control over that

It typically only gets updated when a new version of Ubuntu gets released (May 2025)

I do plan on following up on that though, because yt-dlp should be exempt from that rule on the basis that it's ["A library for a web service needs to be updated for changes to the web server API."](https://canonical-sru-docs.readthedocs-hosted.com/en/latest/reference/requirements/#what-is-acceptable-to-sru). However, given yt-dlp commonly has regressions, I see little chance that Canonical (who maintain Ubuntu's repo) will accept that proposal, unless someone's willing to maintain a fork of yt-dlp that only contains critical extractor fixes.

In the meantime, I recommend running the following one line command which should permanently fix your issue
```
echo "--extractor-args "youtube:player_client=mweb,default" > yt-dlp.conf
```
(provided you don't already have a yt-dlp.conf file)

**Comment by nabeelr** [comment] 2024-10-11 05:31
Thanks,

I'll give that a shot. I appreciate the help.
