### ISSUE TITLE
ERROR: unsupported operand type(s) for -: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by schmorp** [yt-dlp/yt-dlp#3288] opened 2022-04-02 19:56 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The error in title appears when using 2022.03.08.1 and breaks the download. Version 2022.02.04 works fine.

Reproducer:

yt-dlp --sleep-requests 1 --sleep-subtitles 1 --no-write-playlist-metafiles --write-subs --write-auto-subs --throttled-rate 50K --abort-on-unavailable-fragment --fragment-retries 25 --throttled-rate 50K --socket-timeout 10 --sleep-interval 1 --add-metadata --cookies /root/.youtube-dl-cookies --force-ipv4 --buffer-size 1M --convert-subtitles srt --embed-subs --sub-lang en,de --embed-subs --merge-output-format mkv --no-cache-dir -f 'bestvideo[vcodec=vp9][height=1440]+bestaudio[acodec=opus]/bestvideo[vcodec=m4a][height=1440]+bestaudio[acodec=opus]/bestvideo[vcodec=vp9][height=1080]+bestaudio[acodec=opus]/bestvideo[vcodec=m4a][height=1080]+bestaudio[acodec=opus]/bestvideo[vcodec=vp9][height=720]+bestaudio[acodec=opus]/bestvideo[vcodec=m4a][height=720]+bestaudio[acodec=opus]/bestvideo[height<=?1080]+bestaudio/best[height<=?1080]/bestvideo+bestaudio/best' -o '%(uploader)s-%(title)s-%(upload_date)s-%(id)s.%(ext)s' -i -c OSiHucm45D0

### Verbose log

```shell
[debug] Command-line config: ['-v', '--sleep-requests', '1', '--sleep-subtitles', '1', '--no-write-playlist-metafiles', '--write-subs', '--write-auto-subs', '--throttled-rate', '50K', '--abort-on-unavailable-fragment', '--fragment-retries', '25', '--throttled-rate', '50K', '--socket-timeout', '10', '--sleep-interval', '1', '--add-metadata', '--cookies', '/root/.youtube-dl-cookies', '--force-ipv4', '--buffer-size', '1M', '--convert-subtitles', 'srt', '--embed-subs', '--sub-lang', 'en,de', '--embed-subs', '--merge-output-format', 'mkv', '--no-cache-dir', '-f', 'bestvideo[vcodec=vp9][height=1440]+bestaudio[acodec=opus]/bestvideo[vcodec=m4a][height=1440]+bestaudio[acodec=opus]/bestvideo[vcodec=vp9][height=1080]+bestaudio[acodec=opus]/bestvideo[vcodec=m4a][height=1080]+bestaudio[acodec=opus]/bestvideo[vcodec=vp9][height=720]+bestaudio[acodec=opus]/bestvideo[vcodec=m4a][height=720]+bestaudio[acodec=opus]/bestvideo[height<=?1080]+bestaudio/best[height<=?1080]/bestvideo+bestaudio/best', '-o', '%(uploader)s-%(title)s-%(upload_date)s-%(id)s.%(ext)s', '-i', '-c', 'OSiHucm45D0']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-13-amd64-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4 (fdk,setts), ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: brotli, Cryptodome, secretstorage, sqlite
[debug] Proxy map: {'no': '127.0.0.1,localhost,cerebro,fuji,doom,127.0.0.0/8,10.0.0.0/8,192.168.0.0/16', 'http': 'http://10.0.0.5:3128/', 'xv_open': '/root/s/xv_open_proxy', 'https': 'http://10.0.0.5:3128/'}
[debug] [youtube] Extracting URL: OSiHucm45D0
[youtube] OSiHucm45D0: Downloading webpage
[youtube] Sleeping 1.0 seconds ...
[youtube] OSiHucm45D0: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] OSiHucm45D0: Downloading 1 format(s): 248+251
[SubtitlesConvertor] There aren't any subtitles to convert
[debug] Invoking downloader on "https://rr1---sn-h0jeln7e.googlevideo.com/videoplayback?expire=1648950932&ei=NKpIYtjqK4W6gQeOmLGIBQ&ip=37.49.68.13&id=o-AGp_4D88I9qr6XCGy1-icZ5Jz_yoEzOqTC-rgRt_npgx&itag=248&source=youtube&requiressl=yes&mh=Ne&mm=31%2C26&mn=sn-h0jeln7e%2Csn-4g5lzney&ms=au%2Conr&mv=m&mvi=1&pl=22&initcwndbps=1161250&vprv=1&mime=video%2Fwebm&gir=yes&clen=12694937&dur=128.766&lmt=1556130868613033&mt=1648928945&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAL5-HzMYd60lbaLRpBYrVM4NqRc8xAEU9hCsT1XAand-AiA7D9P8CkEOThHy3jTpdPLhkFNfEXcCosLkgk-3yNfPqA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMX20MhNBv3gg8GEx_SKKkTmqeWSKTw22p18HQaUrtuIAiEAvj7Bbu2dNg543OCjpAs8QjwmyCEC5L9qFEbNF4NYc3s%3D"
ERROR: unsupported operand type(s) for -: 'NoneType' and 'float'
Traceback (most recent call last):
  File "/root/s/youtube-dl/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/root/s/youtube-dl/yt_dlp/YoutubeDL.py", line 1473, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/root/s/youtube-dl/yt_dlp/YoutubeDL.py", line 1529, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/root/s/youtube-dl/yt_dlp/YoutubeDL.py", line 2638, in process_video_result
    self.process_info(new_info)
  File "/root/s/youtube-dl/yt_dlp/YoutubeDL.py", line 3110, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/root/s/youtube-dl/yt_dlp/YoutubeDL.py", line 2835, in dl
    return fd.download(name, new_info, subtitle)
  File "/root/s/youtube-dl/yt_dlp/downloader/common.py", line 438, in download
    sleep_interval = random.uniform(min_sleep_interval, max_sleep_interval)
  File "/usr/lib/python3.9/random.py", line 506, in uniform
    return a + (b - a) * self.random()
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

**Comment by NanaMizukiAnother7** [comment] 2022-04-02 21:21
This issue is a duplicate of #3012. It has been fixed.

**Closed** 2022-04-03 03:20 UTC
Labels: bug, triage
