### ISSUE TITLE
Problem with set release_year

### ISSUE THREAD

**Issue by KRUXLEX** [yt-dlp/yt-dlp#4698] opened 2022-08-18 19:19 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.14** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi,
I'm trying to download a playlist:
yt-dlp --config-locations ~/.yt-dlp-best_audio.conf https://www.youtube.com/playlist?list=OLAK5uy_kf_AVWQtmQf0S0sppySWE391g0fGGlJcI

I wan set metadata and all is ok between release_year. In log we can se it parse okey, but in final file it full date with month and day. 
![obraz](https://user-images.githubusercontent.com/22861005/185485906-9c88ee17-a6f4-4c67-8625-c022bffdce95.png)

Bellow configg file:

```
--ignore-errors 
--format bestaudio 
--extract-audio 
--audio-format mp3 
--audio-quality 0 
# --output "%(id)s.%(title)s.%(ext)s" 
--output "%(artist)s - %(title)s.%(ext)s" 
--add-metadata 
--yes-playlist 

# Interpret the title as "Artist - Title"
--parse-metadata "title:%(title)s"
--parse-metadata "artist:%(artist)s"
--parse-metadata "album:%(album)s"
--parse-metadata "disc:%(disc_number)s"
--parse-metadata "playlist_index:%(track_number)s"
--parse-metadata "%(release_date>%Y)s:%(release_year)s"
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube:tab] OLAK5uy_kf_AVWQtmQf0S0sppySWE391g0fGGlJcI: Downloading webpage
[youtube:tab] OLAK5uy_kf_AVWQtmQf0S0sppySWE391g0fGGlJcI: Downloading API JSON with unavailable videos
[download] Downloading playlist: The Documentary 2
[youtube:tab] playlist The Documentary 2: Downloading 19 videos
[download] Downloading video 1 of 19
[youtube] M5hHIApY-3k: Downloading webpage
[youtube] M5hHIApY-3k: Downloading android player API JSON
[MetadataParser] Parsed title from '%(title)s': 'Intro'
[MetadataParser] Parsed artist from '%(artist)s': 'The Game'
[MetadataParser] Parsed album from '%(album)s': 'The Documentary 2'
[MetadataParser] Parsed disc_number from '%(disc)s': 'NA'
[MetadataParser] Parsed track_number from '%(playlist_index)s': '01'
[MetadataParser] Parsed release_year from '%(release_date>%Y)s': '2015'
```

**Comment by pukkandan** [comment] 2022-08-19 02:14
From the limited information give, it looks like duplicate of https://github.com/yt-dlp/yt-dlp/issues/3087

**Closed by pukkandan** 2022-08-19 02:14 UTC
Labels: bug, incomplete

**Comment by KRUXLEX** [comment] 2022-08-19 07:11
This is not, duplicate, this set correct but don add this to mp3 file
`[MetadataParser] Parsed release_year from '%(release_date>%Y)s': '2015'`

Maybe I doing something wrong...
