### ISSUE TITLE
https://www.cnn.com/2024/08/01/health/video/covid-summer-wave-dr-sanjay-gupta-on-call-digvid cnn.py--CNNArticleIE Unable to parse

### ISSUE THREAD

**Issue by pythonlw** [yt-dlp/yt-dlp#11260] opened 2024-10-16 04:21 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

https://www.cnn.com/2024/08/01/health/video/covid-summer-wave-dr-sanjay-gupta-on-call-digvid cnn.py--CNNArticleIE Unable to parse

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ERROR: [CNNArticle] Unable to extract cnn url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "C:\Users\administered\Desktop\python_test\news_spider\yt_dlp\YoutubeDL.py", line 1627, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\administered\Desktop\python_test\news_spider\yt_dlp\YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\administered\Desktop\python_test\news_spider\yt_dlp\extractor\common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\administered\Desktop\python_test\news_spider\yt_dlp\extractor\cnn.py", line 154, in _real_extract
    cnn_url = self._html_search_regex(r"video:\s*'([^']+)'", webpage, 'cnn url')
  File "C:\Users\administered\Desktop\python_test\news_spider\yt_dlp\extractor\common.py", line 1382, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "C:\Users\administered\Desktop\python_test\news_spider\yt_dlp\extractor\common.py", line 1346, in _search_regex
    raise RegexNotFoundError(f'Unable to extract {_name}')
yt_dlp.utils.RegexNotFoundError: [CNNArticle] Unable to extract cnn url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\administered\Desktop\python_test\news_spider\y.py", line 145, in <module>
    get_article_info()
  File "C:\Users\administered\Desktop\python_test\news_spider\y.py", line 88, in get_article_info
    info = ydl.extract_info(url, download=False)
  File "C:\Users\administered\Desktop\python_test\news_spider\yt_dlp\YoutubeDL.py", line 1616, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Users\administered\Desktop\python_test\news_spider\yt_dlp\YoutubeDL.py", line 1645, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "C:\Users\administered\Desktop\python_test\news_spider\yt_dlp\YoutubeDL.py", line 1093, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\administered\Desktop\python_test\news_spider\yt_dlp\YoutubeDL.py", line 1031, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [CNNArticle] Unable to extract cnn url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment] 2024-10-16 05:41
Duplicate of #9719

**Closed by bashonly** 2024-10-16 05:41 UTC
Labels: site-bug, triage
