### ISSUE TITLE
ERROR: [facebook] 1963379427336513: Cannot parse data

### ISSUE THREAD

**Issue by monostudio88** [yt-dlp/yt-dlp#7922] opened 2023-08-21 06:18 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp -Fv --ignore-config https://www.facebook.com/khimsokheng.ksh/videos/1963379427336513
[debug] Command-line config: ['-Fv', '--ignore-config', 'https://www.facebook.com/khimsokheng.ksh/videos/1963379427336513']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.20.172604 [7cccab79e] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111199-g2cac3fd744-20230620 (setts), ffprobe N-111199-g2cac3fd744-20230620
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[facebook] Extracting URL: https://www.facebook.com/khimsokheng.ksh/videos/1963379427336513
[facebook] 1963379427336513: Downloading webpage
[facebook] 1963379427336513: Downloading webpage
ERROR: [facebook] 1963379427336513: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\facebook.py", line 733, in _real_extract
  File "yt_dlp\extractor\facebook.py", line 680, in _extract_from_url
  
 How to fix it?. I updated to nightly@2023.08.20.172604.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment] 2023-08-21 06:18
Duplicate of #7901

**Closed by bashonly** 2023-08-21 06:18 UTC
Labels: duplicate, site-bug, site:facebook
