### ISSUE TITLE
mtv.com no longer working

### ISSUE THREAD

**Issue by drsuchan** [yt-dlp/yt-dlp#6284] opened 2023-02-19 06:06 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

example: https://www.mtv.com/video-clips/gp23om/secrets-revealed-night-is-coming-to-mtv-tuesdays

mtv.com recently updated their video system so that yt-dlp can no longer access their videos.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\***>yt-dlp https://www.mtv.com/video-clips/gp23om/secrets-revealed-night-is-coming-to-mtv-tuesdays  -vU
[debug] Command-line config: ['https://www.mtv.com/video-clips/gp23om/secrets-revealed-night-is-coming-to-mtv-tuesdays', '-vU']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-03-17-git-242c07982a-full_build-www.gyan.dev (setts), ffprobe 2022-03-17-git-242c07982a-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'https://127.0.0.1:7890', 'ftp': 'ftp://127.0.0.1:7890'}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[mtv] Extracting URL: https://www.mtv.com/video-clips/gp23om/secrets-revealed-night-is-coming-to-mtv-tuesdays
[mtv] secrets-revealed-night-is-coming-to-mtv-tuesdays: Downloading webpage
[mtv] 3d8a7f53-ed25-4543-b941-e096d4e08f40: Downloading info
ERROR: [mtv] gp23om: Unable to download XML: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 693, in extract
  File "yt_dlp\extractor\mtv.py", line 323, in _real_extract
  File "yt_dlp\extractor\mtv.py", line 227, in _get_videos_info
  File "yt_dlp\extractor\mtv.py", line 230, in _get_videos_info_from_url
  File "yt_dlp\extractor\common.py", line 1047, in download_content
  File "yt_dlp\extractor\common.py", line 1011, in download_handle
  File "yt_dlp\extractor\common.py", line 881, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 838, in _request_webpage

  File "yt_dlp\extractor\common.py", line 820, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3726, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by bashonly** [comment] 2023-02-19 06:09
Duplicate of #4928

**Closed by bashonly** 2023-02-19 06:09 UTC
Labels: site-bug, triage
