### ISSUE TITLE
discoveryplus.no not working after update on page

### ISSUE THREAD

**Issue by CiASpook** [yt-dlp/yt-dlp#2210] opened 2022-01-02 22:09 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Norway

### Description

I can't download videos from discoveryplus.no anymore after they updated the page. I have a paid subscripton for the site and have tried with both with username/password and cookies. Keep getting the same issue.

### Verbose log

```shell
yt-dlp.exe -Uv --cookies cookies.txt -u ****** -p ****** https://www.discoveryplus.no/video/nissene-i-bingen/sesong-1-episode-10
[debug] Command-line config: ['-Uv', '--cookies', 'cookies.txt', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.discoveryplus.no/video/nissene-i-bingen/sesong-1-episode-10']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_dir)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 2021-12-30-git-12f21849e5-essentials_build-www.gyan.dev (setts), ffprobe 2021-12-30-git-12f21849e5-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [DPlay] Extracting URL: https://www.discoveryplus.no/video/nissene-i-bingen/sesong-1-episode-10
[debug] Using fake IP 84.215.14.105 (NO) as X-Forwarded-For
[DPlay] nissene-i-bingen/sesong-1-episode-10: Downloading JSON metadata
[DPlay] 1245481: Downloading JSON metadata
ERROR: [DPlay] nissene-i-bingen/sesong-1-episode-10: This video is only available for registered users. You may want to use --cookies.
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\dplay.py", line 320, in _real_extract
  File "yt_dlp\extractor\dplay.py", line 104, in _get_disco_api_info
  File "yt_dlp\extractor\dplay.py", line 50, in _process_errors

yt-dlp.exe -Uv --cookies cookies.txt https://www.discoveryplus.no/video/nissene-i-bingen/sesong-1-episode-10
[debug] Command-line config: ['-Uv', '--cookies', 'cookies.txt', 'https://www.discoveryplus.no/video/nissene-i-bingen/sesong-1-episode-10']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_dir)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 2021-12-30-git-12f21849e5-essentials_build-www.gyan.dev (setts), ffprobe 2021-12-30-git-12f21849e5-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [DPlay] Extracting URL: https://www.discoveryplus.no/video/nissene-i-bingen/sesong-1-episode-10
[debug] Using fake IP 84.214.45.110 (NO) as X-Forwarded-For
[DPlay] nissene-i-bingen/sesong-1-episode-10: Downloading JSON metadata
[DPlay] 1245481: Downloading JSON metadata
ERROR: [DPlay] nissene-i-bingen/sesong-1-episode-10: This video is only available for registered users. You may want to use --cookies.
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\dplay.py", line 320, in _real_extract
  File "yt_dlp\extractor\dplay.py", line 104, in _get_disco_api_info
  File "yt_dlp\extractor\dplay.py", line 50, in _process_errors

yt-dlp.exe -Uv -u ****** -p ****** https://www.discoveryplus.no/video/nissene-i-bingen/sesong-1-episode-10
[debug] Command-line config: ['-Uv', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.discoveryplus.no/video/nissene-i-bingen/sesong-1-episode-10']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_dir)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 2021-12-30-git-12f21849e5-essentials_build-www.gyan.dev (setts), ffprobe 2021-12-30-git-12f21849e5-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [DPlay] Extracting URL: https://www.discoveryplus.no/video/nissene-i-bingen/sesong-1-episode-10
[debug] Using fake IP 84.212.114.227 (NO) as X-Forwarded-For
[DPlay] nissene-i-bingen/sesong-1-episode-10: Downloading token
[DPlay] nissene-i-bingen/sesong-1-episode-10: Downloading JSON metadata
[DPlay] 1245481: Downloading JSON metadata
ERROR: [DPlay] nissene-i-bingen/sesong-1-episode-10: This video is only available for registered users. You may want to use --cookies.
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\dplay.py", line 320, in _real_extract
  File "yt_dlp\extractor\dplay.py", line 104, in _get_disco_api_info
  File "yt_dlp\extractor\dplay.py", line 50, in _process_errors
```

**Comment by pukkandan** [comment] 2022-01-03 06:31
Duplicate of #2138

**Closed by pukkandan** 2022-01-03 06:31 UTC
Labels: site-bug, triage
