### ISSUE TITLE
Failed to Download Video from Ixigua: Error "Failed to get SSR_HYDRATED_DATA"

### ISSUE THREAD

**Issue by michaellee455939** [yt-dlp/yt-dlp#9466] opened 2024-03-16 01:32 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Not Applicable

### Provide a description that is worded well enough to be understood

When attempting to download a video from Ixigua using yt-dlp, I encountered an error stating "Failed to get SSR_HYDRATED_DATA." This issue persists even after ensuring that the yt-dlp version is up-to-date and that the URL is accessible and playable in a browser under the same network conditions.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', '--cookies-from-browser', 'chrome', 'https://www.ixigua.com/7258096154809172515']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (pip)
[debug] Python 3.11.5 (CPython AMD64 64bit) - Windows-10-10.0.20348-SP0 (OpenSSL 3.0.9 30 May 2023)
[debug] exe versions: ffmpeg 2024-01-01-git-e1c1dc8347-full_build-www.gyan.dev (setts), ffprobe 2024-01-01-git-e1c1dc8347-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.42.0, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: [HIDDEN]
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\*****\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\*****\AppData\Local\Google\Chrome\User Data\Local State"
Extracted 116 cookies from chrome
[debug] cookie version breakdown: {'v10': 116, 'other': 0, 'unencrypted': 0}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[Ixigua] Extracting URL: https://www.ixigua.com/7258096154809172515
[Ixigua] 725809615480917251: Downloading webpage
ERROR: [Ixigua] 725809615480917251: Failed to get SSR_HYDRATED_DATA; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 732, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\ixigua.py", line 67, in _real_extract
    json_data = self._get_json_data(webpage, video_id)['anyVideo']['gidInformation']['packerData']['video']
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\*****\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\ixigua.py", line 39, in _get_json_data
    raise ExtractorError('Failed to get SSR_HYDRATED_DATA')
```

**Comment by bashonly** [comment] 2024-03-16 08:41
Duplicate of #5374

**Closed by bashonly** 2024-03-16 08:41 UTC
Labels: site-bug, triage
