### ISSUE TITLE
[youtube] Skipping player response from ios client

### ISSUE THREAD

**Issue by Masterolic** [yt-dlp/yt-dlp#8811] opened 2023-12-20 10:05 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

This happens only when I use socks5 proxy 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --proxy socks5://fixie:shq7ywvjq2AjDOf@speedway.usefixie.com:1080 "https://youtube.com/shorts/ds9oSmnJET0?si=70s3LhYJJOMC6NuP"
[debug] Command-line config: ['-vU', '--proxy', 'socks5://fixie:shq7ywvjq2AjDOf@speedway.usefixie.com:1080', 'https://youtube.com/shorts/ds9oSmnJET0?si=70s3LhYJJOMC6NuP']                                          [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875]                                   [debug] Lazy loading extractors is disabled
[debug] Python 3.11.6 (CPython aarch64 64bit) - Linux-4.14.186-g4dc92ef73-dirty-aarch64-with-glibc2.37 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.1-3 (setts), ffprobe 6.1-3                                                 [debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.21.0, sqlite3-3.44.0, urllib3-1.24.3, websockets-12.0
[debug] Proxy map: {'all': 'socks5://fixie:shq7ywvjq2AjDOf@speedway.usefixie.com:1080'}
[debug] Request Handlers: urllib, websockets
[debug] Loaded 1792 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://youtube.com/shorts/ds9oSmnJET0?si=70s3LhYJJOMC6NuP
[youtube] ds9oSmnJET0: Downloading webpage
[youtube] ds9oSmnJET0: Downloading ios player API JSON
WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "ds9oSmnJET0"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] ds9oSmnJET0: Downloading android player API JSON
WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "ds9oSmnJET0"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "ds9oSmnJET0"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: Only images are available for download. use --list-formats to see them
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto                                                                                               [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id                                            [debug] Default format spec: bestvideo*+bestaudio/best
[info] ds9oSmnJET0: Downloading 1 format(s): sb0                                                          [debug] Invoking mhtml downloader on "https://i.ytimg.com/sb/M5t4UHllkUM/storyboard3_L2/M$M.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgi867OjBg==&sigh=rs$AOn4CLD6zz6wUMPtwBuO9zjkyt-TR6iF_g"                        [mhtml] Total fragments: 4
[download] Destination: Video Not Available [ds9oSmnJET0].mhtml
[download] 100% of   20.07KiB in 00:00:08 at 2.42KiB/s
```

**Comment by bashonly** [comment] 2023-12-20 10:37
Your proxy's IP address is in a blocked range. Duplicate of #7143

**Closed by bashonly** 2023-12-20 10:37 UTC
Labels: site-bug, triage
