### ISSUE TITLE
Unable to extract video url on Instagram.

### ISSUE THREAD

**Issue by scruffyeagle** [yt-dlp/yt-dlp#10081] opened 2024-06-01 06:48 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I tried to download a video I'd enjoyed in the browser.  yt-dlp couldn't do it.  I followed instructions, and updated yt-dlp.  That worked.  I tried again, and had same result.  The error message was in 2 parts.  1st part told me it couldn't extract the username.  2nd part told me it couldn't extract the video url.  The last instruction told me to come here and file this report.  The video url I was trying to download was [https://www.instagram.com/p/C7oXn8uOa5N/](url)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.instagram.com/p/C7oXn8uOa5N/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (zip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.57-antix.1-amd64-smp-x86_64-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.6-0, ffprobe 4.3.6-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.34.1, urllib3-1.26.5, websockets-8.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[Instagram] Extracting URL: https://www.instagram.com/p/C7oXn8uOa5N/
[Instagram] C7oXn8uOa5N: Setting up session
[Instagram] C7oXn8uOa5N: Downloading JSON metadata
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] C7oXn8uOa5N: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/instagram.py", line 490, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1473, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1363, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1327, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by kclauhk** [comment] 2024-06-01 12:36
you need cookies in order to download this video
pass --cookies-from-browser or --cookies to yt-dlp

**Comment by bashonly** [comment] 2024-06-01 13:44
Duplicate of #5967

> you need cookies in order to download this video
> pass --cookies-from-browser or --cookies to yt-dlp

This. But be aware that instagram does not hesitate to ban accounts when it detects them using 3rd party tools.

**Closed by bashonly** 2024-06-01 13:44 UTC
Labels: duplicate, site-bug, site:instagram
