### ISSUE TITLE
when download from douyin.com , can't parse json

### ISSUE THREAD

**Issue by feiyundu** [yt-dlp/yt-dlp#7471] opened 2023-06-30 13:13 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

china

### Provide a description that is worded well enough to be understood

when download from douyin.com , can't parse json

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[Douyin] Extracting URL: https://www.douyin.com/video/7250319466863594789
[Douyin] 7250319466863594789: Downloading video feed
[Douyin] 7250319466863594789: Unable to find video in feed; trying with webpage
[Douyin] 7250319466863594789: Downloading webpage
ERROR: [Douyin] 7250319466863594789: 7250319466863594789: Failed to parse JSON (caused by JSONDecodeError('Extra data in \'3-04-27"}}</script><\': line 1 column 99057 (char 99056)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 708, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 1028, in _real_extract
    render_data = self._parse_json(
                  ^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1009, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 992, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 624, in decode
    return super().decode(s)
           ^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 99057 (char 99056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1006, in _parse_json
    return json.loads(
           ^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 632, in decode
    raise type(e)(f'{e.msg} in {s[e.pos-10:e.pos+10]!r}', s, e.pos)
json.decoder.JSONDecodeError: Extra data in '3-04-27"}}</script><': line 1 column 99057 (char 99056)
```

**Comment by bashonly** [comment] 2023-06-30 13:24
Fixed in a2be9781fbf4d7e4db245c277ca2ecc41cf3a7b2

Use [the nightly builds](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases) or wait for next release

Closing as duplicate of #7431

**Closed by bashonly** 2023-06-30 13:24 UTC
Labels: duplicate, site-bug, site:tiktok

**Comment by wwfcnu** [comment] 2023-08-04 09:36
Is the tiktok extractor also applicable to douyin in mainland China? @bashonly

**Comment by bashonly** [comment] 2023-08-04 17:51
@wwfcnu I don't know for sure but I assumed so.

Are you referring to [this issue you were having](https://github.com/yt-dlp/yt-dlp/issues/2841#issuecomment-1663246568)?

You need to navigate to the video in browser, solve the puzzle challenge, and then pass `--cookies-from-browser` in order for the Douyin extractor to work
