### ISSUE TITLE
Latest version of yt-dlp can't read my configuration file.

### ISSUE THREAD

**Issue by zohozer** [yt-dlp/yt-dlp#3135] opened 2022-03-20 19:16 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

After an update to the latest vesion, yt-dlp it is no longer able to read my configuration file. I am using Windows10 and I do installed yt-dlp using PIP package manager.

The configuration file it is located under:
`C:\Users\myname\AppData\Roaming\yt-dlp\config.txt`

and inside of this file I do have a download rate limiter `--limit-rate 0.5M` which seems that yt-dlp it is not respecting anymore, looks like it is downloading now at the full speed of my internet connection.

How I can fix this issue?

### Verbose log

```shell
Not available.
```

**Comment by pukkandan** [comment] 2022-03-20 19:27
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3070

**Closed by pukkandan** 2022-03-20 19:27 UTC
Labels: bug, triage
