### ISSUE TITLE
YouTube Cookies is not working anymore

### ISSUE THREAD

**Issue by alimirjahani7** [yt-dlp/yt-dlp#11784] opened 2024-12-10 17:30 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

canada 

### Provide a description that is worded well enough to be understood

the YouTube download with cookies is not working anymore
ERROR: [youtube] Yzt7KnWfwgs: Video unavailable. This content isn’t available.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
root@ip-10-0-29-86:/# yt-dlp --get-title --skip-download --get-format --get-duration -f "bestvideo[height<=?720][ext=mp4][vcodec!=av01]+bestaudio/best"      https://www.youtube.com/watch?v=Yzt7KnWfwgs --cookies ./youtube_cookies_copy.txt -vU
[debug] Command-line config: ['--get-title', '--skip-download', '--get-format', '--get-duration', '-f', 'bestvideo[height<=?720][ext=mp4][vcodec!=av01]+bestaudio/best', 'https://www.youtube.com/watch?v=Yzt7KnWfwgs', '--cookies', './youtube_cookies_copy.txt', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.06 from yt-dlp/yt-dlp [4bd265539]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.10.228-219.884.amzn2.x86_64-x86_64-with-glibc2.28 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.28)
[debug] exe versions: ffmpeg 4.1.11-0, ffprobe 4.1.11-0
[debug] Optional libraries: certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.27.2, urllib3-2.2.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.06 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=Yzt7KnWfwgs
[youtube] Yzt7KnWfwgs: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] Yzt7KnWfwgs: Downloading web creator player API JSON
[youtube] Yzt7KnWfwgs: Downloading mweb player API JSON
ERROR: [youtube] Yzt7KnWfwgs: Video unavailable. This content isn’t available.
  File "/src/yt-dlp/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/src/yt-dlp/yt_dlp/extractor/youtube.py", line 4492, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/src/yt-dlp/yt_dlp/extractor/common.py", line 1276, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

root@ip-10-0-29-86:/# yt-dlp --get-title --skip-download --get-format --get-duration -f bestvideo[height<=?720][ext=mp4][vcodec!=av01]+bestaudio/best https://www.youtube.com/watch?v=Yzt7KnWfwgs --cookies ./youtube_cookies_copy.txt
bash: =?720][ext=mp4][vcodec!=av01]+bestaudio/best: No such file or directory
root@ip-10-0-29-86:/# yt-dlp --get-title --skip-download --get-format --get-duration -f "bestvideo[height<=?720][ext=mp4][vcodec!=av01]+bestaudio/best" https://www.youtube.com/watch?v=Yzt7
KnWfwgs --cookies ./youtube_cookies_copy.txt
ERROR: [youtube] Yzt7KnWfwgs: Video unavailable. This content isn’t available.
```

**Comment by bashonly** [comment] 2024-12-10 18:44
Duplicate of #10085

Your account has been temporarily(?) restricted from watching videos

**Closed by bashonly** 2024-12-10 18:44 UTC
Labels: site-bug, triage

**Comment by alimirjahani7** [comment] 2024-12-11 19:44
I changed the token
but either the token is getting expired or the account getting ban every day
