### ISSUE TITLE
Updater regularly fails for me *when called from other scripts* on Windows. 

### ISSUE THREAD

**Issue by ibex-are-goats** [yt-dlp/yt-dlp#335] opened 2021-05-22 12:50 UTC
This was referenced already here: https://github.com/yt-dlp/yt-dlp/pull/64

Related code is here: https://github.com/yt-dlp/yt-dlp/blob/65075de35b9fb7cc9e03db322ed4be69fdcf808a/yt_dlp/update.py#L161

I've reported this to the other fork, but more is getting done in this project. Basically there is something getting out of sync with the Windows updater.... the parent is rushing ahead before the child is done.

I'm not 100% sure what's going on with the hack in the little batch file that gets created every update, but it's failing for me routinely in my scripting. I've had to script my own workaround by waiting for the batch window child-child to disappear before continuing with my scripts. I do like so:

```
start /wait "Youtube-DL Updater" cmd /C "cls & echo Checking for update to Youtube-DL ... & ..\youtube-dl.exe --ignore-config --update & exit"
:UpdaterDelayLoop
tasklist /fi "windowtitle eq Youtube-DL*"  | find "===" >nul && goto :UpdaterDelayLoop
```

That has my batch script force everything to run in a named window, and wait for the child batch script to die before moving on. That took a lot of .bat research for me, lol. Not sure if it will help in this situation, because I don't know how the updater and the app know when to move themselves on.

Someone with more skill will figure it out, but I'm working on Windows and I can read any ideas at least.

**Comment by pukkandan** [comment] 2021-05-22 13:13
The issue is that the updater (the batch) can only run after the exe's handle has closed.

Afaik, there is no way other than for the parent to wait for the update process to finish. I'm not sure if this is of any help, but the updater never takes more than ~6 sec to run after the main app is closed.

If you know of any way to replace the exe while keeping the process active, we can try to implement it

**Comment by pukkandan** [comment] 2021-05-22 13:25
> This was referenced already here: #64

If you are talking about this:
> But there is a small issue with the windows updater. If the file handle is not closed for whatever reason, the update won't be successful, but Updated youtube-dlc to version %s message is still issued. You can run youtube-dlc.exe -U URL to reproduce the issue reliably

This is a separate (but related) issue and is already fixed

**Comment by pukkandan** [comment] 2021-05-22 13:33
Related: https://github.com/ytdl-org/youtube-dl/issues/28488#issuecomment-808723707

**Comment by pukkandan** [comment] 2021-05-22 16:13
After a lot of experimentation, I actually found a fix for this: https://github.com/pukkandan/yt-dlp-dev/commit/20693e16eec518dcdb15596c5b77f18830eecea0

I need to do a lot more testing b4 this can be finalized though. Expect the patch in next release

**Closed** 2021-05-25 19:44 UTC
Labels: bug
