### ISSUE TITLE
[tiktok] 

### ISSUE THREAD

**Issue by Mo-0hammed** [yt-dlp/yt-dlp#2165] opened 2021-12-30 00:25 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

cmd : `'https://m.tiktok.com/v/7046834999626091778.html' '--no-playlist' '--ignore-config' '--write-info-json' '--format=bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' '--output=39580TK.%(ext)s'`

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://m.tiktok.com/v/7046834999626091778.html', '--no-playlist', '--ignore-config', '--write-info-json', '--format=bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--output=39580TK.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-91-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: https://m.tiktok.com/v/7046834999626091778.html
[generic] 7046834999626091778: Requesting header
[redirect] Following redirect to https://www.tiktok.com/@zo.zy1/video/7046834999626091778?source=h5_m&_r=1
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@zo.zy1/video/7046834999626091778?source=h5_m&_r=1
[TikTok] 7046834999626091778: Downloading video details
WARNING: [TikTok] 7046834999626091778: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; Retrying with webpage
[TikTok] 7046834999626091778: Downloading webpage
[TikTok] 7046834999626091778: Downloading video webpage
ERROR: [TikTok] 7046834999626091778: Unable to extract json_string; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/tiktok.py", line 368, in _real_extract
    json_string = self._search_regex(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 1173, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by pukkandan** [comment] 2021-12-30 00:31
Duplicate of #2133

**Closed by pukkandan** 2021-12-30 00:31 UTC
Labels: duplicate, site:tiktok
