### ISSUE TITLE
Download form ard mediathek failed 

### ISSUE THREAD

**Issue by mightyscrub** [yt-dlp/yt-dlp#1792] opened 2021-11-25 10:28 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Description

Download form ard mediathek failed with latest yt-dlp (2021.11.10.1). Download is working  with latest youtube-dl (2021.06.06).

### Verbose log

```shell
yt-dlp -Uv 'https://www.ardmediathek.de/video/snow-angels/folge-1-ohne-erinnerung-s01-e01/one/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTQ5ODM5Y2YzLWEyNjQtNDdhYi04MGMyLTdlMjA5MmJhNjkzZQ'
[debug] Command-line config: ['-Uv', 'https://www.ardmediathek.de/video/snow-angels/folge-1-ohne-erinnerung-s01-e01/one/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTQ5ODM5Y2YzLWEyNjQtNDdhYi04MGMyLTdlMjA5MmJhNjkzZQ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1 (zip)
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.15.0-1-amd64-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.4.1-2 (setts), ffprobe 4.4.1-2
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] Using fake IP 53.115.136.120 (DE) as X-Forwarded-For
[debug] [ARD:mediathek] Extracting URL: https://www.ardmediathek.de/video/snow-angels/folge-1-ohne-erinnerung-s01-e01/one/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTQ5ODM5Y2YzLWEyNjQtNDdhYi04MGMyLTdlMjA5MmJhNjkzZQ
[ARD:mediathek] Y3JpZDovL3dkci5kZS9CZWl0cmFnLTQ5ODM5Y2YzLWEyNjQtNDdhYi04MGMyLTdlMjA5MmJhNjkzZQ: Downloading webpage
[ARD:mediathek] 10064551: Downloading media JSON
ERROR: [ARD:mediathek] Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 713, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3295, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by pukkandan** [comment] 2021-11-25 11:01
Duplicate of #1601, fixed in 14a086058a30a0748b5b716e9b21481f993518f3

**Closed by pukkandan** 2021-11-25 11:01 UTC
Labels: extractor-bug, triage
