### ISSUE TITLE
Download YouTube playlist as .mru playlist or similar

### ISSUE THREAD

**Issue by zohozer** [yt-dlp/yt-dlp#3116] opened 2022-03-19 08:38 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hi. I do want to save all the URLs from a YouTube channel as .mru playlist, so I can use this playlist file to play all the downloaded files at once. It is possible to add this feature into yt-dlp? Best regards.

**Comment by pukkandan** [comment] 2022-03-19 13:42
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1633

**Closed by pukkandan** 2022-03-19 13:42 UTC
Labels: enhancement, triage

**Comment by pukkandan** [comment] 2022-03-19 13:44
FYI, you can kinda already do this with `--print-to-file` if you know how to format the file

**Comment by dirkf** [comment] 2022-03-19 14:15
Do you mean M3U? A list of the filenames would be adequate for that.

You can use `-q --exec echo` to print a list of the downloaded and post-processed filenames that you could redirect to `playlist.m3u` using shell facilities (eg, `> playlist.m3u`) while also actually downloading (and merging, etc) the files. Note `-q` required to avoid progress diagnostics mixed in with the playlist output.

As above `--print-to-file` or `--no-simulate -q --print` with a shell redirection might work but the template may need a WHEN: prefix to get the right filename: I couldn't get an extracted audio filename in that way, even with `after_video:filename` or `after_video:filepath`. 

Once you can make the list of filenames, it should be possible to use command-line shell facilities and additional yt-dlp options to make a more advanced playlist file (`#EXTM3U ...`). Eg, with a POSIX shell:
```
{ echo '#EXTM3U'; yt-dlp -q --exec "printf '%(filepath)s\n%s' '#EXTIMG: %(thumbnail)s'" "$playlist_url_or_id" }
```
Exercise 1: translate the above for Windows _cmd_

Exercise 2: write the filename of the thumbnail saved as a separate file into the `#EXTIMG` line. This may be a research problem.

**Comment by pukkandan** [comment] 2022-03-19 14:17
`--exec echo` ~= `--print after_move:`

**Comment by pukkandan** [comment] 2022-03-19 14:21
> printf '%(filepath)s\n%s'

Better to use `%(filepath)q` since this will break if filename contains single quote

**Comment by zohozer** [comment] 2022-03-19 19:42
Thank you for the answers.

I do tryed the following command:

`yt-dlp.exe https://www.youtube.com/channel/UCP5tjEmvPItGyLhmjdwP7Ww --exec echo --print after_move:%(filepath)q`

but seems that yt-dlp it is not doing anything.

**Comment by dirkf** [comment] 2022-03-19 19:51
`--exec echo` or `--print ...`, not both:
```
$ yt-dlp -q --exec echo PL8BCB4981DD1A0108
/home/wherever/Lecture 1 _ New Revolutions in Particle Physics - Standard Model [Igl8hE3Eac0].mp4
...
$
```

>Better to use %(filepath)q since this will break if filename contains single quote

`printf '%s\n%s' %(filepath)q ...` then?

**Comment by pukkandan** [comment] 2022-03-19 22:57
> yt-dlp.exe https://www.youtube.com/channel/UCP5tjEmvPItGyLhmjdwP7Ww --exec echo --print after_move:%(filepath)q

> but seems that yt-dlp it is not doing anything.

Add a `--no-simulate`

`--print` implies `-s`. I am aware this doesn't make much sense when using after_move as WHEN, but I have not yet decided how to deal with this

**Comment by zohozer** [comment] 2022-03-20 19:43
`yt-dlp.exe --get-filename --skip-download --quiet https://www.youtube.com/channel/UCP5tjEmvPItGyLhmjdwP7Ww`

This command prints the correct output in console, but I need a way to print this also to a file.

If I add `--print-to-file _list.txt` I do get the following error:

`yt-dlp: error: --print-to-file option requires 2 arguments`

I don't understand what are the two required arguments.

**Comment by pukkandan** [comment] 2022-03-20 19:47
You obviously have to tell it What to print!

From readme:
```
    --print-to-file [WHEN:]TEMPLATE FILE
                                     Append given template to the file. The
                                     values of WHEN and TEMPLATE are same as
                                     that of --print. FILE uses the same syntax
                                     as the output template. This option can be
                                     used multiple times
```

so in your case, it would be `--print-to-file filepath _list.txt`

**Comment by zohozer** [comment] 2022-03-20 19:57
It is possible to replace automatically the `filepath` argument with the current directory if no argument it is provided?

**Comment by zohozer** [comment] 2022-03-20 20:07
If I do use `--print-to-file C:\temp\mylist _list.txt` I do get into the output file: `C:\temp\mylist` on every single line.

**Comment by dirkf** [comment] 2022-03-20 23:16
>This command prints the correct output in console, but I need a way to print this also to a file.

Learn about **shell redirection** from the web (add your OS name Windows/Linux/macOS/whatever to the search to get the most useful answers).

>Seems that whatewer I put between --print-to-file and _list.txt it is just printed inside of the _list.txt file

That's exactly what the `--print-to-file` option does. Try `--print-to-file after_move:%(filepath)q _list.txt` or just `--print-to-file filepath _list.txt` as in  https://github.com/yt-dlp/yt-dlp/issues/3116#issuecomment-1073335419.
