### ISSUE TITLE
twitter changed domain name to x.com

### ISSUE THREAD

**Issue by terrancewong** [yt-dlp/yt-dlp#10010] opened 2024-05-23 17:32 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

twitter changed it primary domain to x.com. so copied video address will be x.com.

video download with x.com url failes, but works if replace 'x' with 'twitter'

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
% yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.7.12-amd64-x86_64-with-glibc2.38 (OpenSSL 3.2.2-dev , glibc 2.38)
[debug] exe versions: ffmpeg 6.1.1-4 (setts), ffprobe 6.1.1-4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, requests-2.31.0, sqlite3-3.45.3, urllib3-1.26.18, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)

 % yt-dlp --output %(title).30s.%(id)s.%(ext)s https://x.com/i/status/1793243998351483249
[generic] Extracting URL: https://x.com/i/status/1793243998351483249
[generic] 1793243998351483249: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1793243998351483249: Extracting information
ERROR: Unsupported URL: https://x.com/i/status/1793243998351483249

 % yt-dlp --output %(title).30s.%(id)s.%(ext)s https://twitter.com/i/status/1793243998351483249
[twitter] Extracting URL: https://twitter.com/i/status/1793243998351483249
[twitter] 1793243998351483249: Downloading guest token
[twitter] 1793243998351483249: Downloading GraphQL JSON
[twitter] 1793243998351483249: Downloading m3u8 information
[info] 1793239547024683008: Downloading 1 format(s): http-632
[download] Destination: Bin Xie - Chinese EV BYD model.1793239547024683008.mp4
[download] 100% of  451.65KiB in 00:00:00 at 2.34MiB/s
```

**Comment by seproDev** [comment] 2024-05-23 17:34
Duplicate of #9923

Update to nightly:

```
# To update to nightly from stable executable/binary:
yt-dlp --update-to nightly

# To install nightly with pip:
python3 -m pip install -U --pre "yt-dlp[default]"
```

**Closed by seproDev** 2024-05-23 17:34 UTC
Labels: site-bug, triage
