### ISSUE TITLE
[Question] merge one video with multi audio

### ISSUE THREAD

**Issue by apt42541** [yt-dlp/yt-dlp#610] opened 2021-08-02 10:39 UTC
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

can i use yt-dlp for merge  one video with multi audio ?

**Comment by pukkandan** [comment] 2021-08-02 13:54
Duplicate of #607

**Comment by pukkandan** [comment] 2021-08-02 13:55
oops, sorry for closing

Use `--audio-multistreams -f videoformat+audio1+audio2`

**Comment by apt42541** [comment] 2021-08-03 06:35
if i want to merge with -allow-unplayable-formats ?

**Comment by MinePlayersPE** [comment] 2021-08-03 06:44
afaik like the error said, you are not able to merge them with ffmpeg unless you decrypt them first (which is another story)

**Comment by apt42541** [comment] 2021-08-03 06:45
i already decrypt... can i merge with multi format sir ?

**Comment by MinePlayersPE** [comment] 2021-08-03 06:47
not yt-dlp related, but hopefully `ffmpeg -i <videofile> -i <audiofile1> -i <audiofile2> -c copy <mergedfile>` should do

**Comment by apt42541** [comment] 2021-08-03 07:16
i tring to find a way to merge with auto name of feature yt-dlp  

![image](https://user-images.githubusercontent.com/12625408/127973877-be102b6b-0cf8-48a8-a944-8d04818e2144.png)

**Comment by pukkandan** [comment] 2021-08-03 13:37
You are asking help for ripping DRM protected content. No help will be provided by use for this

**Closed by pukkandan** 2021-08-03 13:37 UTC
Labels: question
