### ISSUE TITLE
yt-dlp gets stuck at "Testing format 609"

### ISSUE THREAD

**Issue by pboettcher** [yt-dlp/yt-dlp#10324] opened 2024-07-01 15:15 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

yt-dlp gets stuck at "Testing format 609" and CPU becomes hot when started directly.
Same URL works when started from a batch file.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Normally I do this from a GUI-shell-program with CreateProcess, but here is how to reproduce this:

Press Win+R and enter a following command:

"C:\Program Files (x86)\yt-dlp\yt-dlp.exe" -vU -f "bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]" -o "R:\%(release_date,upload_date)s %(title)s.%(ext)s" "https://www.youtube.com/watch?v=es5brHuuxdk"

yt-dlp starts, but then it gets stuck on the "Testing format 609" line and CPU becomes hot.

[debug] Command-line config: ['-vU', '-f', 'bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]', '-o', 'R:\\%(release_date,upload_date)s %(title)s.%(ext)s', 'https://www.youtube.com/watch?v=es5brHuuxdk']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-10-12-git-a7663c9604-full_build-www.gyan.dev (setts), ffprobe 2023-10-12-git-a7663c9604-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.2, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=es5brHuuxdk
[youtube] es5brHuuxdk: Downloading webpage
[youtube] es5brHuuxdk: Downloading ios player API JSON
[debug] Loading youtube-nsig.5b22937f from cache
[debug] [youtube] Decrypted nsig 57FQLCaUV2wTz6Fv => 0v_bd6u0Ejcwkg
[debug] Loading youtube-nsig.5b22937f from cache
[debug] [youtube] Decrypted nsig VLruxLz29QYmRFha => b5Dh1iOFgykkSQ
[youtube] es5brHuuxdk: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Testing format 609

======

If I write the same command into a batch file:

@echo off
chcp 65001
"C:/Program Files (x86)/yt-dlp/yt-dlp.exe" -f "bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]" -o "R:\%%(release_date,upload_date)s %%(title)s.%%(ext)s" "https://www.youtube.com/watch?v=es5brHuuxdk"
pause

taking into account only that percent sign should be escaped, it downloads the video normally.
```

**Comment by bashonly** [comment] 2024-07-01 16:06
```
[info] Testing format 609
```
yt-dlp is trying to write a temp file when it does this. What is the current working directory of your terminal when you encounter the issue?

**Comment by bashonly** [comment] 2024-07-01 16:07
Most likely a duplicate of #7894

**Comment by pboettcher** [comment] 2024-07-01 17:25
> ```
> [info] Testing format 609
> ```
> 
> yt-dlp is trying to write a temp file when it does this. What is the current working directory of your terminal when you encounter the issue?

1. I't better get this information from yt-dlp debug output, what yt-dlp thinks, its working directory is.
2. I used the same command line for approximately one year before this suddenly started.
3. Will check the working directory in a couple of hours.

**Comment by bashonly** [comment] 2024-07-01 17:27
> working directory

It's the current directory of your terminal, it should be visible in the command prompt e.g.

```
C:\>
```

> I used the same command line for approximately one year before this suddenly started.

yt-dlp only forces `--check-formats` for newly posted Youtube videos (within the past calendar day) when HLS formats are being selected for download. So it's likely you just hadn't run into this scenario before. A workaround is passing `--no-check-formats`

**Comment by pboettcher** [comment] 2024-07-02 07:15
> > working directory
> 
> It's the current directory of your terminal, it should be visible in the command prompt e.g.
> 
> ```
> C:\>
> ```
> 
> > I used the same command line for approximately one year before this suddenly started.
> 
> yt-dlp only forces `--check-formats` for newly posted Youtube videos (within the past calendar day) when HLS formats are being selected for download. So it's likely you just hadn't run into this scenario before. A workaround is passing `--no-check-formats`

When I am doing this from the already started terminal, everything works. I thought about fresh videos, but this very video isn't fresh anymore and I am still experiencing same issue.

**Comment by pboettcher** [comment] 2024-07-02 07:36
I changed the call to

_run(exePath, cmdLine, dest);

and now it worked. The drawback is that when dest is an UNC network path, everything hangs as before, because Windows doesn't allow to set an UNC path as a working directory.

I could set a %TEMP% path as the working directory, but I'd prefer the RAM disk R: to save the SSD life a bit. Other users, who use this shell, but do not have the R: drive, will suffer.

**Comment by bashonly** [comment] 2024-07-02 07:50
> I thought about fresh videos, but this very video isn't fresh anymore and I am still experiencing same issue.

Please show a log of this, this shouldn't be happening unless the video was posted within the past 2 days or unless you are manually passing `--check-formats`

> Other users, who use this shell, but do not have the R: drive, will suffer.

It's 10KB or less. If you're worried about disk writes, then I'd be much more concerned about what the pyinstaller executable unpacks to temp. As I said above, you can pass `--no-check-formats` if you really don't want any format testing.

**Comment by bashonly** [comment] 2024-07-02 07:52
Closing as duplicate of #7894

**Closed by bashonly** 2024-07-02 07:52 UTC
Labels: bug, duplicate, external issue
