### ISSUE TITLE
Select "good" subtitle file on arte.tv 

### ISSUE THREAD

**Issue by pavel167** [yt-dlp/yt-dlp#4254] opened 2022-07-03 10:44 UTC
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello,

Downloading subtitles on arte.tv videos dosn't work correctly.
For French language there are 2 version of subtitles:

- Complete subtitle file, where everything is subtitled regardless of the language spoken
- "Good" subtitle file where only languages other than French are subtitled

BTW when video is playing online it's "good" subtitle file that is selected.
You can dowload it using Firefox's "Web Development Tool" facilities: specify vtt in "Filter" while selecting "Network" tab ... link to vtt file of "good" subtitles appears.
But when using option write-subs and selecting French, it's Complete subtitle file that is downloaded.
Here is example:
[https://www.arte.tv/fr/videos/104769-000-A/antonio-banderas-et-pedro-almodovar/](url)
The size of "good" subtitles file is about 44kB, whereas size of "complete" subtitles (downloaded using option write-subs and selecting French) is about 98kB.

How to select a "Good" version of subtitles.
Thanks

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by HobbyistDev** [comment] 2022-07-03 10:50
Seems related to #3302

**Comment by pavel167** [comment] 2022-07-03 10:57
I searched 3302, but couldn't find anything related to the problem, revealed in my 1st post.

**Comment by pavel167** [comment] 2022-07-03 11:08
When you ask for the subtitles for this particular video, you can see that apparently _French_ and _German_ have two subtitles. Otherwise how to explain two **vtt** symbols for _French_ and _German_ unlike only one for _English_ and _Italian_.
Here is output of --list subs request (I did not understand why the lines are crossed out.)

(arte_env1) pavel@ALABAMA:~/arte_env1$ yt-dlp --list-subs --skip-download https://www.arte.tv/fr/videos/104769-000-A/antonio-banderas-et-pedro-almodovar/
DeprecationWarning: Support for Python version 3.6 has been deprecated and will break in future versions of yt-dlp! Please update to Python 3.7 or above
[ArteTV] 104769-000-A: Downloading JSON metadata
[ArteTV] 104769-000-A: Downloading m3u8 information
[ArteTV] 104769-000-A: Downloading m3u8 information
[ArteTV] 104769-000-A: Downloading m3u8 information
[ArteTV] 104769-000-A: Downloading m3u8 information
[ArteTV] 104769-000-A: Downloading m3u8 information
[ArteTV] 104769-000-A: Downloading m3u8 information
[info] Available subtitles for 104769-000-A:
Language Formats
fr       vtt, vtt
de       vtt, vtt
en       vtt
it       vtt
(arte_env1) pavel@ALABAMA:~/arte_env1$

**Comment by Ashish0804** [comment] 2022-07-03 14:04
Currently it is not possible to select subs (other than the lang ofc).
and yes ur assumption is likely correct that there are 2 vtt for ger and fr bcoz there are 2 types of subs available.


@fstirlitz can u take this feature in ur PR aswell. Use `good-` as a prefix for the subs. 
So after the patch, --list subs will show:
```
fr vtt
good-fr vtt
de vtt
good-de vtt
en vtt
it vtt
```

**Comment by fstirlitz** [comment] 2022-07-03 15:51
What is a ‘good’ subtitle file?

**Comment by pukkandan** [comment] 2022-07-03 16:30
The extractor could implement this in #3302 as Ashish said. But the general feature request is a duplicate of https://github.com/yt-dlp/yt-dlp/issues/946

**Closed by pukkandan** 2022-07-03 16:30 UTC
Labels: enhancement, triage
