### ISSUE TITLE
--sponsorblock-remove sponsor leads to ERROR: Postprocessing: Conversion failed!

### ISSUE THREAD

**Issue by Geneocide** [yt-dlp/yt-dlp#5753] opened 2022-12-09 17:35 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

If I remove the --sponsorblock-remove sponsor parameter the video downloads without complaint. Also, for videos without a "sponsor" section from sponsorblock, there is no problem. Command I used to generate the verbose log is below. Please let me know if there's anything I can do to help.

yt-dlp -S  "res:1080" --merge-output-format mp4 --mark-watched --sponsorblock-remove sponsor -vU "https://www.youtube.com/watch?v=2xUKzeflvR0"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-S', 'res:1080', '--merge-output-format', 'mp4', '--mark-watched', '--sponsorblock-remove', 'sponsor', '-vU', 'https://www.youtube.com/watch?v=2xUKzeflvR0']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-102811-ga978b915ec-gde8e6e67e7 (setts), ffprobe N-102811-ga978b915ec-gde8e6e67e7
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=2xUKzeflvR0
[youtube] 2xUKzeflvR0: Downloading webpage
[youtube] 2xUKzeflvR0: Downloading android player API JSON
[debug] Sort order given by user: res:1080
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, res:1080(1080.0), quality, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/68cb?service=YouTube&categories=%5B%22sponsor%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%2C+%22chapter%22%5D
[SponsorBlock] Found 2 segments in the SponsorBlock database
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2xUKzeflvR0: Downloading 1 format(s): 247+251
[debug] Invoking http downloader on "https://rr5---sn-qxo7rn7r.googlevideo.com/videoplayback?expire=1670628478&ei=HnCTY4DOJuaglu8Pzu-X6AE&ip=73.243.167.69&id=o-AFjkf3Ol5MdemN2ugCgNgse5YzTYbeSvEEK8tOatV7oZ&itag=247&source=youtube&requiressl=yes&mh=Ab&mm=31%2C29&mn=sn-qxo7rn7r%2Csn-qxoedne7&ms=au%2Crdu&mv=m&mvi=5&pl=16&initcwndbps=1840000&spc=SFxXNiFaFXtSent3yVqxZ_NRenmlo4c&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=38902164&dur=633.900&lmt=1670525189413863&mt=1670606707&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAP6Scw4Cw2_6CMbjFsq2F7c6KCyPzs9BA6GfEIFXT9tQAiAnymAjYsW9cWCM2DUCOkYEUJ6FhMJQLf1IoqqM_QmIYA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAJLHJeds87Uty0lz_vffl1am__zRhnol7tvx0aMl4Ry4AiBNu_-SnIxy5K3brm36_3dTo38OQc5ItvXLmE--F6i2Ew%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: True Facts： Animal Awards [2xUKzeflvR0].f247.webm
[download] 100% of   37.10MiB in 00:00:01 at 20.20MiB/s
[debug] Invoking http downloader on "https://rr5---sn-qxo7rn7r.googlevideo.com/videoplayback?expire=1670628478&ei=HnCTY4DOJuaglu8Pzu-X6AE&ip=73.243.167.69&id=o-AFjkf3Ol5MdemN2ugCgNgse5YzTYbeSvEEK8tOatV7oZ&itag=251&source=youtube&requiressl=yes&mh=Ab&mm=31%2C29&mn=sn-qxo7rn7r%2Csn-qxoedne7&ms=au%2Crdu&mv=m&mvi=5&pl=16&initcwndbps=1840000&spc=SFxXNiFaFXtSent3yVqxZ_NRenmlo4c&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=11109737&dur=633.941&lmt=1670512728360855&mt=1670606707&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgLwTUGZP3FjekUURE0F2sJUsKUv_zCY-bWPM0uw46vXACIHQ1ZcFPz9Fz2pxJKTf0ZbkIFUZmgELn5Zk-4w2idfIj&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAJLHJeds87Uty0lz_vffl1am__zRhnol7tvx0aMl4Ry4AiBNu_-SnIxy5K3brm36_3dTo38OQc5ItvXLmE--F6i2Ew%3D%3D"
[download] Destination: True Facts： Animal Awards [2xUKzeflvR0].f251.webm
[download] 100% of   10.60MiB in 00:00:00 at 16.26MiB/s
[Merger] Merging formats into "True Facts： Animal Awards [2xUKzeflvR0].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:True Facts： Animal Awards [2xUKzeflvR0].f247.webm" -i "file:True Facts： Animal Awards [2xUKzeflvR0].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:True Facts： Animal Awards [2xUKzeflvR0].temp.mp4"
Deleting original file True Facts： Animal Awards [2xUKzeflvR0].f251.webm (pass -k to keep)
Deleting original file True Facts： Animal Awards [2xUKzeflvR0].f247.webm (pass -k to keep)
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:True Facts： Animal Awards [2xUKzeflvR0].mp4"
[debug] Concat spec = 2.915000-264.813000, 334.581000-inf
[ModifyChapters] Removing chapters from True Facts： Animal Awards [2xUKzeflvR0].mp4
[debug] Writing concat spec to True Facts： Animal Awards [2xUKzeflvR0].temp.mp4.concat
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -hide_banner -nostdin -f concat -safe 0 -i "file:True Facts： Animal Awards [2xUKzeflvR0].temp.mp4.concat" -map 0 -dn -ignore_unknown -c copy "-c:s" mov_text -movflags "+faststart" "file:True Facts： Animal Awards [2xUKzeflvR0].temp.mp4"
[debug] Input #0, concat, from 'file:True Facts： Animal Awards [2xUKzeflvR0].temp.mp4.concat':
  Duration: N/A, start: -2.915000, bitrate: 626 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 1280x720, 489 kb/s, SAR 1:1 DAR 16:9, 29.97 fps, 29.97 tbr, 16k tbn
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 137 kb/s
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
[mp4 @ 0000020b3bc5e500] track 1: codec frame size is not set
Output #0, mp4, to 'file:True Facts： Animal Awards [2xUKzeflvR0].temp.mp4':
  Metadata:
    encoder         : Lavf59.3.101
  Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 489 kb/s, 29.97 fps, 29.97 tbr, 16k tbn
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: opus (Opus / 0x7375704F), 48000 Hz, stereo, fltp, 137 kb/s
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
frame=    1 fps=0.0 q=-1.0 size=       0kB time=00:00:00.00 bitrate=5587.3kbits/s speed=N/A
[mp4 @ 0000020b3bc5e500] Non-monotonous DTS in output stream 0:1; previous: 12710448, current: 12585264; changing to 12710449. This may result in incorrect timestamps in the output file.
[concat @ 0000020b3bc4d7c0] DTS 4148512 < 4190112 out of order
[mp4 @ 0000020b3bc5e500] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 4236752 >= 4195152
av_interleaved_write_frame(): Invalid argument
[mp4 @ 0000020b3bc5e500] Starting second pass: moving the moov atom to the beginning of the file
frame= 7938 fps=0.0 q=-1.0 Lsize=   22253kB time=00:04:24.80 bitrate= 688.4kbits/s speed=1.14e+03x
video:17614kB audio:4393kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.114230%
Conversion failed!

ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3276, in process_info
  File "yt_dlp\YoutubeDL.py", line 3453, in post_process
  File "yt_dlp\YoutubeDL.py", line 3435, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3414, in run_pp
  File "yt_dlp\postprocessor\common.py", line 24, in run
  File "yt_dlp\postprocessor\common.py", line 129, in wrapper
  File "yt_dlp\postprocessor\modify_chapters.py", line 61, in run
  File "yt_dlp\postprocessor\modify_chapters.py", line 59, in remove_chapters
  File "yt_dlp\postprocessor\modify_chapters.py", line 318, in remove_chapters
  File "yt_dlp\postprocessor\ffmpeg.py", line 415, in concat_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 361, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

**Comment by bashonly** [comment] 2022-12-09 18:24
This is happening due to an issue with ffmpeg versions older than 5.1:
https://github.com/yt-dlp/FFmpeg-Builds#2-fix-for-youtubes-vp9-encodes-with-non-monotonous-dts

[As recommended in the readme](https://github.com/yt-dlp/yt-dlp#strongly-recommended), you could use the [yt-dlp custom builds of ffmpeg](https://github.com/yt-dlp/FFmpeg-Builds). Or you can use a [vanilla ffmpeg build](https://github.com/BtbN/FFmpeg-Builds) as long as it is version 5.1 or newer. Either would solve this issue.

Also: I've noticed that the master builds (`ffmpeg-N-1`...) have been a bit dicey lately, so IMO it would be better to go with a stable build (`ffmpeg-n5.1`...)

Closing as duplicate of #871

**Closed by bashonly** 2022-12-09 18:24 UTC
Labels: bug, triage

**Comment by Geneocide** [comment] 2022-12-09 18:49
ooo... thanks. I didn't pick up on the version of ffmpeg.
