### ISSUE TITLE
[ARD:mediathek] Video not downloadable: 410 - Gone

### ISSUE THREAD

**Issue by tplank** [yt-dlp/yt-dlp#8127] opened 2023-09-16 20:53 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Austria

### Provide a description that is worded well enough to be understood

Video is marked as "410 Gone" but is normally playable in the browser.

Possible duplicate of https://github.com/yt-dlp/yt-dlp/issues/7666 - but unfortunately I'm not sure.

Update to latest nightly `yt-dlp version nightly@2023.09.16.182946 [069cbece9] (zip)` has no effect.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--no-check-certificate', '--no-cache-dir', '--ignore-errors', '--no-progress', '--compat-options', 'filename', '--format', 'best[height<1080]', '-o', '%(title)s.%(ext)s', 'https://www.ardmediathek.de/video/dokus-und-reportagen/1923-der-lange-schatten-der-inflation/hr-fernsehen/ZTRjYTRhMGYtZTlkYi00M2RjLThjYmUtZmFmZTIwYWI5YmFh']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (zip)
[debug] Compatibility options: *filename
[debug] Python 3.9.16 (CPython x86_64 64bit) - CYGWIN_NT-10.0-22623-3.4.8-1.x86_64-x86_64-64bit-WindowsPE (OpenSSL 1.1.1v  1 Aug 2023)
[debug] exe versions: ffmpeg 2023-09-04-git-f8503b4c33-full_build-www.gyan.dev (setts), ffprobe 2023-09-04-git-f8503b4c33-full_build-www.gyan.dev
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: cedf44a9cf3c241520a692c1006d276e6f434d4d945727c47cb1a70d32953f4a
yt-dlp is up to date (stable@2023.07.06)
[debug] Using fake IP 53.155.54.10 (DE) as X-Forwarded-For
[ARD:mediathek] Extracting URL: https://www.ardmediathek.de/video/dokus-und-reportagen/1923-der-lange-schatten-der-inflation/hr-fernsehen/ZTRjYTRhMGYtZTlkYi00M2RjLThjYmUtZmFmZTIwYWI5YmFh
[ARD:mediathek] ZTRjYTRhMGYtZTlkYi00M2RjLThjYmUtZmFmZTIwYWI5YmFh: Downloading webpage
[ARD:mediathek] 94736366: Downloading media JSON
ERROR: [ARD:mediathek] None: Unable to download JSON metadata: HTTP Error 410: Gone (caused by <HTTPError 410: 'Gone'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/cygdrive/c/Dropbox/Tools/youtube-dl/yt-dlp/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "/cygdrive/c/Dropbox/Tools/youtube-dl/yt-dlp/yt_dlp/extractor/ard.py", line 275, in _real_extract
    info = self._extract_media_info(
  File "/cygdrive/c/Dropbox/Tools/youtube-dl/yt-dlp/yt_dlp/extractor/ard.py", line 28, in _extract_media_info
    media_info = self._download_json(
  File "/cygdrive/c/Dropbox/Tools/youtube-dl/yt-dlp/yt_dlp/extractor/common.py", line 1064, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/cygdrive/c/Dropbox/Tools/youtube-dl/yt-dlp/yt_dlp/extractor/common.py", line 1028, in download_handle
    res = self._download_webpage_handle(
  File "/cygdrive/c/Dropbox/Tools/youtube-dl/yt-dlp/yt_dlp/extractor/common.py", line 898, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/cygdrive/c/Dropbox/Tools/youtube-dl/yt-dlp/yt_dlp/extractor/common.py", line 855, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/cygdrive/c/Dropbox/Tools/youtube-dl/yt-dlp/yt_dlp/extractor/common.py", line 837, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/cygdrive/c/Dropbox/Tools/youtube-dl/yt-dlp/yt_dlp/YoutubeDL.py", line 3863, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 410: Gone
```

**Comment by bashonly** [comment] 2023-09-16 21:39
Yeah looks like it is indeed a duplicate of #7666

**Closed by bashonly** 2023-09-16 21:39 UTC
Labels: site-bug, triage
