### ISSUE TITLE
Can't download a certain Youtube video

### ISSUE THREAD

**Issue by vortaj** [yt-dlp/yt-dlp#7884] opened 2023-08-17 18:20 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

Other videos in this format (137) download with no errors

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=vX5PevdrOS0']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n4.4.1-1-gb9f55b190f-20211026 (setts), ffprobe n4.4.1-1-gb9f55b190f-20211026, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=vX5PevdrOS0
[youtube] vX5PevdrOS0: Downloading webpage
[youtube] vX5PevdrOS0: Downloading ios player API JSON
[youtube] vX5PevdrOS0: Downloading android player API JSON
[debug] Loading youtube-nsig.f980f2a9 from cache
[debug] [youtube] Decrypted nsig u0l-FVuvNrIyMxG2Th => ZqKCW5YX6cRzsw
[youtube] vX5PevdrOS0: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] vX5PevdrOS0: Downloading 1 format(s): 137+140
[debug] Invoking http downloader on "https://rr7---sn-gvnuxaxjvh-304s.googlevideo.com/videoplayback?expire=1692317607&ei=R2PeZPeEC62Sv_IPw6WLgAU&ip=2a00%3A1e88%3A780c%3Af702%3A7489%3Abdd9%3A7dd1%3Addaa&id=o-AGL7PW-oOpwS8ToFqTz2fESHK1jd3Wq7LQ6ZnvrOlqMA&itag=137&source=youtube&requiressl=yes&mh=9o&mm=31%2C29&mn=sn-gvnuxaxjvh-304s%2Csn-n8v7kn7d&ms=au%2Crdu&mv=m&mvi=7&pl=35&initcwndbps=1028750&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=216748180&dur=2519.440&lmt=1673848674182025&mt=1692295780&fvip=12&keepalive=yes&fexp=24007246%2C24363391&beids=24350018&c=IOS&txp=1216224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgZbUJonN-dn3rdyYeucnnNzh3bS4T-P8o91aMvNWGi2cCIQCUCMPLLgdNTzInlkmJVEIu1A3gRejRm7d9uWF-tcO6AA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgMNnX3cYd7U2RC8A6euVDfR1CO00NwyTe4GHdaaoDv4UCIHOD39hif0-KecxYhopcrNbo_DWpDz6H6r6fx47T1uAU"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Binding of Isaac - Wrath of the Lamb - sBoy [vX5PevdrOS0].f137.mp4
[download]  24.0% of  206.71MiB at    9.07MiB/s ETA 00:17[download] Got error: The read operation timed out. Retrying (1/10)...
[download] Destination: Binding of Isaac - Wrath of the Lamb - sBoy [vX5PevdrOS0].f137.mp4
[download]  24.2% of  206.71MiB at   65.89KiB/s ETA 40:35[download] Got error: HTTP Error 503: Service Unavailable. Retrying (2/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (3/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (4/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (5/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (6/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (7/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (8/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (9/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Retrying (10/10)...
[download] Got error: HTTP Error 503: Service Unavailable. Giving up after 10 retries
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1008, in main
  File "yt_dlp\__init__.py", line 998, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3485, in download
  File "yt_dlp\YoutubeDL.py", line 3460, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1549, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1709, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1768, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2897, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3345, in process_info
  File "yt_dlp\YoutubeDL.py", line 3084, in dl
  File "yt_dlp\downloader\common.py", line 461, in download
  File "yt_dlp\downloader\http.py", line 375, in real_download
  File "yt_dlp\utils\_utils.py", line 5634, in __iter__
  File "yt_dlp\downloader\common.py", line 402, in report_retry
  File "yt_dlp\utils\_utils.py", line 5641, in report_retry
  File "yt_dlp\downloader\common.py", line 405, in <lambda>
  File "yt_dlp\YoutubeDL.py", line 1042, in report_error
  File "yt_dlp\YoutubeDL.py", line 970, in trouble


[debug] Invoking http downloader on "https://rr7---sn-gvnuxaxjvh-304s.googlevideo.com/videoplayback?expire=1692317607&ei=R2PeZPeEC62Sv_IPw6WLgAU&ip=2a00%3A1e88%3A780c%3Af702%3A7489%3Abdd9%3A7dd1%3Addaa&id=o-AGL7PW-oOpwS8ToFqTz2fESHK1jd3Wq7LQ6ZnvrOlqMA&itag=140&source=youtube&requiressl=yes&mh=9o&mm=31%2C29&mn=sn-gvnuxaxjvh-304s%2Csn-n8v7kn7d&ms=au%2Crdu&mv=m&mvi=7&pl=35&initcwndbps=1028750&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=40776106&dur=2519.504&lmt=1673847818031516&mt=1692295780&fvip=12&keepalive=yes&fexp=24007246%2C24363391&beids=24350018&c=IOS&txp=1211224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIt3gE4ToA8rjg4mWmPPaxFgvIKpsV9qvXtnS7pck8wTAiAKj_f7a7KGXGKdy11F6VAfm6meBC_eVANdHO1zZv0jQw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgMNnX3cYd7U2RC8A6euVDfR1CO00NwyTe4GHdaaoDv4UCIHOD39hif0-KecxYhopcrNbo_DWpDz6H6r6fx47T1uAU"
[download] Destination: Binding of Isaac - Wrath of the Lamb - sBoy [vX5PevdrOS0].f140.m4a
[download] 100% of   38.89MiB in 00:00:04 at 8.94MiB/s
```

**Comment by bashonly** [comment] 2023-08-17 18:52
> HTTP Error 503: Service Unavailable

This is an error on Youtube's end, there is a problem with this particular format. Nothing we can do

Usually  you could add `--check-formats` to your command and it would detect this sort of problem and auto-select the next best format, but that option is broken in `2023.07.06`. Update to nightly if you want to be able to use it.

Or else you could add `-f 270+140` to your command to get an alternate/working 1080p avc video format

Closing as duplicate of #7872

**Closed by bashonly** 2023-08-17 18:52 UTC
Labels: site-bug, triage

**Comment by vortaj** [comment] 2023-08-17 19:22
> > HTTP Error 503: Service Unavailable
> 
> This is an error on Youtube's end, there is a problem with this particular format. Nothing we can do
> 
> Usually you could add `--check-formats` to your command and it would detect this sort of problem and auto-select the next best format, but that option is broken in `2023.07.06`. Update to nightly if you want to be able to use it.
> 
> Or else you could add `-f 270+140` to your command to get an alternate/working 1080p avc video format
> 
> Closing as duplicate of #7872

270 doesn't work as well

**Comment by bashonly** [comment] 2023-08-17 19:33
Try adding `--extractor-args "youtube:player_client=web"`
That fixes format 137 for me

**Comment by vortaj** [comment] 2023-08-17 19:37
Also, although I'm not a web developer and may not understand something, my issue doesn't seem like a total duplicate of the mentioned one.

**Comment by bashonly** [comment] 2023-08-17 19:38
It's a duplicate in that the problem is on Youtube's end and we have no control over it, and the workarounds/solutions is the same

**Comment by vortaj** [comment] 2023-08-17 19:42
OK, thanks for the suggestion and for the explanation
