### ISSUE TITLE
No comments downloaded from youtube video. 

### ISSUE THREAD

**Issue by sidomir7** [yt-dlp/yt-dlp#9974] opened 2024-05-20 08:48 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi when I am using --write-comments switch comments are not downloaded to .info.json file. 
I tried it on more then one video. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--write-comments', 'https://www.youtube.com/watch?v=nPtfVJlK0Ko']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.2.0-39-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=nPtfVJlK0Ko
[youtube] nPtfVJlK0Ko: Downloading webpage
[youtube] nPtfVJlK0Ko: Downloading ios player API JSON
[youtube] nPtfVJlK0Ko: Downloading android player API JSON
WARNING: [youtube] Skipping player responses from android clients (got player responses for video "aQvGIIdgFDM" instead of "nPtfVJlK0Ko")
[debug] Loading youtube-nsig.b05eda73 from cache
[debug] [youtube] Decrypted nsig BC7gFaBcOi6KLiqmkzED => tKqB8iAI9y6Veg
[debug] Loading youtube-nsig.b05eda73 from cache
[debug] [youtube] Decrypted nsig AtFQh6KuAWTbaVixl5cD => jOm4hT8x70ZRSA
[youtube] nPtfVJlK0Ko: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[youtube] Downloading comment section API JSON
[youtube] Downloading ~136 comments
[youtube] Sorting comments by newest first
[youtube] Downloading comment API JSON page 1 (0/~136)
[youtube] Downloading comment API JSON page 2 (0/~136)
[youtube] Downloading comment API JSON page 3 (0/~136)
[youtube] Downloading comment API JSON page 4 (0/~136)
[youtube] Downloading comment API JSON page 5 (0/~136)
[youtube] Downloading comment API JSON page 6 (0/~136)
[youtube] Extracted 0 comments
[debug] Default format spec: bestvideo*+bestaudio/best
[info] nPtfVJlK0Ko: Downloading 1 format(s): 308+251
[info] Writing video metadata as JSON to: Hrali sme 2 vs 2 AIRSOFT Turnaj [nPtfVJlK0Ko].info.json
[debug] Invoking http downloader on "https://rr1---sn-nav853-cunz.googlevideo.com/videoplayback?expire=1716216222&ei=Pg1LZorfHdmt6dsPhOCM2Ag&ip=91.228.164.152&id=o-AKMdkQSEr-7tHHLf9YeBT0EHW5Da_9cCkM9T5EWqZ-Ef&itag=308&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=EB&mm=31%2C29&mn=sn-nav853-cunz%2Csn-2gb7snez&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=24&initcwndbps=7490000&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=959538536&dur=624.140&lmt=1714358144465304&mt=1716194472&fvip=4&keepalive=yes&c=IOS&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAOiX5GtZIJX34oWqrVgoaluYaYp6JV8FT1Hu7lLqtoSqAiBftMBkH8Z75r6JVWmeY9fvZOBY3JN2agPP0qtqPbbTLw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRgIhALoZCec1ABBoyAwSFjmoYxSwBD1PyD86tpO43lIeuFpEAiEA5KDZ2lt6nPY8otHM_jAGjGY0aS5yhWX9k5p3IShXNpQ%3D"
[download] Destination: Hrali sme 2 vs 2 AIRSOFT Turnaj [nPtfVJlK0Ko].f308.webm
[download] 100% of  915.09MiB in 00:03:06 at 4.91MiB/s
[debug] Invoking http downloader on "https://rr1---sn-nav853-cunz.googlevideo.com/videoplayback?expire=1716216221&ei=PQ1LZtCWLIK06dsPg9i0iA0&ip=91.228.164.152&id=o-AOMr1yK4ar83jqTZhpWbhtLMFcv06VdhPI9LEvasyDzV&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=EB&mm=31%2C29&mn=sn-nav853-cunz%2Csn-2gb7snez&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=24&initcwndbps=10801250&bui=AWRWj2Quz9CT8oZMITJmOucJHBcmjKKblPMSYS_-KPU0IZ1yNNILKyl1b356f8-Jcwihmx7SmKssorM9&spc=UWF9f269GvvCXMdn_MKiEhK2zhkb0jFsYMy0ZmzCWh6XKQZyT7ABPMPajx1G&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=RLC0Wg0Rwreb6EhiPZesEygQ&rqh=1&gir=yes&clen=10147633&dur=624.161&lmt=1714350981427869&mt=1716194216&fvip=4&keepalive=yes&c=WEB&sefc=1&txp=5532434&n=jOm4hT8x70ZRSA&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAMXyDLuqHe_kAGATm1vlHrtNGfzhuzHxdvTbF8wadBHlAiAJFRGl0paDkpo42prk5tcyOB_9P3mWyBMsLL1trQa97A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHWaYeowRQIgPUKUCthwLlP-5Y9PR0BUJBR16EoKIAB6UPqfEPGc-_UCIQDXstoLYA_6s88iKqDlKoShyVkWkG_0uqhpWaCv5VxsbA%3D%3D"
[download] Destination: Hrali sme 2 vs 2 AIRSOFT Turnaj [nPtfVJlK0Ko].f251.webm
[download] 100% of    9.68MiB in 00:00:01 at 5.21MiB/s
[Merger] Merging formats into "Hrali sme 2 vs 2 AIRSOFT Turnaj [nPtfVJlK0Ko].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Hrali sme 2 vs 2 AIRSOFT Turnaj [nPtfVJlK0Ko].f308.webm' -i 'file:Hrali sme 2 vs 2 AIRSOFT Turnaj [nPtfVJlK0Ko].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Hrali sme 2 vs 2 AIRSOFT Turnaj [nPtfVJlK0Ko].temp.webm'
Deleting original file Hrali sme 2 vs 2 AIRSOFT Turnaj [nPtfVJlK0Ko].f251.webm (pass -k to keep)
Deleting original file Hrali sme 2 vs 2 AIRSOFT Turnaj [nPtfVJlK0Ko].f308.webm (pass -k to keep)
```

**Comment by Kilobyte3189** [comment] 2024-05-21 20:31
This has been happening to me with most videos, if not all, for months. Updating did not bring any improvement. I think the people who create archives should check if comments have been downloaded at all, because I did and saw that many videos have either no comments or only a fraction of the comments.

**Comment by bashonly** [comment] 2024-05-21 20:37
Duplicate of #9358

you need to update to ***nightly***

```
yt-dlp --update-to nightly
```

or

https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-nightly

**Closed by bashonly** 2024-05-21 20:37 UTC
Labels: bug, triage

**Comment by Kilobyte3189** [comment] 2024-05-21 20:42
Thank you very much! I tried this when the problem first occurred, with no improvement (months ago). But now it works.
