### ISSUE TITLE
There is no audio when downloading shorts by creator from sex.com and only downloads one page

### ISSUE THREAD

**Issue by bwalker22** [yt-dlp/yt-dlp#11076] opened 2024-09-24 19:05 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States of America

### Provide a description that is worded well enough to be understood

Im using "https://www.sex.com/en/creators/anettelawrence/shorts" as an example.
I've  downloaded the creator's shorts but the downloaded video doesnt have audio.

I also have to download the shorts page by page and it makes the downloaded video's name include the page number causing the file name to be something like "Anette's profile - shorts ｜ Sex.com (19) [shorts？page=4-19].mp4".
could i get some help with this?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Microsoft Windows [Version 10.0.19045.4894]
(c) Microsoft Corporation. All rights reserved.

C:\Users\boo>yt-dlp -vU "https://www.sex.com/en/creators/anettelawrence/shorts"
[debug] Command-line config: ['-vU', 'https://www.sex.com/en/creators/anettelawrence/shorts']
[debug] User config "C:\Users\boo\AppData\Roaming\yt-dlp\config.txt": ['-P', 'F:\\yt-dlp']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds [4a9bc8c36] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-11-05-git-44a0148fad-full_build-www.gyan.dev (setts), ffprobe 2023-11-05-git-44a0148fad-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1835 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://www.sex.com/en/creators/anettelawrence/shorts
[generic] shorts: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] shorts: Extracting information
[debug] Looking for embeds
[debug] Identified 24 html5 embeds
[download] Downloading playlist: Anette's profile - shorts | Sex.com
[generic] Playlist Anette's profile - shorts | Sex.com: Downloading 24 items of 24
[download] Downloading item 1 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-1: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/0c20cd0f-dff7-405f-bce7-48d536eda10b/165037ba-bb8e-4a97-86f1-87dba1d00e89_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (1) [shorts-1].mp4 has already been downloaded
[download] 100% of  171.30KiB
[download] Downloading item 2 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-2: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/856d8d5b-be21-4457-894e-08d0c4deb822/de5112fd-80b6-448c-a69d-0848c909cc4b_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (2) [shorts-2].mp4 has already been downloaded
[download] 100% of  164.14KiB
[download] Downloading item 3 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-3: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/95a13987-f191-44be-9651-33ec3319a0b9/de6acc83-b37c-42bf-a456-a6f101050c35_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (3) [shorts-3].mp4 has already been downloaded
[download] 100% of  205.44KiB
[download] Downloading item 4 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-4: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/40f8273a-5ee2-4804-bb85-31b45b1a5d3f/354ca721-445c-441f-bc1b-9906d47ee5e6_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (4) [shorts-4].mp4 has already been downloaded
[download] 100% of  192.52KiB
[download] Downloading item 5 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-5: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/f81b21f4-7440-435e-a6e5-de644bad78d9/b9d186e9-2b3e-4d9f-98dd-bff1841bb11a_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (5) [shorts-5].mp4 has already been downloaded
[download] 100% of  182.95KiB
[download] Downloading item 6 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-6: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/4297a793-6034-41a3-8781-b66127120f0e/827b5dea-60d6-4951-95a7-cb7332f714c3_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (6) [shorts-6].mp4 has already been downloaded
[download] 100% of  213.32KiB
[download] Downloading item 7 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-7: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/cb6401f4-25f8-417b-8b61-652d81d73ee4/fd51c9d9-7e61-410b-8065-6621ee487d3f_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (7) [shorts-7].mp4 has already been downloaded
[download] 100% of  164.17KiB
[download] Downloading item 8 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-8: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/eceb34b2-6f2a-48cb-bb8e-e1ce69513342/2766aede-651d-479d-aab6-38a6486bc9a0_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (8) [shorts-8].mp4 has already been downloaded
[download] 100% of  194.21KiB
[download] Downloading item 9 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-9: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/3707dac6-3611-4efc-817e-71922d0c6591/5b6e431d-e5fb-406d-af37-cf5a59e3fda1_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (9) [shorts-9].mp4 has already been downloaded
[download] 100% of  178.22KiB
[download] Downloading item 10 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-10: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/d569a358-0d8e-4546-9b62-2560c2d950a8/9b2bfd27-5fca-40d2-8fad-1cb084b912c9_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (10) [shorts-10].mp4 has already been downloaded
[download] 100% of  214.73KiB
[download] Downloading item 11 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-11: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/e4c1d049-fc1f-4ddc-867a-f3f19c3eeae8/0ff9c480-3b35-422b-b7c6-8630917aae84_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (11) [shorts-11].mp4 has already been downloaded
[download] 100% of  172.47KiB
[download] Downloading item 12 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-12: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/f1ecd731-0c53-4616-a582-1887d047d736/4a7592e4-d856-4770-9eea-f28385fe071c_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (12) [shorts-12].mp4 has already been downloaded
[download] 100% of  136.97KiB
[download] Downloading item 13 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-13: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/a29dc256-747e-42ec-9b16-90ee85496042/e7a9eea3-2803-48c7-b0d9-1c8fc285f40e_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (13) [shorts-13].mp4 has already been downloaded
[download] 100% of  186.13KiB
[download] Downloading item 14 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-14: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/075498fc-9d49-4231-8feb-0ec111dea4c1/bfc9decd-9a49-43b6-821f-eff9116450cf_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (14) [shorts-14].mp4 has already been downloaded
[download] 100% of  174.42KiB
[download] Downloading item 15 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-15: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/aa75697c-a290-4a31-8754-58a788eab6c0/ad39a32f-5683-407f-8b9a-bc3512c1089b_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (15) [shorts-15].mp4 has already been downloaded
[download] 100% of  168.76KiB
[download] Downloading item 16 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-16: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/fd4c0281-834c-4d37-ae6d-ef08d28207b8/1393049f-64a2-4c0e-bf4d-38bb77c0d576_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (16) [shorts-16].mp4 has already been downloaded
[download] 100% of  160.88KiB
[download] Downloading item 17 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-17: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/e71f065c-1b7d-4e5b-8a93-7d087f77cecb/419ce226-65ab-4ea7-8d7e-929660b4baac_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (17) [shorts-17].mp4 has already been downloaded
[download] 100% of  175.93KiB
[download] Downloading item 18 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-18: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/f54df26a-1bdb-4a46-9564-99c29a6152b0/2ecf131f-318e-4cdf-8f84-d16ce69a3ea2_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (18) [shorts-18].mp4 has already been downloaded
[download] 100% of  167.24KiB
[download] Downloading item 19 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-19: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/0826150d-0090-49cc-83f1-aa6af9b74641/7da84b0b-2237-4708-b161-a655dc2ef1df_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (19) [shorts-19].mp4 has already been downloaded
[download] 100% of  201.65KiB
[download] Downloading item 20 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-20: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/2f7ed62c-6487-454c-986e-bf50c8ba1675/c3d2dfe6-6c28-43ad-93c5-b15f4a85f46c_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (20) [shorts-20].mp4 has already been downloaded
[download] 100% of  166.29KiB
[download] Downloading item 21 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-21: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/6000cbd6-206c-4a04-8da4-f55b4d665ab7/b3cd8d5e-1005-4672-ba5a-98a542894483_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (21) [shorts-21].mp4 has already been downloaded
[download] 100% of  163.43KiB
[download] Downloading item 22 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-22: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/8138a8b5-d0b4-4e2a-b477-d3bcc965ac39/39e5db69-15e5-49ba-91f0-9c19b9532eb4_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (22) [shorts-22].mp4 has already been downloaded
[download] 100% of  143.17KiB
[download] Downloading item 23 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-23: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/8614b07a-b930-4fc2-ba9d-2643d7c13a47/6343fa2d-9f97-4b39-9a1d-3da6a8df0366_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (23) [shorts-23].mp4 has already been downloaded
[download] 100% of  130.94KiB
[download] Downloading item 24 of 24
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] shorts-24: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://m2.cdn.sex.com/videos/e672c09d-577f-440f-8012-df6aa71bb6a2/8a124043-afbd-4ff7-8d87-b704f9c85f95_preview.mp4"
[download] F:\yt-dlp\Anette's profile - shorts ｜ Sex.com (24) [shorts-24].mp4 has already been downloaded
[download] 100% of  148.31KiB
[download] Finished downloading playlist: Anette's profile - shorts | Sex.com
```

**Comment by grqz** [comment] 2024-10-05 08:40
duplicate of #2457

**Closed** 2024-10-05 14:50 UTC
Labels: site-request, NSFW, triage
