### ISSUE TITLE
using python, but I got 403 error while downloading YouTube video

### ISSUE THREAD

**Issue by Seo0903** [yt-dlp/yt-dlp#7984] opened 2023-08-29 09:37 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Republic of Korea

### Provide a description that is worded well enough to be understood

Hello
I downloaded a youtube video using yt-dlp on python around May, but I ran it to use it again today, but I got an error 403. I updated to 2023.07.06 version, but I couldn't resolve the error 403.
When I tried to fit the yt-dlp [OPTIONS] URL [URL...] form, I found that it worked very well.
If you import subprocess and replace the above form with python just in case, you will also get error 403.
I'm saying this because I think you might misunderstand, but I originally used import yt_dlp.
Is there a way to solve this problem

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale cp949, fs utf-8, pref cp949, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip) API 
[debug] params: {'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', 'outtmpl': '1. La.%(ext)s', 'verbose': True, 'compat_opts': set()} 
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023) 
[debug] exe versions: ffmpeg 2023-01-25-git-2c3107c3e9-essentials_build-www.gyan.dev (setts), ffprobe 2023-01-25-git-2c3107c3e9-essentials_build-www.gyan.dev 
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2 
[debug] Proxy map: {} 
[debug] Loaded 1786 extractors 
[youtube] Extracting URL: https://www.youtube.com/watch?v=U8rvZpWr4Wg 
[youtube] U8rvZpWr4Wg: Downloading webpage 
[youtube] U8rvZpWr4Wg: Downloading android player API JSON 
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto 
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] U8rvZpWr4Wg: Downloading 1 format(s): 137+140 
[debug] Invoking dashsegments downloader on "https://rr1---sn-n3cgv5qc5oq-bh2sk.googlevideo.com/videoplayback?expire=1693322062&ei=7rbtZMa7N92A2roPv6uagAo&ip=58.236.82.132&id=o-AOYOpxbffp29cKBKA4pMuMJyS7nFQULCHzsmrDoLQrFV&itag=137&source=youtube&requiressl=yes&mh=fw&mm=31%2C26&mn=sn-n3cgv5qc5oq-bh2sk%2Csn-oguesndl&ms=au%2Conr&mv=m&mvi=1&pl=23&initcwndbps=1832500&spc=UWF9fxvWbyB0kJY0tVkl1TGUIsLRN0JWGSyM7bWJyA&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=3469932&dur=215.033&lmt=1690125497592747&mt=1693300158&fvip=4&keepalive=yes&fexp=24007246%2C24362685%2C24363392&beids=24350017&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgRI9rG5Xyz_1DRJj5rOlhyO5iV_yYmO828fiRA5IInCMCIESB5Wel9Yc4iOg16ETT3PnA-_X0RZ-Khmtb29mfr9Py&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAJIWDOBZkbxjoGh6eFrBIZxke-906EzhnZgtZNA2KdF8AiBceeeueo3NAswnB0Obo3nEGj3Q2DJFWkNeL70RSODd8g%3D%3D"
[dashsegments] Total fragments: 1 
[download] Destination: 1. La.f137.mp4
[debug] File locking is not supported. Proceeding without locking
[download] Got error: HTTP Error 403: Forbidden 
  File "e:\mapList\5. lyrics\1탄\2\LiteExslCutter.py", line 22, in <module> 
    download_youtube_video(link, filename)
  File "e:\mapList\5. lyrics\1탄\2\LiteExslCutter.py", line 12, in download_youtube_video
    ydl.download([url])
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 3369, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 3344, in wrapper
    res = func(*args, **kwargs)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 1507, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 2779, in process_video_result
    self.process_info(new_info)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 3229, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 2970, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\dash.py", line 60, in real_download
    return self.download_and_append_fragments_multiple(*args, is_fatal=lambda idx: idx == 0)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\fragment.py", line 382, in download_and_append_fragments_multiple
    return self.download_and_append_fragments(*args[0], **kwargs)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\fragment.py", line 521, in download_and_append_fragments
    download_fragment(fragment, ctx)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\fragment.py", line 466, in download_fragment
    for retry in RetryManager(self.params.get('fragment_retries'), error_callback):
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\utils.py", line 6141, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\fragment.py", line 463, in error_callback
    self.report_retry(err, count, retries, frag_index, fatal)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\common.py", line 389, in report_retry
    RetryManager.report_retry(
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\utils.py", line 6148, in report_retry
    return error(f'{e}. Giving up after {count - 1} retries') if count > 1 else error(str(e))
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\common.py", line 392, in <lambda>
    error=IDENTITY if not fatal else lambda e: self.report_error(f'\r[download] Got error: {e}'),
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 1015, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 944, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

Traceback (most recent call last):
  File "e:\mapList\5. lyrics\1탄\2\LiteExslCutter.py", line 22, in <module>
    download_youtube_video(link, filename)
  File "e:\mapList\5. lyrics\1탄\2\LiteExslCutter.py", line 12, in download_youtube_video
    ydl.download([url])
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 3369, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 3344, in wrapper
    res = func(*args, **kwargs)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 1507, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 2779, in process_video_result
    self.process_info(new_info)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 3229, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 2970, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\dash.py", line 60, in real_download
    return self.download_and_append_fragments_multiple(*args, is_fatal=lambda idx: idx == 0)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\fragment.py", line 382, in download_and_append_fragments_multiple
    return self.download_and_append_fragments(*args[0], **kwargs)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\fragment.py", line 521, in download_and_append_fragments
    download_fragment(fragment, ctx)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\fragment.py", line 466, in download_fragment
    for retry in RetryManager(self.params.get('fragment_retries'), error_callback):
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\utils.py", line 6141, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\fragment.py", line 463, in error_callback
    self.report_retry(err, count, retries, frag_index, fatal)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\common.py", line 389, in report_retry
    RetryManager.report_retry(
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\utils.py", line 6148, in report_retry
    return error(f'{e}. Giving up after {count - 1} retries') if count > 1 else error(str(e))
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\downloader\common.py", line 392, in <lambda>
    error=IDENTITY if not fatal else lambda e: self.report_error(f'\r[download] Got error: {e}'),
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 1015, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\amas4\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\YoutubeDL.py", line 955, in trouble
    raise DownloadError(message, exc_info)
[download] Got error: HTTP Error 403: Forbidden
```

**Comment by Seo0903** [comment] 2023-08-29 11:22
When I read that comment
1. Did you update it? Yes
2. YouTube ip blocked? NO
- Both login and logout status are normally played
When you attempt to download to the yt-dlp [OPTIONS] URL [URL...], it will download normally

**Comment by bashonly** [comment] 2023-08-29 21:35
in your log, you are using version 2023.03.04:

> [debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip) API 

so your issue looks like #7811 and you just need to update ( `python3 -m pip install -U yt-dlp` )


Otherwise if you actually update and still get the error, this is a duplicate of #7860 as dirkf said

**Closed by bashonly** 2023-08-29 21:35 UTC
Labels: site-bug, triage

**Comment by Seo0903** [comment] 2023-08-30 12:57
I'm so sorry.
I definitely did 2023.07.06 when I did yt-dlp --version, but it didn't work, so I asked you a question, but I just saw the answer and updated it again with administrator privileges, so it works well.
I'm sorry and thank you.
