### ISSUE TITLE
Only "Downloading API JSON" but not downloading youtube shorts playlist

### ISSUE THREAD

**Issue by AzizxonZufarov** [yt-dlp/yt-dlp#11023] opened 2024-09-17 03:17 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Uzbekistan

### Provide a description that is worded well enough to be understood

Good day!
I tried to download youtube shorts playlist using `yt-dlp -vU --playlist-items 1:2 URL` 
yt-dlp prints "Downloading API JSON" but not downloading youtube shorts playlist. Nothing downloaded.
Please, help.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\Downloads>yt-dlp -vU --playlist-items 1:2 "https://www.youtube.com/@thang010146/shorts"
[debug] Command-line config: ['-vU', '--playlist-items', '1:2', 'https://www.youtube.com/@thang010146/shorts']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.18363-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/@thang010146/shorts
[youtube:tab] @thang010146/shorts: Downloading webpage
[debug] [youtube:tab] Selected tab: 'shorts' (shorts), Requested tab: 'shorts'
[download] Downloading playlist: thang010146 - Shorts
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 1: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 2: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 3: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 4: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 5: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 6: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 7: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 8: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 9: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 10: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 11: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 12: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 13: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 14: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 15: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 16: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 17: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 18: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 19: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 20: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 21: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 22: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 23: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 24: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 25: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 26: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 27: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 28: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 29: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 30: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 31: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 32: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 33: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 34: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 35: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 36: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 37: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 38: Downloading API JSON
[youtube:tab] UCli_RJkGWfZvw4IlDLHNCQg page 39: Downloading API JSON
[youtube:tab] Playlist thang010146 - Shorts: Downloading 0 items
[download] Finished downloading playlist: thang010146 - Shorts
```

**Comment by seproDev** [comment] 2024-09-17 07:10
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/10936
Update to nightly:
```
yt-dlp --update-to nightly
```

**Closed** 2024-09-17 07:10 UTC
Labels: duplicate

**Comment by AzizxonZufarov** [comment] 2024-09-17 12:43
> yt-dlp --update-to nightly

Thank You very much!
