### ISSUE TITLE
Vimeo format extraction broken

### ISSUE THREAD

**Issue by t0ben** [yt-dlp/yt-dlp#11037] opened 2024-09-19 06:55 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

EMEA

### Provide a description that is worded well enough to be understood

yt-dlp shows just shows 2 audio tracks with unkown codecs.
 -bestaudio downloads a .mp4 with a pure aac stream. This should be a m4a with opus.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp  -vUF --referer https://shop.auditorium-netzwerk.de  https://player.vimeo.com/video/908213770
[debug] Command-line config: ['-vUF', '--referer', 'https://shop.auditorium-netzwerk.de', 'https://player.vimeo.com/video/908213770']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds (linux_exe)
[debug] Python 3.11.10 (CPython x86_64 64bit) - Linux-6.9.12-3-MANJARO-x86_64-with (OpenSSL 3.1.7 3 Sep 2024)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.2.3, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1835 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds)
[vimeo] Extracting URL: https://player.vimeo.com/video/908213770
[vimeo] 908213770: Downloading webpage
[vimeo] 908213770: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 908213770: Downloading fastly_skyfire m3u8 information
[vimeo] 908213770: Downloading akfire_interconnect_quic MPD information
WARNING: [vimeo] 908213770: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[vimeo] 908213770: Downloading fastly_skyfire MPD information
WARNING: [vimeo] 908213770: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[info] Available formats for 908213770:
ID                                              EXT RESOLUTION FPS │   FILESIZE  TBR PROTO │ VCODEC       VBR ACODEC     MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-akfire_interconnect_quic-audio-high-Deutsch mp4 audio only     │                 m3u8  │ audio only       unknown    [de] Deutsch
hls-fastly_skyfire-audio-high-Deutsch           mp4 audio only     │                 m3u8  │ audio only       unknown    [de] Deutsch
hls-akfire_interconnect_quic-252                mp4 426x240     25 │ ~138.82MiB 252k m3u8  │ avc1.640015 252k video only
hls-fastly_skyfire-252                          mp4 426x240     25 │ ~138.82MiB 252k m3u8  │ avc1.640015 252k video only
hls-akfire_interconnect_quic-306                mp4 640x360     25 │ ~168.57MiB 306k m3u8  │ avc1.64001E 306k video only
hls-fastly_skyfire-306                          mp4 640x360     25 │ ~168.57MiB 306k m3u8  │ avc1.64001E 306k video only
hls-akfire_interconnect_quic-418                mp4 960x540     25 │ ~230.26MiB 418k m3u8  │ avc1.64001F 418k video only
hls-fastly_skyfire-418                          mp4 960x540     25 │ ~230.26MiB 418k m3u8  │ avc1.64001F 418k video only
hls-akfire_interconnect_quic-558                mp4 1280x720    25 │ ~307.38MiB 558k m3u8  │ avc1.640020 558k video only
hls-fastly_skyfire-558                          mp4 1280x720    25 │ ~307.38MiB 558k m3u8  │ avc1.640020 558k video only
hls-akfire_interconnect_quic-923                mp4 1920x1080   25 │ ~508.45MiB 923k m3u8  │ avc1.64002A 923k video only
hls-fastly_skyfire-923                          mp4 1920x1080   25 │ ~508.45MiB 923k m3u8  │ avc1.64002A 923k video only

The actual playlists :
clip_id	"1efee937-bce0-4246-a82b-6d009d06b69b"
base_url	"../../../range/avf/"
video	[…]
audio	
0	
id	"6089a0f6-5a6b-4abf-942d-e17d67fb2640"
avg_id	"1efee937"
base_url	""
format	"dash"
mime_type	"audio/mp4"
codecs	"mp4a.40.2"
bitrate	196000
avg_bitrate	194000
duration	4621.845333333334
channels	2
sample_rate	48000
max_segment_duration	6
init_segment	"AAAAHGZ0eXBkYXNoAAAAAGRh…AEAAAABAAAAAQAAAAAAAQAA"
index_segment	"6089a0f6-5a6b-4abf-942d-…r=dXM%3D&range=678-9961"
segments	[…]
audio_primary	true
1	
id	"918535a1-6d9d-4ef8-94a5-56c4ffb2925a"
avg_id	"1efee937"
base_url	""
format	"dash"
mime_type	"audio/mp4"
codecs	"opus"
bitrate	102000
avg_bitrate	101000
duration	4621.84
channels	2
sample_rate	48000
max_segment_duration	8
init_segment	"AAAAHGZ0eXBkYXNoAAAAAGRh…AEAAAABAAAAAQAAAAAAAQAA"
index_segment	"918535a1-6d9d-4ef8-94a5-…r=dXM%3D&range=690-9961"
segments	[…]
audio_primary	true
2	
id	"44f2c347-f87f-448e-9f4a-e083dcda27ef"
avg_id	"1efee937"
base_url	""
format	"dash"
mime_type	"audio/mp4"
codecs	"opus"
bitrate	69000
avg_bitrate	69000
duration	4621.84
channels	2
sample_rate	48000
max_segment_duration	8
init_segment	"AAAAHGZ0eXBkYXNoAAAAAGRh…AEAAAABAAAAAQAAAAAAAQAA"
index_segment	"44f2c347-f87f-448e-9f4a-…r=dXM%3D&range=690-9961"
segments	[…]
audio_primary	true
```

**Comment by bashonly** [comment] 2024-09-19 06:58
Duplicate of #10370

**Closed by bashonly** 2024-09-19 06:58 UTC
Labels: duplicate, site-bug, site:vimeo
