### ISSUE TITLE
Twitter - randombly breaks with bad guest token

### ISSUE THREAD

**Issue by altryne** [yt-dlp/yt-dlp#5768] opened 2022-12-11 03:20 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

For the past 3 days, twitter downloads have started randomly failing with `Bad guest token.` 

After restarting my process, this seems to go away for a little while and then comes back

A fresh yt-dlp run from command line doesn't seem to fail

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.15.0-46-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.6.1, brotli-1.0.9, certifi-2019.11.28, mutagen-1.46.0, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
```

**Comment by bashonly** [comment] 2022-12-11 03:33
Fixed in 352e7d987323e9df9205ee117a604ee4123231c2. Wait for the next release or use the master branch.

Closing as duplicate of #5548

**Closed by bashonly** 2022-12-11 03:33 UTC
Labels: site-bug, triage

**Comment by altryne** [comment] 2022-12-11 03:43
> Fixed in [352e7d9](https://github.com/yt-dlp/yt-dlp/commit/352e7d987323e9df9205ee117a604ee4123231c2). Wait for the next release or use the master branch.
> 
> Closing as duplicate of #5548

Thanks bashonly, is this a regression? would downgrading to an earlier vesion fix this do you think?

**Comment by pukkandan** [comment] 2022-12-11 03:47
possibly, but then you'll get #5157/#5147

**Comment by pukkandan** [comment] 2022-12-11 03:48
See https://github.com/yt-dlp/yt-dlp/wiki/Forks#automated-daily-releases if you don't wish to wait for official release
