### ISSUE TITLE
ERROR: [crunchyroll:beta] G14U4DVWV: No video formats found!

### ISSUE THREAD

**Issue by BraveSail** [yt-dlp/yt-dlp#4886] opened 2022-09-10 08:37 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

This show is hard-subbed and other soft-subbed shows are ok, I don't know if it's related.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', '-R', 'infinite', '--force-overwrites', '--fragment-retries', 'infinite', '--no-mtime', '--proxy', 'socks5://127.0.0.1:7893', 'https://www.crunchyroll.com/the-journey/the-journey-the-journey-864714', '-u', 'PRIVATE', '-p', 'PRIVATE', '-N', '16', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0', '--cookies', '/root/cookie-cr.txt', '--embed-subs', '--sub-langs', 'all', '--remux-video', 'mkv', '-o', '/root/1.mkv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d656] (linux_exe)
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.0-13-arm64-aarch64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-108083-g06b98e396a-20220909 (setts), ffprobe N-104327-g1902a60dda
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {'http': 'socks5://127.0.0.1:7893', 'https': 'socks5://127.0.0.1:7893'}
[debug] Loaded 1670 extractors
[debug] [crunchyroll] Extracting URL: https://www.crunchyroll.com/the-journey/the-journey-the-journey-864714
[crunchyroll] 864714: Downloading webpage
[crunchyroll] 864714: Redirected to beta site - https://beta.crunchyroll.com/watch/G14U4DVWV/the-journey
[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/watch/G14U4DVWV/the-journey
[crunchyroll:beta] Retrieving main page
[crunchyroll:beta] Authenticating with grant_type=etp_rt_cookie
[crunchyroll:beta] Retrieving signed policy
[crunchyroll:beta] the-journey: Retrieving episode metadata
[crunchyroll:beta] the-journey: Retrieving stream info
ERROR: [crunchyroll:beta] G14U4DVWV: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1474, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1571, in __extract_info
  File "yt_dlp/YoutubeDL.py", line 1629, in process_ie_result
  File "yt_dlp/YoutubeDL.py", line 2561, in process_video_result
  File "yt_dlp/YoutubeDL.py", line 1026, in raise_no_formats
yt_dlp.utils.ExtractorError: [crunchyroll:beta] G14U4DVWV: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by october262** [comment] 2022-09-11 03:50
can you try again but leave out the username & password option and just use the cookies.txt file instead

**Comment by BraveSail** [comment] 2022-09-11 14:24
> can you try again but leave out the username & password option and just use the cookies.txt file instead

same error

**Comment by Haldrie** [comment] 2022-09-25 09:14
I get the same error with Dragon Half, Chargeman Ken, the Sub version of Ghost Stories, and the Sub version of Hells so far. The theory about hard coded subs might have some merit since all of these are hard coded though Hells is the only one I can't verify about that.

[debug] Command-line config: ['--cookies', 'cookies\\crunchyroll.txt', '-o', 'output\\tmp\\%%(title)s', '-vU', 'https://www.crunchyroll.com/dragon-half/episode-1-episode-1-688019']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-08-25-git-9bf9d42d01-essentials_build-www.gyan.dev (setts), ffprobe 2022-08-25-git-9bf9d42d01-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [crunchyroll] Extracting URL: https://www.crunchyroll.com/dragon-half/episode-1-episode-1-688019
[crunchyroll] 688019: Downloading webpage
[crunchyroll] 688019: Redirected to beta site - https://beta.crunchyroll.com/watch/G6ZXD15DR/episode-1
[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/watch/G6ZXD15DR/episode-1
[crunchyroll:beta] Retrieving main page
[crunchyroll:beta] Authenticating with grant_type=etp_rt_cookie
[crunchyroll:beta] Retrieving signed policy
[crunchyroll:beta] episode-1: Retrieving episode metadata
[crunchyroll:beta] episode-1: Retrieving stream info
ERROR: [crunchyroll:beta] G6ZXD15DR: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1556, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1614, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2546, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1025, in raise_no_formats
yt_dlp.utils.ExtractorError: [crunchyroll:beta] G6ZXD15DR: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by pukkandan** [comment] 2022-09-25 15:01
@tejing1

**Comment by pukkandan** [comment] 2022-09-25 15:23
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3397

**Closed by pukkandan** 2022-09-25 15:23 UTC
Labels: account-needed, site-bug, can-share-account

**Comment by tejing1** [comment] 2022-09-25 18:55
To directly address the problem for the OP, you can run `yt-dlp` with `--extractor-args crunchyrollbeta:hardsub=en-US` to explicitly ask it to get the hardsubbed version.

I made the decision to ignore hardsubbed formats normally to avoid wasting an annoying amount of back-and-forth with the server listing formats people were very seldom interested in. It seems to be coming back to bite me.
