### ISSUE TITLE
Download file with age restriction

### ISSUE THREAD

**Issue by pavel167** [yt-dlp/yt-dlp#8404] opened 2023-10-21 17:47 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,
This video in this link
[The House that Jack Built](https://www.arte.tv/fr/videos/082716-000-A/the-house-that-jack-built/)
is labeled 18+ and available in the evening time slot, i.e. 11 p.m.... 6 a.m.
But I can visualize it on the site using my login (i.e. e-mail and password)
Is it possible to overcome time restriction to be able to download this video with yt-dlp at any time ... perhaps using credentials (i.e e-mail/password).
Thanks.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(env_video_dnld) pavel@MISSURI:~/env_video_dnld$ yt-dlp -vU https://www.arte.tv/fr/videos/082716-000-A/the-house-that-jack-built/
[debug] Command-line config: ['-vU', 'https://www.arte.tv/fr/videos/082716-000-A/the-house-that-jack-built/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.2.0-34-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.10.13, Current version: 2023.01.06
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2023.10.13/_update_spec
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[ArteTV] Extracting URL: https://www.arte.tv/fr/videos/082716-000-A/the-house-that-jack-built/
[ArteTV] 082716-000-A: Downloading JSON metadata
ERROR: [ArteTV] 082716-000-A: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/pavel/env_video_dnld/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/home/pavel/env_video_dnld/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1599, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/pavel/env_video_dnld/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1658, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/pavel/env_video_dnld/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2606, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/pavel/env_video_dnld/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1043, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [ArteTV] 082716-000-A: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

(env_video_dnld) pavel@MISSURI:~/env_video_dnld$
```

**Comment by bashonly** [comment] 2023-10-21 22:53
> Latest version: 2023.10.13, Current version: 2023.01.06
> ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update

**Comment by Gloster10** [comment] 2023-10-22 00:51
@pavel167, try the following :

If you use firefox, install an addon to export cookies (as txt-file).
`yt-dlp -F -o "%(title)s.%(ext)s" --cookies cookies.txt "https://..."`

**Comment by absidue** [comment] 2023-10-22 07:47
@Gloster10 The problem isn't cookies, it's that they are using a version for yt-dlp from January and not the latest version. Both the yt-dlp output and bashonly have told them to update to the latest version. Also they lied about using the latest version in the checkboxes.

**Comment by StefanLobbenmeier** [comment] 2023-10-26 14:39
just for the link, this was fixed in the latest release:

https://github.com/yt-dlp/yt-dlp/pull/8301

**Closed** 2023-10-26 14:45 UTC
Labels: question, incomplete

**Comment by pavel167** [comment] 2023-10-26 17:39
Should I update yt-dlp or just yt_dlp/extractor/arte.py will be sufficient ?

**Comment by bashonly** [comment] 2023-10-26 17:40
update yt-dlp

**Comment by pavel167** [comment] 2023-10-26 17:45
I don't remember how I installed yt-dlp ... using pip or using binary. Is it possible to check ?

**Comment by bashonly** [comment] 2023-10-26 17:47
according to your log, you installed with pip

`python3 -m pip install -U yt-dlp`

**Comment by pavel167** [comment] 2023-10-26 17:55
Ok, thanks
