### ISSUE TITLE
IMD

### ISSUE THREAD

**Issue by AlirezaJanbabaei** [yt-dlp/yt-dlp#6143] opened 2023-02-02 19:55 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

-Each part of a Single Video:
https://videos.imedicaldoctor.net/cmeinfo/Clinical%20_%20USMLE%20Step%202/Parts/01%20-%20Cardiology-117689.mp4.1
https://videos.imedicaldoctor.net/cmeinfo/Clinical%20_%20USMLE%20Step%202/Parts/01%20-%20Cardiology-117689.mp4.2
https://videos.imedicaldoctor.net/cmeinfo/Clinical%20_%20USMLE%20Step%202/Parts/01%20-%20Cardiology-117689.mp4.3
https://videos.imedicaldoctor.net/cmeinfo/Clinical%20_%20USMLE%20Step%202/Parts/01%20-%20Cardiology-117689.mp4.4
https://videos.imedicaldoctor.net/cmeinfo/Clinical%20_%20USMLE%20Step%202/Parts/01%20-%20Cardiology-117689.mp4.5
https://videos.imedicaldoctor.net/cmeinfo/Clinical%20_%20USMLE%20Step%202/Parts/01%20-%20Cardiology-117689.mp4.6
https://videos.imedicaldoctor.net/cmeinfo/Clinical%20_%20USMLE%20Step%202/Parts/01%20-%20Cardiology-117689.mp4.7
https://videos.imedicaldoctor.net/cmeinfo/Clinical%20_%20USMLE%20Step%202/Parts/01%20-%20Cardiology-117689.mp4.8
https://videos.imedicaldoctor.net/cmeinfo/Clinical%20_%20USMLE%20Step%202/Parts/01%20-%20Cardiology-117689.mp4.9
https://videos.imedicaldoctor.net/cmeinfo/Clinical%20_%20USMLE%20Step%202/Parts/01%20-%20Cardiology-117689.mp4.10

### Provide a description that is worded well enough to be understood

This Website splits each part of a video to 10 parts.
Downloading each part is easy but i can't play them. I have merged the with ffmpeg but it is still unplayable but when they are streamed through the IMD app it is shown that the content type is octet stream and each file has an E-Tag. [don't know if this is helpful!]

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://videos.imedicaldoctor.net/cmeinfo/Clinical%20_%20USMLE%20Step%202/Parts/01%20-%20Cardiology-117689.mp4.1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109674-gc0bc804e55-20230127 (setts), ffprobe N-109674-gc0bc804e55-20230127
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: https://videos.imedicaldoctor.net/cmeinfo/Clinical%20_%20USMLE%20Step%202/Parts/01%20-%20Cardiology-117689.mp4.1
[generic] 01 - Cardiology-117689.mp4: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
WARNING: [generic] URL could be a direct video link, returning it as such.
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 01 - Cardiology-117689.mp4: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://videos.imedicaldoctor.net/cmeinfo/Clinical%20_%20USMLE%20Step%202/Parts/01%20-%20Cardiology-117689.mp4.1"
[debug] File locking is not supported. Proceeding without locking
```

**Comment by pukkandan** [comment] 2023-02-02 19:59
Sorry, I don't understand what you are asking for

**Comment by AlirezaJanbabaei** [comment] 2023-02-02 20:31
> Sorry, I don't understand what you are asking for

How can I merge these files in a way that they would play.

**Comment by bashonly** [comment] 2023-02-02 21:17
https://en.imedicaldoctor.net/buy.php#pricing

This is subscription-only content for a paid app. Nobody will know how to merge these files into a playable state without access to the site/app. Are these videos viewable via the website? Share webpage URLs.

> I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

Are you actually willing to do this ^?

This is also a duplicate of #5843, do not open multiple issues for the same request

**Comment by pukkandan** [comment] 2023-02-03 00:41
It's not in scope for yt-dlp to merge random files for you. If you meant this to be a site request, #5843 can be re-opened

**Closed by pukkandan** 2023-02-03 00:41 UTC
Labels: site-request, incomplete, account-needed
