### ISSUE TITLE
 unsupported operand type(s) for -: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by mikhnevich** [yt-dlp/yt-dlp#3012] opened 2022-03-10 04:19 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

Certain youtube videos cannot be downloaded when "--sleep-interval" argument.
if I remove the arg - everything works.

### Verbose log

```shell
[debug] Command-line config: ['--ignore-config', '--verbose', '--sleep-interval', '3', 'https://www.youtube.com/watch?v=zQk7U6InXZs']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: none
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=zQk7U6InXZs
[youtube] zQk7U6InXZs: Downloading webpage
[youtube] zQk7U6InXZs: Downloading android player API JSON
[youtube] zQk7U6InXZs: Downloading MPD manifest
[youtube] zQk7U6InXZs: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] zQk7U6InXZs: Downloading 1 format(s): 18
[debug] Invoking downloader on "https://rr2---sn-ab5szn7y.googlevideo.com/videoplayback?expire=1646907290&ei=OnspYv7pENew8wSW54aoDA&ip=162.218.210.26&id=o-AHLcuusDQFrs-vFFR07YP0biwKdS3VLCzGvA5-nM18d_&itag=18&source=youtube&requiressl=yes&mh=V3&mm=31%2C29&mn=sn-ab5szn7y%2Csn-ab5l6n6s&ms=au%2Crdu&mv=m&mvi=2&pl=23&initcwndbps=2183750&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=3857.809&lmt=1635825302011444&mt=1646885329&fvip=2&fexp=24001373%2C24007246&c=ANDROID&txp=2210224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPi5d7MqOqIlIbyFz_N5desBnaVueaMBbYpvxpPsnrqTAiEAu0oiPmYWwOLqh9HXe5xNSHLOOfqmYnT438HL8Pd4300%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANzQa990i0htAnqFVH2nSd-PhCpTVBV-sU9lcyxsF_VkAiEA5nMAKcafS-_DhTl5FaxqdOwkGy1ymBRLQ5WWSCWkhxQ%3D"
ERROR: unsupported operand type(s) for -: 'NoneType' and 'float'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1473, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1529, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2638, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3128, in process_info
  File "yt_dlp\YoutubeDL.py", line 2835, in dl
  File "yt_dlp\downloader\common.py", line 438, in download
  File "random.py", line 417, in uniform
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

**Comment by Lesmiscore** [comment] 2022-03-10 04:21
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2996

**Comment by pukkandan** [comment] 2022-03-10 06:07
Not it's duplicate actually

**Closed** 2022-03-10 06:08 UTC
Labels: site-bug, triage
