### ISSUE TITLE
soundcloud username/password support

### ISSUE THREAD

**Issue by philcerf** [yt-dlp/yt-dlp#3348] opened 2022-04-08 02:48 UTC
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://soundcloud.com/wandw/the-chainsmokers-ft-daya-dont-let-me-down-ww-remix-1

### Description

Hey.

I've stumbled over this PR that was apparently never merged into youtube-dl and also seems to be missing from yt-dlp:

https://github.com/ytdl-org/youtube-dl/pull/26265

As far as I understand it, it would add username/password login to soundcloud.

Maybe it makes sense to have that merged into yt-dlp?

Thanks for consideration

### Verbose log

```shell
N/A
```

**Comment by pukkandan** [comment] 2022-04-08 06:46
That PR no longer works

**Comment by HobbyistDev** [comment] 2022-06-18 10:51
Doesn't this duplicate of #997 ?

**Closed** 2022-06-18 14:17 UTC
Labels: duplicate, site-enhancement
