### ISSUE TITLE
Display “current url number”/“total number of urls” on console output

### ISSUE THREAD

**Issue by 49studebaker** [yt-dlp/yt-dlp#8371] opened 2023-10-18 01:54 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Could you display “current url number”/“total number of urls” on console output? Or at least display the current url number.

If downloading stopped at url number 10. I would like to write a program that would remove or comment out urls 1-9.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by gamer191** [comment] 2023-10-18 02:12
> If downloading stopped at url number 10. I would like to write a program that would remove or comment out urls 1-9.

Off-topic, but you may be interested in `--download-archive`

**Comment by bashonly** [comment] 2023-10-18 03:52
As a feature request, this is a duplicate of #3126, or else a duplicate of #1760 (and related to #3680)

It's also a duplicate of #8222, which you opened a few weeks ago, and was closed as a duplicate. Please do not intentionally open duplicate issues!

As a workaround (although parsing console output would itself be a workaround), you could use `--print-to-file` to write the `original_url` of finished downloads to another file, and then your program could compare with the original batch file and remove.

e.g. `yt-dlp --print-to-file after_move:original_url finished.txt -a batch_urls.txt`

**Closed by bashonly** 2023-10-18 03:52 UTC
Labels: enhancement, triage
