### ISSUE TITLE
mac 上使用，提示WARNING: [BiliBili] unable to extract play info 卸载后，重新安装也无法使用。。 youtube也不行

### ISSUE THREAD

**Issue by zifeicsy** [yt-dlp/yt-dlp#11684] opened 2024-11-30 03:12 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp 'https://www.bilibili.com/video/BV1nmzzYQE3m/?spm_id_from=333.337.search-card.all.click&vd_source=5dde80c3ed81d20cbf5260524061a1c7'
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1nmzzYQE3m/?spm_id_from=333.337.search-card.all.click&vd_source=...d20cbf5260524061a1c7
[BiliBili] 1nmzzYQE3m: Downloading webpage
WARNING: [BiliBili] unable to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BiliBili] 1nmzzYQE3m: Failed to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.bilibili.com/video/BV1nmzzYQE3m/?spm_id_from=333.337.search-card.all.click&vd_source=5dde80c3ed81d20cbf5260524061a1c7']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.11.27.232921 from yt-dlp/yt-dlp-nightly-builds [00dcde728] (pip)
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-14.5-arm64-arm-64bit (OpenSSL 3.1.2 1 Aug 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.1, brotli-None, certifi-2023.05.07, mutagen-1.47.0, requests-2.32.3, sqlite3-3.42.0, urllib3-2.1.0, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.11.27.232921 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.11.27.232921 from yt-dlp/yt-dlp-nightly-builds)
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1nmzzYQE3m/?spm_id_from=333.337.search-card.all.click&vd_source=5dde80c3ed81d20cbf5260524061a1c7
[BiliBili] 1nmzzYQE3m: Downloading webpage
WARNING: [BiliBili] unable to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BiliBili] 1nmzzYQE3m: Failed to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/Users/csy/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/csy/.local/lib/python3.11/site-packages/yt_dlp/extractor/bilibili.py", line 664, in _real_extract
    raise ExtractorError('Failed to extract play info')
```

**Comment by zifeicsy** [comment] 2024-11-30 03:21
pip install --force-reinstall --break-system-packages git+https://github.com/grqz/yt-dlp.git@ie/bilibili/pi_fallbk

用这个可以解决问题

**Comment by grqz** [comment] 2024-11-30 03:28
Duplicate of #11665

**Closed** 2024-11-30 04:07 UTC
Labels: question
