### ISSUE TITLE
[Site Request] Paramount Plus (Australia)

### ISSUE THREAD

**Issue by mj23au** [yt-dlp/yt-dlp#1355] opened 2021-10-20 12:09 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Verbose log

```
C:\Users\xxxxxx\Downloads>yt-dlp https://www.paramountplus.com/shows/spreadsheet/video/lG_VFofpERimaYNXrSJ_f2F7xRRxSwG5/spreadsheet-/ --cookies-from-browser chrome --verbose
[debug] Command-line config: ['https://www.paramountplus.com/shows/spreadsheet/video/lG_VFofpERimaYNXrSJ_f2F7xRRxSwG5/spreadsheet-/', '--cookies-from-browser', 'chrome', '--verbose']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\xxxxxx\AppData\Local\Google\Chrome\User Data\Default\Cookies"
[Cookies] Extracted 3261 cookies from chrome
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.10.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.3.2-2021-02-27-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
[debug] [ParamountPlus] Extracting URL: https://www.paramountplus.com/shows/spreadsheet/video/lG_VFofpERimaYNXrSJ_f2F7xRRxSwG5/spreadsheet-/
[ParamountPlus] lG_VFofpERimaYNXrSJ_f2F7xRRxSwG5: Downloading JSON metadata
ERROR: [ParamountPlus] lG_VFofpERimaYNXrSJ_f2F7xRRxSwG5: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 698, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3228, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default

```

## Description

It seems with the launch of Paramount Plus in Australia that they might be doing something "different" with the media

cant use https://www.paramountplus.com/shows/spreadsheet/video/lG_VFofpERimaYNXrSJ_f2F7xRRxSwG5/spreadsheet-/

but https://www.paramountplus.com/shows/spongebob-squarepants/video/ZvEow_nZm5WAiLeMlEmISm3Deti40Ciu/spongebob-squarepants-help-wanted-reef-blowers-tea-at-the-treedome/ seems to work

**Comment by gamer191** [comment] 2022-06-05 11:19
This website requires either a Paramount Plus, a Fetch TV or an Apple TV account

**Comment by wxolp** [comment] 2022-06-19 05:23
I think issue should be closed, URL is dead:

https://www.paramountplus.com/shows/video/lG_VFofpERimaYNXrSJ_f2F7xRRxSwG5/

**Comment by pukkandan** [comment] 2022-11-01 13:22
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1355

**Closed by pukkandan** 2022-11-01 13:22 UTC
Labels: account-needed, geo-blocked, site-bug
