### ISSUE TITLE
[BBC] Unable to extract playlist data

### ISSUE THREAD

**Issue by TomMettam** [yt-dlp/yt-dlp#2021] opened 2021-12-16 23:14 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Description

yt-dlp https://www.bbc.co.uk/archive/tomorrows-world--first-edition/zrrpjhv

[bbc] zrrpjhv: Downloading webpage
ERROR: [bbc] zrrpjhv: Unable to extract playlist data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://www.bbc.co.uk/archive/tomorrows-world--first-edition/zrrpjhv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.4-essentials_build-www.gyan.dev (setts), ffprobe 4.4-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [bbc] Extracting URL: https://www.bbc.co.uk/archive/tomorrows-world--first-edition/zrrpjhv
[bbc] zrrpjhv: Downloading webpage
ERROR: [bbc] zrrpjhv: Unable to extract playlist data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\bbc.py", line 1262, in _real_extract
  File "yt_dlp\extractor\common.py", line 1171, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract playlist data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\bbc.py", line 1262, in _real_extract
  File "yt_dlp\extractor\common.py", line 1171, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract playlist data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1329, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1398, in __extract_info
  File "yt_dlp\extractor\common.py", line 623, in extract
yt_dlp.utils.RegexNotFoundError: [bbc] zrrpjhv: Unable to extract playlist data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by pukkandan** [comment] 2021-12-16 23:25
Duplicate of #1374

**Closed by pukkandan** 2021-12-16 23:25 UTC
Labels: extractor-bug, triage

**Comment by TomMettam** [comment] 2021-12-16 23:30
Ah sorry, I didn't think it was the same because it's on a different section of the website.
