### ISSUE TITLE
Unable to download videos due to "File name too long"

### ISSUE THREAD

**Issue by DontEatOreo** [yt-dlp/yt-dlp#2329] opened 2022-01-13 15:14 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

If you're trying to download a video from a Twitter Tweet that's long enough, you will get an error saying the "File name too long", which prevents you from downloading the video. I haven't tried on other sites, since it's not an easy issue to replicate, but it most likely affects them too. A possible way to solve this issue is to allow longer file names.

### Verbose log

```shell
yt-dlp -Uv "https://twitter.com/i/status/1481455453137772550"
[debug] Command-line config: ['-Uv', 'https://twitter.com/i/status/1481455453137772550']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.16.0-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [twitter] Extracting URL: https://twitter.com/i/status/1481455453137772550
[twitter] 1481455453137772550: Downloading guest token
[twitter] 1481455453137772550: Downloading JSON metadata
[twitter] 1481455453137772550: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, tbr, vbr, abr, filesize, fs_approx, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1481455453137772550: Downloading 1 format(s): http-832
[debug] Invoking downloader on "https://video.twimg.com/ext_tw_video/1479629017716301824/pu/vid/480x414/392qmpo3xVS4pONh.mp4?tag=12"
ERROR: unable to open for writing: [Errno 36] File name too long: '🇺🇸LT.JG. Pliskin🇮🇪 - I thought this was a gag_skit. But upon looking into this, apparently... allegedly... Poki used to do coke on stream a LOT before it got really popular and this is a clip from that time. lol 👀 [1481455453137772550].mp4.part'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 265, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/usr/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 218, in sanitize_open
    return sanitize_open(filename, open_mode)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 557, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
OSError: [Errno 36] File name too long: '🇺🇸LT.JG. Pliskin🇮🇪 - I thought this was a gag_skit. But upon looking into this, apparently... allegedly... Poki used to do coke on stream a LOT before it got really popular and this is a clip from that time. lol 👀 [1481455453137772550].mp4.part'
```

**Comment by pukkandan** [comment] 2022-01-13 16:00
Duplicate of #1136

**Closed by pukkandan** 2022-01-13 16:00 UTC
Labels: bug, triage

**Comment by rubyFeedback** [comment] 2022-10-05 12:48
It seems as if:

     yt-dlp -o "%(id)s.%(ext)s"

worked for me. I got the downloaded file. Found it on reddit and github actually. Not very elegant
but I can work around it via a secondary script aka "if error is too long file name, use the -o 
variant instead", so my problem was solved actually. \o/

Still, would be nice for others if yt-dlp can offer this in general.

**Comment by erik55** [comment] 2023-01-23 11:14
There is an option called `--trim-filenames NUM`. Shouldn’t that work?

**Comment by numpad0** [comment] 2023-01-23 15:22
`-o "%(title).150B [%(id)s].%(ext)s".` is more backward/forward compatible, besides it's ready to copy and paste from here should anyone encounter this issue before it's fixed

**Comment by erik55** [comment] 2023-01-23 17:02
Well, `--trim-filenames` seems to **not** work. Bug?

**Comment by numpad0** [comment] 2023-01-24 20:40
Yes, it's known that the option is buggy, ref: https://github.com/yt-dlp/yt-dlp/issues/2314#issuecomment-1011295071. Just copy-paste that format string when yt-dlp complains and it should be all-around most compatible.

**Comment by prvn-pa** [comment] 2023-03-16 05:35
> Well, `--trim-filenames` seems to **not** work. Bug?

It is actually working and solved the issue.

**Comment by jammi** [comment] 2023-03-30 14:49
This is not fixed, therefore this issue should not be closed. The filename length is typically around 256 bytes depending on OS and FS, so why not pick a safe number as the default behavior? If you want to store the entire text content of the web page somewhere, the filename shouldn't be that place, extended attribute metadata is for stuff like that. Even if someone wanted to use a filename for that, then _that_ should be the extra option, but definitely not the default.

**Comment by pukkandan** [comment] 2023-03-31 06:59
https://github.com/yt-dlp/yt-dlp/issues/2329#issuecomment-1012272943
