### ISSUE TITLE
HTTP Error 404

### ISSUE THREAD

**Issue by TaiVaanan** [yt-dlp/yt-dlp#1807] opened 2021-11-26 21:59 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Using use some m3u8 extractor and used to successfully download from "xvideos.com". The past few days, it errors out. Verbose output is provided under. 
Your help would be highly appreciated. Thanks.

### Verbose log

```shell
yt-dlp.exe -Uv https://www.xvideos.com/video52388485/butt_plugged_blonde_walked_in_public
[debug] Command-line config: ['-Uv', 'https://www.xvideos.com/video52388485/butt_plugged_blonde_walked_in_public']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-07-04-git-301d275301-full_build-www.gyan.dev (setts), ffprobe 2021-07-04-git-301d275301-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [XVideos] Extracting URL: https://www.xvideos.com/video52388485/butt_plugged_blonde_walked_in_public
[XVideos] 52388485: Downloading webpage
ERROR: [XVideos] 52388485: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 713, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3295, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

**Comment by MinePlayersPE** [comment] 2021-11-26 22:08
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1788?

**Closed** 2021-11-26 22:31 UTC
Labels: bug, triage
