### ISSUE TITLE
[YouTube] video is not downloaded from the stream beginning. 

### ISSUE THREAD

**Issue by miaulightouch** [yt-dlp/yt-dlp#2974] opened 2022-03-06 15:24 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Taiwan

### Description

video is not downloaded from the stream beginning, but it would be fine if watch at youtube.

the `Total fragments` in log is wrong, it's a seven hours live and it should be more than 20k fragments.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=iVoIj6D2eFo']
[debug] Encodings: locale cp950, fs utf-8, out utf-8, err utf-8, pref cp950
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 5.0-full_build-www.gyan.dev (setts), ffprobe 5.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=iVoIj6D2eFo
[youtube] iVoIj6D2eFo: Downloading webpage
[youtube] iVoIj6D2eFo: Downloading android player API JSON
[youtube] iVoIj6D2eFo: Downloading m3u8 information
[youtube] iVoIj6D2eFo: Downloading MPD manifest
[youtube] iVoIj6D2eFo: Downloading m3u8 information
[youtube] iVoIj6D2eFo: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] iVoIj6D2eFo: Downloading 1 format(s): 301
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1646601357/ei/LNAkYrb0O5aQlQTS446gCQ/ip/114.46.183.74/id/iVoIj6D2eFo.2/itag/301/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D299/hls_chunk_host/rr3---sn-un57enel.googlevideo.com/force_finished/1/vprv/1/playlist_type/CLEAN/initcwndbps/5220/mh/hn/mm/44/mn/sn-un57enel/ms/lva/mv/m/mvi/3/pl/23/dover/11/pacing/0/keepalive/yes/fexp/24001373,24007246/mt/1646579559/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,force_finished,vprv,playlist_type/sig/AOq0QJ8wRAIgBDPyTVFewecL1DT_L-2sbwtKb_C04_6xdrIZOQbkzw4CIEJCEJVvkyN2xoPOOlb_6RwYYv4Igb1Cg67cXilL_dSQ/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRgIhAN3o1EJlXVd_QrH_iapkjWSCS8MxNCy_E3ZQXEjknJgcAiEA-LLjfmSKEVvNM3vnSKVjx1c14Vs4HhZW7oaLtPwT9v8%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 7200
[download] Destination: 【全編無料配信】#BLACKVOXX ~ぶぎぼ2周忌~【BOOGEY VOXX】 [iVoIj6D2eFo].mp4
[download]   0.4% of ~5.51GiB at  5.94MiB/s ETA 15:53 (frag 30/7200)
ERROR: Interrupted by user
```

**Comment by pukkandan** [comment] 2022-03-06 15:26
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1564

**Closed by pukkandan** 2022-03-06 15:26 UTC
Labels: site-bug, triage
