### ISSUE TITLE
TikTok error: Unable to find video in feed - the JSON object must be str, bytes or bytearray, not NoneType

### ISSUE THREAD

**Issue by pablodelflo** [yt-dlp/yt-dlp#9013] opened 2024-01-16 13:52 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Spain

### Provide a description that is worded well enough to be understood

I have programmed a small script to download TikTok videos from a user-created collection. This collection has 20 videos, of which 19 have been downloaded, giving me error only one.

The URL is accessible and the video can be downloaded from the browser, but not from the script.

My version is:

yt-dlp -U
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -o 7261360391379307803.mp4 -P "C:/Users/delgadop/Documents/Formacion/python/tiktok_bot/VIDEOS/" https://www.tiktok.com/@movistarplus/video/7261360391379307803 -vU
[debug] Command-line config: ['-o', '7261360391379307803.mp4', '-P', 'C:/Users/delgadop/Documents/ITALTEL/Formacion/python/tiktok_bot/VIDEOS/', 'https://www.tiktok.com/@movistarplus/video/7261360391379307803', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip)
[debug] Python 3.11.4 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, requests-2.31.0, sqlite3-3.42.0, urllib3-2.0.4, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[TikTok] Extracting URL: https://www.tiktok.com/@movistarplus/video/7261360391379307803
[TikTok] 7261360391379307803: Downloading video feed
WARNING: [TikTok] 7261360391379307803: Unable to find video in feed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7261360391379307803: Downloading webpage
ERROR: [TikTok] 7261360391379307803: Unable to extract sigi state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\delgadop\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\delgadop\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\tiktok.py", line 700, in _real_extract
    sigi_data = self._get_sigi_state(webpage, video_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\delgadop\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\tiktok.py", line 52, in _get_sigi_state
    return self._search_json(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\delgadop\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1280, in _search_json
    json_string = self._search_regex(
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\delgadop\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1266, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment] 2024-01-16 14:00
1. The video is not available from the mobile feed API; either it is flagged as sensitive, the audio has been taken down, or it is otherwise de-listed/shadowbanned - this results in the `Unable to find video in feed` warning and the fallback to webpage extraction. This is a known issue:
  - #8678
  - #6483
  - #4992

2. TT is now blocking yt-dlp from accessing any of their webpages, sending us captcha challenge pages w/o any video data instead. This is the cause of the `Unable to extract sigi state` error. This is being tracked by:
  - #8620

3. The JSON error output in your title is not found anywhere in your log?

Closing as duplicate of #8620 and/or #8678

**Closed by bashonly** 2024-01-16 14:00 UTC
Labels: duplicate, site-bug, site:tiktok
