### ISSUE TITLE
Add download Tiktok live

### ISSUE THREAD

**Issue by JC-Chung** [yt-dlp/yt-dlp#5510] opened 2022-11-12 08:50 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Example URLs

`https://tiktok.com/@<uniqueId>/live`
`https://vt.tiktok.com/.........`
`https://tiktok.com/@nozomi0125/live`
`https://vt.tiktok.com/ZSRT6Wqvf`

### Provide a description that is worded well enough to be understood

Currently `yt-dlp` does not support `https://tiktok.com/@<uniqueId>/live`, but it is possible to get a download link using the following methods.

```py
import json
import requests
from bs4 import BeautifulSoup

uniqueId = "nozomi0125"
url = f"https://tiktok.com/@{uniqueId}/live"
html = requests.get(url)
body = BeautifulSoup(html.text, "html5lib")
json_data = body.find("script", attrs={"id": "SIGI_STATE"})
data = json.loads(json_data.text)

if data["LiveRoom"]["liveRoomUserInfo"]:
    roomId = data["LiveRoom"]["liveRoomUserInfo"]["user"]["roomId"]
    print(roomId)
    # 7164947213481691905
    live_url = f"https://tiktok.com/api/live/detail/?aid=1988&roomID={roomId}"
    # live_url from https://github.com/Pauloo27/tiktok-live/blob/master/index.js#L23
    live_data = json.loads(requests.get(live_url).text)
    liveUrl = live_data["LiveRoomInfo"]["liveUrl"]
    liveUrl = liveUrl.replace("pull-hls", "pull-flv").replace("/playlist.m3u8", ".flv").replace(".m3u8", ".flv")
    print(liveUrl)
    # https://pull-flv-f1-sg01.tiktokcdn.com/stage/stream-7164947186352966402_or4.flv
else:
    print("This user didn't have live room.")
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-F', 'https://vt.tiktok.com/ZSRT6Wqvf']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b]
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.6 (CPython AMD64 64bit) - Windows-10-10.0.19042-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-11-03-git-5ccd4d3060-full_build-www.gyan.dev (setts), ffprobe 2022-11-03-git-5ccd4d3060-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.09.14, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Loaded 1724 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [vm.tiktok] Extracting URL: https://vt.tiktok.com/ZSRT6Wqvf
[vm.tiktok] ZSRT6Wqvf: Downloading webpage
[debug] [generic] Extracting URL: https://www.tiktok.com/@nozomi0125/live?_r=1&checksum=f77a7b8796d3b2beab89a8e5626546d421e64d592b5fe4fd0060392d7edc81ba&sec_user_id=MS4wLjABAAAAZKssYC4STmt4ZtbXjSBk5v8q74cMW_oXiWXjuvQRbWEf4JH6NfUkHCK2QWF5e0gz&share_app_id=1180&share_link_id=C54BB0AE-35AC-46A0-B3D9-3FD958E98855&source=h5_t&timestamp=1668219406&tt_from=twitter&ug_btm=b0%2Cb0&user_id=6639585750018146306&utm_campaign=client_share&utm_medium=ios&utm_source=twitter
[generic] live?_r=1&checksum=f77a7b8796d3b2beab89a8e5626546d421e64d592b5fe4fd0060392d7edc81ba&sec_user_id=MS4wLjABAAAAZKssYC4STmt4ZtbXjSBk5v8q74cMW_oXiWXjuvQRbWEf4JH6NfUkHCK2QWF5e0gz&share_app_id=1180&share_link_id=C54BB0AE-35AC-46A0-B3D9-3FD958E98855&source=h5_t&timestamp=1668219406&tt_from=twitter&ug_btm=b0,b0&user_id=6639585750018146306&utm_campaign=client_share&utm_medium=ios&utm_source=twitter: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] live?_r=1&checksum=f77a7b8796d3b2beab89a8e5626546d421e64d592b5fe4fd0060392d7edc81ba&sec_user_id=MS4wLjABAAAAZKssYC4STmt4ZtbXjSBk5v8q74cMW_oXiWXjuvQRbWEf4JH6NfUkHCK2QWF5e0gz&share_app_id=1180&share_link_id=C54BB0AE-35AC-46A0-B3D9-3FD958E98855&source=h5_t&timestamp=1668219406&tt_from=twitter&ug_btm=b0,b0&user_id=6639585750018146306&utm_campaign=client_share&utm_medium=ios&utm_source=twitter: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.tiktok.com/@nozomi0125/live?_r=1&checksum=f77a7b8796d3b2beab89a8e5626546d421e64d592b5fe4fd0060392d7edc81ba&sec_user_id=MS4wLjABAAAAZKssYC4STmt4ZtbXjSBk5v8q74cMW_oXiWXjuvQRbWEf4JH6NfUkHCK2QWF5e0gz&share_app_id=1180&share_link_id=C54BB0AE-35AC-46A0-B3D9-3FD958E98855&source=h5_t&timestamp=1668219406&tt_from=twitter&ug_btm=b0%2Cb0&user_id=6639585750018146306&utm_campaign=client_share&utm_medium=ios&utm_source=twitter
Traceback (most recent call last):
  File "C:\Users\test01\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\test01\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1561, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\test01\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\test01\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\generic.py", line 2721, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tiktok.com/@nozomi0125/live?_r=1&checksum=f77a7b8796d3b2beab89a8e5626546d421e64d592b5fe4fd0060392d7edc81ba&sec_user_id=MS4wLjABAAAAZKssYC4STmt4ZtbXjSBk5v8q74cMW_oXiWXjuvQRbWEf4JH6NfUkHCK2QWF5e0gz&share_app_id=1180&share_link_id=C54BB0AE-35AC-46A0-B3D9-3FD958E98855&source=h5_t&timestamp=1668219406&tt_from=twitter&ug_btm=b0%2Cb0&user_id=6639585750018146306&utm_campaign=client_share&utm_medium=ios&utm_source=twitter
```

**Comment by pukkandan** [comment] 2022-11-12 08:58
Duplicate of #3698

**Closed** 2022-11-12 09:00 UTC
Labels: duplicate, site-request, site:tiktok

**Comment by mac3265708** [comment] 2022-11-16 17:09
[debug] Command-line config: ['https://www.tiktok.com/@adekosjh68f/live', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (darwin_exe)
[debug] Python 3.8.9 (CPython arm64 64bit) - macOS-12.6-arm64-arm-64bit (LibreSSL 2.8.3)
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'http': 'http://127.0.0.1:1082', 'https': 'http://127.0.0.1:1082'}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://www.tiktok.com/@adekosjh68f/live
[generic] live: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] live: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.tiktok.com/@adekosjh68f/live
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1561, in __extract_info
  File "yt_dlp/extractor/common.py", line 674, in extract
  File "yt_dlp/extractor/generic.py", line 2721, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tiktok.com/@adekosjh68f/live

**Comment by mac3265708** [comment] 2022-11-16 17:11
Problems downloading tiktoklive
