### ISSUE TITLE
Yt-dlp wont downlald tiktok profiles

### ISSUE THREAD

**Issue by JaKrIvMa** [yt-dlp/yt-dlp#2488] opened 2022-01-25 20:59 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Yt-dlp won't download profiles when copied url and pasted after yt-dlp.

### Verbose log

```shell
[debug] Command-line config: ['--hls-use-mpegts', '--no-part', '-P', '/data/data/com.termux/files/home/storage/shared/Youtube-DL/', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', 'https://vm.tiktok.com/ZML8BHeLu/', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-4.19.202-g76868f17c3ad-ab7943297-aarch64-with-libc
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://vm.tiktok.com/ZML8BHeLu/
[generic] ZML8BHeLu: Requesting header
[redirect] Following redirect to https://www.tiktok.com/@gialeach2?_d=secCgwIARCbDRjEFSACKAESPgo8Yar2hrGpKcrAb2Ksl5VhJtGtq5OopSk%2F8YLVSjSlE6W2lp40duaAGnISlojpsv%2FVEzupIZAxCnDcXy9vGgA%3D&language=en&sec_uid=MS4wLjABAAAA_4YFteAsI2uO7NtwOOm1DZELyj8TOqqsattDcyIPDqZGYI6a_KKsFK4hbd0zHFCG&sec_user_id=MS4wLjABAAAAGZftKBDhy0L3u6h0rXFjcLZK2H0r56Wc4mRUIc3q2w2sx8Mcp21RRknI4MVsoiY0&share_app_id=1233&share_author_id=6829289036316115974&share_link_id=869a1d00-a945-44af-ae22-e24f5dc03ccb&timestamp=1643143718&u_code=d8jg2m6b11h2fa&user_id=6746561257421292549&utm_campaign=client_share&utm_medium=android&utm_source=more&source=h5_m&_r=1
[debug] [tiktok:user] Extracting URL: https://www.tiktok.com/@gialeach2?_d=secCgwIARCbDRjEFSACKAESPgo8Yar2hrGpKcrAb2Ksl5VhJtGtq5OopSk%2F8YLVSjSlE6W2lp40duaAGnISlojpsv%2FVEzupIZAxCnDcXy9vGgA%3D&language=en&sec_uid=MS4wLjABAAAA_4YFteAsI2uO7NtwOOm1DZELyj8TOqqsattDcyIPDqZGYI6a_KKsFK4hbd0zHFCG&sec_user_id=MS4wLjABAAAAGZftKBDhy0L3u6h0rXFjcLZK2H0r56Wc4mRUIc3q2w2sx8Mcp21RRknI4MVsoiY0&share_app_id=1233&share_author_id=6829289036316115974&share_link_id=869a1d00-a945-44af-ae22-e24f5dc03ccb&timestamp=1643143718&u_code=d8jg2m6b11h2fa&user_id=6746561257421292549&utm_campaign=client_share&utm_medium=android&utm_source=more&source=h5_m&_r=1
[tiktok:user] gialeach2: Downloading webpage
[tiktok:user] gialeach2: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying...
[tiktok:user] gialeach2: Downloading user video list page 1 (attempt 1)
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying...
[tiktok:user] gialeach2: Downloading user video list page 1 (attempt 2)
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying...
[tiktok:user] gialeach2: Downloading user video list page 1 (attempt 3)
ERROR: [tiktok:user] gialeach2: gialeach2: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/tiktok.py", line 561, in _real_extract
    thumbnail = traverse_obj(videos, (0, 'author', 'avatar_larger', 'url_list', 0))
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 5135, in traverse_obj
    val = _traverse_obj(obj, path)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 5121, in _traverse_obj
    obj = obj[key]
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2736, in __getitem__
    self.__cache.extend(itertools.islice(self.__iterable, n))
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/tiktok.py", line 530, in _video_entries_api
    post_list = self._call_api('aweme/post', query, username,
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/tiktok.py", line 80, in _call_api
    return self._download_json(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 992, in _download_json
    res = self._download_json_handle(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 978, in _download_json_handle
    return self._parse_json(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1007, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
```

**Comment by NanaMizukiAnother7** [comment] 2022-01-25 21:06
> * [x]  I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates

Thi is duplicate of #2135.

**Comment by pukkandan** [comment] 2022-01-25 21:10
Same underlying issue as #2476

**Closed by pukkandan** 2022-01-25 21:10 UTC
Labels: duplicate, site-bug, site:tiktok

**Comment by decryptozoo** [comment] 2022-02-02 22:15
This is fixed on current master branch.

**Comment by UnixCro** [comment] 2022-05-21 06:21
I can´t download the whole profile with yt-dlp. Previous it worked without problems and really fast.

```
fuck@differences % yt-dlp -v https://www.tiktok.com/@lisaandlena
[debug] Command-line config: ['-v', 'https://www.tiktok.com/@lisaandlena']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.8.9 (CPython 64bit) - macOS-12.0.1-x86_64-i386-64bit
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.1-tessus (setts), ffprobe 4.4.1-tessus
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [tiktok:user] Extracting URL: https://www.tiktok.com/@lisaandlena
[tiktok:user] lisaandlena: Downloading webpage
ERROR: [tiktok:user] lisaandlena: Unable to download webpage: The read operation timed out (caused by timeout('The read operation timed out')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/Library/Python/3.8/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/Library/Python/3.8/site-packages/yt_dlp/extractor/tiktok.py", line 629, in _real_extract
    webpage = self._download_webpage(url, user_name, headers={
  File "/Library/Python/3.8/site-packages/yt_dlp/extractor/common.py", line 933, in _download_webpage
    res = self._download_webpage_handle(
  File "/Library/Python/3.8/site-packages/yt_dlp/extractor/common.py", line 801, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/Library/Python/3.8/site-packages/yt_dlp/extractor/common.py", line 786, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/Library/Python/3.8/site-packages/yt_dlp/extractor/common.py", line 768, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Library/Python/3.8/site-packages/yt_dlp/YoutubeDL.py", line 3596, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Python/3.8/site-packages/yt_dlp/utils.py", line 1419, in https_open
    return self.do_open(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1358, in do_open
    r = h.getresponse()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1344, in getresponse
    response.begin()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

fuck@differences % 
```

**Comment by warshell** [comment] 2023-01-20 21:14
```
[debug] Command-line config: ['-v', 'https://www.tiktok.com/@som']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg 4.2.1
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user] Extracting URL: https://www.tiktok.com/@som
[tiktok:user] somaleto: Downloading webpage
ERROR: [tiktok:user] som: Unable to download webpage: The read operation timed out (caused by TimeoutError('The read operation timed out')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Server\bin\python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 680, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\site-packages\yt_dlp\extractor\tiktok.py", line 672, in _real_extract
    webpage = self._download_webpage(url, user_name, headers={
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1083, in _download_webpage
    return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 1034, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 868, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 825, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "C:\Server\bin\python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 807, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\site-packages\yt_dlp\utils.py", line 1535, in https_open
    return self.do_open(
           ^^^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\urllib\request.py", line 1352, in do_open
    r = h.getresponse()
        ^^^^^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Server\bin\python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Server\bin\python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out
```
