### ISSUE TITLE
 [iqiyi] None: Can't find any video

### ISSUE THREAD

**Issue by thanhky69** [yt-dlp/yt-dlp#7383] opened 2023-06-22 11:29 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

 [iqiyi] None: Can't find any video

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\yt-dlp>yt-dlp -vU yt-dlp --cookies-from-browser Firefox https://www.iqiyi.com/v_19rthmf0b0.html
[debug] Command-line config: ['-vU', 'yt-dlp', '--cookies-from-browser', 'Firefox', 'https://www.iqiyi.com/v_19rthmf0b0.html']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.06.22.080226 [812cdfa06] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110509-g722ff74055-20230506 (setts), ffprobe N-110509-g722ff74055-20230506
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\84562\AppData\Roaming\Mozilla\Firefox\Profiles\wabojgkx.default-release-1-1685454224602\cookies.sqlite"
[Cookies] Extracted 194 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.06.22.080226, Current version: nightly@2023.06.22.080226
Current Build Hash: 64bc9dc2239dd2373d7efa206d4853301a0c32828d99a960bde6b4e244bf940d
yt-dlp is up to date (nightly@2023.06.22.080226)
[CommonMistakes] Extracting URL: yt-dlp
ERROR: [CommonMistakes] None: You've asked yt-dlp to download the URL "yt-dlp". That doesn't make any sense. Simply remove the parameter in your command or configuration.
  File "yt_dlp\extractor\common.py", line 708, in extract
  File "yt_dlp\extractor\commonmistakes.py", line 25, in _real_extract

[iqiyi] Extracting URL: https://www.iqiyi.com/v_19rthmf0b0.html
[iqiyi] temp_id: download video page
ERROR: [iqiyi] None: Can't find any video; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 708, in extract
  File "yt_dlp\extractor\iqiyi.py", line 355, in _real_extract
```

**Comment by bashonly** [comment] 2023-06-22 11:35
Duplicate of #2740

**Closed by bashonly** 2023-06-22 11:35 UTC
Labels: site-bug, triage
