### ISSUE TITLE
[facebook] New link format /reel/

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#4112] opened 2022-06-19 13:22 UTC
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Looks like FB now has a new link format Facebook watch and it's user agent based. 

So, the links are:
https://www.facebook.com/reel/522098049695565/?s=single_unit
https://www.facebook.com/reel/425457359591024/?s=ifu

On mobile they redirect to:
https://www.facebook.com/EviSiskos/videos/for-real-thought-toocute-cutenessoverload/425457359591024/
https://www.facebook.com/xaviermortimervegas/videos/walking-on-a-street-light-/242081260998047/

but on desktop they are redirected to FB login page.
passing user agent gives an error - ERROR: [facebook] 522098049695565: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U 

**Potential solution** - maybe if this /reel/ link is detected, just use some random mobile device user agent and as you'll see in the log, use the "correct" redirect link  which is already supported. _redirect] Following redirect to https://m.facebook.com/xaviermortimervegas/videos/522098049695565/?refsrc=deprecated&_rdr_

### Verbose log

```shell
With random iPhone user agent:

./yt-dlp -v --user-agent "Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Mobile/15E148 Safari/604.1" -F "https://www.facebook.com/reel/522098049695565/?s=single_unit"
[debug] Command-line config: ['-v', '--user-agent', 'Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Mobile/15E148 Safari/604.1', '-F', 'https://www.facebook.com/reel/522098049695565/?s=single_unit']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.9.13 (CPython 64bit) - macOS-12.4-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.facebook.com/reel/522098049695565/?s=single_unit
[generic] ?s=single_unit: Requesting header
[redirect] Following redirect to https://m.facebook.com/watch/?v=522098049695565&refsrc=deprecated&_rdr
[debug] [facebook] Extracting URL: https://m.facebook.com/watch/?v=522098049695565&refsrc=deprecated&_rdr
[facebook] 522098049695565: Downloading webpage
[facebook] 522098049695565: Downloading webpage
ERROR: [facebook] 522098049695565: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "./yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/facebook.py", line 715, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "./yt-dlp/yt_dlp/extractor/facebook.py", line 661, in _extract_from_url
    raise ExtractorError('Cannot parse data')

------------------------------------------------------------------------
Without user-agent:
./yt-dlp -v -F "https://www.facebook.com/reel/522098049695565/?s=single_unit" 
[debug] Command-line config: ['-v', '-F', 'https://www.facebook.com/reel/522098049695565/?s=single_unit']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.9.13 (CPython 64bit) - macOS-12.4-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.facebook.com/reel/522098049695565/?s=single_unit
[generic] ?s=single_unit: Requesting header
[redirect] Following redirect to https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Freel%2F522098049695565%2F%3Fs%3Dsingle_unit
[debug] [generic] Extracting URL: https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Freel%2F522098049695565%2F%3Fs%3Dsingle_unit
[generic] login.php?next=https://www.facebook: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] login.php?next=https://www.facebook: Downloading webpage
[generic] login.php?next=https://www.facebook: Extracting information
[debug] Looking for video embeds
[redirect] Following redirect to https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Freel%2F522098049695565%2F%3Fs%3Dsingle_unit&_fb_noscript=1
[debug] [generic] Extracting URL: https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Freel%2F522098049695565%2F%3Fs%3Dsingle_unit&_fb_noscript=1
[generic] login.php?next=https://www.facebook: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] login.php?next=https://www.facebook: Downloading webpage
[generic] login.php?next=https://www.facebook: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Freel%2F522098049695565%2F%3Fs%3Dsingle_unit&_fb_noscript=1
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1420, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1490, in __extract_info
    ie_result = ie.extract(url)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/generic.py", line 4135, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Freel%2F522098049695565%2F%3Fs%3Dsingle_unit&_fb_noscript=1
```

**Comment by pukkandan** [comment] 2022-06-19 13:28
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/4039

**Closed by pukkandan** 2022-06-19 13:28 UTC
Labels: duplicate, site-request, site:facebook
