### ISSUE TITLE
Support for time-range based slicing of media

### ISSUE THREAD

**Issue by tripulse** [yt-dlp/yt-dlp#2105] opened 2021-12-24 16:51 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When I download a video, I have to download it entirely. It'd be great if we had a feature to download only a slice of it. The current workaround is to get the URL from `-g` then pass it to FFmpeg and specify a loose temporal range, so the trimmed version is downloaded losslessly.

For example, `yt-dlp --begin-ts 01:00 --end-ts 01:45 ...` or `--duration 00:45` instead of `--end-ts`. Making a wrapper shell-script is rather inconvenient. The [timestamps][1] need not be followed exactly when `--recode-video` isn't specified. This is accomplished with a trivial wrapper over FFmpeg.

[1]: https://ffmpeg.org/ffmpeg-utils.html#Time-duration

**Comment by pukkandan** [comment] 2021-12-24 17:26
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/52
Also see https://github.com/yt-dlp/yt-dlp/issues/686

**Closed by pukkandan** 2021-12-24 17:26 UTC
Labels: enhancement, triage
