### ISSUE TITLE
[ceskatelevize.cz] Cannot download manifest - SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by pukkandan** [yt-dlp/yt-dlp#2043] opened 2021-12-18 17:52 UTC
I'm sorry, but I think that the extractor is still broken. For instance:

```
$ yt-dlp --verbose "https://www.ceskatelevize.cz/porady/10095426857-interview-ct24/221411058041217/"
[debug] Command-line config: ['--verbose', 'https://www.ceskatelevize.cz/porady/10095426857-interview-ct24/221411058041217/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.15.5-gentoo-x86_64-x86_64-AMD_Ryzen_9_3900X_12-Core_Processor-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Crypto, sqlite
[debug] Proxy map: {}
[debug] [CeskaTelevize] Extracting URL: https://www.ceskatelevize.cz/porady/10095426857-interview-ct24/221411058041217/
[CeskaTelevize] 221411058041217: Downloading webpage
[CeskaTelevize] 221411058041217: Downloading webpage
[CeskaTelevize] 221411058041217: Downloading webpage
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading MPD manifest
WARNING: [CeskaTelevize] Failed to download MPD manifest: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1145)>
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading m3u8 information
WARNING: [CeskaTelevize] Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1145)>
[download] Downloading playlist: 17. prosinec - Interview ČT24 | Česká televize
[CeskaTelevize] playlist 17. prosinec - Interview ČT24 | Česká televize: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
ERROR: [CeskaTelevize] 61924494877975106: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

_Originally posted by @zippy2 in https://github.com/yt-dlp/yt-dlp/issues/1899#issuecomment-997226548_

**Comment by mkubecek** [comment] 2021-12-18 21:59
Works for me (it's not 2021.12.01, it's commit 37bd07a29dec from mk/cz branch in mkubecek/yt-dlp which is a recent snapshot of master branch with some improvements for stream.cz and iprima.cz):
```
mike@lion:/srv/ram> yt-dlp -v https://www.ceskatelevize.cz/porady/10095426857-interview-ct24/221411058041217/
[debug] Command-line config: ['-v', 'https://www.ceskatelevize.cz/porady/10095426857-interview-ct24/221411058041217/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (zip)
[debug] Lazy loading extractors is disabled
[debug] Python version 3.6.15 (CPython 64bit) - Linux-5.16.0-rc5-lp153.2.gc317c11-default-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 4.4.git (setts), ffprobe 4.4.git, rtmpdump 2.4
[debug] Optional libraries: sqlite, websockets
[debug] Proxy map: {}
[debug] [CeskaTelevize] Extracting URL: https://www.ceskatelevize.cz/porady/10095426857-interview-ct24/221411058041217/
[CeskaTelevize] 221411058041217: Downloading webpage
[CeskaTelevize] 221411058041217: Downloading webpage
[CeskaTelevize] 221411058041217: Downloading webpage
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading MPD manifest
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: 17. prosinec - Interview ČT24 | Česká televize
[CeskaTelevize] playlist 17. prosinec - Interview ČT24 | Česká televize: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 61924494877975106: Downloading 1 format(s): dash-main-1001-1506+dash-main-1002-1504
[debug] Invoking downloader on "https://ivys-cdn.o2tv.cz/cdn/uri/get/?token=66d3c4b50aee2cb6712cd50aed8f71b9719e34ff&contentType=vod&drmOnly=false&expiry=1639867583&id=61924494877975106&playerType=dash&quality=web&region=1&skipIpAddressCheck=false&userId=dca32c21-54b5-40f5-a9b0-de2f6bbd2402&encryption=wv"
[dashsegments] Total fragments: 739
[download] Destination: 17. prosinec - Interview ČT24 _ Česká televize [61924494877975106].fdash-main-1001-1506.mp4
[download] 100% of 1.03GiB in 01:21                                                     
[debug] Invoking downloader on "https://ivys-cdn.o2tv.cz/cdn/uri/get/?token=66d3c4b50aee2cb6712cd50aed8f71b9719e34ff&contentType=vod&drmOnly=false&expiry=1639867583&id=61924494877975106&playerType=dash&quality=web&region=1&skipIpAddressCheck=false&userId=dca32c21-54b5-40f5-a9b0-de2f6bbd2402&encryption=wv"
[dashsegments] Total fragments: 739
[download] Destination: 17. prosinec - Interview ČT24 _ Česká televize [61924494877975106].fdash-main-1002-1504.m4a
[download] 100% of 23.18MiB in 00:23                                                     
[Merger] Merging formats into "17. prosinec - Interview ČT24 _ Česká televize [61924494877975106].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:17. prosinec - Interview ČT24 _ Česká televize [61924494877975106].fdash-main-1001-1506.mp4' -i 'file:17. prosinec - Interview ČT24 _ Česká televize [61924494877975106].fdash-main-1002-1504.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:17. prosinec - Interview ČT24 _ Česká televize [61924494877975106].temp.mp4'
Deleting original file 17. prosinec - Interview ČT24 _ Česká televize [61924494877975106].fdash-main-1002-1504.m4a (pass -k to keep)
Deleting original file 17. prosinec - Interview ČT24 _ Česká televize [61924494877975106].fdash-main-1001-1506.mp4 (pass -k to keep)
[download] Finished downloading playlist: 17. prosinec - Interview ČT24 | Česká televize
```
Could it be an openssl compatibility issue?

**Comment by pukkandan** [comment] 2021-12-18 22:16
Not sure. I can reproduce in py3.10 OpenSSL 1.1.1. What is your OpenSSL version?

```
➤ py -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.1.1l  24 Aug 2021

➤ yt-dlp --verbose "https://www.ceskatelevize.cz/porady/10095426857-interview-ct24/221411058041217"
[debug] Command-line config: ['--verbose', 'https://www.ceskatelevize.cz/porady/10095426857-interview-ct24/221411058041217']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071af6] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: e72906804
[debug] Python version 3.10.0 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-103892-g71f2a9a2e5-20210927 (setts,fdk), ffprobe N-103892-g71f2a9a2e5-20210927, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [CeskaTelevize] Extracting URL: https://www.ceskatelevize.cz/porady/10095426857-interview-ct24/221411058041217
[CeskaTelevize] 221411058041217: Downloading webpage
[CeskaTelevize] 221411058041217: Downloading webpage
[CeskaTelevize] 221411058041217: Downloading webpage
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading MPD manifest
WARNING: [CeskaTelevize] Failed to download MPD manifest: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)>
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading JSON metadata
[CeskaTelevize] 221411058041217: Downloading m3u8 information
WARNING: [CeskaTelevize] Failed to download m3u8 information: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)>
[download] Downloading playlist: 17. prosinec - Interview ČT24 | Česká televize
[CeskaTelevize] playlist 17. prosinec - Interview ČT24 | Česká televize: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
ERROR: [CeskaTelevize] 61924494877975106: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1337, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1744, in __process_iterable_entry
    return self.process_ie_result(
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1472, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 2358, in process_video_result
    self.raise_no_formats(info_dict)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 939, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [CeskaTelevize] 61924494877975106: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

[download] Finished downloading playlist: 17. prosinec - Interview ČT24 | Česká televize
```

**Comment by mkubecek** [comment] 2021-12-18 23:52
I get `OpenSSL 1.1.1d  10 Sep 2019` (1.1.1d package in openSUSE Leap 15.3).

**Comment by zippy2** [comment] 2021-12-19 07:52
Yeah, I have the same version as @pukkandan :
```
OpenSSL 1.1.1l  24 Aug 2021
````

and I'm on current `master` (`d76d15a66`).

**Comment by pukkandan** [comment] 2021-12-19 14:38
I can't find any relevant changes in the OpenSSL changelog https://www.openssl.org/news/cl111.txt

**Comment by MartinLojda** [comment] 2022-01-04 08:31
Same situation on Mac (installed via Homebrew). 
The problem is caused by OpenSSL library - the removed some ssl ciphers in newer versions used by ceskatelevize.cz servers.

Possible solution might be to replace "https" with "http" in https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/ceskatelevize.py#L159 and use non secure protocol for all links

Unfortunatelly, I'm not skilled in Python enough to make PR. Hope it helps.

**Comment by MartinLojda** [comment] 2022-01-12 19:36
It works. Can be closed now. Thank you!

**Comment by wlritchi** [comment] 2022-05-07 10:59
This issue is also affecting me for the AfreecaTV user extractor. Unfortunately, the `http` workaround isn't available for that extractor, because the server redirects it to https. Since this looks like some kind of external issue that's affecting multiple sites for us, should we continue discussion here, or open a fresh issue to discuss?

<details>
<summary>Environment</summary>

```
Arch Linux
Python 3.10.4
yt-dlp 2022.04.08
OpenSSL 1.1.1o  3 May 2022
```
</details>

<details>
<summary>Verbose log</summary>

```
$ yt-dlp -vU --no-config -- http://bj.afreecatv.com/ryuryu24/vods/user
[debug] Command-line config: ['-vU', '--no-config', '--', 'http://bj.afreecatv.com/ryuryu24/vods/user']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.15.3-arch1-1-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [afreecatv:user] Extracting URL: http://bj.afreecatv.com/ryuryu24/vods/user
[download] Downloading playlist: ryuryu24 - user
[afreecatv:user] ryuryu24: Downloading user video page 1
ERROR: Unable to download JSON metadata: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)> (caused by URLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_
ssl.c:997)')))
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wlritchi/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 767, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/wlritchi/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3601, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/wlritchi/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/utils.py", line 1543, in https_open
    return self.do_open(functools.partial(
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)>

[afreecatv:user] playlist ryuryu24 - user: Downloading 0 videos
[download] Finished downloading playlist: ryuryu24 - user
```
</details>

Troubleshooting (OpenSSL)
-------------------------------------

I took a look at the TLS ciphers available on the relevant host, and it is [a bit of a weird mix](https://www.ssllabs.com/ssltest/analyze.html?d=bjapi.afreecatv.com). Every supported cipher is marked as weak, and I think none of them support forward secrecy. That's an interesting observation given [this note in the Python docs suggesting that the default ciphers require forward secrecy since 3.10](https://docs.python.org/3/library/ssl.html#ssl.SSLContext).

I tried having OpenSSL connect directly, and this worked:
<details>
<summary>OpenSSL</summary>

```
$ openssl s_client -connect bjapi.afreecatv.com:443
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = Thawte RSA CA 2018
verify return:1
depth=0 C = KR, ST = Gyeonggi-do, L = Seongnam-si, O = "AfreecaTV co., Ltd", CN = *.afreecatv.com
verify return:1
---
Certificate chain
 0 s:C = KR, ST = Gyeonggi-do, L = Seongnam-si, O = "AfreecaTV co., Ltd", CN = *.afreecatv.com
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = Thawte RSA CA 2018
 1 s:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = Thawte RSA CA 2018
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
 2 s:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGczCCBVugAwIBAgIQCY8iOkHdLZBS1Ur4vot/RDANBgkqhkiG9w0BAQsFADBc
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMRswGQYDVQQDExJUaGF3dGUgUlNBIENBIDIwMTgwHhcN
MjEwNTI4MDAwMDAwWhcNMjIwNjI2MjM1OTU5WjBwMQswCQYDVQQGEwJLUjEUMBIG
A1UECBMLR3llb25nZ2ktZG8xFDASBgNVBAcTC1Nlb25nbmFtLXNpMRswGQYDVQQK
ExJBZnJlZWNhVFYgY28uLCBMdGQxGDAWBgNVBAMMDyouYWZyZWVjYXR2LmNvbTCC
ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANRbT8QX0pbs49MXriKA4wmj
QvWgaF4HxqaOP11ooQDSmAKrV0PIe5O10J2dPEKo7XldGCUPu+Zu/iR1c/MBAXe0
fbMaGDvIIYEWtnjDFlcbJQmBS+rETbQl4EXALYl20lGL4Mhxc3PCl4kO0KuAr69+
98abOwCq7KatpiSlYCWbOVvD/QX4uqKoHv1kyifH4YZrO37+h25ny2xWGBm2p9ri
u4GwoErj9Nyy0rXOI2UmZYJwwf4CXIXQxNFqEunacN8TfMSyEaJilxJoB3V7yqhW
LEQF2b3INbyKLdNG7VTzUYmnUNDZ+Z64ZBnSb/yWJgYQkKq/v372jK0OW0k+SsMC
AwEAAaOCAxswggMXMB8GA1UdIwQYMBaAFKPIXmVU5TB4wQXqBwpqWcy5/t5aMB0G
A1UdDgQWBBS134wyaJDmF1/xJmZq+sREFrK89TApBgNVHREEIjAggg8qLmFmcmVl
Y2F0di5jb22CDWFmcmVlY2F0di5jb20wDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQW
MBQGCCsGAQUFBwMBBggrBgEFBQcDAjA6BgNVHR8EMzAxMC+gLaArhilodHRwOi8v
Y2RwLnRoYXd0ZS5jb20vVGhhd3RlUlNBQ0EyMDE4LmNybDA+BgNVHSAENzA1MDMG
BmeBDAECAjApMCcGCCsGAQUFBwIBFhtodHRwOi8vd3d3LmRpZ2ljZXJ0LmNvbS9D
UFMwbwYIKwYBBQUHAQEEYzBhMCQGCCsGAQUFBzABhhhodHRwOi8vc3RhdHVzLnRo
YXd0ZS5jb20wOQYIKwYBBQUHMAKGLWh0dHA6Ly9jYWNlcnRzLnRoYXd0ZS5jb20v
VGhhd3RlUlNBQ0EyMDE4LmNydDAMBgNVHRMBAf8EAjAAMIIBfgYKKwYBBAHWeQIE
AgSCAW4EggFqAWgAdQApeb7wnjk5IfBWc59jpXflvld9nGAK+PlNXSZcJV3HhAAA
AXmwsZxPAAAEAwBGMEQCIBZiePfDQipx7IhEE2M5JgeKRIIriYmvuNBXxL2Awc01
AiB557m9yQnfj/7BUrA3KGoQu1fffuT2PN6T6VfqEFRM2gB2ACJFRQdZVSRWlj+h
L/H3bYbgIyZjrcBLf13Gg1xu4g8CAAABebCxnGsAAAQDAEcwRQIhAPL9pu3KG7ha
m/UwlPptBvuDbCIYk6ekUpAI96UfHK8nAiAyik40VS+VrzLHaY5BvSsqlZ4PHisF
rNYazL10HU3MvQB3AFGjsPX9AXmcVm24N3iPDKR6zBsny/eeiEKaDf7UiwXlAAAB
ebCxnJUAAAQDAEgwRgIhANPgpQoN/tGX9ZArNuhbFKyD/ABIqgvwQOBUvyzJE399
AiEAxzuFXybDt5fimjU0s2Q9KTE8qtH7RqpAaQJJDrAMUiwwDQYJKoZIhvcNAQEL
BQADggEBAGCxvSUBcdE+45xH7TkvpHkQzDLEbAPsfbCgnR7IO+odp3h+2vjL4Rny
WapHGRKj7+IiidONVlsAuB1BuNl9KS8mbdYisX/Fkdvma8XbfZ0zOPNmZkHcZ3PW
vKQRd7Jr7CWt0YLWiYI++7e9347W+zBTbWSJeKNaY8cMBR9NhCSAmrXp/FyUfEY4
UP0UKb3BRorfgYYK9Y2xKcM+qbizWyZI3DXEWZbbEF4gHxR29YmcUn+mbxi6/t5k
T9q9v/VMKq86HlAwS3sfBVJ0sRFqcOL+2jyCnMF/798QUSL05IDQTtlQ3mOFIr1+
VOwfzTA2UGXi7Ec9YDAGxd8xnpq8Fhk=
-----END CERTIFICATE-----
subject=C = KR, ST = Gyeonggi-do, L = Seongnam-si, O = "AfreecaTV co., Ltd", CN = *.afreecatv.com

issuer=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = Thawte RSA CA 2018

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 4503 bytes and written 471 bytes
Verification: OK
---
New, TLSv1.0, Cipher is ECDHE-RSA-AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA
    Session-ID: 13888370D84E5B39EAF4037E589237CC11A3A306B3DDA7B0F4514D9C4D0A53A7
    Session-ID-ctx:
    Master-Key: 1F1ED56186F7862591086D858735C2C9CB4E620596C0A7726F53742C4ABC0F70F764F2823D84F374A24C7E3F017DA9C9
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 43 38 41 e1 6c 68 98 cf-68 05 98 0d 82 c6 ba ef   C8A.lh..h.......
    0010 - 59 5a d5 3b 8d 69 2c 42-ee 1d de c9 c4 5f bc 44   YZ.;.i,B....._.D
    0020 - c0 cf a7 54 74 c8 da dd-61 e1 dc ea a8 cb 43 a5   ...Tt...a.....C.
    0030 - 54 05 0d 85 19 fa 53 4e-8b 94 e9 1a ef e0 c6 cb   T.....SN........
    0040 - 01 8f 8e d8 fc f1 33 a4-26 93 b9 86 b1 9a b3 00   ......3.&.......
    0050 - 7d c8 ad bc e9 e4 29 21-68 b2 5f c1 60 f2 c1 83   }.....)!h._.`...
    0060 - 7e 02 1d e8 a3 e7 c7 c5-3e 7b bb c6 67 7e ae c9   ~.......>{..g~..
    0070 - 0a 8c 9f f8 c1 ea 11 1a-49 8f b1 b6 85 28 12 fe   ........I....(..
    0080 - b3 e4 bb 55 c8 75 48 99-ff 1b 20 7c ad ee 8c 6e   ...U.uH... |...n
    0090 - 0b 46 75 d4 ef 7b de 97-df 4f 88 84 05 df 06 5e   .Fu..{...O.....^
    00a0 - ae 42 46 05 1b f3 90 f7-ae 6d 46 27 56 9f 6c 5d   .BF......mF'V.l]
    00b0 - 30 f3 d6 54 ab dd 1f 38-d6 40 1d e2 df 52 55 24   0..T...8.@...RU$
    00c0 - 69 fc 11 e4 2e 54 ba 84-7c 7b 1a 1c 73 35 91 06   i....T..|{..s5..

    Start Time: 1651918837
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
closed
```
</details>

Troubleshooting (Python)
---------------------------------

In a Python shell from the same venv that `yt_dlp` is running from, I tried setting up an SSL context manually and connecting, and it gave the same error as `yt_dlp` got. Some StackOverflow posts about similar error messages suggested trying to force the target TLS version and cipher suite to a known working one, but I couldn't get anywhere with that approach (I may have done it wrong, though).

<details>
<summary>Python shell</summary>

```
>>> import ssl
>>> import socket
>>> ctx = ssl.create_default_context()
>>> ctx.load_default_certs()
>>> ctx.wrap_socket(socket.socket(socket.AF_INET), server_hostname='bjapi.afreecatv.com').connect(('bjapi.afreecatv.com', 443))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/ssl.py", line 1374, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.10/ssl.py", line 1365, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)
>>>
>>>
>>> ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2, ciphers="ECDHE_RSA_AES256_SHA")
>>> ctx.load_default_certs()
>>> ctx.wrap_socket(socket.socket(socket.AF_INET), server_hostname='bjapi.afreecatv.com').connect(('bjapi.afreecatv.com', 443))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/ssl.py", line 1374, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.10/ssl.py", line 1365, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)
```
</details>

Since `yt_dlp` uses `http.client`, which uses `urllib.request`, which uses `ssl`, we get the same behaviour trying to make the request with any of these.

As an experiment, I installed `requests` into the venv, and tried to get the page with `requests.get(...)`. That worked fine, so apparently `requests` (which uses `urllib3`) is doing something differently than `ssl`.

For context on the scope of available solutions, have we ever considered switching to another library like `urllib3` or `requests`?

**Comment by pukkandan** [comment] 2022-05-07 12:27
> For context on the scope of available solutions, have we ever considered switching to another library like urllib3 or requests?

See #2861 #2862 #3668. But this is a big project (with lots of potential for serious regression) and so will likely take months (if not more than an year) to get anywhere

**Closed** 2022-05-07 13:11 UTC
Labels: help wanted, external issue

**Comment by pukkandan** [comment] 2022-05-07 13:14
@wlritchi Thanks for pointing me in the right direction. I have implemented a fix when using the `--legacy-server-connect` option. I don't think we should enable this fix globally by default. Ideally, there should be a way for the extractor to enable this without the user having to pass the option. But since our context is shared with the whole program, implementing this would be quite difficult
