### ISSUE TITLE
No longer support for Postprocessing Arg FFmpeg -ar

### ISSUE THREAD

**Issue by LittleMiho** [yt-dlp/yt-dlp#2113] opened 2021-12-25 04:52 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.25**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Description

It is no longer possible to change the sample frequency with FFmpeg postprocessing arg -ar
Works great til version from 01.12.2021. I used this feature when I download the audio part from a video to change the sample frequency from 48.000 to audio standard 44100.
Now I get a error message: Postprocessing: audio conversion failed: Option sample_rate not found.

### Verbose log

```shell
is really not needed
```

**Comment by pukkandan** [comment] 2021-12-25 04:53
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2112

**Comment by pukkandan** [comment] 2021-12-25 04:53
> is really not needed

IT REALLY IS!

**Closed by pukkandan** 2021-12-25 04:53 UTC
Labels: duplicate, incomplete
