### ISSUE TITLE
"FutureWarning: Possible nested set" not treated as warning

### ISSUE THREAD

**Issue by Skydef** [yt-dlp/yt-dlp#5795] opened 2022-12-13 11:04 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Related to: https://github.com/yt-dlp/yt-dlp/issues/5749
The FutureWarning from jsinterp.py is not treated as a warning. It is printed when `--no-warnings` parameter is given and it's printed to stderr.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
>yt-dlp -vU --no-warnings --skip-download -- jzRrUPQgrpc
[debug] Command-line config: ['-vU', '--no-warnings', '--skip-download', '--', 'jzRrUPQgrpc']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube] Extracting URL: jzRrUPQgrpc
[youtube] jzRrUPQgrpc: Downloading webpage
[youtube] jzRrUPQgrpc: Downloading android player API JSON
[debug] Loading youtube-nsig.e96685ea from cache
yt_dlp\jsinterp.py:346: FutureWarning: Possible nested set at position 1
[debug] [youtube] Decrypted nsig tUD2xVWMYRhcAXPrz => tOO7XgR6I0kELg
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] jzRrUPQgrpc: Downloading 1 format(s): 315+251

>yt-dlp --no-warnings --skip-download -- jzRrUPQgrpc 2>&1 1>nul
yt_dlp\jsinterp.py:346: FutureWarning: Possible nested set at position 1
```

**Comment by bashonly** [comment] 2022-12-13 12:41
This warning is coming directly from the Python interpreter instead of yt-dlp, so it cannot be suppressed by `--no-warnings`. See #5749 for more information

The cause of this warning was fixed in b44cd29851fdc2fadb283adb59a074f89a27ba7e. You could wait for the next release, use the master branch or try the [unofficial daily builds](https://github.com/ytdl-patched/yt-dlp)

Closing as duplicate

**Closed by bashonly** 2022-12-13 12:41 UTC
Labels: bug, triage
