### ISSUE TITLE
Stage +

### ISSUE THREAD

**Issue by nellie232** [yt-dlp/yt-dlp#7570] opened 2023-07-12 04:07 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

All

### Example URLs

- https://www.stage-plus.com/video/vod_concert_APNM8GRFDPHMASJKBSPJ6CO?player=true&trackId=performance_work_A1IN4PJFE9MM2RJ3CLBMUSJBBSOJ8C9J&t=67
- https://www.stage-plus.com/video/vod_concert_APNM8GRFDPHMASJKBSPJ6CO?player=true&trackId=performance_work_A1IN4PJFE9MM2RJ3CLBMUSJBBSOJ8C9K&t=0
- https://www.stage-plus.com/video/vod_concert_APNM8GRFDPHMASJKBSPJ6CO?player=true&trackId=performance_work_A1IN4PJFE9MM2RJ3CLBMUSJBBSOJEC9J&t=0
- https://www.stage-plus.com/video/vod_concert_APNM8GRFDPHMASJKBSPJ6CO?player=true&trackId=performance_work_A1IN4PJFE9MM2RJ3CLBMUSJBBSOJ8C9L&t=0
- https://www.stage-plus.com/video/vod_concert_APNM8GRFDPHMASJKBSPJ6CO?player=true&trackId=performance_work_A1IN4PJFE9MM2RJ3CLBMUSJBBSOJEC9K&t=0
- The program: https://www.stage-plus.com/video/vod_concert_APNM8GRFDPHMASJKBSPJ6CO

### Provide a description that is worded well enough to be understood

This is a registered-user-only site for concert videos, which means the extractor has to take account credentials or cookies. If needed, I can provide my username and password. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '<https://www.stage-plus.com/video/vod_concert_APNM8GRFDPHMASJKBSPJ6CO>']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-11.3.1-arm64-arm-64bit (OpenSSL 3.1.1 30 May 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: <https://www.stage-plus.com/video/vod_concert_APNM8GRFDPHMASJKBSPJ6CO>
ERROR: [generic] None: '<https://www.stage-plus.com/video/vod_concert_APNM8GRFDPHMASJKBSPJ6CO>' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:<https://www.stage-plus.com/video/vod_concert_APNM8GRFDPHMASJKBSPJ6CO>" ) to search YouTube
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.7.6/libexec/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2403, in _real_extract
    raise ExtractorError(
```

**Comment by bashonly** [comment] 2023-07-12 04:14
> `[debug] Command-line config: ['-vU', '<https://www.stage-plus.com/video/vod_concert_APNM8GRFDPHMASJKBSPJ6CO>']`

Support was added in e5265dc6517478e589ee3c1ff0cb19bdf4e35ce1

Remove the `<` and `>` from the beginning and end of the URL
Pass cookies or use `--username` / `--password`

Duplicate of #6806

**Closed by bashonly** 2023-07-12 04:14 UTC
Labels: site-request, triage
