### ISSUE TITLE
Tiktok user scraping

### ISSUE THREAD

**Issue by BasedDrainer** [yt-dlp/yt-dlp#7531] opened 2023-07-07 13:36 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Didn't find any mention of this in the bug reports.
Basically inputting a tiktok user link won't scrape the videos. Manually pasting in links seperated by a space works fine so downloading isn't the issue.
Is there any fix for this? Please help me out :)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe -vU -P C:\Users\User\Downloads\tiki\patrik https://www.tiktok.com/@patrikivan7/
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win32_dir)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user] Extracting URL: https://www.tiktok.com/@patrikivan7/
[tiktok:user] patrikivan7: Downloading webpage
[tiktok:user] patrikivan7: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] patrikivan7: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] patrikivan7: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] patrikivan7: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (1/3)...
[tiktok:user] patrikivan7: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] patrikivan7: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] patrikivan7: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] patrikivan7: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (2/3)...
[tiktok:user] patrikivan7: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] patrikivan7: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] patrikivan7: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] patrikivan7: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (3/3)...
[tiktok:user] patrikivan7: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] patrikivan7: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] patrikivan7: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] patrikivan7: Downloading user video list page 1
ERROR: [tiktok:user] patrikivan7: patrikivan7: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\tiktok.py", line 779, in _real_extract
  File "yt_dlp\utils\traversal.py", line 239, in traverse_obj
  File "yt_dlp\utils\traversal.py", line 227, in _traverse_obj
  File "yt_dlp\utils\traversal.py", line 215, in apply_path
  File "yt_dlp\utils\traversal.py", line 173, in apply_key
  File "yt_dlp\utils\_utils.py", line 2661, in __getitem__
  File "yt_dlp\extractor\tiktok.py", line 747, in _video_entries_api
  File "yt_dlp\utils\_utils.py", line 5634, in __iter__
  File "yt_dlp\extractor\common.py", line 3749, in _error_or_warning
  File "yt_dlp\utils\_utils.py", line 5642, in report_retry
  File "yt_dlp\extractor\tiktok.py", line 749, in _video_entries_api
  File "yt_dlp\extractor\tiktok.py", line 132, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 125, in _call_api
  File "yt_dlp\extractor\tiktok.py", line 62, in _call_api_impl
  File "yt_dlp\extractor\common.py", line 1064, in download_content
  File "yt_dlp\extractor\common.py", line 1034, in download_handle
  File "yt_dlp\extractor\common.py", line 1024, in parse
  File "yt_dlp\extractor\common.py", line 1011, in _parse_json
  File "yt_dlp\extractor\common.py", line 994, in __print_error

  File "yt_dlp\utils\_utils.py", line 624, in decode
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1008, in _parse_json
  File "json\__init__.py", line 370, in loads
  File "yt_dlp\utils\_utils.py", line 632, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by bashonly** [comment] 2023-07-07 13:55
Duplicate of #3776

you can try this plugin https://github.com/bashonly/yt-dlp-TTUser but it is reportedly somewhat broken

**Closed by bashonly** 2023-07-07 13:55 UTC
Labels: duplicate, site-bug, site:tiktok

**Comment by BasedDrainer** [comment] 2023-07-14 17:51
How can I use your fork? I'm on windows and a guide would be really helpful

**Comment by bashonly** [comment] 2023-07-15 16:45
@BasedDrainer
It's a yt-dlp plugin, not a fork, so you can use your current installation of yt-dlp with it.
1. install python if you don't have it installed already.
2. [install the required dependencies](https://github.com/bashonly/yt-dlp-TTUser#requirements)
3. [install the plugin](https://github.com/bashonly/yt-dlp-TTUser#installation)
