### ISSUE TITLE
Instagram Reels URL falls back to generic extractor

### ISSUE THREAD

**Issue by amir16yp** [yt-dlp/yt-dlp#9538] opened 2024-03-26 14:47 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Provide a description that is worded well enough to be understood

It seems like the regex for detecting an instagram reels URL is broken. I tried both on nightly and the current release (2024.03.10), both fall back to the generic extractor and fail.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\pc\Videos>yt-dlp --verbose https://www.instagram.com/reels/C49EgTpPR0P/
[debug] Command-line config: ['--verbose', 'https://www.instagram.com/reels/C49EgTpPR0P/']
[debug] Portable config "C:\Users\pc\scoop\apps\yt-dlp\current\yt-dlp.conf": []
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.03.22.232703 from yt-dlp/yt-dlp-nightly-builds [e5d4f1110] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1.1-full_build-www.gyan.dev (setts), ffprobe 6.1.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1807 extractors
[generic] Extracting URL: https://www.instagram.com/reels/C49EgTpPR0P/
[generic] C49EgTpPR0P: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] C49EgTpPR0P: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.instagram.com/reels/C49EgTpPR0P/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1605, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1740, in __extract_info
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\generic.py", line 2530, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.instagram.com/reels/C49EgTpPR0P/


C:\Users\pc\Videos>
```

**Comment by bashonly** [comment] 2024-03-26 14:49
Duplicate of #6689

workaround: change `/reels/` to `/reel/` in the URL

**Closed by bashonly** 2024-03-26 14:49 UTC
Labels: duplicate, site-bug, site:instagram
