### ISSUE TITLE
Adding an option to get an extractor credentials with a shell command

### ISSUE THREAD

**Issue by NDagestad** [yt-dlp/yt-dlp#6676] opened 2023-03-29 21:29 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Using a netrc file has some annoying drawbacks. First it keeps your passwords in a plain file. And seccond you'll need to keep it synchronised with your password manager if you have one.

Therefor I propose to introduce a way for the user to specify a command that can be run by yt-dlp to get the credential for an extractor.

An implementation can be found in my fork at https://github.com/ndagestad/yt-dlp 

For now I called the option `auth-command`, it takes a shell command that should return the password one one line and username on a second line.
`{target}` in the shell command will be replaced by the name of the extractor we want the credentials for.

E.g. for using the `pass` password manager:
```
yt-dlp --auth-command "pass ytldp/youtube" https://www.youtube.com/watch?v=BaW_jenozKc
```

Doing things this way is in my opinion much better than both of the current options
If this seems like a feature you'd want I can open a pull request so you can review how it is implemented and give feedback as to what you might want to change.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment] 2023-03-30 04:33
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1706

> An implementation can be found in my fork at [ndagestad/yt-dlp](https://github.com/ndagestad/yt-dlp)

The impl needs some changes but looks fine overall:
* switch name and output format aren't clear - maybe `--netrc-cmd` a suggested in above issue?
* Issue warnings if multiple of these options are passed. Currently there is no warning for netrc + username either, but seems like a good opportunity to add it.
* Use `utils.Popen.run`
* Use `%(extractor_key)s` like `--output` or just `{}` like `--exec`, not `{target}`

Will you be making a PR?

**Closed by pukkandan** 2023-03-30 04:33 UTC
Labels: enhancement, triage

**Comment by NDagestad** [comment] 2023-03-30 20:02
> Duplicate of #1706

My bad, I got a bit overwhelmed by the 70+ pages of issues I got when I searched for things related to the subject.
I should have tried the filters a bit more probably.

> * switch name and output format aren't clear - maybe `--netrc-cmd` as suggested in above issue?

`netrc-cmd` sounds good. What would want the output format to be ?
I thought that having the password and username each on their own line and nothing else would be the most practical. But since it's supposed to be a shell command, it can be used to format the output however we want anyway.

> * Issue warnings if multiple of these options are passed. Currently there is no warning for netrc + username either, but seems like a good opportunity to add it.

Sure while not, havent looked much at the argument parsing but I don't expect it to be to hard to add that

> * Use `utils.Popen.run`

Does `utils.Popen` run the command in a shell or support `shell=True` the same way `subprocess` does ?

> * Use `%(extractor_key)s` like `--output` or just `{}` like `--exec`, not `{target}`

I'll go for `{}`, it's quite common and easy to implement. That being said, `%(extractor_key)s` would be more versatile and consistent with other commands. If you prefer it I  could do the effort to do that instead.

> Will you be making a PR?

Yep, I'll open th PR when I've done the changes you requested 👍

**Comment by pukkandan** [comment] 2023-03-31 07:16
> > Duplicate of #1706
> 
> My bad, I got a bit overwhelmed by the 70+ pages of issues I got when I searched for things related to the subject. I should have tried the filters a bit more probably.

It's fine. I know it's sometimes difficult to find dupes unless you know what u are looking for.


> I thought that having the password and username each on their own line and nothing else would be the most practical. But since it's supposed to be a shell command, it can be used to format the output however we want anyway.

I was thinking we expect netrc format? So `--netrc-cmd "cat ~/.netrc"` will work and other commands can return multiple machines if needed without parsing extractor key.

> I'll go for `{}`, it's quite common and easy to implement. That being said, `%(extractor_key)s` would be more versatile and consistent with other commands. If you prefer it I could do the effort to do that instead.

`%(...)s` support can also be added in future if needed like we did for `--exec`. `{}` is fine for now. But should it be replaced with `ie_key()` or with `_NETRC_MACHINE`? I think the latter is better.
