### ISSUE TITLE
Incomplete live_chat subtitles from a past YouTube livestream.

### ISSUE THREAD

**Issue by Satougg4** [yt-dlp/yt-dlp#9463] opened 2024-03-15 21:25 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Attempting to download live_chat subtitles from a past YouTube livestream results in incomplete chat logs and a smaller file size than expected. The JSON file is larger during the download than it is upon completion. In this example, the file was about 150~ MB near completion and resulted in a 55~ MB file.

The command I used is:

`yt-dlp https://www.youtube.com/watch?v=A-h5fIN_Eco --skip-download --write-subs --sub-lang live_chat`

A possible fix might be to restore or combine all downloaded fragments. I don't know where the fragments are downloaded to, but it seems they might not be stored in the file's output directory during the download.

A solution would show the finished download size to be consistent with the in-progress size.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=A-h5fIN_Eco', '--skip-download', '--write-subs', '--sub-lang', 'live_chat']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (pip)
[debug] Python 3.11.7 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg 5.0-full_build-www.gyan.dev (setts), ffprobe 5.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.43.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=A-h5fIN_Eco
[youtube] A-h5fIN_Eco: Downloading webpage
[youtube] A-h5fIN_Eco: Downloading ios player API JSON
[youtube] A-h5fIN_Eco: Downloading android player API JSON
[debug] [youtube] Extracting signature function js_d552837c_107
[youtube] A-h5fIN_Eco: Downloading player d552837c
[debug] Saving youtube-sigfuncs.js_d552837c_107 to cache
[debug] Loading youtube-nsig.d552837c from cache
[debug] [youtube] Decrypted nsig nAx9l_CoD4lL-s6j4H => yWZlmhIauoETZw
[youtube] A-h5fIN_Eco: Downloading m3u8 information
[info] A-h5fIN_Eco: Downloading subtitles: live_chat
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] A-h5fIN_Eco: Downloading 1 format(s): 308+251
[info] Writing video subtitles to: 🔴LIVE - DR DISRESPECT - HELLDIVERS 2 - ALONE IN HELL [A-h5fIN_Eco].live_chat.json
[debug] Invoking youtube_live_chat downloader on "https://www.youtube.com/watch?v=A-h5fIN_Eco&bpctr=9999999999&has_verified=1"
[youtube_live_chat] Downloading live chat
[youtube_live_chat] Total fragments: unknown (live)
[download] Destination: 🔴LIVE - DR DISRESPECT - HELLDIVERS 2 - ALONE IN HELL [A-h5fIN_Eco].live_chat.json
[debug] File locking is not supported. Proceeding without locking
[download] 100% of   55.69MiB in 00:07:17 at 130.48KiB/s
```

**Comment by bashonly** [comment] 2024-03-16 18:53
> incomplete chat logs and a smaller file size than expected

Do you know for sure that there are messages missing? Or is this an assumption based on the filesize comparison?

**Comment by Satougg4** [comment] 2024-03-16 20:14
I know this for sure. My best guess is that maybe the top messages are included (from YouTube's chat filter) rather than all messages.

**Comment by pukkandan** [comment] 2024-05-18 21:51
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/9943 (I know this was opened first, but that issue has more details. So closing this instead)

**Closed by pukkandan** 2024-05-18 21:51 UTC
Labels: site-bug, triage
