### ISSUE TITLE
[RUTUBE] ERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Fred-Vatin** [yt-dlp/yt-dlp#11768] opened 2024-12-08 18:47 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

Tring to download this video https://rutube.ru/video/0bb480824aa4a573f2c6aa9aa2040bb1/ with this command:
```
yt-dlp -vU -f "bestvideo[vcodec^=avc1]+bestaudio[ext=m4a]/best" --merge-output-format mp4 -o "E:/OneDrive/yt-dlp/%(uploader)s - %(title)s.%(ext)s" "https://rutube.ru/video/0bb480824aa4a573f2c6aa9aa2040bb1/"
```

Possibly related to #7064 and #8433 (DRM issue).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'bestvideo[vcodec^=avc1]+bestaudio[ext=m4a]/best', '--merge-output-format', 'mp4', '-o', 'E:/OneDrive/Téléchargements/yt-dlp/%(uploader)s - %(title)s.%(ext)s', 'https://rutube.ru/video/0bb480824aa4a573f2c6aa9aa2040bb1/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.06 from yt-dlp/yt-dlp [4bd265539] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.1-full_build-www.gyan.dev (setts), ffprobe 7.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.06 from yt-dlp/yt-dlp)
[rutube] Extracting URL: https://rutube.ru/video/0bb480824aa4a573f2c6aa9aa2040bb1/
[rutube] 0bb480824aa4a573f2c6aa9aa2040bb1: Downloading video JSON
[rutube] 0bb480824aa4a573f2c6aa9aa2040bb1: Downloading options JSON
[rutube] 0bb480824aa4a573f2c6aa9aa2040bb1: Downloading m3u8 information
[rutube] 0bb480824aa4a573f2c6aa9aa2040bb1: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 0bb480824aa4a573f2c6aa9aa2040bb1: Downloading 1 format(s): m3u8-5555-1
[debug] Invoking hlsnative downloader on "https://river-1.rutube.ru/hls-vod/yF3DlCNbyk45aIFPG7LBiw/1734288111/2476/0x5000c500e8827278/7be8ef1317d048a494c4f3ce874fe037.mp4.m3u8?i=1920x864_5555"
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3479, in process_info
  File "yt_dlp\YoutubeDL.py", line 3199, in dl
  File "yt_dlp\downloader\common.py", line 464, in download
  File "yt_dlp\downloader\hls.py", line 77, in real_download
  File "yt_dlp\YoutubeDL.py", line 4162, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 365, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment] 2024-12-08 18:57
Can't reproduce the issue. Closing since the link is not legitimate

**Closed by bashonly** 2024-12-08 18:57 UTC
Labels: site-bug, triage

**Comment by bashonly** [comment] 2024-12-08 18:59
Do not open another issue with an illegitimate link or you will be blocked from the repository
