### ISSUE TITLE
Cannot parse data facebook

### ISSUE THREAD

**Issue by wankio** [yt-dlp/yt-dlp#4477] opened 2022-07-28 18:47 UTC
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

https://www.facebook.com/groups/439702346672583/posts/1057389978237147/ or https://www.facebook.com/marcelino.flores.9887117/videos/1182954855629253
and 
https://www.facebook.com/groups/439702346672583/posts/1042846249691520/ or https://www.facebook.com/100072432424064/videos/576188904076728

i checked my cookies and nothing wrong about it, so i test with public fanpage 
https://www.facebook.com/watch/?v=593133995742684
still have same error

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\GEN32UC>yt-dlp https://www.facebook.com/100072432424064/videos/576188904076728 --verbose
[debug] Command-line config: ['https://www.facebook.com/100072432424064/videos/576188904076728', '--verbose']
[debug] User config "C:\Users\GEN32UC\AppData\Roaming\yt-dlp\config.txt": ['-o', 'I:/youtube-dl/%(extractor)s/%(title)s-%(uploader)s-%(channel_id)s-%(channel)s-%(id)s.%(ext)s', '-f', 'bestvideo[height<=?1080]+bestaudio/best', '--write-thumbnail', '--cookies', 'C:/Users/GEN32UC/AppData/Roaming/youtube-dl/cookies.txt', '--write-sub', '--write-auto-sub', '--sub-lang', 'en-GB']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0-4-g911d7f167c-20220219 (setts), ffprobe n5.0-4-g911d7f167c-20220219
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2020.04.05.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.0
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/100072432424064/videos/576188904076728
[facebook] 576188904076728: Downloading webpage
[facebook] 576188904076728: Downloading webpage
ERROR: [facebook] 576188904076728: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\extractor\common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\extractor\facebook.py", line 713, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\extractor\facebook.py", line 659, in _extract_from_url
    raise ExtractorError('Cannot parse data')
```

**Comment by maximmai** [comment] 2022-07-29 07:53
I was able to reproduce with the link in the log, but unable to reproduce with the public fanpage, with the latest code from master

It seems that we currently don't have logic to get the `video_data` and need to enhance the Facebook extractor to support this webpage, and extract the `video_data`.


![image](https://user-images.githubusercontent.com/506983/181711437-0fe55c4e-f809-4101-b162-884d96e1cd81.png)

![image](https://user-images.githubusercontent.com/506983/181711684-cac59b9c-26e6-42e1-9a9f-cd6808a6ddc3.png)

**Comment by wizoomer95** [comment] 2022-08-01 02:24
Really quick, I just wanted to say that I got this error, too with yt-dlp.  It was a video for a private Facebook group, and I have 2-step verification turned on my account, which further complicated things.  However, using the original youtube-dl program and cookies exported from Chrome, I could download the same video that resulted in this error on yt-dlp.  Here's the verbose log from youtube-dl, if this helps developers:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--cookies', '/Users/ricorobbins/Downloads/facebook.com_cookies.txt', '-f', '532500871983715v+1105145563727593a', 'https://www.facebook.com/rico.robbins.3/videos/394691086101184', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 0b030b74e
[debug] Python version 3.10.5 (CPython) - macOS-12.3-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.0.1, ffprobe 5.0.1
[debug] Proxy map: {}
[facebook] 394691086101184: Downloading webpage
[facebook] 394691086101184: Downloading webpage
[debug] Invoking downloader on 'https://video-msp1-1.xx.fbcdn.net/v/t39.25447-2/296164434_413742270559445_4176151265288212920_n.mp4?_nc_cat=102&ccb=1-7&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfcjJfYXZjX2dlbjFhdmNfbGNfcTkwX2ZyYWdfMl92aWRlbyJ9&_nc_ohc=OE4HUfzoGqsAX8r1XrI&_nc_ht=video-msp1-1.xx&oh=00_AT_f3e0PJWOBhfETdoVMAB3SCinpIux1RWsXfTRjRsbFJQ&oe=62EB46A7'
[download] Destination: Happy 22nd anniversary to Thomas and the Magic Railroad to all my fellow US T...-394691086101184.f532500871983715v.mp4
[download] 100% of 41.58MiB in 00:02
[debug] Invoking downloader on 'https://video-msp1-1.xx.fbcdn.net/v/t42.1790-2/295893333_467725188052763_4619451105377307953_n.mp4?_nc_cat=107&ccb=1-7&_nc_sid=5aebc0&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfYXVkaW9fYWFjcF82NF9mcmFnXzJfYXVkaW8ifQ==&_nc_ohc=fVgyOshbB5wAX-FdQ60&_nc_ht=video-msp1-1.xx&oh=00_AT-nAVxklE8Ogh4-z9QESeHbSj9DmwvzAVgpKZSXNyB9cQ&oe=62E75761'
[download] Destination: Happy 22nd anniversary to Thomas and the Magic Railroad to all my fellow US T...-394691086101184.f1105145563727593a.m4a
[download] 100% of 1.05MiB in 00:00
[ffmpeg] Merging formats into "Happy 22nd anniversary to Thomas and the Magic Railroad to all my fellow US T...-394691086101184.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Happy 22nd anniversary to Thomas and the Magic Railroad to all my fellow US T...-394691086101184.f532500871983715v.mp4' -i 'file:Happy 22nd anniversary to Thomas and the Magic Railroad to all my fellow US T...-394691086101184.f1105145563727593a.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Happy 22nd anniversary to Thomas and the Magic Railroad to all my fellow US T...-394691086101184.temp.mp4'
Deleting original file Happy 22nd anniversary to Thomas and the Magic Railroad to all my fellow US T...-394691086101184.f532500871983715v.mp4 (pass -k to keep)
Deleting original file Happy 22nd anniversary to Thomas and the Magic Railroad to all my fellow US T...-394691086101184.f1105145563727593a.m4a (pass -k to keep)
```

**Comment by pukkandan** [comment] 2022-08-03 23:21
Duplicate of #4311

**Closed by pukkandan** 2022-08-03 23:21 UTC
Labels: duplicate, site-bug, regression, site:facebook

**Comment by ritcheyvs** [comment] 2022-08-09 21:42
Using GUI, when I try to download any video from facebook an "Analysis failed" message pops up.  When I click on that message it pops up a black box that says "Sorry, video analysis failed!  Reason: [facebook] 823654602373488: Cannot parse data; please report this issue on github...
Facebook downloads worked fine until about 10 days ago. I installed a Streamfab update just before this problem began.  Coincidence?  I don't have the first clue about how to get to the log file.  I just expect Streamfab to work and it doesn't.

**Comment by ritcheyvs** [comment] 2022-08-09 21:44
This is a poor and unsatisfactory way to report problems with such a pricy product.

**Comment by pukkandan** [comment] 2022-08-10 01:15
@ritcheyvs I think you are on the wrong repo. yt-dlp has no GUI and definitely is not a paid product

**Comment by ritcheyvs** [comment] 2022-08-28 16:39
I am using a paid (like $300) product called Streamfab, which apparently includes something named yt-dlp.  About a month ago, downloads from YouTube stopped working and the error message directed me to your site.  I found that surprising because you are a development community, apparently not affiliated with Streamfab.  My complaint is with Streamfab, not the github community but this is where the error message lead me.  There have been two Streamfab updates since I posted but the problem remains.  Sorry to be a nuisance here.  
I'll include the log below, which may explain how I ended up here.
[parse error.txt](https://github.com/yt-dlp/yt-dlp/files/9440071/parse.error.txt)

**Comment by dmn001** [comment] 2022-08-28 16:53
> I am using a paid (like $300) product called Streamfab

yt-dlp (and youtube-dl) is a free and open source project. If you paid money for Streamfab you should ask for a refund, as you can do all of what it advertises and more for FREE by just using yt-dlp. Streamfab is 100% a scam as it sells paid versions of software that is just repackaged free software. The error message is one that yt-dlp outputs. There is absolutely no affiliation with the two pieces of software, you have been duped.

**Comment by dmn001** [comment] 2022-08-28 16:53
> I am using a paid (like $300) product called Streamfab

yt-dlp (and youtube-dl) is a free and open source project. If you paid money for Streamfab you should ask for a refund, as you can do all of what it advertises and more for FREE by just using yt-dlp. Streamfab is 100% a scam as it sells paid versions of software that is just repackaged free software. The error message is one that yt-dlp outputs. There is absolutely no affiliation with the two pieces of software, you have been duped.

**Comment by ritcheyvs** [comment] 2022-08-28 17:54
Dave, Thank you so much for your reply.  I also have a (much cheaper) paid program called 4K Video Downloader that still works fine with YouTube.  The full version of Streamfab downloads from dozens of other sites, like Amazon, Hulu, YouTube, Netflix, etc. so it’s not a total loss; I am just irritated that the YouTube interface quit working and Streamfab is slow to fix it.  My coding days were back in the 70s and 80s so I mostly use GUIs these days.  Thanks again for setting me straight.  Scott
