### ISSUE TITLE
[crunchyroll] playlist: Unable to extract initial state

### ISSUE THREAD

**Issue by Puuma** [yt-dlp/yt-dlp#7988] opened 2023-08-29 22:48 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Finland

### Provide a description that is worded well enough to be understood

Crunchyroll get playlist fails on every show. Can reproduce every time. Same error every time.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --flat-playlist --print urls 'https://www.crunchyroll.com/series/GR49G9VP6/sword-art-online'
[debug] Command-line config: ['-vU', '--flat-playlist', '--print', 'urls', 'https://www.crunchyroll.com/series/GR49G9VP6/sword-art-online']
[debug] User config "/home/puma/.config/yt-dlp/config": ['--no-part', '--mark-watched']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (debian*)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-7-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 6.0-6 (setts), ffprobe 6.0-6
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[crunchyroll:playlist] Extracting URL: https://www.crunchyroll.com/series/GR49G9VP6/sword-art-online
[crunchyroll:playlist] Retrieving main page (lang=None)
ERROR: [crunchyroll:playlist] GR49G9VP6: Unable to extract initial state; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/crunchyroll.py", line 476, in _real_extract
    **traverse_obj(self._call_api(f'series/{internal_id}', internal_id, lang, 'series'), ('data', 0, {
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/crunchyroll.py", line 114, in _call_api
    result = self._call_base_api(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/crunchyroll.py", line 99, in _call_base_api
    self._update_query(lang)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/crunchyroll.py", line 72, in _update_query
    initial_state = self._search_json(r'__INITIAL_STATE__\s*=', webpage, 'initial state', None)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1272, in _search_json
    json_string = self._search_regex(
                  ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1258, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by Grub4K** [comment] 2023-08-29 22:51
Duplicate of #7624. Use `yt-dlp --update-to nightly` or [download the nightly binary](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases) if you cannot auto-update.

**Closed by Grub4K** 2023-08-29 22:51 UTC
Labels: site-bug, triage
