### ISSUE TITLE
DownloadError: ERROR: [vimeo] 942547573: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

### ISSUE THREAD

**Issue by SasaniP** [yt-dlp/yt-dlp#9932] opened 2024-05-16 09:46 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi, I am unable to download a password protected Vimeo video using yt-dlp. I am trying to download the video using the "format": "bestvideo+bestaudio", "format": "worstvideo+worstaudio" in yt_dlp_options.

Eg:
yt_dlp_options_best = {
                "format": "bestvideo+bestaudio",
                "referer": "https://vimeo.com",
                "external_downloader": "aria2c",
                "external_downloader_args": ["-x", "16", "-s", "16", "-k", "5M", "--max-concurrent-downloads=16"],
                "outtmpl": os.path.join(output_folder, "%(title)s (%(format_id)s).%(ext)s"),
                "writeinfojson": True,
                "quiet": True,
                "nooverwrites": True,
                "tempdir": tempfile.gettempdir(),
            }

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ERROR: [vimeo] 942547573: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
Error downloading in worst video https://vimeo.com/942547573
downloading in best video
ERROR: [vimeo] 942547573: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py in _request_webpage(self, url_or_request, video_id, note, errnote, fatal, data, headers, query, expected_status, impersonate, require_impersonation)
    889         try:
--> 890             return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
    891         except network_exceptions as err:

42 frames
/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in urlopen(self, req)
   4130         try:
-> 4131             return self._request_director.send(req)
   4132         except NoSupportingHandlers as e:

/usr/local/lib/python3.10/dist-packages/yt_dlp/networking/common.py in send(self, request)
    114             try:
--> 115                 response = handler.send(request)
    116             except RequestError:

/usr/local/lib/python3.10/dist-packages/yt_dlp/networking/_helper.py in wrapper(self, *args, **kwargs)
    207         try:
--> 208             return func(self, *args, **kwargs)
    209         except UnsupportedRequest as e:

/usr/local/lib/python3.10/dist-packages/yt_dlp/networking/common.py in send(self, request)
    334             raise TypeError('Expected an instance of Request')
--> 335         return self._send(request)
    336 

/usr/local/lib/python3.10/dist-packages/yt_dlp/networking/_requests.py in _send(self, request)
    349         if not 200 <= res.status < 300:
--> 350             raise HTTPError(res, redirect_loop=max_redirects_exceeded)
    351 

HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

ExtractorError                            Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in wrapper(self, *args, **kwargs)
   1605                 try:
-> 1606                     return func(self, *args, **kwargs)
   1607                 except (DownloadCancelled, LazyList.IndexError, PagedList.IndexError):

/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in __extract_info(self, url, ie, download, extra_info, process)
   1740         try:
-> 1741             ie_result = ie.extract(url)
   1742         except UserNotLive as e:

/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py in extract(self, url)
    733                         url if self.get_param('verbose') else truncate_string(url, 100, 20)))
--> 734                     ie_result = self._real_extract(url)
    735                     if ie_result is None:

/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/vimeo.py in _real_extract(self, url)
    890             if not page_config:
--> 891                 return self._extract_from_api(video_id)
    892             config_url = page_config['player']['config_url']

/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/vimeo.py in _extract_from_api(self, video_id, unlisted_hash)
    755             api_url += ':' + unlisted_hash
--> 756         video = self._download_json(
    757             api_url, video_id, headers={

/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py in download_content(self, url_or_request, video_id, note, errnote, transform_source, fatal, encoding, data, headers, query, expected_status, impersonate, require_impersonation)
   1126             # The method is fetched by name so subclasses can override _download_..._handle
-> 1127             res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
   1128             return res if res is False else res[0]

/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py in download_handle(self, url_or_request, video_id, note, errnote, transform_source, fatal, encoding, data, headers, query, expected_status, impersonate, require_impersonation)
   1086                             impersonate=None, require_impersonation=False):
-> 1087             res = self._download_webpage_handle(
   1088                 url_or_request, video_id, note=note, errnote=errnote, fatal=fatal, encoding=encoding,

/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py in _download_webpage_handle(self, url_or_request, video_id, note, errnote, fatal, encoding, data, headers, query, expected_status, impersonate, require_impersonation)
    953 
--> 954         urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
    955                                      headers=headers, query=query, expected_status=expected_status,

/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py in _request_webpage(self, url_or_request, video_id, note, errnote, fatal, data, headers, query, expected_status, impersonate, require_impersonation)
    902             if fatal:
--> 903                 raise ExtractorError(errmsg, cause=err)
    904             else:

ExtractorError: [vimeo] 942547573: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

During handling of the above exception, another exception occurred:

DownloadError                             Traceback (most recent call last)
<ipython-input-8-99d62dac52b4> in <cell line: 1>()
      1 try:
----> 2     ydl_worst.download([url])
      3 except yt_dlp.utils.DownloadError:

/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in download(self, url_list)
   3571         for url in url_list:
-> 3572             self.__download_wrapper(self.extract_info)(
   3573                 url, force_generic_extractor=self.params.get('force_generic_extractor', False))

/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in wrapper(*args, **kwargs)
   3546             try:
-> 3547                 res = func(*args, **kwargs)
   3548             except UnavailableVideoError as e:

/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in extract_info(self, url, download, ie_key, extra_info, process, force_generic_extractor)
   1594                 break
-> 1595             return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
   1596         else:

/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in wrapper(self, *args, **kwargs)
   1623                 except ExtractorError as e:  # An error we somewhat expected
-> 1624                     self.report_error(str(e), e.format_traceback())
   1625                 except Exception as e:

/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in report_error(self, message, *args, **kwargs)
   1072         '''
-> 1073         self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
   1074 

/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in trouble(self, message, tb, is_error)
   1011                 exc_info = sys.exc_info()
-> 1012             raise DownloadError(message, exc_info)
   1013         self._download_retcode = 1

DownloadError: ERROR: [vimeo] 942547573: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

During handling of the above exception, another exception occurred:

HTTPError                                 Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py in _request_webpage(self, url_or_request, video_id, note, errnote, fatal, data, headers, query, expected_status, impersonate, require_impersonation)
    889         try:
--> 890             return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
    891         except network_exceptions as err:

/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in urlopen(self, req)
   4130         try:
-> 4131             return self._request_director.send(req)
   4132         except NoSupportingHandlers as e:

/usr/local/lib/python3.10/dist-packages/yt_dlp/networking/common.py in send(self, request)
    114             try:
--> 115                 response = handler.send(request)
    116             except RequestError:

/usr/local/lib/python3.10/dist-packages/yt_dlp/networking/_helper.py in wrapper(self, *args, **kwargs)
    207         try:
--> 208             return func(self, *args, **kwargs)
    209         except UnsupportedRequest as e:

/usr/local/lib/python3.10/dist-packages/yt_dlp/networking/common.py in send(self, request)
    334             raise TypeError('Expected an instance of Request')
--> 335         return self._send(request)
    336 

/usr/local/lib/python3.10/dist-packages/yt_dlp/networking/_requests.py in _send(self, request)
    349         if not 200 <= res.status < 300:
--> 350             raise HTTPError(res, redirect_loop=max_redirects_exceeded)
    351 

HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

ExtractorError                            Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in wrapper(self, *args, **kwargs)
   1605                 try:
-> 1606                     return func(self, *args, **kwargs)
   1607                 except (DownloadCancelled, LazyList.IndexError, PagedList.IndexError):

/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in __extract_info(self, url, ie, download, extra_info, process)
   1740         try:
-> 1741             ie_result = ie.extract(url)
   1742         except UserNotLive as e:

/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py in extract(self, url)
    733                         url if self.get_param('verbose') else truncate_string(url, 100, 20)))
--> 734                     ie_result = self._real_extract(url)
    735                     if ie_result is None:

/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/vimeo.py in _real_extract(self, url)
    890             if not page_config:
--> 891                 return self._extract_from_api(video_id)
    892             config_url = page_config['player']['config_url']

/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/vimeo.py in _extract_from_api(self, video_id, unlisted_hash)
    755             api_url += ':' + unlisted_hash
--> 756         video = self._download_json(
    757             api_url, video_id, headers={

/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py in download_content(self, url_or_request, video_id, note, errnote, transform_source, fatal, encoding, data, headers, query, expected_status, impersonate, require_impersonation)
   1126             # The method is fetched by name so subclasses can override _download_..._handle
-> 1127             res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
   1128             return res if res is False else res[0]

/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py in download_handle(self, url_or_request, video_id, note, errnote, transform_source, fatal, encoding, data, headers, query, expected_status, impersonate, require_impersonation)
   1086                             impersonate=None, require_impersonation=False):
-> 1087             res = self._download_webpage_handle(
   1088                 url_or_request, video_id, note=note, errnote=errnote, fatal=fatal, encoding=encoding,

/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py in _download_webpage_handle(self, url_or_request, video_id, note, errnote, fatal, encoding, data, headers, query, expected_status, impersonate, require_impersonation)
    953 
--> 954         urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
    955                                      headers=headers, query=query, expected_status=expected_status,

/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py in _request_webpage(self, url_or_request, video_id, note, errnote, fatal, data, headers, query, expected_status, impersonate, require_impersonation)
    902             if fatal:
--> 903                 raise ExtractorError(errmsg, cause=err)
    904             else:

ExtractorError: [vimeo] 942547573: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

During handling of the above exception, another exception occurred:

DownloadError                             Traceback (most recent call last)
<ipython-input-8-99d62dac52b4> in <cell line: 1>()
      4     print(f"Error downloading in worst video {url}")
      5     print("downloading in best video")
----> 6     ydl_best.download([url])
      7 except Exception as e:
      8     print(f"Error downloading in best video {url}: {e}")

/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in download(self, url_list)
   3570 
   3571         for url in url_list:
-> 3572             self.__download_wrapper(self.extract_info)(
   3573                 url, force_generic_extractor=self.params.get('force_generic_extractor', False))
   3574 

/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in wrapper(*args, **kwargs)
   3545         def wrapper(*args, **kwargs):
   3546             try:
-> 3547                 res = func(*args, **kwargs)
   3548             except UnavailableVideoError as e:
   3549                 self.report_error(e)

/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in extract_info(self, url, download, ie_key, extra_info, process, force_generic_extractor)
   1593                     raise ExistingVideoReached()
   1594                 break
-> 1595             return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
   1596         else:
   1597             extractors_restricted = self.params.get('allowed_extractors') not in (None, ['default'])

/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in wrapper(self, *args, **kwargs)
   1622                     self.report_error(msg)
   1623                 except ExtractorError as e:  # An error we somewhat expected
-> 1624                     self.report_error(str(e), e.format_traceback())
   1625                 except Exception as e:
   1626                     if self.params.get('ignoreerrors'):

/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in report_error(self, message, *args, **kwargs)
   1071         in red if stderr is a tty file.
   1072         '''
-> 1073         self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
   1074 
   1075     def write_debug(self, message, only_once=False):

/usr/local/lib/python3.10/dist-packages/yt_dlp/YoutubeDL.py in trouble(self, message, tb, is_error)
   1010             else:
   1011                 exc_info = sys.exc_info()
-> 1012             raise DownloadError(message, exc_info)
   1013         self._download_retcode = 1
   1014 

DownloadError: ERROR: [vimeo] 942547573: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
```

**Comment by Oorha** [comment] 2024-05-16 13:18
Precisely the same issue, just simpler input on my end:

` yt-dlp "https://vimeo.com/link" --video-password "password"
[vimeo] Extracting URL: https://vimeo.com/913372337
[vimeo] 913372337: Downloading webpage
[vimeo] 913372337: Downloading JSON metadata
[vimeo] 913372337: Downloading JSON metadata
**ERROR: [vimeo] 913372337: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)**`

**Comment by bashonly** [comment] 2024-05-16 13:51
Duplicate of #6603

**Closed by bashonly** 2024-05-16 13:51 UTC
Labels: duplicate, incomplete, site-bug, site:vimeo
