### ISSUE TITLE
Site "AlphaPorno" returns error: Unable to extract video url

### ISSUE THREAD

**Issue by TVARecordings** [yt-dlp/yt-dlp#11267] opened 2024-10-16 19:06 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Netherlands, but i believe it's worldwide available.

### Provide a description that is worded well enough to be understood

Dear developers.

I unfortunately encountered a error when i tried to download videos from "Alphaporno.com", see the verbose output.
I have not tried this website in the past, so i do not know for how long this issue exists. However, no tickets we're made for this site in the past. 

Please understand this is my first time opening a ticket for yt-dlp.exe.
Although i've read the guidelines for opening a issue, pardon me if i have done anything incorrectly!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[20h58:23.125] DownloadVideo:  Downloading video with command: yt-dlp -f "bestvideo[height<=2160]+bestaudio/best" -vU --merge-output-format mp4 "https://www.alphaporno.com/videos/impressive-anal-pov-after-this-teen-sucks-the-dick-weyt/" -o E:/AmecaCore/media/youtube/temp_video_1729105100834.mp4

Error downloading video: Error: Command failed: yt-dlp -f "bestvideo[height<=2160]+bestaudio/best" -vU --merge-output-format mp4 "https://www.alphaporno.com/videos/impressive-anal-pov-after-this-teen-sucks-the-dick-weyt/" -o E:/AmecaCore/media/youtube/temp_video_1729105100834.mp4
[debug] Command-line config: ['-f', 'bestvideo[height<=2160]+bestaudio/best', '-vU', '--merge-output-format', 'mp4', 'https://www.alphaporno.com/videos/impressive-anal-pov-after-this-teen-sucks-the-dick-weyt/', '-o', 'E:/AmecaCore/media/youtube/temp_video_1729105100834.mp4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-06-21-git-d45e20c37b-full_build-www.gyan.dev (setts), ffprobe 2024-06-21-git-d45e20c37b-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: [AlphaPorno] impressive-anal-pov-after-this-teen-sucks-the-dick-weyt: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
File "yt_dlp\extractor\common.py", line 741, in extract
File "yt_dlp\extractor\alphaporno.py", line 39, in _real_extract
File "yt_dlp\extractor\common.py", line 1345, in _search_regex
```

**Comment by bashonly** [comment] 2024-10-16 19:15
Duplicate of #2702

**Closed by bashonly** 2024-10-16 19:15 UTC
Labels: NSFW, site-bug, triage
