### ISSUE TITLE
HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

### ISSUE THREAD

**Issue by somebadhat** [yt-dlp/yt-dlp#9402] opened 2024-03-09 14:06 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

I've used yt-tlp and it's variant for 20 years.

yesterday I wrote my first python script.
I installed / started using for the first time:
pillow, piexif,tqdm,pyinstaller, imagemagik,exiftool, and the java development kit.

today YT-dlp asked me to report this issue so I am.

the number and subject of videos I requested were returned and playable in VLC. `'verbose': True` does not work for me so I used `--verbose`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--verbose', '--restrict-filenames', '--download-archive', 'c:\\downloads\\DoNotDelete\\archive.txt', '-f', '18', '-o', '%(title)s.%(ext)s', '-i', 'ytsearch3:Dell laptop disassembly']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 3.4.1 (fdk), ffprobe 6.1.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Loading archive file 'c:\\downloads\\DoNotDelete\\archive.txt'
[youtube:search] Extracting URL: ytsearch3:Dell laptop disassembly
[download] Downloading playlist: Dell laptop disassembly
[youtube:search] query "Dell laptop disassembly": Downloading web client config
[youtube:search] query "Dell laptop disassembly" page 1: Downloading API JSON
[youtube:search] Playlist Dell laptop disassembly: Downloading 3 items of 3
[download] Downloading item 1 of 3
[youtube] Extracting URL: https://www.youtube.com/watch?v=AAqP9nxZa8I
[youtube] AAqP9nxZa8I: Downloading webpage
[youtube] AAqP9nxZa8I: Downloading ios player API JSON
[youtube] AAqP9nxZa8I: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] AAqP9nxZa8I: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] AAqP9nxZa8I: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] AAqP9nxZa8I: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig ZupuNOzcwyjXQFCn => ckexCB3Am-2Wcg
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig xB42rravqF3dF2Mc => 0rD5rdf00U5B_Q
[youtube] AAqP9nxZa8I: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] AAqP9nxZa8I: Downloading 1 format(s): 18
[debug] Invoking http downloader on "https://rr1---sn-vgqsknlk.googlevideo.com/videoplayback?expire=1710012624&ei=cGTsZesKlaTL-w_Bg4e4Bw&ip=97.84.131.30&id=o-AFVif07DHnB5Rl2Wzb3HwzoqP7UoP_soApP-QRXvkJ0k&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=N6&mm=31%2C29&mn=sn-vgqsknlk%2Csn-vgqsrn6z&ms=au%2Crdu&mv=m&mvi=1&pl=18&initcwndbps=1355000&spc=UWF9fxlIGDf6psR_g7sYyAd-0mDMowj4ln6unLEWJ65sNkU&vprv=1&svpuc=1&mime=video%2Fmp4&ns=a2_lv2UAhVp32OhP-7WxrDcQ&cnr=14&ratebypass=yes&dur=681.436&lmt=1664070034880842&mt=1709990726&fvip=2&fexp=24007246&beids=24350322&c=WEB&sefc=1&txp=5438434&n=ckexCB3Am-2Wcg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIgFrB41l0VH0O3oLe4fP0gKg9EOQ2QHvOlCm1QdPmeHdYCIQCM3b0nkez85kQVx7ok2FrMSjGMv94OoeSU4fFqX-P73Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=APTiJQcwRQIgbDWVVByrSXTtXZER4D87YRshPxl6PlHg4votS9t9yEgCIQD5--v5JM91rorq0JkzzhuPnJ5KnjUQFRKs_qS5FIzWSw%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: How_to_Disassembly_Assembly_Dell_Inspiron_15_3000_Series_SSD_Change_RAM_Change.mp4
[download] 100% of   21.76MiB in 00:00:07 at 3.03MiB/s
[debug] Adding to archive: youtube AAqP9nxZa8I
[download] Downloading item 2 of 3
[youtube] Extracting URL: https://www.youtube.com/watch?v=xlGGXzHJeVg
[youtube] xlGGXzHJeVg: Downloading webpage
[youtube] xlGGXzHJeVg: Downloading ios player API JSON
[youtube] xlGGXzHJeVg: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] xlGGXzHJeVg: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] xlGGXzHJeVg: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] xlGGXzHJeVg: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig B0YuLjNfxdtTKLlN => P_k9wzdzkXEtyg
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig 0XXKLRlU6s8L9wqd => We5AXrEvkPNsUw
[youtube] xlGGXzHJeVg: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] xlGGXzHJeVg: Downloading 1 format(s): 18
[debug] Invoking http downloader on "https://rr2---sn-vgqsknzs.googlevideo.com/videoplayback?expire=1710012638&ei=fmTsZZztGcXFy_sPiPmduA8&ip=97.84.131.30&id=o-AGiDuiLafcoK9C2Wdt9TFAfiTNtMAYc0UkAXBPm3yKFg&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=vq&mm=31%2C26&mn=sn-vgqsknzs%2Csn-q4fl6n6y&ms=au%2Conr&mv=m&mvi=2&pl=18&initcwndbps=1347500&spc=UWF9f4CNKEJ5WxOow7csy1g-DimhVldaJSxz_0PKlmITNcY&vprv=1&svpuc=1&mime=video%2Fmp4&ns=2O3js3kTgQ63TcT2HwOaPpMQ&cnr=14&ratebypass=yes&dur=350.110&lmt=1659756401081248&mt=1709990726&fvip=5&fexp=24007246&beids=24350322&c=WEB&sefc=1&txp=5318224&n=P_k9wzdzkXEtyg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRAIgfqLj8zkOQo1FpDaK2a5leC_ddCJr2uIPDCd94Xl023MCIDab8fR3WxrTgwB1Z_jcbB8j6d0DsL6WTBvGEZnF7Jvk&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=APTiJQcwRgIhALevwfC2CLs2VvqcB724SxY6m184YN-gBS7E2EBxp6eAAiEAhWYYH1VlRwUhi3jHXiAjwe2x7hm1roPWkND_paiYI2I%3D"
[download] Destination: Dell_Inspiron_15_3000_Series_Disassembly_WiFi_RAM_and_SSD_Upgrade.mp4
[download] 100% of   19.06MiB in 00:00:05 at 3.53MiB/s
[debug] Adding to archive: youtube xlGGXzHJeVg
[download] Downloading item 3 of 3
[youtube] Extracting URL: https://www.youtube.com/watch?v=Gfqha7lkTIA
[youtube] Gfqha7lkTIA: Downloading webpage
[youtube] Gfqha7lkTIA: Downloading ios player API JSON
[youtube] Gfqha7lkTIA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] Gfqha7lkTIA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] Gfqha7lkTIA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] Gfqha7lkTIA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig uLGuil8vWql-wtnC => 3c22i75ATt6bKg
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig h7zuxTinz1z9wWlC => BPvRi3j36Ut4Mg
[youtube] Gfqha7lkTIA: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Gfqha7lkTIA: Downloading 1 format(s): 18
[debug] Invoking http downloader on "https://rr2---sn-vgqsknse.googlevideo.com/videoplayback?expire=1710012650&ei=imTsZdmjFpuuj-8Pl6-uiAI&ip=97.84.131.30&id=o-AI03Z3o-cYpPL0_LbjIwPs6l_duGeTainqLIUAvIWO9-&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=My&mm=31%2C26&mn=sn-vgqsknse%2Csn-q4fl6nd6&ms=au%2Conr&mv=m&mvi=2&pl=18&initcwndbps=1347500&spc=UWF9f1Jc-gM2-WLuW2fagCvO32ewOySvSzK1vNYU3snYCPg&vprv=1&svpuc=1&mime=video%2Fmp4&ns=316M9UAw3AeFBejE1COda_wQ&gir=yes&clen=8916209&ratebypass=yes&dur=154.691&lmt=1704768497633498&mt=1709990726&fvip=2&fexp=24007246&beids=24350322&c=WEB&sefc=1&txp=5309224&n=3c22i75ATt6bKg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIgEtENGt0nEliJHCqGuLjrjy5NJZSptC6HFO8dtLLePtcCIQCROzF52DL3X8XzMJZNqXj18d3YPOxJuG2bhdpvUyYahg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=APTiJQcwRQIhAK9KVKChkzZV_7aTVEMdfB4imNcOCKlovJ3HKeoUF6ZrAiA215PdC1I63qf1pM6DqC3HzKaHqPgeEV8HkzgMSihZ9Q%3D%3D"
[download] Destination: Dell_Inspiron_15_5100_Disassembly_Upgrade_Options.mp4
[download] 100% of    8.50MiB in 00:00:02 at 3.27MiB/s
[debug] Adding to archive: youtube Gfqha7lkTIA
[download] Finished downloading playlist: Dell laptop disassembly

C:\Users\_9doug\Desktop\video>
```

**Comment by Twometer** [comment] 2024-03-09 14:16
I came here to post that same issue, but you were 8 minutes faster :)

Exact same error message for me

**Comment by seproDev** [comment] 2024-03-09 14:27
Duplicate of #9316

Update to nightly

if you are using the exe/zip:
```
yt-dlp --update-to nightly
```

or if you installed with pip:
```
python3 -m pip install -U --pre yt-dlp
```

**Closed by seproDev** 2024-03-09 14:27 UTC
Labels: site-bug, triage

**Comment by SteveLevesque** [comment] 2024-03-09 15:06
Got the same issue on Unraid's kmb32123 version. Even after update with pip to nightly, got the same error, but download perfectly.

**Comment by bashonly** [comment] 2024-03-09 15:15
@rich0 yes, soon
