### ISSUE TITLE
[youtube] Requested format is not available.

### ISSUE THREAD

**Issue by torfinli** [yt-dlp/yt-dlp#11783] opened 2024-12-10 16:48 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Provide a description that is worded well enough to be understood

I have a new YouTube account and I use its cookie to download YouTube videos, but it always reports this error. If I don't use cookies, it won't report the error. (my account can browse the YouTube website normally)
Later, I found out that after a period of time (about 12 hours), my machine could use cookies normally, but if my IP changed (I guess), it would report this error again. I am not using the latest version, I can reproduce this error using the latest version.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --no-progress --no-mtime --cookies cookies.txt  https://www.yout
ube.com/watch?v=syO5pPc-isg -vU
[debug] Command-line config: ['--no-progress', '--no-mtime', '--cookies', '/app/tmp/import/runtime/cookies.txt', 'https://www.youtube.com/watch?v=syO5pPc-isg', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.8.0-1015-gcp-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2024.11.18 from yt-dlp/yt-dlp
Latest version: stable@2024.12.06 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[youtube] Extracting URL: https://www.youtube.com/watch?v=syO5pPc-isg
[youtube] syO5pPc-isg: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] syO5pPc-isg: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] syO5pPc-isg: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] syO5pPc-isg: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] syO5pPc-isg: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
[youtube] syO5pPc-isg: Downloading mweb player API JSON
[youtube] syO5pPc-isg: Downloading player 3bb1f723
WARNING: [youtube] Falling back to generic n function search
         player = https://www.youtube.com/s/player/3bb1f723/player_ias.vflset/en_US/base.js
WARNING: [youtube] syO5pPc-isg: nsig extraction failed: Some formats may be missing
         n = deZEZ9RAgn4BATzPv0 ; player = https://www.youtube.com/s/player/3bb1f723/player_ias.vflset/en_US/base.js
[debug] [youtube] Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Falling back to generic n function search
         player = https://www.youtube.com/s/player/3bb1f723/player_ias.vflset/en_US/base.js
WARNING: [youtube] syO5pPc-isg: nsig extraction failed: Some formats may be missing
         n = jkxnzG01SsDV0Y21Bf ; player = https://www.youtube.com/s/player/3bb1f723/player_ias.vflset/en_US/base.js
WARNING: Only images are available for download. use --list-formats to see them
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
ERROR: [youtube] syO5pPc-isg: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/app/venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1624, in wrapper
    return func(self, *args, **kwargs)
  File "/app/venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1780, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/app/venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1839, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/app/venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2972, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] syO5pPc-isg: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment] 2024-12-10 18:46
> [debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (pip)

Your yt-dlp is out-of-date. Update

Duplicate of #11744 and #11640

**Closed by bashonly** 2024-12-10 18:46 UTC
Labels: duplicate, site-bug

**Comment by torfinli** [comment] 2024-12-11 02:50
> > [debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [[7ea2787](https://github.com/yt-dlp/yt-dlp/commit/7ea2787920cccc6b8ea30791993d114fbd564434)] (pip)
> 
> Your yt-dlp is out-of-date. Update
> 
> Duplicate of #11744 and #11640

Thanks a lot. It seems that the latest version has fixed the issues with 'bad request' and 'too few available formats'.
