### ISSUE TITLE
Feature Request: Support for downloading videos in multiple threads.

### ISSUE THREAD

**Issue by SONGjiemo** [yt-dlp/yt-dlp#2642] opened 2022-02-05 08:26 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

1. The download of some niche websites or large websites is between 400KB/S.
I hope to use multi-threading to download him. This is very important.
2. I hope you can play it while downloading, use the default player or choose the player.

**Comment by pukkandan** [comment] 2022-02-05 10:36
Duplicate of #1918

**Closed by pukkandan** 2022-02-05 10:36 UTC
Labels: enhancement, triage
