### ISSUE TITLE
NBC shows requiring authentication fail with HTTP 401 when using Comcast_SSO adobepass

### ISSUE THREAD

**Issue by pdisciascio** [yt-dlp/yt-dlp#5123] opened 2022-10-03 11:52 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States - Eastern Pennsylvania

### Provide a description that is worded well enough to be understood

NBC shows requiring authentication fail with HTTP 401 when using --ap-mso Comcast_SSO (Xfinity as linked provider)
Some example URLs that fail include:
https://www.nbc.com/the-real-housewives-of-beverly-hills/video/we-need-to-talk-about-kathy/9000249196
https://www.nbc.com/saturday-night-live/video/october-1-miles-teller/9000258299
https://www.nbc.com/below-deck-down-under/video/somethings-fishy/9000265442
https://www.nbc.com/dateline-unforgettable/video/under-the-desert-sky/9000256501

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
debug] Command-line config: ['-vU', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.nbc.com/dateline-unforgettable/video/under-the-desert-sky/9000256501']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (zip)
[debug] Python 3.10.4 (CPython 64bit) - Linux-5.15.0-46-lowlatency-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [NBC] Extracting URL: https://www.nbc.com/dateline-unforgettable/video/under-the-desert-sky/9000256501
[NBC] 9000256501: Downloading JSON metadata
[NBC] 9000256501: Downloading JSON metadata
[NBC] 9000256501: Downloading Provider Redirect Page
[NBC] 9000256501: Logging in
[NBC] 9000256501: Retrieving Session
ERROR: [NBC] 9000256501: Unable to download webpage: HTTP Error 401:  (caused by <HTTPError 401: ''>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/nbc.py", line 142, in _real_extract
    query['auth'] = self._extract_mvpd_auth(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/adobepass.py", line 1715, in _extract_mvpd_auth
    session = self._download_webpage(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1079, in _download_webpage
    return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1030, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/adobepass.py", line 1361, in _download_webpage_handle
    return super(AdobePassIE, self)._download_webpage_handle(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 864, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 821, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 803, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3656, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401:
```

**Comment by pdisciascio** [comment] 2022-10-29 13:27
@wxolp I believe this is different, since that issue did not involve SSO, and my issue with the previously mentioned URLs still exists.

**Comment by wxolp** [comment] 2022-10-29 13:49
The URLs you mentioned not need SSO:

~~~
POST http://access-cloudpath.media.nbcuni.com/access/vod/nbcuniversal/9000256501
GET https://east.manifest.na.theplatform.com/m/HNK2IC/IeSM1ihtyGA8,h9L82AiZfyLP,a3QSdBW04gyi,1jj6HdGW8QIv,vZNbnH3FnqLY,jFy2kU89d6If.m3u8?sid=a57521c0-3b9b-4bd8-8551-df13ec5f1dee&policy=188569627&date=1667051218171&ip=72.181.23.38&schema=1.1&manifest=M3U&tracking=true&switch=HLSServiceSecure&am_sdkv=null&p2=null&_fw_did=&nw=169843&f1=&am_extmp=default&uuid=optout-919864457317695&am_appv=null&mode=on-demand&uoo=1&sfid=9244572&s3=null&am_buildv=null&am_abvrtd=null&s4=poc&_fw_ae=&debug=false&csid=oneapp_phone_android_app_ondemand&metr=1023&am_cpsv=4.0.0-2&bundleId=&userAgent=Go-http-client%2F1.1&e1=default&afid=200265138&prof=nbcu_android_cts_bl&c3=null&a2=4.0.0-2&a3=null&a5=null&a6=0&am_crmid=null&rdid=android&am_playerv=null&did=optout&am_stitcherv=poc&am_abtestid=null&sig=369ecdf2d629673ac604902147be3ef9e72b8fbc611ec92aa71c76f88ec70178
GET https://east.manifest.na.theplatform.com/m/HNK2IC/IeSM1ihtyGA8,h9L82AiZfyLP,a3QSdBW04gyi,1jj6HdGW8QIv,vZNbnH3FnqLY,jFy2kU89d6If/4.m3u8?sid=a57521c0-3b9b-4bd8-8551-df13ec5f1dee&policy=188569627&date=1667051218576&ip=72.181.23.38&schema=1.1&cid=a7dc58df-2da9-4122-9852-b6153f9e1c5a&host=vod-lf-oneapp-prd.akamaized.net&meta=false&manifest=M3U&switch=HLSServiceSecure&am_sdkv=null&p2=null&_fw_did=&nw=169843&f1=&am_extmp=default&tracking=true&uuid=optout-919864457317695&am_appv=null&mode=on-demand&uoo=1&sfid=9244572&s3=null&am_buildv=null&am_abvrtd=null&s4=poc&_fw_ae=&csid=oneapp_phone_android_app_ondemand&metr=1023&am_cpsv=4.0.0-2&bundleId=&userAgent=Go-http-client%2F1.1&e1=default&afid=200265138&prof=nbcu_android_cts_bl&c3=null&a2=4.0.0-2&a3=null&a5=null&a6=0&am_crmid=null&rdid=android&am_playerv=null&did=optout&am_stitcherv=poc&am_abtestid=null&sig=25d85f429b2e3f4ceb99c330387f5a823306dd424849a9db30a74d891f95ffad
1.04%   19.84 megabyte   19.81 megabyte/s
~~~

**Comment by pdisciascio** [comment] 2022-10-29 14:48
I dont understand this response.  My problem as documented here: https://github.com/yt-dlp/yt-dlp/issues/5123
still exists with the listed example URLs:

https://www.nbc.com/the-real-housewives-of-beverly-hills/video/we-need-to-talk-about-kathy/9000249196
https://www.nbc.com/saturday-night-live/video/october-1-miles-teller/9000258299
https://www.nbc.com/below-deck-down-under/video/somethings-fishy/9000265442
https://www.nbc.com/dateline-unforgettable/video/under-the-desert-sky/9000256501

**Comment by bashonly** [comment] 2022-12-10 00:54
see #5742 for a possible workaround

**Comment by pukkandan** [comment] 2022-12-10 08:52
Possibly same issue as https://github.com/yt-dlp/yt-dlp/issues/4038, https://github.com/yt-dlp/yt-dlp/issues/516

**Comment by pukkandan** [comment] 2023-09-06 12:24
Closing as dupe of https://github.com/yt-dlp/yt-dlp/issues/516. Try the posted workaround and let us know it it doesn't work

**Closed by pukkandan** 2023-09-06 12:24 UTC
Labels: account-needed, geo-blocked, site-bug, can-share-account
