### ISSUE TITLE
New links from Apple Podcast not working

### ISSUE THREAD

**Issue by zerohedgedata** [yt-dlp/yt-dlp#10829] opened 2024-08-22 22:01 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

canada

### Provide a description that is worded well enough to be understood

[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-23-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2023.11.17, mutagen-1.46.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.40.1, urllib3-2.1.0, websockets-10.4, xattr-0.10.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)

Recently apple podcast page changed and I used to download some episodes with the command:
yt-dlp -a, --batch-file test.txt

Now there is an error, see in the next field. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-a,', '--batch-file', 'test.txt']
[debug] Batch file urls: ['https://podcasts.apple.com/us/podcast/bad-taste-august-15-2024-walmart-hits-52-week-highs/id496019927?i=1000665518804', 'https://podcasts.apple.com/us/podcast/bad-taste-august-15-2024-walmart-hits-52-week-highs/id496019927?i=1000665518834']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-23-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2023.11.17, mutagen-1.46.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.40.1, urllib3-2.1.0, websockets-10.4, xattr-0.10.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[ApplePodcasts] Extracting URL: https://podcasts.apple.com/us/podcast/bad-taste-august-15-2024-walmart-hits-52-week-highs/id496019927?i=1000665518804
[ApplePodcasts] 1000665518804: Downloading webpage
ERROR: 1000665518804: An extractor error has occurred. (caused by StopIteration()); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/applepodcasts.py", line 48, in _real_extract
    amp_data = try_get(amp_data,
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 2640, in try_get
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 2631, in try_call
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/applepodcasts.py", line 50, in <lambda>
    next(a[x] for x in iter(a) if episode_id in x),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

[ApplePodcasts] Extracting URL: https://podcasts.apple.com/us/podcast/bad-taste-august-15-2024-walmart-hits-52-week-highs/id496019927?i=1000665518834
[ApplePodcasts] 1000665518834: Downloading webpage
ERROR: 1000665518834: An extractor error has occurred. (caused by StopIteration()); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/applepodcasts.py", line 48, in _real_extract
    amp_data = try_get(amp_data,
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 2640, in try_get
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 2631, in try_call
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/applepodcasts.py", line 50, in <lambda>
    next(a[x] for x in iter(a) if episode_id in x),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

**Comment by bashonly** [comment] 2024-08-22 22:32
Duplicate of #10809

**Closed by bashonly** 2024-08-22 22:32 UTC
Labels: site-bug, triage
