### ISSUE TITLE
ERROR: Postprocessing: Error opening output files: Invalid argument

### ISSUE THREAD

**Issue by tantined-lotus** [yt-dlp/yt-dlp#9605] opened 2024-04-03 15:08 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Netherlands

### Provide a description that is worded well enough to be understood

```console
$ yt-dlp --split-chapters --embed-thumbnail --extract-audio --audio-quality 0 'https://www.youtube.com/watch?v=U0udmoQ8uD8'
[youtube] Extracting URL: https://www.youtube.com/watch?v=U0udmoQ8uD8
[youtube] U0udmoQ8uD8: Downloading webpage
[youtube] U0udmoQ8uD8: Downloading ios player API JSON
[youtube] U0udmoQ8uD8: Downloading android player API JSON
[youtube] U0udmoQ8uD8: Downloading m3u8 information
[info] U0udmoQ8uD8: Downloading 1 format(s): 251
[info] Downloading video thumbnail 46 ...
[info] Writing video thumbnail 46 to: 🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].webp
[download] Destination: 🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].webm
[download] 100% of  251.27MiB in 00:00:12 at 20.11MiB/s
[ExtractAudio] Destination: 🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].opus
Deleting original file 🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].webm (pass -k to keep)
[ThumbnailsConvertor] Converting thumbnail "🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].webp" to png
[EmbedThumbnail] mutagen: Adding thumbnail to "🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].opus"
[SplitChapters] Splitting video by chapters; 9 chapters found
[SplitChapters] Chapter 001; Destination: 🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic - 001 Adventure - Alexander Nakarada [U0udmoQ8uD8].opus
ERROR: Postprocessing: Error opening output files: Invalid argument
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --split-chapters --embed-thumbnail --extract-audio --audio-quality 0 'https://www.youtube.com/watch?v=U0udmoQ8uD8'
[debug] Command-line config: ['-vU', '--split-chapters', '--embed-thumbnail', '--extract-audio', '--audio-quality', '0', 'https://www.youtube.com/watch?v=U0udmoQ8uD8']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.8 (CPython x86_64 64bit) - Linux-6.8.2-0-edge-x86_64-with (OpenSSL 3.2.1 30 Jan 2024)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1808 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=U0udmoQ8uD8
[youtube] U0udmoQ8uD8: Downloading webpage
[youtube] U0udmoQ8uD8: Downloading ios player API JSON
[youtube] U0udmoQ8uD8: Downloading android player API JSON
[youtube] U0udmoQ8uD8: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] U0udmoQ8uD8: Downloading 1 format(s): 251
[info] Downloading video thumbnail 46 ...
[info] Writing video thumbnail 46 to: 🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].webp
[debug] Invoking http downloader on "https://rr5---sn-32o-1the.googlevideo.com/videoplayback?expire=1712178221&ei=zW8NZq6yKLiA6dsPgtSNyAs&ip=XXXX%3AXXXX%3AXXXX%3AXXXX%3AXXXX%3AXXXX%3AXXXX%3AXXXX&id=...
[download] Destination: 🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].webm
[download] 100% of  251.27MiB in 00:00:12 at 20.24MiB/s
[debug] ffmpeg command line: ffprobe -show_streams 'file:🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].webm'
[ExtractAudio] Destination: 🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].opus
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].webm' -vn -acodec copy -movflags +faststart 'file:🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].opus'
Deleting original file 🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].webm (pass -k to keep)
[ThumbnailsConvertor] Converting thumbnail "🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].webp' -update 1 -movflags +faststart 'file:🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].png'
[EmbedThumbnail] mutagen: Adding thumbnail to "🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].opus"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].png'
[SplitChapters] Splitting video by chapters; 9 chapters found
[SplitChapters] Chapter 001; Destination: 🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic - 001 Adventure - Alexander Nakarada [U0udmoQ8uD8].opus
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -ss 0.0 -t 276.0 -i 'file:🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].opus' -map 0 -dn -ignore_unknown -c copy -movflags +faststart 'file:🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic - 001 Adventure - Alexander Nakarada [U0udmoQ8uD8].opus'
[debug] ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.1 (Alpine 13.2.1_git20240309) 20240309
  configuration: --prefix=/usr --disable-librtmp --disable-lzma --disable-static --disable-stripping --enable-avfilter --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libmp3lame --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librist --enable-libsoxr --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-lto=auto --enable-lv2 --enable-openssl --enable-pic --enable-postproc --enable-pthreads --enable-shared --enable-vaapi --enable-vdpau --enable-version3 --enable-vulkan --optflags=-O3 --enable-libjxl --enable-libsvtav1 --enable-libvpl
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
[ogg @ 0x7f48c3abc600] 261343 bytes of comment header remain
Input #0, ogg, from 'file:🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic [U0udmoQ8uD8].opus':
  Duration: 03:54:04.43, start: 0.007500, bitrate: 149 kb/s
  Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      encoder         : Lavf60.16.100
  Stream #0:1: Video: png, rgb24(pc, gbr/unknown/unknown), 1280x720, 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Cover (front)
[opus @ 0x7f48c01f3280] Unsupported codec id in stream 1
[out#0/opus @ 0x7f48c34da7c0] Could not write header (incorrect codec parameters ?): Invalid argument
Error opening output file file:🍻🎶 Viking music, Celtic music, Medieval, Tavern Music - (non copyright) #music #celticmusic - 001 Adventure - Alexander Nakarada [U0udmoQ8uD8].opus.
Error opening output files: Invalid argument

ERROR: Postprocessing: Error opening output files: Invalid argument
Traceback (most recent call last):
  File "/home/guest/src/github.com/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3526, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guest/src/github.com/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3708, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guest/src/github.com/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3690, in run_all_pps
    info = self.run_pp(pp, info)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/guest/src/github.com/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3668, in run_pp
    files_to_delete, infodict = pp.run(infodict)
                                ^^^^^^^^^^^^^^^^
  File "/home/guest/src/github.com/yt-dlp/yt-dlp/yt_dlp/postprocessor/common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guest/src/github.com/yt-dlp/yt-dlp/yt_dlp/postprocessor/common.py", line 128, in wrapper
    return func(self, info)
           ^^^^^^^^^^^^^^^^
  File "/home/guest/src/github.com/yt-dlp/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 1066, in run
    self.real_run_ffmpeg([(in_file, opts)], [(destination, self.stream_copy_opts())])
  File "/home/guest/src/github.com/yt-dlp/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 367, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Error opening output files: Invalid argument
```

**Comment by bashonly** [comment] 2024-04-03 15:34
Duplicate of #6225

**Closed by bashonly** 2024-04-03 15:34 UTC
Labels: site-bug, triage
