### ISSUE TITLE
remove finished links from batch-file

### ISSUE THREAD

**Issue by Franzl123** [yt-dlp/yt-dlp#3894] opened 2022-05-28 11:23 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hello,
how about an option to remove completed links from the link-file when using batch mode (-a)?
That keeps the file nice and clean and you can see which links were not loaded correctly (for recheck).

**Comment by pukkandan** [comment] 2022-05-28 13:23
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1760

**Closed by pukkandan** 2022-05-28 13:23 UTC
Labels: enhancement, triage
