### ISSUE TITLE
[PBS] Nova: ERROR: An extractor error has occurred. (caused by KeyError('title'));

### ISSUE THREAD

**Issue by AngelBlue01** [yt-dlp/yt-dlp#3879] opened 2022-05-26 23:00 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I cannot download the latest episode of PBS's Nova: https://www.pbs.org/wgbh/nova/video/ice-age-footprints

The error message reported by yt-dl is "ERROR: An extractor error has occurred. (caused by KeyError('title'));"

### Verbose log

```shell
[debug] Command-line config: ['https://www.pbs.org/wgbh/nova/video/ice-age-footprints', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-14-amd64-x86_64-with-glibc2.31
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2021.05.30, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] Using fake IP 6.133.96.219 (US) as X-Forwarded-For
[pbs] Downloading JSON metadata
[debug] [pbs] Extracting URL: https://www.pbs.org/wgbh/nova/video/ice-age-footprints
[pbs] ice-age-footprints: Downloading webpage
[pbs] Downloading widget/partnerplayer page
[pbs] Downloading portalplayer page
ERROR: An extractor error has occurred. (caused by KeyError('title')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/pbs.py", line 690, in _real_extract
    'title': info['title'],
KeyError: 'title'
```

**Comment by gamer191** [comment] 2022-05-27 04:53
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2606

**Closed** 2022-05-27 05:21 UTC
Labels: site-bug, triage
