### ISSUE TITLE
ERROR: [Zee5] 0-1-6z5120257: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>)

### ISSUE THREAD

**Issue by blahiri** [yt-dlp/yt-dlp#3379] opened 2022-04-10 08:39 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Hi, I am unable to download videos from ZEE5 using the latest version of yt-dlp. The full error traceback is given in the 'verbose log' section. Some links that I tried downloading with,

https://www.zee5.com/tv-shows/details/zee-bangla-sonar-sansar-awards-2022/0-6-4z595996/zee-bangla-sonar-sansar-awards-2022/0-1-6z5120257

This is the summary of the error that I am getting,

<pre>
yt-dlp https://www.zee5.com/tv-shows/details/zee-bangla-sonar-sansar-awards-2022/0-6-4z595996/zee-bangla-sonar-sansar-awards-2022/0-1-6z5120257
[Zee5] 0-1-6z5120257: Downloading access token
[Zee5] 0-1-6z5120257: Downloading JSON metadata
ERROR: [Zee5] 0-1-6z5120257: Unable to download JSON metadata: 
HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); 
please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. 
Confirm you are on the latest version using  yt-dlp -U
</pre>

### Verbose log

```shell
g:\bin>yt-dlp -vU https://www.zee5.com/tv-shows/details/zee-bangla-sonar-sansar-
awards-2022/0-6-4z595996/zee-bangla-sonar-sansar-awards-2022/0-1-6z5120257
[debug] Command-line config: ['-vU', 'https://www.zee5.com/tv-shows/details/zee-
bangla-sonar-sansar-awards-2022/0-6-4z595996/zee-bangla-sonar-sansar-awards-2022
/0-1-6z5120257']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No A
NSI), pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.
1-full_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websoc
kets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] Using fake IP 117.229.95.104 (IN) as X-Forwarded-For
[debug] [Zee5] Extracting URL: https://www.zee5.com/tv-shows/details/zee-bangla-
sonar-sansar-awards-2022/0-6-4z595996/zee-bangla-sonar-sansar-awards-2022/0-1-6z
5120257
[Zee5] 0-1-6z5120257: Downloading access token
[Zee5] 0-1-6z5120257: Downloading JSON metadata
ERROR: [Zee5] 0-1-6z5120257: Unable to download JSON metadata: HTTP Error 400: B
ad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue
on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate iss
ue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\zee5.py", line 131, in _real_extract
  File "yt_dlp\extractor\common.py", line 1029, in _download_json
  File "yt_dlp\extractor\common.py", line 1008, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 800, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 785, in _request_webpage

  File "yt_dlp\extractor\common.py", line 767, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3601, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by pukkandan** [comment] 2022-04-10 09:00
Show log with cookies passed

**Comment by blahiri** [comment] 2022-04-10 11:40
<pre>
g:\bin>yt-dlp -vU --cookies-from-browser opera https://www.zee5.com/tv-shows/det
ails/zee-bangla-sonar-sansar-awards-2022/0-6-4z595996/zee-bangla-sonar-sansar-aw
ards-2022/0-1-6z5120257
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'opera', 'https:/
/www.zee5.com/tv-shows/details/zee-bangla-sonar-sansar-awards-2022/0-6-4z595996/
zee-bangla-sonar-sansar-awards-2022/0-1-6z5120257']
[Cookies] Extracting cookies from opera
[debug] Extracting cookies from: "C:\Users\Ravi\AppData\Roaming\Opera Software\O
pera Stable\Network\Cookies"
[Cookies] Extracted 3010 cookies from opera
[debug] cookie version breakdown: {'v10': 3010, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No A
NSI), pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.
1-full_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websoc
kets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] Using fake IP 117.233.252.24 (IN) as X-Forwarded-For
[debug] [Zee5] Extracting URL: https://www.zee5.com/tv-shows/details/zee-bangla-
sonar-sansar-awards-2022/0-6-4z595996/zee-bangla-sonar-sansar-awards-2022/0-1-6z
5120257
[Zee5] 0-1-6z5120257: Downloading access token
[Zee5] 0-1-6z5120257: Downloading JSON metadata
ERROR: [Zee5] 0-1-6z5120257: Unable to download JSON metadata: HTTP Error 400: B
ad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue
on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate iss
ue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\zee5.py", line 131, in _real_extract
  File "yt_dlp\extractor\common.py", line 1029, in _download_json
  File "yt_dlp\extractor\common.py", line 1008, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 800, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 785, in _request_webpage

  File "yt_dlp\extractor\common.py", line 767, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3601, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request


</pre>

**Comment by m4tu4g** [comment] 2022-04-10 14:53
issue fixed by [commit](https://github.com/yt-dlp/yt-dlp/commit/2d2b5493ee88ccde079a5cde3d58ac5469057d17)

**Comment by pukkandan** [comment] 2022-04-10 15:08
oops, I forgot that commit wasn't in the release 😓 and thought the issue appeared again 😄

**Comment by pukkandan** [comment] 2022-04-10 15:08
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3105

**Closed by pukkandan** 2022-04-10 15:08 UTC
Labels: account-needed, site-bug, can-share-account
