### ISSUE TITLE
AMC Error Downloading The Walking Dead World Beyond

### ISSUE THREAD

**Issue by jsmith1299** [yt-dlp/yt-dlp#1665] opened 2021-11-14 16:19 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Getting an Error on all of the Walking Dead sites. I've tried with and without cookies but it errors out.

### Verbose log

```shell
yt-dlp.exe --cookies a.txt https://www.amc.com/shows/the-walking-dead-world-beyond/episodes/season-2-konsekans -Uv
[debug] Command-line config: ['--cookies', 'a.txt', 'https://www.amc.com/shows/the-walking-dead-world-beyond/episodes/season-2-konsekans', '-Uv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg N-93302-g147ef1d947, ffprobe N-93302-g147ef1d947
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [AMCNetworks] Extracting URL: https://www.amc.com/shows/the-walking-dead-world-beyond/episodes/season-2-konsekans
[AMCNetworks] shows/the-walking-dead-world-beyond/episodes/season-2-konsekans: Downloading JSON metadata
ERROR: [AMCNetworks] shows/the-walking-dead-world-beyond/episodes/season-2-konsekans: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 713, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3295, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default





yt-dlp.exe --cookies a.txt https://www.amc.com/shows/the-walking-dead-world-beyond/episodes/season-2-konsekans--1033905?twduRedirectUrl=https://www.amc.com/twdu/the-walking-dead-world-beyond
[AMCNetworks] shows/the-walking-dead-world-beyond/episodes/season-2-konsekans--1033905: Downloading JSON metadata
ERROR: [AMCNetworks] shows/the-walking-dead-world-beyond/episodes/season-2-konsekans--1033905: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

yt-dlp.exe --cookies a.txt https://www.amc.com/shows/the-walking-dead-world-beyond/episodes/season-2-konsekans--1033905?twduRedirectUrl=https://www.amc.com/twdu/the-walking-dead-world-beyond -Uv
[debug] Command-line config: ['--cookies', 'a.txt', 'https://www.amc.com/shows/the-walking-dead-world-beyond/episodes/season-2-konsekans--1033905?twduRedirectUrl=https://www.amc.com/twdu/the-walking-dead-world-beyond', '-Uv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg N-93302-g147ef1d947, ffprobe N-93302-g147ef1d947
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [AMCNetworks] Extracting URL: https://www.amc.com/shows/the-walking-dead-world-beyond/episodes/season-2-konsekans--1033905?twduRedirectUrl=https://www.amc.com/twdu/the-walking-dead-world-beyond
[AMCNetworks] shows/the-walking-dead-world-beyond/episodes/season-2-konsekans--1033905: Downloading JSON metadata
ERROR: [AMCNetworks] shows/the-walking-dead-world-beyond/episodes/season-2-konsekans--1033905: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 713, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3295, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

**Comment by pukkandan** [comment] 2021-11-27 16:49
Try passing MSO details

**Comment by jcschmidt31** [comment] 2021-12-03 21:21
Based on other issues in the past this is what I tried.

.\yt-dlp -v -F "https://www.amc.com/shows/the-walking-dead/episodes/season-11-acheron-part-i--1027621" --ap-mso 'Comcast_SSO' --ap-username 'REDACTED' --ap-password 'REDACTED' --cookies 'G:\Youtube\yt-dlp\cookies.txt'
[debug] Command-line config: ['-v', '-F', 'https://www.amc.com/shows/the-walking-dead/episodes/season-11-acheron-part-i--1027621', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--cookies', 'G:\\Youtube\\yt-dlp\\cookies.txt']
[debug] Portable config file: G:\Youtube\yt-dlp\yt-dlp.conf
[debug] Portable config: ['-o', 'G:/YoutubeDL/%(title)s.%(ext)s', '--external-downloader', 'aria2c']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [AMCNetworks] Extracting URL: https://www.amc.com/shows/the-walking-dead/episodes/season-11-acheron-part-i--1027621
[AMCNetworks] shows/the-walking-dead/episodes/season-11-acheron-part-i--1027621: Downloading JSON metadata
ERROR: [AMCNetworks] shows/the-walking-dead/episodes/season-11-acheron-part-i--1027621: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 715, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3385, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default

**Comment by dano-code** [comment] 2021-12-06 18:53
someone opened an issue on youtube-dl that AMC was now using Brightcove instead of Theplatform. It had the same symptom of 404 when looking for the JSON URL. I think that means the extractor needs to be changed.

**Comment by jcschmidt31** [comment] 2021-12-08 19:27
I can provide Comcast/Xfinity TV Provider login credentials for any contributor/member who can help resolve this issue.

**Comment by pukkandan** [comment] 2021-12-08 22:37
Comcast_SSO is currently broken. Closing as duplicate of #516 unless someone can check if this issue can be reproduced with other MSOs

**Comment by jsmith1299** [comment] 2021-12-18 13:44
I am seeing the same issue on Verizon

yt-dlp.exe --cookies a.txt --ap-mso Verizon --ap-username <<>>--ap-password <<>> https://www.amc.com/shows/fear-the-walking-dead/episodes/season-7-the-beacon--1034034?twduRedirectUrl=https://www.amc.com/twdu/fear-the-walking-dead -v
[debug] Command-line config: ['--cookies', 'a.txt', '--ap-mso', 'Verizon', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.amc.com/shows/fear-the-walking-dead/episodes/season-7-the-beacon--1034034?twduRedirectUrl=https://www.amc.com/twdu/fear-the-walking-dead', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg N-93302-g147ef1d947, ffprobe N-93302-g147ef1d947
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [AMCNetworks] Extracting URL: https://www.amc.com/shows/fear-the-walking-dead/episodes/season-7-the-beacon--1034034?twduRedirectUrl=https://www.amc.com/twdu/fear-the-walking-dead
[AMCNetworks] shows/fear-the-walking-dead/episodes/season-7-the-beacon--1034034: Downloading JSON metadata
ERROR: [AMCNetworks] shows/fear-the-walking-dead/episodes/season-7-the-beacon--1034034: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 715, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3385, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default

**Comment by Sipherdrakon** [comment] 2022-01-17 05:50
This is an issue with all of AMC and Affiliates. The move to brightcove broke the extractor. So WeTV and anything else that uses AMCNetworks from what I can tell.

**Comment by PrSinister** [comment] 2022-01-24 17:17
Is there a way to force using the Brightcove:new extractor?

I am getting the following error on WEtv:

[debug] Command-line config: ['-Uv', '-i', '--write-sub', '--add-metadata', '-o', 'Love After Lockup.%(season_number)sx%(episode_number)02d.%(title)s.%(height)sp WEB-DL.%(ext)s', '--downloader', 'aria2c', '--convert-subs=srt', '--embed-subs', '--all-subs', '--ignore-config', '--hls-prefer-native', '--no-geo-bypass', '--cookies', './cookies.txt', 'https://www.wetv.com/shows/life-after-lockup/episodes/season-2-episode-19-trials-tribulations--1044960']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-essentials_build-www.gyan.dev (setts), ffprobe 4.4-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [AMCNetworks] Extracting URL: https://www.wetv.com/shows/life-after-lockup/episodes/season-2-episode-19-trials-tribulations--1044960
[AMCNetworks] shows/life-after-lockup/episodes/season-2-episode-19-trials-tribulations--1044960: Downloading JSON metadata
ERROR: [AMCNetworks] shows/life-after-lockup/episodes/season-2-episode-19-trials-tribulations--1044960: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 730, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3526, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default

**Comment by Sipherdrakon** [comment] 2022-02-05 03:27
> Is there a way to force using the Brightcove:new extractor?
> 

I tried using the brightcove extractor and it came back DRM protected. So that won't work. Unless there is an m3u8 or mpd that doesn't have DRM, might be SOL.

**Comment by gkoelln** [comment] 2022-04-28 21:03
From @89z: https://github.com/89z/mech/tree/741d1067/research/bbcamerica

**Closed** 2022-04-28 21:24 UTC
Labels: DRM, account-needed, site-bug

**Comment by pukkandan** [comment] 2022-04-28 21:25
@gkoelln Do not post links related to breaking DRM

**Comment by gkoelln** [comment] 2022-04-28 21:26
Sorry!  Won't happen again!
