### ISSUE TITLE
Facebook Reels URL gives 404 or Parse error

### ISSUE THREAD

**Issue by acdcfanbill** [yt-dlp/yt-dlp#5219] opened 2022-10-12 21:41 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

I'm attempting to download a public 'reel' video from facebook.  If no cookies are provided, it gives a 404 error.  If cookies are provided, it gives a parse error.  I can confirm the video is public, and if I attempt to use yt-dlp on regular, non-reel, public, videos on facebook, it downloads them as I would expect.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --cookies cookies.Facebook.txt https://www.facebook.com/reel/569643148263317
[debug] Command-line config: ['-vU', '--cookies', 'cookies.Facebook.txt', 'https://www.facebook.com/reel/569643148263317']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.10.7 (CPython 64bit) - macOS-12.5.1-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [facebook:reel] Extracting URL: https://www.facebook.com/reel/569643148263317
[debug] [facebook] Extracting URL: https://m.facebook.com/watch/?v=569643148263317&_rdr
[facebook] 569643148263317: Downloading webpage
[facebook] 569643148263317: Downloading webpage
ERROR: [facebook] 569643148263317: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/facebook.py", line 705, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/facebook.py", line 651, in _extract_from_url
    raise ExtractorError('Cannot parse data')

$ yt-dlp -vU  https://www.facebook.com/reel/569643148263317
[debug] Command-line config: ['-vU', 'https://www.facebook.com/reel/569643148263317']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.10.7 (CPython 64bit) - macOS-12.5.1-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [facebook:reel] Extracting URL: https://www.facebook.com/reel/569643148263317
[debug] [facebook] Extracting URL: https://m.facebook.com/watch/?v=569643148263317&_rdr
[facebook] 569643148263317: Downloading webpage
ERROR: [facebook] 569643148263317: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/facebook.py", line 705, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/facebook.py", line 381, in _extract_from_url
    webpage = self._download_webpage(
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1081, in _download_webpage
    return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1032, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 866, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 823, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 805, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/opt/homebrew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3682, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by denaunistic** [comment] 2022-10-12 21:42
This looks like a duplicate of #4311

**Comment by bashonly** [comment] 2022-10-12 22:02
> `https://www.facebook.com/reel/569643148263317`

i get "This page isn't available" (404) with browser.

**Closed** 2022-10-12 23:16 UTC
Labels: invalid, site:facebook
