### ISSUE TITLE
Embed subtitles and metadata during merge instaed of seperatly after

### ISSUE THREAD

**Issue by mrherman** [yt-dlp/yt-dlp#3952] opened 2022-06-03 02:49 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Currently yt-dlp merges video+audio in to container (mp4 for my test case) then embeds subtitles then embeds metadata (using a call to ffmpeg command each time).  During the two embeds ffmpeg creates a new file that contains what is being embedded then deletes the old file; therefore, you get two additional writes (one each for subtitles and metadata) on the filesystem.  When working with large files this could add many gigs of disk writes that could be avoided if the inclusion of subtitles and metadata happens during the initial merge of the audio and video files, or if not then at least if subtitles and metadata were added together in the same command.

The below shows that the video is written to the file system 4 times during the whole process. 
```
**mp4 video only downloaded  \ 
                               > -- **mp4 (audio+video) \
   m4a audio only downloaded /                           > --**mp4(video, audio, subtitles) \
                                            subtitiles /                                      >--- **Final video
                                                                                   metadata /
```
Ideally, it would be like this where the video is written twice.
```
** mp4 video only downloaded  \
    m4a audio                  \  -- **Final video
    subtitles                  /
    metadata                  /
```
### Verbose log

```shell
$ yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]' --merge-output-format mp4 --convert-thumb png --embed-thumbnail --sub-lang en --embed-subs --add-metadata --parse-metadata "description:(?P<meta_description>.+)((\s)+)CAPTION STATUS" --parse-metadata "title:\s*(?P<episode_name>.+?)\s*[|].+Campaign\s*(?P<season_num>[\d]+),\s*Episode\s*(?P<episode_num>[\d]+)" --parse-metadata "episode_name:%(meta_title)s" --parse-metadata ":(?P<meta_synopsis>)" -o "Critical Role - s%(season_num)03de%(episode_num)03d - %(episode_name)s" -vU https://www.youtube.com/watch?v=POgfa65vi4k
[debug] Command-line config: ['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]', '--merge-output-format', 'mp4', '--convert-thumb', 'png', '--embed-thumbnail', '--sub-lang', 'en', '--embed-subs', '--add-metadata', '--parse-metadata', 'description:(?P<meta_description>.+)((\\s)+)CAPTION STATUS', '--parse-metadata', 'title:\\s*(?P<episode_name>.+?)\\s*[|].+Campaign\\s*(?P<season_num>[\\d]+),\\s*Episode\\s*(?P<episode_num>[\\d]+)', '--parse-metadata', 'episode_name:%(meta_title)s', '--parse-metadata', ':(?P<meta_synopsis>)', '-o', 'Critical Role - s%(season_num)03de%(episode_num)03d - %(episode_name)s', '-vU', 'https://www.youtube.com/watch?v=POgfa65vi4k']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-99-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=POgfa65vi4k
[youtube] POgfa65vi4k: Downloading webpage
[youtube] POgfa65vi4k: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: en
[debug] Searching for '(?P<meta_description>.+)((\\s)+)CAPTION STATUS' in '%(description)s'
[MetadataParser] Parsed meta_description from '%(description)s': 'While investigating a series of thefts at the behest of their potential patron, the group stumbles onto something much more dangerous than they anticipated, with lasting consequences...'
[debug] Searching for '\\s*(?P<episode_name>.+?)\\s*[|].+Campaign\\s*(?P<season_num>[\\d]+),\\s*Episode\\s*(?P<episode_num>[\\d]+)' in '%(title)s'
[MetadataParser] Parsed episode_name from '%(title)s': 'The Trail and the Toll'
[MetadataParser] Parsed season_num from '%(title)s': '3'
[MetadataParser] Parsed episode_num from '%(title)s': '3'
[debug] Searching for '(?P<meta_title>.+)' in '%(episode_name)s'
[MetadataParser] Parsed meta_title from '%(episode_name)s': 'The Trail and the Toll'
[debug] Searching for '(?P<meta_synopsis>)' in ''
[MetadataParser] Parsed meta_synopsis from '': ''
[info] POgfa65vi4k: Downloading 1 format(s): 137+140
[info] Writing video subtitles to: Critical Role - s003e003 - The Trail and the Toll.en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=POgfa65vi4k&caps=asr&xoaf=4&xosf=1&hl=en&ip=0.0.0.0&ipbits=0&expire=1654249004&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=D9184E8F61D12B0CB91B6A8C54A33D87D417292D.8AB3C97FBD48044B9C07E41097FF3B0768184456&key=yt8&lang=en&fmt=vtt"
[download] Destination: Critical Role - s003e003 - The Trail and the Toll.en.vtt
[download] 100% of 428.11KiB in 00:00
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: Critical Role - s003e003 - The Trail and the Toll.webp
[ThumbnailsConvertor] Converting thumbnail "Critical Role - s003e003 - The Trail and the Toll.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:Critical Role - s003e003 - The Trail and the Toll.webp' -movflags +faststart 'file:Critical Role - s003e003 - The Trail and the Toll.png'
Deleting original file Critical Role - s003e003 - The Trail and the Toll.webp (pass -k to keep)
[debug] Invoking http downloader on "https://rr6---sn-8xgp1vo-p5qe.googlevideo.com/videoplayback?expire=1654245405&ei=vXOZYoGkFtKS8wTz6YeQCA&ip=108.15.23.60&id=o-AFy6SakaUYNBH68hYIqCa7UWXru6ZrT39l8RZwxn8yUs&itag=137&source=youtube&requiressl=yes&mh=zb&mm=31%2C29&mn=sn-8xgp1vo-p5qe%2Csn-p5qs7nzk&ms=au%2Crdu&mv=m&mvi=6&pl=17&initcwndbps=1777500&vprv=1&mime=video%2Fmp4&gir=yes&clen=2064521451&dur=14921.673&lmt=1639257143133743&mt=1654223576&fvip=4&keepalive=yes&fexp=24001373%2C24007246%2C24208264&c=ANDROID&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAK38H6cwZWWYJXiBfD_9eUcxotsCbtXMT9xGxzEpww-ZAiB2TS1shN8TRnORJ1o6ty4yGXTSGefbEt0knbKIGONF0g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgM4BvsLP0KCzIE36iKQSJrpSdAYCd7lDemwt87WLE0K0CIQDyMkvUycSXG-Uu1oPP7nFTPw3bLT8U0_rUhTbmL55gYw%3D%3D"
[download] Destination: Critical Role - s003e003 - The Trail and the Toll.f137.mp4
[download] 100% of 1.92GiB in 03:20
[debug] Invoking http downloader on "https://rr6---sn-8xgp1vo-p5qe.googlevideo.com/videoplayback?expire=1654245405&ei=vXOZYoGkFtKS8wTz6YeQCA&ip=108.15.23.60&id=o-AFy6SakaUYNBH68hYIqCa7UWXru6ZrT39l8RZwxn8yUs&itag=140&source=youtube&requiressl=yes&mh=zb&mm=31%2C29&mn=sn-8xgp1vo-p5qe%2Csn-p5qs7nzk&ms=au%2Crdu&mv=m&mvi=6&pl=17&initcwndbps=1777500&vprv=1&mime=audio%2Fmp4&gir=yes&clen=241492157&dur=14921.722&lmt=1639252963953704&mt=1654223576&fvip=4&keepalive=yes&fexp=24001373%2C24007246%2C24208264&c=ANDROID&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMsyS4HoEeaL_EHs1EMKxe7igeB9CGZAhlhrD8_tHyfqAiEA6vb3lW3Lsl3bvlIh3704VMKxrSea7Z5-mnRXIpx34y0%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgM4BvsLP0KCzIE36iKQSJrpSdAYCd7lDemwt87WLE0K0CIQDyMkvUycSXG-Uu1oPP7nFTPw3bLT8U0_rUhTbmL55gYw%3D%3D"
[download] Destination: Critical Role - s003e003 - The Trail and the Toll.f140.m4a
[download] 100% of 230.30MiB in 00:25
[Merger] Merging formats into "Critical Role - s003e003 - The Trail and the Toll.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Critical Role - s003e003 - The Trail and the Toll.f137.mp4' -i 'file:Critical Role - s003e003 - The Trail and the Toll.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Critical Role - s003e003 - The Trail and the Toll.temp.mp4'
Deleting original file Critical Role - s003e003 - The Trail and the Toll.f137.mp4 (pass -k to keep)
Deleting original file Critical Role - s003e003 - The Trail and the Toll.f140.m4a (pass -k to keep)
[EmbedSubtitle] Embedding subtitles in "Critical Role - s003e003 - The Trail and the Toll.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Critical Role - s003e003 - The Trail and the Toll.mp4' -i 'file:Critical Role - s003e003 - The Trail and the Toll.en.vtt' -map 0 -dn -ignore_unknown -c copy -c:s mov_text -map -0:s -map 1:0 -metadata:s:s:0 language=eng -metadata:s:s:0 handler_name=English -metadata:s:s:0 title=English -movflags +faststart 'file:Critical Role - s003e003 - The Trail and the Toll.temp.mp4'
Deleting original file Critical Role - s003e003 - The Trail and the Toll.en.vtt (pass -k to keep)
[Metadata] Adding metadata to "Critical Role - s003e003 - The Trail and the Toll.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Critical Role - s003e003 - The Trail and the Toll.mp4' -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata 'title=The Trail and the Toll' -metadata date=20211108 -metadata 'description=While investigating a series of thefts at the behest of their potential patron, the group stumbles onto something much more dangerous than they anticipated, with lasting consequences...' -metadata synopsis= -metadata 'purl=https://www.youtube.com/watch?v=POgfa65vi4k' -metadata 'comment=https://www.youtube.com/watch?v=POgfa65vi4k' -metadata 'artist=Critical Role' -movflags +faststart 'file:Critical Role - s003e003 - The Trail and the Toll.temp.mp4'
[EmbedThumbnail] mutagen: Adding thumbnail to "Critical Role - s003e003 - The Trail and the Toll.mp4"
```

**Comment by dirkf** [comment] 2022-06-03 11:42
According to #3316, this is a duplicate of #126.

**Closed** 2022-06-03 12:16 UTC
Labels: enhancement, triage
