### ISSUE TITLE
ITV Hub - No 1080p Option?

### ISSUE THREAD

**Issue by danieldavis3924** [yt-dlp/yt-dlp#5010] opened 2022-09-23 20:38 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am new to this software, and I am trying to download a movie from ITV Hub. When I check what versions are available, I am not able to see any 720p or 1080p versions? Have I missed something, or is this a known issue?

URL: https://www.itv.com/hub/wonder-woman/2a7968a0001

COMMAND: yt-dlp -F https://www.itv.com/hub/wonder-woman/2a7968a0001

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\youtube-dl>yt-dlp -vU -F https://www.itv.com/hub/wonder-woman/2a7968a0001
[debug] Command-line config: ['-vU', '-F', 'https://www.itv.com/hub/wonder-woman/2a7968a0001']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-09-22-git-af919cf780-essentials_build-www.gyan.dev (setts), ffprobe 2022-09-22-git-af919cf780-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] Using fake IP 25.134.132.217 (GB) as X-Forwarded-For
[debug] [ITV] Extracting URL: https://www.itv.com/hub/wonder-woman/2a7968a0001
[ITV] 2a7968a0001: Downloading webpage
[ITV] 2a7968a0001: Downloading JSON metadata
[ITV] 2a7968a0001: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 2a7968a0001:
ID       EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR
──────────────────────────────────────────────────────────────────────────────────────
hls-68   mp4 audio only     │ ~ 64.22MiB   68k m3u8  │ audio only        mp4a.40.2 64k
hls-102  mp4 audio only     │ ~ 96.34MiB  102k m3u8  │ audio only        mp4a.40.2 96k
hls-285  mp4 512x288     25 │ ~269.17MiB  285k m3u8  │ avc1.4D401F  204k mp4a.40.2 64k
hls-637  mp4 512x288     25 │ ~601.63MiB  637k m3u8  │ avc1.4D401F  504k mp4a.40.2 96k
hls-848  mp4 512x288     25 │ ~800.91MiB  848k m3u8  │ avc1.4D401F  704k mp4a.40.2 96k
hls-1272 mp4 896x504     25 │ ~  1.17GiB 1272k m3u8  │ avc1.4D401F 1104k mp4a.40.2 96k
hls-1908 mp4 896x504     25 │ ~  1.76GiB 1908k m3u8  │ avc1.4D401F 1704k mp4a.40.2 96k
```

**Comment by pukkandan** [comment] 2022-09-24 09:20
>  ### Make sure you are **only** asking a question and not reporting a bug or requesting a feature.
> If your question contains "isn't working" or "can you add", this is most likely the wrong template.
> If you are in doubt whether this is the right template, **USE ANOTHER TEMPLATE**!

Didn't read the template?

---

What country are u in? The site asks me for login

**Comment by dirkf** [comment] 2022-09-26 16:19
I don't have any record of 1080p downloads from ITV Hub, eg
* https://github.com/yt-dlp/yt-dlp/issues/1775#issuecomment-978795367
* https://github.com/ytdl-org/youtube-dl/issues/30578#issuecomment-1033683100.

OP should verify that a 720p or 1080p version is available in the web player for the desired show.

If there is one and the extractor isn't finding it, the extractor may be ignoring it as unplayable (eg, DRM), or just not finding it.

**Comment by Vangelis66** [comment] 2022-09-29 01:11
To my best recollection, **ITV Hub** only offers up to `504p` encodes in their **desktop browser** edition; some years ago, the HTML5 desktop streams would use **ClearKey** encryption, but for the past two years at least, everything on desktop ITV Hub is **behind full-blown DRM** (requires a supported version of the WidevineCDM). 

Whether ITV now provide `720p`/`1080p` encodes on desktop browsers is a moot point with regards to OP's "question", because they would certainly be behind DRM that `yt-dlp` doesn't support (more accurately, doesn't have - and **won't have** - a "built-in"' solution for DRM decryption). 

The crux of the matter is that the existing `itvIE` on both `youtube-dl` and `yt-dlp` relies upon the **HLSe** (AES-128 encrypted) streams targeting older Apple MOBILE devices (iPhones/iPads) and these streams max out at `504p` SD... 

(Possibly a duplicate of upstream issue [#25053](https://github.com/ytdl-org/youtube-dl/issues/25053))

**Closed** 2022-09-29 01:30 UTC
Labels: incomplete, site-enhancement

**Comment by Vangelis66** [comment] 2022-09-29 01:48
> OP should verify that a 720p or 1080p version is available in the web player for the desired show.

... Trying to initiate playback in my **desktop browser** (whitelisted UK IP address via VPN, personal ITV Hub account used) of the `id` mentioned by OP: 

![itvhub](https://user-images.githubusercontent.com/9669492/192917688-091ac318-783e-4576-b763-d7b99a655918.jpg)

the browser clearly indicates the media content is DRM'ed, plus it's being served the following MPEG-DASH `cenc` (master) manifest: 
```
https://itvpnpdotcom.blue.content.itv.com/2-7968-0001-002/18/1/VAR028/2-7968-0001-002_18_1_VAR028.ism/.mpd?hdnea=st=1664414251~exp=1664435851~acl=/2-7968-0001-002/*~data=nohubplus~hmac=57a18370ff941d28f254a4cebfe8d55d91b7eae171c23adddf87f2607a68fd12
```
This is **geo-blocked**, **tokenised** and **short-lived**, thus I'm attaching its content below: 
[ITVHub.mpd.txt](https://github.com/yt-dlp/yt-dlp/files/9670033/ITVHub.mpd.txt) ; the excerpt:

```xml
      <Representation
        id="video=503992"
        bandwidth="503992"
        width="512"
        height="288"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=703981"
        bandwidth="703981"
        width="512"
        height="288"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=1103985"
        bandwidth="1103985"
        width="896"
        height="504"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=1403938"
        bandwidth="1403938"
        width="896"
        height="504"
        scanType="progressive">
      </Representation>
      <Representation
        id="video=1703955"
        bandwidth="1703955"
        width="896"
        height="504"
        scanType="progressive">
      </Representation>
```
clearly demonstrates that **no "Representation" is being offered with height > "504"**... 

Unless OP (or someone else in the UK) can say otherwise, this issue/question can be closed (and this specific comment only tries to answer whether > `504p` is being offered inside ITV Hub; as explained above, fetching+decrypting it with `yt-dlp`, had it been offered, would've been impossible).

**Comment by wxolp** [comment] 2022-09-29 23:26
I am getting this message, even with VPN:

> Sorry!
> This video isn't available right now. Check out our Shows section for more great programmes.

**Comment by danieldavis3924** [comment] 2022-10-11 07:19
I am in the UK. There may be some geo-restrictions. Thank youSent from my iPhoneOn 24 Sep 2022, at 10:21, pukkandan ***@***.***> wrote:﻿

Make sure you are only asking a question and not reporting a bug or requesting a feature.
If your question contains "isn't working" or "can you add", this is most likely the wrong template.
If you are in doubt whether this is the right template, USE ANOTHER TEMPLATE!

Didn't read the template?

What country are u in? The site asks me for login

**Comment by pukkandan** [comment] 2022-10-11 07:22
See Vangelis' comment
