### ISSUE TITLE
[tiktok] Comments support

### ISSUE THREAD

**Issue by upintheairsheep** [yt-dlp/yt-dlp#3881] opened 2022-05-27 16:53 UTC
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Southern California, USA

### Example URLs

http://tiktok.com/@123blur
https://www.tiktok.com/@ultimatemariofan101/video/7090771071787470123

### Description

TikTok comments and replies are not downloaded even with --write comments. Please add an extractor for TikTok comments, im confused about why you did not do it in the first place. Comments include likes, profile pic urls, text, video links and thumbnails, and username. Some other TikTok downloaders include support for comments and replies. Please make sure to get all replies and all comments.

### Verbose log

```shell
see https://ia802506.us.archive.org/19/items/TikTok-7090771071787470123/7090771071787470123.info.json for info.json
```

**Comment by pukkandan** [comment] 2022-06-20 08:47
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/4012

**Closed by pukkandan** 2022-06-20 08:47 UTC
Labels: duplicate, site-enhancement, site:tiktok
