### ISSUE TITLE
Instagram Extractor needs login to download video

### ISSUE THREAD

**Issue by johnconnorskynet** [yt-dlp/yt-dlp#1523] opened 2021-11-02 13:25 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Description

Hi Guys,

I tried to download a video from instagram : https://www.instagram.com/p/CHbHrdNnqRz/ at the command line.
Unfortunately the debug verbose says it needs login credentials which was the not the case with youtube-dl.
It would be very convenient to have a login less option.

Thanks.

### Verbose log

```shell
yt-dlp --verbose https://www.instagram.com/p/CHbHrdNnqRz/

[debug] Command-line config: ['--verbose', 'https://www.instagram.com/p/CHbHrdNnqRz/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8[debug] yt-dlp version 2021.10.22
[debug] Python version 3.7.2 (CPython 64bit) - Linux-4.4.0-142-generic-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 2.8.17, ffprobe 2.8.17, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[Instagram] Downloading login webpage
[Instagram] Logging in
ERROR: [Instagram] CHbHrdNnqRz: Unable to login; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 591, in extract
    self.initialize()
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 499, in initialize
    self._real_initialize()
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/instagram.py", line 183, in _real_initialize
    self._login()
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/instagram.py", line 180, in _login
    raise ExtractorError('Unable to login')
yt_dlp.utils.ExtractorError: Unable to login; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 591, in extract
    self.initialize()
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 499, in initialize
    self._real_initialize()
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/instagram.py", line 183, in _real_initialize
    self._login()
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/instagram.py", line 180, in _login
    raise ExtractorError('Unable to login')
yt_dlp.utils.ExtractorError: Unable to login; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1280, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1305, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 610, in extract
    e.msg, video_id=video_id, ie=self.IE_NAME, tb=e.traceback, expected=e.expected, cause=e.cause)
yt_dlp.utils.ExtractorError: [Instagram] CHbHrdNnqRz: Unable to login; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by Ashish0804** [comment] 2021-11-02 13:30
> I've searched the bugtracker for similar issues including closed ones. DO NOT post duplicates

u know the checkboxes are not for just shitz and gigglz, right?

dupe of https://github.com/yt-dlp/yt-dlp/issues/1457

**Closed by Ashish0804** 2021-11-02 13:30 UTC
Labels: duplicate, site:instagram

**Comment by johnconnorskynet** [comment] 2021-11-02 13:48
Sorry My bad. Left is:open in the search box. Thanks.
