### ISSUE TITLE
HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>);

### ISSUE THREAD

**Issue by YoruNeko33** [yt-dlp/yt-dlp#8533] opened 2023-11-05 19:26 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

lunarsol@lunarsol-CG8270:~/Documents$ sudo ./yt-dlp_linux -u r******t@gmail.com -p ***** -P "/home/lunarsol/Vidéos" -o "%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s" "https://www.udemy.com/hacking-ethique-le-cours-complet/"
[udemy:course] Downloading login popup
ERROR: [udemy:course] hacking-ethique-le-cours-complet: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
lunarsol@lunarsol-CG8270:~/Documents$ yt-dlp_linux -U
yt-dlp_linux : commande introuvable
lunarsol@lunarsol-CG8270:~/Documents$ ./yt-dlp_linux -U
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 6d30ea8e0f299a91c22161e87746162e3ff4d34df78a7f5dc00d51d02086f908
yt-dlp is up to date (stable@2023.10.13)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.2.0-36-generic-x86_64-with-glibc2.35 (OpenSSL 3.1.3 19 Sep 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.43.2, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 6d30ea8e0f299a91c22161e87746162e3ff4d34df78a7f5dc00d51d02086f908
yt-dlp is up to date (stable@2023.10.13)
```

**Comment by bashonly** [comment] 2023-11-05 22:53
Duplicate of #1164

**Closed by bashonly** 2023-11-05 22:53 UTC
Labels: site-bug, triage
