### ISSUE TITLE
Add photo album download support

### ISSUE THREAD

**Issue by feureau** [yt-dlp/yt-dlp#8360] opened 2023-10-16 04:28 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

With the addition of shorts and photo album to major social networking sites, most sites now supports posting both shorts (e.g. instagram reels) and album (e.g. tiktok album) however the support to download photo album seems to be spotty at best. For example, downloading tiktok album doesn't seem to work or it only downloads the first image and the music attached.

Please add full support to fully download photo album from major social network sites (eg. tiktok & instagram)

Thank you.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment] 2023-10-16 04:46
Downloading photos is out-of-scope

Duplicate of #6168, #6217

Look into [gallery-dl](https://github.com/mikf/gallery-dl)

**Closed by bashonly** 2023-10-16 04:46 UTC
Labels: enhancement, triage
