### ISSUE TITLE
SOCKS proxy error crashes the program, ignoring the --extractor-retries (a.k.a improve support for unstable proxies)

### ISSUE THREAD

**Issue by UnasZole** [yt-dlp/yt-dlp#6887] opened 2023-04-22 14:18 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Sometimes, one needs to use a proxy that is extremely unstable, and that may return errors for 80% of requests and work 20% of the time. Typically, when trying to download a geo-restricted video only available in very small countries with very few public proxies available.

yt-dlp has a nice "--extractor-retries" option that allows increasing the number of retries for standard network errors (socket timeout, connection reset by peer, etc.)
However, sometimes the proxy may even reply a malformed message to the SOCKS protocol layer, and in that cases it completely crashes the application, thus ignoring the --extractor-retries.

Errors raised by the SOCKS layer should be caught and handled as normal network errors.

Note that the logs below refer to a Youtube download, but the error comes from the SOCKS library that is global.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--proxy', 'socks4://80.80.164.164:10801', 'https://www.youtube.com/watch?v=r1CV2VKIp9k', '-f', '22', '--extractor-retries', '50', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.4.0-147-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'http': 'socks4://80.80.164.164:10801', 'https': 'socks4://80.80.164.164:10801'}
[debug] Loaded 1793 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=r1CV2VKIp9k
[youtube] r1CV2VKIp9k: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urlopen error [Errno 104] Connection reset by peer>
[youtube] r1CV2VKIp9k: Downloading android player API JSON
WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (1/50)...
[youtube] r1CV2VKIp9k: Downloading android player API JSON
WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (2/50)...
[youtube] r1CV2VKIp9k: Downloading android player API JSON
WARNING: [youtube] <urlopen error timed out>. Retrying (3/50)...
[youtube] r1CV2VKIp9k: Downloading android player API JSON
WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (4/50)...
[youtube] r1CV2VKIp9k: Downloading android player API JSON
WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (5/50)...
[youtube] r1CV2VKIp9k: Downloading android player API JSON
WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (6/50)...
[youtube] r1CV2VKIp9k: Downloading android player API JSON
WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (7/50)...
[youtube] r1CV2VKIp9k: Downloading android player API JSON
[youtube] r1CV2VKIp9k: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: <urlopen error timed out>
[youtube] r1CV2VKIp9k: Downloading web player API JSON
WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (1/50)...
[youtube] r1CV2VKIp9k: Downloading web player API JSON
WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (2/50)...
[youtube] r1CV2VKIp9k: Downloading web player API JSON
WARNING: [youtube] <urlopen error [Errno 104] Connection reset by peer>. Retrying (3/50)...
[youtube] r1CV2VKIp9k: Downloading web player API JSON
WARNING: [youtube] <urlopen error timed out>. Retrying (4/50)...
[youtube] r1CV2VKIp9k: Downloading web player API JSON
ERROR: 8 bytes missing
Traceback (most recent call last):
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 3940, in _real_extract
    webpage, master_ytcfg, player_responses, player_url = self._download_player_responses(url, smuggled_data, video_id, webpage_url)
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 3908, in _download_player_responses
    player_responses, player_url = self._extract_player_responses(
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 3588, in _extract_player_responses
    pr = initial_pr if client == 'web' and initial_pr else self._extract_player_response(
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 3508, in _extract_player_response
    return self._extract_response(
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 917, in _extract_response
    response = self._call_api(
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 593, in _call_api
    return self._download_json(
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1048, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1012, in download_handle
    res = self._download_webpage_handle(
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 882, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 821, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3743, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/utils.py", line 1555, in https_open
    return self.do_open(
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/utils.py", line 1522, in connect
    self.sock.connect((self.host, self.port))
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/socks.py", line 264, in connect
    self._make_proxy(socket.socket.connect, address)
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/socks.py", line 260, in _make_proxy
    setup_funcs[self._proxy.type](address)
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/socks.py", line 161, in _setup_socks4
    version, resp_code, dstport, dsthost = struct.unpack('!BBHI', self.recvall(8))
  File "/snap/yt-dlp/233/lib/python3.10/site-packages/yt_dlp/socks.py", line 120, in recvall
    raise EOFError(f'{cnt - len(data)} bytes missing')
EOFError: 8 bytes missing
```

**Comment by suger520HT** [comment] 2023-04-22 16:16
I'm in the same situation as you

**Comment by pukkandan** [comment] 2023-04-22 16:43
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/6627

**Closed by pukkandan** 2023-04-22 16:43 UTC
Labels: bug, triage

**Comment by UnasZole** [comment] 2023-04-22 17:42
@pukkandan If you say so !
I don't see much in common in the stack traces involved, but I'm not familiar with this code so you probably know better.
Also not sure why an uncaught exception qualifies as "enhancement" and not bug.

For anyone else fighting to download big videos over an unstable proxy, so far, the only workaround I've found to get the data downloaded (after a very, very long while and several thousands of retries) is to re-run the yt-dlp call in an infinite loop : 
`while ! yt-dlp --proxy socks4://80.80.164.164:10801 --retries 50 --extractor-retries 50 https://www.youtube.com/watch?v=r1CV2VKIp9k -f 22 --verbose ; do echo "Retrying..." ; done`
And then let it run in my terminal for hours and hours until the full file is downloaded.

The idea is that, thankfully, the yt-dlp has proper error reporting : when terminated by the exception, the command returns a proper error status 1, whereas it returns a success status 0 when download completes, so the while loop allows restarting the command on every crash until completion.
And thankfully as well, yt-dlp's default behaviour is to resume downloads where it left off, so as long as the ".part" file is not deleted, new contents end up getting appended.

**Comment by pukkandan** [comment] 2023-04-22 22:16
> Also not sure why an uncaught exception qualifies as "enhancement" and not bug.

As explained in the other issue, the option was never designed to retry on network errors from client side, only on known errors from the extractor's server side - hence the option name. So this is a request to add another retry for network errors.

**Comment by UnasZole** [comment] 2023-04-22 22:22
Thanks, that makes more sense !

And indeed, the same error occurs not only within the extractor, but also within the downloader.
So it would indeed make sense to have a separate and shared handling for network errors :-)
