### ISSUE TITLE
can not retrieve the list of youtube playlists

### ISSUE THREAD

**Issue by mast3rz3ro** [yt-dlp/yt-dlp#11671] opened 2024-11-28 19:35 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Hi there,

I'm trying to retrieve list of all playlists titles available inside particular YouTube channel, however I'm not able to get it working.

Passing the playlist link seems to be just working, but I need to archive the entire with observing the videos with their own playlists.

Best regards.
Thanks you!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://youtube.com/@_noisecode', '--print', 'playlist_title']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (pip)
[debug] Python 3.11.9 (CPython aarch64 64bit) - Linux-4.14.336-perf-gbd8f1c4cdb06-dirty-aarch64-with-libc (OpenSSL 3.3.2 3 Sep 2024, libc)
[debug] exe versions: ffmpeg 6.1.2 (setts), ffprobe 6.1.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2024.09.27 from yt-dlp/yt-dlp
Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[youtube:tab] Extracting URL: https://youtube.com/@_noisecode
[youtube:tab] @_noisecode: Downloading webpage
[debug] [youtube:tab] Selected tab: 'videos' (videos), Requested tab: ''
[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[download] Downloading playlist: Logan Smith - Videos
[youtube:tab] Playlist Logan Smith - Videos: Downloading 13 items of 13
[download] Downloading item 1 of 13
[youtube] Extracting URL: https://www.youtube.com/watch?v=KWB-gDVuy_I
[youtube] KWB-gDVuy_I: Downloading webpage
[youtube] KWB-gDVuy_I: Downloading ios player API JSON
[youtube] KWB-gDVuy_I: Downloading web creator player API JSON
[youtube] KWB-gDVuy_I: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] KWB-gDVuy_I: Downloading 1 format(s): 616+251
Logan Smith - Videos
[download] Downloading item 2 of 13
[youtube] Extracting URL: https://www.youtube.com/watch?v=SmlLdd1Q2V8
[youtube] SmlLdd1Q2V8: Downloading webpage
[youtube] SmlLdd1Q2V8: Downloading ios player API JSON
[youtube] SmlLdd1Q2V8: Downloading web creator player API JSON
[youtube] SmlLdd1Q2V8: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] SmlLdd1Q2V8: Downloading 1 format(s): 616+251
Logan Smith - Videos
[download] Downloading item 3 of 13
[youtube] Extracting URL: https://www.youtube.com/watch?v=wU8hQvU8aKM
[youtube] wU8hQvU8aKM: Downloading webpage
[youtube] wU8hQvU8aKM: Downloading ios player API JSON
[youtube] wU8hQvU8aKM: Downloading web creator player API JSON
[youtube] wU8hQvU8aKM: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] wU8hQvU8aKM: Downloading 1 format(s): 303+251
Logan Smith - Videos
[download] Downloading item 4 of 13
[youtube] Extracting URL: https://www.youtube.com/watch?v=8j_FbjiowvE
[youtube] 8j_FbjiowvE: Downloading webpage
[youtube] 8j_FbjiowvE: Downloading ios player API JSON
[youtube] 8j_FbjiowvE: Downloading web creator player API JSON
[youtube] 8j_FbjiowvE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 8j_FbjiowvE: Downloading 1 format(s): 299+251
Logan Smith - Videos
[download] Downloading item 5 of 13
[youtube] Extracting URL: https://www.youtube.com/watch?v=algDLvbl1YY
[youtube] algDLvbl1YY: Downloading webpage
[youtube] algDLvbl1YY: Downloading ios player API JSON
[youtube] algDLvbl1YY: Downloading web creator player API JSON
[youtube] algDLvbl1YY: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] algDLvbl1YY: Downloading 1 format(s): 303+251
Logan Smith - Videos
[download] Downloading item 6 of 13
[youtube] Extracting URL: https://www.youtube.com/watch?v=s5S2Ed5T-dc
[youtube] s5S2Ed5T-dc: Downloading webpage
[youtube] s5S2Ed5T-dc: Downloading ios player API JSON
[youtube] s5S2Ed5T-dc: Downloading web creator player API JSON
[youtube] s5S2Ed5T-dc: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] s5S2Ed5T-dc: Downloading 1 format(s): 303+251
Logan Smith - Videos
[download] Downloading item 7 of 13
[youtube] Extracting URL: https://www.youtube.com/watch?v=SqT5YglW3qU
[youtube] SqT5YglW3qU: Downloading webpage
[youtube] SqT5YglW3qU: Downloading ios player API JSON
[youtube] SqT5YglW3qU: Downloading web creator player API JSON
[youtube] SqT5YglW3qU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] SqT5YglW3qU: Downloading 1 format(s): 303+251
Logan Smith - Videos
[download] Downloading item 8 of 13
[youtube] Extracting URL: https://www.youtube.com/watch?v=6c7pZYP_iIE
[youtube] 6c7pZYP_iIE: Downloading webpage
[youtube] 6c7pZYP_iIE: Downloading ios player API JSON
[youtube] 6c7pZYP_iIE: Downloading web creator player API JSON
[youtube] 6c7pZYP_iIE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 6c7pZYP_iIE: Downloading 1 format(s): 299+251
Logan Smith - Videos
[download] Downloading item 9 of 13
[youtube] Extracting URL: https://www.youtube.com/watch?v=A4cKi7PTJSs
[youtube] A4cKi7PTJSs: Downloading webpage
[youtube] A4cKi7PTJSs: Downloading ios player API JSON
[youtube] A4cKi7PTJSs: Downloading web creator player API JSON
[youtube] A4cKi7PTJSs: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] A4cKi7PTJSs: Downloading 1 format(s): 303+251
Logan Smith - Videos
[download] Downloading item 10 of 13
[youtube] Extracting URL: https://www.youtube.com/watch?v=AWmcxqYTNK4
[youtube] AWmcxqYTNK4: Downloading webpage
[youtube] AWmcxqYTNK4: Downloading ios player API JSON
[youtube] AWmcxqYTNK4: Downloading web creator player API JSON
[youtube] AWmcxqYTNK4: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] AWmcxqYTNK4: Downloading 1 format(s): 299+251
Logan Smith - Videos
[download] Downloading item 11 of 13
[youtube] Extracting URL: https://www.youtube.com/watch?v=vvXI_0AgY3M
[youtube] vvXI_0AgY3M: Downloading webpage
[youtube] vvXI_0AgY3M: Downloading ios player API JSON
[youtube] vvXI_0AgY3M: Downloading web creator player API JSON
[youtube] vvXI_0AgY3M: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] vvXI_0AgY3M: Downloading 1 format(s): 299+251
Logan Smith - Videos
[download] Downloading item 12 of 13
[youtube] Extracting URL: https://www.youtube.com/watch?v=WlUVRl5GUVE
[youtube] WlUVRl5GUVE: Downloading webpage
[youtube] WlUVRl5GUVE: Downloading ios player API JSON
[youtube] WlUVRl5GUVE: Downloading web creator player API JSON
[youtube] WlUVRl5GUVE: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] WlUVRl5GUVE: Downloading 1 format(s): 299+251
Logan Smith - Videos
[download] Downloading item 13 of 13
[youtube] Extracting URL: https://www.youtube.com/watch?v=_Od0wIt5FRU
[youtube] _Od0wIt5FRU: Downloading webpage
[youtube] _Od0wIt5FRU: Downloading ios player API JSON
[youtube] _Od0wIt5FRU: Downloading web creator player API JSON
[youtube] _Od0wIt5FRU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] _Od0wIt5FRU: Downloading 1 format(s): 299+251
Logan Smith - Videos
[download] Finished downloading playlist: Logan Smith - Videos
```

**Comment by bashonly** [comment] 2024-11-28 20:12
Duplicate of #11524

[Update to nightly](https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-nightly)

**Closed by bashonly** 2024-11-28 20:12 UTC
Labels: site-bug, triage

**Comment by heyeanne34** [comment] 2024-11-29 06:57
hey @mast3rz3ro do you use proxy ? what do you use to get cookies? cuzz whenever i run my command it says WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] ATTFiY3oPGA: Downloading ios player API JSON is still there everytime but yours doesnt have any
