### ISSUE TITLE
yt-dlp finds ffmpeg, but ffmpeg reported as being not installed

### ISSUE THREAD

**Issue by monolied** [yt-dlp/yt-dlp#4273] opened 2022-07-04 21:15 UTC
### Checklist

- [x] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Provide a description that is worded well enough to be understood

First of all: Sorry for reporting this as a broken site. I couldn't for the life of me find a category for an ordinary bug report. Also the "choose a different type." link on top does not list any. This was the closest I found.
Also, I did the -U - update before, so it was the latest version as of today, as you can see in the log.

The issue: At first it looks like ffmpeg was found and versions checked:

```
[debug] Checking exe version: "C:/Program Files/_media/TwitchLeech\ffmpeg" -bsfs
[debug] Checking exe version: "C:/Program Files/_media/TwitchLeech\ffprobe" -bsfs
[debug] Checking exe version: "C:/Program Files/_media/TwitchLeech\avprobe" -bsfs
[debug] exe versions: ffmpeg 5.0-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
```

But then this:

`ERROR: You have requested downloading the video partially, but ffmpeg is not installed. Aborting`

Also I could swear that I managed to download a piece before, with the same setup and versions. Alas, I don't have the output of that run anymore.

I tried different versions of ffmpeg, to no avail:

```
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: "C:/Program Files/_media/ffmpeg/bin\ffmpeg" -bsfs
[debug] Checking exe version: "C:/Program Files/_media/ffmpeg/bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
```
(This was a somewhat earlier attempt, with a different ffmpeg and yt-dlp, however with the same result and error message.)

I also tried both backwards and forwards slashes with the ffmpeg-location.

Thanks in advance for any insights offered.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--verbose', '--continue', '--download-sections', '*00:00:00.00-05:00:10.00', '--split-chapters', '--ffmpeg-location', 'C:/Program Files/_media/TwitchLeech', 'https://www.twitch.tv/videos/1515612408']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error cp1252 (No ANSI), screen cp1252 (No ANSI)
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0 
[debug] Checking exe version: "C:/Program Files/_media/TwitchLeech\ffmpeg" -bsfs
[debug] Checking exe version: "C:/Program Files/_media/TwitchLeech\ffprobe" -bsfs
[debug] Checking exe version: "C:/Program Files/_media/TwitchLeech\avprobe" -bsfs
[debug] exe versions: ffmpeg 5.0-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [twitch:vod] Extracting URL: https://www.twitch.tv/videos/1515612408
[twitch:vod] 1515612408: Downloading stream metadata GraphQL
[twitch:vod] 1515612408: Downloading video access token GraphQL
[twitch:vod] 1515612408: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] v1515612408: Downloading 1 format(s): 1080p60
[info] v1515612408: Downloading 1 time ranges: 0-18010
ERROR: You have requested downloading the video partially, but ffmpeg is not installed. Aborting
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 921, in main
  File "yt_dlp\__init__.py", line 913, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3249, in download
  File "yt_dlp\YoutubeDL.py", line 3225, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1411, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1420, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1504, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1561, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2630, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3008, in process_info
  File "yt_dlp\YoutubeDL.py", line 962, in report_error
  File "yt_dlp\YoutubeDL.py", line 894, in trouble
```

**Comment by pukkandan** [comment] 2022-07-05 01:46
--ffmpeg-location only works for postprocessing. Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2191

**Closed by pukkandan** 2022-07-05 01:46 UTC
Labels: site-bug, triage
