### ISSUE TITLE
youtube, get error information,but download still works

### ISSUE THREAD

**Issue by Gloster10** [yt-dlp/yt-dlp#9407] opened 2024-03-09 21:56 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

During download, get an error message, refer to verbose data. But download started as proper as usual, do not know whether it is an issue.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vf', 'b', '-o', '%(title)s.%(ext)s', '--no-playlist', '-N', '8', 'https://www.youtube.com/watch?v=uI-WD5BP1aA&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=344&pp=iAQB']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-21-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.37.2, urllib3-2.2.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=uI-WD5BP1aA&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=344&pp=iAQB
[youtube:tab] Downloading just the video uI-WD5BP1aA because of --no-playlist
[youtube] Extracting URL: https://www.youtube.com/watch?v=uI-WD5BP1aA
[youtube] uI-WD5BP1aA: Downloading webpage
[youtube] uI-WD5BP1aA: Downloading ios player API JSON
[youtube] uI-WD5BP1aA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] uI-WD5BP1aA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] uI-WD5BP1aA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] uI-WD5BP1aA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] [debug] Command-line config: ['-vf', 'b', '-o', '%(title)s.%(ext)s', '--no-playlist', '-N', '8', 'https://www.youtube.com/watch?v=uI-WD5BP1aA&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=344&pp=iAQB']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-21-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.37.2, urllib3-2.2.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=uI-WD5BP1aA&list=PLHxc_q5EHiHQX3VxMaUDOdM8NMSTyRjkZ&index=344&pp=iAQB
[youtube:tab] Downloading just the video uI-WD5BP1aA because of --no-playlist
[youtube] Extracting URL: https://www.youtube.com/watch?v=uI-WD5BP1aA
[youtube] uI-WD5BP1aA: Downloading webpage
[youtube] uI-WD5BP1aA: Downloading ios player API JSON
[youtube] uI-WD5BP1aA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] uI-WD5BP1aA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] uI-WD5BP1aA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] uI-WD5BP1aA: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig bhgus62vmm7qmE8I => -8dL8pTw1ijNeg
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig XlQu7PBWUWqTrSSZ => CIrvdba0Iv6lcg
[youtube] uI-WD5BP1aA: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] uI-WD5BP1aA: Downloading 1 format(s): 18
[debug] Invoking http downloader on "https://rr2---sn-uxax4vopj5qx-q0n6.googlevideo.com/videoplayback?expire=1710039039&ei=n8vsZcmxDO686dsP2K-ByA0&ip=80.171.183.208&id=o-ACQfY46LKOycv6NMpBaAahZKg89RtemLUcZIDy-TcU4s&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=sN&mm=31%2C29&mn=sn-uxax4vopj5qx-q0n6%2Csn-4g5ednd7&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=18&initcwndbps=1221250&spc=UWF9fxKKxQgvC3u8RZpejnvWPsyv7A-0UKKVutETJ8ZaeyA&vprv=1&svpuc=1&mime=video%2Fmp4&ns=0Hdqh0CGpar_LiCW0E8q7SYQ&cnr=14&ratebypass=yes&dur=5018.180&lmt=1696811476550418&mt=1710017113&fvip=5&fexp=24007246&beids=24350307&c=WEB&sefc=1&txp=6308224&n=-8dL8pTw1ijNeg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRgIhAMlIHczuIO_FEMbVbwKnYjsI_Kj7-XaYN5h0oBz9U_wtAiEA9fzQTQxaxfhgwnpK-VnLhIELwn1oIsNdcD-ZINs1WxQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=APTiJQcwRgIhAOS3OwChn2AYuLlHLjwhZjFkAhjliV2XwWt7JEmf1aT2AiEArTZrwBaB3NYkYmFlQzaXX0St3bWu19qjKc_R5-OQRp4%3D"
[download] Destination: Silent Night, Bloody Night ｜ Thriller ｜ Ganzer Film auf Deutsch.mp4
[download]  36.8% of  231.90MiB at    6.76MiB/s ETA 00:21^C
ERROR: Interrupted by user
Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig bhgus62vmm7qmE8I => -8dL8pTw1ijNeg
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig XlQu7PBWUWqTrSSZ => CIrvdba0Iv6lcg
[youtube] uI-WD5BP1aA: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] uI-WD5BP1aA: Downloading 1 format(s): 18
[debug] Invoking http downloader on "https://rr2---sn-uxax4vopj5qx-q0n6.googlevideo.com/videoplayback?expire=1710039039&ei=n8vsZcmxDO686dsP2K-ByA0&ip=80.171.183.208&id=o-ACQfY46LKOycv6NMpBaAahZKg89RtemLUcZIDy-TcU4s&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=sN&mm=31%2C29&mn=sn-uxax4vopj5qx-q0n6%2Csn-4g5ednd7&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=18&initcwndbps=1221250&spc=UWF9fxKKxQgvC3u8RZpejnvWPsyv7A-0UKKVutETJ8ZaeyA&vprv=1&svpuc=1&mime=video%2Fmp4&ns=0Hdqh0CGpar_LiCW0E8q7SYQ&cnr=14&ratebypass=yes&dur=5018.180&lmt=1696811476550418&mt=1710017113&fvip=5&fexp=24007246&beids=24350307&c=WEB&sefc=1&txp=6308224&n=-8dL8pTw1ijNeg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRgIhAMlIHczuIO_FEMbVbwKnYjsI_Kj7-XaYN5h0oBz9U_wtAiEA9fzQTQxaxfhgwnpK-VnLhIELwn1oIsNdcD-ZINs1WxQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=APTiJQcwRgIhAOS3OwChn2AYuLlHLjwhZjFkAhjliV2XwWt7JEmf1aT2AiEArTZrwBaB3NYkYmFlQzaXX0St3bWu19qjKc_R5-OQRp4%3D"
[download] Destination: Silent Night, Bloody Night ｜ Thriller ｜ Ganzer Film auf Deutsch.mp4
[download]  36.8% of  231.90MiB at    6.76MiB/s ETA 00:21^C
ERROR: Interrupted by user
```

**Comment by seproDev** [comment] 2024-03-09 21:57
Duplicate of #9316

Update to nightly

if you are using the exe/zip:
```
yt-dlp --update-to nightly
```

or if you installed with pip:
```
python3 -m pip install -U --pre yt-dlp
```

**Closed by seproDev** 2024-03-09 21:57 UTC
Labels: site-bug, triage
