### ISSUE TITLE
[Youtube] Option --download-section downloads audio only on some videos

### ISSUE THREAD

**Issue by DanSM-5** [yt-dlp/yt-dlp#8066] opened 2023-09-09 03:32 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

# Description

Trying to download certain videos from youtube using `--download-segment` flag only downloads audio if range doesn't start with 0 (e.g. `*0-5` works but `*5-10` doesn't give video). Not all videos are affected.

# Steps to reproduce

1. Download a video segment by time range e.g. 5 seconds with a start time other than 0
```bash
# Smash Bros parody
yt-dlp https://www.youtube.com/watch?v=1lKPu5jesu0 --download-sections "*60-65" --force-keyframes-at-cuts
# or cats video
yt-dlp https://www.youtube.com/watch?v=y0sF5xhGreA --download-sections "*60-65" --force-keyframes-at-cuts
```
2. Wait for video to finish download
3. Play video. Observe it has no video, just audio.

# Expected result
Downloaded videos have both video and audio 

# Actual result
Some videos only download audio if the start time of the segment is any number different than 0.

# Library versions tested
## Windows
- yt-dlp `2023.07.06`. Also tested `2023.09.08.125456` (nightly)
- ffmpeg `6.0-essentials_build-www.gyan.dev`
## Termux (android)
- yt-dlp `2023.07.06`
- ffmpeg `6.0`
## Ubuntu (WSL)
- yt-dlp `2023.07.06`
- ffmpeg `5.1.3`

# Additional notes
- I think this is related to hls or ts containers because on the affected videos I can see logs like these `[hls @ 0xb9a6c0] HLS request... ...seg.ts`. Other non-affected videos do not display those logs.

- The warning that appears at the start of the verbose log
```
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```
not always appeared in my test on failing videos. I can't say it is related but working videos never showed the warning.

- All my tests were with segments between 5 to 15 seconds of length. Didn't try anything shorter or larger.

Here is the file with the full log output. I can't add complete in the box below because github complains the comment has more than 65536 characters.
[yt-dlp_download-segments_log.txt](https://github.com/yt-dlp/yt-dlp/files/12564510/yt-dlp_download-segments_log.txt)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=1lKPu5jesu0', '-vU', '--download-sections', '*60-65']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 5.1.3 (setts), ffprobe 5.1.3
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=1lKPu5jesu0
[youtube] 1lKPu5jesu0: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 1lKPu5jesu0: Downloading ios player API JSON
[youtube] 1lKPu5jesu0: Downloading android player API JSON
[youtube] 1lKPu5jesu0: Downloading iframe API JS
[youtube] 1lKPu5jesu0: Downloading player 7ee36b0e
[youtube] 1lKPu5jesu0: Downloading web player API JSON
[youtube] 1lKPu5jesu0: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] 1lKPu5jesu0: Downloading initial data API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1lKPu5jesu0: Downloading 1 format(s): 616+251
[info] 1lKPu5jesu0: Downloading 1 time ranges: 60.0-65.0
[debug] Invoking ffmpeg downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1694246628/ei/hNL7ZJS5Ir_Hx_AP7MyS-AU/ip/154.47.29.10/id/d6528fbb98deb2ed/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D63495801%3Bdur%3D252.320%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1662001234516028/hls_chunk_host/rr4---sn-4g5lznl7.googlevideo.com/mh/uy/mm/31,29/mn/sn-4g5lznl7,sn-4g5edn6y/ms/au,rdu/mv/m/mvi/4/pl/26/initcwndbps/1451250/vprv/1/playlist_type/DVR/dover/13/txp/5532434/mt/1694224863/fvip/3/short_key/1/keepalive/yes/fexp/24007246/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,vprv,playlist_type/sig/AOq0QJ8wRQIhAONwYNOax-PpSvA1qAysz8CYPDcLO5ypLjIQpzK0kcrVAiAxZsLhHt_9cKI-tuL7zaWymkc1Z9i3h0M00tA5XEfdug%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRgIhAOOXJZRifS3s_hXvZFlz4KS5QmBmunIc-BaMHSX6eTGhAiEAt2eIOSCZM4LqgvfYVi-2FG8vtLlhbRpZiO2_vp0q0QE%3D/playlist/index.m3u8", "https://rr3---sn-4g5edn6y.googlevideo.com/videoplayback?expire=1694246629&ei=hdL7ZKDFCtGrx_APh86YgAY&ip=154.47.29.10&id=o-AGnDyyrO5Vsb7Ge1bqnsvxcMemcp5cnE2RZAgtxKITc7&itag=251&source=youtube&requiressl=yes&mh=uy&mm=31%2C26&mn=sn-4g5edn6y%2Csn-5hnekn7d&ms=au%2Conr&mv=m&mvi=3&pl=26&initcwndbps=1987500&spc=UWF9fy0XZqxn5BN6JvUW0NvWKyRZgvQ&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=4037075&dur=252.341&lmt=1656042252594464&mt=1694224619&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJMLMIxnpphyMnj2agddKjx6LuHHyJbKF89-3oqjm3W3AiEAowKN-dsRrCtcAaW2ZTjktroNEarHJZZsdj24OY2tFZQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgI5sKdKljKus4RQ67sgvtVqupbx1Xvlp_oH0JMh9IYboCIQDpYSArAPuXM8aelZoricbQkccyiqx4yvkVRvHL4sjPPA%3D%3D"
[download] Destination: Doom vs Smash Bros [1lKPu5jesu0].webm
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
' -ss 60.0 -t 5.0 -i https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1694246628/ei/hNL7ZJS5Ir_Hx_AP7MyS-AU/ip/154.47.29.10/id/d6528fbb98deb2ed/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D63495801%3Bdur%3D252.320%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1662001234516028/hls_chunk_host/rr4---sn-4g5lznl7.googlevideo.com/mh/uy/mm/31,29/mn/sn-4g5lznl7,sn-4g5edn6y/ms/au,rdu/mv/m/mvi/4/pl/26/initcwndbps/1451250/vprv/1/playlist_type/DVR/dover/13/txp/5532434/mt/1694224863/fvip/3/short_key/1/keepalive/yes/fexp/24007246/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,vprv,playlist_type/sig/AOq0QJ8wRQIhAONwYNOax-PpSvA1qAysz8CYPDcLO5ypLjIQpzK0kcrVAiAxZsLhHt_9cKI-tuL7zaWymkc1Z9i3h0M00tA5XEfdug%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRgIhAOOXJZRifS3s_hXvZFlz4KS5QmBmunIc-BaMHSX6eTGhAiEAt2eIOSCZM4LqgvfYVi-2FG8vtLlhbRpZiO2_vp0q0QE%3D/playlist/index.m3u8 -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
' -ss 60.0 -t 5.0 -i 'https://rr3---sn-4g5edn6y.googlevideo.com/videoplayback?expire=1694246629&ei=hdL7ZKDFCtGrx_APh86YgAY&ip=154.47.29.10&id=o-AGnDyyrO5Vsb7Ge1bqnsvxcMemcp5cnE2RZAgtxKITc7&itag=251&source=youtube&requiressl=yes&mh=uy&mm=31%2C26&mn=sn-4g5edn6y%2Csn-5hnekn7d&ms=au%2Conr&mv=m&mvi=3&pl=26&initcwndbps=1987500&spc=UWF9fy0XZqxn5BN6JvUW0NvWKyRZgvQ&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=4037075&dur=252.341&lmt=1656042252594464&mt=1694224619&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJMLMIxnpphyMnj2agddKjx6LuHHyJbKF89-3oqjm3W3AiEAowKN-dsRrCtcAaW2ZTjktroNEarHJZZsdj24OY2tFZQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgI5sKdKljKus4RQ67sgvtVqupbx1Xvlp_oH0JMh9IYboCIQDpYSArAPuXM8aelZoricbQkccyiqx4yvkVRvHL4sjPPA%3D%3D' -c copy -map 0:0 -map 1:0 -f webm 'file:Doom vs Smash Bros [1lKPu5jesu0].webm.part'
ffmpeg version 5.1.3 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.3.0 (GCC)
  configuration: --disable-static --prefix=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-5.1.3 --target_os=linux --arch=x86_64 --pkg-config=pkg-config --enable-gpl --enable-version3 --disable-nonfree --enable-shared --enable-pic --disable-small --enable-runtime-cpudetect --disable-gray --enable-swscale-alpha --enable-hardcoded-tables --enable-safe-bitstream-reader --enable-pthreads --disable-w32threads --disable-os2threads --enable-network --enable-pixelutils --datadir=/nix/store/jh8h7qypbsj9nbjla1nsjs45gfspbn9n-ffmpeg-5.1.3-data/share/ffmpeg --enable-ffmpeg --disable-ffplay --enable-ffprobe --bindir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-5.1.3-bin/bin --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-avutil --enable-postproc --enable-swresample --enable-swscale --libdir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-5.1.3-lib/lib --incdir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-5.1.3-dev/include --enable-doc --enable-htmlpages --enable-manpages --mandir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-5.1.3-man/share/man --enable-podpages --enable-txtpages --docdir=/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-ffmpeg-5.1.3-doc/share/doc/ffmpeg --enable-alsa --enable-bzlib --disable-libcelt --disable-cuda --disable-cuda-llvm --enable-libdav1d --disable-libfdk-aac --disable-libflite --enable-fontconfig --enable-libfreetype --disable-frei0r --disable-libfribidi --disable-libgme --enable-gnutls --disable-libgsm --disable-ladspa --enable-libmp3lame --disable-libaom --enable-libass --disable-libbluray --disable-libbs2b --disable-libdc1394 --enable-libdrm --enable-iconv --disable-libjack --disable-libmfx --disable-libmodplug --disable-libmysofa --enable-libopus --disable-librsvg --enable-libsrt --enable-libssh --disable-libtensorflow --enable-libtheora --disable-libv4l2 --disable-v4l2-m2m --enable-vaapi --enable-vdpau --enable-libvorbis --disable-libvmaf --enable-libvpx --disable-libwebp --disable-xlib --disable-libxcb --disable-libxcb-shm --disable-libxcb-xfixes --disable-libxcb-shape --disable-libxml2 --enable-lzma --enable-cuvid --enable-nvdec --enable-nvenc --disable-openal --disable-opencl --disable-libopencore-amrnb --disable-opengl --disable-libopenh264 --disable-libopenjpeg --disable-libopenmpt --enable-libpulse --disable-librav1e --disable-libsvtav1 --disable-librtmp --enable-sdl2 --enable-libsoxr --enable-libspeex --disable-libvidstab --disable-libvo-amrwbenc --enable-libx264 --enable-libx265 --disable-libxavs --enable-libxvid --disable-libzmq --enable-libzimg --enable-zlib --disable-vulkan --disable-libglslang --disable-libsmbclient --disable-debug --enable-optimizations --disable-extra-warnings --disable-stripping
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[tcp @ 0xb9f440] Starting connection attempt to 142.251.36.46 port 443
[tcp @ 0xb9f440] Successfully connected to 142.251.36.46 port 443
[hls @ 0xb9a6c0] Skip ('#EXT-X-VERSION:6')
[hls @ 0xb9a6c0] HLS request for url 'https://rr4---sn-4g5lznl7.googlevideo.com/videoplayback/id/d6528fbb98deb2ed/itag/616/source/youtube/expire/1694246628/ei/hNL7ZJS5Ir_Hx_AP7MyS-AU/ip/154.47.29.10/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D63495801%3Bdur%3D252.320%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1662001234516028/hls_chunk_host/rr4---sn-4g5lznl7.googlevideo.com/mh/uy/mm/31,29/mn/sn-4g5lznl7,sn-4g5edn6y/ms/au,rdu/mv/m/mvi/4/pl/26/initcwndbps/1451250/vprv/1/playlist_type/DVR/txp/5532434/mt/1694224863/fvip/3/keepalive/yes/fexp/24007246/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,vprv,playlist_type/sig/AOq0QJ8wRQIhAONwYNOax-PpSvA1qAysz8CYPDcLO5ypLjIQpzK0kcrVAiAxZsLhHt_9cKI-tuL7zaWymkc1Z9i3h0M00tA5XEfdug%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRgIhAOOXJZRifS3s_hXvZFlz4KS5QmBmunIc-BaMHSX6eTGhAiEAt2eIOSCZM4LqgvfYVi-2FG8vtLlhbRpZiO2_vp0q0QE%3D/playlist/index.m3u8/govp/slices%3D0-284863/gosq/0?is=1&file=seg.ts', offset 0, playlist 0
[hls @ 0xb9a6c0] Opening 'https://rr4---sn-4g5lznl7.googlevideo.com/videoplayback/id/d6528fbb98deb2ed/itag/616/source/youtube/expire/1694246628/ei/hNL7ZJS5Ir_Hx_AP7MyS-AU/ip/154.47.29.10/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D63495801%3Bdur%3D252.320%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1662001234516028/hls_chunk_host/rr4---sn-4g5lznl7.googlevideo.com/mh/uy/mm/31,29/mn/sn-4g5lznl7,sn-4g5edn6y/ms/au,rdu/mv/m/mvi/4/pl/26/initcwndbps/1451250/vprv/1/playlist_type/DVR/txp/5532434/mt/1694224863/fvip/3/keepalive/yes/fexp/24007246/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,vprv,playlist_type/sig/AOq0QJ8wRQIhAONwYNOax-PpSvA1qAysz8CYPDcLO5ypLjIQpzK0kcrVAiAxZsLhHt_9cKI-tuL7zaWymkc1Z9i3h0M00tA5XEfdug%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRgIhAOOXJZRifS3s_hXvZFlz4KS5QmBmunIc-BaMHSX6eTGhAiEAt2eIOSCZM4LqgvfYVi-2FG8vtLlhbRpZiO2_vp0q0QE%3D/playlist/index.m3u8/govp/slices%3D0-284863/gosq/0?is=1&file=seg.ts' for reading

...

Input file #0 (https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1694246628/ei/hNL7ZJS5Ir_Hx_AP7MyS-AU/ip/154.47.29.10/id/d6528fbb98deb2ed/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D63495801%3Bdur%3D252.320%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1662001234516028/hls_chunk_host/rr4---sn-4g5lznl7.googlevideo.com/mh/uy/mm/31,29/mn/sn-4g5lznl7,sn-4g5edn6y/ms/au,rdu/mv/m/mvi/4/pl/26/initcwndbps/1451250/vprv/1/playlist_type/DVR/dover/13/txp/5532434/mt/1694224863/fvip/3/short_key/1/keepalive/yes/fexp/24007246/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,vprv,playlist_type/sig/AOq0QJ8wRQIhAONwYNOax-PpSvA1qAysz8CYPDcLO5ypLjIQpzK0kcrVAiAxZsLhHt_9cKI-tuL7zaWymkc1Z9i3h0M00tA5XEfdug%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRgIhAOOXJZRifS3s_hXvZFlz4KS5QmBmunIc-BaMHSX6eTGhAiEAt2eIOSCZM4LqgvfYVi-2FG8vtLlhbRpZiO2_vp0q0QE%3D/playlist/index.m3u8):
  Input stream #0:0 (video): 0 packets read (0 bytes); 
  Total: 0 packets (0 bytes) demuxed
Input file #1 (https://rr3---sn-4g5edn6y.googlevideo.com/videoplayback?expire=1694246629&ei=hdL7ZKDFCtGrx_APh86YgAY&ip=154.47.29.10&id=o-AGnDyyrO5Vsb7Ge1bqnsvxcMemcp5cnE2RZAgtxKITc7&itag=251&source=youtube&requiressl=yes&mh=uy&mm=31%2C26&mn=sn-4g5edn6y%2Csn-5hnekn7d&ms=au%2Conr&mv=m&mvi=3&pl=26&initcwndbps=1987500&spc=UWF9fy0XZqxn5BN6JvUW0NvWKyRZgvQ&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=4037075&dur=252.341&lmt=1656042252594464&mt=1694224619&fvip=5&keepalive=yes&fexp=24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJMLMIxnpphyMnj2agddKjx6LuHHyJbKF89-3oqjm3W3AiEAowKN-dsRrCtcAaW2ZTjktroNEarHJZZsdj24OY2tFZQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgI5sKdKljKus4RQ67sgvtVqupbx1Xvlp_oH0JMh9IYboCIQDpYSArAPuXM8aelZoricbQkccyiqx4yvkVRvHL4sjPPA%3D%3D):
  Input stream #1:0 (audio): 750 packets read (243347 bytes); 
  Total: 750 packets (243347 bytes) demuxed
Output file #0 (file:Doom vs Smash Bros [1lKPu5jesu0].webm.part):
  Output stream #0:0 (video): 0 packets muxed (0 bytes); 
  Output stream #0:1 (audio): 749 packets muxed (243055 bytes); 
  Total: 749 packets (243055 bytes) muxed
[AVIOContext @ 0x1439b40] Statistics: 249034 bytes written, 0 seeks, 1 writeouts
[AVIOContext @ 0x7f1aa001b580] Statistics: 27866862 bytes read, 0 seeks
[AVIOContext @ 0x7f1aa0633100] Statistics: 20692677 bytes read, 0 seeks
[AVIOContext @ 0xeb4f80] Statistics: 48096 bytes read, 0 seeks
[AVIOContext @ 0x1121d00] Statistics: 278528 bytes read, 1 seeks

[download] 100% of  243.20KiB in 00:00:44 at 5.41KiB/s
```

**Comment by bashonly** [comment] 2023-09-09 03:37
Duplicate of #7824

ffmpeg bug

Use `-S proto:https` or `--extractor-args "youtube:player_client=android,web"` to avoid the iOS m3u8 formats

**Closed by bashonly** 2023-09-09 03:37 UTC
Labels: site-bug, triage
