### ISSUE TITLE
There is an error when loading videos

### ISSUE THREAD

**Issue by xxkillaxx** [yt-dlp/yt-dlp#7208] opened 2023-06-02 20:29 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

On June 2nd, an error occurred while uploading a video file. I can assist you in troubleshooting the issue.

from yt_dlp import YoutubeDL

urls="https://youtu.be/QWfjna0mKMU"

ydl_opts = {
    # reduces the several line of output to barest minimal and therefore, time
    'quiet': True,
    'noplaylist': True,
    'format': "best[height<=720]",
    'format': 'best[filesize<=2G]',
    # 'outtmpl': output_path,
    "playlist_items": "1",
}

with YoutubeDL(ydl_opts) as ydl:
    ydl.download([urls])

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
"C:\Program Files\Python310\python.exe" C:/Users/Administrator/Desktop/BOT_tg_TEST/test_down.py
Вошел в download_video!!!!
WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "QWfjna0mKMU"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "QWfjna0mKMU"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: Only images are available for download. use --list-formats to see them
ERROR: [youtube] QWfjna0mKMU: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2743, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] QWfjna0mKMU: Requested format is not available. Use --list-formats for a list of available formats

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\BOT_tg_TEST\test_down.py", line 20, in <module>
    ydl.download([urls])
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3369, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3344, in wrapper
    res = func(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1507, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1536, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1015, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 955, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] QWfjna0mKMU: Requested format is not available. Use --list-formats for a list of available formats

Process finished with exit code 1
```

**Comment by bashonly** [comment] 2023-06-02 20:32
Replace `'quiet': True,` with `'verbose': True,` in your `ydl_opts` and post verbose output

Possible duplicate of #7143

**Closed** 2023-06-03 00:50 UTC
Labels: duplicate, question, incomplete

**Comment by xxkillaxx** [comment] 2023-06-03 06:49
from yt_dlp import YoutubeDL

# urls="https://www.youtube.com/watch?v=QWfjna0mKMU"
urls="https://youtu.be/QWfjna0mKMU"

print("Вошел в download_video!!!!")
max_size = 2040109465
aiogram_size = 50331648  # 48Мб., для отправка с помощью aiogram
ydl_opts = {
    # reduces the several line of output to barest minimal and therefore, time
    'verbose': True,
    'noplaylist': True,
    'format': "best[height<=720]",
    # 'format': 'best[filesize<=2G]',
    # 'outtmpl': output_path,
    "playlist_items": "1",
}
with YoutubeDL(ydl_opts) as ydl:
    ydl.download([urls])

**Comment by xxkillaxx** [comment] 2023-06-03 06:49
"C:\Program Files\Python310\python.exe" C:/Users/Administrator/Desktop/BOT_tg_TEST/test_down.py
Вошел в download_video!!!!
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip) API
[debug] params: {'verbose': True, 'noplaylist': True, 'format': 'best[height<=720]', 'playlist_items': '1', 'compat_opts': set()}
[debug] Python 3.10.5 (CPython AMD64 64bit) - Windows-10-10.0.14393-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[youtube] Extracting URL: https://youtu.be/QWfjna0mKMU
[youtube] QWfjna0mKMU: Downloading webpage
[youtube] QWfjna0mKMU: Downloading android player API JSON
WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "QWfjna0mKMU"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "QWfjna0mKMU"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: Only images are available for download. use --list-formats to see them
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
ERROR: [youtube] QWfjna0mKMU: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2743, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] QWfjna0mKMU: Requested format is not available. Use --list-formats for a list of available formats

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2743, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] QWfjna0mKMU: Requested format is not available. Use --list-formats for a list of available formats

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\BOT_tg_TEST\test_down.py", line 19, in <module>
    ydl.download([urls])
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3369, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3344, in wrapper
    res = func(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1507, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1536, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1015, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 955, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] QWfjna0mKMU: Requested format is not available. Use --list-formats for a list of available formats

Process finished with exit code 1

**Comment by xxkillaxx** [comment] 2023-06-03 06:52
> Замените `'quiet': True,`на `'verbose': True,`в своем `ydl_opts`и опубликуйте подробный вывод
> 
> Возможный дубликат [# 7143](https://github.com/yt-dlp/yt-dlp/issues/7143)

I have read this post. Up until June 2nd, the upload was working without any errors. I believe something has changed on YouTube's end.
