### ISSUE TITLE
Unable to download JSON metadata

### ISSUE THREAD

**Issue by pavel167** [yt-dlp/yt-dlp#4150] opened 2022-06-23 10:43 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hello,
Since several days can't download videos from "ARTE" channel.

### Verbose log

```shell
(arte_env) pavel@ALABAMA:~/arte_env$ yt-dlp https://www.arte.tv/fr/videos/065287-001-A/beau-sejour-1-10/
DeprecationWarning: Support for Python version 3.6 has been deprecated and will break in future versions of yt-dlp! Please update to Python 3.7 or above
[ArteTV] 065287-001-A: Downloading JSON metadata
ERROR: [ArteTV] 065287-001-A: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
(arte_env) pavel@ALABAMA:~/arte_env$
```

**Comment by HobbyistDev** [comment] 2022-06-23 10:57
Hello, i think this related to #3302

**Comment by HobbyistDev** [comment] 2022-06-23 13:28
I think this issue is duplicate of #3622

**Closed** 2022-06-23 23:35 UTC
Labels: bug, triage

**Comment by pukkandan** [comment] 2022-06-23 23:37
@HobbyistDev Thanks for the help in triaging. I have noticed you adding these comments in many issues ❤️
