### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by joaquinito2070** [yt-dlp/yt-dlp#5949] opened 2023-01-04 16:26 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.02** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

As for today, Facebook has bugs in yt-dlp.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--format-sort', 'br', 'https://www.facebook.com/loteriasyapuestas.es/videos/2163911480483853']
[debug] User config: []
[debug] System config: []
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.02 [d83b0ad] (win32_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-12-25-git-eeb280f351-full_build-www.gyan.dev (setts), ffprobe 2022-12-25-git-eeb280f351-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1754 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.02, Current version: 2023.01.02
yt-dlp is up to date (2023.01.02)
[facebook] Extracting URL: https://www.facebook.com/loteriasyapuestas.es/videos/2163911480483853
[facebook] 2163911480483853: Downloading webpage
[facebook] 2163911480483853: Downloading webpage
ERROR: [facebook] 2163911480483853: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\facebook.py", line 703, in _real_extract
  File "yt_dlp\extractor\facebook.py", line 650, in _extract_from_url
```

**Comment by bashonly** [comment] 2023-01-04 16:43
Does the video load in your browser when you're not logged in? (use a private/incognito tab)
If not, yt-dlp will not be able to download it without cookies

with browser I get this:
>>> This Video Isn't Available Anymore
The link may be broken or the video may have been removed. You can explore more videos or try logging into facebook.com and then visiting the link again.

with yt-dlp I get this:
```
[facebook] Extracting URL: https://www.facebook.com/loteriasyapuestas.es/videos/2163911480483853
[facebook] 2163911480483853: Downloading webpage
ERROR: [facebook] 2163911480483853: This video is only available for registered users. Use --cookies, --cookies-from-browser, --username and --password, or --netrc (facebook) to provide account credentials
```
if you still get an error when passing cookies (`--cookies-from-browser chrome`), then this is a duplicate of #4311, closing this as such

**Closed by bashonly** 2023-01-04 16:43 UTC
Labels: duplicate, site-bug
