### ISSUE TITLE
Request for Threads support

### ISSUE THREAD

**Issue by xuen97** [yt-dlp/yt-dlp#10133] opened 2024-06-08 06:03 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Singapore

### Example URLs

- Single audio: https://www.threads.net/@ss2513014/post/C761Dlxv0dF
- Single video: https://www.threads.net/@millylin0117/post/C76iXhMSe0R
- Single image: https://www.threads.net/@jeremymonteiro/post/C75oCRpSTq4
- Series of images: https://www.threads.net/@mothershipsg/post/C78RkLtS8sj
- Series of images and videos: https://www.threads.net/@clc_intl/post/C76rBuSve9i

### Provide a description that is worded well enough to be understood

It would be great to be able to use yt-dlp to extract all forms of media that could be found on Threads. Currently, this site is unsupported (though it is somewhat similar to Instagram.)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.threads.net/@millylin0117/post/C76iXhMSe0R']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (pip)
[debug] Python 3.10.0 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1l  24 Aug 2021)
[debug] exe versions: ffmpeg 2023-07-19-git-efa6cec759-full_build-www.gyan.dev (setts), ffprobe 2023-07-19-git-efa6cec759-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.threads.net/@millylin0117/post/C76iXhMSe0R
[generic] C76iXhMSe0R: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] C76iXhMSe0R: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.threads.net/@millylin0117/post/C76iXhMSe0R
Traceback (most recent call last):
  File "C:\Users\Xuen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Xuen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Xuen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Xuen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.threads.net/@millylin0117/post/C76iXhMSe0R
```

**Comment by bashonly** [comment] 2024-06-08 16:55
Duplicate of #7523

**Closed by bashonly** 2024-06-08 16:55 UTC
Labels: site-request, triage
