### ISSUE TITLE
Tver download unavailable

### ISSUE THREAD

**Issue by Articulatedbus** [yt-dlp/yt-dlp#4031] opened 2022-06-09 04:10 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Korea

### Description

Tver video link for "https://tver.jp/episodes/epff8xrman" is failed to download, while actual link is working for playing on the website.
(HTTPError 404: 'Not Found')

### Verbose log

```shell
[debug] Command-line config: ['--write-sub', '--embed-subs', '-vU', 'https://tver.jp/episodes/epff8xrman']
[debug] Encodings: locale cp949, fs utf-8, pref cp949, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 2022-04-11-git-d6d46a2c50-full_build-www.gyan.dev (setts), ffprobe 2022-04-11-git-d6d46a2c50-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[TVer] Creating session
[debug] [TVer] Extracting URL: https://tver.jp/episodes/epff8xrman
[TVer] epff8xrman: Downloading JSON metadata
[TVer] epff8xrman: Downloading JSON metadata
[debug] [brightcove:new] Extracting URL: http://players.brightcove.net/6191645753001/default_default/index.html?videoId=ref:4z10810009_20220606#__youtubedl_smuggle=%7B%22geo_countries%22%3A+%5B%22JP%22%5D%7D
[debug] Using fake IP 133.120.244.61 (JP) as X-Forwarded-For
[debug] Loading brightcove.6191645753001_default from cache
[brightcove:new] ref:4z10810009_20220606: Downloading JSON metadata
ERROR: [brightcove:new] Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\brightcove.py", line 648, in _real_extract
  File "yt_dlp\extractor\common.py", line 1030, in _download_json
  File "yt_dlp\extractor\common.py", line 1009, in _download_json_handle
  File "yt_dlp\extractor\adobepass.py", line 1364, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 801, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 786, in _request_webpage

  File "yt_dlp\extractor\common.py", line 768, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3596, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by pukkandan** [comment] 2022-06-09 14:54
Duplicate of #4018

**Closed by pukkandan** 2022-06-09 14:54 UTC
Labels: site-bug
