### ISSUE TITLE
Fails to save JSON file when filename which is retrieved from the source is invalid

### ISSUE THREAD

**Issue by SuRGeoNix** [yt-dlp/yt-dlp#3867] opened 2022-05-25 18:02 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Before trying to save each json file should validate that is OS valid filename. Both characters and length.

### Verbose log

```shell
yt-dlp.exe --no-check-certificate --skip-download --youtube-skip-dash-manifest --write-info-json -P c:\root\_delme01 https://twitter.com/i/status/1529206489633660929
[twitter] 1529206489633660929: Downloading guest token
[twitter] 1529206489633660929: Downloading JSON metadata
[twitter] 1529206489633660929: Downloading m3u8 information
[info] 1529206489633660929: Downloading 1 format(s): http-2176
[info] Writing video metadata as JSON to: c:\root\_delme01\Marka2 - Με ένα καυστικό βίντεο με τίτλο «Εσείς γιατί δεν τον χειροκροτείτε;» ο Γιάννης Μαντζουράνης, μέλος της ΚΕ του ΣΥΡΙΖΑ-ΠΣ, σχολιάζει δηκτικά το ταξίδι του Κυριάκου Μητσοτάκη στις ΗΠΑ και το κενό περιεχομένου αποτέλεσμα που είχε για την πατρίδα και την εξωτερική πολιτική. Εξαιρετικο [1529206489633660929].info.json
ERROR: Cannot write video metadata to JSON file c:\root\_delme01\Marka2 - Με ένα καυστικό βίντεο με τίτλο «Εσείς γιατί δεν τον χειροκροτείτε;» ο Γιάννης Μαντζουράνης, μέλος της ΚΕ του ΣΥΡΙΖΑ-ΠΣ, σχολιάζει δηκτικά το ταξίδι του Κυριάκου Μητσοτάκη στις ΗΠΑ και το κενό περιεχομένου αποτέλεσμα που είχε για την πατρίδα και την εξωτερική πολιτική. Εξαιρετικο [1529206489633660929].info.json
```

**Comment by pukkandan** [comment] 2022-05-25 21:56
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1136

**Closed by pukkandan** 2022-05-25 21:56 UTC
Labels: bug, triage
