### ISSUE TITLE
Download fails when the title of the video is too long (or contains invalid characters)

### ISSUE THREAD

**Issue by abolibibelot1980** [yt-dlp/yt-dlp#2088] opened 2021-12-22 22:16 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The download fails with the basic syntax when a video's title is longer than the max path length allowed on the operating system (in this case Windows 7), and/or contains invalid characters (in the example below I'm not sure which of those two possible causes is the actual culprit as the video's title has both characteristics), with a misleading error message saying “No such file or directory”. The download starts normally if a shorter / valid file name is specified for the output.

So yt-dlp should shorten the automatically generated output file name to a length below the limit of the current system (and replace any invalid characters with placeholder characters), or prompt the user with a (non misleading) warning and a request to manually input a valid output file name.

### Verbose log

```shell
H:\>yt-dlp -Uv https://twitter.com/i/status/1473417773372030981
[debug] Command-line config: ['-Uv', 'https://twitter.com/i/status/1473417773372030981']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2.3, ffprobe git-2019-12-26-b0d0d7e
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [twitter] Extracting URL: https://twitter.com/i/status/1473417773372030981
[twitter] 1473417773372030981: Downloading guest token
[twitter] 1473417773372030981: Downloading JSON metadata
[twitter] 1473417773372030981: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, tbr, vbr, abr, filesize, fs_approx, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1473417773372030981: Downloading 1 format(s): http-2176
[debug] Invoking downloader on "https://video.twimg.com/amplify_video/1473414109798576137/vid/1280x720/I7DLU-AQFjaR6gJn.mp4?tag=14"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'Alexandria Ocasio-Cortez - We're back-back-back again!  Despite the challenges, we've accomplished so much together over the past year. Thank you to EVERYONE who zoomed, taught, organized, and built community with us.  Without further ado - 21 wins for 2021. Want to join for '22 ?? [1473417773372030981].mp4.part'
Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 266, in download
  File "yt_dlp\utils.py", line 2094, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'Alexandria Ocasio-Cortez - We're back-back-back again!  Despite the challenges, we've accomplished so much together over the past year. Thank you to EVERYONE who zoomed, taught, organized, and built community with us.  Without further ado - 21 wins for 2021. Want to join for '22 ?? [1473417773372030981].mp4.part'

H:\>yt-dlp -Uv https://twitter.com/i/status/1473417773372030981 -o "Alexandria Ocasio-Cortez - We're back-back-back again!.mp4"
[debug] Command-line config: ['-Uv', 'https://twitter.com/i/status/1473417773372030981', '-o', "Alexandria Ocasio-Cortez - We're back-back-back again!.mp4"]
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2.3, ffprobe git-2019-12-26-b0d0d7e
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [twitter] Extracting URL: https://twitter.com/i/status/1473417773372030981
[twitter] 1473417773372030981: Downloading guest token
[twitter] 1473417773372030981: Downloading JSON metadata
[twitter] 1473417773372030981: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, tbr, vbr, abr, filesize, fs_approx, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1473417773372030981: Downloading 1 format(s): http-2176
[debug] Invoking downloader on "https://video.twimg.com/amplify_video/1473414109798576137/vid/1280x720/I7DLU-AQFjaR6gJn.mp4?tag=14"
[download] Destination: Alexandria Ocasio-Cortez - We're back-back-back again!.mp4
[download]  15.3% of 27.67MiB at  1.10MiB/s ETA 00:21
```

**Comment by pukkandan** [comment] 2021-12-22 22:57
Invalid characters are already handled. The issue is with long filenames. Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1136

**Closed by pukkandan** 2021-12-22 22:57 UTC
Labels: bug, triage
