### ISSUE TITLE
Discovery Plus

### ISSUE THREAD

**Issue by MotleyC** [yt-dlp/yt-dlp#3683] opened 2022-05-08 23:31 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

Discovery Plus error when trying to download a video. Worked last week fine.

### Verbose log

```shell
[DiscoveryPlus] 90-day-fiance/pasta-la-vista: Downloading JSON metadata
ERROR: [DiscoveryPlus] 90-day-fiance/pasta-la-vista: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pukkandan** [comment] 2022-05-09 01:48
> Provide the complete verbose output of yt-dlp **that clearly demonstrates the problem**.
> Add the `-vU` flag to your command line you run yt-dlp with (`yt-dlp -vU <your command line>`), copy the WHOLE output and insert it below.

Which part of this don't you understand??

Possibly duplicate of #1623

**Comment by MotleyC** [comment] 2022-05-09 11:26
I use Tartube to download because it is a gui front end. I don't know how to trigger the verbose error output.

It is not a duplicate of #1623 This is a new issue that just started this week..

**Closed** 2022-05-09 11:42 UTC
Labels: incomplete, site-bug
