### ISSUE TITLE
ERROR: [youtube]  Unable to extract uploader id

### ISSUE THREAD

**Issue by Shituation** [yt-dlp/yt-dlp#6253] opened 2023-02-16 17:51 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

https://github.com/ytdl-org/youtube-dl/issues/31530

Mistaken yt-dl for yt-dlp. That issue is still valid.

`ERROR: [youtube] pjxa_BEZOHU: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template.`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe -4 --restrict-filenames --downloader aria2c -o "E:\FOLDER\Downloads\%(title)s.%(ext)s" https://www.youtube.com/watch?v=pjxa_BEZOHU -vU
[debug] Command-line config: ['-4', '--restrict-filenames', '--downloader', 'aria2c', '-o', 'E:\\FOLDER\\Downloads\\%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=pjxa_BEZOHU', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109541-g94aa70d757-20230109 (setts), ffprobe N-109541-g94aa70d757-20230109, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=pjxa_BEZOHU
[youtube] pjxa_BEZOHU: Downloading webpage
[youtube] pjxa_BEZOHU: Downloading android player API JSON
[youtube] pjxa_BEZOHU: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
[youtube] pjxa_BEZOHU: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
ERROR: [youtube] pjxa_BEZOHU: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\youtube.py", line 4049, in _real_extract
  File "yt_dlp\extractor\common.py", line 1228, in _search_regex
```

**Comment by KilliK69** [comment] 2023-02-16 17:54
yeah, i am getting the same error just now.

**Comment by ComunicPlus** [comment] 2023-02-16 17:54
Me too, i am getting the same error just now.

**Comment by gianpaima** [comment] 2023-02-16 18:01
Me too, i am getting the same error just now.

**Comment by lordars** [comment] 2023-02-16 18:07
Me too

**Comment by DalisonCPU** [comment] 2023-02-16 18:10
I am also having this problem here. Reading the debug, it shows that the error is in the limit of requests.

**Comment by lapcdelain** [comment] 2023-02-16 18:11
Same error here.

**Comment by Grub4K** [comment] 2023-02-16 18:13
> - [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates

Duplicate of #6247 (which is both **pinned *and* linked in the [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766)**). Refer to that issue for further conversation.

As said there, a new release will be coming soon. Alternatively you may [install from master with pip](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip).

Please always check the [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) before opening anything new, it makes our live a lot easier that way.

**Comment by Shituation** [comment] 2023-02-16 18:13
Seems they were waiting for me all the time...

**Comment by ROBdk97** [comment] 2023-02-16 18:13
Same here

**Comment by Lesmiscore** [comment] 2023-02-16 18:21
For daily build users: the next version (2023.02.17.xxx) is expected to resolve this issue
I'll be fixing rebase issue before the build start

**Closed** 2023-02-17 12:35 UTC
Labels: duplicate, site-bug
