### ISSUE TITLE
Sign in to confirm you’re not a bot. this helps protect our community. learn more

### ISSUE THREAD

**Issue by joliedevil** [yt-dlp/yt-dlp#10134] opened 2024-06-08 08:49 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Viet Nam

### Provide a description that is worded well enough to be understood

how to fix? Sign in to confirm you’re not a bot. this helps protect our community. learn more

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[Error] :sign in to confirm you’re not a bot. this helps protect our community. learn more
```

**Comment by coletdjnz** [comment] 2024-06-08 09:09
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/10108

No known fix yet (except change IP?)

**Closed** 2024-06-08 09:09 UTC
Labels: duplicate, site-bug

**Comment by ProjectBackSlash** [comment] 2024-06-09 04:28
> Duplicate of #10108
> 
> No known fix yet (except change IP?)

I do believe that you are correct, changing my IP has corrected the issue for me atleast.

**Comment by drpshtiwan** [comment] 2024-06-09 15:00
Provide cookies fixed the issue for me, but this is not practical. Is there any alternative way?

```bash
yt-dlp --cookies youtube_cookies.txt <video_url>

```

**Comment by drpshtiwan** [comment] 2024-06-10 22:22
If anyone has this issue on production, can use the proxy from another and use it on the production server. Below link explains in depth

https://chatgpt.com/share/d98b0924-c157-4609-88c8-80910dad2fe3
