### ISSUE TITLE
API not found: https://api.nfl.com/v3/shield/

### ISSUE THREAD

**Issue by mrKraftVI** [yt-dlp/yt-dlp#11376] opened 2024-10-27 21:00 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I'm hitting an error trying to reach this endpoint:

https://api.nfl.com/v3/shield : 

HTTP Error 500: Domain Not Found

{'data': None, 'errors': [{'message': 'HTTP Error 500: Domain Not Found', 'exception': <HTTPError 500: 'Domain Not Found'>, 'status': 500, 'headers': <http.client.HTTPMessage object at 0x000002C1F368B1D0>, 'body': '\n\n\n<title>Fastly error: unknown domain shield-jarvis-api.nfl.com</title>\n\n\n

Fastly error: unknown domain: shield-jarvis-api.nfl.com. Please check that this domain has been added to a service.

\n
Details: cache-bur-kbur8200047-BUR (140.248.67.47)

'}]}
Any ideas?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] https://api.nfl.com/v3/shield : HTTP Error 500: Domain Not Found
```

**Comment by seproDev** [comment] 2024-10-27 21:33
A complete verbose log is mandatory

**Comment by bashonly** [comment] 2024-10-29 17:07
I'm guessing the NFLPlus extractor is broken since it also uses this endpoint, but that output is not from yt-dlp

**Comment by bashonly** [comment] 2024-10-30 14:34
Maybe #11409 is relevant to your interests

Closing as incomplete; can reopen if this indeed was intended as an issue to track the yt-dlp extractor(s)

**Closed by bashonly** 2024-10-30 14:34 UTC
Labels: incomplete, site-bug, triage
