### ISSUE TITLE
Facebook not parsing videos

### ISSUE THREAD

**Issue by agentsix1** [yt-dlp/yt-dlp#7839] opened 2023-08-15 02:30 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

PS C:\Users\Jeremy\Desktop\Youtube-DL\music> ./yt-dlp --update-to nightly
Available version: nightly@2023.08.14.182926, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
Updating to nightly@2023.08.14.182926 ...
Updated yt-dlp to nightly@2023.08.14.182926
PS C:\Users\Jeremy\Desktop\Youtube-DL\music> ./yt-dlp -f bestvideo[height<=1080]+bestaudio https://www.facebook.com/100068412606448/videos/2082785925397242 -o "test.%(ext)s"
[facebook] Extracting URL: https://www.facebook.com/100068412606448/videos/2082785925397242
[facebook] 2082785925397242: Downloading webpage
[facebook] 2082785925397242: Downloading webpage
ERROR: [facebook] 2082785925397242: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
PS C:\Users\Jeremy\Desktop\Youtube-DL\music>

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\Users\Jeremy\Desktop\Youtube-DL\music> ./yt-dlp -vU -f bestvideo[height<=1080]+bestaudio https://www.facebook.com/
100068412606448/videos/2082785925397242 -o "test.%(ext)s"
[debug] Command-line config: ['-vU', '-f', 'bestvideo[height<=1080]+bestaudio', 'https://www.facebook.com/100068412606448/videos/2082785925397242', '-o', 'test.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.14.182926 [876b70c8e] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-01-24-git-0a83ecbf48-full_build-www.gyan.dev (setts), ffprobe 2022-01-24-git-0a83ecbf48-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1863 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.08.14.182926, Current version: nightly@2023.08.14.182926
Current Build Hash: 7f7cdae9ae8c2706352e1ca2314642026bf5afeb6c20fb76ec3e79cbb5fc6256
yt-dlp is up to date (nightly@2023.08.14.182926)
[facebook] Extracting URL: https://www.facebook.com/100068412606448/videos/2082785925397242
[facebook] 2082785925397242: Downloading webpage
[facebook] 2082785925397242: Downloading webpage
ERROR: [facebook] 2082785925397242: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\facebook.py", line 733, in _real_extract
  File "yt_dlp\extractor\facebook.py", line 680, in _extract_from_url
```

**Comment by agentsix1** [comment] 2023-08-15 02:31
I have tried this with videos I have been able to download in the past and I am now getting this error even with them.

**Comment by bashonly** [comment] 2023-08-15 02:44
Closing as duplicate of #4311, but I am noting in that issue that this error occurs with nearly every FB video

**Closed by bashonly** 2023-08-15 02:44 UTC
Labels: duplicate, site-bug, site:facebook
