### ISSUE TITLE
[abema]  yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by wjx0912** [yt-dlp/yt-dlp#9300] opened 2024-02-26 07:26 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

japan

### Provide a description that is worded well enough to be understood

abema 403 error (8 video pass and 2 video failed)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\userxxx\Desktop\abema_test>yt-dlp.exe   --no-check-certificates --no-warnings   --proxy 127.0.0.1:7890    --use-extractors AbemaTV   --cookies   "C:\Users\userxxx\Desktop\abema.tv_cookies.txt"  -vU --verbose                           https://abema.tv/video/episode/19-174_s1_p9
[debug] Command-line config: ['--no-check-certificates', '--no-warnings', '--proxy', '127.0.0.1:7890', '--use-extractors', 'AbemaTV', '--cookies', 'C:\\Users\\userxxx\\Desktop\\abema.tv_cookies.txt', '-vU', '--verbose', 'https://abema.tv/video/episode/19-174_s1_p9']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {'all': '127.0.0.1:7890'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[AbemaTV] Extracting URL: https://abema.tv/video/episode/19-174_s1_p9
[AbemaTV] Authorizing
[AbemaTV] 19-174_s1_p9: Downloading webpage
[AbemaTV] 19-174_s1_p9: Checking playability
[AbemaTV] 19-174_s1_p9: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 19-174_s1_p9: Downloading 1 format(s): 5300
[debug] Invoking hlsnative downloader on "https://vod-abematv.akamaized.net/program/19-174_s1_p9/1080/playlist.m3u8?aver=1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 133
[download] Destination: #09『自殺か他殺か』 [19-174_s1_p9].mp4
[debug] File locking is not supported. Proceeding without locking
[download]   0.4% of ~   1.89GiB at    1.29MiB/s ETA 02:39:38 (frag 1/133)[AbemaTV] Fetching media token
[AbemaTV] Requesting playback license
ERROR: [urllib] Unexpected error: ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4082, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_requests.py", line 343, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 850, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4114, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4082, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_requests.py", line 343, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 850, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4114, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_urllib.py", line 396, in _send
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\extractor\abematv.py", line 88, in abematv_license_open
  File "yt_dlp\extractor\abematv.py", line 63, in _get_videokey_from_ticket
  File "yt_dlp\extractor\common.py", line 1072, in download_content
  File "yt_dlp\extractor\common.py", line 1036, in download_handle
  File "yt_dlp\extractor\common.py", line 906, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 863, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

ERROR: Unable to handle request: Unsupported url scheme: "abematv-license" (requests, websockets) + 1 unexpected error(s)
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1587, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1743, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1802, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2952, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3418, in process_info
  File "yt_dlp\YoutubeDL.py", line 3139, in dl
  File "yt_dlp\downloader\common.py", line 455, in download
  File "yt_dlp\downloader\hls.py", line 375, in real_download
  File "yt_dlp\downloader\fragment.py", line 516, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 358, in decrypt_fragment
  File "yt_dlp\downloader\fragment.py", line 347, in _get_key
  File "yt_dlp\YoutubeDL.py", line 4082, in urlopen
  File "yt_dlp\networking\common.py", line 127, in send
yt_dlp.networking.exceptions.NoSupportingHandlers: Unable to handle request: Unsupported url scheme: "abematv-license" (requests, websockets) + 1 unexpected error(s)


C:\Users\userxxx\Desktop\abema_test>
```

**Comment by bashonly** [comment] 2024-02-26 09:37
Can you try with `--username` and `--password` and NOT `--cookies` on yt-dlp nightly? And share the log if it doesn't work.

**Comment by bashonly** [comment] 2024-02-27 02:16
you need to try with the **nightly** version though. there have been fixes to the abematv extractor since the last stable release

**Comment by bashonly** [comment] 2024-02-27 05:36
> (4)yt-dlp nightly, use --username and --password, test ok

You will need to do it this way for the time being. Your auth token is now cached, so until it expires, you can continue to pass the same credentials even if you used a one-time password. If passing the `--username` and `--password` arguments is the problem, you could [create a `.netrc` file](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#authentication-with-netrc) and pass `--netrc` instead.

> fix the --cookies download.

This is being tracked in #7775. I do not have an account so I do not know if it is even possible, though

Closing as duplicate of #7775

**Closed by bashonly** 2024-02-27 05:36 UTC
Labels: incomplete, site-bug, triage
