### ISSUE TITLE
SonyLIV Premium Content giving 406 ERROR

### ISSUE THREAD

**Issue by kr-v** [yt-dlp/yt-dlp#1945] opened 2021-12-09 19:21 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

_India_

### Description

Requesting support for SonyLIV to download the latest episodes .
->The content is a subscriber-only episode.
->The content is non DRM, I have verified.
->I have passed cookies from my premium account using --cookies.

Running URL : 
https://www.sonyliv.com/shows/kaun-banega-crorepati-1700000195/fighting-all-odds-on-the-hot-seat-1000148334?watch=true

Gives an error 406.
I am running the latest version.

### Verbose log

```shell
[debug] Command-line config: ['https://www.sonyliv.com/shows/kaun-banega-crorepati-1700000195/fighting-all-odds-on-the-hot-seat-1000148334?watch=true', '--cookies', 'sony-cookie.txt', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (zip)
[debug] Python version 3.9.7 (CPython 64bit) - macOS-11.5.2-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Using fake IP 117.195.44.37 (IN) as X-Forwarded-For
[SonyLIV] Downloading JSON metadata
[debug] [SonyLIV] Extracting URL: https://www.sonyliv.com/shows/kaun-banega-crorepati-1700000195/fighting-all-odds-on-the-hot-seat-1000148334?watch=true
[SonyLIV] 1000148334: Downloading JSON metadata
ERROR: [SonyLIV] 1000148334: Unable to download JSON metadata: HTTP Error 406: Not Acceptable (caused by <HTTPError 406: 'Not Acceptable'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 406: 'Not Acceptable'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3385, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by Ashish0804** [comment] 2021-12-09 19:24
Fixing this "bug" is not worth it.
Just try after 24hours (it won't be DRM'd after 24hrs if it weren't to bein with afaik)

Also dupe of https://github.com/yt-dlp/yt-dlp/issues/1838 but GH keeps deleting that issue

**Comment by kr-v** [comment] 2021-12-09 19:25
> Just try after 24hours (it won't be DRM'd after 24hrs if it weren't to bein with afaik)

Sir I have verified, the video in question is not protected by DRM.

**Comment by Ashish0804** [comment] 2021-12-09 19:41
To make API requests for "latest" content, sonyliv requires you to add device id and token (idr the exact field name)
The only way to get this token is to make proper OTP requests.

Now implementing this in dlp is almost a complete copy paste from zee5.py

But unlike zee5, this is only required for "latest" stuff and thus will make the whole extractor useless for many users like me as to even determine if an url is latest, u have to make the api request which requires the token.

A possible solution is to let the user himself provide the url with `latest` keyword `latest:<url>` but it's ugly and kinda hard to document effectively now.

Therefore I'll only implement this when sony puts more stuff behind this token like zee5 or there's a neater way to implement this.


Meanwhile few workarounds are:
1. Just try after 24 hrs
2. manually provide token and device id in headers

**Closed** 2021-12-14 17:09 UTC
Labels: extractor-bug

**Comment by jashanbeniwal** [comment] 2025-04-22 09:50
Anyone help me create a telegram sony liv drm project.

**Comment by bashonly** [comment] 2025-04-22 10:58
@jashanbeniwal No, and this issue tracker is not the place to ask about this
