### ISSUE TITLE
Precodition check failed.

### ISSUE THREAD

**Issue by dsFejerA** [yt-dlp/yt-dlp#9396] opened 2024-03-09 01:14 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When i download youtube video with audio appear a WARNING message related to Precondition check.
But it downloads fine audio + video and merges.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube] 4sqRnc-gru8: Downloading webpage
[youtube] 4sqRnc-gru8: Downloading ios player API JSON
[youtube] 4sqRnc-gru8: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] 4sqRnc-gru8: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] 4sqRnc-gru8: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] 4sqRnc-gru8: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 4sqRnc-gru8: Downloading m3u8 information
[info] 4sqRnc-gru8: Downloading 1 format(s): 247+251
[download] Resuming download at byte 61478869
[download] Destination: Bűnvadászok [Teljes film] [HD] [4sqRnc-gru8].f247.webm
[download] 100% of  678.59MiB in 00:00:16 at 41.47MiB/s
[download] Destination: Bűnvadászok [Teljes film] [HD] [4sqRnc-gru8].f251.webm
[download] 100% of   78.65MiB in 00:00:04 at 19.20MiB/s
[Merger] Merging formats into "Bűnvadászok [Teljes film] [HD] [4sqRnc-gru8].webm"
Deleting original file Bűnvadászok [Teljes film] [HD] [4sqRnc-gru8].f251.webm (pass -k to keep)
Deleting original file Bűnvadászok [Teljes film] [HD] [4sqRnc-gru8].f247.webm (pass -k to keep)
```

**Comment by bashonly** [comment] 2024-03-09 01:18
Duplicate of #9316

Update to nightly

if you are using the exe/zip:
```
yt-dlp --update-to nightly
```

or if you installed with pip:
```
python3 -m pip install -U --pre yt-dlp
```

**Closed by bashonly** 2024-03-09 01:18 UTC
Labels: duplicate, site-bug
