### ISSUE TITLE
Getting an "error: 'list' object has no attribute 'items' downloading a video from Rumble

### ISSUE THREAD

**Issue by walt93** [yt-dlp/yt-dlp#7141] opened 2023-05-27 07:05 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Downloading this video with yt-dlp is resulting in something that looks like a python error

Rumble URL: 
`https://rumble.com/v2hl1om-is-a-trumpkennedy-2024-ticket-around-the-corner-on-occams-razor-ep.-281.html
`

Exact yt-dlp options I used: 
`yt-dlp --write-thumbnail -S res,ext:mp4:m4a --recode mp4 -o "/tmp/%(title)s.%(ext)s" https://rumble.com/v2hl1om-is-a-trumpkennedy-2024-ticket-around-the-corner-on-occams-razor-ep.-281.html
`

Simplified yt-dlp options I tried:
`yt-dlp https://rumble.com/v2hl1om-is-a-trumpkennedy-2024-ticket-around-the-corner-on-occams-razor-ep.-281.html
`

Exact error I got, either way I tried it:
```
[Rumble] Extracting URL: https://rumble.com/v2hl1om-is-a-trumpkennedy-2024-ticket-around-the-corner-on-occams-razor-ep.-281.html
[Rumble] v2hl1om-is-a-trumpkennedy-2024-ticket-around-the-corner-on-occams-razor-ep.-281.html: Downloading webpage
[RumbleEmbed] Extracting URL: https://rumble.com/embed/v2ezmdm
[RumbleEmbed] v2ezmdm: Downloading JSON metadata
ERROR: 'list' object has no attribute 'items'
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
% yt-dlp https://rumble.com/v2hl1om-is-a-trumpkennedy-2024-ticket-around-the-corner-on-occams-razor-ep.-281.html -vU
[debug] Command-line config: ['https://rumble.com/v2hl1om-is-a-trumpkennedy-2024-ticket-around-the-corner-on-occams-razor-ep.-281.html', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.10.11 (CPython arm64 64bit) - macOS-12.6.2-arm64-arm-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.1
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[Rumble] Extracting URL: https://rumble.com/v2hl1om-is-a-trumpkennedy-2024-ticket-around-the-corner-on-occams-razor-ep.-281.html
[Rumble] v2hl1om-is-a-trumpkennedy-2024-ticket-around-the-corner-on-occams-razor-ep.-281.html: Downloading webpage
[RumbleEmbed] Extracting URL: https://rumble.com/embed/v2ezmdm
[RumbleEmbed] v2ezmdm: Downloading JSON metadata
ERROR: 'list' object has no attribute 'items'
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/lib/python3.10/site-packages/yt_dlp/extractor/rumble.py", line 167, in _real_extract
    for height, video_info in (ext_info or {}).items():
AttributeError: 'list' object has no attribute 'items'
```

**Comment by flashdagger** [comment] 2023-05-27 10:10
Duplicate of #6612. Already fixed in master.

**Closed** 2023-05-27 10:11 UTC
Labels: duplicate
