### ISSUE TITLE
--auto-sub-langs

### ISSUE THREAD

**Issue by upintheairsheep2** [yt-dlp/yt-dlp#4030] opened 2022-06-09 00:36 UTC
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Please add a flag for automatic sub languages separating it from the main sub Lang's. I want to download all original created subtitles if It excists and live chat, but not all translations of the auto subtitles. Also please append .auto to the auto subs. 

### Verbose log

```shell
NA
```

**Comment by pukkandan** [comment] 2022-06-09 14:34
duplicate of https://github.com/yt-dlp/yt-dlp/issues/2262

**Closed by pukkandan** 2022-06-09 14:34 UTC
Labels: enhancement, triage
