### ISSUE TITLE
error 404 arte.tv

### ISSUE THREAD

**Issue by ludo77** [yt-dlp/yt-dlp#4245] opened 2022-07-02 06:28 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

FRANCE

### Provide a description that is worded well enough to be understood

here is my problem: 
yt-dlp https://www.arte.tv/fr/videos/104351-002-A/serviteur-du-peuple-1-23/
[ArteTV] 104351-002-A: Downloading JSON metadata
ERROR: [ArteTV] 104351-002-A: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.arte.tv/fr/videos/104351-002-A/serviteur-du-peuple-1-23/
[debug] Command-line config: ['-vU', 'https://www.arte.tv/fr/videos/104351-002-A/serviteur-du-peuple-1-23/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (zip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-121-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: certifi-2019.11.28, pycrypto-2.6.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [ArteTV] Extracting URL: https://www.arte.tv/fr/videos/104351-002-A/serviteur-du-peuple-1-23/
[ArteTV] 104351-002-A: Downloading JSON metadata
ERROR: [ArteTV] 104351-002-A: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/extractor/arte.py", line 54, in _real_extract
    info = self._download_json(
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1002, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 966, in download_handle
    res = self._download_webpage_handle(
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 834, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 791, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 773, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3596, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by Lesmiscore** [comment] 2022-07-02 06:29
> [x] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=sort%3Aupdated-desc) for similar issues **including closed ones**. DO NOT post duplicates

Duplicate of #3622

**Closed by Lesmiscore** 2022-07-02 06:29 UTC
Labels: site-bug, triage

**Comment by ludo77** [comment] 2022-07-02 06:39
I just realized that there was already a bug in the deposit: 
https://github.com/yt-dlp/yt-dlp/pull/3302
