### ISSUE TITLE
Every video with percentage on the title doesn't embed thumbnail

### ISSUE THREAD

**Issue by Arkile5542** [yt-dlp/yt-dlp#5264] opened 2022-10-17 08:00 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm trying to download this elden ring playlist https://www.youtube.com/playlist?list=PLCnfQcJQPCdMKPpvYOzlrMd9kfmlND4Ic
and i noticed that every video that has percentage on it doesn't embed thumbnail,and i get [WinError 2],i also noticed that the png thumbnail has an extra % on it.I tried multiple ffmpeg builds!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-o', 'D:\\yt-dlp-batch\\Downloads/%(title)s[%(id)s].%(ext)s', '-f', 'bv*[height<=720][ext=mp4]+ba/b[ext=mp4] / bv*+ba/b', '-vU', '--verbose', '--merge-output-format', 'mp4', '--embed-thumbnail', '--add-metadata', '--embed-chapters', 'https://youtu.be/dLeCXmbg6lE']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-10-13-git-9e8a327e68-essentials_build-www.gyan.dev (setts), ffprobe 2022-10-13-git-9e8a327e68-essentials_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [youtube] Extracting URL: https://youtu.be/dLeCXmbg6lE
[youtube] dLeCXmbg6lE: Downloading webpage
[youtube] dLeCXmbg6lE: Downloading android player API JSON
[debug] Loading youtube-nsig.1f77e565 from cache
[debug] [youtube] Decrypted nsig zHeF9im5LqPjQp8sc0 => 6PrEK2C57pXiQQ
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] dLeCXmbg6lE: Downloading 1 format(s): 298+251
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].webp
[debug] Invoking http downloader on 
=oAOLWpwVHfE3aXnnhHD6bp0TZFQAs4sGeuDvGFJ7X_eVZ&itag=298&source=youtube&requiressl=yes&mh=WJ&mm=31%2C26&mn=sn-5hnekn7d%2Csn-4g5ednde&ms=au%2Conr&mv=m&mvi=4&pl=25&initcwndbps=505000&spc=yR2vpylB937Cz5odyyeStR1GBvKTsgs&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=279274866&dur=683.100&lmt=1647564750852554&mt=1665992966&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAN2Y2gX6wm_O9xIOY4U8dJTSTt3LuoRBSpqInymdT98rAiEAzaazRhVFSKuVUa877ZpoE-Aeh9oyGSlX-Sn4TPneooE%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJcmcTIYPK-w6nI4L0gr3F7OA5SmJd-1Wlzkf_qzmzECAiEA5KX9_uud9Z2tnI-_x7MO7VeO6cqrX6pjgaNmqTA8ocU%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].f298.mp4
[download] 100% of  266.34MiB in 00:01:25 at 3.13MiB/s
[debug] Invoking=o-AOLWpwVHfE3aXnnhHD6bp0TZFQAs4sGeuDvGFJ7X_eVZ&itag=251&source=youtube&requiressl=yes&mh=WJ&mm=31%2C26&mn=sn-5hnekn7d%2Csn-4g5ednde&ms=au%2Conr&mv=m&mvi=4&pl=25&initcwndbps=505000&spc=yR2vpylB937Cz5odyyeStR1GBvKTsgs&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=11422301&dur=683.141&lmt=1647564590557372&mt=1665992966&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgAoV3C4tuafg6z0vXKnaCGEg9ooYoaQNADNhCkrN8s9MCIB_xvMvp7g49g_NVRVRYW-OpIfmqdfiuhpv49YhGLoWO&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJcmcTIYPK-w6nI4L0gr3F7OA5SmJd-1Wlzkf_qzmzECAiEA5KX9_uud9Z2tnI-_x7MO7VeO6cqrX6pjgaNmqTA8ocU%3D"
[download] Destination: D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].f251.webm
[download] 100% of   10.89MiB in 00:00:05 at 1.96MiB/s
[Merger] Merging formats into "D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].f298.mp4" -i "file:D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].temp.mp4"
Deleting original file D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].f251.webm (pass -k to keep)
Deleting original file D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].f298.mp4 (pass -k to keep)
[Metadata] Adding metadata to "D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].mp4" -i "file:D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].meta" -map 0 -dn -ignore_unknown -c copy -map_metadata 1 -write_id3v1 1 -metadata "title=Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough | Upgrade Your Flasks!" -metadata "date=20220318" -metadata "description=In this video I show you guys all the Sacred Tear locations in the game. If you find this helpful please consider subscribing and maybe leaving a like on the video this helps me a ton :)

Support me on Patreon: https://www.patreon.com/LukeCanWin?fan_landing=true

#Sacred #Tear #Guide

TIMESTAMPS
0:00 Intro
0:28 First Sacred Tear(Third Church of Marika)
0:59 Second Sacred Tear(Callu Baptismal Church)
2:08 Third Sacred Tear(Church of Pilgrimage)
2:29 Fourth Sacred Tear(Fourth Church of Marika)
2:44 Fifth Sacred Tear(Church of Irith)
3:10 Sixth Sacred Tear(Bellum Church)
3:37 Seventh Sacred Tear(Church of Inhibition)
4:19 Eighth Sacred Tear(Second Church of Marika)
4:56 Ninth Sacred Tear(Stormcaller Church)
5:48 Tenth Sacred Tear(Sellia Puzzle & Church of the Plague)
10:01 Eleventh Sacred Tear(Church of Repose)
10:50 Twelfth Sacred Tear(First Church of Marika)" -metadata "synopsis=In this video I show you guys all the Sacred Tear locations in the game. If you find this helpful please consider subscribing and maybe leaving a like on the video this helps me a ton :)

Support me on Patreon: https://www.patreon.com/LukeCanWin?fan_landing=true

#Sacred #Tear #Guide

TIMESTAMPS
0:00 Intro
0:28 First Sacred Tear(Third Church of Marika)
0:59 Second Sacred Tear(Callu Baptismal Church)
2:08 Third Sacred Tear(Church of Pilgrimage)
2:29 Fourth Sacred Tear(Fourth Church of Marika)
2:44 Fifth Sacred Tear(Church of Irith)
3:10 Sixth Sacred Tear(Bellum Church)
3:37 Seventh Sacred Tear(Church of Inhibition)
4:19 Eighth Sacred Tear(Second Church of Marika)
4:56 Ninth Sacred Tear(Stormcaller Church)
5:48 Tenth Sacred Tear(Sellia Puzzle & Church of the Plague)
10:01 Eleventh Sacred Tear(Church of Repose)
10:50 Twelfth Sacred Tear(First Church of Marika)" -metadata "purl=https://www.youtube.com/watch?v=dLeCXmbg6lE" -metadata "comment=https://www.youtube.com/watch?v=dLeCXmbg6lE" -metadata "artist=LukeCanWin" -movflags "+faststart" "file:D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].temp.mp4"
[ThumbnailsConvertor] Converting thumbnail "D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -f image2 -pattern_type none -i "file:D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].webp" -movflags "+faststart" "file:D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100%% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].png"
[EmbedThumbnail] mutagen: Adding thumbnail to "D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].mp4"
WARNING: unable to embed using mutagen; [Errno 2] No such file or directory: 'D:\\yt-dlp-batch\\Downloads\\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].png'
[EmbedThumbnail] mutagen was not found. Falling back to AtomicParsley
[EmbedThumbnail] atomicparsley: Adding thumbnail to "D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].mp4"
[debug] AtomicParsley command line: AtomicParsley "D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].mp4" --artwork "D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].png" -o "D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].temp.mp4"
WARNING: Unable to embed thumbnails using AtomicParsley; AtomicParsley error: can't open D:\yt-dlp-batch\Downloads\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].png for reading: No such file or directory
ERROR: [WinError 2] O sistema não pode encontrar o arquivo especificado: 'D:\\yt-dlp-batch\\Downloads\\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].temp.mp4' -> 'D:\\yt-dlp-batch\\Downloads\\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].mp4'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1574, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1632, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2733, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3272, in process_info
  File "yt_dlp\YoutubeDL.py", line 3449, in post_process
  File "yt_dlp\YoutubeDL.py", line 3431, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3410, in run_pp
  File "yt_dlp\postprocessor\common.py", line 24, in run
  File "yt_dlp\postprocessor\common.py", line 129, in wrapper
  File "yt_dlp\postprocessor\embedthumbnail.py", line 219, in run
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado: 'D:\\yt-dlp-batch\\Downloads\\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].temp.mp4' -> 'D:\\yt-dlp-batch\\Downloads\\Elden Ring - All Sacred Tear Locations 100% Complete Guide & Walkthrough ｜ Upgrade Your Flasks![dLeCXmbg6lE].mp4'
```

**Comment by pukkandan** [comment] 2022-10-17 08:14
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/4604

**Closed by pukkandan** 2022-10-17 08:14 UTC
Labels: bug, triage
