### ISSUE TITLE
Instagram not working

### ISSUE THREAD

**Issue by maxibrot** [yt-dlp/yt-dlp#3960] opened 2022-06-04 13:36 UTC
### Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I think Instagram changed something in their code. Image Max URL and other sites dont work properly aswell. A week ago it worked flawlessly.

### Verbose log

```shell
[debug] Command-line config: ['-F', 'https://www.instagram.com/reel/Cd2vkWQKuR0/', '--cookies-from-browser', 'firefox', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 2022-01-10-git-f37e66b393-essentials_build-www.gyan.dev (setts), ffprobe 2022-01-10-git-f37e66b393-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\USER\AppData\Roaming\Mozilla\Firefox\Profiles\aup5iws6.default-release-1641574058189\cookies.sqlite"
[Cookies] Extracted 3206 cookies from firefox
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [Instagram] Extracting URL: https://www.instagram.com/reel/Cd2vkWQKuR0/
[Instagram] Cd2vkWQKuR0: Downloading webpage
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] Cd2vkWQKuR0: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\instagram.py", line 415, in _real_extract
  File "yt_dlp\extractor\common.py", line 1340, in _og_search_video_url
  File "yt_dlp\extractor\common.py", line 1235, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1226, in _search_regex
```

**Comment by pukkandan** [comment] 2022-06-04 13:52
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3077

**Closed** 2022-06-04 13:56 UTC
Labels: duplicate, site-bug, site:instagram
