### ISSUE TITLE
 Closed 9 tasks done No package metadata was found for yt-dlp after openSUSE Tumbleweed System Update

### ISSUE THREAD

**Issue by richardstevenhack** [yt-dlp/yt-dlp#8432] opened 2023-10-25 12:59 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Running openSUSE Tumbleweed after a new distro update on 2023-20-25, IOW, just a couple hours ago. Note that earlier in the day, before the Tumbleweed system update, I was running yt-dlp as usual using Media Downloader as well as from the command line to download over 100 Youtube videos and there was no issue.

An attempt to download a video from youtube resulted in the error message shown in the verbose output box below.
```
Searching through bug reports, I found this discussion:
No package metadata was found for yt-dlp #5941 
https://github.com/yt-dlp/yt-dlp/issues/5941

That includes this discussion:

> @Len-PGH
> what happens if you run
> 
> python3 -m pip install --upgrade pip setuptools wheel
> 
> then
> 
> python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.zip
> 
> and then run yt-dlp
> 

I attempted to run the first command to upgrade the setuptools wheel, but openSUSE Tumbleweed has a controlled python installation  environment and returned this message:

```
rhack@localhost:/Data2/Work> python3 -m pip install --upgrade pipx setuptools wheel
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try
    zypper install python311-xyz, where xyz is the package
    you are trying to install.
    
    If you wish to install a non-rpm packaged Python package,
    create a virtual environment using python3.11 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-rpm packaged Python application,
    it may be easiest to use `pipx install xyz`, which will manage a
    virtual environment for you. Install pipx via `zypper install python311-pipx` .

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
I tried the first and the third suggested commands, but neither function.  I am not familiar enough with python or python virtual environments to figure out how to do the second suggested method.

As it stands, my yt-dlp is broken. Can anyone suggest a solution?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
rhack@localhost:/Data2/Work> /usr/bin/python3 /usr/bin/yt-dlp -R 0 -vU  --no-config --no-progress --fragment-retries 0 --skip-unavailable-fragments --abort-on-unavailable-fragment -o "%(title)s.%(ext)s" https://www.youtube.com/watch?v=x-nqRcDRTVs
Traceback (most recent call last):
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/yt-dlp", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp==2023.10.13', 'console_scripts', 'yt-dlp')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for yt-dlp
```

**Comment by richardstevenhack** [comment] 2023-10-25 13:18
In further exploring, I find this script was installed in /usr/local/bin just two days ago on 2023-10-23:

```
`#!/usr/bin/python3.11
# EASY-INSTALL-ENTRY-SCRIPT: 'yt-dlp==2023.10.13','console_scripts','yt-dlp'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'yt-dlp==2023.10.13'

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point


def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()


globals().setdefault('load_entry_point', importlib_load_entry_point)


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('yt-dlp==2023.10.13', 'console_scripts', 'yt-dlp')())`

```
It would seem that lines 9-15 would seem to be the source of the error, from my (unfamiliar) reading of the python script. But I don't know what it means.

**Comment by Grub4K** [comment] 2023-10-25 13:29
Duplicate of #8430, please direct your comments there.

**Closed by Grub4K** 2023-10-25 13:29 UTC
Labels: bug, triage
