### ISSUE TITLE
ERROR: Postprocessing: Conversion failed!

### ISSUE THREAD

**Issue by stillpointx** [yt-dlp/yt-dlp#2051] opened 2021-12-19 15:00 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

ERROR: Postprocessing: Conversion failed! error

yt-dlp -f 'bestvideo[height<=720]+bestaudio[ext=m4a]/best[height<=720]/bestvideo+bestaudio' --merge-output-format mp4 --output "%(title)s_%(resolution)s.%(ext)s" https://youtu.be/XSsDcF-KF3I
[youtube] XSsDcF-KF3I: Downloading webpage
[youtube] XSsDcF-KF3I: Downloading android player API JSON
[youtube] XSsDcF-KF3I: Downloading MPD manifest
[youtube] XSsDcF-KF3I: Downloading MPD manifest
[info] XSsDcF-KF3I: Downloading 1 format(s): 247+140
[dashsegments] Total fragments: 84
[download] Destination: Blender for Scientists - How to Make Cross-Sectioned Spheres in Blender_1280x720.f247.webm
[download] 100% of 18.16MiB in 02:46                                                   
[download] Destination: Blender for Scientists - How to Make Cross-Sectioned Spheres in Blender_1280x720.f140.m4a
[download] 100% of 6.38MiB in 00:11                                      
[Merger] Merging formats into "Blender for Scientists - How to Make Cross-Sectioned Spheres in Blender_1280x720.mp4"
**ERROR: Postprocessing: Conversion failed!**

yt-dlp -v
[debug] Command-line config: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.11.0-43-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

### Verbose log

```shell
yt-dlp -Uvf 'bestvideo[height<=720]+bestaudio[ext=m4a]/best[height<=720]/bestvideo+bestaudio' --merge-output-format mp4 --output "%(title)s_%(resolution)s.%(ext)s" https://youtu.be/XSsDcF-KF3I
[debug] Command-line config: ['-Uvf', 'bestvideo[height<=720]+bestaudio[ext=m4a]/best[height<=720]/bestvideo+bestaudio', '--merge-output-format', 'mp4', '--output', '%(title)s_%(resolution)s.%(ext)s', 'https://youtu.be/XSsDcF-KF3I']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.11.0-43-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [youtube] Extracting URL: https://youtu.be/XSsDcF-KF3I
[youtube] XSsDcF-KF3I: Downloading webpage
[youtube] XSsDcF-KF3I: Downloading android player API JSON
[youtube] XSsDcF-KF3I: Downloading MPD manifest
[youtube] XSsDcF-KF3I: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] XSsDcF-KF3I: Downloading 1 format(s): 247+140
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1639947546/ei/uki_Ye2mCajhj-8Pv8aF0Ao/ip/107.72.178.235/id/5d2b03705f8a1772/source/youtube/requiressl/yes/playback_host/rr5---sn-5uaeznrz.googlevideo.com/mh/Qr/mm/31%2C29/mn/sn-5uaeznrz%2Csn-5ualdnls/ms/au%2Crdu/mv/m/mvi/5/pl/24/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/248750/vprv/1/mt/1639925581/fvip/5/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRgIhAK6GqWe42U5g8tXnvsAGiaE5J6ipBTJmubKclsenSfebAiEAoFzCg7JIj6JVnnX_D6v8pQLzvU5bfpREX1NdenqXFSY%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRgIhAPRF1Ov7fKP100uITCS8UFFvHNPuTK81M-zZjq_5gk7xAiEA3pimSFdiAAX3haBFOEhAPYCanpPGW81Ta8rjmjRTb8M%3D"
[download] Blender for Scientists - How to Make Cross-Sectioned Spheres in Blender_1280x720.f247.webm has already been downloaded
[download] 100% of 18.16MiB[debug] Invoking downloader on "https://rr5---sn-5ualdnls.googlevideo.com/videoplayback?expire=1639947547&ei=u0i_Yby0FMTp4QTJwbzIBw&ip=107.72.178.235&id=o-AL_xiEdt51dGhWuxSykQXDsNcy3Cgz6EDWxD00alUY7Z&itag=140&source=youtube&requiressl=yes&mh=Qr&mm=31%2C26&mn=sn-5ualdnls%2Csn-hp57knz6&ms=au%2Conr&mv=m&mvi=5&pl=24&initcwndbps=377500&vprv=1&mime=audio%2Fmp4&gir=yes&clen=6693447&otfp=1&dur=413.524&lmt=1593640719035742&mt=1639925581&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIgXoLju5S1WvfsWiOQ6aRWoVgJmQp8UYPkmnIH1OH4KacCIQCb9CpLdU_xm2Hi_MOOZHxp9AHFNwt8Nr9IH5x3jjzByw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgPn5CXt2qvx2XvCqO8W9evNJrzGa5vhG-8EkOph05UhYCIEZfdAYaTUA2IIOXGswBQ4JPEB0mb5ySZwJZ_VoogIRZ"
[download] Blender for Scientists - How to Make Cross-Sectioned Spheres in Blender_1280x720.f140.m4a has already been downloaded
[download] 100% of 6.38MiB[Merger] Merging formats into "Blender for Scientists - How to Make Cross-Sectioned Spheres in Blender_1280x720.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Blender for Scientists - How to Make Cross-Sectioned Spheres in Blender_1280x720.f247.webm' -i 'file:Blender for Scientists - How to Make Cross-Sectioned Spheres in Blender_1280x720.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Blender for Scientists - How to Make Cross-Sectioned Spheres in Blender_1280x720.temp.mp4'
[debug] ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from 'file:Blender for Scientists - How to Make Cross-Sectioned Spheres in Blender_1280x720.f247.webm':
  Metadata:
    encoder         : google/video-file
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 83 
                    : Segment-Durations-Ms: 5000(r=81),3458, 
                    :  
                    : 
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1280x720, SAR 1:1 DAR 16:9, 24 fps, 24 tbr, 1k tbn, 1k tbc (default)
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'file:Blender for Scientists - How to Make Cross-Sectioned Spheres in Blender_1280x720.f140.m4a':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6mp41
    creation_time   : 2020-07-01T21:58:17.000000Z
  Duration: 00:06:53.52, start: 0.000000, bitrate: 129 kb/s
    Stream #1:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 3 kb/s (default)
    Metadata:
      creation_time   : 2020-07-01T21:58:17.000000Z
      handler_name    : ISO Media file produced by Google Inc.
Output #0, mp4, to 'file:Blender for Scientists - How to Make Cross-Sectioned Spheres in Blender_1280x720.temp.mp4':
  Metadata:
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 83 
                    : Segment-Durations-Ms: 5000(r=81),3458, 
                    :  
                    : 
    encoder         : Lavf58.29.100
    Stream #0:0(eng): Video: vp9 (Profile 0) (vp09 / 0x39307076), yuv420p(tv, bt709/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 24 fps, 24 tbr, 16k tbn, 1k tbc (default)
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 3 kb/s (default)
    Metadata:
      creation_time   : 2020-07-01T21:58:17.000000Z
      handler_name    : ISO Media file produced by Google Inc.
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp4 @ 0x55c93b49abc0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 80000 >= 80000
av_interleaved_write_frame(): Invalid argument
frame=  122 fps=0.0 q=-1.0 Lsize=     219kB time=00:00:05.01 bitrate= 357.0kbits/s speed=  19x    
video:163kB audio:79kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3001, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3165, in post_process
    info = self.run_pp(pp, info)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3108, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/common.py", line 118, in wrapper
    return func(self, info)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 815, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 280, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 317, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

**Comment by pukkandan** [comment] 2021-12-19 15:06
> [x] I've searched the bugtracker for similar issues including closed ones. DO NOT post duplicates

It is interesting how people have searched the issue tracker and still can't find the 

## PINNED ISSUE WITH THE SAME EXACT TITLE

**Comment by pukkandan** [comment] 2021-12-19 15:06
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/871

**Closed by pukkandan** 2021-12-19 15:06 UTC
Labels: bug, triage
