### ISSUE TITLE
Hotstar wont download with cookies from browser or the txt file.

### ISSUE THREAD

**Issue by drewmeel** [yt-dlp/yt-dlp#11691] opened 2024-12-01 08:11 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

So Ive been trying to get hotstar to work since they changed to a new UI but its not working at all even with the commands I found from the past issues here on the repo. 

Anyone know how to fix this?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU -F --cookies hotstarcookie.txt https://www.hotstar.com/in/shows/ghum-hai-kisikey-pyaar-meiin/1260043179/meet-virat-an-ips-officer/1000253056/watch
[debug] Command-line config: ['-vU', '-F', '--cookies', 'hotstarcookie.txt', 'https://www.hotstar.com/in/shows/ghum-hai-kisikey-pyaar-meiin/1260043179/meet-virat-an-ips-officer/1000253056/watch']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.18 from yt-dlp/yt-dlp)
[hotstar] Extracting URL: https://www.hotstar.com/in/shows/ghum-hai-kisikey-pyaar-meiin/1260043179/meet-virat-an-ips-officer/1000253056/watch
[hotstar] 1000253056: Downloading JSON metadata
WARNING: [hotstar] Unable to download JSON metadata: HTTPSConnectionPool(host='api.hotstar.com', port=443): Read timed out. (read timeout=20.0)
[hotstar] 1000253056: Downloading webpage
ERROR: [hotstar] 1000253056: Unable to download webpage: HTTPSConnectionPool(host='www.hotstar.com', port=443): Read timed out. (read timeout=20.0) (caused by TransportError("HTTPSConnectionPool(host='www.hotstar.com', port=443): Read timed out. (read timeout=20.0)"))
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\hotstar.py", line 243, in _real_extract
  File "yt_dlp\extractor\common.py", line 962, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 911, in _request_webpage

  File "urllib3\connectionpool.py", line 466, in _make_request
  File "urllib3\connectionpool.py", line 1095, in _validate_conn
  File "urllib3\connection.py", line 730, in connect
  File "urllib3\connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 469, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 513, in _ssl_wrap_socket_impl
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
TimeoutError: _ssl.c:990: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 449, in increment
  File "urllib3\util\util.py", line 39, in reraise
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 490, in _make_request
  File "urllib3\connectionpool.py", line 468, in _make_request
  File "urllib3\connectionpool.py", line 369, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.hotstar.com', port=443): Read timed out. (read timeout=20.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\networking\_requests.py", line 328, in _send
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 713, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.hotstar.com', port=443): Read timed out. (read timeout=20.0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 898, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4161, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 352, in _send
yt_dlp.networking.exceptions.TransportError: HTTPSConnectionPool(host='www.hotstar.com', port=443): Read timed out. (read timeout=20.0)
```

**Comment by bashonly** [comment] 2024-12-01 14:02
1st attempt is an issue with the VPN

2nd attempt is a duplicate of #11195

**Closed by bashonly** 2024-12-01 14:02 UTC
Labels: site-bug, triage
