### ISSUE TITLE
ERROR: 'manifest_url' while downloading premiere on YouTube

### ISSUE THREAD

**Issue by CaliforniaMountainSnake** [yt-dlp/yt-dlp#9002] opened 2024-01-14 21:33 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

1. I upload a test video to the my youtube channel and press "Start premiere now ".
2. Then put video's code into yt-dlp and try to download it in real time.
3. Downloading goes as usual, but I always get `ERROR: 'manifest_url'` in the end.

I tried this multiple times and always get this error.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--output', '%(id)s.%(ext)s', '--format-sort', 'vcodec:h264', '--format', 'bv*[height<=1080]+ba', '--live-from-start', '--wait-for-video', '60', '--write-thumbnail', '--verbose', 'UYnBC-mtQu4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.01.09.232723 from yt-dlp/yt-dlp-nightly-builds [95e82347b] (linux_exe)
[debug] Python 3.10.13 (CPython x86_64 64bit) - Linux-5.8.0-050800-generic-x86_64-with-glibc2.31 (OpenSSL 3.2.0 23 Nov 2023, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[youtube] Extracting URL: UYnBC-mtQu4
[youtube] UYnBC-mtQu4: Downloading webpage
[youtube] UYnBC-mtQu4: Downloading ios player API JSON
[youtube] UYnBC-mtQu4: Downloading android player API JSON
WARNING: [youtube] Premiere will begin shortly
WARNING: Release time of video is not known
[wait] Waiting for 00:01:00 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data                 
[youtube] Extracting URL: UYnBC-mtQu4
[youtube] UYnBC-mtQu4: Downloading webpage
[youtube] UYnBC-mtQu4: Downloading ios player API JSON
[youtube] UYnBC-mtQu4: Downloading android player API JSON
[youtube] UYnBC-mtQu4: Downloading MPD manifest
[youtube] UYnBC-mtQu4: Downloading MPD manifest
[debug] Sort order given by user: vcodec:h264
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, vcodec:h264(7), quality, res, fps, hdr:12(7), source, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] UYnBC-mtQu4: Downloading 1 format(s): 136+140
[info] Downloading video thumbnail 47 ...
[info] Video Thumbnail 47 does not exist
[info] Downloading video thumbnail 46 ...
[info] Writing video thumbnail 46 to: UYnBC-mtQu4.jpg
[debug] Invoking dashsegments downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1705288644/ei/ZE-kZey2CbDMv_IP3Z-zwA4/ip/188.113.33.131/id/UYnBC-mtQu4.0/source/yt_premiere_broadcast/requiressl/yes/xpc/EgVo2aDSNQ%3D%3D/tx/51033619/txs/51033612%2C51033613%2C51033614%2C51033615%2C51033616%2C51033617%2C51033618%2C51033619%2C51033620/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/spc/UWF9fyWJQFx-i5JJTHmqoev9Q_TjNHel9h3U/vprv/1/pacing/0/itag_bl/376%2C377%2C384%2C385%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24007246/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Cxpc%2Ctx%2Ctxs%2Cas%2Cspc%2Cvprv%2Citag%2Cplaylist_type/sig/AJfQdSswRgIhAN7UYOZx-h-g-4C4ZxuLZjWWaWW_0zfjL6oFUU4Ddn8iAiEAuYe8uE_GcOamXaniv7NybA6Ook06PfxmGNbfhazk2e8%3D", "https://manifest.googlevideo.com/api/manifest/dash/expire/1705288644/ei/ZE-kZey2CbDMv_IP3Z-zwA4/ip/188.113.33.131/id/UYnBC-mtQu4.0/source/yt_premiere_broadcast/requiressl/yes/xpc/EgVo2aDSNQ%3D%3D/tx/51033619/txs/51033612%2C51033613%2C51033614%2C51033615%2C51033616%2C51033617%2C51033618%2C51033619%2C51033620/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/spc/UWF9fyWJQFx-i5JJTHmqoev9Q_TjNHel9h3U/vprv/1/pacing/0/itag_bl/376%2C377%2C384%2C385%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24007246/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Cxpc%2Ctx%2Ctxs%2Cas%2Cspc%2Cvprv%2Citag%2Cplaylist_type/sig/AJfQdSswRgIhAN7UYOZx-h-g-4C4ZxuLZjWWaWW_0zfjL6oFUU4Ddn8iAiEAuYe8uE_GcOamXaniv7NybA6Ook06PfxmGNbfhazk2e8%3D"
[dashsegments] Total fragments: unknown (live)
[download] Destination: UYnBC-mtQu4.f136.mp4
[dashsegments] Total fragments: unknown (live)
[download] Destination: UYnBC-mtQu4.f140.mp4
[debug] [youtube] [UYnBC-mtQu4] Generating fragments for format 136
[debug] [youtube] [UYnBC-mtQu4] Generating fragments for format 140
[download]    8.29MiB at      0.00B/s (00:03:07) (frag 51/51)[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (1/10)...B at  440.02KiB/s (00:03:06) (frag 51/51)
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (1/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (2/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (3/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (4/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (5/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (6/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (7/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (8/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (9/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (10/10)...
[download] Got error: HTTP Error 404: Not Found. Retrying fragment 52 (10/10)...
[download] fragment not found; Skipping fragment 52 ...
[download] fragment not found; Skipping fragment 52 ...
[youtube] UYnBC-mtQu4: Downloading webpage
[youtube] UYnBC-mtQu4: Downloading ios player API JSON
[youtube] UYnBC-mtQu4: Downloading android player API JSON
[youtube] UYnBC-mtQu4: Downloading m3u8 information
ERROR: 'manifest_url'
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1587, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1743, in __extract_info
  File "yt_dlp/YoutubeDL.py", line 1802, in process_ie_result
  File "yt_dlp/YoutubeDL.py", line 2952, in process_video_result
  File "yt_dlp/YoutubeDL.py", line 3365, in process_info
  File "yt_dlp/YoutubeDL.py", line 3139, in dl
  File "yt_dlp/downloader/common.py", line 455, in download
  File "yt_dlp/downloader/dash.py", line 63, in real_download
  File "yt_dlp/downloader/fragment.py", line 421, in download_and_append_fragments_multiple
  File "yt_dlp/downloader/fragment.py", line 404, in future_result
  File "concurrent/futures/_base.py", line 458, in result
  File "concurrent/futures/_base.py", line 403, in __get_result
  File "concurrent/futures/thread.py", line 58, in run
  File "yt_dlp/downloader/fragment.py", line 385, in thread_func
  File "yt_dlp/downloader/fragment.py", line 510, in download_and_append_fragments
  File "yt_dlp/downloader/fragment.py", line 407, in interrupt_trigger_iter
  File "yt_dlp/downloader/dash.py", line 74, in _get_fragments
  File "yt_dlp/extractor/youtube.py", line 2892, in _live_dash_fragments
  File "yt_dlp/extractor/youtube.py", line 2848, in _extract_sequence_from_mpd
  File "yt_dlp/extractor/youtube.py", line 2810, in mpd_feed
KeyError: 'manifest_url'
```

**Comment by CaliforniaMountainSnake** [comment] 2024-01-15 10:39
Another log:
```
ERROR: 'manifest_url'
Traceback (most recent call last):
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1743, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1802, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2952, in process_video_result
    self.process_info(new_info)
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3365, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3139, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/downloader/dash.py", line 63, in real_download
    return self.download_and_append_fragments_multiple(*args, is_fatal=lambda idx: idx == 0)
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/downloader/fragment.py", line 421, in download_and_append_fragments_multiple
    result = result and future_result(job)
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/downloader/fragment.py", line 404, in future_result
    return future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/downloader/fragment.py", line 385, in thread_func
    return self.download_and_append_fragments(
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/downloader/fragment.py", line 510, in download_and_append_fragments
    for fragment in fragments:
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/downloader/fragment.py", line 407, in interrupt_trigger_iter
    for f in fg:
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/downloader/dash.py", line 74, in _get_fragments
    for i, fragment in enumerate(fragments):
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 2892, in _live_dash_fragments
    should_continue, last_seq = _extract_sequence_from_mpd(True, no_fragment_score > 15)
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 2848, in _extract_sequence_from_mpd
    mpd_url, stream_number, is_live = (mpd_feed(format_id, 5 if expire_fast else 18000)
  File "/home/gogo/.local/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 2810, in mpd_feed
    return f['manifest_url'], f['manifest_stream_number'], is_live
KeyError: 'manifest_url'
```

**Comment by dirkf** [comment] 2024-01-15 15:37
Now:
```
ERROR: [youtube] UYnBC-mtQu4: Video unavailable. This video has been removed by the uploader
```

**Comment by CaliforniaMountainSnake** [comment] 2024-01-15 21:22
> Now:
> 
> ```
> ERROR: [youtube] UYnBC-mtQu4: Video unavailable. This video has been removed by the uploader
> ```

Yes, this is because I have deleted the video. You can reproduce the bug with any video:

> I upload a test video to the my youtube channel and press "Start premiere now ".

I used a generic testsrc video, generated by ffmpeg.
https://youtu.be/dhTMKqV5Ihw

**Comment by pukkandan** [comment] 2024-01-18 02:45
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/8543

**Closed by pukkandan** 2024-01-18 02:45 UTC
Labels: site-bug
