### ISSUE TITLE
[VIU Indonesia] Can't download video from VIU because the URL is not supported

### ISSUE THREAD

**Issue by Frsb2** [yt-dlp/yt-dlp#5994] opened 2023-01-09 00:08 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Indonesia

### Provide a description that is worded well enough to be understood

Hi there,

I got an error when downloading from Viu

yt-dlp detects VIU Indonesia links as generic.

ERROR: Unsupported URL

It's the saame as issue #1757 #1996 and I have tried the plugin but got an error

TypeError: first argument must be string or compiled pattern
[5952] Failed to execute script '__main__' due to unhandled exception!

For full error please see the verbose log output

Thanks

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.viu.com/ott/id/id/all/video-korean-reality-tv_shows-entertainment_weekly_episode_1622-1118617054']
[debug] User config "C:\Users\Fatikah\AppData\Roaming\yt-dlp\config.txt": ['--no-mtime', '--sub-langs', 'all,-live_chat', '--convert-subs', 'srt', '--embed-subs', '--embed-chapters', '--downloader', 'aria2c', '--console-title', '--restrict-filenames', '--merge-output-format', 'mkv', '-o', '%(title).60s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Extractor Plugins: ViuOTTNewBaseIE, ViuOTTNewIE, ViuOTTNewPlaylistIE
[debug] Plugin directories: {'C:\\Users\\Fatikah\\AppData\\Roaming\\yt-dlp\\plugins\\yt-dlp-viu-plugins\\yt_dlp_plugins'}
[debug] Loaded 1763 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 970, in main
  File "yt_dlp\__init__.py", line 960, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3358, in download
  File "yt_dlp\YoutubeDL.py", line 3333, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1478, in extract_info
  File "yt_dlp\extractor\common.py", line 549, in suitable
  File "yt_dlp\extractor\common.py", line 541, in _match_valid_url
  File "re.py", line 252, in compile
  File "re.py", line 303, in _compile
TypeError: first argument must be string or compiled pattern
[5952] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by bashonly** [comment] 2023-01-09 09:54
Closing as duplicate of #1757

**Closed by bashonly** 2023-01-09 09:54 UTC
Labels: site-bug, triage
