### ISSUE TITLE
YT age restriction bypass broke

### ISSUE THREAD

**Issue by GodSaveTheDoge** [yt-dlp/yt-dlp#3182] opened 2022-03-24 21:42 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Yt-dlp age restriction bypass doesn't seem to work anymore, I tested with multiple videos and they are all broken (one of the videos is playable on invidious `2022.03.15-5b82370b` (https://invidious.snopyta.org)).
This might be a duplicate of #2923

https://youtube.com/watch?v=CUO8secmc0g
https://youtube.com/watch?v=dIZ-e4WwJ5w

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://youtube.com/watch?v=CUO8secmc0g']
[debug] User config "/home/doggo/.config/yt-dlp/config": ['-f', 'bestvideo[height<=1080]+bestaudio/best']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.16.15-arch1-1-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0
[debug] Optional libraries: brotli, Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [youtube] Extracting URL: https://youtube.com/watch?v=CUO8secmc0g
[youtube] CUO8secmc0g: Downloading webpage
[youtube] CUO8secmc0g: Downloading android player API JSON
[youtube] CUO8secmc0g: Downloading android agegate player API JSON
[youtube] CUO8secmc0g: Downloading web agegate player API JSON
ERROR: [youtube] CUO8secmc0g: Sign in to confirm your age. This video may be inappropriate for some users.
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 617, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 3339, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1126, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by pukkandan** [comment] 2022-03-24 23:36
> (one of the videos is playable on invidious 2022.03.15-5b82370b ([invidious.snopyta.org](https://invidious.snopyta.org/))).

Neither of the videos you gave is working on invidious

**Comment by NanaMizukiAnother7** [comment] 2022-03-25 06:41
I can reproduce this issue here:
> C:\Users\User>yt-dlp -Uv https://youtube.com/watch?v=CUO8secmc0g -f "bestvideo[height<=1080]+bestaudio/best"
> [debug] Command-line config: ['-Uv', 'https://youtube.com/watch?v=CUO8secmc0g', '-f', 'bestvideo[height<=1080]+bestaudio/best']
> [debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
> [debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
> [debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
> [debug] exe versions: ffmpeg N-105883-g3706fb8f16-20220308 (setts), ffprobe N-105038-g30322ebe3c-sherpya
> [debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
> [debug] Proxy map: {}
> Latest version: 2022.03.08.1, Current version: 2022.03.08.1
> yt-dlp is up to date (2022.03.08.1)
> [debug] [youtube] Extracting URL: https://youtube.com/watch?v=CUO8secmc0g
> [youtube] CUO8secmc0g: Downloading webpage
> [youtube] CUO8secmc0g: Downloading android player API JSON
> [youtube] CUO8secmc0g: Downloading android agegate player API JSON
> [youtube] CUO8secmc0g: Downloading web agegate player API JSON
> ERROR: [youtube] CUO8secmc0g: Sign in to confirm your age. This video may be inappropriate for some users.
>   File "yt_dlp\extractor\common.py", line 617, in extract
>   File "yt_dlp\extractor\youtube.py", line 3339, in _real_extract
>   File "yt_dlp\extractor\common.py", line 1126, in raise_no_formats

**Comment by vaaski** [comment] 2022-03-25 07:13
I can also confirm
```cmd
yt-dlp -J https://youtube.com/watch?v=CUO8secmc0g
ERROR: [youtube] CUO8secmc0g: Sign in to confirm your age. This video may be inappropriate for some users.
null
```

**Comment by pukkandan** [comment] 2022-03-25 07:23
[Tier 1](https://github.com/yt-dlp/yt-dlp/pull/575#issuecomment-888837000) bypass will be fixed by https://github.com/yt-dlp/yt-dlp/commit/ae72962643aa43b1e1037293b226acc71fb34297. Tier 2 bypass appears to have been patched. Until someone finds a new method, nothing can be done about this

Note that afaik, unverified logged-in cookies still work to bypass the ID verification requirement in EU

You might want to check out [this plugin](https://github.com/yt-dlp/yt-dlp/issues/2808#issuecomment-1078620107) that uses a [third-party proxy](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/tree/main/account-proxy) to perform bypass (why this isn't merged into yt-dlp is [explained here](https://github.com/yt-dlp/yt-dlp/issues/2808#issuecomment-1042588812))

**Comment by nicolaasjan** [comment] 2022-03-25 07:52
> Note that afaik, unverified logged-in cookies still work to bypass the ID verification requirement in EU

Confirmed.
Here in The Netherlands the [second video](https://www.youtube.com/watch?v=dIZ-e4WwJ5w) downloaded with `--cookies-from-browser`.

**Comment by rajatvermaiam** [comment] 2022-03-26 18:41
Yes , the embed method  to bypass  age restricted videos are no longer  working..

**Comment by Doktor-X** [comment] 2022-03-27 09:47
I dont get why google is so determined to prevent users to see age restricted content, and constantly making changes to api

**Comment by swiftgeek** [comment] 2022-03-28 02:35
This seems to work for me https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass

**Comment by duarm** [comment] 2022-03-28 14:44
> I dont get why google is so determined to prevent users to see age restricted content, and constantly making changes to api

they most likely just want you to use your addressable cookies

**Closed** 2022-03-29 10:05 UTC
Labels: site-bug

**Comment by Idesmi** [comment] 2022-04-18 06:59
This seems to be happening again.

**Comment by coletdjnz** [comment] 2022-04-18 07:04
> This seems to be happening again.

Still seems to be working for me? not all videos will work. The second video ([dIZ-e4WwJ5w](https://youtube.com/watch?v=dIZ-e4WwJ5w)) OP posted is working, the first never worked afaik.

**Comment by Idesmi** [comment] 2022-04-18 07:20
> Still seems to be working for me? not all videos will work. The second video ([dIZ-e4WwJ5w](https://youtube.com/watch?v=dIZ-e4WwJ5w)) OP posted is working, the first never worked afaik.

Unfortunately from Italy that isn't working, both passing or not cookies from browser.
I am logged in with an account but I haven't verified age with ID.

**Comment by pukkandan** [comment] 2022-04-18 11:02
Open a new issue with necessary details including a verbose log

**Comment by pukkandan** [comment] 2022-06-16 01:37
@xznhj8129 tiers 1-3 are still working. tier 4 never worked without cookies (Tiers: https://github.com/yt-dlp/yt-dlp/pull/575#issuecomment-888837000)

If you are saying it is broken with logged in cookies, open a new issue with verbose log. Otherwise, the video you are checking is likely tier 4. If you have reason to think it is not, explain with verbose log

**Comment by ask2018** [comment] 2023-03-22 07:52
It is broken again. See also this. Seems to be related, that all local bypasses stopped working after some YT change.
https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/183

**Comment by ask2018** [comment] 2023-03-22 10:58
Yeah with login probably yes, but my point is it is not working without login as it was working before. I didn't even know about the cookies feature to be honest, but many people included me don't want to create accounts on Google services like Youtube at all. And as it was working before without the account. I'd like to see this great feature fixed.

**Comment by pukkandan** [comment] 2023-03-22 15:52
@ask2018 Read https://github.com/yt-dlp/yt-dlp/issues/3182#issuecomment-1078730899 for a status of the various age-gate workarounds

> `--cookies-from-browser` isn't even supported on Pale Moon b.t.w.

https://github.com/yt-dlp/yt-dlp/issues/2903
