### ISSUE TITLE
Discovery - free video but stated "This video is only available for registered users"

### ISSUE THREAD

**Issue by fedepr** [yt-dlp/yt-dlp#2073] opened 2021-12-21 08:43 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Description

Hello, i wanted to download as usual from Discovery plus but now it says that the video is available only for registered users, but that's not true, this video is available for free and not for registered users only as yt-dlp is stating... how can i solve this??
The url is "https://www.discoveryplus.com/it/video/i-signori-della-neve/stagione-2-episodio-1-i-preparativi"
Can anyone kindly help?

### Verbose log

```shell
yt-dlp_min.exe -Uv -F https://www.discoveryplus.com/it/video/i-signori-della-neve/stagione-2-episodio-1-i-preparativi
[debug] Command-line config: ['-Uv', '-F', 'https://www.discoveryplus.com/it/video/i-signori-della-neve/stagione-2-episodio-1-i-preparativi']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (py2exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042
[debug] exe versions: none
[debug] Optional libraries: mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/it/video/i-signori-della-neve/stagione-2-episodio-1-i-preparativi
[debug] Using fake IP 6.141.33.185 (US) as X-Forwarded-For
[DiscoveryPlus] i-signori-della-neve/stagione-2-episodio-1-i-preparativi: Downloading JSON metadata
ERROR: [DiscoveryPlus] i-signori-della-neve/stagione-2-episodio-1-i-preparativi: This video is only available for registered users. You may want to use --cookies.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.pyc", line 715, in _request_webpage
  File "yt_dlp\YoutubeDL.pyc", line 3385, in urlopen
  File "urllib\request.pyc", line 531, in open
  File "urllib\request.pyc", line 640, in http_response
  File "urllib\request.pyc", line 569, in error
  File "urllib\request.pyc", line 502, in _call_chain
  File "urllib\request.pyc", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\dplay.pyc", line 80, in _get_disco_api_info
  File "yt_dlp\extractor\common.pyc", line 977, in _download_json
  File "yt_dlp\extractor\common.pyc", line 956, in _download_json_handle
  File "yt_dlp\extractor\common.pyc", line 748, in _download_webpage_handle
  File "yt_dlp\extractor\common.pyc", line 733, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.pyc", line 597, in extract
  File "yt_dlp\extractor\dplay.pyc", line 396, in _real_extract
  File "yt_dlp\extractor\dplay.pyc", line 92, in _get_disco_api_info
  File "yt_dlp\extractor\dplay.pyc", line 50, in _process_errors
yt_dlp.utils.ExtractorError: This video is only available for registered users. You may want to use --cookies.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.pyc", line 715, in _request_webpage
  File "yt_dlp\YoutubeDL.pyc", line 3385, in urlopen
  File "urllib\request.pyc", line 531, in open
  File "urllib\request.pyc", line 640, in http_response
  File "urllib\request.pyc", line 569, in error
  File "urllib\request.pyc", line 502, in _call_chain
  File "urllib\request.pyc", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\dplay.pyc", line 80, in _get_disco_api_info
  File "yt_dlp\extractor\common.pyc", line 977, in _download_json
  File "yt_dlp\extractor\common.pyc", line 956, in _download_json_handle
  File "yt_dlp\extractor\common.pyc", line 748, in _download_webpage_handle
  File "yt_dlp\extractor\common.pyc", line 733, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.pyc", line 597, in extract
  File "yt_dlp\extractor\dplay.pyc", line 396, in _real_extract
  File "yt_dlp\extractor\dplay.pyc", line 92, in _get_disco_api_info
  File "yt_dlp\extractor\dplay.pyc", line 50, in _process_errors
yt_dlp.utils.ExtractorError: This video is only available for registered users. You may want to use --cookies.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.pyc", line 1329, in wrapper
  File "yt_dlp\YoutubeDL.pyc", line 1398, in __extract_info
  File "yt_dlp\extractor\common.pyc", line 623, in extract
yt_dlp.utils.ExtractorError: [DiscoveryPlus] i-signori-della-neve/stagione-2-episodio-1-i-preparativi: This video is only available for registered users. You may want to use --cookies.
```

**Comment by Ashish0804** [comment] 2021-12-21 08:49
try passing cookies (just logged in, no sub needed)

**Comment by fedepr** [comment] 2021-12-22 09:51
would --cookies-from-browser firefox work instead? because i'm struggling with the --cookies and "Netscape format cookies file"

**Comment by pukkandan** [comment] 2021-12-22 12:57
Yes, assuming you are logged in to firefox

**Comment by fedepr** [comment] 2021-12-22 14:37
nope...

yt-dlp_min.exe -Uv --cookies-from-browser firefox -F "https://www.discoveryplus.com/it/video/i-signori-della-neve/stagione-2-episodio-1-i-preparativi"
[debug] Command-line config: ['-Uv', '--cookies-from-browser', 'firefox', '-F', 'https://www.discoveryplus.com/it/video/i-signori-della-neve/stagione-2-episodio-1-i-preparativi']
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "XXX\cookies.sqlite"
[Cookies] Extracted 376 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (py2exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042
[debug] exe versions: none
[debug] Optional libraries: mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/it/video/i-signori-della-neve/stagione-2-episodio-1-i-preparativi
[debug] Using fake IP 6.223.201.89 (US) as X-Forwarded-For
[DiscoveryPlus] i-signori-della-neve/stagione-2-episodio-1-i-preparativi: Downloading JSON metadata
ERROR: [DiscoveryPlus] i-signori-della-neve/stagione-2-episodio-1-i-preparativi: This video is only available for registered users. You may want to use --cookies.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.pyc", line 715, in _request_webpage
  File "yt_dlp\YoutubeDL.pyc", line 3385, in urlopen
  File "urllib\request.pyc", line 531, in open
  File "urllib\request.pyc", line 640, in http_response
  File "urllib\request.pyc", line 569, in error
  File "urllib\request.pyc", line 502, in _call_chain
  File "urllib\request.pyc", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\dplay.pyc", line 80, in _get_disco_api_info
  File "yt_dlp\extractor\common.pyc", line 977, in _download_json
  File "yt_dlp\extractor\common.pyc", line 956, in _download_json_handle
  File "yt_dlp\extractor\common.pyc", line 748, in _download_webpage_handle
  File "yt_dlp\extractor\common.pyc", line 733, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.pyc", line 597, in extract
  File "yt_dlp\extractor\dplay.pyc", line 396, in _real_extract
  File "yt_dlp\extractor\dplay.pyc", line 92, in _get_disco_api_info
  File "yt_dlp\extractor\dplay.pyc", line 50, in _process_errors
yt_dlp.utils.ExtractorError: This video is only available for registered users. You may want to use --cookies.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.pyc", line 715, in _request_webpage
  File "yt_dlp\YoutubeDL.pyc", line 3385, in urlopen
  File "urllib\request.pyc", line 531, in open
  File "urllib\request.pyc", line 640, in http_response
  File "urllib\request.pyc", line 569, in error
  File "urllib\request.pyc", line 502, in _call_chain
  File "urllib\request.pyc", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\dplay.pyc", line 80, in _get_disco_api_info
  File "yt_dlp\extractor\common.pyc", line 977, in _download_json
  File "yt_dlp\extractor\common.pyc", line 956, in _download_json_handle
  File "yt_dlp\extractor\common.pyc", line 748, in _download_webpage_handle
  File "yt_dlp\extractor\common.pyc", line 733, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.pyc", line 597, in extract
  File "yt_dlp\extractor\dplay.pyc", line 396, in _real_extract
  File "yt_dlp\extractor\dplay.pyc", line 92, in _get_disco_api_info
  File "yt_dlp\extractor\dplay.pyc", line 50, in _process_errors
yt_dlp.utils.ExtractorError: This video is only available for registered users. You may want to use --cookies.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.pyc", line 1329, in wrapper
  File "yt_dlp\YoutubeDL.pyc", line 1398, in __extract_info
  File "yt_dlp\extractor\common.pyc", line 623, in extract
yt_dlp.utils.ExtractorError: [DiscoveryPlus] i-signori-della-neve/stagione-2-episodio-1-i-preparativi: This video is only available for registered users. You may want to use --cookies.

any help?

**Comment by timethrow** [comment] 2021-12-23 09:29
I **think** its this;

```
[debug] Using fake IP 6.223.201.89 (US) as X-Forwarded-For
```

**Comment by MinePlayersPE** [comment] 2021-12-23 09:35
If above is correct, then duplicate of https://github.com/yt-dlp/yt-dlp/issues/1623?
(Test with `--no-geo-bypass`)

**Comment by rgabbo** [comment] 2021-12-23 12:58
Same issue here. Tried with `--no-geo-bypass` and extracting cookies from edge but I get the same error that video is available only to registered users (I have a paid subscription).

**Comment by timethrow** [comment] 2021-12-23 13:58
Thanks, taking a further look, I think the Geo Stuff, is a Red Herring, but pointed me in the right direction (and still needs to be fixes, but there a separate issue for that).

It looks like following the site domain changes from `discoveryplus.it` to `discoveryplus.com/it/` it uses the `DiscoveryPlusIE` Extractor now;

https://github.com/yt-dlp/yt-dlp/blob/b28bac93abe9d376b0b05c467006a5f7135b9aee/yt_dlp/extractor/dplay.py#L350-L397

This has a couple of issues for non US (and possibly Canada?) sites;

1. The API URL is hardcoded to `us1-prod-direct.discoveryplus.com`, looking at the site via a VPN, it should be `eu1-prod-direct.discoveryplus.com` for Italy (and probably most/all Europe sites). - Guessing a bit here, but there is either additional authentication/verification on the API endpoints or they are separate systems and so it does not understand the request hence a 400.
2. In Line 397 its forcing a US Country Code, this should be extracted from the URL now and if none is provided fallback to US (since their URLs don't have one). So long as the Country Code matches this will then fix issue #1623 as in Lines 70-73, it uses the Country Code specified.

I should note I don't have a Italian (or European) Discovery+ Account so I can't test/verify that this will fix it all, but that looks to be the bulk of it. From what I could see (and I couldn't get any videos to play) the request format looks to be the same, just different endpoints.

A PR to fix it _should_ be relatively simple, but it depends on how we want to translate Country Codes to API Endpoints, and if there are many endpoints, how we verify/test them.

**Comment by pukkandan** [comment] 2021-12-23 14:26
Does it work if you pass the URL `discoveryplus.it/...`? Is only Italy affected by this change? If so, a simpler fix would be to just adjust the `VALID_URL`s to account for this

> A PR to fix it should be relatively simple, but it depends on how we want to translate Country Codes to API Endpoints, and if there are many endpoints, how we verify/test them.

`DplayIE` already has a mechanism to change the API endpoint based on country code. It just needs to be improved (or generalized to DiscoveryPlusIE) to account for the new changes

**Comment by Tb3986** [comment] 2021-12-23 15:09
You should try with discoveryplus.it and not: com/it
https://i.postimg.cc/7ZCPRxZ5/Untitled.jpg

You get this (i'm stuck too with discoveryplus since all protection has been changed).

Now? Any advice to download and decrypt audio and video? Still figure out this part.

Thank you

**Comment by TriHard7777** [comment] 2021-12-24 02:34
🤔

**Comment by pukkandan** [comment] 2021-12-24 03:44
@TriHard7777 Don't spam

**Closed** 2021-12-25 00:24 UTC
Labels: extractor-bug

**Comment by fedepr** [comment] 2021-12-26 08:58
hi! it works, but with the -F i see "audio only" and "video only" separated tracks... how can i choose and merge audio and video? or may i use external tools?

**Comment by pukkandan** [comment] 2021-12-26 10:43
Use + instead of ,

**Comment by fedepr** [comment] 2021-12-26 13:49
perfect!! + ffmpeg. thank you so much

**Comment by bann0** [comment] 2021-12-26 18:11
I have a similar problem,  I don't know if it's related or not.
These urls:
[https://www.discoveryplus.it/video/dal-pollaio-alla-pista/stagione-2-episodio-6-ford-escort-mk1-parte-1](url)
[https://www.discoveryplus.it/video/dal-pollaio-alla-pista/stagione-2-episodio-8-fiat-x19-silhouette-parte-1](url)
 work with a browser and not with yt-dlp.

$ yt-dlp --no-config -v https://www.discoveryplus.it/video/dal-pollaio-alla-pista/stagione-2-episodio-6-ford-escort-mk1-parte-1
[debug] Command-line config: ['--no-config', '-v', 'https://www.discoveryplus.it/video/dal-pollaio-alla-pista/stagione-2-episodio-6-ford-escort-mk1-parte-1']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.12.25 [87e049962]
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.7.3 (CPython 64bit) - Linux-4.19.0-18-amd64-x86_64-with-debian-10.11
[debug] exe versions: ffmpeg 4.1.8-0, ffprobe 4.1.8-0, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: Crypto, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [DPlay] Extracting URL: https://www.discoveryplus.it/video/dal-pollaio-alla-pista/stagione-2-episodio-6-ford-escort-mk1-parte-1
[debug] Using fake IP 79.30.156.88 (IT) as X-Forwarded-For
[DPlay] dal-pollaio-alla-pista/stagione-2-episodio-6-ford-escort-mk1-parte-1: Downloading token
[DPlay] dal-pollaio-alla-pista/stagione-2-episodio-6-ford-escort-mk1-parte-1: Downloading JSON metadata
[DPlay] 130662: Downloading JSON metadata
ERROR: [DPlay] dal-pollaio-alla-pista/stagione-2-episodio-6-ford-escort-mk1-parte-1: This video is only available for registered users. You may want to use --cookies.
  File "/opt/yt-dlp/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/opt/yt-dlp/yt_dlp/extractor/dplay.py", line 321, in _real_extract
    url, display_id, host, 'dplay' + country, country, domain)
  File "/opt/yt-dlp/yt_dlp/extractor/dplay.py", line 104, in _get_disco_api_info
    self._process_errors(e, geo_countries)
  File "/opt/yt-dlp/yt_dlp/extractor/dplay.py", line 51, in _process_errors
    'This video is only available for registered users. You may want to use --cookies.', expected=True)

Obviously same error with www.discoveryplus.com/it.
I have tried several combo cmd line params:
--cookies (extracted after free login auth)
--no-geo-bypass
--geo-bypass
--geo-bypass-country IT

This [https://www.discoveryplus.it/video/dal-pollaio-alla-pista/stagione-2-episodio-7-ford-escort-mk1-parte-2](url) works.

Maybe some episodes use DRM?
Someone can verify?
Thanks

**Comment by Tb3986** [comment] 2021-12-27 09:38
> I have a similar problem, I don't know if it's related or not. These urls: [https://www.discoveryplus.it/video/dal-pollaio-alla-pista/stagione-2-episodio-6-ford-escort-mk1-parte-1](url) [https://www.discoveryplus.it/video/dal-pollaio-alla-pista/stagione-2-episodio-8-fiat-x19-silhouette-parte-1](url) work with a browser and not with yt-dlp.
> 
> $ yt-dlp --no-config -v https://www.discoveryplus.it/video/dal-pollaio-alla-pista/stagione-2-episodio-6-ford-escort-mk1-parte-1 [debug] Command-line config: ['--no-config', '-v', 'https://www.discoveryplus.it/video/dal-pollaio-alla-pista/stagione-2-episodio-6-ford-escort-mk1-parte-1'] [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8 [debug] yt-dlp version 2021.12.25 [[87e0499](https://github.com/yt-dlp/yt-dlp/commit/87e049962422201950ece298ea5aee55684ca7a8)] [debug] Plugins: ['SamplePluginIE', 'SamplePluginPP'] [debug] Python version 3.7.3 (CPython 64bit) - Linux-4.19.0-18-amd64-x86_64-with-debian-10.11 [debug] exe versions: ffmpeg 4.1.8-0, ffprobe 4.1.8-0, phantomjs ., rtmpdump 2.4 [debug] Optional libraries: Crypto, keyring, mutagen, sqlite, websockets [debug] Proxy map: {} [debug] [DPlay] Extracting URL: https://www.discoveryplus.it/video/dal-pollaio-alla-pista/stagione-2-episodio-6-ford-escort-mk1-parte-1 [debug] Using fake IP 79.30.156.88 (IT) as X-Forwarded-For [DPlay] dal-pollaio-alla-pista/stagione-2-episodio-6-ford-escort-mk1-parte-1: Downloading token [DPlay] dal-pollaio-alla-pista/stagione-2-episodio-6-ford-escort-mk1-parte-1: Downloading JSON metadata [DPlay] 130662: Downloading JSON metadata ERROR: [DPlay] dal-pollaio-alla-pista/stagione-2-episodio-6-ford-escort-mk1-parte-1: This video is only available for registered users. You may want to use --cookies. File "/opt/yt-dlp/yt_dlp/extractor/common.py", line 599, in extract ie_result = self._real_extract(url) File "/opt/yt-dlp/yt_dlp/extractor/dplay.py", line 321, in _real_extract url, display_id, host, 'dplay' + country, country, domain) File "/opt/yt-dlp/yt_dlp/extractor/dplay.py", line 104, in _get_disco_api_info self._process_errors(e, geo_countries) File "/opt/yt-dlp/yt_dlp/extractor/dplay.py", line 51, in _process_errors 'This video is only available for registered users. You may want to use --cookies.', expected=True)
> 
> Obviously same error with [www.discoveryplus.com/it](http://www.discoveryplus.com/it). I have tried several combo cmd line params: --cookies (extracted after free login auth) --no-geo-bypass --geo-bypass --geo-bypass-country IT
> 
> This [https://www.discoveryplus.it/video/dal-pollaio-alla-pista/stagione-2-episodio-7-ford-escort-mk1-parte-2](url) works.
> 
> Maybe some episodes use DRM? Someone can verify? Thanks

Same for me for Bake Off Italy. Everytime i get: "This video is only available for registered users. You may want to use --cookies." but i exported all my cookie.

**Comment by pukkandan** [comment] 2021-12-27 17:25
the original reported issue was caused due to the URL being passed to the wrong extractor. This has been fixed. Your issue is different despite the same error message. Please open a new issue (with verbose log while passing cookies). I suggest also trying `--no-geo-bypass`

**Comment by fedepr** [comment] 2022-05-17 14:45
hi, sorry to reopen this but unfortunately it happened again. being the alternative dmax.it link not recognized, i tried to download from https://www.discoveryplus.com/it/video/uomini-di-pietra/stagione-1-episodio-1-le-cave-di-marmo and similars - but now it's not working anymore (it says only available for registered users but the video is marked as "free" and i can't proceed)
