### ISSUE TITLE
Not working  anymore on france.tv

### ISSUE THREAD

**Issue by denezmarchand** [yt-dlp/yt-dlp#9376] opened 2024-03-06 20:11 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

yt-dlp not working anymore on france.tv site

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.france.tv/france-2/la-peste/saison-1/5762901-episode-1.html
[debug] Command-line config: ['-vU', 'https://www.france.tv/france-2/la-peste/saison-1/5762901-episode-1.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.12.2 (CPython aarch64 64bit) - Linux-6.7.7-200.fc39.aarch64-aarch64-with-glibc2.38 (OpenSSL 3.1.1 30 May 2023, glibc 2.38)
[debug] exe versions: ffmpeg N-112890-g0a13178de8-20231202 (setts), ffprobe N-112890-g0a13178de8-20231202
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.05.07, mutagen-1.46.0, requests-2.28.2, sqlite3-3.42.0, urllib3-1.26.18, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[FranceTVSite] Extracting URL: https://www.france.tv/france-2/la-peste/saison-1/5762901-episode-1.html
[FranceTVSite] 5762901-episode-1: Downloading webpage
[FranceTV] Extracting URL: francetv:60b0fc1a-9b38-4ba6-b6dc-3bb2a9ccc509
[FranceTV] 60b0fc1a-9b38-4ba6-b6dc-3bb2a9ccc509: Downloading desktop video JSON
WARNING: [FranceTV] Unable to download JSON metadata: HTTP Error 400: Bad Request
[FranceTV] 60b0fc1a-9b38-4ba6-b6dc-3bb2a9ccc509: Downloading mobile video JSON
WARNING: [FranceTV] Unable to download JSON metadata: HTTP Error 400: Bad Request
[debug] Extractor gave empty title. Creating a generic title
ERROR: [FranceTV] 60b0fc1a-9b38-4ba6-b6dc-3bb2a9ccc509: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1587, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1743, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1802, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2781, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1085, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [FranceTV] 60b0fc1a-9b38-4ba6-b6dc-3bb2a9ccc509: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment] 2024-03-06 21:01
Duplicate of #9323

run `yt-dlp --update-to nightly` and try again

**Closed by bashonly** 2024-03-06 21:01 UTC
Labels: site-bug, triage
