### ISSUE TITLE
Error on France TV : "Failed to download MPD manifest: HTTP Error 403: Forbidden"

### ISSUE THREAD

**Issue by SpaceOds** [yt-dlp/yt-dlp#10186] opened 2024-06-15 00:20 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

Hello,

I tried downloading a video from the https://www.france.tv/ site, and I got an error 403. The result is the same whatever valid URL I give. Two days ago (during the night between Wednesday 12th & Thursday 13th, France time), it was still working. I updated yt-dlp to no avail.

I have separate installations for stable & nightly releases. The output for the nightly version was exactly the same. But interrestingly, when I wanted to update my nightly setup, it just said : `ERROR: tag/francetv` and that's all !

I found this issue : https://github.com/yt-dlp/yt-dlp/issues/10153 which also is about an error 403, but I'm not sure it's really the same, since what I get is about downloading the MPD manifest & the m3u8 information, and not the whole webpage.

Nevertheless, it advised to use curl_cffi, so I installed it with `pip install curl_cffi --upgrade`, and tried with `--impersonate chrome` added to my command, but I must be missing something, as the answer was : `yt-dlp: error: no such option: --impersonate`.

Can you help me ? Thanks.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.france.tv/films/6073196-ghost-dog-la-voie-du-samourai.html']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111652-gbf9f6a5e55-20230730 (setts), ffprobe N-111652-gbf9f6a5e55-20230730
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.2, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[FranceTVSite] Extracting URL: https://www.france.tv/films/6073196-ghost-dog-la-voie-du-samourai.html
[FranceTVSite] 6073196-ghost-dog-la-voie-du-samourai: Downloading webpage
[FranceTV] Extracting URL: francetv:9b962884-237d-440e-8041-1bb81a05e11d#__youtubedl_smuggle=%7B%22hostname%22%3A+%22www.france.tv%22%7D
[FranceTV] 9b962884-237d-440e-8041-1bb81a05e11d: Downloading desktop chrome video JSON
[FranceTV] 9b962884-237d-440e-8041-1bb81a05e11d: Downloading mobile safari video JSON
[FranceTV] 9b962884-237d-440e-8041-1bb81a05e11d: Downloading MPD manifest
WARNING: [FranceTV] Failed to download MPD manifest: HTTP Error 403: Forbidden
[FranceTV] 9b962884-237d-440e-8041-1bb81a05e11d: Downloading m3u8 information
WARNING: [FranceTV] Failed to download m3u8 information: HTTP Error 403: Forbidden
[FranceTV] 9b962884-237d-440e-8041-1bb81a05e11d: Checking for geo-restriction
WARNING: Only images are available for download. use --list-formats to see them
[debug] Sort order given by extractor: res, tbr, proto
[debug] Formats sorted by: hasvid, ie_pref, res, tbr, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
ERROR: [FranceTV] 9b962884-237d-440e-8041-1bb81a05e11d: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1606, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1762, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1821, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2955, in process_video_result
yt_dlp.utils.ExtractorError: [FranceTV] 9b962884-237d-440e-8041-1bb81a05e11d: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by seproDev** [comment] 2024-06-15 00:24
Duplicate of #10175
Update to nightly
```
yt-dlp --update-to nightly
```

**Closed by seproDev** 2024-06-15 00:24 UTC
Labels: site-bug, triage

**Comment by SpaceOds** [comment] 2024-06-15 02:50
I'm sorry, I hadn't seen the duplicate. As the problem was very recent, I only looked at the first page of listed issues, and it didn't appeared there…
As I had told, my nightly setup wouldn't update. But when I switched my stable setup to nightly, it worked perfectly !
Thank you very much for such a prompt answer.
