### ISSUE TITLE
[Twitcasting] steam/movie download. Initialization fragment found after media fragments error.

### ISSUE THREAD

**Issue by cherryxmilktea** [yt-dlp/yt-dlp#10741] opened 2024-08-14 03:05 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

America

### Provide a description that is worded well enough to be understood

I am unable to download this twitcasting steam. And I was able to download other shorter streams. I apologize if I'm being oblivious, as it's my first time using anything like this.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://twitcasting.tv/luluu_ria/movie/795973331']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.13.232739 from yt-dlp/yt-dlp-nightly-builds [232e6db30] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.13.232739 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.13.232739 from yt-dlp/yt-dlp-nightly-builds)
[TwitCasting] Extracting URL: https://twitcasting.tv/luluu_ria/movie/795973331
[TwitCasting] 795973331: Downloading webpage
[TwitCasting] 795973331: Downloading live info
[TwitCasting] 795973331: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 795973331: Downloading 1 format(s): 2660
[debug] Invoking hlsnative downloader on "https://dl193248.twitcasting.tv/tc.vod.v2/v1/streams/795973331.0.2.1.1719459405/hls/v0/media.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3405
[download] Destination: さいごのおうたわく [795973331].mp4
[debug] File locking is not supported. Proceeding without locking
ERROR: Initialization fragment found after media fragments, unable to download
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1081, in main
  File "yt_dlp\__init__.py", line 1071, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3607, in download
  File "yt_dlp\YoutubeDL.py", line 3582, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1615, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 3015, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 179, in wrapper
  File "yt_dlp\YoutubeDL.py", line 3483, in process_info
  File "yt_dlp\YoutubeDL.py", line 3203, in dl
  File "yt_dlp\downloader\common.py", line 466, in download
  File "yt_dlp\downloader\hls.py", line 211, in real_download
  File "yt_dlp\YoutubeDL.py", line 1092, in report_error
  File "yt_dlp\YoutubeDL.py", line 1020, in trouble
```

**Comment by bashonly** [comment] 2024-08-14 03:09
Duplicate of #5497

Pass `--downloader ffmpeg` to work around the issue

**Closed by bashonly** 2024-08-14 03:09 UTC
Labels: site-bug, triage

**Comment by cherryxmilktea** [comment] 2024-08-14 03:12
Am I doing something wrong?
C:\Users\stell\Videos>yt-dlp --downloader ffmpeg https://twitcasting.tv/luluu_ria/movie/795973331
[TwitCasting] Extracting URL: https://twitcasting.tv/luluu_ria/movie/795973331
[TwitCasting] 795973331: Downloading webpage
[TwitCasting] 795973331: Downloading live info
[TwitCasting] 795973331: Downloading m3u8 information
[info] 795973331: Downloading 1 format(s): 2660
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3405
[download] Destination: さいごのおうたわく [795973331].mp4
ERROR: Initialization fragment found after media fragments, unable to download

**Comment by bashonly** [comment] 2024-08-29 20:20
install ffmpeg

**Comment by e-ave** [comment] 2024-12-13 00:26
> Duplicate of #5497
> 
> Pass `--downloader ffmpeg` to work around the issue

This is not a solution... ffmpeg produces a corrupted video
