### ISSUE TITLE
Forcing color output even when redirected

### ISSUE THREAD

**Issue by ClementNerma** [yt-dlp/yt-dlp#3856] opened 2022-05-24 07:23 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hi there!

I'm currently using `yt-dlp` in some automation tools where I'd like to write the output to a file and still display it in the terminal. Using ZSH, I either have the choice of doing `yt-dlp [...] 1>&1 2>&2 1>stdout.log` or `yt-dlp [...] | tee stdout.log`.

But when using any of these options, the output displayed in the terminal doesn't contain any color. It seems like `yt-dlp` detects its output is being redirected and thus disables color output.

Would it be possible to force color output even when redirected? I don't care if the log file is bloated with espace sequences.

Thanks in advance!

**Comment by pukkandan** [comment] 2022-05-24 08:31
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3643

**Closed by pukkandan** 2022-05-24 08:31 UTC
Labels: enhancement, triage
