### ISSUE TITLE
YouTube Music Incomplete Title/Song name

### ISSUE THREAD

**Issue by RaduTek** [yt-dlp/yt-dlp#4111] opened 2022-06-19 10:25 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

So I want to download some albums/singles which have multiple remixes of a song, but the track name of each file is the same and lacks the remix name in the parentheses.

Sample single: [https://music.youtube.com/playlist?list=OLAK5uy_mNSRRQ4ohcVspLLa42g1NUdafH5zc6Dik](url)

On the YT Music page you can clearly see each track has a different name, but when opening the playlist in regular YouTube the parentheses are missing. Same applies to YT-DLP, even when dumping the metadata with `--write-info-json`. You cannot find the complete song name in there.

I think this may be an issue on YouTube's side, maybe a quirk of how these tracks were added into their database. Not sure if this can be fixed without reworking how YouTube downloads work or how metadata is pulled though.

### Verbose log

```shell
[debug] Command-line config: ['--verbose', '--extract-audio', '--embed-metadata', 'https://music.youtube.com/playlist?list=OLAK5uy_mNSRRQ4ohcVspLLa42g1NUdafH5zc6Dik']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 2022-06-16-git-5242ede48d-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://music.youtube.com/playlist?list=OLAK5uy_mNSRRQ4ohcVspLLa42g1NUdafH5zc6Dik
[youtube:tab] OLAK5uy_mNSRRQ4ohcVspLLa42g1NUdafH5zc6Dik: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=OLAK5uy_mNSRRQ4ohcVspLLa42g1NUdafH5zc6Dik
[youtube:tab] OLAK5uy_mNSRRQ4ohcVspLLa42g1NUdafH5zc6Dik: Downloading API JSON with unavailable videos
[download] Downloading playlist: Album - All Night High
[youtube:tab] playlist Album - All Night High: Downloading 5 videos
[download] Downloading video 1 of 5
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=-AmisaMS7vQ#__youtubedl_smuggle=%7B%22is_music_url%22%3A+true%7D
[youtube] -AmisaMS7vQ: Downloading webpage
[youtube] -AmisaMS7vQ: Downloading android player API JSON
[youtube] -AmisaMS7vQ: Downloading android music player API JSON
[youtube] -AmisaMS7vQ: Downloading web music client config
[youtube] -AmisaMS7vQ: Downloading player f05de49d
[youtube] -AmisaMS7vQ: Downloading web music player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] -AmisaMS7vQ: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr5---sn-gqn-ungs.googlevideo.com/videoplayback?expire=1655655479&ei=1_euYuf-KOmXx_APkumMwAs&ip=2a02%3A2f09%3A350e%3Ac00%3Ad173%3A4f44%3Ab26c%3Ad21&id=o-AJ_DyZvtKq0ACXxeznEakk9sTlG4AdaFnjOucDE_O2kK&itag=251&source=youtube&requiressl=yes&mh=q_&mm=31%2C29&mn=sn-gqn-ungs%2Csn-c0q7lns7&ms=au%2Crdu&mv=m&mvi=5&pcm2cms=yes&pl=45&gcr=ro&initcwndbps=1416250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=6995360&dur=431.601&lmt=1570186458378697&mt=1655633565&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=1301222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOAGQa3uvGSTZoRIJqe61HApa4tTA37eMwynuHeP_xD-AiBckaQiWfPDgg-ydXW9z3dMgVnbtveNybFyxxUfY13MCw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMD4xZv1RvGEivrY4wqxiq0gWF0wUEnPlRCoyzec-sgDAiEA3FoE1vKaC301MGwBiF4VObWRNiMAl0nhZYvpmEi9wvI%3D"
[debug] File locking is not supported on this platform. Proceeding without locking
[download] Destination: All Night High [-AmisaMS7vQ].webm
[download] 100% of 6.67MiB in 00:00
[debug] ffmpeg command line: ffmpeg -i "file:All Night High [-AmisaMS7vQ].webm"
[ExtractAudio] Destination: All Night High [-AmisaMS7vQ].opus
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:All Night High [-AmisaMS7vQ].webm" -vn -acodec copy -movflags "+faststart" "file:All Night High [-AmisaMS7vQ].opus"
Deleting original file All Night High [-AmisaMS7vQ].webm (pass -k to keep)
[Metadata] Adding metadata to "All Night High [-AmisaMS7vQ].opus"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:All Night High [-AmisaMS7vQ].opus" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=All Night High" -metadata "date=20170830" -metadata "description=Provided to YouTube by Ingrooves

All Night High · Lisa Shaw

All Night High

℗ ℗ 2008 SALTED MUSIC

Released on: 2008-03-25

Composer, Writer: Dave Warrin
Remixer: Miguel Migs

Auto-generated by YouTube." -metadata "synopsis=Provided to YouTube by Ingrooves

All Night High · Lisa Shaw

All Night High

℗ ℗ 2008 SALTED MUSIC

Released on: 2008-03-25

Composer, Writer: Dave Warrin
Remixer: Miguel Migs

Auto-generated by YouTube." -metadata "purl=https://www.youtube.com/watch?v=-AmisaMS7vQ" -metadata "comment=https://www.youtube.com/watch?v=-AmisaMS7vQ" -metadata "artist=Lisa Shaw" -metadata "album=All Night High" -movflags "+faststart" "file:All Night High [-AmisaMS7vQ].temp.opus"
[download] Downloading video 2 of 5
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=DOKLjKqlPBY#__youtubedl_smuggle=%7B%22is_music_url%22%3A+true%7D
[youtube] DOKLjKqlPBY: Downloading webpage
[youtube] DOKLjKqlPBY: Downloading android player API JSON
[youtube] DOKLjKqlPBY: Downloading android music player API JSON
[youtube] DOKLjKqlPBY: Downloading web music client config
[youtube] DOKLjKqlPBY: Downloading web music player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] DOKLjKqlPBY: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr4---sn-gqn-ungs.googlevideo.com/videoplayback?expire=1655655482&ei=2veuYo2CGI_x-gaAxbPgBQ&ip=2a02%3A2f09%3A350e%3Ac00%3Ad173%3A4f44%3Ab26c%3Ad21&id=o-ADxIl3zPxTXiFGXnX1_obJgvNTVy3RN7Gam1ASX-0UU3&itag=251&source=youtube&requiressl=yes&mh=uZ&mm=31%2C29&mn=sn-gqn-ungs%2Csn-c0q7lns7&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=45&gcr=ro&initcwndbps=1416250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=6305932&dur=385.261&lmt=1570192598448488&mt=1655633565&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=1301222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAM_8swwtXSiqFBnQpCV4RjPYAiq5ZDBZxZbHY3azsmsDAiEAkMEO095KGD_XqsrWoVC0B7q_5cG86u6hJIJzFHCilCs%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgKYfxYvjxnYeoOe0SWkSkXgLcaU_s6rYlFF4oi5_tjnMCIHWPr55eFM3xbuxVhy2TKYVgjMycEiF8h_Ka6vjDW01k"
[download] Destination: All Night High [DOKLjKqlPBY].webm
[download] 100% of 6.01MiB in 00:01
[debug] ffmpeg command line: ffmpeg -i "file:All Night High [DOKLjKqlPBY].webm"
[ExtractAudio] Destination: All Night High [DOKLjKqlPBY].opus
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:All Night High [DOKLjKqlPBY].webm" -vn -acodec copy -movflags "+faststart" "file:All Night High [DOKLjKqlPBY].opus"
Deleting original file All Night High [DOKLjKqlPBY].webm (pass -k to keep)
[Metadata] Adding metadata to "All Night High [DOKLjKqlPBY].opus"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:All Night High [DOKLjKqlPBY].opus" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=All Night High" -metadata "date=20170830" -metadata "description=Provided to YouTube by Ingrooves

All Night High · Lisa Shaw

All Night High

℗ ℗ 2008 SALTED MUSIC

Released on: 2008-03-25

Composer, Writer: Dave Warrin
Remixer: Miguel Migs

Auto-generated by YouTube." -metadata "synopsis=Provided to YouTube by Ingrooves

All Night High · Lisa Shaw

All Night High

℗ ℗ 2008 SALTED MUSIC

Released on: 2008-03-25

Composer, Writer: Dave Warrin
Remixer: Miguel Migs

Auto-generated by YouTube." -metadata "purl=https://www.youtube.com/watch?v=DOKLjKqlPBY" -metadata "comment=https://www.youtube.com/watch?v=DOKLjKqlPBY" -metadata "artist=Lisa Shaw" -metadata "album=All Night High" -movflags "+faststart" "file:All Night High [DOKLjKqlPBY].temp.opus"
[download] Downloading video 3 of 5
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=J-Sr0FSZCBc#__youtubedl_smuggle=%7B%22is_music_url%22%3A+true%7D
[youtube] J-Sr0FSZCBc: Downloading webpage
[youtube] J-Sr0FSZCBc: Downloading android player API JSON
[youtube] J-Sr0FSZCBc: Downloading android music player API JSON
[youtube] J-Sr0FSZCBc: Downloading web music client config
[youtube] J-Sr0FSZCBc: Downloading web music player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] J-Sr0FSZCBc: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr3---sn-gqn-ung6.googlevideo.com/videoplayback?expire=1655655486&ei=3veuYreRA9qmx_AP44e8uAs&ip=2a02%3A2f09%3A350e%3Ac00%3Ad173%3A4f44%3Ab26c%3Ad21&id=o-AH1nJ7B1qBlYBZMI-feijUbC1MPTPk4Il7G6E_oUJK2O&itag=251&source=youtube&requiressl=yes&mh=dq&mm=31%2C29&mn=sn-gqn-ung6%2Csn-c0q7lnse&ms=au%2Crdu&mv=m&mvi=3&pl=45&gcr=ro&initcwndbps=1583750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=7332245&dur=450.221&lmt=1570199414064897&mt=1655633565&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=1301222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAPZWaAp6pkftVP_asHRQV0SI3m4LRLj7OKK-kqwZMnPQAiBOTRs8s602UIr03HhYD4Qx6BslzcQGckp41877wS3low%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANjZHXCmhbzAFNQpl1wTxpaW9lRA83rhgGBUXRcngo6tAiEAhhIiUF0y9-rVBuVRcVyjHmqNHkTGPuEFA5-ptepNvuY%3D"
[download] Destination: All Night High [J-Sr0FSZCBc].webm
[download] 100% of 6.99MiB in 00:01
[debug] ffmpeg command line: ffmpeg -i "file:All Night High [J-Sr0FSZCBc].webm"
[ExtractAudio] Destination: All Night High [J-Sr0FSZCBc].opus
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:All Night High [J-Sr0FSZCBc].webm" -vn -acodec copy -movflags "+faststart" "file:All Night High [J-Sr0FSZCBc].opus"
Deleting original file All Night High [J-Sr0FSZCBc].webm (pass -k to keep)
[Metadata] Adding metadata to "All Night High [J-Sr0FSZCBc].opus"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:All Night High [J-Sr0FSZCBc].opus" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=All Night High" -metadata "date=20170830" -metadata "description=Provided to YouTube by Ingrooves

All Night High · Lisa Shaw

All Night High

℗ ℗ 2008 SALTED MUSIC

Released on: 2008-03-25

Composer, Writer: Dave Warrin
Remixer: Justin Michael
Remixer: Solo

Auto-generated by YouTube." -metadata "synopsis=Provided to YouTube by Ingrooves

All Night High · Lisa Shaw

All Night High

℗ ℗ 2008 SALTED MUSIC

Released on: 2008-03-25

Composer, Writer: Dave Warrin
Remixer: Justin Michael
Remixer: Solo

Auto-generated by YouTube." -metadata "purl=https://www.youtube.com/watch?v=J-Sr0FSZCBc" -metadata "comment=https://www.youtube.com/watch?v=J-Sr0FSZCBc" -metadata "artist=Lisa Shaw" -metadata "album=All Night High" -movflags "+faststart" "file:All Night High [J-Sr0FSZCBc].temp.opus"
[download] Downloading video 4 of 5
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=u1kb7Dctze8#__youtubedl_smuggle=%7B%22is_music_url%22%3A+true%7D
[youtube] u1kb7Dctze8: Downloading webpage
[youtube] u1kb7Dctze8: Downloading android player API JSON
[youtube] u1kb7Dctze8: Downloading android music player API JSON
[youtube] u1kb7Dctze8: Downloading web music client config
[youtube] u1kb7Dctze8: Downloading web music player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] u1kb7Dctze8: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr7---sn-gqn-ungs.googlevideo.com/videoplayback?expire=1655655489&ei=4feuYuHHEJ6Wx_AP5KmYkAw&ip=2a02%3A2f09%3A350e%3Ac00%3Ad173%3A4f44%3Ab26c%3Ad21&id=o-AHgQYxZscgDxFES3Ht0VAFo1v2onNwDAhQvCKTiABYf5&itag=251&source=youtube&requiressl=yes&mh=Qo&mm=31%2C29&mn=sn-gqn-ungs%2Csn-c0q7lnsl&ms=au%2Crdu&mv=m&mvi=7&pcm2cms=yes&pl=45&gcr=ro&initcwndbps=1416250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=6992940&dur=415.501&lmt=1570217853518278&mt=1655633565&fvip=2&keepalive=yes&fexp=24001373%2C24007246%2C24208265&c=ANDROID&txp=1301222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgQySu3yGBNZiYDTwQOYoqPRNAdz91_m3boKvWFfPy_K4CIA68htmSdpcDdASf-APCwxO6H4nc_OQSDkzgHoDEHbDz&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANV7DVu5TxgjrkSSx4NivsfHqmc_BBdT112UNScdmsbSAiEAkNx7ce43f-2074ve4XXbqWCgFpWfzjFnfEgs5IpyHAc%3D"
[download] Destination: All Night High [u1kb7Dctze8].webm
[download] 100% of 6.67MiB in 00:01
[debug] ffmpeg command line: ffmpeg -i "file:All Night High [u1kb7Dctze8].webm"
[ExtractAudio] Destination: All Night High [u1kb7Dctze8].opus
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:All Night High [u1kb7Dctze8].webm" -vn -acodec copy -movflags "+faststart" "file:All Night High [u1kb7Dctze8].opus"
Deleting original file All Night High [u1kb7Dctze8].webm (pass -k to keep)
[Metadata] Adding metadata to "All Night High [u1kb7Dctze8].opus"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:All Night High [u1kb7Dctze8].opus" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=All Night High" -metadata "date=20170830" -metadata "description=Provided to YouTube by Ingrooves

All Night High · Lisa Shaw

All Night High

℗ ℗ 2008 SALTED MUSIC

Released on: 2008-03-25

Composer, Writer: Dave Warrin

Auto-generated by YouTube." -metadata "synopsis=Provided to YouTube by Ingrooves

All Night High · Lisa Shaw

All Night High

℗ ℗ 2008 SALTED MUSIC

Released on: 2008-03-25

Composer, Writer: Dave Warrin

Auto-generated by YouTube." -metadata "purl=https://www.youtube.com/watch?v=u1kb7Dctze8" -metadata "comment=https://www.youtube.com/watch?v=u1kb7Dctze8" -metadata "artist=Lisa Shaw" -metadata "album=All Night High" -movflags "+faststart" "file:All Night High [u1kb7Dctze8].temp.opus"
[download] Downloading video 5 of 5
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=rGyse2vUPoM#__youtubedl_smuggle=%7B%22is_music_url%22%3A+true%7D
[youtube] rGyse2vUPoM: Downloading webpage
[youtube] rGyse2vUPoM: Downloading android player API JSON
[youtube] rGyse2vUPoM: Downloading android music player API JSON
[youtube] rGyse2vUPoM: Downloading web music client config
[youtube] rGyse2vUPoM: Downloading web music player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] rGyse2vUPoM: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr8---sn-gqn-ungs.googlevideo.com/videoplayback?expire=1655655492&ei=5PeuYoCIKMKYx_AP_YG9wAs&ip=2a02%3A2f09%3A350e%3Ac00%3Ad173%3A4f44%3Ab26c%3Ad21&id=o-ALg66EN6nZaILuoWP3hl82zunZLkms50fxdnenKgjHMz&itag=251&source=youtube&requiressl=yes&mh=Zs&mm=31%2C29&mn=sn-gqn-ungs%2Csn-c0q7lnsl&ms=au%2Crdu&mv=m&mvi=8&pcm2cms=yes&pl=45&gcr=ro&initcwndbps=1416250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=5964100&dur=369.321&lmt=1621742638209536&mt=1655633565&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=1311222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOQR-b5ETIxFM9A8ztmg5HZMfAiJrxl3ODjkABgEa9daAiEA1wHgBQ5T8ah5Tqrjg3PUh08ZqhPVRHN2_9LNjaAHM2A%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgRjIbKhOl3sghffa0LYtXbL6b3F4PUOCR4FUPY8T0ilACIQDro-loVQVU1vzuuJVaDCH7D3ek0OFjA_FgGJlIEVJkdQ%3D%3D"
[download] Destination: All Night High [rGyse2vUPoM].webm
[download] 100% of 5.69MiB in 00:01
[debug] ffmpeg command line: ffmpeg -i "file:All Night High [rGyse2vUPoM].webm"
[ExtractAudio] Destination: All Night High [rGyse2vUPoM].opus
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:All Night High [rGyse2vUPoM].webm" -vn -acodec copy -movflags "+faststart" "file:All Night High [rGyse2vUPoM].opus"
Deleting original file All Night High [rGyse2vUPoM].webm (pass -k to keep)
[Metadata] Adding metadata to "All Night High [rGyse2vUPoM].opus"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:All Night High [rGyse2vUPoM].opus" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=All Night High" -metadata "date=20150726" -metadata "description=Provided to YouTube by Ingrooves

All Night High · Lisa Shaw

All Night High

℗ ℗ 2008 SALTED MUSIC

Released on: 2008-03-25

Composer, Writer, Remixer: Dave Warrin

Auto-generated by YouTube." -metadata "synopsis=Provided to YouTube by Ingrooves

All Night High · Lisa Shaw

All Night High

℗ ℗ 2008 SALTED MUSIC

Released on: 2008-03-25

Composer, Writer, Remixer: Dave Warrin

Auto-generated by YouTube." -metadata "purl=https://www.youtube.com/watch?v=rGyse2vUPoM" -metadata "comment=https://www.youtube.com/watch?v=rGyse2vUPoM" -metadata "artist=Lisa Shaw" -metadata "album=All Night High" -movflags "+faststart" "file:All Night High [rGyse2vUPoM].temp.opus"
[download] Finished downloading playlist: Album - All Night High
```

**Comment by pukkandan** [comment] 2022-06-19 13:23
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/622

**Closed by pukkandan** 2022-06-19 13:23 UTC
Labels: site-bug, triage
