### ISSUE TITLE
Request: Could --download-archive filenames use output template fields?

### ISSUE THREAD

**Issue by SiXOTshRuTEr** [yt-dlp/yt-dlp#6915] opened 2023-04-25 23:29 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Suggestion:  It would be really nice if the --download-archive option could make use of output template fields in the archive filename.

Example:  --download-archive "archive-%(webpage_url_domain.:-4)s-%(uploader)s.txt"
Output:  "archive-youtube-ChannelName.txt

Use case:  For organizational purposes, I like to keep a separate archive file for each site.  My .cmd scripts are primarily for one site, but when I archive from another, I have to remember to either manually change the archive filename in the script, and then change it back, or make a separate copy.  However, if the output template fields were supported, the same argument could automatically name/use a site-specific archive file, without having to remember to manually change it.  I could even generate a separate archive file per uploader/channel, which would satisfy my organizational desires even further.

Hopefully this is a reasonable request, and thanks for the awesome yt-dlp utility!

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment] 2023-04-25 23:39
Duplicate of #953

**Closed by bashonly** 2023-04-25 23:39 UTC
Labels: enhancement, triage
