### ISSUE TITLE
Unable to Download Thumbnail for Upcoming Live Events with --skip-download --write-thumbnail

### ISSUE THREAD

**Issue by sermelipharo** [yt-dlp/yt-dlp#11431] opened 2024-11-02 10:01 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Any

### Provide a description that is worded well enough to be understood

When using `yt-dlp --skip-download --write-thumbnail` for an upcoming live event, yt-dlp returns the error: `“This live event will begin in XXX.”` The expected behavior is that yt-dlp should skip trying to download the video and only download the available thumbnail.

Adding flags such as `--ignore-errors`, `--no-wait-for-video`, `--no-check-formats`, and --`no-abort-on-error` does not affect this behavior. This issue may be related to #9934.

Original video ID is probably will be irrelevant in log, because live will already start, but it's valid for any [upcoming live video](https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig/livetab?ss=CKMK).
The issue is valid both for `https://www.youtube.com/watch?v=` and `https://www.youtube.com/live/` links

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-o', '%(id)s--%(title)s.%(ext)s', '--skip-download', '--write-thumbnail', 'https://www.youtube.com/watch?v=MCiRiF-EH1E', '-i', '--no-abort-on-error', '--no-wait-for-video', '--no-check-formats', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (pip)
[debug] Python 3.13.0 (CPython arm64 64bit) - macOS-15.1-arm64-arm-64bit-Mach-O (OpenSSL 3.4.0 22 Oct 2024)
[debug] exe versions: ffmpeg 7.1 (setts), ffprobe 7.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.47.0, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=MCiRiF-EH1E
[youtube] MCiRiF-EH1E: Downloading webpage
[youtube] MCiRiF-EH1E: Downloading ios player API JSON
[youtube] MCiRiF-EH1E: Downloading mweb player API JSON
ERROR: [youtube] MCiRiF-EH1E: This live event will begin in 2 hours.
  File "/opt/homebrew/Cellar/yt-dlp/2024.10.22/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2024.10.22/libexec/lib/python3.13/site-packages/yt_dlp/extractor/youtube.py", line 4671, in _real_extract
    self.raise_no_formats(reason, expected=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.10.22/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 1275, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by bashonly** [comment] 2024-11-04 04:56
Are you sure it doesn't work with `--ignore-no-formats`? You didn't use that option in your log.

**Comment by bashonly** [comment] 2024-11-04 05:00
closing as duplicate of #10582

**Closed by bashonly** 2024-11-04 05:00 UTC
Labels: question
