### ISSUE TITLE
Unable to download ESPN+, told to report

### ISSUE THREAD

**Issue by hootie318** [yt-dlp/yt-dlp#8575] opened 2023-11-14 02:42 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Stated

### Provide a description that is worded well enough to be understood

I am trying to download a stream and I keep getting an error

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe --ap-mso DTV --ap-username <username> --ap-password <password> "https://www.espn.com/watch/player/_/id/33a21881-e2c2-4624-b160-a7a096c34715" --verbose
[debug] Command-line config: ['--ap-mso', 'DTV', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.espn.com/watch/player/_/id/33a21881-e2c2-4624-b160-a7a096c34715', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[WatchESPN] Extracting URL: https://www.espn.com/watch/player/_/id/33a21881-e2c2-4624-b160-a7a096c34715
[WatchESPN] 33a21881-e2c2-4624-b160-a7a096c34715: Downloading JSON metadata
[WatchESPN] 33a21881-e2c2-4624-b160-a7a096c34715: Downloading Provider Redirect Page
[WatchESPN] 33a21881-e2c2-4624-b160-a7a096c34715: Downloading Provider Login Page
ERROR: [WatchESPN] 33a21881-e2c2-4624-b160-a7a096c34715: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\espn.py", line 404, in _real_extract
  File "yt_dlp\extractor\adobepass.py", line 1715, in _extract_mvpd_auth
  File "yt_dlp\extractor\adobepass.py", line 1395, in post_form
  File "yt_dlp\extractor\common.py", line 1299, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1263, in _search_regex
```

**Comment by bashonly** [comment] 2023-11-14 04:00
Looks like a problem with adobepass / the MSO sign-in rather than the ESPN+ extractor itself. Closing as duplicate of #2188

**Closed by bashonly** 2023-11-14 04:00 UTC
Labels: site-bug, triage
