### ISSUE TITLE
Crpj4_loF6L: Requested content is not available, rate-limit reached or login required.

### ISSUE THREAD

**Issue by mbilalsiddique1** [yt-dlp/yt-dlp#7221] opened 2023-06-03 18:47 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The error message indicates that yt-dlp encountered difficulties extracting metadata and content from the Instagram post. It first attempted to extract general metadata but failed, resulting in missing metadata. Subsequently, it tried to download the webpage but encountered another issue where the main webpage was locked behind a login page. As a fallback, it attempted to download the embed webpage, but additional data extraction also failed.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
root@:~# yt-dlp -vU -o nasha.mp4 'https://www.instagram.com/reel/Crpj4_loF6L/?igshid=MzRlODBiNWFlZA=='
[debug] Command-line config: ['-vU', '-o', 'nasha.mp4', 'https://www.instagram.com/reel/Crpj4_loF6L/?igshid=MzRlODBiNWFlZA==']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.10.7 (CPython x86_64 64bit) - Linux-5.19.0-31-generic-x86_64-with-glibc2.36 (OpenSSL 3.0.5 5 Jul 2022, glibc 2.36)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[Instagram] Extracting URL: https://www.instagram.com/reel/Crpj4_loF6L/?igshid=MzRlODBiNWFlZA==
[Instagram] Crpj4_loF6L: Setting up session
[Instagram] Crpj4_loF6L: Downloading JSON metadata
WARNING: [Instagram] Crpj4_loF6L: General metadata extraction failed (some metadata might be missing).
[Instagram] Crpj4_loF6L: Downloading webpage
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
[Instagram] Crpj4_loF6L: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] Crpj4_loF6L: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, or --netrc (instagram) to provide account credentials
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/instagram.py", line 456, in _real_extract
    self.raise_login_required('Requested content is not available, rate-limit reached or login required')
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 1154, in raise_login_required
    raise ExtractorError(msg, expected=True)

root@:~#
```

**Comment by bashonly** [comment] 2023-06-03 18:49
Duplicate of #7165

**Closed by bashonly** 2023-06-03 18:49 UTC
Labels: duplicate, site-bug
