### ISSUE TITLE
player.vimeo.com fails on info section extraction

### ISSUE THREAD

**Issue by v3l0c1r4pt0r** [yt-dlp/yt-dlp#5713] opened 2022-12-05 17:07 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Provide a description that is worded well enough to be understood

Trying to download any video from `player.vimeo.com` fails, when it tries to extract "info section". Looks like vimeo has changed something in their website. Can be reproduced on test video from yt-dlp sources: https://player.vimeo.com/video/54469442.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'http://player.vimeo.com/video/54469442']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.8 (CPython 64bit) - Linux-6.0.9-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-None, certifi-2021.10.08, mutagen-1.45.1, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.07.18
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.11.11/_update_spec
ERROR: It looks like you installed yt-dlp with a package manager, pip or setup.py; Use that to update
[debug] [vimeo] Extracting URL: http://player.vimeo.com/video/54469442
[vimeo] 54469442: Downloading webpage
ERROR: [vimeo] 54469442: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/admin/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/home/admin/.local/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py", line 880, in _real_extract
    config = self._parse_json(self._search_regex(
  File "/home/admin/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1194, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment] 2022-12-05 17:15
> Latest version: 2022.11.11, Current version: 2022.07.18
> ERROR: It looks like you installed yt-dlp with a package manager, pip or setup.py; Use that to update

Update

Duplicate of #5361, fixed in db4678e448d6e7da9743f4028c94b540fcafc528

**Closed by bashonly** 2022-12-05 17:15 UTC
Labels: duplicate, site-bug, site:vimeo

**Comment by scrutinizer11** [comment] 2023-02-05 05:42
I've experienced this issue piping hot. The yt-dlp is **2023.01.06** on macOS 10.9. The error is 

`ERROR: [vimeo] 271390639: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. `

The URL is [https://player.vimeo.com/video/271390639](url)

**Comment by pboesch** [comment] 2023-02-09 10:02
Same here. Could you please re-open this issue?

**Comment by mrzenwiz** [comment] 2023-02-10 01:43
I echo pboesch's comment - this is still happening, on two different URLs today.

The first URL:

$ yt-dlp -vU 'https://player.vimeo.com/video/783324308?h=423c8b699e'
[debug] Command-line config: ['-vU', 'https://player.vimeo.com/video/783324308?h=423c8b699e']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-60-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[vimeo] Extracting URL: https://player.vimeo.com/video/783324308?h=423c8b699e
[vimeo] 783324308: Downloading webpage
ERROR: [vimeo] 783324308: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/admar/bin/yt-dlp/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/home/admar/bin/yt-dlp/yt_dlp/extractor/vimeo.py", line 837, in _real_extract
    config = self._parse_json(self._search_regex(
  File "/home/admar/bin/yt-dlp/yt_dlp/extractor/common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

The second URL:

$ yt-dlp -vU 'https://app.kartra.com/external_video/vimeo/797163741?h=0732af73ce'
[debug] Command-line config: ['-vU', 'https://app.kartra.com/external_video/vimeo/797163741?h=0732af73ce']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-60-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: https://app.kartra.com/external_video/vimeo/797163741?h=0732af73ce
[generic] 797163741?h=0732af73ce: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 797163741?h=0732af73ce: Extracting information
[debug] Looking for embeds
[debug] Identified a vimeo embed
[vimeo] Extracting URL: https://player.vimeo.com/video/797163741?h=0732af73ce#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fapp.kartra.com%2Fexternal_video%2Fvimeo%2F797163741%3Fh%3D0732af73ce%22%7D%7D
[vimeo] 797163741: Downloading webpage
ERROR: [vimeo] 797163741: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/admar/bin/yt-dlp/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/home/admar/bin/yt-dlp/yt_dlp/extractor/vimeo.py", line 837, in _real_extract
    config = self._parse_json(self._search_regex(
  File "/home/admar/bin/yt-dlp/yt_dlp/extractor/common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

Please re-open and fix - the traceback is all there...

Thank you!

**Comment by pukkandan** [comment] 2023-02-10 13:18
https://github.com/yt-dlp/yt-dlp/issues/6149
