### ISSUE TITLE
downloading .mp3 files from youtube fails - only mhtml format is available

### ISSUE THREAD

**Issue by ilanit1997** [yt-dlp/yt-dlp#9286] opened 2024-02-24 18:17 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I've been successfully using yt-dlp to download .mp3 from YouTube for a while now. Recently, though, I've encountered a problem where I'm unable to download what seem to be straightforward videos from YouTube. These are popular videos that load fine in a browser, yet yt-dlp seems incapable of handling them for some reason. It seems no real mp3 is available to download (--list-format returns .mhtml format). I also tried downloading various other videos from YouTube and nothing works. 

This issue arose while running yt-dlp on my on-premises virtual machine, which had been operating using yt-dlp commands without any issues up until today. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-x', '--audio-format', 'mp3', '-o', '/data/home/ilanit.sobol/code_files/test_output/%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=9OvibwfflDg']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.02.23.232656 from yt-dlp/yt-dlp-nightly-builds [998dffb5a] (pip)
[debug] Python 3.9.18 (CPython x86_64 64bit) - Linux-3.10.0-1160.99.1.el7.x86_64-x86_64-with-glibc2.17 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.17)
[debug] exe versions: ffmpeg 3.4.13, ffprobe 3.4.13
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.41.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1833 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.02.23.232656 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.02.23.232656 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=9OvibwfflDg
[youtube] 9OvibwfflDg: Downloading webpage
[youtube] 9OvibwfflDg: Downloading ios player API JSON
WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "9OvibwfflDg"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 9OvibwfflDg: Downloading android player API JSON
WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "9OvibwfflDg"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "9OvibwfflDg"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Invalid start time (138.0 > 93) for chapter "Family Room"
WARNING: [youtube] Invalid start time (286.0 > 93) for chapter "Outdoor Area"
WARNING: [youtube] Invalid start time (412.0 > 93) for chapter "Bedroom"
WARNING: [youtube] Invalid start time (518.0 > 93) for chapter "Sitting Area"
WARNING: [youtube] Invalid start time (539.0 > 93) for chapter "Bathroom"
WARNING: [youtube] Invalid start time (570.0 > 93) for chapter "Closet"
WARNING: Only images are available for download. use --list-formats to see them
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] 9OvibwfflDg: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/data/home/ilanit.sobol/anaconda3/envs/llms_env/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1593, in wrapper
    return func(self, *args, **kwargs)
  File "/data/home/ilanit.sobol/anaconda3/envs/llms_env/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1749, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/data/home/ilanit.sobol/anaconda3/envs/llms_env/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1808, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/data/home/ilanit.sobol/anaconda3/envs/llms_env/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2928, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] 9OvibwfflDg: Requested format is not available. Use --list-formats for a list of available formats

------------------------------------------
When look into --list-formats output:

yt-dlp --list-formats https://www.youtube.com/watch?v=9OvibwfflDg
[youtube] Extracting URL: https://www.youtube.com/watch?v=9OvibwfflDg
[youtube] 9OvibwfflDg: Downloading webpage
[youtube] 9OvibwfflDg: Downloading ios player API JSON
WARNING: [youtube] Skipping player response from ios client (got player response for video "M5t4UHllkUM" instead of "9OvibwfflDg"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 9OvibwfflDg: Downloading android player API JSON
WARNING: [youtube] Skipping player response from android client (got player response for video "M5t4UHllkUM" instead of "9OvibwfflDg"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Skipping player response from web client (got player response for video "M5t4UHllkUM" instead of "9OvibwfflDg"); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Invalid start time (138.0 > 93) for chapter "Family Room"
WARNING: [youtube] Invalid start time (286.0 > 93) for chapter "Outdoor Area"
WARNING: [youtube] Invalid start time (412.0 > 93) for chapter "Bedroom"
WARNING: [youtube] Invalid start time (518.0 > 93) for chapter "Sitting Area"
WARNING: [youtube] Invalid start time (539.0 > 93) for chapter "Bathroom"
WARNING: [youtube] Invalid start time (570.0 > 93) for chapter "Closet"
WARNING: Only images are available for download. use --list-formats to see them
[info] Available formats for 9OvibwfflDg:
ID  EXT   RESOLUTION FPS │ PROTO │ VCODEC MORE INFO
────────────────────────────────────────────────────
sb2 mhtml 48x27        1 │ mhtml │ images storyboard
sb1 mhtml 72x45        1 │ mhtml │ images storyboard
sb0 mhtml 144x90       1 │ mhtml │ images storyboard
```

**Comment by bashonly** [comment] 2024-02-24 19:03
Duplicate of #7143

Youtube has blocked your IP address

**Closed by bashonly** 2024-02-24 19:03 UTC
Labels: site-bug, triage
