### ISSUE TITLE
Why are the YouTube entries for the Shorts empty?

### ISSUE THREAD

**Issue by rmaleki** [yt-dlp/yt-dlp#11072] opened 2024-09-24 11:01 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [x] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to retrieve Shorts from YouTube channels. However, when I attempt to call and print the entries, the entries list is empty. I can retrieve playlists with this configuration; in that case, the entries list is not empty.

I used:
python==3.12
yt-dlp==2024.8.6

```
        ydl_opts = {
            "proxy": 'my-proxy',
            "quiet": True,
            "extract_flat": True,
            "force_generic_extractor": True,
            "username": "oauth2",
            "password": "",
        }
        with YoutubeDL(ydl_opts) as ydl:
            result = ydl.extract_info('https://www.youtube.com/@Mikikalafe444/shorts', download=False)
            print(result["entries"])

```

[]

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment] 2024-09-24 11:07
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/10936
Update to nightly

**Closed by seproDev** 2024-09-24 11:07 UTC
Labels: question
