### ISSUE TITLE
401590806345712: No video formats found

### ISSUE THREAD

**Issue by davkbod** [yt-dlp/yt-dlp#11367] opened 2024-10-27 02:23 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

error "facebook 401590806345712: No video formats found!"

Video site : yt-dlp https://fb.watch/vtkorrRM0p

[generic] Extracting URL: https://fb.watch/vtkorrRM0p
[generic] vtkorrRM0p: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/RBReich/videos/401590806345712/?share_url=https%3A%2F%2Ffb.watch%2FvtkorrRM0p
[facebook] Extracting URL: https://www.facebook.com/RBReich/videos/401590806345712/?share_url=https%3A%2F%2Ffb.watch%2FvtkorrRM0p
[facebook] 401590806345712: Downloading webpage
ERROR: [facebook] 401590806345712: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U"

yt-dlp https://www.facebook.com/RBReich/videos/401590806345712/
[facebook] Extracting URL: https://www.facebook.com/RBReich/videos/401590806345712/
[facebook] 401590806345712: Downloading webpage
ERROR: [facebook] 401590806345712: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U"

No apparent problems with other videos, just his particular one..

davkbod@yahoo.com

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://fb.watch/vtkorrRM0p
[debug] Command-line config: ['-vU', 'https://fb.watch/vtkorrRM0p']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (zip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-47-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-2.0.7, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://fb.watch/vtkorrRM0p
[generic] vtkorrRM0p: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/RBReich/videos/401590806345712/?share_url=https%3A%2F%2Ffb.watch%2FvtkorrRM0p
[facebook] Extracting URL: https://www.facebook.com/RBReich/videos/401590806345712/?share_url=https%3A%2F%2Ffb.watch%2FvtkorrRM0p
[facebook] 401590806345712: Downloading webpage
ERROR: [facebook] 401590806345712: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1781, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1840, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2846, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1122, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [facebook] 401590806345712: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
yt-dlp -U
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
```

**Comment by bashonly** [comment] 2024-10-27 02:30
Duplicate of #11337

**Closed by bashonly** 2024-10-27 02:30 UTC
Labels: duplicate, site-bug, site:facebook

**Comment by davkbod** [comment] 2024-10-30 01:29
Did the --update-to-nightly, but issue seems to still be happening...

sudo yt-dlp --update-to nightly
[sudo] password for davkbod: 
Current version: stable@2024.10.22 from yt-dlp/yt-dlp
Latest version: nightly@2024.10.29.232854 from yt-dlp/yt-dlp-nightly-builds
Current Build Hash: a87033b5686c5512adcd26023c6ac4a56957d736f4653033e36901dbcc8bf7bb
Updating to nightly@2024.10.29.232854 from yt-dlp/yt-dlp-nightly-builds ...
Updated yt-dlp to nightly@2024.10.29.232854 from yt-dlp/yt-dlp-nightly-builds
davkbod@davkbod-hp-compaq:~/Downloads$ yt-dlp https://fb.watch/vxemEFv5az/
[generic] Extracting URL: https://fb.watch/vxemEFv5az/
[generic] vxemEFv5az: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/watch/?v=1794785514598234&ref=sharing&share_url=https%3A%2F%2Ffb.watch%2FvxemEFv5az%2F
[facebook] Extracting URL: https://www.facebook.com/watch/?v=1794785514598234&ref=sharing&share_url=https%3A%2F%2Ffb.watch%2FvxemEFv5az%2F
[facebook] 1794785514598234: Downloading webpage
ERROR: [facebook] 1794785514598234: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by bashonly** [comment] 2024-10-30 02:57
show a verbose log, add `-v` to your command
