### ISSUE TITLE
yt-dlp rips slowly, but youtube-dl is fine

### ISSUE THREAD

**Issue by whiteazn** [yt-dlp/yt-dlp#1141] opened 2021-10-02 02:22 UTC
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
yt-dlp -v --abort-on-unavailable-fragment --output "test.mp4" --hls-prefer-native --no-check-certificate --add-header "authorization:AUTHKEY" "https://hlsvod-akc-clt1.media.plus.espn.com/ps01/espn/hls/21038bd8-031a-4249-b5f3-b6eeff6d893f/master-ts-wired60-silk-86a302ed-b866-4754-9afc-75683050f457-056d417f-4215-4e2c-ab5e-598d69ea032c.m3u8"
[debug] Command-line config: ['-v', '--abort-on-unavailable-fragment', '--output', 'test.mp4', '--hls-prefer-native', '--no-check-certificate', '--add-header', 'authorization:AUTHKEY', 'https://hlsvod-akc-clt1.media.plus.espn.com/ps01/espn/hls/21038bd8-031a-4249-b5f3-b6eeff6d893f/master-ts-wired60-silk-86a302ed-b866-4754-9afc-75683050f457-056d417f-4215-4e2c-ab5e-598d69ea032c.m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.09.25 (zip)
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-144-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://hlsvod-akc-clt1.media.plus.espn.com/ps01/espn/hls/21038bd8-031a-4249-b5f3-b6eeff6d893f/master-ts-wired60-silk-86a302ed-b866-4754-9afc-75683050f457-056d417f-4215-4e2c-ab5e-598d69ea032c.m3u8
[generic] master-ts-wired60-silk-86a302ed-b866-4754-9afc-75683050f457-056d417f-4215-4e2c-ab5e-598d69ea032c: Requesting header
[generic] master-ts-wired60-silk-86a302ed-b866-4754-9afc-75683050f457-056d417f-4215-4e2c-ab5e-598d69ea032c: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] master-ts-wired60-silk-86a302ed-b866-4754-9afc-75683050f457-056d417f-4215-4e2c-ab5e-598d69ea032c: Downloading 1 format(s): 7181
[debug] Invoking downloader on "https://hlsvod-akc-clt1.media.plus.espn.com/ps01/espn/hls/21038bd8-031a-4249-b5f3-b6eeff6d893f/r/c9919dad-94b3-47be-858d-cccef0c015b4/4df2-MAIN/09/7000K/7000_complete.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 454
[download] Destination: test.mp4
[download]   0.2% of ~1.86GiB at 99.83MiB/s ETA 00:44

```

## Description

I been downloading some videos from ESPN for quite sometime.  I was using youtube-dl, but recently (a couple months ago) switched to yt-dlp (for unrelated reasons, had support for a site that youtube-dl didn't have at the time).  

My normal process is to spin up a new VM, install everything (install youtube-dl and all it's dependencies, then yt-dlp, and then rip)

But it seems this time around, yt-dlp just, "hangs"  you will see it start downloading to the destination (0.2% of ~1.86GB [...]) and just sit there.  It seems to be downloading very slowly.  as the ETA will go from 44 seconds, to 12 hours or something long like that (even though the speed stays at 90+ MiB/s the whole time).    It doesn't update the current status all that much either.  so it'll just show "0.2% of ~1.86GiB at 99.83MiB/s ETA 00:44" for a few minutes, then update to: "0.5% of ~1.86GiB at 99.83MiB/s ETA 11:23:44".  So it would just take forever to rip something.  

If I switch the command to just use youtube-dl over yt-dlp, it rips just fine.  The last time I ripped was 2021-09-24, so before this new version.  So not sure if something changed in the recent release or not?

**Comment by Ashish0804** [comment] 2021-10-02 05:31
Try using `-N 12` or `--downloader aria2c`

**Comment by MinePlayersPE** [comment] 2021-10-02 05:34
Might be related to https://github.com/yt-dlp/yt-dlp/issues/1087?

**Comment by pukkandan** [comment] 2021-10-02 11:53
Duplicate of #1087. Use `--downloader ffmpeg` or install pycryptodome. Will be fully fixed in next release

**Closed by pukkandan** 2021-10-02 11:53 UTC
