### ISSUE TITLE
bilibili video gives me 403 error and no sound

### ISSUE THREAD

**Issue by ualaa1** [yt-dlp/yt-dlp#2872] opened 2022-02-24 07:34 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Downloaded file seems somewhat broken. Opens fine in handbrake but not in quicktime player.
Video is https://www.bilibili.com/video/BV11x411y7yL?p=4

Edit: After rendering with handbrake, the resulting video has no sound.

### Verbose log

```shell
yt-dlp "https://www.bilibili.com/video/BV11x411y7yL?p=4" -v
[debug] Command-line config: ['https://www.bilibili.com/video/BV11x411y7yL?p=4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.9.0 (CPython 64bit) - macOS-12.2.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV11x411y7yL?p=4
[BiliBili] 11x411y7yL: Grabbing original ID via API
[BiliBili] 8789150: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliBili] 8789150: Extracting videos in anthology
[BiliBili] 8789150: Downloading tags
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 8789150_part4: Downloading 1 format(s): 8+2
[debug] Invoking downloader on "https://upos-sz-mirrorcosov.bilivideo.com/upgcxcode/46/52/14495246/14495246_fh1-1-30066.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1645695112&gen=playurlv2&os=cosovbv&oi=797993132&trid=9be6962c49044317a71b6a7663f53abcu&platform=pc&upsig=d9c95286569ad4a189cec6df265f9208&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&nettype=0&orderid=0,1&agrr=1&bw=96357&logo=80000000"
[download] 002 [8789150_part4].f8.mp4 has already been downloaded
[download] 100% of 135.63MiB
[debug] Invoking downloader on "https://upos-sz-mirrorcosov.bilivideo.com/upgcxcode/46/52/14495246/14495246_da3-1-30232.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1645695112&gen=playurlv2&os=cosovbv&oi=797993132&trid=9be6962c49044317a71b6a7663f53abcu&platform=pc&upsig=41b1580f988a2f95b77270daa0f7c7b9&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&mid=0&bvc=vod&nettype=0&orderid=0,1&agrr=1&bw=16459&logo=80000000"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3068, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2801, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 371, in real_download
    establish_connection()
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 119, in establish_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/downloader/http.py", line 113, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3558, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by dirkf** [comment] 2022-02-24 09:54
Seems OK for me (UK), also with yt-dl (but combined 480p .flv there).

Audio stream downloaded from [here](https://upos-hz-mirrorakam.akamaized.net/upgcxcode/46/52/14495246/14495246_da3-1-30232.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1645702954&gen=playurlv2&os=akam&oi=856047848&trid=09728adab6f7406882b82594d80e1762u&platform=pc&upsig=24edeb2dbf429059973b0c056aa6fa4f&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,platform&hdnts=exp=1645702954~hmac=cb4628ee6e9ec8c5699fbe6d30d87bf0116660ca41028fdb8ed1376a7b4e5aca&mid=0&bvc=vod&nettype=0&orderid=0,1&agrr=1&bw=16459&logo=80000000).

You may be getting a (temporary?) block from the CDN, which is different from the one I got as linked above.

**Comment by DogTorrent** [comment] 2022-02-24 15:45
I can't download audio and got same error(403), no matter directly downloading or using '-f 2' to specify the audio. But video is ok.
I retried it using VPN, from HK I also got 403 error but from the US I succeeded, so maybe it only happened in china?

**Comment by pukkandan** [comment] 2022-03-01 05:25
Can't reproduce. Confirm whether you can access the video (with audio) in browser from the same IP. If you can, try adding `--check-formats`

**Comment by ualaa1** [comment] 2022-03-01 08:01
I have access in browser with sound. I am not using any proxies and am accessing from the US.

**Comment by ualaa1** [comment] 2022-03-01 08:03
you-get --check-formats "https://www.bilibili.com/video/BV11x411y7yL?p=4"
usage: you-get [OPTION]... URL...
you-get: error: unrecognized arguments: --check-formats

When I try to do --check formates

**Comment by deluxghost** [comment] 2022-03-01 14:05
@ualaa1 you are using `you-get`...

seems like related to #2834 which is not released yet

**Comment by pukkandan** [comment] 2022-03-01 14:50
Thanks @deluxghost I forgot to test with the release branch. I can reproduce the issue, and can confirm it is fixed in master

**Closed by pukkandan** 2022-03-01 14:50 UTC
Labels: cant reproduce, incomplete, site-bug
