### ISSUE TITLE
ERROR: [Ixigua] 737962095470631373: 737962095470631373: Failed to parse JSON (caused by JSONDecodeError)

### ISSUE THREAD

**Issue by seaklin83546** [yt-dlp/yt-dlp#11733] opened 2024-12-04 17:51 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi Admin. How to fix this error?

yt-dlp -vU --cookies cookies.txt https://www.ixigua.com/7379620954706313738
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://www.ixigua.com/7379620954706313738']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.26.232826 from yt-dlp/yt-dlp-nightly-builds [5c880ef42] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 2024-10-27-git-bb57b78013-full_build-www.gyan.dev (setts), ffprobe 2024-10-27-git-bb57b78013-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.12.03.232932/SHA2-256SUMS
Current version: nightly@2024.10.26.232826 from yt-dlp/yt-dlp-nightly-builds
Latest version: nightly@2024.12.03.232932 from yt-dlp/yt-dlp-nightly-builds
Current Build Hash: 9ddc742b80841fb9ce3c082ffc4027972f58c544c7d19f44a8146a797cf6e1e2
Updating to nightly@2024.12.03.232932 from yt-dlp/yt-dlp-nightly-builds ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.12.03.232932/yt-dlp.exe
Updated yt-dlp to nightly@2024.12.03.232932 from yt-dlp/yt-dlp-nightly-builds
[debug] Restarting: C:\bin\yt-dlp.exe -vU --cookies cookies.txt https://www.ixigua.com/7379620954706313738
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://www.ixigua.com/7379620954706313738']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.12.03.232932 from yt-dlp/yt-dlp-nightly-builds [cfa76f35d] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 2024-10-27-git-bb57b78013-full_build-www.gyan.dev (setts), ffprobe 2024-10-27-git-bb57b78013-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.12.03.232932 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.12.03.232932 from yt-dlp/yt-dlp-nightly-builds)
[Ixigua] Extracting URL: https://www.ixigua.com/7379620954706313738
[Ixigua] 737962095470631373: Downloading webpage
ERROR: [Ixigua] 737962095470631373: 737962095470631373: Failed to parse JSON (caused by JSONDecodeError('Extra data in \'atedData" = "functio\': line 2 column 37 (char 37)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\ixigua.py", line 67, in _real_extract
  File "yt_dlp\extractor\ixigua.py", line 42, in _get_json_data
  File "yt_dlp\extractor\common.py", line 1094, in _parse_json
  File "yt_dlp\extractor\common.py", line 1077, in __print_error

  File "yt_dlp\utils\_utils.py", line 565, in decode
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 2 column 37 (char 37)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1091, in _parse_json
  File "json\__init__.py", line 359, in loads
  File "yt_dlp\utils\_utils.py", line 573, in decode
json.decoder.JSONDecodeError: Extra data in 'atedData" = "functio': line 2 column 37 (char 37)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment] 2024-12-04 22:25
Duplicate of #11134

**Closed by bashonly** 2024-12-04 22:25 UTC
Labels: question
