### ISSUE TITLE
NBC Error 404 Not Found

### ISSUE THREAD

**Issue by jriker1** [yt-dlp/yt-dlp#4038] opened 2022-06-09 22:43 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

Last week was able to download America's Got Talent in the US with Xfinity.  Today not so.  Tried updating my cookies as don't think Adobe Pass stopped working a ways back but no joy.

### Verbose log

```shell
[debug] Command-line config: ['--audio-quality', '0', '--add-metadata', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.nbc.com/americas-got-talent/video/auditions-2/9000246182', '-o', "America's Got Talent S17E2.mp4", '--cookies', 'c:\\temp\\nbc.com_cookies.txt', '--ffmpeg-location', 'z:\\ffmpeg\\bin', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.9.0 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: "z:\ffmpeg\bin\ffprobe" -bsfs
[debug] Checking exe version: "z:\ffmpeg\bin\ffmpeg" -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [NBC] Extracting URL: https://www.nbc.com/americas-got-talent/video/auditions-2/9000246182
[NBC] 9000246182: Downloading JSON metadata
[NBC] 9000246182: Downloading JSON metadata
[debug] Loading ap-mvpd.nbcentertainment from cache
[NBC] 9000246182: Retrieving Media Token
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/NnzsPC/media/guid/2410887629/9000246182?mbr=true&manifest=m3u&auth=%3CsignatureInfo%3EEjKVQoqSLIY4x2u80Gffm1Sm9Ki1XAayoAFWCqK8ChZGaNED959s3UBDGWqDJx3HLWDjQVWWOyu1W3OIQPJm4Ca8VsfaFbGHzFnyr3A9fQEc8dk3Va3xtgJWDDz8dP1iqLVl3HTGKQf6rBhzdCD%2BBCh%2B3ZT6YeJM2%2F5o74qr8b0%3D%3CsignatureInfo%3E%3CauthToken%3E%3CsessionGUID%3E4fc043b16ed1aff6ef1d0fad32591510%3C%2FsessionGUID%3E%3CrequestorID%3Enbcentertainment%3C%2FrequestorID%3E%3CresourceID%3E%3C%21%5BCDATA%5B%3Crss+version%3D%222.0%22+xmlns%3Amedia%3D%22http%3A%2F%2Fsearch.yahoo.com%2Fmrss%2F%22%3E%3Cchannel%3E%3Ctitle%3Enbcentertainment%3C%2Ftitle%3E%3Citem%3E%3Ctitle%3EAuditions+2%3C%2Ftitle%3E%3Cguid%3E9000246182%3C%2Fguid%3E%3Cmedia%3Arating+scheme%3D%22urn%3Av-chip%22%3ETV-14%3C%2Fmedia%3Arating%3E%3C%2Fitem%3E%3C%2Fchannel%3E%3C%2Frss%3E%5D%5D%3E%3C%2FresourceID%3E%3Cttl%3E420000%3C%2Fttl%3E%3CissueTime%3E2022-06-09+15%3A42%3A17+-0700%3C%2FissueTime%3E%3CmvpdId%3EComcast_SSO%3C%2FmvpdId%3E%3C%2FauthToken%3E#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 9000246182: Downloading SMIL data
[ThePlatform] 9000246182: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] 9000246182: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 9000246182: Downloading 1 format(s): hls-7916
[debug] Invoking hlsnative downloader on "https://nbcmpx-vh.akamaihd.net/i/prod/video/j6b/abE/9000246182/1654634324092-BgxQ0/HD_TVE_AMERICASGO_06072022_,185,783,483,300,86,35,0k.mp4.csmil/index_1_av.m3u8?null=0&id=AgBi5NtzFyNEFEt3omJmfE9Yz1RcoG5SnMc1ogNIv4NhUCAAW%2fD2R6JJnLzJ+S0enIIJR%2fNXnDjtJQ%3d%3d&hdntl=exp=1654900939~acl=%2fi%2fprod%2fvideo%2fj6b%2fabE%2f9000246182%2f1654634324092-BgxQ0%2fHD_TVE_AMERICASGO_06072022_*~data=hdntl~hmac=b807a89e15524f0482df10eeab330246be5470bc7ffbb39d318fb47a11f0bb8c"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 513
[download] Destination: America's Got Talent S17E2.mp4
[debug] File locking is not supported on this platform. Proceeding without locking
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10) ...
ERROR: Giving up after 10 fragment retries
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\Scripts\yt-dlp.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\__init__.py", line 857, in main
    _real_main(argv)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\__init__.py", line 847, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 3254, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 3230, in wrapper
    res = func(*args, **kwargs)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1386, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1479, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1583, in process_ie_result
    return self.process_ie_result(
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1535, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2640, in process_video_result
    self.process_info(new_info)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 3130, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2838, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\downloader\common.py", line 445, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\downloader\hls.py", line 348, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\downloader\fragment.py", line 520, in download_and_append_fragments
    download_fragment(fragment, ctx)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\downloader\fragment.py", line 484, in download_fragment
    self.report_error('Giving up after %s fragment retries' % fragment_retries)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 936, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 868, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1479, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1583, in process_ie_result
    return self.process_ie_result(
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1535, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2640, in process_video_result
    self.process_info(new_info)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 3130, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2838, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\downloader\common.py", line 445, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\downloader\hls.py", line 348, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\downloader\fragment.py", line 522, in download_and_append_fragments
    decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\downloader\fragment.py", line 365, in decrypt_fragment
    return unpad_pkcs7(aes_cbc_decrypt_bytes(frag_content, decrypt_info['KEY'], iv))
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\aes.py", line 10, in aes_cbc_decrypt_bytes
    return Cryptodome_AES.new(key, Cryptodome_AES.MODE_CBC, iv).decrypt(data)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\Cryptodome\Cipher\_mode_cbc.py", line 229, in decrypt
    plaintext = create_string_buffer(len(ciphertext))
TypeError: object of type 'NoneType' has no len()
```

**Comment by jriker1** [comment] 2022-06-17 22:25
Some more log info:

[debug] Command-line config: ['--audio-quality', '0', '--add-metadata', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.nbc.com/americas-got-talent/video/auditions-3/9000246183', '-o', "America's Got Talent S17E3.mp4", '--cookies', 'c:\\temp\\nbc.com_cookies.txt', '--ffmpeg-location', 'z:\\ffmpeg\\bin', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.9.0 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: "z:\ffmpeg\bin\ffprobe" -bsfs
[debug] Checking exe version: "z:\ffmpeg\bin\ffmpeg" -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [NBC] Extracting URL: https://www.nbc.com/americas-got-talent/video/auditions-3/9000246183
[NBC] 9000246183: Downloading JSON metadata
[NBC] 9000246183: Downloading JSON metadata
[debug] Loading ap-mvpd.nbcentertainment from cache
[NBC] 9000246183: Retrieving Media Token
[debug] [ThePlatform] Extracting URL: http://link.theplatform.com/s/NnzsPC/media/guid/2410887629/9000246183?mbr=true&manifest=m3u&auth=%3CsignatureInfo%3EhDcQh36uYkq%2FgkuanfXi1iRV%2FqAPSuazx5LbxQzq3EWiqzr7EXImVi44X1Bcpqh8kurpc3%2FTX6amuQZtXwjeP5Lzijh0RmbGGf%2FUq2pB0sklsyyyVcNlPYXBZ38aBLiZB9oT43OqK2iN%2FK7lecI7h8%2BsScphSifQgjTe6ST8GlU%3D%3CsignatureInfo%3E%3CauthToken%3E%3CsessionGUID%3E4fc043b16ed1aff6ef1d0fad32591510%3C%2FsessionGUID%3E%3CrequestorID%3Enbcentertainment%3C%2FrequestorID%3E%3CresourceID%3E%3C%21%5BCDATA%5B%3Crss+version%3D%222.0%22+xmlns%3Amedia%3D%22http%3A%2F%2Fsearch.yahoo.com%2Fmrss%2F%22%3E%3Cchannel%3E%3Ctitle%3Enbcentertainment%3C%2Ftitle%3E%3Citem%3E%3Ctitle%3EAuditions+3%3C%2Ftitle%3E%3Cguid%3E9000246183%3C%2Fguid%3E%3Cmedia%3Arating+scheme%3D%22urn%3Av-chip%22%3ETV-PG%3C%2Fmedia%3Arating%3E%3C%2Fitem%3E%3C%2Fchannel%3E%3C%2Frss%3E%5D%5D%3E%3C%2FresourceID%3E%3Cttl%3E420000%3C%2Fttl%3E%3CissueTime%3E2022-06-17+15%3A23%3A30+-0700%3C%2FissueTime%3E%3CmvpdId%3EComcast_SSO%3C%2FmvpdId%3E%3C%2FauthToken%3E#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 9000246183: Downloading SMIL data
[ThePlatform] 9000246183: Downloading m3u8 information
WARNING: [ThePlatform] Failed to download m3u8 information: HTTP Error 404: Not Found
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[ThePlatform] 9000246183: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
ERROR: [ThePlatform] 9000246183: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1479, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1583, in process_ie_result
    return self.process_ie_result(
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1535, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2622, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [ThePlatform] 9000246183: Requested format is not available. Use --list-formats for a list of available formats

**Comment by HobbyistDev** [comment] 2022-06-18 11:52
The link you gave (https://www.nbc.com/americas-got-talent/video/auditions-3/9000246183) have geo-block

**Comment by gamer191** [comment] 2022-06-18 12:27
Firstly, can you please put the verbose log in this template next time, so that it formats nicely:

````
```
Verbose log
```
````

Secondly, can you please put run the above command with `--list-formats` and send a verbose log of the results

Observation: it appears that the 2nd verbose log has a different error message compared to the first one

**Comment by pukkandan** [comment] 2022-06-18 14:54
@jriker1 The error message in your second log is weird. Can you show the output of `yt-dlp -vF "URL"`?

**Comment by pukkandan** [comment] 2023-09-06 12:25
Possible dupe of https://github.com/yt-dlp/yt-dlp/issues/516, https://github.com/yt-dlp/yt-dlp/issues/5123, but I'm not sure. Someone pls test the provided workaround in #516 and let us know

**Closed** 2023-11-28 23:41 UTC
Labels: incomplete, account-needed, geo-blocked, site-bug, can-share-account
