### ISSUE TITLE
How to use yt-dlp to merge multiple URLs

### ISSUE THREAD

**Issue by raidboy** [yt-dlp/yt-dlp#6060] opened 2023-01-19 23:48 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am using yt-dlp to download videos from german broadcaster 'medatheks'. For some reasons, it often happens that the web-page for some media is removed / disabled from their servers, but the actual media is still available. So i may end up having a URL for the videos m3u playlist and another URL for the subtitles for the media. In more complex situations i may also have two or more separate audio URLs (for different audio channels). I can use yt-dlp to individually download them, but not for all the nice work yt-dlp does in merging them (including conversions):

I can not figure out if or how i would be able to call yt-dlp to pull in all these URLs and merge them. Of course, yt-dlp can do this if there was a web-page that was including all these URLs.

If there is no trick with yt-dlp command line arguments to get this done, maybe there is an example most-simple "shim" webpage i could construct from a script that include these multiple media URLs, and then feed (as a file argument) this shim webpage .. But i do not know how such a minimal shim webpage should look like for yt-dlp to be able to parse it.

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

NA (don't know how to do it with yt-dlp as explained above)

**Comment by bashonly** [comment] 2023-01-20 01:05
Can you share example URLs? It sounds like you may be downloading variant m3u8 URLs. If there is a master m3u8 manifest available instead, that could possibly solve your problem

**Comment by raidboy** [comment] 2023-01-20 12:26
website        = 'https://tvthek.orf.at/profile/Tatort/2713749/Tatort-Toedliche-Habgier/14163209'
url_subtitles  = 'https://api-tvthek.orf.at/assets/subtitles/0148/41/c17e9a2a672c614a474abd474f54a591d877df57.ttml'
url_http_hd    = 'https://apasfiis.sf.apa.at/ipad/cms-worldwide/2023-01-07_2155_sd_02_Tatort--Toedlic_____14163209__o__1952470803__s15309500_0__ORF2HD_21555417P_23242005P_Q8C.mp4/playlist.m3u8'

These URLs are from the mediathekview.de database, which scrapes the web pages of the public german broadcasters (germany, switzerland, austria). The webpage URL is what you would normally give to yt-dlp, but then these do often not live long (maybe even as little as a single week). But the media URLs work longer.

In this case i can separately download via yt-dlp the video and the subtitle, but i can not figure out how to use yt-dlp to merge them into a single .mp4 file. Which involves conversion of the subtitles into srt. Which yt-dlp all perfectly does when its given a working webpage.

**Comment by dirkf** [comment] 2023-01-20 18:45
This sounds like a plausible approach, which you might be able to automate using a tool like _jq_:
1. Use `--write-info-json --simulate` for each of the to-be-merged URLs.
2. Merge the resulting JSON files.
4. Optionally, correct important metadata in the JSON like `title` that could be used to name the final media file.
3. Use `--load-info-json ...`, specifying the merged JSON, to download and process the items mentioned in the merged JSON.

**Comment by raidboy** [comment] 2023-01-21 17:37
Thanks a lot

a) i could not make yt-dlp to generate any json file with "--write-info-json". I straced it, and no file was opened to write. Would appreciate an example that is known to work, and what the name/directory of the generated json file is supposed to be with the example.

b) Instead, i could generate the json with the -j option

c) I could successfully create the desired output by I) dumping json of a working webpage with "-j", and II) reimporting the json with --load-info-json. So in general, this is a near trick.

d) alas, when i tried to create the json for the broken webpage case from the json of the m3u and then adding the subtitles JSON elements, running --load-info-json gives the following error:

[EmbedSubtitle] Embedding subtitles in "Das fleißige Lieschen [12254727].mp4"
ERROR: Postprocessing: file:Das fleißige Lieschen [12254727].de.ttml: Invalid data found when processing input

e) That actually was recreation of the effort with the working webpage, but removing the vtt format subtitle. Aka: whenever i do not have a working webpage, there is also no vtt subtitle URL, but only a ttml format subtitle URL, and it seems as if yt-dlp can not deal with ttml.  Which is strange, because from reading docs, it sounds as if yt-dlp seems to support ttml.

See attached json file. This will download with video/subtitle via --load-info-json, but if you remove the "vtt" type block from the file, yt-dlp will try to download the ttml, which it doesn, but then fail conversion with above error message.

[json.txt](https://github.com/yt-dlp/yt-dlp/files/10472681/json.txt)

**Comment by dirkf** [comment] 2023-01-21 18:34
Sorry, `--skip-download`, not `--simulate`, should give you a JSON file with the name of the putative video file.

**Comment by raidboy** [comment] 2023-01-21 19:33
Should i open a new issue against the problem with the ttml file ?

**Comment by pukkandan** [comment] 2023-01-21 22:01
The error message appear to be coming from ffmpeg, which implies that the subtitles are malformed. More details can be seen in the verbose log. It may also help to attach the subtitle file

> Provide verbose output that clearly demonstrates the problem
> * [x]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by dirkf** [comment] 2023-01-23 20:48
>yt-dlp does not convert from ttml subtitles to vtt subtitles

It might if you used `--convert-subs ...`, but that depends on _ffmpeg_ which [can't decode TTML](https://trac.ffmpeg.org/ticket/4859). The ticket has a linked script that would convert TTML which could be rewritten as an escape in the subtitle conversion postprocessor routine using Python XML processing, or the author of [this repo](https://github.com/isaacbernat/netflix-to-srt) could be asked to release his Python script for that purpose.

**Comment by pukkandan** [comment] 2023-01-28 15:03
Can't help you since you refuse to provide logs

**Closed by pukkandan** 2023-01-28 15:03 UTC
Labels: question

**Comment by Zocker1999NET** [comment] 2023-12-27 11:15
To avoid submitting a similar issue, I get the same issue on the same site, but with a different video. I attached the complete log (excluding the dynamic progress bar): [log.txt](https://github.com/yt-dlp/yt-dlp/files/13778092/log.txt)

**Comment by bashonly** [comment] 2023-12-27 20:49
@Zocker1999NET looks like your issue is unrelated, and you are experiencing [an ffmpeg regression](https://github.com/yt-dlp/yt-dlp/issues/8641). Upgrade to [the latest ***master*** build](https://github.com/yt-dlp/FFmpeg-Builds/releases/latest) or downgrade to ffmpeg 6.0
