### ISSUE TITLE
[Facebook] This video is only available for registered users

### ISSUE THREAD

**Issue by xenova** [yt-dlp/yt-dlp#542] opened 2021-07-22 03:03 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.07.21**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
Downloading the video (works correctly):
```
[debug] Command-line config: ['-v', 'https://www.facebook.com/disguisedtoast/videos/333201981735004/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.07.21 (source)
[debug] Python version 3.7.11 (CPython 64bit) - Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/disguisedtoast/videos/333201981735004/
[facebook] 333201981735004: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: 333201981735004
[facebook] playlist 333201981735004: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 333201981735004: Downloading 1 format(s): hd
[debug] Invoking downloader on "https://scontent-ort2-2.xx.fbcdn.net/v/t66.36240-6/42652743_516468659568827_1724802297672679617_n.mp4?_nc_cat=109&ccb=1-3&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6MTAyNCwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=dUON7GG4L0oAX9ZhbhE&_nc_oc=AQmV6TGrIpTO-hDcQDoi0eRgkrpl_WnMh0lLSl2YHzl2iNAKnLY07HIWUnKhjOM74C4&rl=1500&vabr=259&_nc_ht=scontent-ort2-2.xx&oh=31e1df728d35eb0224b6f3db5fb66c26&oe=60FCD410"
[download] Destination: Facebook video #333201981735004 [333201981735004].mp4
[download] 100% of 3.86MiB in 00:16
[download] Finished downloading playlist: 333201981735004
```

Listing formats (does not work)
```
[debug] Command-line config: ['-v', '-F', 'https://www.facebook.com/disguisedtoast/videos/333201981735004/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.07.21 (source)
[debug] Python version 3.7.11 (CPython 64bit) - Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/disguisedtoast/videos/333201981735004/
[facebook] 333201981735004: Downloading webpage
ERROR: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1151, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1176, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/common.py", line 572, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/facebook.py", line 672, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/facebook.py", line 526, in _extract_from_url
    self.raise_login_required()
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/common.py", line 1042, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials

```

Retrieving JSON info (does not work):
```
[debug] Command-line config: ['-v', '-j', 'https://www.facebook.com/disguisedtoast/videos/333201981735004/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.07.21 (source)
[debug] Python version 3.7.11 (CPython 64bit) - Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/disguisedtoast/videos/333201981735004/
[facebook] 333201981735004: Downloading webpage
ERROR: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1151, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1176, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/common.py", line 572, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/facebook.py", line 672, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/facebook.py", line 526, in _extract_from_url
    self.raise_login_required()
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/common.py", line 1042, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials

```

## Description

**PLEASE NOTE:** I am aware that the error given clearly describes how to solve the problem (i.e., supplying a username and password), however, I am unfortunately unable to provide authentication for my use-case.

Somehow, yt-dlp (and youtube-dl) is able to download the video, but cannot supply any other information? Is this intended? I would assume that if the video can be downloaded, it should have enough information to return the JSON (or list formats).

> I've checked that all provided URLs are alive and playable in a browser

I have loaded the video (without being logged in - and in incognito mode) and it seems to be playable in the browser, however, the error raised implies that login information is required.

**Comment by pukkandan** [comment] 2021-07-22 03:06
It didn't fail because of the -J/-F. The video seems to randomly succeed/fail when not authenticated
```
$ retry yt-dlp https://www.facebook.com/disguisedtoast/videos/333201981735004 -v

RUNNING: yt-dlp https://www.facebook.com/disguisedtoast/videos/333201981735004 -v
[debug] Command-line config: ['https://www.facebook.com/disguisedtoast/videos/333201981735004', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.21 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 3ba7740dd8
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/disguisedtoast/videos/333201981735004
[facebook] 333201981735004: Downloading webpage
ERROR: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials
Traceback (most recent call last):
  File "D:\Programs\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1152, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Programs\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1177, in __extract_info
    ie_result = ie.extract(url)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\common.py", line 572, in extract
    ie_result = self._real_extract(url)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\facebook.py", line 672, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\facebook.py", line 526, in _extract_from_url
    self.raise_login_required()
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\common.py", line 1042, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials

ERROR, Retrying...
--------------------------------------------------

RUNNING: yt-dlp https://www.facebook.com/disguisedtoast/videos/333201981735004 -v
[debug] Command-line config: ['https://www.facebook.com/disguisedtoast/videos/333201981735004', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.21 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 3ba7740dd8
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/disguisedtoast/videos/333201981735004
[facebook] 333201981735004: Downloading webpage
ERROR: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials
Traceback (most recent call last):
  File "D:\Programs\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1152, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Programs\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1177, in __extract_info
    ie_result = ie.extract(url)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\common.py", line 572, in extract
    ie_result = self._real_extract(url)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\facebook.py", line 672, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\facebook.py", line 526, in _extract_from_url
    self.raise_login_required()
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\common.py", line 1042, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials

ERROR, Retrying...
--------------------------------------------------

RUNNING: yt-dlp https://www.facebook.com/disguisedtoast/videos/333201981735004 -v
[debug] Command-line config: ['https://www.facebook.com/disguisedtoast/videos/333201981735004', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.21 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 3ba7740dd8
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/disguisedtoast/videos/333201981735004
[facebook] 333201981735004: Downloading webpage
ERROR: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials
Traceback (most recent call last):
  File "D:\Programs\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1152, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Programs\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1177, in __extract_info
    ie_result = ie.extract(url)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\common.py", line 572, in extract
    ie_result = self._real_extract(url)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\facebook.py", line 672, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\facebook.py", line 526, in _extract_from_url
    self.raise_login_required()
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\common.py", line 1042, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials

ERROR, Retrying...
--------------------------------------------------

RUNNING: yt-dlp https://www.facebook.com/disguisedtoast/videos/333201981735004 -v
[debug] Command-line config: ['https://www.facebook.com/disguisedtoast/videos/333201981735004', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.21 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 3ba7740dd8
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/disguisedtoast/videos/333201981735004
[facebook] 333201981735004: Downloading webpage
ERROR: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials
Traceback (most recent call last):
  File "D:\Programs\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1152, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Programs\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1177, in __extract_info
    ie_result = ie.extract(url)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\common.py", line 572, in extract
    ie_result = self._real_extract(url)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\facebook.py", line 672, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\facebook.py", line 526, in _extract_from_url
    self.raise_login_required()
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\common.py", line 1042, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials

ERROR, Retrying...
--------------------------------------------------

RUNNING: yt-dlp https://www.facebook.com/disguisedtoast/videos/333201981735004 -v
[debug] Command-line config: ['https://www.facebook.com/disguisedtoast/videos/333201981735004', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.21 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 3ba7740dd8
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/disguisedtoast/videos/333201981735004
[facebook] 333201981735004: Downloading webpage
ERROR: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials
Traceback (most recent call last):
  File "D:\Programs\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1152, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Programs\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1177, in __extract_info
    ie_result = ie.extract(url)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\common.py", line 572, in extract
    ie_result = self._real_extract(url)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\facebook.py", line 672, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\facebook.py", line 526, in _extract_from_url
    self.raise_login_required()
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\common.py", line 1042, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials

ERROR, Retrying...
--------------------------------------------------

RUNNING: yt-dlp https://www.facebook.com/disguisedtoast/videos/333201981735004 -v
[debug] Command-line config: ['https://www.facebook.com/disguisedtoast/videos/333201981735004', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.21 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 3ba7740dd8
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/disguisedtoast/videos/333201981735004
[facebook] 333201981735004: Downloading webpage
ERROR: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials
Traceback (most recent call last):
  File "D:\Programs\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1152, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Programs\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1177, in __extract_info
    ie_result = ie.extract(url)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\common.py", line 572, in extract
    ie_result = self._real_extract(url)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\facebook.py", line 672, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\facebook.py", line 526, in _extract_from_url
    self.raise_login_required()
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\common.py", line 1042, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials

ERROR, Retrying...
--------------------------------------------------

RUNNING: yt-dlp https://www.facebook.com/disguisedtoast/videos/333201981735004 -v
[debug] Command-line config: ['https://www.facebook.com/disguisedtoast/videos/333201981735004', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.21 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 3ba7740dd8
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/disguisedtoast/videos/333201981735004
[facebook] 333201981735004: Downloading webpage
ERROR: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials
Traceback (most recent call last):
  File "D:\Programs\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1152, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Programs\Source\yt-dlp\yt_dlp\YoutubeDL.py", line 1177, in __extract_info
    ie_result = ie.extract(url)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\common.py", line 572, in extract
    ie_result = self._real_extract(url)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\facebook.py", line 672, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\facebook.py", line 526, in _extract_from_url
    self.raise_login_required()
  File "D:\Programs\Source\yt-dlp\yt_dlp\extractor\common.py", line 1042, in raise_login_required
    raise ExtractorError(msg, expected=True)
yt_dlp.utils.ExtractorError: This video is only available for registered users. Use --cookies, --username and --password or --netrc to provide account credentials

ERROR, Retrying...
--------------------------------------------------

RUNNING: yt-dlp https://www.facebook.com/disguisedtoast/videos/333201981735004 -v
[debug] Command-line config: ['https://www.facebook.com/disguisedtoast/videos/333201981735004', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.21 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 3ba7740dd8
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/disguisedtoast/videos/333201981735004
[facebook] 333201981735004: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: 333201981735004
[facebook] playlist 333201981735004: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 333201981735004: Downloading 1 format(s): hd
[debug] Invoking downloader on "https://scontent.fblr4-1.fna.fbcdn.net/v/t66.36240-6/42652743_516468659568827_1724802297672679617_n.mp4?_nc_cat=109&ccb=1-3&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6MTAyNCwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=dUON7GG4L0oAX9rJgZl&_nc_oc=AQnxV5NZgElrbHLYgLMWT0fNhmQTlD-b23Roe2bf_jCdFCU0yHuTXvJgsxUQ7H7HALo&rl=1500&vabr=259&_nc_ht=scontent.fblr4-1.fna&oh=4149ef55aa5890f82a7be4eed339fd6d&oe=60FECE50"
[download] Destination: Facebook video #333201981735004 [333201981735004].mp4
[download]  25.9% of 3.86MiB at  1.55MiB/s ETA 00:01
ERROR: Interrupted by user
Terminate batch job (Y/N)?
```

**Comment by pukkandan** [comment] 2021-07-22 03:09
Related: https://github.com/ytdl-org/youtube-dl/issues/29490

**Comment by xenova** [comment] 2021-07-22 03:17
Oh wow, how strange.

I'm not sure if this is related, but I switched browsers and tried again and got this:
![image](https://user-images.githubusercontent.com/26504141/126585458-04bf5cdb-5f2c-4081-89c1-ab57e05b7862.png)


However, after simply clicking "close", I was able to watch the video?
![image](https://user-images.githubusercontent.com/26504141/126585489-7cb262c8-d162-4b74-a54b-504b4c2cf14b.png)

**Comment by xenova** [comment] 2021-07-25 18:36
Okay, so I've been trying to fix this for the past few days and I think I've come to the following conclusions:
1. The main problem seems to be trying to access https://www.facebook.com/video/tahoe/async/{video_id} and https://www.facebook.com/video.php?v={video_id}. Both endpoints seem to be highly unpredictable: sometimes requiring authentication and sometimes not.
2. In my opinion, we should try convert as many requests as possible (maybe all) to use https://www.facebook.com/api/graphql/ and a suitable query (headers). From my testing, there is a possibility this could work. Unfortunately, there are a few problems: 
    - I am still looking for the correct queries to make, as most of this is undocumented.
    - In some cases, the response isn't proper JSON; rather, it is a collection of ~3 JSON responses (for some reason?)

For anyone willing to assist, I would recommend just opening a webpage in incognito mode, opening dev tools and observing the "graphql" queries being sent.

In the meantime, I will try do the same and post and discoveries here. My first one being:

---
```python
import requests
import json

video_id = 333201981735004 # example 1
video_id = 570133851026337 # example 2

data = {
  '__user': '0',
  '__a': '1',
  '__comet_req': '1',
  'variables': json.dumps({
      'upNextVideoID': video_id,
      'currentID': video_id,
      'scale': 1,
  }),
  'doc_id': '4730353697015342'
}


response = requests.post('https://www.facebook.com/api/graphql/', data=data)
print(response.json())
```

In fact, the request can be shortened to this, which gives a few warnings (due to missing parameters), but returns information we want:
```python
import requests
import json

video_id = 333201981735004

data = {
  '__user': '0',
  '__a': '1',
  '__comet_req': '1',
  'variables': json.dumps({
      'upNextVideoID': video_id,
  }),
  'doc_id': '4730353697015342'
}

response = requests.post('https://www.facebook.com/api/graphql/', data=data)
print(response.json())
```

returns (slightly truncated)
```json
{
   "data":{
      "upNextVideoData":{
         "is_live_streaming":false,
         "title_with_fallback":"My absolute weirdest fan interaction ever",
         "owner":{
            "__typename":"User",
            "name":"Disguised Toast",
            "profile_picture":{
               "uri":"https://scontent-cpt1-1.xx.fbcdn.net/v/t1.6435-1/cp0/p60x60/174117027_303848991109910_3830552023470292711_n.jpg?_nc_cat=1&ccb=1-3&_nc_sid=c6021c&_nc_ohc=1wVFH71FNEMAX9OSTry&_nc_ht=scontent-cpt1-1.xx&oh=592e95da311b0c22f8bb810ee8c046c6&oe=61248DEB"
            },
            "__isVideoOwner":"User",
            "uri_token":"disguisedtoast",
            "id":"100044544334877"
         },
         "savable_description":{
            "text":"My weirdest fan interaction story."
         },
         "publish_time":1624064401,
         "play_count":49192,
         "image":{
            "uri":"https://scontent-cpt1-1.xx.fbcdn.net/v/t15.5256-10/s640x640/194618398_333204035068132_5257593534289420431_n.jpg?_nc_cat=109&ccb=1-3&_nc_sid=ad6a45&_nc_ohc=zUMqz-KA7f8AX-9sG7u&_nc_ht=scontent-cpt1-1.xx&oh=87b0f5b86e34372609da20c8d4d75181&oe=6103082E"
         },
         "smart_preview_video":"None",
         "broadcast_status":"None",
         "has_viewer_watched_show_video":false,
         "playable_duration":104,
         "breaking_status":false,
         "is_premiere":false,
         "url":"https://www.facebook.com/disguisedtoast/videos/333201981735004/",
         "id":"333201981735004"
      }
}
```

---

Hopefully someone can pick up where I have left off :) :+1:

**Comment by llacb47** [comment] 2021-07-26 23:01
@xenova Thanks for your research. Are you sure that `https://www.facebook.com/video/tahoe/async/` is flaky with unregistered users (even with my patch)? I haven't personally experienced that. What is the response from that endpoint telling you that auth is req'd? 

All in all, moving this extractor to gql is a good idea since facebook's frontend is basically built on it. I'll look into it and possibly have some time to work on it this week.

**Comment by marcello-pietrobon** [comment] 2022-10-25 16:03
> [xenova](/xenova)
> For anyone willing to assist, I would recommend just opening a webpage in incognito mode, opening dev tools and observing the "graphql" queries being sent.

May I ask what exactly we need to look for inside the dev tools in order to see what you describe?

Is there a tutorial somewhere on how we can better expand or create a new extractor?
(I wouldn't want to open a new issue just for this question)
Thanks!

**Comment by bashonly** [comment] 2024-01-31 23:36
Can no longer reproduce the issue; example links download fine with master

Tahoe endpoint request failure can be tracked in #4311

**Closed by bashonly** 2024-01-31 23:36 UTC
Labels: site-bug, site:facebook
