### ISSUE TITLE
Douyin Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by wangxiaochao** [yt-dlp/yt-dlp#11329] opened 2024-10-23 07:57 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --cookies-from-browser chrome --verbose 'https://www.douyin.com/video/7424816300066671872'
[debug] Command-line config: ['--cookies-from-browser', 'chrome', '--verbose', 'https://www.douyin.com/video/7424816300066671872']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874] (pip)
[debug] Python 3.13.0 (CPython x86_64 64bit) - macOS-12.4-x86_64-i386-64bit-Mach-O (OpenSSL 3.3.2 3 Sep 2024)
[debug] exe versions: ffmpeg 7.1 (setts), ffprobe 7.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/wangxiaochao/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
Extracted 961 cookies from chrome
[debug] cookie version breakdown: {'v10': 976, 'other': 0, 'unencrypted': 2}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[Douyin] Extracting URL: https://www.douyin.com/video/7424816300066671872
[Douyin] 7424816300066671872: Downloading web detail JSON
WARNING: [Douyin] 7424816300066671872: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
ERROR: [Douyin] 7424816300066671872: Fresh cookies (not necessarily logged in) are needed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/Cellar/yt-dlp/2024.10.7/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2024.10.7/libexec/lib/python3.13/site-packages/yt_dlp/extractor/tiktok.py", line 1337, in _real_extract
    raise ExtractorError(
        'Fresh cookies (not necessarily logged in) are needed',
        expected=not self._get_cookies(self._WEBPAGE_HOST).get('s_v_web_id'))
```

**Comment by bashonly** [comment] 2024-10-23 08:06
Duplicate of #9667

**Closed by bashonly** 2024-10-23 08:06 UTC
Labels: duplicate, site-bug, site:tiktok
