### ISSUE TITLE
[Broken] [ZEE5] Can not download JSON metadata

### ISSUE THREAD

**Issue by GetPHP-IR** [yt-dlp/yt-dlp#736] opened 2021-08-19 09:19 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
yt-dlp -F "https://www.zee5.com/tvshows/details/yeh-teri-galiyan/0-6-tvshow_826525818/yeh-teri-galiyan-episode-1-july-25-2018-full-episode/0-1-tvshow_826525818-season_1212543750-episode_606680477" -v
[debug] Command-line config: ['-F', 'https://www.zee5.com/tvshows/details/yeh-teri-galiyan/0-6-tvshow_826525818/yeh-teri-galiyan-episode-1-july-25-2018-full-episode/0-1-tvshow_826525818-season_1212543750-episode_606680477', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10
[debug] Python version 3.7.8 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-102995-g694545b6d5-20210718, ffprobe N-102995-g694545b6d5-20210718
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [Zee5] Extracting URL: https://www.zee5.com/tvshows/details/yeh-teri-galiyan/0-6-tvshow_826525818/yeh-teri-galiyan-episode-1-july-25-2018-full-episode/0-1-tvshow_826525818-season_1212543750-episode_606680477
[Zee5] 0-1-tvshow_826525818-season_1212543750-episode_606680477: Downloading access token
[Zee5] 0-1-tvshow_826525818-season_1212543750-episode_606680477: Downloading video token
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "C:\Users\Hamed\AppData\Roaming\Python\Python37\site-packages\yt_dlp\extractor\common.py", line 682, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Hamed\AppData\Roaming\Python\Python37\site-packages\yt_dlp\YoutubeDL.py", line 3190, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "e:\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "e:\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "e:\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "e:\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "e:\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "e:\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "e:\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "e:\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "e:\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "e:\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description

Seems the yt-dlp can not access http://useraction.zee5.com/tokennd/ and gives 404 error. (I don't try with a Indian proxy server)

**Comment by MinePlayersPE** [comment] 2021-08-19 09:20
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/728?

**Comment by Ashish0804** [comment] 2021-08-19 09:47
Do not check `I've searched the bugtracker for similar issues including closed ones` blindly.

**Closed by Ashish0804** 2021-08-19 09:47 UTC
