### ISSUE TITLE
unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by momogood168** [yt-dlp/yt-dlp#8433] opened 2023-10-25 15:28 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

D:\yt-dlp>yt-dlp https://fod.fujitv.co.jp/title/f0ik/f0ik110024/
[FujiTVFODPlus7] Extracting URL: https://fod.fujitv.co.jp/title/f0ik/f0ik110024/
[FujiTVFODPlus7] f0ik110024: Downloading webpage
[FujiTVFODPlus7] f0ik110024: Downloading JSON metadata
[FujiTVFODPlus7] f0ik110024: Downloading JSON metadata
[FujiTVFODPlus7] f0ik110024: Downloading m3u8 information
[FujiTVFODPlus7] f0ik110024: Downloading m3u8 information
[FujiTVFODPlus7] f0ik110024: Downloading m3u8 information
[info] f0ik110024: Downloading 1 format(s): 99
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\yt-dlp>yt-dlp -uV https://fod.fujitv.co.jp/title/f0ik/f0ik110024/
Type account password and press [Return]:
WARNING: [FujiTVFODPlus7] Login with password is not supported for this website. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[FujiTVFODPlus7] Extracting URL: https://fod.fujitv.co.jp/title/f0ik/f0ik110024/
[FujiTVFODPlus7] f0ik110024: Downloading webpage
[FujiTVFODPlus7] f0ik110024: Downloading JSON metadata
[FujiTVFODPlus7] f0ik110024: Downloading JSON metadata
[FujiTVFODPlus7] f0ik110024: Downloading m3u8 information
[FujiTVFODPlus7] f0ik110024: Downloading m3u8 information
[FujiTVFODPlus7] f0ik110024: Downloading m3u8 information
[info] f0ik110024: Downloading 1 format(s): 99
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment] 2023-10-25 16:18
Duplicate of #7064

The video is DRM protected. Extractor needs to be improved to detect DRM and raise an appropriate error

**Closed by bashonly** 2023-10-25 16:18 UTC
Labels: question
