### ISSUE TITLE
[YOUTUBE] '-f worst' : ERROR:  Requested format is not available.

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#11164] opened 2024-10-04 17:39 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Norway

### Provide a description that is worded well enough to be understood

Requesting video format `-f worst` fails. Enclosed terminal output will hopefully be sufficient input on my side for devs to debug this. Downloading these files individually with `-f 134+139`

 works fine.### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -f worst --dateafter 20221101 --datebefore 20221110 https://www.youtube.com/@DeFriaBankreform
[youtube:tab] Extracting URL: https://www.youtube.com/@DeFriaBankreform
[youtube:tab] @DeFriaBankreform: Downloading webpage
[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[youtube:tab] @DeFriaBankreform/shorts: Downloading webpage
[youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUF91tw2MUPA9KsOuUvU5B0w
[download] Downloading playlist: De Fria
[youtube:tab] Playlist De Fria: Downloading 2 items of 2
[download] Downloading item 1 of 2
[download] Downloading playlist: De Fria - Videos
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 1: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 2: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 3: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 4: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 5: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 6: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 7: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 8: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 9: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 10: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 11: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 12: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 13: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 14: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 15: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 16: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 17: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 18: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 19: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 20: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 21: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 22: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 23: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 24: Downloading API JSON
[youtube:tab] UCF91tw2MUPA9KsOuUvU5B0w page 25: Downloading API JSON
[youtube:tab] Playlist De Fria - Videos: Downloading 770 items of 770
[download] Downloading item 1 of 770
[youtube] Extracting URL: https://www.youtube.com/watch?v=ws-u1iry7_c
[youtube] ws-u1iry7_c: Downloading webpage
[youtube] ws-u1iry7_c: Downloading ios player API JSON
[youtube] ws-u1iry7_c: Downloading web creator player API JSON
[youtube] ws-u1iry7_c: Downloading m3u8 information
[download] 2024-10-04 upload date is not in range 2022-11-01 to 2022-11-10
[download] Downloading item 2 of 770



[download] 2022-11-11 upload date is not in range 2022-11-01 to 2022-11-10
[download] Downloading item 305 of 770
[youtube] Extracting URL: https://www.youtube.com/watch?v=NoxzC0Xgy-I
[youtube] NoxzC0Xgy-I: Downloading webpage
[youtube] NoxzC0Xgy-I: Downloading ios player API JSON
[youtube] NoxzC0Xgy-I: Downloading web creator player API JSON
[youtube] NoxzC0Xgy-I: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] NoxzC0Xgy-I: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1841, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2977, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] NoxzC0Xgy-I: Requested format is not available. Use --list-formats for a list of available formats

[download] Downloading item 306 of 770
[youtube] Extracting URL: https://www.youtube.com/watch?v=tx4d1NISm-0
[youtube] tx4d1NISm-0: Downloading webpage
[youtube] tx4d1NISm-0: Downloading ios player API JSON
[youtube] tx4d1NISm-0: Downloading web creator player API JSON
[youtube] tx4d1NISm-0: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] tx4d1NISm-0: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1841, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2977, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] tx4d1NISm-0: Requested format is not available. Use --list-formats for a list of available formats

[download] Downloading item 307 of 770
[youtube] Extracting URL: https://www.youtube.com/watch?v=t01Osz-bPyY
[youtube] t01Osz-bPyY: Downloading webpage
[youtube] t01Osz-bPyY: Downloading ios player API JSON
[youtube] t01Osz-bPyY: Downloading web creator player API JSON
[youtube] t01Osz-bPyY: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] t01Osz-bPyY: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1841, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2977, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] t01Osz-bPyY: Requested format is not available. Use --list-formats for a list of available formats

[download] Downloading item 308 of 770
[youtube] Extracting URL: https://www.youtube.com/watch?v=u0kK5fnrzqQ
[youtube] u0kK5fnrzqQ: Downloading webpage
[youtube] u0kK5fnrzqQ: Downloading ios player API JSON
[youtube] u0kK5fnrzqQ: Downloading web creator player API JSON
[youtube] u0kK5fnrzqQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] u0kK5fnrzqQ: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1841, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/halvor/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2977, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] u0kK5fnrzqQ: Requested format is not available. Use --list-formats for a list of available formats

[download] Downloading item 309 of 770
[youtube] Extracting URL: https://www.youtube.com/watch?v=HFfwIwkjfGs
[youtube] HFfwIwkjfGs: Downloading webpage
[youtube] HFfwIwkjfGs: Downloading ios player API JSON
[youtube] HFfwIwkjfGs: Downloading web creator player API JSON
[youtube] HFfwIwkjfGs: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[download] 2022-10-31 upload date is not in range 2022-11-01 to 2022-11-10



$ yt-dlp -F https://www.youtube.com/watch?v=NoxzC0Xgy-I
[youtube] Extracting URL: https://www.youtube.com/watch?v=NoxzC0Xgy-I
[youtube] NoxzC0Xgy-I: Downloading webpage
[youtube] NoxzC0Xgy-I: Downloading ios player API JSON
[youtube] NoxzC0Xgy-I: Downloading web creator player API JSON
[youtube] NoxzC0Xgy-I: Downloading m3u8 information
[info] Available formats for NoxzC0Xgy-I:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb1 mhtml 80x45        0    │                  mhtml │ images                                  storyboard
sb0 mhtml 160x90       0    │                  mhtml │ images                                  storyboard
233 mp4   audio only        │                  m3u8  │ audio only          unknown             Default
234 mp4   audio only        │                  m3u8  │ audio only          unknown             Default
139 m4a   audio only      2 │   46.37MiB   49k https │ audio only          mp4a.40.5   49k 22k low, m4a_dash
140 m4a   audio only      2 │  123.07MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, m4a_dash
269 mp4   256x144     30    │ ~104.50MiB  110k m3u8  │ avc1.4D400C    110k video only
160 mp4   256x144     30    │   15.59MiB   16k https │ avc1.4D400C     16k video only          144p, mp4_dash
230 mp4   640x360     30    │ ~228.32MiB  240k m3u8  │ avc1.4D401E    240k video only
134 mp4   640x360     30    │   37.49MiB   39k https │ avc1.4D401E     39k video only          360p, mp4_dash
605 mp4   640x360     30    │ ~278.25MiB  293k m3u8  │ vp09.00.21.08  293k video only
232 mp4   1280x720    30    │ ~404.25MiB  425k m3u8  │ avc1.4D401F    425k video only
136 mp4   1280x720    30    │  127.46MiB  134k https │ avc1.4D401F    134k video only          720p, mp4_dash
270 mp4   1920x1080   30    │ ~  1.61GiB 1735k m3u8  │ avc1.640028   1735k video only
137 mp4   1920x1080   30    │    1.10GiB 1189k https │ avc1.640028   1189k video only          1080p, mp4_dash


$ yt-dlp -F https://www.youtube.com/watch?v=tx4d1NISm-0
[youtube] Extracting URL: https://www.youtube.com/watch?v=tx4d1NISm-0
[youtube] tx4d1NISm-0: Downloading webpage
[youtube] tx4d1NISm-0: Downloading ios player API JSON
[youtube] tx4d1NISm-0: Downloading web creator player API JSON
[youtube] tx4d1NISm-0: Downloading m3u8 information
[info] Available formats for tx4d1NISm-0:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb1 mhtml 80x45        0    │                  mhtml │ images                                  storyboard
sb0 mhtml 160x90       0    │                  mhtml │ images                                  storyboard
233 mp4   audio only        │                  m3u8  │ audio only          unknown             Default
234 mp4   audio only        │                  m3u8  │ audio only          unknown             Default
139 m4a   audio only      2 │   39.72MiB   49k https │ audio only          mp4a.40.5   49k 22k low, m4a_dash
140 m4a   audio only      2 │  105.42MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, m4a_dash
251 webm  audio only      2 │   86.95MiB  107k https │ audio only          opus       107k 48k medium, webm_dash
269 mp4   256x144     30    │ ~ 86.12MiB  106k m3u8  │ avc1.4D400C    106k video only
160 mp4   256x144     30    │   12.63MiB   16k https │ avc1.4D400C     16k video only          144p, mp4_dash
230 mp4   640x360     30    │ ~195.10MiB  240k m3u8  │ avc1.4D401E    240k video only
134 mp4   640x360     30    │   29.43MiB   36k https │ avc1.4D401E     36k video only          360p, mp4_dash
18  mp4   640x360     30  2 │  279.49MiB  343k https │ avc1.42001E         mp4a.40.2       44k 360p
605 mp4   640x360     30    │ ~262.52MiB  322k m3u8  │ vp09.00.21.08  322k video only
243 webm  640x360     30    │   51.41MiB   63k https │ vp9             63k video only          360p, webm_dash
232 mp4   1280x720    30    │ ~320.94MiB  394k m3u8  │ avc1.4D401F    394k video only
136 mp4   1280x720    30    │   97.84MiB  120k https │ avc1.4D401F    120k video only          720p, mp4_dash
270 mp4   1920x1080   30    │ ~  1.24GiB 1565k m3u8  │ avc1.640028   1565k video only
137 mp4   1920x1080   30    │  882.58MiB 1084k https │ avc1.640028   1084k video only          1080p, mp4_dash


$ yt-dlp -F https://www.youtube.com/watch?v=t01Osz-bPyY
[youtube] Extracting URL: https://www.youtube.com/watch?v=t01Osz-bPyY
[youtube] t01Osz-bPyY: Downloading webpage
[youtube] t01Osz-bPyY: Downloading ios player API JSON
[youtube] t01Osz-bPyY: Downloading web creator player API JSON
[youtube] t01Osz-bPyY: Downloading m3u8 information
[info] Available formats for t01Osz-bPyY:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb1 mhtml 80x45        0    │                  mhtml │ images                                  storyboard
sb0 mhtml 160x90       0    │                  mhtml │ images                                  storyboard
233 mp4   audio only        │                  m3u8  │ audio only          unknown             Default
234 mp4   audio only        │                  m3u8  │ audio only          unknown             Default
139 m4a   audio only      2 │   37.60MiB   49k https │ audio only          mp4a.40.5   49k 22k low, m4a_dash
140 m4a   audio only      2 │   99.80MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, m4a_dash
251 webm  audio only      2 │   77.49MiB  101k https │ audio only          opus       101k 48k medium, webm_dash
269 mp4   256x144     30    │ ~117.65MiB  153k m3u8  │ avc1.4D400C    153k video only
160 mp4   256x144     30    │   13.00MiB   17k https │ avc1.4D400C     17k video only          144p, mp4_dash
230 mp4   640x360     30    │ ~257.72MiB  334k m3u8  │ avc1.4D401E    334k video only
134 mp4   640x360     30    │   31.38MiB   41k https │ avc1.4D401E     41k video only          360p, mp4_dash
605 mp4   640x360     30    │ ~342.29MiB  444k m3u8  │ vp09.00.21.08  444k video only
232 mp4   1280x720    30    │ ~431.87MiB  560k m3u8  │ avc1.4D401F    560k video only
136 mp4   1280x720    30    │   98.97MiB  128k https │ avc1.4D401F    128k video only          720p, mp4_dash
270 mp4   1920x1080   30    │ ~  1.34GiB 1777k m3u8  │ avc1.640028   1777k video only
137 mp4   1920x1080   30    │  783.77MiB 1017k https │ avc1.640028   1017k video only          1080p, mp4_dash
```

**Comment by seproDev** [comment] 2024-10-04 18:01
`-f worst` downloads, the worst combined video and audio format. YouTube only has a single combined format remaining and that is 18. They currently seem to be experimenting with removing that too.

**Comment by Trit34** [comment] 2024-10-04 18:47
I recently noticed that format 136 (720p30 MP4, useful when using a computer old enough – 2009, Core 2 Duo inside – that does not like 720p60) is missing sometimes, but becomes available later. I don’t know if it’s like this for a long time or if it’s new.

**Comment by bashonly** [comment] 2024-10-05 00:13
same issue as #11154

**Comment by dbirchbauer** [comment] 2024-10-06 21:27
I am seeing the same issue of format not found when using best and I have FFMPEG defined

**Comment by seproDev** [comment] 2024-10-06 21:49
`best`/`worst` means the best/worst **premerged** format. If there is no premerged format available, nothing can be downloaded. Imo. you nearly never want to pass `-f best`/`-f worst`.
Leave the default `-f` value and yt-dlp will decide by itself if a premerged video can be downloaded or if separate audio/video tracks need to be merged.

**Comment by bashonly** [comment] 2024-10-07 23:14
Duplicate of #11185

**Closed by bashonly** 2024-10-07 23:14 UTC
Labels: question

**Comment by Trit34** [comment] 2024-10-08 08:08
> Yep, must be a new thing. Havent had any problems earlier on using this format as my default for older machines. Only recently yt-dlp started to report 136+140 on check fine as usual, but trying to download it fails with the format being unavailable most of the time. Falls back to 135+140 (480p30) in my case.

Retrying generally works (for now).

Well, it’s infortunate, because I used to download replays of Twitch steams reposted on YT, where they are available in 720p30 (instead of 720p60 on the Twitch’s own replay).

**Comment by bashonly** [comment] 2024-10-08 20:32
update yt-dlp
