### ISSUE TITLE
The Tencent Video extractor is not functioning properly

### ISSUE THREAD

**Issue by Lonely233233** [yt-dlp/yt-dlp#8551] opened 2023-11-09 04:33 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Unable to extract and play.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Administrator>yt-dlp -vU -F https://v.qq.com/x/cover/aa79w3zdmnfkfy4/t0015v0hm7t.html
[debug] Command-line config: ['-vU', '-F', 'https://v.qq.com/x/cover/aa79w3zdmnfkfy4/t0015v0hm7t.html']
[debug] Portable config "E:\Tencent\Mplayer\yt-dlp.conf": ['--output', 'E:\\Tencent\\N_m3u8DL-CLI\\Downloads\\%(title)s-%(section_number)s-%(section_title)s.%(ext)s', '--console-title', '--progress-template', 'download-title:%(info.id)s-%(progress.eta)s', '--merge-output-format', 'mp4', '--no-write-subs', '--external-downloader', 'aria2c', '--cookies-from-browser', 'edge', '--embed-thumbnail', '--embed-metadata']
Extracting cookies from edge
[debug] Extracting cookies from: "C:\Users\Administrator\AppData\Local\Microsoft\Edge\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Administrator\AppData\Local\Microsoft\Edge\User Data\Local State"
Extracted 252 cookies from edge
[debug] cookie version breakdown: {'v10': 252, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.12.0 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg 2022-12-01-git-45ab5307a6-full_build-www.gyan.dev (setts), ffprobe 2022-12-01-git-45ab5307a6-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.42.0, urllib3-2.0.7, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1887 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 10a1bbe7cd1162918c7d7d73127bf6886a648aa8e01b5663d5abc52d9b7d162d
yt-dlp is up to date (stable@2023.10.13)
[vqq:video] Extracting URL: https://v.qq.com/x/cover/aa79w3zdmnfkfy4/t0015v0hm7t.html
[vqq:video] t0015v0hm7t: Downloading webpage
WARNING: [vqq:video] t0015v0hm7t: Unable to extract pinia data - Failed to parse JSON: t0015v0hm7t: Failed to parse JSON (caused by JSONDecodeError('Expecting \',\' delimiter in \'lice.call"({"0":[{"c\': line 1 column 12591 (char 12590)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[vqq:video] t0015v0hm7t: Downloading webpage
[vqq:video] t0015v0hm7t: Downloading webpage
[vqq:video] t0015v0hm7t: Downloading webpage
[vqq:video] t0015v0hm7t: Downloading m3u8 information
```

**Comment by bashonly** [comment] 2023-11-09 09:13
> ```
> [vqq:video] t0015v0hm7t: Downloading m3u8 information
> ```

it hangs at this step? exits?

seems possibly related to #8171

**Comment by Lonely233233** [comment] 2023-11-09 09:30
> > ```
> > [vqq:video] t0015v0hm7t: Downloading m3u8 information
> > ```
> 
> it hangs at this step? exits?
> 
> seems possibly related to #8171

It seems that it can be parsed, but it is very slow, and the download speed is also limited

**Comment by bashonly** [comment] 2023-11-09 10:03
Then this is a duplicate of #8171

No known solution or workaround yet, sorry

**Closed by bashonly** 2023-11-09 10:03 UTC
Labels: site-bug, triage
