### ISSUE TITLE
[Hidive] Can only download the account's default subtitle/dub option

### ISSUE THREAD

**Issue by acc029** [yt-dlp/yt-dlp#6724] opened 2023-04-06 20:49 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I can only download the "Spanish LatAm" subtitles, when many other options (English, Portuguese, German, Arabic, and more) are available on the site.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--list-subs', '-vU', 'https://www.hidive.com/stream/ahiru-no-sora/s01e001']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.04.06.074452 [141a8dff9] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.1
[debug] Proxy map: {}
[debug] Loaded 1791 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.04.06.074452, Current version: nightly@2023.04.06.074452
Current Build Hash: 2e4ba37c2958203b7326e04fd2f73ee4cc326ea1ba863b53e4bf03ffb6d5d754
yt-dlp is up to date (nightly@2023.04.06.074452)
[HiDive] None: Downloading webpage
[HiDive] Logging in
[HiDive] Extracting URL: https://www.hidive.com/stream/ahiru-no-sora/s01e001
[HiDive] ahiru-no-sora/s01e001: Downloading JSON metadata
[HiDive] ahiru-no-sora/s01e001: Downloading m3u8 information
[HiDive] ahiru-no-sora/s01e001: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available subtitles for ahiru-no-sora/s01e001:
Language           Formats
spanish-latam-subs vtt
```

**Comment by Tblue** [comment] 2023-05-28 01:45
I think I have a fix for this, will try to create a PR for that in the next days.

**Comment by Jaynator495** [comment] 2023-06-29 13:55
It's worth noting that this is a regression in the extractor, it worked in an older version, here is a comparison from when it worked vs when it broke:
https://github.com/yt-dlp/yt-dlp/compare/2023.01.06...2023.02.17

**Comment by pukkandan** [comment] 2023-06-29 19:25
cc @chexxor

**Comment by bashonly** [comment] 2023-07-01 04:40
per discussion on discord, the old subtitles extraction code still works and retrieves all available languages

**Comment by chexxor** [comment] 2023-07-01 22:49
Yeah, that looks like my change broke it. When I was making my change, I couldn't figure out where it was getting the subtitle info from, so I wasn't able to make that work well again. Feel free to copy-paste the previous subtitle extraction code into the main branch again.

**Comment by Tblue** [comment] 2023-07-02 13:48
FYI, [above, I wrote:](https://github.com/yt-dlp/yt-dlp/issues/6724#issuecomment-1565790552):

> I think I have a fix for this, will try to create a PR for that in the next days.

Turns out my "fix" looks pretty much like what the extractor was doing before the regression was introduced in 7708df8, so let me know if you still want me to open a PR with my code, or if someone wants to restore the old code.

**Comment by pukkandan** [comment] 2023-07-03 09:38
Yes, pls make PR. Even if it's just reverting to old code, I don't have account to test.

**Comment by Tblue** [comment] 2023-07-15 21:17
> Yes, pls make PR. Even if it's just reverting to old code, I don't have account to test.

Sorry, might take a while longer, I'm dealing with some personal stuff at the moment.

**Comment by nagi-neko1** [comment] 2023-10-03 00:05
Hello, will the fix be pushed in soon? I am looking to download Hidive episodes, but have been stuck on this issue.

**Comment by Tblue** [comment] 2023-10-13 12:05
I’ll try to have a look soon. Am 03.10.2023 um 02:06 schrieb nagi-neko1 ***@***.***>:﻿
Hello, will the fix be pushed in soon? I am looking to download Hidive episodes, but have been stuck on this issue.

**Comment by bashonly** [comment] 2024-03-09 23:56
Closing due to #9385

**Closed by bashonly** 2024-03-09 23:56 UTC
Labels: account-needed, site-bug, can-share-account, regression
