### ISSUE TITLE
[RUMBLE] Downloads playlist, then stops.

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#10979] opened 2024-09-11 13:20 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Norway

### Provide a description that is worded well enough to be understood

Downloading files in playlists or portions of playlists appears to be broken. yt-dlp simply exits following the retrieval of the playlist.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU -S res:360 --dateafter 20240901 --datebefore 20240905 https://rumble.com/c/RedVoiceMedia
[debug] Command-line config: ['-vU', '-S', 'res:360', '--dateafter', '20240901', '--datebefore', '20240905', 'https://rumble.com/c/RedVoiceMedia']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-119-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[RumbleChannel] Extracting URL: https://rumble.com/c/RedVoiceMedia
[download] Downloading playlist: RedVoiceMedia
[RumbleChannel] RedVoiceMedia: Downloading page 1
[RumbleChannel] RedVoiceMedia: Downloading page 2
[RumbleChannel] RedVoiceMedia: Downloading page 3
[RumbleChannel] RedVoiceMedia: Downloading page 4
[RumbleChannel] RedVoiceMedia: Downloading page 5
[RumbleChannel] RedVoiceMedia: Downloading page 6
[RumbleChannel] RedVoiceMedia: Downloading page 7

[lines deleted]

[RumbleChannel] RedVoiceMedia: Downloading page 696
[RumbleChannel] RedVoiceMedia: Downloading page 697
[RumbleChannel] RedVoiceMedia: Downloading page 698
[RumbleChannel] RedVoiceMedia: Downloading page 699
[RumbleChannel] RedVoiceMedia: Downloading page 700
[RumbleChannel] RedVoiceMedia: Downloading page 701
[RumbleChannel] RedVoiceMedia: Downloading page 702
[RumbleChannel] Playlist RedVoiceMedia: Downloading 0 items
[download] Finished downloading playlist: RedVoiceMedia
halvor@halvor-NBLK-WAX9X:~$
```

**Comment by bashonly** [comment] 2024-09-11 14:51
Duplicate of #10833

**Closed by bashonly** 2024-09-11 14:51 UTC
Labels: duplicate, site-bug
