### ISSUE TITLE
Hidive not working with --cookies-from-browser

### ISSUE THREAD

**Issue by nmills3** [yt-dlp/yt-dlp#6493] opened 2023-03-09 22:12 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Provide a description that is worded well enough to be understood

Currently the --cookies-from-browser feature doesn't seem to be working with the hidive extractor. When trying to download premium content with cookies from the browser you get the premiumcontent error. When exporting the same cookies to a file and giving them via the --cookies option it works perfectly. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'chrome', '-vU', 'https://www.hidive.com/stream/reincarnated-as-a-sword/s01e011']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\nicho\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\nicho\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 3040 cookies from chrome
[debug] cookie version breakdown: {'v10': 3040, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[HiDive] Extracting URL: https://www.hidive.com/stream/reincarnated-as-a-sword/s01e011
[HiDive] reincarnated-as-a-sword/s01e011: Downloading JSON metadata
ERROR: [HiDive] reincarnated-as-a-sword/s01e011: HiDive said: PremiumContent
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\hidive.py", line 81, in _real_extract
```

**Comment by pukkandan** [comment] 2023-03-09 22:16
Try using `--username` instead

**Comment by nmills3** [comment] 2023-03-09 22:19
[HiDive] None: Downloading webpage
[HiDive] Logging in
ERROR: [HiDive] reincarnated-as-a-sword/s01e011: Unable to extract profile_id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by pukkandan** [comment] 2023-03-09 22:20
cc @chexxor since u added the profile selection code

**Comment by pukkandan** [comment] 2023-03-09 22:22
Actually, it looks like a tiny bug. @nmills3 Would you be able to test this patch?
```diff
diff --git a/yt_dlp/extractor/hidive.py b/yt_dlp/extractor/hidive.py
index 8a8749859..f5d05ff9f 100644
--- a/yt_dlp/extractor/hidive.py
+++ b/yt_dlp/extractor/hidive.py
@@ -47,7 +47,7 @@ def _perform_login(self, username, password):
         login_webpage = self._download_webpage(
             self._LOGIN_URL, None, 'Logging in', data=urlencode_postdata(data))
         # If the user has multiple profiles on their account, select one. For now pick the first profile.
-        profile_id = self._search_regex(r'<button [^>]+?data-profile-id="(\w+)"', login_webpage, 'profile_id')
+        profile_id = self._search_regex(r'<button [^>]+?data-profile-id="(\w+)"', login_webpage, 'profile_id', default=None)
         if profile_id is None:
             return  # If only one profile, Hidive auto-selects it
         profile_id_hash = self._search_regex(r'\<button [^>]+?data-hash="(\w+)"', login_webpage, 'profile_id_hash')
```

**Comment by nmills3** [comment] 2023-03-09 22:26
how do i test it? i've only even used the binaries to run yt-dlp before

**Comment by chexxor** [comment] 2023-03-10 03:21
@nmills3 This "hydive.py" file is an interpreted script, so you can update it in place. You just need to find that file on your file system and edit it to add that "default=None" part to that line.
I don't know how to locate that file on your filesystem though. If on linux,  you could use "which yt-dlp", or similar. Any ideas from anyone else?

**Comment by nmills3** [comment] 2023-03-10 11:56
I can confirm that that fix does make it so that doing --username and --password works. So i do have a way to download from hidive now so thanks for that. 

but that doesn't really solve the reason this issue was opened. The hidive extractor still seems to be having issues with the cookies from browser option.

**Comment by bashonly** [comment] 2023-03-10 21:30
> When exporting the same cookies to a file and giving them via the --cookies option it works perfectly

cannot confirm w/o account but this could possibly be caused by #5534

**Comment by chexxor** [comment] 2023-03-10 21:53
I've only used yt-dlp for Hidive. I tried the "cookies from browser" feature when I was making that patch for the Hidive extractor, but I couldn't get it to work.

@nmills3 have you successfully used "cookies from browser" with other extractors? Or did it work with the Hidive extractor in the past?

**Comment by pukkandan** [comment] 2023-03-10 23:44
> When exporting the same cookies to a file and giving them via the --cookies option it works perfectly

I did not notice this part! If this is true, then issue is definitely #5534. Closing as duplicate

**Closed by pukkandan** 2023-03-10 23:44 UTC
Labels: account-needed, site-enhancement

**Comment by nmills3** [comment] 2023-03-11 05:02
@chexxor i can confirm that other extractors ARE working with --cookies-from-browser i tested using crunchyroll and that grabbed the cookies from the browser and worked fine. So this issue with cookies from browser is specific to hidive for me.

I did also find that hidive or the hidive extractor is very picky with what cookie export tools work with it. When testing originally i found that the cookies exported by the chrome extension "Edit this cookie" did not work and the only one i did manage to get working cookies from was "get cookies.txt LOCALLY". i'm not sure if that's relevant but maybe that tool grabs a cookie that some other tools miss

**Comment by Tblue** [comment] 2023-05-27 21:12
I think the issue here is that HIDIVE uses session cookies, and those don't seem to be persisted to the Firefox `cookies.sqlite` file. Hence, `yt-dlp` won't be able to see those session cookies, and HIDIVE will think you're not logged in.

What worked for me was to combine the `--cookies` option (so that `yt-dlp` persists the session cookies), and the `--username` option:

```sh
# This first command will fail with the "PremiumContent" error, but it will store the session
# cookies in the cookie jar:
yt-dlp --cookies yt-dlp-cookies.txt --username jon.doe@example.com https://www.hidive.com/stream/xxxx

# Running the previous command once again will now succeed, presumably because it used some of 
# the session cookies in the cookie jar:
yt-dlp --cookies yt-dlp-cookies.txt --username jon.doe@example.com https://www.hidive.com/stream/xxxx
```

So it seems like the HIDIVE extractor would also need to be patched so that it makes an additional request to get the session cookies.

**Comment by kekkoudesu** [comment] 2023-08-23 11:51
Neither `--username` nor extracting the cookies and using those works anymore. It seems like Hidive is now prompting users with a challenge to prove they're human.

**Comment by kekkoudesu** [comment] 2023-08-24 03:56
Nevermind. Using `--username` with `--cookies` works.

**Comment by BraveSail** [comment] 2023-08-24 18:44
```
[debug] Command-line config: ['-v', '-R', 'infinite', '--force-overwrites', '--fragment-retries', 'infinite', '--no-mtime', '--proxy', 'http://127.0.0.1:1080', 'https://www.hidive.com/stream/chiikawa/s01e054', '-u', 'PRIVATE', '-p', 'PRIVATE', '-N', '16', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0', '--cookies', '/root/cookie-sentai.txt', '--embed-subs', '--convert-subs', 'ass', '--sub-langs', 'all', '--remux-video', 'mkv', '-o', '/root/bangumi/[GJ.Y] Chiikawa - 54 (Sentai .mkv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.5 (CPython aarch64 64bit) - Linux-5.10.0-21-arm64-aarch64-with-glibc2.36 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.36)
[debug] exe versions: ffmpeg N-109851-ge506ea3ce1-20230212 (setts), ffprobe N-108083-g06b98e396a-20220909
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {'all': 'http://127.0.0.1:1080'}
[debug] Loaded 1857 extractors
[HiDive] None: Downloading webpage
[HiDive] Logging in
[HiDive] Extracting URL: https://www.hidive.com/stream/chiikawa/s01e054
[HiDive] chiikawa/s01e054: Downloading JSON metadata
ERROR: [HiDive] chiikawa/s01e054: HiDive said: PremiumContent
  File "/root/dump_tools/yt-dlp-sentai/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/root/dump_tools/yt-dlp-sentai/yt_dlp/extractor/hidive.py", line 93, in _real_extract
    raise ExtractorError(
```

> It seems like Hidive is now prompting users with a challenge to prove they're human.

I think you are right, seems `-u -p` is broken now.

**Comment by Tblue** [comment] 2023-08-24 18:53
Dumping all cookies for `hidive.com` (and subdomains), and using the resulting cookie jar (`--cookies` option) still works for me. 

The important thing is to also include session cookies in the cookie jar.

**Comment by BraveSail** [comment] 2023-08-25 08:29
> Dumping all cookies
How did you dump cookies?

**Comment by kekkoudesu** [comment] 2023-08-25 08:46
> > Dumping all cookies
> 
> How did you dump cookies?

I personally used the [cookies.txt extension](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/) for Firefox.

**Comment by JAllius** [comment] 2023-08-25 15:11
Reading the cookies from file worked for me until 2 days ago, now it's the same problem as with `--cookies-from-browser`. Session cookies were also included:

```
[debug] Command-line config: ['https://www.hidive.com/stream/spy-classroom/s02e019', '-v', '-u', 'PRIVATE', '-p', 'PRIVATE', '--ignore-config', '-f', 'b[language=ja]/b', '--video-multistreams', '--audio-multistreams', '--write-subs', '--sub-lang', 'english-subs', '--sub-format', 'vtt', '--add-metadata', '--remux-video', 'mkv', '--merge-output-format', 'mkv', '--rm-cache-dir', '-o', '.\\temp\\hidive\\single\\%(title)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.20.172604 [7cccab79e] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-02-22-git-d5cc7acff1-full_build-www.gyan.dev (setts), ffprobe 2023-02-22-git-d5cc7acff1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
Removing cache dir C:\Users\User/.cache\yt-dlp ..
[HiDive] None: Downloading webpage
[HiDive] Logging in
[HiDive] Extracting URL: https://www.hidive.com/stream/spy-classroom/s02e019
[HiDive] spy-classroom/s02e019: Downloading JSON metadata
ERROR: [HiDive] spy-classroom/s02e019: HiDive said: PremiumContent
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\hidive.py", line 82, in _real_extract
```

**Comment by kekkoudesu** [comment] 2023-08-25 15:24
Can confirm the extractor no longer works with `--username` and newly-extracted cookies:

```
[debug] Command-line config: ['-N', '4', '--add-metadata', '--all-subs', '-f', '--cookies', '../cookies/Hidive/cookies.txt', '-o', '%(title)s.%(ext)s', '-v', 'https://www.hidive.com/stream/oshi-no-ko/s01e001', '-u', 'PRIVATE']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.4.11-zen2-1-zen-x86_64-with-glibc2.38 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[generic] Extracting URL: ../cookies/Hidive/cookies.txt
ERROR: [generic] None: '../cookies/Hidive/cookies.txt' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:../cookies/Hidive/cookies.txt" ) to search YouTube
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2403, in _real_extract
    raise ExtractorError(

[HiDive] None: Downloading webpage
[HiDive] Logging in
[HiDive] Extracting URL: https://www.hidive.com/stream/oshi-no-ko/s01e001
[HiDive] oshi-no-ko/s01e001: Downloading JSON metadata
ERROR: [HiDive] oshi-no-ko/s01e001: HiDive said: PremiumContent
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/hidive.py", line 82, in _real_extract
    raise ExtractorError(
```

**Comment by bashonly** [comment] 2023-08-25 15:26
what if you only pass cookies (no `-u` or `-p`)

**Comment by Tblue** [comment] 2023-08-25 15:36
@BraveSail:
 
> How did you dump cookies?

I wrote my own script because I don't trust the Firefox extensions that are available (call me paranoid): https://gist.github.com/Tblue/8c6ee7c29b683dcf3e5dad2ff1edc338

Usage:

1. Visit `hidive.com`, and make sure you're logged in.
1. Make sure Firefox is set to restore windows and tabs on start (otherwise, session cookies won't be persisted to disk).
2. Close Firefox.
3. Make sure the Python package `lz4` is installed: Either use the package manager of your OS (on Arch Linux, install package `python-lz4`), or create a virtualenv and install `lz4` using `pip`.
4. Run: `./dump-firefox-cookies.py ~/.mozilla/firefox/lgcihc77.default-1554305833516  cookies.txt -l '*.hidive.com'` (you of course need to specify the correct path to your Firefox profile)
5. Find cookies in file `cookies.txt`.

I just tried it, and it still works for me. I can download an episode from Hidive.

**Comment by BraveSail** [comment] 2023-08-25 18:14
> I just tried it, and it still works for me.

Thanks for your script, it works.

But I think it's a temporary fix since the expiration date of cookies, I dont know if yt-dlp can renew the cookie automatically, like crunchyroll, I need to renew the cookie by opening the browser manually. The final fix is using curl_cffi to bypass the CR's human verification then let yt-dlp login with username and password, but seems hidive doesn't use cloudflare.

**Comment by Tblue** [comment] 2023-08-25 19:09
A glance suggests they use ReCaptcha _and_ AWS WAF's "Intelligent threat integration": https://docs.aws.amazon.com/waf/latest/developerguide/waf-application-integration.html

**Comment by Tblue** [comment] 2023-08-25 20:04
Honestly, I don't think it's worthwhile trying to circumvent ReCaptcha and/or AWS WAF security features.

Even if you manage to do it (and it would certainly be interesting), it'll just turn into a game of cat and mouse. It's way easier (and more future-proof) to just grab the cookies, even if you have to open `hidive.com` in a browser from time to time.

**Comment by BraveSail** [comment] 2023-09-28 15:37
> But I think it's a temporary fix since the expiration date of cookies, I dont know if yt-dlp can renew the cookie automatically,

The cookie expired, seems the valid period is 1 month.
