### ISSUE TITLE
Could not download some video from tiktok

### ISSUE THREAD

**Issue by ks-zealot** [yt-dlp/yt-dlp#9457] opened 2024-03-15 10:12 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

Youtube dl could not download some video from tiktok
For example https://www.tiktok.com/@russk0e_kin0/video/7346145736842595590

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU https://www.tiktok.com/@russk0e_kin0/video/7346145736842595590
[debug] Command-line config: ['-vU', 'https://www.tiktok.com/@russk0e_kin0/video/7346145736842595590']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (zip)
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.1.0-11-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.9 30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0
[debug] Optional libraries: brotli-None, certifi-2023.05.07, requests-2.29.0, sqlite3-3.41.2, urllib3-1.26.16
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[TikTok] Extracting URL: https://www.tiktok.com/@russk0e_kin0/video/7346145736842595590
[TikTok] 7346145736842595590: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7346145736842595590: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7346145736842595590: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7346145736842595590: Downloading video feed
WARNING: [TikTok] 7346145736842595590: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); trying with webpage
[TikTok] 7346145736842595590: Downloading webpage
[debug] [TikTok] Found universal data for rehydration
ERROR: [TikTok] 7346145736842595590: Video not available, status code 10204; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/opt/tg_bots/telegram_video_convert_bot/./yt-dlp/yt_dlp/extractor/common.py", line 732, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tg_bots/telegram_video_convert_bot/./yt-dlp/yt_dlp/extractor/tiktok.py", line 735, in _real_extract
    raise ExtractorError(f'Video not available, status code {status}', video_id=video_id)
```

**Comment by keustii** [comment] 2024-03-15 14:01
update your package

**Comment by bashonly** [comment] 2024-03-15 14:27
`yt-dlp --update-to nightly`

see pinned issues

duplicate of #9441

**Closed by bashonly** 2024-03-15 14:27 UTC
Labels: duplicate, site-bug, site:tiktok
