### ISSUE TITLE
[iq.com] No video formats

### ISSUE THREAD

**Issue by ludo77** [yt-dlp/yt-dlp#4292] opened 2022-07-07 00:29 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

france

### Provide a description that is worded well enough to be understood

ERROR: [iq.com] slxk4ry5to: PhantomJS executable not found in PATH, download it from http://phantomjs.org

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.iq.com/play/hikaru-no-go-episode-1-slxk4ry5to?lang=en_us
[debug] Command-line config: ['-vU', 'https://www.iq.com/play/hikaru-no-go-episode-1-slxk4ry5to?lang=en_us']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c41e] (zip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-121-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [iq.com] Extracting URL: https://www.iq.com/play/hikaru-no-go-episode-1-slxk4ry5to?lang=en_us
[iq.com] slxk4ry5to: Downloading webpage
[debug] Loading iq.player_js from cache
ERROR: [iq.com] slxk4ry5to: PhantomJS executable not found in PATH, download it from http://phantomjs.org
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/extractor/iqiyi.py", line 591, in _real_extract
    dash_paths = self._parse_json(PhantomJSwrapper(self).get(
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/extractor/openload.py", line 107, in __init__
    raise ExtractorError('PhantomJS executable not found in PATH, '

I don't find similar issue
thanks
```

**Comment by pukkandan** [comment] 2022-07-07 04:32
Did you read the error message?

> ERROR: [iq.com] slxk4ry5to: PhantomJS executable not found in PATH, download it from http://phantomjs.org/

**Comment by ludo77** [comment] 2022-07-08 04:27
I downloaded phantomjs, it worked for a while.
But this time, I have another error:
`[debug] Command-line config: ['--write-subs', 'en', '-vU', 'http://www.iq.com/play/hikaru-no-go-episode-16-mx40vokhn8?lang=en_us']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c41e] (zip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-121-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [generic] Extracting URL: en
ERROR: [generic] 'en' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:en" ) to search YouTube
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2792, in _real_extract
    raise ExtractorError(

[debug] [iq.com] Extracting URL: http://www.iq.com/play/hikaru-no-go-episode-16-mx40vokhn8?lang=en_us
[iq.com] mx40vokhn8: Downloading webpage
[debug] Loading iq.player_js from cache
[debug] Loading iq.player_js from cache
[iq.com] mx40vokhn8: Executing signature code
[iq.com] mx40vokhn8: Downloading initial video format info
ERROR: [iq.com] mx40vokhn8: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1420, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1504, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1561, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2450, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/ludo77/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 993, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [iq.com] mx40vokhn8: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
`
I don't see where the error comes from

**Comment by gamer191** [comment] 2022-07-10 15:29
On a side note, `--write-subs en` is not a valid option. You're looking for `--write-subs --sub-langs en`

**Comment by bashonly** [comment] 2023-06-11 16:38
Duplicate of #2813

See https://github.com/yt-dlp/yt-dlp/issues/5702#issuecomment-1384245060 for explanation

**Closed by bashonly** 2023-06-11 16:38 UTC
Labels: site-bug, triage
