### ISSUE TITLE
Getting HTTP Error 403: Forbidden at Yandex Zen

### ISSUE THREAD

**Issue by stackhanovets** [yt-dlp/yt-dlp#3363] opened 2022-04-09 03:57 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Description

Hi everyone, 
I never tried to use this tool to get video from Yandex Zen and cannot say that I'm pretty experienced with this tool in general. 
The point is the video content, I really love it. 
Please note, I've fixed this issue by myself (see below), yet a system approach is still required, I guess. 
Logs attached. 

# Bug:

```
[debug] Command-line config: ['--verbose', '-f', 'bestvideo+bestaudio/best', '-o', 'D:\\Videos\\youtube-dl\\%(title)s__%(id)s.%(ext)s', 'https://zen.yandex.ru/video/watch/624fb2a5ecbac6189480a429']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, err utf-8, pref cp1251
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106539-g49526852c3-20220408 (setts), ffprobe N-106539-g49526852c3-20220408
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [ZenYandex] Extracting URL: https://zen.yandex.ru/video/watch/624fb2a5ecbac6189480a429
[ZenYandex] 624fb2a5ecbac6189480a429: Downloading webpage
ERROR: [ZenYandex] 624fb2a5ecbac6189480a429: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\yandexvideo.py", line 238, in _real_extract
  File "yt_dlp\extractor\common.py", line 932, in _download_webpage
  File "yt_dlp\extractor\common.py", line 800, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 785, in _request_webpage

  File "yt_dlp\extractor\common.py", line 767, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3601, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

# Fix:

I used DevTools Inspector to jump into the frame code:
```
;!function(){function main(e){var n=window;var a=n&&n.YandexZen&&n.YandexZen.VideoPlayerBundle;var r=n&&n.YandexZen&&n.YandexZen.loadVideoPlayerScripts;var i=n&&n.YandexZen&&n.YandexZen.inlineManager;var d=i&&i.getModule("inlineStatLogger");if(!a||!d){return}if(r){r()}a.videoPlayersManager.inlineStartPlayer(e,d.playerStatLogger)};main({"playerConfig":{"heartbeatTimes":[4,6,9,13,17,24,28,33,40,46,51,56,61,69,79,90,100,110,125,140,160,180,210,240,270,300,330,360,390,420,450,480,510,540,570,600,630,660,690,720,750,780,810,840,870,900,930,960,990,1020,1050,1080,1110,1140,1170,1200,1230,1260,1290,1320,1350,1380,1410,1440,1470,1500,1530,1560,1590,1620,1650,1680,1710,1740,1770,1800,1860,1920,1980,2040,2100,2160,2220,2280,2340,2400,2460,2520,2580,2640,2700,2760,2820,2880,2940,3000,3060,3120,3180,3240,3300,3360,3420,3480,3540,3600],"isMuted":true,"isAutoplay":true,"placeName":"video-modal","frameFit":"contain","hackPreload":false,"maxBufferLength":7,"restorePlaybackProgress":false,"isPreloadOptimizationEnabled":true,"apiName":"sandbox","isVideoSubtitlesForceEnabled":false,"isNativeAdControlsHidden":false,"isMovePlayerCheckExists":false,"autoplayMode":"player"},"isDeferredAutoplay":false,"videoSource":{"adConfig":{"partnerId":981611,"category":1016,"hasPreroll":false,"skipAllAdPods":false},"streams":[{"url":"https://strm.yandex.ru/vod/zen-vod/vod-content/39257e7220ffc12b70a51f790ef0f49b/8501de3c-1b6a88bc-caac9aa0-9d10c08d/kaltura/desc_b239d9865fbf43f0f4b4dec1da97123e/1998637068528493755/ysign1=d9f36044a2eb300bd106f54f7f3a761fd60b70fd24bce8bcff5074464952f6d8,abcID=967,from=zen,pfx,sfx,ts=625e2a60/manifest.mpd?testid=559152&vsid=sckd6k5flapiqrl9uvaewmuqozoz5180e6kyqvvjjvh3xZENx0000x1649474400"},{"url":"https://strm.yandex.ru/vod/zen-vod/vod-content/39257e7220ffc12b70a51f790ef0f49b/8501de3c-1b6a88bc-caac9aa0-9d10c08d/kaltura/desc_b239d9865fbf43f0f4b4dec1da97123e/1998637068528493755/ysign1=bbb5a3e180285ea2fdc4457df181330a21fec7f7a708263c83b9f0be801f1b8e,abcID=967,from=zen,pfx,sfx,ts=625e2a60/master.m3u8?testid=559152&vsid=sckd6k5flapiqrl9uvaewmuqozoz5180e6kyqvvjjvh3xZENx0000x1649474400"}],"withCredentials":false,"additionalParams":{"video-content-id":"vu6SRGNOVvBs","from":"zen","from_block":"video_desktop","strongest_id":"","item_id":"-6962108456166511667","stream_block":"video_related:video_page","rid":"4276276551.96.1649474400567.21151","ppi":"video_desktop:yandex:video_desktop"},"videoInfo":{"videoContentId":"vu6SRGNOVvBs"}},"playerElementId":"preloaded-player-id","isForceMutedWhenInline":false})}();;;!function(){function main(){var e=window;var n=e&&e.YandexZen&&e.YandexZen.VideoPlayerBundle;if(!n){return}var r=n.videoPlayersManager.getPlayerRUM();r.inlineSendFirstScreenMark("render")};main({})}();;;!function(){function main(){var n=window;var e=n&&n.YandexZen&&n.YandexZen.VideoPlayerBundle;if(!e){return}e.inlinePlayerSkin.subscribe()};main({})}();
```
And this line seemed to be working:
```
[debug] Command-line config: ['--verbose', '-f', 'bestvideo+bestaudio/best', '-o', 'D:\\Videos\\youtube-dl\\%(title)s__%(id)s.%(ext)s', 'https://strm.yandex.ru/vod/zen-vod/vod-content/39257e7220ffc12b70a51f790ef0f49b/8501de3c-1b6a88bc-caac9aa0-9d10c08d/kaltura/desc_b239d9865fbf43f0f4b4dec1da97123e/1998637068528493755/ysign1=d9f36044a2eb300bd106f54f7f3a761fd60b70fd24bce8bcff5074464952f6d8,abcID=967,from=zen,pfx,sfx,ts=625e2a60/manifest.mpd?testid=559152&vsid=sckd6k5flapiqrl9uvaewmuqozoz5180e6kyqvvjjvh3xZENx0000x1649474400']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, err utf-8, pref cp1251
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106539-g49526852c3-20220408 (setts), ffprobe N-106539-g49526852c3-20220408
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://strm.yandex.ru/vod/zen-vod/vod-content/39257e7220ffc12b70a51f790ef0f49b/8501de3c-1b6a88bc-caac9aa0-9d10c08d/kaltura/desc_b239d9865fbf43f0f4b4dec1da97123e/1998637068528493755/ysign1=d9f36044a2eb300bd106f54f7f3a761fd60b70fd24bce8bcff5074464952f6d8,abcID=967,from=zen,pfx,sfx,ts=625e2a60/manifest.mpd?testid=559152&vsid=sckd6k5flapiqrl9uvaewmuqozoz5180e6kyqvvjjvh3xZENx0000x1649474400
[generic] manifest: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
[debug] Identified a DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] manifest: Downloading 1 format(s): vid7+aid4
[debug] Invoking downloader on "https://strm.yandex.ru/vod/zen-vod/vod-content/39257e7220ffc12b70a51f790ef0f49b/8501de3c-1b6a88bc-caac9aa0-9d10c08d/kaltura/desc_b239d9865fbf43f0f4b4dec1da97123e/1998637068528493755/ysign1=d9f36044a2eb300bd106f54f7f3a761fd60b70fd24bce8bcff5074464952f6d8,abcID=967,from=zen,pfx,sfx,ts=625e2a60/manifest.mpd?testid=559152&vsid=sckd6k5flapiqrl9uvaewmuqozoz5180e6kyqvvjjvh3xZENx0000x1649474400"
[dashsegments] Total fragments: 1023
[download] Destination: D:\Videos\youtube-dl\manifest__manifest.fvid7.mp4
[debug] File locking is not supported on this platform. Proceeding without locking
[download] 100% of 2.36GiB in 05:10
[debug] Invoking downloader on "https://strm.yandex.ru/vod/zen-vod/vod-content/39257e7220ffc12b70a51f790ef0f49b/8501de3c-1b6a88bc-caac9aa0-9d10c08d/kaltura/desc_b239d9865fbf43f0f4b4dec1da97123e/1998637068528493755/ysign1=d9f36044a2eb300bd106f54f7f3a761fd60b70fd24bce8bcff5074464952f6d8,abcID=967,from=zen,pfx,sfx,ts=625e2a60/manifest.mpd?testid=559152&vsid=sckd6k5flapiqrl9uvaewmuqozoz5180e6kyqvvjjvh3xZENx0000x1649474400"
[dashsegments] Total fragments: 1023
[download] Destination: D:\Videos\youtube-dl\manifest__manifest.faid4.m4a
[download] 100% of 67.21MiB in 02:12
[Merger] Merging formats into "D:\Videos\youtube-dl\manifest__manifest.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:D:\Videos\youtube-dl\manifest__manifest.fvid7.mp4" -i "file:D:\Videos\youtube-dl\manifest__manifest.faid4.m4a" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:D:\Videos\youtube-dl\manifest__manifest.temp.mp4"
Deleting original file D:\Videos\youtube-dl\manifest__manifest.fvid7.mp4 (pass -k to keep)
Deleting original file D:\Videos\youtube-dl\manifest__manifest.faid4.m4a (pass -k to keep)
```

### Verbose log

```shell
The resulting file is slightly more than 2.5Gb, I have not performed a detailed check, but the size looks OK.
```

**Comment by stackhanovets** [comment] 2022-04-09 05:28
I finished to enjoy, I mean, examine it. The file integrity is OK.

**Comment by sergeevabc** [comment] 2022-04-15 07:32
version 2022.04.15.19419

$ yt-dlp https://zen.yandex.ru/video/watch/61afc4e1781cc81fb6c6321f
ERROR: [ZenYandex] 61afc4e1781cc81fb6c6321f: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>);  please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by pukkandan** [comment] 2022-04-15 18:03
This is weird. Using Python 3.10 works! No idea why

```diff
 [debug] Command-line config: ['-vs', '--ignore-config', 'https://zen.yandex.ru/video/watch/624fb2a5ecbac6189480a429']
 [debug] Encodings: locale cp65001, fs utf-8, out utf-8, err utf-8, pref cp65001
 [debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
-[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
+[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
 [debug] Checking exe version: ffmpeg -bsfs
 [debug] Checking exe version: ffprobe -bsfs
 [debug] exe versions: ffmpeg N-105465-gbedb4bac1c-20220206 (fdk,setts), ffprobe N-105465-gbedb4bac1c-20220206, phantomjs 2.1.1
 [debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
 [debug] Proxy map: {}
 [debug] [ZenYandex] Extracting URL: https://zen.yandex.ru/video/watch/624fb2a5ecbac6189480a429
 [ZenYandex] 624fb2a5ecbac6189480a429: Downloading webpage
-ERROR: [ZenYandex] 624fb2a5ecbac6189480a429: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
-  File "yt_dlp\extractor\common.py", line 641, in extract
-    ie_result = self._real_extract(url)
-  File "yt_dlp\extractor\yandexvideo.py", line 238, in _real_extract
-    webpage = self._download_webpage(url, id)
-  File "yt_dlp\extractor\common.py", line 932, in _download_webpage
-    res = self._download_webpage_handle(
-  File "yt_dlp\extractor\common.py", line 800, in _download_webpage_handle
-    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
-  File "yt_dlp\extractor\common.py", line 785, in _request_webpage
-    raise ExtractorError(errmsg, cause=err)
-
-  File "yt_dlp\extractor\common.py", line 767, in _request_webpage
-    return self._downloader.urlopen(url_or_request)
-  File "yt_dlp\YoutubeDL.py", line 3601, in urlopen
-    return self._opener.open(req, timeout=self._socket_timeout)
-  File "urllib\request.py", line 531, in open
-  File "urllib\request.py", line 640, in http_response
-  File "urllib\request.py", line 569, in error
-  File "urllib\request.py", line 502, in _call_chain
-  File "urllib\request.py", line 649, in http_error_default
-urllib.error.HTTPError: HTTP Error 403: Forbidden
+[ZenYandex] 624fb2a5ecbac6189480a429: Downloading MPD manifest
+[ZenYandex] 624fb2a5ecbac6189480a429: Downloading m3u8 information
+[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
+[debug] Default format spec: bestvideo*+bestaudio/best
+[info] 624fb2a5ecbac6189480a429: Downloading 1 format(s): 4281-5
```

**Comment by coletdjnz** [comment] 2022-05-28 03:58
I think this is the same as #3878 

i.e. fixed by https://github.com/yt-dlp/yt-dlp/commit/2c6dcb65fb612fc5bc5c61937bf438d3c473d8d0

https://github.com/coletdjnz/yt-dlp-dev/actions/runs/2399861703

**Comment by stackhanovets** [comment] 2022-05-28 06:45
Got it, let's wait till the next release.

```
[debug] Command-line config: ['--add-metadata', '--all-subs', '--convert-subs=ass', '--embed-subs', '--format', 'bestvideo+bestaudio/best', '--merge-output-format', 'mkv', '--output', 'D:\\Videos\\youtube-dl\\%(title)s__%(id)s.%(ext)s', '--verbose', 'https://zen.yandex.ru/video/watch/624fb2a5ecbac6189480a429']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg N-107013-g93b31dae1d-20220527 (setts), ffprobe N-107013-g93b31dae1d-20220527
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [ZenYandex] Extracting URL: https://zen.yandex.ru/video/watch/624fb2a5ecbac6189480a429
[ZenYandex] 624fb2a5ecbac6189480a429: Downloading webpage
ERROR: [ZenYandex] 624fb2a5ecbac6189480a429: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\yandexvideo.py", line 235, in _real_extract
  File "yt_dlp\extractor\common.py", line 933, in _download_webpage
  File "yt_dlp\extractor\common.py", line 801, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 786, in _request_webpage

  File "yt_dlp\extractor\common.py", line 768, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3596, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Closed** 2022-05-28 08:52 UTC
Labels: site-bug
