### ISSUE TITLE
No such dash external downloader "native"

### ISSUE THREAD

**Issue by spvkgn** [yt-dlp/yt-dlp#4166] opened 2022-06-24 14:00 UTC
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

This works with previous release, but with 2022.06.22.1 I got this error.

### Verbose log

```shell
$ yt-dlp -vU --no-config --downloader "dash,m3u8:native" 'https://www.youtube.com/watch?v=TZbJMUuzmls'
[debug] Command-line config: ['-vU', '--no-config', '--downloader', 'dash,m3u8:native', 'https://www.youtube.com/watch?v=TZbJMUuzmls']

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: No such dash external downloader "native"
```

**Comment by Lesmiscore** [comment] 2022-06-24 14:15
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/4157

**Closed** 2022-06-24 15:46 UTC
Labels: bug, triage
