### ISSUE TITLE
[youtube] change of default player clients to ios,tv breaks -f b and getting m3u8 URL with both video and audio in a single stream

### ISSUE THREAD

**Issue by jester-xbmc** [yt-dlp/yt-dlp#10660] opened 2024-08-04 19:13 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Latest release yt-dlp 2024.08.01 and specifically commit https://github.com/yt-dlp/yt-dlp/commit/efb42763dec23ccf6a2e3bac3afbfefce8efd012

This breaks getting youtube m3u8 live-stream URLs for usage with VLC/m3u8 players (think apple tv and not wanting to use the crappy youtube app)

It used to be a simple as yt-dlp -g -f b -v https://www.youtube.com/url > stream.m3u8
but with the above change -f b doesn't work any longer and removing -f b or using -f "bv+ba" one gets a m3u8 file with 2 m3u8 urls (one for video and one for audio) which in many m3u8 players are seen as 2 entries and therefor wont work.

possible fix is yt-dlp -g -v -f b --extractor-args "youtube:player-client=ios,web" https://www.youtube.com/url > stream.m3u8

other solutions welcome given the multiple WARNING: [youtube] Webpage contains broken formats (poToken experiment detected) with the above "fix"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-g', '-v', '-f', 'b', 'https://www.youtube.com/watch?v=FkP_Qxw5xns']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.01 from yt-dlp/yt-dlp [ffd7781d6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n7.0.1-6-gf0b747ef1a-20240614 (setts), ffprobe n7.0.1-6-gf0b747ef1a-20240614
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=FkP_Qxw5xns
[youtube] FkP_Qxw5xns: Downloading webpage
[youtube] FkP_Qxw5xns: Downloading ios player API JSON
[youtube] FkP_Qxw5xns: Downloading tv player API JSON
[youtube] FkP_Qxw5xns: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] FkP_Qxw5xns: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2977, in process_video_result
yt_dlp.utils.ExtractorError: [youtube] FkP_Qxw5xns: Requested format is not available. Use --list-formats for a list of available formats


and now with "fix"


[debug] Command-line config: ['-g', '-v', '-f', 'b', '--extractor-args', 'youtube:player-client=ios,web', 'https://www.youtube.com/watch?v=FkP_Qxw5xns']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.01 from yt-dlp/yt-dlp [ffd7781d6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n7.0.1-6-gf0b747ef1a-20240614 (setts), ffprobe n7.0.1-6-gf0b747ef1a-20240614
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=FkP_Qxw5xns
[youtube] FkP_Qxw5xns: Downloading webpage
[youtube] FkP_Qxw5xns: Downloading ios player API JSON
[youtube] FkP_Qxw5xns: Downloading m3u8 information
[youtube] FkP_Qxw5xns: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] FkP_Qxw5xns: Downloading 1 format(s): 300
https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1722819499/ei/S8-vZtaUMc-06dsP5IzAiAI/ip/188.213.89.160/id/FkP_Qxw5xns.1/itag/300/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D298/rqh/1/hdlc/1/hls_chunk_host/rr4---sn-5hnekn7l.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/playlist_duration/30/manifest_duration/30/spc/NO7bAX9bm24r4uuHxsLbVPKjTfLkpHW3xP_e_fOSGLfR5FkBR22doGwU3Z5cHk8/vprv/1/playlist_type/DVR/initcwndbps/2953750/mh/jv/mm/44/mn/sn-5hnekn7l/ms/lva/mv/m/mvi/4/pl/21/dover/11/pacing/0/keepalive/yes/mt/1722797562/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,rqh,hdlc,xpc,playlist_duration,manifest_duration,spc,vprv,playlist_type/sig/AJfQdSswRgIhAJRKYA7Q667t6xD-oqlUk6GJ0oiUZSwLor8c0He10poLAiEAqwatEqcpZJa9f-Lt3LBndqdjyfkLXC2wj0vWn7WU0kI%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AGtxev0wRQIhANru6o4EuJTI0zzmSK0zqiKakHBnjVHKuvemlnvA05vtAiBzNGdY7pIdc1_2BWGtWjiKDOzxiM_8c5UiBmZ_exK5ow%3D%3D/playlist/index.m3u8
```

**Comment by seproDev** [comment] 2024-08-04 19:23
The problem is that the `web` client will probably soon stop working entirely, as YouTube now requires browser integrity checks.
If you do need these pre-merged formats, I would either use the `web_creator` or `mediaconnect` client.
Note that both could also be subject to integrity checks soon, and `mediaconnect` tops out at 480p for some livestreams.
 
We will consider changing the default for livestreams to `ios,web_creator`

**Comment by jester-xbmc** [comment] 2024-08-04 19:26
I was afraid of that, but understood, thanks for the insight.

**Closed** 2024-08-05 23:26 UTC
Labels: site-bug
