### ISSUE TITLE
--extract-audio progress

### ISSUE THREAD

**Issue by bw4518** [yt-dlp/yt-dlp#2826] opened 2022-02-18 22:17 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I will just reference the issue started on youtube-dl [here](https://github.com/ytdl-org/youtube-dl/issues/288).

The question basically is, could we get an encoding progress for extract-audio in yt-dlp?

**Comment by pukkandan** [comment] 2022-02-19 09:49
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1720

**Closed by pukkandan** 2022-02-19 09:49 UTC
Labels: enhancement
