### ISSUE TITLE
Unicode "|" character is being replaced in filenames on filesystems that support it 

### ISSUE THREAD

**Issue by Gestas** [yt-dlp/yt-dlp#4547] opened 2022-08-03 18:41 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Per the documentation ```--no-restrict-filenames``` should support Unicode characters. However the `|` character, which is valid Unicode is being replaced with `_` in file paths -

## Actual behavior - 

```
$ yt-dlp -vU \
--get-filename \
-o "/%(uploader)s/S01E%(video_autonumber)02d - %(title)s/S01E%(video_autonumber)02d - %(title)s [%(id)s].%(ext)s" \
l4gGWufoIYI

[debug] Command-line config: ['-vU', '--get-filename', '-o', '/%(uploader)s/S01E%(video_autonumber)02d - %(title)s/S01E%(video_autonumber)02d - %(title)s [%(id)s].%(ext)s', 'l4gGWufoIYI']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.10.4 (CPython 64bit) - Linux-5.17.15-76051715-generic-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: brotli-1.0.9, certifi-2020.06.20, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [youtube] Extracting URL: l4gGWufoIYI
[youtube] l4gGWufoIYI: Downloading webpage
[youtube] l4gGWufoIYI: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] l4gGWufoIYI: Downloading 1 format(s): 248+251

/Action BOX/S01E01 - Homemade Plastic Injection Machine _ DIY/S01E01 - Homemade Plastic Injection Machine _ DIY [l4gGWufoIYI].webm
```

## Expected behavior - 
The video title on Youtube is "Homemade Plastic Injection Machine | DIY" so the expected file path is -
```
/Action BOX/S01E01 - Homemade Plastic Injection Machine | DIY/S01E01 - Homemade Plastic Injection Machine | DIY [l4gGWufoIYI].webm
```

## Notes - 
I'm running Ubuntu 21 with a `ext4` filesystem, `|` is a supported character in filenames - 
```
$ touch 'this is a pipe | in a filename'
$ ls
'this is a pipe | in a filename'
```
To the best of my knowledge NTFS (Windows) is the only filesystem that doesn't support `|` in a path. `yt-dlp` already handles filenames differently when running on Windows via the default `--no-windows-filenames`. Removing the `|` restriction for non-NTFS shouldn't cause an issue. 

## Extras - 
While this ticket is specific to the '|' character NTFS is the only filesystem that doesn't support all Unicode characters - 
```
$ touch 'this is a happy filename 😀'
$ ls
'this is a happy filename 😀'
```
It may be worth exploring supporting the entire Unicode character set in `yt-dlp`.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--get-filename', '-o', '/%(uploader)s/S01E%(video_autonumber)02d - %(title)s/S01E%(video_autonumber)02d - %(title)s [%(id)s].%(ext)s', 'l4gGWufoIYI']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.10.4 (CPython 64bit) - Linux-5.17.15-76051715-generic-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: brotli-1.0.9, certifi-2020.06.20, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [youtube] Extracting URL: l4gGWufoIYI
[youtube] l4gGWufoIYI: Downloading webpage
[youtube] l4gGWufoIYI: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] l4gGWufoIYI: Downloading 1 format(s): 248+251

/Action BOX/S01E01 - Homemade Plastic Injection Machine _ DIY/S01E01 - Homemade Plastic Injection Machine _ DIY [l4gGWufoIYI].webm
```

**Comment by pukkandan** [comment] 2022-08-03 23:02
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3385

**Comment by pukkandan** [comment] 2022-08-03 23:04
Actually, this issue is better reported. So I'll close that one instead

**Comment by light-and-ray** [comment] 2022-11-11 18:25
Maybe you can add simple flag `--ext4-filename-sanitization`, if you have problems with filename restrictions deduction. In this fs you need to replace only `/` symbol

**Comment by chungy** [comment] 2022-12-25 21:54
Documentation suggests to use `--no-windows-filenames` but it still tries to replace characters like `*`, `?`, `|` -- all of them are perfectly valid file name characters in Unix.

(Maybe `yt-dlp` could default to `--windows-filenames` if the filesystem is one of msdos/vfat/exfat, otherwise it should be all fine.)

**Comment by Jason5Lee** [comment] 2023-02-11 14:45
I got a reversed issue. I have `--windows-filenames` arg but it does not replace `|`.

**Comment by pukkandan** [comment] 2023-03-11 21:39
Can someone make a summary of which popular FS/OS blocks which characters? We may be able to get away with using `--windows-filenames` to deal with this, but I need to be sure it won't cause issues

**Comment by Lesmiscore** [comment] 2023-03-12 07:03
https://stackoverflow.com/a/31976060

**Comment by light-and-ray** [comment] 2023-03-12 07:46
Here:
https://en.m.wikipedia.org/wiki/Comparison_of_file_systems

Limits -> 3rd column

вс, 12 мар. 2023 г., 01:39 pukkandan ***@***.***>:

**Comment by mikkovedru** [comment] 2023-03-26 15:11
In Linux out of all the characters, there are only `/` (forward slash) and 0 (Null) forbidden. 

I suggest checking the OS environment and **automatically** applying `--windows-filenames` in Windows and `--no-windows-filenames` (perhaps should be divided into `--linux-filenames` and `--macos-filenames`) in Linux.

**Comment by mikkovedru** [comment] 2023-05-20 07:44
Unlike I wrote in my bug report #6480 , the issue does not only concern Cyrillic/UTF-16 names, but ordinary Latin ones as well.

Example of the video: https://www.youtube.com/watch?v=Xfl6ZL5FK54
Run: `yt-dlp -o '%(title)s_%(fulltitle)s.%(ext)s' -f "bv*[height=480]+ba" --merge-output-format mkv --progress --concurrent-fragments 10 -R infinite -vU https://www.youtube.com/watch\?v\=Xfl6ZL5FK54`

Any chances of fixing the issue, @pukkandan ?

**Comment by dirkf** [comment] 2023-05-21 19:24
The character set support in the destination file system is a factor, as well as the OS.

Then one could consider whether some weird character might be censored even if the FS allows it, so as to make the filename acceptable in other common FSs (to which the file might be copied).

**Comment by mikkovedru** [comment] 2023-05-21 23:50
What needs to be done is to substitute (or to stop substituting, if that's what is happening now) a certain set of characters. There aren't that many of them. **And not all of them even have anything to do with the OS filesystem limitations**.
- Should use `|` instead of `｜`.
- Should use `:` instead of `：`.
- Should use `?` instead of `？`.
- Should use `*` instead of `＊`.
- Should use `"` instead of `＂`.

**Comment by mikkovedru** [comment] 2023-06-13 01:47
In case someone wonders how to rename the already saved files, use the Linux shell command is `rename 's/｜/|/' name-of-the-file.mkv` (fixes 1 out of 5 cases named in my previous comment just above)

In order to rename all of the files in the current directory recursively, one can apply the following commands one after another:
```
find . -type f -name '*' -exec rename 's/｜/|/' {} +
find . -type f -name '*' -exec rename 's/：/:/' {} +
find . -type f -name '*' -exec rename 's/？/?/' {} +
find . -type f -name '*' -exec rename 's/＊/*/' {} +
find . -type f -name '*' -exec rename 's/＂/"/' {} +
```

**Comment by pukkandan** [comment] 2023-07-03 09:14
An implementation where explicitly passing `--no-windows-filenames` prevents this sanitization is welcome

**Comment by catthou** [comment] 2023-09-08 21:29
Looking forward to any progress on this issue!

**Comment by Krinkle** [comment] 2023-11-18 23:44
As of writing, the `--no-windows-filenames --no-restrict-filenames` options still do not work. yt-dlp still replaces the double quotes in titles with the Unicode "Fullwidth Quotation Mark" (also known as char code `65282` or `&#xff02;`).

I did find a **workaround** that works today, by setting `--compat-options filename-sanitization`.

This will replace double quotes with regular single quotes instead. Ideally they'd be left alone, but at least these are more reasonable to work with.

**Comment by NintendoManiac64** [comment] 2024-02-29 23:06
I just recently realized that, while a standard ASCII `/` is replaced with a unicode slash that looks darned-near identical, a standard ASCII `:` is replaced by the substantially wider-spaced full-width colon `：` rather than a colon that's similarly-sized to the standard ASCII colon, such as the modifier letter colon `꞉` (U+A789):
- https://www.fileformat.info/info/unicode/char/a789/index.htm

**Comment by pukkandan** [comment] 2024-03-01 07:45
@NintendoManiac64 Off topic... It's just what seemed reasonable to me at the time. It is possible there are better alternatives, but any benefit gained by changing this is not worth breaking compatibility now. You can always do custom replacements with `--replace-in-metadata`

**Comment by NintendoManiac64** [comment] 2024-03-06 21:30
> @NintendoManiac64 Off topic

Then what is the appropriate issue for unicode character replacement of ascii characters? I specifically put my comment here because, when doing a searching for the relevant issue, I thought that this is what this issue was discussing (but apparently not?).

**Comment by pukkandan** [comment] 2024-04-01 15:57
> Then what is the appropriate issue for reporting and/or discussing unicode character replacement of ascii characters?

You could open a new issue. But,



> It is possible there are better alternatives, but any benefit gained by changing this is not worth breaking compatibility now

**Comment by NintendoManiac64** [comment] 2024-04-01 17:49
> It is possible there are better alternatives, but any benefit gained by changing this is not worth breaking compatibility now

I completely agree, but my lack of software dev skills means I'm at a loss as for what compatibility there even is? Like, does the file name matter for programs that directly hook the likes of yt-dlp to steam videos from YouTube? I only ask because I only ever use yt-dlp directly via batch scripts to download a given audio or video format...

**Comment by mwoehlke** [comment] 2024-07-01 18:23
So, this drives me nuts also. Here's a crazy idea... don't sanitize the file name at all (except `/`) and *try to create it*. If the OS throws an error, apply some sanitization and try again. Rinse and repeat until success, each time with progressively more restrictions. (Also, adding `./` to the name should avoid pitfalls with certain prefixes having special meaning, though those are so unlikely to occur "in the wild" that sanitizing them always is probably fine.)

Honestly, since I don't know how to determine the FS type from Python (and Linux can mount FSs that have restrictions), I don't think there's a way to reliably know whether a filename is valid *except* to just try it.

That said, #9591 (i.e. "trust the user and they can keep the pieces if it breaks") would be an improvement!

**Closed** 2024-12-23 10:27 UTC
Labels: enhancement
