### ISSUE TITLE
[YouTube] 404 while downloading m3u8, if format is `worstvideo` with limit

### ISSUE THREAD

**Issue by SunSerega** [yt-dlp/yt-dlp#7809] opened 2023-08-11 09:41 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Ukraine

### Provide a description that is worded well enough to be understood

In my use case, I have multiple format options, and the one selected is `worstvideo[height>=1080]+bestaudio`, but I found that `worstvideo[height=1080]` is enough to reproduce.
- Needs to be `worstvideo`. Works fine with `bestvideo`
- Needs to be limited further (I'm using height in this case)

This is far from the first video that gives this error. But usually, this problem fixes itself after a few hours (it was 14 hours at most, usually <2 hours) after it has been uploaded.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
> yt-dlp.exe -vU -f "worstvideo[height=1080]" "https://www.youtube.com/watch?v=RXgFZCPvXdk"
[debug] Command-line config: ['-vU', '-f', 'worstvideo[height=1080]', 'https://www.youtube.com/watch?v=RXgFZCPvXdk']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.04.221808 [db7b054a6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-07-19-git-efa6cec759-full_build-www.gyan.dev (setts), ffprobe 2023-07-19-git-efa6cec759-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1860 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.08.04.221808, Current version: nightly@2023.08.04.221808
Current Build Hash: c1578ba3139f74f3cf72bb5decc88c88deb52c51573047f32888f65547901a6a
yt-dlp is up to date (nightly@2023.08.04.221808)
[youtube] Extracting URL: https://www.youtube.com/watch?v=RXgFZCPvXdk
[youtube] RXgFZCPvXdk: Downloading webpage
[youtube] RXgFZCPvXdk: Downloading ios player API JSON
[youtube] RXgFZCPvXdk: Downloading android player API JSON
[debug] Loading youtube-nsig.3cd2d050 from cache
[debug] [youtube] Decrypted nsig a5vFpNRDQ3SCJ_eWn3U => tOElBEk-s2cTKQ
[youtube] RXgFZCPvXdk: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] RXgFZCPvXdk: Downloading 1 format(s): 312
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1691767994/ei/WgDWZI7lI8rL7QTkoKPgCA/ip/2a09:bac5:593b:2dc::49:1d0/id/4578056423ef5dd9/itag/312/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/sgovp/clen%3D468348324%3Bdur%3D782.733%3Bgir%3Dyes%3Bitag%3D299%3Blmt%3D1691741707120662/hls_chunk_host/rr7---sn-bpb5oxu-3c2d.googlevideo.com/mh/Et/mm/31,29/mn/sn-bpb5oxu-3c2d,sn-3c27sne7/ms/au,rdu/mv/m/mvi/7/pl/43/initcwndbps/376250/vprv/1/playlist_type/DVR/dover/13/txp/3319224/mt/1691745921/fvip/18/short_key/1/keepalive/yes/fexp/24007246/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,sgovp,vprv,playlist_type/sig/AOq0QJ8wRQIgBp5jOMR-1pBBP-AT4sQZkY4dqgYBZ1-C3zbSg3fDKXQCIQCx4Sy1xMD546VUumQtzNJUOZeUYb2UJha5SCbptfHGOg%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRQIhAN2gqmoe4qN2y9jNGpXd56XRMRpw28WAMuvNhV_J95HvAiBdrFwNPHq1U72wobO4CSxXo8LZxt372i8YLcdNVdgswQ%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "yt_dlp\networking\_urllib.py", line 438, in _send
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4059, in urlopen
  File "yt_dlp\networking\common.py", line 114, in send
  File "yt_dlp\networking\_helper.py", line 203, in wrapper
  File "yt_dlp\networking\common.py", line 325, in send
  File "yt_dlp\networking\_urllib.py", line 443, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3395, in process_info
  File "yt_dlp\YoutubeDL.py", line 3116, in dl
  File "yt_dlp\downloader\common.py", line 455, in download
  File "yt_dlp\downloader\hls.py", line 77, in real_download
  File "yt_dlp\YoutubeDL.py", line 4078, in urlopen
yt_dlp.networking.exceptions._CompatHTTPError: HTTP Error 404: Not Found
```

**Comment by bashonly** [comment] 2023-08-11 09:53
Duplicate of #7747

workarounds:
 - use `--check-formats` if you are using nightly
 - wait until all formats have finished processing
 - add `--extractor-args "youtube:player_client=android,web"` to avoid potentially problematic iOS formats

**Closed by bashonly** 2023-08-11 09:53 UTC
Labels: site-bug, triage
