### ISSUE TITLE
[Bug] Download Music Premium thumbnails don't work

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [yt-dlp/yt-dlp#3613] opened 2022-05-01 22:04 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

I'm trying to download thumbnails from Music Premium songs, but did not work.

### Verbose log

```shell
[debug] Command-line config: ['--no-warnings', '-i', '--ignore-no-formats-error', '--no-download', '-o', 'Thumbnail - %(title)s.%(ext)s', 'https://www.youtube.com/watch?v=yGZYKYc-pZs', 'https://www.youtube.com/watch?v=tTqK-UJjKzg', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-04-07-git-607ecc27ed-full_build-www.gyan.dev (setts), ffprobe N-106528-g4fbf3c828b-sherpya
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=yGZYKYc-pZs
[youtube] yGZYKYc-pZs: Downloading webpage
[youtube] yGZYKYc-pZs: Downloading android player API JSON
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=tTqK-UJjKzg
[youtube] tTqK-UJjKzg: Downloading webpage
[youtube] tTqK-UJjKzg: Downloading android player API JSON
[debug] Default format spec: bestvideo*+bestaudio/best
Arfenhouse! Teh Movie!
```

**Comment by pukkandan** [comment] 2022-05-01 22:54
How do I know what u mean by "do not work"? especially since you have cut off the log mid way. But likely a duplicate of https://github.com/yt-dlp/yt-dlp/issues/622 https://github.com/yt-dlp/yt-dlp/issues/3542

**Comment by pukkandan** [comment] 2022-05-01 22:56
You aren't even using `--write-thumbnail` 😕

**Closed by pukkandan** 2022-05-01 22:56 UTC
Labels: incomplete, site-bug

**Comment by NanaMizukiAnother7** [comment] 2022-05-01 22:59
It worked. Thanks pukkandan!:

```
C:\Users\User>yt-dlp --no-warnings -i --ignore-no-formats-error --no-download -o "Thumbnail - %(title)s.%(ext)s" https://www.youtube.com/watch?v=yGZYK
Yc-pZs https://www.youtube.com/watch?v=tTqK-UJjKzg -v --write-thumbnail
[debug] Command-line config: ['--no-warnings', '-i', '--ignore-no-formats-error', '--no-download', '-o', 'Thumbnail - %(title)s.%(ext)s', 'https://www.youtube.com/watch?v=yGZYKYc-pZs', 'https://www.youtube.com/watch?v=tTqK-UJjKzg', '-v', '--write-thumbnail']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-04-07-git-607ecc27ed-full_build-www.gyan.dev (setts), ffprobe N-106528-g4fbf3c828b-sherpya
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=yGZYKYc-pZs
[youtube] yGZYKYc-pZs: Downloading webpage
[youtube] yGZYKYc-pZs: Downloading android player API JSON
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: Thumbnail - THEME OF MAGIC ATTRACTION.webp
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=tTqK-UJjKzg
[youtube] tTqK-UJjKzg: Downloading webpage
[youtube] tTqK-UJjKzg: Downloading android player API JSON
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: Thumbnail - Independent Love Song.webp
```
