### ISSUE TITLE
[Viu] Website overhaul.

### ISSUE THREAD

**Issue by obiyomida** [yt-dlp/yt-dlp#7562] opened 2023-07-10 10:58 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Asia

### Provide a description that is worded well enough to be understood

It appears that the website has undergone an overhaul, resulting in a different user interface compared to its previous version.
I attempted to download the same video that I had downloaded before, but the error persists.
If I remembered correctly, it seems that the URL has changed as well.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--embed-subs', '--sub-langs', 'en', '-P', 'D:\\', '--embed-thumbnail', '--embed-metadata', '--concurrent-fragments', '5', 'https://www.viu.com/ott/my/en/vod/2205719/Running-Man-2023']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[generic] Extracting URL: https://www.viu.com/ott/my/en/vod/2205719/Running-Man-2023
[generic] Running-Man-2023: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Running-Man-2023: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.viu.com/ott/my/en/vod/2205719/Running-Man-2023
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1560, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1688, in __extract_info
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.viu.com/ott/my/en/vod/2205719/Running-Man-2023
```

**Comment by bashonly** [comment] 2023-07-10 13:07
Duplicate of #6482

A workaround you can try:
replace `/en/` in the URL with `/sg-en/` (or instead of `sg`, use your own 2-letter locale code)

e.g.
`https://www.viu.com/ott/my/sg-en/vod/2205719/Running-Man-2023`

**Closed** 2023-07-10 13:07 UTC
Labels: duplicate, geo-blocked, site-bug

**Comment by obiyomida** [comment] 2023-07-11 05:30
I've tried all the workaround and still got the same error.
If I changed it to `/en/` to `/my-en/` it will end up with 404 error.
Tried with other region still the same, even with your suggestions.

Also the links now is really short. Few weeks ago before the website change the UI the links is quite long.

**Comment by Stardevv** [comment] 2023-07-12 14:44
@obiyomida might want to attach the new error, so they know its not some bullsh*ting.
