### ISSUE TITLE
with a vimeo URL it only works sometimes

### ISSUE THREAD

**Issue by andronelu** [yt-dlp/yt-dlp#11925] opened 2024-12-27 15:27 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Romania

### Provide a description that is worded well enough to be understood

Downloading video from the following address:
ytdl2.exe" "https://player.vimeo.com/video/974458988"
sometimes it works but sometimes I get this error:
"ERROR: [vimeo] 974458988: Unable to download webpage: HTTP Error 401: Unauthorized (caused by <HTTPError 401: Unauthorized>)\n"
It does not help if I specify the --referrer
Why sometimes work and sometimes not?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dl.exe -vU "https://player.vimeo.com/video/974458988"
[debug] Command-line config: ['-vU', 'https://player.vimeo.com/video/974458988']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.0-essentials_build-www.gyan.dev (setts), ffprobe 7.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.23 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.23 from yt-dlp/yt-dlp)
[vimeo] Extracting URL: https://player.vimeo.com/video/974458988
[vimeo] 974458988: Downloading webpage
[vimeo] 974458988: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 974458988: Downloading fastly_skyfire m3u8 information
[vimeo] 974458988: Downloading akfire_interconnect_quic MPD information
WARNING: [vimeo] 974458988: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[vimeo] 974458988: Downloading fastly_skyfire MPD information
WARNING: [vimeo] 974458988: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 974458988: Downloading 1 format(s): hls-fastly_skyfire-1510+hls-fastly_skyfire-audio-high-English
[debug] Invoking hlsnative downloader on "https://skyfire.vimeocdn.com/1735316735-0xac4d494911f62914ab8ea14df9664977935a0ef0/7241b199-6223-436e-ab39-1596a183c07c/v2/playlist/av/7241b199/avf/51f8af7d/media.m3u8?pathsig=8c953e4f~iM04iBV-iI19_eSEmjhZgj1OKijacf9TSN0pNoSMeeg&qsr=1&sf=ts&st=video"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 12
[download] Destination: DS4 Integration with Karaoke Surgeon [974458988].fhls-fastly_skyfire-1510.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of   12.10MiB in 00:00:01 at 7.71MiB/s
[debug] Invoking hlsnative downloader on "https://skyfire.vimeocdn.com/1735316735-0xac4d494911f62914ab8ea14df9664977935a0ef0/7241b199-6223-436e-ab39-1596a183c07c/v2/playlist/av/7241b199/avf/11fb3b8e/media.m3u8?pathsig=8c953e4f~c5S6gHCPO_IcnEi4jHNFh8WuOpsIYRaqgyH2dZfDVZk&qsr=1&sf=ts&st=audio"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 12
[download] Destination: DS4 Integration with Karaoke Surgeon [974458988].fhls-fastly_skyfire-audio-high-English.mp4
[download] 100% of    1.73MiB in 00:00:00 at 2.81MiB/s
[debug] ffmpeg command line: ffprobe -show_streams "file:DS4 Integration with Karaoke Surgeon [974458988].fhls-fastly_skyfire-audio-high-English.mp4"
[Merger] Merging formats into "DS4 Integration with Karaoke Surgeon [974458988].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:DS4 Integration with Karaoke Surgeon [974458988].fhls-fastly_skyfire-1510.mp4" -i "file:DS4 Integration with Karaoke Surgeon [974458988].fhls-fastly_skyfire-audio-high-English.mp4" -c copy -map 0:v:0 -map 1:a:0 -bsf:a:0 aac_adtstoasc -movflags +faststart "file:DS4 Integration with Karaoke Surgeon [974458988].temp.mp4"
Deleting original file DS4 Integration with Karaoke Surgeon [974458988].fhls-fastly_skyfire-1510.mp4 (pass -k to keep)
Deleting original file DS4 Integration with Karaoke Surgeon [974458988].fhls-fastly_skyfire-audio-high-English.mp4 (pass -k to keep)





yt-dl.exe -vU "https://player.vimeo.com/video/974458988"
[debug] Command-line config: ['-vU', 'https://player.vimeo.com/video/974458988']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.0-essentials_build-www.gyan.dev (setts), ffprobe 7.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.23 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.23 from yt-dlp/yt-dlp)
[vimeo] Extracting URL: https://player.vimeo.com/video/974458988
[vimeo] 974458988: Downloading webpage
ERROR: [vimeo] 974458988: Unable to download webpage: HTTP Error 401: Unauthorized (caused by <HTTPError 401: Unauthorized>)
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\vimeo.py", line 961, in _real_extract
  File "yt_dlp\extractor\common.py", line 962, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 911, in _request_webpage

  File "yt_dlp\extractor\common.py", line 898, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4172, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_curlcffi.py", line 156, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_curlcffi.py", line 252, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by bashonly** [comment] 2024-12-28 21:44
vimeo is using cloudflare turnstile plus their own anti-bot/fingerprinting to block yt-dlp's requests

Duplicate of #10645, maybe also #10422

**Closed by bashonly** 2024-12-28 21:44 UTC
Labels: duplicate, site-bug, site:vimeo
