### ISSUE TITLE
WARNING: [PornHub] 1449860981: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by det66** [yt-dlp/yt-dlp#5433] opened 2022-11-02 08:13 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

 yt-dlp version 2022.10.04 worked with pornhub perfect until 31.10.2022.
Since yesterday (01.11.2022) I get the following error:
WARNING: [PornHub] 1449860981: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
(see debug info below.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
/var/www/ip2/adm/usr/local/bin/yt-dlp -vU 'https://www.pornhub.com/view_video.php?viewkey=ph615d8da106dcd' -o /var/www/ip2/content/636215a8ef8ba3.27746403.mp4.mp4
[debug] Command-line config: ['-vU', 'https://www.pornhub.com/view_video.php?viewkey=ph615d8da106dcd', '-o', '/var/www/ip2/content/636215a8ef8ba3.27746403.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (zip)
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.0-16-amd64-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-62475-g130d19bf20-static (setts), ffprobe N-62475-g130d19bf20-static
[debug] Optional libraries: certifi-2020.06.20, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [PornHub] Extracting URL: https://www.pornhub.com/view_video.php?viewkey=ph615d8da106dcd
[PornHub] ph615d8da106dcd: Downloading pc webpage
[PornHub] ph615d8da106dcd: Downloading JSON metadata
WARNING: [PornHub] ph615d8da106dcd: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
[debug] Sort order given by extractor: height, width, fps, format_id
[debug] Formats sorted by: hasvid, ie_pref, height, width, fps, id, lang, quality, res, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ph615d8da106dcd: Downloading 1 format(s): 720p
[debug] Invoking http downloader on "https://ev.phncdn.com/videos/201603/21/71659671/191019_1446_720P_4000K_71659671.mp4?validfrom=1632770612&validto=1632777812&rate=500k&burst=1000k&ipa=162.211.96.225&hash=5CYLDGi46uYZ402kGCvHZno8Q2s%3D"
ERROR: unable to download video data: HTTP Error 472:
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3196, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2920, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 446, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 371, in real_download
    establish_connection()
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3682, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 472:
```

**Comment by byzod** [comment] 2022-11-02 09:51
same here, windows version

**Comment by bashonly** [comment] 2022-11-02 10:02
see pinned known issues, duplicate of #4627

**Closed** 2022-11-02 10:02 UTC
Labels: duplicate, NSFW, site-bug

**Comment by det66** [comment] 2022-11-02 10:39
Sorry but issue #4627 doesn't have this error message (see topic) and it appears since yesterday with the current version.
I am running 4 different servers and all have the same problem though nothing was changed from my side.

**Comment by Slqck** [comment] 2022-11-04 10:01
A friend told me about this issue but on my end everything worked fine.
He was using latest yt-dlp.exe 2022.10.04 and I still had an older version running python 3.6 2022.04.08
So now hes using yt-dlp.exe from 2022.04.08 while waiting for a new update.

**Comment by coletdjnz** [comment] 2022-11-04 20:51
> A friend told me about this issue but on my end everything worked fine. He was using latest yt-dlp.exe 2022.10.04 and I still had an older version running python 3.6 2022.04.08 So now hes using yt-dlp.exe from 2022.04.08 while waiting for a new update.

makes sense, think we've seen this before. iirc python 3.6 has a different ssl cipher selection so different ssl fingerprint. same reason 3.10+ works too.
