### ISSUE TITLE
Download from DiscoveryNetworksDe (dmax.de) not possible

### ISSUE THREAD

**Issue by ffw2** [yt-dlp/yt-dlp#7530] opened 2023-07-07 13:16 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Provide a description that is worded well enough to be understood

The website was redesigned some months ago but the URL scheme seems to be the same.
(But now there is no longer a direct link to a season to download a playlist)

Now, it's not possible to download a single video anymore.
After downloading the latest yt-dlp version, it's downloading a MHTML file with pictures instead of the video.

https://dmax.de/sendungen/goldrausch-in-australien/german-gold
https://dmax.de/sendungen/outback-opal-hunters/die-letzte-chance

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://dmax.de/sendungen/goldrausch-in-au
stralien/german-gold']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), erro
r utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.
1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe
6.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07,
 mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releas
es/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb3
52aa
yt-dlp is up to date (stable@2023.07.06)
[DiscoveryNetworksDe] Extracting URL: https://dmax.de/sendungen/goldrausch-in-au
stralien/german-gold
[debug] Using fake IP 53.123.184.21 (DE) as X-Forwarded-For
[DiscoveryNetworksDe] goldrausch-in-australien/german-gold: Downloading token
[DiscoveryNetworksDe] goldrausch-in-australien/german-gold: Downloading JSON met
adata
[DiscoveryNetworksDe] 4756322: Downloading JSON metadata
[DiscoveryNetworksDe] goldrausch-in-australien/german-gold: Downloading MPD mani
fest
[DiscoveryNetworksDe] goldrausch-in-australien/german-gold: Downloading m3u8 inf
ormation
WARNING: This video is drm protected and only images are available for download.
 use --list-formats to see them
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7),
vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, so
urce, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 4756322: Downloading 1 format(s): dash-thumbnails
[debug] Invoking mhtml downloader on "https://dplaydk.media-edge.prod-vod.h264.i
o/2f85f75e-10da-4b8d-9e2d-d05a83c00349/dash_widevinePlayready_fmp4/edge-cache-to
ken=Expires=1688821862&KeyName=media-edge-key-prod-eu-661a302&Signature=ciO-3tmN
zu6UEPehUB7t642rVYIdZhA3c9xGdWKmFcXtzzpMLL7yt4Df4hk1klxCKMEnRvY-5RAs2wlBwBDRBg/m
aster.mpd"
[mhtml] Total fragments: 662
[download] Destination: German Gold [4756322].mhtml
[debug] File locking is not supported. Proceeding without locking
[download] 100% of   11.21MiB in 00:02:18 at 83.17KiB/s
```

**Comment by bashonly** [comment] 2023-07-07 13:22
> WARNING: This video is drm protected and only images are available for download.

Have you tried disabling DRM in your browser and seeing if the video will play? [(instructions)](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)

I get the same result with 2023.06.22, so this isn't due to the change in yt-dlp's DRM detection

**Comment by theDispare** [comment] 2023-08-14 21:44
> > WARNING: This video is drm protected and only images are available for download.
> 
> Have you tried disabling DRM in your browser and seeing if the video will play? [(instructions)](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)
> 
> I get the same result with 2023.06.22, so this isn't due to the change in yt-dlp's DRM detection

Hey, i tried it with firefox and edge. If drm disabled in my browser the video still could be played perfectly. I had the issue with "you must enable DRM to play some audio or video on this page" just today with https://dmax.de/sendungen/fritz-meinecke-facing-the-unknown/auf-den-spuren-der-salzkarawanen-unter-kamelen and saw this open issue. what is the current state on this?

**Comment by Fantastik07** [comment] 2023-08-17 23:48
Hi I also have the same problem: "WARNING: This video is drm protected and only images are available for download." but until last week everything was working fine, I am also attaching a screenshot:
![image](https://github.com/yt-dlp/yt-dlp/assets/115841212/54ab1606-8d0d-4d60-94d8-53c42af0bed4)
However if I open the link from my firefox browser everything works fine, I am attaching the screenshot of that too: 
![image](https://github.com/yt-dlp/yt-dlp/assets/115841212/c5d3992e-e317-4b15-a601-43c7c774cc7e)
I hope the problem can be solved as soon as possible.

**Comment by ffw2** [comment] 2023-08-18 15:20
> Hey, i tried it with firefox and edge. If drm disabled in my browser the video still could be played perfectly. I had the issue with "you must enable DRM to play some audio or video on this page" just today with https://dmax.de/sendungen/fritz-meinecke-facing-the-unknown/auf-den-spuren-der-salzkarawanen-unter-kamelen and saw this open issue. what is the current state on this?

Hi,
I tried the link from you and now it I can play it with disabled DRM without any problems.
I can also play the videos from my first post with disabled DRM.
Maybe they changed something on their sever.

For discoveryplus.com I can't watch a video with disabled DRM.
But dmax.de is now working wth disabled DRM but it's downloading still a *.MHTML file with images.

@bashonly can you please review the problem again, since the DRM protection isn't a problem anymore for dmax.de?
Thanks!

**Comment by bashonly** [comment] 2023-08-18 15:42
This is the JSON response from the `videoPlayback` endpoint, which is the same API endpoint that the browser calls to fetch stream data. I am, however, geo-blocked from the website, so I can't confirm that the response in a DRM-disabled browser is the same. Someone else will have to do that
```json
{
  "data": {
    "attributes": {
      "markers": {
        "videoAboutToEnd": 2637160
      },
      "protection": {
        "clearkeyEnabled": false,
        "drmEnabled": true,
        "drmToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImYxN2M1NWFkLTBhYmYtNTAwZi1mMTI2LTIwZjVlNjU2ZTE2OCIsIm9wZXJhdG9ySWQiOiIzMDg2In0.eyJleHAiOjE2OTI0NTkzNTcsImp0aSI6ImYwMzgzODk5LWI3YTQtNGY1NS1hOWYxLTM3NWYzNGNmYTcxOSIsInNjb3BlIjoibGljQXV0aCIsIm9wZXJhdG9ySWQiOiIzMDg2IiwibW9kZSI6IlNUUkVBTUlORyIsImNvbnRlbnRJZCI6IjA5NmQ0MzIxLWU3ZWUtNTE3OS1hYWQ0LTg4OGE3NDdkODg0OCIsImNvbnRlbnRUeXBlIjoiVk9EIiwibGljZW5zZUR1cmF0aW9uIjoiUFQyNEgwTTBTIiwicGxheWJhY2tEdXJhdGlvbiI6IlBUMjRIME0wUyIsInVyaVByb2ZpbGVJZCI6IkZSRUVfVVNBR0UifQ.Leff--uTVaaqUshrYMyD7kaUhTPVuC5vPFVEHRi9c31axbH7XvejgowO-Ihg4DAbr4bfH8SIqSCKfPKE7CWrsKfFJcHrLZplRLCgfXKWB20on2DdQAqyTKqVA01zrxQBpc4WBrEqx9k8637Rh1BNIgtRMLoPLWkodkuuECa1cnoodhAH4qOHiNX4sH3k3-6Q-cQz7uQECDr6VYA7o42AnV08C7smZEpFfyILHcrGz9fnRjWKBo4AK3PHGPKr7PncHMxXGekuvcNwY1EcHeP9mRDuMjA9b-WY3dF4tl2ppUA2GY8TGfOuFO15Wo0U5u8HURwbAOVIguu-PrhVcM37_g",
        "schemes": {
          "fairplay": {
            "certificateUrl": "https://discovery-eur.conax.cloud/fairplay/certificates/A30BAEFF134A609B019CBBB0D5880803B5D5E9D0",
            "licenseUrl": "https://discovery-eur.conax.cloud/fairplay/license"
          },
          "playready": {
            "licenseUrl": "https://discovery-eur.conax.cloud/cxplayready/rightsmanager.asmx"
          },
          "widevine": {
            "certificateUrl": "https://discovery-eur.conax.cloud/widevine/certificates/conax",
            "licenseUrl": "https://discovery-eur.conax.cloud/widevine/license"
          }
        }
      },
      "reportProgressInterval": 60000,
      "sourceSystemId": "DMAXDE_DE_DCB761660001100",
      "streaming": {
        "dash": {
          "url": "https://dplaydk-prod-vod.akamaized.net/0ad1029b-2602-44c4-a2e8-5f66d356f8cd/dash_widevinePlayready_fmp4/hdntl=exp=1692459357~acl=/0ad1029b-2602-44c4-a2e8-5f66d356f8cd/dash_widevinePlayready_fmp4/*~data=hdntl~hmac=456b631326de67d5c6004e89a8f755e1daa781a721dc4ca0a384cc7ba80ef179/master.mpd"
        },
        "hls": {
          "url": "https://dplaydk-google-v2.prod-vod.h264.io/0ad1029b-2602-44c4-a2e8-5f66d356f8cd/hls_fairPlay_ts/x-goog-token=Expires=1692459357&KeyName=prod-sign-url-key-eu&Signature=P-8hExML6U0DcC-hfw0yDdD6SeQ/master.m3u8"
        }
      },
      "userInfo": {
        "packages": [
          "Free"
        ]
      },
      "viewingHistory": {
        "viewed": false
      }
    },
    "id": "5153555",
    "type": "videoPlaybackInfo"
  }
}
```
as you can see, only DRM formats are provided

**Comment by bashonly** [comment] 2023-08-18 16:37
With this patch I can get non-DRM HLS formats:
```diff
diff --git a/yt_dlp/extractor/dplay.py b/yt_dlp/extractor/dplay.py
index 363b4bec9..ec2f42f15 100644
--- a/yt_dlp/extractor/dplay.py
+++ b/yt_dlp/extractor/dplay.py
@@ -355,12 +355,10 @@ def _download_video_playback_info(self, disco_base, video_id, headers):
             video_id, headers=headers, data=json.dumps({
                 'deviceInfo': {
                     'adBlocker': False,
+                    'drmSupported': False,
                 },
                 'videoId': video_id,
-                'wisteriaProperties': {
-                    'platform': 'desktop',
-                    'product': self._PRODUCT,
-                },
+                'wisteriaProperties': {},
             }).encode('utf-8'))['data']['attributes']['streaming']
 
     def _real_extract(self, url):
@@ -878,7 +876,7 @@ def _update_disco_api_headers(self, headers, disco_base, display_id, realm):
         })
 
 
-class DiscoveryNetworksDeIE(DPlayBaseIE):
+class DiscoveryNetworksDeIE(DiscoveryPlusBaseIE):
     _VALID_URL = r'https?://(?:www\.)?(?P<domain>(?:tlc|dmax)\.de|dplay\.co\.uk)/(?:programme|show|sendungen)/(?P<programme>[^/]+)/(?:video/)?(?P<alternate_id>[^/]+)'
 
     _TESTS = [{
@@ -921,7 +919,14 @@ def _real_extract(self, url):
         realm = 'questuk' if country == 'GB' else domain.replace('.', '')
         return self._get_disco_api_info(
             url, '%s/%s' % (programme, alternate_id),
-            'sonic-eu1-prod.disco-api.com', realm, country)
+            'eu1-prod.disco-api.com', realm, country)
+
+    def _update_disco_api_headers(self, headers, disco_base, display_id, realm):
+        headers.update({
+            'x-disco-params': 'realm=%s' % realm,
+            'x-disco-client': 'Alps:HyogaPlayer:0.0.0',
+            'Authorization': self._get_auth(disco_base, display_id, realm),
+        })
 
 
 class DiscoveryPlusShowBaseIE(DPlayBaseIE):
 ```
 I don't know how it will impact other extractors subclassed from `DiscoveryPlusBaseIE`, though. I am pretty sure most of the other DiscoveryPlus sites are having the same DRM issue; hopefully this fix could work for them too (probably with some needed improvements/tweaks)

**Comment by theDispare** [comment] 2023-08-23 12:03
@bashonly 
First Time building yt-dlp. cloned the repo. replaced your code. 
used the commands:

`python3 -m pip install -U pyinstaller -r requirements.txt`
`python3 devscripts/make_lazy_extractors.py`
`python3 pyinst.py`

Build was completed. Used the exe in \dist

Tried `.\yt-dlp.exe -F https://dmax.de/sendungen/fritz-meinecke-facing-the-unknown/auf-den-spuren-der-salzkarawanen-unter-kamelen`

still only a mhtml file. Do I miss something?

**Comment by bashonly** [comment] 2023-08-23 12:29
@theDispare it sounds like maybe you missed a line of the patch. Instead of editing the code by hand, it is best to save the patch as a file and use `git apply patchfile.diff` to have git take care of it for you.

Patch still works for me:
```shell
$ yt-dlp -F "https://dmax.de/sendungen/fritz-meinecke-facing-the-unknown/auf-den-spuren-der-salzkarawanen-unter-kamelen"
[DiscoveryNetworksDe] Extracting URL: https://dmax.de/sendungen/fritz-meinecke-facing-the-unknown/auf-den-spuren-der-salzkarawanen-unter-kamelen
[DiscoveryNetworksDe] fritz-meinecke-facing-the-unknown/auf-den-spuren-der-salzkarawanen-unter-kamelen: Downloading token
[DiscoveryNetworksDe] fritz-meinecke-facing-the-unknown/auf-den-spuren-der-salzkarawanen-unter-kamelen: Downloading JSON metadata
[DiscoveryNetworksDe] 5153555: Downloading JSON metadata
[DiscoveryNetworksDe] fritz-meinecke-facing-the-unknown/auf-den-spuren-der-salzkarawanen-unter-kamelen: Downloading m3u8 information
[info] Available formats for 5153555:
ID                         EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-audio-aacl-125-English mp4 audio only     │                  m3u8  │ audio only        unknown    [en] English
hls-304                    mp4 416x234     25 │ ~ 98.64MiB  304k m3u8  │ avc1.4D400D  304k video only
hls-437                    mp4 640x360     25 │ ~141.79MiB  437k m3u8  │ avc1.4D401E  437k video only
hls-653                    mp4 768x432     25 │ ~211.87MiB  653k m3u8  │ avc1.4D401E  653k video only
hls-1107                   mp4 1280x720    25 │ ~359.18MiB 1107k m3u8  │ avc1.4D401F 1107k video only
hls-1921                   mp4 1280x720    25 │ ~623.29MiB 1921k m3u8  │ avc1.4D401F 1921k video only
hls-3582                   mp4 1920x1080   25 │ ~  1.13GiB 3582k m3u8  │ avc1.4D4028 3582k video only
hls-5362                   mp4 1920x1080   25 │ ~  1.70GiB 5362k m3u8  │ avc1.4D4028 5362k video only
hls-8098                   mp4 1920x1080   25 │ ~  2.57GiB 8098k m3u8  │ avc1.4D4028 8098k video only
```

**Comment by theDispare** [comment] 2023-08-23 13:38
@bashonly copying your patch and trying to apply it it gave me an error in line 42.

But it was right that I missed a change in your patch. Now i was able to download the video perfectly. Thank you.

**Comment by bashonly** [comment] 2023-08-23 13:41
@theDispare In the future, you need to copy the entire patch, all the down to the very bottom line (e.g. `class DiscoveryPlusShowBaseIE(DPlayBaseIE):`) or else git can't parse the patch correctly. Glad you got it working though

**Comment by ffw2** [comment] 2023-08-23 15:08
@theDispare Would it be possible for you to provide me with the new yt-dlp.exe for testing? Thanks!

**Comment by bashonly** [comment] 2023-08-24 03:14
Here is a pre-release build for testing:
https://github.com/bashonly/yt-dlp/releases/tag/2023.08.24.000249

or you can run this:
```shell
yt-dlp --update-to bashonly/yt-dlp@2023.08.24.000249
```

**Comment by Fantastik07** [comment] 2023-08-24 04:17
You could make a patch or a pre-release also for discoveryplus.com/it please? ç.ç

**Comment by bashonly** [comment] 2023-08-24 09:52
@Fantastik07 try this build, it may work for more sites than just DE

**Comment by jaylex32** [comment] 2023-08-27 10:01
I can confirm that with the patch release above is working perfectly fine with Investigation Discovery, is this going to be add it to the next release?

**Comment by bashonly** [comment] 2023-08-27 16:52
> is this going to be add it to the next release?

As I mentioned above, the patch makes changes that impact several other site's extractors. I am not able to test all of these sites due to some geo-restrictions and subscription requirements. If others want to help test and report back (with logs), that would help towards getting this merged

**Comment by ffw2** [comment] 2023-08-27 18:27
@bashonly I can confirm that the download from dmax.de is working without any problems:

![dmax](https://github.com/yt-dlp/yt-dlp/assets/15077753/2384f80c-72d7-4714-81e8-687ab6e5b8e5)

But discoveryplus.com is not working for me using --cookies-from-browser chrome.
Maybe I'm doing something wrong, because in the past discoveryplus.com also didn't work for me:

![discovery](https://github.com/yt-dlp/yt-dlp/assets/15077753/f5a75ac4-917d-40f2-8fa1-9c1aec127de1)

**Comment by jaylex32** [comment] 2023-08-27 20:03
> @bashonly I can confirm that the download from dmax.de is working without any problems:
> 
> ![dmax](https://user-images.githubusercontent.com/15077753/263547149-2384f80c-72d7-4714-81e8-687ab6e5b8e5.png)
> 
> But discoveryplus.com is not working for me using --cookies-from-browser chrome. Maybe I'm doing something wrong, because in the past discoveryplus.com also didn't work for me:
> 
> ![discovery](https://user-images.githubusercontent.com/15077753/263547178-f5a75ac4-917d-40f2-8fa1-9c1aec127de1.png)

try with cookies.txt, it works for me like that.

**Comment by jaylex32** [comment] 2023-08-27 20:49
> > is this going to be add it to the next release?
> 
> As I mentioned above, the patch makes changes that impact several other sites' extractors. I am not able to test all of these sites due to some geo-restrictions and subscription requirements. If others want to help test and report back (with logs), that would help towards getting this merged

I'm curious on how it impact other extractors, it shares a code with other extractors or what's the reason?

**Comment by bashonly** [comment] 2023-08-28 03:06
> I'm curious on how it impact other extractors, it shares a code with other extractors or what's the reason?

The patch modifies the extractor base class `DiscoveryPlusBaseIE`, from which all of the below extractors inherit code:

```
GoDiscoveryIE
TravelChannelIE
CookingChannelIE
HGTVUsaIE
FoodNetworkIE
DestinationAmericaIE
InvestigationDiscoveryIE
AmHistoryChannelIE
ScienceChannelIE
DIYNetworkIE
DiscoveryLifeIE
AnimalPlanetIE
TLCIE
MotorTrendIE
MotorTrendOnDemandIE
DiscoveryPlusIE
DiscoveryPlusIndiaIE
DiscoveryPlusItalyIE
GlobalCyclingNetworkPlusIE
```

**Comment by ffw2** [comment] 2023-08-28 11:32
> try with cookies.txt, it works for me like that.

@jaylex32 thanks, but doesn't work. I use the chrome extension  "Get cookies.txt LOCALLY" with Netscape format.
It irritates me that the command line says: "This video is only available for registered users. You may want to use --cookies."

![discovery_2](https://github.com/yt-dlp/yt-dlp/assets/15077753/53162195-ce31-421d-8802-d658dbce2290)

**Comment by jaylex32** [comment] 2023-08-28 12:18
> > try with cookies.txt, it works for me like that.
> 
> @jaylex32 thanks, but doesn't work. I use the chrome extension "Get cookies.txt LOCALLY" with Netscape format. It irritates me that the command line says: "This video is only available for registered users. You may want to use --cookies."
> 
> ![discovery_2](https://user-images.githubusercontent.com/15077753/263689636-53162195-ce31-421d-8802-d658dbce2290.png)

do you have access to it? are you been able to see the episodes in the browser? if you dont have an account or tv provider I dont think you will be able to get it if you do, try to use the go.discovery.com for example look:

[GoDiscovery] Extracting URL: https://go.discovery.com/video/dual-survival-discovery/shipwrecked
[GoDiscovery] dual-survival-discovery/shipwrecked: Downloading JSON metadata
[GoDiscovery] 2194327: Downloading JSON metadata
[GoDiscovery] dual-survival-discovery/shipwrecked: Downloading m3u8 information
[info] 2194327: Downloading 1 format(s): hls-10245+hls-audio-aacl-125-English
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 656
[download] Destination: C:\Users\J-PLEX SERVER\source\repos\new ASD Downloader\bin\Debug\net6.0-windows\win-x64\Downloads\Shipwrecked.fhls-10245.mp4
[download]   0.0% of ~ 472.58MiB at    4.36KiB/s ETA 30:51:45 (frag 0/656)
[download]   0.0% of ~ 472.58MiB at   13.01KiB/s ETA 10:19:57 (frag 0/656)
[download]   0.0% of ~ 472.58MiB at   30.22KiB/s ETA 04:26:50 (frag 0/656)
[download]   0.0% of ~ 472.58MiB at   64.49KiB/s ETA 02:05:03 (frag 0/656)
[download]   0.0% of ~ 472.58MiB at  126.03KiB/s ETA 01:03:59 (frag 0/656)
[download]   0.0% of ~ 472.58MiB at  254.06KiB/s ETA 31:44 (frag 0/656)   
[download]   0.0% of ~ 472.58MiB at  473.87KiB/s ETA 17:00 (frag 0/656)
[download]   0.1% of ~ 472.58MiB at  869.84KiB/s ETA 09:16 (frag 0/656)

**Comment by ffw2** [comment] 2023-08-28 12:26
> do you have access to it? are you been able to see the episodes in the browser? if you dont have an account or tv provider I dont think you will be able to get it if you do, try to use the go.discovery.com for example look:

Sure, I have an account and I'm logged in and can play all content. 
In the cookies.txt file are also all necessary data from discoveryplus.com I think.

go.discovery. com isn't available in my country. 
Others have/had problems with it too (reddit, ...) and I've tried everything but it doesn't work.
So I don't know what I can do.

**Comment by MagicAndre1981** [comment] 2023-08-28 16:33
> Here is a pre-release build for testing: https://github.com/bashonly/yt-dlp/releases/tag/2023.08.24.000249

works fine for me to download _112: Feuerwehr im Einsatz_ 👍

**Comment by Fantastik07** [comment] 2023-08-28 16:42
@bashonly unfortunately that build with discoveryplus.com/it doesn't work the same, so I hope someone can make a patch for discoveryplus.com/it as was done for discovery de, which seems to work fine

**Comment by bashonly** [comment] 2023-08-28 21:01
@Fantastik07 are you passing logged-in cookies to yt-dlp? are you experiencing #2361 or #2138? share a verbose log, or open a new issue if your issue seems unrelated to the linked issues

**Comment by si70so15** [comment] 2023-10-03 16:32
> Here is a pre-release build for testing: https://github.com/bashonly/yt-dlp/releases/tag/2023.10.03.043124
> 
> or you can run this:
> 
> ```shell
> yt-dlp --update-to bashonly/yt-dlp@2023.10.03.043124
> ```
thank you bashonly,  your patch work fine like a previous.
I would also ask to you, if this patch will be inserted on the next release of yt-dlp, or you must make a new fix after release of new one.

Thank you very much.

**Comment by Fantastik07** [comment] 2023-10-14 19:56
@bashonly yes, sure, I'm passing logged-in cookies from firefox to yt-dlp, you can see it in the screenshot of the [first message I posted](https://github.com/yt-dlp/yt-dlp/issues/7530#issuecomment-1683125108), and now by installing your patch it works also for me, and I can download again from discoveryplus.com/it and the message "WARNING: This video is drm protected and only images are available for download." no longer comes out, but now I have another problem, every video I download when I open it the audio is only there for the first 3 seconds, then it stops and the rest of the video is without audio, and I don't understand why...

![Screenshot_1](https://github.com/yt-dlp/yt-dlp/assets/115841212/6a5b6f71-bf6c-4bf0-836c-33e330fdca2f)
![Screenshot_2](https://github.com/yt-dlp/yt-dlp/assets/115841212/f5ad5464-1b0b-4f32-aca6-959ef27cf8ea)

**Comment by OdomLinx** [comment] 2023-11-15 18:55
> Oh dmax is getting me headaches..... I got the links for the dmax show https://dmax.de/sendungen/steel-buddies with this cool shit: https://github.com/Brawl345/Get-DMAX-Links
> 
> Then I installed the cool build from bashonly. tried to download the video normally -> it says DRM protection. Next shot: tried to use with firefox cookies - same thing happens.
> 
With the extracted Link from "Get-DMAX-Links" i've the same problem, but with the direkt link from DMAX (https://dmax.de/sendungen/steel-buddies/der-bockige-brite) the download works without cookies from browser.

**Comment by fnordson** [comment] 2023-11-15 22:04
> With the extracted Link from "Get-DMAX-Links" i've the same problem, but with the direkt link from DMAX (https://dmax.de/sendungen/steel-buddies/der-bockige-brite) the download works without cookies from browser.

I have the same problem as @medienoekonom and trying to download from the direct link gives me an 11MB  .mhtml-File. 
Which command did you use?

**Comment by OdomLinx** [comment] 2023-11-16 16:17
> > With the extracted Link from "Get-DMAX-Links" i've the same problem, but with the direkt link from DMAX (https://dmax.de/sendungen/steel-buddies/der-bockige-brite) the download works without cookies from browser.
> 
> I have the same problem as @medienoekonom and trying to download from the direct link gives me an 11MB .mhtml-File. Which command did you use?

Strange, now it doesn't work for me either. Yesterday it still worked.

I had tried something around:
- DMAX URL opened in the browser
- yt-dlp --cookies-from-browser vivaldi and the "Get-DMAX-Links" URL, then there was PermissionError: [Errno 13] , could be fixed by closing the browser. The cookies were read in, but there was also the message DRM
- yt-dlp DMAX URL, the download then worked (over 2GB)


today exactly this procedure does not work anymore and I get the DRM error

Both days with yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875]

**Comment by ffw2** [comment] 2024-01-13 09:53
@bashonly since your pre-release for testing works good to download for single episodes, can you please integrate into the official yt-dlp.exe? Thank you!

**Comment by jaylex32** [comment] 2024-01-16 00:15
@bashonly this fix is been hanging around for a while and it haven't been introduce to the main release, can you please merge the patch? thanks in advance.

**Closed** 2024-05-25 15:01 UTC
Labels: site-bug, patch-available, needs-testing
