### ISSUE TITLE
[Broken] Can't download a Facebook watch video

### ISSUE THREAD

**Issue by TheMulti0** [yt-dlp/yt-dlp#1166] opened 2021-10-04 09:16 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
ERROR: [facebook] 243035547657520: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

I tried downloading the following facebook video without a username or password. 
https://facebook.com/hebpmo/posts/243035547657520

**Comment by ReignBit** [comment] 2021-10-04 19:12
Facebook is down right now

**Comment by coletdjnz** [comment] 2021-10-04 23:53
Seems to be working now

**Comment by TheMulti0** [comment] 2021-10-05 08:41
> Facebook is down right now

Actually this error started before facebook was down

**Comment by TheMulti0** [comment] 2021-10-05 18:16
The error continues with other Facebook video posts such as https://facebook.com/ayelet.benshaul.shaked/posts/4665401926872827

**Comment by pukkandan** [comment] 2021-10-05 21:43
Show full log, not just the error message. The purticular video in your above comment looks like it needs an account to download. You can try passing cookies. This is also possibly a duplicate of #542

**Closed** 2021-10-18 13:32 UTC
Labels: incomplete, site:facebook
