### ISSUE TITLE
nonp-printable characters on 8bit locales

### ISSUE THREAD

**Issue by avpanov** [yt-dlp/yt-dlp#1306] opened 2021-10-16 15:16 UTC
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Verbose log

```
PASTE VERBOSE LOG HERE

```

yt-dlp -v -o "%(title)s.%(ext)s" -f 135+140 https://www.youtube.com/watch?v=nmpl1PsHlmk
[debug] Command-line config: ['-v', '-o', '%(title)s.%(ext)s', '-f', '135+140', 'https://www.youtube.com/watch?v=nmpl1PsHlmk']
[debug] Encodings: locale KOI8-R, fs koi8-r, out koi8-r, pref KOI8-R
[debug] yt-dlp version 2021.10.10
[debug] Python version 3.10.0 (CPython 64bit) - Linux-4.19.211-x86_64-Intel-R-_Core-TM-_i5-3330_CPU_@_3.00GHz-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=nmpl1PsHlmk
[youtube] nmpl1PsHlmk: Downloading webpage
[youtube] nmpl1PsHlmk: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[info] nmpl1PsHlmk: Downloading 1 format(s): 135+140
[debug] Invoking downloader on "https://r2---sn-hxb54vo-88vl.googlevideo.com/videoplayback?expire=1634418241&ei=4elqYeCvBYyxyQXr9IDwAg&ip=94.198.20.42&id=o-AC5mf_7h1oaSKIuiviWcXXAanzbM3kWiYcWUiNfONVUn&itag=135&source=youtube&requiressl=yes&mh=Pv&mm=31%2C29&mn=sn-hxb54vo-88vl%2Csn-n8v7znly&ms=au%2Crdu&mv=u&mvi=2&pl=21&vprv=1&mime=video%2Fmp4&gir=yes&clen=27297094&dur=660.000&lmt=1634145841439681&mt=1634395672&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgLBDpKendkKJlTsc5DBkCv7wgnADuF3wTrDYGw9oa188CIQDaH3HiNxqrME6FyoX2mXOLgAOP2aoY7BkEQE2zzJ5BMg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRAIgP3ui8EKsSP-Bo0ohLLl1H3wepcyuWkUJp4ijUChOEq0CIEZcQXyofLrceXJTjbHPMmbuk_V_jmWb9NHdXIP7CKFL"
ERROR: 'charmap' codec can't encode character '\u2014' in position 10: character maps to <undefined>
Traceback (most recent call last):
  File "/usr/lib64/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1263, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib64/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1301, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib64/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1351, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib64/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2361, in process_video_result
    self.process_info(new_info)
  File "/usr/lib64/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2783, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/lib64/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2508, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/lib64/python3.10/site-packages/yt_dlp/downloader/common.py", line 397, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/lib64/python3.10/site-packages/yt_dlp/downloader/http.py", line 371, in real_download
    return download()
  File "/usr/lib64/python3.10/site-packages/yt_dlp/downloader/http.py", line 264, in download
    ctx.stream, ctx.tmpfilename = sanitize_open(
  File "/usr/lib64/python3.10/site-packages/yt_dlp/utils.py", line 2068, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
  File "/usr/lib64/python3.10/encodings/koi8_r.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character '\u2014' in position 10: character maps to <undefined>

## Description

WRITE DESCRIPTION HERE

I use non-unicode 8-bit locale. The filenames are saved under this 8-bit locale.
Sometimes, the filenames at, for example, youtube contain characters non-existing under this 8-bit locale, e.g.  '\u2014'.
yt-dlp stops at this situation, while youtube-dl silently drops these characters on saving files. The option '--restrict-filenames' purges almost everything from filenames here. Possibly, it would be useful to extend the behavior of '--restrict-filenames' to non-ANSI 8-bit locales.

**Comment by avpanov** [comment] 2021-10-16 16:32
youtube-dl -v -o "%(title)s.%(ext)s" -f 135+140 https://www.youtube.com/watch?v=nmpl1PsHlmk
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-o', u'%(title)s.%(ext)s', u'-f', u'135+140', u'https://www.youtube.com/watch?v=nmpl1PsHlmk']
[debug] Encodings: locale KOI8-R, fs KOI8-R, out KOI8-R, pref KOI8-R
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.18 (CPython) - Linux-4.19.211-x86_64-Intel-R-_Core-TM-_i5-3330_CPU_@_3.00GHz-with-slackware-15.0
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] nmpl1PsHlmk: Downloading webpage
[debug] Invoking downloader on u'https://r2---sn-hxb54vo-88vl.googlevideo.com/videoplayback?expire=1634423365&ei=5f1qYan3Mdn97gT4go7gDQ&ip=94.198.20.42&id=o-ACAE6mpRg-IiRNcXOjrPWYQJY1ECsCWRe7v5PHkAna8g&itag=135&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=Pv&mm=31%2C29&mn=sn-hxb54vo-88vl%2Csn-n8v7znly&ms=au%2Crdu&mv=u&mvi=2&pl=21&pcm2=yes&vprv=1&mime=video%2Fmp4&ns=KXZZweMvp5k1B_fQQNavQUwG&gir=yes&clen=27297094&dur=660.000&lmt=1634145841439681&mt=1634401441&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5535432&n=T6lj_UiqM3p4jGn_L&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOPxqeMUBSYhHpecFXVPkfneS2p9T689jUjRMaAoyMs6AiEA7_fRxQBkrF9mSkSgIWgNBbiYJOrYvmSBTH2CRM4jWNU%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRgIhAOLZMQ2kvDt_TFNggA0VSmisMRZ_UWPwOArNBC2snFvdAiEA6_H94l8vaNI77elf3TxIItnzkPdnO83sNLJ9z9IWCz0%3D'
[download] Destination: Лео и Тиг  Солнечный зайчик  Серия 58 _ Мультики для детей.f135.mp4
[download]   1.5% of 26.03MiB at 56.32KiB/s ETA 07:46^C

**Comment by sulyi** [comment] 2022-04-26 19:38
In order to reproduce issue I've made `cyril-encoding.py`:
```py
import sys

import yt_dlp.version
from yt_dlp.utils import sanitize_open


print('python', sys.version)
print('yt_dlp', yt_dlp.version.__version__)

stream = sanitize_open('Лео и Тиг — Солнечный зайчик — Серия 58 _ Мультики для детей.f135.mp4', 'wb')
```
and running it after following steps at https://wiki.archlinux.org/title/locale#Generating_locales like this:
```
$ LC_ALL=ru_RU.KOI8-R python my-stuff/cyril-encoding.py
python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
yt_dlp 2022.03.08.1
Traceback (most recent call last):
  File "/home/arsene/PycharmProjects/yt-dlp/my-stuff/cyril-encoding.py", line 10, in <module>
    stream = sanitize_open('��� � ��� \u2014 ��������� ������ \u2014 ����� 58 _ �������� ��� �����.f135.mp4', 'wb')
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 678, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).open()
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 2202, in __init__
    self.f = io.open(filename, mode, encoding=encoding)
  File "/usr/lib/python3.10/encodings/koi8_r.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character '\u2014' in position 10: character maps to <undefined>
$ 
```
results the same problem.

**Comment by sulyi** [comment] 2022-04-27 11:28
Alternatively, setting `PYTHONUTF8=1` or adding `-X utf8` interpreter option might be enough.

**Comment by pukkandan** [comment] 2024-04-14 04:11
https://github.com/yt-dlp/yt-dlp/issues/5341 was a dup of this, but since recent discussions happened there, I'm closing this instead. Pls track that issue for updates

**Closed by pukkandan** 2024-04-14 04:11 UTC
Labels: bug, help-wanted
