### ISSUE TITLE
Provide an option to set file modification time to upload_date

### ISSUE THREAD

**Issue by srussel** [yt-dlp/yt-dlp#9127] opened 2024-02-02 23:32 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When downloading YouTube playlists, using the default `--mtime` option,  I sometimes find the file modification date is very different to the upload date. Sometimes weeks earlier or later. This results in playlists being out of order when sorted by date.

If I include `%(upload_date)` in the filename template, I get the correct date in the filename. But I would prefer to set the upload date in the file modification time instead of including the date in the filename so I can easily switch between sorting by name or date in my file browser.

What I would like is a option that will make yt-dlp set the modification time of downloads to the upload date of the video instead of the current `--mtime` or `--no-mtime` behavior.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment] 2024-02-02 23:36
Duplicate of #903

see https://github.com/bradenhilton/yt-dlp-FixupMtime

**Closed by bashonly** 2024-02-02 23:36 UTC
Labels: enhancement, triage
