### ISSUE TITLE
Previously working teachable.com site now broken. 

### ISSUE THREAD

**Issue by hubdows** [yt-dlp/yt-dlp#10230] opened 2024-06-21 21:37 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Running this command has worked for the past 6-8 months. Now it errors saying that the site is Unsupported.

> yt-dlp -vvU --cookies cookies.txt --referer https://player.hotmart.com/ `https://frank-bunn.teachable.com/courses/2442083/lectures/54629763

Site headers confirm the referrer is still https://player.hotmart.com. I updated the site cookies as well.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vvU --cookies cookies.txt --referer https://player.hotmart.com/ https://frank-bunn.teachable.com/courses/2442083/lectures/54629763
[debug] Command-line config: ['-vvU', '--cookies', 'cookies.txt', '--referer', 'https://player.hotmart.com/', 'https://frank-bunn.teachable.com/courses/2442083/lectures/54629763']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (debian*)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.1.0, websockets-9.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://frank-bunn.teachable.com/courses/2442083/lectures/54629763
[generic] 54629763: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 54629763: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://frank-bunn.teachable.com/courses/2442083/lectures/54629763
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://frank-bunn.teachable.com/courses/2442083/lectures/54629763
```

**Comment by bashonly** [comment] 2024-06-21 22:51
try prefixing the input URL with `teachable:`, e.g.

```
yt-dlp -vU --cookies cookies.txt --referer "https://player.hotmart.com/" "teachable:https://frank-bunn.teachable.com/courses/2442083/lectures/54629763"
```

**Comment by hubdows** [comment] 2024-06-21 23:32
Here is the updated debug:

[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', '--referer', 'https://player.hotmart.com/', 'teachable:https://frank-bunn.teachable.com/courses/2442083/lectures/54530225']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (debian*)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.1.0, websockets-9.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[Teachable] Extracting URL: teachable:https://frank-bunn.teachable.com/courses/2442083/lectures/54530225
[Teachable] 54530225: Downloading webpage
ERROR: [Teachable] 54530225: Unable to find video URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/teachable.py", line 174, in _real_extract
    raise ExtractorError('Unable to find video URL')

**Comment by bashonly** [comment] 2024-06-21 23:37
Duplicate of #3564

You could try #7650

**Closed by bashonly** 2024-06-21 23:37 UTC
Labels: site-bug, triage

**Comment by hubdows** [comment] 2024-06-21 23:45
I switched back to the original script by @Green0Photon in #7650 and it works using "teachable:https://...". I haven't needed this in the past, and it's strange it's not working with yt-dlp natively.

Regards

**Comment by LuCu11** [comment] 2024-07-12 14:10
> I switched back to the original script by @Green0Photon in #7650 and it works using "teachable:https://...". I haven't needed this in the past, and it's strange it's not working with yt-dlp natively.
> 
> Regards

how exactly does your call of the script look like, I tried it but was not successful. Am I right that I have to export the Cockie information from my browser to a text file first?
