### ISSUE TITLE
Asked to report  "[youtube] unable to extract yt initial data"

### ISSUE THREAD

**Issue by sqeeezy** [yt-dlp/yt-dlp#7932] opened 2023-08-22 08:18 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Spain

### Provide a description that is worded well enough to be understood

/Users/nik:yt-dlp 'https://youtu.be/och9ipLUc-4'
[youtube] Extracting URL: https://youtu.be/och9ipLUc-4
[youtube] och9ipLUc-4: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] och9ipLUc-4: Downloading ios player API JSON
[youtube] och9ipLUc-4: Downloading android player API JSON
[youtube] och9ipLUc-4: Downloading iframe API JS
[youtube] och9ipLUc-4: Downloading player f980f2a9
[youtube] och9ipLUc-4: Downloading web player API JSON
[youtube] och9ipLUc-4: Downloading m3u8 information
[youtube] och9ipLUc-4: Downloading MPD manifest
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] och9ipLUc-4: Downloading initial data API JSON
[info] och9ipLUc-4: Downloading 1 format(s): 247+251
[dashsegments] Total fragments: 98
[download] Destination: The Silver Fleet (1943) - the traitor exposed [och9ipLUc-4].f247.webm
[download] 100% of   49.45MiB in 00:02:14 at 377.32KiB/s
[download] Destination: The Silver Fleet (1943) - the traitor exposed [och9ipLUc-4].f251.webm
[download] 100% of    6.07MiB in 00:00:04 at 1.44MiB/s
[Merger] Merging formats into "The Silver Fleet (1943) - the traitor exposed [och9ipLUc-4].webm"
Deleting original file The Silver Fleet (1943) - the traitor exposed [och9ipLUc-4].f247.webm (pass -k to keep)
Deleting original file The Silver Fleet (1943) - the traitor exposed [och9ipLUc-4].f251.webm (pass -k to keep)

So it worked despite initial complaint. I'm reporting this as a problem because yt-dlp asked me too, nothing more.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
/Users/nik:yt-dlp -vU 'https://youtu.be/och9ipLUc-4'
[debug] Command-line config: ['-vU', 'https://youtu.be/och9ipLUc-4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.4 (CPython x86_64 64bit) - macOS-10.14.6-x86_64-i386-64bit (OpenSSL 3.1.1 30 May 2023)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4
[debug] Optional libraries: certifi-2023.05.07, pycrypto-3.18.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://youtu.be/och9ipLUc-4
[youtube] och9ipLUc-4: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] och9ipLUc-4: Downloading ios player API JSON
[youtube] och9ipLUc-4: Downloading android player API JSON
[youtube] och9ipLUc-4: Downloading iframe API JS
[youtube] och9ipLUc-4: Downloading player f980f2a9
[youtube] och9ipLUc-4: Downloading web player API JSON
[youtube] och9ipLUc-4: Downloading m3u8 information
[youtube] och9ipLUc-4: Downloading MPD manifest
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] och9ipLUc-4: Downloading initial data API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] och9ipLUc-4: Downloading 1 format(s): 247+251
[download] The Silver Fleet (1943) - the traitor exposed [och9ipLUc-4].webm has already been downloaded
/Users/nik:
```

**Comment by colecovision** [comment] 2023-08-22 11:11
I can confirm this same issue from Italy. However, in my case, this happens very sporadically.
In particular, running `yt-dlp --write-subs [URL]` would at times throw this warning, and then proceed to download **only the first fragment** of a live chat (with video and audio downloaded without issue). Sometimes, after several tries, the same exact command will actually download live chat in full.
I am not currently able to reproduce the former, failed case, but if I am ever able to do so I shall report its (verbose) output here.

**Comment by bashonly** [comment] 2023-08-22 11:19
Duplicate of #7904

**Closed by bashonly** 2023-08-22 11:19 UTC
Labels: site-bug, triage
