### ISSUE TITLE
prosiebensat1 video download does not work

### ISSUE THREAD

**Issue by danielmarschall** [yt-dlp/yt-dlp#8557] opened 2023-11-09 19:59 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

URL: https://www.prosieben.de/serien/joko-klaas-live-die-schatzsuche/videos/lesung-konzert-v_yd0czlu26gxi

Error message:
```
[prosiebensat1] Extracting URL: https://www.prosieben.de/serien/joko-klaas-live-die-schatzsuche/videos/lesung-konzert-v_yd0czlu26gxi
[prosiebensat1] serien/joko-klaas-live-die-schatzsuche/videos/lesung-konzert-v_yd0czlu26gxi: Downloading webpage
ERROR: [prosiebensat1] serien/joko-klaas-live-die-schatzsuche/videos/lesung-konzert-v_yd0czlu26gxi: Unable to extract clip id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ ./yt-dlp -vU "https://www.prosieben.de/serien/joko-klaas-live-die-schatzsuche/videos/lesung-konzert-v_yd0czlu26gxi"
[debug] Command-line config: ['-vU', 'https://www.prosieben.de/serien/joko-klaas-live-die-schatzsuche/videos/lesung-konzert-v_yd0czlu26gxi']
Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                    You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (zip)
[debug] Python 3.7.3 (CPython armv7l 32bit) - Linux-5.10.103-v7l+-armv7l-with-debian-10.13 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.28)
[debug] exe versions: ffmpeg 4.1.11-0, ffprobe 4.1.11-0
[debug] Optional libraries: Cryptodome-3.19.0, certifi-2018.08.24, secretstorage-2.3.1, sqlite3-3.27.2
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: be5cfb6be8930e1a5f427533ec32f2a481276b3da7b249d0150ce2b740ccf1ce
yt-dlp is up to date (stable@2023.10.13)
[prosiebensat1] Extracting URL: https://www.prosieben.de/serien/joko-klaas-live-die-schatzsuche/videos/lesung-konzert-v_yd0czlu26gxi
[prosiebensat1] serien/joko-klaas-live-die-schatzsuche/videos/lesung-konzert-v_yd0czlu26gxi: Downloading webpage
ERROR: [prosiebensat1] serien/joko-klaas-live-die-schatzsuche/videos/lesung-konzert-v_yd0czlu26gxi: Unable to extract clip id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "../yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "../yt-dlp/yt_dlp/extractor/prosiebensat1.py", line 491, in _real_extract
    return self._extract_clip(url, webpage)
  File "../yt-dlp/yt_dlp/extractor/prosiebensat1.py", line 432, in _extract_clip
    self._CLIPID_REGEXES, webpage, 'clip id')
  File "../yt-dlp/yt_dlp/extractor/common.py", line 1299, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "../yt-dlp/yt_dlp/extractor/common.py", line 1263, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by danielmarschall** [comment] 2023-11-09 20:39
It turns out that this PR fixes the problem : https://github.com/yt-dlp/yt-dlp/pull/5593

Is there any chance that this gets included?

**Comment by bashonly** [comment] 2023-11-09 20:41
Have you actually tested that PR? I don't think it works, which is why it hasn't been merged

Closing as duplicate of #7264

**Closed by bashonly** 2023-11-09 20:41 UTC
Labels: site-bug, triage

**Comment by danielmarschall** [comment] 2023-11-09 20:57
After I downloaded the file, it turns out that the download actually didn't work.

The downloaded video file is just a black screen with the following text

Diese App wurde eingestellt.
Die Inhalte findest Du jetzt bei Joyn.
Bitte lade Dir die Joyn App im App-Store herunter.

(This app was discontinued. You will find the contents at Joyn.)

So the whole prosiebensat1 downloader seems to be obsolete??

**Comment by danielmarschall** [comment] 2023-11-13 22:25
@bashonly  I have looked further in this topic. Can you please re-open this ticket?

Here is how I can get to the video file. I am not sure how the extractor code works, but since the extractor code says "VAS v4" and the current service is also called "VAS v4", I understand that there are probably only a few differences, and I think the plugin can be modified to make it work.

Public URL:
https://www.prosieben.de/serien/joko-klaas-live-die-schatzsuche/videos/lesung-konzert-v_yd0czlu26gxi

This file is accessed in Chrome (but where do we get the JWT token?):
https://vas-v4.p7s1video.net/4.0/getsources?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Inhfc3VwZXJub3ZhdHZjLWRlIn0.eyJjb250ZW50X2lkcyI6eyJ2X3lkMGN6bHUyNmd4aSI6e319LCJzZWN1cmVfZGVsaXZlcnkiOnRydWUsImlhdCI6MTY5OTkxMjU4MiwibmJmIjoxNjk5OTEyMjgyLCJleHAiOjE2OTk5MTI4ODJ9.vPomNSmOsd5Wh1pNjBRuyEO4fRCWM2norj4V62UQX-I

Inside this "getsources" file, you wil find the video file:
https://p7s1-vod-001-prod.akamaized.net/02/v/t_001/4.0/progressive/clear/01/REbxn8rhHFGJUMAcT71XGMO65NWBQIBWUl-WawovzhyOT1fY0KKNyDlDdsXhDuqaA_HLypp48ItcvS1-8kVFf_GxxdNR7KUvRdMOhoU3iFlZ0NbhU5seGf3mli2ohMs1izaoZDu3HENmo9ga5wgwfim6LXxtoQG9d_J9i4xeFaA/v.ism/x.mp4?hdnea=st=1699912616~exp=1699920099~acl=%2AREbxn8rhHFGJUMAc%2A~hmac=bdfdf2b458c98b9f332120d33a79f2fd0ec3a002cbcb53ae76b6430e977a112d

**Comment by bashonly** [comment] 2023-11-13 22:33
It was closed because it's a duplicate. Post your findings in #7264 where we are tracking this

**Comment by danielmarschall** [comment] 2023-11-13 22:56
@bashonly Thanks for the clarification! Sorry, I was confused.
