### ISSUE TITLE
Initial Player Response Error

### ISSUE THREAD

**Issue by edenlith** [yt-dlp/yt-dlp#8126] opened 2023-09-16 17:34 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi guys. This might be a noob question but when I download a video I receive a warning (pasted down under). I just want to know why am I getting this warning and if there's anything I could do to stop getting it. 

Thanks.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
"WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] -uM5oFvuQbE: Downloading ios player API JSON
[youtube] -uM5oFvuQbE: Downloading android player API JSON
[youtube] -uM5oFvuQbE: Downloading iframe API JS
[youtube] -uM5oFvuQbE: Downloading player afd1b6e5
[youtube] -uM5oFvuQbE: Downloading web player API JSON
[youtube] -uM5oFvuQbE: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] -uM5oFvuQbE: Downloading initial data API JSON"
```

**Comment by bashonly** [comment] 2023-09-16 17:44
> just want to know ... if there's anything I could do to stop getting it.

`yt-dlp --update-to nightly`

Duplicate of #7594

**Closed by bashonly** 2023-09-16 17:44 UTC
Labels: question

**Comment by edenlith** [comment] 2023-09-16 17:56
Thank you very much. It solved the problem. Case closed.
