### ISSUE TITLE
No format found error 

### ISSUE THREAD

**Issue by dotjsNet** [yt-dlp/yt-dlp#11369] opened 2024-10-27 12:53 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Error: ERROR: [facebook] 1212065173146104: No video formats found!; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U
<img width="1452" alt="Screenshot 2024-10-27 at 4 51 08 pm" src="https://github.com/user-attachments/assets/1922d229-11d0-4755-bcc6-20198b37d8a6">
facing that issue here https://toolstackfree.com/facebook-videos-downloader thanks for your attention. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Python integration...

Error: ERROR: [facebook] 1212065173146104: No video formats found!; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

the link that was tested https://www.facebook.com/reel/1212065173146104
```

**Comment by seproDev** [comment] 2024-10-27 12:56
This site is not run by us. yt-dlp is a command line application with no official website. You will need to contact the site's owner and ask them to update yt-dlp.

Duplicate of #11337

**Closed by seproDev** 2024-10-27 12:56 UTC
Labels: duplicate, site:facebook
