### ISSUE TITLE
Combine merging operations for more efficiency

### ISSUE THREAD

**Issue by mikepiman** [yt-dlp/yt-dlp#10575] opened 2024-07-27 10:18 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [x] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Could the various "merging" operations be **combined** when possible, instead of doing them one at a time?  This would save a lot of disk writing time and wear&tear.  In the attached example, the output file was written nearly 4 times:  for merging, then container conversion, then metadata, then thumbnail. 

Is ffmpeg capable of this?
At least when converting to MKV, **mkvmerge** will combine all operations.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Formats sorted by: hasvid, ie_pref, +acodec, proto, res, +vcodec, quality, fps, hdr:12(7), source, channels, lang, size, br, asr, vext, aext, hasaud, id
[info] zLKktS61JrM: Downloading 1 format(s): 234+137
[info] Writing video description to: Who were the first people in recorded history？ [zLKktS61JrM].description
Deleting existing file Who were the first people in recorded history？ [zLKktS61JrM].en.vtt
[info] Writing video subtitles to: Who were the first people in recorded history？ [zLKktS61JrM].en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=zLKktS61JrM&ei=mcOkZpr3POmUybgP_Mu9yAY&caps=asr&opi=112496729&exp=xbt&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1722099210&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cei%2Ccaps%2Copi%2Cexp%2Cxoaf&signature=0DD883B809457BCB597296833225097E550DE697.6DEC9F505C69FB11B33DA0BDD36213FFD36BC2A8&key=yt8&lang=en&fmt=vtt"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Who were the first people in recorded history？ [zLKktS61JrM].en.vtt
[download] 100% of   59.98KiB in 00:00:00 at 638.08KiB/s
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: Who were the first people in recorded history？ [zLKktS61JrM].webp
[download] Who were the first people in recorded history？ [zLKktS61JrM].mkv has already been downloaded
[VideoRemuxer] Not remuxing media file "Who were the first people in recorded history？ [zLKktS61JrM].mkv"; already is in target format mkv
[Metadata] Adding metadata to "Who were the first people in recorded history？ [zLKktS61JrM].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:Who were the first people in recorded history ？ [zLKktS61JrM].mkv" -i "file:Who were the first people in recorded history？ [zLKktS61JrM].meta" -map 0 -dn -ignore_unknown -c copy -map_metadata 1 -movflags +faststart "file:Who were the first people in recorded history？ [zLKktS61JrM].temp.mkv"
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:Who were the first people in recorded history？ [zLKktS61JrM].mkv"
[EmbedThumbnail] ffmpeg: Adding thumbnail to "Who were the first people in recorded history？ [zLKktS61JrM].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:Who were the first people in recorded history ？ [zLKktS61JrM].mkv" -map 0 -dn -ignore_unknown -c copy -map -0:2 -attach "file:Who were the first people in recorded history？ [zLKktS61JrM].webp" -metadata:s:2 "mimetype=image/webp" -metadata:s:2 "filename=cover.webp" -movflags +faststart "file:Who were the first people in recorded history？ [zLKktS61JrM].temp.mkv"
```

**Comment by bashonly** [comment] 2024-07-27 15:08
Duplicate of #126

**Closed by bashonly** 2024-07-27 15:08 UTC
Labels: enhancement, triage
