### ISSUE TITLE
TELE5 partially DRM locked (Missing deviceId in context)

### ISSUE THREAD

**Issue by KodJak7549** [yt-dlp/yt-dlp#3623] opened 2022-05-02 21:06 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Problem:
The video in the following link can't be downloaded (see verbose log).

The problem seams to be a new DRM system. If I activate "Play DRM media" in Firefox (99.0.1 64 bit), the video can be played. If I deactivate this function, the video can't be played.

### "Solution":
Bypass / crack DRM (yeah... I know....).

### Proposed solution:
None.

### FYI:
I guess this issue is more for documentation purposes as another series (Gene Roddenberry's Andromeda) doesn't work either (see [issue 3183](https://github.com/yt-dlp/yt-dlp/issues/3183))

Tested the following currently running series for the same problem (FYI for others who are looking for this problem):

The following series **STILL WORK**:
- Star Trek: Discovery
- Ghost Adventures

The following series **DON'T WORK** (ERROR: [Tele5] EPISODE_NAME_HERE: Missing deviceId in context):
- Gene Roddenberry's Andromeda (not currently running but added for documentation -> see [issue 3183](https://github.com/yt-dlp/yt-dlp/issues/3183)) 
- Kampfstern Galactica
- Star Trek: Raumschiff Enterprise
- Star Trek: Das nächste Jahrhundert
- Star Trek: Raumschiff Voyager
- Star Trek: Deep Space Nine
- Relic Hunter - Die Schatzjägerin
- Buck Rogers

### Verbose log

```shell
yt-dlp https://tele5.de/mediathek/star-trek-raumschiff-voyager/der-fursorger-1/ -vU
[debug] Command-line config: ['https://tele5.de/mediathek/star-trek-raumschiff-voyager/der-fursorger-1/', '-vU']
[debug] User config "/home/REDACTED/.config/yt-dlp/config": ['-o', '~/REDACTED/%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.10.109-1-MANJARO-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: brotlicffi, certifi, Cryptodome, mutagen, sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] Using fake IP 53.89.72.159 (DE) as X-Forwarded-For
[debug] [Tele5] Extracting URL: https://tele5.de/mediathek/star-trek-raumschiff-voyager/der-fursorger-1/
[Tele5] der-fursorger-1: Downloading webpage
[Tele5] 2238020: Downloading token
[Tele5] 2238020: Downloading JSON metadata
[Tele5] 2238020: Downloading JSON metadata
ERROR: [Tele5] der-fursorger-1: Missing deviceId in context
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/tele5.py", line 87, in _real_extract
    return self._get_disco_api_info(url, asset_id, endpoint, realm, country)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/dplay.py", line 104, in _get_disco_api_info
    self._process_errors(e, geo_countries)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/dplay.py", line 52, in _process_errors
    raise ExtractorError(info['errors'][0]['detail'], expected=True)
```

**Comment by pukkandan** [comment] 2022-05-02 21:12
Effectively duplicate of https://github.com/yt-dlp/yt-dlp/issues/3183

**Closed by pukkandan** 2022-05-02 21:12 UTC
Labels: site-bug, triage
