### ISSUE TITLE
download-archive parameter could apply output file template

### ISSUE THREAD

**Issue by audryste** [yt-dlp/yt-dlp#1725] opened 2021-11-20 01:46 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

--download-archive parameter could apply output file template. Sample usage could be:

yt-dlp.ex -f "ba" -x --audio-format flac --download-archive "%(playlist_title)sArchiveVideos.txt" https://www.youtube.com/playlist?list=PLjmqT_NbGciuxxNHpz1rDLNxcl42XH5Tb -o "%(playlist_title)s/%(playlist_index)s-%(title)s.%(ext)s"

Some playlists may have same file, it will be found in archives. So it would be nice to have separate archives for each playlist.

**Comment by pukkandan** [comment] 2021-11-20 02:38
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/953

**Closed by pukkandan** 2021-11-20 02:38 UTC
Labels: enhancement, triage
