### ISSUE TITLE
Rumble livestream download (from previous livestreams)

### ISSUE THREAD

**Issue by thisisawesome1994** [yt-dlp/yt-dlp#11081] opened 2024-09-25 04:06 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Netherlands

### Provide a description that is worded well enough to be understood

Hi,

The rumble livestream directory of a /user/BLCKBX/livestreams is downloading a lot of pages without actually starting any download, more then are available on the website through a browser, and it also doesnt download because the script ends with an error without downloading anything. (livestream tab from livestreams in the past)

Awaiting your solution.

J

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp.exe -vU "https://rumble.com/user/BLCKBX/livestreams"
[debug] Command-line config: ['-vU', 'https://rumble.com/user/BLCKBX/livestreams']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 7.0.1-full_build-www.gyan.dev (setts), ffprobe 7.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[RumbleChannel] Extracting URL: https://rumble.com/user/BLCKBX/livestreams
[download] Downloading playlist: BLCKBX
[RumbleChannel] BLCKBX: Downloading page 1
[RumbleChannel] BLCKBX: Downloading page 2
[RumbleChannel] BLCKBX: Downloading page 3
[RumbleChannel] BLCKBX: Downloading page 4
[RumbleChannel] BLCKBX: Downloading page 5
[RumbleChannel] BLCKBX: Downloading page 6
[RumbleChannel] BLCKBX: Downloading page 7
[RumbleChannel] BLCKBX: Downloading page 8
[RumbleChannel] BLCKBX: Downloading page 9
[RumbleChannel] BLCKBX: Downloading page 10
[RumbleChannel] BLCKBX: Downloading page 11
[RumbleChannel] BLCKBX: Downloading page 12
[RumbleChannel] BLCKBX: Downloading page 13
[RumbleChannel] BLCKBX: Downloading page 14
[RumbleChannel] BLCKBX: Downloading page 15
[RumbleChannel] BLCKBX: Downloading page 16
[RumbleChannel] BLCKBX: Downloading page 17
[RumbleChannel] BLCKBX: Downloading page 18
[RumbleChannel] BLCKBX: Downloading page 19
[RumbleChannel] BLCKBX: Downloading page 20
[RumbleChannel] BLCKBX: Downloading page 21
[RumbleChannel] BLCKBX: Downloading page 22
[RumbleChannel] BLCKBX: Downloading page 23
[RumbleChannel] BLCKBX: Downloading page 24
[RumbleChannel] BLCKBX: Downloading page 25
[RumbleChannel] BLCKBX: Downloading page 26
[RumbleChannel] BLCKBX: Downloading page 27
[RumbleChannel] BLCKBX: Downloading page 28
[RumbleChannel] BLCKBX: Downloading page 29
[RumbleChannel] BLCKBX: Downloading page 30
[RumbleChannel] BLCKBX: Downloading page 31
[RumbleChannel] BLCKBX: Downloading page 32
[RumbleChannel] BLCKBX: Downloading page 33
[RumbleChannel] BLCKBX: Downloading page 34
[RumbleChannel] BLCKBX: Downloading page 35
[RumbleChannel] BLCKBX: Downloading page 36
[RumbleChannel] BLCKBX: Downloading page 37
[RumbleChannel] BLCKBX: Downloading page 38
[RumbleChannel] BLCKBX: Downloading page 39
[RumbleChannel] BLCKBX: Downloading page 40
[RumbleChannel] BLCKBX: Downloading page 41
[RumbleChannel] BLCKBX: Downloading page 42
[RumbleChannel] BLCKBX: Downloading page 43
[RumbleChannel] BLCKBX: Downloading page 44
[RumbleChannel] BLCKBX: Downloading page 45
[RumbleChannel] BLCKBX: Downloading page 46
[RumbleChannel] BLCKBX: Downloading page 47
[RumbleChannel] BLCKBX: Downloading page 48
[RumbleChannel] BLCKBX: Downloading page 49
[RumbleChannel] BLCKBX: Downloading page 50
[RumbleChannel] BLCKBX: Downloading page 51
[RumbleChannel] BLCKBX: Downloading page 52
[RumbleChannel] BLCKBX: Downloading page 53
[RumbleChannel] BLCKBX: Downloading page 54
[RumbleChannel] BLCKBX: Downloading page 55
[RumbleChannel] BLCKBX: Downloading page 56
[RumbleChannel] BLCKBX: Downloading page 57
[RumbleChannel] BLCKBX: Downloading page 58
[RumbleChannel] BLCKBX: Downloading page 59
[RumbleChannel] BLCKBX: Downloading page 60
[RumbleChannel] BLCKBX: Downloading page 61
[RumbleChannel] BLCKBX: Downloading page 62
[RumbleChannel] BLCKBX: Downloading page 63
[RumbleChannel] BLCKBX: Downloading page 64
[RumbleChannel] BLCKBX: Downloading page 65
[RumbleChannel] BLCKBX: Downloading page 66
[RumbleChannel] BLCKBX: Downloading page 67
[RumbleChannel] BLCKBX: Downloading page 68
[RumbleChannel] BLCKBX: Downloading page 69
[RumbleChannel] BLCKBX: Downloading page 70
[RumbleChannel] BLCKBX: Downloading page 71
[RumbleChannel] BLCKBX: Downloading page 72
[RumbleChannel] BLCKBX: Downloading page 73
[RumbleChannel] BLCKBX: Downloading page 74
[RumbleChannel] Playlist BLCKBX: Downloading 0 items
[download] Finished downloading playlist: BLCKBX
```

**Comment by bashonly** [comment] 2024-09-25 04:12
Duplicate of #10833

**Closed by bashonly** 2024-09-25 04:12 UTC
Labels: site-bug, triage
