### ISSUE TITLE
Multiple warnings/errors and download becomes incomplete on Bilibili

### ISSUE THREAD

**Issue by stuffed18** [yt-dlp/yt-dlp#8699] opened 2023-12-02 10:11 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

I am attempting to download a video from Bilibili.tv using yt-dlp.exe on windows 10. 
The command I am using to download is `yt-dlp.exe https://www.bilibili.tv/en/video/12345678 ` but with the real video link. 
I get this output when doing so:

`[BiliIntl] Extracting URL: https://www.bilibili.tv/en/video/2041676096
[BiliIntl] 2041676096: Downloading webpage
WARNING: [BiliIntl] unable to extract JSON-LD ; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [BiliIntl] unable to extract og:title; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [BiliIntl] unable to extract og:description; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[BiliIntl] 2041676096: Downloading video formats
[info] 2041676096: Downloading 1 format(s): 10+2
WARNING: You have requested merging of multiple formats but ffmpeg is not installed. The formats won't be merged
[download] Destination: Hilda Season 2 Episode 2 Chapter 2 [2041676096].f10.mp4
[download]  51.4% of  123.15MiB at    5.13MiB/s ETA 00:11[download] Got error: 67108864 bytes read, 62026108 more expected. Retrying (1/10)...
[download] Destination: Hilda Season 2 Episode 2 Chapter 2 [2041676096].f10.mp4
[download]  51.8% of  123.15MiB at    5.81MiB/s ETA 00:10[download] Got error: 736338 bytes read, 62026108 more expected. Retrying (2/10)...
[download] Destination: Hilda Season 2 Episode 2 Chapter 2 [2041676096].f10.mp4
[download]  51.9% of  123.15MiB at    7.54MiB/s ETA 00:07[download] Got error: 213074 bytes read, 62026108 more expected. Retrying (3/10)...
[download] Destination: Hilda Season 2 Episode 2 Chapter 2 [2041676096].f10.mp4
[download]  52.0% of  123.15MiB at    3.96MiB/s ETA 00:14[download] Got error: 83026 bytes read, 62026108 more expected. Retrying (4/10)...
[download] Destination: Hilda Season 2 Episode 2 Chapter 2 [2041676096].f10.mp4
[download]  52.0% of  123.15MiB at  904.59KiB/s ETA 01:06[download] Got error: 18514 bytes read, 62026108 more expected. Retrying (5/10)...
[download] Destination: Hilda Season 2 Episode 2 Chapter 2 [2041676096].f10.mp4
[download]  52.0% of  123.15MiB at  Unknown B/s ETA Unknown[download] Got error: 3154 bytes read, 62026108 more expected. Retrying (6/10)...
[download] Got error: 82 bytes read, 62026108 more expected. Retrying (7/10)...
[download] Got error: 82 bytes read, 62026108 more expected. Retrying (8/10)...
[download] Got error: 82 bytes read, 62026108 more expected. Retrying (9/10)...
[download] Got error: 82 bytes read, 62026108 more expected. Retrying (10/10)...
[download] Got error: 82 bytes read, 62026108 more expected. Giving up after 10 retries

[download] Destination: Hilda Season 2 Episode 2 Chapter 2 [2041676096].f2.mp4
[download] 100% of   21.19MiB in 00:00:03 at 6.15MiB/s`

The output I eventually get is an audio file (.f2 format) and a .part file. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.bilibili.tv/en/video/2041676096']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[BiliIntl] Extracting URL: https://www.bilibili.tv/en/video/2041676096
[BiliIntl] 2041676096: Downloading webpage
WARNING: [BiliIntl] unable to extract JSON-LD ; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [BiliIntl] unable to extract og:title; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [BiliIntl] unable to extract og:description; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[BiliIntl] 2041676096: Downloading video formats
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 2041676096: Downloading 1 format(s): 10+2
WARNING: You have requested merging of multiple formats but ffmpeg is not installed. The formats won't be merged
[debug] Invoking http downloader on "https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/un/6y/n220614ad1yyjght30zefepy2src6yun-1-141220110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1701519046&gen=playurlv2&os=akam&oi=2510794197&trid=64d9127043bc4087bcbd0fc388624005i&mid=0&platform=pc&upsig=e0b3309e9f9edfe888a54cec9dc96afc&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1701519046~hmac=8a8b35b137318ec23078e7855e6dacfabb20d84dbac9a3209545e2f74160c0c8&bvc=vod&nettype=0&orderid=0,1&logo=00000000&f=i_0_0"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Hilda Season 2 Episode 2 Chapter 2 [2041676096].f10.mp4
[download]  52.0% of  123.15MiB at    6.17MiB/s ETA 00:09[download] Got error: 67108864 bytes read, 62026108 more expected. Retrying (1/10)...
[download] Destination: Hilda Season 2 Episode 2 Chapter 2 [2041676096].f10.mp4
[download]  52.0% of  123.15MiB at  Unknown B/s ETA Unknown[download] Got error: 1024 bytes read, 62026108 more expected. Retrying (2/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (3/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (4/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (5/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (6/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (7/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (8/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (9/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Retrying (10/10)...
[download] Got error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). Giving up after 10 retries
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1008, in main
  File "yt_dlp\__init__.py", line 998, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3511, in download
  File "yt_dlp\YoutubeDL.py", line 3486, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1556, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1723, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1782, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2922, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3370, in process_info
  File "yt_dlp\YoutubeDL.py", line 3109, in dl
  File "yt_dlp\downloader\common.py", line 455, in download
  File "yt_dlp\downloader\http.py", line 362, in real_download
  File "yt_dlp\utils\_utils.py", line 5114, in __iter__
  File "yt_dlp\downloader\common.py", line 401, in report_retry
  File "yt_dlp\utils\_utils.py", line 5121, in report_retry
  File "yt_dlp\downloader\common.py", line 404, in <lambda>
  File "yt_dlp\YoutubeDL.py", line 1045, in report_error
  File "yt_dlp\YoutubeDL.py", line 973, in trouble


[debug] Invoking http downloader on "https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/un/6y/n220614ad1yyjght30zefepy2src6yun-1-1c1301000023.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1701519046&gen=playurlv2&os=akam&oi=2510794197&trid=49ed2ad0b4f64f119e3e6072c6e4e619i&mid=0&platform=pc&upsig=baab76357702e43f21f0b4033f7fa665&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1701519046~hmac=60a1c4d55969683ec43ce4615510dff463de14ed5b6b21e2caf7137f764933f8&bvc=vod&nettype=0&orderid=0,1&logo=00000000&f=i_0_0"
[download] Destination: Hilda Season 2 Episode 2 Chapter 2 [2041676096].f2.mp4
[download] 100% of   21.19MiB in 00:00:03 at 6.36MiB/s
```

**Comment by bashonly** [comment] 2023-12-06 18:37
Duplicate of #8044

**Closed by bashonly** 2023-12-06 18:37 UTC
Labels: site-bug, triage
