### ISSUE TITLE
[Dailymotion][Live] '[height<=720]' picks a 1080p stream

### ISSUE THREAD

**Issue by pihug12** [yt-dlp/yt-dlp#10064] opened 2024-05-29 23:33 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

`yt-dlp -f '[height<=720]' --simulate https://www.dailymotion.com/video/x2lefik` picks a 1080p stream (which is tagged 1280x720 in the M3U8 file).

```
$ yt-dlp -F https://www.dailymotion.com/video/x2lefik
[dailymotion] Extracting URL: https://www.dailymotion.com/video/x2lefik
[dailymotion] Downloading Access Token
[dailymotion] x2lefik: Downloading media JSON metadata
[dailymotion] x2lefik: Downloading metadata JSON
[dailymotion] x2lefik: Downloading m3u8 information
[info] Available formats for x2lefik:
ID    EXT RESOLUTION FPS │   TBR PROTO │ VCODEC      ACODEC
──────────────────────────────────────────────────────────────
hls-0 mp4 320x180     25 │  475k m3u8  │ avc1.42000c mp4a.40.5
hls-1 mp4 320x180     25 │  475k m3u8  │ avc1.42000c mp4a.40.5
hls-2 mp4 512x288     25 │  782k m3u8  │ avc1.420015 mp4a.40.5
hls-3 mp4 512x288     25 │  782k m3u8  │ avc1.420015 mp4a.40.5
hls-4 mp4 848x477     25 │ 1360k m3u8  │ avc1.64001e mp4a.40.2
hls-5 mp4 848x477     25 │ 1360k m3u8  │ avc1.64001e mp4a.40.2
hls-6 mp4 1280x720    25 │ 2179k m3u8  │ avc1.64001f mp4a.40.2
hls-7 mp4 1280x720    25 │ 2179k m3u8  │ avc1.64001f mp4a.40.2
hls-8 mp4 1920x1080   25 │ 6275k m3u8  │ avc1.640028 mp4a.40.2
```

yt-dlp picks "hls-7" which is a 1080p in reality whereas "hls-6" is a real 720p stream.

The M3U8 file (found in there https://www.dailymotion.com/player/metadata/video/x2lefik) looks like this:
```
#EXTM3U
#EXT-X-STREAM-INF:RESOLUTION=848x477,FRAME-RATE=25.000000,BANDWIDTH=1359872,CODECS="avc1.64001e,mp4a.40.2",NAME="480"
https://live-b.cf.dmcdn.net/sec2(VeQxFk8AeBFx-iq0GMvSfoUWKgFkZA0IvJ7lpfSJPxPCTNJzdJYc_MLLgIiSJgV8ish5ptQQVZDZbWuJHBoNHe9SAxcRDV9U0kvyah17UuE)/dm/3/x2lefik/d/live-2.m3u8#cell=lcfb
#EXT-X-STREAM-INF:RESOLUTION=848x477,FRAME-RATE=25.000000,BANDWIDTH=1359872,CODECS="avc1.64001e,mp4a.40.2",NAME="480"
https://live-b.cf.dmcdn.net/sec2(C489n-mt3VG_mZu-bwEEv19_jtpKublj4L75x3x3DvAbMAUmX9LV3E6S4Mn-WL7nhY0DTN1KGbmvGiL9_kKBqsiNuMS7TIxsSQXBBpL58rk)/dm/3/x6saxk1/s/live-2.m3u8
#EXT-X-STREAM-INF:RESOLUTION=320x180,FRAME-RATE=25.000000,BANDWIDTH=475136,CODECS="avc1.42000c,mp4a.40.5",NAME="240"
https://live-b.cf.dmcdn.net/sec2(VeQxFk8AeBFx-iq0GMvSfoUWKgFkZA0IvJ7lpfSJPxPCTNJzdJYc_MLLgIiSJgV8ish5ptQQVZDZbWuJHBoNHe9SAxcRDV9U0kvyah17UuE)/dm/3/x2lefik/d/live-0.m3u8#cell=lcfb
#EXT-X-STREAM-INF:RESOLUTION=320x180,FRAME-RATE=25.000000,BANDWIDTH=475136,CODECS="avc1.42000c,mp4a.40.5",NAME="240"
https://live-b.cf.dmcdn.net/sec2(C489n-mt3VG_mZu-bwEEv19_jtpKublj4L75x3x3DvAbMAUmX9LV3E6S4Mn-WL7nhY0DTN1KGbmvGiL9_kKBqsiNuMS7TIxsSQXBBpL58rk)/dm/3/x6saxk1/s/live-0.m3u8
#EXT-X-STREAM-INF:RESOLUTION=512x288,FRAME-RATE=25.000000,BANDWIDTH=782336,CODECS="avc1.420015,mp4a.40.5",NAME="380"
https://live-b.cf.dmcdn.net/sec2(VeQxFk8AeBFx-iq0GMvSfoUWKgFkZA0IvJ7lpfSJPxPCTNJzdJYc_MLLgIiSJgV8ish5ptQQVZDZbWuJHBoNHe9SAxcRDV9U0kvyah17UuE)/dm/3/x2lefik/d/live-1.m3u8#cell=lcfb
#EXT-X-STREAM-INF:RESOLUTION=512x288,FRAME-RATE=25.000000,BANDWIDTH=782336,CODECS="avc1.420015,mp4a.40.5",NAME="380"
https://live-b.cf.dmcdn.net/sec2(C489n-mt3VG_mZu-bwEEv19_jtpKublj4L75x3x3DvAbMAUmX9LV3E6S4Mn-WL7nhY0DTN1KGbmvGiL9_kKBqsiNuMS7TIxsSQXBBpL58rk)/dm/3/x6saxk1/s/live-1.m3u8
#EXT-X-STREAM-INF:RESOLUTION=1280x720,FRAME-RATE=25.000000,BANDWIDTH=2179072,CODECS="avc1.64001f,mp4a.40.2",NAME="720"
https://live-b.cf.dmcdn.net/sec2(VeQxFk8AeBFx-iq0GMvSfoUWKgFkZA0IvJ7lpfSJPxPCTNJzdJYc_MLLgIiSJgV8ish5ptQQVZDZbWuJHBoNHe9SAxcRDV9U0kvyah17UuE)/dm/3/x2lefik/d/live-3.m3u8#cell=lcfb
#EXT-X-STREAM-INF:RESOLUTION=1280x720,FRAME-RATE=25.000000,BANDWIDTH=2179072,CODECS="avc1.64001f,mp4a.40.2",NAME="720"
https://live-b.cf.dmcdn.net/sec2(C489n-mt3VG_mZu-bwEEv19_jtpKublj4L75x3x3DvAbMAUmX9LV3E6S4Mn-WL7nhY0DTN1KGbmvGiL9_kKBqsiNuMS7TIxsSQXBBpL58rk)/dm/3/x6saxk1/s/live-3.m3u8
#EXT-X-STREAM-INF:RESOLUTION=1920x1080,FRAME-RATE=25.000000,BANDWIDTH=6275072,CODECS="avc1.640028,mp4a.40.2",NAME="1080"
https://live-b.cf.dmcdn.net/sec2(VeQxFk8AeBFx-iq0GMvSfoUWKgFkZA0IvJ7lpfSJPxPCTNJzdJYc_MLLgIiSJgV8ish5ptQQVZDZbWuJHBoNHe9SAxcRDV9U0kvyah17UuE)/dm/3/x2lefik/d/live-4.m3u8#cell=lcfb
```

Does the streams with `/x6saxk1/` should be ignored to keep only the streams with `/x2lefik/` (the ID of the video asked)?

I think there should be only 5 formats used by yt-dlp and not 9?

"https://live-b.cf.dmcdn.net/sec2(VeQxFk8AeBFx-iq0GMvSfoUWKgFkZA0IvJ7lpfSJPxPCTNJzdJYc_MLLgIiSJgV8ish5ptQQVZDZbWuJHBoNHe9SAxcRDV9U0kvyah17UuE)/dm/3/x2lefik/d/live-3.m3u8#cell=lcfb" is the correct 720p stream.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[myThinkPad ~]$ yt-dlp -vU -f '[height<=720]' --simulate https://www.dailymotion.com/video/x2lefik[debug] Command-line config: ['-vU', '-f', '[height<=720]', '--simulate', 'https://www.dailymotion.com/video/x2lefik']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (pip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.9-200.fc39.x86_64-x86_64-with-glibc2.38 (OpenSSL 3.1.1 30 May 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.05.07, mutagen-1.46.0, requests-2.32.2, sqlite3-3.42.0, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[dailymotion] Extracting URL: https://www.dailymotion.com/video/x2lefik
[dailymotion] Downloading Access Token
[dailymotion] x2lefik: Downloading media JSON metadata
[dailymotion] x2lefik: Downloading metadata JSON
[dailymotion] x2lefik: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] x2lefik: Downloading 1 format(s): hls-7
[myThinkPad ~]$
[myThinkPad ~]$
[myThinkPad ~]$ yt-dlp -vU -F https://www.dailymotion.com/video/x2lefik
[debug] Command-line config: ['-vU', '-F', 'https://www.dailymotion.com/video/x2lefik']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (pip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.9-200.fc39.x86_64-x86_64-with-glibc2.38 (OpenSSL 3.1.1 30 May 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.05.07, mutagen-1.46.0, requests-2.32.2, sqlite3-3.42.0, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[dailymotion] Extracting URL: https://www.dailymotion.com/video/x2lefik
[dailymotion] Downloading Access Token
[dailymotion] x2lefik: Downloading media JSON metadata
[dailymotion] x2lefik: Downloading metadata JSON
[dailymotion] x2lefik: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for x2lefik:
ID    EXT RESOLUTION FPS │   TBR PROTO │ VCODEC      ACODEC
──────────────────────────────────────────────────────────────
hls-0 mp4 320x180     25 │  475k m3u8  │ avc1.42000c mp4a.40.5
hls-1 mp4 320x180     25 │  475k m3u8  │ avc1.42000c mp4a.40.5
hls-2 mp4 512x288     25 │  782k m3u8  │ avc1.420015 mp4a.40.5
hls-3 mp4 512x288     25 │  782k m3u8  │ avc1.420015 mp4a.40.5
hls-4 mp4 848x477     25 │ 1360k m3u8  │ avc1.64001e mp4a.40.2
hls-5 mp4 848x477     25 │ 1360k m3u8  │ avc1.64001e mp4a.40.2
hls-6 mp4 1280x720    25 │ 2179k m3u8  │ avc1.64001f mp4a.40.2
hls-7 mp4 1280x720    25 │ 2179k m3u8  │ avc1.64001f mp4a.40.2
hls-8 mp4 1920x1080   25 │ 6275k m3u8  │ avc1.640028 mp4a.40.2
[myThinkPad ~]$
```
```

**Comment by bashonly** [comment] 2024-05-31 00:34
is this reproducible with other videos? or only this one?

**Comment by bashonly** [comment] 2024-07-20 04:46
Closing as incomplete. Can re-open if anyone can provide other examples / demonstrate that the issue is widespread across dailymotion

**Closed by bashonly** 2024-07-20 04:46 UTC
Labels: incomplete, site-bug, triage
