### ISSUE TITLE
What is keeping me from the HD versions on Vimeo

### ISSUE THREAD

**Issue by djrbos** [yt-dlp/yt-dlp#4126] opened 2022-06-20 19:24 UTC
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

Couldn't download this video with the master.json link So today i tried using different links that end in .mp4, there are different links for each quality ie 240 504 720 1080 some of the lower res links work out of the box, no headers no cookies, the higher res do not work with cookies or headers, in fact it says it can't send head request and suggests opening an issue on github.  Not sure what is keeping me from the 1080p version...

First one is the 720p link, Second one is the 1080p link both fail, the last one is the 504p version and it works.

any idea what the reason is?

### Verbose log

```shell
C:\youtube-dl>yt-dlp --verbose https://17vod-adaptive.akamaized.net/exp=16557720
61acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2Ahmac=ab26adba64ac7933551d96
d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-043e6c701ab0/
parcel/video/0ea30f4d.mp4
[debug] Command-line config: ['--verbose', 'https://17vod-adaptive.akamaized.net
/exp=1655772061acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2Ahmac=ab26adba6
4ac7933551d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-
043e6c701ab0/parcel/video/0ea30f4d.mp4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No ANSI), er
ror utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.05.18 [https://github.com/yt-dlp/yt-dlp/commit/b14d523558c04dd0c3ae17877f22f707a805cf5b] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg n4.4.1-14-g5a7763bdfa-20220109 (setts)
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08,
mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://17vod-adaptive.akamaized.net/exp=16557
72061acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2Ahmac=ab26adba64ac7933551
d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-043e6c701a
b0/parcel/video/0ea30f4d.mp4
[generic] 0ea30f4d: Requesting header
WARNING: [generic] Could not send HEAD request to https://17vod-adaptive.akamaiz/
ed.net/exp=1655772061acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2Ahmac=ab2
6adba64ac7933551d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6
-9e8e-043e6c701ab0/parcel/video/0ea30f4d.mp4: HTTP Error 403: Forbidden
[generic] 0ea30f4d: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused b
y <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/
/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm y
ou are on the latest version using yt-dlp -U
File "yt_dlp\extractor\common.py", line 642, in extract
File "yt_dlp\extractor\generic.py", line 2737, in _real_extract
File "yt_dlp\extractor\common.py", line 786, in _request_webpage

File "yt_dlp\extractor\common.py", line 768, in _request_webpage
File "yt_dlp\YoutubeDL.py", line 3596, in urlopen
File "urllib\request.py", line 531, in open
File "urllib\request.py", line 640, in http_response
File "urllib\request.py", line 569, in error
File "urllib\request.py", line 502, in _call_chain
File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

C:\youtube-dl>yt-dlp --verbose https://17vod-adaptive.akamaized.net/exp=16557720
61acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2Ahmac=ab26adba64ac7933551d96
d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-043e6c701ab0/
parcel/video/cba0091d.mp4
[debug] Command-line config: ['--verbose', 'https://17vod-adaptive.akamaized.net
/exp=1655772061acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2Ahmac=ab26adba6
4ac7933551d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-
043e6c701ab0/parcel/video/cba0091d.mp4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No ANSI), er
ror utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.05.18 [https://github.com/yt-dlp/yt-dlp/commit/b14d523558c04dd0c3ae17877f22f707a805cf5b] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg n4.4.1-14-g5a7763bdfa-20220109 (setts)
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08,
mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://17vod-adaptive.akamaized.net/exp=16557
72061acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2Ahmac=ab26adba64ac7933551
d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-043e6c701a
b0/parcel/video/cba0091d.mp4
[generic] cba0091d: Requesting header
WARNING: [generic] Could not send HEAD request to https://17vod-adaptive.akamaiz/
ed.net/exp=1655772061acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2Ahmac=ab2
6adba64ac7933551d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6
-9e8e-043e6c701ab0/parcel/video/cba0091d.mp4: HTTP Error 403: Forbidden
[generic] cba0091d: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused b
y <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/
/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm y
ou are on the latest version using yt-dlp -U
File "yt_dlp\extractor\common.py", line 642, in extract
File "yt_dlp\extractor\generic.py", line 2737, in _real_extract
File "yt_dlp\extractor\common.py", line 786, in _request_webpage

File "yt_dlp\extractor\common.py", line 768, in _request_webpage
File "yt_dlp\YoutubeDL.py", line 3596, in urlopen
File "urllib\request.py", line 531, in open
File "urllib\request.py", line 640, in http_response
File "urllib\request.py", line 569, in error
File "urllib\request.py", line 502, in _call_chain
File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

C:\youtube-dl>yt-dlp --verbose https://17vod-adaptive.akamaized.net/exp=16557720
61acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2Ahmac=ab26adba64ac7933551d96
d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-043e6c701ab0/
parcel/video/74484e5e.mp4
[debug] Command-line config: ['--verbose', 'https://17vod-adaptive.akamaized.net
/exp=1655772061acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2Ahmac=ab26adba6
4ac7933551d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-
043e6c701ab0/parcel/video/74484e5e.mp4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No ANSI), er
ror utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.05.18 [https://github.com/yt-dlp/yt-dlp/commit/b14d523558c04dd0c3ae17877f22f707a805cf5b] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg n4.4.1-14-g5a7763bdfa-20220109 (setts)
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08,
mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://17vod-adaptive.akamaized.net/exp=16557
72061acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2Ahmac=ab26adba64ac7933551
d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-043e6c701a
b0/parcel/video/74484e5e.mp4
[generic] 74484e5e: Requesting header
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7),
vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext,
aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 74484e5e: Downloading 1 format(s): mp4
[debug] Invoking http downloader on "https://17vod-adaptive.akamaized.net/exp=16
55772061acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2Ahmac=ab26adba64ac7933
551d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-043e6c7
01ab0/parcel/video/74484e5e.mp4"
[debug] File locking is not supported on this platform. Proceeding without locki
ng
[download] Destination: 74484e5e [74484e5e].mp4
[download] 9.3% of 1.13GiB at 3.37MiB/s ETA 05:11
```

**Comment by pukkandan** [comment] 2022-06-20 19:37
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/4108

403 means the server is denying your request https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

As I said in the other issue, this can happen because of many reasons (lacking headers/cookies is a common cause). Since you are passing a direct video/manifest URL rather than a supported webpage URL (and especially since the base webpage you want to extract from is paywalled), there really is nothing I can do to help. Opening new issue doesn't change that fact

If you want, I can convert #4108 into a site request for `dlc.tokyo` assuming you are [willing to share account details with any dev who wants to work on it](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed)

**Closed by pukkandan** 2022-06-20 19:37 UTC
Labels: duplicate, invalid, question, site:vimeo
