### ISSUE TITLE
Issues w/ only TikTok

### ISSUE THREAD

**Issue by earthyrock** [yt-dlp/yt-dlp#2250] opened 2022-01-07 12:08 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Description

Previously on vers. 12/27.
Last night was working fine. Issues appeared this morning w/ *only TikTok*. No issues w/ other sites.
Get this:
Failed to parse JSON  (caused by JSONDecodeError

### Verbose log

```shell
G:\00OSz\12win10b zEnt-LTSC x64 1809\05Apps\Multimedia\Video\Installed\yt-dlp>".\yt-dlp.exe" --verbose --config-location ".\yt-dlp.conf" "https://www.tiktok.com/@chelyschneider3.0/video/7041265070491454726?is_from_webapp=1&sender_device=pc&web_id7029538146535998982" >> c:\log
[debug] Command-line config: ['--verbose', '--config-location', '.\\yt-dlp.conf', 'https://www.tiktok.com/@chelyschneider3.0/video/7041265070491454726?is_from_webapp=1&sender_device=pc&web_id7029538146535998982']
[debug] Custom config file: .\yt-dlp.conf
[debug] Custom config: ['--ffmpeg-location', '..\\ffmpeg\\bin\\ffmpeg.exe', '--audio-format', 'mp3', '--format', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4', '--output', 'X:\\10Video\\Podcasts\\zzTikTok\\aaCompletes\\%(uploader)s\\%(uploader)s %(view_count)s %(title)s.%(ext)s']
[debug] Portable config file: G:\00OSz\12win10b zEnt-LTSC x64 1809\05Apps\Multimedia\Video\Installed\yt-dlp\yt-dlp.conf
[debug] Portable config: ['--ffmpeg-location', '..\\ffmpeg\\bin\\ffmpeg.exe', '--audio-format', 'mp3', '--format', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4', '--output', 'X:\\10Video\\Podcasts\\zzTikTok\\aaCompletes\\%(uploader)s\\%(uploader)s %(view_count)s %(title)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252 (No ANSI), err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 2021-11-10-git-44c65c6cc0-full_build-www.gyan.dev (setts), ffprobe 2021-11-10-git-44c65c6cc0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@chelyschneider3.0/video/7041265070491454726?is_from_webapp=1&sender_device=pc&web_id7029538146535998982
WARNING: [TikTok] 7041265070491454726: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; Retrying with webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Invoking downloader on "https://v16-webapp.tiktok.com/d0523ffc72e6d04761ad9501b3691bc2/61d8804a/video/tos/useast2a/tos-useast2a-ve-0068c003/f6322afee12d45839f0243b7187f4cfc/?a=1988&br=2932&bt=1466&cd=0%7C0%7C1&ch=0&cr=0&cs=0&cv=1&dr=0&ds=3&er=&ft=Yu12_FGgkag3-I&l=20220107120239010223098156180835CC&lr=tiktok_m&mime_type=video_mp4&net=0&pl=0&qs=0&rc=M2RuaTw6ZmtzOTMzNzczM0ApNWZkO2k6PGQ6Nzo2PGg6PGduXi8vcjQwZm9gLS1kMTZzc2I0Li5eLTEvXl4uNmNhLTI6Yw%3D%3D&vl=&vr="
```

**Comment by MinePlayersPE** [comment] 2022-01-07 12:15
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2133 or https://github.com/yt-dlp/yt-dlp/issues/2135

**Closed** 2022-01-07 12:20 UTC
Labels: duplicate, site-bug, site:tiktok
