### ISSUE TITLE
[youtube] Signature extraction failed

### ISSUE THREAD

**Issue by Lastique** [yt-dlp/yt-dlp#6072] opened 2023-01-22 00:36 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

Playing the following URL with mpv+yt-dlp fails: https://www.youtube.com/watch?v=0pB4N59-uBc

The output is:

```
[ytdl_hook] ERROR: [youtube] 0pB4N59-uBc: Signature extraction failed: Traceback (most recent call last):
[ytdl_hook]   File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2500, in _decrypt_signature
[ytdl_hook]     return func(s)
[ytdl_hook]   File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2406, in <lambda>
[ytdl_hook]     return lambda s: ''.join(s[i] for i in cache_spec)
[ytdl_hook]   File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2406, in <genexpr>
[ytdl_hook]     return lambda s: ''.join(s[i] for i in cache_spec)
[ytdl_hook] TypeError: string indices must be integers
[ytdl_hook]  (caused by TypeError('string indices must be integers')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U 
[ytdl_hook] youtube-dl failed: unexpected error occurred 
```

This error can also be reproduced purely in yt-dlp with this command line:

```
yt-dlp --list-formats https://www.youtube.com/watch?v=0pB4N59-uBc
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -v --list-formats https://www.youtube.com/watch?v=0pB4N59-uBc
[debug] Command-line config: ['-v', '--list-formats', 'https://www.youtube.com/watch?v=0pB4N59-uBc']
[debug] User config "/home/lastique/.config/yt-dlp/config": ['--socket-timeout', '10', '--skip-unavailable-fragments', '--concurrent-fragments', '5', '--mark-watched', '--buffer-size', '256K', '--http-chunk-size', '1M', '--format-sort', 'quality,res,fps,codec,size,br,asr,proto,ext,hasaud,source,id', '--format', '(bestvideo*[dynamic_range=?SDR][width<=?2560]+bestaudio)/best[dynamic_range=?SDR]']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.6 (CPython 64bit) - Linux-5.15.0-58-lowlatency-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2-1mind3 (setts), ffprobe 5.1.2-1mind3, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=0pB4N59-uBc
[youtube] 0pB4N59-uBc: Downloading webpage
[youtube] 0pB4N59-uBc: Downloading android player API JSON
[debug] Loading youtube-sigfuncs.js_4248d311_109 from cache
ERROR: [youtube] 0pB4N59-uBc: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2500, in _decrypt_signature
    return func(s)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2406, in <lambda>
    return lambda s: ''.join(s[i] for i in cache_spec)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2406, in <genexpr>
    return lambda s: ''.join(s[i] for i in cache_spec)
TypeError: string indices must be integers
 (caused by TypeError('string indices must be integers')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 3357, in _real_extract
    live_broadcast_details, is_live, streaming_data, formats = self._list_formats(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 3271, in _list_formats
    formats = list(self._extract_formats(streaming_data, video_id, player_url, is_live, duration))
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 3098, in _extract_formats
    signature = self._decrypt_signature(sc['s'][0], video_id, player_url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2502, in _decrypt_signature
    raise ExtractorError('Signature extraction failed: ' + traceback.format_exc(), cause=e)

  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2500, in _decrypt_signature
    return func(s)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2406, in <lambda>
    return lambda s: ''.join(s[i] for i in cache_spec)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2406, in <genexpr>
    return lambda s: ''.join(s[i] for i in cache_spec)
TypeError: string indices must be integers
```

**Comment by bashonly** [comment] 2023-01-22 00:41
> [debug] yt-dlp version 2022.04.08 [7884ade65]

`Latest version: 2023.01.06`

update yt-dlp

duplicate of #4635

**Closed by bashonly** 2023-01-22 00:41 UTC
Labels: site-bug, triage

**Comment by Lastique** [comment] 2023-01-22 12:38
Thanks and sorry for the noise. I messed up updating yt-dlp and thought I was running the latest version.
