### ISSUE TITLE
tiktok extractor broken for playlist

### ISSUE THREAD

**Issue by error-reporting** [yt-dlp/yt-dlp#10805] opened 2024-08-20 15:40 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

tiktok playlist is using generic extractor

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--config-locations', '/data/user/0/com.deniscerri.ytdl/cache/config-TERMINAL[1724166598025].txt', '-P', '/storage/emulated/0/Download/YTDLnis/Command', '--no-cache-dir', '--ffmpeg-location', '/data/app/com.deniscerri.ytdl-Z-mB9Bd2kzOoSfmyPlxQfg==/lib/arm64/libffmpeg.so']
[debug] | Config "/data/user/0/com.deniscerri.ytdl/cache/config-TERMINAL[1724166598025].txt": ['https://www.tiktok.com/@nhthonghunh0/playlist/REVIEW-H%C3%80I-C%C3%94NG-NGH%E1%BB%86-7129292736678742810?_d=secCgYIASAHKAESPgo8SfEKJIQ1Y2iJ6XmE%2Fzud3P%2BEj4TKT19GQZAHjvyqmEuQAREhsnXIL5p4p5PYxbAoTU001m7s6KQ7fjtJGgA%3D&_r=1&author_id=6539665572547985409&checksum=1a2488498662281a386258a20e06e5a653c08167957b93e91af8a575f65ad645&language=vi&sec_user_id=MS4wLjABAAAAyvUbgaQnpE0Q7x6TEdbfI-tP_wRNw5SrKU3UeJDSLVzN9FaZbvEuiq1VWkh7Zftf&share_app_id=1180&share_link_id=8e05f91a-da2a-4e8c-9ec5-25e038245bde&social_share_type=16&timestamp=1724166221&u_code=e9ej01f6cj0l96&ug_btm=b5836%2CMixVideoDetailActivity&ugbiz_name=UNKNOWN&user_id=7267867257676727297&utm_campaign=client_share&utm_medium=android&utm_source=copy', '-vU', '--buffer-size', '4096', '--no-hls-use-mpegts', '--write-info-json', '--write-playlist-metafiles', '--write-comments', '--merge-output-format', 'mkv', '--fixup', 'never', '--add-metadata', '--remux-video', 'mkv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version master@2024.08.19.221301 from yt-dlp/yt-dlp-master-builds [f0bb28504] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-4.9.190+-aarch64-with-libc (OpenSSL 1.1.1t  7 Feb 2023, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.17, mutagen-1.46.0, sqlite3-3.30.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
WARNING: [generic] Falling back on generic information extractor
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.tiktok.com/@nhthonghunh0/playlist/REVIEW-H%C3%80I-C%C3%94NG-NGH%E1%BB%86-7129292736678742810?_d=secCgYIASAHKAESPgo8SfEKJIQ1Y2iJ6XmE%2Fzud3P%2BEj4TKT19GQZAHjvyqmEuQAREhsnXIL5p4p5PYxbAoTU001m7s6KQ7fjtJGgA%3D&_r=1&author_id=6539665572547985409&checksum=1a2488498662281a386258a20e06e5a653c08167957b93e91af8a575f65ad645&language=vi&sec_user_id=MS4wLjABAAAAyvUbgaQnpE0Q7x6TEdbfI-tP_wRNw5SrKU3UeJDSLVzN9FaZbvEuiq1VWkh7Zftf&share_app_id=1180&share_link_id=8e05f91a-da2a-4e8c-9ec5-25e038245bde&social_share_type=16&timestamp=1724166221&u_code=e9ej01f6cj0l96&ug_btm=b5836%2CMixVideoDetailActivity&ugbiz_name=UNKNOWN&user_id=7267867257676727297&utm_campaign=client_share&utm_medium=android&utm_source=copy
Traceback (most recent call last):
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tiktok.com/@nhthonghunh0/playlist/REVIEW-H%C3%80I-C%C3%94NG-NGH%E1%BB%86-7129292736678742810?_d=secCgYIASAHKAESPgo8SfEKJIQ1Y2iJ6XmE%2Fzud3P%2BEj4TKT19GQZAHjvyqmEuQAREhsnXIL5p4p5PYxbAoTU001m7s6KQ7fjtJGgA%3D&_r=1&author_id=6539665572547985409&checksum=1a2488498662281a386258a20e06e5a653c08167957b93e91af8a575f65ad645&language=vi&sec_user_id=MS4wLjABAAAAyvUbgaQnpE0Q7x6TEdbfI-tP_wRNw5SrKU3UeJDSLVzN9FaZbvEuiq1VWkh7Zftf&share_app_id=1180&share_link_id=8e05f91a-da2a-4e8c-9ec5-25e038245bde&social_share_type=16&timestamp=1724166221&u_code=e9ej01f6cj0l96&ug_btm=b5836%2CMixVideoDetailActivity&ugbiz_name=UNKNOWN&user_id=7267867257676727297&utm_campaign=client_share&utm_medium=android&utm_source=copy
```

**Comment by bashonly** [comment] 2024-08-20 19:10
Duplicate of #7804

**Closed by bashonly** 2024-08-20 19:10 UTC
Labels: duplicate, site-enhancement, site:tiktok
