### ISSUE TITLE
BBC News fails with "Unable to extract playlist data" error

### ISSUE THREAD

**Issue by Prill** [yt-dlp/yt-dlp#9942] opened 2024-05-17 04:02 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I attempted to download the following video: https://www.bbc.com/news/uk-england-leeds-69023225

It fails with the message "Unable to extract playlist data".

Running with `--write-pages` produces the following dump: https://gist.github.com/Prill/728801a3439788a4a0a66c49ca7846da

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.bbc.com/news/uk-england-leeds-69023225']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (pip)
[debug] Python 3.12.3 (CPython arm64 64bit) - macOS-13.6.4-arm64-arm-64bit (OpenSSL 3.2.1 30 Jan 2024)
[debug] exe versions: ffmpeg 7.0 (setts), ffprobe 7.0
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[bbc] Extracting URL: https://www.bbc.com/news/uk-england-leeds-69023225
[bbc] uk-england-leeds-69023225: Downloading webpage
ERROR: [bbc] uk-england-leeds-69023225: Unable to extract playlist data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/opt/homebrew/Cellar/yt-dlp/2024.4.9_1/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.4.9_1/libexec/lib/python3.12/site-packages/yt_dlp/extractor/bbc.py", line 1291, in _real_extract
    self._search_regex(
  File "/opt/homebrew/Cellar/yt-dlp/2024.4.9_1/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1321, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by Prill** [comment] 2024-05-17 04:04
Please let me know if I didn't provide enough information.

**Comment by bashonly** [comment] 2024-05-17 04:13
You went above-and-beyond with providing info; thanks!

Have to close this is a duplicate of #9701, though. And yes, that issue's title is not exactly optimized for searches, so no worries.

This will be fixed by #9705

**Closed by bashonly** 2024-05-17 04:13 UTC
Labels: site-bug, triage

**Comment by Prill** [comment] 2024-05-17 04:21
Is there a known workaround? I don't mind poking around the source code for a m3u8 URL or whatever, but I couldn't find one in this case.

**Comment by bashonly** [comment] 2024-05-17 04:26
you can install the PR branch:

```
python3 -m pip install -U pip hatchling wheel
python3 -m pip install --force-reinstall "yt-dlp[default] @ https://github.com/kylegustavo/yt-dlp/archive/kg.bbc-1.tar.gz"
```

**Comment by bashonly** [comment] 2024-05-17 06:22
@Prill The PR has been merged. If you installed with homebrew, you can do this to install from the master branch:
```
brew uninstall yt-dlp
brew install --HEAD yt-dlp
```

**Comment by Prill** [comment] 2024-05-18 01:41
Danke. I'll probably wait until it's officially in the release; it's not urgent.
