### ISSUE TITLE
[Broken] BBC America: Unable to download JSON

### ISSUE THREAD

**Issue by IONECarter** [yt-dlp/yt-dlp#1212] opened 2021-10-09 20:10 UTC
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.10.09**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones
- [X] I've read the opening an issue section in CONTRIBUTING.md
- [X] I have given an appropriate title to the issue

## Verbose log

```
 yt-dlp -vU "https://www.bbcamerica.com/shows/the-graham-norton-show/episodes/season-28-compilation-show-1--1015989"
[debug] Command-line config: ['-vU', 'https://www.bbcamerica.com/shows/the-graham-norton-show/episodes/season-28-compilation-show-1--1015989']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.10.09
[debug] Python version 3.9.7 (CPython 64bit) - macOS-11.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.09)
[debug] [AMCNetworks] Extracting URL: https://www.bbcamerica.com/shows/the-graham-norton-show/episodes/season-28-compilation-show-1--1015989
[AMCNetworks] shows/the-graham-norton-show/episodes/season-28-compilation-show-1--1015989: Downloading JSON metadata
ERROR: [AMCNetworks] shows/the-graham-norton-show/episodes/season-28-compilation-show-1--1015989: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 698, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3227, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

```

## Description

BBC America uses the AMCNetworks extractor. However, it seems that for the provided link I tried https://www.bbcamerica.com/shows/the-graham-norton-show/episodes/season-28-compilation-show-1--1015989 it is unable to find the required JSON.

Not sure if this is the right thing, but looking at the amcnetworks.py extractor, it seems the JSON location currently is different to what I'm seeing on my end for the show link I was trying.

**amcnetworks.py**
https://github.com/yt-dlp/yt-dlp/blob/a170527e1fc382dd7be214c5134f5013a5f0747f/yt_dlp/extractor/amcnetworks.py#L65-L75

**Network Log**
Looking at network log on provide show link the JSON seems to be at:
```https://gw.cds.amcn.com/content-compiler-cr/api/v1/content/amcn/bbca/path/shows/the-graham-norton-show/episodes/season-28-compilation-show-1--1015989```

Thank you for the help and looking into.

**Comment by IONECarter** [comment] 2021-10-19 18:15
I run into the same issue when passing account details to it and/or using cookies.

Account
```
[debug] Command-line config: ['-vU', 'https://www.bbcamerica.com/shows/the-graham-norton-show/episodes/season-28-compilation-show-1--1015989', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.10.10
[debug] Python version 3.9.7 (CPython 64bit) - macOS-11.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.10)
[debug] [AMCNetworks] Extracting URL: https://www.bbcamerica.com/shows/the-graham-norton-show/episodes/season-28-compilation-show-1--1015989
[AMCNetworks] shows/the-graham-norton-show/episodes/season-28-compilation-show-1--1015989: Downloading JSON metadata
ERROR: [AMCNetworks] shows/the-graham-norton-show/episodes/season-28-compilation-show-1--1015989: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 698, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3228, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

Account + Cookies
```
debug] Command-line config: ['-vU', 'https://www.bbcamerica.com/shows/the-graham-norton-show/episodes/season-28-compilation-show-1--1015989', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--cookies-from-browser', 'firefox']
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/Users/kenny/Library/Application Support/Firefox/Profiles/rbu22xhm.Default User/cookies.sqlite"
[Cookies] Extracted 2639 cookies from firefox
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.10.10
[debug] Python version 3.9.7 (CPython 64bit) - macOS-11.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.10)
[debug] [AMCNetworks] Extracting URL: https://www.bbcamerica.com/shows/the-graham-norton-show/episodes/season-28-compilation-show-1--1015989
[AMCNetworks] shows/the-graham-norton-show/episodes/season-28-compilation-show-1--1015989: Downloading JSON metadata
ERROR: [AMCNetworks] shows/the-graham-norton-show/episodes/season-28-compilation-show-1--1015989: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 698, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3228, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by pukkandan** [comment] 2021-12-08 22:37
Comcast_SSO is currently broken. Closing as duplicate of #516 unless someone can check if this issue can be reproduced with other MSOs

**Closed by pukkandan** 2021-12-08 22:37 UTC
Labels: account-needed, extractor-bug

**Comment by wxolp** [comment] 2022-03-30 22:20
Here is one that should work without login:

https://www.bbcamerica.com/shows/killing-eve/episodes/season-4-just-dunk-me--1052529

however, it seems web and Android clients use DRM, so maybe you just want to retag the issue and keep closed? Up to you.
