### ISSUE TITLE
[Broken] YouTube - Fallback to a different googlevideo host

### ISSUE THREAD

**Issue by archiif** [yt-dlp/yt-dlp#283] opened 2021-04-28 23:05 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.04.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Command-line config: ['https://www.youtube.com/watch?v=UaDOpyh1crg', '-v']
[debug] Loading archive file None
[debug] Encodings: locale cp932, fs utf-8, out utf-8, pref cp932
[debug] yt-dlp version 2021.04.22
[debug] Python version 3.9.4 (CPython 64bit) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 2021-01-27-git-149bfc2445-full_build-www.gyan.dev, ffprobe 2021-01-27-git-149bfc2445-full_build-www.gyan.dev, rtmpdump 2.3
[debug] Proxy map: {}
[youtube] UaDOpyh1crg: Downloading webpage
[youtube] UaDOpyh1crg: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] UaDOpyh1crg: Downloading format(s) 248+251
[debug] Invoking downloader on 'https://manifest.googlevideo.com/api/manifest/dash/expire/1619671901/ei/_eaJYM76EMuN3LUP5Pic2AM/ip/139.228.46.50/id/51a0cea7287572b8/source/youtube/requiressl/yes/playback_host/r1---sn-4pgnuhxqp5-n0cl.googlevideo.com/mh/o5/mm/31%2C29/mn/sn-4pgnuhxqp5-n0cl%2Csn-4pgnuhxqp5-jb3el/ms/au%2Crdu/mv/m/mvi/1/pcm2cms/yes/pl/20/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/532500/vprv/1/mt/1619649879/fvip/1/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIhAPfk3SDJnIZerpGIfoTgqfbV7cMrd10e6ri5hyht1U4vAiAZGzpq-1J4h81X-j3ENz_LEBH1N2KrjepgYCYW6h5q3Q%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIhAN6VB9SnB003CIUSAGy55BGxWZ9RW6SaNB4rvHI_WIJnAiAmkPXfqjeZKCUzM7buHg7PqRpGvK6q2BgQoHPH106xBA%3D%3D'
[dashsegments] Total fragments: 108
[download] Destination: The Dog House _ Finding A Little Boy The Best Companion [UaDOpyh1crg].f248.webm
ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "c:\users\user\appdata\local\programs\python\python39\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\user\appdata\local\programs\python\python39\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\user\appdata\local\programs\python\python39\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\user\appdata\local\programs\python\python39\lib\http\client.py", line 1008, in _send_output
    self.send(msg)
  File "c:\users\user\appdata\local\programs\python\python39\lib\http\client.py", line 948, in send
    self.connect()
  File "c:\users\user\appdata\local\programs\python\python39\lib\http\client.py", line 1415, in connect
    super().connect()
  File "c:\users\user\appdata\local\programs\python\python39\lib\http\client.py", line 919, in connect
    self.sock = self._create_connection(
  File "c:\users\user\appdata\local\programs\python\python39\lib\socket.py", line 843, in create_connection
    raise err
  File "c:\users\user\appdata\local\programs\python\python39\lib\socket.py", line 831, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2460, in process_info
    partial_success, real_download = dl(fname, new_info)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2240, in dl
    return fd.download(name, new_info, subtitle)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\common.py", line 381, in download
    return self.real_download(filename, info_dict), True
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\dash.py", line 172, in real_download
    frag_content, frag_index = download_fragment(fragment)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\dash.py", line 91, in download_fragment
    success, frag_content = self._download_fragment(ctx, fragment_url, info_dict)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\fragment.py", line 105, in _download_fragment
    success = ctx['dl'].download(fragment_filename, fragment_info_dict)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\common.py", line 381, in download
    return self.real_download(filename, info_dict), True
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\http.py", line 352, in real_download
    establish_connection()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\http.py", line 117, in establish_connection
    raise err
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\http.py", line 111, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2890, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "c:\users\user\appdata\local\programs\python\python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "c:\users\user\appdata\local\programs\python\python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "c:\users\user\appdata\local\programs\python\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\utils.py", line 2781, in https_open
    return self.do_open(functools.partial(
  File "c:\users\user\appdata\local\programs\python\python39\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

```

## Description

I've been getting a lot of `[WinError 10060]` error messages on certain videos with yt-dlp, even though the videos plays perfectly fine in the web browser.

Here are some random examples (I will update the list in case I found more):

- https://youtube.com/watch?v=UaDOpyh1crg
- https://youtube.com/watch?v=vyvh0U94jhg

A pattern I'm noticing with the videos is that they tend to have a low viewcount and/or recently uploaded. I think this error also depends on your ISP and region so you might not be able to reproduce it.

According to this comment: https://github.com/ytdl-org/youtube-dl/issues/18586#issuecomment-449240668, this is caused by certain `googlevideo.com` hosts being down. On the web browser, YouTube will fallback to a different host in the case that something like this happens, but yt-dlp has no such functionality.

Is it possible to implement a similar behavior for yt-dlp?

Another potentially related issue: https://github.com/ytdl-org/youtube-dl/issues/11779

**Comment by pukkandan** [comment] 2021-04-29 00:06
Duplicate of #3

**Closed by pukkandan** 2021-04-29 00:06 UTC
