### ISSUE TITLE
Set `filesize_approx` based on tbr and duration?

### ISSUE THREAD

**Issue by 7x11x13** [yt-dlp/yt-dlp#11350] opened 2024-10-25 17:03 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When run with `--list-formats`, each codec is shown with an approximate filesize based on the tbr and duration known. However, filtering formats by `filesize_approx` does not work.

We can see from this code that the approximate filesize shown in the formats table is based on tbr and duration:
https://github.com/yt-dlp/yt-dlp/blob/c29f5a7fae93a08f3cfbb6127b2faa75145b06a0/yt_dlp/YoutubeDL.py#L3914-L3918

It would be nice to be able to filter formats based on this, is there a reason `filesize_approx` is not set from the bitrate and duration info?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp https://soundcloud.com/violinbutterflynet/8768434t --list-formats
[soundcloud] Extracting URL: https://soundcloud.com/violinbutterflynet/8768434t
[soundcloud] violinbutterflynet/8768434t: Downloading info JSON
[soundcloud] 1929129134: Downloading hls_mp3 format info JSON
[soundcloud] 1929129134: Downloading http_mp3 format info JSON
[soundcloud] 1929129134: Downloading hls_opus format info JSON
[info] Available formats for 1929129134:
ID           EXT  RESOLUTION │ FILESIZE  TBR PROTO │ VCODEC     ACODEC  ABR
───────────────────────────────────────────────────────────────────────────
hls_mp3_128  mp3  audio only │ ~4.70MiB 128k m3u8  │ audio only mp3    128k
http_mp3_128 mp3  audio only │ ~4.70MiB 128k http  │ audio only mp3    128k
hls_opus_64  opus audio only │ ~2.35MiB  64k m3u8  │ audio only opus    64k

===========================================================================

$ yt-dlp https://soundcloud.com/violinbutterflynet/8768434t -f "[filesize_approx<25M]"
[soundcloud] Extracting URL: https://soundcloud.com/violinbutterflynet/8768434t
[soundcloud] violinbutterflynet/8768434t: Downloading info JSON
[soundcloud] 1929129134: Downloading hls_mp3 format info JSON
[soundcloud] 1929129134: Downloading http_mp3 format info JSON
[soundcloud] 1929129134: Downloading hls_opus format info JSON
ERROR: [soundcloud] 1929129134: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment] 2024-10-26 13:02
Duplicate of #8730

Everything I said in my reply to that issue also applies to soundcloud:

> What's happening is:
> - the ~~bandcamp~~ soundcloud extractor sets `abr` (audio bitrate) for the formats it returns, but not `tbr` (total bitrate).
> - yt-dlp core code calculates the `filesize_approx` from `duration` and `tbr` (if we have those values).
> - core populates `tbr` from `abr` for formats where there is no video codec, but this is done in `FormatSorter.calculate_preference` (format sorting) *after* we've already tried to calculate `filesize_approx` for the format dicts, so it's only rendered in the formats list, but not available for filtering/printing or in the JSON output

But your case as the additional wrinkle that manifest formats (m3u8/HLS, mpd/DASH) have intentionally had their `filesize_approx` values made unavailable from format filtering/selection due to their often extreme inaccuracy. You can make them available again by passing `--compat manifest-filesize-approx`. This will work again when #11353 is merged

**Closed by bashonly** 2024-10-26 13:02 UTC
Labels: bug
