### ISSUE TITLE
Windows Defender detects Trojan Win32/Wacatac.B!ml in yt-dlp.exe 2023.07.06

### ISSUE THREAD

**Issue by bobanm** [yt-dlp/yt-dlp#7532] opened 2023-07-07 15:25 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

After downloading [the latest Windows build 2023.07.06](https://github.com/yt-dlp/yt-dlp/releases/download/2023.07.06/yt-dlp.exe), Windows Defender detected a trojan `Win32/Wacatac.B!ml`.

I tried twice, and got the same response from Windows Defender.

I've been using yt-dlp for a long time, and this never happened with the previous builds.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Not really applicable to the issue I'm reporting.
```

**Comment by bashonly** [comment] 2023-07-07 17:01
Duplicate of #25

__pukkandan__ wrote:
> It is a false positive caused due to the exe being unsigned.
> This is a known issue. I don't have any way of fixing it.

**Closed by bashonly** 2023-07-07 17:01 UTC
Labels: bug, triage

**Comment by bobanm** [comment] 2023-07-07 19:10
I checked some old issues, but not over 2 years ago when this was first reported 😊

If unsigned file is what causes the false positive, what prevented it from being signed this time? None of the previous versions I used triggered Windows Defender, so I would assume those were properly signed?

**Comment by bashonly** [comment] 2023-07-07 19:21
> None of the previous versions I used triggered Windows Defender

Windows Defender gives false positives seemingly at random

> I would assume those were properly signed?

No. Read the linked issue for more info

> what prevented it from being signed

Among other things, signing a windows exe requires a certificate issued by a CA, and the hassle/cost of it all is generally not worth it for a FOSS python project
