### ISSUE TITLE
tl problem

### ISSUE THREAD

**Issue by developerss** [yt-dlp/yt-dlp#4644] opened 2022-08-12 18:34 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I am getting error 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Admin>C:\Temp\yt-dlp.exe https://t.me/English1me/70 -vU
[debug] Command-line config: ['https://t.me/English1me/70', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158f7] (py2exe)
[debug] Python 3.9.7 (CPython 64bit) - Windows-10-10.0.22000
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107743-g8fc7f0fdec-20220811 (setts), ffprobe N-107743-g8fc7f0fdec-20220811
[debug] Optional libraries: brotli-1.0.9, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] [telegram:embed] Extracting URL: https://t.me/English1me/70
[telegram:embed] 70: Downloading webpage
[telegram:embed] 70: Downloading ermbed page
ERROR: [telegram:embed] 70: Unable to extract source; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.pyc", line 666, in extract
  File "yt_dlp\extractor\telegram.pyc", line 25, in _real_extract
  File "yt_dlp\extractor\common.pyc", line 1218, in _search_regex
```

**Comment by pukkandan** [comment] 2022-08-12 18:49
Duplicate of #3606

**Closed by pukkandan** 2022-08-12 18:49 UTC
Labels: bug, triage
