### ISSUE TITLE
[Youtube][Request] Add Subtitle Skipping Based on SponsorBlock Segments

### ISSUE THREAD

**Issue by benmier** [yt-dlp/yt-dlp#11325] opened 2024-10-22 23:01 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Currently, the SponsorBlock integration allows you to skip specific segments (e.g., sponsor, self-promo) when downloading video or audio. This request aims to extend this functionality to subtitle downloads as well. Specifically, the goal is to modify the subtitle processing logic to remove or adjust subtitle cues that fall within segments defined by SponsorBlock, based on user-selected categories, thereby allowing subtitle file downloads that do not contain undesired segments.

Here's a [gist](https://gist.github.com/benmier/fa30142b70bb5338400503d844258d55) where I took a crack at adding a new postprocessor to perform this logic.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment] 2024-11-12 15:43
Duplicate of #6616

**Closed by bashonly** 2024-11-12 15:43 UTC
Labels: enhancement, triage
