### ISSUE TITLE
Unable to download webpage: HTTP Error 403: Forbidden Crunchyroll

### ISSUE THREAD

**Issue by levaculik2** [yt-dlp/yt-dlp#8087] opened 2023-09-11 23:58 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

It's been a while since I've been able to download anything and it's always giving me the same error. I tried several tips mentioned here and nothing worked.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--match-filters', 'language=pt-BR', '--extractor-args', 'crunchyrollbeta:format=adaptive_dash', '-f', 'ba', '--audio-multistreams', '-a', '/home/levaculik/Documentos/list/crunchyptBR.txt', '--cookies-from-browser', 'chrome', 'www.crunchyroll.com/', '--no-geo-bypass', '-o', '%(series)s S0%(season_number)sE0%(episode_number)s - %(episode)s.pt-BR.%(ext)s']
[debug] Batch file urls: ['https://www.crunchyroll.com/watch/G14U498EV']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-83-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.46.0, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/home/levaculik/.config/google-chrome/Default/Cookies"
[Cookies] Loading cookie      0/  3574[debug] detected desktop environment: XFCE
[debug] Chosen keyring: GNOMEKEYRING
[Cookies] Extracted 3445 cookies from chrome
[debug] cookie version breakdown: {'v10': 0, 'v11': 3563, 'other': 0, 'unencrypted': 11}
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/G14U498EV
[crunchyroll] Retrieving main page (lang=None)
ERROR: [crunchyroll] G14U498EV: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/crunchyroll.py", line 320, in _real_extract
    response = traverse_obj(self._call_api(
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/crunchyroll.py", line 114, in _call_api
    result = self._call_base_api(
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/crunchyroll.py", line 99, in _call_base_api
    self._update_query(lang)
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/crunchyroll.py", line 69, in _update_query
    webpage = self._download_webpage(
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1113, in _download_webpage
    return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1064, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 898, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 855, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 837, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3863, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

[generic] Extracting URL: www.crunchyroll.com/
WARNING: [generic] The url doesn't specify the protocol, trying with http
[generic] Extracting URL: http://www.crunchyroll.com/
[generic] www.crunchyroll: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] www.crunchyroll: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.crunchyroll.com/
Traceback (most recent call last):
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1688, in __extract_info
    ie_result = ie.extract(url)
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
  File "/home/levaculik/.local/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.crunchyroll.com/
```

**Comment by bashonly** [comment] 2023-09-12 01:51
First, you'll need to [install master with pip](https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-master)

Then you'll need to [follow these steps to workaround crunchyroll's cloudflare protection](https://github.com/yt-dlp/yt-dlp/issues/7442#issuecomment-1610223778)

Duplicate of #7442

**Closed by bashonly** 2023-09-12 01:51 UTC
Labels: site-bug, triage
