### ISSUE TITLE
Infinite resolving of some M3U urls

### ISSUE THREAD

**Issue by ArcPlayz** [yt-dlp/yt-dlp#9505] opened 2024-03-21 01:10 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Poland

### Provide a description that is worded well enough to be understood

Generic extractor does not finish resolving some M3U urls like those:
http://radio.pervii.com/top_radio_80s.m3u
https://raw.githubusercontent.com/junguler/m3u-radio-music-playlists/main/world.m3u
Some just work as they should:
https://www.internet-radio.com/servers/tools/playlistgenerator/?u=http://uk1.internet-radio.com:8004/listen.pls&t=.m3u
As I checked, the last version, on which everything was working correctly was 2023.3.4.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--dump-json', 'http://radio.pervii.com/top_radio_80s.m3u']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447]
[debug] Lazy loading extractors is disabled
[debug] Python 3.12.2 (CPython x86_64 64bit) - Linux-6.8.1-arch1-1-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1806 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[generic] Extracting URL: http://radio.pervii.com/top_radio_80s.m3u
[generic] top_radio_80s: Downloading webpage
[debug] Identified a direct video link
[generic] top_radio_80s: Downloading m3u8 information
[generic] top_radio_80s: Checking m3u8 live status
```

**Comment by bashonly** [comment] 2024-03-21 04:13
The cause of the issue is that they are m3u playlists and yt-dlp is treating them like they are m3u8 playlists. This behavior was introduced in 5940862d5a75ae45a640e0ce3104dd18c9864e26 and exacerbated by 93e7c6995e07dafb9dcc06c0d06acf6c5bdfecc5 (which causes yt-dlp to download the stream thinking it's a manifest)

Have to close this issue though due to the pirate radio links. Feel free to open a new issue when you have legitimate URLs

**Closed by bashonly** 2024-03-21 04:13 UTC
Labels: site-bug, triage
