### ISSUE TITLE
tiktok live not  downloading? user is live but yt-dlp says theyre not

### ISSUE THREAD

**Issue by neuri48** [yt-dlp/yt-dlp#9517] opened 2024-03-23 01:51 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States 

### Provide a description that is worded well enough to be understood

i put in the share link from tiktok live but it just says creator not live. i also use the https://tiktok.com/[creator]/live but that also comes back with the is not live result

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['tiktok.com/@tylerliv314/live', '-vU']
[debug] User config "/data/data/com.termux/files/home/.config/yt-dlp/config": ['--output', '/data/data/com.termux/files/home/storage/shared/_Saved Live Streams/%(uploader)s/%(uploader)s ~ %(fulltitle|).80s ~ %(epoch-3600>%Y-%m-%d ~ %I:%H:%M.%S.%p)s.%(ext)s', '--cookies', '/storage/emulated/0/cookies.txt', '--compat-options', '-no-youtube-channel-redirect,-no-youtube-prefer-utc-upload-date,-no-live-chat,-embed-metadata,-no-external-downloader-progress', '--extractor-args', 'youtube:player-client=web;youtube:player_skip=webpage,web,js;youtube:skip=translated_subs,webpage,web,ios,android;youtubetab:skip=webpage;youtube:formats=duplicate;twitch:twitch:client_id=Y4BQvDDWKlXdICSniiu1qgaVeGcsxiXb;generic:fragment_query=variant_query=VALUE', '--legacy-server-connect', '--fragment-retries', '4', '--skip-unavailable-fragments', '--merge-output-format', 'mp4', '--no-abort-on-error', '--no-cache-dir', '--no-call-home', '--mtime', '--socket-timeout', '30', '--no-part', '--no-part', '--ignore-errors', '--remux-video', 'mp4', '-S', 'tbr:ext=m4a', '-f', 'bv*', '--downloader', 'axel']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.8 (CPython aarch64 64bit) - Linux-5.10.168-android12-9-27760517-abS908U1UES4DXB5-aarch64-with-libc (OpenSSL 3.2.1 30 Jan 2024, libc)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1806 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.03.10 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.03.10 from yt-dlp/yt-dlp)
[generic] Extracting URL: tiktok.com/@tylerliv314/live
WARNING: [generic] The url doesn't specify the protocol, trying with http
[tiktok:live] Extracting URL: http://tiktok.com/@tylerliv314/live
[tiktok:live] tylerliv314: Downloading webpage
[tiktok:live] 7349332158538009390: Downloading JSON metadata
ERROR: [tiktok:live] tylerliv314: The channel is not currently live
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 732, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 1224, in _real_extract
    live_info = self._call_api(
                ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/tiktok.py", line 1204, in _call_api
    raise UserNotLive(video_id=uploader)
```

**Comment by bashonly** [comment] 2024-03-23 02:26
Duplicate of #9418

**Closed by bashonly** 2024-03-23 02:26 UTC
Labels: duplicate, site-bug, site:tiktok
