### ISSUE TITLE
Error spliting opus into chapters with embeded thumbnail

### ISSUE THREAD

**Issue by ethanh92** [yt-dlp/yt-dlp#6826] opened 2023-04-16 05:12 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When splitting an opus file into chapters, I receive an error that prevents the operation from completing if the original, unsplit file contains a thumbnail.

```
  Stream #0:1: Video: png, rgb24(pc), 1280x720, 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Cover (front)
[opus @ 0x557c5f526040] Unsupported codec id in stream 1
[out#0/opus @ 0x557c5f526400] Could not write header (incorrect codec parameters ?): Invalid argument
[vost#0:1/copy @ 0x557c5f534780] Error initializing output stream:
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)


ERROR: Postprocessing:   Stream #0:1 -> #0:1 (copy)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3323, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3502, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3484, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3462, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 1054, in run
    self.real_run_ffmpeg([(in_file, opts)], [(destination, self.stream_copy_opts())])
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 362, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #0:1 -> #0:1 (copy)
```

Here's the config I'm using:

```
--ignore-config

# Naming
--output "%(title)s_%(id)s.%(ext)s"
--paths ~/
--restrict-filenames

# Split chapters
--split-chapters
--output "chapter:%(title)s_%(id)s/%(section_number)02d_%(title)s_%(id)s_%(section_title)s.%(ext)s"
#--output "chapter:%(title)s_%(id)s/%(section_number)02d_%(section_title)s.%(ext)s"

# Embed
--embed-metadata
--embed-chapters
--embed-thumbnail

# Download best audio stream only
--format "(bestaudio) / (bv*+ba/b)"
--extract-audio
--audio-format best

# Do not overwrite existing output files
--no-overwrites

# Concurrent fragments
--concurrent-fragments 8

# Delete original file
--exec "post_process:rm"
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--config-locations=/home/user/.config/yt-dlp/audio-chapter-split', 'https://www.youtube.com/watch?v=87K1dudpDLo', '-vU']
[debug] | Config "/home/user/.config/yt-dlp/audio-chapter-split": ['--ignore-config', '--config-locations=/home/user/.config/yt-dlp/skels/main', '--config-locations=/home/user/.config/yt-dlp/skels/thumbs', '--format', '(bestaudio) / (bv*+ba/b)', '--extract-audio', '--audio-format', 'best', '--split-chapters', '--output', 'chapter:%(title)s_%(id)s/%(section_number)02d_%(title)s_%(id)s_%(section_title)s.%(ext)s', '--exec', 'post_process:rm']
[debug] | | Config "/home/user/.config/yt-dlp/skels/main": ['--output', '%(title)s_%(id)s.%(ext)s', '--paths', '~/', '--restrict-filenames', '--embed-metadata', '--embed-chapters', '--no-overwrites', '--concurrent-fragments', '8']
[debug] | | Config "/home/user/.config/yt-dlp/skels/thumbs": ['--embed-thumbnail']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux-6.2.11-1-ck-generic-v2-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2017.04.17, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: https://www.youtube.com/watch?v=87K1dudpDLo
[youtube] 87K1dudpDLo: Downloading webpage
[youtube] 87K1dudpDLo: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] 87K1dudpDLo: Downloading 1 format(s): 251
[info] Downloading video thumbnail 45 ...
[info] Writing video thumbnail 45 to: /home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.webp
[debug] Invoking dashsegments downloader on "https://rr1---sn-ux3n588t-t8ge.googlevideo.com/videoplayback?expire=1681643134&ei=HYI7ZIjRKICksfIPgeiGuAU&ip=107.190.21.146&id=o-AEi44_f2u51I6IszZ-2apTOakWpziqMx9wHyeG3zubyK&itag=251&source=youtube&requiressl=yes&mh=zL&mm=31%2C29&mn=sn-ux3n588t-t8ge%2Csn-tt1eln7l&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=1252500&spc=99c5CbFK6HkVQrftDZO2WFTHwIpZoqo&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=40053967&dur=2589.021&lmt=1679290509642590&mt=1681621270&fvip=2&keepalive=yes&fexp=24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgHt8ECQTUqYI7cHw4XKu0Llb4YtsQgO3RqSfksXcZA04CIQCg96qvGHRK7l6vXzUdk81WYVd5rFKOj1wPC4_RA7EDCQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKuc8geLc63pRzj1S9y-mxBowEBXTePTjiM5RGBPInz9AiEAnxgo1uxoRGy2oCqhgIY5fl2kQ25-0FmR1M6BwIJGVUM%3D"
[dashsegments] Total fragments: 4
[download] Destination: /home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.webm
WARNING: The download speed shown is only of one thread. This is a known issue

[download]   0.0% of ~  40.00MiB at   14.00KiB/s ETA 48:45 (frag 0/4)
[download]   0.0% of ~  40.00MiB at   41.49KiB/s ETA 16:27 (frag 0/4)
[download]   0.0% of ~  40.00MiB at   95.61KiB/s ETA 07:08 (frag 0/4)
[download]   0.0% of ~  40.00MiB at  202.39KiB/s ETA 03:22 (frag 0/4)
[download]   0.0% of ~  40.00MiB at   11.69KiB/s ETA 58:24 (frag 0/4)
[download]   0.0% of ~  40.00MiB at   34.48KiB/s ETA 19:47 (frag 0/4)
[download]   0.0% of ~  32.79MiB at   11.23KiB/s ETA 49:49 (frag 0/4)
[download]   0.0% of ~  32.79MiB at   33.01KiB/s ETA 16:57 (frag 0/4)
[download]   0.0% of ~  40.00MiB at   75.64KiB/s ETA 09:01 (frag 0/4)
[download]   0.1% of ~  40.00MiB at  331.14KiB/s ETA 02:03 (frag 0/4)
[download]   0.0% of ~  40.00MiB at   10.54KiB/s ETA 01:04:46 (frag 0/4)
[download]   0.0% of ~  40.00MiB at   31.10KiB/s ETA 21:56 (frag 0/4)   
[download]   0.0% of ~  32.79MiB at   71.28KiB/s ETA 07:51 (frag 0/4)
[download]   0.0% of ~  40.00MiB at  150.72KiB/s ETA 04:31 (frag 0/4)
[download]   0.0% of ~  32.79MiB at  148.25KiB/s ETA 03:46 (frag 0/4)
[download]   0.0% of ~  40.00MiB at   68.03KiB/s ETA 10:01 (frag 0/4)
[download]   0.0% of ~  40.00MiB at  143.37KiB/s ETA 04:45 (frag 0/4)
[download]   0.1% of ~  32.79MiB at  291.48KiB/s ETA 01:55 (frag 0/4)
[download]   0.1% of ~  40.00MiB at  281.14KiB/s ETA 02:25 (frag 0/4)
[download]   0.1% of ~  40.00MiB at  276.05KiB/s ETA 02:28 (frag 0/4)
[download]   0.2% of ~  40.00MiB at  555.31KiB/s ETA 01:13 (frag 0/4)
[download]   0.2% of ~  32.79MiB at  507.99KiB/s ETA 01:05 (frag 0/4)
[download]   0.2% of ~  40.00MiB at  489.99KiB/s ETA 01:23 (frag 0/4)
[download]   0.3% of ~  40.00MiB at  962.68KiB/s ETA 00:42 (frag 0/4)
[download]   0.2% of ~  40.00MiB at  470.23KiB/s ETA 01:26 (frag 0/4)
[download]   0.4% of ~  32.79MiB at  849.14KiB/s ETA 00:39 (frag 0/4)
[download]   0.3% of ~  40.00MiB at  787.30KiB/s ETA 00:51 (frag 0/4)
[download]   0.3% of ~  40.00MiB at  775.46KiB/s ETA 00:52 (frag 0/4)
[download]   0.6% of ~  40.00MiB at    1.44MiB/s ETA 00:27 (frag 0/4)
[download]   0.8% of ~  32.79MiB at    1.23MiB/s ETA 00:26 (frag 0/4)
[download]   0.6% of ~  40.00MiB at    1.18MiB/s ETA 00:33 (frag 0/4)
[download]   0.6% of ~  40.00MiB at    1.14MiB/s ETA 00:34 (frag 0/4)
[download]   1.2% of ~  40.00MiB at    1.79MiB/s ETA 00:22 (frag 0/4)
[download]   1.5% of ~  32.79MiB at    1.62MiB/s ETA 00:19 (frag 0/4)
[download]   1.2% of ~  40.00MiB at    1.57MiB/s ETA 00:25 (frag 0/4)
[download]   1.2% of ~  40.00MiB at    1.55MiB/s ETA 00:25 (frag 0/4)
[download]   2.5% of ~  40.00MiB at    2.20MiB/s ETA 00:17 (frag 0/4)
[download]   2.5% of ~  40.00MiB at    1.99MiB/s ETA 00:19 (frag 0/4)
[download]   2.5% of ~  40.00MiB at    1.95MiB/s ETA 00:20 (frag 0/4)
[download]   3.0% of ~  32.79MiB at    1.91MiB/s ETA 00:16 (frag 0/4)
[download]   5.0% of ~  40.00MiB at    2.46MiB/s ETA 00:15 (frag 0/4)
[download]   5.0% of ~  40.00MiB at    2.26MiB/s ETA 00:16 (frag 0/4)
[download]   5.0% of ~  40.00MiB at    2.23MiB/s ETA 00:17 (frag 0/4)
[download]   6.1% of ~  32.79MiB at    2.21MiB/s ETA 00:13 (frag 0/4)
[download]  10.0% of ~  40.00MiB at    2.46MiB/s ETA 00:14 (frag 0/4)
[download]  10.0% of ~  40.00MiB at    2.31MiB/s ETA 00:15 (frag 0/4)
[download]  10.0% of ~  40.00MiB at    2.31MiB/s ETA 00:15 (frag 0/4)
[download]  12.2% of ~  32.79MiB at    2.30MiB/s ETA 00:12 (frag 0/4)
[download]  16.1% of ~  40.00MiB at    2.49MiB/s ETA 00:13 (frag 0/4)
[download]  15.9% of ~  40.00MiB at    2.44MiB/s ETA 00:13 (frag 0/4)
[download]  15.9% of ~  40.00MiB at    2.42MiB/s ETA 00:13 (frag 0/4)
[download]  19.5% of ~  32.79MiB at    2.41MiB/s ETA 00:10 (frag 0/4)
[download]  25.0% of ~  32.79MiB at    2.43MiB/s ETA 00:10 (frag 0/4)
[download]  25.0% of ~  32.79MiB at    2.43MiB/s ETA 00:10 (frag 1/4)
[download]  47.2% of ~  36.40MiB at   47.13MiB/s ETA 00:03 (frag 1/4)
[download]  47.4% of ~  36.40MiB at   34.82MiB/s ETA 00:04 (frag 1/4)
[download]  47.4% of ~  36.40MiB at   33.77MiB/s ETA 00:04 (frag 1/4)
[download]  50.0% of ~  36.40MiB at   19.99MiB/s ETA 00:03 (frag 1/4)
[download]  50.0% of ~  36.40MiB at   19.90MiB/s ETA 00:03 (frag 2/4)
[download]  75.0% of ~  37.60MiB at  298.82MiB/s ETA 00:01 (frag 2/4)
[download]  75.0% of ~  37.60MiB at  286.03MiB/s ETA 00:01 (frag 3/4)
[download] 100.0% of ~  38.20MiB at  207.29MiB/s ETA 00:00 (frag 3/4)
[download] 100.0% of ~  38.20MiB at  199.30MiB/s ETA 00:00 (frag 4/4)
[download] 100% of   38.20MiB in 00:00:04 at 9.53MiB/s               
[debug] ffmpeg command line: ffprobe -show_streams file:/home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.webm
[ExtractAudio] Destination: /home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.opus
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:/home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.webm -vn -acodec copy -movflags +faststart file:/home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.opus
Deleting original file /home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.webm (pass -k to keep)
[Metadata] Adding metadata to "/home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.opus"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:/home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.opus -i file:/home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.meta -map 0 -dn -ignore_unknown -c copy -map_metadata 1 -write_id3v1 1 -metadata 'title=Afsky - Om Hundrede År (Full Album)' -metadata date=20230315 -metadata 'description=Country: Denmark | Year: 2023 | Genre: Black Metal 

CD, MC & Digital Album available here: 
https://afsky.bandcamp.com/album/om-hundrede-r 
https://vendetta-records.bandcamp.com/album/om-hundrede-r 
https://vendettarecords.bigcartel.com 

- Afsky -
Facebook: https://www.facebook.com/afskymusic
Instagram: https://www.instagram.com/afskyofficial 
Bandcamp: https://afsky.bandcamp.com
Youtube: https://www.youtube.com/channel/UCioLxfiu1AUWUEagGypDGxw
Metal Archives: https://www.metal-archives.com/bands/Afsky/3540403189

- Vendetta Records - 
Website: https://vendetta-records.com 
Webshop: https://vendettarecords.bigcartel.com
Facebook: https://www.facebook.com/pages/vendetta/113775778703319
Instagram: https://www.instagram.com/vendettarecs
Bandcamp: https://vendetta-records.bandcamp.com 

Tracklist: 
1. Stormfulde hav 00:00
2. Frosne vind 07:51
3. Tak for alt 15:18
4. Det der var 22:41
5. Tid 29:30
6. Fred være med støvet 36:29

Upload on behalf of Afsky!' -metadata 'synopsis=Country: Denmark | Year: 2023 | Genre: Black Metal 

CD, MC & Digital Album available here: 
https://afsky.bandcamp.com/album/om-hundrede-r 
https://vendetta-records.bandcamp.com/album/om-hundrede-r 
https://vendettarecords.bigcartel.com 

- Afsky -
Facebook: https://www.facebook.com/afskymusic
Instagram: https://www.instagram.com/afskyofficial 
Bandcamp: https://afsky.bandcamp.com
Youtube: https://www.youtube.com/channel/UCioLxfiu1AUWUEagGypDGxw
Metal Archives: https://www.metal-archives.com/bands/Afsky/3540403189

- Vendetta Records - 
Website: https://vendetta-records.com 
Webshop: https://vendettarecords.bigcartel.com
Facebook: https://www.facebook.com/pages/vendetta/113775778703319
Instagram: https://www.instagram.com/vendettarecs
Bandcamp: https://vendetta-records.bandcamp.com 

Tracklist: 
1. Stormfulde hav 00:00
2. Frosne vind 07:51
3. Tak for alt 15:18
4. Det der var 22:41
5. Tid 29:30
6. Fred være med støvet 36:29

Upload on behalf of Afsky!' -metadata 'purl=https://www.youtube.com/watch?v=87K1dudpDLo' -metadata 'comment=https://www.youtube.com/watch?v=87K1dudpDLo' -metadata 'artist=Black Metal Promotion' -movflags +faststart file:/home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.temp.opus
[ThumbnailsConvertor] Converting thumbnail "/home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i file:/home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.webp -update 1 -movflags +faststart file:/home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.png
[EmbedThumbnail] mutagen: Adding thumbnail to "/home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.opus"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:/home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.png
[SplitChapters] Splitting video by chapters; 6 chapters found
[SplitChapters] Chapter 001; Destination: /home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo/01_Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo_1._Stormfulde_hav.opus
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -ss 0.0 -t 471.0 -i file:/home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.opus -map 0 -dn -ignore_unknown -c copy -movflags +faststart file:/home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo/01_Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo_1._Stormfulde_hav.opus
[debug] ffmpeg version n6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.1 (GCC) 20230201
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[ogg @ 0x55ea68539000] 40492 bytes of comment header remain
Input #0, ogg, from 'file:/home/user/Afsky_-_Om_Hundrede_Ar_Full_Album_87K1dudpDLo.opus':
  Duration: 00:43:09.02, start: 0.000000, bitrate: 127 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 471.000000
      Metadata:
        title           : 1. Stormfulde hav
    Chapter #0:1: start 471.000000, end 918.000000
      Metadata:
        title           : 2. Frosne vind
    Chapter #0:2: start 918.000000, end 1361.000000
      Metadata:
        title           : 3. Tak for alt
    Chapter #0:3: start 1361.000000, end 1770.000000
      Metadata:
        title           : 4. Det der var
    Chapter #0:4: start 1770.000000, end 2189.000000
      Metadata:
        title           : 5. Tid
    Chapter #0:5: start 2189.000000, end 2589.020000
      Metadata:
        title           : 6. Fred være med støvet
  Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      encoder         : Lavf60.3.100
      title           : Afsky - Om Hundrede År (Full Album)
      date            : 20230315
      purl            : https://www.youtube.com/watch?v=87K1dudpDLo
      synopsis        : Country: Denmark | Year: 2023 | Genre: Black Metal 
                      : 
                      : CD, MC & Digital Album available here: 
                      : https://afsky.bandcamp.com/album/om-hundrede-r 
                      : https://vendetta-records.bandcamp.com/album/om-hundrede-r 
                      : https://vendettarecords.bigcartel.com 
                      : 
                      : - Afsky -
                      : Facebook: https://www.facebook.com/afskymusic
                      : Instagram: https://www.instagram.com/afskyofficial 
                      : Bandcamp: https://afsky.bandcamp.com
                      : Youtube: https://www.youtube.com/channel/UCioLxfiu1AUWUEagGypDGxw
                      : Metal Archives: https://www.metal-archives.com/bands/Afsky/3540403189
                      : 
                      : - Vendetta Records - 
                      : Website: https://vendetta-records.com 
                      : Webshop: https://vendettarecords.bigcartel.com
                      : Facebook: https://www.facebook.com/pages/vendetta/113775778703319
                      : Instagram: https://www.instagram.com/vendettarecs
                      : Bandcamp: https://vendetta-records.bandcamp.com 
                      : 
                      : Tracklist: 
                      : 1. Stormfulde hav 00:00
                      : 2. Frosne vind 07:51
                      : 3. Tak for alt 15:18
                      : 4. Det der var 22:41
                      : 5. Tid 29:30
                      : 6. Fred være med støvet 36:29
                      : 
                      : Upload on behalf of Afsky!
      comment         : https://www.youtube.com/watch?v=87K1dudpDLo
      artist          : Black Metal Promotion
  Stream #0:1: Video: png, rgb24(pc), 1280x720, 90k tbr, 90k tbn (attached pic)
    Metadata:
      comment         : Cover (front)
[opus @ 0x55ea68579040] Unsupported codec id in stream 1
[out#0/opus @ 0x55ea68579400] Could not write header (incorrect codec parameters ?): Invalid argument
[vost#0:1/copy @ 0x55ea68587780] Error initializing output stream: 
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)


ERROR: Postprocessing:   Stream #0:1 -> #0:1 (copy)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3323, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3502, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3484, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3462, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 1054, in run
    self.real_run_ffmpeg([(in_file, opts)], [(destination, self.stream_copy_opts())])
  File "/usr/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 362, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #0:1 -> #0:1 (copy)
```

**Comment by bashonly** [comment] 2023-04-16 08:40
Duplicate of #6225

**Closed by bashonly** 2023-04-16 08:40 UTC
Labels: bug, triage
