### ISSUE TITLE
[YouTube] `android_embedscreen`: Skipping player responses

### ISSUE THREAD

**Issue by joaquinito2070** [yt-dlp/yt-dlp#9725] opened 2024-04-19 09:57 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

As for today, yt-dlp is not working correctly.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\marco>yt-dlp --list-formats --extractor-args "youtube:player_client=all" ytsearch:"CantaJuego Lo Mejor de Rodri"
[youtube:search] Extracting URL: ytsearch:CantaJuego Lo Mejor de Rodri
[download] Downloading playlist: CantaJuego Lo Mejor de Rodri
[youtube:search] query "CantaJuego Lo Mejor de Rodri": Downloading web client config
[youtube:search] query "CantaJuego Lo Mejor de Rodri" page 1: Downloading API JSON
[youtube:search] Playlist CantaJuego Lo Mejor de Rodri: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=yZgwnRIC7gY
[youtube] yZgwnRIC7gY: Downloading webpage
[youtube] yZgwnRIC7gY: Downloading ios player API JSON
[youtube] yZgwnRIC7gY: Downloading ios embedded player API JSON
[youtube] yZgwnRIC7gY: Downloading ios music player API JSON
[youtube] yZgwnRIC7gY: Downloading ios creator player API JSON
[youtube] yZgwnRIC7gY: Downloading ios embedscreen player API JSON
[youtube] yZgwnRIC7gY: Downloading android player API JSON
[youtube] yZgwnRIC7gY: Downloading android embedded player API JSON
[youtube] yZgwnRIC7gY: Downloading android music player API JSON
[youtube] yZgwnRIC7gY: Downloading android creator player API JSON
[youtube] yZgwnRIC7gY: Downloading android embedscreen player API JSON
[youtube] yZgwnRIC7gY: Downloading web embedded client config
[youtube] yZgwnRIC7gY: Downloading player 0af6e327
[youtube] yZgwnRIC7gY: Downloading web embedded player API JSON
[youtube] yZgwnRIC7gY: Downloading web music client config
[youtube] yZgwnRIC7gY: Downloading web music player API JSON
[youtube] yZgwnRIC7gY: Downloading web creator player API JSON
[youtube] yZgwnRIC7gY: Downloading web embedscreen player API JSON
[youtube] yZgwnRIC7gY: Downloading tv embedded player API JSON
[youtube] yZgwnRIC7gY: Downloading mweb player API JSON
[youtube] yZgwnRIC7gY: Downloading mweb embedscreen player API JSON
WARNING: [youtube] Skipping player responses from android_embedscreen clients (got player responses for video "aQvGIIdgFDM" instead of "yZgwnRIC7gY")
[youtube] yZgwnRIC7gY: Downloading m3u8 information
[youtube] yZgwnRIC7gY: Downloading m3u8 information
[youtube] yZgwnRIC7gY: Downloading m3u8 information
[youtube] yZgwnRIC7gY: Downloading m3u8 information
[youtube] yZgwnRIC7gY: Downloading m3u8 information
[info] Available formats for yZgwnRIC7gY:
ID      EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb3     mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb2     mhtml 80x45        0    │                  mhtml │ images                                  storyboard
sb1     mhtml 160x90       0    │                  mhtml │ images                                  storyboard
sb0     mhtml 320x180      0    │                  mhtml │ images                                  storyboard
233     mp4   audio only        │                  m3u8  │ audio only          unknown             Default
234     mp4   audio only        │                  m3u8  │ audio only          unknown             Default
599     m4a   audio only      2 │    9.66MiB   31k https │ audio only          mp4a.40.5   31k 22k ultralow, m4a_dash
600     webm  audio only      2 │   11.17MiB   36k https │ audio only          opus        36k 48k ultralow, webm_dash
249-drc webm  audio only      2 │   16.46MiB   52k https │ audio only          opus        52k 48k low, DRC, webm_dash
250-drc webm  audio only      2 │   21.72MiB   69k https │ audio only          opus        69k 48k low, DRC, webm_dash
139     m4a   audio only      2 │   15.31MiB   49k https │ audio only          mp4a.40.5   49k 22k low, m4a_dash
249     webm  audio only      2 │   16.46MiB   52k https │ audio only          opus        52k 48k low, webm_dash
250     webm  audio only      2 │   21.72MiB   69k https │ audio only          opus        69k 48k low, webm_dash
140-drc m4a   audio only      2 │   40.63MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, DRC, m4a_dash

251-drc webm  audio only      2 │   42.68MiB  136k https │ audio only          opus       136k 48k medium, DRC, webm_dash
140     m4a   audio only      2 │   40.63MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, m4a_dash
251     webm  audio only      2 │   42.67MiB  136k https │ audio only          opus       136k 48k medium, webm_dash
597     mp4   256x144     13    │   10.18MiB   32k https │ avc1.4d400b     32k video only          144p, mp4_dash
602     mp4   256x144     13    │ ~ 34.11MiB  109k m3u8  │ vp09.00.10.08  109k video only
598     webm  256x144     13    │    9.26MiB   29k https │ vp9             29k video only          144p, webm_dash
269     mp4   256x144     25    │ ~ 53.95MiB  172k m3u8  │ avc1.4D400C    172k video only
160     mp4   256x144     25    │   32.02MiB  102k https │ avc1.4D400C    102k video only          144p, mp4_dash
603     mp4   256x144     25    │ ~ 55.01MiB  175k m3u8  │ vp09.00.11.08  175k video only
278     webm  256x144     25    │   24.08MiB   77k https │ vp09.00.11.08   77k video only          144p, webm_dash
229     mp4   426x240     25    │ ~ 98.20MiB  313k m3u8  │ avc1.4D4015    313k video only
133     mp4   426x240     25    │   69.30MiB  221k https │ avc1.4D4015    221k video only          240p, mp4_dash
604     mp4   426x240     25    │ ~ 99.83MiB  318k m3u8  │ vp09.00.20.08  318k video only
242     webm  426x240     25    │   48.30MiB  154k https │ vp09.00.20.08  154k video only          240p, webm_dash
230     mp4   640x360     25    │ ~252.80MiB  805k m3u8  │ avc1.4D401E    805k video only
134     mp4   640x360     25    │  152.59MiB  486k https │ avc1.4D401E    486k video only          360p, mp4_dash
18      mp4   640x360     25  2 │ ≈193.13MiB  615k https │ avc1.42001E         mp4a.40.2       44k 360p
605     mp4   640x360     25    │ ~249.69MiB  796k m3u8  │ vp09.00.21.08  796k video only
243     webm  640x360     25    │  117.93MiB  376k https │ vp09.00.21.08  376k video only          360p, webm_dash
231     mp4   854x480     25    │ ~426.91MiB 1360k m3u8  │ avc1.4D401E   1360k video only
135     mp4   854x480     25    │  245.78MiB  783k https │ avc1.4D401E    783k video only          480p, mp4_dash
606     mp4   854x480     25    │ ~384.14MiB 1224k m3u8  │ vp09.00.30.08 1224k video only
244     webm  854x480     25    │  170.12MiB  542k https │ vp09.00.30.08  542k video only          480p, webm_dash
22      mp4   1280x720    25  2 │ ≈424.62MiB 1353k https │ avc1.64001F         mp4a.40.2       44k 720p
232     mp4   1280x720    25    │ ~806.22MiB 2569k m3u8  │ avc1.4D401F   2569k video only
136     mp4   1280x720    25    │  384.07MiB 1224k https │ avc1.4D401F   1224k video only          720p, mp4_dash
609     mp4   1280x720    25    │ ~715.82MiB 2281k m3u8  │ vp09.00.31.08 2281k video only
247     webm  1280x720    25    │  340.12MiB 1084k https │ vp09.00.31.08 1084k video only          720p, webm_dash
270     mp4   1920x1080   25    │ ~  1.44GiB 4696k m3u8  │ avc1.640028   4696k video only
137     mp4   1920x1080   25    │    1.11GiB 3612k https │ avc1.640028   3612k video only          1080p, mp4_dash
614     mp4   1920x1080   25    │ ~  1.21GiB 3942k m3u8  │ vp09.00.40.08 3942k video only
248     webm  1920x1080   25    │  554.18MiB 1766k https │ vp09.00.40.08 1766k video only          1080p, webm_dash
616     mp4   1920x1080   25    │ ~  1.79GiB 5843k m3u8  │ vp09.00.40.08 5843k video only          Premium
[download] Finished downloading playlist: CantaJuego Lo Mejor de Rodri
```

**Comment by bashonly** [comment] 2024-04-20 17:53
The problem is intermittent and likely a symptom of Youtube slowly killing the player params we use for all Android client requests

**Comment by bashonly** [comment] 2024-04-23 04:49
Closing as duplicate of #9554

**Closed by bashonly** 2024-04-23 04:49 UTC
Labels: site-bug

**Comment by liaolingfen4** [comment] 2024-05-09 07:50
any update？
