### ISSUE TITLE
facebookreels yt_dlp.utils.DownloadError: ERROR: [facebook] 976838136866036: Cannot parse data

### ISSUE THREAD

**Issue by kishoreyakkanti** [yt-dlp/yt-dlp#8145] opened 2023-09-18 09:57 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt_dlp.utils.DownloadError: ERROR: [facebook] 976838136866036: Cannot parse data

[facebook:reel] Extracting URL: https://www.facebook.com/reel/976838136866036
[facebook] Extracting URL: https://m.facebook.com/watch/?v=976838136866036&_rdr
[facebook] 976838136866036: Downloading webpage
[facebook] 976838136866036: Downloading webpage
ERROR: [facebook] 976838136866036: Cannot parse data;

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
info = ydl.extract_info(url, download=False)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1549, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1709, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1791, in process_ie_result
    extra_info=extra_info)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1549, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1578, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1042, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/datascience.apis/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 981, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [facebook] 976838136866036: Cannot parse data;
```

**Comment by bashonly** [comment] 2023-09-18 10:11
Duplicate of #7901

[Install from the master branch](https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-master) or [get the nightly build](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest)

**Closed by bashonly** 2023-09-18 10:11 UTC
Labels: duplicate, site-bug, site:facebook

**Comment by kishoreyakkanti** [comment] 2023-09-21 10:40
Thank you its working
