### ISSUE TITLE
Stripchat extractor not working

### ISSUE THREAD

**Issue by Freshro** [yt-dlp/yt-dlp#7325] opened 2023-06-16 11:49 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Provide a description that is worded well enough to be understood

Extractor is unable to find any active streams.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://stripchat.com/M--I--A
[debug] Command-line config: ['-vU', 'https://stripchat.com/M--I--A']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 2023-02-13-git-2296078397-full_build-www.gyan.dev (setts), ffprobe 2023-02-13-git-2296078397-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1843 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[Stripchat] Extracting URL: https://stripchat.com/M--I--A
[Stripchat] M--I--A: Downloading webpage
[Stripchat] M--I--A: Downloading m3u8 information
WARNING: [Stripchat] Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: [Stripchat] M--I--A: No active streams found
  File "C:\Users\Dab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\extractor\common.py", line 704, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Dab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\extractor\stripchat.py", line 57, in _real_extract
    self.raise_no_formats('No active streams found', expected=True)
  File "C:\Users\Dab\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\yt_dlp\extractor\common.py", line 1182, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by bashonly** [comment] 2023-06-16 11:58
This was just fixed yesterday in f9213f8a2d7ba46b912afe1dd3ce6bb700a33d72

if running from source: pull from master
if running from exe/binary: `yt-dlp --update-to nightly`
if running pip installation: [install from master branch](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip)

Duplicate of #7305

**Closed by bashonly** 2023-06-16 11:58 UTC
Labels: site-bug, triage
