### ISSUE TITLE
[ArteTV] : No video formats found

### ISSUE THREAD

**Issue by Titanet** [yt-dlp/yt-dlp#8226] opened 2023-09-28 19:55 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

$ yt-dlp https://www.arte.tv/fr/videos/108497-000-A/fanny-ardant-naissance-d-une-passion/
[ArteTV] Extracting URL: https://www.arte.tv/fr/videos/108497-000-A/fanny-ardant-naissance-d-une-passion/
[ArteTV] 108497-000-A: Downloading JSON metadata
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
ERROR: [ArteTV] 108497-000-A: No video formats found!; please report this issue

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.arte.tv/fr/videos/108497-000-A/fanny-ardant-naissance-d-une-passion/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481]
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-6.1.53-1-MANJARO-x86_64-with-glibc2.38 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.47.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.07.06
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
ERROR: You installed yt-dlp with a package manager or setup.py; Use that to update
[ArteTV] Extracting URL: https://www.arte.tv/fr/videos/108497-000-A/fanny-ardant-naissance-d-une-passion/
[ArteTV] 108497-000-A: Downloading JSON metadata
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
WARNING: [ArteTV] Skipping stream with unknown protocol API_HLS_NG
ERROR: [ArteTV] 108497-000-A: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1560, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1709, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1768, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2732, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1073, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [ArteTV] 108497-000-A: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment] 2023-09-28 20:01
> - [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)

> [debug] yt-dlp version stable@2023.07.06 [b532a3481]

Update

Duplicate of #8156

Fixed in c2da0b5ea215298135f76e3dc14b972a3c4afacb

**Closed by bashonly** 2023-09-28 20:01 UTC
Labels: site-bug, triage
