### ISSUE TITLE
Facebook Reels video download error

### ISSUE THREAD

**Issue by namgod99** [yt-dlp/yt-dlp#10244] opened 2024-06-23 10:54 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Vietnamese

### Provide a description that is worded well enough to be understood

Facebook Reels video download error

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', '--merge-output-format', 'mp4', '--postprocessor-args', '-c:v libx264 -c:a aac', '-o', 'D:\\Downloads\\Video\\test\\%(title).50s.%(ext)s', '-a', 'D:\\Downloads\\Video\\test.txt']
[debug] Batch file urls: ['https://www.facebook.com/reel/991364288915525', 'https://www.facebook.com/reel/771980511482187', 'https://www.facebook.com/reel/554328930256471', 'https://www.facebook.com/reel/791420246168498', 'https://www.facebook.com/reel/1601802577053541', 'https://www.facebook.com/reel/885029770333773', 'https://www.facebook.com/reel/806189081604732', 'https://www.facebook.com/reel/1486036938673421', 'https://www.facebook.com/reel/875409411049923', 'https://www.facebook.com/reel/1832577750575141', 'https://www.facebook.com/reel/805855678303552', 'https://www.facebook.com/reel/753444033370050', 'https://www.facebook.com/reel/991636582286327', 'https://www.facebook.com/reel/827323909336578', 'https://www.facebook.com/reel/1001239021526753', 'https://www.facebook.com/reel/428106070059342', 'https://www.facebook.com/reel/1909951286142101', 'https://www.facebook.com/reel/486983817173844', 'https://www.facebook.com/reel/796507252617321', 'https://www.facebook.com/reel/418075314550847', 'https://www.facebook.com/reel/437772052408808', 'https://www.facebook.com/reel/996139615258025', 'https://www.facebook.com/reel/335314479442894', 'https://www.facebook.com/reel/1404544860258376']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-06-16-git-fcf72966a5-essentials_build-www.gyan.dev (setts), ffprobe 2024-06-16-git-fcf72966a5-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.2, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
WARNING: Post-Processor arguments given without specifying name. The arguments will be given to all post-processors
[debug] Loaded 1820 extractors
[facebook:reel] Extracting URL: https://www.facebook.com/reel/991364288915525
[facebook] Extracting URL: https://m.facebook.com/watch/?v=991364288915525&_rdr
[facebook] 991364288915525: Downloading webpage
ERROR: [facebook] 991364288915525: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1606, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1762, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1821, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2825, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1104, in raise_no_formats
yt_dlp.utils.ExtractorError: [facebook] 991364288915525: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[facebook:reel] Extracting URL: https://www.facebook.com/reel/771980511482187
[facebook] Extracting URL: https://m.facebook.com/watch/?v=771980511482187&_rdr
[facebook] 771980511482187: Downloading webpage
ERROR: [facebook] 771980511482187: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1606, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1762, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1821, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2825, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1104, in raise_no_formats
yt_dlp.utils.ExtractorError: [facebook] 771980511482187: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[facebook:reel] Extracting URL: https://www.facebook.com/reel/554328930256471
[facebook] Extracting URL: https://m.facebook.com/watch/?v=554328930256471&_rdr
[facebook] 554328930256471: Downloading webpage
```

**Comment by seproDev** [comment] 2024-06-23 10:55
Duplicate of #10227

Update to nightly:
```
yt-dlp --update-to nightly
```

**Closed by seproDev** 2024-06-23 10:55 UTC
Labels: duplicate, site-bug, site:facebook

**Comment by josepine** [comment] 2024-06-24 10:47
is there any way to download facebook reel videos right now?
![image](https://github.com/yt-dlp/yt-dlp/assets/173683087/37ec280a-358d-4d3c-a308-5a54d2d5861e)

**Comment by seproDev** [comment] 2024-06-24 10:51
@josepine Read the comment above yours. You need to update to nightly by running:
```
yt-dlp --update-to nightly
```

**Comment by josepine** [comment] 2024-06-24 13:30
> @josepine Read the comment above yours. You need to update to nightly by running:
> 
> ```
> yt-dlp --update-to nightly
> ```

thanks @seproDev
