### ISSUE TITLE
Newgrounds downloads a .com file instead of a .mp4 file

### ISSUE THREAD

**Issue by Adamantcheese** [yt-dlp/yt-dlp#7780] opened 2023-08-06 07:38 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Newgrounds downloads a .com file instead of a .mp4 file. Manually going to the page and finding the appropriate \<video> element and using that URL downloads the proper file. Unsure if this is a result of using aria2c as an external downloader, but my understanding is that aria2c is only invoked once the proper URL is determined by yt-dlp. Site changes may have broken the site, but I'm not sure and I don't feel like that's likely. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--config-location', 'C:\\bin', '-vU', 'https://www.newgrounds.com/portal/view/893377', 'https://www.newgrounds.com/portal/view/893377']
[debug] | Config "C:\bin\yt-dlp.conf": ['--rm-cache-dir', '-f', 'bestvideo+bestaudio/best', '--ffmpeg-location', 'C:\\bin', '--external-downloader', 'aria2c', '--external-downloader-args', 'aria2c:--continue --max-concurrent-downloads 8 --max-connection-per-server 16 --split 3 --min-split-size 1M', '-o', 'F:\\VIDEO ARCHIVE\\youtube-dl\\%(title).160s-%(id)s.%(ext)s', '--audio-format', 'mp3', '--audio-quality', '320K', '--embed-subs', '--cookies-from-browser', 'firefox']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-96489-g670799697e-g1ab302da6e (fdk), ffprobe N-96489-g670799697e-g1ab302da6e, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\<user>\AppData\Roaming\Mozilla\Firefox\Profiles\gu2i0z36.default-1512098829284\cookies.sqlite"
[Cookies] Extracted 1198 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
Removing cache dir C:\Users\<user>/.cache\yt-dlp ..
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[Newgrounds] Extracting URL: https://www.newgrounds.com/portal/view/893377
[Newgrounds] 893377: Downloading webpage
[Newgrounds] 893377: Checking source video format URL
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 893377: Downloading 1 format(s): source
[info] There are no subtitles for the requested languages
[debug] Invoking aria2c downloader on "https://<user>.newgrounds.com"
[download] Destination: F:\VIDEO ARCHIVE\youtube-dl\Top and RabRab - Player 3-893377.com
[download] Writing temporary cookies file to "C:\Users\<user>\AppData\Local\Temp\tmpaktjqxkn.cookies"
[debug] aria2c command line: aria2c -c --no-conf "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--http-accept-gzip=true" "--file-allocation=none" -x16 -j16 -s16 --min-split-size 1M "--load-cookies=C:\Users\<user>\AppData\Local\Temp\tmpaktjqxkn.cookies" --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.24 Safari/537.36" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Language: en-us,en;q=0.5" --header "Sec-Fetch-Mode: navigate" "--check-certificate=true" "--remote-time=true" "--show-console-readout=true" --continue --max-concurrent-downloads 8 --max-connection-per-server 16 --split 3 --min-split-size 1M --dir "F:\VIDEO ARCHIVE\youtube-dl\" --out ".\Top and RabRab - Player 3-893377.com.part" "--auto-file-renaming=false" -- "https://<user>.newgrounds.com"
[download] 100% of   77.32KiB in 00:00:00 at 90.82KiB/s
[EmbedSubtitle] Subtitles can only be embedded in mp4, mov, m4a, webm, mkv, mka files
[Newgrounds] Extracting URL: https://www.newgrounds.com/portal/view/893377
[Newgrounds] 893377: Downloading webpage
[Newgrounds] 893377: Checking source video format URL
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 893377: Downloading 1 format(s): source
[info] There are no subtitles for the requested languages
[debug] Invoking aria2c downloader on "https://<user>.newgrounds.com"
[download] F:\VIDEO ARCHIVE\youtube-dl\Top and RabRab - Player 3-893377.com has already been downloaded
[download] 100% of   77.32KiB
[EmbedSubtitle] Subtitles can only be embedded in mp4, mov, m4a, webm, mkv, mka files
```

**Comment by bashonly** [comment] 2023-08-06 10:07
Duplicate of #6488

**Comment by bashonly** [comment] 2023-08-06 10:08
Workaround: `--no-cookies-from-browser`

**Closed by bashonly** 2023-08-06 10:07 UTC
Labels: site-bug, triage
