### ISSUE TITLE
Not downloading subtitle from NBC(HTTP Error 403)

### ISSUE THREAD

**Issue by MoHasan7** [yt-dlp/yt-dlp#11268] opened 2024-10-16 20:24 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

I want to download subtitle from the link (https://www.nbc.com/sed-de-venganza/video/prueba-de-lealtad/9000406641) but it shows the error of "video URL is invalid, skipping: HTTP Error 403: Forbidden." is there a solution?

the subtitle is available in NBC in spanish.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--all-subs', '--skip-download', 'https://www.nbc.com/sed-de-venganza/video/prueba-de-lealtad/9000406641']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.15.232919 from yt-dlp/yt-dlp-nightly-builds [64d84d75c] (pip)
[debug] Python 3.11.4 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: ffmpeg 2021-10-30-git-d92fdc7144-full_build-www.gyan.dev (setts), ffprobe 2021-10-30-git-d92fdc7144-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, requests-2.32.3, sqlite3-3.42.0, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {'http': 'http://127.0.0.1:10809', 'https': 'http://127.0.0.1:10809', 'ftp': 'http://127.0.0.1:10809'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.15.232919 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.15.232919 from yt-dlp/yt-dlp-nightly-builds)
[NBC] Extracting URL: https://www.nbc.com/sed-de-venganza/video/prueba-de-lealtad/9000406641
[NBC] 9000406641: Downloading JSON metadata
[NBC] 9000406641: Downloading JSON metadata
[ThePlatform] Extracting URL: http://link.theplatform.com/s/NnzsPC/media/guid/2304991196/9000406641?mbr=true&manifest=m3u&switch=HLSServiceSecure#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] 9000406641: Downloading SMIL data
[ThePlatform] 9000406641: Checking video URL
[ThePlatform] 9000406641: video URL is invalid, skipping: HTTP Error 403: Forbidden
[ThePlatform] 9000406641: Checking for HLS formats
WARNING: [ThePlatform] No HLS formats found: HTTP Error 403: Forbidden
[ThePlatform] 9000406641: Downloading JSON metadata
[info] 9000406641: Downloading subtitles: en
ERROR: [ThePlatform] 9000406641: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1894, in process_ie_result
    return self.process_ie_result(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 2847, in process_video_result
    self.raise_no_formats(info_dict)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1123, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [ThePlatform] 9000406641: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment] 2024-10-16 20:53
if you only want the subtitles, you can add `--ignore-no-formats` to your command

as for the video, it appears to be DRM protected. can you play it in your browser [with DRM disabled](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)?

**Comment by MoHasan7** [comment] 2024-10-16 21:16
> if you only want the subtitles, you can add `--ignore-no-formats` to your command
> 
> as for the video, it appears to be DRM protected. can you play it in your browser [with DRM disabled](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)?

thanks. I just needed to download subtitle and the command worked fine for me.

I can't play the video based on what you said and it seems it's a DRM protected video.

**Comment by bashonly** [comment] 2024-10-16 21:22
Closing as duplicate of #11148

**Closed by bashonly** 2024-10-16 21:22 UTC
Labels: site-bug, triage
