### ISSUE TITLE
[Question] --no-download-archive --no-mark-watched when printing video information

### ISSUE THREAD

**Issue by idMysteries** [yt-dlp/yt-dlp#1092] opened 2021-09-26 12:31 UTC
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I can't print information about the video if it is in the archive. For example:
`yt-dlp --print id --playlist-end 1 https://www.youtube.com/playlist?list=WL` prints an empty line if the first video is in the archive
I have to add the parameter "--no-download-archive".
I also need to add the "--no-mark-watched " parameter so that the video is not marked as viewed if the parameter is in the configuration file. Can you fix it?

**Comment by pukkandan** [comment] 2021-09-26 12:36
The point of using a download archive is that the video is not processed if it is the archive. So this is intended behavior

**Comment by idMysteries** [comment] 2021-09-26 12:39
> 
> 
> The point of using a download archive is that the video is not processed if it is the archive. So this is intended behavior

Then it is not possible to print information about the playlist. There is also a problem with --mark-watched.

**Comment by pukkandan** [comment] 2021-09-26 12:41
It is possible. Just don't use `--download-archive`. Or use `--no-download-archive` or `--no-config` to override the setting in configuration. You can't pass an option to yt-dlp and expect it to ignore it. There are usecases where `--print` and the archive are used together intentionally

**Comment by idMysteries** [comment] 2021-09-26 12:46
> 
> 
> It is possible. Just don't use `--download-archive`. Or use `--no-download-archive` or `--no-config` to override the setting in configuration. You can't pass an option to yt-dlp and expect it to ignore it. There are usecases where `--print` and the archive are used together intentionally

OK. When I used the "-J" (dump single json) parameter, the entire playlist was marked as viewed. Is this intentional behavior?

**Comment by pukkandan** [comment] 2021-09-26 13:16
Marked as watched? yes, that is intended.

If it got written to archive, there is some issue (unless you used some other option to force it). If that is the case, show me the verbose log

**Comment by idMysteries** [comment] 2021-09-26 13:19
> 
> 
> Marked as watched? yes, that is intended.
> 
> If it got written to archive, there is some issue (unless you used some other option to force it). If that is the case, show me the verbose log

I just don't understand why the video is marked as watched if I'm just "--print" information.

**Comment by pukkandan** [comment] 2021-09-26 13:22
Marking as watched is part of the extraction process. It doesn't matter if you downloaded it or not. It could be argued that it should work like download-archive, but this is how youtube-dl handles this, and the hassle of changing this is not worth it since you can just use `--no-mark-watched` when simulating

**Comment by pukkandan** [comment] 2021-09-26 13:23
I will update the docs to make this clearer

**Closed** 2021-09-26 13:23 UTC
Labels: question
