### ISSUE TITLE
[tiktok:user]

### ISSUE THREAD

**Issue by 2936747557** [yt-dlp/yt-dlp#5109] opened 2022-10-02 05:33 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Unable to download webpage: HTTP Error 403: Forbidden？

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
>yt-dlp https://www.tiktok.com/@mich.bunny
[tiktok:user] Setting up session
WARNING: [tiktok:user] Unable to download webpage: HTTP Error 403: Forbidden
[tiktok:user] mich.bunny: Downloading webpage
[tiktok:user] mich.bunny: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 1 of 5)
[tiktok:user] mich.bunny: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 2 of 5)
[tiktok:user] mich.bunny: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 3 of 5)
[tiktok:user] mich.bunny: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 4 of 5)
[tiktok:user] mich.bunny: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying (1/3)...
[tiktok:user] mich.bunny: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 1 of 5)
[tiktok:user] mich.bunny: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 2 of 5)
[tiktok:user] mich.bunny: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying... (attempt 3 of 5)
[tiktok:user] mich.bunny: Downloading user video list page 1
ERROR: [tiktok:user] mich.bunny: Unable to download user video list: <urlopen error [WinError 10054] 远程主机强迫关闭了 一个现有的连接。> (caused by URLError(ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
```

**Comment by pukkandan** [comment] 2022-10-02 12:43
Don't spam!

Duplicate of a pinned issue

**Closed by pukkandan** 2022-10-02 12:43 UTC
Labels: question, site:tiktok
