### ISSUE TITLE
ZEE5: TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'

### ISSUE THREAD

**Issue by blahiri** [yt-dlp/yt-dlp#3226] opened 2022-03-28 04:46 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Hi, I am unable to download videos from ZEE5 using the latest version of yt-dlp. The full error traceback is given in the 'verbose log' section. Some links that I tried downloading with,

[https://www.zee5.com/tv-shows/details/didi-no-1-season-8/0-6-1230/didi-no-1-season-8-august-16-2020/0-1-manual_6jhqmlqqgem0](https://www.zee5.com/tv-shows/details/didi-no-1-season-8/0-6-1230/didi-no-1-season-8-august-16-2020/0-1-manual_6jhqmlqqgem0)

[https://www.zee5.com/tv-shows/details/didi-no1-season-9/0-6-4z587360/four-actresses-arrive-with-their-mothers/0-1-6z5115899](https://www.zee5.com/tv-shows/details/didi-no1-season-9/0-6-4z587360/four-actresses-arrive-with-their-mothers/0-1-6z5115899)

This is the summary of the error that I am getting,

<pre>
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'

[11984] Failed to execute script '__main__' due to unhandled exception!
</pre>

I was able to download all ZEE5 links normally with the previous yt-dlp versions (namely, 2022.02.04).

Just wanted to mention that I have tried to download the mentioned links with the latest version of `yt-dlp_x86.exe` as well, just to ensure that the error was not binary/build related.

### Verbose log

```shell
g:\bin>yt-dlp -vU https://www.zee5.com/tv-shows/details/didi-no1-season-9/0-6-4z
587360/four-actresses-arrive-with-their-mothers/0-1-6z5115899
[debug] Command-line config: ['-vU', 'https://www.zee5.com/tv-shows/details/didi
-no1-season-9/0-6-4z587360/four-actresses-arrive-with-their-mothers/0-1-6z511589
9']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No A
NSI), pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.
1-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] Using fake IP 117.240.185.15 (IN) as X-Forwarded-For
[debug] [Zee5] Extracting URL: https://www.zee5.com/tv-shows/details/didi-no1-se
ason-9/0-6-4z587360/four-actresses-arrive-with-their-mothers/0-1-6z5115899
[Zee5] 0-1-6z5115899: Downloading access token
[Zee5] 0-1-6z5115899: Downloading JSON metadata
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 735, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3591, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\zee5.py", line 136, in _real_extract
  File "yt_dlp\extractor\common.py", line 997, in _download_json
  File "yt_dlp\extractor\common.py", line 976, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 768, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 753, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 400: B
ad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue
on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue templ
ate properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [Zee5] 0-1-6z5115899: Unable to download JSON metad
ata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); ple
ase report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Br
oken site" issue template properly. Confirm you are on the latest version using
 yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 864, in main
  File "yt_dlp\__init__.py", line 854, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3254, in download
  File "yt_dlp\YoutubeDL.py", line 3227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1380, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1407, in wrapper
  File "yt_dlp\utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' a
nd 'tb'
[11984] Failed to execute script '__main__' due to unhandled exception!

g:\bin>
```

**Comment by Lesmiscore** [comment] 2022-03-28 06:23
Duplicate of #3105

**Closed by Lesmiscore** 2022-03-28 06:23 UTC
Labels: site-bug, triage
