### ISSUE TITLE
New problem downloading PBS NOVA episode - no valid audio track.

### ISSUE THREAD

**Issue by PacoH** [yt-dlp/yt-dlp#2335] opened 2022-01-14 01:42 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

https://www.pbs.org/show/nova/episodes/season/48/

Problem episode has valid `video only` tracks but no valid `audio only` tracks, yet plays in browser with audio.

	u=https://www.pbs.org/video/the-cannabis-question-82boad

	yt-dlp -Uv -F "$u"

	Latest version: 2021.12.27, Current version: 2021.12.27
	yt-dlp is up to date (2021.12.27)
	[pbs] Downloading JSON metadata
	[pbs] the-cannabis-question-82boad: Downloading webpage
	[pbs] the-cannabis-question-82boad: Downloading widget/partnerplayer page
	[pbs] the-cannabis-question-82boad: Downloading portalplayer page
	[pbs] the-cannabis-question-82boad: Downloading 0 video url info
	[pbs] the-cannabis-question-82boad: Downloading m3u8 information
	[pbs] the-cannabis-question-82boad: Downloading 1 video url info
	[info] Available formats for 3059938214:
	ID                                   EXT RESOLUTION |   FILESIZE   TBR PROTO  | VCODEC        VBR ACODEC     MORE INFO
	----------------------------------------------------|-------------------------|----------------------------------------------
	hls-multiple_audio_tracks-English    mp4            |                  m3u8_n | audio only        unknown    [eng] English
	hls-multiple_audio_tracks-English_AD mp4            |                  m3u8_n | audio only        unknown    [eng] English AD
	2                                    mp4 unknown    |                  https  | unknown           unknown
	hls-334                              mp4 416x234    | ~131.21MiB  334k m3u8_n | avc1.4d400c  334k video only
	hls-565                              mp4 480x270    | ~221.89MiB  565k m3u8_n | avc1.4d4015  565k video only
	hls-958                              mp4 640x360    | ~375.81MiB  958k m3u8_n | avc1.64001e  958k video only
	hls-1340                             mp4 768x432    | ~525.70MiB 1340k m3u8_n | avc1.64001e 1340k video only
	hls-2268                             mp4 960x540    | ~889.51MiB 2268k m3u8_n | avc1.64001f 2268k video only
	hls-3301                             mp4 1280x720   | ~  1.26GiB 3301k m3u8_n | avc1.64001f 3301k video only
	hls-4849                             mp4 1280x720   | ~  1.86GiB 4849k m3u8_n | avc1.64001f 4849k video only
	hls-6915                             mp4 1920x1080  | ~  2.65GiB 6915k m3u8_n | avc1.640028 6915k video only

	yt-dlp -Uv --concurrent-fragments 20 -o "%(title)s %(resolution)s %(format_id)s %(vcodec)s %(acodec)s.%(ext)s" "$u"

	[debug] Command-line config: ['-Uv', '--concurrent-fragments', '20', '-o', '%(title)s %(resolution)s %(format_id)s %(vcodec)s %(acodec)s.%(ext)s', 'https://www.pbs.org/video/the-cannabis-question-82boad']
	[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
	[debug] yt-dlp version 2021.12.27 [6223f67a8]
	[debug] Python version 3.7.6 (CPython 64bit) - Darwin-12.6.0-x86_64-i386-64bit
	[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, phantomjs 2.1.1, rtmpdump 2.4
	[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
	[debug] Proxy map: {}
	Latest version: 2021.12.27, Current version: 2021.12.27
	yt-dlp is up to date (2021.12.27)
	[debug] Using fake IP 6.82.105.91 (US) as X-Forwarded-For
	[pbs] Downloading JSON metadata
	[debug] [pbs] Extracting URL: https://www.pbs.org/video/the-cannabis-question-82boad
	[pbs] the-cannabis-question-82boad: Downloading webpage
	[pbs] the-cannabis-question-82boad: Downloading widget/partnerplayer page
	[pbs] the-cannabis-question-82boad: Downloading portalplayer page
	[pbs] the-cannabis-question-82boad: Downloading 0 video url info
	[pbs] the-cannabis-question-82boad: Downloading m3u8 information
	[pbs] the-cannabis-question-82boad: Downloading 1 video url info
	[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
	[debug] Default format spec: bestvideo*+bestaudio/best
	[info] 3059938214: Downloading 1 format(s): hls-6915+hls-multiple_audio_tracks-English_AD
	[debug] Invoking downloader on "https://ga.video.cdn.pbs.org/videos/nova/bd96a72e-cb0d-4e9b-b4b7-35fb9efe8191/2000257824/hd-16x9-mezzanine-1080p/nova4811_r2-hls-16x9-1080p-1080p-6500k.m3u8"
	[hlsnative] Downloading m3u8 manifest
	[hlsnative] Total fragments: 535
	[download] Destination: NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-6915.mp4
	WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
	[download] 100% of 2.52GiB in 03:11
	[debug] Invoking downloader on "https://ga.video.cdn.pbs.org/videos/nova/bd96a72e-cb0d-4e9b-b4b7-35fb9efe8191/2000257824/hd-16x9-mezzanine-1080p/nova4811_r2-hls-16x9-1080pAudio%20Selector%202.m3u8"
	[hlsnative] Downloading m3u8 manifest
	[hlsnative] Total fragments: 535
	[download] Destination: NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-multiple_audio_tracks-English_AD.mp4
	WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
	[download] 100% of 30.71MiB in 00:06
	[debug] ffmpeg command line: ffprobe -show_streams 'file:NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-multiple_audio_tracks-English_AD.mp4'
	[Merger] Merging formats into "NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.mp4"
	[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-6915.mp4' -i 'file:NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-multiple_audio_tracks-English_AD.mp4' -c copy -map 0:v:0 -map 1:a:0 -bsf:a:0 aac_adtstoasc -movflags +faststart 'file:NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.temp.mp4'
	Deleting original file NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-multiple_audio_tracks-English_AD.mp4 (pass -k to keep)
	Deleting original file NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-6915.mp4 (pass -k to keep)

`mediainfo` shows `Audio Duration : 6s 59ms`.

============================================================================================================================================

Random episodes:

Video has `video + audio` tracks only so audio downloads without problem.

	u=https://www.pbs.org/video/high-risk-high-rise-w74hk4/

	Latest version: 2021.12.27, Current version: 2021.12.27
	yt-dlp is up to date (2021.12.27)
	[pbs] Downloading JSON metadata
	[pbs] high-risk-high-rise-w74hk4: Downloading webpage
	[pbs] high-risk-high-rise-w74hk4: Downloading widget/partnerplayer page
	[pbs] high-risk-high-rise-w74hk4: Downloading portalplayer page
	[pbs] high-risk-high-rise-w74hk4: Downloading 0 video url info
	[pbs] high-risk-high-rise-w74hk4: Downloading m3u8 information
	[pbs] high-risk-high-rise-w74hk4: Downloading 1 video url info
	[info] Available formats for 3063038394:
	ID       EXT RESOLUTION FPS |   FILESIZE   TBR PROTO  | VCODEC        VBR ACODEC    ABR
	----------------------------|-------------------------|--------------------------------
	0        mp4 unknown        |                  https  | unknown           unknown
	hls-204  mp4 416x234      9 | ~ 80.09MiB  204k m3u8_n | avc1.4d400c  204k mp4a.40.5  0k
	hls-492  mp4 480x270     14 | ~193.21MiB  492k m3u8_n | avc1.4d4015  492k mp4a.40.5  0k
	hls-885  mp4 640x360     29 | ~347.29MiB  885k m3u8_n | avc1.64001e  885k mp4a.40.5  0k
	hls-1267 mp4 768x432     29 | ~497.01MiB 1267k m3u8_n | avc1.64001e 1267k mp4a.40.5  0k
	hls-2195 mp4 960x540     29 | ~860.85MiB 2195k m3u8_n | avc1.64001f 2195k mp4a.40.5  0k
	hls-3227 mp4 1280x720    29 | ~  1.24GiB 3227k m3u8_n | avc1.64001f 3227k mp4a.40.5  0k
	hls-4845 mp4 1280x720    29 | ~  1.86GiB 4845k m3u8_n | avc1.64001f 4845k mp4a.40.2  0k
	hls-6914 mp4 1920x1080   29 | ~  2.65GiB 6914k m3u8_n | avc1.640028 6914k mp4a.40.2  0k

	yt-dlp -Uv --concurrent-fragments 20 -o "%(title)s %(resolution)s %(format_id)s %(vcodec)s %(acodec)s.%(ext)s" "$u"

	[debug] Command-line config: ['-Uv', '--concurrent-fragments', '20', '-o', '%(title)s %(resolution)s %(format_id)s %(vcodec)s %(acodec)s.%(ext)s', 'https://www.pbs.org/video/high-risk-high-rise-w74hk4/']
	[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
	[debug] yt-dlp version 2021.12.27 [6223f67a8]
	[debug] Python version 3.7.6 (CPython 64bit) - Darwin-12.6.0-x86_64-i386-64bit
	[debug] exe versions: ffmpeg 3.4.1, ffprobe 3.4.1, phantomjs 2.1.1, rtmpdump 2.4
	[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
	[debug] Proxy map: {}
	Latest version: 2021.12.27, Current version: 2021.12.27
	yt-dlp is up to date (2021.12.27)
	[debug] Using fake IP 6.119.217.11 (US) as X-Forwarded-For
	[pbs] Downloading JSON metadata
	[debug] [pbs] Extracting URL: https://www.pbs.org/video/high-risk-high-rise-w74hk4/
	[pbs] high-risk-high-rise-w74hk4: Downloading webpage
	[pbs] high-risk-high-rise-w74hk4: Downloading widget/partnerplayer page
	[pbs] high-risk-high-rise-w74hk4: Downloading portalplayer page
	[pbs] high-risk-high-rise-w74hk4: Downloading 0 video url info
	[pbs] high-risk-high-rise-w74hk4: Downloading m3u8 information
	[pbs] high-risk-high-rise-w74hk4: Downloading 1 video url info
	[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
	[debug] Default format spec: bestvideo*+bestaudio/best
	[info] 3063038394: Downloading 1 format(s): hls-6914
	[debug] Invoking downloader on "https://ga.video.cdn.pbs.org/videos/nova/b7b2f5e7-71cc-45c7-9534-e1abeba75e08/2000273858/hd-16x9-mezzanine-1080p/nova4808r2fix-hls-16x9-1080p-1080p-6500k.m3u8"
	[hlsnative] Downloading m3u8 manifest
	[hlsnative] Total fragments: 535
	[download] Destination: NOVA - High-Risk High-Rise 1920x1080 hls-6914 avc1.640028 mp4a.40.2.mp4
	WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
	[download] 100% of 2.59GiB in 02:32
	[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:NOVA - High-Risk High-Rise 1920x1080 hls-6914 avc1.640028 mp4a.40.2.mp4'
	[FixupM3u8] Fixing MPEG-TS in MP4 container of "NOVA - High-Risk High-Rise 1920x1080 hls-6914 avc1.640028 mp4a.40.2.mp4"
	[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:NOVA - High-Risk High-Rise 1920x1080 hls-6914 avc1.640028 mp4a.40.2.mp4' -c copy -map 0 -dn -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:NOVA - High-Risk High-Rise 1920x1080 hls-6914 avc1.640028 mp4a.40.2.temp.mp4'

`mediainfo` shows `Audio Duration : 53mn 32s`.

Other episodes have the same problem as the *Problem episode* above.

============================================================================================================================================

https://www.pbs.org/show/nova/episodes/season/47/

Random episodes are all `audio + video only`. Did not attempt to download but have never had a problem with seasons before season 48.

### Verbose log

```shell
Included in description
```

**Comment by TheGrimKeeper** [comment] 2022-01-14 19:06
I fail to see what's wrong here.  The "problem" episode has two valid audio tracks, and they are separate because there are two.  One includes the audio descriptions for visually impaired viewers, and one does not.  Your download grabbed the AD track, but if that's not what you want just use -f to specify the other track.

I've seen this behavior numerous times on various websites that offer AD tracks.  Just pay attention to what you're downloading and you'll be fine.

And, I downloaded the AD track for the "problem" episode and it is 56 minutes long, so something is up with your mediainfo.

**Comment by pukkandan** [comment] 2022-01-15 14:00
Everything looks good in your logs too. What exactly is the problem?

**Comment by PacoH** [comment] 2022-01-15 18:28
`yt-dlp --concurrent-fragments 20 -o "%(title)s %(resolution)s %(format_id)s %(vcodec)s %(acodec)s.%(ext)s" "$u"` downloads the AD track by default for whatever reason. I had also specified `-f hls-6915+hls-multiple_audio_tracks-English_AD` and `hls-6915+hls-multiple_audio_tracks-English` and got the same result each time.

NB: `mediainfo` correctly identifies the duration as verified by playing the file with `mpv`.

--------------------------------------------------------------------------------------------------------------------------------------------

`yt-dlp --concurrent-fragments 20 -f hls-6915+hls-multiple_audio_tracks-English_AD -k -o "%(title)s %(resolution)s %(format_id)s %(vcodec)s %(acodec)s.%(ext)s" "$u"`

Audio + Video:

`NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.mp4`

`mediainfo`:
Video Duration: 53mn 32s
Audio Duration: 6s 59ms
`ffprobe`:
Duration (both): 00:53:32.41

Audio only:

`NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-multiple_audio_tracks-English_AD.mp4`

`mediainfo`:
No duration reported
`ffprobe`:
Duration: 00:56:41.28

File plays correctly in `mpv`.

--------------------------------------------------------------------------------------------------------------------------------------------

`yt-dlp --concurrent-fragments 20 -f hls-6915+hls-multiple_audio_tracks-English -k -o "%(title)s %(resolution)s %(format_id)s %(vcodec)s %(acodec)s.%(ext)s" "$u"`
I also downloaded just the audio tracks and each of them was complete. However, when I specified both tracks as above,

Audio + Video:

`NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English avc1.640028 NA.mp4`

`mediainfo`:
Video Duration: 53mn 32s
Audio Duration: 6s 59ms
`ffprobe`:
Duration (both): 00:53:32.41

Audio only:

`NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English avc1.640028 NA.fhls-multiple_audio_tracks-English.mp4`

`mediainfo`:
No duration reported
`ffprobe`:
Duration: 00:53:33.99

File plays correctly in `mpv`.

--------------------------------------------------------------------------------------------------------------------------------------------

Interestingly enough, the audio only files play just fine with `mpv`, unlike the audio+video files. The only conclusion I can reach is that `ffmpeg` is not merging the entire audio file. Did you try downloading the audio+video file?

	Merging formats into "NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.mp4"
	ffmpeg command line: \
	ffmpeg -y -loglevel repeat+info \
	-i 'file:NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-6915.mp4' \
	-i 'file:NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-multiple_audio_tracks-English_AD.mp4' \
	-c copy -map 0:v:0 -map 1:a:0 -bsf:a:0 aac_adtstoasc -movflags +faststart \
	'file:NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.temp.mp4'

**Comment by pukkandan** [comment] 2022-01-15 19:44
No. Since I have to download over a VPN, getting the full episode is gonna take a while. Can you check if the issue exists with the smaller video formats as well? So that I can just download them to try and reproduce

Also, I noticed that your ffmpeg version is very old

> [debug] exe versions: ffmpeg 3.4.1

You might wanna try again after updating it

**Comment by PacoH** [comment] 2022-01-15 22:39
I know. The problem is that I am on an old Mac Pro with an old OS X that cannot be updated without thousands of dollars worth of hardware, so I am stuck with this version. I tried using an updated version on a newer Mac and it did work. So the old version of `ffmpeg` is the culprit.

Latest `ffmpeg`:

	yt-dlp -Uv --concurrent-fragments 20 -o "%(title)s %(resolution)s %(format_id)s %(vcodec)s %(acodec)s.%(ext)s" "$u"
	[debug] Command-line config: ['-Uv', '--concurrent-fragments', '20', '-o', '%(title)s %(resolution)s %(format_id)s %(vcodec)s %(acodec)s.%(ext)s', 'https://www.pbs.org/video/the-cannabis-question-82boad']
	[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
	[debug] yt-dlp version 2021.12.27 [6223f67a8]
	[debug] Python version 3.8.12 (CPython 64bit) - macOS-12.0.1-x86_64-i386-64bit
	[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
	[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
	[debug] Proxy map: {}
	Latest version: 2021.12.27, Current version: 2021.12.27
	yt-dlp is up to date (2021.12.27)
	[debug] Using fake IP 6.51.248.103 (US) as X-Forwarded-For
	[pbs] Downloading JSON metadata
	[debug] [pbs] Extracting URL: https://www.pbs.org/video/the-cannabis-question-82boad
	[pbs] the-cannabis-question-82boad: Downloading webpage
	[pbs] the-cannabis-question-82boad: Downloading widget/partnerplayer page
	[pbs] the-cannabis-question-82boad: Downloading portalplayer page
	[pbs] the-cannabis-question-82boad: Downloading 0 video url info
	[pbs] the-cannabis-question-82boad: Downloading m3u8 information
	[pbs] the-cannabis-question-82boad: Downloading 1 video url info
	[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
	[debug] Default format spec: bestvideo*+bestaudio/best
	[info] 3059938214: Downloading 1 format(s): hls-6915+hls-multiple_audio_tracks-English_AD
	[debug] Invoking downloader on "https://ga.video.cdn.pbs.org/videos/nova/bd96a72e-cb0d-4e9b-b4b7-35fb9efe8191/2000257824/hd-16x9-mezzanine-1080p/nova4811_r2-hls-16x9-1080p-1080p-6500k.m3u8"
	[hlsnative] Downloading m3u8 manifest
	[hlsnative] Total fragments: 535
	[download] Destination: NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-6915.mp4
	WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
	[download] 100% of 2.52GiB in 02:17
	[debug] Invoking downloader on "https://ga.video.cdn.pbs.org/videos/nova/bd96a72e-cb0d-4e9b-b4b7-35fb9efe8191/2000257824/hd-16x9-mezzanine-1080p/nova4811_r2-hls-16x9-1080pAudio%20Selector%202.m3u8"
	[hlsnative] Downloading m3u8 manifest
	[hlsnative] Total fragments: 535
	[download] Destination: NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-multiple_audio_tracks-English_AD.mp4
	WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
	[download] 100% of 30.71MiB in 00:07
	[debug] ffmpeg command line: ffprobe -show_streams 'file:NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-multiple_audio_tracks-English_AD.mp4'
	[Merger] Merging formats into "NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.mp4"
	[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-6915.mp4' -i 'file:NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-multiple_audio_tracks-English_AD.mp4' -c copy -map 0:v:0 -map 1:a:0 -bsf:a:0 aac_adtstoasc -movflags +faststart 'file:NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.temp.mp4'
	Deleting original file NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-6915.mp4 (pass -k to keep)
	Deleting original file NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.fhls-multiple_audio_tracks-English_AD.mp4 (pass -k to keep)

`NOVA - The Cannabis Question 1920x1080 hls-6915+hls-multiple_audio_tracks-English_AD avc1.640028 NA.mp4`

`mediainfo`:
Video Duration: 53mn 32s
Audio Duration: 53mn 32s
`ffprobe`:
Duration (both): 00:53:32.42

I tried downloading `hls-334+hls-multiple_audio_tracks-English_AD` on my old machine and got the same 6s 59ms audio track.

I wonder if I can just add --postprocessor-args for FFmpeg to do a custom merge that would solve the duration problem.

**Comment by pukkandan** [comment] 2022-01-16 04:00
If it is an ffmpeg issue, especially one that has been fixed in latest versions, nothing we can do.

> I wonder if I can just add --postprocessor-args for FFmpeg to do a custom merge that would solve the duration problem.

It is possible, but you will need to try and find the issue and any possible option to fix it

**Closed by pukkandan** 2022-01-16 04:00 UTC
Labels: site-bug
