### ISSUE TITLE
[YouTube] Comments are no longer downloaded

### ISSUE THREAD

**Issue by kiri35** [yt-dlp/yt-dlp#9664] opened 2024-04-10 19:21 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

~~~
yt-dlp --no-download --no-write-info-json --extractor-args "youtube:comment_sort=new" --write-comments https://www.youtube.com/watch?v=PA5_T1QDDuw
~~~
doesn't work anymore.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
~~~
$ yt-dlp -vU --no-download --no-write-info-json --extractor-args "youtube:comment_sort=new" --write-comments https://www.youtube.com/watch?v=PA5_T1QDDuw
[debug] Command-line config: ['-vU', '--no-download', '--no-write-info-json', '--extractor-args', 'youtube:comment_sort=new', '--write-comments', 'https://www.youtube.com/watch?v=PA5_T1QDDuw']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-6.6.16-2-MANJARO-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2023.05.07, pycrypto-3.20.0, requests-2.31.0, sqlite3-3.45.1, urllib3-2.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=PA5_T1QDDuw
[youtube] PA5_T1QDDuw: Downloading webpage
[youtube] PA5_T1QDDuw: Downloading ios player API JSON
[youtube] PA5_T1QDDuw: Downloading android player API JSON
[youtube] PA5_T1QDDuw: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[youtube] Downloading comment section API JSON
[youtube] Downloading ~224 comments
[youtube] Sorting comments by newest first
[youtube] Downloading comment API JSON page 1 (0/~224)
[youtube] Downloading comment API JSON page 2 (0/~224)
[youtube] Downloading comment API JSON page 3 (0/~224)
[youtube] Downloading comment API JSON page 4 (0/~224)
[youtube] Downloading comment API JSON page 5 (0/~224)
[youtube] Downloading comment API JSON page 6 (0/~224)
[youtube] Downloading comment API JSON page 7 (0/~224)
[youtube] Downloading comment API JSON page 8 (0/~224)
[youtube] Downloading comment API JSON page 9 (0/~224)
[youtube] Downloading comment API JSON page 10 (0/~224)
[youtube] Extracted 0 comments
[debug] Default format spec: bestvideo*+bestaudio/best
[info] PA5_T1QDDuw: Downloading 1 format(s): 247+251
~~~

Another Example:
~~~
$ yt-dlp -vU --no-download --no-write-info-json --extractor-args "youtube:comment_sort=new" --write-comments https://www.youtube.com/watch?v=icWHucreShA
[debug] Command-line config: ['-vU', '--no-download', '--no-write-info-json', '--extractor-args', 'youtube:comment_sort=new', '--write-comments', 'https://www.youtube.com/watch?v=icWHucreShA']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.11.7 (CPython x86_64 64bit) - Linux-6.6.16-2-MANJARO-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2023.05.07, pycrypto-3.20.0, requests-2.31.0, sqlite3-3.45.1, urllib3-2.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=icWHucreShA
[youtube] icWHucreShA: Downloading webpage
[youtube] icWHucreShA: Downloading ios player API JSON
[youtube] icWHucreShA: Downloading android player API JSON
[youtube] icWHucreShA: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[youtube] Downloading comment section API JSON
[youtube] Downloading ~35 comments
[youtube] Sorting comments by newest first
[youtube] Downloading comment API JSON page 1 (0/~35)
[youtube] Downloading comment API JSON page 2 (0/~35)
[youtube] Extracted 0 comments
[debug] Default format spec: bestvideo*+bestaudio/best
[info] icWHucreShA: Downloading 1 format(s): 137+251
~~~
```

**Comment by bashonly** [comment] 2024-04-10 19:21
Duplicate of #9358

**Closed by bashonly** 2024-04-10 19:21 UTC
Labels: site-bug, triage

**Comment by kiri35** [comment] 2024-04-10 20:36
Because no command line `yt-dlp ...` was given in [#9358](https://github.com/yt-dlp/yt-dlp/issues/9358) I did not understand that it could be the same.
Then we can close this topic.
