### ISSUE TITLE
[Facebook] Can't download stories

### ISSUE THREAD

**Issue by ivo-ns** [yt-dlp/yt-dlp#8462] opened 2023-10-28 17:12 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Bulgaria

### Provide a description that is worded well enough to be understood

Hello,

I'm trying to download this story https://www.facebook.com/stories/2910336895647666 but it's not working.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.facebook.com/stories/2910336895647666']
[debug] User config "C:\Users\ivo\AppData\Roaming\yt-dlp\config.txt": ['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '-i', '-o', 'D:/Courses/%(title)s.%(ext)s', '--no-mtime']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.10.28.155411 [4a601c9ef] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2021-02-02-git-2367affc2c-full_build-www.gyan.dev, ffprobe 2021-02-02-git-2367affc2c-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.0.7, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.10.28.155411, Current version: nightly@2023.10.28.155411
Current Build Hash: f4da8a97b3a3a2b48b5effce680444668857b57d11de65a7ee6218c8f52d3ea3
yt-dlp is up to date (nightly@2023.10.28.155411)
[generic] Extracting URL: https://www.facebook.com/stories/2910336895647666
[generic] 2910336895647666: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fstories%2F2910336895647666
[generic] Extracting URL: https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fstories%2F2910336895647666
[generic] login.php?next=https://www.facebook: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] login.php?next=https://www.facebook: Extracting information
[debug] Looking for embeds
[redirect] Following redirect to https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fstories%2F2910336895647666&_fb_noscript=1
[generic] Extracting URL: https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fstories%2F2910336895647666&_fb_noscript=1
[generic] login.php?next=https://www.facebook: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] login.php?next=https://www.facebook: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fstories%2F2910336895647666&_fb_noscript=1
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2577, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fstories%2F2910336895647666&_fb_noscript=1
```

**Comment by bashonly** [comment] 2023-10-28 20:17
Duplicate of #5763

**Closed by bashonly** 2023-10-28 20:17 UTC
Labels: duplicate, site-request, site:facebook
