### ISSUE TITLE
can't fetch youtube url

### ISSUE THREAD

**Issue by Sunda001** [yt-dlp/yt-dlp#11550] opened 2024-11-15 04:55 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

it returned error msgs when i use: yt-dlp url

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --username oauth --password '' -F https://www.youtube.com/watch?v=XFkzRNyygfk -vU
[debug] Command-line config: ['--username', 'PRIVATE', '--password', 'PRIVATE', '-F', 'https://www.youtube.com/watch?v=XFkzRNyygfk', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (pip)
[debug] Python 3.12.6 (CPython aarch64 64bit) - Linux-6.11.2-1-aarch64-ARCH-aarch64-with-glibc2.39 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.39)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Plugin directories: ['/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp_plugins']
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.04 from yt-dlp/yt-dlp)
[debug] Loading youtube.oauth_refresh_token_default from cache
[youtube] oauth: Refreshing access token
[debug] [youtube] oauth: Logged in using profile "default"
[youtube] Extracting URL: https://www.youtube.com/watch?v=XFkzRNyygfk
[youtube] XFkzRNyygfk: Downloading webpage
[youtube] XFkzRNyygfk: Downloading ios player API JSON
[youtube] XFkzRNyygfk: Downloading mweb player API JSON
[debug] [youtube] Extracting signature function js_0ccfa671_101
[debug] Loading youtube-sigfuncs.js_0ccfa671_101 from cache
[debug] Loading youtube-nsig.0ccfa671 from cache
[debug] [youtube] Decrypted nsig Yr2VXeOkN38uNNS => cImxN2GWvbmNcA
[debug] [youtube] Extracting signature function js_0ccfa671_105
[debug] Loading youtube-sigfuncs.js_0ccfa671_105 from cache
[debug] Loading youtube-nsig.0ccfa671 from cache
[debug] [youtube] Decrypted nsig l8RFihFto07Xh01 => ImJ80tfy8sxolA
[youtube] XFkzRNyygfk: Downloading m3u8 information
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] XFkzRNyygfk: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] XFkzRNyygfk: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] XFkzRNyygfk: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] XFkzRNyygfk: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
ERROR: [youtube] XFkzRNyygfk: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 4902, in _real_extract
    initial_data = self._extract_response(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 1270, in _extract_response
    next(main_retries)
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/utils/_utils.py", line 5271, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 3895, in _error_or_warning
    RetryManager.report_retry(
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/utils/_utils.py", line 5279, in report_retry
    raise e
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 1243, in _extract_response
    response = self._call_api(
               ^^^^^^^^^^^^^^^
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 861, in _call_api
    return self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1152, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1112, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 962, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 911, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 898, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 4162, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/sakty/automate-siakad-stkip-syekhManshur/siakad/lib/python3.12/site-packages/yt_dlp/networking/_requests.py", line 365, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request
```

**Comment by seproDev** [comment] 2024-11-15 04:57
Duplicate of #11462

YouTube broke OAuth, use cookies instead. OAuth will likely be removed soon.

**Closed by seproDev** 2024-11-15 04:57 UTC
Labels: bug, triage

**Comment by seproDev** [comment] 2024-11-15 05:49
Then likely your cookies are not valid/not signed in

**Comment by Sunda001** [comment] 2024-11-15 05:51
> I'm using cookies but it's says "Sign in to confirm you are not a bot".
> 
> How can solve this issues?!

for me cookies works

**Comment by Sunda001** [comment] 2024-11-15 05:52
> Then likely your cookies are not valid/not signed in

when i try to download this https://youtu.be/jvnfCfWnybY?si=qmWh4qT9pKpVt_J- and trying to get 'requested_formats' but why it doesn't exist?

**Comment by seproDev** [comment] 2024-11-15 05:56
You will have to show a verbose log

**Comment by Sunda001** [comment] 2024-11-15 06:08
> You will have to show a verbose log

![IMG_20241115_130716_850.jpg](https://github.com/user-attachments/assets/bbae9dad-014b-48ed-977a-a0a66ec94ed0)

nvm, it works fine, it was my syntax fault, i was about to get the filesize

**Comment by Sunda001** [comment] 2024-11-15 06:09
> You will have to show a verbose log

you know how to limit filesize? i use config max_filesize, but it seems like ignored

**Comment by bashonly** [comment] 2024-11-15 15:01
@Sunda001 unrelated. open a new question issue if you can't figure it out

@iCodexDev that's not a software problem, and unrelated to this issue
