### ISSUE TITLE
[Question] CBS - No video formats found, only impacts some videos.

### ISSUE THREAD

**Issue by BeeMuffins** [yt-dlp/yt-dlp#240] opened 2021-04-13 17:28 UTC
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, I figured I would ask this as a question and rather than a 'Broken site support' as I am not sure if the site is really broken or if something else is going on. I am using the latest 2021.04.11 release of yt-dlp.

As an example I'm looking at two videos from the cbs.com website one video is working and one video is providing an error that "No video formats found".  Both videos work fine in the browser and do not require an account.  Looking at the .mpd files (attached below) I can't seem to identify something that is drastically different between the two files as I'm trying to understand why one works and one does not.

What seems to be happening is that when a video is first posted to cbs.com (regardless of show) yt-dlp gives the error "No video formats found", but then after a week or two, the video seems to be able to be downloaded with yt-dlp without issue. I am not sure if CBS changes something on their end after a period of time.

If this is DRM related totally understand and I'm not looking for how to bypass, it just seemed odd to me that DRM would only be applied for a short period of time and then removed.  What I would like to understand is if it is DRM related, how does one identify that DRM is actually the issue?

Below are the verbose logs:
**Working**
```sh
yt-dlp -v -s "https://www.cbs.com/shows/the-neighborhood/video/xqDR2B_ysdrUkqnTDu7pUktg9U_yBlN1/the-neighborhood-welcome-to-the-treehouse/"
[debug] Command-line config: ['-v', '-s', 'https://www.cbs.com/shows/the-neighborhood/video/xqDR2B_ysdrUkqnTDu7pUktg9U_yBlN1/the-neighborhood-welcome-to-the-treehouse/']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.04.11
[debug] Python version 3.9.4 (CPython 64bit) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2
[debug] Proxy map: {}
[CBS] xqDR2B_ysdrUkqnTDu7pUktg9U_yBlN1: Downloading XML
[CBS] xqDR2B_ysdrUkqnTDu7pUktg9U_yBlN1: Downloading StreamPack SMIL data
[CBS] xqDR2B_ysdrUkqnTDu7pUktg9U_yBlN1: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[CBS] xqDR2B_ysdrUkqnTDu7pUktg9U_yBlN1: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Downloading format(s) hls-4550
```
**Not Working**
```sh
yt-dlp -v -s "https://www.cbs.com/shows/the-neighborhood/video/CIjLEg0RBLnXWQy_Dt_nuJR3sjqnrSWq/the-neighborhood-welcome-to-the-art-class/"
[debug] Command-line config: ['-v', '-s', 'https://www.cbs.com/shows/the-neighborhood/video/CIjLEg0RBLnXWQy_Dt_nuJR3sjqnrSWq/the-neighborhood-welcome-to-the-art-class/']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.04.11
[debug] Python version 3.9.4 (CPython 64bit) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2
[debug] Proxy map: {}
[CBS] CIjLEg0RBLnXWQy_Dt_nuJR3sjqnrSWq: Downloading XML
ERROR: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1037, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1058, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/cbs.py", line 115, in _real_extract
    return self._extract_video_info(content_id)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/cbs.py", line 97, in _extract_video_info
    self._sort_formats(formats)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1673, in _sort_formats
    raise ExtractorError('No video formats found')
yt_dlp.utils.ExtractorError: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

Here are the MDP files:
**Working**
[Working MPD.txt](https://github.com/yt-dlp/yt-dlp/files/6305540/Working.MPD.txt)
**Not Working**
[Not Working MPD.txt](https://github.com/yt-dlp/yt-dlp/files/6305541/Not.Working.MPD.txt)

There are similar issues that have been bought up on the youtube-dl, but many have been closed or tagged DRM, but I'm not sure that's really it. Examples noted below for reference. Again I am not looking to bypass DRM, just better understand what is going on and try to learn more about how yt-dlp is working.

References: https://github.com/ytdl-org/youtube-dl/issues/27028 and https://github.com/ytdl-org/youtube-dl/issues/26993 and https://github.com/ytdl-org/youtube-dl/issues/28662

Thank you.

**Comment by pukkandan** [comment] 2021-04-13 17:33
Its geo-blocked for me. I wil test manually with the given mpd when I have time.

> What I would like to understand is if it is DRM related, how does one identify that DRM is actually the issue?

Try: `yt-dlp --allow-unplayable-formats -F URL`. If it shows you the formats, the issue is DRM

**Comment by BeeMuffins** [comment] 2021-04-13 17:40
> Its geo-blocked for me. I wil test manually with the given mpd when I have time.
> 
> > What I would like to understand is if it is DRM related, how does one identify that DRM is actually the issue?
> 
> Try: `yt-dlp --allow-unplayable-formats -F URL`. If it shows you the formats, the issue is DRM

Thanks for the suggestion and offering to look into this.  Below is the verbose log I get for the non-working file when using  the options you mentioned.

```sh
yt-dlp -v --allow-unplayable-formats -F "https://www.cbs.com/shows/the-neighborhood/video/CIjLEg0RBLnXWQy_Dt_nuJR3sjqnrSWq/the-neighborhood-welcome-to-the-art-class/"
[debug] Command-line config: ['-v', '--allow-unplayable-formats', '-F', 'https://www.cbs.com/shows/the-neighborhood/video/CIjLEg0RBLnXWQy_Dt_nuJR3sjqnrSWq/the-neighborhood-welcome-to-the-art-class/']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.04.11
[debug] Python version 3.9.4 (CPython 64bit) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2
[debug] Proxy map: {}
[CBS] CIjLEg0RBLnXWQy_Dt_nuJR3sjqnrSWq: Downloading XML
ERROR: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1037, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1058, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/cbs.py", line 115, in _real_extract
    return self._extract_video_info(content_id)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/cbs.py", line 97, in _extract_video_info
    self._sort_formats(formats)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1673, in _sort_formats
    raise ExtractorError('No video formats found')
yt_dlp.utils.ExtractorError: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by pukkandan** [comment] 2021-04-14 02:39
BOTH mpds you provided have DRM. See the part that says `xmlns:mspr="urn:microsoft:playready"`. This indicates that it has playready protection. However, youtube-dl **does not** download these MPDs for the links that you provided. The first URL downloads from an m3u8 manifest, not from an mpd, and youtube-dl can't find an m3u8 for the second link

**Comment by BeeMuffins** [comment] 2021-04-14 17:56
Thank you for looking into and explaining the mpd portion to me, I see what you mean regarding those tags.

Related to how youtube-dl works, I'm struggling to understand how it identifies and gets the link for the m3u8 manifest for the working link, as when I'm looking through the browser console/dev tool view, I was only able to find the mpd steam link. Taking a look thru the cbs.py extractor code (starting at line 60) I was trying to trace how I think it gets the m3u8.

```sh
    def _extract_video_info(self, content_id, site='cbs', mpx_acc=2198311517):
        items_data = self._download_xml(
            'https://can.cbs.com/thunder/player/videoPlayerService.php',
            content_id, query={'partner': site, 'contentId': content_id})
        video_data = xpath_element(items_data, './/item')
        title = xpath_text(video_data, 'videoTitle', 'title') or xpath_text(video_data, 'videotitle', 'title')
        tp_path = 'dJ5BDC/media/guid/%d/%s' % (mpx_acc, content_id)
        tp_release_url = 'https://link.theplatform.com/s/' + tp_path
```
Using that I was able to find what seems like m3u8 links for both the working and not working links I provided.  It seems that youtube-dl is passing additional information to these, if this is what is being requested, as in browser it gives an access denied.  Not sure if this is the right path or not. Either way, it does seem that a m3u8 manifest exists for the not working link, but I'm not sure if something would need to be updated in the extractor for it to find the Not Working Video.

**Working Video**
http://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/03/11/1872163395891/CBS_THE_NEIGHBORHOOD_312_PRORES_2398_R_598478_2228000.mp4.csmil/master.m3u8

**Not Working Video**
http://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/03/26/1878036035939/CBS_THE_NEIGHBORHOOD_313_2398_623476_2228000.mp4.csmil/master.m3u8

**Comment by october262** [comment] 2021-04-14 18:50
i can get this episode to download - "https://www.cbs.com/shows/the-neighborhood/video/CIjLEg0RBLnXWQy_Dt_nuJR3sjqnrSWq/the-neighborhood-welcome-to-the-art-class/"  using firefox + the stream detector addon set to FFmpeg command.
the resulting file is a .ts file but it is DRM encrypted even when converted to mp4

**Comment by IONECarter** [comment] 2021-04-14 19:11
> i can get this episode to download - "https://www.cbs.com/shows/the-neighborhood/video/CIjLEg0RBLnXWQy_Dt_nuJR3sjqnrSWq/the-neighborhood-welcome-to-the-art-class/" using firefox + the stream detector addon set to FFmpeg command.
> the resulting file is a .ts file but it is DRM encrypted even when converted to mp4

Yes, I was able to get that link as well, but those are the mpd streams that I posted in my initial post.

**Comment by pukkandan** [comment] 2021-04-15 07:52
> Not Working Video
http://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/03/26/1878036035939/CBS_THE_NEIGHBORHOOD_313_2398_623476_2228000.mp4.csmil/master.m3u8

Can you upload this m3u8? Let me first see whether it has any DRM. If it doesn't, then we can look into why yt-dlp cannot find it

**Comment by BeeMuffins** [comment] 2021-04-15 21:40
I'm struggling through this, but trying to figure out more as I go. Thanks for the continued help.

On the working link the yt-dlp verbose logs show it going XML -> SteamPack SMIL data -> m3u8.  On the nonworking link it errors after XML. However, I was able to find what looks to be the SMIL data for both of the links at the below locations (attached as well).

**Working Link:** http://link.theplatform.com/s/dJ5BDC/media/guid/2198311517/xqDR2B_ysdrUkqnTDu7pUktg9U_yBlN1?format=SMIL&mbr=true
_File: [xqDR2B_ysdrUkqnTDu7pUktg9U_yBlN1.txt](https://github.com/yt-dlp/yt-dlp/files/6321213/xqDR2B_ysdrUkqnTDu7pUktg9U_yBlN1.txt)_


**Not Working Link:** http://link.theplatform.com/s/dJ5BDC/media/guid/2198311517/CIjLEg0RBLnXWQy_Dt_nuJR3sjqnrSWq?format=SMIL&mbr=true
_File_: [CIjLEg0RBLnXWQy_Dt_nuJR3sjqnrSWq.txt](https://github.com/yt-dlp/yt-dlp/files/6321216/CIjLEg0RBLnXWQy_Dt_nuJR3sjqnrSWq.txt)

These files show all the various m3u8 manifest URL locations however, trying to access any of them directly in browser whether for the working or not working original video links gives an access denied error (see below).  My assumption is that the API being used is passing additional information here.

```sh
Access Denied
You don't have permission to access "http://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2021/03/26/1878036035939/CBS_THE_NEIGHBORHOOD_313_2398_623476_4628000.mp4.csmil/master.m3u8" on this server.
Reference #18.4bc7cf17.1618522481.1a814c88
```

My struggle seems to be the linkage from the SMIL to being able to read the m3u8 it references as I am not familiar with the API it seems to be using.  Not sure if you have any suggestions.

**Comment by BeeMuffins** [comment] 2021-04-20 18:32
To follow back up on this one. As expected, it has been one week and the original non-working link is now working. CBS must be doing some thing on their end that is changing how yt-dlp is finding and accessing the m3u8 manifest for newly published shows. I unsure what's going on as these videos play fine in browser and do not require a login. 

Also as expected, the most recent episode that was posted https://www.cbs.com/shows/the-neighborhood/video/z6jldNkH8VlhsBzmTyEjE7AlGi1Ros3s/the-neighborhood-welcome-to-the-hero/ is providing the following error which is consistent to what I noted in my original post.
```sh
yt-dlp -v "https://www.cbs.com/shows/the-neighborhood/video/z6jldNkH8VlhsBzmTyEjE7AlGi1Ros3s/the-neighborhood-welcome-to-the-hero/"
[debug] Command-line config: ['-v', 'https://www.cbs.com/shows/the-neighborhood/video/z6jldNkH8VlhsBzmTyEjE7AlGi1Ros3s/the-neighborhood-welcome-to-the-hero/']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.04.11
[debug] Python version 3.9.4 (CPython 64bit) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[CBS] z6jldNkH8VlhsBzmTyEjE7AlGi1Ros3s: Downloading XML
ERROR: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1037, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1058, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/cbs.py", line 115, in _real_extract
    return self._extract_video_info(content_id)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/cbs.py", line 97, in _extract_video_info
    self._sort_formats(formats)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1673, in _sort_formats
    raise ExtractorError('No video formats found')
yt_dlp.utils.ExtractorError: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by RedPenguin2** [comment] 2021-04-21 07:18
Just to give a little insight, here is what I think is going on based on this conversation and what I learned about CBS with a Fire TV.

CBS seems to me implementing a system like ABC & NBC where you wait a week to see many shows with no TV Provider.

It's more like NBC where episodes are on the website immediately but not mobile. ABC locks everything.

Anyway I think what's occurring is, youtube-dlp is trying to act as a "mobile user" and get the m3u8 but it can't because it's blocked for a week.

I seen that on a PC you can get an mpd but it has PlayReady DRM. I was hoping it would be Widevine L3 as there are ways to obtain but I believe Playready is hopeless.

**Comment by pukkandan** [comment] 2021-04-26 03:10
>BOTH mpds you provided have DRM. See the part that says xmlns:mspr="urn:microsoft:playready" and the <ContentProtection/> tags. This indicates that it has playready protection. However, youtube-dl does not download these MPDs for the links that you provided. The first URL downloads from an m3u8 manifest, not from an mpd, and youtube-dl can't find an m3u8 for the second link

> CBS seems to me implementing a system like ABC & NBC where you wait a week to see many shows with no TV Provider. It's more like NBC where episodes are on the website immediately but not mobile. ABC locks everything.

It does seem like only the DRM mpds are available for the first week; then the unencrypted m3u8 becomes available

I am closing this since the original question has been answered. If you can find an m3u8 that exists from the start, then this can be reopened

**Closed by pukkandan** 2021-04-26 03:10 UTC
Labels: question
