### ISSUE TITLE
not support x.com video 

### ISSUE THREAD

**Issue by kaixuangh** [yt-dlp/yt-dlp#9998] opened 2024-05-22 11:27 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp "https://x.com/i/status/1793054150277857513"
/Users/kaixuan/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[generic] Extracting URL: https://x.com/i/status/1793054150277857513
[generic] 1793054150277857513: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1793054150277857513: Extracting information
ERROR: Unsupported URL: https://x.com/i/status/1793054150277857513

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by PoisonFrog** [comment] 2024-05-22 11:55
You can download the video if you replace "x" with "twitter" in the URL. I hope devs fix this X issue.

**Comment by kaixuangh** [comment] 2024-05-22 12:34
> You can download the video if you replace "x" with "twitter" in the URL. I hope devs fix this X issue.

it work for me

**Comment by seproDev** [comment] 2024-05-22 13:19
Duplicate of #9923

Update to nightly:

```
# To update to nightly from stable executable/binary:
yt-dlp --update-to nightly

# To install nightly with pip:
python3 -m pip install -U --pre yt-dlp[default]
```

**Closed by seproDev** 2024-05-22 13:19 UTC
Labels: question
