### ISSUE TITLE
bestaudio seems to choose the worst audio format available

### ISSUE THREAD

**Issue by studentism** [yt-dlp/yt-dlp#11564] opened 2024-11-16 23:12 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

My sincerest apologies if this was already covered, but I didn't see this in the known issue thread and was unsuccessful finding a recent similar issue in search (the latter may very well be my fault). Apologies also if I've opened this ticket in the wrong category.

Neither `-f bv*+ba/b` nor `-f bv+ba/b` grab the best audio option available from a particular site's m3u8. In the below example, yt-dlp grabs the 96kbps stream instead of the 192. I can obviously specify the exact IDs I want for each video, but am I misunderstanding something fundamental? (By the way, I do understand that with this particular format listing, there is no functional difference between the two `-f` options. Just including the output of both for completion's sake.)

Please note that I'm using "{$URL}" to redact a private URL and "{$VIDNAME}" to redact an identifying video name. The site can probably be inferred from the cookies file name.

**List formats**
```
$ ~/.local/bin/yt-dlp-master -vU -F --cookies ../masclas-cookies.txt "{$URL}.m3u8"
[debug] Command-line config: ['-vU', '-F', '--cookies', '../masclas-cookies.txt', '"{$URL}".m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.11.16.200858 from yt-dlp/yt-dlp-master-builds [1d253b0a2] (zip)
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 3.0.14 4 Jun 2024, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.0.9, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.2, sqlite3-3.45.3, urllib3-2.2.2, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1841 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.11.16.200858 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.11.16.200858 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: "{$URL}".m3u8
[generic] "{$VIDNAME}": Downloading webpage
[debug] Identified a direct video link
[generic] "{$VIDNAME}": Downloading m3u8 information
[generic] "{$VIDNAME}": Checking m3u8 live status
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for af103smokeporkbuttv12brightcovev2-63001:
ID                    EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────
audio_aac_128-English mp4 audio only     │                  m3u8  │ audio only        unknown    [eng] English
audio_aac_192-English mp4 audio only     │                  m3u8  │ audio only        unknown    [eng] English
audio_aac_96-English  mp4 audio only     │                  m3u8  │ audio only        unknown    [eng] English
1204                  mp4 640x360     24 │ ~220.19MiB 1204k m3u8  │ avc1.77.30  1204k video only
2421                  mp4 960x540     24 │ ~442.84MiB 2422k m3u8  │ avc1.4d401f 2422k video only
3442                  mp4 1280x720    24 │ ~629.49MiB 3442k m3u8  │ avc1.64001f 3442k video only
7834                  mp4 1920x1080   24 │ ~  1.40GiB 7834k m3u8  │ avc1.640028 7834k video only
```

**bv*+ba/b Download**
```
$ ~/.local/bin/yt-dlp-master -vU -f bv*+ba/b --cookies ../masclas-cookies.txt "{$URL}".m3u8
[debug] Command-line config: ['-vU', '-f', 'bv*+ba/b', '--cookies', '../masclas-cookies.txt', '"{$URL}".m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.11.16.200858 from yt-dlp/yt-dlp-master-builds [1d253b0a2] (zip)
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 3.0.14 4 Jun 2024, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.0.9, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.2, sqlite3-3.45.3, urllib3-2.2.2, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1841 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.11.16.200858 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.11.16.200858 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: "{$URL}".m3u8
[generic] "{$VIDNAME}": Downloading webpage
[debug] Identified a direct video link
[generic] "{$VIDNAME}": Downloading m3u8 information
[generic] "{$VIDNAME}": Checking m3u8 live status
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] "{$VIDNAME}": Downloading 1 format(s): 7834+audio_aac_96-English
[debug] Invoking hlsnative downloader on "{$URL}"
[hlsnative] Downloading m3u8 manifest
WARNING: Live HLS streams are not supported by the native downloader. If this is a livestream, please add "--downloader ffmpeg --hls-use-mpegts" to your command
[hlsnative] Total fragments: 384
[download] Destination: "{$VIDNAME}" ["{$VIDNAME}"].f7834.mp4
...
```

**bv+ba/b Download**
```
$ ~/.local/bin/yt-dlp-master -vU -f bv+ba/b --cookies ../masclas-cookies.txt "{$URL}"
[debug] Command-line config: ['-vU', '-f', 'bv+ba/b', '--cookies', '../masclas-cookies.txt', '"{$URL}"']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.11.16.200858 from yt-dlp/yt-dlp-master-builds [1d253b0a2] (zip)
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 3.0.14 4 Jun 2024, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.0.9, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.2, sqlite3-3.45.3, urllib3-2.2.2, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1841 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.11.16.200858 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.11.16.200858 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: "{$URL}"
[generic] "{$VIDNAME}": Downloading webpage
[debug] Identified a direct video link
[generic] "{$VIDNAME}": Downloading m3u8 information
[generic] "{$VIDNAME}": Checking m3u8 live status
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] "{$VIDNAME}": Downloading 1 format(s): 7834+audio_aac_96-English
[debug] Invoking hlsnative downloader on "{$URL}"
[hlsnative] Downloading m3u8 manifest
WARNING: Live HLS streams are not supported by the native downloader. If this is a livestream, please add "--downloader ffmpeg --hls-use-mpegts" to your command
[hlsnative] Total fragments: 384
[download] Destination: "{$VIDNAME}" ["{$VIDNAME}"].f7834.mp4
...
```

I don't mind sharing cookies or creds with a developer.

Thank you very much.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment] 2024-11-16 23:20
Duplicate of #11178

**Closed by bashonly** 2024-11-16 23:20 UTC
Labels: question

**Comment by bashonly** [comment] 2024-11-16 23:37
> My sincerest apologies if this was already covered, but I didn't see this in the known issue thread

You're right, the original issue should be added. Done
