### ISSUE TITLE
[Site Request] Telemundo

### ISSUE THREAD

**Issue by umbongodrink** [yt-dlp/yt-dlp#284] opened 2021-04-29 09:18 UTC
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.04.22**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
Hello,  please can yt-dlp support videos such as:
https://www.telemundo.com/noticias/noticias-telemundo-en-la-noche/video/noticias-telemundo-en-la-noche-28-de-abril-de-2021-tmvo9805534

When I run yt-dlp against that URL I get the following output:

`yt-dlp https://www.telemundo.com/noticias/noticias-telemundo-en-la-noche/video/noticias-telemundo-en-la-noche-28-de-abril-de-2021-tmvo9805534
[generic] noticias-telemundo-en-la-noche-28-de-abril-de-2021-tmvo9805534: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] noticias-telemundo-en-la-noche-28-de-abril-de-2021-tmvo9805534: Downloading webpage
[generic] noticias-telemundo-en-la-noche-28-de-abril-de-2021-tmvo9805534: Extracting information
ERROR: Unsupported URL: https://www.telemundo.com/noticias/noticias-telemundo-en-la-noche/video/noticias-telemundo-en-la-noche-28-de-abril-de-2021-tmvo9805534`

Thank you : )

**Comment by pukkandan** [comment] 2021-05-01 13:57
Related: https://github.com/ytdl-org/youtube-dl/issues/28924

**Comment by umbongodrink** [comment] 2021-05-22 16:47
Hello, thank you for all your work in adding the appropriate extractor. 

I'm afraid there still is a problem, which is that yt-dlp doesn't recognise the "main video" on the webpage. For example, if I issue the command:

`yt-dlp https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405`

a video is downloaded that is ~31 seconds in duration, rather than the main video which is 17 minutes 35 seconds in duration. 

Could you help please? Very many thanks.

**Comment by pukkandan** [comment] 2021-05-22 18:03
cc @king-millez

**Comment by pukkandan** [comment] 2021-05-22 18:11
@umbongodrink Seems to work for me
```
$ yt-dlp https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405 -v
[debug] Command-line config: ['https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.05.20 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 135e6b93f4
[debug] Python version 3.9.2 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [Telemundo] Extracting URL: https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405
[Telemundo] tmvo9832405: Downloading webpage
[Telemundo] tmvo9832405: Processing m3u8
[Telemundo] tmvo9832405: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] tmvo9832405: Downloading 1 format(s): 4179
[debug] Invoking downloader on 'https://telemundo-vh.akamaihd.net/i/MPX/video/NBCU_Telemundo/20210521/4366610_1621643913/210521_4366610_Noticias_Telemundo_6_30_pm__21_de_mayo_de_20_,25,40,18,12,7,4,2,00.mp4.csmil/index_1_av.m3u8?null=0&id=AgAAAAAAMSyDBtBIqWCLfsWhHEc7h%2fQUV9p1DGzpxbU4K+4menTE4e6q3kZfL35crfDRe1feQtLycA%3d%3d&hdntl=exp=1621793360~acl=%2fi%2fMPX%2fvideo%2fNBCU_Telemundo%2f20210521%2f4366610_1621643913%2f210521_4366610_Noticias_Telemundo_6_30_pm__21_de_mayo_de_20_*~data=hdntl~hmac=aa33b36fcda1087fbe170684542ff11874e503943420c11dce64ebf4ba62639e'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 106
[download] Destination: Noticias Telemundo 6_30 pm, 21 de mayo de 2021 [tmvo9832405].mp4
[download]  12.3% of ~563.60MiB at  2.57MiB/s ETA 03:12
ERROR: Interrupted by user
```

Show your verbose output

**Comment by umbongodrink** [comment] 2021-05-22 19:29
Hi @pukkandan, thank you very much indeed for your fast response. Great that it's working on your system. 

This is the verbose output on mine:

`$ yt-dlp https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405 -v
[debug] Command-line config: ['https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.05.20
[debug] Python version 3.8.8 (CPython 64bit) - Linux-4.15.0-123-generic-x86_64-with-glibc2.27
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [Telemundo] Extracting URL: https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405
[Telemundo] tmvo9832405: Downloading webpage
[Telemundo] tmvo9832405: Processing m3u8
[Telemundo] tmvo9832405: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] tmvo9832405: Downloading 1 format(s): 3988
[debug] Invoking downloader on 'https://telemundo-vh.akamaihd.net/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_,25,40,18,12,7,4,2,00.mp4.csmil/index_1_av.m3u8?null=0&id=AgAAAAAAAhJC3+RaqWAVobqAWfGJTNStV0SHi6QS4zj02Jp7IXR5mLDZJzakedVeKp3%2fEIbND4MiWA%3d%3d&hdntl=exp=1621797988~acl=%2fi%2fMPX%2fvideo%2fNBCU_Telemundo%2f20210522%2f4366678_1621659183%2f210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_*~data=hdntl~hmac=f61de993027262258914a365e45bdfc985d2180dcb914c8509b82c7fc4722f46'
[download] Destination: Noticias Telemundo 6_30 pm, 21 de mayo de 2021 [tmvo9832405].mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3608.5 Safari/537.36
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
Cookie: _alid_=/GmJX2IIdqb1xvqd76wSEQ==
' -i 'https://telemundo-vh.akamaihd.net/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_,25,40,18,12,7,4,2,00.mp4.csmil/index_1_av.m3u8?null=0&id=AgAAAAAAAhJC3+RaqWAVobqAWfGJTNStV0SHi6QS4zj02Jp7IXR5mLDZJzakedVeKp3%2fEIbND4MiWA%3d%3d&hdntl=exp=1621797988~acl=%2fi%2fMPX%2fvideo%2fNBCU_Telemundo%2f20210522%2f4366678_1621659183%2f210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_*~data=hdntl~hmac=f61de993027262258914a365e45bdfc985d2180dcb914c8509b82c7fc4722f46' -c copy -f mp4 'file:Noticias Telemundo 6_30 pm, 21 de mayo de 2021 [tmvo9832405].mp4.part'
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[hls,applehttp @ 0x55d10bfd7bc0] HLS request for url 'https://telemundo-vh.akamaihd.net/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_,25,40,18,12,7,4,2,00.mp4.csmil/segment1_1_av.ts?null=0&id=AgAAAAAAAhJC3+RaqWAVobqAWfGJTNStV0SHi6QS4zj02Jp7IXR5mLDZJzakedVeKp3%2fEIbND4MiWA%3d%3d&hdntl=exp=1621797988~acl=/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_*~data=hdntl~hmac=f61de993027262258914a365e45bdfc985d2180dcb914c8509b82c7fc4722f46', offset 0, playlist 0
[hls,applehttp @ 0x55d10bfd7bc0] Opening 'https://telemundo-vh.akamaihd.net/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_,25,40,18,12,7,4,2,00.mp4.csmil/crypt.key?null=0&id=AgAAAAAAAhJC3+RaqWAVobqAWfGJTNStV0SHi6QS4zj02Jp7IXR5mLDZJzakedVeKp3%2fEIbND4MiWA%3d%3d&hdntl=exp=1621797988~acl=/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_*~data=hdntl~hmac=f61de993027262258914a365e45bdfc985d2180dcb914c8509b82c7fc4722f46' for reading
[hls,applehttp @ 0x55d10bfd7bc0] Opening 'crypto+https://telemundo-vh.akamaihd.net/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_,25,40,18,12,7,4,2,00.mp4.csmil/segment1_1_av.ts?null=0&id=AgAAAAAAAhJC3+RaqWAVobqAWfGJTNStV0SHi6QS4zj02Jp7IXR5mLDZJzakedVeKp3%2fEIbND4MiWA%3d%3d&hdntl=exp=1621797988~acl=/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_*~data=hdntl~hmac=f61de993027262258914a365e45bdfc985d2180dcb914c8509b82c7fc4722f46' for reading
[h264 @ 0x55d10c3e14c0] Reinit context to 1920x1088, pix_fmt: yuv420p
Input #0, hls,applehttp, from 'https://telemundo-vh.akamaihd.net/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_,25,40,18,12,7,4,2,00.mp4.csmil/index_1_av.m3u8?null=0&id=AgAAAAAAAhJC3+RaqWAVobqAWfGJTNStV0SHi6QS4zj02Jp7IXR5mLDZJzakedVeKp3%2fEIbND4MiWA%3d%3d&hdntl=exp=1621797988~acl=%2fi%2fMPX%2fvideo%2fNBCU_Telemundo%2f20210522%2f4366678_1621659183%2f210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_*~data=hdntl~hmac=f61de993027262258914a365e45bdfc985d2180dcb914c8509b82c7fc4722f46':
  Duration: 00:00:36.34, start: 0.100511, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (Main), 1 reference frame ([27][0][0][0] / 0x001B), yuv420p(left), 1920x1080 (1920x1088), Closed Captions, 29.97 tbr, 90k tbn, 59.94 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:Noticias Telemundo 6_30 pm, 21 de mayo de 2021 [tmvo9832405].mp4.part':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: h264 (Main), 1 reference frame (avc1 / 0x31637661), yuv420p(left), 1920x1080 (0x0), q=2-31, 29.97 tbr, 90k tbn, 90k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
Automatically inserted bitstream filter 'aac_adtstoasc'; args=''
[hls,applehttp @ 0x55d10bfd7bc0] HLS request for url 'https://telemundo-vh.akamaihd.net/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_,25,40,18,12,7,4,2,00.mp4.csmil/segment2_1_av.ts?null=0&id=AgAAAAAAAhJC3+RaqWAVobqAWfGJTNStV0SHi6QS4zj02Jp7IXR5mLDZJzakedVeKp3%2fEIbND4MiWA%3d%3d&hdntl=exp=1621797988~acl=/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_*~data=hdntl~hmac=f61de993027262258914a365e45bdfc985d2180dcb914c8509b82c7fc4722f46', offset 0, playlist 0
[hls,applehttp @ 0x55d10bfd7bc0] Opening 'crypto+https://telemundo-vh.akamaihd.net/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_,25,40,18,12,7,4,2,00.mp4.csmil/segment2_1_av.ts?null=0&id=AgAAAAAAAhJC3+RaqWAVobqAWfGJTNStV0SHi6QS4zj02Jp7IXR5mLDZJzakedVeKp3%2fEIbND4MiWA%3d%3d&hdntl=exp=1621797988~acl=/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_*~data=hdntl~hmac=f61de993027262258914a365e45bdfc985d2180dcb914c8509b82c7fc4722f46' for reading
[hls,applehttp @ 0x55d10bfd7bc0] HLS request for url 'https://telemundo-vh.akamaihd.net/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_,25,40,18,12,7,4,2,00.mp4.csmil/segment3_1_av.ts?null=0&id=AgAAAAAAAhJC3+RaqWAVobqAWfGJTNStV0SHi6QS4zj02Jp7IXR5mLDZJzakedVeKp3%2fEIbND4MiWA%3d%3d&hdntl=exp=1621797988~acl=/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_*~data=hdntl~hmac=f61de993027262258914a365e45bdfc985d2180dcb914c8509b82c7fc4722f46', offset 0, playlist 0
[hls,applehttp @ 0x55d10bfd7bc0] Opening 'crypto+https://telemundo-vh.akamaihd.net/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_,25,40,18,12,7,4,2,00.mp4.csmil/segment3_1_av.ts?null=0&id=AgAAAAAAAhJC3+RaqWAVobqAWfGJTNStV0SHi6QS4zj02Jp7IXR5mLDZJzakedVeKp3%2fEIbND4MiWA%3d%3d&hdntl=exp=1621797988~acl=/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_*~data=hdntl~hmac=f61de993027262258914a365e45bdfc985d2180dcb914c8509b82c7fc4722f46' for reading
[hls,applehttp @ 0x55d10bfd7bc0] HLS request for url 'https://telemundo-vh.akamaihd.net/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_,25,40,18,12,7,4,2,00.mp4.csmil/segment4_1_av.ts?null=0&id=AgAAAAAAAhJC3+RaqWAVobqAWfGJTNStV0SHi6QS4zj02Jp7IXR5mLDZJzakedVeKp3%2fEIbND4MiWA%3d%3d&hdntl=exp=1621797988~acl=/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_*~data=hdntl~hmac=f61de993027262258914a365e45bdfc985d2180dcb914c8509b82c7fc4722f46', offset 0, playlist 0
[hls,applehttp @ 0x55d10bfd7bc0] Opening 'crypto+https://telemundo-vh.akamaihd.net/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_,25,40,18,12,7,4,2,00.mp4.csmil/segment4_1_av.ts?null=0&id=AgAAAAAAAhJC3+RaqWAVobqAWfGJTNStV0SHi6QS4zj02Jp7IXR5mLDZJzakedVeKp3%2fEIbND4MiWA%3d%3d&hdntl=exp=1621797988~acl=/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_*~data=hdntl~hmac=f61de993027262258914a365e45bdfc985d2180dcb914c8509b82c7fc4722f46' for reading
No more output streams to write to, finishing.e=00:00:35.87 bitrate=3916.7kbits/s speed=11.9x
frame= 1089 fps=356 q=-1.0 Lsize=   17742kB time=00:00:36.31 bitrate=4002.3kbits/s speed=11.9x
video:17274kB audio:437kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.178403%
Input file #0 (https://telemundo-vh.akamaihd.net/i/MPX/video/NBCU_Telemundo/20210522/4366678_1621659183/210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_,25,40,18,12,7,4,2,00.mp4.csmil/index_1_av.m3u8?null=0&id=AgAAAAAAAhJC3+RaqWAVobqAWfGJTNStV0SHi6QS4zj02Jp7IXR5mLDZJzakedVeKp3%2fEIbND4MiWA%3d%3d&hdntl=exp=1621797988~acl=%2fi%2fMPX%2fvideo%2fNBCU_Telemundo%2f20210522%2f4366678_1621659183%2f210522_4366678_Dejaran_de_enviar_fondos_al_Gobierno_de_El_S_*~data=hdntl~hmac=f61de993027262258914a365e45bdfc985d2180dcb914c8509b82c7fc4722f46):
  Input stream #0:0 (video): 1089 packets read (17688510 bytes);
  Input stream #0:1 (audio): 1565 packets read (447407 bytes);
  Total: 2654 packets (18135917 bytes) demuxed
Output file #0 (file:Noticias Telemundo 6_30 pm, 21 de mayo de 2021 [tmvo9832405].mp4.part):
  Output stream #0:0 (video): 1089 packets muxed (17688510 bytes);
  Output stream #0:1 (audio): 1565 packets muxed (447407 bytes);
  Total: 2654 packets (18135917 bytes) muxed
[ffmpeg] Downloaded 18168272 bytes
[download] 100% of 17.33MiB in 00:04`

**Comment by umbongodrink** [comment] 2021-05-22 19:36
The above example is from my Ubuntu 18.04LTS VM machine. 

The following example is from my Ubuntu 20.04LTS VM machine, which it doesn't work on either. This is a fresh installation of yt-dlp (it wasn't on this machine before, installed via the command `python3 -m pip install --upgrade git+https://github.com/yt-dlp/yt-dlp`):

`$ yt-dlp https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405 -v
[debug] Command-line config: ['https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.05.11
[debug] Python version 3.8.5 (CPython 64bit) - Linux-5.8.0-44-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405
[generic] noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405: Downloading webpage
[generic] noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405: Extracting information
ERROR: Unsupported URL: https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405
Traceback (most recent call last):
  File "/home/ladmin/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1126, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ladmin/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1147, in __extract_info
    ie_result = ie.extract(url)
  File "/home/ladmin/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 564, in extract
    ie_result = self._real_extract(url)
  File "/home/ladmin/.local/lib/python3.8/site-packages/yt_dlp/extractor/generic.py", line 3573, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405`

**Comment by pukkandan** [comment] 2021-05-22 19:59
> The following example is from my Ubuntu 20.04LTS VM machine, which it doesn't work on either

This one is using an outdated version

---

It is working for me sometimes, and not working other times. When `4179` appears in the formats, it is working, otherwise not. I'll need to investigate further

```
$ yt-dlp https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405 -v -F
[debug] Command-line config: ['https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405', '-v', '-F']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.05.20 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 8f0cc7cb44
[debug] Python version 3.9.2 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [Telemundo] Extracting URL: https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405
[Telemundo] tmvo9832405: Downloading webpage
[Telemundo] tmvo9832405: Processing m3u8
[Telemundo] tmvo9832405: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for tmvo9832405:
ID   EXT RESOLUTION |   TBR PROTO  | VCODEC        VBR ACODEC     ABR
---- --- ---------- - ----- ------ - ----------- ----- --------- ----
300  mp4 416x236    |  300k m3u8_n | avc1.42001e  300k mp4a.40.2   0k
477  mp4 416x236    |  477k m3u8_n | avc1.42001e  477k mp4a.40.2   0k
749  mp4 640x360    |  749k m3u8_n | avc1.42001e  749k mp4a.40.2   0k
1208 mp4 960x540    | 1208k m3u8_n | avc1.42001e 1208k mp4a.40.2   0k
1846 mp4 960x540    | 1846k m3u8_n | avc1.4d001f 1846k mp4a.40.2   0k
2518 mp4 1280x720   | 2518k m3u8_n | avc1.4d001f 2518k mp4a.40.2   0k
3988 mp4 1920x1080  | 3988k m3u8_n | avc1.4d001f 3988k mp4a.40.2   0k

$ yt-dlp https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405 -v -F
[debug] Command-line config: ['https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405', '-v', '-F']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.05.20 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 8f0cc7cb44
[debug] Python version 3.9.2 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [Telemundo] Extracting URL: https://www.telemundo.com/noticias/edicion-noticias-telemundo/video/noticias-telemundo-630-pm-21-de-mayo-de-2021-tmvo9832405
[Telemundo] tmvo9832405: Downloading webpage
[Telemundo] tmvo9832405: Processing m3u8
[Telemundo] tmvo9832405: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for tmvo9832405:
ID   EXT RESOLUTION |   TBR PROTO  | VCODEC        VBR ACODEC     ABR
---- --- ---------- - ----- ------ - ----------- ----- --------- ----
313  mp4 416x236    |  313k m3u8_n | avc1.42001e  313k mp4a.40.2   0k
511  mp4 416x236    |  511k m3u8_n | avc1.42001e  511k mp4a.40.2   0k
808  mp4 640x360    |  808k m3u8_n | avc1.42001e  808k mp4a.40.2   0k
1303 mp4 960x540    | 1303k m3u8_n | avc1.42001e 1303k mp4a.40.2   0k
1941 mp4 960x540    | 1941k m3u8_n | avc1.4d001f 1941k mp4a.40.2   0k
2652 mp4 1280x720   | 2652k m3u8_n | avc1.4d001f 2652k mp4a.40.2   0k
4179 mp4 1920x1080  | 4179k m3u8_n | avc1.4d001f 4179k mp4a.40.2   0k
```

**Comment by umbongodrink** [comment] 2021-05-22 20:08
ok thank you @pukkandan, I'll wait for your findings. Have a great evening.

**Comment by king-millez** [comment] 2021-06-01 23:38
I'll have a look at this again, maybe I missed something. Could someone send URLs that are more faulty than others, or do I just have to try until failure?

**Comment by umbongodrink** [comment] 2021-06-04 11:57
Hello @king-millez, apologies for the slow reply I've just seen your message. I've upgraded to 2021.06.01 and it's worked  on both my Ubuntu 18.04LTS VM  and my 20.04LTS VM today. I'll keep testing and report again if it fails. I'm also going to build a container for it based on Ubuntu and test. 
Thank you to everyone involved for your work thus far.

**Comment by pukkandan** [comment] 2021-06-07 06:34
I also couldn't reproduce the issue since my last comment. I am closing this again. Please open a new issue if you encounter it again

**Closed by pukkandan** 2021-06-07 06:34 UTC
Labels: site-request
