### ISSUE TITLE
when using --get-filename it adds a random space at the end of the filename

### ISSUE THREAD

**Issue by Sipherdrakon** [yt-dlp/yt-dlp#3731] opened 2022-05-14 04:50 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

So I have tested this on the latest yt-dlp as well as the last version and it happened somewhere in between the two because 03.08 works fine and has no added space when running the command.

### Verbose log

```shell
ytdl --cookies-from-browser chrome --get-filename -o "%(series)s - %(season_number)02dx%(episode_number)02d - %(title)s [WEBDL].%(ext)s" "https://watch.hgtv.com/video/lil-jon-wants-to-do-what-hgtv-atve-us/stone-with-the-honeytones" -v >> test.txt
[debug] Command-line config: ['--cookies-from-browser', 'chrome', '--get-filename', '-o', '%(series)s - %(season_number)02dx%(episode_number)02d - %(title)s [WEBDL].%(ext)s', 'https://watch.hgtv.com/video/lil-jon-wants-to-do-what-hgtv-atve-us/stone-with-the-honeytones', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade65] (win_exe)
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.4 (CPython 64bit) - Windows-10-10.0.18362-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 2022-04-21-git-83e1a1de88-full_build-www.gyan.dev (setts), ffprobe 2022-04-21-git-83e1a1de88-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2021.05.30, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.0
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "****"
[debug] Found local state file at "****"
[Cookies] Extracted 3305 cookies from chrome
[debug] cookie version breakdown: {'v10': 3305, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] [HGTVUsa] Extracting URL: https://watch.hgtv.com/video/lil-jon-wants-to-do-what-hgtv-atve-us/stone-with-the-honeytones
[debug] Using fake IP 6.199.201.125 (US) as X-Forwarded-For
[HGTVUsa] lil-jon-wants-to-do-what-hgtv-atve-us/stone-with-the-honeytones: Downloading JSON metadata
[HGTVUsa] 4768598: Downloading JSON metadata
[HGTVUsa] lil-jon-wants-to-do-what-hgtv-atve-us/stone-with-the-honeytones: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 4768598: Downloading 1 format(s): hls-5286

OUTPUT: Lil Jon Wants to Do What - 01x02 - Stone With the Honeytones [WEBDL].mp4 

***USING 03.08***
ytdl0308 --cookies-from-browser chrome --get-filename -o "%(series)s - %(season_number)02dx%(episode_number)02d - %(title)s [WEBDL].%(ext)s" "https://watch.hgtv.com/video/lil-jon-wants-to-do-what-hgtv-atve-us/stone-with-the-honeytones" -v >> test.txt
[debug] Command-line config: ['--cookies-from-browser', 'chrome', '--get-filename', '-o', '%(series)s - %(season_number)02dx%(episode_number)02d - %(title)s [WEBDL].%(ext)s', 'https://watch.hgtv.com/video/lil-jon-wants-to-do-what-hgtv-atve-us/stone-with-the-honeytones', '-v']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "****"
[Cookies] Extracted 3307 cookies from chrome
[debug] cookie version breakdown: {'v10': 3307, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, out cp1252 (No ANSI), err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 2022-04-21-git-83e1a1de88-full_build-www.gyan.dev (setts), ffprobe 2022-04-21-git-83e1a1de88-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [HGTVUsa] Extracting URL: https://watch.hgtv.com/video/lil-jon-wants-to-do-what-hgtv-atve-us/stone-with-the-honeytones
[debug] Using fake IP 6.178.141.90 (US) as X-Forwarded-For
[HGTVUsa] lil-jon-wants-to-do-what-hgtv-atve-us/stone-with-the-honeytones: Downloading JSON metadata
[HGTVUsa] 4768598: Downloading JSON metadata
[HGTVUsa] lil-jon-wants-to-do-what-hgtv-atve-us/stone-with-the-honeytones: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 4768598: Downloading 1 format(s): hls-5286

OUTPUT: Lil Jon Wants to Do What - 01x02 - Stone With the Honeytones [WEBDL].mp4

This is wreaking havoc on my bash scripts as they try to mux a file that doesn't exist as it has an additional space at the end of the extension.

I've also tested this on paramount+ URLs to see if it was extractor specific and it also does it to those files as well.
```

**Comment by pukkandan** [comment] 2022-05-14 10:10
> I have tested this on the latest yt-dlp

which commit? This should be already fixed

**Comment by gamer191** [comment] 2022-05-15 13:37
> which commit? This should be already fixed

According to the verbose log, they are using the latest release (2022.04.08 windows exe). Has this been fixed in master since that release? If yes, then this should be closed as a duplicate of https://github.com/yt-dlp/yt-dlp/issues/3733 :trollface:

**Comment by pukkandan** [comment] 2022-05-15 15:05
@Sipherdrakon I thought you were saying the tried in both release and master! But it's seems you were comparing 04.08 and 03.08 versions. In that case, I can't reproduce

**Comment by Sipherdrakon** [comment] 2022-05-15 15:24
You're good. I was thinking I was comparing the two but must have been an issue with my build. Rebuilt from master and its working fine now. Sorry for the trouble.

**Closed** 2022-05-15 15:24 UTC
Labels: bug, cant reproduce, incomplete
