### ISSUE TITLE
[youtube] YouTube said: ERROR - Precondition check failed

### ISSUE THREAD

**Issue by rmstock3** [yt-dlp/yt-dlp#9408] opened 2024-03-09 23:16 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Netherlands

### Provide a description that is worded well enough to be understood

WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] OJ56MAGFPGM: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] OJ56MAGFPGM: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] OJ56MAGFPGM: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU -F https://www.youtube.com/watch?v=OJ56MAGFPGM 
[debug] Command-line config: ['-vU', '-F', 'https://www.youtube.com/watch?v=OJ56MAGFPGM']
[debug] User config "/home/ubuntu/.config/yt-dlp/config": ['--hls-prefer-native']
[debug] System config "/etc/yt-dlp.conf": ['--prefer-free-formats']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Python 3.8.2 (CPython x86_64 64bit) - Linux-5.4.0-42-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotlicffi-1.1.0.0, certifi-2019.11.28, mutagen-1.44.0, requests-2.31.0, secretstorage-2.3.1, sqlite3-3.31.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=OJ56MAGFPGM
[youtube] OJ56MAGFPGM: Downloading webpage
[youtube] OJ56MAGFPGM: Downloading ios player API JSON
[youtube] OJ56MAGFPGM: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] OJ56MAGFPGM: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] OJ56MAGFPGM: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] OJ56MAGFPGM: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig V8l29Rzb7FmoZi7S => 6rTtLGyiKk6SIQ
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig W_Qu1x2mDTWuxAkc => eF9ujUGGCdAl-g
[youtube] OJ56MAGFPGM: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for OJ56MAGFPGM:
ID    EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb3   mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb2   mhtml 80x45        0    │                  mhtml │ images                                  storyboard
sb1   mhtml 160x90       0    │                  mhtml │ images                                  storyboard
sb0   mhtml 320x180      0    │                  mhtml │ images                                  storyboard
233-0 mp4   audio only        │                  m3u8  │ audio only          unknown             [es] Español - dubbed, IOS
233-1 mp4   audio only        │                  m3u8  │ audio only          unknown             [fr] Français - dubbed, IOS
233-2 mp4   audio only        │                  m3u8  │ audio only          unknown             [nl] Nederlands - dubbed, IOS
233-3 mp4   audio only        │                  m3u8  │ audio only          unknown             [pt] Português - dubbed, IOS
233-4 mp4   audio only        │                  m3u8  │ audio only          unknown             [en] English - original, IOS
234-0 mp4   audio only        │                  m3u8  │ audio only          unknown             [es] Español - dubbed, IOS
234-1 mp4   audio only        │                  m3u8  │ audio only          unknown             [fr] Français - dubbed, IOS
234-2 mp4   audio only        │                  m3u8  │ audio only          unknown             [nl] Nederlands - dubbed, IOS
234-3 mp4   audio only        │                  m3u8  │ audio only          unknown             [pt] Português - dubbed, IOS
234-4 mp4   audio only        │                  m3u8  │ audio only          unknown             [en] English - original, IOS
139-0 m4a   audio only      2 │    2.83MiB   49k https │ audio only          mp4a.40.5   49k 22k [es] Spanish, low, IOS, m4a_dash
139-1 m4a   audio only      2 │    2.83MiB   49k https │ audio only          mp4a.40.5   49k 22k [fr] French, low, IOS, m4a_dash
139-2 m4a   audio only      2 │    2.83MiB   49k https │ audio only          mp4a.40.5   49k 22k [pt] Portuguese, low, IOS, m4a_dash
139-3 m4a   audio only      2 │    2.83MiB   49k https │ audio only          mp4a.40.5   49k 22k [en] low, IOS, m4a_dash
139-4 m4a   audio only      2 │    2.83MiB   49k https │ audio only          mp4a.40.5   49k 22k [nl] Dutch, low, IOS, m4a_dash
139-5 m4a   audio only      2 │    2.83MiB   49k https │ audio only          mp4a.40.5   49k 22k [en] English original (default), low, IOS, m4a_dash
249-0 webm  audio only      2 │    2.77MiB   48k https │ audio only          opus        48k 48k [fr] French, low, WEB, webm_dash
249-1 webm  audio only      2 │    2.82MiB   49k https │ audio only          opus        49k 48k [nl] Dutch, low, WEB, webm_dash
249-2 webm  audio only      2 │    2.83MiB   49k https │ audio only          opus        49k 48k [pt] Portuguese, low, WEB, webm_dash
249-3 webm  audio only      2 │    2.83MiB   49k https │ audio only          opus        49k 48k [es] Spanish, low, WEB, webm_dash
249-4 webm  audio only      2 │    2.93MiB   51k https │ audio only          opus        51k 48k [en] low, WEB, webm_dash
250-0 webm  audio only      2 │    3.57MiB   62k https │ audio only          opus        62k 48k [fr] French, low, WEB, webm_dash
250-1 webm  audio only      2 │    3.59MiB   62k https │ audio only          opus        62k 48k [pt] Portuguese, low, WEB, webm_dash
250-2 webm  audio only      2 │    3.61MiB   62k https │ audio only          opus        62k 48k [nl] Dutch, low, WEB, webm_dash
250-3 webm  audio only      2 │    3.67MiB   63k https │ audio only          opus        63k 48k [es] Spanish, low, WEB, webm_dash
250-4 webm  audio only      2 │    3.82MiB   66k https │ audio only          opus        66k 48k [en] low, WEB, webm_dash
249-5 webm  audio only      2 │    2.93MiB   51k https │ audio only          opus        51k 48k [en] English original (default), low, WEB, webm_dash
250-5 webm  audio only      2 │    3.82MiB   66k https │ audio only          opus        66k 48k [en] English original (default), low, WEB, webm_dash
140-0 m4a   audio only      2 │    7.51MiB  129k https │ audio only          mp4a.40.2  129k 44k [en] medium, IOS, m4a_dash
140-1 m4a   audio only      2 │    7.51MiB  129k https │ audio only          mp4a.40.2  129k 44k [fr] French, medium, IOS, m4a_dash
140-2 m4a   audio only      2 │    7.51MiB  129k https │ audio only          mp4a.40.2  129k 44k [es] Spanish, medium, IOS, m4a_dash
140-3 m4a   audio only      2 │    7.51MiB  129k https │ audio only          mp4a.40.2  129k 44k [pt] Portuguese, medium, IOS, m4a_dash
140-4 m4a   audio only      2 │    7.51MiB  129k https │ audio only          mp4a.40.2  129k 44k [nl] Dutch, medium, IOS, m4a_dash
140-5 m4a   audio only      2 │    7.51MiB  129k https │ audio only          mp4a.40.2  129k 44k [en] English original (default), medium, IOS, m4a_dash
251-0 webm  audio only      2 │    6.89MiB  119k https │ audio only          opus       119k 48k [nl] Dutch, medium, WEB, webm_dash
251-1 webm  audio only      2 │    6.93MiB  119k https │ audio only          opus       119k 48k [pt] Portuguese, medium, WEB, webm_dash
s       119k 48k [pt] Portuguese, medium, WEB, webm_dash
251-2 webm  audio only      2 │    6.94MiB  120k https │ audio only          opus       120k 48k [fr] French, medium, WEB, webm_dash
251-3 webm  audio only      2 │    7.10MiB  122k https │ audio only          opus       122k 48k [es] Spanish, medium, WEB, webm_dash
251-4 webm  audio only      2 │    7.28MiB  126k https │ audio only          opus       126k 48k [en] medium, WEB, webm_dash
251-5 webm  audio only      2 │    7.28MiB  126k https │ audio only          opus       126k 48k [en] English original (default), medium, WEB, webm_dash
602   mp4   256x144     13    │ ~  7.32MiB  123k m3u8  │ vp09.00.10.08  123k video only          IOS
269   mp4   256x144     25    │ ~ 10.89MiB  184k m3u8  │ avc1.4D400C    184k video only          IOS
160   mp4   256x144     25    │    6.25MiB  108k https │ avc1.4D400C    108k video only          144p, IOS, mp4_dash
603   mp4   256x144     25    │ ~ 11.56MiB  195k m3u8  │ vp09.00.11.08  195k video only          IOS
278   webm  256x144     25    │    6.44MiB  111k https │ vp09.00.11.08  111k video only          144p, IOS, webm_dash
229   mp4   426x240     25    │ ~ 19.48MiB  328k m3u8  │ avc1.4D4015    328k video only          IOS
133   mp4   426x240     25    │   13.90MiB  240k https │ avc1.4D4015    240k video only          240p, IOS, mp4_dash
604   mp4   426x240     25    │ ~ 22.24MiB  375k m3u8  │ vp09.00.20.08  375k video only          IOS
242   webm  426x240     25    │   13.13MiB  226k https │ vp09.00.20.08  226k video only          240p, IOS, webm_dash
230   mp4   640x360     25    │ ~ 48.12MiB  811k m3u8  │ avc1.4D401E    811k video only          IOS
134   mp4   640x360     25    │   31.19MiB  538k https │ avc1.4D401E    538k video only          360p, IOS, mp4_dash
18    mp4   640x360     25  2 │   36.83MiB  635k https │ avc1.42001E         mp4a.40.2       44k [en] 360p, WEB
605   mp4   640x360     25    │ ~ 40.06MiB  675k m3u8  │ vp09.00.21.08  675k video only          IOS
243   webm  640x360     25    │   21.00MiB  362k https │ vp09.00.21.08  362k video only          360p, IOS, webm_dash
231   mp4   854x480     25    │ ~ 88.52MiB 1492k m3u8  │ avc1.4D401E   1492k video only          IOS
135   mp4   854x480     25    │   60.58MiB 1045k https │ avc1.4D401E   1045k video only          480p, IOS, mp4_dash
606   mp4   854x480     25    │ ~ 64.73MiB 1091k m3u8  │ vp09.00.30.08 1091k video only          IOS
244   webm  854x480     25    │   35.77MiB  617k https │ vp09.00.30.08  617k video only          480p, IOS, webm_dash
22    mp4   1280x720    25  2 │ ≈182.17MiB 3071k https │ avc1.64001F         mp4a.40.2       44k [en] 720p, WEB
136   mp4   1280x720    25    │  120.31MiB 2075k https │ avc1.64001f   2075k video only          720p, WEB, mp4_dash
247   webm  1280x720    25    │   63.73MiB 1099k https │ vp9           1099k video only          720p, WEB, webm_dash
311   mp4   1280x720    50    │ ~254.86MiB 4296k m3u8  │ avc1.640020   4296k video only          IOS
298   mp4   1280x720    50    │  194.40MiB 3353k https │ avc1.640020   3353k video only          720p50, IOS, mp4_dash
612   mp4   1280x720    50    │ ~217.67MiB 3669k m3u8  │ vp09.00.40.08 3669k video only          IOS
302   webm  1280x720    50    │  140.55MiB 2424k https │ vp09.00.40.08 2424k video only          720p50, IOS, webm_dash
312   mp4   1920x1080   50    │ ~405.77MiB 6840k m3u8  │ avc1.64002A   6840k video only          IOS299   mp4   1920x1080   50    │  337.30MiB 5817k https │ avc1.64002A   5817k video only          1080p50, IOS, mp4_dash
617   mp4   1920x1080   50    │ ~321.33MiB 5416k m3u8  │ vp09.00.41.08 5416k video only          IOS
303   webm  1920x1080   50    │  228.37MiB 3939k https │ vp09.00.41.08 3939k video only          1080p50, IOS, webm_dash
$
```

**Comment by seproDev** [comment] 2024-03-09 23:17
Duplicate of #9316

Update to nightly

if you are using the exe/zip:
```
yt-dlp --update-to nightly
```

or if you installed with pip:
```
python3 -m pip install -U --pre yt-dlp
```

**Closed by seproDev** 2024-03-09 23:17 UTC
Labels: site-bug, triage

**Comment by NyanBlade** [comment] 2024-03-11 22:29
@seproDev This doesn't work for me. I have updated to the nightly releases for the last two days, and updated to the latest stable release today but I still get this error:
```
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by seproDev** [comment] 2024-03-11 23:23
@NyanBlade Post a verbose log by running `yt-dlp -vU "URL"`.
