### ISSUE TITLE
[Broken] Certain YouTube videos fail to download (HTTP Error 404: Not Found. Retrying fragment 1)

### ISSUE THREAD

**Issue by fastily** [yt-dlp/yt-dlp#1102] opened 2021-09-27 08:00 UTC
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ yt-dlp -v 'https://www.youtube.com/watch?v=XuupsFx6lNk'
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=XuupsFx6lNk']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.25
[debug] Git HEAD: 109f24fd6
[debug] Python version 3.9.7 (CPython 64bit) - macOS-11.6-arm64-arm-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Crypto, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=XuupsFx6lNk
[youtube] XuupsFx6lNk: Downloading webpage
[youtube] XuupsFx6lNk: Downloading android player API JSON
[youtube] XuupsFx6lNk: Downloading MPD manifest
[youtube] XuupsFx6lNk: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Testing thumbnail 41
[debug] Unable to connect to thumbnail 41 URL "https://i.ytimg.com/vi_webp/XuupsFx6lNk/maxresdefault.webp" - HTTP Error 404: Not Found. Skipping...
[debug] Testing thumbnail 40
[debug] Unable to connect to thumbnail 40 URL "https://i.ytimg.com/vi/XuupsFx6lNk/maxresdefault.jpg" - HTTP Error 404: Not Found. Skipping...
[debug] Testing thumbnail 39
[debug] Unable to connect to thumbnail 39 URL "https://i.ytimg.com/vi_webp/XuupsFx6lNk/hq720.webp" - HTTP Error 404: Not Found. Skipping...
[debug] Testing thumbnail 38
[debug] Unable to connect to thumbnail 38 URL "https://i.ytimg.com/vi/XuupsFx6lNk/hq720.jpg" - HTTP Error 404: Not Found. Skipping...
[debug] Testing thumbnail 37
[debug] Unable to connect to thumbnail 37 URL "https://i.ytimg.com/vi_webp/XuupsFx6lNk/sddefault.webp" - HTTP Error 404: Not Found. Skipping...
[debug] Default format spec: bestvideo*+bestaudio/best
[info] XuupsFx6lNk: Downloading 1 format(s): 244+251
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1632750729/ei/KXhRYeTNI8uJkga8ho6QDA/ip/24.5.179.166/id/5eeba9b05c7a94d9/source/youtube/requiressl/yes/playback_host/r4---sn-o097znze.googlevideo.com/mh/nq/mm/31%2C29/mn/sn-o097znze%2Csn-n4v7snee/ms/au%2Crdu/mv/m/mvi/4/pl/20/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/2071250/vprv/1/mt/1632728930/fvip/4/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRgIhAKuIyZoOjtrhtGGxHis7RXH3cc8rJ07g5mLn_2lq3rEvAiEAu3XHL2iRhAjNxUJQz_oDUB4DwOaDHjTCnvbuzk9bIXM%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRAIgfR-f5VbRymc1dR9Lii095noM_pwZqEnN-0QHDOV0Ld4CIDeTN3QqUJ2mL705efAXtYWkooB8RriAYGxcN3DlG8Vb"
[dashsegments] Total fragments: 4
[download] Destination: Pip luv [XuupsFx6lNk].f244.webm
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 1 (attempt 10 of 10) ...
ERROR: Giving up after 10 fragment retries
  File "/opt/homebrew/bin/yt-dlp", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp==2021.9.25', 'console_scripts', 'yt-dlp')())
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/__init__.py", line 777, in main
    _real_main(argv)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/__init__.py", line 767, in _real_main
    retcode = ydl.download(all_urls)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2925, in download
    res = self.extract_info(
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1219, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1227, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1265, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1315, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2344, in process_video_result
    self.process_info(new_info)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2812, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2489, in dl
    return fd.download(name, new_info, subtitle)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 408, in download
    return self.real_download(filename, info_dict), True
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/downloader/dash.py", line 63, in real_download
    return self.download_and_append_fragments(ctx, fragments_to_download, info_dict)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/downloader/fragment.py", line 477, in download_and_append_fragments
    frag_content, frag_index = download_fragment(fragment, ctx)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/downloader/fragment.py", line 440, in download_fragment
    self.report_error('Giving up after %s fragment retries' % fragment_retries)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 176, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 819, in report_error
    self.trouble(error_message, tb)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 775, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

ERROR: fragment 1 not found, unable to continue
  File "/opt/homebrew/bin/yt-dlp", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp==2021.9.25', 'console_scripts', 'yt-dlp')())
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/__init__.py", line 777, in main
    _real_main(argv)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/__init__.py", line 767, in _real_main
    retcode = ydl.download(all_urls)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2925, in download
    res = self.extract_info(
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1219, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1227, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1265, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1315, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2344, in process_video_result
    self.process_info(new_info)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2812, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2489, in dl
    return fd.download(name, new_info, subtitle)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 408, in download
    return self.real_download(filename, info_dict), True
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/downloader/dash.py", line 63, in real_download
    return self.download_and_append_fragments(ctx, fragments_to_download, info_dict)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/downloader/fragment.py", line 478, in download_and_append_fragments
    result = append_fragment(decrypt_fragment(fragment, frag_content), frag_index, ctx)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/downloader/fragment.py", line 451, in append_fragment
    self.report_error(
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 176, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 819, in report_error
    self.trouble(error_message, tb)
  File "/opt/homebrew/Cellar/yt-dlp/2021.9.25/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 775, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

[debug] Invoking downloader on "https://r4---sn-o097znze.googlevideo.com/videoplayback?expire=1632750730&ei=KnhRYb7uDIeVkgah2qCAAg&ip=24.5.179.166&id=o-ADf2_uQMgRnZMwUWvTcZLmA8bP3rElA9mMl-WHtPvkiR&itag=251&source=youtube&requiressl=yes&mh=nq&mm=31%2C29&mn=sn-o097znze%2Csn-n4v7snee&ms=au%2Crdu&mv=m&mvi=4&pl=20&initcwndbps=2137500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=182135&dur=15.101&lmt=1563369864083152&mt=1632728681&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANXHx7j4aA0r5VJQwUIyqWuEYv0kAMhbJhlxEwxYmq5NAiEAgNpqGv4O6TnXasWFI6BlTyvMR0vO6g_0-5yKIBFMGEI%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgHKBItUABjOzyi4E5j9D37k8trbHhW2KeqqFEajTDVuwCIBttiNreQUGbOxRuxqidvpO22hOlGV2eMZLjsPhiq4u8"
[download] Destination: Pip luv [XuupsFx6lNk].f251.webm
[download] 100% of 177.87KiB in 00:00

```

## Description

I've discovered a couple of YouTube videos that play fine in the browser, but are otherwise failing to download:

* [1](https://www.youtube.com/watch?v=XuupsFx6lNk)
* [2](https://www.youtube.com/watch?v=0gXvFkgNvHg)

Possibly related to #502.  Main difference seems to be that downloading the videos linked above errors out within seconds, whereas the [video](https://www.youtube.com/watch?v=V_h3Z40AAtw) in #502 fails extremely slowly.

**Comment by coletdjnz** [comment] 2021-09-27 08:15
Yeah this is the same as #502 afaik.

> whereas the video in #502 fails extremely slowly.

From what I've seen, sometimes these particular formats fail on the first fragment, others later on or even eventually succeed.

**Comment by pukkandan** [comment] 2021-09-27 19:49
Marking this as duplicate of #502. To the best of my knowledge, this is youtube's fault. If you try to force the format on browser, you get the same results. Nothing we can do to completely fix it. You can workaround the issue by adding a `--check-formats` to your command.

Feel free to continue any discussion in #502

**Closed by pukkandan** 2021-09-27 19:49 UTC
Labels: duplicate
