### ISSUE TITLE
[ytmusic] Save lyrics in LYRICS field from Lyrics tab in music.youtube.com

### ISSUE THREAD

**Issue by Rexadev** [yt-dlp/yt-dlp#3925] opened 2022-05-31 16:22 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

 example - `music.youtube.com/watch?v=q4ixeKXJGvo&list=RDAMVMq4ixeKXJGvo`

**Comment by NanaMizukiAnother7** [comment] 2022-06-05 02:14
Hmmm... This issue looks like #3847, which that this issue is a duplicate of it. You can keep looking for it.

**Comment by Rexadev** [comment] 2022-06-05 05:28
@NanaMizukiAnother7 No that is no generic issue i put for discussion here I am telling exactly what I suggest

**Comment by NanaMizukiAnother7** [comment] 2022-06-05 18:14
Well, if we suggest that the lyrics are extracted, how about LYRICS can put on metadata?

**Comment by Rexadev** [comment] 2022-06-05 18:17
>  how about LYRICS can put on metadata?
What?
Also https://github.com/yt-dlp/yt-dlp/issues/3847 is about description here I am talking about music.youtube.com

**Comment by pukkandan** [comment] 2022-06-06 04:04
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/622

**Closed by pukkandan** 2022-06-06 04:04 UTC
Labels: enhancement, triage
