### ISSUE TITLE
403 error when using 'download_ranges' via ffmpeg with a proxy

### ISSUE THREAD

**Issue by jamesvickers19** [yt-dlp/yt-dlp#11421] opened 2024-11-01 01:29 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I have a Python server that downloads videos with yt-dlp `2024.10.22` using the Python library.  It issues requests with a proxy (NordVPN).  It can download full videos fine, but recently has stopped working when using the `'download_ranges'` ranges option.  The error output says `yt_dlp.utils.DownloadError: ERROR: ffmpeg exited with code 1` and `HTTP error 403 Forbidden` on downloading the video via ffmpeg.  When I try the ffmpeg command in the logs without a proxy, it works.

As an attempted fix, I tried adding this parameter to the `YoutubeDL` parameters with no effect: `'postprocessor_args': ['-http_proxy', f"http://{proxy_user}:{proxy_password}@{proxy_address}"]`.

Possibly the most relevant info is that this appears to have started with recent versions of yt-dlp, with no other code changes on my part.  I think it started on either `2024.10.7` or `2024.9.27`, though now going back to those versions doesn't work with YouTube when I try to test that theory.  I never had to configure the usage of ffmpeg for the proxy before, but wondering if recent changes have made that necessary and if I'm not doing so correctly.  I also notice the logged ffmpeg command line args do not seem to include the `-http_proxy` argument.  If requests are to go through a proxy, is this configuration of ffmpeg to use that proxy necessary and does it look reasonable?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (pip) API
[debug] params: {'format': 'best', 'outtmpl': '/tmp/17c6830d-22eb-4ba2-bd56-ad182dcf6e54_%(section_title)s.%(ext)s', 'download_ranges': <function download_video.<locals>.<lambda> at 0x77a159489280>, 'proxy': 'https://REDACTED_USER:REDACTED_PASSWORD@us6779.nordvpn.com:89', 'postprocessor_args': ['-http_proxy', 'http://REDACTED_USER:REDACTED_PASSWORD@us6779.nordvpn.com:89'], 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.15 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.9.19 (CPython x86_64 64bit) - Linux-6.8.0-45-generic-x86_64-with-glibc2.36 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.5-0 (setts), ffprobe 5.1.5-0
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.2, websockets-13.1
[debug] Proxy map: {'all': 'https://REDACTED_USER:REDACTED_PASSWORD@us6779.nordvpn.com:89'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[youtube] Extracting URL: https://youtube.com/watch?v=qz1EpqwMmf4
[youtube] qz1EpqwMmf4: Downloading webpage
[youtube] qz1EpqwMmf4: Downloading ios player API JSON
[youtube] qz1EpqwMmf4: Downloading mweb player API JSON
[debug] Loading youtube-nsig.4e23410d from cache
[debug] [youtube] Decrypted nsig b6azZWbfWpPEHGtil => -Z9XOEZIOt6m3Q
[youtube] qz1EpqwMmf4: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] qz1EpqwMmf4: Downloading 1 format(s): 18
[info] qz1EpqwMmf4: Downloading 1 time ranges: 0.0-1.2
[debug] Invoking ffmpeg downloader on "https://rr3---sn-ab5sznld.googlevideo.com/videoplayback?expire=1730445328&ei=sCskZ6_lF-CAkucPuODj0QQ&ip=185.199.103.31&id=o-ABDK53HWGPR8hm9KVkw8J7dbnW41GWaW-dt_yDzpcXTB&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1730423728%2C&mh=mj&mm=31%2C26&mn=sn-ab5sznld%2Csn-vgqsknls&ms=au%2Conr&mv=m&mvi=3&pl=24&rms=au%2Cau&initcwndbps=1457500&bui=AQn3pFSZi1P05Xy9cRcyKy8br2PexUEh1PJu3wd3duv7Z2OOVskGIPdZDKPQH-QMyjsRJ3sp3EpMJqkq&spc=qtApAf3OnJ9rjBXPJeVrdYjh9Mhqf87xdZIxJ9-UOWIFbj5vK3iZBGUCghDatiw&vprv=1&svpuc=1&mime=video%2Fmp4&ns=LnsFn35jHeeWSY8crI6Ou3cQ&rqh=1&gir=yes&clen=95113&ratebypass=yes&dur=3.366&lmt=1720864670659914&mt=1730423348&fvip=2&fexp=51312688%2C51326932%2C51331020&c=MWEB&sefc=1&txp=6218224&n=-Z9XOEZIOt6m3Q&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIhAMSotR1C6Y3JvNInAvL1B58Gc4S8LQcwS8XendEbixpzAiB6fRVsb8PuphC00gZAYpY8RYtC0qQkVj0rkkUWHsCqcQ%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=ACJ0pHgwRAIgcYNS8b_1E7ZpX0KIhdS3EnDHFp-76-ff0Xem32AYMvQCIFFESa0RidBmiREtwSBdAow9rkvr1N0UW64-w1dD3KjX"
[download] Destination: /tmp/17c6830d-22eb-4ba2-bd56-ad182dcf6e54_Voldemort_Laughing_range.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.15 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
' -t 1.25 -i 'https://rr3---sn-ab5sznld.googlevideo.com/videoplayback?expire=1730445328&ei=sCskZ6_lF-CAkucPuODj0QQ&ip=185.199.103.31&id=o-ABDK53HWGPR8hm9KVkw8J7dbnW41GWaW-dt_yDzpcXTB&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1730423728%2C&mh=mj&mm=31%2C26&mn=sn-ab5sznld%2Csn-vgqsknls&ms=au%2Conr&mv=m&mvi=3&pl=24&rms=au%2Cau&initcwndbps=1457500&bui=AQn3pFSZi1P05Xy9cRcyKy8br2PexUEh1PJu3wd3duv7Z2OOVskGIPdZDKPQH-QMyjsRJ3sp3EpMJqkq&spc=qtApAf3OnJ9rjBXPJeVrdYjh9Mhqf87xdZIxJ9-UOWIFbj5vK3iZBGUCghDatiw&vprv=1&svpuc=1&mime=video%2Fmp4&ns=LnsFn35jHeeWSY8crI6Ou3cQ&rqh=1&gir=yes&clen=95113&ratebypass=yes&dur=3.366&lmt=1720864670659914&mt=1730423348&fvip=2&fexp=51312688%2C51326932%2C51331020&c=MWEB&sefc=1&txp=6218224&n=-Z9XOEZIOt6m3Q&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIhAMSotR1C6Y3JvNInAvL1B58Gc4S8LQcwS8XendEbixpzAiB6fRVsb8PuphC00gZAYpY8RYtC0qQkVj0rkkUWHsCqcQ%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=ACJ0pHgwRAIgcYNS8b_1E7ZpX0KIhdS3EnDHFp-76-ff0Xem32AYMvQCIFFESa0RidBmiREtwSBdAow9rkvr1N0UW64-w1dD3KjX' -c copy -f mp4 file:/tmp/17c6830d-22eb-4ba2-bd56-ad182dcf6e54_Voldemort_Laughing_range.mp4.part
ffmpeg version 5.1.5-0+deb12u1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+deb12u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[tcp @ 0x6065258ae000] Starting connection attempt to 173.194.185.136 port 443
[tcp @ 0x6065258ae000] Successfully connected to 173.194.185.136 port 443
[tcp @ 0x606525979b40] Starting connection attempt to 74.125.0.169 port 443
[tcp @ 0x606525979b40] Successfully connected to 74.125.0.169 port 443
[https @ 0x6065258a9d80] HTTP error 403 Forbidden
https://rr3---sn-ab5sznld.googlevideo.com/videoplayback?expire=1730445328&ei=sCskZ6_lF-CAkucPuODj0QQ&ip=185.199.103.31&id=o-ABDK53HWGPR8hm9KVkw8J7dbnW41GWaW-dt_yDzpcXTB&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1730423728%2C&mh=mj&mm=31%2C26&mn=sn-ab5sznld%2Csn-vgqsknls&ms=au%2Conr&mv=m&mvi=3&pl=24&rms=au%2Cau&initcwndbps=1457500&bui=AQn3pFSZi1P05Xy9cRcyKy8br2PexUEh1PJu3wd3duv7Z2OOVskGIPdZDKPQH-QMyjsRJ3sp3EpMJqkq&spc=qtApAf3OnJ9rjBXPJeVrdYjh9Mhqf87xdZIxJ9-UOWIFbj5vK3iZBGUCghDatiw&vprv=1&svpuc=1&mime=video%2Fmp4&ns=LnsFn35jHeeWSY8crI6Ou3cQ&rqh=1&gir=yes&clen=95113&ratebypass=yes&dur=3.366&lmt=1720864670659914&mt=1730423348&fvip=2&fexp=51312688%2C51326932%2C51331020&c=MWEB&sefc=1&txp=6218224&n=-Z9XOEZIOt6m3Q&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIhAMSotR1C6Y3JvNInAvL1B58Gc4S8LQcwS8XendEbixpzAiB6fRVsb8PuphC00gZAYpY8RYtC0qQkVj0rkkUWHsCqcQ%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=ACJ0pHgwRAIgcYNS8b_1E7ZpX0KIhdS3EnDHFp-76-ff0Xem32AYMvQCIFFESa0RidBmiREtwSBdAow9rkvr1N0UW64-w1dD3KjX: Server returned 403 Forbidden (access denied)


ERROR: ffmpeg exited with code 1
  File "/usr/local/lib/python3.9/threading.py", line 937, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/app/./main.py", line 57, in download_video_by_id
    downloaded_file = download_video(
  File "/app/./youtube_client.py", line 137, in download_video
    error = ytdl.download([youtube_video_url(video_id)])
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3608, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3581, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1614, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1781, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1840, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3014, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 178, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3482, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3202, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/downloader/external.py", line 80, in real_download
    self.report_error('%s exited with code %d' % (
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1091, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1019, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

INFO:     REDACTED IP ADDRESS - "POST /download_video HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 631, in __call__
    await self.app(scope, otel_receive, otel_send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/app/./main.py", line 57, in download_video_by_id
    downloaded_file = download_video(
  File "/app/./youtube_client.py", line 137, in download_video
    error = ytdl.download([youtube_video_url(video_id)])
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3608, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3581, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1614, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1781, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1840, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3014, in process_video_result
    self.process_info(new_info)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 178, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3482, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3202, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/downloader/external.py", line 80, in real_download
    self.report_error('%s exited with code %d' % (
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1091, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1030, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: ffmpeg exited with code 1
```
```

**Comment by bashonly** [comment] 2024-11-01 02:32
> As an attempted fix, I tried adding this parameter to the `YoutubeDL` parameters with no effect: `'postprocessor_args': ['-http_proxy', f"http://{proxy_user}:{proxy_password}@{proxy_address}"]`.
> ... the logged ffmpeg command line args do not seem to include the `-http_proxy` argument. 

`postprocessor_args` is a no-op, because `download_ranges` is applied during download, not during postprocessing. ffmpeg is being used as the external downloader, so you would do this instead:

```py
'external_downloader_args': {'ffmpeg': ['-http_proxy', f'http://{proxy_user}:{proxy_password}@{proxy_address}']}
```

...but that brings me to your next question:

---

> If requests are to go through a proxy, is this configuration of ffmpeg to use that proxy necessary

No, passing the ffmpeg proxy args via `external_downloader_args` is not necessary. yt-dlp already passes the proxy to ffmpeg via environment variables:

https://github.com/yt-dlp/yt-dlp/blob/a6783a3b9905e547f6c1d4df9d7c7999feda8afa/yt_dlp/downloader/external.py#L519-L525

---

> I have a Python server that downloads videos with yt-dlp `2024.10.22` using the Python library.  It issues requests with a proxy (NordVPN).  
> Possibly the most relevant info is that this appears to have started with recent versions of yt-dlp, with no other code changes on my part.  I think it started on either `2024.10.7` or `2024.9.27`, though now going back to those versions doesn't work with YouTube when I try to test that theory.  
> I never had to configure the usage of ffmpeg for the proxy before, but wondering if recent changes have made that necessary

The only relevant yt-dlp changes since July have been efb42763dec23ccf6a2e3bac3afbfefce8efd012, 406f4c2e47502fffc1b0c210b4ee6487c89a44cb and de2062753a188060d76f587e45becce61fe399f9. All 3 were changes to the default player clients that yt-dlp uses when extracting Youtube formats.

You can use the `player_client` Youtube extractor argument to test if the previous default player clients work any better for you, e.g.:

```py
'extractor_args': {'youtube': {'player_client': ['tv']}}
```

`['ios', 'tv']` were the default player clients from version `2024.08.01` until `2024.08.06`, when they were changed to `['ios', 'web_creator']`. And it was shortly before the `2024.10.07` release that they were changed to what they are now, `['ios', 'mweb']`. Before August '24, they were `['ios', 'web']`.

Note that some of these default client changes in yt-dlp were necessitated by Youtube changes: `web` became afflicted with a [`po_token` requirement](https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide), and `web_creator` [began requiring sign-in](https://github.com/yt-dlp/yt-dlp/issues/11201#issuecomment-2402824649)

What's happening in your case may be unrelated to the player client changes, though. It's possibly related to some of the [other proxy-related Youtube issues](https://github.com/yt-dlp/yt-dlp/issues/11349) being reported lately.

**Comment by jamesvickers19** [comment] 2024-11-01 23:31
Thank you _very_ much for the details response.  In that other issue someone [mentioned](https://github.com/yt-dlp/yt-dlp/issues/11349#issuecomment-2438798064) changing the VPN server address as a fix.  I tried this to no avail though :(

If it was that the VPN server is blacklisted or something, I would think I wouldn't be able to download any video through the VPN.  But it's only ffpmeg that can't do it, that's the curious part.

**Comment by jamesvickers19** [comment] 2024-11-01 23:37
Also tried setting `'extractor_args': {'youtube': {'player_client': ['tv']}}`, no change.

**Comment by jamesvickers19** [comment] 2024-11-02 16:23
Today when I try running that `ffmpeg` command, it gets a 403 with or without a proxy set from my personal laptop and the server.  Curious if anyone else sees the same.

**Comment by bashonly** [comment] 2024-11-02 16:32
I can't reproduce the 403 on master. Just ran `yt-dlp --ignore-config -vf18 --download-sections "*0.0-1.2" qz1EpqwMmf4` and the ffmpeg download completed without issue

**Comment by jamesvickers19** [comment] 2024-11-02 16:34
Interesting.  The command you posted works on my laptop, but the ffmpeg one doesn't.

**Comment by bashonly** [comment] 2024-11-02 16:55
what ffmpeg command?

**Comment by bashonly** [comment] 2024-11-02 17:00
If you're talking about the ffmpeg command from the log in your original post, that URL expired over 24 hours ago; the 403 is expected

**Comment by jamesvickers19** [comment] 2024-11-02 17:10
Yes, that was the command.  Gotcha

**Comment by bashonly** [comment] 2024-11-23 17:42
Closing since this can't be reproduced and is likely caused by the VPN

**Closed by bashonly** 2024-11-23 17:42 UTC
Labels: site-bug, triage, site:youtube
