### ISSUE TITLE
YouTube's best quality is premium on some videos ("HTTP Error 404: Not Found")

### ISSUE THREAD

**Issue by jshir** [yt-dlp/yt-dlp#7978] opened 2023-08-28 19:34 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Example video ttps://www.youtube.com/watch?v=Whqs8v1svyo
This video is one of several I have encountered where YouTube offers a 1080p premium option.
I don't have premium (and those users who do may not feel the quality bump is worth sharing the session cookie). So the best quality I can access is 248, and 616 is premium. (Formats pasted in verbose field)

It is easy enough to work around if you are comfortable with custom command switches, but I'll bet some people are using yt-dlp behind a frontend and wondering what is going on. If I force format 248 it works. If I force "best" explicitly, it picks format 22 (1280x720) and works but is far from actually the best format as the built in warning advises.

I have to assume that behind the scenes there is some kind of exception handling where YouTube demands a login session and then requires it be current with a Premium subscription. If possible, I would love for the default to be format 616, and the exception is caught, and yt-dlp to retry with 248 (obviously substitute whatever the actual formats are if they differ). Also since yt-dlp already knows it is a Premium option, if I don't pass a cookie, trying that format will never bear fruit and it could be skipped entirely.

My apologies if this is duplicate, I feel I shouldn't be the first to report this but searching gave me nothing similar previously reported.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=Whqs8v1svyo']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109772-gc56f5be678-20230208 (setts), ffprobe N-109772-gc56f5be678-20230208, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=Whqs8v1svyo
[youtube] Whqs8v1svyo: Downloading webpage
[youtube] Whqs8v1svyo: Downloading ios player API JSON
[youtube] Whqs8v1svyo: Downloading android player API JSON
[youtube] Whqs8v1svyo: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Whqs8v1svyo: Downloading 1 format(s): 616+251
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1693272185/ei/GfTsZKnUFqPWir4Pgq-NkAs/ip/76.136.107.231/id/5a1aacf2fd6cbf2a/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D247678746%3Bdur%3D673.960%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1693236236819650/hls_chunk_host/rr3---sn-vgqsrnzs.googlevideo.com/mh/Ko/mm/31,29/mn/sn-vgqsrnzs,sn-vgqsknlr/ms/au,rdu/mv/m/mvi/3/pl/22/initcwndbps/1573750/vprv/1/playlist_type/DVR/dover/13/txp/3308224/mt/1693250224/fvip/5/short_key/1/keepalive/yes/fexp/24007246/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,vprv,playlist_type/sig/AOq0QJ8wRQIgThO87fgcjBcjip11RHdG8nA458kdufFltOI3KxWLw0ECIQDOiQUr-U-ibryDX3ReaN0J302carRAEuJJ1NQ-36D1zw%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AG3C_xAwRQIhAP43hN4J0ruB2yEsMhOr1REmJGs5i_Lr_LriSvTgdL0eAiAPFsz6igLi7Ob_2MSpXTn8EioXWoUH5rIDJB65IYEhcA%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3345, in process_info
  File "yt_dlp\YoutubeDL.py", line 3084, in dl
  File "yt_dlp\downloader\common.py", line 461, in download
  File "yt_dlp\downloader\hls.py", line 77, in real_download
  File "yt_dlp\YoutubeDL.py", line 3863, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

---------

[info] Available formats for Whqs8v1svyo:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb1 mhtml 80x45        0    │                  mhtml │ images                                  storyboard
sb0 mhtml 160x90       0    │                  mhtml │ images                                  storyboard
233 mp4   audio only        │                  m3u8  │ audio only          unknown             [en] Default
234 mp4   audio only        │                  m3u8  │ audio only          unknown             [en] Default
599 m4a   audio only      2 │    2.47MiB   31k https │ audio only          mp4a.40.5   31k 22k [en] ultralow, m4a_dash
600 webm  audio only      2 │    2.79MiB   35k https │ audio only          opus        35k 48k [en] ultralow, webm_dash
139 m4a   audio only      2 │    3.92MiB   49k https │ audio only          mp4a.40.5   49k 22k [en] low, m4a_dash
249 webm  audio only      2 │    4.08MiB   51k https │ audio only          opus        51k 48k [en] low, webm_dash
250 webm  audio only      2 │    5.10MiB   63k https │ audio only          opus        63k 48k [en] low, webm_dash
140 m4a   audio only      2 │   10.40MiB  129k https │ audio only          mp4a.40.2  129k 44k [en] medium, m4a_dash
251 webm  audio only      2 │    9.61MiB  120k https │ audio only          opus       120k 48k [en] medium, webm_dash
17  3gp   176x144      6  1 │    6.16MiB   77k https │ mp4v.20.3           mp4a.40.2       22k [en] 144p
597 mp4   256x144     13    │    2.57MiB   32k https │ avc1.4d400b     32k video only          144p, mp4_dash
602 mp4   256x144     13    │ ~  9.61MiB  117k m3u8  │ vp09.00.10.08  117k video only
598 webm  256x144     13    │    2.85MiB   35k https │ vp9             35k video only          144p, webm_dash
269 mp4   256x144     25    │ ~ 15.38MiB  187k m3u8  │ avc1.4D400C    187k video only
160 mp4   256x144     25    │    5.43MiB   68k https │ avc1.4D400C     68k video only          144p, mp4_dash
603 mp4   256x144     25    │ ~ 15.09MiB  183k m3u8  │ vp09.00.11.08  183k video only
278 webm  256x144     25    │    6.32MiB   79k https │ vp09.00.11.08   79k video only          144p, webm_dash
229 mp4   426x240     25    │ ~ 30.57MiB  372k m3u8  │ avc1.4D4015    372k video only
133 mp4   426x240     25    │   12.10MiB  151k https │ avc1.4D4015    151k video only          240p, mp4_dash
604 mp4   426x240     25    │ ~ 25.99MiB  316k m3u8  │ vp09.00.20.08  316k video only
242 webm  426x240     25    │   10.29MiB  128k https │ vp09.00.20.08  128k video only          240p, webm_dash
230 mp4   640x360     25    │ ~ 64.78MiB  787k m3u8  │ avc1.4D401E    787k video only
134 mp4   640x360     25    │   23.68MiB  295k https │ avc1.4D401E    295k video only          360p, mp4_dash
18  mp4   640x360     25  2 │   31.52MiB  392k https │ avc1.42001E         mp4a.40.2       44k [en] 360p
605 mp4   640x360     25    │ ~ 54.48MiB  662k m3u8  │ vp09.00.21.08  662k video only
243 webm  640x360     25    │   19.10MiB  238k https │ vp09.00.21.08  238k video only          360p, webm_dash
231 mp4   854x480     25    │ ~114.81MiB 1395k m3u8  │ avc1.4D401E   1395k video only
135 mp4   854x480     25    │   46.33MiB  577k https │ avc1.4D401E    577k video only          480p, mp4_dash
606 mp4   854x480     25    │ ~ 86.89MiB 1056k m3u8  │ vp09.00.30.08 1056k video only
244 webm  854x480     25    │   32.22MiB  401k https │ vp09.00.30.08  401k video only          480p, webm_dash
22  mp4   1280x720    25  2 │ ≈105.36MiB 1281k https │ avc1.64001F         mp4a.40.2       44k [en] 720p
232 mp4   1280x720    25    │ ~207.29MiB 2519k m3u8  │ avc1.64001F   2519k video only
136 mp4   1280x720    25    │   92.57MiB 1152k https │ avc1.64001F   1152k video only          720p, mp4_dash
609 mp4   1280x720    25    │ ~176.22MiB 2142k m3u8  │ vp09.00.31.08 2142k video only
247 webm  1280x720    25    │   64.40MiB  802k https │ vp09.00.31.08  802k video only          720p, webm_dash
270 mp4   1920x1080   25    │ ~436.50MiB 5305k m3u8  │ avc1.640028   5305k video only
137 mp4   1920x1080   25    │  188.88MiB 2351k https │ avc1.640028   2351k video only          1080p, mp4_dash
614 mp4   1920x1080   25    │ ~277.30MiB 3370k m3u8  │ vp09.00.40.08 3370k video only
248 webm  1920x1080   25    │  117.87MiB 1467k https │ vp09.00.40.08 1467k video only          1080p, webm_dash
616 mp4   1920x1080   25    │ ~468.61MiB 5696k m3u8  │ vp09.00.40.08 5696k video only          Premium
```

**Comment by bashonly** [comment] 2023-08-28 19:44
It's not premium-only, format 616 just hasn't finished processing yet. The 404 error happens with newly uploaded videos, and it is temporary.

Workarounds:
 - use `--check-formats` to have yt-dlp auto-select a working format when this happens (you'll need to run `yt-dlp --update-to nightly` first)
 - just wait longer
 
Duplicate of #7747

**Closed by bashonly** 2023-08-28 19:44 UTC
Labels: site-bug, triage
