### ISSUE TITLE
O'Reilly: Login Issue

### ISSUE THREAD

**Issue by declansmartwood** [yt-dlp/yt-dlp#7488] opened 2023-07-02 05:15 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

While attempting to download a course from O'Reilly Learning, yt-dlp throws an error during its login attempt. This seems like a redirect issue.

I have also attempted to use cookies without login credentials and with only a username provided. In the former case, yt-dlp will download truncated videos (1:00) - meaning O'Reilly does not recognize an authenticated session. In the latter case, the same error  is thrown. 

I can provide credentials, if necessary.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--proxy', '192.168.1.111:8118', '-u', 'PRIVATE', '-p', 'PRIVATE', '-o', './%(playlist_title)s/%(playlist_index)s_%(title)s.%(ext)s', 'https://learning.oreilly.com/videos/comptia-network-n10-008/9780137507450/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (zip)
[debug] Python 3.8.0 (CPython x86_64 64bit) - Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.27 (OpenSSL 1.1.1  11 Sep 2018, glibc 2.27)
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: Crypto-broken 2.6.1, certifi-2018.01.18, sqlite3-2.6.0
[debug] Proxy map: {'http': '192.168.1.111:8118', 'https': '192.168.1.111:8118'}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 924464eb831bdb99d854b9d47ff9e1c0870eab276113adaf8a74a8561ad332b9
yt-dlp is up to date (stable@2023.06.22)
[safari:course] Downloading login page
ERROR: 9780137507450: An extractor error has occurred. (caused by KeyError('next')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 705, in extract
    self.initialize()
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 611, in initialize
    self._perform_login(username, password)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/safari.py", line 41, in _perform_login
    'https://api.oreilly.com', qs['next'][0])
KeyError: 'next'
```

**Comment by bashonly** [comment] 2023-07-02 12:09
Duplicate of #3526

**Closed by bashonly** 2023-07-02 12:09 UTC
Labels: site-bug, triage
