### ISSUE TITLE
Failed to parse JSON on Mixcloud show

### ISSUE THREAD

**Issue by zesoft23** [yt-dlp/yt-dlp#8106] opened 2023-09-14 14:29 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States of America

### Provide a description that is worded well enough to be understood

I'm having some issues with using yt-dlp on a mixcloud show. It returns a JSON decoder error (see logs). Could it be something with their cloudflare server? I'm able to access this show ok when I use my browser! Let me know

The show: [https://www.mixcloud.com/8ballradio/invention-for-radio-41/](https://www.mixcloud.com/8ballradio/invention-for-radio-41/)

My command: `yt-dlp -vU https://www.mixcloud.com/8ballradio/invention-for-radio-41/`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.mixcloud.com/8ballradio/invention-for-radio-41/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-10-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.9 30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3-1 (setts), ffprobe 5.1.3-1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
[mixcloud] Extracting URL: https://www.mixcloud.com/8ballradio/invention-for-radio-41/
[mixcloud] 8ballradio_invention-for-radio-41: Downloading JSON metadata
ERROR: [mixcloud] None: 8ballradio_invention-for-radio-41: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/jack/scripts/yt-dl/ytenv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/scripts/yt-dl/ytenv/lib/python3.11/site-packages/yt_dlp/extractor/mixcloud.py", line 82, in _real_extract
    cloudcast = self._call_api('cloudcast', '''audioLength
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/scripts/yt-dl/ytenv/lib/python3.11/site-packages/yt_dlp/extractor/mixcloud.py", line 22, in _call_api
    return self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/scripts/yt-dl/ytenv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1064, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/scripts/yt-dl/ytenv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1034, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/scripts/yt-dl/ytenv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1024, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/scripts/yt-dl/ytenv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1011, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "/home/jack/scripts/yt-dl/ytenv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 994, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "/home/jack/scripts/yt-dl/ytenv/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 624, in decode
    return super().decode(s)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/scripts/yt-dl/ytenv/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1008, in _parse_json
    return json.loads(
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jack/scripts/yt-dl/ytenv/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 632, in decode
    raise type(e)(f'{e.msg} in {s[e.pos-10:e.pos+10]!r}', s, e.pos)
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by ApoorvShah111** [comment] 2023-09-14 15:12
I have tested it out with multiple different Mixcloud URLs and they all seem to be having the same error.

**Comment by bashonly** [comment] 2023-09-14 15:18
Duplicate of #8104

**Closed by bashonly** 2023-09-14 15:18 UTC
Labels: site-bug, triage
