### ISSUE TITLE
 [DouYin]Unable to download webpage: EOF occurred in violation of protocol (_ssl.c:1131) 

### ISSUE THREAD

**Issue by Topi9999** [yt-dlp/yt-dlp#10375] opened 2024-07-07 07:51 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

yt-dlp https://v.douyin.com/i6X7K8oS/
[generic] Extracting URL: https://v.douyin.com/i6X7K8oS/
[generic] i6X7K8oS: Downloading webpage
ERROR: [generic] Unable to download webpage: EOF occurred in violation of protocol (_ssl.c:1131) (caused by SSLError('EOF occurred in violation of protocol (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

can not download Douyin video
https://v.douyin.com/i6X7K8oS/        i sure can paly

-vu 

![image](https://github.com/yt-dlp/yt-dlp/assets/38421083/ff332804-865a-451f-8e86-e66b6cafb2c0)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://v.douyin.com/i6X7K8oS/']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n4.3.2-160-gfbb9368226, ffprobe 2022-04-07-git-607ecc27ed-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890', 'ftp': 'http://127.0.0.1:7890'}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.02 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.02 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://v.douyin.com/i6X7K8oS/
[generic] i6X7K8oS: Downloading webpage
ERROR: [generic] Unable to download webpage: EOF occurred in violation of protocol (_ssl.c:1131) (caused by SSLError('EOF occurred in violation of protocol (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\generic.py", line 2383, in _real_extract
  File "yt_dlp\extractor\common.py", line 909, in _request_webpage

  File "urllib3\connectionpool.py", line 775, in urlopen
  File "urllib3\connectionpool.py", line 1044, in _prepare_proxy
  File "urllib3\connection.py", line 652, in connect
  File "urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 449, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 775, in urlopen
  File "urllib3\connectionpool.py", line 1044, in _prepare_proxy
  File "urllib3\connection.py", line 652, in connect
  File "urllib3\connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
  File "urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\networking\_requests.py", line 324, in _send
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 711, in send
requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 896, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4161, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 337, in send
  File "yt_dlp\networking\_requests.py", line 342, in _send
yt_dlp.networking.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1131)
```

**Comment by Topi9999** [comment] 2024-07-07 07:54
when i close Network Wallbreaking。


[debug] Command-line config: ['-vU', 'https://v.douyin.com/i6X7K8oS/']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n4.3.2-160-gfbb9368226, ffprobe 2022-04-07-git-607ecc27ed-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.02 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.02 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://v.douyin.com/i6X7K8oS/
[generic] i6X7K8oS: Downloading webpage
[redirect] Following redirect to https://www.douyin.com/video/7387401979636649268?previous_page=app_code_link
[Douyin] Extracting URL: https://www.douyin.com/video/7387401979636649268?previous_page=app_code_link
[Douyin] 7387401979636649268: Downloading web detail JSON
WARNING: [Douyin] 7387401979636649268: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
ERROR: [Douyin] 7387401979636649268: Fresh cookies (not necessarily logged in) are needed
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\tiktok.py", line 1327, in _real_extract

**Comment by Topi9999** [comment] 2024-07-07 07:57
when i close Network Wallbreaking 


yt-dlp -vU https://v.douyin.com/i6X7K8oS/
[debug] Command-line config: ['-vU', 'https://v.douyin.com/i6X7K8oS/']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n4.3.2-160-gfbb9368226, ffprobe 2022-04-07-git-607ecc27ed-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.02 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.02 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://v.douyin.com/i6X7K8oS/
[generic] i6X7K8oS: Downloading webpage
[redirect] Following redirect to https://www.douyin.com/video/7387401979636649268?previous_page=app_code_link
[Douyin] Extracting URL: https://www.douyin.com/video/7387401979636649268?previous_page=app_code_link
[Douyin] 7387401979636649268: Downloading web detail JSON
WARNING: [Douyin] 7387401979636649268: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
ERROR: [Douyin] 7387401979636649268: Fresh cookies (not necessarily logged in) are needed
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\tiktok.py", line 1327, in _real_extract

**Comment by bashonly** [comment] 2024-07-07 14:50
the issue in the OP is a problem with your proxy, and the issue in the 2nd log is a duplicate of #9667

**Closed by bashonly** 2024-07-07 14:50 UTC
Labels: duplicate, site-bug, site:tiktok
