### ISSUE TITLE
paramount plus download corruption

### ISSUE THREAD

**Issue by leoy1234** [yt-dlp/yt-dlp#3759] opened 2022-05-16 15:51 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

for https://www.paramountplus.com/shows/video/DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A/
total video duration should be 23 min 9 s but yt-dlp only get 23 min 3 s. the video and subtitle are not sync in this case. 

With streamfab I can download a video with duration of 23 min 8 s and video match subtitle perfectly.

I've redownload this video for 100+ times. every time result with 23 min 3 s which cost video out of sync with subtitle.
I don't know if this is a duplicate of exist issue or not. But I did not found a solution for this.  
Thank you

### Verbose log

```shell
yt-dlp -v -N 16 --all-subs https://www.paramountplus.com/shows/video/DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A/
[debug] Command-line config: ['-v', '-N', '16', '--all-subs', 'https://www.paramountplus.com/shows/video/DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A/']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, err utf-8, pref cp936
[debug] yt-dlp version 2022.04.08 [7884ade] (win_dir)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 3.0.1 (needs_adtstoasc), ffprobe 3.0.1
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'https://127.0.0.1:7890', 'ftp': 'ftp://127.0.0.1:7890'}
[debug] [ParamountPlus] Extracting URL: https://www.paramountplus.com/shows/video/DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A/
[ParamountPlus] DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A: Downloading JSON metadata
[ParamountPlus] DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A: Downloading JSON metadata
[ParamountPlus] DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A: Downloading DASH_CENC_PRECON SMIL data
[ParamountPlus] DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en
[debug] Default format spec: bestvideo*+bestaudio/best
[info] DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A: Downloading 1 format(s): hls-3091
Deleting existing file Team Umizoomi - The Big Boat Race [DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A].en.vtt
[info] Writing video subtitles to: Team Umizoomi - The Big Boat Race [DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A].en.vtt
[debug] Invoking downloader on "https://cc.cbs.com/closedcaption/CBS_Production_Entertainment_VMS/329/450/DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A_1633737809860.vtt"
[debug] File locking is not supported on this platform. Proceeding without locking
[download] Destination: Team Umizoomi - The Big Boat Race [DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A].en.vtt
[download] 100% of 53.72KiB in 00:13
[debug] Invoking downloader on "https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2020/11/13/1819263043575/NICKELODEON_TEAMUMIZOOMI_101_365829_,2228,4628,3128,1628,848,503,000.mp4.csmil/index_2_av.m3u8?null=0&id=AgAtjp+XFzu+F6twgmJ3mtH15whJIGxoWaQO2iAbp22Utr8Ye8tD7rcsDuOnNDTvN5UNOzRsBHt5tg%3d%3d&hdntl=exp=1652802091~acl=%2fi%2ftemp_hd_gallery_video%2fCBS_Production_Outlet_VMS%2fvideo_robot%2fCBS_Production_Entertainment%2f2020%2f11%2f13%2f1819263043575%2fNICKELODEON_TEAMUMIZOOMI_101_365829_*~data=hdntl~hmac=4cea02ab287aac7ea2e048a960df0725662b80c6a2d08d0ce8986c94d0c34762"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 138
[download] Destination: Team Umizoomi - The Big Boat Race [DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A].mp4
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download]  81.1% of ~525.93MiB at  7.09MiB/s ETA 00:10 (frag 112/138)
[download] 100% of 528.47MiB in 00:55
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:Team Umizoomi - The Big Boat Race [DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Team Umizoomi - The Big Boat Race [DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Team Umizoomi - The Big Boat Race [DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:Team Umizoomi - The Big Boat Race [DIsddvlTR_yGUWS3QU_HzUqEUOyzr_3A].temp.mp4"
```

**Comment by larsenv** [comment] 2022-05-20 21:19
2022.05.18 seems to solve the problems I'm having with hashes being different for downloads. Maybe try that and see if it fixes it.

**Comment by larsenv** [comment] 2022-05-20 21:19
2022.05.18 seems to solve the problems I'm having with hashes being different for downloads. Maybe try that and see if it fixes it.

**Comment by larsenv** [comment] 2022-05-20 21:19
2022.05.18 seems to solve the problems I'm having with hashes being different for downloads. Maybe try that and see if it fixes it.

**Comment by larsenv** [comment] 2022-05-20 21:19
2022.05.18 seems to solve the problems I'm having with hashes being different for downloads. Maybe try that and see if it fixes it.

**Comment by larsenv** [comment] 2022-05-20 21:19
2022.05.18 seems to solve the problems I'm having with hashes being different for downloads. Maybe try that and see if it fixes it.

**Comment by larsenv** [comment] 2022-05-20 21:19
2022.05.18 seems to solve the problems I'm having with hashes being different for downloads. Maybe try that and see if it fixes it.

**Comment by larsenv** [comment] 2022-05-20 21:19
2022.05.18 seems to solve the problems I'm having with hashes being different for downloads. Maybe try that and see if it fixes it.

**Comment by larsenv** [comment] 2022-05-20 21:19
2022.05.18 seems to solve the problems I'm having with hashes being different for downloads. Maybe try that and see if it fixes it.

**Comment by larsenv** [comment] 2022-05-20 21:20
2022.05.18 seems to solve the problems I'm having with hashes being different for downloads. Maybe try that and see if it fixes it.

**Comment by larsenv** [comment] 2022-05-20 21:20
2022.05.18 seems to solve the problems I'm having with hashes being different for downloads. Maybe try that and see if it fixes it.

**Comment by larsenv** [comment] 2022-05-20 21:20
2022.05.18 seems to solve the problems I'm having with hashes being different for downloads. Maybe try that and see if it fixes it.

**Comment by lowprofileusername** [comment] 2022-05-21 00:44
Same here. with 2022.05.18 still no luck.you can try with the line I provided see of you can get file other than 23 min 3 s

**Comment by leoy1234** [comment] 2022-05-21 01:08
Same here. with 2022.05.18 still no luck.you can try with the line I provided see of you can get file other than 23 min 3 s

**Comment by BrendanoElTaco** [comment] 2022-05-22 01:36
This is actually a bug from the Paramount website and is not fixable with yt-dlp. However, there is a shell script that compares the video file with the video stream and determines if it is corrupted. It is extremely useful and will fix the issue 99% of the time. However, there are sometimes unfixable videos. Here is the [LINK](https://github.com/Grandfather-Paradox/paramount-dl). For windows, you run it in Cygwin with the bash paramount-dl command.

**Comment by pukkandan** [comment] 2022-05-22 09:47
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/898 ?

**Closed** 2022-05-22 09:48 UTC
Labels: external issue, site-bug
