### ISSUE TITLE
--download-archive filename: Allow exactly the same template fields as we have in --output filename?

### ISSUE THREAD

**Issue by schittli** [yt-dlp/yt-dlp#2431] opened 2022-01-21 18:44 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Good evening

### Situation description
If we use the great archive function `--download-archive` and we are downloading multiple files (e.g. audio and video separated) from YouTube channels, then we need to run yt-dlp multiple times and therefore, we have to use a separate archive file for each downloaded file type.

### Feature Request
Therefore it would be great if we could also generate the archive filename dynamically by template.

### Discussion suggestion
For the parameter `--output` there is already an ingenious concept for file name templates.
Therefore, it would be awesome if we could use the exact same templates as `--output` already supports: it would allow us to have yt-dlp automagically use the right archive file 😃 

#### A simple example would be:

For the audio file:
`yt-dlp -f "ba" -o "%(title)s BestAudio.%(ext)s" --download-archive "%(channel_id)s Audio-Archive.txt"`

For the video file:
`yt-dlp -f "bv" -o "%(title)s BestVideo.%(ext)s" --download-archive "%(channel_id)s Video-Archive.txt"`

Thanks a lot, kind regards,
Thomas

**Comment by pukkandan** [comment] 2022-01-21 20:43
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/953

**Closed by pukkandan** 2022-01-21 20:43 UTC
Labels: enhancement, triage

**Comment by afterdelight** [comment] 2022-05-15 12:06
pls add this

**Comment by pukkandan** [comment] 2022-05-15 12:10
@afterdelight DO NOT SPAM
