### ISSUE TITLE
NBC and Unable to extract post url

### ISSUE THREAD

**Issue by TenSai27** [yt-dlp/yt-dlp#3900] opened 2022-05-29 07:55 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Description

I am logged in correctly and I get this error 

ERROR: [NBC] 9000221348: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U 

### Verbose log

```shell
[debug] Command-line config: ['https://www.nbc.com/pasion-de-gavilanes/video/la-valentia-de-norma/9000221348?utm_campaign=tlmddotcom', '-vU', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--ap-mso', 'DTV']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [NBC] Extracting URL: https://www.nbc.com/pasion-de-gavilanes/video/la-valentia-de-norma/9000221348?utm_campaign=tlmddotcom
[NBC] 9000221348: Downloading JSON metadata
[NBC] 9000221348: Downloading JSON metadata
[NBC] 9000221348: Downloading Provider Redirect Page
[NBC] 9000221348: Downloading Provider Login Page
ERROR: [NBC] 9000221348: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 642, in extract
    if ie_result is None:
  File "yt_dlp\extractor\nbc.py", line 142, in _real_extract
    query['auth'] = self._extract_mvpd_auth(
  File "yt_dlp\extractor\adobepass.py", line 1713, in _extract_mvpd_auth
    mvpd_confirm_page_res = post_form(provider_login_page_res, 'Logging in', form_data)
  File "yt_dlp\extractor\adobepass.py", line 1393, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "yt_dlp\extractor\common.py", line 1235, in _html_search_regex
    if res:
  File "yt_dlp\extractor\common.py", line 1226, in _search_regex
    else:
```

**Comment by pukkandan** [comment] 2022-06-01 19:14
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2188

**Closed by pukkandan** 2022-06-01 19:14 UTC
Labels: site-bug, triage
