### ISSUE TITLE
No video formats found!

### ISSUE THREAD

**Issue by meby5** [yt-dlp/yt-dlp#6572] opened 2023-03-20 09:26 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

There is an issue with some of the video links from this particular website (www.sbs.com.au) where the video format cannot be determined from the m3u8 data extracted from the link, even though the video can be successfully played using a web browser.  Other videos from the same site can be downloaded okay, but there appears to be no difference with the URL provided for the individual videos, other than the unique number used for the video.  

For example the link https://www.sbs.com.au/ondemand/watch/2021697091880 can be downloaded successfully, but the link https://www.sbs.com.au/ondemand/watch/2176223299956 does not.

I am using version 2023.04.04 and checked for any recent updates.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Collecting video metadata...
Looking for thumbnail...
Generating output filename...
Generated command line:
C:\Users\Owner\.stacher/youtube-dl -f best --no-warnings --no-check-certificate --verbose -o S:\New\%(upload_date)s_%(title)s.%(ext)s https://www.sbs.com.au/ondemand/watch/2176223299956
Starting download...
[debug] Command-line config: ['-f', 'best', '--no-warnings', '--no-check-certificate', '--verbose', '-o', 'S:\\New\\%(upload_date)s_%(title)s.%(ext)s', 'https://www.sbs.com.au/ondemand/watch/2176223299956']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT) [debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k 25 Mar 2021)
[debug] exe versions: none [debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[SBS] Extracting URL: https://www.sbs.com.au/ondemand/watch/2176223299956 [SBS] 2176223299956: Downloading JSON metadata
[ThePlatform] Extracting URL: http://link.theplatform.com/s/Bgtm9B/m_ebYXn31zxt?feed=Video%20-%20Single&mbr=true&manifest=m3u&ord=3656496&policy=11929623&dfptag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.factual.sbs.com.au%2Fsec30htmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast2%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dpreroll%26ad_rule%3D0%26cmsid%3D531%26nofb%3D1%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F2176223299956%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D2176223299956&dfpmidtag=sz%3D530x298%26iu%3D%2F4117%2Fvideo.factual.sbs.com.au%2Fsec30midrollhtmlweb%26ciu_szs%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dxml_vast2%26unviewed_position_start%3D1%26url%3Dwww.sbs.com.au%26description_url%3DSBS%26cust_params%3Dtype%253Dmidroll%26ad_rule%3D0%26cmsid%3D531%26nofb%3D1%26url%3Dhttp%253A%252F%252Fwww.sbs.com.au%252Fondemand%252Fvideo%252Fsingle%252F2176223299956%26description_url%3DSBS%26correlator%3D--ORD--%26vid%3D2176223299956#__youtubedl_smuggle=%7B%22force_smil_url%22%3A+true%7D
[ThePlatform] m_ebYXn31zxt: Downloading SMIL data
[ThePlatform] m_ebYXn31zxt: Downloading m3u8 information
[ThePlatform] m_ebYXn31zxt: Downloading JSON metadata
ERROR: [ThePlatform] m_ebYXn31zxt: No video formats found!; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U
Traceback (most recent call last): File "yt_dlp\YoutubeDL.py", line 1518, in wrapper File "yt_dlp\YoutubeDL.py", line 1615, in __extract_info File "yt_dlp\YoutubeDL.py", line 1727, in process_ie_result File "yt_dlp\YoutubeDL.py", line 1674, in process_ie_result File "yt_dlp\YoutubeDL.py", line 2615, in process_video_result File "yt_dlp\YoutubeDL.py", line 1046, in raise_no_formats yt_dlp.utils.ExtractorError: [ThePlatform] m_ebYXn31zxt: No video formats found!; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U
```

**Comment by bashonly** [comment] 2023-03-20 10:52
Duplicate of #6543

**Closed by bashonly** 2023-03-20 10:52 UTC
Labels: duplicate, geo-blocked, site-bug
