### ISSUE TITLE
ERROR: C0T5h3xNSEJ: An extractor error has occurred. (caused by KeyError('config')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### ISSUE THREAD

**Issue by tunbyte** [yt-dlp/yt-dlp#9133] opened 2024-02-03 15:53 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Azerbaycan

### Provide a description that is worded well enough to be understood

```
import pathlib

from yt_dlp import YoutubeDL

VIDEO_EXTENSION = 'mp4'
class Instagram:
    def download_video(url, output_path):
        ydl_opts = {
            'quiet': True,
            'outtmpl': output_path + '/%(title)s.%(ext)s',
            'format': 'best[filesize<8MiB] / w',
            'postprocessors': [{
                'key': 'FFmpegVideoConvertor',
                'preferedformat': VIDEO_EXTENSION
            }],
        }
        with YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            info_video = dict(info)
            info_video['ext'] = VIDEO_EXTENSION
            return ydl.prepare_filename(info_video)


path_to_folder = str(pathlib.Path().resolve())
```
this code is provided by you and it works on my local machine when I run it just as it but when I add it to my telegram bot it doesn't work

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
i don't run it from command line it works well in command line my issue is it doesn't work with my telegram bot.it works well when I run the code in another file but not in my telegram bot
```

**Comment by bashonly** [comment] 2024-02-03 16:26
> i don't run it from command line it works well in command line my issue is it doesn't work with my telegram bot.

IG blocks data center IPs.

Though the specific error you are receiving looks like a duplicate of #7328 or else #4394

**Closed by bashonly** 2024-02-03 16:26 UTC
Labels: site-bug, triage

**Comment by tunbyte** [comment] 2024-02-03 16:47
```
from yt_dlp import YoutubeDL

import pathlib
import os

VIDEO_EXTENSION = 'mp4'
URL = 'https://www.instagram.com/reel/C2SkOJrsXO-/?utm_source=ig_web_copy_link'

def download_video(url, output_path):
    ydl_opts = {
        'quiet' : True,
        'outtmpl': output_path + '/%(title)s.%(ext)s',
        'format' : 'best[filesize<8MiB] / w',
        'postprocessors': [{
            'key': 'FFmpegVideoConvertor',
            'preferedformat': VIDEO_EXTENSION
        }]
    }
    with YoutubeDL(ydl_opts) as ydl:
        print('Starting download')
        info = ydl.extract_info(url, download=True)
        info_video = dict(info)
        info_video['ext'] = VIDEO_EXTENSION
        return ydl.prepare_filename(info_video)


path_to_folder = str(pathlib.Path().resolve())
video_name = download_video(URL, path_to_folder+"/videos")
video_size = (os.path.getsize(video_name) / 1024) / 1024

```
but why when I run just this code in another file it works?

**Comment by bashonly** [comment] 2024-02-03 17:07
show a verbose log or else I can't tell you anything

**Comment by Botato300** [comment] 2024-02-04 12:30
> IG blocks data center IPs

If I have a website that needs to download videos from Instagram, what do I do? do I use proxies?

**Comment by tunbyte** [comment] 2024-02-04 18:23
> show a verbose log or else I can't tell you anything

[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out None (No ANSI), error None (No ANSI), screen None (No ANSI)
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (pip) API
[debug] params: {'quiet': True, 'outtmpl': '/home/tunar/videos/%(title)s.%(ext)s', 'format': 'best[filesize<8MiB] / w', 'postprocessors': [{
'key': 'FFmpegVideoConvertor', 'preferedformat': 'mp4'}], 'username': '', 'password': '', 'verbose': True, 'compat_opts': se
t(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 S
afari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-
Mode': 'navigate'}}
[debug] Python 3.10.5 (CPython x86_64 64bit) - Linux-5.15.0-1044-aws-x86_64-with-glibc2.31 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.47.0, requests-2.31.0, sqlite3-3.31.1, urllib3-2.
2.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[Instagram] Downloading login webpage
ERROR: C0T5h3xNSEJ: An extractor error has occurred. (caused by KeyError('config')); please report this issue on  https://github.com/yt-dlp/
yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

im using my instagram username and password bcc when I use cookies it gives login error

**Comment by bashonly** [comment] 2024-02-04 19:06
> im using my instagram username and password

Then this is a dupe of #7328. Instagram login is broken.

> Linux-5.15.0-1044-aws

You are running this on cloud hosting. As I've already said, IG blocks data center IPs

> If I have a website that needs to download videos from Instagram, what do I do? do I use proxies?

Sure. This is not a yt-dlp problem though, this is a "your website" problem
