### ISSUE TITLE
un ignore able error

### ISSUE THREAD

**Issue by rubenh2905** [yt-dlp/yt-dlp#2103] opened 2021-12-24 08:07 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

WARNING: Falling back to normal extractor since lazy extractor YoutubeSearchIE does not have attribute _VALID_URL; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

what the fuck is this error ?
i use every single ignore args but no one can ignore this error and stop showing this.

yt-dlp.exe --get-url -f 251 ytsearch10:"2022 new year music list" + everything about ignoring 

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '--get-url', '-f', '251', 'ytsearch10:2022 new year music list']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_dir)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
WARNING: Falling back to normal extractor since lazy extractor YoutubeSearchIE does not have attribute _VALID_URL; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.[debug] [youtube:search] Extracting URL: ytsearch10:2022 new year music list
[download] Downloading playlist: 2022 new year music list
[youtube:search] query "2022 new year music list" page 1: Downloading API JSON
[youtube:search] playlist 2022 new year music list: Downloading 10 videos
[download] Downloading video 1 of 10
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=ueq3qDVvIZ4
[youtube] ueq3qDVvIZ4: Downloading webpage

ERROR: Interrupted by user
```

**Comment by MinePlayersPE** [comment] 2021-12-24 08:13
> [x] I've searched the bugtracker for similar issues including closed ones. DO NOT post duplicates

Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1851

**Comment by coletdjnz** [comment] 2021-12-24 08:18
Already fixed, will be in next release. Nothing to worry about, it still works afaik.

**Closed by coletdjnz** 2021-12-24 08:18 UTC
Labels: bug, triage
