### ISSUE TITLE
Facebook Privare group video download 

### ISSUE THREAD

**Issue by brcisna** [yt-dlp/yt-dlp#2545] opened 2022-01-30 15:27 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When trying to download a Facebook video from a private group(am a member)  download fails wanting username & password.
Adding cookies.txt does not fix the problem. tried the --user-agent switch ,,("supplying web browser info from whatsmyip "),this does not work
Can download fine from a friends videos on FB.  

Version 2022.01.22

### Verbose log

```shell
ERROR: [facebook] 1976102752646732: This video is only available for registered users. Use --cookies, --username and --password, or --netrc to provide account credentials
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/facebook.py", line 723, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/facebook.py", line 603, in _extract_from_url
    self.raise_login_required()
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1102, in raise_login_required
    raise ExtractorError(msg, expected=True)
```

**Comment by pukkandan** [comment] 2022-01-30 16:46
### Provide COMPLETE verbose output 

### Also make sure it is not A DUPLICATE of the already open facebook issues

> - [x] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates

**Closed by pukkandan** 2022-01-30 16:46 UTC
Labels: incomplete, site-bug, site:facebook
