### ISSUE TITLE
Cannot download webm due to unavailable format

### ISSUE THREAD

**Issue by scineram** [yt-dlp/yt-dlp#5989] opened 2023-01-07 20:55 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

On all tried Youtube videos yt-dlp is getting `Requested format is not available.` errors when requesting webm even when it is listed as available. At the same time original youtube-dl works (glacially of course). Such as https://www.youtube.com/watch?v=x1StEneaFqA

```
C:\Users\John\Downloads>yt-dlp.exe -F "https://www.youtube.com/watch?v=x1StEneaFqA"
[youtube] Extracting URL: https://www.youtube.com/watch?v=x1StEneaFqA
[youtube] x1StEneaFqA: Downloading webpage
[youtube] x1StEneaFqA: Downloading android player API JSON
[youtube] x1StEneaFqA: Downloading player e5f6cbd5
[info] Available formats for x1StEneaFqA:
ID  EXT   RESOLUTION FPS CH │   FILESIZE  TBR PROTO │ VCODEC       VBR ACODEC      ABR ASR MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0    │                 mhtml │ images                               storyboard
sb1 mhtml 80x45        0    │                 mhtml │ images                               storyboard
sb0 mhtml 160x90       0    │                 mhtml │ images                               storyboard
599 m4a   audio only      2 │    1.13MiB  31k https │ audio only       mp4a.40.5   31k 22k ultralow, m4a_dash
600 webm  audio only      2 │    1.18MiB  32k https │ audio only       opus        32k 48k ultralow, webm_dash
139 m4a   audio only      2 │    1.79MiB  49k https │ audio only       mp4a.40.5   49k 22k low, m4a_dash
249 webm  audio only      2 │    1.73MiB  47k https │ audio only       opus        47k 48k low, webm_dash
250 webm  audio only      2 │    2.30MiB  63k https │ audio only       opus        63k 48k low, webm_dash
140 m4a   audio only      2 │    4.75MiB 129k https │ audio only       mp4a.40.2  129k 44k medium, m4a_dash
251 webm  audio only      2 │    4.58MiB 125k https │ audio only       opus       125k 48k medium, webm_dash
17  3gp   176x144      7  1 │    1.84MiB  50k https │ mp4v.20.3    50k mp4a.40.2    0k 22k 144p
597 mp4   256x144     15    │  471.85KiB  13k https │ avc1.4d400b  13k video only          144p, mp4_dash
598 webm  256x144     15    │  716.03KiB  19k https │ vp9          19k video only          144p, webm_dash
160 mp4   256x144     30    │  528.88KiB  14k https │ avc1.4d400c  14k video only          144p, mp4_dash
278 webm  256x144     30    │  999.77KiB  27k https │ vp9          27k video only          144p, webm_dash
133 mp4   426x240     30    │  880.15KiB  23k https │ avc1.4d4015  23k video only          240p, mp4_dash
242 webm  426x240     30    │    1.35MiB  37k https │ vp9          37k video only          240p, webm_dash
134 mp4   640x360     30    │    1.39MiB  38k https │ avc1.4d401e  38k video only          360p, mp4_dash
18  mp4   640x360     30  2 │ ~  6.28MiB 167k https │ avc1.42001E 167k mp4a.40.2    0k 44k 360p
243 webm  640x360     30    │    3.20MiB  87k https │ vp9          87k video only          360p, webm_dash
135 mp4   854x480     30    │    2.00MiB  55k https │ avc1.4d401f  55k video only          480p, mp4_dash
244 webm  854x480     30    │    4.45MiB 121k https │ vp9         121k video only          480p, webm_dash
22  mp4   1280x720    30  2 │ ~  9.82MiB 261k https │ avc1.64001F 261k mp4a.40.2    0k 44k 720p
136 mp4   1280x720    30    │    4.84MiB 132k https │ avc1.4d401f 132k video only          720p, mp4_dash
247 webm  1280x720    30    │    8.37MiB 229k https │ vp9         229k video only          720p, webm_dash
298 mp4   1280x720    60    │    6.09MiB 166k https │ avc1.4d4020 166k video only          720p60, mp4_dash
302 webm  1280x720    60    │    9.92MiB 271k https │ vp9         271k video only          720p60, webm_dash
299 mp4   1920x1080   60    │   10.32MiB 282k https │ avc1.64002a 282k video only          1080p60, mp4_dash
303 webm  1920x1080   60    │   20.34MiB 555k https │ vp9         555k video only          1080p60, webm_dash
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\John\Downloads>yt-dlp.exe -vf webm "https://www.youtube.com/watch?v=x1StEneaFqA"
[debug] Command-line config: ['-vf', 'webm', 'https://www.youtube.com/watch?v=x1StEneaFqA']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=x1StEneaFqA
[youtube] x1StEneaFqA: Downloading webpage
[youtube] x1StEneaFqA: Downloading android player API JSON
[debug] [youtube] Extracting signature function js_e5f6cbd5_106
[debug] Loading youtube-sigfuncs.js_e5f6cbd5_106 from cache
[debug] Loading youtube-nsig.e5f6cbd5 from cache
[debug] [youtube] Decrypted nsig JJogh8AyKGwtfvI1V => evkkIeLX4aAWRA
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
ERROR: [youtube] x1StEneaFqA: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1599, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1658, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2736, in process_video_result
yt_dlp.utils.ExtractorError: [youtube] x1StEneaFqA: Requested format is not available. Use --list-formats for a list of available formats

C:\Users\John\Downloads>youtube-dl.exe -f webm "https://www.youtube.com/watch?v=x1StEneaFqA"
[youtube] x1StEneaFqA: Downloading webpage
[youtube] x1StEneaFqA: Downloading player e5f6cbd5
[download] Destination: 【ウマ娘】BLOW my GALE【パート分け_歌詞】【Full】-x1StEneaFqA.webm
[download] 100% of 20.34MiB in 06:35

C:\Users\John\Downloads>yt-dlp.exe -Uv
[debug] Command-line config: ['-Uv']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)

C:\Users\John\Downloads>youtube-dl.exe -Uv
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-Uv']
[debug] Encodings: locale cp1250, fs mbcs, out cp852, pref cp1250
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: none
[debug] Proxy map: {}
youtube-dl is up-to-date (2021.12.17)
```

**Comment by october262** [comment] 2023-01-07 21:52
try yt-dlp -f 303 "https://www.youtube.com/watch?v=x1StEneaFqA"

**Comment by bashonly** [comment] 2023-01-07 22:14
From the `yt-dlp` README:
>>> You can also use a file extension (currently 3gp, aac, flv, m4a, mp3, mp4, ogg, wav, webm are supported) to download the best quality format of a particular file extension served as a single file, e.g. `-f webm` will download the best quality format with the webm extension served as a single file.

The example URL you are using does not have a webm format available where video+audio are served as a single file. There are only separate video and audio formats that need to be merged. So if you use `-f webm`, yt-dlp will not find a suitable format to download.

This section of `youtube-dl`'s README is identical; however, the actual behavior of `youtube-dl` is different, and does not match its documentation.

`youtube-dl -f webm` does technically work on this youtube video, but it will download only a video-only webm format. It would be equivalent to using `-f 303`, like october262 said, or `-f "bestvideo[ext=webm]/best[ext=webm]"`. 
I am assuming this is a bug/unintended behavior in youtube-dl (cc: @dirkf). And I also assume you want audio to go along with the video.

`-S "ext:webm:webm"` is a more general option that you can use with yt-dlp that will prioritize webm formats, and it will download and merge formats that have separate video and audio tracks. It will also download non-webm formats if no webm formats are available. If you prefer to not download anything if no webm formats are available, then you can use `-f "(bv*+ba)[ext=webm]/b[ext=webm]"`

**Comment by dirkf** [comment] 2023-01-08 00:49
yt-dl looks for any format selector `s` in this list
```py
['mp4', 'flv', 'webm', '3gp', 'm4a', 'mp3', 'ogg', 'aac', 'wav']
```
and transforms such a format selector into (essentially) `-f [ext={s}]`.
>...I am assuming this is a bug/unintended behavior in youtube-dl ...

I think it's just an undocumented feature that was thought both "nice-to-have" and "trivially implemented". Ignoring the audio-only extensions in the list, the user is expected to know whether the selected file will contain video or audio+video.

Otherwise a different selector should be used, like `-f "bestvideo[ext=webm]+bestaudio/best[ext=webm]/best"`. In fact the Manual shows that for mp4:
```
              # Download best mp4 format available or any other best if no mp4 a
vailable
              $ youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'
```

**Comment by pukkandan** [comment] 2023-01-08 08:30
> into (essentially) `-f [ext={s}]`.

`[ext=s]` is same as `best[ext=s]` which is not what `-f s` is doing in youtube-dl.

Actually, due to the way format sorting works, youtube-dl's behavior is a bit complicated in this case. `-f s` is equivalent to `-f best[ext=s]/bestvideo[ext=s]/bestaudio[ext=s]`.

See below examples:

```
❯ youtube-dl test:youtube -F
[TestURL] Test URL: https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9
[youtube] BaW_jenozKc: Downloading webpage
[info] Available formats for BaW_jenozKc:
format code  extension  resolution note
249          webm       audio only tiny   48k , webm_dash container, opus @ 48k (48000Hz), 58.17KiB
250          webm       audio only tiny   63k , webm_dash container, opus @ 63k (48000Hz), 76.07KiB
251          webm       audio only tiny  115k , webm_dash container, opus @115k (48000Hz), 138.96KiB
140          m4a        audio only tiny  127k , m4a_dash container, mp4a.40.2@127k (44100Hz), 154.06KiB
278          webm       256x144    144p   43k , webm_dash container, vp9@  43k, 30fps, video only, 52.22KiB
160          mp4        256x144    144p  112k , mp4_dash container, avc1.4d400c@ 112k, 15fps, video only, 135.08KiB
242          webm       426x240    240p   27k , webm_dash container, vp9@  27k, 30fps, video only, 33.27KiB
133          mp4        426x240    240p  245k , mp4_dash container, avc1.4d4015@ 245k, 30fps, video only, 294.27KiB
243          webm       640x360    360p   62k , webm_dash container, vp9@  62k, 30fps, video only, 75.55KiB
134          mp4        640x360    360p  292k , mp4_dash container, avc1.4d401e@ 292k, 30fps, video only, 349.59KiB
244          webm       854x480    480p  137k , webm_dash container, vp9@ 137k, 30fps, video only, 165.49KiB
135          mp4        854x480    480p  710k , mp4_dash container, avc1.4d401f@ 710k, 30fps, video only, 849.41KiB
247          webm       1280x720   720p  420k , webm_dash container, vp9@ 420k, 30fps, video only, 504.68KiB
136          mp4        1280x720   720p 1365k , mp4_dash container, avc1.4d401f@1365k, 30fps, video only, 1.60MiB
248          webm       1920x1080  1080p  804k , webm_dash container, vp9@ 804k, 30fps, video only, 965.31KiB
137          mp4        1920x1080  1080p 1803k , mp4_dash container, avc1.640028@1803k, 30fps, video only, 2.11MiB
18           mp4        640x360    360p  420k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz)
22           mp4        1280x720   720p 1493k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)

❯ youtube-dl --get-format test:youtube -f mp4
22 - 1280x720 (720p)

❯ youtube-dl --get-format test:youtube -f best[ext=mp4]
22 - 1280x720 (720p)

❯ youtube-dl --get-format test:youtube -f bestvideo[ext=mp4]
137 - 1920x1080 (1080p)

❯ youtube-dl --get-format test:youtube -f webm
248 - 1920x1080 (1080p)

❯ youtube-dl --get-format test:youtube -f [ext=webm]
ERROR: requested format not available

❯ youtube-dl --get-format test:youtube -f bestvideo[ext=webm]
248 - 1920x1080 (1080p)
```

Whether this is a bug is up to interpretation, but if not, the documentation should be updated accordingly imo.

**Comment by dirkf** [comment] 2023-01-08 14:57
Currently the disagreement is that case 4 `-f webm` gives an error while yt-dl finds format 248. There is no combined webm format and ...

> ... Arguably [yt-dl] should be trying for -f best[ext={s}] instead.

This is easy to arrange by applying the logic in the `selector_function()` from the best/worst/None case, which I think we all feel is what a user would expect, or at least not what a user wouldn't expect.

Then (in fact, reusing the same code) there is no disagreement on this set of test cases:
```diff
--- old/youtube_dl/YoutubeDL.py
+++ new/youtube_dl/YoutubeDL.py
@@ -1298,24 +1298,32 @@
                 format_spec = selector.selector
 
                 def selector_function(ctx):
+
+                    def best_worst(fmts, fs='best'):
+                        format_idx = 0 if fs == 'worst' else -1
+                        audiovideo_formats = [
+                            f for f in fmts
+                            if f.get('vcodec') != 'none' and f.get('acodec') != 'none']
+                        if audiovideo_formats:
+                            return audiovideo_formats[format_idx]
+                        # for extractors with incomplete formats (audio only (soundcloud)
+                        # or video only (imgur)) we will fallback to best/worst
+                        # {video,audio}-only format
+                        elif ctx['incomplete_formats']:
+                            return fmts[format_idx]
+
                     formats = list(ctx['formats'])
                     if not formats:
                         return
                     if format_spec == 'all':
                         for f in formats:
                             yield f
+
                     elif format_spec in ['best', 'worst', None]:
-                        format_idx = 0 if format_spec == 'worst' else -1
-                        audiovideo_formats = [
-                            f for f in formats
-                            if f.get('vcodec') != 'none' and f.get('acodec') != 'none']
-                        if audiovideo_formats:
-                            yield audiovideo_formats[format_idx]
-                        # for extractors with incomplete formats (audio only (soundcloud)
-                        # or video only (imgur)) we will fallback to best/worst
-                        # {video,audio}-only format
-                        elif ctx['incomplete_formats']:
-                            yield formats[format_idx]
+                        f = best_worst(formats, format_spec)
+                        if f:
+                            yield f
+
                     elif format_spec == 'bestaudio':
                         audio_formats = [
                             f for f in formats
@@ -1346,9 +1354,9 @@
                             filter_f = lambda f: f['ext'] == format_spec
                         else:
                             filter_f = lambda f: f['format_id'] == format_spec
-                        matches = list(filter(filter_f, formats))
-                        if matches:
-                            yield matches[-1]
+                        f = best_worst(filter(filter_f, formats))
+                        if f:
+                            yield f
             elif selector.type == MERGE:
                 def _merge(formats_info):
                     format_1, format_2 = [f['format_id'] for f in formats_info]
```
And:
```shellsession
$ for fmt in mp4 'best[ext=mp4]' 'bestvideo[ext=mp4]' webm '[ext=webm]' 'bestvideo[ext=webm]'; do echo -n "${fmt}: "; python3.9 -m youtube_dl --get-format -f "$fmt" test:youtube; done
mp4: 22 - 1280x720 (720p)
best[ext=mp4]: 22 - 1280x720 (720p)
bestvideo[ext=mp4]: 137 - 1920x1080 (1080p)
webm: ERROR: requested format not available
[ext=webm]: ERROR: requested format not available
bestvideo[ext=webm]: 248 - 1920x1080 (1080p)
$
``` 
If I commit that it should save yt-dlp from adding a compat option, but it doesn't help OP who should be using a format selection similar to that [suggested above](https://github.com/yt-dlp/yt-dlp/issues/5989#issuecomment-1374673284).

**Comment by scineram** [comment] 2023-01-09 08:05
Thanks for all the comments. My understanding has improved.

To be honest my original attempt was `-f webm,m4a -x` which only gave me the `m4a` version. I found that weird and then tried splitting the formats. So there still seems to be some inconsistency in how yt-dlp handles the selection. Because `-f m4a` DOES work and is byte identical to `-f m4a -x` even though like webm there is no combined file in that format. So yt-dlp seems to handel m4a the same way youtube-dl handles webm. Should that be changed in the code?

Going forward I will indeed standardize on `-f ba[ext=webm],ba[ext=m4a] -x` for my usecase.

**Comment by Owez** [comment] 2023-01-13 17:58
> ```python
> ['mp4', 'flv', 'webm', '3gp', 'm4a', 'mp3', 'ogg', 'aac', 'wav']
> ```

@dirkf Do you know if `.mp4`, `.flv`, `.webm`, and `.3gp` are the only final video file formats a yt-dlp download can result in? Sorry to butt in, this issue is the only place I could find with this info

**Comment by pukkandan** [comment] 2023-01-13 18:02
@Owez Assuming no post processing options, it can only be mp4, webm, mkv and 3gp for YouTube. From other sites, it can be any format depending on what the site provides.


If you have further questions, open new issue - don't ask on unrelated ones...

**Closed** 2023-03-25 09:48 UTC
Labels: bug, triage, regression
