### ISSUE TITLE
Facebook Cannot parse data

### ISSUE THREAD

**Issue by mharvey500** [yt-dlp/yt-dlp#7982] opened 2023-08-28 23:33 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

Error message trying to download audio from facebook video.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'bestaudio[ext=m4a]', '--no-playlist', 'https://www.facebook.com/torontocbc/videos/3476238815976753/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.28.213404 [b9f2bc2db] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.08.28.213404, Current version: nightly@2023.08.28.213404
Current Build Hash: b6830ed434df2c619770901ff1da5210fcbd0774769ec5fd6af788236e60ddd3
yt-dlp is up to date (nightly@2023.08.28.213404)
[facebook] Extracting URL: https://www.facebook.com/torontocbc/videos/3476238815976753/
[facebook] 3476238815976753: Downloading webpage
[facebook] 3476238815976753: Downloading webpage
ERROR: [facebook] 3476238815976753: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\facebook.py", line 733, in _real_extract
  File "yt_dlp\extractor\facebook.py", line 680, in _extract_from_url
```

**Comment by bashonly** [comment] 2023-08-28 23:57
Duplicate of #7901

**Closed by bashonly** 2023-08-28 23:57 UTC
Labels: duplicate, site-bug, site:facebook

**Comment by mharvey500** [comment] 2023-08-29 01:31
Sorry for posting duplicate. I was under the impression the fixes were already in the latest build but apparently they are not.Sent from my Galaxy
-------- Original message --------From: bashonly ***@***.***> Date: 2023-08-28  7:57 p.m.  (GMT-05:00) To: yt-dlp/yt-dlp ***@***.***> Cc: mharvey500 ***@***.***>, Author ***@***.***> Subject: Re: [yt-dlp/yt-dlp] Facebook Cannot parse data (Issue #7982) 
Duplicate of #7901

**Comment by sebma** [comment] 2023-09-14 17:33
#4311
