### ISSUE TITLE
Multiple videos on one website, howto get second video?

### ISSUE THREAD

**Issue by MuenchenSued** [yt-dlp/yt-dlp#3456] opened 2022-04-17 08:31 UTC
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

On the website https://tele5.de/mediathek/quatermain-und-der-schatz-des-koenig-salomon-teil-1-2/ two videos are provided but yt-yt-dlp only load the first of them. How will I get the second video?

### Verbose log

```shell
./yt-dlp -v https://tele5.de/mediathek/quatermain-und-der-schatz-des-koenig-salomon-teil-1-2/
[debug] Command-line config: ['-v', 'https://tele5.de/mediathek/quatermain-und-der-schatz-des-koenig-salomon-teil-1-2/']
[debug] User config "/home/user/.config/yt-dlp/config": ['--restrict-filenames', '--no-mtime', '--compat-options', 'filename', '--no-progress', '--console-title']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Compatibility options: filename
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-107-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: certifi, Crypto, secretstorage, sqlite
[debug] Proxy map: {}
[debug] Using fake IP 53.65.110.41 (DE) as X-Forwarded-For
[debug] [Tele5] Extracting URL: https://tele5.de/mediathek/quatermain-und-der-schatz-des-koenig-salomon-teil-1-2/
[Tele5] quatermain-und-der-schatz-des-koenig-salomon-teil-1-2: Downloading webpage
[Tele5] 2116636: Downloading token
[Tele5] 2116636: Downloading JSON metadata
[Tele5] 2116636: Downloading JSON metadata
[Tele5] 2116636: Downloading MPD manifest
[Tele5] 2116636: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2116636: Downloading 1 format(s): hls-6454+dash-995756510
```

**Comment by pukkandan** [comment] 2022-04-17 08:52
Duplicate of #3051

**Closed by pukkandan** 2022-04-17 08:52 UTC
Labels: question
