### ISSUE TITLE
tiktok download seams broken on some cases with non-ascii characters

### ISSUE THREAD

**Issue by estatistics** [yt-dlp/yt-dlp#8534] opened 2023-11-05 20:18 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

greece

### Provide a description that is worded well enough to be understood

both produce same results 
Note that in some chinese characters using "restrict filenames workt as well by limiting characters" but not here. 
yt-dlp -v https://www.tiktok.com/@www.tiktok.comdrbw
yt-dlp -v -o "%(uploader).30B - %(title).60B.%(ext)s" https://www.tiktok.com/@www.tiktok.comdrbw

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', 'https://www.tiktok.com/@www.tiktok.comdrbw']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (zip)
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux-6.1.0-9-amd64-x86_64-with-glibc2.36 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3-1 (setts), ffprobe 5.1.3-1, rtmpdump 2.4
[debug] Optional libraries: brotli-None, certifi-2022.09.14, sqlite3-3.41.2, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:user] Extracting URL: https://www.tiktok.com/@www.tiktok.comdrbw
[tiktok:user] www.tiktok.comdrbw: Downloading webpage
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (1/3)...
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (2/3)...
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying (3/3)...
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:user] www.tiktok.comdrbw: Downloading user video list page 1
ERROR: [tiktok:user] www.tiktok.comdrbw: www.tiktok.comdrbw: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/tiktok.py", line 806, in _real_extract
    thumbnail = traverse_obj(videos, (0, 'author', 'avatar_larger', 'url_list', 0))
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/traversal.py", line 239, in traverse_obj
    result = _traverse_obj(obj, path, index == len(paths), True)
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/traversal.py", line 227, in _traverse_obj
    results, has_branched, is_dict = apply_path(obj, path, test_type)
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/traversal.py", line 215, in apply_path
    branching, results = apply_key(key, obj, last)
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/traversal.py", line 173, in apply_key
    result = obj[key]
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 2195, in __getitem__
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/tiktok.py", line 774, in _video_entries_api
    for retry in self.RetryManager():
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 5114, in __iter__
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 3760, in _error_or_warning
    RetryManager.report_retry(
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 5122, in report_retry
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/tiktok.py", line 776, in _video_entries_api
    post_list = self._call_api(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/tiktok.py", line 132, in _call_api
    raise e
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/tiktok.py", line 125, in _call_api
    res = self._call_api_impl(ep, real_query, manifest_app_version, video_id, fatal, note, errnote)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/tiktok.py", line 62, in _call_api_impl
    return self._download_json(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1069, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1039, in download_handle
    return parse(self, content, video_id, transform_source=transform_source, fatal=fatal, errnote=errnote), urlh
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1029, in parse
    return getattr(ie, parser)(content, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1016, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 999, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 555, in decode
  File "/home/eros/anaconda3/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/eros/anaconda3/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1013, in _parse_json
    return json.loads(
  File "/home/eros/anaconda3/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/local/bin/yt-dlp/yt_dlp/utils/_utils.py", line 563, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by bashonly** [comment] 2023-11-05 22:52
Nope, extractor is just broken, like the warning said

Duplicate of #3776

could try https://github.com/bashonly/yt-dlp-TTUser

**Closed by bashonly** 2023-11-05 22:52 UTC
Labels: duplicate, site-bug, site:tiktok
