### ISSUE TITLE
ERROR: [Globo]: Unable to download JSON metadata: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by lucascrds** [yt-dlp/yt-dlp#9540] opened 2024-03-26 16:46 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

Hello,

I've been encountering an issue with yt-dlp`when trying to download videos from Globo. Until about a week ago, everything was functioning correctly. However, now I receive the following error message:

ERROR: [Globo] 4198581: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>

The error persists despite ensuring the URL is correct and trying various suggested troubleshooting steps, such as updating yt-dlp, using different flags, and providing cookies for authentication. The content is still available online and can be accessed directly through a web browser.

Any assistance or guidance on this matter would be greatly appreciated, as the ability to download these videos is crucial for my usage. Thank you in advance for your help!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'mp4', '--autonumber-start', '1', '-o', 'C:\\Users\\lucas\\Videos\\downloads-dlp\\[ILP]_%(autonumber)03d.%(ext)s', '--downloader', 'aria2c', '-u', 'PRIVATE', '-p', 'PRIVATE', '--cookies-from-browser', 'firefox', '--batch-file', 'C:\\Users\\lucas\\Desktop\\downloads2\\lista_videos.txt']
[debug] User config "C:\Users\lucas\AppData\Roaming\yt-dlp\config.txt": []
[debug] Batch file urls: ['https://globoplay.globo.com/v/4171702', 'https://globoplay.globo.com/v/4174464', 'https://globoplay.globo.com/v/4179545', 'https://globoplay.globo.com/v/4182240', 'https://globoplay.globo.com/v/4185144', 'https://globoplay.globo.com/v/4187037', 'https://globoplay.globo.com/v/4190351', 'https://globoplay.globo.com/v/4193055', 'https://globoplay.globo.com/v/4195810', 'https://globoplay.globo.com/v/4198581']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.03.22.232703 from yt-dlp/yt-dlp-nightly-builds [e5d4f1110] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-02-22-git-d5cc7acff1-full_build-www.gyan.dev (setts), ffprobe 2023-02-22-git-d5cc7acff1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\lucas\AppData\Roaming\Mozilla\Firefox\Profiles\fhqg19kv.default-release\cookies.sqlite"
Extracted 174 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1807 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.03.22.232703 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.03.22.232703 from yt-dlp/yt-dlp-nightly-builds)
[Globo] Extracting URL: https://globoplay.globo.com/v/4171702
[Globo] 4171702: Getting cookies
[Globo] 4171702: Downloading JSON metadata
[Globo] 4171702: Downloading security hash for 4171702
ERROR: [Globo] 4171702: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\globo.py", line 99, in _real_extract
  File "yt_dlp\extractor\common.py", line 1086, in download_content
  File "yt_dlp\extractor\common.py", line 1050, in download_handle
  File "yt_dlp\extractor\common.py", line 920, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 877, in _request_webpage

  File "yt_dlp\extractor\common.py", line 864, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4128, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 335, in send
  File "yt_dlp\networking\_requests.py", line 350, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

[Globo] Extracting URL: https://globoplay.globo.com/v/4174464
[Globo] 4174464: Getting cookies
[Globo] 4174464: Downloading JSON metadata
[Globo] 4174464: Downloading security hash for 4174464
ERROR: [Globo] 4174464: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\globo.py", line 99, in _real_extract
  File "yt_dlp\extractor\common.py", line 1086, in download_content
  File "yt_dlp\extractor\common.py", line 1050, in download_handle
  File "yt_dlp\extractor\common.py", line 920, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 877, in _request_webpage

  File "yt_dlp\extractor\common.py", line 864, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4128, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 335, in send
  File "yt_dlp\networking\_requests.py", line 350, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

[Globo] Extracting URL: https://globoplay.globo.com/v/4179545
[Globo] 4179545: Getting cookies
[Globo] 4179545: Downloading JSON metadata
[Globo] 4179545: Downloading security hash for 4179545
ERROR: [Globo] 4179545: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\globo.py", line 99, in _real_extract
  File "yt_dlp\extractor\common.py", line 1086, in download_content
  File "yt_dlp\extractor\common.py", line 1050, in download_handle
  File "yt_dlp\extractor\common.py", line 920, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 877, in _request_webpage

  File "yt_dlp\extractor\common.py", line 864, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4128, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 335, in send
  File "yt_dlp\networking\_requests.py", line 350, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

[Globo] Extracting URL: https://globoplay.globo.com/v/4182240
[Globo] 4182240: Getting cookies
[Globo] 4182240: Downloading JSON metadata
[Globo] 4182240: Downloading security hash for 4182240
ERROR: [Globo] 4182240: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\globo.py", line 99, in _real_extract
  File "yt_dlp\extractor\common.py", line 1086, in download_content
  File "yt_dlp\extractor\common.py", line 1050, in download_handle
  File "yt_dlp\extractor\common.py", line 920, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 877, in _request_webpage

  File "yt_dlp\extractor\common.py", line 864, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4128, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 335, in send
  File "yt_dlp\networking\_requests.py", line 350, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

[Globo] Extracting URL: https://globoplay.globo.com/v/4185144
[Globo] 4185144: Getting cookies
[Globo] 4185144: Downloading JSON metadata
[Globo] 4185144: Downloading security hash for 4185144
ERROR: [Globo] 4185144: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\globo.py", line 99, in _real_extract
  File "yt_dlp\extractor\common.py", line 1086, in download_content
  File "yt_dlp\extractor\common.py", line 1050, in download_handle
  File "yt_dlp\extractor\common.py", line 920, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 877, in _request_webpage

  File "yt_dlp\extractor\common.py", line 864, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4128, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 335, in send
  File "yt_dlp\networking\_requests.py", line 350, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

[Globo] Extracting URL: https://globoplay.globo.com/v/4187037
[Globo] 4187037: Getting cookies
[Globo] 4187037: Downloading JSON metadata
[Globo] 4187037: Downloading security hash for 4187037
ERROR: [Globo] 4187037: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\globo.py", line 99, in _real_extract
  File "yt_dlp\extractor\common.py", line 1086, in download_content
  File "yt_dlp\extractor\common.py", line 1050, in download_handle
  File "yt_dlp\extractor\common.py", line 920, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 877, in _request_webpage

  File "yt_dlp\extractor\common.py", line 864, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4128, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 335, in send
  File "yt_dlp\networking\_requests.py", line 350, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

[Globo] Extracting URL: https://globoplay.globo.com/v/4190351
[Globo] 4190351: Getting cookies
[Globo] 4190351: Downloading JSON metadata
[Globo] 4190351: Downloading security hash for 4190351
ERROR: [Globo] 4190351: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\globo.py", line 99, in _real_extract
  File "yt_dlp\extractor\common.py", line 1086, in download_content
  File "yt_dlp\extractor\common.py", line 1050, in download_handle
  File "yt_dlp\extractor\common.py", line 920, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 877, in _request_webpage

  File "yt_dlp\extractor\common.py", line 864, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4128, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 335, in send
  File "yt_dlp\networking\_requests.py", line 350, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

[Globo] Extracting URL: https://globoplay.globo.com/v/4193055
[Globo] 4193055: Getting cookies
[Globo] 4193055: Downloading JSON metadata
[Globo] 4193055: Downloading security hash for 4193055
ERROR: [Globo] 4193055: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\globo.py", line 99, in _real_extract
  File "yt_dlp\extractor\common.py", line 1086, in download_content
  File "yt_dlp\extractor\common.py", line 1050, in download_handle
  File "yt_dlp\extractor\common.py", line 920, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 877, in _request_webpage

  File "yt_dlp\extractor\common.py", line 864, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4128, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 335, in send
  File "yt_dlp\networking\_requests.py", line 350, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

[Globo] Extracting URL: https://globoplay.globo.com/v/4195810
[Globo] 4195810: Getting cookies
[Globo] 4195810: Downloading JSON metadata
[Globo] 4195810: Downloading security hash for 4195810
ERROR: [Globo] 4195810: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\globo.py", line 99, in _real_extract
  File "yt_dlp\extractor\common.py", line 1086, in download_content
  File "yt_dlp\extractor\common.py", line 1050, in download_handle
  File "yt_dlp\extractor\common.py", line 920, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 877, in _request_webpage

  File "yt_dlp\extractor\common.py", line 864, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4128, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 335, in send
  File "yt_dlp\networking\_requests.py", line 350, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found

[Globo] Extracting URL: https://globoplay.globo.com/v/4198581
[Globo] 4198581: Getting cookies
[Globo] 4198581: Downloading JSON metadata
[Globo] 4198581: Downloading security hash for 4198581
ERROR: [Globo] 4198581: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "yt_dlp\extractor\common.py", line 732, in extract
  File "yt_dlp\extractor\globo.py", line 99, in _real_extract
  File "yt_dlp\extractor\common.py", line 1086, in download_content
  File "yt_dlp\extractor\common.py", line 1050, in download_handle
  File "yt_dlp\extractor\common.py", line 920, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 877, in _request_webpage

  File "yt_dlp\extractor\common.py", line 864, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4128, in urlopen
  File "yt_dlp\networking\common.py", line 115, in send
  File "yt_dlp\networking\_helper.py", line 204, in wrapper
  File "yt_dlp\networking\common.py", line 335, in send
  File "yt_dlp\networking\_requests.py", line 350, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found
```

**Comment by bashonly** [comment] 2024-03-26 16:48
Duplicate of #9512

**Closed by bashonly** 2024-03-26 16:48 UTC
Labels: site-bug, triage
