### ISSUE TITLE
Getting an error message on TubiTV.com downloads

### ISSUE THREAD

**Issue by h4ckrn00b** [yt-dlp/yt-dlp#8098] opened 2023-09-13 04:45 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

If i run the following command:
 .\yt-dlp -vU https://tubitv.com/movies/584759/termination

gets me the error message:
JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)"));

How do I fix that?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\Programs\codecs\FFMpeg> .\yt-dlp -vU https://tubitv.com/movies/584759/termination
[debug] Command-line config: ['-vU', 'https://tubitv.com/movies/584759/termination']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-49757-g969039e (needs_adtstoasc), ffprobe 4.0
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
yt-dlp is up to date (stable@2023.07.06)
[debug] Using fake IP 6.221.54.106 (US) as X-Forwarded-For
[TubiTv] Extracting URL: https://tubitv.com/movies/584759/termination
[TubiTv] 584759: Downloading JSON metadata
ERROR: [TubiTv] 584759: 584759: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 710, in extract
  File "yt_dlp\extractor\tubitv.py", line 85, in _real_extract
  File "yt_dlp\extractor\common.py", line 1064, in download_content
  File "yt_dlp\extractor\common.py", line 1034, in download_handle
  File "yt_dlp\extractor\common.py", line 1024, in parse
  File "yt_dlp\extractor\common.py", line 1011, in _parse_json
  File "yt_dlp\extractor\common.py", line 994, in __print_error

  File "yt_dlp\utils\_utils.py", line 624, in decode
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1008, in _parse_json
  File "json\__init__.py", line 370, in loads
  File "yt_dlp\utils\_utils.py", line 632, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by bashonly** [comment] 2023-09-13 04:49
This looks like a duplicate of #8018

Note that tubitv is geo-restricted

I cannot reproduce the issue from a US IP
```shell
$ yt-dlp -F "https://tubitv.com/movies/584759/termination"
[TubiTv] Extracting URL: https://tubitv.com/movies/584759/termination
[TubiTv] 584759: Downloading JSON metadata
[TubiTv] 584759: Downloading MPD manifest
[TubiTv] 584759: Downloading m3u8 information
[TubiTv] 584759: Downloading m3u8 information
[info] Available formats for 584759:
ID                                 EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hlsv6-default-audio-group-stream_0 mp4 audio only │                  m3u8  │ audio only        unknown             [en] stream_0
dash-1                             m4a audio only │ ~ 83.07MiB  133k https │ audio only        mp4a.40.2  133k 44k [en] DASH audio, m4a_dash
hlsv6-467                          mp4 640x360    │ ~292.95MiB  468k m3u8  │ avc1.4d401e  468k video only
dash-3                             mp4 640x360    │ ~414.16MiB  661k https │ avc1.4d401e  661k video only          DASH video, mp4_dash
hlsv3-512                          mp4 640x360    │ ~320.62MiB  512k m3u8  │ avc1.4D401E       mp4a.40.2
hlsv6-1295                         mp4 854x480    │ ~811.45MiB 1296k m3u8  │ avc1.640028 1296k video only
dash-4                             mp4 854x480    │ ~854.89MiB 1365k https │ avc1.640028 1365k video only          DASH video, mp4_dash
hlsv3-1358                         mp4 854x480    │ ~850.41MiB 1358k m3u8  │ avc1.640028       mp4a.40.2
hlsv6-2442                         mp4 1280x720   │ ~  1.49GiB 2443k m3u8  │ avc1.640028 2443k video only
dash-8                             mp4 1280x720   │ ~  1.63GiB 2661k https │ avc1.640028 2661k video only          DASH video, mp4_dash
hlsv3-2530                         mp4 1280x720   │ ~  1.55GiB 2530k m3u8  │ avc1.640028       mp4a.40.2
```

**Closed** 2023-09-13 04:54 UTC
Labels: duplicate, geo-blocked, site-bug

**Comment by gamer191** [comment] 2023-09-14 06:41
> * I've checked that all provided URLs are playable in a browser with the same IP and same login details

really? Are you using a VPN by any chance?
