### ISSUE TITLE
-x and --split-chapters no longer work together

### ISSUE THREAD

**Issue by RomanSedykh** [yt-dlp/yt-dlp#10278] opened 2024-06-27 11:46 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

-x and --split-chapters no longer work together. It gives me "Postprocessing: Conversion failed!". Any of those options alone works well. I am tried to use both regular ffmpeg and provided in the yt-dlp github page.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-Uv', '-x', '--split-chapters', 'https://www.youtube.com/watch?v=b1Fo_M_tj6w']
[debug] User config "C:\Users\Roman\AppData\Roaming\yt-dlp\config": ['--ppa', "ThumbnailsConvertor+ffmpeg_o:-c:v png -vf crop='ih'", '--path', 'C:/Users/Roman/Videos', '--output', '%(uploader)s/%(playlist_title)s/%(upload_date)s %(title)s.%(ext)s', '--restrict-filenames', '--embed-thumbnail', '--embed-metadata', '--ffmpeg-location', 'C:/Users/Roman/AppData/Local/Programs/yt-dlp']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.06.27.000217 from yt-dlp/yt-dlp-master-builds [0953209a8] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116017-ge61fed8280-20240626 (setts), ffprobe N-116017-ge61fed8280-20240626
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.06.27.000217 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.06.27.000217 from yt-dlp/yt-dlp-master-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=b1Fo_M_tj6w
[youtube] b1Fo_M_tj6w: Downloading webpage
[youtube] b1Fo_M_tj6w: Downloading ios player API JSON
[debug] Loading youtube-nsig.a95aa57a from cache
[debug] [youtube] Decrypted nsig fxLG87dNKGHtp6Qm => ZXTBe1Bnu7zVqA
[debug] Loading youtube-nsig.a95aa57a from cache
[debug] [youtube] Decrypted nsig 7jZREcI9AtBgOzZS => uD0QiR9SUXmLNQ
[youtube] b1Fo_M_tj6w: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] b1Fo_M_tj6w: Downloading 1 format(s): 251
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.webp
[debug] Invoking http downloader on "https://rr1---sn-hxb54vo-bvws.googlevideo.com/videoplayback?expire=1719510338&ei=4lB9ZoyOOpOc0u8Ph52muA8&ip=178.178.197.137&id=o-ANJNFk4TmoTC3NfZE_QT76Equ3G85SFAWMB36GrysCKf&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=Mp&mm=31%2C29&mn=sn-hxb54vo-bvws%2Csn-n8v7znz7&ms=au%2Crdu&mv=m&mvi=1&pl=23&initcwndbps=587500&bui=AbKP-1PJWcYAnjGx12am1ggCksvId50tXZ6_vtNapaHy1Is1G6H7eLJU2Gi7uiGaeHPO0r3YsY5hsiXy&spc=UWF9f1s2zIwBSjSLRtIcs1S1nwfUWv5vgCpQ3W-zrRZEi-DE33MstHHPtnA2&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=cbXd83AhkGMlin_lEJyxmv4Q&rqh=1&gir=yes&clen=1420018&dur=79.421&lmt=1708723266167367&mt=1719488229&fvip=2&keepalive=yes&c=WEB&sefc=1&txp=4532434&n=uD0QiR9SUXmLNQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgQ38LGAp03MJUUvOzDCiGNqBtxUnN3VXp6KxU-uxCeDQCIQDI4RnX4W8ZOHXm1F_WfdesmBnQQFRoc1NetrD-a9x6uA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIhAKvUgcebPXOEjl07DVp3aFx5zj2Orp7aiC5G3E5JB7sMAiAd9gcJwUA45Qfy1NQJA_nSFsqHNoo-k6gnea4aRi8ruw%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.webm
[download] 100% of    1.35MiB in 00:00:00 at 1.69MiB/s
[debug] ffmpeg command line: C:/Users/Roman/AppData/Local/Programs/yt-dlp\ffprobe -show_streams "file:C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.webm"
[ExtractAudio] Destination: C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.opus
[debug] ffmpeg command line: C:/Users/Roman/AppData/Local/Programs/yt-dlp\ffmpeg -y -loglevel repeat+info -i "file:C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.webm" -vn -acodec copy -movflags +faststart "file:C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.opus"
Deleting original file C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.webm (pass -k to keep)
[Metadata] Adding metadata to "C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.opus"
[debug] ffmpeg command line: C:/Users/Roman/AppData/Local/Programs/yt-dlp\ffmpeg -y -loglevel repeat+info -i "file:C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.opus" -i "file:C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.meta" -map 0 -dn -ignore_unknown -c copy -map_metadata 1 -write_id3v1 1 -metadata "title=How to Add Chapters to Your Videos Using Timestamps" -metadata "date=20200616" -metadata "description=Have you ever spent time trying to find an exact moment in a video? Look no further! We’re introducing Video Chapters on Desktop, Android and iOS, which allows you to jump forward to a specific section of a video, rewatch a portion of a video, and more. Chapters appear at the bottom of the video player and use timestamps from the creator's video description.  Note: chapters are only shown on videos if the creator has included them.

Chapters:
0:00 An intro to video chapters
0:23 How to set up video chapters
1:07 See video chapters in action

Learn more about video chapters here: https://support.google.com/youtube/thread/49733199

Subscribe and hit the bell to see new videos: https://goo.gl/So4XIG

► Check out our Help Center: https://goo.gl/fBzr7" -metadata "synopsis=Have you ever spent time trying to find an exact moment in a video? Look no further! We’re introducing Video Chapters on Desktop, Android and iOS, which allows you to jump forward to a specific section of a video, rewatch a portion of a video, and more. Chapters appear at the bottom of the video player and use timestamps from the creator's video description.  Note: chapters are only shown on videos if the creator has included them.

Chapters:
0:00 An intro to video chapters
0:23 How to set up video chapters
1:07 See video chapters in action

Learn more about video chapters here: https://support.google.com/youtube/thread/49733199

Subscribe and hit the bell to see new videos: https://goo.gl/So4XIG

► Check out our Help Center: https://goo.gl/fBzr7" -metadata "purl=https://www.youtube.com/watch?v=b1Fo_M_tj6w" -metadata "comment=https://www.youtube.com/watch?v=b1Fo_M_tj6w" -metadata "artist=YouTube Creators" -metadata:s:0 "language=eng" -movflags +faststart "file:C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.temp.opus"
[ThumbnailsConvertor] Converting thumbnail "C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.webp" to png
[debug] ffmpeg command line: C:/Users/Roman/AppData/Local/Programs/yt-dlp\ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i "file:C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.webp" -update 1 -movflags +faststart -c:v png -vf "crop=ih" "file:C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.png"
[EmbedThumbnail] mutagen: Adding thumbnail to "C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.opus"
[debug] ffmpeg command line: C:/Users/Roman/AppData/Local/Programs/yt-dlp\ffmpeg -y -loglevel repeat+info -i "file:C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.png"
[SplitChapters] Splitting video by chapters; 3 chapters found
[SplitChapters] Chapter 001; Destination: C:\Users\Roman\Videos\How_to_Add_Chapters_to_Your_Videos_Using_Timestamps-001-An_intro_to_video_chapters-[b1Fo_M_tj6w].opus
[debug] ffmpeg command line: C:/Users/Roman/AppData/Local/Programs/yt-dlp\ffmpeg -y -loglevel repeat+info -ss 0.0 -t 23.0 -i "file:C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.opus" -map 0 -dn -ignore_unknown -c copy -movflags +faststart "file:C:\Users\Roman\Videos\How_to_Add_Chapters_to_Your_Videos_Using_Timestamps-001-An_intro_to_video_chapters-[b1Fo_M_tj6w].opus"
[debug] ffmpeg version N-116017-ge61fed8280-20240626 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 14.1.0 (crosstool-NG 1.26.0.93_a87bf7f)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-libxml2 --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-libdvdread --enable-libdvdnav --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs=-lgomp --extra-ldflags=-pthread --extra-ldexeflags= --cc=x86_64-w64-mingw32-gcc --cxx=x86_64-w64-mingw32-g++ --ar=x86_64-w64-mingw32-gcc-ar --ranlib=x86_64-w64-mingw32-gcc-ranlib --nm=x86_64-w64-mingw32-gcc-nm --extra-version=20240626
  libavutil      59. 26.100 / 59. 26.100
  libavcodec     61.  8.100 / 61.  8.100
  libavformat    61.  4.100 / 61.  4.100
  libavdevice    61.  2.100 / 61.  2.100
  libavfilter    10.  2.102 / 10.  2.102
  libswscale      8.  2.100 /  8.  2.100
  libswresample   5.  2.100 /  5.  2.100
  libpostproc    58.  2.100 / 58.  2.100
[ogg @ 000001dc34b5fb40] 2425 bytes of comment header remain
Input #0, ogg, from 'file:C:\Users\Roman\Videos\YouTube_Creators\NA\20200616 How_to_Add_Chapters_to_Your_Videos_Using_Timestamps.opus':
  Duration: 00:01:19.42, start: 0.000000, bitrate: 164 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 23.000000
      Metadata:
        title           : An intro to video chapters
    Chapter #0:1: start 23.000000, end 67.000000
      Metadata:
        title           : How to set up video chapters
    Chapter #0:2: start 67.000000, end 79.420000
      Metadata:
        title           : See video chapters in action
  Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
      Metadata:
        encoder         : Lavf61.4.100
        title           : How to Add Chapters to Your Videos Using Timestamps
        date            : 20200616
        purl            : https://www.youtube.com/watch?v=b1Fo_M_tj6w
        synopsis        : Have you ever spent time trying to find an exact moment in a video? Look no further! We’re introducing Video Chapters on Desktop, Android and iOS, which allows you to jump forward to a specific section of a video, rewatch a portion of a video, and more.
                        :
                        : Chapters:
                        : 0:00 An intro to video chapters
                        : 0:23 How to set up video chapters
                        : 1:07 See video chapters in action
                        :
                        : Learn more about video chapters here: https://support.google.com/youtube/thread/49733199
                        :
                        : Subscribe and hit the bell to see new videos: https://goo.gl/So4XIG
                        :
                        : ► Check out our Help Center: https://goo.gl/fBzr7
        comment         : https://www.youtube.com/watch?v=b1Fo_M_tj6w
        artist          : YouTube Creators
  Stream #0:1: Video: png, rgb24(pc, gbr/unknown/unknown), 720x720, 90k tbr, 90k tbn (attached pic)
      Metadata:
        comment         : Cover (front)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
[opus @ 000001dc34b631c0] Unsupported codec id in stream 1
[out#0/opus @ 000001dc34b35d80] Could not write header (incorrect codec parameters ?): Invalid argument
Conversion failed!

ERROR: Postprocessing: Conversion failed!
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3537, in process_info
  File "yt_dlp\YoutubeDL.py", line 3719, in post_process
  File "yt_dlp\YoutubeDL.py", line 3701, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3679, in run_pp
  File "yt_dlp\postprocessor\common.py", line 23, in run
  File "yt_dlp\postprocessor\common.py", line 128, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 1065, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 367, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

**Comment by RomanSedykh** [comment] 2024-06-27 11:52
I found that it looks like the issue with --embed-thumbnail option. Without it everything works alright.

**Comment by bashonly** [comment] 2024-06-27 13:48
Duplicate of #6225

**Closed by bashonly** 2024-06-27 13:48 UTC
Labels: site-bug, triage
