### ISSUE TITLE
Can't download password-protected Vimeo link / [vimeo] Unable to download JSON metadata: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by BoredinBerlin** [yt-dlp/yt-dlp#6603] opened 2023-03-22 18:48 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

Simple Vimeo link, passworded, ang getting a Bad Request JSON error. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://vimeo.com/669743367/40c9ad2582', '--video-password', 'PRIVATE', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - macOS-13.1-x86_64-i386-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[vimeo] Extracting URL: https://vimeo.com/669743367/40c9ad2582
[vimeo] 669743367: Downloading JSON metadata
[vimeo] 669743367: Downloading JSON metadata
ERROR: [vimeo] 669743367: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/vimeo.py", line 825, in _real_extract
    return self._extract_from_api(video_id, unlisted_hash)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/vimeo.py", line 756, in _extract_from_api
    video = self._download_json(
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1048, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1012, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 882, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 839, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 821, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3742, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by bashonly** [comment] 2023-03-22 19:08
Possible workarounds:
 * Try removing the last part of the URL: `https://vimeo.com/669743367`
 * Use this URL `https://player.vimeo.com/video/669743367?h=40c9ad2582` and pass the `--referer`
 
 I can reproduce the issue with the password-protected youtube-dl video if I add its unlisted hash to the URL:
 ```
 $ yt-dlp --video-password "youtube-dl" "https://vimeo.com/68375962/264643868c"
[vimeo] Extracting URL: https://vimeo.com/68375962/264643868c
[vimeo] 68375962: Downloading JSON metadata
[vimeo] 68375962: Downloading JSON metadata
ERROR: [vimeo] 68375962: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```
The problem is that If the URL is in the form of `https://vimeo.com/{id}/{unlisted_hash}`, the extractor does not do anything with the video password, it jumps right into trying to extract the video from the API

**Comment by BoredinBerlin** [comment] 2023-03-22 20:30
That did it! Much thanks! 

If I run into the problem in the future, is there an easy way to find the unlisted hash?

**Comment by bashonly** [comment] 2023-03-22 22:17
> That did it!

out of curiosity, which workaround worked for you?

> If I run into the problem in the future, is there an easy way to find the unlisted hash?

in this URL, `https://vimeo.com/669743367/40c9ad2582`, the unlisted hash is `40c9ad2582`
the suggested workarounds either removed it or converted the URL into a `player.vimeo.com` URL

**Comment by StefanLobbenmeier** [comment] 2024-04-20 13:11
Hope it is okay to comment on this one year old thread, but I had a look at this today and noticed, that in principle we could also authenticate via cookie. There is a session cookie set with the key 12345678_password (number censored, not sure if it is sensitive). Using that cookie should enable downloading vimeo videos where the browser is already authenticated.

But I noticed that session cookies are currently filtered out. I went into that rabbit hole and found out they are incorrectly marked as expired. Will check if I can fix this.

**Comment by pukkandan** [comment] 2024-04-20 17:11
> Hope it is okay to comment on this one year old thread

Open issues are never too old to comment on

**Comment by yesilcimenahmet** [comment] 2024-05-16 11:47
Please fix this error!

**Comment by SasaniP** [comment] 2024-05-16 15:00
Hi I am currently having this issue and I have tried @BoredinBerlin's exact code, but the issue still persists. 

my code
`!yt-dlp "https://vimeo.com/942547573" --referer "https://player.vimeo.com/video/942547573?h=password-here" --video-password _hidden_`

The error
`[vimeo] Extracting URL: https://vimeo.com/942547573
[vimeo] 942547573: Downloading webpage
[vimeo] 942547573: Downloading JSON metadata
[vimeo] 942547573: Downloading JSON metadata
ERROR: [vimeo] 942547573: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)`

**Comment by yesilcimenahmet** [comment] 2024-05-16 18:32
this is not working please fix this. Before it was working like 1 month ago but I dont know what happened I am using latest version of yt-dlp

**Comment by yesilcimenahmet** [comment] 2024-05-16 18:54
get cookies from chrome is not working, when it try to copy session folder it fails, when I run with -disable-features=LockProfileCookieDatabase vimeo.com does not allow me to enter site! My video is private and I know the password. So none of your suggestions are working.

**Comment by yesilcimenahmet** [comment] 2024-05-16 19:05
I installed plugin and solved! Thanks.

**Comment by SasaniP** [comment] 2024-05-16 19:13
> I installed plugin and solved! Thanks.

Can you please elaborate so I can try the same method ?

**Comment by yesilcimenahmet** [comment] 2024-05-16 19:29
**1)** Download nightly build via https://github.com/yt-dlp/yt-dlp-nightly-builds/releases

**2)** Download ChromeCookieUnlock plugin ZIP via https://github.com/seproDev/yt-dlp-ChromeCookieUnlock/releases/tag/v2024.04.29

**3)** Create a folder called yt-dlp-plugins in the directory where yt-dlp.exe is located. Copy the yt-dlp-ChromeCookieUnlock folder into this folder.

**4)** Open the chrome browser and go the video link enter your password on the web site, after then run the below commands.

**5)** yt-dlp  "https://vimeo.com/xxxxx" --video-password "password" --cookies-from-browser chrome


**PS: sometimes it can fail, go to the page again, refresh and enter the password, play the video for a second or two and run the script.**

**Comment by eweinhold** [comment] 2024-05-17 09:16
the nightly build 2024.05.16.232713 fixes that Vimeo password thing completely for me :) *THANKS*

yt-dlp_macos --video-password PASSWORD --restrict-filenames 'https://vimeo.com/902571486'

works now like before!

**Comment by bashonly** [comment] 2024-05-17 14:06
yt-dlp nightly works because it has a `--cookies-from-browser` improvement that collects session cookies from chrome/chromium; there have been no changes to the Vimeo extractor since before the last stable release. If you are not using `--cookies-from-browser`, then there is no effectively no difference between nightly and stable when it comes to Vimeo extraction

**Comment by bashonly** [comment] 2024-06-07 14:58
See #10127 for more examples and some analysis

**Comment by ThomVivet** [comment] 2024-06-26 20:53
Using alternate URL worked fine for me:
`yt-dlp https://player.vimeo.com/video/xxx --video-password xxx`
(instead of simple URL: `yt-dlp https://vimeo.com/xxx --video-password xxx`)

**Comment by ilmarilahti** [comment] 2024-07-02 11:06
Back in spring a couple months ago (can't remember exactly when, sorry) I had this issue, but interestingly, it was solved by itself – one day trying to download the exact same video as before just worked, and I am certain yt-dlp had not been updated. However, for the past week or two the problem has returned. Updating to Homebrew's 2024.7.1 version only changed the error message from the usual JSON metadata error to
`WARNING: [vimeo] The extractor is attempting impersonation, but no impersonate target is available; if you encounter errors, then see  https://github.com/yt-dlp/yt-dlp#impersonation  for information on installing the required dependencies`
I tried installing yt-dlp via pip to make sure curl_cffi was included, that didn't help. Neither did dumping cookies from Firefox or using --cookies-from-browser with it. Maybe Vimeo is doing some kind of [enshittification](https://en.wikipedia.org/wiki/Enshittification) A/B testing with this?

**Comment by bashonly** [comment] 2024-07-02 15:16
@ilmarilahti Vimeo is using TLS fingerprinting to block requests that do not have the fingerprint of a web browser. See #10325. The warning given by yt-dlp is actually unrelated to the HTTP Error 400, though (there's unfortunately no way to know in advance that a Vimeo video is password-protected).

Some users have reported success with using the equivalent `player.vimeo.com/video/` URL for the password-protected video. Otherwise, exporting vimeo.com cookies and passing them with `--cookies` should work, as long as you've entered the video password in your current browser session.

**Comment by ilmarilahti** [comment] 2024-07-02 15:51
@bashonly thanks for the comment and clarification, I forgot to add those details in my message. I did try the URL variations as mentioned above, it didn't help. And like I said, --cookies didn't help. The video is password protected but it was known to me since it's private content I've paid for.

Looking at the other ticket you linked to I learned about the --impersonate parameter (the error message about TLS fingerprinting only pointed to the install page so I assumed it was in use automatically), and after several attempts it seems it works with the combination of --impersonate chrome and the cookies also being dumped from Chrome (not FF as before).

...though after 27% downloaded of ~200MB, python crashes 😅 repeatedly:
```
Python(18005,0x1f1dd8c00) malloc: *** error for object 0x600001b7f7a0: pointer being freed was not allocated
Python(18005,0x1f1dd8c00) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Comment by bashonly** [comment] 2024-07-02 16:02
The crashes are coming from trying to download a large media file with curl_cffi, which is used as the file downloader's request handler when you pass `--impersonate`. So don't pass it: If you have curl_cffi installed, you don't need to pass `--impersonate`. Impersonation is built-in to the extractor now (hence the warning you get when curl_cffi isn't installed).

**Comment by ilmarilahti** [comment] 2024-07-02 16:18
Thanks, that cleared it up! So it is now working with the normal stable version and using cookies dumped from Chrome with --cookies, I didn't realize before that cookies from other browsers won't work (because of the fingerprinting?). And like you said the password has to have been set in the current session, so if Vimeo shows the video without asking for password (getting it from some cache other than cookies apparently), have to wipe Vimeo cache and try again before dumping cookies.

**Comment by bashonly** [comment] 2024-07-02 16:36
> I didn't realize before that cookies from other browsers won't work (because of the fingerprinting?).

Vimeo is using cloudflare fingerprinting for `vimeo.com` URLs, which could be user-agent dependent. But it also could be that the relevant session cookie isn't being exported from Firefox. You'd need to compare the cookiefile dumps to see.

Session cookies aren't written to the same location on disk as regular cookies, and they are supposed to be wiped every time you restart the browser (though Chrome doesn't actually do this ~~because Google wants to rewrite the rules of the internet in its own image~~).

**Comment by brightghost** [comment] 2024-07-03 04:29
Same issue here, FWIW none of the tricks with alternate URLs worked for me (doesn't seem the "unlisted_hash" is a relevant detail any longer as my URL does not have one) but was able to use the Chrome cookies workaround, after installing Chrome on my worker system which I am loathe to do. 

Not sure why the session cookies being wiped after each session in other browsers would be an issue so long as the cookie exists in my current session? Presumably the Cloudflare fingerprinting they are using supports other browsers as well, as the web page works in them.

I did just now try exporting vimeo.com cookies from Firefox and it has an entry which looks like the hashed password for the video in question (`229435366` is the ID):

    .vimeo.com	TRUE	/	TRUE	0	229435366_password	47db19e933e804a70f624044dad4db7ea7e8eaac.1719976691

...but curiously, Chrome has the same cookie with a different hash:

    .vimeo.com	TRUE	/	TRUE	0	229435366_password	c4989aa0b4eb6f0ae2873658ec85f5b06f6b0907.1719979148

**Comment by SasaniP** [comment] 2024-07-03 08:53
> Using alternate URL worked fine for me: `yt-dlp https://player.vimeo.com/video/xxx --video-password xxx` (instead of simple URL: `yt-dlp https://vimeo.com/xxx --video-password xxx`)

I have tried this work-around and now face a different issue.

```
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.07.01 from yt-dlp/yt-dlp [5ce582448] (pip) API
[debug] params: {'videopassword': 'B4U_Television_282', 'verbose': True, 'format': 'bestvideo+bestaudio', 'referer': 'https://vimeo.com', 'external_downloader': 'aria2c', 'external_downloader_args': ['-x', '16', '-s', '16', '-k', '5M', '--max-concurrent-downloads=16'], 'outtmpl': '/Users/sasanisulakshi/Desktop/vimeo_videos/%(title)s (%(format_id)s).%(ext)s', 'writeinfojson': True, 'nooverwrites': True, 'tempdir': '/var/folders/m7/n7p88dkn4wj496yhzls19tv40000gp/T', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.10.11 (CPython arm64 64bit) - macOS-14.4.1-arm64-arm-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 6.1.1-tessus (setts)
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
Video Downloading in best quality
[vimeo] Extracting URL: http://player.vimeo.com/video/954682288
[vimeo] 954682288: Downloading webpage
[debug] Loaded 1831 extractors
ERROR: [vimeo] 954682288: Cannot download embed-only video without embedding URL. Please call yt-dlp with the URL of the page that embeds this video.
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py", line 843, in _real_extract
    raise ExtractorError(

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 4161, in urlopen
    return self._request_director.send(req)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/_requests.py", line 361, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py", line 835, in _real_extract
    webpage, urlh = self._download_webpage_handle(
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1757, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py", line 843, in _real_extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [vimeo] 954682288: Cannot download embed-only video without embedding URL. Please call yt-dlp with the URL of the page that embeds this video.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/downloader.py", line 45, in vimeo_download
    result = ydl_worst.download([url])
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3603, in download
    self.__download_wrapper(self.extract_info)(
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3578, in wrapper
    res = func(*args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1611, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1640, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1088, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1027, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [vimeo] 954682288: Cannot download embed-only video without embedding URL. Please call yt-dlp with the URL of the page that embeds this video.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 4161, in urlopen
    return self._request_director.send(req)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/networking/_requests.py", line 361, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py", line 835, in _real_extract
    webpage, urlh = self._download_webpage_handle(
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)
yt_dlp.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1757, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py", line 843, in _real_extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [vimeo] 954682288: Cannot download embed-only video without embedding URL. Please call yt-dlp with the URL of the page that embeds this video.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/downloader.py", line 66, in <module>
    vimeo_download(vimeo_link_password)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/downloader.py", line 51, in vimeo_download
    result = ydl_best.download([url])
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3603, in download
    self.__download_wrapper(self.extract_info)(
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3578, in wrapper
    res = func(*args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1611, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1640, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1088, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/Users/sasanisulakshi/PycharmProjects/vimeo-download/.venv/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1027, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [vimeo] 954682288: Cannot download embed-only video without embedding URL. Please call yt-dlp with the URL of the page that embeds this video.

Process finished with exit code 1
```

**Comment by bashonly** [comment] 2024-07-03 14:20
https://github.com/yt-dlp/yt-dlp/pull/10341 should fix this, if anyone wants to try it

**Comment by ilmarilahti** [comment] 2024-07-03 14:52
@bashonly I can confirm that #10341 fixed it for me at least, the previous videos now download nicely without gimmicks. Thank you for your efforts!

**Closed** 2024-07-05 18:32 UTC
Labels: site-bug, site:vimeo

**Comment by kendalldita** [comment] 2024-08-26 08:36
I finally got an error message saying that it could be my VPN, after trying suggestions here, and that was the case. Disconnecting from Proton VPN allowed the original URL to be used to download the video.
