### ISSUE TITLE
Mixcloud problem with specific link from python program

### ISSUE THREAD

**Issue by jimger** [yt-dlp/yt-dlp#2900] opened 2022-02-26 14:20 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom - Globally

### Description

I am using yt-dlp as part of bigger python program.
I have a very specific issuw with this link

```py
orig_link = "https://www.mixcloud.com/Marios_Dionellis/%CE%BC%CE%AE%CF%80%CF%89%CF%82-%CE%B7-%CE%B3%CE%B9%CE%B1%CE%B3%CE%B9%CE%AC-%CE%BA%CE%B1%CE%B9-%CE%BF-%CF%80%CE%B1%CF%80%CF%80%CE%BF%CF%8D%CF%82-%CE%BC%CE%B1%CF%82-%CF%80%CE%B5%CF%81%CE%B9%CF%83%CF%83%CE%B5%CF%8D%CE%BF%CF%85%CE%BD-%CF%80%CE%AF%CF%83%CF%89-%CF%83%CE%B5%CE%BB%CE%AF%CE%B4%CE%B5%CF%82-%CE%B4%CE%B5%CF%85%CF%84%CE%AD%CF%81%CE%B1-14-%CF%86%CE%B5%CE%B2%CF%81%CE%BF%CF%85%CE%B1%CF%81%CE%AF%CE%BF%CF%85-2022/"

 ydl_opts = {'simulate': not download,
                'forcetitle': True,
                'forceduration': True,
                'forceurl': True,
                'forcedescription': True,
                'nocheckcertificate': True,
                'outtmpl': "temp.%(ext)s",
                'timestamp': True
                }

 with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.download([orig_link])
                info_dict = ydl.extract_info(orig_link, download=False)
```

The code is used for quite sometime. That's the only link I have issue. I don't know how to get verbose log as I don't have any issue from command line but only from within python.

I am pasting the tracecode. I think it is easy to reproduce it. youtube-dl the original doesn't have any problem with this.

### Verbose log

```shell
ydl.download([orig_link])
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 3212, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 3185, in wrapper
    res = func(*args, **kwargs)
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1372, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1465, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 2516, in process_video_result
    info_dict, _ = self.pre_process(info_dict)
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 3329, in pre_process
    info = self.run_all_pps(key, info)
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 3321, in run_all_pps
    self._forceprint(key, info)
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 2704, in _forceprint
    info_copy['formats_table'] = self.render_formats_table(info_dict)
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 3477, in render_formats_table
    delim = self._format_screen('\u2502', self.Styles.DELIM, '|', test_encoding=True)
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 900, in _format_screen
    return self._format_text(
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 892, in _format_text
    text = text.encode(encoding, 'ignore').decode(encoding)
TypeError: encode() argument 'encoding' must be str, not None
```

**Comment by pukkandan** [comment] 2022-02-27 14:58
>  I don't know how to get verbose log

Add `'verbose': True` to the opts

**Comment by pukkandan** [comment] 2022-03-01 06:35
possible duplicate of #2711

**Comment by jimger** [comment] 2022-03-01 14:27
ydl = yt_dlp.YoutubeDL(ydl_opts)
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 654, in __init__
    self.print_debug_header()
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 3574, in print_debug_header
    get_encoding(self._screen_file), get_encoding(self._err_file),
  File "C:\Python3\lib\site-packages\yt_dlp\YoutubeDL.py", line 3568, in get_encoding
    ret += ' (No VT)' if WINDOWS_VT_MODE is False else ' (No ANSI)'
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'

**Comment by jimger** [comment] 2022-03-01 14:35
> possible duplicate of #2711

I have read that now that u posted it. I tried to put at the ydl_options but still no good...

**Comment by pukkandan** [comment] 2022-03-04 14:49
Please check if the issue still exists in master

**Comment by jimger** [comment] 2022-03-04 16:53
> Please check if the issue still exists in master

Yeap, master solves it. I assume it will be merged to releases with the next version? Is there a way to move back to releases after it has been merged?

**Comment by pukkandan** [comment] 2022-03-04 19:57
> I assume it will be merged to releases with the next version?

Yes

> Is there a way to move back to releases after it has been merged?

i dont understand what u mean

**Closed** 2022-03-04 19:57 UTC
Labels: bug, incomplete
