### ISSUE TITLE
[twitch] "amemiyanazuna/videos?filter=all" now reports 100 videos instead of 117 after update from 2023.11.16

### ISSUE THREAD

**Issue by helpimnotdrowning** [yt-dlp/yt-dlp#8964] opened 2024-01-09 09:23 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I updated yt-dlp from `2023.11.16` to `2023.12.30` and nightly due to "Unable to download JSON metadata" errors (which I now think is just rate limiting since I forgot) a few hours ago. Since then, yt-dlp only reports 100 VODs instead of the 117 it was just before. However, downgrading yt-dlp does not fix this.

117 is also the amount of visible broadcasts (100 exact, [filter:past broadcasts](https://www.twitch.tv/amemiyanazuna/videos?filter=archives)) and highlights (17, [filter:highlights](https://www.twitch.tv/amemiyanazuna/videos?filter=highlights)), which make up all the VODs on the channel that I can see and know about. This is not about the sub-only VODs, since there are only 13 of them and I have an active sub.

Curiously, I looked over my terminal logs, and since I have a custom prompt I was able to see that all runs before midnight PST returned 117 VODs. Afterwards, it was only 100 VODs. API change?
![image](https://github.com/yt-dlp/yt-dlp/assets/35247379/46b4ce55-749b-45a9-abb4-d175c0111e4e)
![image](https://github.com/yt-dlp/yt-dlp/assets/35247379/2c854aae-4980-4610-aea2-13fd77a07730)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
AFTER DOWNGRADING BACK TO 2023.11.16:

[debug] Command-line config: ['--downloader', 'aria2c', '--downloader-args', '--continue --max-concurrent-downloads=10 --max-connection-per-server=10 --split=10 --min-split-size=5M', '--force-ipv4', '--keep-video', '--cookies', '/mnt/W/ytdl/cookies.txt', '--sleep-requests', '1', '--sleep-interval', '5', '--max-sleep-interval', '30', '--ignore-errors', '--no-continue', '--no-overwrites', '--add-metadata', '--write-description', '--write-info-json', '--write-annotations', '--write-thumbnail', '--embed-thumbnail', '--all-subs', '--embed-subs', '--get-comments', '--check-formats', '--concurrent-fragments', '10', '--output', '/mnt/W/ytdl//%(uploader)s/%(upload_date)s - %(title)s/%(title)s [%(id)s] f%(format_id)s.%(ext)s', '--throttled-rate', '100K', 'https://www.twitch.tv/amemiyanazuna/videos?filter=all&sort=views', '-s', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8 (No ANSI), screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (linux_exe)
[debug] Python 3.10.13 (CPython x86_64 64bit) - Linux-6.1.0-16-amd64-x86_64-with-glibc2.36 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.0, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2023.12.30/SHA2-256SUMS
Current version: stable@2023.11.16 from yt-dlp/yt-dlp
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
Current Build Hash: 331d8637a0000633c74b7ba7e3c5ce8cfd19940fe7b8ba8bcc3fb771fe182220
Updating to stable@2023.12.30 from yt-dlp/yt-dlp ...
ERROR: Unable to write to /usr/local/bin/yt-dlp; try running as administrator
[TwitchVideos] Extracting URL: https://www.twitch.tv/amemiyanazuna/videos?filter=all&sort=views
[download] Downloading playlist: amemiyanazuna - All Videos sorted by Popular
[TwitchVideos] amemiyanazuna: Downloading Videos GraphQL page 1
[TwitchVideos] Sleeping 1.0 seconds ...
[TwitchVideos] amemiyanazuna: Downloading Videos GraphQL page 2
[TwitchVideos] Playlist amemiyanazuna - All Videos sorted by Popular: Downloading 100 items of 100
[download] Downloading item 1 of 100
...

THIS IS THE MOST COMPLETE OUTPUT I HAVE OF IT SHOWING 117 VODS, THIS IS THE SAME OUTPUT AS IN THE SCREENSHOT

./dl "https://www.twitch.tv/amemiyanazuna/videos?filter=all'&'sort=time"
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[TwitchVideos] Extracting URL: https://www.twitch.tv/amemiyanazuna/videos?filter=all&sort=time
[download] Downloading playlist: amemiyanazuna - All Videos sorted by Date
[TwitchVideos] amemiyanazuna: Downloading Videos GraphQL page 1
[TwitchVideos] amemiyanazuna: Downloading Videos GraphQL page 2
[info] Playlist metadata is already present
[info] There's no playlist description to write
[info] There are no playlist thumbnails to download
[TwitchVideos] Playlist amemiyanazuna - All Videos sorted by Date: Downloading 117 items of 117
[download] Downloading item 1 of 117
...
```

**Comment by bashonly** [comment] 2024-01-09 13:32
> API change?

Yes, and yt-dlp is failing the client integrity check and thus only being served 1 page of VOD results

Closing as duplicate of #7058 and reopening that issue

**Closed by bashonly** 2024-01-09 13:32 UTC
Labels: duplicate, site-bug, site:twitch
