### ISSUE TITLE
SOLVED: ERROR: unable to download video data: HTTP Error 403

### ISSUE THREAD

**Issue by Persona78** [yt-dlp/yt-dlp#11943] opened 2024-12-29 14:50 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

PORTUGAL

### Example URLs

https://www.youtube.com/watch?v=ekr2nIex040&list=PL3-sRm8xAzY9gpXTMGVHJWy_FMD67NBed

### Provide a description that is worded well enough to be understood

Hi!
I solved the "unable to download video data: HTTP Error 403"  by using cookie.txt file.

... Deleted ...

On yt-dlp use like this (if you want to download as mp3 file):
yt-dlp.exe --cookies cookie.txt -4 --no-flat-playlist --recode-video mp3 --extract-audio --audio-quality 0 --progress -P YOUR_DIRECTORY --no-keep-video --ffmpeg-location YOUR_ffmpeg.exe_LOCATION YOUTUBE_LINK

I think for video must be:
yt-dlp.exe --cookies cookie.txt -4 YOUTUBE_LINK

For me is working fine!

I create a batch, if you want it i can share it!

I hope this helps on this issue.

Happy New Year to All!

.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies', 'bin\\cookie.txt', '-4', '--no-flat-playlist', '--recode-video', 'mp3', '--extract-audio', '--audio-quality', '0', '--progress', '-P', 'Albuns\\29.12.2024\\New_2024', '--no-keep-video', '--ffmpeg-location', 'bin\\ffmpeg.exe', 'https://www.youtube.com/watch?v=ekr2nIex040&list=PL3-sRm8xAzY9gpXTMGVHJWy_FMD67NBed', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26100-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.1-full_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.23 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.23 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=ekr2nIex040&list=PL3-sRm8xAzY9gpXTMGVHJWy_FMD67NBed
[youtube:tab] Downloading playlist PL3-sRm8xAzY9gpXTMGVHJWy_FMD67NBed - add --no-playlist to download just the video ekr2nIex040
[youtube:tab] PL3-sRm8xAzY9gpXTMGVHJWy_FMD67NBed: Downloading webpage
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PL3-sRm8xAzY9gpXTMGVHJWy_FMD67NBed
[youtube:tab] PL3-sRm8xAzY9gpXTMGVHJWy_FMD67NBed: Downloading webpage
[youtube:tab] PL3-sRm8xAzY9gpXTMGVHJWy_FMD67NBed: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: New Songs 2024 - New Music Playlist - New Music & Latest Hits
[youtube:tab] PL3-sRm8xAzY9gpXTMGVHJWy_FMD67NBed page 1: Downloading API JSON
[youtube:tab] Playlist New Songs 2024 - New Music Playlist - New Music & Latest Hits: Downloading 100 items of 100
[download] Downloading item 1 of 100
[youtube] Extracting URL: https://www.youtube.com/watch?v=ekr2nIex040
[youtube] ekr2nIex040: Downloading webpage
[youtube] ekr2nIex040: Downloading ios player API JSON
[youtube] ekr2nIex040: Downloading mweb player API JSON
[debug] [youtube] ekr2nIex040: ios client https formats require a PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a PO Token for this client with --extractor-args "youtube:po_token=ios+XXX. For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[debug] [youtube] Extracting signature function js_03dbdfab_103
[debug] Loading youtube-sigfuncs.js_03dbdfab_103 from cache
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig sw3pVVxQG9ewFHI4P => W-YOPVBiaSSW9Q
[debug] [youtube] Extracting signature function js_03dbdfab_107
[debug] Loading youtube-sigfuncs.js_03dbdfab_107 from cache
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig Iw0fUYOB0zk1svDdt => 52AglLsc8_8nAA
[youtube] ekr2nIex040: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] ekr2nIex040: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr1---sn-8vq54vox2u-v2vl.googlevideo.com/videoplayback?expire=1735504416&ei=wF1xZ-fzEq2hvdIPz9-T2AQ&ip=89.115.5.141&id=o-AKh_V510_6-3R2XZpZryxL0OEH7whM-pZQUuYAxHEWxQ&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1735482816%2C&mh=7E&mm=31%2C29&mn=sn-8vq54vox2u-v2vl%2Csn-8vq54vox2u-apns&ms=au%2Crdu&mv=m&mvi=1&pl=19&rms=au%2Cau&gcr=pt&initcwndbps=3322500&bui=AfMhrI97ae1e_CuNJQSmiK8xk_F3fOIbJiq8TtP7pPBgdqERbhExEEYlBFOAludM6kMQRQu5hPgmQ6vQ&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=BXeRrWlpeIx7Edi0aZku4KwQ&rqh=1&gir=yes&clen=2710676&dur=173.401&lmt=1729642612123602&mt=1735482322&fvip=1&keepalive=yes&fexp=51326932%2C51331020%2C51335594%2C51371294&c=MWEB&sefc=1&txp=4532434&n=52AglLsc8_8nAA&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRgIhAMDb-FZv9HUD36sbwbUuTEKVjBTFty8fwHntY0P190_KAiEAi1ibtOtnLiHFHPvtBx81kqPgwMyhVbUj9VtR__WOpgA%3D&sig=AJfQdSswRgIhAKRcR3FdcUZDrs-w6OURpgfHmwtMDqd04Ec8obTzPLpZAiEAgiXCuejwfz_nRwKmHQI2b4RyIEmolWJhRg5dfKHJWp0%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Albuns\29.12.2024\New_2024\ROSÉ & Bruno Mars - APT. (Official Music Video) [ekr2nIex040].webm
[download] 100% of    2.59MiB in 00:00:00 at 13.35MiB/s
[debug] ffmpeg command line: bin\ffmpeg.exe -i "file:Albuns\29.12.2024\New_2024\ROSÉ & Bruno Mars - APT. (Official Music Video) [ekr2nIex040].webm"
[ExtractAudio] Destination: Albuns\29.12.2024\New_2024\ROSÉ & Bruno Mars - APT. (Official Music Video) [ekr2nIex040].opus
[debug] ffmpeg command line: bin\ffmpeg.exe -y -loglevel repeat+info -i "file:Albuns\29.12.2024\New_2024\ROSÉ & Bruno Mars - APT. (Official Music Video) [ekr2nIex040].webm" -vn -acodec copy -movflags +faststart "file:Albuns\29.12.2024\New_2024\ROSÉ & Bruno Mars - APT. (Official Music Video) [ekr2nIex040].opus"
Deleting original file Albuns\29.12.2024\New_2024\ROSÉ & Bruno Mars - APT. (Official Music Video) [ekr2nIex040].webm (pass -k to keep)
[VideoConvertor] Converting video from opus to mp3; Destination: Albuns\29.12.2024\New_2024\ROSÉ & Bruno Mars - APT. (Official Music Video) [ekr2nIex040].mp3
[debug] ffmpeg command line: bin\ffmpeg.exe -y -loglevel repeat+info -i "file:Albuns\29.12.2024\New_2024\ROSÉ & Bruno Mars - APT. (Official Music Video) [ekr2nIex040].opus" -map 0 -dn -ignore_unknown -movflags +faststart "file:Albuns\29.12.2024\New_2024\ROSÉ & Bruno Mars - APT. (Official Music Video) [ekr2nIex040].mp3"
Deleting original file Albuns\29.12.2024\New_2024\ROSÉ & Bruno Mars - APT. (Official Music Video) [ekr2nIex040].opus (pass -k to keep)
[download] Downloading item 2 of 100
[youtube] Extracting URL: https://www.youtube.com/watch?v=kPa7bsKwL-c
[youtube] kPa7bsKwL-c: Downloading webpage
[youtube] kPa7bsKwL-c: Downloading ios player API JSON
[youtube] kPa7bsKwL-c: Downloading mweb player API JSON
[debug] [youtube] kPa7bsKwL-c: ios client https formats require a PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a PO Token for this client with --extractor-args "youtube:po_token=ios+XXX. For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig 8ovv45jBh4Vcn2KOn => 3qc31pDVs2FqEA
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig z17Pbj201Jtisje9s => 1p3MMQ_KU8Ovzg
[youtube] kPa7bsKwL-c: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] kPa7bsKwL-c: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr3---sn-8vq54vox2u-v2vl.googlevideo.com/videoplayback?expire=1735504421&ei=xV1xZ4ieBP-ShcIP8omasAM&ip=89.115.5.141&id=o-AEx0Deq0h4ZHywwHwmxFtYOeXwgLoVDxxtVx8POw3PvC&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1735482821%2C&mh=Ji&mm=31%2C29&mn=sn-8vq54vox2u-v2vl%2Csn-8vq54vox2u-apn6&ms=au%2Crdu&mv=m&mvi=3&pl=19&rms=au%2Cau&gcr=pt&initcwndbps=3322500&bui=AfMhrI-UI-Xv12_LCna2Kw_VtyyXvCMMxrkAj5zVTTvGj4EvMJsCkmKTTGR4b-1873hN_Zt5lnGjGlpu&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=cFfmuRNxfMwvRwzmaFcTx3AQ&rqh=1&gir=yes&clen=4113988&dur=252.321&lmt=1731709075916431&mt=1735482322&fvip=2&keepalive=yes&fexp=51326932%2C51331020%2C51335594%2C51371294&c=MWEB&sefc=1&txp=4532434&n=1p3MMQ_KU8Ovzg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRAIgOFn7xPYJioqI5891Hhe41bbH18Mt6b8o8kI2SzZk9S0CIEb_qs-BWD1XvLctgnMZ4amVBqauzP7A76vwKqMtX8HS&sig=AJfQdSswRQIgP1gTVP-6pFDoGN_iWYwSc9OzsDwXEngsTjL8-vIbw_QCIQDymFkLFC3_luMfCrcyCc9nN6k219g1OF6a2Cm5umNvwQ%3D%3D"
[download] Destination: Albuns\29.12.2024\New_2024\Lady Gaga, Bruno Mars - Die With A Smile (Official Music Video) [kPa7bsKwL-c].webm
[download] 100% of    3.92MiB in 00:00:00 at 23.53MiB/s
[debug] ffmpeg command line: bin\ffmpeg.exe -i "file:Albuns\29.12.2024\New_2024\Lady Gaga, Bruno Mars - Die With A Smile (Official Music Video) [kPa7bsKwL-c].webm"
[ExtractAudio] Destination: Albuns\29.12.2024\New_2024\Lady Gaga, Bruno Mars - Die With A Smile (Official Music Video) [kPa7bsKwL-c].opus
[debug] ffmpeg command line: bin\ffmpeg.exe -y -loglevel repeat+info -i "file:Albuns\29.12.2024\New_2024\Lady Gaga, Bruno Mars - Die With A Smile (Official Music Video) [kPa7bsKwL-c].webm" -vn -acodec copy -movflags +faststart "file:Albuns\29.12.2024\New_2024\Lady Gaga, Bruno Mars - Die With A Smile (Official Music Video) [kPa7bsKwL-c].opus"
Deleting original file Albuns\29.12.2024\New_2024\Lady Gaga, Bruno Mars - Die With A Smile (Official Music Video) [kPa7bsKwL-c].webm (pass -k to keep)
[VideoConvertor] Converting video from opus to mp3; Destination: Albuns\29.12.2024\New_2024\Lady Gaga, Bruno Mars - Die With A Smile (Official Music Video) [kPa7bsKwL-c].mp3

...
```

**Comment by gamer191** [comment] 2024-12-29 16:24
I would advise you to delete this post, and then log out and back in on all your devices (I recommend following https://www.wikihow.com/Sign-Out-of-Your-Google-Account-on-All-Devices-at-Once)

You seem unaware that cookies files provide full access to your account, bypassing passwords, 2fa, and security alerts

If you follow the tutorial above, your cookies file will be invalidated, making it no longer problematic

Happy New Year, and I’m sorry that your attempt to be helpful backfired so badly

**Comment by Persona78** [comment] 2024-12-29 17:53
> I would advise you to delete this post, and then log out and back in on all your devices (I recommend following https://www.wikihow.com/Sign-Out-of-Your-Google-Account-on-All-Devices-at-Once)
> 
> You seem unaware that cookies files provide full access to your account, bypassing passwords, 2fa, and security alerts
> 
> If you follow the tutorial above, your cookies file will be invalidated, making it no longer problematic
> 
> Happy New Year, and I’m sorry that your attempt to be helpful backfired so badly


Hi!

I don´t have Firefox. i used Thor Browser to navigate to Youtube nad don´t logged there..., just copy the link.

I Still don´t know where yt-dlp.exe get the cookies!?

For youtube logged i use Edge...

I still have my account comprimised?????

Please replay.

**Comment by bashonly** [comment] 2024-12-29 18:02
I don't think those were logged-in cookies. You don't have anything to worry about. But for the future, I'd suggest not publicly posting any cookie data just to be safe.

Sharing cookies is not a valid solution, so I am closing this as a duplicate of the pinned issue

**Closed by bashonly** 2024-12-29 18:02 UTC
Labels: site-enhancement, triage

**Comment by Dmole** [comment] 2024-12-30 15:34
As per the pinned issue https://github.com/yt-dlp/yt-dlp/issues/11868 2024-12-16 was the last day yt-dlp worked without

> --cookies-from-browser Firefox
