### ISSUE TITLE
support request for www.cinematheque.fr

### ISSUE THREAD

**Issue by miggazElquez** [yt-dlp/yt-dlp#5363] opened 2022-10-26 20:27 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

France

### Example URLs

https://www.cinematheque.fr/henri/film/154168-la-route-des-alpes-d-evian-au-mont-pelvoux-andre-bayard-1921/

### Provide a description that is worded well enough to be understood

Official organisation from france, who provide access to old movies.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.cinematheque.fr/henri/film/154168-la-route-des-alpes-d-evian-au-mont-pelvoux-andre-bayard-1921/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] API
[debug] Python 3.10.8 (CPython 64bit) - Linux-6.0.2-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://www.cinematheque.fr/henri/film/154168-la-route-des-alpes-d-evian-au-mont-pelvoux-andre-bayard-1921/
[generic] 154168-la-route-des-alpes-d-evian-au-mont-pelvoux-andre-bayard-1921: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 154168-la-route-des-alpes-d-evian-au-mont-pelvoux-andre-bayard-1921: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
[debug] Identified a vimeo embed
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/746866425?color=7db3af&texttrack=fr#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fwww.cinematheque.fr%2Fhenri%2Ffilm%2F154168-la-route-des-alpes-d-evian-au-mont-pelvoux-andre-bayard-1921%2F%22%7D%7D
[vimeo] 746866425: Downloading webpage
ERROR: [vimeo] 746866425: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py", line 872, in _real_extract
    config = self._parse_json(self._search_regex(
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1224, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment] 2022-10-27 11:09
As noted by @eladkarako above, the example URL is a Vimeo embed. The embed is detected but then the Vimeo extractor fails; the underlying issue is the same as #5361.

It looks like all the films that are available to watch on [this page](https://www.cinematheque.fr/henri/) are Vimeo embeds. Is there another section of the site that has videos that we should look into supporting? If not, then this issue will be resolved when #5361 is fixed.

**Comment by miggazElquez** [comment] 2022-10-27 11:55
> Is there another section of the site that has videos that we should look into supporting?

I don't think so (I didn't find any). 
I should have read the output more carefully, thanks for the help !

**Comment by pukkandan** [comment] 2022-10-28 10:32
Closing as duplicate of #5361. Once the vimeo issue is fixed, you can re-open this if you think a dedicated extractor is still needed.

**Closed by pukkandan** 2022-10-28 10:32 UTC
Labels: site-request, triage
