### ISSUE TITLE
[youtube] Unable to download API page: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by budsz** [yt-dlp/yt-dlp#9399] opened 2024-03-09 02:06 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Indonesia

### Provide a description that is worded well enough to be understood

```
# python -V
Python 3.9.18

# yt-dlp -U
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)

# yt-dlp -f 18 -o "JT LAGU DAYAK BORNEO Cover - Bintang Atei - DAERAH - ST.mp4" https://youtu.be/UZ9yjUHsgj8?si=P3wgAl_I
jL3wk_wC
[youtube] Extracting URL: https://youtu.be/UZ9yjUHsgj8?si=P3wgAl_IjL3wk_wC
[youtube] UZ9yjUHsgj8: Downloading webpage
[youtube] UZ9yjUHsgj8: Downloading ios player API JSON
[youtube] UZ9yjUHsgj8: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] UZ9yjUHsgj8: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] UZ9yjUHsgj8: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] UZ9yjUHsgj8: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] UZ9yjUHsgj8: Downloading m3u8 information
[info] UZ9yjUHsgj8: Downloading 1 format(s): 18
[download] Destination: JT LAGU DAYAK BORNEO Cover - Bintang Atei - DAERAH - ST.mp4
[download] 100% of    7.08MiB in 00:00:12 at 596.99KiB/s
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
# yt-dlp -vU -f 18 -o "JT LAGU DAYAK BORNEO Cover - Bintang Atei - DAERAH - ST.mp4" https://youtu.be/UZ9yjUHsgj8?si=P3wgAl_IjL3wk_wC
[debug] Command-line config: ['--force-overwrites', '-vU', '-f', '18', '-o', 'JT LAGU DAYAK BORNEO Cover - Bintang Atei - DAERAH - ST.mp4', 'https://youtu.be/UZ9yjUHsgj8?si=P3wgAl_IjL3wk_wC']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (zip)
[debug] Python 3.9.18 (CPython amd64 64bit) - FreeBSD-14.0-RELEASE-p5-amd64-64bit-ELF (OpenSSL 3.0.12 24 Oct 2023, libc 7)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: certifi-2024.02.02, requests-2.31.0, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://youtu.be/UZ9yjUHsgj8?si=P3wgAl_IjL3wk_wC
[youtube] UZ9yjUHsgj8: Downloading webpage
[youtube] UZ9yjUHsgj8: Downloading ios player API JSON
[youtube] UZ9yjUHsgj8: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] UZ9yjUHsgj8: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] UZ9yjUHsgj8: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] UZ9yjUHsgj8: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig aTHKfaksQcXcmqqA => 2-_K8orHQtCcSw
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig FwK2dpAFEq6Eydyd => 5cOdkSihOTnfsQ
[youtube] UZ9yjUHsgj8: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] UZ9yjUHsgj8: Downloading 1 format(s): 18
Deleting existing file JT LAGU DAYAK BORNEO Cover - Bintang Atei - DAERAH - ST.mp4
[debug] Invoking http downloader on "https://rr3---sn-2ugxh5a5-cqvl.googlevideo.com/videoplayback?expire=1709971084&ei=LMLrZdClI_7k4t4Pg763iA8&ip=202.138.247.170&id=o-ANic5FMfjieyur7aqSCykEsow3FT0AxhufQXucXuaC0x&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=3o&mm=31%2C29&mn=sn-2ugxh5a5-cqvl%2Csn-v2u0n-ntqk&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=24&initcwndbps=613750&spc=UWF9f2y-JwW8jFhZo4bJbwLu-vAaNUUxrgoIOZs1N2YRIzI&vprv=1&svpuc=1&mime=video%2Fmp4&ns=zkGWVF-yxxoFexmzgrQOQd8Q&gir=yes&clen=7424234&ratebypass=yes&dur=316.580&lmt=1709584025925900&mt=1709949200&fvip=1&fexp=24007246&c=WEB&sefc=1&txp=6219224&n=2-_K8orHQtCcSw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIhAJY0SLlFmGGjj71mQFawZlLzB6gYJihkTv6iO4hKSUcNAiAtWLciUxnJEXUR82mtZtAjoQkSJYho7sVef6rsl54tAQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=APTiJQcwRQIgC589IeIlIb23Zok29ajMnwZ3mGEzdQoNQSo5jtfvmbQCIQC79VETNzLfi6Cpdo68x9MnrVtALNiHUnpJJ7vqqpvc-A%3D%3D"
[download] Destination: JT LAGU DAYAK BORNEO Cover - Bintang Atei - DAERAH - ST.mp4
[download] 100% of    7.08MiB in 00:00:00 at 10.16MiB/s
```

**Comment by seproDev** [comment] 2024-03-09 02:09
Duplicate of #9316

Update to nightly

if you are using the exe/zip:
```
yt-dlp --update-to nightly
```

or if you installed with pip:
```
python3 -m pip install -U --pre yt-dlp
```

**Closed by seproDev** 2024-03-09 02:09 UTC
Labels: site-bug, triage

**Comment by budsz** [comment] 2024-03-09 02:12
Thanks @seproDev for information.

**Comment by notmutiny** [comment] 2024-03-09 07:29
I am experiencing this too. The logs told me to create a new issue but creating a new issue requires an entire high school textbook of reading. Here are my logs.

```
C:\Users\Admin\Downloads>yt-dlp.exe https://www.youtube.com/watch?v=vH9ZV6iGlZU
[youtube] Extracting URL: https://www.youtube.com/watch?v=vH9ZV6iGlZU
[youtube] vH9ZV6iGlZU: Downloading webpage
[youtube] vH9ZV6iGlZU: Downloading ios player API JSON
[youtube] vH9ZV6iGlZU: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] vH9ZV6iGlZU: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] vH9ZV6iGlZU: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] vH9ZV6iGlZU: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] vH9ZV6iGlZU: Downloading m3u8 information
[info] vH9ZV6iGlZU: Downloading 1 format(s): 244+251
[download] Destination: The Legend of Zelda： Oracle of Seasons and Ages - Ending Theme (Orchestrated) [vH9ZV6iGlZU].f244.webm
[download] 100% of  753.11KiB in 00:00:00 at 2.01MiB/s
[download] Destination: The Legend of Zelda： Oracle of Seasons and Ages - Ending Theme (Orchestrated) [vH9ZV6iGlZU].f251.webm
[download] 100% of    2.23MiB in 00:00:00 at 4.98MiB/s
[Merger] Merging formats into "The Legend of Zelda： Oracle of Seasons and Ages - Ending Theme (Orchestrated) [vH9ZV6iGlZU].webm"
Deleting original file The Legend of Zelda： Oracle of Seasons and Ages - Ending Theme (Orchestrated) [vH9ZV6iGlZU].f244.webm (pass -k to keep)
Deleting original file The Legend of Zelda： Oracle of Seasons and Ages - Ending Theme (Orchestrated) [vH9ZV6iGlZU].f251.webm (pass -k to keep)
```

I believe this broke the NPM packages I am dependent on too

**Comment by notmutiny** [comment] 2024-03-09 07:47
CC @seproDev

**Comment by seproDev** [comment] 2024-03-09 08:18
@notmutiny From your logs you are using the exe.
```
yt-dlp --update-to nightly
```
