### ISSUE TITLE
Add a new return code when the playlist contains unavailable files  

### ISSUE THREAD

**Issue by 62Maurizio** [yt-dlp/yt-dlp#2480] opened 2022-01-25 09:00 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hi.. 
to describe..  just issue this command ..  (saving you to download files...) on this  playlist with some unavailable files..
yt-dlp  -i --get-filename https://www.youtube.com/playlist?list=PL589F59AC75C74A37
yt-dlp return error code 1 
the real problem is when  i pass to download files   
it succesfully download all the files and skip the unavailables .. but still return error code 1
this causes  problems in my program because it checks return code to perform further actions on downlaoded files..
in this way i'm not able to distinguish if there was a real network error and  files are not complete..
is this possible to introduce a new return code when there are   unavailable files.. ?
i.e  Return 2 .. 
or to do not broken other people code..  introduce also new parameter  that permit to check with an  "IF,THEN.ELSE" the new return code ..   i.e  --manage-returncode
Thanks in advance
Maurizio

**Comment by pukkandan** [comment] 2022-01-25 13:49
Duplicate of #457

**Closed by pukkandan** 2022-01-25 13:49 UTC
Labels: enhancement, triage

**Comment by 62Maurizio** [comment] 2022-01-26 14:44
Hi 
I receaved email  with  your update..
I'm new of github , this is the first time, so just two little questions..
As far you know... when #457 is planned to be available ? 
Is there a way to be automatically informed via Email ?   
Thanks.. Maurizio

**Comment by pukkandan** [comment] 2022-01-26 15:00
There is no ETA, but likely not anytime soon

For notification, you can subscribe to issues

![image](https://user-images.githubusercontent.com/6623388/151187577-67e98199-8f34-4a35-9e61-f607f2912d48.png)
