### ISSUE TITLE
[youtube] Cannot get index py in: {} (caused by KeyError('py'));

### ISSUE THREAD

**Issue by migwynkriid** [yt-dlp/yt-dlp#11845] opened 2024-12-17 18:08 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

This seems to be a new 'issue', yt-dlp is updated to the latest release.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Command processor started
2024-12-17 18:54:06 INFO     discord.voice_state Connecting to voice...
2024-12-17 18:54:06 [INFO] Connecting to voice...
2024-12-17 18:54:06 INFO     discord.voice_state Starting voice handshake... (connection attempt 1)
2024-12-17 18:54:06 [INFO] Starting voice handshake... (connection attempt 1)
2024-12-17 18:54:07 INFO     discord.voice_state Voice handshake complete. Endpoint found: milan3333.discord.media
2024-12-17 18:54:07 [INFO] Voice handshake complete. Endpoint found: milan3333.discord.media
2024-12-17 18:54:07 INFO     discord.voice_state Voice connection complete.
2024-12-17 18:54:07 [INFO] Voice connection complete.
2024-12-17 18:54:07 [DEBUG] [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
2024-12-17 18:54:07 [DEBUG] [debug] yt-dlp version stable@2024.12.06 from yt-dlp/yt-dlp [4bd265539] (pip) API
2024-12-17 18:54:07 [DEBUG] [debug] params: {'format': 'bestaudio[ext=m4a][abr<=96]/bestaudio[abr<=96]/bestaudio/best/bestaudio*', 'outtmpl': '/Users/sebastijan/discord-ytdlp/downloads/%(id)s.%(ext)s', 'extract_audio': True, 'concurrent_fragments': 4, 'abort_on_unavailable_fragments': True, 'nopostoverwrites': True, 'windowsfilenames': True, 'restrictfilenames': True, 'noplaylist': True, 'nocheckcertificate': True, 'default_search': 'ytsearch', 'source_address': '0.0.0.0', 'extract_flat': False, 'force_generic_extractor': False, 'verbose': True, 'logger': <Logger yt-dlp (DEBUG)>, 'ignoreerrors': True, 'ffmpeg_location': 'ffmpeg', 'yt_dlp_filename': '/Users/sebastijan/discord-ytdlp/yt-dlp', 'cookiefile': '/Users/sebastijan/discord-ytdlp/cookies.txt', 'progress_hooks': [<function MusicBot.download_song.<locals>.<lambda> at 0x10358d260>], 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
2024-12-17 18:54:07 [DEBUG] [debug] Python 3.12.2 (CPython arm64 64bit) - macOS-14.6.1-arm64-arm-64bit (OpenSSL 3.2.1 30 Jan 2024)
2024-12-17 18:54:07 [WARNING] ffmpeg-location ffmpeg does not exist! Continuing without ffmpeg
2024-12-17 18:54:07 [DEBUG] [debug] exe versions: none
2024-12-17 18:54:07 [DEBUG] [debug] Optional libraries: certifi-2024.08.30, requests-2.32.3, sqlite3-3.45.2, urllib3-2.2.3
2024-12-17 18:54:07 [DEBUG] [debug] Proxy map: {}
2024-12-17 18:54:07 [DEBUG] [debug] Request Handlers: urllib, requests
2024-12-17 18:54:07 [DEBUG] [debug] Loaded 1837 extractors
2024-12-17 18:54:07 [DEBUG] [youtube:search] Extracting URL: ytsearch:1 hour white noise
2024-12-17 18:54:07 [DEBUG] [download] Downloading playlist: 1 hour white noise
2024-12-17 18:54:07 [DEBUG] [youtube:search] query "1 hour white noise": Downloading web client config
2024-12-17 18:54:09 [DEBUG] [debug] [youtube:search] Extracted SAPISID cookie
2024-12-17 18:54:09 [DEBUG] [youtube:search] query "1 hour white noise" page 1: Downloading API JSON
2024-12-17 18:54:10 [DEBUG] [youtube:search] Playlist 1 hour white noise: Downloading 1 items of 1
2024-12-17 18:54:10 [DEBUG] [debug] The information of all playlist entries will be held in memory
2024-12-17 18:54:10 [DEBUG] [download] Downloading item 1 of 1
2024-12-17 18:54:10 [DEBUG] [youtube] Extracting URL: https://www.youtube.com/watch?v=lzmSKX5TF3g
2024-12-17 18:54:10 [DEBUG] [youtube] lzmSKX5TF3g: Downloading webpage
2024-12-17 18:54:10 [DEBUG] [debug] [youtube] Extracted SAPISID cookie
2024-12-17 18:54:10 [DEBUG] [youtube] lzmSKX5TF3g: Downloading web creator player API JSON
2024-12-17 18:54:11 [DEBUG] [youtube] lzmSKX5TF3g: Downloading mweb player API JSON
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Extracting signature function js_2f1832d2_112
2024-12-17 18:54:11 [DEBUG] [youtube] lzmSKX5TF3g: Downloading player 2f1832d2
2024-12-17 18:54:11 [WARNING] [youtube] lzmSKX5TF3g: Signature extraction failed: Some formats may be missing
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Extracting signature function js_2f1832d2_108
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [DEBUG] [debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2024-12-17 18:54:11 [WARNING] Only images are available for download. use --list-formats to see them
2024-12-17 18:54:11 [DEBUG] [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
2024-12-17 18:54:11 [DEBUG] [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
2024-12-17 18:54:11 [ERROR] ERROR: [youtube] lzmSKX5TF3g: Requested format is not available. Use --list-formats for a list of available formats
2024-12-17 18:54:11 [ERROR] Traceback (most recent call last):
  File "/Users/sebastijan/discord-ytdlp/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1624, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sebastijan/discord-ytdlp/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1780, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sebastijan/discord-ytdlp/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1839, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sebastijan/discord-ytdlp/venv/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 2973, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] lzmSKX5TF3g: Requested format is not available. Use --list-formats for a list of available formats

2024-12-17 18:54:11 [DEBUG] [download] Finished downloading playlist: 1 hour white noise
Error downloading song: 'NoneType' object is not subscriptable
Error playing song: 'NoneType' object is not subscriptable
```

**Comment by bashonly** [comment] 2024-12-17 18:09
Duplicate of #11798

update yt-dlp

**Closed by bashonly** 2024-12-17 18:09 UTC
Labels: bug, triage
