### ISSUE TITLE
Unable to download the meta data of Vimeo video

### ISSUE THREAD

**Issue by Atif-Sheikh** [yt-dlp/yt-dlp#9925] opened 2024-05-15 13:19 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm trying to get the metadata for the Vimeo video below but got an error.

Vimeo Video URL: https://vimeo.com/247280882

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.06.01 
[debug] Git HEAD: 1f526ed
[debug] Python version 2.7.18 (CPython 64bit) - Darwin-21.6.0-arm64-arm-64bit
[debug] exe versions: ffmpeg 4.4.4, ffprobe 4.4.4
[debug] Proxy map: {}
ERROR: It looks like you installed yt-dlp with a package manager, pip, setup.py or a tarball. Please use that to update
[debug] [vimeo] Extracting URL: https://vimeo.com/946003283/145fd436b8
[vimeo] 946003283: Downloading JSON metadata
[vimeo] 946003283: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 406: Not Acceptable (caused by HTTPError()); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/Users/apple/.pyenv/versions/2.7.18/lib/python2.7/site-packages/yt_dlp/extractor/common.py", line 675, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Users/apple/.pyenv/versions/2.7.18/lib/python2.7/site-packages/yt_dlp/YoutubeDL.py", line 3062, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Users/apple/.pyenv/versions/2.7.18/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/Users/apple/.pyenv/versions/2.7.18/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/apple/.pyenv/versions/2.7.18/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/Users/apple/.pyenv/versions/2.7.18/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Users/apple/.pyenv/versions/2.7.18/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
```

**Comment by Domejko** [comment] 2024-05-15 13:29
I would suggest to first update your `yt-dlp` version as it suggested in error msg since you are using `2021.06.01` version instead of `2024.4.9`.

**Comment by bashonly** [comment] 2024-05-15 14:45
Duplicate of #9124

**Closed by bashonly** 2024-05-15 14:45 UTC
Labels: duplicate, incomplete, site-bug, site:vimeo
