### ISSUE TITLE
Site support request for iyf.tv

### ISSUE THREAD

**Issue by Ziyi6** [yt-dlp/yt-dlp#11575] opened 2024-11-18 08:04 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Unknown

### Example URLs

https://www.iyf.tv/play/ecJJy0t3oOR?id=Spip8DKPFW7

### Provide a description that is worded well enough to be understood

The above site is not supported, could you support it? Thanks!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.iyf.tv/play/ecJJy0t3oOR?id=Spip8DKPFW7
[debug] Command-line config: ['-vU', 'https://www.iyf.tv/play/ecJJy0t3oOR?id=Spip8DKPFW7']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.26.232938 from yt-dlp/yt-dlp-nightly-builds [eabb4680f] (pip)
[debug] Python 3.9.17 (CPython x86_64 64bit) - Linux-6.5.0-35-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.9 30 May 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-None, certifi-2023.05.07, mutagen-1.47.0, requests-2.32.3, sqlite3-3.41.2, urllib3-2.2.1, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
Current version: nightly@2024.09.26.232938 from yt-dlp/yt-dlp-nightly-builds
Latest version: nightly@2024.11.18.232921 from yt-dlp/yt-dlp-nightly-builds
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[generic] Extracting URL: https://www.iyf.tv/play/ecJJy0t3oOR?id=Spip8DKPFW7
[generic] ecJJy0t3oOR?id=Spip8DKPFW7: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ecJJy0t3oOR?id=Spip8DKPFW7: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.iyf.tv/play/ecJJy0t3oOR?id=Spip8DKPFW7
Traceback (most recent call last):
  File "/home/devops/miniconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/home/devops/miniconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
  File "/home/devops/miniconda3/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "/home/devops/miniconda3/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.iyf.tv/play/ecJJy0t3oOR?id=Spip8DKPFW7
```

**Comment by grqz** [comment] 2024-11-18 08:27
> [www.iyf.tv](http://www.iyf.tv)

is that the same as #11225?

**Comment by Ziyi6** [comment] 2024-11-18 08:33
> > [www.iyf.tv](http://www.iyf.tv)
> 
> is that the same as #11225? Please provide some _playable_ URLs instead of the homepage

Yes, I just checked these websites, they are the same.

Playable URL for www.yfsp.tv:
https://www.yfsp.tv/play/ecJJy0t3oOR

for iyf.tv:
https://www.iyf.tv/play/ecJJy0t3oOR?id=Spip8DKPFW7

for olevod.tv:
https://www.olevod.com/player/vod/2-60810-1.html

**Comment by bashonly** [comment] 2024-11-18 13:14
One site support request per issue. Pleaase decide which one you would like to request in this issue and edit your original post accordingly.

> Complete Verbose Output

This :point_up:  is **not optional!** Please provide a verbose log or this issue will be closed as incomplete.

**Comment by Ziyi6** [comment] 2024-11-19 03:38
> One site support request per issue. Pleaase decide which one you would like to request in this issue and edit your original post accordingly.
> 
> > Complete Verbose Output
> 
> This ☝️ is **not optional!** Please provide a verbose log of a download attempt from the requested site, or else this issue will be closed as incomplete.

Hi，I just modified the issue, please have a check.

**Comment by bashonly** [comment] 2024-11-19 03:47
Thanks, but it's still missing **verbose** output. Add `-vU` to your command

**Comment by bashonly** [comment] 2024-11-19 03:48
So isn't this a duplicate of https://github.com/yt-dlp/yt-dlp/issues/11225?

**Closed** 2024-11-21 19:31 UTC
Labels: site-request, triage
