### ISSUE TITLE
ERROR: '<' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by koshikas** [yt-dlp/yt-dlp#3011] opened 2022-03-10 03:58 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

after updating to latest 2022.03.08.1 i get this error; "ERROR: '<' not supported between instances of 'float' and 'str"
and yt-dlp skips without downloading the video, however the same video(s) do download without a glitch on 2022.02.04. the verbose output of the properly functioning 2022.02.04 is as follows;

[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=RcNrknuUL8M']
[debug] User config "/home/koshika/.config/yt-dlp/config": ['-o', '/mnt/reserve/4kDownloader/%(title)s.%(ext)s', '--no-playlist', '--no-overwrite', '--no-mtime', '-f', '135+140/bv*[height<=480][vcodec^=avc1]+ba[ext=m4a]/b[height<=480]/wv*+ba/w', '-N', '4', '--throttled-rate', '80K']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (zip)
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.15.25-1-MANJARO-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: Crypto, sqlite
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=RcNrknuUL8M
[youtube] RcNrknuUL8M: Downloading webpage
[youtube] RcNrknuUL8M: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] RcNrknuUL8M: Downloading 1 format(s): 135+140
[debug] Invoking downloader on "https://rr3---sn-nau-jhcz.googlevideo.com/videoplayback?expire=1646905961&ei=CXYpYsz_A4K9rtoPm4WJuAM&ip=112.134.94.254&id=o-ALvu6w98MZPBhJ8VqhyuPEbhkW9Pc0Y8u2oULP0eHgOt&itag=135&source=youtube&requiressl=yes&mh=Ur&mm=31%2C29&mn=sn-nau-jhcz%2Csn-npoe7ne7&ms=au%2Crdu&mv=m&mvi=3&pl=22&initcwndbps=570000&vprv=1&mime=video%2Fmp4&gir=yes&clen=771131&dur=42.099&lmt=1646873003185128&mt=1646883892&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgN5mMtsWT_Vlvu9CCDiLonuloYMbO0rqVIP8bQM-JWKECIQDJGCrtv1zArdKdUvGYYiGNoKzp-JtaxLFlL7fm2ZbmiA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIyDokqAHfzsO0XuVhkIpa877tjrwVyCOFIMw-hUvMMKAiBoLrmpwjDuTJGvHyU-a1HQBk9PTxLst2qTxAwrSGJVCg%3D%3D"
[download] Resuming download at byte 1024
[download] Destination: /mnt/reserve/4kDownloader/A crater in Turkmenistan has been on fire for about 50 years #shorts.f135.mp4
[download] 100% of 753.06KiB in 00:00
[debug] Invoking downloader on "https://rr3---sn-nau-jhcz.googlevideo.com/videoplayback?expire=1646905961&ei=CXYpYsz_A4K9rtoPm4WJuAM&ip=112.134.94.254&id=o-ALvu6w98MZPBhJ8VqhyuPEbhkW9Pc0Y8u2oULP0eHgOt&itag=140&source=youtube&requiressl=yes&mh=Ur&mm=31%2C29&mn=sn-nau-jhcz%2Csn-npoe7ne7&ms=au%2Crdu&mv=m&mvi=3&pl=22&initcwndbps=570000&vprv=1&mime=audio%2Fmp4&gir=yes&clen=683368&dur=42.167&lmt=1646872763617990&mt=1646883892&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAL8jHwNtv3jlJQj3DrIvperEwA6tPOOcacyx2shP7G_fAiEAuj-5a7ZvzzaC4_mEGFbLwhp-h1tpfOGlKkPkPVcTtq0%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIyDokqAHfzsO0XuVhkIpa877tjrwVyCOFIMw-hUvMMKAiBoLrmpwjDuTJGvHyU-a1HQBk9PTxLst2qTxAwrSGJVCg%3D%3D"
[download] Destination: /mnt/reserve/4kDownloader/A crater in Turkmenistan has been on fire for about 50 years #shorts.f140.m4a
[download] 100% of 667.35KiB in 00:00
[Merger] Merging formats into "/mnt/reserve/4kDownloader/A crater in Turkmenistan has been on fire for about 50 years #shorts.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/mnt/reserve/4kDownloader/A crater in Turkmenistan has been on fire for about 50 years #shorts.f135.mp4' -i 'file:/mnt/reserve/4kDownloader/A crater in Turkmenistan has been on fire for about 50 years #shorts.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:/mnt/reserve/4kDownloader/A crater in Turkmenistan has been on fire for about 50 years #shorts.temp.mp4'
Deleting original file /mnt/reserve/4kDownloader/A crater in Turkmenistan has been on fire for about 50 years #shorts.f135.mp4 (pass -k to keep)
Deleting original file /mnt/reserve/4kDownloader/A crater in Turkmenistan has been on fire for about 50 years #shorts.f140.m4a (pass -k to keep)

### Verbose log

```shell
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=RcNrknuUL8M']
[debug] User config "/home/koshika/.config/yt-dlp/config": ['-o', '/mnt/reserve/4kDownloader/%(title)s.%(ext)s', '--no-playlist', '--no-overwrite', '--no-mtime', '-f', '135+140/bv*[height<=480][vcodec^=avc1]+ba[ext=m4a]/b[height<=480]/wv*+ba/w', '-N', '4', '--throttled-rate', '80K']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.15.25-1-MANJARO-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: Crypto, sqlite
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=RcNrknuUL8M
[youtube] RcNrknuUL8M: Downloading webpage
[youtube] RcNrknuUL8M: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] RcNrknuUL8M: Downloading 1 format(s): 135+140
[debug] Invoking downloader on "https://rr3---sn-nau-jhcz.googlevideo.com/videoplayback?expire=1646905603&ei=o3QpYp6PIomgvwSWsrzgCg&ip=112.134.94.254&id=o-ADmaThxfHfrHYgMancwLHQ2MECe_ZPAXNYIWvavGh8wP&itag=135&source=youtube&requiressl=yes&mh=Ur&mm=31%2C29&mn=sn-nau-jhcz%2Csn-npoe7ne7&ms=au%2Crdu&mv=m&mvi=3&pl=22&initcwndbps=553750&vprv=1&mime=video%2Fmp4&gir=yes&clen=771131&dur=42.099&lmt=1646873003185128&mt=1646883653&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOZJZiFto7RXgSOnRXgchwZF5_WYvkZCe7LpTp-19j0WAiEAmdqikeKWAGQ_K9NAGL-nB1T1N8-0LqWAtsbykpDR6DY%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgeUYaYdrGo6BmiOz-157eNjXw9NQxkJ6Rj9HWpnWgYN8CIQCkEdDVKUlRZR05YfaIwu-Yk6eEJxFQFMMdGD_6URBvnw%3D%3D"
[download] Destination: /mnt/reserve/4kDownloader/A crater in Turkmenistan has been on fire for about 50 years #shorts.f135.mp4
[download]   0.1% of 753.06KiB at 79.20KiB/s ETA 00:09ERROR: '<' not supported between instances of 'float' and 'str'
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1473, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1529, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2638, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3110, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2835, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 453, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 384, in real_download
    return download()
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 334, in download
    if speed and speed < (self.params.get('throttledratelimit') or 0):
TypeError: '<' not supported between instances of 'float' and 'str'
```

**Comment by Lesmiscore** [comment] 2022-03-10 04:01
Duplicate of #2996

**Closed by Lesmiscore** 2022-03-10 04:01 UTC
Labels: bug, triage
