### ISSUE TITLE
Radiko No video formats found and 403 forbidden error

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#7192] opened 2023-06-01 08:51 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

How can I download timefree radio audio from the website radiko? I am trying yt-dlp and I get 403 Forbidden

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://radiko.jp/#!/ts/OBC/20230530010000']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n5.1.2-ffmpeg-windows-build-helpers (fdk,setts), ffprobe n5.1.2-ffmpeg-windows-build-helpers, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[Radiko] Extracting URL: https://radiko.jp/#!/ts/OBC/20230530010000
[Radiko] 20230530010000: Downloading radio program for OBC station
[debug] Loading radiko.auth_data from cache
[Radiko] 20230530010000: Downloading stream information
[Radiko] 20230530010000: Downloading m3u8 information from tf-c-rpaa-radiko.smartstream.ne.jp
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20230530010000: Downloading m3u8 information from tf-f-rpaa-radiko.smartstream.ne.jp
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20230530010000: Downloading m3u8 information from si-f-radiko.smartstream.ne.jp
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20230530010000: Downloading m3u8 information from si-c-radiko.smartstream.ne.jp
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20230530010000: Downloading m3u8 information from rd-wowza-radiko.radiko-cf.com
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20230530010000: Downloading m3u8 information from rd-wowza-radiko.radiko-cf.com
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20230530010000: Downloading m3u8 information from f-radiko.smartstream.ne.jp
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20230530010000: Downloading m3u8 information from radiko.jp
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 401: Unauthorized
[Radiko] 20230530010000: Downloading m3u8 information from c-radiko.smartstream.ne.jp
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] Downloading authentication page
[Radiko] Downloading player js code
[Radiko] Authenticating
[debug] Saving radiko.auth_data to cache
[Radiko] 20230530010000: Downloading stream information
[Radiko] 20230530010000: Downloading m3u8 information from tf-c-rpaa-radiko.smartstream.ne.jp
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20230530010000: Downloading m3u8 information from tf-f-rpaa-radiko.smartstream.ne.jp
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20230530010000: Downloading m3u8 information from si-f-radiko.smartstream.ne.jp
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20230530010000: Downloading m3u8 information from si-c-radiko.smartstream.ne.jp
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20230530010000: Downloading m3u8 information from rd-wowza-radiko.radiko-cf.com
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20230530010000: Downloading m3u8 information from rd-wowza-radiko.radiko-cf.com
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20230530010000: Downloading m3u8 information from f-radiko.smartstream.ne.jp
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
[Radiko] 20230530010000: Downloading m3u8 information from radiko.jp
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 401: Unauthorized
[Radiko] 20230530010000: Downloading m3u8 information from c-radiko.smartstream.ne.jp
WARNING: [Radiko] Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: [Radiko] 20230530010000: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1615, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2615, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1046, in raise_no_formats
yt_dlp.utils.ExtractorError: [Radiko] 20230530010000: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pukkandan** [comment] 2023-06-01 08:57
The log is incomplete.

**Comment by throwaway234432** [comment] 2023-06-01 09:00
Updated log

**Comment by pukkandan** [comment] 2023-06-01 09:06
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details

@throwaway234432 Are you sure about this? The site tells me `Radiko service is available only in Japan`

**Comment by throwaway234432** [comment] 2023-06-01 09:31
Yes, I am using a VPN to access the website

**Comment by pukkandan** [comment] 2023-06-01 09:58
Is yt-dlp going through the same VPN?

**Comment by throwaway234432** [comment] 2023-06-01 20:52
Yes, I am using the command with VPN on

**Comment by garret1317** [comment] 2023-06-04 01:41
could you post a log using `--dump-pages` so i can see your auth2 result? (shows where radiko thinks you are/what region your token applies to)
alternatively, the results of https://api.radiko.jp/apparea/area or https://radiko.jp/area (doesn't really matter which)
with the vpn of course

**Comment by garret1317** [comment] 2023-06-04 01:58
also, personal anecdote/possible root cause
some mullvad osaka servers get detected as tokyo for me
you're trying to download from an osaka station, maybe the same thing's happening to you?

**Comment by bakanano** [comment] 2023-06-06 00:46
> could you post a log using `--dump-pages` so i can see your auth2 result? (shows what region your token applies to/where radiko thinks you are) alternatively, the results of https://api.radiko.jp/apparea/area or https://radiko.jp/area (doesn't really matter which) with the vpn of course

How can I find the log files for --dump-pages?

Also, when I try to access https://api.radiko.jp/apparea/area or https://radiko.jp/area, I get blank pages. Nothing loads for me. 

My browser is Firefox, updated to latest version.

**Comment by throwaway234432** [comment] 2023-06-06 00:48
> could you post a log using `--dump-pages` so i can see your auth2 result? (shows what region your token applies to/where radiko thinks you are) alternatively, the results of https://api.radiko.jp/apparea/area or https://radiko.jp/area (doesn't really matter which) with the vpn of course

Where can I find the logs when I use --dump-pages?

Also, when I try to access https://api.radiko.jp/apparea/area or https://radiko.jp/are, I get blank pages. 

I'm on Firefox, updated to latest version

**Comment by garret1317** [comment] 2023-06-06 01:36
> Also, when I try to access https://api.radiko.jp/apparea/area or https://radiko.jp/area, I get blank pages.

are you using the [rajiko](https://github.com/jackyzy823/rajiko/) browser extension? it blocks those pages so the site js doesn't know where you are
otherwise i don't know why that would be happening, try with curl/wget instead

**Comment by garret1317** [comment] 2023-08-18 22:04
op deleted account so can probably close this now

**Closed** 2023-08-19 17:23 UTC
Labels: geo-blocked, site-bug, triage
