### ISSUE TITLE
extraction failed: Some formats may be missing Install PhantomJS to workaround the issue.

### ISSUE THREAD

**Issue by caf2022** [yt-dlp/yt-dlp#10404] opened 2024-07-09 20:23 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

I have a new problem after update to latest version on all of my servers about formats, and already installed the phantomjs but not solved,

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--format', '18', 'https://www.youtube.com/watch?v=RQaXfEJ8f3o']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.08.232708 from yt-dlp/yt-dlp-nightly-builds [1a6ac547e] (zip)
[debug] Python 3.9.18 (CPython x86_64 64bit) - Linux-5.14.0-427.20.1.el9_4.x86_64-x86_64-with-glibc2.34 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.34)

root@jp6hjv7a8z [~]# [debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, phantomjs 2.1.1
[debug] Optional libraries: requests-2.25.1, sqlite3-3.34.1, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.07.08.232708 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.07.08.232708 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=RQaXfEJ8f3o
[youtube] RQaXfEJ8f3o: Downloading webpage
[youtube] RQaXfEJ8f3o: Downloading ios player API JSON
[debug] Loading youtube-nsig.b22ef6e7 from cache
WARNING: [youtube] RQaXfEJ8f3o: Native nsig extraction failed: Trying with PhantomJS
         n = nQUdOSW_wQEGKrUxa ; player = https://www.youtube.com/s/player/b22ef6e7/player_ias.vflset/en_US/base.js
[debug] [youtube] No terminating paren } in: {e=e===void 0?"":e;f=f===void 0?!1:f;h=h===void...024&&(f=f.substr(0,e));c.push(f)}return c.join(""); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] RQaXfEJ8f3o: Executing signature code
[debug] [youtube] PhantomJS command line: phantomjs --ssl-protocol=any /tmp/tmptli0oznm
WARNING: [youtube] RQaXfEJ8f3o: nsig extraction failed: Some formats may be missing
         n = nQUdOSW_wQEGKrUxa ; player = https://www.youtube.com/s/player/b22ef6e7/player_ias.vflset/en_US/base.js
[debug] [youtube] Executing signature code failed: Unable to run PhantomJS binary (caused by TimeoutExpired(['phantomjs', '--ssl-protocol=any', '/tmp/tmptli0oznm'], 5.0)); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Loading youtube-nsig.b22ef6e7 from cache
WARNING: [youtube] RQaXfEJ8f3o: Native nsig extraction failed: Trying with PhantomJS
         n = wFe4I3_j15dJH402I ; player = https://www.youtube.com/s/player/b22ef6e7/player_ias.vflset/en_US/base.js
[youtube] RQaXfEJ8f3o: Executing signature code
[debug] [youtube] PhantomJS command line: phantomjs --ssl-protocol=any /tmp/tmp8x16e2vx
WARNING: [youtube] RQaXfEJ8f3o: nsig extraction failed: Some formats may be missing
         n = wFe4I3_j15dJH402I ; player = https://www.youtube.com/s/player/b22ef6e7/player_ias.vflset/en_US/base.js
[debug] [youtube] Executing signature code failed: Unable to run PhantomJS binary (caused by TimeoutExpired(['phantomjs', '--ssl-protocol=any', '/tmp/tmp8x16e2vx'], 5.0)); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] RQaXfEJ8f3o: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] RQaXfEJ8f3o: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 1778, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 1837, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 2974, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] RQaXfEJ8f3o: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by caf2022** [comment] 2024-07-09 20:25
This problem started to happen after I updated to the latest version yesterday

**Comment by bashonly** [comment] 2024-07-09 20:26
Duplicate of #10391

`yt-dlp --update-to master` (not fixed in nightly yet)

**Closed by bashonly** 2024-07-09 20:26 UTC
Labels: site-bug, triage
