### ISSUE TITLE
SonyLiv : Unable to download JSON metadata: HTTP Error 406: Not Acceptable 

### ISSUE THREAD

**Issue by vinraghav** [yt-dlp/yt-dlp#1838] opened 2021-11-29 19:00 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I saw a very similar issue [here](https://github.com/yt-dlp/yt-dlp/issues/991) which I guess was eventually resolved. I have been seeing this issue on the videos marked as "Latest" which are playable by me in the app with an account. I have a semi-premium account which allows premium playback with ads. Recently, they made this change on their app in which if you want to download an episode then you are going to have to watch ads first. I passed the cookies after logging in to make this work. This error doesn't appear on the videos that are not marked as latest.

### Verbose log

```shell
[debug] Command-line config: ['-vU', '--downloader=aria2c', '-v', '--cookies', 'sonyliv.com_cookies.txt', 'https://www.sonyliv.com/shows/kaun-banega-crorepati-1700000195/naya-hafta-nayi-seekh-1000146516?watch=true']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.7.12 (CPython 64bit) - Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] Using fake IP 117.244.185.35 (IN) as X-Forwarded-For
[SonyLIV] Downloading JSON metadata
[debug] [SonyLIV] Extracting URL: https://www.sonyliv.com/shows/kaun-banega-crorepati-1700000195/naya-hafta-nayi-seekh-1000146516?watch=true
[SonyLIV] 1000146516: Downloading JSON metadata
ERROR: [SonyLIV] 1000146516: Unable to download JSON metadata: HTTP Error 406: Not Acceptable (caused by <HTTPError 406: 'Not Acceptable'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 406: 'Not Acceptable'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/common.py", line 713, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 3295, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by pukkandan** [comment] 2021-12-09 19:25
Closing as duplicate of https://github.com/yt-dlp/yt-dlp/issues/1945

**Closed by pukkandan** 2021-12-09 19:25 UTC
Labels: bug
