### ISSUE TITLE
Tiktok support breaks

### ISSUE THREAD

**Issue by rcodo** [yt-dlp/yt-dlp#4099] opened 2022-06-18 07:22 UTC
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

us

### Example URLs

- https://www.tiktok.com/@fabianmagicofificial

### Description

Tiktok download not working anymore

### Verbose log

```shell
[debug] Command-line config: ['-v', '-o', '%(uploader)s/%(title)s.%(ext)s', '-f', 'best', 'https://www.tiktok.com/@fabianmagicofificial']
WARNING: "-f best" selects the best pre-merged format which is often not the best option.
         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.
         If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.9.10 (CPython 64bit) - macOS-12.4-arm64-arm-64bit
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] [tiktok:user] Extracting URL: https://www.tiktok.com/@fabianmagicofificial
[tiktok:user] fabianmagicofificial: Downloading webpage
ERROR: [tiktok:user] fabianmagicofificial: Unable to download webpage: The read operation timed out (caused by timeout('The read operation timed out')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by Lesmiscore** [comment] 2022-06-18 07:44
Duplicate of #3776

**Closed by Lesmiscore** 2022-06-18 07:44 UTC
Labels: duplicate, site:tiktok

**Comment by MinePlayersPE** [comment] 2022-06-18 07:45
1. Wrong tag
2. <img width="462" alt="a checklist tag saying to NOT POST DUPLICATES" src="https://user-images.githubusercontent.com/20515340/174428142-ee3457ea-6876-4816-ab45-76b88a50ccd8.png">
<img width="212" alt="search result demonstrating that TIKTOK has multiple OPEN ISSUES" src="https://user-images.githubusercontent.com/20515340/174428199-b9e38828-30b8-4a79-82d0-5dcd466f859c.png">
<img width="948" alt="a PINNED issue with the word IMPORTANT CAPITALIZED to " src="https://user-images.githubusercontent.com/20515340/174428093-03135843-ca93-4b70-a5a7-21136c1bd78f.png">
