### ISSUE TITLE
`Comcast_SSO`: Can no longer download DisneyNow videos that require credentials

### ISSUE THREAD

**Issue by DaftMink** [yt-dlp/yt-dlp#7841] opened 2023-08-15 04:28 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Recently I've been unable to download any DisneyNow videos that requires being signed into my provider to watch. I can still watch the videos fine in my browser and I use to be able to download the videos fine in the past, it just recently stopped working.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://disneynow.com/shows/pupstruction/season-01/episode-11-professor-frazzle-a-crabby-neighbor/vdka34060521', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--write-subs', '--cookies-from-browser', 'FireFox']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\Mitchell Thomas\AppData\Roaming\Mozilla\Firefox\Profiles\oyzxpvgc.default-release\cookies.sqlite"
Extracted 2869 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.14.182926 [876b70c8e] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n5.0-4-g911d7f167c-20220311 (setts), ffprobe n5.0-4-g911d7f167c-20220311
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1863 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.08.14.182926, Current version: nightly@2023.08.14.182926
Current Build Hash: 7f7cdae9ae8c2706352e1ca2314642026bf5afeb6c20fb76ec3e79cbb5fc6256
yt-dlp is up to date (nightly@2023.08.14.182926)
[Go] Extracting URL: https://disneynow.com/shows/pupstruction/season-01/episode-11-professor-frazzle-a-crabby-neighbor/vdka34060521
[Go] vdka34060521: Downloading JSON metadata
[debug] Loading ap-mvpd.DisneyChannels from cache
[Go] VDKA34060521: Downloading Provider Redirect Page
ERROR: [Go] vdka34060521: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\go.py", line 250, in _real_extract
  File "yt_dlp\extractor\adobepass.py", line 1490, in _extract_mvpd_auth
  File "yt_dlp\extractor\adobepass.py", line 1395, in post_form
  File "yt_dlp\extractor\common.py", line 1299, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1263, in _search_regex


D:\youtube-dl>
```

**Comment by bashonly** [comment] 2023-08-15 21:02
Related (same?) issue: #7495

**Comment by CeruleanSky** [comment] 2023-08-30 00:09
https://github.com/yt-dlp/yt-dlp/blob/099fb1b35cf835303306549f5113d1802d79c9c7/yt_dlp/extractor/adobepass.py#L1473=

change line 1473 of adobepass.py from `elif 'automatically signed in with' in provider_redirect_page:`
to  `elif ('automatically signed in with' in provider_redirect_page) or ('initInterstitialRedirect' in provider_redirect_page):`

I'll consider this a work around as I haven't seen enough of these pages to know if this is a proper or stable fix, but it works for me.

Here is the webpage that causes the current elif to fail so it is available to look at in case there is a better choice to be picked:
https://pastebin.com/6aNsFieW

**Comment by pukkandan** [comment] 2023-09-06 12:26
Closing as dupe of https://github.com/yt-dlp/yt-dlp/issues/516 since underlying issue appears to be the same.

**Closed by pukkandan** 2023-09-06 12:26 UTC
Labels: account-needed, geo-blocked, site-bug, triage, can-share-account

**Comment by howarmat** [comment] 2023-09-17 02:30
> I have problems playing video with the browser/apps so I looked into this.
> 
> https://github.com/yt-dlp/yt-dlp/blob/099fb1b35cf835303306549f5113d1802d79c9c7/yt_dlp/extractor/adobepass.py#L1473=
> 
> change line 1473 of adobepass.py from `elif 'automatically signed in with' in provider_redirect_page:` to `elif ('automatically signed in with' in provider_redirect_page) or ('initInterstitialRedirect' in provider_redirect_page):`
> 
> I'll consider this a work around as I haven't seen enough of these pages to know if this is a proper or stable fix, so needs testing, but it works for me. I don't have Vice so I can't test for #7495 but I suspect it would work there as well if @MrOctober77 wants to try it.
> 
> Here is the webpage that causes the current elif to fail so it is available to look at in case there is a better choice to be picked: https://pastebin.com/6aNsFieW

Thanks a ton with this fix!

**Comment by DaftMink** [comment] 2023-09-17 19:53
Can anyone compile the yt-dlp.exe with the changes suggested by CeruleanSky?. I've been checking the nightly build every day and it's yet to be resolved.

**Comment by MrOctober77** [comment] 2023-09-18 03:36
Editing adobepass.py worked for Vice TV.
