### ISSUE TITLE
some videos downloaded from twitter can't be played normally (long video perhaps)

### ISSUE THREAD

**Issue by CainXCain** [yt-dlp/yt-dlp#8623] opened 2023-11-19 17:05 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

HK

### Provide a description that is worded well enough to be understood

I downloaded some video from twitter and they can't be played normally in VLC, windows media player, pixel defeat media player: either can't open at all, or no sound, can't drag timeline(or draging timeline make the video content became blocks of colors)

In windows file info: no info or super high bit rate
![image](https://github.com/yt-dlp/yt-dlp/assets/74123674/6556db59-d5ef-43a8-bb9f-f2ace35a38b5)
(words from above: video length, frame width, frame height, data rate, total bit rate, frame rate)

I only find chrome can play them normally; use ffmpeg `ffmpeg -i test.mp4 test1.mp4` can fix the video itself, but yt-dlp should download it correctly.

seems this only happens to long videos(at least 15mins as I find, didn't test a lot videos), such videos on twitter are mostly porn videos so I tried but didn't find non-NSFW long enough videos.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
two examples here(warning: video content is porn but I can't find an example not porn)

yt-dlp.exe --cookies-from-browser chrome -a 1.txt -vU
[debug] Command-line config: ['--cookies-from-browser', 'chrome', '-a', '1.txt', '-vU']
[debug] Batch file urls: ['https://twitter.com/i/status/1697897432271794547']
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\vampy\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\vampy\AppData\Local\Google\Chrome\User Data\Local State"
Extracted 3237 cookies from chrome
[debug] cookie version breakdown: {'v10': 3268, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.11.18.232705 from yt-dlp/yt-dlp-nightly-builds [585d0ed9a] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110984-g2342c05e43-20230603 (setts), ffprobe N-110984-g2342c05e43-20230603
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1910 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2023.11.18.232705 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2023.11.18.232705 from yt-dlp/yt-dlp-nightly-builds)
[twitter] Extracting URL: https://twitter.com/i/status/1697897432271794547
[twitter] 1697897432271794547: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1697896700881580032
[twitter] 1697897432271794547: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, br, size, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1697896700881580032: Downloading 1 format(s): http-950
[debug] Invoking http downloader on "https://video.twimg.com/amplify_video/1697896700881580032/vid/464x808/p-aAd_g1u1TelkNI.mp4?tag=14"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: 哈利S - 天菜帅哥做爱长视频😍 [1697896700881580032].mp4
[download] 100% of   50.71MiB in 00:00:09 at 5.31MiB/s

------------

yt-dlp.exe --cookies-from-browser chrome -a 1.txt -vU
[debug] Command-line config: ['--cookies-from-browser', 'chrome', '-a', '1.txt', '-vU']
[debug] Batch file urls: ['https://twitter.com/i/status/1686930793082638336']
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\vampy\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\vampy\AppData\Local\Google\Chrome\User Data\Local State"
Extracted 3238 cookies from chrome
[debug] cookie version breakdown: {'v10': 3269, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.11.18.232705 from yt-dlp/yt-dlp-nightly-builds [585d0ed9a] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110984-g2342c05e43-20230603 (setts), ffprobe N-110984-g2342c05e43-20230603
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1910 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2023.11.18.232705 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2023.11.18.232705 from yt-dlp/yt-dlp-nightly-builds)
[twitter] Extracting URL: https://twitter.com/i/status/1686930793082638336
[twitter] 1686930793082638336: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 1686926079163076608
[twitter] 1686930793082638336: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, br, size, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1686926079163076608: Downloading 1 format(s): http-2176
[debug] Invoking http downloader on "https://video.twimg.com/amplify_video/1686926079163076608/vid/1280x720/HHDzGljObuj1OBC5.mp4?tag=14"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: ✨芒果宇宙🥭 - 🍁🍁剧情片，墙裂推荐！🍁🍁 #melody  女儿想要一辆吉普作为自己的圣诞礼物，但继父不同
意。女儿说你知道我在学校是个什么样的人么？继父表示想多了解了解。感觉餐桌上的互相试探比后面的做爱要有趣得多 —————————————————— 投稿💌：  @riliwanji777  @WanJibb_  @XiaoWanbb_   #日理万姬 [1686926079163076608].mp4
```

**Comment by bashonly** [comment] 2023-11-19 17:16
Duplicate of #8117

Video container is anomalous at the source. Nothing we can do

If it's an hls format, you can pass `--fixup force` to force a remux, which should fix the issue

If it's an http format, you could pass an `--exec` line to remux with ffmpeg, or else use `--remux mkv` if you're ok with a container other than mp4

**Closed by bashonly** 2023-11-19 17:16 UTC
Labels: site-bug, triage
