### ISSUE TITLE
[CNNArticle] None: Unable to extract cnn url

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#6167] opened 2023-02-05 22:13 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

anywhere

### Provide a description that is worded well enough to be understood

Test Link:
https://edition.cnn.com/2022/09/16/health/4-7-8-breathing-technique-relaxing-wellness/index.html

Most likely regex related

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -Uv -F "https://edition.cnn.com/2022/09/16/health/4-7-8-breathing-technique-relaxing-wellness/index.html"
[debug] Command-line config: ['-Uv', '-F', 'https://edition.cnn.com/2022/09/16/health/4-7-8-breathing-technique-relaxing-wellness/index.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd2508] (zip)
[debug] Python 3.10.9 (CPython arm64 64bit) - macOS-12.6.3-arm64-arm-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Extractor Plugins: SamplePluginIE
[debug] Post-Processor Plugins: SamplePluginPP
[debug] Loaded 1822 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[CNNArticle] Extracting URL: https://edition.cnn.com/2022/09/16/health/4-7-8-breathing-technique-relaxing-wellness/index.html
[CNNArticle] index.html: Downloading webpage
ERROR: [CNNArticle] None: Unable to extract cnn url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "./yt-dlp/yt_dlp/extractor/common.py", line 682, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/cnn.py", line 142, in _real_extract
    cnn_url = self._html_search_regex(r"video:\s*'([^']+)'", webpage, 'cnn url')
  File "./yt-dlp/yt_dlp/extractor/common.py", line 1266, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 1230, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by dirkf** [comment] 2023-02-06 07:10
This page has a `VideoObject` hidden in its `NewsArticle` ld+json block. The video resolution and bitrate are encoded in the media url.

**Comment by bashonly** [comment] 2023-02-07 01:24
Duplicate of #2640

**Closed by bashonly** 2023-02-07 01:24 UTC
Labels: duplicate, site-bug
