### ISSUE TITLE
cannot download ig story by adding username and password

### ISSUE THREAD

**Issue by ginkgog** [yt-dlp/yt-dlp#7408] opened 2023-06-24 15:17 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

n extractor error has occurred. (caused by KeyError('config')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ERROR: 3132125792765796653: An extractor error has occurred. (caused by KeyError('config')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment] 2023-06-24 15:20
Duplicate of #7328

workaround: pass cookies instead

disclaimer: instagram bans accounts that use yt-dlp

**Closed by bashonly** 2023-06-24 15:20 UTC
Labels: question

**Comment by ginkgog** [comment] 2023-06-24 16:29
how to use pass cookies any example? thank you:)

**Comment by bashonly** [comment] 2023-06-24 16:59
https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp
`--cookies cookies.txt` (replace `cookies.txt` with the actual path to your cookies file)
`--cookies-from-browser chrome` (or replace `chrome ` with the browser you are logged in with)

> disclaimer: instagram bans accounts that use yt-dlp
