### ISSUE TITLE
ZenYandex: Unable to extract metadata

### ISSUE THREAD

**Issue by hazyfossa** [yt-dlp/yt-dlp#8406] opened 2023-10-22 07:18 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Yt-dlp breaks on every video from dzen when trying to extract metadata. I think they did some sort of backend update over there at yandex, which broke the search regex. I already tried to fix it myself, but the i'm not familiar with yt-dlp's codebase and writing extractors for it. Would appreciate any help.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://dzen.ru/video/watch/6002240ff8b1af50bb2da5e3']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (pip)
[debug] Python 3.11.5 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 3.0.9 30 May 2023) 
[debug] exe versions: none 
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.42.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest 
Available version: stable@2023.10.13, Current version: stable@2023.10.13 
yt-dlp is up to date (stable@2023.10.13) 
[ZenYandex] Extracting URL: https://dzen.ru/video/watch/6002240ff8b1af50bb2da5e3 
[ZenYandex] 6002240ff8b1af50bb2da5e3: Downloading webpage 
[ZenYandex] 6002240ff8b1af50bb2da5e3: Redirecting 
ERROR: [ZenYandex] 6002240ff8b1af50bb2da5e3: Unable to extract metadata; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\test\.venv\Lib\site-packages\yt_dlp\extractor\common.py", line 715, in extract 
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\yt_dlp\extractor\yandexvideo.py", line 260, in _real_extract
    data_json = self._search_json(
                ^^^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\yt_dlp\extractor\common.py", line 1277, in _search_json
    json_string = self._search_regex(
                  ^^^^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\yt_dlp\extractor\common.py", line 1263, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment] 2023-10-22 11:55
Duplicate of #8275

**Closed by bashonly** 2023-10-22 11:55 UTC
Labels: site-bug, triage
