### ISSUE TITLE
ARD Audiothek

### ISSUE THREAD

**Issue by cyborgx7** [yt-dlp/yt-dlp#6364] opened 2023-02-26 22:44 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Germany

### Example URLs

- Entire show (Sendung): https://www.ardaudiothek.de/sendung/soundcheck/24035666/
- Single Episode: https://www.ardaudiothek.de/episode/soundcheck/helge-schneider-gorillaz-orbital-sunny-war/radioeins/12413409/

### Provide a description that is worded well enough to be understood

Official platform for the audio content of the biggest german public broadcaster. As far as I can see, all episodes are freely accessible without an account, with download links and a lot of metadata provided.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c0154]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux-5.15.93-1-MANJARO-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2022.12.07, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
```

**Comment by dirkf** [comment] 2023-02-27 10:22
https://github.com/ytdl-org/youtube-dl/pull/22349 but needs to be revised to use https://api.ardaudiothek.de/docs/#/web%2Fv1/get_web_v1_episode__id_.

**Comment by bashonly** [comment] 2023-06-02 20:01
Duplicate of #5605

**Closed by bashonly** 2023-06-02 20:01 UTC
Labels: site-request, patch-available
