### ISSUE TITLE
tiktok:sound is not working properly

### ISSUE THREAD

**Issue by Sunda001** [yt-dlp/yt-dlp#8879] opened 2023-12-29 16:22 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

when i try to execute download tiktok sound https://vt.tiktok.com/ZSNnkjXcK/ it occured errors. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(yt) [sakty@vps-iad yt-dlp-api]$ yt-dlp -vU -J https://vt.tiktok.com/ZSNnkjXcK/
[debug] Command-line config: ['-vU', '-J', 'https://vt.tiktok.com/ZSNnkjXcK/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp [24f827875] (pip)
[debug] Python 3.11.6 (CPython aarch64 64bit) - Linux-6.2.10-1-aarch64-ARCH-aarch64-with-glibc2.35 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.35)
[debug] exe versions: ffmpeg 6.1 (setts), ffprobe 6.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.44.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.11.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.11.16 from yt-dlp/yt-dlp)
[vm.tiktok] Extracting URL: https://vt.tiktok.com/ZSNnkjXcK/
[vm.tiktok] ZSNnkjXcK: Downloading webpage
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[tiktok:sound] Extracting URL: https://www.tiktok.com/music/suara-asli-Lana-7270868411033570053?_d=secCgYIASAHKAESPgo8k6dxRqZt0GqLo3cLODgjoRkOoFn7WO%2FYrgVGqJn6nMPQAsnQTLNJbQ1yfuBCOT8sLfGKdnmeWQttmCQqGgA%3D&_r=1&checksum=4d1f4106dcd4ab8544a13382ad5c9aaf2a05f0adc15a94fcd5d1c4e14d09b71f&sec_user_id=MS4wLjABAAAA8TnSgZh0RVh7x4LbQFc9HxixB-9jMIDFOYp0s5XIFRCRH04Vo4M1sDl6k10FDQJA&share_app_id=1180&share_link_id=69c10c6a-bb17-4c2a-a81c-98735821f774&share_music_id=7270868411033570053&sharer_language=en&social_share_type=7&source=h5_t&timestamp=1703848148&u_code=dea2jhblfbaia6&ug_btm=b2001%2Cb5171&ugbiz_name=UNKNOWN&user_id=6868923991672833025&utm_campaign=client_share&utm_medium=android&utm_source=copy
[download] Downloading playlist: 7270868411033570053
[tiktok:sound] 7270868411033570053: Downloading video list page 1
WARNING: [tiktok:sound] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:sound] 7270868411033570053: Downloading video list page 1
WARNING: [tiktok:sound] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:sound] 7270868411033570053: Downloading video list page 1
WARNING: [tiktok:sound] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:sound] 7270868411033570053: Downloading video list page 1
WARNING: [tiktok:sound] Expecting value in '': line 1 column 1 (char 0). Retrying (1/3)...
[tiktok:sound] 7270868411033570053: Downloading video list page 1
WARNING: [tiktok:sound] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:sound] 7270868411033570053: Downloading video list page 1
WARNING: [tiktok:sound] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:sound] 7270868411033570053: Downloading video list page 1
WARNING: [tiktok:sound] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:sound] 7270868411033570053: Downloading video list page 1
WARNING: [tiktok:sound] Expecting value in '': line 1 column 1 (char 0). Retrying (2/3)...
[tiktok:sound] 7270868411033570053: Downloading video list page 1
WARNING: [tiktok:sound] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:sound] 7270868411033570053: Downloading video list page 1
WARNING: [tiktok:sound] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:sound] 7270868411033570053: Downloading video list page 1
WARNING: [tiktok:sound] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:sound] 7270868411033570053: Downloading video list page 1
WARNING: [tiktok:sound] Expecting value in '': line 1 column 1 (char 0). Retrying (3/3)...
[tiktok:sound] 7270868411033570053: Downloading video list page 1
WARNING: [tiktok:sound] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[tiktok:sound] 7270868411033570053: Downloading video list page 1
WARNING: [tiktok:sound] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[tiktok:sound] 7270868411033570053: Downloading video list page 1
WARNING: [tiktok:sound] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[tiktok:sound] 7270868411033570053: Downloading video list page 1
ERROR: 7270868411033570053: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/sakty/dlp-serv/yt-dlp-api/yt/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 555, in decode
    return super().decode(s)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sakty/dlp-serv/yt-dlp-api/yt/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1013, in _parse_json
    return json.loads(
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/sakty/dlp-serv/yt-dlp-api/yt/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 563, in decode
    raise type(e)(f'{e.msg} in {s[e.pos-10:e.pos+10]!r}', s, e.pos)
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)

[tiktok:sound] Playlist 7270868411033570053: Downloading 1 items
[debug] The information of all playlist entries will be held in memory
[download] Finished downloading playlist: 7270868411033570053
{"id": "7270868411033570053", "_type": "playlist", "entries": [null], "original_url": "https://vt.tiktok.com/ZSNnkjXcK/", "webpage_url": "https://www.tiktok.com/music/suara-asli-Lana-7270868411033570053?_d=secCgYIASAHKAESPgo8k6dxRqZt0GqLo3cLODgjoRkOoFn7WO%2FYrgVGqJn6nMPQAsnQTLNJbQ1yfuBCOT8sLfGKdnmeWQttmCQqGgA%3D&_r=1&checksum=4d1f4106dcd4ab8544a13382ad5c9aaf2a05f0adc15a94fcd5d1c4e14d09b71f&sec_user_id=MS4wLjABAAAA8TnSgZh0RVh7x4LbQFc9HxixB-9jMIDFOYp0s5XIFRCRH04Vo4M1sDl6k10FDQJA&share_app_id=1180&share_link_id=69c10c6a-bb17-4c2a-a81c-98735821f774&share_music_id=7270868411033570053&sharer_language=en&social_share_type=7&source=h5_t&timestamp=1703848148&u_code=dea2jhblfbaia6&ug_btm=b2001%2Cb5171&ugbiz_name=UNKNOWN&user_id=6868923991672833025&utm_campaign=client_share&utm_medium=android&utm_source=copy", "webpage_url_basename": "suara-asli-Lana-7270868411033570053", "webpage_url_domain": "tiktok.com", "extractor": "tiktok:sound", "extractor_key": "TikTokSound", "requested_entries": [1], "playlist_count": 0, "epoch": 1703866868, "__files_to_move": {}, "_version": {"version": "2023.11.16", "current_git_head": null, "release_git_head": "24f827875c6ba513f12ed09a3aef2bbed223760d", "repository": "yt-dlp/yt-dlp"}}
```

**Comment by bashonly** [comment] 2023-12-29 16:27
Duplicate of #4329

**Closed by bashonly** 2023-12-29 16:27 UTC
Labels: duplicate, site-bug, site:tiktok
