### ISSUE TITLE
Crunchyroll URLs not being recognized by crunchyroll extractor

### ISSUE THREAD

**Issue by SavagePenguin21** [yt-dlp/yt-dlp#5395] opened 2022-10-29 18:16 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Around 2 weeks ago, I ran into the same issue with Crunchyroll that many people were having, where every attempted download was throwing a 403: forbidden error. I found the workaround in issue https://github.com/yt-dlp/yt-dlp/pull/5294: updating from Python version 3.8 to 3.10 indeed made this issue go away.

However, now every single video I attempt to download from Crunchyroll results in yt_dlp defaulting to the generic extractor, and not recognizing Crunchyroll at all. Downloads worked on all videos on there prior to the transition out of beta that many people experienced. I have tried several attempts, with no arguments at all and with cookies, and nothing has worked. I have not made any changes to my instance of yt_dlp or anything else, aside from upgrading to Python 3.10. Additionally, I just tried this on 3.8 and I'm now having the same issue, of it defaulting to the generic extractor.

Edit: Just realized this seems to be a duplicate of https://github.com/yt-dlp/yt-dlp/issues/5292. Please ignore.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--verbose', 'https://www.crunchyroll.com/watch/G9DUEJ002/meowys-whereabouts']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip)
[debug] Python 3.10.8 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-108640-g9e8a327e68-20221013 (setts), ffprobe N-108640-g9e8a327e68-20221013
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] [generic] Extracting URL: https://www.crunchyroll.com/watch/G9DUEJ002/meowys-whereabouts
[generic] meowys-whereabouts: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] meowys-whereabouts: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.crunchyroll.com/watch/G9DUEJ002/meowys-whereabouts
Traceback (most recent call last):
  File "C:\Users\***********\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\***********\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1553, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\***********\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\***********\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\generic.py", line 3062, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.crunchyroll.com/watch/G9DUEJ002/meowys-whereabouts
```

**Comment by bashonly** [comment] 2022-10-29 20:55
duplicate of #5292

**Closed by bashonly** 2022-10-29 20:55 UTC
Labels: site-bug, triage
