### ISSUE TITLE
91视频无法下载

### ISSUE THREAD

**Issue by daybreak-git** [yt-dlp/yt-dlp#6083] opened 2023-01-24 10:03 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

提示无法获取视频的名称报错

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 224, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/ytdlbot/ytdlbot/ytdl_bot.py", line 87, in wrapper
    return func(client, message)
  File "/ytdlbot/ytdlbot/ytdl_bot.py", line 362, in download_handler
    ytdl_download_entrance(bot_msg, client, url)
  File "/ytdlbot/ytdlbot/tasks.py", line 143, in ytdl_download_entrance
    ytdl_normal_download(bot_msg, client, url)
  File "/ytdlbot/ytdlbot/tasks.py", line 256, in ytdl_normal_download
    result = ytdl_download(url, temp_dir.name, bot_msg)
  File "/ytdlbot/ytdlbot/downloader.py", line 210, in ytdl_download
    result, err_msg = check_quota(detect_filesize(url), chat_id)
  File "/ytdlbot/ytdlbot/downloader.py", line 329, in detect_filesize
    info_dict = ydl.extract_info(url, download=False)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1491, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1520, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1012, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 952, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [91porn] 26ec66f6b16249ae097b: Unable to extract title; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pukkandan** [comment] 2023-01-24 10:08
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3256

**Closed by pukkandan** 2023-01-24 10:08 UTC
Labels: duplicate, incomplete, NSFW, site-bug
