### ISSUE TITLE
--limit-rate does not seem to work after the 2022.03.08.1 update

### ISSUE THREAD

**Issue by maxalentix** [yt-dlp/yt-dlp#3070] opened 2022-03-14 17:29 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I often use the --limit-rate switch with yt-dlp. After the 2022.03.08.1 update, this option stopped limiting the maximum download rate.
An example command that I am using:
yt-dlp -c -k --limit-rate 150000 -f  139 https://www.youtube.com/watch?v=HXCGKZjP8-M  or 
yt-dlp -c -k --limit-rate 150K -f  139 https://www.youtube.com/watch?v=HXCGKZjP8-M
The above command used to limit the download rate to 150KB per second, but now it downloads at over 3MB/s (my max rate)
I reverted to the previous version of yt-dlp and I confirmed that --limit-rate works as intended.

### Verbose log

```shell
$yt-dlp -vU -c -k --limit-rate 150000 -f  139 https://www.youtube.com/watch?v=HXCGKZjP8-M
[debug] Command-line config: ['-vU', '-c', '-k', '--limit-rate', '150000', '-f', '139', 'https://www.youtube.com/watch?v=HXCGKZjP8-M']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-104-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Crypto, secretstorage, mutagen, sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=HXCGKZjP8-M
[youtube] HXCGKZjP8-M: Downloading webpage
[youtube] HXCGKZjP8-M: Downloading android player API JSON
[debug] Loading youtube-nsig.87b9576a from cache
[debug] [youtube] Decrypted nsig WVOPcdAuueamDKhtNR => g7r4QfRQz9veqw
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] HXCGKZjP8-M: Downloading 1 format(s): 139
[debug] Invoking downloader on "https://rr2---sn-cxaaj5o5q5-tt1r.googlevideo.com/videoplayback?expire=1647300435&ei=83ovYpPLKYiyiwTboJ2QBQ&ip=142.180.143.13&id=o-ANsy3z2Z8HlBWwQcj6OwYdM5KVF3kBkxjEmADiZ1skK6&itag=139&source=youtube&requiressl=yes&mh=Qg&mm=31%2C26&mn=sn-cxaaj5o5q5-tt1r%2Csn-t0a7sn7d&ms=au%2Conr&mv=m&mvi=2&pl=21&initcwndbps=1621250&vprv=1&mime=audio%2Fmp4&gir=yes&clen=3077058&dur=504.430&lmt=1645886328804698&mt=1647278468&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJYTDVZyThLOVrM5vNpTcn6kW7kXPEBlYMvQCJeScA6fAiEAmY3bOuG9DhqUZLcpFmVjt--gNT072D-ahT3vVH2eCps%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgGawUtGT5tvaJcEsSAXSEVeUgjTol4p8IrbHB7aMRUW0CIQC2cz-IpA-aqYGE-n5xoizkFSL1o0ITJ0DVqnWKvuPDEg%3D%3D"
[download] Destination: Spark Plug Experiment and MPG [HXCGKZjP8-M].m4a
[download] 100% of 2.93MiB in 00:01
[FixupM4a] Correcting container of "Spark Plug Experiment and MPG [HXCGKZjP8-M].m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Spark Plug Experiment and MPG [HXCGKZjP8-M].m4a' -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags +faststart 'file:Spark Plug Experiment and MPG [HXCGKZjP8-M].temp.m4a'
```

**Comment by Lesmiscore** [comment] 2022-03-14 17:31
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2996

**Closed by Lesmiscore** 2022-03-14 17:31 UTC
Labels: bug, triage

**Comment by maxalentix** [comment] 2022-03-14 17:40
My bad. When I searched for similar issues, I used the search criteria:  **is:issue is:open --limit-rate**
