### ISSUE TITLE
[Broken] nick.de

### ISSUE THREAD

**Issue by BCellar** [yt-dlp/yt-dlp#370] opened 2021-06-02 20:57 UTC
## Checklist

- [x] I'm reporting a broken site support
- [xI've verified that I'm running yt-dlp version **2021.06.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
./yt-dlp https://www.nick.de/episodes/fkwvs6/avatar-der-herr-der-elemente-aang-erwacht-staffel-3-ep-1
[nick.de] avatar-der-herr-der-elemente-aang-erwacht-staffel-3-ep-1: Downloading webpage
[nick.de] c51c627c-7a9c-11e0-8fe5-0026b9414f30: Downloading JSON metadata
[nick.de] c51c627c-7a9c-11e0-8fe5-0026b9414f30: Downloading info
ERROR: Unable to download XML: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
bernd@knight:~/yt-dlc$ ./yt-dlp -v https://www.nick.de/episodes/fkwvs6/avatar-der-herr-der-elemente-aang-erwacht-staffel-3-ep-1
[debug] Command-line config: ['-v', 'https://www.nick.de/episodes/fkwvs6/avatar-der-herr-der-elemente-aang-erwacht-staffel-3-ep-1']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.06.01 (zip)
[debug] Python version 3.8.5 (CPython 64bit) - Linux-5.8.0-53-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [nick.de] Extracting URL: https://www.nick.de/episodes/fkwvs6/avatar-der-herr-der-elemente-aang-erwacht-staffel-3-ep-1
[nick.de] avatar-der-herr-der-elemente-aang-erwacht-staffel-3-ep-1: Downloading webpage
[nick.de] c51c627c-7a9c-11e0-8fe5-0026b9414f30: Downloading JSON metadata
[nick.de] c51c627c-7a9c-11e0-8fe5-0026b9414f30: Downloading info
ERROR: Unable to download XML: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "./yt-dlp/yt_dlp/extractor/common.py", line 675, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3062, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)


```

## Description

Trying to download a video from nick.de results in a "Internal Server Error".

**Comment by pukkandan** [comment] 2021-06-02 21:10
Duplicate of #169

**Closed by pukkandan** 2021-06-02 21:10 UTC
