### ISSUE TITLE
download from douyin dosen't work

### ISSUE THREAD

**Issue by neohob** [yt-dlp/yt-dlp#3946] opened 2022-06-02 12:52 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I'm downloading video from douyin, screen output cookies issues, so I use --cookies-from-browser  chrome args, also I logined on chrome, but still dosen't work. 

### Verbose log

```shell
yt-dlp --cookies-from-browser  chrome  -vU https://www.douyin.com/video/7084108804954033444
[debug] Command-line config: ['--cookies-from-browser', 'chrome', '-vU', 'https://www.douyin.com/video/7084108804954033444']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.9.13 (CPython 64bit) - macOS-12.4-x86_64-i386-64bit
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/neo/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
[Cookies] Extracted 2485 cookies from chrome
[debug] cookie version breakdown: {'v10': 2462, 'other': 0, 'unencrypted': 23}
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [Douyin] Extracting URL: https://www.douyin.com/video/7084108804954033444
[Douyin] 7084108804954033444: Downloading video details
WARNING: [Douyin] 7084108804954033444: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; Retrying with feed workaround
[Douyin] 7084108804954033444: Downloading video feed
WARNING: [Douyin] 7084108804954033444: Unable to find video in feed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; Retrying with webpage
[Douyin] 7084108804954033444: Downloading webpage
ERROR: [Douyin] 7084108804954033444: Fresh cookies (not necessarily logged in) are needed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/tiktok.py", line 852, in _real_extract
    raise ExtractorError('Fresh cookies (not necessarily logged in) are needed')
```

**Comment by gamer191** [comment] 2022-06-02 13:11
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3897, but in my opinion #3897 should be closed, because it's currently marked as incomplete and it doesn't have any verbose logs

**Comment by Lesmiscore** [comment] 2022-06-02 13:19
Have you tried re-exporting cookies? (as the error message suggests)

cc @MinePlayersPE

**Comment by gamer191** [comment] 2022-06-02 13:27
> I logined on chrome

The error message says that the cookies shouldn't necessarily be "logged in" cookies. Maybe try visiting the website, but not logging in, on a different browser/profile

**Comment by gamer191** [comment] 2022-06-03 02:00
> > > I logined on chrome
> > 
> > 
> > The error message says that the cookies shouldn't necessarily be "logged in" cookies. Maybe try visiting the website, but not logging in, on a different browser/profile
> 
> yes, I use another not loggined browser, it works

Well then I guess this issue has been solved. That said, it's up to a maintainer whether to close this, because the `fresh cookies are needed` error is a bug (at least according to the verbose log).

@neohob please don't close this issue

**Comment by neohob** [comment] 2022-06-03 04:39
> > > I logined on chrome
> > 
> > 
> > The error message says that the cookies shouldn't necessarily be "logged in" cookies. Maybe try visiting the website, but not logging in, on a different browser/profile
> 
> yes, I use another not loggined browser, it works

not stable, sometimes still got ERROR message: Fresh cookies (not necessarily logged in) are needed;

**Comment by pyunpack** [comment] 2022-06-24 21:27
> > > > I logined on chrome
> > > 
> > > 
> > > The error message says that the cookies shouldn't necessarily be "logged in" cookies. Maybe try visiting the website, but not logging in, on a different browser/profile
> > 
> > 
> > yes, I use another not loggined browser, it works
> 
> not stable, sometimes still got ERROR message: Fresh cookies (not necessarily logged in) are needed;

I was able to download now with `--cookies-from-browser  chrome` (firstly login in chrome). 
Without this flag, still got ERROR message: `Fresh cookies (not necessarily logged in) are needed;`

**Comment by pukkandan** [comment] 2022-07-02 14:21
Duplicate of #2267

**Closed by pukkandan** 2022-07-02 14:21 UTC
Labels: duplicate, site-bug, site:tiktok
