### ISSUE TITLE
cannot choose 22 format anymore

### ISSUE THREAD

**Issue by gituser23234235234887** [yt-dlp/yt-dlp#9409] opened 2024-03-10 02:36 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

so I tried downloading some videos today, last time I used yt-dlp was a few months ago.
so I always would just choose 720p format 22, but now I cant find it anymore. highest mp4 with both video and audio is 480p format 18.
is it because yt-dlp has been limited? or some other reason?
this is the video I was getting: https://www.youtube.com/watch?v=gucKRNrarVo

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=gucKRNrarVo', '-F', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (debian*)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-100-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5, websockets-9.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=gucKRNrarVo
[youtube] gucKRNrarVo: Downloading webpage
[youtube] gucKRNrarVo: Downloading ios player API JSON
[youtube] gucKRNrarVo: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] gucKRNrarVo: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] gucKRNrarVo: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] gucKRNrarVo: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig M6zujmCZ1j4mjeu- => h5Pk5uQ2Uai4Yg
[debug] Loading youtube-nsig.c48a9559 from cache
[debug] [youtube] Decrypted nsig waFOucC8_A3DFypc => Nm74rAv031yaFA
[youtube] gucKRNrarVo: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for gucKRNrarVo:
ID  EXT   RESOLUTION FPS CH │  FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb3 mhtml 48x27        0    │                 mhtml │ images                                  storyboard
sb2 mhtml 80x45        1    │                 mhtml │ images                                  storyboard
sb1 mhtml 160x90       1    │                 mhtml │ images                                  storyboard
sb0 mhtml 320x180      1    │                 mhtml │ images                                  storyboard
233 mp4   audio only        │                 m3u8  │ audio only          unknown             Default, IOS
234 mp4   audio only        │                 m3u8  │ audio only          unknown             Default, IOS
139 m4a   audio only      2 │   1.17MiB   49k https │ audio only          mp4a.40.5   49k 22k low, IOS, m4a_dash
249 webm  audio only      2 │   1.15MiB   48k https │ audio only          opus        48k 48k low, WEB, webm_dash
250 webm  audio only      2 │   1.53MiB   64k https │ audio only          opus        64k 48k low, WEB, webm_dash
140 m4a   audio only      2 │   3.09MiB  130k https │ audio only          mp4a.40.2  130k 44k medium, IOS, m4a_dash
251 webm  audio only      2 │   3.04MiB  127k https │ audio only          opus       127k 48k medium, WEB, webm_dash
269 mp4   256x144     24    │ ~ 4.15MiB  170k m3u8  │ avc1.4D400C    170k video only          IOS
160 mp4   256x144     24    │   1.85MiB   78k https │ avc1.4D400C     78k video only          144p, IOS, mp4_dash
603 mp4   256x144     24    │ ~ 3.73MiB  153k m3u8  │ vp09.00.11.08  153k video only          IOS
278 webm  256x144     24    │   1.85MiB   77k https │ vp09.00.11.08   77k video only          144p, IOS, webm_dash
229 mp4   426x240     24    │ ~ 7.55MiB  309k m3u8  │ avc1.4D4015    309k video only          IOS
133 mp4   426x240     24    │   3.79MiB  159k https │ avc1.4D4015    159k video only          240p, IOS, mp4_dash
604 mp4   426x240     24    │ ~ 6.82MiB  279k m3u8  │ vp09.00.20.08  279k video only          IOS
242 webm  426x240     24    │   3.79MiB  159k https │ vp09.00.20.08  159k video only          240p, IOS, webm_dash
230 mp4   640x360     24    │ ~15.91MiB  652k m3u8  │ avc1.4D401E    652k video only          IOS
134 mp4   640x360     24    │   6.79MiB  284k https │ avc1.4D401E    284k video only          360p, IOS, mp4_dash
18  mp4   640x360     24  2 │ ≈10.10MiB  414k https │ avc1.42001E         mp4a.40.2       44k 360p, WEB
605 mp4   640x360     24    │ ~13.27MiB  543k m3u8  │ vp09.00.21.08  543k video only          IOS
243 webm  640x360     24    │   6.76MiB  283k https │ vp09.00.21.08  283k video only          360p, IOS, webm_dash
231 mp4   854x480     24    │ ~22.37MiB  916k m3u8  │ avc1.4D401E    916k video only          IOS
135 mp4   854x480     24    │  11.12MiB  466k https │ avc1.4D401E    466k video only          480p, IOS, mp4_dash
606 mp4   854x480     24    │ ~21.49MiB  880k m3u8  │ vp09.00.30.08  880k video only          IOS
244 webm  854x480     24    │  11.58MiB  485k https │ vp09.00.30.08  485k video only          480p, IOS, webm_dash
232 mp4   1280x720    24    │ ~54.97MiB 2251k m3u8  │ avc1.4D401F   2251k video only          IOS
136 mp4   1280x720    24    │  27.35MiB 1146k https │ avc1.4D401F   1146k video only          720p, IOS, mp4_dash
609 mp4   1280x720    24    │ ~40.11MiB 1643k m3u8  │ vp09.00.31.08 1643k video only          IOS
247 webm  1280x720    24    │  22.30MiB  935k https │ vp09.00.31.08  935k video only          720p, IOS, webm_dash
```

**Comment by bashonly** [comment] 2024-03-10 04:28
It's due to this:
```
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] gucKRNrarVo: Downloading android player API JSON
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

This issue has been fixed in master/nightly. 

To install:
https://github.com/yt-dlp/yt-dlp/wiki/Installation
https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest

Or else wait for the next stable release, which will be happening soon.

Closing as duplicate of #9316

**Closed by bashonly** 2024-03-10 04:28 UTC
Labels: question
