### ISSUE TITLE
Option to Select thumbnail id from --list-thumbnail?

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#2087] opened 2021-12-22 19:20 UTC
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I usually prefer the "highest quality" jpgs over the "highest quality" webps.

There is a `--list-thumbnails` but no option to select and download specific thumbnail ID afaik, unless I'm mistaken?

I'm looking for a `-f` equivalent for selecting thumbnail IDs from `--list-thumbnails`?

Thank you for any help.

**Comment by pukkandan** [comment] 2021-12-22 19:21
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/237

**Closed by pukkandan** 2021-12-22 19:21 UTC
Labels: question

**Comment by barkoder** [comment] 2021-12-22 19:49
I could have sworn I searched the issue tracker for this before hitting submit.

Sorry. My bad.

**Comment by pukkandan** [comment] 2021-12-22 20:00
np. It's a pretty old and inactive issue. So of all the duplicate issues I get, this one I can understand
