### ISSUE TITLE
Slow execution time on Macos

### ISSUE THREAD

**Issue by aandrew-me** [yt-dlp/yt-dlp#10826] opened 2024-08-22 19:52 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Execution of any command takes a long time on Macos with intel chip.

Just executing the command to check version takes around 20 seconds

```
❯ time ./yt-dlp_macos --version
2024.08.06

________________________________________________________
Executed in   19.25 secs      fish           external
   usr time  700.52 millis  204.00 micros  700.32 millis
   sys time  364.98 millis  788.00 micros  364.19 millis
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.08.21.071743 from yt-dlp/yt-dlp-master-builds [6f9e65374] (darwin_exe)
[debug] Python 3.12.4 (CPython x86_64 64bit) - macOS-14.6.1-x86_64-i386-64bit (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.08.21.071743 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.08.21.071743 from yt-dlp/yt-dlp-master-builds)
```

**Comment by bashonly** [comment] 2024-08-22 20:00
Duplicate of #10425

> > This could be caused by MacOS Notarisation scanning all the files in the folder, does this continue to happen after the first time(s) you run it?
> 
> Yeah, this is my best guess too: some sort of Apple security scanning is happening.
> 
> `yt-dlp_macos` is a pyinstaller-bundled "onefile" executable, which means every time you execute it, it first needs to unpack its contents (~30-50MB of shared libraries and script files) into a temporary directory before yt-dlp itself is executed. These temp files are cleaned up once the executable has finished, so the security scanning would be invoked on every run, not just the first run.
> 
> An alternative would be the `yt-dlp_macos.zip` "onedir" build, where you unpack it yourself into a directory upon installation and no further unpacking is ever needed. The downside with the onedir build is that you can't use the yt-dlp self-updater (`-U`/`--update-to`); you would need to manually download updates from Github.
> 
> Another alternative is installing with [homebrew](https://brew.sh). While not an official channel for yt-dlp releases, brew is a very well-managed project that is quick to push updates of yt-dlp. (This is not a viable option if you require yt-dlp to have browser impersonation support via `curl_cffi`, though.)

**Closed by bashonly** 2024-08-22 20:00 UTC
Labels: bug, triage
