### ISSUE TITLE
Display progress of ffmpeg calls

### ISSUE THREAD

**Issue by WillPittenger** [yt-dlp/yt-dlp#4490] opened 2022-07-30 06:04 UTC
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When yt-dlp calls ffmpeg, it uses ffmpeg.exe rather than their API.  It then redirects the output from ffmpeg to the nul device.  So the user has no idea how much longer ffmpeg is going to need.  They might think it or yt-dlp hung.  During some of these calls, if the user interrupts the process with Ctrl-C and then restarts it, yt-dlp thinks the call to ffmpeg completed successfully and proceeds to the next video.

I think the API should be used.  That would then allow yt-dlp to display a progress via ffmpeg's callback routines.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by HobbyistDev** [comment] 2022-07-30 06:48
I think the title is a bit misleading. You want yt-dlp to use ffmpeg api instead ffmpeg exe, right?. If not, i think this is duplicate of #1720 or #1317

**Comment by WillPittenger** [comment] 2022-07-30 06:59
#1720 is a good match.

**Comment by pukkandan** [comment] 2022-07-30 08:42
ffmpeg has no API for Python. (It does have one for C by virtue of being written in C. But even that is not well documented). The closest we have is libraries like https://github.com/kkroening/ffmpeg-python, which is actually just a wrapper around the CLI. There isn't much point in using them over writing owr own wrappers like #2475 

As for progress reporting, duplicate of #1720

**Closed by pukkandan** 2022-07-30 08:42 UTC
Labels: enhancement, triage
