### ISSUE TITLE
Funimation error

### ISSUE THREAD

**Issue by nyxtyr** [yt-dlp/yt-dlp#2211] opened 2022-01-02 23:33 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

When trying to list the information for this episode it is unable to

### Verbose log

```shell
[debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '--cookies', 'funimation.com_cookies.txt', '--list-formats', 'https://www.funimation.com/v/a-certain-magical-index/the-amakusa-church', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_dir)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 2021-12-30-git-12f21849e5-full_build-www.gyan.dev (setts), ffprobe 2021-12-30-git-12f21849e5-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[funimation:page] Logging in
[debug] [funimation:page] Extracting URL: https://www.funimation.com/v/a-certain-magical-index/the-amakusa-church
[funimation:page] a-certain-magical-index_the-amakusa-church: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/93386
[Funimation] 93386: Downloading player webpage for 93386
ERROR: [Funimation] 93386: Unable to extract show data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\funimation.py", line 193, in _real_extract
  File "yt_dlp\extractor\funimation.py", line 171, in _get_episode
  File "yt_dlp\extractor\common.py", line 1173, in _search_regex
```

**Comment by pukkandan** [comment] 2022-01-10 09:16
#2255 is a duplicate of this

**Closed by pukkandan** 2022-01-10 09:16 UTC
Labels: site-bug, triage
