### ISSUE TITLE
Incorrect thumbnails for YouTube Music

### ISSUE THREAD

**Issue by probablykasper** [yt-dlp/yt-dlp#3542] opened 2022-04-24 11:19 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When downloading YouTube Music URLs, a 16x9 thumbnail is downloaded, even though YouTube Music thumbnails should be 1x1.

Example URL: https://music.youtube.com/watch?v=oun1bb16PDM

Actual downloaded thumbnail:
![Ryllz - Topic - Nemesis copy converted](https://user-images.githubusercontent.com/11315492/164973956-44bd9f2c-cb4b-4345-9bbe-85ea38e4c292.jpg)

Expected thumbnail:
![unnamed](https://user-images.githubusercontent.com/11315492/164973966-ea763d05-75d4-449e-9ce9-17276c90be9e.jpg)
URL: https://lh3.googleusercontent.com/6d9B87eJB9GKlxTWWLubvLnDF_PTDvsoRkxPTkNs2KmdyLai-zJ7roHmA0u_HZpuHvl0mLlm1wO1di1u=s0

### Verbose log

```shell
N/A
```

**Comment by pukkandan** [comment] 2022-04-24 11:56
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/622

**Closed by pukkandan** 2022-04-24 11:56 UTC
Labels: duplicate, site-enhancement
