### ISSUE TITLE
How to download video from Douyin

### ISSUE THREAD

**Issue by k15fb-mmo** [yt-dlp/yt-dlp#10409] opened 2024-07-10 02:56 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp -vU -f "bv*[vcodec^=avc]+ba[ext=m4a]/b[ext=mp4]/b" --cookies cookie.txt https://www.douyin.com/video/7336481666707229992

[Douyin] Extracting URL: https://www.douyin.com/video/7336481666707229992
[Douyin] 7336481666707229992: Downloading web detail JSON
WARNING: [Douyin] 7336481666707229992: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
ERROR: [Douyin] 7336481666707229992: Fresh cookies (not necessarily logged in) are needed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\tiktok.py", line 1327, in _real_extract

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU -f "bv*[vcodec^=avc]+ba[ext=m4a]/b[ext=mp4]/b" --cookies cookie.txt https://www.douyin.com/video/7336481666707229992
[debug] Command-line config: ['-vU', '-f', 'bv*[vcodec^=avc]+ba[ext=m4a]/b[ext=mp4]/b', '--cookies', 'cookie.txt', 'https://www.douyin.com/video/7336481666707229992']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.02.232715 from yt-dlp/yt-dlp-nightly-builds [d28aa87e2] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.2.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.07.09.232843/SHA2-256SUMS
Current version: nightly@2024.07.02.232715 from yt-dlp/yt-dlp-nightly-builds
Latest version: nightly@2024.07.09.232843 from yt-dlp/yt-dlp-nightly-builds
Current Build Hash: 0b6dfc829e6feb94a53893a2c46d713831ffb18dcc6fa52d7d6ef9032ef82376
Updating to nightly@2024.07.09.232843 from yt-dlp/yt-dlp-nightly-builds ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.07.09.232843/yt-dlp.exe
Updated yt-dlp to nightly@2024.07.09.232843 from yt-dlp/yt-dlp-nightly-builds
[debug] Restarting: C:\bin\yt-dlp.exe -vU -f "bv*[vcodec^=avc]+ba[ext=m4a]/b[ext=mp4]/b" --cookies cookie.txt https://www.douyin.com/video/7336481666707229992
[debug] Command-line config: ['-vU', '-f', 'bv*[vcodec^=avc]+ba[ext=m4a]/b[ext=mp4]/b', '--cookies', 'cookie.txt', 'https://www.douyin.com/video/7336481666707229992']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.09.232843 from yt-dlp/yt-dlp-nightly-builds [d2189d3d3] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.2.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.07.09.232843 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.07.09.232843 from yt-dlp/yt-dlp-nightly-builds)
[Douyin] Extracting URL: https://www.douyin.com/video/7336481666707229992
[Douyin] 7336481666707229992: Downloading web detail JSON
WARNING: [Douyin] 7336481666707229992: Failed to parse JSON: Expecting value in '': line 1 column 1 (char 0)
ERROR: [Douyin] 7336481666707229992: Fresh cookies (not necessarily logged in) are needed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\tiktok.py", line 1327, in _real_extract
```

**Comment by bashonly** [comment] 2024-07-10 03:12
The extractor is currently broken. Closing as duplicate of #9667

**Closed by bashonly** 2024-07-10 03:12 UTC
Labels: duplicate, site-bug, site:tiktok
