### ISSUE TITLE
yt-dlp is not supporting globoplay live

### ISSUE THREAD

**Issue by punkstarbr** [yt-dlp/yt-dlp#9033] opened 2024-01-20 02:36 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brasil

### Example URLs

https://globoplay.globo.com/agora-na-tv/
https://globoplay.globo.com/globonews/ao-vivo/7339101/
https://globoplay.globo.com/sportv/ao-vivo/7339108/
https://globoplay.globo.com/multishow/ao-vivo/7339131/
https://globoplay.globo.com/bbb-24-acompanhe-a-casa/ao-vivo/244881/
https://globoplay.globo.com/bbb-24-segue-o-lider/ao-vivo/244887/

### Provide a description that is worded well enough to be understood

need a login and password to access this channels live, and a plan if you watch outside Brasil, i want can use yt-dlp to have a .m3u8 link for the livestream from GloboPlay, they have valid for 24 horas or less time

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\SWITCHER6>yt-dlp -v --cookies-from-browser chrome https://globoplay.globo.com/tv-globo/ao-vivo/6120663/
[debug] Command-line config: ['-v', '--cookies-from-browser', 'chrome', 'https://globoplay.globo.com/tv-globo/ao-vivo/6120663/']
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\SWITCHER6\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\SWITCHER6\AppData\Local\Google\Chrome\User Data\Local State"
Extracted 351 cookies from chrome
[debug] cookie version breakdown: {'v10': 351, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1-full_build-www.gyan.dev (setts), ffprobe 6.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[GloboArticle] Extracting URL: https://globoplay.globo.com/tv-globo/ao-vivo/6120663/
[GloboArticle] 6120663: Downloading webpage
[download] Downloading playlist: TV Globo Ao Vivo Online Grátis | Assista no Globoplay
[GloboArticle] Playlist TV Globo Ao Vivo Online Grátis | Assista no Globoplay: Downloading 0 items
[download] Finished downloading playlist: TV Globo Ao Vivo Online Grátis | Assista no Globoplay





yt-dlp -v --cookies-from-browser chrome https://globoplay.globo.com/bbb-24-segue-o-lider/ao-vivo/244887/
[debug] Command-line config: ['-v', '--cookies-from-browser', 'chrome', 'https://globoplay.globo.com/bbb-24-segue-o-lider/ao-vivo/244887/']
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\SWITCHER6\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\SWITCHER6\AppData\Local\Google\Chrome\User Data\Local State"
Extracted 351 cookies from chrome
[debug] cookie version breakdown: {'v10': 351, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1-full_build-www.gyan.dev (setts), ffprobe 6.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[GloboArticle] Extracting URL: https://globoplay.globo.com/bbb-24-segue-o-lider/ao-vivo/244887/
[GloboArticle] 244887: Downloading webpage
[download] Downloading playlist: Assistir BBB 24 - Segue o Líder Ao Vivo | Globoplay
[GloboArticle] Playlist Assistir BBB 24 - Segue o Líder Ao Vivo | Globoplay: Downloading 0 items
[download] Finished downloading playlist: Assistir BBB 24 - Segue o Líder Ao Vivo | Globoplay


C:\Users\SWITCHER6>yt-dlp -v -g --cookies-from-browser chrome https://globoplay.globo.com/bbb-24-segue-o-lider/ao-vivo/244887/
[debug] Command-line config: ['-v', '-g', '--cookies-from-browser', 'chrome', 'https://globoplay.globo.com/bbb-24-segue-o-lider/ao-vivo/244887/']
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\SWITCHER6\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\SWITCHER6\AppData\Local\Google\Chrome\User Data\Local State"
Extracted 351 cookies from chrome
[debug] cookie version breakdown: {'v10': 351, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1-full_build-www.gyan.dev (setts), ffprobe 6.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[GloboArticle] Extracting URL: https://globoplay.globo.com/bbb-24-segue-o-lider/ao-vivo/244887/
[GloboArticle] 244887: Downloading webpage
[download] Downloading playlist: Assistir BBB 24 - Segue o Líder Ao Vivo | Globoplay
[GloboArticle] Playlist Assistir BBB 24 - Segue o Líder Ao Vivo | Globoplay: Downloading 0 items
[download] Finished downloading playlist: Assistir BBB 24 - Segue o Líder Ao Vivo | Globoplay



C:\Users\SWITCHER6>yt-dlp -v -g --cookies-from-browser chrome https://globoplay.globo.com/bbb-24-mosaico-bbb/ao-vivo/10101606/
[debug] Command-line config: ['-v', '-g', '--cookies-from-browser', 'chrome', 'https://globoplay.globo.com/bbb-24-mosaico-bbb/ao-vivo/10101606/']
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\SWITCHER6\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\SWITCHER6\AppData\Local\Google\Chrome\User Data\Local State"
Extracted 351 cookies from chrome
[debug] cookie version breakdown: {'v10': 351, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1-full_build-www.gyan.dev (setts), ffprobe 6.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[GloboArticle] Extracting URL: https://globoplay.globo.com/bbb-24-mosaico-bbb/ao-vivo/10101606/
[GloboArticle] 10101606: Downloading webpage
[download] Downloading playlist: Assistir BBB 24 - Mosaico BBB Ao Vivo | Globoplay
[GloboArticle] Playlist Assistir BBB 24 - Mosaico BBB Ao Vivo | Globoplay: Downloading 0 items
[download] Finished downloading playlist: Assistir BBB 24 - Mosaico BBB Ao Vivo | Globoplay
```

**Comment by bashonly** [comment] 2024-02-06 18:08
Duplicate of #4879

**Closed by bashonly** 2024-02-06 18:08 UTC
Labels: site-enhancement, triage

**Comment by strikeinthehouse** [comment] 2025-06-24 18:03
i think this is not working actually
