### ISSUE TITLE
`--sub-format all`

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6832] opened 2023-04-16 08:32 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Can we have a `--sub-format all` switch analogous to `--sub-langs all` ?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment] 2023-04-16 09:53
Duplicate of your own issue? https://github.com/yt-dlp/yt-dlp/issues/2276

**Closed by pukkandan** 2023-04-16 09:53 UTC
Labels: enhancement, triage

**Comment by pukkandan** [comment] 2023-04-16 10:08
When I get time, I'll try to write up a single implementation I have in mind that'll solve all these subtitle selection issues in one go. Though, my idea is reliant on #4846 and so will likely take a while to get done.
