### ISSUE TITLE
[Funimation] Mature Content

### ISSUE THREAD

**Issue by CZeil** [yt-dlp/yt-dlp#2634] opened 2022-02-04 03:36 UTC
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.03**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

It would be possible that through the user credentials can detect if we have enabled the mature content, since currently it can only be detected through the user cookie file.

**Comment by pukkandan** [comment] 2022-02-04 04:13
I don't understand. Provide examples. Since you say "it can only be detected through the user cookie file.", include verbose logs showing it "working" with cookies and "not working" with password

**Comment by CZeil** [comment] 2022-02-04 14:11
> I don't understand. Provide examples. Since you say "it can only be detected through the user cookie file.", include verbose logs showing it "working" with cookies and "not working" with password

Sorry I suck at explaining 😅.

What I mean is that there are chapters or series that Funimation lists as mature content. In order to download them you need an account that allows mature content, but this only works through cookies. I'll show you the verbose log so you know what I'm talking about.

Example without user credentials
'''
C:\youtube-dl>yt-dlp https://www.funimation.com/v/arifureta-from-commonplace-to-worlds-strongest/the-monster-of-the-abyss --no-check-certificates -v
[debug] Command-line config: ['https://www.funimation.com/v/arifureta-from-commonplace-to-worlds-strongest/the-monster-of-the-abyss', '--no-check-certificates', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: b76142822
[debug] Python version 3.9.7 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg n5.0-20220114 (setts), ffprobe n5.0-20220114
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[funimation:page] Checking geo-location
[debug] [funimation:page] Extracting URL: https://www.funimation.com/v/arifureta-from-commonplace-to-worlds-strongest/the-monster-of-the-abyss
[funimation:page] arifureta-from-commonplace-to-worlds-strongest_the-monster-of-the-abyss: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/925446
[Funimation] 925446: Downloading player webpage for 925446
[Funimation] the-monster-of-the-abyss: Downloading Simulcast japanese (917148) JSON
WARNING: [Funimation] Funimation said: Error 2 - If you are not a member, sign up at www.funimation.com. Otherwise, log in.
[Funimation] the-monster-of-the-abyss: Downloading Uncut japanese (1133574) JSON
WARNING: [Funimation] Funimation said: Error 2 - If you are not a member, sign up at www.funimation.com. Otherwise, log in.
[Funimation] the-monster-of-the-abyss: Downloading Simulcast english (925446) JSON
WARNING: [Funimation] Funimation said: Error 2 - If you are not a member, sign up at www.funimation.com. Otherwise, log in.
[Funimation] the-monster-of-the-abyss: Downloading Uncut english (1133576) JSON
WARNING: [Funimation] Funimation said: Error 2 - If you are not a member, sign up at www.funimation.com. Otherwise, log in.
ERROR: [Funimation] 917147: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 1465, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 2431, in process_video_result
    self.raise_no_formats(info_dict)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 961, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Funimation] 917147: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
'''

Example with user credentials only
'''
C:\youtube-dl>yt-dlp https://www.funimation.com/v/arifureta-from-commonplace-to-worlds-strongest/the-monster-of-the-abyss --no-check-certificates -n -v
[debug] Command-line config: ['https://www.funimation.com/v/arifureta-from-commonplace-to-worlds-strongest/the-monster-of-the-abyss', '--no-check-certificates', '-n', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: b76142822
[debug] Python version 3.9.7 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg n5.0-20220114 (setts), ffprobe n5.0-20220114
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[funimation:page] Checking geo-location
[funimation:page] Logging in
[debug] [funimation:page] Extracting URL: https://www.funimation.com/v/arifureta-from-commonplace-to-worlds-strongest/the-monster-of-the-abyss
[funimation:page] arifureta-from-commonplace-to-worlds-strongest_the-monster-of-the-abyss: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/925446
[Funimation] 925446: Downloading player webpage for 925446
[Funimation] the-monster-of-the-abyss: Downloading Simulcast japanese (917148) JSON
WARNING: [Funimation] Funimation said: Error 2 - If you are not a member, sign up at www.funimation.com. Otherwise, log in.
[Funimation] the-monster-of-the-abyss: Downloading Uncut japanese (1133574) JSON
WARNING: [Funimation] Funimation said: Error 2 - If you are not a member, sign up at www.funimation.com. Otherwise, log in.
[Funimation] the-monster-of-the-abyss: Downloading Simulcast english (925446) JSON
WARNING: [Funimation] Funimation said: Error 2 - If you are not a member, sign up at www.funimation.com. Otherwise, log in.
[Funimation] the-monster-of-the-abyss: Downloading Uncut english (1133576) JSON
WARNING: [Funimation] Funimation said: Error 2 - If you are not a member, sign up at www.funimation.com. Otherwise, log in.
ERROR: [Funimation] 917147: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 1465, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 2431, in process_video_result
    self.raise_no_formats(info_dict)
  File "C:\Program Files\youtube-dl\yt-dlp\yt_dlp\YoutubeDL.py", line 961, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Funimation] 917147: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
'''

Example with cookies
'''
C:\youtube-dl>yt-dlp --cookies cookies-funimation-com.txt --no-check-certificates https://www.funimation.com/v/arifureta-from-commonplace-to-worlds-strongest/the-monster-of-the-abyss -v
[debug] Command-line config: ['--cookies', 'cookies-funimation-com.txt', '--no-check-certificates', 'https://www.funimation.com/v/arifureta-from-commonplace-to-worlds-strongest/the-monster-of-the-abyss', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: b76142822
[debug] Python version 3.9.7 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg n5.0-20220114 (setts), ffprobe n5.0-20220114
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [funimation:page] Extracting URL: https://www.funimation.com/v/arifureta-from-commonplace-to-worlds-strongest/the-monster-of-the-abyss
[funimation:page] arifureta-from-commonplace-to-worlds-strongest_the-monster-of-the-abyss: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/925446
[Funimation] 925446: Downloading player webpage for 925446
[Funimation] the-monster-of-the-abyss: Downloading Simulcast japanese (917148) JSON
[Funimation] the-monster-of-the-abyss: Downloading Simulcast japanese (917148) m3u8 information
[Funimation] the-monster-of-the-abyss: Downloading Uncut japanese (1133574) JSON
[Funimation] the-monster-of-the-abyss: Downloading Uncut japanese (1133574) m3u8 information
[Funimation] the-monster-of-the-abyss: Downloading Simulcast english (925446) JSON
[Funimation] the-monster-of-the-abyss: Downloading Simulcast english (925446) m3u8 information
[Funimation] the-monster-of-the-abyss: Downloading Uncut english (1133576) JSON
[Funimation] the-monster-of-the-abyss: Downloading Uncut english (1133576) m3u8 information
[debug] Sort order given by extractor: lang, source
[debug] Formats sorted by: hasvid, ie_pref, lang, source, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 917147: Downloading 1 format(s): 1133574-hls-7001+1133576-hls-audio-aacl-256-English
[debug] Invoking downloader on "https://vmfst-api.prd.funimationsvc.com/FunimationStoreFront/V1831798/74f4bf36-6b71-46f8-84ed-a89c6e746841strnv-hl154_streaming_video_1920_1080_7800000_index.m3u8?Key-Pair-Id=APKAIHNXECY27H4O6NIA&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMzNldDc3ZXZkOWJnZy5jbG91ZGZyb250Lm5ldC9GdW5pbWF0aW9uU3RvcmVGcm9udC9WMTgzMTc5OC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjQzOTg2ODEyfX19XX0_&Signature=BFPS0tn6LIN3Muw769tsd7B1qkF7A%7EYgHNJaIBgzYPEAr8Ijgzk9fYyyjP9RUtKAz%7ENOYztkX2GskQLiqDzKLJ7nWqLLvt5zxn71d%7EyAo0aNMc4B3Do7KZTI95GHD-dKNGI-5lBDGO1X4K1wRvgJKcwR0ZLLom-Vd5ty1PG863wcrW9PASoOYNeVJjosV2k3WRw5m3qVH0ihhUSXNy9clzz4O-NuxC4HdmxEOOV9pDwzp5Pt3VNfrI1UypYdZZc6BRa4foYMwYkwCnS0KBQ%7E64GO2bTXW6OxyHWoysVBatnDXqpmf5nABjWsTbaNvFBxGBA7rkXpzcof7OnI-U9q8Q__&rt=1415080"
[hlsnative] Downloading m3u8 manifest
'''

What I want to achieve with this site enhancement, is that the extractor can recognize that I have enabled mature content through user credentials and not only through cookies.

I can share my account information but I clarify that it is a free account, I only created it precisely because of the mature content.

**Comment by pukkandan** [comment] 2022-02-04 14:24
Gotcha. duplicate of https://github.com/yt-dlp/yt-dlp/issues/1569

**Closed by pukkandan** 2022-02-04 14:24 UTC
Labels: incomplete, site-enhancement
