### ISSUE TITLE
[crunchyroll:music] No video formats found

### ISSUE THREAD

**Issue by red5h4d0w** [yt-dlp/yt-dlp#9454] opened 2024-03-15 04:05 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

I noticed today that I couldn't use yt-dlp anymore on Music Videos found on Crunchyroll. This is possibly linked to recent changes over at Crunchyroll that also caused #9439 .

Please note that I cannot read said video on Firefox without Widevine CDM enabled.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://www.crunchyroll.com/fr/watch/musicvideo/MV7ECCE32D/hakanakumo-towano-kanashi']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.03.14.232144 from yt-dlp/yt-dlp-master-builds [f2868b26e] (linux_exe)
[debug] Python 3.10.13 (CPython x86_64 64bit) - Linux-6.7.9-arch1-1-x86_64-with-glibc2.39 (OpenSSL 3.2.1 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/me/.mozilla/firefox/5ayqpx4m.default-release/cookies.sqlite"
Extracted 521 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.03.14.232144 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.03.14.232144 from yt-dlp/yt-dlp-master-builds)
[crunchyroll:music] Extracting URL: https://www.crunchyroll.com/fr/watch/musicvideo/MV7ECCE32D/hakanakumo-towano-kanashi
[debug] [crunchyroll:music] Using cxApiParam=noaihdevm_6iyg0a8l0q
[crunchyroll:music] Authenticating with grant_type=etp_rt_cookie
[crunchyroll:music] MV7ECCE32D: Downloading music video info JSON (music)
[crunchyroll:music] MV7ECCE32D: Downloading stream info JSON (music)
ERROR: [crunchyroll:music] MV7ECCE32D: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1594, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1750, in __extract_info
  File "yt_dlp/YoutubeDL.py", line 1809, in process_ie_result
  File "yt_dlp/YoutubeDL.py", line 2797, in process_video_result
  File "yt_dlp/YoutubeDL.py", line 1092, in raise_no_formats
yt_dlp.utils.ExtractorError: [crunchyroll:music] MV7ECCE32D: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment] 2024-03-15 04:19
Closing as duplicate of #9453 (same root issue -- no more `vo_adaptive_hls` formats)

**Closed by bashonly** 2024-03-15 04:19 UTC
Labels: site-bug, triage
