### ISSUE TITLE
WARNING: [youtube] rTt9AscnpeU: nsig extraction failed: Some formats may be missing

### ISSUE THREAD

**Issue by ndyanx** [yt-dlp/yt-dlp#10614] opened 2024-07-31 17:42 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Perú

### Provide a description that is worded well enough to be understood

WARNING: [youtube] rTt9AscnpeU: nsig extraction failed: Some formats may be missing
         n = clwiHcYqanSWtv0Y ; player = https://www.youtube.com/s/player/20dfca59/player_ias.vflset/en_US/base.js
WARNING: [youtube] rTt9AscnpeU: nsig extraction failed: Some formats may be missing
         n = LAZJ24rI6irU4QAv ; player = https://www.youtube.com/s/player/20dfca59/player_ias.vflset/en_US/base.js

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\ndyan>yt-dlp --verbose --list-formats --format-sort "tbr" "https://www.youtube.com/watch?v=rTt9AscnpeU"
[debug] Command-line config: ['--verbose', '--list-formats', '--format-sort', 'tbr', 'https://www.youtube.com/watch?v=rTt9AscnpeU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.30.232707 from yt-dlp/yt-dlp-nightly-builds [4b69e1b53] (pip)
[debug] Python 3.11.3 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg n7.0.1-6-gf0b747ef1a-20240616 (setts), ffprobe n7.0.1-6-gf0b747ef1a-20240616, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.2, sqlite3-3.40.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=rTt9AscnpeU
[youtube] rTt9AscnpeU: Downloading webpage
[youtube] rTt9AscnpeU: Downloading ios player API JSON
[debug] [youtube] Extracting signature function js_20dfca59_103
[debug] Loading youtube-sigfuncs.js_20dfca59_103 from cache
[youtube] rTt9AscnpeU: Downloading player 20dfca59
WARNING: [youtube] rTt9AscnpeU: nsig extraction failed: Some formats may be missing
         n = clwiHcYqanSWtv0Y ; player = https://www.youtube.com/s/player/20dfca59/player_ias.vflset/en_US/base.js
[debug] [youtube] Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] rTt9AscnpeU: nsig extraction failed: Some formats may be missing
         n = LAZJ24rI6irU4QAv ; player = https://www.youtube.com/s/player/20dfca59/player_ias.vflset/en_US/base.js
[debug] [youtube] Extracting signature function js_20dfca59_107
[debug] Loading youtube-sigfuncs.js_20dfca59_107 from cache
[youtube] rTt9AscnpeU: Downloading m3u8 information
[debug] Sort order given by user: tbr
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, tbr, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for rTt9AscnpeU:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        1    │                  mhtml │ images                                  storyboard
sb1 mhtml 80x45        1    │                  mhtml │ images                                  storyboard
sb0 mhtml 160x90       1    │                  mhtml │ images                                  storyboard
233 mp4   audio only        │                  m3u8  │ audio only          unknown             [nl] Default, IOS
234 mp4   audio only        │                  m3u8  │ audio only          unknown             [nl] Default, IOS
139 m4a   audio only      2 │    1.11MiB   49k https │ audio only          mp4a.40.5   49k 22k [nl] low, IOS, m4a_dash
140 m4a   audio only      2 │    2.95MiB  130k https │ audio only          mp4a.40.2  130k 44k [nl] medium, IOS, m4a_dash
160 mp4   256x144     24    │  693.44KiB   30k https │ avc1.4D400C     30k video only          144p, IOS, mp4_dash
133 mp4   426x240     24    │    1.10MiB   48k https │ avc1.4D4015     48k video only          240p, IOS, mp4_dash
395 mp4   426x240     24    │    1.30MiB   57k https │ av01.0.00M.08   57k video only          240p, IOS, mp4_dash
394 mp4   256x144     24    │    1.40MiB   61k https │ av01.0.00M.08   61k video only          144p, IOS, mp4_dash
278 webm  256x144     24    │    1.47MiB   65k https │ vp09.00.11.08   65k video only          144p, IOS, webm_dash
242 webm  426x240     24    │    1.59MiB   70k https │ vp09.00.20.08   70k video only          240p, IOS, webm_dash
602 mp4   256x144     12    │ ~  1.86MiB   82k m3u8  │ vp09.00.10.08   82k video only          IOS
134 mp4   640x360     24    │    1.92MiB   84k https │ avc1.4D401E     84k video only          360p, IOS, mp4_dash
396 mp4   640x360     24    │    2.39MiB  105k https │ av01.0.01M.08  105k video only          360p, IOS, mp4_dash
243 webm  640x360     24    │    2.41MiB  106k https │ vp09.00.21.08  106k video only          360p, IOS, webm_dash
135 mp4   854x480     24    │    3.01MiB  132k https │ avc1.4D401E    132k video only          480p, IOS, mp4_dash
269 mp4   256x144     24    │ ~  3.21MiB  141k m3u8  │ avc1.4D400C    141k video only          IOS
603 mp4   256x144     24    │ ~  3.45MiB  152k m3u8  │ vp09.00.11.08  152k video only          IOS
244 webm  854x480     24    │    3.51MiB  154k https │ vp09.00.30.08  154k video only          480p, IOS, webm_dash
397 mp4   854x480     24    │    4.16MiB  182k https │ av01.0.04M.08  182k video only          480p, IOS, mp4_dash
229 mp4   426x240     24    │ ~  4.54MiB  199k m3u8  │ avc1.4D4015    199k video only          IOS
136 mp4   1280x720    24    │    5.68MiB  249k https │ avc1.4D401F    249k video only          720p, IOS, mp4_dash
604 mp4   426x240     24    │ ~  6.03MiB  265k m3u8  │ vp09.00.20.08  265k video only          IOS
247 webm  1280x720    24    │    6.10MiB  268k https │ vp09.00.31.08  268k video only          720p, IOS, webm_dash
398 mp4   1280x720    24    │    8.00MiB  351k https │ av01.0.05M.08  351k video only          720p, IOS, mp4_dash
230 mp4   640x360     24    │ ~  8.92MiB  392k m3u8  │ avc1.4D401E    392k video only          IOS
605 mp4   640x360     24    │ ~ 11.70MiB  514k m3u8  │ vp09.00.21.08  514k video only          IOS
231 mp4   854x480     24    │ ~ 12.04MiB  529k m3u8  │ avc1.4D401E    529k video only          IOS
399 mp4   1920x1080   24    │   14.25MiB  625k https │ av01.0.08M.08  625k video only          1080p, IOS, mp4_dash
606 mp4   854x480     24    │ ~ 14.94MiB  656k m3u8  │ vp09.00.30.08  656k video only          IOS
248 webm  1920x1080   24    │   17.88MiB  785k https │ vp09.00.40.08  785k video only          1080p, IOS, webm_dash
232 mp4   1280x720    24    │ ~ 19.02MiB  835k m3u8  │ avc1.4D401F    835k video only          IOS
137 mp4   1920x1080   24    │   22.13MiB  971k https │ avc1.640028    971k video only          1080p, IOS, mp4_dash
609 mp4   1280x720    24    │ ~ 24.68MiB 1084k m3u8  │ vp09.00.31.08 1084k video only          IOS
614 mp4   1920x1080   24    │ ~ 56.87MiB 2498k m3u8  │ vp09.00.40.08 2498k video only          IOS
270 mp4   1920x1080   24    │ ~ 62.14MiB 2729k m3u8  │ avc1.640028   2729k video only          IOS
```

**Comment by seproDev** [comment] 2024-07-31 17:47
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/10608

**Closed by seproDev** 2024-07-31 17:47 UTC
Labels: site-bug, triage
