### ISSUE TITLE
[Hidive] HiDive said: PremiumContent (`-u`/`-p` login is broken, `--cookies-from-browser` won't work)

### ISSUE THREAD

**Issue by Killua-Zolldyck** [yt-dlp/yt-dlp#8019] opened 2023-09-03 12:58 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

Hi @ all,

No matter what I try (-u -p or cookies-from-browser), I always get the error "HiDive said: PremiumContent". Am I the only one, having this issue or am I doing anything wrong? Latest stable version and latest nightly resulting in same error. Also no difference in using cookies-from-browser edge or firefox with proper user-agent.

Best Regards

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'edge', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.69', 'https://www.hidive.com/stream/kubo-wont-let-me-be-invisible/s01e001']
Extracting cookies from edge
[debug] Extracting cookies from: "C:\Users\xxx\AppData\Local\Microsoft\Edge\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\xxx\AppData\Local\Microsoft\Edge\User Data\Local State"
Extracted 2903 cookies from edge
[debug] cookie version breakdown: {'v10': 2903, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.09.02.144028 [2301b5c1b] (win32_dir)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111587-gf803c07d2d-ga4e616824b (fdk,setts), ffprobe N-111587-gf803c07d2d-ga4e616824b, rtmpdump 2.4-20220520-g922b131-GnuTLS_3.7.8-x86_64-static
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.09.02.144028, Current version: nightly@2023.09.02.144028
yt-dlp is up to date (nightly@2023.09.02.144028)
[HiDive] Extracting URL: https://www.hidive.com/stream/kubo-wont-let-me-be-invisible/s01e001
[HiDive] kubo-wont-let-me-be-invisible/s01e001: Downloading JSON metadata
ERROR: [HiDive] kubo-wont-let-me-be-invisible/s01e001: HiDive said: PremiumContent
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\hidive.py", line 82, in _real_extract
```

**Comment by bashonly** [comment] 2023-09-03 14:08
Try [exporting cookies to a text file via browser extension](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp) and passing them to yt-dlp with `--cookies` instead. I think HiDive is storing the auth info as a session cookie, which cannot be extracted with `--cookies-from-browser`.

While this issue is similar to #6493, IMO this new issue is not a duplicate, since Hidive login is also broken now, and we do not have an issue tracking that. (The old issue was closed as a duplicate of #5534, a general bug report/feature request about yt-dlp being unable to extract session cookies with `--cookies-from-browser`.)

**Comment by bashonly** [comment] 2023-09-03 14:11
As for login, I looked into this a couple months back and IIRC Hidive employs a captcha challenge upon logging in with browser now. Not sure if there's a way around it. We may need to rework the extractor's login to allow the user to pass their token/session cookie as a password or something

**Comment by Killua-Zolldyck** [comment] 2023-09-03 17:58
I exported the cookies in a file to use it as option. Still not working. But looking at the cookies.txt I've found this:
".hidive.com	TRUE	/	TRUE	1725385401	UserStatus	Trial"

I am using a new account and am still in the trial period. For it works in the browser itself, maybe this is the problem it does not work with yt-dlp?

For I am not in a hurry, I just think it might help to wait till first payment in 7 days and have a look again.

**Comment by gamer191** [comment] 2023-09-07 03:50
can you please post a verbose log demonstrating that -u/-p doesn't work?

**Comment by BraveSail** [comment] 2023-09-07 05:29
> can you please post a verbose log demonstrating that -u/-p doesn't work?

https://github.com/yt-dlp/yt-dlp/issues/6493#issuecomment-1693538651

It shows logging then return PremiumContent without debug errors.

**Comment by Killua-Zolldyck** [comment] 2023-09-07 05:38
[debug] Command-line config: ['-vU', '-u', 'PRIVATE', '-p', 'PRIVATE', '--cookies', 'cookies.txt', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0', 'https://www.hidive.com/stream/kubo-wont-let-me-be-invisible/s01e001']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.09.05.203540 [d3d81cc98] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-111587-gf803c07d2d-ga4e616824b (fdk,setts), ffprobe N-111587-gf803c07d2d-ga4e616824b, rtmpdump 2.4-20220520-g922b131-GnuTLS_3.7.8-x86_64-static
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.47.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1864 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.09.05.203540, Current version: nightly@2023.09.05.203540
Current Build Hash: b9c1cda74d2a2aaa37a9c1c7475b9f54a5f79bf22b362341fb2e63cfda2644a6
yt-dlp is up to date (nightly@2023.09.05.203540)
[HiDive] None: Downloading webpage
[HiDive] Logging in
[HiDive] Extracting URL: https://www.hidive.com/stream/kubo-wont-let-me-be-invisible/s01e001
[HiDive] kubo-wont-let-me-be-invisible/s01e001: Downloading JSON metadata
ERROR: [HiDive] kubo-wont-let-me-be-invisible/s01e001: HiDive said: PremiumContent
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\hidive.py", line 82, in _real_extract

**Comment by bashonly** [comment] 2023-09-07 16:26
> Okay, please don't get mad on me. ... I can garantuee it did not work that day. But the exact same command line is working today. 

No worries. I was able to reproduce this same issue a couple months ago with an account that was shared to me. Not sure if it was also a new account, or if that's that cause of the issue. But it's not just you

> So using -u/-p is working without further issues for me now, I am closing this.

This issue can be re-opened if you begin experiencing the issue again, or if anyone else reports experiencing it

**Comment by Tama47** [comment] 2023-09-24 23:30
> Try [exporting cookies to a text file via browser extension](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp) and passing them to yt-dlp with --cookies instead.

I can confirm that this method is working because it starts downloading immediately.
```
Extracting cookies from chrome
Extracted 514 cookies from chrome
[HiDive] Extracting URL: https://www.hidive.com/stream/dark-gathering/s01e012
[HiDive] dark-gathering/s01e012: Downloading JSON metadata
[HiDive] dark-gathering/s01e012: Downloading m3u8 information
[info] dark-gathering/s01e012: Downloading subtitles: english-subs
[info] dark-gathering/s01e012: Downloading 1 format(s): ja_br_or-6357
[info] Writing video subtitles to: /Users/tama/Downloads/Dark Gathering Episode 12 - The Castle H Ruins, Danger Rank S!.english-subs.vtt
[download] Destination: /Users/tama/Downloads/Dark Gathering Episode 12 - The Castle H Ruins, Danger Rank S!.english-subs.vtt
[download] 100% of   34.42KiB in 00:00:00 at 284.60KiB/s
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 144
[download] Destination: /Users/tama/Downloads/Dark Gathering Episode 12 - The Castle H Ruins, Danger Rank S!.mp4
[download] 100% of  579.36MiB in 00:01:06 at 8.67MiB/s
[FixupM3u8] Fixing MPEG-TS in MP4 container of "/Users/tama/Downloads/Dark Gathering Episode 12 - The Castle H Ruins, Danger Rank S!.mp4"
```

However, I still have the issue of not being able to stream it directly with mpv. Not sure if this is an mpv issue.

```
mpv https://www.hidive.com/stream/dark-gathering/s01e012

Not seekable, but enabling seeking on user request.
[ffmpeg] https: HTTP error 404 Not Found
Failed to open https://www.hidive.com/manifest/child/f5769a4663272672867acf7397806edbb13824ea/DKG_s01e012_tv_br_or_ja_xx_HLS1080p_16x9_01_v.m3u8?#=.

Exiting... (Errors when loading file)
```

**Comment by Parent5446** [comment] 2024-03-04 06:57
Found this issue when searching, and I'm actually experiencing it myself, both when using CLI to supply the username and password and also with netrc.

```
[debug] Command-line config: ['-vvv', 'https://www.hidive.com/stream/the-dangers-in-my-heart/s02e013']
[debug] User config "/home/parent5446/.config/yt-dlp.conf": ['--netrc', '--cookies-from-browser', 'firefox', '--retries', 'infinite', '--mark-watched', '--embed-thumbnail']
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/parent5446/.mozilla/firefox/uiisyysg.default-release/cookies.sqlite"
Extracted 1669 cookies from firefox
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Lazy loading extractors is disabled
[debug] Python 3.12.2 (CPython x86_64 64bit) - Linux-6.7.6-200.fc39.x86_64-x86_64-with-glibc2.38 (OpenSSL 3.1.1 30 May 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0.1 (setts), ffprobe 6.0.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.05.07, mutagen-1.46.0, requests-2.28.2, secretstorage-3.3.3, sqlite3-3.42.0, urllib3-1.26.18, websockets-11.0.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[HiDive] None: Downloading webpage
[HiDive] Logging in
[HiDive] Extracting URL: https://www.hidive.com/stream/the-dangers-in-my-heart/s02e013
[HiDive] the-dangers-in-my-heart/s02e013: Downloading JSON metadata
ERROR: [HiDive] the-dangers-in-my-heart/s02e013: HiDive said: PremiumContent
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/hidive.py", line 82, in _real_extract
    raise ExtractorError(
```

**Comment by Parent5446** [comment] 2024-03-05 06:53
Yep I've tried with a large variety of options. The only thing that works is manually exporting cookies from Firefox while logged in.

I think the problem is it has trouble logging in, perhaps due to CAPTCHA issues mentioned in existing issues. But if that's the case it should probably throw an error rather than silently succeeding.

**Comment by bashonly** [comment] 2024-03-09 23:57
Closing due to #9385

**Closed by bashonly** 2024-03-09 23:57 UTC
Labels: account-needed, site-bug, can-share-account
