### ISSUE TITLE
xigua move error

### ISSUE THREAD

**Issue by xzwilliam** [yt-dlp/yt-dlp#7401] opened 2023-06-23 14:34 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

china

### Provide a description that is worded well enough to be understood

(venv) D:\project\202306\yt-dlp\yt-dlp-master>python main.py -vU "https://www.ixigua.com/6691980319295275532?logTag=aa89cccc1827aa13e317&wid_try=1" --add-header "Cookie:__ac_nonce=06495870200182b5abe66;__ac_signature=_02B4Z6wo00f01fRoHgwAAIDDnOOP6KkjDFX0WRqAABmRb5;csrf_session_id=a49a0a622b9c542f509fe75088885da8;ttwid=1%7CtR195dZnXIw3vES2Hl05_E53xRG42WwhWF37BrC1AgY%7C1687521028%7C79edc69e7f7edd79580857e3db251909bbdf6dce15f19f80ae16a5ffbd11dde3" -f 30-1
[debug] Override config: ['-v', 'https://www.ixigua.com/6691980319295275532?logTag=fdecdee8adf05e7efc9c&wid_try=1', '--add-header', 'Cookie:__ac_nonce=06495870200182b5abe66;__ac_signature=_02B4Z6wo00f01fRoHgwAAIDDnOOP6KkjDFX0WRqAABmRb5;csrf_session_id=a49a0a622b9c542f509fe75088885da8;ttwid=1%7CtR195dZnXIw3vES2Hl05_E53xRG42WwhWF37BrC1AgY%7C1687521028%7C79edc69e7f7edd79580857e3db251909bbdf6dce15f19f80ae16a5ffbd11dde3;', '-f', '30-1']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.3 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-110228-g4dffa564d1-20230411 (setts), ffprobe N-110228-g4dffa564d1-20230411
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'http': 'http://127.0.0.1:10900', 'https': 'http://127.0.0.1:10900', 'ftp': 'http://127.0.0.1:10900'}
[debug] Loaded 1851 extractors
[Ixigua] Extracting URL: https://www.ixigua.com/6691980319295275532?logTag=fdecdee8adf05e7efc9c&wid_try=1
[Ixigua] 6691980319295275532: Downloading webpage
ERROR: 6691980319295275532: An extractor error has occurred. (caused by KeyError('video')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "D:\project\202306\yt-dlp\yt-dlp-master\yt_dlp\extractor\common.py", line 708, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\202306\yt-dlp\yt-dlp-master\yt_dlp\extractor\ixigua.py", line 67, in _real_extract
    json_data = self._get_json_data(webpage, video_id)['anyVideo']['gidInformation']['packerData']['video']
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'video'

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(venv) D:\project\202306\yt-dlp\yt-dlp-master>python main.py -vU "https://www.ixigua.com/6691980319295275532?logTag=aa89cccc1827aa13e317&wid_try=1" --add-header "Cookie:__ac_nonce=06495870200182b5abe66;__ac_signature=_02B4Z6wo00f01fRoHgwAAIDDnOOP6KkjDFX0WRqAABmRb5;csrf_session_id=a49a0a622b9c542f509fe75088885da8;ttwid=1%7CtR195dZnXIw3vES2Hl05_E53xRG42WwhWF37BrC1AgY%7C1687521028%7C79edc69e7f7edd79580857e3db251909bbdf6dce15f19f80ae16a5ffbd11dde3" -f 30-1
[debug] Override config: ['-v', 'https://www.ixigua.com/6691980319295275532?logTag=fdecdee8adf05e7efc9c&wid_try=1', '--add-header', 'Cookie:__ac_nonce=06495870200182b5abe66;__ac_signature=_02B4Z6wo00f01fRoHgwAAIDDnOOP6KkjDFX0WRqAABmRb5;csrf_session_id=a49a0a622b9c542f509fe75088885da8;ttwid=1%7CtR195dZnXIw3vES2Hl05_E53xRG42WwhWF37BrC1AgY%7C1687521028%7C79edc69e7f7edd79580857e3db251909bbdf6dce15f19f80ae16a5ffbd11dde3;', '-f', '30-1']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.3 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-110228-g4dffa564d1-20230411 (setts), ffprobe N-110228-g4dffa564d1-20230411
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {'http': 'http://127.0.0.1:10900', 'https': 'http://127.0.0.1:10900', 'ftp': 'http://127.0.0.1:10900'}
[debug] Loaded 1851 extractors
[Ixigua] Extracting URL: https://www.ixigua.com/6691980319295275532?logTag=fdecdee8adf05e7efc9c&wid_try=1
[Ixigua] 6691980319295275532: Downloading webpage
ERROR: 6691980319295275532: An extractor error has occurred. (caused by KeyError('video')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "D:\project\202306\yt-dlp\yt-dlp-master\yt_dlp\extractor\common.py", line 708, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\202306\yt-dlp\yt-dlp-master\yt_dlp\extractor\ixigua.py", line 67, in _real_extract
    json_data = self._get_json_data(webpage, video_id)['anyVideo']['gidInformation']['packerData']['video']
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'video'
```

**Comment by bashonly** [comment] 2023-06-23 15:47
Duplicate of #6932

Also, the workaround (solution?) from #5374 may also apply here:

Navigate to the page in your web browser, let the video load, and then pass cookies with yt-dlp with
`--cookies-from-browser chrome` (or whatever browser you use)

**Closed by bashonly** 2023-06-23 15:47 UTC
Labels: site-bug, triage
