### ISSUE TITLE
BR (Bayerischer Rundfunk) broken download

### ISSUE THREAD

**Issue by chris242135215** [yt-dlp/yt-dlp#9671] opened 2024-04-11 13:00 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

Links from https://br.de do not work anymore.

BR: Bayerischer Rundfunk is mentioned under https://ytdl-org.github.io/youtube-dl/supportedsites.html as supported site.

The users of our frontend to yt-dlp also mentioned, that it worked in the past.
I do not know, if the BR site structure for offering the content changed.

Example Link: https://www.br.de/br-fernsehen/import/audiovideo/erinnerungsprojekt-caro-matzko-100.html

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.br.de/br-fernsehen/import/audiovideo/erinnerungsprojekt-caro-matzko-100.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.04.09.232723 from yt-dlp/yt-dlp-nightly-builds [168e72dcd] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.47.0, pyxattr-0.7.2, requests-2.31.0, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.04.09.232723 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.04.09.232723 from yt-dlp/yt-dlp-nightly-builds)
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[BR] Extracting URL: https://www.br.de/br-fernsehen/import/audiovideo/erinnerungsprojekt-caro-matzko-100.html
[BR] erinnerungsprojekt-caro-matzko-100: Downloading webpage
ERROR: [BR] erinnerungsprojekt-caro-matzko-100: Unable to extract XMLURL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/chris/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "/home/chris/.local/lib/python3.10/site-packages/yt_dlp/extractor/br.py", line 84, in _real_extract
    xml_url = self._search_regex(
  File "/home/chris/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1321, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by pukkandan** [comment] 2024-04-11 13:46
Duplicate of #8740

**Closed by pukkandan** 2024-04-11 13:46 UTC
Labels: site-bug, triage
