### ISSUE TITLE
ERROR: [facebook]: No video formats found!

### ISSUE THREAD

**Issue by scrutinizer11** [yt-dlp/yt-dlp#11345] opened 2024-10-24 22:58 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Attempting to download a Facebook (public) reel throws up the error indicated in the subject of this issue. The error pops up regardless of the proxy option to the command. Additionally, I cannot use the command without overriding the certificate check.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--proxy', 'localhost:3128', '-U', '--no-check-certificates', '-v', 'https://www.facebook.com/reel/1704841553648926']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.23.232902 from yt-dlp/yt-dlp-nightly-builds [914af9a0c] (darwin_legacy_exe)
[debug] Python 3.10.5 (CPython x86_64 64bit) - macOS-10.9.5-x86_64-i386-64bit (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg N-101508-ge93403b (setts), ffprobe N-101508-ge93403b
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {'all': 'localhost:3128'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.23.232902 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.23.232902 from yt-dlp/yt-dlp-nightly-builds)
[facebook:reel] Extracting URL: https://www.facebook.com/reel/1704841553648926
[facebook] Extracting URL: https://m.facebook.com/watch/?v=1704841553648926&_rdr
[facebook] 1704841553648926: Downloading webpage
ERROR: [facebook] 1704841553648926: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1625, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1781, in __extract_info
  File "yt_dlp/YoutubeDL.py", line 1840, in process_ie_result
  File "yt_dlp/YoutubeDL.py", line 2846, in process_video_result
  File "yt_dlp/YoutubeDL.py", line 1122, in raise_no_formats
yt_dlp.utils.ExtractorError: [facebook] 1704841553648926: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment] 2024-10-24 23:01
duplicate of #11337

run `yt-dlp --update-to master` or wait an hour and update to the latest nightly

**Closed by bashonly** 2024-10-24 23:01 UTC
Labels: duplicate, site-bug, site:facebook

**Comment by scrutinizer11** [comment] 2024-10-24 23:31
Why?

**Comment by bashonly** [comment] 2024-10-25 00:02
because this is a duplicate issue that has already been fixed. update to nightly/master
