### ISSUE TITLE
Dowload arte.tv video with embeded subtittles does not work

### ISSUE THREAD

**Issue by MaxBMic** [yt-dlp/yt-dlp#6560] opened 2023-03-18 20:01 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,

I try to download video from Arte.tv.

I want download video in original Italian langage with embeded French subtittles.

The video is downloaded correctly but without embedded subtitles

Is the command correct ?

can you help me please ?

**Operating system :** Fedora Linux 37

**The video URL :** https://www.arte.tv/fr/videos/097481-001-A/esterno-notte-1-6/

### yt-dlp version :

```
[user@pc-linux]~ $ yt-dlp --update
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
```

### yt-dlp command :

`[user@pc-linux]~ $ yt-dlp -vU -f "bestvideo+VO-STF-program_audio_0-VO" --embed-subs --sub-langs "fr" https://www.arte.tv/fr/videos/097481-001-A/esterno-notte-1-6/`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```
[user@pc-linux]~ $ yt-dlp -vU -f "bestvideo+VO-STF-program_audio_0-VO" --embed-subs --sub-langs "fr" https://www.arte.tv/fr/videos/097481-001-A/esterno-notte-1-6/

[debug] Command-line config: ['-vU', '-f', 'bestvideo+VO-STF-program_audio_0-VO', '--embed-subs', '--sub-langs', 'fr', 'https://www.arte.tv/fr/videos/097481-001-A/esterno-notte-1-6/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.18-200.fc37.x86_64-x86_64-with-glibc2.36 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.17.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[ArteTV] Extracting URL: https://www.arte.tv/fr/videos/097481-001-A/esterno-notte-1-6/
[ArteTV] 097481-001-A: Downloading JSON metadata
[ArteTV] 097481-001-A: Downloading m3u8 information
[ArteTV] 097481-001-A: Downloading m3u8 information
[ArteTV] 097481-001-A: Downloading m3u8 information
[ArteTV] 097481-001-A: Downloading m3u8 information
[ArteTV] 097481-001-A: Downloading m3u8 information
[info] 097481-001-A: Downloading subtitles: fr
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 097481-001-A: Downloading 1 format(s): VF-STF-2023+VO-STF-program_audio_0-VO
[info] Writing video subtitles to: Esterno notte (1⧸6) [097481-001-A].fr.vtt
[debug] Invoking hlsnative downloader on "https://arte-cmafhls.akamaized.net/am/cmaf/097000/097400/097481-001-A/230306085847/medias/097481-001-A_st_VF-MAL.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1
[download] Destination: Esterno notte (1⧸6) [097481-001-A].fr.vtt
[download] 100% of   89.67KiB in 00:00:00 at 787.87KiB/s
[debug] Invoking hlsnative downloader on "https://arte-cmafhls.akamaized.net/am/cmaf/097000/097400/097481-001-A/230306085847/medias/097481-001-A_v1080.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 564
[download] Destination: Esterno notte (1⧸6) [097481-001-A].fVF-STF-2023.mp4
[download] 100% of  763.29MiB in 00:02:44 at 4.64MiB/s
[debug] Invoking hlsnative downloader on "https://arte-cmafhls.akamaized.net/am/cmaf/097000/097400/097481-001-A/230306085847/medias/097481-001-A_aud_VO-ITA_1.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 565
[download] Destination: Esterno notte (1⧸6) [097481-001-A].fVO-STF-program_audio_0-VO.mp4
[download] 100% of   52.80MiB in 00:00:52 at 1.01MiB/s
[debug] ffmpeg command line: ffprobe -show_streams 'file:Esterno notte (1⧸6) [097481-001-A].fVO-STF-program_audio_0-VO.mp4'
[Merger] Merging formats into "Esterno notte (1⧸6) [097481-001-A].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Esterno notte (1⧸6) [097481-001-A].fVF-STF-2023.mp4' -i 'file:Esterno notte (1⧸6) [097481-001-A].fVO-STF-program_audio_0-VO.mp4' -c copy -map 0:v:0 -map 1:a:0 -bsf:a:0 aac_adtstoasc -movflags +faststart 'file:Esterno notte (1⧸6) [097481-001-A].temp.mp4'
Deleting original file Esterno notte (1⧸6) [097481-001-A].fVO-STF-program_audio_0-VO.mp4 (pass -k to keep)
Deleting original file Esterno notte (1⧸6) [097481-001-A].fVF-STF-2023.mp4 (pass -k to keep)
[EmbedSubtitle] Embedding subtitles in "Esterno notte (1⧸6) [097481-001-A].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Esterno notte (1⧸6) [097481-001-A].mp4' -i 'file:Esterno notte (1⧸6) [097481-001-A].fr.vtt' -map 0 -dn -ignore_unknown -c copy -c:s mov_text -map -0:s -map 1:0 -metadata:s:s:0 language=fra -movflags +faststart 'file:Esterno notte (1⧸6) [097481-001-A].temp.mp4'
Deleting original file Esterno notte (1⧸6) [097481-001-A].fr.vtt (pass -k to keep)
```

Thank you  :)

**Comment by bashonly** [comment] 2023-03-19 01:36
This seems to be caused by ffmpeg being unable to parse webvtt subs that have a `STYLE` block at the beginning of the file, as these subs do:
```
WEBVTT

STYLE
::cue(.black) {
 color: black;
}
```
Per https://trac.ffmpeg.org/ticket/9064 :
> If a webvtt file contains STYLE blocks, the webvtt decoder truncates the file at the first such block. Since these blocks typically occur at the top of the webvtt file, this results in an empty file (except for the WEBVTT header line).

Also related: https://trac.ffmpeg.org/ticket/8684

There are a couple of patches linked in those issues (that have not been merged):
https://patchwork.ffmpeg.org/project/ffmpeg/patch/CA+_k4RJ1CNriPbhxxzLf1O6V1VuP2OXch3E8LqOsMNSRUyEnTw@mail.gmail.com/
https://ffmpeg.org/pipermail/ffmpeg-devel/2022-May/296353.html

Maybe one of these could be considered for the yt-dlp custom ffmpeg builds?

**Comment by pukkandan** [comment] 2023-03-19 02:56
Does https://github.com/yt-dlp/FFmpeg-Builds#1-webvtt-decoding-fix not fix it?

**Comment by bashonly** [comment] 2023-03-19 02:59
d'oh, that is the patch I referenced in my above post. my bad

**Closed** 2023-03-19 03:04 UTC
Labels: external issue
