### ISSUE TITLE
YouTube import 400 Error 

### ISSUE THREAD

**Issue by alimirjahani7** [yt-dlp/yt-dlp#11503] opened 2024-11-11 14:29 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

canada 

### Provide a description that is worded well enough to be understood

The YouTube import is not working since few hours ago
I even refreshed my OAuth token but it didn't change as it is giving 400 error
So I think YouTube probably change something in their codes

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(test-project) ali@S14:~/Desktop/Test/test-project$ yt-dlp   https://www.youtube.com/watch?v=qJXKhu5UZwk -vU --username oauth2 --password ''
[debug] Command-line config: ['https://www.youtube.com/watch?v=qJXKhu5UZwk', '-vU', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6]
[debug] Lazy loading extractors is disabled
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Extractor Plugins: oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeTabIE)
[debug] Plugin directories: ['/home/ali/.virtualenvs/test-project/src/yt-dlp-youtube-oauth2/yt_dlp_plugins']
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2024.05.27 from yt-dlp/yt-dlp
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp from a manual build or with a package manager; Use that to update
[debug] YouTube OAuth2 plugin version 2024.10.29
WARNING: The YouTube OAuth2 plugin is obsolete! Official support for logging into YouTube with OAuth in yt-dlp was added in the 2024.10.22 release. 
See  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#logging-in-with-oauth  for how to use the official OAuth implementation.

To uninstall the plugin:

pip: pip uninstall yt-dlp-youtube-oauth2
pipx: pipx uninject yt-dlp yt-dlp-youtube-oauth2
manual: delete the plugin zip or files where you installed them

[debug] Loading youtube-oauth2.token_data from cache
[youtube+oauth2] Extracting URL: https://www.youtube.com/watch?v=qJXKhu5UZwk
[youtube+oauth2] qJXKhu5UZwk: Downloading webpage
[youtube+oauth2] qJXKhu5UZwk: Downloading ios player API JSON
[youtube+oauth2] qJXKhu5UZwk: Downloading player baafab19
WARNING: [youtube+oauth2] qJXKhu5UZwk: nsig extraction failed: You may experience throttling for some formats
         n = iwoK4Fz-ApJJuPK ; player = https://www.youtube.com/s/player/baafab19/player_ias.vflset/en_US/base.js
[debug] [youtube+oauth2] Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issue
s?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube+oauth2] qJXKhu5UZwk: nsig extraction failed: You may experience throttling for some formats
         n = 2NwWsTmySuXGunM ; player = https://www.youtube.com/s/player/baafab19/player_ias.vflset/en_US/base.js
[youtube+oauth2] qJXKhu5UZwk: Downloading m3u8 information
WARNING: [youtube+oauth2] Incomplete data received in embedded initial data; re-fetching using API.
[youtube+oauth2] qJXKhu5UZwk: Downloading initial data API JSON
WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube+oauth2] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube+oauth2] qJXKhu5UZwk: Downloading initial data API JSON
WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube+oauth2] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube+oauth2] qJXKhu5UZwk: Downloading initial data API JSON
WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube+oauth2] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube+oauth2] qJXKhu5UZwk: Downloading initial data API JSON
WARNING: [youtube+oauth2] YouTube said: ERROR - Request contains an invalid argument.
ERROR: [youtube+oauth2] qJXKhu5UZwk: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/extractor/youtube.py", line 4478, in _real_extract
    initial_data = self._extract_response(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/extractor/youtube.py", line 996, in _extract_response
    next(main_retries)
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/utils/_utils.py", line 5077, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/extractor/common.py", line 3857, in _error_or_warning
    RetryManager.report_retry(
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/utils/_utils.py", line 5085, in report_retry
    raise e
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/extractor/youtube.py", line 968, in _extract_response
    response = self._call_api(
               ^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/extractor/youtube.py", line 616, in _call_api
    return self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/extractor/common.py", line 1133, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/extractor/common.py", line 1093, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/extractor/common.py", line 954, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/extractor/common.py", line 903, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/extractor/common.py", line 890, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/YoutubeDL.py", line 4142, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-project/src/yt-dlp/yt_dlp/networking/_requests.py", line 361, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request
```

**Comment by alimirjahani7** [comment] 2024-11-11 14:49
the problem was Oauth arguments shouldn't be passed any more

**Comment by Grub4K** [comment] 2024-11-11 15:24
why reopen this?

**Comment by alimirjahani7** [comment] 2024-11-11 15:37
the OAuth wasn't the problem 
removing the OAuth would just try to download but will face Rate limit after a while

**Comment by Grub4K** [comment] 2024-11-11 15:40
You are using an outdated version. update and then check if you hit any of #10128, #10085 or #10108 (in which case you can close this) and post a verbose log if not.

**Comment by alimirjahani7** [comment] 2024-11-11 15:46
same thing on the latest version


[debug] Command-line config: ['-f', 'bestvideo[height<=?720][ext=mp4]+bestaudio/best', 'https://www.youtube.com/watch?v=qJXKhu5UZwk', '--username=PRIVATE', '--password=', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b]
[debug] Lazy loading extractors is disabled
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.04 from yt-dlp/yt-dlp)
[debug] Loading youtube.oauth_refresh_token_default from cache
[youtube] oauth: Refreshing access token
[debug] [youtube] oauth: Logged in using profile "default"
[youtube] Extracting URL: https://www.youtube.com/watch?v=qJXKhu5UZwk
[youtube] qJXKhu5UZwk: Downloading webpage
[youtube] qJXKhu5UZwk: Downloading ios player API JSON
[youtube] qJXKhu5UZwk: Downloading mweb player API JSON
[debug] Loading youtube-nsig.baafab19 from cache
[debug] [youtube] Decrypted nsig bSjcGguZB4X0agm => lD-V3o-gdmwNIw
[debug] Loading youtube-nsig.baafab19 from cache
[debug] [youtube] Decrypted nsig 5DF9sOj9GJubaHH => woPgg-9ayNqcLw
[youtube] qJXKhu5UZwk: Downloading m3u8 information
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] qJXKhu5UZwk: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] qJXKhu5UZwk: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] qJXKhu5UZwk: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] qJXKhu5UZwk: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
ERROR: [youtube] qJXKhu5UZwk: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/extractor/youtube.py", line 4902, in _real_extract
    initial_data = self._extract_response(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/extractor/youtube.py", line 1270, in _extract_response
    next(main_retries)
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/utils/_utils.py", line 5271, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/extractor/common.py", line 3895, in _error_or_warning
    RetryManager.report_retry(
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/utils/_utils.py", line 5279, in report_retry
    raise e
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/extractor/youtube.py", line 1243, in _extract_response
    response = self._call_api(
               ^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/extractor/youtube.py", line 861, in _call_api
    return self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/extractor/common.py", line 1152, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/extractor/common.py", line 1112, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/extractor/common.py", line 962, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/extractor/common.py", line 911, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/extractor/common.py", line 898, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/YoutubeDL.py", line 4162, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ali/.virtualenvs/test-backend/src/yt-dlp/yt_dlp/networking/_requests.py", line 365, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request

**Comment by alimirjahani7** [comment] 2024-11-11 16:56
I did some digging and looks like InfoExtractor._download_webpage is returning very different result base on if it has any auth headers or not ???? it returns less data when it's authenticated

**Comment by bashonly** [comment] 2024-11-11 19:35
Duplicate of #11462

The tl;dr is that oauth is going away completely very soon. Learn to [use cookies instead](https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies)

**Closed by bashonly** 2024-11-11 19:35 UTC
Labels: site-bug, triage
