### ISSUE TITLE
[twitter:shortener] extractor gives 404 error

### ISSUE THREAD

**Issue by krink7** [yt-dlp/yt-dlp#3878] opened 2022-05-26 20:39 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

The twitter::shortener extractor gives a 404 error when the link is reachable via a browser.

### Verbose log

```shell
D:\test>yt-dlp --ignore-config -vU https://t.co/PPJ8b8Eub4
[debug] Command-line config: ['--ignore-config', '-vU', 'https://t.co/PPJ8b8Eub4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 2022-05-23-git-6076dbcb55-essentials_build-www.gyan.dev (setts), ffprobe 2022-05-23-git-6076dbcb55-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [twitter:shortener] Extracting URL: https://t.co/PPJ8b8Eub4
[twitter:shortener] PPJ8b8Eub4: Downloading webpage
ERROR: [twitter:shortener] PPJ8b8Eub4: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\twitter.py", line 695, in _real_extract
  File "yt_dlp\extractor\common.py", line 786, in _request_webpage

  File "yt_dlp\extractor\common.py", line 768, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3596, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by pukkandan** [comment] 2022-05-26 21:25
I can reproduce this issue, but only on Python 3.8. Makes me think it's some bug in python, but not entirely sure

**Comment by krink7** [comment] 2022-05-26 21:32
> I can reproduce this issue, but only on Python 3.8. Makes me think it's some bug in python, but not entirely sure

It was working for me up until last night.  I give this extractor heavy use.

**Comment by coletdjnz** [comment] 2022-05-27 21:49
I had this branch laying around that I never committed, but it seems to fix the issue: https://github.com/coletdjnz/yt-dlp-dev/commit/e20172d32a792ca37fa0f1f211291af42ce77741 

It seems like twitter is TLS fingerprinting based on the curl user agent the extractor adds? ALPN is set by curl by default afaik, so that would make sense.

I'm not sure why this isn't needed for 3.10. They did introduce adding ALPN by default in 3.10 *when there is no SSL context provided*, but we are providing our own custom one.


https://github.com/coletdjnz/yt-dlp-dev/runs/6632222494?check_suite_focus=true

**Comment by pukkandan** [comment] 2022-05-27 23:05
@coletdjnz Since py3.10 has this by default, you can push this to master. Pls leave a comment in the code referring to both this issue and the python issue

> I'm not sure why this isn't needed for 3.10. They did introduce adding ALPN by default in 3.10 _when there is no SSL context provided_, but we are providing our own custom one.

I didn't look at the code closely, but if I had to guess, It's probably set by `set_default_context` which we do call before overriding parameters that we want to change

**Closed** 2022-05-28 03:46 UTC
Labels: help wanted, external issue, site-bug

**Comment by dirkf** [comment] 2022-05-28 12:34
In case this was an issue underlying various unexpected 404/403 errors, I made a version for yt-dl, as below. However, in testing against the problem URL https://t.co/PPJ8b8Eub4 I found that listing formats succeeded for Python in (2.7, 3.5, 3.9) regardless of the patch. Possibly Twitter's CDN is less choosy today?

```py
--- old/youtube_dl/utils.py
+++ new/youtube_dl/utils.py
@@ -2292,12 +2292,30 @@ def formatSeconds(secs):
 
 
 def make_HTTPS_handler(params, **kwargs):
+
+    # https://www.rfc-editor.org/info/rfc7301
+    ALPN_PROTOCOLS = ['http/1.1']
+
+    def set_alpn_protocols(ctx):
+        # From https://github.com/yt-dlp/yt-dlp/commit/2c6dcb65fb612fc5bc5c61937bf438d3c473d8d0
+        # Thanks @coletdjnz
+        # Some servers may (wrongly) reject requests if ALPN extension is not sent. See:
+        # https://github.com/python/cpython/issues/85140
+        # https://github.com/yt-dlp/yt-dlp/issues/3878
+        try:
+            ctx.set_alpn_protocols(ALPN_PROTOCOLS)
+        except (AttributeError, NotImplementedError):
+            # Python < 2.7.10, not ssl.HAS_ALPN
+            pass
+
     opts_no_check_certificate = params.get('nocheckcertificate', False)
     if hasattr(ssl, 'create_default_context'):  # Python >= 3.4 or 2.7.9
         context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
+        set_alpn_protocols(context)
         if opts_no_check_certificate:
             context.check_hostname = False
             context.verify_mode = ssl.CERT_NONE
+
         try:
             return YoutubeDLHTTPSHandler(params, context=context, **kwargs)
         except TypeError:
@@ -2313,6 +2331,7 @@ def make_HTTPS_handler(params, **kwargs):
                                if opts_no_check_certificate
                                else ssl.CERT_REQUIRED)
         context.set_default_verify_paths()
+        set_alpn_protocols(context)
         return YoutubeDLHTTPSHandler(params, context=context, **kwargs)
```
