### ISSUE TITLE
Vimeo error 403 access forbidden issue

### ISSUE THREAD

**Issue by Synida** [yt-dlp/yt-dlp#10326] opened 2024-07-01 16:50 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US/aws - us-east-1

### Provide a description that is worded well enough to be understood

Hi,

Let's start with this: `I've checked that all provided URLs are playable in a browser with the same IP and same login details`
So, this is not really possible, as this is on a aws ec2 server that has no gui. I think I could use a text based browser maybe(?) just to see if the video is loading? Or maybe set up a proxy, but I wouldn't be able to connect because of the SRE and CSEC policies.
Technically there are multiple servers where we have yt-dlp, and everything was working in the last X months until last friday everywhere.
I don't really have any other way of asking about this impossible situation than in this same issue ticket, so if this counts as trigger for block, I understand.

I've spent all day today and friday trying to figure out, how to get this work, so here is the info from my logs.

This is how we used this before:
`./yt-dlp -e https://vimeo.com/23222146`
I have around 5-6 links I tried this with, then I checked out the extractor folder, and went through the public test links in the vimeo.py file, and I got the same result.
Then I noticed that we did have an older version, which was this one: [2023.02.17](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.02.17)
Then going through one of the readme documents here, I found the updater option so I checked out the lts, which resulted in the same output.
Then I found this issue, that looked very similar: https://github.com/yt-dlp/yt-dlp/issues/10153
I followed the instructions, first I tried the --impersonate chrome option after installing the curl_cffi package, I checked it with every browser options and all but Safari resulted in the same error. For Safari it was some error message with mailformed xml input or something like that - I assumed that I'm missing some input parameter, and that's why it didn't get that far.
Then I cloned the repository, compiled the master branch with curl_cffi in the exact same way as it it written there in a comment, and I got the same 403 error message.

This is the output I get when using the -vU option:
```
[root@services bin]# ./yt-dlp-local -vU --impersonate Chrome -e https://vimeo.com/112774669
[debug] Command-line config: ['-vU', '--impersonate', 'Chrome', '-e', 'https://vimeo.com/112774669']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version local@2024.07.01.2 [e6a22834d] (linux_exe)
[debug] Python 3.8.19 (CPython x86_64 64bit) - Linux-3.10.0-1127.18.2.el7.x86_64-x86_64-with-glibc2.14 (OpenSSL 1.0.2k-fips  26 Jan 2017, glibc 2.17)
[debug] exe versions: ffmpeg 3.4.1-static, ffprobe 3.4.1-static
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, secretstorage-3.3.3, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, websockets, curl_cffi
[debug] Loaded 1826 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (local@2024.07.01.2)
[vimeo] Extracting URL: https://vimeo.com/112774669
[vimeo] 112774669: Downloading webpage
ERROR: [vimeo] 112774669: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "yt_dlp/extractor/common.py", line 740, in extract
  File "yt_dlp/extractor/vimeo.py", line 834, in _real_extract
  File "yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
  File "yt_dlp/extractor/common.py", line 909, in _request_webpage

  File "yt_dlp/extractor/common.py", line 896, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 4141, in urlopen
  File "yt_dlp/networking/common.py", line 117, in send
  File "yt_dlp/networking/_curlcffi.py", line 138, in send
  File "yt_dlp/networking/_helper.py", line 208, in wrapper
  File "yt_dlp/networking/common.py", line 337, in send
  File "yt_dlp/networking/_curlcffi.py", line 234, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

I must admit, that I'm not very pro with this package, and I think I'm about to reach the limits of my current knowledge with this.

I may add that I didn't have any account I'm using this with, I don't know on what basis the request is blocked, so what I was hoping for is if I could get some pointers on how this is usually work or what am I might missing that should be used as well.

Thanks!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--impersonate', 'Chrome', '-e', 'https://vimeo.com/112774669']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version local@2024.07.01.2 [e6a22834d] (linux_exe)
[debug] Python 3.8.19 (CPython x86_64 64bit) - Linux-3.10.0-1127.18.2.el7.x86_64-x86_64-with-glibc2.14 (OpenSSL 1.0.2k-fips  26 Jan 2017, glibc 2.17)
[debug] exe versions: ffmpeg 3.4.1-static, ffprobe 3.4.1-static
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, secretstorage-3.3.3, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, websockets, curl_cffi
[debug] Loaded 1826 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (local@2024.07.01.2)
[vimeo] Extracting URL: https://vimeo.com/112774669
[vimeo] 112774669: Downloading webpage
ERROR: [vimeo] 112774669: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "yt_dlp/extractor/common.py", line 740, in extract
  File "yt_dlp/extractor/vimeo.py", line 834, in _real_extract
  File "yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
  File "yt_dlp/extractor/common.py", line 909, in _request_webpage

  File "yt_dlp/extractor/common.py", line 896, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 4141, in urlopen
  File "yt_dlp/networking/common.py", line 117, in send
  File "yt_dlp/networking/_curlcffi.py", line 138, in send
  File "yt_dlp/networking/_helper.py", line 208, in wrapper
  File "yt_dlp/networking/common.py", line 337, in send
  File "yt_dlp/networking/_curlcffi.py", line 234, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by Synida** [comment] 2024-07-01 16:55
Ok, I just saw that someone opened the exact same issue with me in the same time, so idk should this be closed or linked?

I checked out the option too where I use http instead of https and I got the same result for that as well.
```
[root@services bin]# ./yt-dlp-local -vU --impersonate Chrome -e http://vimeo.com/112774669
[debug] Command-line config: ['-vU', '--impersonate', 'Chrome', '-e', 'http://vimeo.com/112774669']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version local@2024.07.01.2 [e6a22834d] (linux_exe)
[debug] Python 3.8.19 (CPython x86_64 64bit) - Linux-3.10.0-1127.18.2.el7.x86_64-x86_64-with-glibc2.14 (OpenSSL 1.0.2k-fips  26 Jan 2017, glibc 2.17)
[debug] exe versions: ffmpeg 3.4.1-static, ffprobe 3.4.1-static
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, secretstorage-3.3.3, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, websockets, curl_cffi
[debug] Loaded 1826 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (local@2024.07.01.2)
[vimeo] Extracting URL: http://vimeo.com/112774669
[vimeo] 112774669: Downloading webpage
ERROR: [vimeo] 112774669: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "yt_dlp/extractor/common.py", line 740, in extract
  File "yt_dlp/extractor/vimeo.py", line 834, in _real_extract
  File "yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
  File "yt_dlp/extractor/common.py", line 909, in _request_webpage

  File "yt_dlp/extractor/common.py", line 896, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 4141, in urlopen
  File "yt_dlp/networking/common.py", line 117, in send
  File "yt_dlp/networking/_curlcffi.py", line 138, in send
  File "yt_dlp/networking/_helper.py", line 208, in wrapper
  File "yt_dlp/networking/common.py", line 337, in send
  File "yt_dlp/networking/_curlcffi.py", line 234, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment] 2024-07-01 17:00
could you try the `http` url *without* `--impersonate`?

**Comment by bashonly** [comment] 2024-07-01 17:00
Also, are you using a data center IP / VPN / proxy?

**Comment by Synida** [comment] 2024-07-01 17:03
> could you try the `http` url _without_ `--impersonate`?

```shell
[root@services bin]# ./yt-dlp-local -vU -e http://vimeo.com/112774669
[debug] Command-line config: ['-vU', '-e', 'http://vimeo.com/112774669']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version local@2024.07.01.2 [e6a22834d] (linux_exe)
[debug] Python 3.8.19 (CPython x86_64 64bit) - Linux-3.10.0-1127.18.2.el7.x86_64-x86_64-with-glibc2.14 (OpenSSL 1.0.2k-fips  26 Jan 2017, glibc 2.17)
[debug] exe versions: ffmpeg 3.4.1-static, ffprobe 3.4.1-static
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, secretstorage-3.3.3, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, websockets, curl_cffi
[debug] Loaded 1826 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (local@2024.07.01.2)
[vimeo] Extracting URL: http://vimeo.com/112774669
[vimeo] 112774669: Downloading webpage
ERROR: [vimeo] 112774669: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "yt_dlp/extractor/common.py", line 740, in extract
  File "yt_dlp/extractor/vimeo.py", line 834, in _real_extract
  File "yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
  File "yt_dlp/extractor/common.py", line 909, in _request_webpage

  File "yt_dlp/networking/_urllib.py", line 396, in _send
  File "urllib/request.py", line 531, in open
  File "urllib/request.py", line 640, in http_response
  File "urllib/request.py", line 569, in error
  File "urllib/request.py", line 502, in _call_chain
  File "urllib/request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp/extractor/common.py", line 896, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 4141, in urlopen
  File "yt_dlp/networking/common.py", line 117, in send
  File "yt_dlp/networking/_helper.py", line 208, in wrapper
  File "yt_dlp/networking/common.py", line 337, in send
  File "yt_dlp/networking/_urllib.py", line 401, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment] 2024-07-01 17:05
Can you view in the video **in a browser from the same IP**?

**Comment by Synida** [comment] 2024-07-01 17:09
> Also, are you using a data center IP / VPN / proxy?

I think we are using Elastic IP - double checking... - yes we are using Elastic IPs, this one that is assigned to these EC2 instances are public IPs.

I can do the following with a YT link, which does work it seems:
```shell
[root@services bin]# ./yt-dlp-local -vU --impersonate Chrome -e https://www.youtube.com/watch?v=h8WqELvQF6E
[debug] Command-line config: ['-vU', '--impersonate', 'Chrome', '-e', 'https://www.youtube.com/watch?v=h8WqELvQF6E']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version local@2024.07.01.2 [e6a22834d] (linux_exe)
[debug] Python 3.8.19 (CPython x86_64 64bit) - Linux-3.10.0-1127.18.2.el7.x86_64-x86_64-with-glibc2.14 (OpenSSL 1.0.2k-fips  26 Jan 2017, glibc 2.17)
[debug] exe versions: ffmpeg 3.4.1-static, ffprobe 3.4.1-static
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, secretstorage-3.3.3, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, websockets, curl_cffi
[debug] Loaded 1826 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (local@2024.07.01.2)
[youtube] Extracting URL: https://www.youtube.com/watch?v=h8WqELvQF6E
[youtube] h8WqELvQF6E: Downloading webpage
[youtube] h8WqELvQF6E: Downloading ios player API JSON
[debug] [youtube] Extracting signature function js_81a0fcab_106
[youtube] h8WqELvQF6E: Downloading player 81a0fcab
[debug] Saving youtube-sigfuncs.js_81a0fcab_106 to cache
[debug] Saving youtube-nsig.81a0fcab to cache
[debug] [youtube] Decrypted nsig r6h6T4NmeFFhFV1ec4Xi => VIO_ergDHvbCoA
[debug] Loading youtube-nsig.81a0fcab from cache
[debug] [youtube] Decrypted nsig 9F4CoiU97gdIGxLDqIP0 => RTlvtFybMdopyg
[debug] [youtube] Extracting signature function js_81a0fcab_102
[debug] Saving youtube-sigfuncs.js_81a0fcab_102 to cache
[youtube] h8WqELvQF6E: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] h8WqELvQF6E: Downloading 1 format(s): 303+251
Funniest moments in Invincible [Season 1]
```

> Can you view in the video in a browser from the same IP?
I don't know how could I do that. I don't have GUI - as I mentioned above. I can't open ports because of CSEC and SRE policies - also doesn't have permission - if I would want to connect with a proxy from my local environment.
And I'm not sure if the CLI text based browser would do the job. Any tips how you guys usually do it in this case, so I could replicate it?

**Comment by bashonly** [comment] 2024-07-01 17:13
Closing as duplicate of #10325

I'll add a note to that issue that Vimeo is discriminating against DC IPs and mitigation tactics will not work for affected IPs

If you can't play a URL in browser then you can't expect yt-dlp to work; you even checked this off in the issue checklist:

> - [x] I've checked that all provided URLs are playable in a browser with the same IP and same login details

**Closed by bashonly** 2024-07-01 17:13 UTC
Labels: duplicate, site-bug, site:vimeo

**Comment by bashonly** [comment] 2024-07-01 17:24
>  Any tips how you guys usually do it in this case, so I could replicate it?

If you can't run a major browser like Chrome / chromium / Firefox / Brave then there's nothing that can be done really
