### ISSUE TITLE
Stuck downloading in 99 percents.

### ISSUE THREAD

**Issue by S-hdyn** [yt-dlp/yt-dlp#423] opened 2021-06-20 04:55 UTC
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.06.09**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
yt-dlp --allow-unplayable-formats -k -f bestvideo,bestaudio -N 64 -v https://m.cdn.klikfilm.net/restorasi_para_perintis_kemerdekaan/mp4dash/stream_widevine.mpd
[debug] Command-line config: ['--allow-unplayable-formats', '-k', '-f', 'bestvideo,bestaudio', '-N', '64', '-v', 'https://m.cdn.klikfilm.net/restorasi_para_perintis_kemerdekaan/mp4dash/stream_widevine.mpd']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.06.09 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://m.cdn.klikfilm.net/restorasi_para_perintis_kemerdekaan/mp4dash/stream_widevine.mpd
[generic] stream_widevine: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] stream_widevine: Downloading webpage
[generic] stream_widevine: Extracting information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] stream_widevine: Downloading 2 format(s): video_avc1_5, audio_en_mp4a_2
[debug] Invoking downloader on "https://m.cdn.klikfilm.net/restorasi_para_perintis_kemerdekaan/mp4dash/stream_widevine.mpd"
[dashsegments] Total fragments: 3035
[download] Destination: stream_widevine [stream_widevine].mp4
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100.0% of ~818.27MiB at  8.87KiB/s ETA 00:00         ERROR: unable to download video data: [WinError 32] The process cannot access the file because it is being used by another process: 'stream_widevine [stream_widevine].mp4.part-Frag1860'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 2645, in process_info
  File "yt_dlp\YoutubeDL.py", line 2308, in dl
  File "yt_dlp\downloader\common.py", line 384, in download
  File "yt_dlp\downloader\dash.py", line 180, in real_download
  File "yt_dlp\downloader\dash.py", line 130, in append_fragment
  File "yt_dlp\downloader\fragment.py", line 129, in _append_fragment
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'stream_widevine [stream_widevine].mp4.part-Frag1860'

[debug] Invoking downloader on "https://m.cdn.klikfilm.net/restorasi_para_perintis_kemerdekaan/mp4dash/stream_widevine.mpd"
[dashsegments] Total fragments: 3642
[download] Destination: stream_widevine [stream_widevine].m4a
WARNING: The download speed shown is only of one thread. This is a known issue
[download]  99.6% of ~173.78MiB at 13.68KiB/s ETA 00:00

```

## Description

Hello. I've been trying to download some movies from VOD with DRM dashsegments. I used -N 64 aka multithread to boost up ma downlad. But when it comes to 99. some number percents, got stuck and not downloading anymore. When I tried re-download them, it said that file already downloaded mewanhile fragment files haven't muxed yet. I've reinstalled yt-dlp many times and tried to download movies [again] many times too but still gave me errors. I've discovered many platforms, but the results still same. Any idea?

**Comment by pukkandan** [comment] 2021-06-20 23:10
Duplicate of #407

**Closed by pukkandan** 2021-06-20 23:10 UTC
