### ISSUE TITLE
support for http://dzen.ru/video/watch

### ISSUE THREAD

**Issue by natee74a** [yt-dlp/yt-dlp#11846] opened 2024-12-17 19:47 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Russia

### Example URLs

single video : https://dzen.ru/video/watch/6759f6b178cb546846d74e7d
playlist: https://dzen.ru/id/66636f6e74e3fd4b431e9301?clid=1400

### Provide a description that is worded well enough to be understood

I cannot download video clips from that site. ie. dzen.ru/video/watch

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://dzen.ru/video/watch/6759f6b178cb546846d74e7d
[debug] Command-line config: ['-vU', 'https://dzen.ru/video/watch/6759f6b178cb546846d74e7d']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.13 from yt-dlp/yt-dlp [542166962] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-126-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.13 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.13 from yt-dlp/yt-dlp)
[ZenYandex] Extracting URL: https://dzen.ru/video/watch/6759f6b178cb546846d74e7d
[ZenYandex] 6759f6b178cb546846d74e7d: Downloading webpage
[ZenYandex] 6759f6b178cb546846d74e7d: Redirecting
ERROR: [ZenYandex] 6759f6b178cb546846d74e7d: Unable to extract metadata; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/yandexvideo.py", line 260, in _real_extract
    data_json = self._search_json(
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 1360, in _search_json
    json_string = self._search_regex(
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 1346, in _search_regex
    raise RegexNotFoundError(f'Unable to extract {_name}')
```

**Comment by bashonly** [comment] 2024-12-17 19:52
Duplicate of #11385

**Closed by bashonly** 2024-12-17 19:52 UTC
Labels: site-request, triage
