### ISSUE TITLE
forking the process to download multiple videos at a time

### ISSUE THREAD

**Issue by solomoncyj** [yt-dlp/yt-dlp#10476] opened 2024-07-15 11:46 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

during the download of a playlist or multiple videos, allow the process to fork itself  to a user defined number of times or the number of threads the cpu can has to speed up download. this can help situations such as if download speed is throttled due to distance from sever or intentionally by server

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by solomoncyj** [comment] 2024-07-15 11:48
![image](https://github.com/user-attachments/assets/c3960166-9356-4007-a789-3d885acc6669)
example of why its need: my pc can download at 15mbps very well, however it randomly drops to 300 kbps for some reason. if 4 videos are downloaded at the same time, it could speed up the downloads

**Comment by bashonly** [comment] 2024-07-15 14:27
Duplicate of #1918

**Closed by bashonly** 2024-07-15 14:27 UTC
Labels: enhancement, triage
