### ISSUE TITLE
Youtube premium foramt is not consitent for download percentage

### ISSUE THREAD

**Issue by kolbdog323** [yt-dlp/yt-dlp#10488] opened 2024-07-16 23:51 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When you download the premium bitrate 616 the download percent is not consitent it keeps bouncing around it shows 17 then shows 15 then it shows 19 then 17 it doesnt remain constant like 15%, 16%, 17% since it shows an amount of fragments so the download percent is not consistent

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', '616+251', 'https://youtu.be/uXYarIMNMlY?si=jBVMJxYDcEbETli6']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.16.232919 from yt-dlp/yt-dlp-nightly-builds [37c233562] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-07-15-git-350146a1ea-full_build-www.gyan.dev (setts), ffprobe 2024-07-15-git-350146a1ea-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.07.16.232919 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.07.16.232919 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://youtu.be/uXYarIMNMlY?si=jBVMJxYDcEbETli6
[youtube] uXYarIMNMlY: Downloading webpage
[youtube] uXYarIMNMlY: Downloading ios player API JSON
[debug] Loading youtube-nsig.65e3708e from cache
[debug] [youtube] Decrypted nsig y-UMbOjQA8QHWV4uJTC => FQUAVRBL7hBJXg
[debug] Loading youtube-nsig.65e3708e from cache
[debug] [youtube] Decrypted nsig TTu8beQqNbsB7p5iEYh => ZF2nfizxLxu9kQ
[youtube] uXYarIMNMlY: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] uXYarIMNMlY: Downloading 1 format(s): 616+251
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1721195407/ei/LweXZpPnD72ykucP07GU0A4/ip/71.171.35.193/id/b9761aac830d3256/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D42857583%3Bdur%3D275.408%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1712428124315339/rqh/1/hls_chunk_host/rr1---sn-8xgp1vo-p5qs.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/pf/mm/31,26/mn/sn-8xgp1vo-p5qs,sn-vgqsrnzr/ms/au,onr/mv/m/mvi/1/pcm2cms/yes/pl/18/force_finished/1/gcr/us/initcwndbps/1238750/vprv/1/playlist_type/DVR/dover/13/txp/5532434/mt/1721173508/fvip/2/short_key/1/keepalive/yes/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,force_finished,gcr,vprv,playlist_type/sig/AJfQdSswRgIhAJQ9ny5ZVFcNJgxXIkzJCvuSmpVDx6b6-yGNGHqiJ7cMAiEAglGU7aIHQL_2JHAIdYMZuLO60uUonFMgwHLWo_SksZY%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pcm2cms,pl,initcwndbps/lsig/AHlkHjAwRQIgPqMjddq1V6EmRlvS3jRjKJWGcaJdjwIEAWN2aXeTstACIQDuzkIyxVouYGxYHwVTD1oaZCqQemtGZcBzd3pEBghI9Q%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 52
[download] Destination: Grannies🥫Read by Suranne Jones ｜ Bluey Book Reads ｜ Bluey [uXYarIMNMlY].f616.mp4
[debug] File locking is not supported. Proceeding without locking
[download]   6.6% of ~  30.49MiB at  285.02KiB/s ETA 00:40 (frag 2/52)
```

**Comment by bashonly** [comment] 2024-07-17 01:39
Duplicate of #7195

**Closed by bashonly** 2024-07-17 01:39 UTC
Labels: bug, triage
