### ISSUE TITLE
Suggest to make a flag that would write (1) (2) (3) and so on at the end of files with the same name

### ISSUE THREAD

**Issue by pavel355** [yt-dlp/yt-dlp#10784] opened 2024-08-18 10:16 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

In this program, there is a problem. If at the end point of saving video or audio, there is a file with the same name, the program just writes an error and does not download. I suggest to make a flag that would write (1) (2) (3) and so on at the end of files with the same name. It's just that I very often download streams from Twitch, and many streamers name the streams the same, and I leave downloading several streams at once for the night

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment] 2024-08-18 15:45
Duplicate of #5485

**Closed by bashonly** 2024-08-18 15:45 UTC
Labels: enhancement, triage
