### ISSUE TITLE
"No video formats found" error on TubiTV

### ISSUE THREAD

**Issue by heliosyne** [yt-dlp/yt-dlp#5128] opened 2022-10-03 16:17 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Tried to download https://tubitv.com/movies/685451 and got a "No video formats found!" error. Reporting as requested.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--embed-subs', '--remux-video', 'mkv', 'https://tubitv.com/movies/685451']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.9.14 (CPython 64bit) - FreeBSD-12.3-RELEASE-p6-amd64-64bit-ELF (libc 7)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.14, mutagen-1.45.1, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] Using fake IP 6.228.51.200 (US) as X-Forwarded-For
[debug] [TubiTv] Extracting URL: https://tubitv.com/movies/685451
[TubiTv] 685451: Downloading JSON metadata
[info] 685451: Downloading subtitles: English
ERROR: [TubiTv] 685451: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/melissa/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/home/melissa/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1556, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/melissa/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1614, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/melissa/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2546, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/melissa/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1025, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [TubiTv] 685451: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by october262** [comment] 2022-10-03 20:50
if i try playing this - https://tubitv.com/movies/685451
i get  "sorry this video is not currently available"

**Comment by bashonly** [comment] 2022-10-03 20:55
DRM formats only

**Comment by heliosyne** [comment] 2022-10-04 08:31
> it's DRM protected

Does the tubi extractor need a fix like the paramount one did?

**Comment by october262** [comment] 2022-10-04 18:50
> > it's DRM protected
> 
> Does the tubi extractor need a fix like the paramount one did?

there's nothing to fix, yt-dlp does not download DRM protected content
see this thread for reference - https://github.com/yt-dlp/yt-dlp/issues/2727

**Comment by coletdjnz** [comment] 2022-10-07 06:15
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/266 https://github.com/yt-dlp/yt-dlp/issues/2727

**Comment by pukkandan** [comment] 2022-10-07 11:48
I shouldn't have closed the other issues. I think it's better to keep DRM issues open if yt-dlp gives the wrong error message. It can be closed when the extractor is updated to detect the case properly

**Comment by heliosyne** [comment] 2022-10-07 16:56
> > > it's DRM protected
> > 
> > 
> > Does the tubi extractor need a fix like the paramount one did?
> 
> there's nothing to fix, yt-dlp does not download DRM protected content see this thread for reference - #2727

I don't mean fix as in make it possible to download DRM content. I mean fix as in improve DRM detection and correctly alert the user about it. As in, like the fix that just done for the paramount extractor, on the other ticket I recently opened about this same issue. Hence the "like the paramount one" reference.

**Closed** 2022-10-07 20:35 UTC
Labels: DRM, site-bug
