### ISSUE TITLE
TestConvertThumbnail.test_escaping test fails with ffmpeg-5

### ISSUE THREAD

**Issue by PPed72** [yt-dlp/yt-dlp#5231] opened 2022-10-13 09:37 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

_______________________________________________ TestConvertThumbnail.test_escaping ________________________________________________

self = <test.test_postprocessors.TestConvertThumbnail testMethod=test_escaping>

    def test_escaping(self):
        pp = FFmpegThumbnailsConvertorPP()
        if not pp.available:
            print('Skipping: ffmpeg not found')
            return
    
        file = 'test/testdata/thumbnails/foo %d bar/foo_%d.{}'
        tests = (('webp', 'png'), ('png', 'jpg'))
    
        for inp, out in tests:
            out_file = file.format(out)
            if os.path.exists(out_file):
                os.remove(out_file)
>           pp.convert_thumbnail(file.format(inp), out)

file       = 'test/testdata/thumbnails/foo %d bar/foo_%d.{}'
inp        = 'webp'
out        = 'png'
out_file   = 'test/testdata/thumbnails/foo %d bar/foo_%d.png'
pp         = <yt_dlp.postprocessor.ffmpeg.FFmpegThumbnailsConvertorPP object at 0x7fe34d7a17e0>
self       = <test.test_postprocessors.TestConvertThumbnail testMethod=test_escaping>
tests      = (('webp', 'png'), ('png', 'jpg'))

test/test_postprocessors.py:56: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
yt_dlp/postprocessor/ffmpeg.py:1093: in convert_thumbnail
    self.real_run_ffmpeg(
        _          = 'test/testdata/thumbnails/foo %d bar/foo_%d'
        self       = <yt_dlp.postprocessor.ffmpeg.FFmpegThumbnailsConvertorPP object at 0x7fe34d7a17e0>
        source_ext = '.webp'
        target_ext = 'png'
        thumbnail_conv_filename = 'test/testdata/thumbnails/foo %d bar/foo_%d.png'
        thumbnail_filename = 'test/testdata/thumbnails/foo %d bar/foo_%d.webp'
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <yt_dlp.postprocessor.ffmpeg.FFmpegThumbnailsConvertorPP object at 0x7fe34d7a17e0>
input_path_opts = [('test/testdata/thumbnails/foo %d bar/foo_%d.webp', ['-f', 'image2', '-pattern_type', 'none'])]
output_path_opts = [('test/testdata/thumbnails/foo %%d bar/foo_%%d.png', [])]

    def real_run_ffmpeg(self, input_path_opts, output_path_opts, *, expected_retcodes=(0,)):
        self.check_version()
    
        oldest_mtime = min(
            os.stat(encodeFilename(path)).st_mtime for path, _ in input_path_opts if path)
    
        cmd = [encodeFilename(self.executable, True), encodeArgument('-y')]
        # avconv does not have repeat option
        if self.basename == 'ffmpeg':
            cmd += [encodeArgument('-loglevel'), encodeArgument('repeat+info')]
    
        def make_args(file, args, name, number):
            keys = ['_%s%d' % (name, number), '_%s' % name]
            return
    
        file = 'test/testdata/thumbnails/foo %d bar/foo_%d.{}'
        tests = (('webp', 'png'), ('png', 'jpg'))
    
        for inp, out in tests:
            out_file = file.format(out)
            if os.path.exists(out_file):
                os.remove(out_file)
>           pp.convert_thumbnail(file.format(inp), out)

file       = 'test/testdata/thumbnails/foo %d bar/foo_%d.{}'
inp        = 'webp'
out        = 'png'
out_file   = 'test/testdata/thumbnails/foo %d bar/foo_%d.png'
pp         = <yt_dlp.postprocessor.ffmpeg.FFmpegThumbnailsConvertorPP object at 0x7fe34d7a17e0>
self       = <test.test_postprocessors.TestConvertThumbnail testMethod=test_escaping>
tests      = (('webp', 'png'), ('png', 'jpg'))

test/test_postprocessors.py:56: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
yt_dlp/postprocessor/ffmpeg.py:1093: in convert_thumbnail
    self.real_run_ffmpeg(
        _          = 'test/testdata/thumbnails/foo %d bar/foo_%d'
        self       = <yt_dlp.postprocessor.ffmpeg.FFmpegThumbnailsConvertorPP object at 0x7fe34d7a17e0>
        source_ext = '.webp'
        target_ext = 'png'
        thumbnail_conv_filename = 'test/testdata/thumbnails/foo %d bar/foo_%d.png'
        thumbnail_filename = 'test/testdata/thumbnails/foo %d bar/foo_%d.webp'
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <yt_dlp.postprocessor.ffmpeg.FFmpegThumbnailsConvertorPP object at 0x7fe34d7a17e0>
input_path_opts = [('test/testdata/thumbnails/foo %d bar/foo_%d.webp', ['-f', 'image2', '-pattern_type', 'none'])]
output_path_opts = [('test/testdata/thumbnails/foo %%d bar/foo_%%d.png', [])]

    def real_run_ffmpeg(self, input_path_opts, output_path_opts, *, expected_retcodes=(0,)):
        self.check_version()
    
        oldest_mtime = min(
            os.stat(encodeFilename(path)).st_mtime for path, _ in input_path_opts if path)
    
        cmd = [encodeFilename(self.executable, True), encodeArgument('-y')]
        # avconv does not have repeat option
        if self.basename == 'ffmpeg':
            cmd += [encodeArgument('-loglevel'), encodeArgument('repeat+info')]
    
        def make_args(file, args, name, number):
            keys = ['_%s%d' % (name, number), '_%s' % name]
            if name == 'o':
                args += ['-movflags', '+faststart']
                if number == 1:
                    keys.append('')
            args += self._configuration_args(self.basename, keys)
            if name == 'i':
                args.append('-i')
            return (
                [encodeArgument(arg) for arg in args]
                + [encodeFilename(self._ffmpeg_filename_argument(file), True)])
    
        for arg_type, path_opts in (('i', input_path_opts), ('o', output_path_opts)):
            cmd += itertools.chain.from_iterable(
                make_args(path, list(opts), arg_type, i + 1)
                for i, (path, opts) in enumerate(path_opts) if path)
    
        self.write_debug('ffmpeg command line: %s' % shell_quote(cmd))
        _, stderr, returncode = Popen.run(
            cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
        if returncode not in variadic(expected_retcodes):
            self.write_debug(stderr)
>           raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
E           yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

_          = ''
arg_type   = 'o'
cmd        = ['ffmpeg',
 '-y',
 '-loglevel',
 'repeat+info',
 '-f',
 'image2',
 '-pattern_type',
 'none',
 '-i',
 'file:test/testdata/thumbnails/foo %d bar/foo_%d.webp',
 '-movflags',
 '+faststart',
 'file:test/testdata/thumbnails/foo %%d bar/foo_%%d.png']
expected_retcodes = (0,)
input_path_opts = [('test/testdata/thumbnails/foo %d bar/foo_%d.webp',
  ['-f', 'image2', '-pattern_type', 'none'])]
make_args  = <function FFmpegPostProcessor.real_run_ffmpeg.<locals>.make_args at 0x7fe34d6f4280>
oldest_mtime = 1664859046.0
output_path_opts = [('test/testdata/thumbnails/foo %%d bar/foo_%%d.png', [])]
path_opts  = [('test/testdata/thumbnails/foo %%d bar/foo_%%d.png', [])]
returncode = 1
self       = <yt_dlp.postprocessor.ffmpeg.FFmpegThumbnailsConvertorPP object at 0x7fe34d7a17e0>
stderr     = ('ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers\n'
 '  built with gcc 12.2.0 (Gentoo 12.2.0 p1)\n'
 '  configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 '
 '--docdir=/usr/share/doc/ffmpeg-5.1.2/html --mandir=/usr/share/man '
 '--enable-shared --cc=x86_64-pc-linux-gnu-gcc --cxx=x86_64-pc-linux-gnu-g++ '
 '--ar=/usr/bin/gcc-ar --nm=/usr/bin/gcc-nm --strip=x86_64-pc-linux-gnu-strip '
 '--ranlib=/usr/bin/gcc-ranlib --pkg-config=x86_64-pc-linux-gnu-pkg-config '
 "--optflags='-O2 -pipe -frecord-gcc-switches -march=skylake -mabm "
 "-ftree-vectorize' --disable-static --enable-avfilter --disable-stripping "
 '--disable-optimizations --disable-libcelt --enable-nonfree --enable-version3 '
 '--disable-indev=oss --disable-indev=jack --disable-indev=sndio '
 '--disable-outdev=oss --disable-outdev=sndio --enable-version3 '
 '--enable-version3 --enable-nonfree --enable-bzlib '
 '--disable-runtime-cpudetect --disable-debug --disable-gcrypt --enable-gnutls '
        self.write_debug('ffmpeg command line: %s' % shell_quote(cmd))
        _, stderr, returncode = Popen.run(
            cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
        if returncode not in variadic(expected_retcodes):
            self.write_debug(stderr)
>           raise FFmpegPostProcessorError(stderr.strip().splitlines()[-1])
E           yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

_          = ''
arg_type   = 'o'
cmd        = ['ffmpeg',
 '-y',
 '-loglevel',
 'repeat+info',
 '-f',
 'image2',
 '-pattern_type',
 'none',
 '-i',
 'file:test/testdata/thumbnails/foo %d bar/foo_%d.webp',
 '-movflags',
 '+faststart',
 'file:test/testdata/thumbnails/foo %%d bar/foo_%%d.png']
expected_retcodes = (0,)
input_path_opts = [('test/testdata/thumbnails/foo %d bar/foo_%d.webp',
  ['-f', 'image2', '-pattern_type', 'none'])]
make_args  = <function FFmpegPostProcessor.real_run_ffmpeg.<locals>.make_args at 0x7fe34d6f4280>
oldest_mtime = 1664859046.0
output_path_opts = [('test/testdata/thumbnails/foo %%d bar/foo_%%d.png', [])]
path_opts  = [('test/testdata/thumbnails/foo %%d bar/foo_%%d.png', [])]
returncode = 1
self       = <yt_dlp.postprocessor.ffmpeg.FFmpegThumbnailsConvertorPP object at 0x7fe34d7a17e0>
stderr     = ('ffmpeg version 5.1.2 Copyright (c) 2000-2022 the FFmpeg developers\n'
 '  built with gcc 12.2.0 (Gentoo 12.2.0 p1)\n'
 '  configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 '
 '--docdir=/usr/share/doc/ffmpeg-5.1.2/html --mandir=/usr/share/man '
 '--enable-shared --cc=x86_64-pc-linux-gnu-gcc --cxx=x86_64-pc-linux-gnu-g++ '
 '--ar=/usr/bin/gcc-ar --nm=/usr/bin/gcc-nm --strip=x86_64-pc-linux-gnu-strip '
 '--ranlib=/usr/bin/gcc-ranlib --pkg-config=x86_64-pc-linux-gnu-pkg-config '
 "--optflags='-O2 -pipe -frecord-gcc-switches -march=skylake -mabm "
 "-ftree-vectorize' --disable-static --enable-avfilter --disable-stripping "
 '--disable-optimizations --disable-libcelt --enable-nonfree --enable-version3 '
 '--disable-indev=oss --disable-indev=jack --disable-indev=sndio '
 '--disable-outdev=oss --disable-outdev=sndio --enable-version3 '
 '--enable-version3 --enable-nonfree --enable-bzlib '
 '--disable-runtime-cpudetect --disable-debug --disable-gcrypt --enable-gnutls '
 '--enable-gmp --enable-gpl --enable-hardcoded-tables --enable-iconv '
 '--enable-libxml2 --enable-lzma --enable-network --enable-opencl '
 '--enable-openssl --enable-postproc --enable-libsmbclient --enable-ffplay '
 '--enable-sdl2 --enable-vaapi --disable-vdpau --enable-vulkan --enable-xlib '
 '--enable-libxcb --enable-libxcb-shm --enable-libxcb-xfixes --enable-zlib '
 '--enable-libcdio --disable-libiec61883 --disable-libdc1394 --disable-libcaca '
 '--enable-openal --enable-opengl --disable-libv4l2 --enable-libpulse '
 '--enable-libdrm --disable-libjack --enable-libopencore-amrwb '
 '--enable-libopencore-amrnb --disable-libcodec2 --enable-libdav1d '
 '--enable-libfdk-aac --enable-libopenjpeg --disable-libjxl '
 '--disable-libbluray --disable-libgme --disable-libgsm --disable-libaribb24 '
 '--disable-mmal --disable-libmodplug --enable-libopus --enable-libilbc '
 '--disable-librtmp --enable-libssh --enable-libspeex --disable-libsrt '
 '--enable-librsvg --disable-ffnvcodec --enable-libvorbis --enable-libvpx '
 '--disable-libzvbi --disable-appkit --enable-libbs2b --disable-chromaprint '
 '--disable-cuda-llvm --disable-libflite --enable-frei0r --disable-libvmaf '
 '--enable-libfribidi --enable-fontconfig --disable-ladspa --enable-lcms2 '
 '--enable-libass --enable-libplacebo --disable-libtesseract --disable-lv2 '
 '--enable-libfreetype --disable-libvidstab --disable-librubberband '
 '--disable-libzmq --disable-libzimg --enable-libsoxr --enable-pthreads '
 '--disable-amf --disable-libvo-amrwbenc --enable-libkvazaar --disable-libaom '
 '--enable-libmp3lame --disable-libopenh264 --disable-librav1e '
 '--disable-libsnappy --enable-libsvtav1 --enable-libtheora '
 '--disable-libtwolame --enable-libwebp --enable-libx264 --enable-libx265 '
 '--enable-libxvid --disable-gnutls --disable-armv5te --disable-armv6 '
 '--disable-armv6t2 --disable-neon --disable-vfp --disable-vfpv3 '
 '--disable-armv8 --disable-mipsdsp --disable-mipsdspr2 --disable-mipsfpu '
 '--disable-altivec --disable-vsx --disable-power8 --disable-amd3dnow '
 '--disable-amd3dnowext --disable-fma4 --disable-xop --cpu=skylake '
 '--enable-lto --enable-doc --enable-htmlpages --enable-manpages\n'
 '  libavutil      57. 28.100 / 57. 28.100\n'
 '  libavcodec     59. 37.100 / 59. 37.100\n'
 '  libavformat    59. 27.100 / 59. 27.100\n'
 '  libavdevice    59.  7.100 / 59.  7.100\n'
 '  libavfilter     8. 44.100 /  8. 44.100\n'
 '  libswscale      6.  7.100 /  6.  7.100\n'
 '  libswresample   4.  7.100 /  4.  7.100\n'
 '  libpostproc    56.  6.100 / 56.  6.100\n'
 "Input #0, image2, from 'file:test/testdata/thumbnails/foo %d "
 "bar/foo_%d.webp':\n"
 '  Duration: 00:00:00.04, start: 0.000000, bitrate: N/A\n'
 '  Stream #0:0: Video: webp, yuv420p(tv, bt470bg/unknown/unknown), 479x309, '
 '25 fps, 25 tbr, 25 tbn\n'
 'Stream mapping:\n'
 '  Stream #0:0 -> #0:0 (webp (native) -> png (native))\n'
 'Press [q] to stop, [?] for help\n'
 "Output #0, image2, to 'file:test/testdata/thumbnails/foo %%d "
 "bar/foo_%%d.png':\n"
 '  Metadata:\n'
 '    encoder         : Lavf59.27.100\n'
 '  Stream #0:0: Video: png, rgb24(pc, gbr/unknown/unknown, progressive), '
 '479x309, q=2-31, 200 kb/s, 25 fps, 25 tbn\n'
 '    Metadata:\n'
 '      encoder         : Lavc59.37.100 png\n'
 'frame=    1 fps=0.0 q=0.0 size=N/A time=00:00:00.00 bitrate=N/A speed=   '
 '0x    \n'
 '[image2 @ 0x564768cf5640] The specified filename '
 "'file:test/testdata/thumbnails/foo %%d bar/foo_%%d.png' does not contain an "
 'image sequence pattern or a pattern is invalid.\n'
 '[image2 @ 0x564768cf5640] Use a pattern such as %03d for an image sequence '
 'or use the -update option (with -frames:v 1 if needed) to write a single '
 'image.\n'
 '[image2 @ 0x564768cf5640] Could not open file : '
 'file:test/testdata/thumbnails/foo %%d bar/foo_%%d.png\n'
 'av_interleaved_write_frame(): Input/output error\n'
 'frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.04 bitrate=N/A '
 'speed=1.48x    \n'
 'video:30kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB '
 'muxing overhead: unknown\n'
 'Conversion failed!\n')

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I can't, because during tests yt-dlp is not installed yet.
```

**Comment by PPed72** [comment] 2022-10-13 09:38
With ffmpeg-4.4.3 tests work fine.

**Comment by pukkandan** [comment] 2022-10-14 02:18
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/4604

**Closed by pukkandan** 2022-10-14 02:18 UTC
Labels: bug, triage
