### ISSUE TITLE
 [prosiebensat1] Unable to extract clip id

### ISSUE THREAD

**Issue by janw** [yt-dlp/yt-dlp#8344] opened 2023-10-13 20:31 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.07** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

Unfortunately `prosiebensat1` seems to be broken. All URLs I tried result in 

> ERROR: [prosiebensat1] (…) Unable to extract clip id

Here's three videos that play just fine in my browser:

* https://www.galileo.tv/video/zu-gast-im-groessten-wohnhaus-der-welt/
* https://www.galileo.tv/video/ungewoehnliche-jobs-schlangen-melker-huepfende-postboten/
* https://www.galileo.tv/video/fast-curious-das-aludosen-experiment/

I uploaded `.dump` files for them here: https://gist.github.com/janw/572aa15d473b1a6860bcf22fc1c55da1

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--write-pages', 'https://www.galileo.tv/video/zu-gast-im-groessten-wohnhaus-der-welt/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip)
[debug] Python 3.11.6 (CPython arm64 64bit) - macOS-14.0-arm64-arm-64bit (OpenSSL 3.1.3 19 Sep 2023)
[debug] exe versions: ffmpeg 6.0 (fdk,setts), ffprobe 6.0, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-3.43.2, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.07, Current version: stable@2023.10.07
yt-dlp is up to date (stable@2023.10.07)
[prosiebensat1] Extracting URL: https://www.galileo.tv/video/zu-gast-im-groessten-wohnhaus-der-welt/
[prosiebensat1] zu-gast-im-groessten-wohnhaus-der-welt/: Downloading webpage
[prosiebensat1] Saving request to zu-gast-im-groessten-wohnhaus-der-welt__https_-_www.galileo.tv_video_zu-gast-im-groessten-wohnhaus-der-welt_.dump
ERROR: [prosiebensat1] zu-gast-im-groessten-wohnhaus-der-welt/: Unable to extract clip id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.7/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.7/libexec/lib/python3.11/site-packages/yt_dlp/extractor/prosiebensat1.py", line 491, in _real_extract
    return self._extract_clip(url, webpage)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.7/libexec/lib/python3.11/site-packages/yt_dlp/extractor/prosiebensat1.py", line 431, in _extract_clip
    clip_id = self._html_search_regex(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.7/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1299, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.10.7/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1263, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment] 2023-10-13 20:35
Duplicate of #7264

Thank you for the page dump files, I will link to them from the other issue

**Closed by bashonly** 2023-10-13 20:35 UTC
Labels: site-bug, triage
