### ISSUE TITLE
[Question] A short description of your question

### ISSUE THREAD

**Issue by pctablet505** [yt-dlp/yt-dlp#1331] opened 2021-10-18 12:35 UTC
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README
- [ ] I've read the opening an issue section in CONTRIBUTING.md
- [ ] I've searched the bugtracker for similar questions including closed ones
- [ ] I have given an appropriate title to the issue

## Question

WRITE QUESTION HERE
Initially I was using youtube-dl but due to speed issues, I switched to yt-dlp, but it is also getting speed issues. After downloading at full speed for certain duration or certain GBs, the speed gets limited to lower speed than full speed. I also tried it on google colab and same happened there, I was downloading a playlist of 23 videos, 6 of them downloaded at full speed 20-50MBPS and then it got throttled to 400kbps- 2mbps.

**Comment by pukkandan** [comment] 2021-10-18 12:38
That is NOT a question!!

Check if your issue is a duplicate of #1301. If not, open a bug report with all details including the verbose log

**Closed by pukkandan** 2021-10-18 12:38 UTC
Labels: question
