### ISSUE TITLE
No Video Formats Found for Facebook Video (v=1089562969553469)"

### ISSUE THREAD

**Issue by HDukenCO** [yt-dlp/yt-dlp#11342] opened 2024-10-24 14:54 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

vietnam

### Provide a description that is worded well enough to be understood

While attempting to download video formats from a Facebook link using yt-dlp, I encountered an error. The command I used was:
yt-dlp -F "https://www.facebook.com/watch/?v=1089562969553469"

The output returned:
[facebook] Extracting URL: https://www.facebook.com/watch/?v=1089562969553469
[facebook] 1089562969553469: Downloading webpage
ERROR: [facebook] 1089562969553469: No video formats found!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp =vU -F "https://www.facebook.com/watch/?v=1089562969553469"
[generic] Extracting URL: =vU
ERROR: [generic] '=vU' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:=vU" ) to search YouTube
[facebook] Extracting URL: https://www.facebook.com/watch/?v=1089562969553469
[facebook] 1089562969553469: Downloading webpage
ERROR: [facebook] 1089562969553469: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment] 2024-10-24 14:58
Duplicate of #11337

**Closed by bashonly** 2024-10-24 14:58 UTC
Labels: duplicate, site-bug, site:facebook

**Comment by Ahmedkhodary97** [comment] 2024-10-28 12:14
Not downloading from Facebook

**Comment by seproDev** [comment] 2024-10-28 13:24
@Ahmedkhodary97 update to nightly. If you are still experiencinh problems open a new issue with a complete verbose log.
