### ISSUE TITLE
Instagram stories: cannot download, says need to log in when already logged in on browser

### ISSUE THREAD

**Issue by steverockwell39** [yt-dlp/yt-dlp#8290] opened 2023-10-06 00:57 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

I am still able to download Instagram 'reels' just fine, but suddenly cannot download any 'stories' as of early morning on October 5th. It says I need to log in when I am already logged in to the same account on Chrome browser. I have been doing this exact same thing daily for the last several months with no problem (downloading 'stories' from multiple users). 

I've seen the notes about how using yt-dlp with Instagram is risky, but somehow I've never had an Instagram account banned due to using yt-dlp.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-o', '%(uploader)s-%(id)s.%(ext)s', '--cookies', 'instagram.com_cookies.txt', 'https:/
/www.instagram.com/stories/kimkardashian/3206599444580335888/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.09.24 [088add956] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-05-26-git-0dcbe1c1aa-full_build-www.gyan.dev (setts), ffprobe 2022-05-26-git-0dcbe1c1aa-fu
ll_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-
11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 125465ac4416bcd4bf1632b899630ceecc08b341e83fdf10bd34700c58ea5152
yt-dlp is up to date (stable@2023.09.24)
[instagram:story] Extracting URL: https://www.instagram.com/stories/kimkardashian/3206599444580335888/
[instagram:story] 3206599444580335888: Downloading webpage
[instagram:story] 3206599444580335888: Downloading JSON metadata
ERROR: [instagram:story] 3206599444580335888: You need to log in to access this content. Use --cookies, --cookies-from-brows
er, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\instagram.py", line 713, in _real_extract
  File "yt_dlp\extractor\common.py", line 1175, in raise_login_required
```

**Comment by october262** [comment] 2023-10-06 01:24
try with --cookies from browser  chrome

**Comment by neilthecellist** [comment] 2023-10-06 01:37
@october262 doesn't work for me, sorry

**Comment by steverockwell39** [comment] 2023-10-06 01:38
had the exact same output

**Comment by neilthecellist** [comment] 2023-10-06 01:42
btw, i'm getting the same errors when downloading Reels, Posts, Stories... It's not just Stories that's affected AFAICT

**Comment by steverockwell39** [comment] 2023-10-06 01:53
just checked again and i can still download reels and posts (videos in photo albums)

currently using gallery-dl as replacement, everything works fine with that

**Comment by gamer191** [comment] 2023-10-06 14:48
> had the exact same output

Please post it anyway (preferably as a verbose log)

**Comment by steverockwell39** [comment] 2023-10-07 05:47
this is with the new yt-dlp update

[debug] Command-line config: ['-vU', '-o', '%(uploader)s-%(id)s.%(ext)s', '--cookies-from-browser', 'chrome', 'https://www.i
nstagram.com/stories/kimkardashian/3206599444580335888/']
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Wiseman\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Wiseman\AppData\Local\Google\Chrome\User Data\Local State"
Extracted 3161 cookies from chrome
[debug] cookie version breakdown: {'v10': 3161, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-05-26-git-0dcbe1c1aa-full_build-www.gyan.dev (setts), ffprobe 2022-05-26-git-0dcbe1c1aa-fu
ll_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-
11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.07, Current version: stable@2023.10.07
Current Build Hash: 7c809be9ad981b2a057bd60d766a9dffb1e88ddea6a9530c416f4741bc297364
yt-dlp is up to date (stable@2023.10.07)
[instagram:story] Extracting URL: https://www.instagram.com/stories/kimkardashian/3206599444580335888/
[instagram:story] 3206599444580335888: Downloading webpage
[instagram:story] 3206599444580335888: Downloading JSON metadata
ERROR: [instagram:story] 3206599444580335888: You need to log in to access this content. Use --cookies, --cookies-from-brows
er, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\instagram.py", line 713, in _real_extract
  File "yt_dlp\extractor\common.py", line 1175, in raise_login_required

**Comment by fmg2099** [comment] 2023-10-08 08:01
Getting the same with --cookies and --cookies-from-browser, also giving user and pass throws this error:

[debug] Command-line config: ['https://www.instagram.com/stories/xxxxxxxxxxx/xxxxxxxxxxxxxxxxx/', '--username', 'PRIVATE', '--password', 'PRIVATE', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip)
[debug] Python 3.11.4 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: ffmpeg 2022-08-03-git-d3f48e68b3-full_build-www.gyan.dev (setts), ffprobe 2022-08-03-git-d3f48e68b3-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, sqlite3-3.42.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.07, Current version: stable@2023.10.07
yt-dlp is up to date (stable@2023.10.07)
[instagram:story] Downloading login webpage
ERROR: 3208732104181607427: An extractor error has occurred. (caused by KeyError('config')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 712, in extract
    self.initialize()
  File "C:\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 618, in initialize
    self._perform_login(username, password)
  File "C:\Python311\Lib\site-packages\yt_dlp\extractor\instagram.py", line 67, in _perform_login
    'X-CSRFToken': shared_data['config']['csrf_token'],
                   ~~~~~~~~~~~^^^^^^^^^^
KeyError: 'config'

**Comment by Urgentemente** [comment] 2023-10-09 20:50
Same issue here, have been using "--cookies-from-browser firefox" for several years (so much so I've aliased it in my .bashrc), but since the update a few days ago, it's acting as if I'm not logged in, and specifying username & password gives the 'An extractor error has occurred. (caused by KeyError('config'))' error.

**Comment by ryanthomas-org** [comment] 2023-11-03 20:14
Replicated on my end as well:

```
[debug] Command-line config: ['--no-warnings', '--ffmpeg-location', '/home/ryan/scripts/yt-dl-ffmpeg/bin/ffmpeg', '-vU', 'https://www.instagram.com/stories/quod.si.noluerit/3227962093125742161/', '--cookies-from-browser', 'firefox']
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/ryan/.mozilla/firefox/4zr5lql7.default-nightly/cookies.sqlite"
Extracted 1740 cookies from firefox
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-76-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg N-112634-gf2687a3b69-20231101 (setts), ffprobe N-112634-gf2687a3b69-20231101
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2020.06.20, secretstorage-3.3.1, sqlite3-3.37.2
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: be5cfb6be8930e1a5f427533ec32f2a481276b3da7b249d0150ce2b740ccf1ce
yt-dlp is up to date (stable@2023.10.13)
[instagram:story] Extracting URL: https://www.instagram.com/stories/quod.si.noluerit/3227962093125742161/
[instagram:story] 3227962093125742161: Downloading webpage
[instagram:story] 3227962093125742161: Downloading JSON metadata
ERROR: [instagram:story] 3227962093125742161: You need to log in to access this content. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
  File "/home/ryan/scripts/yt-dlp-core/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/home/ryan/scripts/yt-dlp-core/yt_dlp/extractor/instagram.py", line 713, in _real_extract
    self.raise_login_required('You need to log in to access this content')
  File "/home/ryan/scripts/yt-dlp-core/yt_dlp/extractor/common.py", line 1175, in raise_login_required
    raise ExtractorError(msg, expected=True)
```

**Comment by nikmurder** [comment] 2023-11-10 12:49
--cookies-from-browser chrome
same result
stories only
posts/reels r ok

**Comment by arnabs542** [comment] 2023-11-13 12:54
same result
facing this issue in stories only
posts/reels are ok

**Comment by ozelentok** [comment] 2023-11-14 15:13
While debugging this issue I found that the user `id` value that is extracted from the JSON is always null while the `pk` value is populated with a number
After replacing the `id` key with `pk` in the following line I successfully downloaded a story video from Instagram
https://github.com/yt-dlp/yt-dlp/blob/87264d4fdadcddd91289b968dd0e4bf58d449267/yt_dlp/extractor/instagram.py#L706

**Comment by MKRhere** [comment] 2023-12-21 22:36
I'm on the latest master release (`2023.12.21.210644`) and I still have this issue.

```sh
$ yt-dlp --cookies-from-browser firefox <Story URL>
Extracting cookies from firefox
Extracted 753 cookies from firefox
[instagram:story] Extracting URL: https://www.instagram.com/stories/user/3262/
[instagram:story] 3262: Downloading webpage
[instagram:story] 3262: Downloading JSON metadata
ERROR: [instagram:story] 3262: You need to log in to access this content. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
```

If I use `--username --password` instead, I get:

```sh
[instagram:story] Downloading login webpage
ERROR: 3262: An extractor error has occurred. (caused by KeyError('config')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by nikmurder** [comment] 2023-12-21 22:54
same result on all 3 latest branches (-U)
albeit w/ chrome cookies
but otherwise getting the exact same output and then the same error

**Comment by MKRhere** [comment] 2023-12-22 08:58
Makes sense; I hadn't realised @ozelentok's patch wasn't merged yet. Someone could PR the fix if they're sure of it; I'm not sure of the repercussions of this change. Comparing with [gallery-dl](https://github.com/mikf/gallery-dl/blob/master/gallery_dl/extractor/instagram.py) didn't particularly help me figure it out, although gallery-dl does work as expected.

**Closed** 2023-12-24 16:40 UTC
Labels: account-needed, site-bug, patch-available, site:instagram

**Comment by dennisnez** [comment] 2024-01-18 18:34
I'm bumping into this, even with 2023.12.30 ... instagram stories not working with that KeyError config error message, when trying to login (via --username or --netrc) ... can anyone check if this works for them?

**Comment by bashonly** [comment] 2024-01-18 18:35
@dennisnez login/netrc is broken for instagram, use cookies instead

**Comment by 03stevensmi** [comment] 2024-02-05 10:01
Still doesn't work. I'm getting this error message when using cookies:
`yt-dlp --cookies-from-browser brave https://www.instagram.com/stories/highlights/1234/
Extracting cookies from brave
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1009, in main
  File "yt_dlp\__init__.py", line 963, in _real_main
  File "yt_dlp\YoutubeDL.py", line 686, in __init__
  File "yt_dlp\YoutubeDL.py", line 4125, in build_request_director
  File "functools.py", line 967, in __get__
  File "yt_dlp\YoutubeDL.py", line 4048, in cookiejar
  File "yt_dlp\cookies.py", line 94, in load_cookies
  File "yt_dlp\cookies.py", line 115, in extract_cookies_from_browser
  File "yt_dlp\cookies.py", line 286, in _extract_chrome_cookies
FileNotFoundError: could not find brave cookies database in "C:\Users\xxx\AppData\Local\BraveSoftware\Brave-Browser\User Data"
[6584] Failed to execute script '__main__' due to unhandled exception!`

**Comment by dennisnez** [comment] 2024-02-05 14:36
That's a different problem, it's not able to find your cookies file. One workaround before that gets fixed is to try to export your cookies into the ol' netscape text format, and then refer to it with --cookies FILE.

**Comment by 03stevensmi** [comment] 2024-02-07 10:45
> That's a different problem, it's not able to find your cookies file. One workaround before that gets fixed is to try to export your cookies into the ol' netscape text format, and then refer to it with --cookies FILE.

@dennisnez Sorry for the late reply.
I can confirm using cookies with file works great!
Thanks. :)

**Comment by alzaji** [comment] 2024-03-21 20:54
As of nightly@2024.03.20.232704 this has happened once again with a raise_login_required exception in common.py when the cookie is present in the browser.

Basically gets to the stage of downloading the JSON metadata but after that it'll raise the exception, maybe instagram changed something in their data model once again...

**Comment by bashonly** [comment] 2024-03-21 21:32
@alzaji please open a new issue with a full verbose log

**Comment by alzaji** [comment] 2024-03-21 21:45
@bashonly will do, give me a few minutes

**Comment by kode-trek** [comment] 2024-07-13 07:46
~$ yt-dlp -U
Latest version: stable@2024.07.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.09 from yt-dlp/yt-dlp)

~$ yt-dlp "IG-LINK" --cookies-from-browser firefox --username "USERNAME" --password "PASSWORD"
