### ISSUE TITLE
Xvideos.com Site Videos Fail to Download - Probably Site Specific Issue

### ISSUE THREAD

**Issue by richardstevenhack** [yt-dlp/yt-dlp#1811] opened 2021-11-27 10:35 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

yt-dlp fails to download any video from the Xvideos.com site, effective 2021-11-27, despite having worked perfectly well yesterday on the same site. It continues to work perfectly well on Youtube, so appears to be site specific. Tested with around eight different videos on the Xvideos site.  Example shown below. Xvideos site has probably changed something.

### Verbose log

```shell
rhack@localhost:/Data2/Work> yt-dlp -Uv https://www.xvideos.com/video4304999/133._swingers_club_cd2
[debug] Command-line config: ['-Uv', 'https://www.xvideos.com/video4304999/133._swingers_club_cd2']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1 (zip)
[debug] Python version 3.6.13 (CPython 64bit) - Linux-5.3.18-59.34-preempt-x86_64-with-glibc2.3.4
[debug] exe versions: ffmpeg 3.4.9, ffprobe 3.4.9
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [XVideos] Extracting URL: https://www.xvideos.com/video4304999/133._swingers_club_cd2
[XVideos] 4304999: Downloading webpage
ERROR: [XVideos] 4304999: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 713, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3295, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by MinePlayersPE** [comment] 2021-11-27 10:37
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1788, fixed in https://github.com/yt-dlp/yt-dlp/pull/1799

**Closed** 2021-11-27 10:38 UTC
Labels: extractor-bug, triage
