### ISSUE TITLE
Wayback Machine automatic fall back option

### ISSUE THREAD

**Issue by adamsatyr** [yt-dlp/yt-dlp#8147] opened 2023-09-18 14:25 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I have a batch file with youtube videos (may be also useful for other sites) and some of the videos are already deleted for youtube.

For now I just created links to wayback machine and put them at the end of the batch file as naive solution.

What I would like to have is an option to automatically fall back to wayback machine if original video is not available. 

```
https://www.youtube.com/watch?v=dQw4w9WgXcQ
https://web.archive.org/web/20230000000000*/https://www.youtube.com/watch?v=dQw4w9WgXcQ
```

I don't know how to demonstrate that with verbose command.

Update: to not overwhelm and wait for wayback machine, I found alternative solution: 
using log file (--download-archive) and replacing "youtube" with "youtubewebarchive".
That should skip all already downloaded files. To be tested.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by MrRawes** [comment] 2023-09-18 16:47
duplicate of https://github.com/yt-dlp/yt-dlp/issues/3342

**Closed** 2023-09-18 16:50 UTC
Labels: duplicate, site-enhancement
