### ISSUE TITLE
YouTube: include "✨ Most replayed" graph

### ISSUE THREAD

**Issue by oddwizard** [yt-dlp/yt-dlp#3987] opened 2022-06-06 12:54 UTC
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://youtu.be/jNQXAC9IVRw

### Description

There's a new feature above YT's progress bar:

> ### Go to the most replayed parts of a video
> The graph above the progress bar lets you see which parts of a video are most frequently re-watched. 
>
> When you start seeking, you’ll see a graph above the red progress bar. If the graph is high, then that part of the video has been replayed often. 
> 
> – [YouTube Help](https://support.google.com/youtube/answer/7174115)

![youtube-most-replayed-video-1920x1131](https://user-images.githubusercontent.com/10303006/172162731-6c79aef6-1242-491e-b550-43729e69d94c.jpg)

It seems to be this metadata is currently not included (`.info.json`) in the latest release of `yt-dlp`. Is there something planned for the coming releases?

**Comment by MrRawes** [comment] 2022-06-06 13:16
duplicate of https://github.com/yt-dlp/yt-dlp/issues/3888

**Closed** 2022-06-06 13:33 UTC
Labels: site-enhancement, triage
