### ISSUE TITLE
Douyin no longer works

### ISSUE THREAD

**Issue by wranai** [yt-dlp/yt-dlp#8090] opened 2023-09-12 05:18 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Douyin downloader returns `ERROR: 'NoneType' object is not subscriptable` 

This is the result of the `awmeme` key being set to `none` in the JSON encoded within `RENDER_DATA` since 1-2 days ago due to what looks like an update of Douyin's private API (they changed their live API too just a couple days prior to this).

There is a new API endpoint that returns the same data (though in a different structure) here: https://www.douyin.com/aweme/v1/web/aweme/detail/ -- this requires signatures which I'm not sure how to generate.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.douyin.com/video/72770389341xxxxxxxx']
[debug] User config "/home/self/.config/yt-dlp/config": ['--ignore-errors', '--prefer-ffmpeg', '--ffmpeg-location', '/usr/bin/ffmpeg', '--cookies', 'youtube-cookies.txt', '--write-sub', '--write-description', '--write-info-json', '--write-annotations', '--write-thumbnail', '--sub-langs', 'all,-live_chat', '--convert-subtitles', 'ass', '--embed-subs', '--add-metadata', '--xattrs', '--embed-thumbnail', '--fragment-retries', '100', '--retries', '100', '--no-mark-watched', '--live-from-start', '--video-multistreams', '--audio-multistreams', '--remux-video', 'aac>m4a/mov>mp4/mkv', '--no-check-certificates']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.09.11.145352 [66cc64ff6] (zip)
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux-6.2.0-20-generic-x86_64-with-glibc2.37 (OpenSSL 3.1.2 1 Aug 2023, glibc 2.37)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, phantomjs 07, rtmpdump 2.4
[debug] Optional libraries: certifi-2023.07.22, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1865 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.09.11.145352, Current version: nightly@2023.09.11.145352
Current Build Hash: 1684787329a8a8328064b63b024c4f496a3ea0f6a1e86ed85463df27f17ed412
yt-dlp is up to date (nightly@2023.09.11.145352)
[Douyin] Extracting URL: https://www.douyin.com/video/72770389341xxxxxxxx
[Douyin] 72770389341xxxxxxxx: Downloading video feed
[Douyin] 72770389341xxxxxxxx: Unable to find video in feed; trying with webpage
[Douyin] 72770389341xxxxxxxx: Downloading webpage
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/self/Scripts/yt-dlp/yt_dlp/YoutubeDL.py", line 1575, in wrapper
    return func(self, *args, **kwargs)
  File "/home/self/Scripts/yt-dlp/yt_dlp/YoutubeDL.py", line 1710, in __extract_info
    ie_result = ie.extract(url)
  File "/home/self/Scripts/yt-dlp/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/home/self/Scripts/yt-dlp/yt_dlp/extractor/tiktok.py", line 1055, in _real_extract
    return self._parse_aweme_video_web(get_first(render_data, ('aweme', 'detail')), url, video_id)
  File "/home/self/Scripts/yt-dlp/yt_dlp/extractor/tiktok.py", line 354, in _parse_aweme_video_web
    video_info = aweme_detail['video']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by bashonly** [comment] 2023-09-12 05:22
Duplicate of #7854

**Closed by bashonly** 2023-09-12 05:22 UTC
Labels: duplicate, site-bug, site:tiktok
