### ISSUE TITLE
Teachable - "Unable to find video URL"

### ISSUE THREAD

**Issue by jasonlitka** [yt-dlp/yt-dlp#5645] opened 2022-11-26 02:39 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I just bought a subscription to some training classes which are hosted on Teachable and I'm having issues downloading them.

I found #5638 and am prefixing the URL with "teachable:" but that leads to a new error, "Unable to find video URL".  This occurs both with the Windows .exe and with master running in python 3.11.

It correctly identifies that there are 11 items in the playlist, but can't find any of the videos.

Video Playlist Name and URLs are sanitized, but happy to provide a unsanitized copy and credentials via PM.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Z:\Downloads>python -m yt_dlp --cookies domain.com_cookies.txt -vU teachable:https://training.domain.com/courses/enrolled/1335658
[debug] Command-line config: ['--cookies', 'domain.com_cookies.txt', '-vU', 'teachable:https://training.domain.com/courses/enrolled/1335658']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1727 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [TeachableCourse] Extracting URL: teachable:https://training.domain.com/courses/enrolled/1335658
[TeachableCourse] 1335658: Downloading webpage
[download] Downloading playlist: MyPlaylistName
[TeachableCourse] Playlist MyPlaylistName: Downloading 11 items of 11
[download] Downloading item 1 of 11
[debug] [Teachable] Extracting URL: teachable:https://training.domain.com/courses/1335658/lectures/30650749
[Teachable] 30650749: Downloading webpage
ERROR: [Teachable] 30650749: Unable to find video URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 678, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\teachable.py", line 173, in _real_extract
    raise ExtractorError('Unable to find video URL')

[download] Downloading item 2 of 11
[debug] [Teachable] Extracting URL: teachable:https://training.domain.com/courses/1335658/lectures/41526504
[Teachable] 41526504: Downloading webpage
ERROR: [Teachable] 41526504: Unable to find video URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 678, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\teachable.py", line 173, in _real_extract
    raise ExtractorError('Unable to find video URL')

[download] Downloading item 3 of 11
[debug] [Teachable] Extracting URL: teachable:https://training.domain.com/courses/1335658/lectures/30673316
[Teachable] 30673316: Downloading webpage
ERROR: [Teachable] 30673316: Unable to find video URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 678, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\teachable.py", line 173, in _real_extract
    raise ExtractorError('Unable to find video URL')

[download] Downloading item 4 of 11
[debug] [Teachable] Extracting URL: teachable:https://training.domain.com/courses/1335658/lectures/30673486
[Teachable] 30673486: Downloading webpage
ERROR: [Teachable] 30673486: Unable to find video URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 678, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\teachable.py", line 173, in _real_extract
    raise ExtractorError('Unable to find video URL')

[download] Downloading item 5 of 11
[debug] [Teachable] Extracting URL: teachable:https://training.domain.com/courses/1335658/lectures/30673559
[Teachable] 30673559: Downloading webpage
ERROR: [Teachable] 30673559: Unable to find video URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 678, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\teachable.py", line 173, in _real_extract
    raise ExtractorError('Unable to find video URL')

[download] Downloading item 6 of 11
[debug] [Teachable] Extracting URL: teachable:https://training.domain.com/courses/1335658/lectures/30673639
[Teachable] 30673639: Downloading webpage
ERROR: [Teachable] 30673639: Unable to find video URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 678, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\teachable.py", line 173, in _real_extract
    raise ExtractorError('Unable to find video URL')

[download] Downloading item 7 of 11
[debug] [Teachable] Extracting URL: teachable:https://training.domain.com/courses/1335658/lectures/30673675
[Teachable] 30673675: Downloading webpage
ERROR: [Teachable] 30673675: Unable to find video URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 678, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\teachable.py", line 173, in _real_extract
    raise ExtractorError('Unable to find video URL')

[download] Downloading item 8 of 11
[debug] [Teachable] Extracting URL: teachable:https://training.domain.com/courses/1335658/lectures/30673869
[Teachable] 30673869: Downloading webpage
ERROR: [Teachable] 30673869: Unable to find video URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 678, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\teachable.py", line 173, in _real_extract
    raise ExtractorError('Unable to find video URL')

[download] Downloading item 9 of 11
[debug] [Teachable] Extracting URL: teachable:https://training.domain.com/courses/1335658/lectures/30673876
[Teachable] 30673876: Downloading webpage
ERROR: [Teachable] 30673876: Unable to find video URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 678, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\teachable.py", line 173, in _real_extract
    raise ExtractorError('Unable to find video URL')

[download] Downloading item 10 of 11
[debug] [Teachable] Extracting URL: teachable:https://training.domain.com/courses/1335658/lectures/30673881
[Teachable] 30673881: Downloading webpage
ERROR: [Teachable] 30673881: Unable to find video URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 678, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\teachable.py", line 173, in _real_extract
    raise ExtractorError('Unable to find video URL')

[download] Downloading item 11 of 11
[debug] [Teachable] Extracting URL: teachable:https://training.domain.com/courses/1335658/lectures/30673904
[Teachable] 30673904: Downloading webpage
ERROR: [Teachable] 30673904: Unable to find video URL; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 678, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jason.litka\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\teachable.py", line 173, in _real_extract
    raise ExtractorError('Unable to find video URL')

[download] Finished downloading playlist: MyPlaylistName
```

**Comment by pukkandan** [comment] 2022-11-26 02:43
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3564

**Closed by pukkandan** 2022-11-26 02:43 UTC
Labels: site-bug, triage
