### ISSUE TITLE
duplicate subtitle while converting vtt subtitle to srt which the vtt subtitle is auto-translated

### ISSUE THREAD

**Issue by liym** [yt-dlp/yt-dlp#3589] opened 2022-04-29 03:06 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

after downloaded the youtube video with only auto-generated subtitles, the post-processor converted the vtt subtitle into srt subtitle succesfully but with improper content.  the srt subtitle have duplicated sentences which is very confusing when watching video with the srt subtitle.  please see the screenshot below and find more as the Archive.zip 

<img width="316" alt="image" src="https://user-images.githubusercontent.com/4084561/165879250-2842f1fc-c349-4a56-a295-3440ca785ab5.png">
[Archive.zip](https://github.com/yt-dlp/yt-dlp/files/8587839/Archive.zip)

### Verbose log

```shell
appledeMacBook-Pro:t apple$ yt-dlp https://www.youtube.com/watch?v=MfGNLVS5-RE -vU -k
[debug] Command-line config: ['https://www.youtube.com/watch?v=MfGNLVS5-RE', '-vU', '-k']
[debug] Home config "yt-dlp.conf": ['--output', '//Users/apple/t/%(uploader)s/%(title)s-%(resolution)s.%(ext)s', '--console-title', '--progress-template', 'download-title:%(info.id)s-%(progress.eta)s', '--merge-output-format', 'mp4', '--sub-langs', 'zh-Hans', '--write-auto-subs', '--convert-subs', 'srt', '--embed-thumbnail', '--embed-metadata']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.10 (CPython 64bit) - macOS-12.3-x86_64-i386-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=MfGNLVS5-RE
[youtube] MfGNLVS5-RE: Downloading webpage
[youtube] MfGNLVS5-RE: Downloading android player API JSON
[debug] Loading youtube-nsig.fe8185e7 from cache
[debug] [youtube] Decrypted nsig jsvJWDITcvfIZU5o8 => eVUJDR5ldPDe7Q
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: zh-Hans
[debug] Default format spec: bestvideo*+bestaudio/best
[info] MfGNLVS5-RE: Downloading 1 format(s): 303+251
[info] Writing video subtitles to: //Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.zh-Hans.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=MfGNLVS5-RE&caps=asr&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1651226072&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=5CCDB8E4A5DBA39718CEBBF106082CFD39A8E058.C4293B498F8739F55519E2EE0C04333C315CD3E9&key=yt8&kind=asr&lang=en&tlang=zh-Hans&fmt=vtt"
[download] Destination: //Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.zh-Hans.vtt
[download] 100% of 22.30KiB in 00:00
[info] Downloading video thumbnail 41 ...
WARNING: Unable to download video thumbnail 41: HTTP Error 404: Not Found
[info] Downloading video thumbnail 40 ...
WARNING: Unable to download video thumbnail 40: HTTP Error 404: Not Found
[info] Downloading video thumbnail 39 ...
WARNING: Unable to download video thumbnail 39: HTTP Error 404: Not Found
[info] Downloading video thumbnail 38 ...
WARNING: Unable to download video thumbnail 38: HTTP Error 404: Not Found
[info] Downloading video thumbnail 37 ...
[info] Writing video thumbnail 37 to: //Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.webp
[SubtitlesConvertor] Converting subtitles
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file://Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.zh-Hans.vtt' -f srt -movflags +faststart 'file://Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.zh-Hans.srt'
[debug] Invoking downloader on "https://rr5---sn-npoldn7e.googlevideo.com/videoplayback?expire=1651222473&ei=aVNrYs_nE8ynwgObh57IDQ&ip=139.180.190.169&id=o-AAJwxP8T1cFvEPrHXpzTyD2buQMUhCD_0VUKnusf5Wvc&itag=303&source=youtube&requiressl=yes&mh=Ce&mm=31%2C26&mn=sn-npoldn7e%2Csn-oguelney&ms=au%2Conr&mv=m&mvi=5&pl=21&initcwndbps=613750&vprv=1&mime=video%2Fwebm&gir=yes&clen=260164413&dur=364.113&lmt=1651178632488776&mt=1651200564&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgUMVsr0fYQdEZh-pGeM1xdL13MLMPF3KVkzmFt9-7QO0CIQC-d18j_IXbdOwnZYLZtnaZWJijC9ASm65Zeg-I8kaLxw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgYK2IC0RZUcNrqETn2LXkgccpdf6ver7p87c5z2XsKkoCIQCiTP0VcBbpaCPIzpF0XTqlXCtBpe8oBNMBA_N-Py87gw%3D%3D"
[download] Destination: //Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.f303.webm
[download] 100% of 248.11MiB in 01:11
[debug] Invoking downloader on "https://rr5---sn-npoldn7e.googlevideo.com/videoplayback?expire=1651222473&ei=aVNrYs_nE8ynwgObh57IDQ&ip=139.180.190.169&id=o-AAJwxP8T1cFvEPrHXpzTyD2buQMUhCD_0VUKnusf5Wvc&itag=251&source=youtube&requiressl=yes&mh=Ce&mm=31%2C26&mn=sn-npoldn7e%2Csn-oguelney&ms=au%2Conr&mv=m&mvi=5&pl=21&initcwndbps=613750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=6070590&dur=364.141&lmt=1651178690673095&mt=1651200564&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALTNc5UW1J2puxv9D5JK0KMSoEhaNe8l_biLR7Nw3kJdAiEA2R6g1wwwH7-DpEnnM2tHzs-doUV6Wv7ectPMmA5KJoY%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgYK2IC0RZUcNrqETn2LXkgccpdf6ver7p87c5z2XsKkoCIQCiTP0VcBbpaCPIzpF0XTqlXCtBpe8oBNMBA_N-Py87gw%3D%3D"
[download] Destination: //Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.f251.webm
[download] 100% of 5.79MiB in 00:02
[Merger] Merging formats into "//Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file://Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.f303.webm' -i 'file://Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file://Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.temp.mp4'
[Metadata] Adding metadata to "//Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file://Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.mp4' -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata 'title=I Am Weird - Solo Practice Session' -metadata date=20220428 -metadata 'description=If you'"'"'d like to support my channel, you can purchase your parts, gear, and supplies through my Rocky Mountain ATV/MC link! Anything at all that you purchase through this link (doesn'"'"'t have to be my favourites), helps support me. Thank you!

https://www.rockymountainatvmc.com/Sales/3329/Megs-Top-Picks?ref=1048&utm_source=youtube&utm_medium=megsbraap&utm_campaign=influencer

When I go for a solo ride that isn'"'"'t focused around stamina training, this is often what I get up to.  Just practicing my technical skills by focusing on obstacles or sections of trail that are difficult.' -metadata 'synopsis=If you'"'"'d like to support my channel, you can purchase your parts, gear, and supplies through my Rocky Mountain ATV/MC link! Anything at all that you purchase through this link (doesn'"'"'t have to be my favourites), helps support me. Thank you!

https://www.rockymountainatvmc.com/Sales/3329/Megs-Top-Picks?ref=1048&utm_source=youtube&utm_medium=megsbraap&utm_campaign=influencer

When I go for a solo ride that isn'"'"'t focused around stamina training, this is often what I get up to.  Just practicing my technical skills by focusing on obstacles or sections of trail that are difficult.' -metadata 'purl=https://www.youtube.com/watch?v=MfGNLVS5-RE' -metadata 'comment=https://www.youtube.com/watch?v=MfGNLVS5-RE' -metadata 'artist=Megs Braap' -movflags +faststart 'file://Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.temp.mp4'
[ThumbnailsConvertor] Converting thumbnail "//Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file://Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.webp' -movflags +faststart 'file://Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.png'
[EmbedThumbnail] mutagen: Adding thumbnail to "//Users/apple/t/Megs Braap/I Am Weird - Solo Practice Session-1920x1080.mp4"
```

**Comment by pukkandan** [comment] 2022-04-29 13:54
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1734

**Closed by pukkandan** 2022-04-29 13:54 UTC
Labels: bug, triage
