### ISSUE TITLE
Unable to extract info section

### ISSUE THREAD

**Issue by mrzenwiz** [yt-dlp/yt-dlp#5418] opened 2022-10-31 17:09 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

I was trying to download a video from vimeo. This has usually worked before. This is the second URL that fails this way.

I got the following error message. I expect it to download without a hitch.

yt-dlp https://player.vimeo.com/video/638145104?h=17ba014eec&badge=0&autopause=0&player_id=0&app_id=58479
[vimeo] 638145104: Downloading webpage
ERROR: [vimeo] 638145104: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Trying again: yt-dlp -t https://player.vimeo.com/video/638145104?h=17ba014eec&badge=0&autopause=0&player_id=0&app_id=58479
[vimeo] 638145104: Downloading webpage
ERROR: [vimeo] 638145104: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Try again with '/home/admar/bin/yt-dlp -u <userid> -p <pswd> -t url'

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU 'https://player.vimeo.com/video/638145104?h=17ba014eec&badge=0&autopause=0&player_id=0&app_id=58479'
[debug] Command-line config: ['-vU', 'https://player.vimeo.com/video/638145104?h=17ba014eec&badge=0&autopause=0&player_id=0&app_id=58479']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (zip)
[debug] Python 3.10.6 (CPython 64bit) - Linux-5.15.0-52-generic-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/638145104?h=17ba014eec&badge=0&autopause=0&player_id=0&app_id=58479
[vimeo] 638145104: Downloading webpage
ERROR: [vimeo] 638145104: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/admar/bin/yt-dlp/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/home/admar/bin/yt-dlp/yt_dlp/extractor/vimeo.py", line 872, in _real_extract
    config = self._parse_json(self._search_regex(
  File "/home/admar/bin/yt-dlp/yt_dlp/extractor/common.py", line 1224, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment] 2022-10-31 17:12
duplicate of #5361

will be fixed in next release

**Closed by bashonly** 2022-10-31 17:12 UTC
Labels: site-bug, triage

**Comment by mrzenwiz** [comment] 2022-11-05 00:33
Pardon my asking, but when is the next release?
