### ISSUE TITLE
[zoom] Password starting with "^" character not accepted

### ISSUE THREAD

**Issue by danyl420** [yt-dlp/yt-dlp#5765] opened 2022-12-10 21:35 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Possible python is not accepting password starting with ^ symbol correctly, as it is an operator in python programming language

yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" **https://fsf-vu-lt.zoom.us/rec/share/M_ZWj2OsRDTfnI7flbQQAxWgGA4abDaGqCRK0hBfVfVoGJsedgzu0dH4AIy04dOr.zq2O2wsIo4JWrX3t --video-password ^G03R#6a**

Trying to run this command password is not accepted, even though it's accepted accessing this recording manually through a browser

Previously tried to use zoom-dl, using a very similar command it gave me an error something on the lines of "Password "G03R#6a" is not correct" Completely omitting the first character "^"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', 'https://fsf-vu-lt.zoom.us/rec/share/M_ZWj2OsRDTfnI7flbQQAxWgGA4abDaGqCRK0hBfVfVoGJsedgzu0dH4AIy04dOr.zq2O2wsIo4JWrX3t', '--video-password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-01-03-git-68d0a7e446-essentials_build-www.gyan.dev (setts), ffprobe 2022-01-03-git-68d0a7e446-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [zoom] Extracting URL: https://fsf-vu-lt.zoom.us/rec/share/M_ZWj2OsRDTfnI7flbQQAxWgGA4abDaGqCRK0hBfVfVoGJsedgzu0dH4AIy04dOr.zq2O2wsIo4JWrX3t
[zoom] M_ZWj2OsRDTfnI7flbQQAxWgGA4abDaGqCRK0hBfVfVoGJsedgzu0dH4AIy04dOr.zq2O2wsIo4JWrX3t: Downloading webpage
[zoom] M_ZWj2OsRDTfnI7flbQQAxWgGA4abDaGqCRK0hBfVfVoGJsedgzu0dH4AIy04dOr.zq2O2wsIo4JWrX3t: Validating passcode
ERROR: [zoom] M_ZWj2OsRDTfnI7flbQQAxWgGA4abDaGqCRK0hBfVfVoGJsedgzu0dH4AIy04dOr.zq2O2wsIo4JWrX3t: Wrong passcode: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\zoom.py", line 41, in _real_extract
  File "yt_dlp\extractor\common.py", line 1034, in download_content
  File "yt_dlp\extractor\common.py", line 998, in download_handle
  File "yt_dlp\extractor\common.py", line 868, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 825, in _request_webpage

  File "yt_dlp\extractor\common.py", line 807, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3692, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by bashonly** [comment] 2022-12-10 22:14
With `--print-traffic` you can see the full password is being sent correctly (url-encoded):
```
send: b'id=eiNTbUup_mV6q-3sYVuIT4KZl1cBowbWlxJYEOR2Acvghc-qi4Rbu-Ta7iT4Z0X7.teaSBN42ode-mBr7&passwd=%5EG03R%236a&action=viewdetailpage'
reply: 'HTTP/1.1 401 Unauthorized\r\n'
```

Browser dev tools show that the extractor sending a POST request to the correct endpoint. The browser also adds an empty `recaptcha=`param to the POST data, but the data is otherwise correctly formatted.

The browser sends a referer header with the password included as a query param:
```
    "referrer": "https://fsf-vu-lt.zoom.us/rec/share/CdpMt1UpzcwaIJjXru_iXWfA2fXz4yxs9cuJBAJ86rwZb7Rg_b6SFsVFDZNaYt7W.MP146CnL-9yfmF2I?password=%5EG03R%236a",
 ```
I've tried adding this and the empty `recaptcha` POST data param to the extractor and still get a 401 response. 
 
There are also a whole lot of dynamically generated headers that the extractor does not include, but not sure if they are necessary or relevant. Possibly of note is the `ZOOM-CSRFTOKEN` header.

Unfortunately, the extractor doesn't have any working tests. Does anyone have any working example URLs (password-protected or otherwise) to share?

**Comment by flashdagger** [comment] 2022-12-10 23:19
@danyl420 Since you are on Windows, did you consider that caret is an escape character in cmd.exe or are you using Powershell?
``` cmd
$ echo ^G03R#6a
G03R#6a

$ echo ^^G03R#6a
^G03R#6a

```

**Comment by pukkandan** [comment] 2022-12-11 03:39
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2299

**Closed by pukkandan** 2022-12-11 03:39 UTC
Labels: site-bug
