### ISSUE TITLE
virustotal 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa

### ISSUE THREAD

**Issue by MagnoAlberto** [yt-dlp/yt-dlp#8148] opened 2023-09-18 19:15 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

https://www.virustotal.com/gui/file/5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb352aa
possible false true W32.AIDetectMalware.64

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment] 2023-09-18 19:17
The source is open and it gets automatically bundled using pyinstaller. You can check for yourself using the action that everything went as expected. No need to worry.

**Comment by bashonly** [comment] 2023-09-18 19:19
Duplicate of #25 -- read for explanation/discussion

**Closed by bashonly** 2023-09-18 19:19 UTC
Labels: question
