### ISSUE TITLE
Can't download any content from youtube. Error: The handshake operation timed out.

### ISSUE THREAD

**Issue by empireFugee** [yt-dlp/yt-dlp#8233] opened 2023-09-29 11:26 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

I have not been able to download any videos from youtube. The videos can be played on browsers.
I've tried adding ` --cookies-from-browser chromium' with same result 

- OS: Arch linux
- linux version: 6.5.4-zen2-1-zen
- installation method: pacman

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
❯ yt-dlp -vU 'https://www.youtube.com/watch?v=xE1A6T1cycU'
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=xE1A6T1cycU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956]
[debug] Python 3.11.5 (CPython x86_64 64bit) - Linux-6.5.4-zen2-1-zen-x86_64-with-glibc2.38 (OpenSSL 3.1.3 19 Sep 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.43.1, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
yt-dlp is up to date (stable@2023.09.24)
[youtube] Extracting URL: https://www.youtube.com/watch?v=xE1A6T1cycU
[youtube] xE1A6T1cycU: Downloading webpage
[youtube] xE1A6T1cycU: Downloading ios player API JSON
[youtube] xE1A6T1cycU: Downloading android player API JSON
[youtube] xE1A6T1cycU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] xE1A6T1cycU: Downloading 1 format(s): 313+251
[debug] Invoking http downloader on "https://rr1---sn-u5u5n3tpo-cagl.googlevideo.com/videoplayback?expire=1696006362&ei=eqwWZc_zLrqL9fwPvZ6rmAY&ip=2402%3Ae280%3A210b%3A1b9%3Ad1f3%3A45cd%3A3be8%3Aeb37&id=o-AKCIDjxZxB0AU4yX4k4Nvh0BxdYa-rkad0U-CELfsvh6&itag=313&source=youtube&requiressl=yes&mh=kH&mm=31%2C29&mn=sn-u5u5n3tpo-cagl%2Csn-h5576nsl&ms=au%2Crdu&mv=m&mvi=1&pl=48&initcwndbps=1366250&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=1467717256&dur=1457.989&lmt=1695683471126771&mt=1695983867&fvip=1&keepalive=yes&fexp=24007246&beids=24350017&c=IOS&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJofoi_UEl6fEBkLfIRMMBiDqBeF71kcttxuNneM5tdSAiEA3CxGILHLYrMaqrAK468isxYTdx9Iq5dB7lsBwpHk0tA%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKYrtZ-7DvWBXhZ5yo0JfhmKhlUFU7QMUuDUHU4cxdEwAiEAzF0KRTZG3nXhzxzwsIFxULR8Z4tF3wvFnONYTrFSbBA%3D"
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (1/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (2/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (3/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (4/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (5/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (6/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (7/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (8/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (9/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (10/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Giving up after 10 retries
  File "/usr/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.11/site-packages/yt_dlp/__init__.py", line 1008, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/lib/python3.11/site-packages/yt_dlp/__init__.py", line 998, in _real_main
    return ydl.download(all_urls)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3510, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3485, in wrapper
    res = func(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1556, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2921, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3369, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3108, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/http.py", line 362, in real_download
    for retry in RetryManager(self.params.get('retries'), self.report_retry):
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 5112, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 401, in report_retry
    RetryManager.report_retry(
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 5119, in report_retry
    return error(f'{e}. Giving up after {count - 1} retries') if count > 1 else error(str(e))
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 404, in <lambda>
    error=IDENTITY if not fatal else lambda e: self.report_error(f'\r[download] Got error: {e}'),
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1045, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 973, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())


[debug] Invoking http downloader on "https://rr1---sn-u5u5n3tpo-cagl.googlevideo.com/videoplayback?expire=1696006363&ei=e6wWZf_FBo-09fwPl6-OuAY&ip=2402%3Ae280%3A210b%3A1b9%3Ad1f3%3A45cd%3A3be8%3Aeb37&id=o-APmC2m7exbRuAxMEqkgm18Hsz5B3A3b28esDqPXvG5cu&itag=251&source=youtube&requiressl=yes&mh=kH&mm=31%2C29&mn=sn-u5u5n3tpo-cagl%2Csn-h5576nsl&ms=au%2Crdu&mv=m&mvi=1&pl=48&initcwndbps=1366250&spc=UWF9f04qf2abqpo71cUQOwZjD9ZKqd0&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=22982464&dur=1458.021&lmt=1695672534158006&mt=1695983867&fvip=1&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAKxwDgfrr1LCXEZHZ6ps6RUQFkgCJcPWmfTX3r-bCOYIAiB8Bge3H8NMzNgj_8GRn9uU05mYN0CZfSb60gdFlVfweQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgY40fMT7FC--b8u5ZOMGGp_xsCbxO-bQQqISVJCxwmbgCIB6NxjsKQH4VuexAjQskq-b2ilC27EJhmyrV84gn2QNc"
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (1/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (2/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (3/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (4/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (5/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (6/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (7/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (8/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (9/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Retrying (10/10)...
[download] Got error: _ssl.c:989: The handshake operation timed out. Giving up after 10 retries
  File "/usr/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.11/site-packages/yt_dlp/__init__.py", line 1008, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/lib/python3.11/site-packages/yt_dlp/__init__.py", line 998, in _real_main
    return ydl.download(all_urls)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3510, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3485, in wrapper
    res = func(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1556, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2921, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3369, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3108, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/http.py", line 362, in real_download
    for retry in RetryManager(self.params.get('retries'), self.report_retry):
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 5112, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 401, in report_retry
    RetryManager.report_retry(
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 5119, in report_retry
    return error(f'{e}. Giving up after {count - 1} retries') if count > 1 else error(str(e))
  File "/usr/lib/python3.11/site-packages/yt_dlp/downloader/common.py", line 404, in <lambda>
    error=IDENTITY if not fatal else lambda e: self.report_error(f'\r[download] Got error: {e}'),
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1045, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 973, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

**Comment by dirkf** [comment] 2023-09-29 11:45
What happens if you select other formats?

What happens if you use an external downloader (eg _ffmpeg_)?

**Comment by RAiZ0K** [comment] 2023-09-29 12:11
> What happens if you select other formats?
> 
> What happens if you use an external downloader (eg _ffmpeg_)?

why do i use another format its a video link!

**Comment by bashonly** [comment] 2023-09-29 13:06
maybe try adding `-4` to your command

**Comment by EmpireFugee** [comment] 2023-09-29 13:17
different format didn't work but mobile hotspot did the trick!
If my IP is blocked, it still doesn't explain how I can play videos on browser.

**Comment by EmpireFugee** [comment] 2023-09-29 13:31
spotdl also works on mobile hotspot which wasn't working on wifi
(adding -4 or -6 didn't work)

**Comment by dirkf** [comment] 2023-09-29 13:59
YT can make the browser perform some trick to show that it is one, whereas yt-dlp (etc) may not respond, or be able to, to the trick request. See also #8227.

**Comment by gamer191** [comment] 2023-09-29 14:01
Can I get you to run the following commands:
```
yt-dlp --simulate "https://rr1---sn-u5u5n3tpo-cagl.googlevideo.com/videoplayback?expire=1696006362&ei=eqwWZc_zLrqL9fwPvZ6rmAY&ip=2402%3Ae280%3A210b%3A1b9%3Ad1f3%3A45cd%3A3be8%3Aeb37&id=o-AKCIDjxZxB0AU4yX4k4Nvh0BxdYa-rkad0U-CELfsvh6&itag=313&source=youtube&requiressl=yes&mh=kH&mm=31%2C29&mn=sn-u5u5n3tpo-cagl%2Csn-h5576nsl&ms=au%2Crdu&mv=m&mvi=1&pl=48&initcwndbps=1366250&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=1467717256&dur=1457.989&lmt=1695683471126771&mt=1695983867&fvip=1&keepalive=yes&fexp=24007246&beids=24350017&c=IOS&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJofoi_UEl6fEBkLfIRMMBiDqBeF71kcttxuNneM5tdSAiEA3CxGILHLYrMaqrAK468isxYTdx9Iq5dB7lsBwpHk0tA%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKYrtZ-7DvWBXhZ5yo0JfhmKhlUFU7QMUuDUHU4cxdEwAiEAzF0KRTZG3nXhzxzwsIFxULR8Z4tF3wvFnONYTrFSbBA%3D"
yt-dlp --simulate "https://rr1---sn-h5576nsl.googlevideo.com/videoplayback?expire=1696006362&ei=eqwWZc_zLrqL9fwPvZ6rmAY&ip=2402%3Ae280%3A210b%3A1b9%3Ad1f3%3A45cd%3A3be8%3Aeb37&id=o-AKCIDjxZxB0AU4yX4k4Nvh0BxdYa-rkad0U-CELfsvh6&itag=313&source=youtube&requiressl=yes&mh=kH&mm=31%2C29&mn=sn-u5u5n3tpo-cagl%2Csn-h5576nsl&ms=au%2Crdu&mv=m&mvi=1&pl=48&initcwndbps=1366250&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=1467717256&dur=1457.989&lmt=1695683471126771&mt=1695983867&fvip=1&keepalive=yes&fexp=24007246&beids=24350017&c=IOS&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJofoi_UEl6fEBkLfIRMMBiDqBeF71kcttxuNneM5tdSAiEA3CxGILHLYrMaqrAK468isxYTdx9Iq5dB7lsBwpHk0tA%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKYrtZ-7DvWBXhZ5yo0JfhmKhlUFU7QMUuDUHU4cxdEwAiEAzF0KRTZG3nXhzxzwsIFxULR8Z4tF3wvFnONYTrFSbBA%3D"
```


I suspect the first one will fail and the second will succeed, in which case this is a duplicate of #1986

**Comment by EmpireFugee** [comment] 2023-09-29 14:16
`❯ yt-dlp --simulate "https://rr1---sn-u5u5n3tpo-cagl.googlevideo.com/videoplayback?expire=1696006362&ei=eqwWZc_zLrqL9fwPvZ6rmAY&ip=2402%3Ae280%3A210b%3A1b9%3Ad1f3%3A45cd%3A3be8%3Aeb37&id=o-AKCIDjxZxB0AU4yX4k4Nvh0BxdYa-rkad0U-CELfsvh6&itag=313&source=youtube&requiressl=yes&mh=kH&mm=31%2C29&mn=sn-u5u5n3tpo-cagl%2Csn-h5576nsl&ms=au%2Crdu&mv=m&mvi=1&pl=48&initcwndbps=1366250&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=1467717256&dur=1457.989&lmt=1695683471126771&mt=1695983867&fvip=1&keepalive=yes&fexp=24007246&beids=24350017&c=IOS&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJofoi_UEl6fEBkLfIRMMBiDqBeF71kcttxuNneM5tdSAiEA3CxGILHLYrMaqrAK468isxYTdx9Iq5dB7lsBwpHk0tA%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKYrtZ-7DvWBXhZ5yo0JfhmKhlUFU7QMUuDUHU4cxdEwAiEAzF0KRTZG3nXhzxzwsIFxULR8Z4tF3wvFnONYTrFSbBA%3D"

[generic] Extracting URL: https://rr1---sn-u5u5n3tpo-cagl.googlevideo.com/videoplayback?expire=1696006362&ei=eqwWZc_zLrqL9f...tF3wvFnONYTrFSbBA%3D
[generic] videoplayback?expire=1696006362&ei=eqwWZc_zLrqL9fwPvZ6rmAY&ip=2402:e280:210b:1b9:d1f3:45cd:3be8:eb37&id=o-AKCIDjxZxB0AU4yX4k4Nvh0BxdYa-rkad0U-CELfsvh6&itag=313&source=youtube&requiressl=yes&mh=kH&mm=31,29&mn=sn-u5u5n3tpo-cagl,sn-h5576nsl&ms=au,rdu&mv=m&mvi=1&pl=48&initcwndbps=1366250&vprv=1&svpuc=1&mime=video/webm&gir=yes&clen=1467717256&dur=1457: Downloading webpage
ERROR: [generic] Unable to download webpage: _ssl.c:989: The handshake operation timed out (caused by TransportError('_ssl.c:989: The handshake operation timed out'))

❯ yt-dlp --simulate "https://rr1---sn-h5576nsl.googlevideo.com/videoplayback?expire=1696006362&ei=eqwWZc_zLrqL9fwPvZ6rmAY&ip=2402%3Ae280%3A210b%3A1b9%3Ad1f3%3A45cd%3A3be8%3Aeb37&id=o-AKCIDjxZxB0AU4yX4k4Nvh0BxdYa-rkad0U-CELfsvh6&itag=313&source=youtube&requiressl=yes&mh=kH&mm=31%2C29&mn=sn-u5u5n3tpo-cagl%2Csn-h5576nsl&ms=au%2Crdu&mv=m&mvi=1&pl=48&initcwndbps=1366250&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=1467717256&dur=1457.989&lmt=1695683471126771&mt=1695983867&fvip=1&keepalive=yes&fexp=24007246&beids=24350017&c=IOS&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJofoi_UEl6fEBkLfIRMMBiDqBeF71kcttxuNneM5tdSAiEA3CxGILHLYrMaqrAK468isxYTdx9Iq5dB7lsBwpHk0tA%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKYrtZ-7DvWBXhZ5yo0JfhmKhlUFU7QMUuDUHU4cxdEwAiEAzF0KRTZG3nXhzxzwsIFxULR8Z4tF3wvFnONYTrFSbBA%3D"

[generic] Extracting URL: https://rr1---sn-h5576n
sl.googlevideo.com/videoplayback?expire=1696006362&ei=eqwWZc_zLrqL9fwPvZ6r...tF3wvFnONYTrFSbBA%3D
[generic] videoplayback?expire=1696006362&ei=eqwWZc_zLrqL9fwPvZ6rmAY&ip=2402:e280:210b:1b9:d1f3:45cd:3be8:eb37&id=o-AKCIDjxZxB0AU4yX4k4Nvh0BxdYa-rkad0U-CELfsvh6&itag=313&source=youtube&requiressl=yes&mh=kH&mm=31,29&mn=sn-u5u5n3tpo-cagl,sn-h5576nsl&ms=au,rdu&mv=m&mvi=1&pl=48&initcwndbps=1366250&vprv=1&svpuc=1&mime=video/webm&gir=yes&clen=1467717256&dur=1457: Downloading webpage
[info] videoplayback?expire=1696006362&ei=eqwWZc_zLrqL9fwPvZ6rmAY&ip=2402:e280:210b:1b9:d1f3:45cd:3be8:eb37&id=o-AKCIDjxZxB0AU4yX4k4Nvh0BxdYa-rkad0U-CELfsvh6&itag=313&source=youtube&requiressl=yes&mh=kH&mm=31,29&mn=sn-u5u5n3tpo-cagl,sn-h5576nsl&ms=au,rdu&mv=m&mvi=1&pl=48&initcwndbps=1366250&vprv=1&svpuc=1&mime=video/webm&gir=yes&clen=1467717256&dur=1457: Downloading 1 format(s): fwebm`

I think you're right

**Closed** 2023-10-06 23:22 UTC
Labels: duplicate, question
