### ISSUE TITLE
[youtube] (very) long videos are cut/not downloaded entirely

### ISSUE THREAD

**Issue by d1nuc0m** [yt-dlp/yt-dlp#3784] opened 2022-05-18 21:08 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Description

When downloading a very long video, apparently there are no errors, but the output is cut down to 03:59:49.

Using [this video](https://www.youtube.com/watch?v=MO_KuNjMjj8) as example, it is 5:24:08, but the downloaded file is cut down to 03:59:49, with the first 1 hour and 24 minutes cut. 

The issue seems not to be related to the format or to the use of multiple download threads, below I posted the output of the last command line used, but the problem persists even with no parameters.

Copyright note: the example video is by GARR, the Italian NREN, and published under CC-BY-NC-ND ([see copyright tags here](https://www.garr.tv/stream/6284bc6e52c211a320641c28))

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-f', '91', '-N', '8', 'https://www.youtube.com/watch?v=MO_KuNjMjj8']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.15.40-1-lts-x86_64-with-glibc2.35
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=MO_KuNjMjj8
[youtube] MO_KuNjMjj8: Downloading webpage
[youtube] MO_KuNjMjj8: Downloading android player API JSON
[youtube] MO_KuNjMjj8: Downloading m3u8 information
[youtube] MO_KuNjMjj8: Downloading MPD manifest
[youtube] MO_KuNjMjj8: Downloading m3u8 information
[youtube] MO_KuNjMjj8: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] MO_KuNjMjj8: Downloading 1 format(s): 91
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1652928672/ei/QFyFYrqTCbmI6dsP-rGJ8Ag/ip/87.16.150.64/id/MO_KuNjMjj8.1/itag/91/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D139/sgovp/gir%3Dyes%3Bitag%3D160/hls_chunk_host/rr1---sn-uxaxpu5ap5-o52l.googlevideo.com/force_finished/1/vprv/1/playlist_type/CLEAN/initcwndbps/9860/mh/zb/mm/44/mn/sn-uxaxpu5ap5-o52l/ms/lva/mv/m/mvi/1/pl/24/dover/11/pacing/0/keepalive/yes/fexp/24001373,24007246/mt/1652906680/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,force_finished,vprv,playlist_type/sig/AOq0QJ8wRAIgRs_Drc2DqQfl-8H1qeMmjfxcUGdHBa317kxGe1hM0Q8CIF5MFunmycmT5Ft7Tq0VVgVJPjo5Pv5tRnqgQ5yIvkS3/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIgXsb0I-VYdDzcBG8HP2bWPdeBEocFcwlzKhMTrpFVx6sCIQDu5fqpNOpQl3vk05ZIhLyKOY6jCoFC06l7fFCbNbdK2w%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2878
[download] Destination: Conferenza GARR 2022 - CondiVisioni [MO_KuNjMjj8].mp4
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download] 100% of 204.41MiB in 01:24
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Conferenza GARR 2022 - CondiVisioni [MO_KuNjMjj8].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Conferenza GARR 2022 - CondiVisioni [MO_KuNjMjj8].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Conferenza GARR 2022 - CondiVisioni [MO_KuNjMjj8].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:Conferenza GARR 2022 - CondiVisioni [MO_KuNjMjj8].temp.mp4'
```

**Comment by pukkandan** [comment] 2022-05-19 08:35
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1564

**Closed by pukkandan** 2022-05-19 08:35 UTC
Labels: site-bug, triage
