### ISSUE TITLE
Error from Download via Iq.com

### ISSUE THREAD

**Issue by Hardstylest** [yt-dlp/yt-dlp#8217] opened 2023-09-27 16:46 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.09.24** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

hey guys,
since few Days i have a problem to download Videos from iq.com i have check the Url, and the Videos are playable in the Browser!
I download normaly from my Server. Than i download it from my Home PC the download works. I use the newest yt-dlp. Browser is up to date. I have since today a new Server and have on the new Server the same Problem at the old Server!

I hope you can help me!
greetz

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Microsoft Windows [Version 10.0.17763.379]
(c) 2018 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Administrator>cd c:/yt

c:\yt>yt-dlp -vU "https://www.iq.com/play/absolute-zero-episode-1-vj8wqjyig0" --cookies-from-browser firefox --write-subs --sub-lang "en.*" --sub-format "srt" -N 12 -o "Absolute.Zero.2023.S01E01.WebRip.AAC.1080p.x264-IQ.mp4"
[debug] Command-line config: ['-vU', 'https://www.iq.com/play/absolute-zero-episode-1-vj8wqjyig0', '--cookies-from-browser', 'firefox', '--write-subs', '--sub-lang', 'en.*', '--sub-format', 'srt', '-N', '12', '-o', 'Absolute.Zero.2023.S01E01.WebRip.AAC.1080p.x264-IQ.mp4']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\Administrator\AppData\Roaming\Mozilla\Firefox\Profiles\0ld7hwdk.default-release\cookies.sqlite"
Extracted 76 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.17763-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 125465ac4416bcd4bf1632b899630ceecc08b341e83fdf10bd34700c58ea5152
yt-dlp is up to date (stable@2023.09.24)
[iq.com] Extracting URL: https://www.iq.com/play/absolute-zero-episode-1-vj8wqjyig0
[iq.com] vj8wqjyig0: Downloading webpage
[iq.com] vj8wqjyig0: Downloading webpack JS
[iq.com] vj8wqjyig0: Downloading #9943 module JS
[iq.com] vj8wqjyig0: Downloading #9922 module JS
[iq.com] vj8wqjyig0: Downloading #9864 module JS
[iq.com] vj8wqjyig0: Downloading #9839 module JS
[iq.com] vj8wqjyig0: Downloading #9491 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] vj8wqjyig0: Downloading #8741 module JS
[iq.com] vj8wqjyig0: Downloading #8085 module JS
[iq.com] vj8wqjyig0: Downloading #7045 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] vj8wqjyig0: Downloading #5482 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] vj8wqjyig0: Downloading #5465 module JS
[iq.com] vj8wqjyig0: Downloading #5449 module JS
[iq.com] vj8wqjyig0: Downloading #5189 module JS
[iq.com] vj8wqjyig0: Downloading #4959 module JS
[iq.com] vj8wqjyig0: Downloading #4753 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] vj8wqjyig0: Downloading #4681 module JS
[iq.com] vj8wqjyig0: Downloading #4403 module JS
[iq.com] vj8wqjyig0: Downloading #4182 module JS
[iq.com] vj8wqjyig0: Downloading #3087 module JS
[iq.com] vj8wqjyig0: Downloading #2925 module JS
[iq.com] vj8wqjyig0: Downloading #2846 module JS
[iq.com] vj8wqjyig0: Downloading #2708 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] vj8wqjyig0: Downloading #2398 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] vj8wqjyig0: Downloading #2274 module JS
[iq.com] vj8wqjyig0: Downloading #2248 module JS
[iq.com] vj8wqjyig0: Downloading #2152 module JS
[iq.com] vj8wqjyig0: Downloading #1903 module JS
[iq.com] vj8wqjyig0: Downloading #1650 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] vj8wqjyig0: Downloading #1647 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] vj8wqjyig0: Downloading #1487 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] vj8wqjyig0: Downloading #1417 module JS
[iq.com] vj8wqjyig0: Downloading #1361 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] vj8wqjyig0: Downloading #1126 module JS
[iq.com] vj8wqjyig0: Downloading #1106 module JS
WARNING: [iq.com] Unable to download module JS: HTTP Error 404: Not Found
[iq.com] vj8wqjyig0: Downloading #268 module JS
ERROR: [iq.com] vj8wqjyig0: Unable to extract player JS; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\iqiyi.py", line 570, in _real_extract
  File "yt_dlp\extractor\iqiyi.py", line 553, in _update_bid_tags
  File "yt_dlp\extractor\iqiyi.py", line 544, in _extract_vms_player_js


c:\yt>
```

**Comment by bashonly** [comment] 2023-09-27 20:00
Duplicate of #8123

**Closed by bashonly** 2023-09-27 20:00 UTC
Labels: site-bug, triage
