### ISSUE TITLE
Embed-subs to allow aditional flags

### ISSUE THREAD

**Issue by tamodolo** [yt-dlp/yt-dlp#5911] opened 2022-12-31 17:39 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When embeding subs to file the result don't default subs to be shown by default demanding user to enable it manually.

I tested this using mp4 and convert subs to srt and defaults subs.
With remuxing to MKV it keeps the native format and don't default subs
Tested with crunchyroll

What is requested:

- feature to use lang code with embed-subs to set the default subtitle while remuxing to mkv and tell it'll be forced.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
NA
```

**Comment by pukkandan** [comment] 2022-12-31 23:34
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2799. See it and linked PR for workarounds

**Closed by pukkandan** 2022-12-31 23:34 UTC
Labels: enhancement, triage

**Comment by tamodolo** [comment] 2022-12-31 23:40
Thanks. I searched to see if this existed but did not find it.
