### ISSUE TITLE
how to download Youtube videos?(i'm using vpn)

### ISSUE THREAD

**Issue by zzfhadr** [yt-dlp/yt-dlp#10639] opened 2024-08-03 00:11 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

G:\download>yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.01 from yt-dlp/yt-dlp [ffd7781d6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts), ffprobe 5.1.2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {'http': 'http://127.0.0.1:10809', 'https': 'http://127.0.0.1:10809', 'ftp': 'http://127.0.0.1:10809'}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.01 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.01 from yt-dlp/yt-dlp)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
G:\download>yt-dlp https://www.youtube.com/watch?v=D-wLIAISF9I&list=PL04A9CC6447FC2540
[youtube] Extracting URL: https://www.youtube.com/watch?v=D-wLIAISF9I
[youtube] D-wLIAISF9I: Downloading webpage
[youtube] D-wLIAISF9I: Downloading ios player API JSON
[youtube] D-wLIAISF9I: Downloading tv player API JSON
ERROR: [youtube] D-wLIAISF9I: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
'list' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by hugepower** [comment] 2024-08-03 00:52
Hi, the error you're encountering is typically due to YouTube requiring you to sign in to confirm you're not a bot. You can use the [--cookies-from-browser](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp) option to bypass this verification.

Please follow these steps:

1. Ensure that you are logged into your YouTube account in your browser.
2. Run `yt-dlp` with the following command:

    ```sh
    yt-dlp --cookies-from-browser chrome https://www.youtube.com/watch?v=D-wLIAISF9I&list=PL04A9CC6447FC2540
    ```

    Replace `chrome` with the name of the browser you are using (e.g., `firefox`).

---

This should help them bypass YouTube's bot verification.

**Comment by bashonly** [comment] 2024-08-03 00:58
> --cookies-from-browser

It should be noted that if you start passing your account's cookies to yt-dlp after receiving the "sign in you bot" errors, there's a good chance that your account will also be banned. I would recommend NOT passing cookies, and either getting a different IP with the VPN or not using the VPN at all. Cookies should be a last resort, and you should only use cookies from an account that you don't care about losing.

Closing as duplicate of #10128

**Closed by bashonly** 2024-08-03 00:58 UTC
Labels: question

**Comment by Tokyo-All-Ready** [comment] 2024-08-03 01:00
Wait wait wait youtube is actually banning accounts and not just restricting the ip?

**Comment by bashonly** [comment] 2024-08-03 01:06
> Wait wait wait youtube is actually banning accounts and not just restricting the ip?

 - https://github.com/yt-dlp/yt-dlp/issues/10085
 
 From what I've observed, you are most at risk if:
 
 - you are using your account to bypass the "sign in you bot" error (it's a trap)
 - you are regularly a high volume downloader w/cookies and don't use `--sleep-interval` or `--sleep-requests`
 - you are using your cookies w/ a data center IP/VPN/proxy

**Comment by Tokyo-All-Ready** [comment] 2024-08-03 01:49
> > Wait wait wait youtube is actually banning accounts and not just restricting the ip?
> 
>     * [[youtube] "Video unavailable" with cookies - YouTube blocking accounts from web #10085](https://github.com/yt-dlp/yt-dlp/issues/10085)
> 
> 
> From what I've observed, you are most at risk if:
> 
>     * you are using your account to bypass the "sign in you bot" error (it's a trap)
> 
>     * you are a high volume downloader w/ cookies
> 
>     * you are using your cookies w/ a data center IP/VPN/proxy

I have only used my cookies on my ip.  I have been using the vpn to download yt videos but not logged in.  Ill need to make a expendable account to see how long it lasts before its blocked.  

If my main yt account has another account with a linked phone number to make a ytdl expendable account will both accounts get banned since its going to be linked via the phone to 2fa to make the account?  Ill change the email but it will still have a common link.

**Comment by zzfhadr** [comment] 2024-08-03 03:26
thanks
