### ISSUE TITLE
WARNING: [youtube] pcJ4uYjcm2U: nsig extraction failed: Some formats may be missing          n = JlyEJ0UViqfmhLcpxr8 ; player = https://www.youtube.com/s/player/8d9f6215/player_ias.vflset/en_US/base.js

### ISSUE THREAD

**Issue by noname198737** [yt-dlp/yt-dlp#10455] opened 2024-07-13 21:49 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

Download audio quality seems to be restricted to 140 m4a only on all YouTube videos now (has only been the past week or so this has begun). I was able to download Opus audio files in the past.

Have gone through the process of updating my Macports & attempted to update yt-dlp.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://youtu.be/IySpQlPYj-k']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29]
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-14.5-arm64-arm-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4
[debug] Optional libraries: pycrypto-3.19.0, sqlite3-3.46.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2024.07.02 from yt-dlp/yt-dlp
Latest version: stable@2024.07.09 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp with MacPorts; Use "sudo port selfupdate && sudo port upgrade yt-dlp" to update. If MacPorts does not have the latest version you can request an update at https://trac.macports.org/newticket?type=update&port=yt-dlp&cc=ryandesign&summary=yt-dlp:%20Update%20to%20latest%20version
[youtube] Extracting URL: https://youtu.be/IySpQlPYj-k
[youtube] IySpQlPYj-k: Downloading webpage
[youtube] IySpQlPYj-k: Downloading ios player API JSON
[debug] [youtube] Extracting signature function js_8d9f6215_109
[debug] Loading youtube-sigfuncs.js_8d9f6215_109 from cache
[youtube] IySpQlPYj-k: Downloading player 8d9f6215
WARNING: [youtube] IySpQlPYj-k: nsig extraction failed: Some formats may be missing
         n = 9WMId7JdLuN9787iYLP ; player = https://www.youtube.com/s/player/8d9f6215/player_ias.vflset/en_US/base.js
[debug] [youtube] Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] IySpQlPYj-k: nsig extraction failed: Some formats may be missing
         n = MAalao_a_my4YVBbNyQ ; player = https://www.youtube.com/s/player/8d9f6215/player_ias.vflset/en_US/base.js
[youtube] IySpQlPYj-k: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] IySpQlPYj-k: Downloading 1 format(s): 616+140
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1720928849/ei/8fWSZsOEOeCRz7sP--GcyA0/ip/103.46.220.61/id/2324a94253d88fe9/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D4143689896%3Bdur%3D6826.600%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1697061475710438/rqh/1/hls_chunk_host/rr2---sn-ntqe6n7r.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/97/mm/31,26/mn/sn-ntqe6n7r,sn-hxa76n7z/ms/au,onr/mv/m/mvi/2/pl/24/force_finished/1/initcwndbps/1898750/vprv/1/playlist_type/DVR/dover/13/txp/4432434/mt/1720906866/fvip/4/short_key/1/keepalive/yes/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,force_finished,vprv,playlist_type/sig/AJfQdSswRAIgNeWWHQwTZ5z9fSuk-RW-60Ui0jjQ2M7ifoIooeOaLwECIA91cE3Lrj0JQf-sbDN-TNvOIU6652s_KRpp7i4QxKpL/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AHlkHjAwRgIhAJyyletdCZV0syvvxKjbY_A6XhcxzRiVrohV89h7dETZAiEA9x0JWyO_jcVh6otwj5WntLbZDK1aew6B7bxH-Om6bRo%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1316
[download] Destination: EXIT 2023 ｜ Marko Nastić live @ mts Dance Arena (HQ Version) [IySpQlPYj-k].f616.mp4
```

**Comment by bashonly** [comment] 2024-07-13 22:02
> ERROR: You installed yt-dlp with MacPorts; Use "sudo port selfupdate && sudo port upgrade yt-dlp" to update. If MacPorts does not have the latest version you can request an update at https://trac.macports.org/newticket?type=update&port=yt-dlp&cc=ryandesign&summary=yt-dlp:%20Update%20to%20latest%20version


Update yt-dlp

Duplicate of #10391

**Closed by bashonly** 2024-07-13 22:02 UTC
Labels: site-bug, triage

**Comment by noname198737** [comment] 2024-07-27 21:46
I managed to update yt-dlp after your comment, which got it working again. Now, I'm having the same problem again. yt-dlp seems to have a newer version, I attempt to update through macports, but still have the issue of missing formats?

**Comment by bashonly** [comment] 2024-07-27 21:56
@noname198737 what formats are missing? share the output of `yt-dlp -vF "URL"`

**Comment by noname198737** [comment] 2024-07-28 06:32
opus format.

yt-dlp -F https://youtu.be/XUcMjLjUF6c
[youtube] Extracting URL: https://youtu.be/XUcMjLjUF6c
[youtube] XUcMjLjUF6c: Downloading webpage
[youtube] XUcMjLjUF6c: Downloading ios player API JSON
[youtube] XUcMjLjUF6c: Downloading player 1f8742dc
WARNING: [youtube] XUcMjLjUF6c: nsig extraction failed: Some formats may be missing
         n = BlF7lKyzLbI3t7qQJ ; player = https://www.youtube.com/s/player/1f8742dc/player_ias.vflset/en_US/base.js
WARNING: [youtube] XUcMjLjUF6c: nsig extraction failed: Some formats may be missing
         n = yiStdX8JV7JMpkvmR ; player = https://www.youtube.com/s/player/1f8742dc/player_ias.vflset/en_US/base.js
[youtube] XUcMjLjUF6c: Downloading m3u8 information
[info] Available formats for XUcMjLjUF6c:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb3 mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb2 mhtml 80x45        0    │                  mhtml │ images                                  storyboard
sb1 mhtml 160x90       0    │                  mhtml │ images                                  storyboard
sb0 mhtml 320x180      0    │                  mhtml │ images                                  storyboard
233 mp4   audio only        │                  m3u8  │ audio only          unknown             Default
234 mp4   audio only        │                  m3u8  │ audio only          unknown             Default
139 m4a   audio only      2 │   60.33MiB   49k https │ audio only          mp4a.40.5   49k 22k low, m4a_dash
140 m4a   audio only      2 │  160.12MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, m4a_dash
602 mp4   256x144     13    │ ~187.11MiB  151k m3u8  │ vp09.00.10.08  151k video only
269 mp4   256x144     25    │ ~292.12MiB  236k m3u8  │ avc1.4D400C    236k video only
160 mp4   256x144     25    │  135.71MiB  110k https │ avc1.4D400C    110k video only          144p, mp4_dash
603 mp4   256x144     25    │ ~272.87MiB  221k m3u8  │ vp09.00.11.08  221k video only
229 mp4   426x240     25    │ ~567.75MiB  459k m3u8  │ avc1.4D4015    459k video only
133 mp4   426x240     25    │  300.42MiB  243k https │ avc1.4D4015    243k video only          240p, mp4_dash
604 mp4   426x240     25    │ ~560.14MiB  453k m3u8  │ vp09.00.20.08  453k video only
230 mp4   640x360     25    │ ~  1.18GiB  980k m3u8  │ avc1.4D401E    980k video only
134 mp4   640x360     25    │  637.58MiB  516k https │ avc1.4D401E    516k video only          360p, mp4_dash
605 mp4   640x360     25    │ ~  1.19GiB  988k m3u8  │ vp09.00.21.08  988k video only
231 mp4   854x480     25    │ ~  2.21GiB 1832k m3u8  │ avc1.4D401E   1832k video only
135 mp4   854x480     25    │    1.26GiB 1045k https │ avc1.4D401E   1045k video only          480p, mp4_dash
606 mp4   854x480     25    │ ~  1.93GiB 1601k m3u8  │ vp09.00.30.08 1601k video only
232 mp4   1280x720    25    │ ~  3.92GiB 3250k m3u8  │ avc1.64001F   3250k video only
136 mp4   1280x720    25    │    2.43GiB 2014k https │ avc1.64001F   2014k video only          720p, mp4_dash
609 mp4   1280x720    25    │ ~  3.99GiB 3304k m3u8  │ vp09.00.31.08 3304k video only
270 mp4   1920x1080   25    │ ~  8.22GiB 6805k m3u8  │ avc1.640028   6805k video only
137 mp4   1920x1080   25    │    4.86GiB 4028k https │ avc1.640028   4028k video only          1080p, mp4_dash
614 mp4   1920x1080   25    │ ~  6.10GiB 5054k m3u8  │ vp09.00.40.08 5054k video only

**Comment by seproDev** [comment] 2024-07-28 06:38
@noname198737 you did not run the command as bashonly wrote it. Please include the `-vF`.
Though based on this incomplete log it still seems like you are using an outdated version.

**Comment by noname198737** [comment] 2024-07-28 06:45
My bad, have done it again & pasted below. As I mentioned in my initial comment, when I follow the update process, the same existing version seems to remain.

yt-dlp -vF "https://youtu.be/XaWTb6X_KsQ"
[debug] Command-line config: ['-vF', 'https://youtu.be/XaWTb6X_KsQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c]
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-14.5-arm64-arm-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4
[debug] Optional libraries: pycrypto-3.19.0, sqlite3-3.46.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1829 extractors
[youtube] Extracting URL: https://youtu.be/XaWTb6X_KsQ
[youtube] XaWTb6X_KsQ: Downloading webpage
[youtube] XaWTb6X_KsQ: Downloading ios player API JSON
[debug] [youtube] Extracting signature function js_1f8742dc_107
[debug] Loading youtube-sigfuncs.js_1f8742dc_107 from cache
[youtube] XaWTb6X_KsQ: Downloading player 1f8742dc
WARNING: [youtube] XaWTb6X_KsQ: nsig extraction failed: Some formats may be missing
         n = VMt3FclU5jMwX5U2N ; player = https://www.youtube.com/s/player/1f8742dc/player_ias.vflset/en_US/base.js
[debug] [youtube] Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] [youtube] Extracting signature function js_1f8742dc_103
[debug] Loading youtube-sigfuncs.js_1f8742dc_103 from cache
WARNING: [youtube] XaWTb6X_KsQ: nsig extraction failed: Some formats may be missing
         n = AhKRdbifrv3WPBrQe ; player = https://www.youtube.com/s/player/1f8742dc/player_ias.vflset/en_US/base.js
[youtube] XaWTb6X_KsQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for XaWTb6X_KsQ:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb3 mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb2 mhtml 80x45        0    │                  mhtml │ images                                  storyboard
sb1 mhtml 160x90       0    │                  mhtml │ images                                  storyboard
sb0 mhtml 320x180      0    │                  mhtml │ images                                  storyboard
233 mp4   audio only        │                  m3u8  │ audio only          unknown             [en] Default, IOS
234 mp4   audio only        │                  m3u8  │ audio only          unknown             [en] Default, IOS
139 m4a   audio only      2 │   31.13MiB   49k https │ audio only          mp4a.40.5   49k 22k [en] low, IOS, m4a_dash
140 m4a   audio only      2 │   82.63MiB  129k https │ audio only          mp4a.40.2  129k 44k [en] medium, IOS, m4a_dash
602 mp4   256x144     15    │ ~ 67.87MiB  106k m3u8  │ vp09.00.10.08  106k video only          IOS
269 mp4   256x144     30    │ ~111.77MiB  175k m3u8  │ avc1.4D400C    175k video only          IOS
160 mp4   256x144     30    │   47.73MiB   75k https │ avc1.4D400C     75k video only          144p, IOS, mp4_dash
603 mp4   256x144     30    │ ~112.21MiB  176k m3u8  │ vp09.00.11.08  176k video only          IOS
229 mp4   426x240     30    │ ~202.05MiB  317k m3u8  │ avc1.4D4015    317k video only          IOS
133 mp4   426x240     30    │  105.35MiB  165k https │ avc1.4D4015    165k video only          240p, IOS, mp4_dash
604 mp4   426x240     30    │ ~199.77MiB  313k m3u8  │ vp09.00.20.08  313k video only          IOS
230 mp4   640x360     30    │ ~518.76MiB  813k m3u8  │ avc1.4D401E    813k video only          IOS
134 mp4   640x360     30    │  212.46MiB  333k https │ avc1.4D401E    333k video only          360p, IOS, mp4_dash
605 mp4   640x360     30    │ ~511.94MiB  802k m3u8  │ vp09.00.21.08  802k video only          IOS
231 mp4   854x480     30    │ ~867.56MiB 1359k m3u8  │ avc1.4D401F   1359k video only          IOS
135 mp4   854x480     30    │  346.85MiB  543k https │ avc1.4D401F    543k video only          480p, IOS, mp4_dash
606 mp4   854x480     30    │ ~784.78MiB 1230k m3u8  │ vp09.00.30.08 1230k video only          IOS
232 mp4   1280x720    30    │ ~  1.43GiB 2297k m3u8  │ avc1.4D401F   2297k video only          IOS
136 mp4   1280x720    30    │  579.16MiB  907k https │ avc1.4D401F    907k video only          720p, IOS, mp4_dash
609 mp4   1280x720    30    │ ~  1.35GiB 2172k m3u8  │ vp09.00.31.08 2172k video only          IOS
270 mp4   1920x1080   30    │ ~  2.97GiB 4764k m3u8  │ avc1.640028   4764k video only          IOS
137 mp4   1920x1080   30    │    1.82GiB 2915k https │ avc1.640028   2915k video only          1080p, IOS, mp4_dash
614 mp4   1920x1080   30    │ ~  2.30GiB 3686k m3u8  │ vp09.00.40.08 3686k video only          IOS
616 mp4   1920x1080   30    │ ~  3.59GiB 5764k m3u8  │ vp09.00.40.08 5764k video only          Premium, IOS

**Comment by seproDev** [comment] 2024-07-28 06:55
> yt-dlp version stable@2024.07.16

Okay you are still on an old version. Youtube is constantly trying to break yt-dlp, so regular updates are required for full functionality. In this case the web formats can no longer be extracted with versions before 2024.07.25. That's why you are missing the opus audio.

Seemingly macports has not yet updated yt-dlp. As the versions package managers are not maintained by us we have no controll over what they ship.
You could consider using brew instead or the standalone macos binary we provide.

**Comment by noname198737** [comment] 2024-07-28 07:27
Thank you for the detailed response. 

If I was to change to one of the 2 options you suggested, would I need to uninstall what I currently have setup? Guessing with the standalone macos binary, that still utilizes code through the Terminal app?

**Comment by seproDev** [comment] 2024-07-28 08:19
Yes you should uninstall the current version of yt-dlp you have installed.
For the macos binary you will want to place it somewhere within you `$PATH`, such as `~/.local/bin` so that you can call it using the Terminal from anywhere.
Updating with the standalone binary happens with `yt-dlp -U`

**Comment by LearZhou** [comment] 2024-07-31 17:38
Similar warning happened again with yt-dlp version stable@2024.07.25, the latest release.

**Comment by seproDev** [comment] 2024-07-31 17:46
@LearZhou https://github.com/yt-dlp/yt-dlp/issues/10608 is being used to track the current nsig breakage

**Comment by romanr** [comment] 2025-05-22 16:25
It happens periodically and to anyone who didnt' update in a while. When you search for `nsig extraction failed` error you arrive at this issue. 
Maybe it will be good idea to add to `nsig extraction failed` error a mention that this is likely to outdated yt-dlp version;

> nsig extraction failed: Some formats may be missing. This is likely due to an outdated version. Please upgrade and try again.

Also it prompts user to submit bug report which may be unnecessary.

**Comment by bashonly** [comment] 2025-05-22 17:33
@romanr As of recently, nsig extraction has been breaking *at least* once a month. We definitely want bug reports. The latest nsig breakge issue is pinned to the top of the issue tracker, with a giant note that it has been fixed in the latest release and users should update.
