### ISSUE TITLE
--download-sections forces overwriting files

### ISSUE THREAD

**Issue by dissona** [yt-dlp/yt-dlp#6846] opened 2023-04-18 00:55 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When downloading twitch VODs using --download-sections it will always overwrite the previous file

These args are completely ignored:
--no-post-overwrites
--no-overwrites
--no-continue

maybe there is a better way to download VODs and skip large sections + supports resuming that i am unaware of?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-Uv', '--no-continue', '--no-overwrites', '--no-post-overwrites', '--download-sections', '*01:00:00-inf', '-i', 'https://www.twitch.tv/videos/1795281279']

Python 3.10.10 (CPython x86_64 64bit) - Linux-6.1.23-1-MANJARO-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
```

**Comment by bashonly** [comment] 2023-04-18 01:00
I cannot reproduce the issue. Post a **complete** verbose log

**Comment by bashonly** [comment] 2023-04-18 01:14
> The log has nothing useful.

How do you expect anyone other than you to diagnose the issue if you don't share the log? This is not the attitude that will solve your problem.

> file created by ffmpeg is videoname.mp4.part then if download fails due to PC crash/loss of internet connectivity and you restart the download with the same name (which it will be) it will be overwritten and all data lost

pukkandan said in https://github.com/yt-dlp/yt-dlp/issues/6740#issuecomment-1500717482:
> Replacing temporary files is an essential part of the program's function and cannot be changed or controlled by user. If you don't want yt-dlp to modify it's own temporary files, you just shouldn't run it.

Since completed downloads are not being overwritten, closing as duplicate of #6740

**Closed by bashonly** 2023-04-18 01:14 UTC
Labels: bug, cant-reproduce, incomplete
