### ISSUE TITLE
 qq music and cool music download failed, after netease cloud music download exceeded, there was a problem with the music naming format. 

### ISSUE THREAD

**Issue by es3344520** [yt-dlp/yt-dlp#9696] opened 2024-04-16 07:09 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Provide a description that is worded well enough to be understood

第一个问题是，在成功下载网易云音乐后，在命名音乐格式的过程中出现了问题。正确的音乐命名格式应该是：歌手-歌曲。但最后是NA-song。也就是说，歌手的名字没有被正确获得。这个网易云基本上是这样的。它需要修复。  

 
 The second problem, unable to download songs from qq music and cool music, any songs from these two platforms are the same, showing no support links. But what it provides is a link to the song interface.  See how it works?? 
 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[generic] Extracting URL: https://y.qq.com/n/ryqq/songDetail/00128N3r2SYKMF
[generic] 00128N3r2SYKMF: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 00128N3r2SYKMF: Extracting information
ERROR: Unsupported URL: https://y.qq.com/n/ryqq/songDetail/00128N3r2SYKMF
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1594, in wrapper
return func(self, *args, **kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1729, in __extract_info
ie_result = ie.extract(url)
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 732, in extract
ie_result = self._real_extract(url)
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2530, in _real_extract
raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://y.qq.com/n/ryqq/songDetail/00128N3r2SYKMF
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/Users/mac/Desktop/1.py", line 19, in <module>
ydl.download(['https://y.qq.com/n/ryqq/songDetail/00128N3r2SYKMF'])
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3558, in download
self.__download_wrapper(self.extract_info)(
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 3533, in wrapper
res = func(*args, **kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1583, in extract_info
return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1612, in wrapper
self.report_error(str(e), e.format_traceback())
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1061, in report_error
self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1000, in trouble
raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: Unsupported URL: https://y.qq.com/n/ryqq/songDetail/00128N3r2SYKMF
```

**Comment by pukkandan** [comment] 2024-04-16 12:35
That is not a full log

**Comment by c-basalt** [comment] 2024-04-22 00:10
Make sure you should provide a full log for your first one.
Btw, the second one you raised (though I don't think it is a good idea to mix two things in a single issue) appears to be a duplicate of #9336.

**Closed** 2024-04-22 05:03 UTC
Labels: incomplete, site-bug, triage
