### ISSUE TITLE
[Vimeo] source/Original video formats aren't always checked by yt-dlp

### ISSUE THREAD

**Issue by Maxr1998** [yt-dlp/yt-dlp#10896] opened 2024-09-01 10:47 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe/Germany

### Provide a description that is worded well enough to be understood

I've recently noticed that videos which should have source/originals available don't return them when queried with yt-dlp (-F). One random example I noticed is [this video](https://vimeo.com/997630629), which has the original available through the site. Nevertheless, yt-dlp doesn't return it. Note that I'm logged in, used cookies from my browser, and successfully have impersonation set up.
While digging through the code and adding some print statements, I noticed the following:
When taking the `_extract_from_api` path, the `_extract_original_format` is never called. I don't know whether the API is supposed to return originals too, and whether it did that in the past, but it clearly doesn't do it now.
I confirmed this issue by (uglily) patching the source extraction into the called method:

<details>
<summary>source patch</summary>

```diff
diff --git a/vimeo.py.bak b/vimeo.py
index a20cf4b..da6fe84 100644
--- a/vimeo.py.bak
+++ b/vimeo.py
@@ -235,6 +235,7 @@ class VimeoBaseInfoExtractor(InfoExtractor):
         }
 
     def _extract_original_format(self, url, video_id, unlisted_hash=None):
+        print("Trying original")
         query = {'action': 'load_download_config'}
         if unlisted_hash:
             query['unlisted_hash'] = unlisted_hash
@@ -798,6 +799,12 @@ class VimeoIE(VimeoBaseInfoExtractor):
 
         info = self._parse_config(self._download_json(
             video['config_url'], video_id), video_id)
+
+        source_format = self._extract_original_format(
+            'https://vimeo.com/' + video_id, video_id, video.get('unlisted_hash'))
+        if source_format:
+            info['formats'].append(source_format)
+
         get_timestamp = lambda x: parse_iso8601(video.get(x + '_time'))
         info.update({
             'description': video.get('description'),
@@ -851,6 +858,7 @@ class VimeoIE(VimeoBaseInfoExtractor):
                 raise
 
     def _real_extract(self, url):
+        print("Running extract")
         url, data, headers = self._unsmuggle_headers(url)
         if 'Referer' not in headers:
             headers['Referer'] = url
@@ -930,6 +938,7 @@ class VimeoIE(VimeoBaseInfoExtractor):
                 r'vimeo\.(?:clip|vod_title)_page_config\s*=\s*({.+?});',
                 webpage, 'page config', default='{}'), video_id, fatal=False)
             if not page_config:
+                print("Running extract from API")
                 return self._extract_from_api(video_id)
             config_url = page_config['player']['config_url']
             cc_license = page_config.get('cc_license')
```
</details>

With this patch, extracting originals works again:

<details>
<summary>log output</summary>

*Note that I'm using the (patched) stable version in this example, the reproducible example in the other logs uses the nightly.*
```
[debug] Command-line config: ['-vU', '-F', '--cookies-from-browser', 'vivaldi', 'https://vimeo.com/997630629']
[debug] User config "/home/max/.config/yt-dlp/config": ['-v', '--merge-output-format', 'mkv', '--write-sub', '--embed-subs', '--sub-format', 'vtt', '--convert-subtitles', 'srt', '--sub-lang', 'en,en-US']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208]
[debug] Python 3.12.5 (CPython x86_64 64bit) - Linux-6.10.6-arch1-1-x86_64-with-glibc2.40 (OpenSSL 3.3.1 4 Jun 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, rtmpdump 2.4
[debug] Optional libraries: certifi-2024.07.04, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.46.1, urllib3-1.26.19, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from vivaldi
[debug] Extracting cookies from: "/home/max/.config/vivaldi/Default/Cookies"
Extracted 3320 cookies from vivaldi
[debug] cookie version breakdown: {'v10': 3310, 'v11': 0, 'other': 0, 'unencrypted': 68}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[vimeo] Extracting URL: https://vimeo.com/997630629
Running extract
[vimeo] 997630629: Downloading webpage
Running extract from API
[vimeo] 997630629: Downloading viewer info
[vimeo] 997630629: Downloading API JSON
[vimeo] 997630629: Downloading API JSON
[vimeo] 997630629: Downloading JSON metadata
[vimeo] 997630629: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 997630629: Downloading fastly_skyfire m3u8 information
[vimeo] 997630629: Downloading akfire_interconnect_quic MPD information
WARNING: [vimeo] 997630629: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[vimeo] 997630629: Downloading fastly_skyfire MPD information
WARNING: [vimeo] 997630629: Failed to parse XML: not well-formed (invalid token): line 1, column 0
Trying original
[vimeo] 997630629: Downloading JSON metadata
[vimeo] 997630629: Checking Original video URL
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[info] Available formats for 997630629:
ID                                              EXT RESOLUTION FPS │  FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-akfire_interconnect_quic-audio-high-English mp4 audio only     │                 m3u8  │ audio only        unknown    [en] English
hls-fastly_skyfire-audio-high-English           mp4 audio only     │                 m3u8  │ audio only        unknown    [en] English
hls-akfire_interconnect_quic-467                mp4 240x426     24 │ ~ 2.78MiB  467k m3u8  │ avc1.640015  467k video only
hls-fastly_skyfire-467                          mp4 240x426     24 │ ~ 2.78MiB  467k m3u8  │ avc1.640015  467k video only
hls-akfire_interconnect_quic-777                mp4 360x640     24 │ ~ 4.63MiB  777k m3u8  │ avc1.64001E  777k video only
hls-fastly_skyfire-777                          mp4 360x640     24 │ ~ 4.63MiB  777k m3u8  │ avc1.64001E  777k video only
hls-akfire_interconnect_quic-1362               mp4 540x960     24 │ ~ 8.12MiB 1362k m3u8  │ avc1.64001F 1362k video only
hls-fastly_skyfire-1362                         mp4 540x960     24 │ ~ 8.12MiB 1362k m3u8  │ avc1.64001F 1362k video only
hls-akfire_interconnect_quic-2472               mp4 720x1280    24 │ ~14.73MiB 2472k m3u8  │ avc1.640020 2472k video only
hls-fastly_skyfire-2472                         mp4 720x1280    24 │ ~14.73MiB 2472k m3u8  │ avc1.640020 2472k video only
hls-akfire_interconnect_quic-4835               mp4 1080x1920   24 │ ~28.82MiB 4835k m3u8  │ avc1.64002A 4835k video only
hls-fastly_skyfire-4835                         mp4 1080x1920   24 │ ~28.82MiB 4835k m3u8  │ avc1.64002A 4835k video only
Original                                        mp4 1080x1920      │   1.10GiB       https │ unknown           unknown
```
</details>

I'm not knowledgeable enough with yt-dlp nor the Vimeo API to provide a patch myself, but I hope this report provides some direction.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-F', '--cookies-from-browser', 'vivaldi', 'https://vimeo.com/997630629']
[debug] User config "/home/max/.config/yt-dlp/config": ['-v', '--merge-output-format', 'mkv', '--write-sub', '--embed-subs', '--sub-format', 'vtt', '--convert-subtitles', 'srt', '--sub-lang', 'en,en-US']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.26.232811 from yt-dlp/yt-dlp-nightly-builds [41be32e78] (pip)
[debug] Python 3.12.5 (CPython x86_64 64bit) - Linux-6.10.6-arch1-1-x86_64-with-glibc2.40 (OpenSSL 3.3.1 4 Jun 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.2.2, websockets-13.0.1
[debug] Proxy map: {}
Extracting cookies from vivaldi
[debug] Extracting cookies from: "/home/max/.config/vivaldi/Default/Cookies"
Extracted 3321 cookies from vivaldi
[debug] cookie version breakdown: {'v10': 3311, 'v11': 0, 'other': 0, 'unencrypted': 68}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.26.232811 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.26.232811 from yt-dlp/yt-dlp-nightly-builds)
[vimeo] Extracting URL: https://vimeo.com/997630629
[vimeo] 997630629: Downloading webpage
[vimeo] 997630629: Downloading viewer info
[vimeo] 997630629: Downloading API JSON
[vimeo] 997630629: Downloading API JSON
[vimeo] 997630629: Downloading JSON metadata
[vimeo] 997630629: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 997630629: Downloading fastly_skyfire m3u8 information
[vimeo] 997630629: Downloading akfire_interconnect_quic MPD information
WARNING: [vimeo] 997630629: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[vimeo] 997630629: Downloading fastly_skyfire MPD information
WARNING: [vimeo] 997630629: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[info] Available formats for 997630629:
ID                                              EXT RESOLUTION FPS │  FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-akfire_interconnect_quic-audio-high-English mp4 audio only     │                 m3u8  │ audio only        unknown    [en] English
hls-fastly_skyfire-audio-high-English           mp4 audio only     │                 m3u8  │ audio only        unknown    [en] English
hls-akfire_interconnect_quic-467                mp4 240x426     24 │ ~ 2.78MiB  467k m3u8  │ avc1.640015  467k video only
hls-fastly_skyfire-467                          mp4 240x426     24 │ ~ 2.78MiB  467k m3u8  │ avc1.640015  467k video only
hls-akfire_interconnect_quic-777                mp4 360x640     24 │ ~ 4.63MiB  777k m3u8  │ avc1.64001E  777k video only
hls-fastly_skyfire-777                          mp4 360x640     24 │ ~ 4.63MiB  777k m3u8  │ avc1.64001E  777k video only
hls-akfire_interconnect_quic-1362               mp4 540x960     24 │ ~ 8.12MiB 1362k m3u8  │ avc1.64001F 1362k video only
hls-fastly_skyfire-1362                         mp4 540x960     24 │ ~ 8.12MiB 1362k m3u8  │ avc1.64001F 1362k video only
hls-akfire_interconnect_quic-2472               mp4 720x1280    24 │ ~14.73MiB 2472k m3u8  │ avc1.640020 2472k video only
hls-fastly_skyfire-2472                         mp4 720x1280    24 │ ~14.73MiB 2472k m3u8  │ avc1.640020 2472k video only
hls-akfire_interconnect_quic-4835               mp4 1080x1920   24 │ ~28.82MiB 4835k m3u8  │ avc1.64002A 4835k video only
hls-fastly_skyfire-4835                         mp4 1080x1920   24 │ ~28.82MiB 4835k m3u8  │ avc1.64002A 4835k video only
```

**Comment by bashonly** [comment] 2024-09-01 17:01
Duplicate of #9163

**Closed by bashonly** 2024-09-01 17:01 UTC
Labels: duplicate, site-bug, site:vimeo
