### ISSUE TITLE
Youtube download in 720p with formula -S res:720,ext:mp4:m4a,vcodec:h264,+acodec:m4a fails for certain videos

### ISSUE THREAD

**Issue by xxxLCxxx** [yt-dlp/yt-dlp#3732] opened 2022-05-14 07:56 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

world

### Description

Recently, some YouTube videos fail to download with the formula:
**-S res:720,ext:mp4:m4a,vcodec:h264,+acodec:m4a**
This seems to be some sort of censorship, as I had only complications with videos not complying with the “Ministry of Truth”, so far.
The failure looks like this (“_Did not get any data blocks_”):
```
[youtube] hQaO678_XSg: Downloading webpage
[youtube] hQaO678_XSg: Downloading android player API JSON
[info] hQaO678_XSg: Downloading 1 format(s): 22
[download] Resuming download at byte 1242903


ERROR: Did not get any data blocks
```

Here is a look at the offending video and its formats:

```
yt-dlp -F "https://www.youtube.com/watch?v=hQaO678_XSg"
[youtube] hQaO678_XSg: Downloading webpage
[youtube] hQaO678_XSg: Downloading android player API JSON
[info] Available formats for hQaO678_XSg:
ID  EXT   RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR     ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27          │                  mhtml │ images                                    storyboard
sb1 mhtml 80x45          │                  mhtml │ images                                    storyboard
sb0 mhtml 160x90         │                  mhtml │ images                                    storyboard
139 m4a   audio only     │   14.60MiB   48k https │ audio only        mp4a.40.5   48k 22050Hz low, m4a_dash
249 webm  audio only     │   15.06MiB   50k https │ audio only        opus        50k 48000Hz low, webm_dash
250 webm  audio only     │   18.08MiB   60k https │ audio only        opus        60k 48000Hz low, webm_dash
140 m4a   audio only     │   38.74MiB  129k https │ audio only        mp4a.40.2  129k 44100Hz medium, m4a_dash
251 webm  audio only     │   31.62MiB  105k https │ audio only        opus       105k 48000Hz medium, webm_dash
17  3gp   176x144      7 │   23.24MiB   77k https │ mp4v.20.3     77k mp4a.40.2    0k 22050Hz 144p
160 mp4   256x144     30 │   16.28MiB   54k https │ avc1.4d400c   54k video only              144p, mp4_dash
278 webm  256x144     30 │   18.44MiB   61k https │ vp9           61k video only              144p, webm_dash
133 mp4   426x240     30 │   34.27MiB  114k https │ avc1.4d4015  114k video only              240p, mp4_dash
242 webm  426x240     30 │   21.92MiB   73k https │ vp9           73k video only              240p, webm_dash
134 mp4   640x360     30 │   60.31MiB  201k https │ avc1.4d401e  201k video only              360p, mp4_dash
18  mp4   640x360     30 │  108.73MiB  363k https │ avc1.42001E  363k mp4a.40.2    0k 44100Hz 360p
243 webm  640x360     30 │   33.52MiB  112k https │ vp9          112k video only              360p, webm_dash
135 mp4   854x480     30 │   99.12MiB  331k https │ avc1.4d401f  331k video only              480p, mp4_dash
244 webm  854x480     30 │   48.73MiB  162k https │ vp9          162k video only              480p, webm_dash
136 mp4   1280x720    30 │  182.28MiB  609k https │ avc1.64001f  609k video only              720p, mp4_dash
22  mp4   1280x720    30 │ ~ 87.38MiB  285k https │ avc1.64001F  285k mp4a.40.2    0k 44100Hz 720p
247 webm  1280x720    30 │  101.31MiB  338k https │ vp9          338k video only              720p, webm_dash
137 mp4   1920x1080   30 │  339.15MiB 1133k https │ avc1.640028 1133k video only              1080p, mp4_dash
248 webm  1920x1080   30 │  119.20MiB  398k https │ vp9          398k video only              1080p, webm_dash
```

You can already tell that the download is going to fail by looking at the faulty size (~ 87.38MiB).
Is there a way to make yt-dlp recognize this and fall-back (get video+audio instead)?

### Verbose log

```shell
yt-dlp -vU -S res:720,ext:mp4:m4a,vcodec:h264,+acodec:m4a  "https://www.youtube.com/watch?v=hQaO678_XSg"
[debug] Command-line config: ['-vU', '-S', 'res:720,ext:mp4:m4a,vcodec:h264,+acodec:m4a', 'https://www.youtube.com/watch?v=hQaO678_XSg']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.10.0 (CPython 64bit) - Linux-3.13.0-144-generic-x86_64-with-glibc2.19
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0-static (setts), ffprobe 4.3.1-static, phantomjs 2.1.1
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=hQaO678_XSg
[youtube] hQaO678_XSg: Downloading webpage
[youtube] hQaO678_XSg: Downloading android player API JSON
[debug] Sort order given by user: res:720, ext:mp4:m4a, vcodec:h264, +acodec:m4a
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, res:720(720.0), vext:mp4(5), aext:m4a(8), vcodec:h264(7), +acodec:m4a(8), quality, fps, hdr:12(7), source, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] hQaO678_XSg: Downloading 1 format(s): 22
[debug] Invoking downloader on "https://rr2---sn-oguelned.googlevideo.com/videoplayback?expire=1652536198&ei=Jl9_Yuv9KdHT7QTcsIKQCA&ip=27.95.77.134&id=o-ACwRpgY0KVeVOCVtRLi9KzNkeyAan7s-0hW8EyTaXRYy&itag=22&source=youtube&requiressl=yes&mh=ds&mm=31%2C26&mn=sn-oguelned%2Csn-3pm7dnes&ms=au%2Conr&mv=m&mvi=2&pl=25&initcwndbps=1050000&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=2510.100&lmt=1652490153223762&mt=1652514294&fvip=1&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANhhfDBLvtkWzFKr8FhNoa6szwV2Guc06w6TBy0w7VF7AiEAgvUCUKuqK5pFSAIfI437oHLcAmNpS6KD_a12zKJQDO4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgMOsyqYYMC0JKYR7ljEMVf7HXgR1lwDlvCh3_RmpT04QCIDW-XeHBmEoifaH87nGZ2VUitiwrb9Yt-h7vuYskNdlL"
[download] Destination: US pours billions into Ukraine proxy war while keeping public in the dark [hQaO678_XSg].mp4
[download]   1.3% of 85.33MiB at 590.64KiB/s ETA 02:25[download] Got server HTTP error: Downloaded 1203731 bytes, expected 89479716 bytes. Retrying (attempt 1 of 10) ...


ERROR: Did not get any data blocks
  File "/tmp/.mount_pythonQxa08Z/opt/python3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_pythonQxa08Z/opt/python3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/bin/yt-dlp/__main__.py", line 19, in <module>
    yt_dlp.main()
  File "/usr/bin/yt-dlp/yt_dlp/__init__.py", line 869, in main
    _real_main(argv)
  File "/usr/bin/yt-dlp/yt_dlp/__init__.py", line 859, in _real_main
    retcode = ydl.download(all_urls)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3264, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3237, in wrapper
    res = func(*args, **kwargs)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1399, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2648, in process_video_result
    self.process_info(new_info)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3138, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2846, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/bin/yt-dlp/yt_dlp/downloader/common.py", line 457, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/bin/yt-dlp/yt_dlp/downloader/http.py", line 370, in real_download
    return download()
  File "/usr/bin/yt-dlp/yt_dlp/downloader/http.py", line 339, in download
    self.report_error('Did not get any data blocks')
  File "/usr/bin/yt-dlp/yt_dlp/downloader/common.py", line 178, in report_error
    self.ydl.report_error(*args, **kargs)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 950, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 884, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
```

**Comment by Lesmiscore** [comment] 2022-05-14 07:59
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/3372

Do not blindly check boxes!

**Closed by Lesmiscore** 2022-05-14 07:59 UTC
Labels: site-bug, triage
