### ISSUE TITLE
TIKTOK api uncompress video

### ISSUE THREAD

**Issue by zone559** [yt-dlp/yt-dlp#6713] opened 2023-04-05 02:37 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Anyone know how to obtain the same api as this website?
His api are able to download video uncompress from tiktok and they are not willing to share.

https://www.tikwm.com/en/

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
none
```

**Comment by bashonly** [comment] 2023-04-05 03:03
Duplicate of #4138

There used to be a known way of getting the source quality but it no longer works. As you noted, the people who know the current working method don't seem like they are willing to share

**Closed by bashonly** 2023-04-05 03:03 UTC
Labels: duplicate, site-enhancement, site:tiktok
