### ISSUE TITLE
6play says "No video formats found!"

### ISSUE THREAD

**Issue by sebastienp7669** [yt-dlp/yt-dlp#5237] opened 2022-10-13 17:18 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

When trying to use yt-dlp with a 6play URL, the answer keeps being "No video formats found!"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.6play.fr/capital-p_860/forains-gens-du-voyage-revelations-sur-une-economie-secrete-c_12970272', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107244-g0744c84792-20220625 (setts), ffprobe N-107244-g0744c84792-20220625
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [6play] Extracting URL: https://www.6play.fr/capital-p_860/forains-gens-du-voyage-revelations-sur-une-economie-secrete-c_12970272
[6play] 12970272: Downloading JSON metadata
ERROR: [6play] 12970272: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1574, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1632, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2569, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1027, in raise_no_formats
yt_dlp.utils.ExtractorError: [6play] 12970272: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by dirkf** [comment] 2022-10-13 21:48
Apparently the extractor only gets DRM formats for this show from the API URL that it uses. Also, it only gets one of them because it doesn't look for the DASH/mpd case. 
```
...
                          'type': 'usp_dashcenc_h264',
...
                          'type': 'usp_hlsfp_h264',
```
The yt-dlp 6Play extractor is essentially identical to the yt-dl version and doesn't understand any special processing for DRM formats.

**Comment by gamer191** [comment] 2022-10-14 08:26
duplicate of #2005

**Closed by gamer191** 2022-10-14 08:26 UTC
Labels: site-bug, triage
