### ISSUE TITLE
HTTP Error 403: Forbidden on Adult Swim (w/Comcast MSO)

### ISSUE THREAD

**Issue by MrOctober77** [yt-dlp/yt-dlp#11247] opened 2024-10-14 16:02 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Trying to download some shows\ on Adult Swim. Was able to download five without needing to use Comcast MSO, but the next ones I try needed logins. Logged in with my Comcast account but got the HTT 403 Forbidden error. Shows play on Chrome, Firefox, Brave with no problem.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.adultswim.com/videos/rick-and-morty/rickfending-your-mort']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe N-91181-gcba167934b
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.07 from yt-dlp/yt-dlp)
[AdultSwim] Extracting URL: https://www.adultswim.com/videos/rick-and-morty/rickfending-your-mort
[AdultSwim] rickfending-your-mort: Downloading JSON metadata
[AdultSwim] 6da5cf250e9fc118d812e023c2b554573ba9211a: Downloading JSON metadata
[AdultSwim] 6da5cf250e9fc118d812e023c2b554573ba9211a: Downloading Provider Redirect Page
ERROR: [AdultSwim] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\adultswim.py", line 151, in _real_extract
  File "yt_dlp\extractor\turner.py", line 232, in _extract_ngtv_info
  File "yt_dlp\extractor\turner.py", line 37, in _add_akamai_spe_token
  File "yt_dlp\extractor\adobepass.py", line 1448, in _extract_mvpd_auth
  File "yt_dlp\extractor\adobepass.py", line 1366, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 961, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 910, in _request_webpage

  File "yt_dlp\extractor\common.py", line 897, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4172, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 365, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment] 2024-10-14 17:50
Duplicate of #10848

**Closed by bashonly** 2024-10-14 17:50 UTC
Labels: site-bug, triage
