### ISSUE TITLE
获取不到youtube博主的短视频信息

### ISSUE THREAD

**Issue by Gscsd8527** [yt-dlp/yt-dlp#11070] opened 2024-09-24 06:22 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

india

### Example URLs

https://www.youtube.com/@watchluke/shorts

### Provide a description that is worded well enough to be understood

我想要获取博主的短视频，只要短视频，但是通过https://www.youtube.com/@watchluke 和 https://www.youtube.com/@watchluke/shorts都获取不到，会自动跳过，比如https://www.youtube.com/@watchluke下有14个视频，其中3个短视频，通过yt-dlp出来只有11个

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube:tab] Extracting URL: https://www.youtube.com/@watchluke
[youtube:tab] @watchluke: Downloading webpage
[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[youtube:tab] @watchluke/shorts: Downloading webpage
[youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUclv7KjuaGvDvMiQZKIHZOA
[download] Downloading playlist: watchluke
[youtube:tab] Playlist watchluke: Downloading 2 items of 2
[download] Downloading item 1 of 2
[download] Downloading playlist: watchluke - Videos
[youtube:tab] Playlist watchluke - Videos: Downloading 11 items of 11
[download] Downloading item 1 of 11
[youtube] Extracting URL: https://www.youtube.com/watch?v=LyhwtnLkzcs
[youtube] LyhwtnLkzcs: Downloading webpage
[youtube] LyhwtnLkzcs: Downloading ios player API JSON
[youtube] LyhwtnLkzcs: Downloading web creator player API JSON
[youtube] LyhwtnLkzcs: Downloading m3u8 information
[info] LyhwtnLkzcs: Downloading 1 format(s): 18
```

**Comment by seproDev** [comment] 2024-09-24 06:41
This issue tracker is in English. Please describe your problem in English to receive help.

Looking at the links you provided, this might be a duplicate of https://github.com/yt-dlp/yt-dlp/issues/10936
If you haven't done so already update to nightly:
```
yt-dlp --update-to nightly
```

**Comment by grqz** [comment] 2024-09-25 01:26
from your description, i'm quite sure this is a duplicate of #10936 and should be closed now

**Closed** 2024-09-25 01:31 UTC
Labels: invalid, incomplete
