### ISSUE TITLE
Download aborted extract audio Crunchyroll

### ISSUE THREAD

**Issue by levaculik2** [yt-dlp/yt-dlp#6646] opened 2023-03-27 02:22 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

lately I'm having this problem when I try to extract audio from an episode of crunchyroll. I've never had a problem, but I've been having this problem for a week. just the audio.
I tried to download removing aria2c, but it didn't work.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', '[height<=?1080]', '-u', 'PRIVATE', '-p', 'PRIVATE', '-a', '/home/levaculik/Documentos/list/crunchyptBR.txt', 'www.crunchyroll.com/', '-x', '--extract-audio', '--cookies-from-browser', 'chrome', '--no-geo-bypass', '--no-check-certificat', '--downloader', 'aria2c', '-o', '%(series)s S0%(season_number)sE0%(episode_number)s - %(episode)s.pt-BR.%(ext)s']
[debug] Batch file urls: ['https://www.crunchyroll.com/watch/GN7UD41KE/super-link-up-play']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-139-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/home/levaculik/.config/google-chrome/Default/Cookies"
[debug] detected desktop environment: XFCE
[debug] Chosen keyring: GNOMEKEYRING
[Cookies] Extracted 3117 cookies from chrome
[debug] cookie version breakdown: {'v10': 0, 'v11': 3094, 'other': 0, 'unencrypted': 23}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/GN7UD41KE/super-link-up-play
[crunchyroll] Retrieving main page
[crunchyroll] Authenticating with grant_type=etp_rt_cookie
[crunchyroll] Retrieving signed policy
[crunchyroll] super-link-up-play: Retrieving episode metadata
[crunchyroll] super-link-up-play: Retrieving stream info
[crunchyroll] To get all formats of a hardsub language, use "--extractor-args crunchyrollbeta:hardsub=<language_code or all>". See https://github.com/yt-dlp/yt-dlp#crunchyrollbeta-crunchyroll for more info
[crunchyroll] super-link-up-play: Downloading adaptive_hls HLS manifest
[crunchyroll] super-link-up-play: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] GN7UD41KE: Downloading 1 format(s): adaptive_hls-8098
[debug] Invoking hlsnative downloader on "https://pl.crunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/index-v1-a1.m3u8?res=1920x1080&Expires=1680056451&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy8yNGVjNDk4NTEzMTViNzU4MDAwZTY0NWU0ZDdhY2VmZS9hc3NldHMvMTgyZmNkZTE3YzExN2E2ZDNkZDY3MTk2NzZiNTVlZmVfNTAzMDI3NS5tcDQvaW5kZXgtdjEtYTEubTN1OD9yZXM9MTkyMHgxMDgwIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjgwMDU2NDUxfX19XX0_&Signature=D-EmBa4~eETGbohucAVMLEgjrn5LFEiu4MKmte1Cbty8VtdfHUy8qbiJSZ9Lr5E~bIfANl9Ye7SG0BiJ7h4zd5NNCDwnU24Aql3Yw0ox1FmMXozRQeR2w0yjSWxUfyIEvvqa12WgAIK1JbX4R1vnuexXGEn9EaNYDWcP7u2rCb6zHHCHnv2i~vGwBRCp3YTd-RqK69zmRV-NMEW9l6PpSeWaPRcu87YAMnk2SeZerQTvGEzbQypifPn04EUtFeFPB0kZTIfBsr49GfCtXWWOMJJ4lDGGgFzGo-J4Au4dfoI5ar-kE5NPyfhVb9w43UeLVJYoZXsX-~KQpd458SIgsQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 355
[download] Destination: BLUELOCK S01E020 - Super Link-Up Play.pt-BR.mp4
[debug] aria2c command line: aria2c -c --console-log-level=warn --summary-interval=0 --download-result=hide --http-accept-gzip=true --file-allocation=none -x16 -j16 -s16 --allow-overwrite=true --allow-piece-length-change=true --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.18 Safari/537.36' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-us,en;q=0.5' --header 'Sec-Fetch-Mode: navigate' --header 'Cookie: _clck=1eg8xp0|1|f4a|0; _ga=GA1.1.402443821.1639308504; _ga_LR7F7G15SW=GS1.1.1661366427.1.1.1661366449.0.0.0; _ga_SYYQC1VW88=GS1.1.1679879339.373.1.1679881243.60.0.0; _gcl_au=1.1.1197020707.1673307117; _shopify_y=baefe6ed-e809-4982-b81f-18c706fabf53; _tt_enable_cookie=1; _ttp=01606852-263e-4b9d-8339-88fe1b9e24ed; _y=baefe6ed-e809-4982-b81f-18c706fabf53; ab.storage.deviceId.80f403d2-1c18-471d-b0ef-243d1d646436=%7B%22g%22%3A%22ebe4cb88-c4c6-e1df-c1be-57dd07d2da05%22%2C%22c%22%3A1663594247993%2C%22l%22%3A1679879340525%7D; ab.storage.sessionId.80f403d2-1c18-471d-b0ef-243d1d646436=%7B%22g%22%3A%22683e81a2-4a21-42f0-c929-0bd6ea7ef6d2%22%2C%22e%22%3A1679881297799%2C%22c%22%3A1679879340519%2C%22l%22%3A1679879497799%7D; ab.storage.userId.80f403d2-1c18-471d-b0ef-243d1d646436=%7B%22g%22%3A%2216922be0-13b2-52a6-932c-108735dae164%22%2C%22c%22%3A1664076301081%2C%22l%22%3A1679879340529%7D; ajs_anonymous_id=d71551b0-6aa7-4755-ac23-444ec3cc1e9f; ajs_user_id=16922be0-13b2-52a6-932c-108735dae164; amplitude_id_f92f25db4ed7f1c7ee55351799d43351crunchyroll.com=eyJkZXZpY2VJZCI6IjRhMjdhODMxLWUyNTktNDE2NC04Yjk3LTE3MmJjNTM1OGVhZlIiLCJ1c2VySWQiOm51bGwsIm9wdE91dCI6ZmFsc2UsInNlc3Npb25JZCI6MTY2MTM2NjQzMzQxMiwibGFzdEV2ZW50VGltZSI6MTY2MTM2NjQzNDM0NiwiZXZlbnRJZCI6MiwiaWRlbnRpZnlJZCI6MSwic2VxdWVuY2VOdW1iZXIiOjN9; c_locale=enUS; c_visitor=a08252df-8a07-44eb-8bf4-55a85635f649; crplusctamembership=1; cto_bundle=jfsPSl9XSGdkREJKMTc0JTJGUWpqYnhkUGRYQiUyQmNiJTJCZXA3N2VIZmZQZmdmMmVBWEpJOXJFUzJGMyUyQmFRRWxKYWhITCUyQkZ0Q0pnQUlsTDVjUnBjR1FRelZRR3F2b3JjRDIxdWtpOXN4NEI3MEhqdEx6RVQlMkJaVHljYkpiaDlTWTIlMkIxJTJCcm9qcUprbTlQQnBoMlNBY3FDRnlIdlpJZVJBJTNEJTNE; etp_rt=9766dd14-7714-4130-a60e-13770b439bf3; ftctav=1; premplusctav=1; __cf_bm=Q6UfccXn0t3nqjhsArwrWiMbGwVvYKZIUztk8S88G5c-1679883649-0-AUfBIzzCYX7/9DhN/JNu32201WjbVgjCto69AkVV3aVOYuXSOUD0Z9k+Vkff7YnZb2i2jFfF7AZ5U1cCCCUM3lKI35x/wC9MZvkzLUQh8G9p' --check-certificate=false --remote-time=true --show-console-readout=true --auto-file-renaming=false --file-allocation=none --uri-selector=inorder -i './BLUELOCK S01E020 - Super Link-Up Play.pt-BR.mp4.part.frag.urls'
[DL:0B][#f88e47 0B/0B][#9f4ca7 0B/0B][#c3b239 0B/0B][#9155f7 0B/0B][#bb029d 0B/0B](+11)^C                                          
03/26 23:10:29 [ERROR] CUID#7 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-1-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

03/26 23:10:29 [ERROR] CUID#8 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-2-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

03/26 23:10:29 [ERROR] CUID#9 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-3-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

03/26 23:10:29 [ERROR] CUID#10 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-4-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

03/26 23:10:29 [ERROR] CUID#11 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-5-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

03/26 23:10:29 [ERROR] CUID#12 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-6-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

03/26 23:10:29 [ERROR] CUID#13 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-7-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

03/26 23:10:29 [ERROR] CUID#14 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-8-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

03/26 23:10:29 [ERROR] CUID#15 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-9-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

03/26 23:10:29 [ERROR] CUID#16 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-10-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

03/26 23:10:29 [ERROR] CUID#17 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-11-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

03/26 23:10:29 [ERROR] CUID#18 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-12-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

03/26 23:10:29 [ERROR] CUID#19 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-13-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

03/26 23:10:29 [ERROR] CUID#20 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-14-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

03/26 23:10:29 [ERROR] CUID#21 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-15-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

03/26 23:10:29 [ERROR] CUID#22 - Download aborted. URI=https://prod.gccrunchyroll.com/evs3/24ec49851315b758000e645e4d7acefe/assets/182fcde17c117a6d3dd6719676b55efe_5030275.mp4/seg-16-v1-a1.ts?URLPrefix=aHR0cHM6Ly9wcm9kLmdjY3J1bmNoeXJvbGwuY29tL2V2czMvMjRlYzQ5ODUxMzE1Yjc1ODAwMGU2NDVlNGQ3YWNlZmUvYXNzZXRzLzE4MmZjZGUxN2MxMTdhNmQzZGQ2NzE5Njc2YjU1ZWZlXzUwMzAyNzUubXA0Lw&Expires=1680055528252&KeyName=cdn-prod-keyset&Signature=CHWKcCEDQF1N5cNIi7m_tmt0zRYV4uyAwsD2kxwJMgjwOfn4zgLVoQJFz6iNz4WN37Z3hcY_r6-B4BX0PFZPBw
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.
[DL:0B][#a0e3c2 0B/0B][#d8a4a4 0B/0B][#e5ec7c 0B/0B][#f1166c 0B/0B][#ffd61a 0B/0B](+11)^C
```

**Comment by Grub4K** [comment] 2023-04-30 14:51
Having the same host, `https://prod.gccrunchyroll.com/evs3/`, makes it be a duplicate of #4898

**Closed by Grub4K** 2023-04-30 14:51 UTC
Labels: site-bug, triage
