### ISSUE TITLE
x.com (works with Twitter.com already)

### ISSUE THREAD

**Issue by JustSuperHuman** [yt-dlp/yt-dlp#9972] opened 2024-05-20 01:15 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

US

### Example URLs

https://x.com/oldrowswig/status/1792227824738111496?s=46

### Provide a description that is worded well enough to be understood

I believe this used to work but I can’t confirm.

I have a shortcut that stopped working and I can confirm X.com links report unsupported when using no switches. 

Just replacing x.com with twitter.com in the URL works perfectly.

Not sure why X never made it to (or was removed from) the supported list but looks like an easy one to add :)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp https://x.com/oldrowswig/statu
s/1792227824738111496?s=46
[generic] Extracting URL: https://x.com/oldrows
wig/status/1792227824738111496?s=46
[generic] 1792227824738111496?s=46: Downloading
 webpage
WARNING: [generic] Falling back on generic info
rmation extractor
[generic] 1792227824738111496?s=46: Extracting 
information
ERROR: Unsupported URL: https://x.com/oldrowswi
g/status/1792227824738111496?s=46
[~group]$ 
ERROR: Unsupported URL: https://x.com/oldrowswi
g/status/1792227824738111496?s=46
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application
/66A27A53-613B-437D-B25E-EB6E7FD549C8/Library/l
ib/python3.11/site-packages/yt_dlp/YoutubeDL.py
", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mobile/Containers/Data/Application
/66A27A53-613B-437D-B25E-EB6E7FD549C8/Library/l
ib/python3.11/site-packages/yt_dlp/YoutubeDL.py
", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/var/mobile/Containers/Data/Application
/66A27A53-613B-437D-B25E-EB6E7FD549C8/Library/l
ib/python3.11/site-packages/yt_dlp/extractor/co
mmon.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/mobile/Containers/Data/Application
/66A27A53-613B-437D-B25E-EB6E7FD549C8/Library/l
ib/python3.11/site-packages/yt_dlp/extractor/ge
neric.py", line 2514, in _real_extract
    raise UnsupportedError(url)
```

**Comment by bashonly** [comment] 2024-05-20 02:04
Duplicate of #9923

Update to nightly

**Closed by bashonly** 2024-05-20 02:04 UTC
Labels: site-request, triage
