### ISSUE TITLE
Not extracting Vimeo embed

### ISSUE THREAD

**Issue by coolandsmartrr** [yt-dlp/yt-dlp#5438] opened 2022-11-03 06:33 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

The website contains an embedded Vimeo player. To download, you pass in the url of the website.

    yt-dlp -vU https://www.cinematheque.fr/henri/film/125173-orson-welles-a-la-cinematheque-francaise-pierre-andre-boutang-guy-seligmann-1983/   

Note: You cannot pass in the url of the embed, due to the privacy settings on Vimeo.

Version is up-to-date.
```
> yt-dlp -U
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.cinematheque.fr/henri/film/125173-orson-welles-a-la-cinematheque-francaise-pierre-andre-boutang-guy-seligmann-1983/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.9.15 (CPython 64bit) - macOS-12.5.1-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://www.cinematheque.fr/henri/film/125173-orson-welles-a-la-cinematheque-francaise-pierre-andre-boutang-guy-seligmann-1983/
[generic] 125173-orson-welles-a-la-cinematheque-francaise-pierre-andre-boutang-guy-seligmann-1983: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 125173-orson-welles-a-la-cinematheque-francaise-pierre-andre-boutang-guy-seligmann-1983: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
[debug] Identified a vimeo embed
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/438576557?color=7db3af&texttrack=fr#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fwww.cinematheque.fr%2Fhenri%2Ffilm%2F125173-orson-welles-a-la-cinematheque-francaise-pierre-andre-boutang-guy-seligmann-1983%2F%22%7D%7D
[vimeo] 438576557: Downloading webpage
ERROR: [vimeo] 438576557: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.9/site-packages/yt_dlp/extractor/vimeo.py", line 872, in _real_extract
    config = self._parse_json(self._search_regex(
  File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1224, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by coletdjnz** [comment] 2022-11-03 08:08
see pinned known issues, duplicate of https://github.com/yt-dlp/yt-dlp/issues/5361

**Closed by coletdjnz** 2022-11-03 08:08 UTC
Labels: duplicate, site-bug, site:vimeo
