### ISSUE TITLE
yt-dlp fails to output progress on new line (--newline) after using external downloader option (--downloader)

### ISSUE THREAD

**Issue by alittlelearn** [yt-dlp/yt-dlp#3330] opened 2022-04-07 05:12 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I use subprocess to call yt-dlp in python and get the progress output, but when the "--downloader" option is used, the "--newline" function does not work, what should I do?

For example, in a Debian terminal execute:
yt-dlp --newline  -o /temp/video/"%(title)s.%(ext)s" -f 22 --proxy https://127.0.0.1:9172 https://www.youtube.com/watch?v=RCGMy9Gqr6k
Got the following results (this is what I need):
[youtube] RCGMy9Gqr6k: Downloading webpage
[youtube] RCGMy9Gqr6k: Downloading android player API JSON
[info] RCGMy9Gqr6k: Downloading 1 format(s): 22
[download] Destination: /temp/video/When girls ask him to sing, he does this....mp4
[download]   0.0% of 81.91MiB at Unknown speed ETA Unknown
[download]   0.0% of 81.91MiB at Unknown speed ETA Unknown
[download]   0.0% of 81.91MiB at 54.16KiB/s ETA 25:48
[download]   0.0% of 81.91MiB at 115.66KiB/s ETA 12:05
[download]   0.0% of 81.91MiB at 95.44KiB/s ETA 14:38
[download]   0.1% of 81.91MiB at 193.70KiB/s ETA 07:12
[download]   0.2% of 81.91MiB at 281.51KiB/s ETA 04:57
[download]   0.3% of 81.91MiB at 220.37KiB/s ETA 06:19
[download]   0.5% of 81.91MiB at 300.15KiB/s ETA 04:37
...
...
...
However, when adding "--downloader":
yt-dlp --newline --downloader aria2c --downloader-args aria2c:"-x 16 -k 1M" -o /temp/video/"%(title)s.%(ext)s" -f 22 --proxy https://127.0.0.1:9172 https://www.youtube.com/watch?v=RCGMy9Gqr6k
Got the following results (which is not what I need):
[youtube] RCGMy9Gqr6k: Downloading webpage
[youtube] RCGMy9Gqr6k: Downloading android player API JSON
[info] RCGMy9Gqr6k: Downloading 1 format(s): 22
[download] Destination: /temp/video/When girls ask him to sing, he does this....mp4
[#8fcbad 1.7MiB/81MiB(2%) CN:16 DL:0B]  

I execute the terminal command like the following in python, I can only capture the output of each line, if there is a better way, please let me know. thank you very much!

import subprocess

cmd = 'yt-dlp --newline --downloader aria2c --downloader-args aria2c:"-x 16 -k 1M" -o /tmp/video/"%(title)s.%(ext)s" -f 22 --proxy https://127.0.0.1:9172 https://www.youtube.com/watch?v=RCGMy9Gqr6k'

popen = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True)
while True:
	next_line = popen.stdout.readline()
	if next_line == b'' and popen.poll() != None:
		break
	else:
		percent = QTableWidgetItem(next_line.decode('utf-8'))
		...
		# The captured progress information is displayed to my simple graphical interface

### Verbose log

```shell
yt-dlp --newline --downloader aria2c --downloader-args aria2c:"-x 16 -k 1M" -o /temp/video/"%(title)s.%(ext)s" -f 22 --proxy https://127.0.0.1:9172 https://www.youtube.com/watch?v=RCGMy9Gqr6k
Got the following results (which is not what I need):
[youtube] RCGMy9Gqr6k: Downloading webpage
[youtube] RCGMy9Gqr6k: Downloading android player API JSON
[info] RCGMy9Gqr6k: Downloading 1 format(s): 22
[download] Destination: /temp/video/When girls ask him to sing, he does this....mp4
[#8fcbad 1.7MiB/81MiB(2%) CN:16 DL:0B]
```

**Comment by pukkandan** [comment] 2022-04-07 06:40
This is because the progress bar is printed by the downloader, not by yt-dlp.

Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2038

**Closed by pukkandan** 2022-04-07 06:40 UTC
Labels: bug, triage
