### ISSUE TITLE
multiple subtitles per lang are ignored but one

### ISSUE THREAD

**Issue by parisni** [yt-dlp/yt-dlp#4114] opened 2022-06-19 16:37 UTC
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

fr

### Description

some video have multiple subs per lang. For eg this one

```
yt-dlp -F --list-sub https://www.arte.tv/en/videos/043794-000-A/behind-the-scenes-a-clockwork-orange/|grep -e fr

ID                                 EXT RESOLUTION FPS │   FILESIZE   TBR PROTO  │ VCODEC        VBR ACODEC     MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
VOF-STMF-program_audio_0-VOF       mp4 audio only     |                  m3u8_n | audio only        unknown    [fr] Original french version - closed captioning (FR) [ccFR]
VOF-STF-program_audio_0-VOF        mp4 audio only     |                  m3u8_n | audio only        unknown    [fr] French (Original) [FR]
VOF-STMF-426                       mp4 384x216     25 | ~161.07MiB  426k m3u8_n | avc1.42e00d  426k video only Original french version - closed captioning (FR) [ccFR]
VOF-STMF-927                       mp4 640x360     25 | ~350.12MiB  927k m3u8_n | avc1.4d401e  927k video only Original french version - closed captioning (FR) [ccFR]
VOF-STMF-1609                      mp4 768x432     25 | ~607.70MiB 1609k m3u8_n | avc1.4d401e 1609k video only Original french version - closed captioning (FR) [ccFR]
VOF-STMF-2322                      mp4 1280x720    25 | ~877.06MiB 2322k m3u8_n | avc1.4d401f 2322k video only Original french version - closed captioning (FR) [ccFR]
```

But when writing subs, result only one sub per lang:

```
yt-dlp --write-subs  --sub-langs "all" --sub-format srt https://www.arte.tv/en/videos/043794-000-A/behind-the-scenes-a-clockwork-orange/
Behind the Scenes - A Clockwork Orange [043794-000-A].fr.vtt
```

reading the code, the dictionary key used makes the content lost:

```
                fmts, subs = self._extract_m3u8_formats_and_subtitles(
                    stream['url'], video_id=video_id, ext='mp4',
                    m3u8_id=stream_version_code,
                )
```

### Verbose log

```shell
logs
```

**Comment by pukkandan** [comment] 2022-06-19 20:18
The given logs do not demonstrate the issue. But assuming it is as you are describing it, duplicate of https://github.com/yt-dlp/yt-dlp/issues/946

**Closed by pukkandan** 2022-06-19 20:18 UTC
Labels: site-bug, triage

**Comment by parisni** [comment] 2022-06-23 14:08
@pukkandan yeah, same issue
