### ISSUE TITLE
facebook video download (with --cookies-from-browser option) does not work

### ISSUE THREAD

**Issue by sunsande** [yt-dlp/yt-dlp#4693] opened 2022-08-18 13:23 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.14** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

EU

### Provide a description that is worded well enough to be understood

PS C:\projects\Video\yt-dlp> .\yt-dlp.exe -U
Latest version: 2022.08.14, Current version: 2022.04.08
Current Build Hash f855977df69a33c10934f9013dc946f516113a53880b218ec7f6abf1dd6e74cc
Updating to version 2022.08.14 ...
Updated yt-dlp to version 2022.08.14
PS C:\projects\Video\yt-dlp> .\yt-dlp.exe https://www.facebook.com/613331887/videos/10158541347286888 --cookies-from-browser firefox:v4loadpk.dev-edition-default
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 685 cookies from firefox
[facebook] 10158541347286888: Downloading webpage
[facebook] 10158541347286888: Downloading webpage
ERROR: [facebook] 10158541347286888: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\projects\Video\yt-dlp> .\yt-dlp.exe -vU https://www.facebook.com/613331887/videos/10158541347286888 --cookies-from-browser firefox:v4loadpk.dev-edition-default
[debug] Command-line config: ['-vU', 'https://www.facebook.com/613331887/videos/10158541347286888', '--cookies-from-browser', 'firefox:v4loadpk.dev-edition-default']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.14 [5593720] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-103290-gc64d56a2f5-20210819 (setts), ffprobe N-103290-gc64d56a2f5-20210819
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\...\AppData\Roaming\Mozilla\Firefox\Profiles\v4loadpk.dev-edition-default\cookies.sqlite"
[Cookies] Extracted 694 cookies from firefox
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.14, Current version: 2022.08.14
yt-dlp is up to date (2022.08.14)
[debug] [facebook] Extracting URL: https://www.facebook.com/613331887/videos/10158541347286888
[facebook] 10158541347286888: Downloading webpage
[facebook] 10158541347286888: Downloading webpage
ERROR: [facebook] 10158541347286888: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\facebook.py", line 705, in _real_extract
  File "yt_dlp\extractor\facebook.py", line 651, in _extract_from_url
```

**Comment by pukkandan** [comment] 2022-08-18 14:52
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/4311

**Closed by pukkandan** 2022-08-18 14:52 UTC
Labels: duplicate, site-bug, site:facebook
