### ISSUE TITLE
TOGGO - An extractor error has occurred. (caused by StopIteration())

### ISSUE THREAD

**Issue by magajoh177** [yt-dlp/yt-dlp#11281] opened 2024-10-18 14:21 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Provide a description that is worded well enough to be understood

Extractor-Error occurs for some videos on www.toogo.de.

For concrete Error see verbose output below....

Examples:
- https://www.toggo.de/grizzy--die-lemminge/folge/die-schatzsuche-vep17274
- https://www.toggo.de/toggolino/rubble--crew-pty561/folge/die-crew-baut-eine-super-badewanne-vep15312
- https://www.toggo.de/ninjago/folge/einladung-zum-turnier-der-quellen-vep20071

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.toggo.de/grizzy--die-lemminge/folge/die-schatzsuche-vep17274']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.8.0-40-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.07 from yt-dlp/yt-dlp)
[toggo] Extracting URL: https://www.toggo.de/grizzy--die-lemminge/folge/die-schatzsuche-vep17274
[toggo] die-schatzsuche-vep17274: Downloading JSON metadata
ERROR: die-schatzsuche-vep17274: An extractor error has occurred. (caused by StopIteration()); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/user/bin/./yt-dlp/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "/home/user/bin/./yt-dlp/yt_dlp/extractor/toggo.py", line 46, in _real_extract
    brightcove_id = next(
StopIteration
```

**Comment by seproDev** [comment] 2024-10-18 14:44
Duplicate of #7511
The three videos you posted all require DRM. The extractor will likely be removed in the future. I was unable to find any DRM free videos.

**Closed by seproDev** 2024-10-18 14:44 UTC
Labels: site-bug, triage

**Comment by magajoh177** [comment] 2024-10-18 14:57
Thanks.
