### ISSUE TITLE
Download Video 4K from iqiyi Android Emulator use Fidder

### ISSUE THREAD

**Issue by light-developer** [yt-dlp/yt-dlp#10137] opened 2024-06-08 19:13 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have VIP member, show I can see 4K from mobile
I can download 1080 from PC via yt-dlp 
I use Android Emulator and try to get network request from Fidder

But I cannot how I can download video from it?

I see topic and see url: cache-video.iq.com

But I cannot see any request have url like this, just only https://api.iq.com/video/play 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment] 2024-06-09 03:22
Duplicate of #7505

**Closed by bashonly** 2024-06-09 03:22 UTC
Labels: question
