### ISSUE TITLE
Download doesn't work

### ISSUE THREAD

**Issue by khk58** [yt-dlp/yt-dlp#8921] opened 2024-01-03 16:13 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

On downloading of some files I get the answer 'Unable to extract playlist; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U'.

But on other files of the same source the download worked - so what's wrong?
And if I look into 'Programs and features' I see installed Python is 3.10.11 (64-bit)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--no-playlist', '--cookies-from-browser', 'firefox', '--download-archive', '..\\..\\archive.txt', '-i', '--geo-bypass', '-o', '%(title)s.%(ext)s', 'https://tvthek.orf.at/profile/Von-der-Loewinger-Buehne/13895428/Von-der-Loewinger-Buehne-Der-Mann-mit-der-Libelle/14206252']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\khk59\AppData\Roaming\Mozilla\Firefox\Profiles\czhw2lsu.default-release-1623234895724\cookies.sqlite"
Extracted 379 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-106936-gdd99d34d67-20220519 (setts), ffprobe git-2020-06-28-4cfcfb3, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Loading archive file '..\\..\\archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[orf:tvthek] Extracting URL: https://tvthek.orf.at/profile/Von-der-Loewinger-Buehne/13895428/Von-der-Loewinger-Buehne-Der-Mann-mit-der-Libelle/14206252
[orf:tvthek] 14206252: Downloading webpage
ERROR: [orf:tvthek] 14206252: Unable to extract playlist; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\orf.py", line 184, in _real_extract
  File "yt_dlp\extractor\common.py", line 1266, in _search_regex


D:\Youtube\filme\SOKO>yt-dlp -vU --no-playlist --cookies-from-browser firefox --download-archive ..\..\archive.txt  -i --geo-bypass -o "%(title)s.%(ext)s" https://tvthek.orf.at/profile/Von-der-Loewinger-Buehne/13895428/Von-der-Loewinger-Buehne-Zwei-mal-zwei-ist-zwei/14205701/Von-der-Loewinger-Buehne-Zwei-mal-zwei-ist-zwei/15531974
[debug] Command-line config: ['-vU', '--no-playlist', '--cookies-from-browser', 'firefox', '--download-archive', '..\\..\\archive.txt', '-i', '--geo-bypass', '-o', '%(title)s.%(ext)s', 'https://tvthek.orf.at/profile/Von-der-Loewinger-Buehne/13895428/Von-der-Loewinger-Buehne-Zwei-mal-zwei-ist-zwei/14205701/Von-der-Loewinger-Buehne-Zwei-mal-zwei-ist-zwei/15531974']
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\khk59\AppData\Roaming\Mozilla\Firefox\Profiles\czhw2lsu.default-release-1623234895724\cookies.sqlite"
Extracted 379 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-106936-gdd99d34d67-20220519 (setts), ffprobe git-2020-06-28-4cfcfb3, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.1, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1798 extractors
[debug] Loading archive file '..\\..\\archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[orf:tvthek] Extracting URL: https://tvthek.orf.at/profile/Von-der-Loewinger-Buehne/13895428/Von-der-Loewinger-Buehne-Zwei-mal-zwei-ist-zwei/14205701/Von-der-Loewinger-Buehne-Zwei-mal-zwei-ist-zwei/15531974
[orf:tvthek] 14205701: Downloading webpage
ERROR: [orf:tvthek] 14205701: Unable to extract playlist; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 718, in extract
  File "yt_dlp\extractor\orf.py", line 184, in _real_extract
  File "yt_dlp\extractor\common.py", line 1266, in _search_regex
```

**Comment by bashonly** [comment] 2024-01-03 21:52
Duplicate of #2649

**Closed by bashonly** 2024-01-03 21:52 UTC
Labels: question

**Comment by dirkf** [comment] 2024-01-05 05:05
Although this might not have been the case when OP tried it, the problem URL redirects to https://tvthek.orf.at/, presumably because it's expired.
