### ISSUE TITLE
Can download video but not audio from Bilibili

### ISSUE THREAD

**Issue by xuancong84** [yt-dlp/yt-dlp#2929] opened 2022-03-03 03:02 UTC
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

It is great that yt-dlp can list format and download video from Bilibili as well. However, it cannot download any audio from Bilibili. What a pity!

### Verbose log

```shell
xuancong@wxc-dell:/dev/shm$ yt-dlp -F 'https://www.bilibili.com/video/BV1ay4y1j7R7'
[BiliBili] 1ay4y1j7R7: Grabbing original ID via API
[BiliBili] 804419108: Downloading webpage
[BiliBili] 804419108: Extracting videos in anthology
[BiliBili] Downloading anthology 804419108 - add --no-playlist to just download video
[download] Downloading playlist: 【4K修复】孙俪&李健 --《风吹麦浪》
[BiliBili] playlist 【4K修复】孙俪&李健 --《风吹麦浪》: Downloading 1 videos
[download] Downloading video 1 of 1
[BiliBili] 1ay4y1j7R7: Grabbing original ID via API
[BiliBili] 804419108: Downloading webpage
[BiliBili] 804419108: Extracting videos in anthology
[BiliBili] 804419108: Downloading tags
[info] Available formats for 804419108_part1:
ID EXT RESOLUTION FPS │  FILESIZE   TBR PROTO │ VCODEC             VBR ACODEC      ABR
───────────────────────────────────────────────────────────────────────────────────────
0  m4a audio only     │ ~ 1.56MiB   67k https │ audio only             mp4a.40.2   67k
1  m4a audio only     │ ~ 3.08MiB  132k https │ audio only             mp4a.40.2  132k
2  m4a audio only     │ ~ 7.46MiB  321k https │ audio only             mp4a.40.2  321k
3  mp4 640x360     25 │ ~ 8.13MiB  350k https │ avc1.64001E       350k video only
4  mp4 640x360     25 │ ~ 4.92MiB  212k https │ hev1.1.6.L120.90  212k video only
5  mp4 852x480     25 │ ~18.22MiB  785k https │ avc1.64001F       785k video only
6  mp4 852x480     25 │ ~10.93MiB  470k https │ hev1.1.6.L120.90  470k video only
7  mp4 1280x720    25 │ ~40.51MiB 1746k https │ avc1.640028      1746k video only
8  mp4 1280x720    25 │ ~24.21MiB 1043k https │ hev1.1.6.L120.90 1043k video only
9  mp4 1920x1080   25 │ ~60.79MiB 2620k https │ avc1.640032      2620k video only
10 mp4 1920x1080   25 │ ~36.32MiB 1565k https │ hev1.1.6.L120.90 1565k video only
[download] Finished downloading playlist: 【4K修复】孙俪&李健 --《风吹麦浪》
xuancong@wxc-dell:/dev/shm$ yt-dlp -f 1 'https://www.bilibili.com/video/BV1ay4y1j7R7'
[BiliBili] 1ay4y1j7R7: Grabbing original ID via API
[BiliBili] 804419108: Downloading webpage
[BiliBili] 804419108: Extracting videos in anthology
[BiliBili] Downloading anthology 804419108 - add --no-playlist to just download video
[download] Downloading playlist: 【4K修复】孙俪&李健 --《风吹麦浪》
[BiliBili] playlist 【4K修复】孙俪&李健 --《风吹麦浪》: Downloading 1 videos
[download] Downloading video 1 of 1
[BiliBili] 1ay4y1j7R7: Grabbing original ID via API
[BiliBili] 804419108: Downloading webpage
[BiliBili] 804419108: Extracting videos in anthology
[BiliBili] 804419108: Downloading tags
[info] 804419108_part1: Downloading 1 format(s): 1
ERROR: unable to download video data: HTTP Error 403: Forbidden
[download] Finished downloading playlist: 【4K修复】孙俪&李健 --《风吹麦浪》
xuancong@wxc-dell:/dev/shm$ yt-dlp -U
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
```

**Comment by pukkandan** [comment] 2022-03-03 09:41
Duplicate of #2872

**Closed by pukkandan** 2022-03-03 09:41 UTC
Labels: bug, triage
