### ISSUE TITLE
Failed to download m3u8 information

### ISSUE THREAD

**Issue by genshisabu** [yt-dlp/yt-dlp#8526] opened 2023-11-05 09:19 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.10.13** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

I entered the following code to download the OPENREC members-only video after logging in to the site. 
yt-dlp --cookies-from-browser firefox https://www.openrec.tv/live/2p8vvn0498y
If so, an error occurred at the end after processing as follows.
Extracting cookies from firefox
Extracted 161 cookies from firefox
[openrec] Extracting URL: https://www.openrec.tv/live/2p8vvn0498y
[openrec] 2p8vvn0498y: Downloading webpage
[openrec] 2p8vvn0498y: Downloading JSON metadata
[openrec] 2p8vvn0498y: Downloading m3u8 information
ERROR: [openrec] 2p8vvn0498y: Failed to download m3u8 information: HTTP Error 401: Unauthorized (caused by <HTTPError 401: Unauthorized>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
We have confirmed that youtube videos can be downloaded.
It has also been updated to the latest version.
Below is the message when running yt-dlp -U.
yt-dlp -U
Available version: stable@2023.10.13, Current version: stable@2023.10.13
Current Build Hash: 13d6a04ef6678dc61cb6e2d42eb53e69486bd2f52b8e5d778db029ccd4c600b4
yt-dlp is up to date (stable@2023.10.13)
Please help me.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I do not know how the error is executed if it is handled.
Perhaps the download will be performed normally.
```

**Comment by bashonly** [comment] 2023-11-05 09:22
Duplicate of #6946

**Comment by bashonly** [comment] 2023-11-05 09:23
Possible workaround: try adding `--referer "https://www.openrec.tv"` to your command

**Closed by bashonly** 2023-11-05 09:22 UTC
Labels: site-bug, triage

**Comment by genshisabu** [comment] 2023-11-05 09:38
I entered the command --referer "https://www.openrec.tv/" and it downloaded.
Thank you so much for your help.
