### ISSUE TITLE
NFL: Failed to parse JSON

### ISSUE THREAD

**Issue by RingoTheDog** [yt-dlp/yt-dlp#5002] opened 2022-09-22 15:54 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

canada

### Provide a description that is worded well enough to be understood

URL:  https://www.miamidolphins.com/video/tua-tagovailoa-september-21-press-conference     (plays correctly in browser)

yt-dlp correctly calls the NFL extractor, but fails with: 

Failed to parse JSON (caused by JSONDecodeError('Extra data: line 1 column 17476 (char 17475)'))

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.py -v "https://www.miamidolphins.com/video/tua-tagovailoa-september-21-press-conference"
[debug] Command-line config: ['-v', 'https://www.miamidolphins.com/video/tua-tagovailoa-september-21-press-conference']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (zip)
[debug] Python 3.10.5 (CPython 64bit) - Windows-10-10.0.14393-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[debug] [nfl.com] Extracting URL: https://www.miamidolphins.com/video/tua-tagovailoa-september-21-press-conference
[nfl.com] tua-tagovailoa-september-21-press-conference: Downloading webpage
ERROR: [nfl.com] tua-tagovailoa-september-21-press-conference: tua-tagovailoa-september-21-press-conference: Failed to parse JSON (caused by JSONDecodeError('Extra data: line 1 column 17476 (char 17475)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\nfl.py", line 132, in _real_extract
    return self._parse_video_config(self._search_regex(
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\nfl.py", line 60, in _parse_video_config
    video_config = self._parse_json(video_config, display_id)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 977, in _parse_json
    self.__print_error('Failed to parse JSON' if errnote is None else errnote, fatal, video_id, ve)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 960, in __print_error
    raise ExtractorError(f'{video_id}: {errnote}', cause=err)

  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 974, in _parse_json
    return json.loads(
  File "C:\Users\TRANSMOG\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\utils.py", line 596, in decode
    return super().decode(s)
  File "C:\Users\TRANSMOG\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 17476 (char 17475)
```

**Comment by pukkandan** [comment] 2022-09-22 16:21
You are opening duplicate of your own issue? 😕 

https://github.com/yt-dlp/yt-dlp/issues/1708

**Closed by pukkandan** 2022-09-22 16:21 UTC
Labels: site-bug, triage

**Comment by RingoTheDog** [comment] 2022-09-22 16:25
Sorry..but are those the same issue?  
I thought the errors are different: **"Failed to parse JSON"** VS  **"HTTP Error 403: Forbidden"**

**Comment by pukkandan** [comment] 2022-09-22 16:27
No worries. It is possible that the errors are actually slightly different. But the whole extractor is broken anyway

> WARNING: The program functionality for this site has been marked as broken, and will probably not work.

There is no need to have multiple issues tracking it
