### ISSUE TITLE
Instagram videos not downloading 

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#10194] opened 2024-06-16 14:10 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When I am downloading any Instagram videos it is showing error downloading 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
-N "3" --cookies "/data/user/0/com.deniscerri.ytdl/cache/cookies.txt" --trim-filenames "184" --no-mtime --sponsorblock-remove "music_offtopic" --parse-metadata "uploader:^(?P<uploader>.*?)(?:(?= - Topic)|$)" --parse-metadata "%(uploader,channel,creator,artist|null)s:%(uploader)s" --sponsorblock-mark "all" --embed-chapters -f "bv+ba/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/8" -o "%(uploader).30B - %(title).170B.%(ext)s" "https://www.instagram.com/reel/C5I7IllvNUM/?igsh=MWp0bmtyMmNjbThkeA=="

WARNING: [Instagram] C5I7IllvNUM: General metadata extraction failed (some metadata might be missing).
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] C5I7IllvNUM: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
```

**Comment by bashonly** [comment] 2024-06-16 14:52
Duplicate of #7165

**Closed by bashonly** 2024-06-16 14:52 UTC
Labels: duplicate, incomplete, site-bug, site:instagram
