### ISSUE TITLE
only 256 pages supported?

### ISSUE THREAD

**Issue by LethalDosage** [yt-dlp/yt-dlp#10883] opened 2024-08-30 18:21 UTC
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

usa

### Provide a description that is worded well enough to be understood

It stops downloading pages after 256 pages.  I don't get any of the new videos.
yt-dlp -vU --max-downloads 4 --playlist-end 20 --dateafter today-20days -N 8 "https://rumble.com/c/StewPeters"
My guess is you have an array sized to 256.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --max-downloads 4 --playlist-end 20 --dateafter today-20days -N 8 "https://rumble.com/c/StewPeters"
[debug] Command-line config: ['-vU', '--max-downloads', '4', '--playlist-end', '20', '--dateafter', 'today-20days', '-N', '8', 'https://rumble.com/c/StewPeters']
[debug] User config "/home/guy/yt-dlp.conf": ['--playlist-reverse', '--live-from-start', '--sleep-interval', '1', '--restrict-filenames', '--trim-filenames', '100', '--continue', '--force-ipv4', '--download-archive', '/var/tmp/youtube-dl.log', '-S', 'height:2160,width:3840', '--prefer-free-formats', '-N', '8']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.26.232811 from yt-dlp/yt-dlp-nightly-builds [41be32e78] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-193-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Crypto-broken 2.6.1, certifi-2019.11.28, pyxattr-0.6.1, requests-2.22.0, secretstorage-2.3.1, sqlite3-3.31.1, urllib3-1.25.8
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1831 extractors
[debug] Loading archive file '/var/tmp/youtube-dl.log'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.26.232811 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.26.232811 from yt-dlp/yt-dlp-nightly-builds)
[RumbleChannel] Extracting URL: https://rumble.com/c/StewPeters
[download] Downloading playlist: StewPeters
[RumbleChannel] StewPeters: Downloading page 1
[RumbleChannel] StewPeters: Downloading page 2
[RumbleChannel] StewPeters: Downloading page 3
[RumbleChannel] StewPeters: Downloading page 4
[RumbleChannel] StewPeters: Downloading page 5
[RumbleChannel] StewPeters: Downloading page 6
[RumbleChannel] StewPeters: Downloading page 7
[RumbleChannel] StewPeters: Downloading page 8
[RumbleChannel] StewPeters: Downloading page 9
[RumbleChannel] StewPeters: Downloading page 10
[RumbleChannel] StewPeters: Downloading page 11
[RumbleChannel] StewPeters: Downloading page 12
[RumbleChannel] StewPeters: Downloading page 13
[RumbleChannel] StewPeters: Downloading page 14
[RumbleChannel] StewPeters: Downloading page 15
[RumbleChannel] StewPeters: Downloading page 16
[RumbleChannel] StewPeters: Downloading page 17
[RumbleChannel] StewPeters: Downloading page 18
[RumbleChannel] StewPeters: Downloading page 19
[RumbleChannel] StewPeters: Downloading page 20
[RumbleChannel] StewPeters: Downloading page 21
[RumbleChannel] StewPeters: Downloading page 22
[RumbleChannel] StewPeters: Downloading page 23
[RumbleChannel] StewPeters: Downloading page 24
[RumbleChannel] StewPeters: Downloading page 25
[RumbleChannel] StewPeters: Downloading page 26
[RumbleChannel] StewPeters: Downloading page 27
[RumbleChannel] StewPeters: Downloading page 28
[RumbleChannel] StewPeters: Downloading page 29
[RumbleChannel] StewPeters: Downloading page 30
[RumbleChannel] StewPeters: Downloading page 31
[RumbleChannel] StewPeters: Downloading page 32
[RumbleChannel] StewPeters: Downloading page 33
[RumbleChannel] StewPeters: Downloading page 34
[RumbleChannel] StewPeters: Downloading page 35
[RumbleChannel] StewPeters: Downloading page 36
[RumbleChannel] StewPeters: Downloading page 37
[RumbleChannel] StewPeters: Downloading page 38
[RumbleChannel] StewPeters: Downloading page 39
[RumbleChannel] StewPeters: Downloading page 40
[RumbleChannel] StewPeters: Downloading page 41
[RumbleChannel] StewPeters: Downloading page 42
[RumbleChannel] StewPeters: Downloading page 43
[RumbleChannel] StewPeters: Downloading page 44
[RumbleChannel] StewPeters: Downloading page 45
[RumbleChannel] StewPeters: Downloading page 46
[RumbleChannel] StewPeters: Downloading page 47
[RumbleChannel] StewPeters: Downloading page 48
[RumbleChannel] StewPeters: Downloading page 49
[RumbleChannel] StewPeters: Downloading page 50
[RumbleChannel] StewPeters: Downloading page 51
[RumbleChannel] StewPeters: Downloading page 52
[RumbleChannel] StewPeters: Downloading page 53
[RumbleChannel] StewPeters: Downloading page 54
[RumbleChannel] StewPeters: Downloading page 55
[RumbleChannel] StewPeters: Downloading page 56
[RumbleChannel] StewPeters: Downloading page 57
[RumbleChannel] StewPeters: Downloading page 58
[RumbleChannel] StewPeters: Downloading page 59
[RumbleChannel] StewPeters: Downloading page 60
[RumbleChannel] StewPeters: Downloading page 61
[RumbleChannel] StewPeters: Downloading page 62
[RumbleChannel] StewPeters: Downloading page 63
[RumbleChannel] StewPeters: Downloading page 64
[RumbleChannel] StewPeters: Downloading page 65
[RumbleChannel] StewPeters: Downloading page 66
[RumbleChannel] StewPeters: Downloading page 67
[RumbleChannel] StewPeters: Downloading page 68
[RumbleChannel] StewPeters: Downloading page 69
[RumbleChannel] StewPeters: Downloading page 70
[RumbleChannel] StewPeters: Downloading page 71
[RumbleChannel] StewPeters: Downloading page 72
[RumbleChannel] StewPeters: Downloading page 73
[RumbleChannel] StewPeters: Downloading page 74
[RumbleChannel] StewPeters: Downloading page 75
[RumbleChannel] StewPeters: Downloading page 76
[RumbleChannel] StewPeters: Downloading page 77
[RumbleChannel] StewPeters: Downloading page 78
[RumbleChannel] StewPeters: Downloading page 79
[RumbleChannel] StewPeters: Downloading page 80
[RumbleChannel] StewPeters: Downloading page 81
[RumbleChannel] StewPeters: Downloading page 82
[RumbleChannel] StewPeters: Downloading page 83
[RumbleChannel] StewPeters: Downloading page 84
[RumbleChannel] StewPeters: Downloading page 85
[RumbleChannel] StewPeters: Downloading page 86
[RumbleChannel] StewPeters: Downloading page 87
[RumbleChannel] StewPeters: Downloading page 88
[RumbleChannel] StewPeters: Downloading page 89
[RumbleChannel] StewPeters: Downloading page 90
[RumbleChannel] StewPeters: Downloading page 91
[RumbleChannel] StewPeters: Downloading page 92
[RumbleChannel] StewPeters: Downloading page 93
[RumbleChannel] StewPeters: Downloading page 94
[RumbleChannel] StewPeters: Downloading page 95
[RumbleChannel] StewPeters: Downloading page 96
[RumbleChannel] StewPeters: Downloading page 97
[RumbleChannel] StewPeters: Downloading page 98
[RumbleChannel] StewPeters: Downloading page 99
[RumbleChannel] StewPeters: Downloading page 100
[RumbleChannel] StewPeters: Downloading page 101
[RumbleChannel] StewPeters: Downloading page 102
[RumbleChannel] StewPeters: Downloading page 103
[RumbleChannel] StewPeters: Downloading page 104
[RumbleChannel] StewPeters: Downloading page 105
[RumbleChannel] StewPeters: Downloading page 106
[RumbleChannel] StewPeters: Downloading page 107
[RumbleChannel] StewPeters: Downloading page 108
[RumbleChannel] StewPeters: Downloading page 109
[RumbleChannel] StewPeters: Downloading page 110
[RumbleChannel] StewPeters: Downloading page 111
[RumbleChannel] StewPeters: Downloading page 112
[RumbleChannel] StewPeters: Downloading page 113
[RumbleChannel] StewPeters: Downloading page 114
[RumbleChannel] StewPeters: Downloading page 115
[RumbleChannel] StewPeters: Downloading page 116
[RumbleChannel] StewPeters: Downloading page 117
[RumbleChannel] StewPeters: Downloading page 118
[RumbleChannel] StewPeters: Downloading page 119
[RumbleChannel] StewPeters: Downloading page 120
[RumbleChannel] StewPeters: Downloading page 121
[RumbleChannel] StewPeters: Downloading page 122
[RumbleChannel] StewPeters: Downloading page 123
[RumbleChannel] StewPeters: Downloading page 124
[RumbleChannel] StewPeters: Downloading page 125
[RumbleChannel] StewPeters: Downloading page 126
[RumbleChannel] StewPeters: Downloading page 127
[RumbleChannel] StewPeters: Downloading page 128
[RumbleChannel] StewPeters: Downloading page 129
[RumbleChannel] StewPeters: Downloading page 130
[RumbleChannel] StewPeters: Downloading page 131
[RumbleChannel] StewPeters: Downloading page 132
[RumbleChannel] StewPeters: Downloading page 133
[RumbleChannel] StewPeters: Downloading page 134
[RumbleChannel] StewPeters: Downloading page 135
[RumbleChannel] StewPeters: Downloading page 136
[RumbleChannel] StewPeters: Downloading page 137
[RumbleChannel] StewPeters: Downloading page 138
[RumbleChannel] StewPeters: Downloading page 139
[RumbleChannel] StewPeters: Downloading page 140
[RumbleChannel] StewPeters: Downloading page 141
[RumbleChannel] StewPeters: Downloading page 142
[RumbleChannel] StewPeters: Downloading page 143
[RumbleChannel] StewPeters: Downloading page 144
[RumbleChannel] StewPeters: Downloading page 145
[RumbleChannel] StewPeters: Downloading page 146
[RumbleChannel] StewPeters: Downloading page 147
[RumbleChannel] StewPeters: Downloading page 148
[RumbleChannel] StewPeters: Downloading page 149
[RumbleChannel] StewPeters: Downloading page 150
[RumbleChannel] StewPeters: Downloading page 151
[RumbleChannel] StewPeters: Downloading page 152
[RumbleChannel] StewPeters: Downloading page 153
[RumbleChannel] StewPeters: Downloading page 154
[RumbleChannel] StewPeters: Downloading page 155
[RumbleChannel] StewPeters: Downloading page 156
[RumbleChannel] StewPeters: Downloading page 157
[RumbleChannel] StewPeters: Downloading page 158
[RumbleChannel] StewPeters: Downloading page 159
[RumbleChannel] StewPeters: Downloading page 160
[RumbleChannel] StewPeters: Downloading page 161
[RumbleChannel] StewPeters: Downloading page 162
[RumbleChannel] StewPeters: Downloading page 163
[RumbleChannel] StewPeters: Downloading page 164
[RumbleChannel] StewPeters: Downloading page 165
[RumbleChannel] StewPeters: Downloading page 166
[RumbleChannel] StewPeters: Downloading page 167
[RumbleChannel] StewPeters: Downloading page 168
[RumbleChannel] StewPeters: Downloading page 169
[RumbleChannel] StewPeters: Downloading page 170
[RumbleChannel] StewPeters: Downloading page 171
[RumbleChannel] StewPeters: Downloading page 172
[RumbleChannel] StewPeters: Downloading page 173
[RumbleChannel] StewPeters: Downloading page 174
[RumbleChannel] StewPeters: Downloading page 175
[RumbleChannel] StewPeters: Downloading page 176
[RumbleChannel] StewPeters: Downloading page 177
[RumbleChannel] StewPeters: Downloading page 178
[RumbleChannel] StewPeters: Downloading page 179
[RumbleChannel] StewPeters: Downloading page 180
[RumbleChannel] StewPeters: Downloading page 181
[RumbleChannel] StewPeters: Downloading page 182
[RumbleChannel] StewPeters: Downloading page 183
[RumbleChannel] StewPeters: Downloading page 184
[RumbleChannel] StewPeters: Downloading page 185
[RumbleChannel] StewPeters: Downloading page 186
[RumbleChannel] StewPeters: Downloading page 187
[RumbleChannel] StewPeters: Downloading page 188
[RumbleChannel] StewPeters: Downloading page 189
[RumbleChannel] StewPeters: Downloading page 190
[RumbleChannel] StewPeters: Downloading page 191
[RumbleChannel] StewPeters: Downloading page 192
[RumbleChannel] StewPeters: Downloading page 193
[RumbleChannel] StewPeters: Downloading page 194
[RumbleChannel] StewPeters: Downloading page 195
[RumbleChannel] StewPeters: Downloading page 196
[RumbleChannel] StewPeters: Downloading page 197
[RumbleChannel] StewPeters: Downloading page 198
[RumbleChannel] StewPeters: Downloading page 199
[RumbleChannel] StewPeters: Downloading page 200
[RumbleChannel] StewPeters: Downloading page 201
[RumbleChannel] StewPeters: Downloading page 202
[RumbleChannel] StewPeters: Downloading page 203
[RumbleChannel] StewPeters: Downloading page 204
[RumbleChannel] StewPeters: Downloading page 205
[RumbleChannel] StewPeters: Downloading page 206
[RumbleChannel] StewPeters: Downloading page 207
[RumbleChannel] StewPeters: Downloading page 208
[RumbleChannel] StewPeters: Downloading page 209
[RumbleChannel] StewPeters: Downloading page 210
[RumbleChannel] StewPeters: Downloading page 211
[RumbleChannel] StewPeters: Downloading page 212
[RumbleChannel] StewPeters: Downloading page 213
[RumbleChannel] StewPeters: Downloading page 214
[RumbleChannel] StewPeters: Downloading page 215
[RumbleChannel] StewPeters: Downloading page 216
[RumbleChannel] StewPeters: Downloading page 217
[RumbleChannel] StewPeters: Downloading page 218
[RumbleChannel] StewPeters: Downloading page 219
[RumbleChannel] StewPeters: Downloading page 220
[RumbleChannel] StewPeters: Downloading page 221
[RumbleChannel] StewPeters: Downloading page 222
[RumbleChannel] StewPeters: Downloading page 223
[RumbleChannel] StewPeters: Downloading page 224
[RumbleChannel] StewPeters: Downloading page 225
[RumbleChannel] StewPeters: Downloading page 226
[RumbleChannel] StewPeters: Downloading page 227
[RumbleChannel] StewPeters: Downloading page 228
[RumbleChannel] StewPeters: Downloading page 229
[RumbleChannel] StewPeters: Downloading page 230
[RumbleChannel] StewPeters: Downloading page 231
[RumbleChannel] StewPeters: Downloading page 232
[RumbleChannel] StewPeters: Downloading page 233
[RumbleChannel] StewPeters: Downloading page 234
[RumbleChannel] StewPeters: Downloading page 235
[RumbleChannel] StewPeters: Downloading page 236
[RumbleChannel] StewPeters: Downloading page 237
[RumbleChannel] StewPeters: Downloading page 238
[RumbleChannel] StewPeters: Downloading page 239
[RumbleChannel] StewPeters: Downloading page 240
[RumbleChannel] StewPeters: Downloading page 241
[RumbleChannel] StewPeters: Downloading page 242
[RumbleChannel] StewPeters: Downloading page 243
[RumbleChannel] StewPeters: Downloading page 244
[RumbleChannel] StewPeters: Downloading page 245
[RumbleChannel] StewPeters: Downloading page 246
[RumbleChannel] StewPeters: Downloading page 247
[RumbleChannel] StewPeters: Downloading page 248
[RumbleChannel] StewPeters: Downloading page 249
[RumbleChannel] StewPeters: Downloading page 250
[RumbleChannel] StewPeters: Downloading page 251
[RumbleChannel] StewPeters: Downloading page 252
[RumbleChannel] StewPeters: Downloading page 253
[RumbleChannel] StewPeters: Downloading page 254
[RumbleChannel] StewPeters: Downloading page 255
[RumbleChannel] StewPeters: Downloading page 256
[RumbleChannel] Playlist StewPeters: Downloading 0 items
[download] Finished downloading playlist: StewPeters
```

**Comment by bashonly** [comment] 2024-08-30 18:37
Duplicate of #10833

**Closed by bashonly** 2024-08-30 18:37 UTC
Labels: site-bug, triage
